dotnet/macios

dotnet/DefaultCompilationIncludes.md
dotnet/targets/Microsoft.Sdk.DefaultItems.template.props

iOS and macOS have support to generate image assets for various
resolutions from vector based PDF files. These files should be included by
default for SDK-Style projects.

Generate default compilation includes for pdf image assets.

---

tests/msbuild/Xamarin.MacDev.Tests/ProjectsTests/CodesignAppBundle.cs

Since we're using msbuild exclusively now.

[tests] Re-enable a test that requires msbuild (as opposed to xbuild).

---

msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
msbuild/Xamarin.Shared/Xamarin.Shared.targets
msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets

* Share the following targets:
* _ResolveAppExtensionReferences
* _SplitAppExtensionReferencesByExistent
* _AssignAppExtensionConfiguration
* _SeparateAppExtensionReferences
* _CopyAppExtensionsToBundle
The first four were pretty much identical between iOS and Mac already, and
needed very few changes.
The latter, _CopyAppExtensionsToBundle, required a little bit of tweaking to
the targets to make sure it works for both iOS and Mac:
* Removed the conditions on the Ditto task to check if we have app extensions
- this is unnecessary because Inputs/Outputs on the target itself (which
weren't there when the Ditto task conditions were written).
* Added a '_PlaceAppExtensions' target that calculates where in the
container's app bundle extensions should be placed (the '_AppExtensionRoot' …

[msbuild] Share the app extensions targets between iOS and Mac.

---

dotnet/targets/Xamarin.Shared.Sdk.targets
tests/common/DotNet.cs
tests/common/TestProjects/MyActionExtension/MyActionExtension.dotnet.csproj
tests/common/TestProjects/MyDocumentPickerExtension/MyDocumentPickerExtension.dotnet.csproj
tests/common/TestProjects/MyExtensionWithPackageReference/MyExtensionWithPackageReference.dotnet.csproj
tests/common/TestProjects/MyKeyboardExtension/MyKeyboardExtension.dotnet.csproj
tests/common/TestProjects/MyPhotoEditingExtension/MyPhotoEditingExtension.dotnet.csproj
tests/common/TestProjects/MyShareExtension/MyShareExtension.dotnet.csproj
tests/common/TestProjects/MyTVServicesExtension/MyTVServicesExtension.dotnet.csproj
tests/common/TestProjects/MyTodayExtension/MyTodayExtension.dotnet.csproj
tests/common/TestProjects/MyWatchApp2/MyWatchApp2.dotnet.csproj
tests/common/TestProjects/MyWatchKit2Extension/MyWatchKit2Extension.dotnet.csproj
tests/common/TestProjects/MyWatchKit2IntentsExtension/MyWatchKit2IntentsExtension.dotnet.csproj
tests/common/TestProjects/MyiOSFrameworkBinding/MyiOSFrameworkBinding.dotnet.csproj

That makes app extensions buid in dotnet.
This required adding a RuntimeIdentifier property to all the extension test
projects.

[dotnet] Add app extension targets to our list of stuff to do during the build.

---

tests/sampletester/Samples.cs

Backport of #10020.
/cc @spouliot

[d16-7] [tests] Bump sampletester hashes to pick up fixes

---

tests/sampletester/Samples.cs

Backport of #10020.
/cc @spouliot

[d16-8] [tests] Bump sampletester hashes to pick up fixes

---

tests/sampletester/Samples.cs

Backport of #10020.
/cc @spouliot

[xcode12.2] [tests] Bump sampletester hashes to pick up fixes

---

dotnet/targets/Xamarin.Shared.Sdk.targets
msbuild/Xamarin.Shared/Xamarin.Shared.props

For some reason .NET 6 does not like spaces in certain places:
MSB4259: Unexpected space at position "32" of condition [...]
So just remove them.

[dotnet] Fix MSBuild syntax.

---

tools/dotnet-linker/LinkerConfiguration.cs
tools/dotnet-linker/Steps/ConfigurationAwareStep.cs
tools/dotnet-linker/Steps/ConfigurationAwareSubStep.cs

Improve error reporting in dotnet-linker by not requiring an instance of a LinkerConfiguration
to report errors. This is accomplished by making the LinkerConfiguration.Report method
a static method.
Otherwise reporting errors before we've successfully created a LinkerConfiguration
turns out to be troublesome (we end up throwing another exception, usually a NullReferenceException,
which is just confusing).

[dotnet-linker] Improve error reporting

---

tools/mmp/mmp.csproj

This makes the file show up in the right place (together with other files from
the tools/mtouch directory) in the solution explorer in VSMac.

[mmp] Fix link path for Stripper.cs

---

tools/mmp/driver.cs

This broke in 59bc3c16abc2162dc3984671f7ff76df92895e3d, and wasn't caught because the Xamarin.Mac build is disabled.

[mmp] Fix the build.

---

tools/devops/automation/build-pipeline.yml
tools/devops/automation/templates/build-packages.yml

The Keychain issue affecting provisioning steps has been fixed in the `install-certificates` template.  Reenable the affected provisioning steps.

Re-enable provisioning steps

---

msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets

The _ACTool_PartialAppManifestCache and _ACTool_BundleResourceCache are
duplicated (merge conflict resolution failure?), and also already present in
Xamarin.Shared.targets, so just remove these definitions.

[msbuild] Remove unnecessary properties in Xamarin.Mac.Common.targets.

---

mk/xamarin.mk

The maccore lib dependency was a problem for governance checks. Also
removes the roslyn analyzer code.
Commits:
* [Deps] Remove Ionic.Zip. Is not needed and gives governance issues. (#8c98216) https://github.com/xamarin/maccore/commit/8c98216efd070686d1bcb86afa2684463b62fc4e
* Remove roslyn-analyzers files (#2149) https://github.com/xamarin/maccore/commit/8c98216efd070686d1bcb86afa2684463b62fc4e
Full diff: https://github.com/xamarin/maccore/compare/f490737c8e3a7ecedb6005bfc8cc9792fe046931..6c3fe624a98287d37d9230da21fe720008fa530e

[Maccore] Bump maccore to remove old not needed code.

---

tests/xharness/Targets/MacTarget.cs

This code isn't necessary in main, because we've removed any GuiUnit usage,
but in d16-8 we're still using GuiUnit, which means we still need to process
GuiUnit project references correctly.
This fixes numerous build failures when building Xamarin.Mac tests (in
particular when building Xamarin.Mac tests for older macOS versions).

[xharness] Bring back special processing of GuiUnit for Xamarin.Mac test projects.

---

msbuild/Xamarin.iOS.Tasks.Core/Tasks/ValidateAppBundleTaskBase.cs

A Watch family is no longer valid for an iOS app because we don't support
watchOS 1 anymore.

[msbuild] Stop allowing a watch family for iOS apps.

---

msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileEntitlementsTaskBase.cs
msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DetectSigningIdentityTaskBase.cs

Seems like this got past the localization work somehow.

[msbuild] Use localized error strings instead of constants for a few errors.

---

mk/xamarin.mk

All governance issues have been fixed.
Commits:
* Remove roslyn-analyzers files (#2149) https://github.com/xamarin/maccore/commit/6c3fe624a98287d37d9230da21fe720008fa530e
* [Governance] Add ignores for the test profiles in maccore. (#2337) https://github.com/xamarin/maccore/commit/5133d2cea1c52fb783f64ab2ba97c760cf33f5f4
Full diff: https://github.com/xamarin/maccore/compare/8c98216efd070686d1bcb86afa2684463b62fc4e..5133d2cea1c52fb783f64ab2ba97c760cf33f5f4

[Maccore] Bump maccore to fix governance issues.

---

tools/mlaunch/Makefile

The original implementation only worked when we used mlaunch from the
macios-binaries repository.

[mlaunch] Adjust build logic to ship mlaunch with the .NET nugets when we're building mlaunch as well.

---

tools/common/Target.cs

We need support for dllmaps, and that isn't working on macOS yet.

[tools] Disable Objective-C exception handling for macOS .NET apps due to a missing feature in the runtime.

---

dotnet/targets/Xamarin.Shared.Sdk.targets

Don't link the main executable with any dylib (except libcoreclr) on macOS,
because that may end up running library initializers in those dylibs, and they
may abort if something goes wrong.
This way we delay any failures until those dylibs are actually needed.
In particular, libSystem.Security.Cryptography.Native.OpenSsl.dylib will abort
in its library initializer if it can't find the native libssl.dylib it wants:
https://github.com/dotnet/runtime/blob/1d9e50cb4735df46d3de0cee5791e97295eaf588/src/libraries/Native/Unix/System.Security.Cryptography.Native/opensslshim.c#L122-L126
and my system doesn't have any of the libssl.dylib versions that code wants.

[dotnet] Don't link the main executable with any dylibs on macOS.

---

src/Makefile

We only need one version, and in any case the code would write both the same
file, causing corruption and random build problems later.
Fixes this problem while building .NET packages:
/Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/dotnet/package/common.csproj(75,5): error : Classification matches no files: Xamarin.WatchOS.dll [/Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/dotnet/package/Microsoft.watchOS.Ref/package.csproj]
make[1]: *** [nupkgs/Microsoft.watchOS.Ref.7.1.100-ci.main.35+sha.a4a1fea86.nupkg] Error 1

[src] Don't generate a reference assembly for both the 32-bit and 64-bit variant of Xamarin.WatchOS.dll.

---

tests/monotouch-test/CoreGraphics/ColorSpaceTest.cs

```
CreateExtendedTest: System.EntryPointNotFoundException : CGColorSpaceCreateExtended assembly:<unknown assembly> type:<unknown type> member:(null)
```
The API was added in iOS 14.0 (Xcode 12.0) but macOS 11.0 (Xcode 12.2)
and it does not exists on my Mac (10.15.7) even if I don't recall seeing
fail on the bots.

[tests][monotouch] Fix recent CGColorSpace tests not to fail on macOS 10.15.x

---

tools/devops/automation/templates/build-packages.yml

Related work item: VS #[1250035](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1250035)
Utilize the `set-path` yaml template to ensure `virtualenv` is on the path for the duration of the build.

Ensure the pip virtualenv command is on the PATH

---

src/Makefile
tests/cecil-tests/Helper.cs
tests/xtro-sharpie/Makefile
tests/xtro-sharpie/xtro-sharpie.csproj
tools/mtouch/Makefile
tools/mtouch/mtouch.cs

Currently we put the implementation assemblies for all Xamarin.iOS platforms
in the same directory. This makes it impossible to have different
implementations for the same assembly in different platforms: in particular,
we're going to want a special version of Xamarin.iOS.dll for Mac Catalyst
(that will just have type forwarders into Xamarin.MacCatalyst.dll), that that
assembly will go into the Mac Catalyst-specific directory of implementation
assemblies.

[src/mtouch] Put implementation assemblies in a per-platform directory

---

src/generator-filters.cs
src/generator.cs

It's not necessary to have logic to compute namespaces anymore, that died with
Xamarin.iOS/Classic mode. So simplify the code to use constant values instead.
I hoped this would speed up the build a little bit, but I wasn't able to
measure any significant difference.

[src] Reintroduce namespaces as constants to simplify code.

---

src/Makefile.generator
src/generate-frameworks.csharp

* Add exception handling to avoid ignoring any failures.
* Pass -s to csharp and improve argument handling a bit.
* Pass the output path as the first argument, this way standard output can
have diagnostic output.
* Use temporary files to avoid rebuilding issues if there are any failures.
This PR might be best viewed by ignoring whitespace.

[src] Improve the generate-frameworks.csharp script.

---

tests/monotouch-test/MediaAccessibility/ImageCaptioningTest.cs

This works fine with Xcode 12.3 beta 1 on 10.15.7 (Intel) and 11.0
ref: https://github.com/xamarin/xamarin-macios/issues/10165

[tests] Re-enable MediaAccessibility/ImageCaptioningTest.cs` `SetCaption` test

---

src/MetricKit/MXMetaData.cs
src/MetricKit/MXMetric.cs
src/MetricKit/MXMetricPayload.cs

It won't work on platforms that don't have these deprecated API (Mac Catalyst).

[MetricKit] Don't use deprecated API to check system version.

---

tools/common/Target.cs

The method `xamarin_create_classes_Xamarin_Mac` was called twice which resulted in corruption of the type map. The first call was made from the generated `xammac_setup` method. The second call was made through registration method added in the RegistrarStep of dotnet-linker. This PR removes the first call for consistency with iOS and other platforms.

[dotnet] Avoid double registration of static registrar

---

opentk/Makefile.include
src/CoreImage/CIContext.cs
src/CoreVideo/CVOpenGLESTexture.cs
src/CoreVideo/CVOpenGLESTextureCache.cs
src/Makefile
src/Makefile.generator
src/OpenGLES/Makefile-1.0.include
src/UIKit/UIVibrancyEffect.cs
src/coreanimation.cs
src/coreimage.cs
src/foundation.cs
src/generate-defines.csharp

Take our list of frameworks per platform, and generate a list of conditional
compiler constants that states that a framework exists for a particular
platform.
Basically generate a list of `-d:HAS_<FRAMEWORK>` for each platform.
This makes it possible to do this:
```csharp
#if HAS_COREMEDIA
using CoreMedia;
#endif
```
instead of this:
```csharp
#if (PLATFORM1 || PLATFORM2) && !PLATFORM3 || PLATFORM4 || BUT_MAYBE_IF_ITS_FRIDAY
using CoreMedia;
#endif
```
Which makes it much easier when adding new platforms (say Mac Catalyst), or
when a framework is added to an already existing platform.
I've included a few examples of how it would end up looking. Changing all the
code to use these new defines is not the goal (nor is it that these defines
should always be used: sometimes they make most …

[src] Generate a define for each framework for every platform.

---

tools/devops/automation/build-pipeline.yml
tools/devops/automation/scripts/VSTS.Tests.ps1
tools/devops/automation/scripts/VSTS.psm1
tools/devops/automation/templates/configure-build.yml
tools/devops/automation/templates/device-tests.yml
tools/devops/automation/templates/governance-checks.yml
tools/devops/automation/templates/publish-html.yml
tools/devops/automation/templates/upload-azure.yml

Related to https://github.com/xamarin/xamarin-macios/pull/10143
Azure DevOps does not support adding build tags to PR builds involving GitHub forks via the [AddBuildTag ](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash#addbuildtag-add-a-tag-to-the-build) command
Consequently, we need to use the [Tags](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/tags?view=azure-devops-rest-6.0) REST API.  Furthermore, we need to use our own Azure DevOps PAT since the System.AccessToken will not work.
This change incorporates a dedicated Azure DevOps PAT based on a service account where the PAT value is obtained from KeyVault.  Replaces the "hard coded" DropsPAT previously used to unblock the tags-related REST API calls.

Tags from labels using dedicated Azure DevOps token

---

msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
msbuild/Xamarin.Shared/Xamarin.Shared.targets
msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets

* Add a stamp file to the Mac version of _CompileToNative. This is used to
force a rebuild of the container app when an app extension changes (and was
already implemented for iOS: 8b376efa4b2045f41e8e7eaa71fc45a41a0fa6a0)
* Rename the iOS stamp file to 'bundler.stamp' instead of 'mtouch.stamp' to
ease code sharing.
* Rename the 'MmpReferencePath' and 'MTouchReferencePath' properties to
'_BundlerReferencePath' to ease code sharing.
* Merge the _GetCompileToNativeInputs targets. The only difference between iOS
and Mac (after the above changes) is that the Mac version now includes
'@(ReferencePath)' in '_CompileToNativeInput'. This should be fine as far as
I know.

[msbuild] Unify the _GetCompileToNativeInputs target between iOS and Mac.

---

dotnet/targets/Xamarin.Shared.Sdk.targets
tools/dotnet-linker/SetupStep.cs
tools/dotnet-linker/Steps/GenerateReferencesStep.cs
tools/dotnet-linker/dotnet-linker.csproj
tools/linker/MonoTouch.Tuner/ListExportedSymbols.cs

Fixes running the following code:
```csharp
var ciFilter = CIFilter.FromName ("CIColorMatrix");
var result = (CIImage)ciFilter.ValueForKey (new NSString ("outputImage"));
```
which resulted into call to `xamarin_IntPtr_objc_msgSend_IntPtr` which was linked out from the native code.
This adds a step to dotnet-linker that mimics what mmp/mtouch was doing. Depending on symbol mode setting it either generates: a) references.m file that contains code referencing all the P/Invoked symbols to prevent the native linker from linking them out, or b) `-u<symbol>` linker flags that mark the symbols to be preserved.

[dotnet] Prevent linking out code referenced by P/Invoke

---

msbuild/Xamarin.Shared/Xamarin.Shared.targets

The build logic will put reference assemblies in
'ResolvedCompileFileDefinitions' instead of '_ReferencesFromNuGetPackages'
when using the new-style packageref format, so we need to handle
'ResolvedCompileFileDefinitions' the same way we handle
'_ReferencesFromNuGetPackages'.
I was unfortunately not able to create a unit test for this scenario, because
xibuild sets MSBUILD_EXE_PATH to make msbuild look in our local build files,
and then the restore fails with:
> Issue9266.csproj : error MSB4236: The SDK 'Msbuild.Sdk.Extras/2.1.2' specified could not be found.
If I don't use "Msbuild.Sdk.Extras" in the test, then it doesn't hit the
broken path this PR is fixing. If I change xibuild to not set
MSBUILD_EXE_PATH, we're not testing our local bits anymore, but the system
Xamarin.Mac.
Fixes …

[msbuild] Treat 'ResolvedCompileFileDefinitions' as a list of reference assemblies as well. Fixes #9266.

---

tools/devops/device-tests/templates/device-tests.yml

Some bots are not configure correctly and block, that means we wait for ever. Just wait for 30 mins max.
Backport of #10204.

[d16-8] [VSTS] Ensure that we have a reasonable timeout. Will unblock device tests.

---

tools/devops/device-tests/templates/device-tests.yml

Some bots are not configure correctly and block, that means we wait for ever. Just wait for 30 mins max.

[VSTS] Ensure that we have a reasonable timeout. Will unblock device tests.

---

tools/devops/device-tests/templates/device-tests.yml

This step is not working on certain bots, there are several examples at https://dev.azure.com/devdiv/DevDiv/_build?definitionId=13122&_a=summary
Backport of #10193.

[d16-8] [VSTS] If we fail dumping the env, continue.

---

tests/mtouch/SdkTest.cs

* Xamarin.Linker.SdkTest.NoLLVMFailuresInWatchOS("../../32bits/Xamarin.WatchOS.dll"):
AOT compilation
Expected: 0
But was: 1
This regresed in 87d04ac3311fa41237046fb499d84b1f3d530995.

[tests] Update test to cope with change in Xamarin.WatchOS.dll's location.

---

tools/devops/device-tests/templates/device-tests.yml

Some bots are not configure correctly and block, that means we wait for ever. Just wait for 30 mins max.
Backport of #10204.

[xcode12.3] [VSTS] Ensure that we have a reasonable timeout. Will unblock device tests.

---

tools/devops/automation/templates/build-packages.yml

If the env is not set, we have names such as
'Microsoft.watchOS.Runtime.watchos-x86.7.1.100-ci.HEAD.165+sha.14522b296.nupkg'

[VSTS] Add branchname in the nugets.

---

msbuild/Xamarin.iOS.Tasks.Core/Tasks/DetectDebugNetworkConfigurationTaskBase.cs
msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets

Not that it was very slow but it did make to the top 10 of the
archive build I was debugging.
Also reduce allocations in the task itself, for when it's needed.

[msbuild] Only execute DetectDebugNetworkConfigurationTask for debug builds

---

src/Constants.iOS.cs.in
src/Constants.mac.cs.in
src/adservices.cs
src/frameworks.sources
tests/xtro-sharpie/iOS-AdServices.todo
tests/xtro-sharpie/macOS-AdServices.todo
tools/common/Frameworks.cs
tools/mtouch/Makefile

Annotations suggest that it's available on tvOS 14.3 but the headers
are not shipped in tvOS SDK.

[adservices] New in Xcode 12.3 beta 1

---

msbuild/Xamarin.iOS.Tasks.Core/Tasks/ArchiveTaskBase.cs

This also includes dSYM inside xcframeworks, e.g.
```
...
├── dSYMs
│   ├── Universal.framework.dSYM
│   │   └── Contents
│   │       ├── Info.plist
│   │       └── Resources
│   │           └── DWARF
│   │               └── Universal
│   └── xcf_ios.app.dSYM
│       └── Contents
│           ├── Info.plist
│           └── Resources
│               └── DWARF
│                   └── xcf_ios
...
```
from https://github.com/spouliot/xcframework/tree/main/xamarin/xcf-ios
versus
```
...
└── dSYMs
├── Universal.framework.dSYM
│   └── Contents
│       ├── Info.plist
│       └── Resources
│           └── DWARF
│               └── Universal
└── xcf-ios.app.dSYM
└── Contents
├── Info.plist
└── Resources
└── DWARF
└── xcf-ios
...
```
from the similar ObjC sample …

[msbuild] Archive the user frameworks .dSYM when available

---

tools/compare-commits.sh

Fixes https://github.com/xamarin/xamarin-macios/issues/10222.

[compare-commits] Fix building the previous commit for Xamarin.MacCatalyst. Fixes #10222.

---

dotnet/targets/Xamarin.Shared.Sdk.targets

Set all current feature switches, except for InvariantGlobalization, to
defaults which trim the features.
Ref: https://github.com/dotnet/runtime/blob/master/docs/workflow/trimming/feature-switches.md
Ref: https://github.com/xamarin/xamarin-android/pull/5337
This drops the hello world app size from 28.6 MB to 23.5 MB. Full report:
https://gist.github.com/rolfbjarne/71cc18b49446862f1d42aa29526b0ac6

[dotnet] Set default runtime feature switches.

---

src/foundation.cs

Fixes https://github.com/xamarin/xamarin-macios/issues/10260.

[Foundation] Fix typo in NSFileCoordinator.CoordinateBatc[h]. Fixes #10260.

---

tools/compare-commits.sh

Rework the code to generate an API comparison and a generator comparison: we
now clone xamarin-macios into a different directory, checks out the hash we
want to compare against, build the whole thing, and then compare the results.
This is somewhat slower than the previous implementation (which would checkout
the previous hash and build that on top of the existing build), but since we
don't have to build mono, it shouldn't make too much of a difference (the
biggest chunk of our build is building src/, and we had to do that anyway with
the previous implementation as well).
The upside is that it should be much more reliable.
Fixes https://github.com/xamarin/maccore/issues/2034.
Fixes https://github.com/xamarin/maccore/issues/1467.
Fixes https://github.com/xamarin/maccore/issues/1059.
Maybe …

[compare-commits] Rework logic to build xamarin-macios again from a separate clone.

---

.github/workflows/backport-trigger.yml

As part of the effort to move away from jenkins, the @monojenkins bot will be retired. This adds an action to be used that does the same job.
New action can be executed via '@vs-mobiletools-engineering-service2 backport $TARGET_BRANCH'

[Actions] Add the backport action

---

.github/workflows/rebase-trigger.yml

As part of the effort to move away from jenkins, the @monojenkins bot will be retired. This adds an action to be used that does the same job.
The new action can be executed via '@vs-mobiletools-engineering-service2 rebase'

[Actions] Add a rebase action.

---

src/foundation.cs

Fixes https://github.com/xamarin/xamarin-macios/issues/10261.

[Foundation] Fix nullability for the 'resourceValues' parameter for NSUrl.CreateBookmarkData. Fixes #10261.

---

tools/devops/automation/build-pipeline.yml
tools/devops/automation/templates/packages/build.yml
tools/devops/automation/templates/packages/stage.yml

Allow a developer to skip the device tests when running from the VSTS UI. Useful when debugging the actual pipeline.

[VSTS] Allow to skip device tests when triggering form vsts.

---

tests/fsharp/fsharp.fsproj
tests/fsharplibrary/fsharplibrary.fsproj

We're not shipping F# assemblies for Mac Catalyst, so just use the ones from
NuGet instead.
This is a partial fix for https://github.com/xamarin/xamarin-macios/issues/10217.

[tests] Use the FSharp.Core NuGet for Mac Catalyst.

---

src/generator-attribute-manager.cs
tests/generator/ErrorTests.cs
tests/generator/bi1059.cs

Fixes https://github.com/xamarin/xamarin-macios/issues/10310.

[bgen] Avoid a NullReferenceException when reporting multiple attributes on a type. Fixes #10310.

---

msbuild/Xamarin.iOS.Tasks.Core/Xamarin.MacCatalyst.ObjCBinding.CSharp.targets
msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
tests/test-libraries/Makefile
tools/common/Application.cs
tools/common/CompilerFlags.cs
tools/mtouch/Application.mtouch.cs

* Build our native test libraries for Mac Catalyst.
* Add the required MSBuild targets file for Mac Catalyst binding projects to work
* Fix up a few things in mtouch and msbuild logic.
This makes the framework-test and interdependent-binding-projects tests green.
Fixes https://github.com/xamarin/xamarin-macios/issues/10286.
Partial fix for https://github.com/xamarin/xamarin-macios/issues/10217.

Add support for binding projects in Mac Catalyst. Fixes #10286.

---

src/generate-type-forwarders/Program.cs

This shows up in a Xamarin.Forms app, which has a reference to
System.Drawing.RectangleF in Xamarin.iOS.dll, which is a type forwarder to
System.Drawing.Common.dll. That type forwarder must also exist in the
Xamarin.iOS.dll Facadate that Mac Catalyst uses.

[src] Any type forwarders in iOS' Xamarin.iOS.dll must appear in the Mac Catalyst facade as well.

---

tools/devops/automation/templates/devices/build.yml
tools/devops/automation/templates/packages/build.yml

The prefix of the location of the logs depends on the platform where it
was executed (else we step on them) but that was not added in the env
var use by xharness.
fixes: https://github.com/xamarin/maccore/issues/2349

[CI][VSTS] Ensure that xharness creates an index with the correct uris.

---

tools/devops/Makefile
tools/devops/build-provisioning.csx.in

Ensure that the new dotnet 6 is installed so that we do build with the
support for it.
fixes: https://github.com/xamarin/maccore/issues/2354

[CI][VSTS] Add the donet 6 pkg as a dependency.

---

tools/devops/automation/scripts/GitHub.psm1

The GitHup url to be used to create comments in PRs is diff to the one
for comments. Use the build reason AND the changeID to identify if we
are building due to a PR and use the correct url.
fixes: https://github.com/xamarin/maccore/issues/2356

[CI][VSTS] Add comments to PR not only to commits.

---

msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CodesignTaskBase.cs
tools/mmp/driver.cs

User frameworks for macOS often uses symlinks (as Xcode creates them
this way).
This cause problem cause the symlink is on the binary and we expected
the `_CodeSignature` directory to by side-by-side with the binary. This
was missing and cause exceptions when codesigning such frameworks.
A second problem happened because `mmp` use `lipo -thin` to remove
non-required architectures. However when a framework has symlinks, like:
```
├── Frameworks
│   └── Universal.framework
│       ├── Resources -> Versions/Current/Resources
│       ├── Universal -> Versions/Current/Universal
│       └── Versions
│           ├── A
│           │   ├── Resources
│           │   │   └── Info.plist
│           │   ├── Universal
│           │   └── _CodeSignature
│           │       └── CodeResources
│ …
```

[macos] Handle symlinks in user frameworks

---

tools/devops/automation/templates/devices/build.yml
tools/devops/automation/templates/packages/build.yml

The prefix of the location of the logs depends on the platform where it
was executed (else we step on them) but that was not added in the env
var use by xharness.
fixes: https://github.com/xamarin/maccore/issues/2349 
Backport of #10345

[xcode12.3] [CI][VSTS] Ensure that xharness creates an index with the correct uris.

---

tools/devops/automation/templates/packages/upload-azure.yml

The wrong variable was used and therefore the dir path was used instead
of the mac pkg name.
fixes: https://github.com/xamarin/maccore/issues/2353 
Backport of #10347

[d16-9] [CI][VSTS] Add the correct mac pkg file name.

---

tools/devops/automation/scripts/GitHub.psm1

The GitHup url to be used to create comments in PRs is diff to the one
for comments. Use the build reason AND the changeID to identify if we
are building due to a PR and use the correct url.
fixes: https://github.com/xamarin/maccore/issues/2356 
Backport of #10350

[d16-9] [CI][VSTS] Add comments to PR not only to commits.

---

tools/devops/automation/templates/devices/build.yml
tools/devops/automation/templates/packages/build.yml

The prefix of the location of the logs depends on the platform where it
was executed (else we step on them) but that was not added in the env
var use by xharness.
fixes: https://github.com/xamarin/maccore/issues/2349 
Backport of #10345

[d16-9] [CI][VSTS] Ensure that xharness creates an index with the correct uris.

---

tools/devops/automation/scripts/GitHub.psm1

The GitHup url to be used to create comments in PRs is diff to the one
for comments. Use the build reason AND the changeID to identify if we
are building due to a PR and use the correct url.
fixes: https://github.com/xamarin/maccore/issues/2356 
Backport of #10350

[xcode12.3] [CI][VSTS] Add comments to PR not only to commits.

---

tests/xharness/Xharness.Tests/Xharness.Tests.csproj
tests/xharness/Xharness.Tests/packages.config
tests/xharness/xharness.csproj

This is mainly to bring in this fix: https://github.com/dotnet/xharness/commit/841114a759e81043973856abe0917329b3ef5749
(two parameters were swapped and `BundleIdentifier` was set to `AppPath`)
Other changes contained:
- We don't log the full XML when listing devices anymore, just the file size
- `SimulatorLoader` has a new method that accepts `retryCount`

[xharness] Bump the shared library version

---

versions-check.csharp

* Pass -s to csharp to tell it the rest of the arguments are the script and its arguments.
Fixes these warnings printed to the terminal:
warning CS2002: Source file `7.0' specified multiple times
warning CS2002: Source file `10.15' specified multiple times
* Add an exception handler and return 1 if there are any exceptions.

[versions-check.csharp] Improve this script a bit

---

msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ArchiveTaskBase.cs
msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DittoTaskBase.cs

`--rsrc` has been the default since macOS 10.4

[msbuild] Remove the old `--rsrc` argument when using `ditto`

---

msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DSymUtilTaskBase.cs
msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets

User frameworks comes in different "shapes"
* You can roll your own (like ours are) and they are likely to be similar
to dynamic libraries. Of interest is the fact that the native binary
will include debugging symbols. On which our tools will, at a later
point, run `dsymutil` to create a `dSYM` and `strip` the binary.
* You can create them with a tool, like Xcode, and the build's output
will give you a `dSYM` and a stripped (no debug information) binary.
Now we can't process the later like the former. Because if we execute
`dsymutil` on the **stripped** framework we'll get an _empty_ (no symbol)
`.dSYM`. The tool will issue a warning like:
> warning: no debug symbols in executable (-arch arm64)
which is easy to miss since it's informational (now promoted to a proper
msbuild warning).
The …

[msbuild] Use the existing user framework dSYM when available

---

src/Security/SecureTransport.cs

This difference manifested as a memory corruption (because we were passing an array of the enum to native code, and the array was half the size it should be, so native code write into random memory).

[Security] Fix the underlying integral type for SslCipherSuite for Mac Catalyst.

---

tests/xharness/Xharness.Tests/Xharness.Tests.csproj
tests/xharness/Xharness.Tests/packages.config
tests/xharness/xharness.csproj

This is mainly to bring in this fix: https://github.com/dotnet/xharness/commit/841114a759e81043973856abe0917329b3ef5749
(two parameters were swapped and `BundleIdentifier` was set to `AppPath`)
Other changes contained:
- We don't log the full XML when listing devices anymore, just the file size
- `SimulatorLoader` has a new method that accepts `retryCount` 
Backport of #10326

[d16-9] [xharness] Bump the shared library version

---

src/Foundation/NSUrlSessionHandler.cs

This is an interesting issue that happens in the following scenario:
1. A request is performed that will take some extra time to get a
response or an error.
2. The request is cancelled BEFORE the delegate methods
DidReceiveResponse, DidReceiveData or DidCompleteWithError and
called. Yet we have not yet fully canceled the native request. It
does take some time to do so, that is why we have a
'NSURLSessionTaskStateCanceling' and not 'NSURLSessionTaskStateCancelled'
The issue happens because the GetInflightData checks if the task has
been canceled. In that method we have the following:
```csharp
if (inflight.CancellationToken.IsCancellationRequested)
task?.Cancel ();
return inflight;
```
The call of the Cancel method in the NSData task has as ripple effect which
is the execution of the …

[Foundation] Break out of the delegate when we have canceled a task. Fixes #9132

---

tools/devops/automation/scripts/GitHub.psm1

Remove the misleading title 'Device tests..' for 'Tests..'. The message
already contains the context of the test execution, it can be:
* Build
* VSTS: device tests iOS32b
* VSTS: device tests tvOS
* VSTS: device tests iOS
Removing the 'Device' word is enough to do not confuse users.
fixes: https://github.com/xamarin/maccore/issues/2358

[CI][VSTS] Add a better title for the comments.

---

msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ResolveFrameworksBase.cs
msbuild/Xamarin.iOS.Tasks.Core/Tasks/MTouchTaskBase.cs
msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/ResolveNativeReferencesTaskTest.cs
tools/mmp/driver.cs

TD&LR: This PR simplifies how we refer to user frameworks and fixes both
warnings and non-optimal (app) output.
Much longer story:
Additional testing on macOS showed some build-time warnings and an
[extra (dupe) file](https://github.com/spouliot/xcframework/commit/a20f8aba419e32e2338cb7c5e4b45d0f38862893#diff-54fd7d9cd5deae57f30195be0a43133eace03c1132401741a317e0ae8d5e13fdR34).
Logs shows that we referred to the xcframework several times, where once
should have been enough.
```
/native-reference:/Users/poupou/git/spouliot/xcframework/Universal.xcframework
/native-reference:/Users/poupou/git/spouliot/xcframework/Universal.xcframework/macos-arm64_x86_64/Universal.framework
/native-reference:/Users/poupou/git/spouliot/xcframework/Universal.xcframework/macos-arm64_x86_64/Universal.framework/Un …
```

[msbuild] Simplify resolving xcframeworks

---

src/UIKit/UIBarItem.cs

Mac Catalyst will be able to reference assemblies built for Xamarin.iOS, but
without any guarantees that it will actually work.
However, we'll want to make basic scenarios work, and with this change we're
adding an overload of UIBarItem.SetTitleTextAttributes that would not normally
exist in Mac Catalyst, so that existing code built for Xamarin.iOS works just
fine at runtime (in particular Xamarin.Forms runs into this).

[UIKit] Add the same UIBarItem.SetTitleTextAttributes overload to Mac Catalyst as iOS has.

---

src/Makefile
tools/dotnet-linker/.gitignore

This version of OpenTK-1.0.dll only contains type forwarders for
System.Drawing.Color and System.Drawing.KnownColor. Eventually it may also
contain stubs that throw PlatformNotSupportedExceptions.
The main problem we're trying to solve is that we want to make the version of
Xamarin.Essentials built for Xamarin.iOS work in Mac Catalyst, and it
references OpenTK-1.0.dll, which means that we'll show an error at build time
if we can't find OpenTK-1.0.dll. This way there will be an OpenTK-1.0.dll, but
it's only available as an implementation assembly, which means that it's not
possible to reference it directly from a Mac Catalyst project.

[src] Build and ship a very simple implementation-only version of OpenTK-1.0.dll for Mac Catalyst.

---

tools/mtouch/Application.mtouch.cs
tools/mtouch/Target.mtouch.cs

This broke with 1582bf47cc272640973cbe6933834b2debb80769 and cause the
frameworks to be nested under another `Frameworks` directory.
See https://github.com/xamarin/xamarin-macios/issues/10382

[mtouch] Fix embedding Mono (and Xamarin) as frameworks. Fixes #10382

---

Make.config

This makes xamarin-macios build on Apple Silicon, and also seems to get an
updated csc that fixes a problem with nullability warnings/errors.

Bump system mono to the latest available 2020-02 package.

---

tools/devops/automation/scripts/GitHub.psm1

Remove the misleading title 'Device tests..' for 'Tests..'. The message
already contains the context of the test execution, it can be:
* Build
* VSTS: device tests iOS32b
* VSTS: device tests tvOS
* VSTS: device tests iOS
Removing the 'Device' word is enough to do not confuse users.
fixes: https://github.com/xamarin/maccore/issues/2358 
Backport of #10383

[xcode12.3] [CI][VSTS] Add a better title for the comments.

---

tools/devops/automation/scripts/GitHub.psm1

Remove the misleading title 'Device tests..' for 'Tests..'. The message
already contains the context of the test execution, it can be:
* Build
* VSTS: device tests iOS32b
* VSTS: device tests tvOS
* VSTS: device tests iOS
Removing the 'Device' word is enough to do not confuse users.
fixes: https://github.com/xamarin/maccore/issues/2358 
Backport of #10383

[d16-9] [CI][VSTS] Add a better title for the comments.

---

tools/devops/automation/build-pipeline.yml
tools/devops/automation/templates/build/build.yml
tools/devops/automation/templates/devices/build.yml
tools/devops/automation/templates/governance-checks.yml

The agent name and HOSTNAME sometimes don't match; particularly, for test machines.  Include the HOSTNAME as a means to better locate the actual machine that the pipeline is running on.
Includes an update to use the correct build definition link as the build definition was recreated at one point.

YAML build: Dump environment steps: Include HOSTNAME

---

tools/devops/automation/scripts/bash/clean-bot.sh

At some point either due to a manual error or a bug in provisionator a
*.xip file was left behind. Those files make provisioantor fail, for
example: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4361631&view=logs&j=f0137cdf-e292-5541-69aa-72303a08a0ba&t=59bea1c0-f907-5818-000e-f6fef9d3ffa2&l=230
We will remove those files to make sure provisionator works and we get
device tests back.

[CI][VSTS] Clean .xip files.

---

tools/dotnet-linker/LinkerConfiguration.cs
tools/dotnet-linker/SetupStep.cs
tools/dotnet-linker/Steps/ComputeNativeBuildFlagsStep.cs
tools/dotnet-linker/Steps/DoneStep.cs

Add a ComputeNativeBuildFlagsStep, which computes the flags to pass to the
native compiler + native linker. This is currently a very simple
implementation, but it will become more complex as support for missing
features are added.
This also required adding support for writing to the same MSBuild output items
multiple times:
* Split parts of LinkerConfiguration.WriteOutputForMSBuild into a
FlushOutputForMSBuild method (the part that does the actual writing).
* Make WriteOutputForMSBuild just store the items in a dictionary.
* Add a DoneStep that runs at the very end and that writes out the MSBuild
output items.

[dotnet-linker] Link with GSS when building for iOS/Mac Catalyst.

---

tests/monotouch-test/dotnet/iOS/monotouch-test.csproj

* Don't use entitlements when building monotouch-test for device.
* Fix conditional compilation constants when building for device.

[monotouch-test] Fix a few issues when running the .NET version of monotouch-test on device.

---

dotnet/targets/Xamarin.Shared.Sdk.targets

Xamarin.iOS don't AOT compile resource assemblies, so we shouldn't do so in
.NET either (and in any case they end up causing native linking failures due
to duplicate native symbols).

[dotnet] Don't AOT compile resource assemblies.

---

tools/devops/automation/scripts/bash/clean-bot.sh

At some point either due to a manual error or a bug in provisionator a
*.xip file was left behind. Those files make provisioantor fail, for
example: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4361631&view=logs&j=f0137cdf-e292-5541-69aa-72303a08a0ba&t=59bea1c0-f907-5818-000e-f6fef9d3ffa2&l=230
We will remove those files to make sure provisionator works and we get
device tests back. 
Backport of #10398

[xcode12.3] [CI][VSTS] Clean .xip files.

---

tools/devops/automation/scripts/bash/clean-bot.sh

At some point either due to a manual error or a bug in provisionator a
*.xip file was left behind. Those files make provisioantor fail, for
example: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4361631&view=logs&j=f0137cdf-e292-5541-69aa-72303a08a0ba&t=59bea1c0-f907-5818-000e-f6fef9d3ffa2&l=230
We will remove those files to make sure provisionator works and we get
device tests back. 
Backport of #10398

[d16-9] [CI][VSTS] Clean .xip files.

---

tests/monotouch-test/CoreGraphics/ColorTest.cs
tests/monotouch-test/SceneKit/AvoidOccluderConstraintTest.cs

This makes these tests not fail on iOS 10.3.3.

[monotouch-test] Add a few Xcode version checks to ColorTest and AvoidOccluderConstraintTest.

---

tests/monotouch-test/CoreFoundation/ProxyTest.cs

All the other *NoProxy tests use the Microsoft uri, which seems to be the uri
that's not supposed to need a proxy (according to what I understand from the
code) - in other words, it looks like this was a c&p error.
Fixes this test failure when running on device:
[FAIL] TestPACParsingAsyncNoProxy :   Expected: None
But was:  HTTPS
at MonoTouchFixtures.CoreFoundation.ProxyTest.TestPACParsingAsyncNoProxy () [0x000fa] in /Users/rolf/work/maccore/onedotnet/xamarin-macios/tests/monotouch-test/CoreFoundation/ProxyTest.cs:238

[monotouch-test] Change the url for the TestPACParsingScriptNoProxy test to be the Microsoft uri.

---

tests/monotouch-test/SystemConfiguration/CaptiveNetworkTest.cs

According to Apple's documentation, an app linked with iOS 12 or later must
enable a specific entitlement, otherwise calls to CNCopyCurrentNetworkInfo
will always return NULL.

[monotouch-test] Adjust CaptiveNetworkTest.TryCopyCurrentNetworkInfo to work on iOS 10.3.3

---

tools/devops/automation/scripts/GitHub.psm1

Github has a limited size for messages in comments. If we did reach that
limit, we create a gist to show all the results.
Backport of #10431

[d16-9] [CI][VSTS] If comments are too large, provide a gist.

---

tests/monotouch-test/dotnet/extra-linker-defs.xml
tests/monotouch-test/dotnet/iOS/monotouch-test.csproj

Ref: https://github.com/dotnet/runtime/issues/46908.

[tests] Preserve a required method in System.Private.CoreLib to work around a bug in .NET 6.

---

msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DetectSigningIdentityTaskBase.cs

Code signing for Mac Catalyst is very much like code signing for macOS, except that:
* If a provisioning profile is required, then we must find a code signing certificate.
* Provide a code signing key even if we don't need a code signing certificate.
This makes the tests in monotouch-test that require a correctly signed app pass.

[msbuild] Fix code signing logic for Mac Catalyst.

---

msbuild/Xamarin.Localization.MSBuild/MSBStrings.Designer.cs
msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx
msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.cs.xlf
msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.de.xlf
msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.es.xlf
msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.fr.xlf
msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.it.xlf
msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.ja.xlf
msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.ko.xlf
msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.pl.xlf
msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.pt-BR.xlf
msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.ru.xlf
msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.tr.xlf
msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.zh-Hans.xlf
msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.zh-Hant.xlf
msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CodesignTaskBase.cs
tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/LocalizationIgnore/common-Translations.ignore

TL&DR:
This effectively change nothing - but prevents (warn) if both options
contradict themselves.
Long Story....
So we have two ways to control the codesign's `--timetamp` option but
they both ignore each other so we can end up with the option being
set more than once at build time.
`DisableTimestamp` was the original one. It was meant for iOS (and
derivative OS) and disable the option (which requires the network)
for simulator or debug builds. IOW we _wanted_ timestamps when doing
release builds for devices.
```
DisableTimestamp="$(_CodesignDisableTimestamp)"
```
```
<_CodesignDisableTimestamp>False</_CodesignDisableTimestamp>
<_CodesignDisableTimestamp Condition="'$(_SdkIsSimulator)' == 'true' Or '$(_BundlerDebug)' == 'true'">True</_CodesignDisableTimestamp>
```
Now disabling the …

[msbuild] Fix semi-conflicting options to set codesign timestamp

---

tests/package-mac-tests.sh

fixes: https://github.com/xamarin/maccore/issues/2363
Backport of #10432

[d16-9] [CI][VSTS] The pkg of the tests fail because there is a path not longer found.

---

tests/xharness/TestProject.cs

Fixes this warning when running xharness:
Unknown file: fsharplibrary.fsproj (extension: .fsproj). There might be a default inclusion behavior for this file.

[xharness] Fix warning about unknown file wrt default inclusion.

---

tests/mtouch/MTouch.cs

Fixes https://github.com/xamarin/maccore/issues/2154.

[tests] Don't use the tcp tunnel in the HttpClientHandler tests. Fixes xamarin/maccore#2154.

---

tools/dotnet-linker/LinkerConfiguration.cs
tools/dotnet-linker/dotnet-linker.csproj
tools/linker/MonoTouch.Tuner/PreserveSmartEnumConversionsSubStep.cs

This allows us to undo a workaround we made for a missing API in the linker
reference assembly (an AnnotationStore.AddPreservedMethod overload).
This also requires a change to use MessageContainer.CreateCustomErrorMessage
instead of MessageContainer.CreateErrorMessage, because apparently having a
reference assembly doesn't mean there can't be incompatible changes in it 😒.

[dotnet] Bump ILLink to get an updated linker reference assembly.

---

msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.TargetFrameworkFix.targets

_XamarinBclPath always has a trailing slash, so no need to add another one
when adding subdirectories to it.
Fixes https://github.com/xamarin/xamarin-macios/issues/10446.

[msbuild] Remove duplicate trailing slash from _XamarinBclPath. Fixes #10446.

---

tests/dotnet/UnitTests/ProjectTest.cs
tools/dotnet-linker/SetupStep.cs
tools/dotnet-linker/Steps/DotNetSubStepDispatcher.cs
tools/dotnet-linker/dotnet-linker.csproj
tools/linker/RemoveUserResourcesSubStep.cs

This comes with a few changes to the RemoveUserResources sub step as well:
* Bail out earlier if we're in the simulator (no need to do any processing at
all - we know at the very beginning if we're building for the simulator).
* Do a positive simulator check, instead of a negative device check (because
Mac[Catalyst] are neither devices - so they pass the negative device check).
* Remove all the conditional mtouch/mmp code, and figure out at runtime which
resource prefixes we need to check for.
It was also necessary to change where steps are added to the pipeline: we have
to remove resources before the OutputStep, but at the same time we have to do
it after the ExtractBindingLibraries step, otherwise the
ExtractBindingLibraries step won't find any binding libraries to extract. So
move the …

[dotnet-linker] Add the RemoveUserResources sub step.

---

tools/common/Application.cs
tools/common/Driver.cs
tools/mtouch/Target.mtouch.cs

because:
> If the file to be deleted does not exist, no exception is thrown.
https://docs.microsoft.com/en-us/dotnet/api/system.io.file.delete?view=net-5.0
and yes this is different from `Directory.Delete` and PR https://github.com/xamarin/xamarin-macios/pull/10441

[tools] Do not check the existing of a file before deleting it

---

tools/common/Application.cs
tools/common/Target.cs
tools/mmp/driver.cs
tools/mtouch/Application.mtouch.cs

Today both `mtouch` and `mmp` are copying the entire `.framework`
directories inside the `.app\[Contents\]Frameworks\` directory.
However not everything in a framework is required at runtime. The most
common unrequired files would be headers (`Headers/*.h`) and modules
(`Modules/*`).
Looking at Xcode build output we can see something like:
```
builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -exclude Headers -exclude PrivateHeaders -exclude Modules -exclude \*.tbd -bitcode-strip replace-with-marker -bitcode-strip-tool
```
which excludes a few more, less common, files.
This _builtin_ command is not available externally (for us to re-use)
but it hints that Xcode is likely using `rsync` to avoid copying part of
the files.
Note: the builtin command also …

[mtouch][mmp] Exclude extraneous framework files from being copied into apps

---

msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CodesignTaskBase.cs

Using `Path.Combine` with a full qualified path for the 2nd argument will
return that 2nd argument (ignoring the first one).
That meant the `StampPath` was pointing to the actual files that were
just signed - overwriting them with a 0-length data (empty).
The solution is to make the 2nd argument relative, starting after
`.app/` so `Path.Combine` works as expected (being relative) while
allowing signing multiple files that have the same name (in different
directories).
ref: https://github.com/xamarin/xamarin-macios/issues/10445

[msbuild] Fix codesign `StampPath`. Fix #10445

---

tools/devops/automation/templates/build/build.yml

The template does not expand wildcards. The template does not know how to
reuse paths.

[CI][VSTS] Remove warning from mac tests upload.

---

msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.TargetFrameworkFix.targets

_XamarinBclPath always has a trailing slash, so no need to add another one
when adding subdirectories to it.
Fixes https://github.com/xamarin/xamarin-macios/issues/10446.
Backport of #10449

[d16-9] [msbuild] Remove duplicate trailing slash from _XamarinBclPath. Fixes #10446.

---

tools/mlaunch/Makefile

This way the bin directory doesn't unnecessarily get an updated timestamp, so
that some build targets in the dotnet/ directory don't rebuild unnecessarily.

[mlaunch] Improve make logic to only install bin/mlaunch if it changed.

---

tools/devops/automation/templates/build/build.yml

The template does not expand wildcards. The template does not know how to
reuse paths.
Backport of #10442

[xcode12.3] [CI][VSTS] Remove warning from mac tests upload.

---

tools/devops/automation/templates/build/build.yml

The template does not expand wildcards. The template does not know how to
reuse paths.
Backport of #10442

[d16-9] [CI][VSTS] Remove warning from mac tests upload.

---

tests/xharness/Jenkins/Reports/HtmlReportWriter.cs

We need to add the prefix to the xharness logs or we will not be able to
acceess them via a click.

[Xharness] Fix the xharness links to work with vsdrops.

---

tests/mtouch/MTouch.cs

Fixes https://github.com/xamarin/maccore/issues/2154.
Backport of #10451

[d16-9] [tests] Don't use the tcp tunnel in the HttpClientHandler tests. Fixes xamarin/maccore#2154.

---

msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DetectSigningIdentityTaskBase.cs

* We assigned the same value to DetectedBundleId in every branch, so instead
assign it once at the beginning.
* We assigned the same value to DetectedAppId to most branches, so instead
assign that value at the beginning as a default value.

[msbuild] Simplify some code in DetectSigningIdentityTask.

---

msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CodesignTaskBase.cs

Using `Path.Combine` with a full qualified path for the 2nd argument will
return that 2nd argument (ignoring the first one).
That meant the `StampPath` was pointing to the actual files that were
just signed - overwriting them with a 0-length data (empty).
The solution is to make the 2nd argument relative, starting after
`.app/` so `Path.Combine` works as expected (being relative) while
allowing signing multiple files that have the same name (in different
directories).
ref: https://github.com/xamarin/xamarin-macios/issues/10445
Backport of #10459

[d16-9] [msbuild] Fix codesign `StampPath`. Fix #10445

---

msbuild/Xamarin.Mac.Tasks.Core/Tasks/CompileAppManifestTaskCore.cs
msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileAppManifestTaskBase.cs
msbuild/Xamarin.iOS.Tasks.Core/Tasks/CompileAppManifestTaskCore.cs
tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/GeneratePlistTaskTests/GeneratePlistTaskTests_iOS.cs

Previously, CFBundleName would default to:
* iOS: CFBundleDisplayName (if set), otherwise the app bundle name.
* all other platforms: the app bundle name.
Now unify the logic so that we have the same behavior on all platforms.
This is a breaking change under the following conditions:
* Building for iOS
* CFBundleName is not set in the Info.plist
* CFBundleDisplayName is set in the Info.plist
* CFBundleDisplayName from the Info.plist is different from AssemblyName in
the csproj (which is the value used to calculate the app bundle name).
The fix would be to:
* Set CFBundleName in the Info.plist to the desired value.
This change works in previous versions of Xamarin.iOS as well.

[msbuild] Unify how CFBundleName is calculated.

---

tests/xharness/Jenkins/Reports/HtmlReportWriter.cs

We need to add the prefix to the xharness logs or we will not be able to
acceess them via a click.
Backport of #10469

[d16-9] [Xharness] Fix the xharness links to work with vsdrops.

---

tests/xharness/Jenkins/Reports/HtmlReportWriter.cs

We need to add the prefix to the xharness logs or we will not be able to
acceess them via a click.
Backport of #10469

[xcode12.3] [Xharness] Fix the xharness links to work with vsdrops.

---

tools/devops/automation/scripts/bash/clean-bot.sh

This is clearly something that has a human behind it and not a script. We
have seen Xcode*.xip which is the download name BUT also xcode12.xip
which looks like a point&click intervention
(https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4387395&view=logs&j=f0137cdf-e292-5541-69aa-72303a08a0ba&t=59bea1c0-f907-5818-000e-f6fef9d3ffa2&l=234)

[CI][VSTS] Remove ALL .xip

---

tools/devops/automation/build-pipeline.yml
tools/devops/automation/templates/build/build.yml
tools/devops/automation/templates/build/stage.yml
tools/devops/provision-brew-packages.csx

This PR contains just the required changes to add notarization via ESRP. Signing the pkg is done by the old python script (pay attention to the args). The artifacts are named the same and are in the same location, we only splinted the work. 
Backport of #10444

[d16-9] [CI][VSTS] Move to ESRP for notarization.

---

tools/devops/automation/build-pipeline.yml
tools/devops/automation/templates/build/build.yml
tools/devops/automation/templates/build/stage.yml
tools/devops/provision-brew-packages.csx

This PR contains just the required changes to add notarization via ESRP. Signing the pkg is done by the old python script (pay attention to the args). The artifacts are named the same and are in the same location, we only splinted the work. 
Backport of #10444

[xcode12.3] [CI][VSTS] Move to ESRP for notarization.

---

tools/devops/automation/scripts/bash/clean-bot.sh

This is clearly something that has a human behind it and not a script. We
have seen Xcode*.xip which is the download name BUT also xcode12.xip
which looks like a point&click intervention
(https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4387395&view=logs&j=f0137cdf-e292-5541-69aa-72303a08a0ba&t=59bea1c0-f907-5818-000e-f6fef9d3ffa2&l=234)
Backport of #10483

[d16-9] [CI][VSTS] Remove ALL .xip

---

tools/devops/automation/scripts/bash/clean-bot.sh

This is clearly something that has a human behind it and not a script. We
have seen Xcode*.xip which is the download name BUT also xcode12.xip
which looks like a point&click intervention
(https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4387395&view=logs&j=f0137cdf-e292-5541-69aa-72303a08a0ba&t=59bea1c0-f907-5818-000e-f6fef9d3ffa2&l=234)
Backport of #10483

[xcode12.3] [CI][VSTS] Remove ALL .xip

---

tools/devops/automation/templates/build/build.yml

There are two issues:
1. The pipeline should provision the simulators.
2. An issue in how xharness reports the failure: https://github.com/xamarin/maccore/issues/2375
This will ensure we are back running the tests as shown in https://github.com/xamarin/xamarin-macios/commit/65f1c3903a8e6892cd4e1830a43a42d81f78da60

[CI][VSTS] Ensure that the required simulators are present in the machine

---

tools/devops/automation/templates/build/build.yml

We want to continue and generate the pkgs, the failure of this step only
results in failing tests.
fixes: https://github.com/xamarin/maccore/issues/2376

[CI][VSTS] Continue on profiles failure.

---

tools/devops/automation/templates/build/build.yml

We want to continue and generate the pkgs, the failure of this step only
results in failing tests.
fixes: https://github.com/xamarin/maccore/issues/2376
Backport of #10487

[xcode12.3] [CI][VSTS] Continue on profiles failure.

---

tools/devops/automation/templates/build/build.yml

We want to continue and generate the pkgs, the failure of this step only
results in failing tests.
fixes: https://github.com/xamarin/maccore/issues/2376
Backport of #10487

[d16-9] [CI][VSTS] Continue on profiles failure.

---

tools/devops/automation/templates/build/build.yml

There are two issues:
1. The pipeline should provision the simulators.
2. An issue in how xharness reports the failure: https://github.com/xamarin/maccore/issues/2375
This will ensure we are back running the tests as shown in https://github.com/xamarin/xamarin-macios/commit/65f1c3903a8e6892cd4e1830a43a42d81f78da60
Backport of #10486

[xcode12.3] [CI][VSTS] Ensure that the required simulators are present in the machine

---

tools/devops/automation/templates/build/build.yml

There are two issues:
1. The pipeline should provision the simulators.
2. An issue in how xharness reports the failure: https://github.com/xamarin/maccore/issues/2375
This will ensure we are back running the tests as shown in https://github.com/xamarin/xamarin-macios/commit/65f1c3903a8e6892cd4e1830a43a42d81f78da60
Backport of #10486

[d16-9] [CI][VSTS] Ensure that the required simulators are present in the machine

---

tests/monotouch-test/Security/CertificateTest.cs
tests/monotouch-test/Security/KeyTest.cs

Also make some generated keys non-permanent so that they're not added to the
keychain in the first place.

[monotouch-test] Be more descriptive and clean up stuff added to the keychain.

---

tools/mtouch/Application.mtouch.cs
tools/mtouch/Target.mtouch.cs

This broke with 1582bf47cc272640973cbe6933834b2debb80769 and cause the
frameworks to be nested under another `Frameworks` directory.
See https://github.com/xamarin/xamarin-macios/issues/10382
Backport of #10400

[d16-9] [mtouch] Fix embedding Mono (and Xamarin) as frameworks. Fixes #10382

---

tools/devops/automation/templates/build/build.yml

If we set the variables as output variables they are not accessible by
the bash scripts resulting in a warning. This is a revert, all other are output vars and should be used the way they are.

[CI][VSTS] Set to no output vars back to be in the env.

---

msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ArchiveTaskBase.cs
msbuild/Xamarin.iOS.Tasks.Core/Tasks/ArchiveTaskBase.cs

Xamarin.Mac was already simplified for dSYM in a previous PR.
Additional sharing will require to determine what Catalyst needs.

[msbuild] Share more code between XI and XM Archive tasks

---

tools/devops/automation/templates/build/build.yml

If we set the variables as output variables they are not accessible by
the bash scripts resulting in a warning. This is a revert, all other are output vars and should be used the way they are.\n\nBackport of #10515

[d16-9] [CI][VSTS] Set to no output vars back to be in the env.

---

tools/devops/automation/templates/build/build.yml

Just executed if:
* succeeded - previous step that installs the plugin.
* we do want to sign pkgs
* we are not a pr.
Contains is used because 'eq' is buggy in certain hosts.

[CI][VSTS] Do not use ESRP when no pkgs is present or in a PR.

---

.github/workflows/backport-trigger.yml

I updated the backport bot code to allow the use of a fork, but the default is false to minimize the impact in other teams.

[Actions] Backports should use forks.

---

tools/devops/automation/templates/build/build.yml

Just executed if:
* succeeded - previous step that installs the plugin.
* we do want to sign pkgs
* we are not a pr.
Contains is used because 'eq' is buggy in certain hosts.
Backport of #10516

[d16-9] [CI][VSTS] Do not use ESRP when no pkgs is present or in a PR.

---

tools/devops/automation/templates/build/build.yml

Just executed if:
* succeeded - previous step that installs the plugin.
* we do want to sign pkgs
* we are not a pr.
Contains is used because 'eq' is buggy in certain hosts.
Backport of #10516

[xcode12.3] [CI][VSTS] Do not use ESRP when no pkgs is present or in a PR.

---

tools/devops/automation/templates/build/build.yml

If we set the variables as output variables they are not accessible by
the bash scripts resulting in a warning. This is a revert, all other are output vars and should be used the way they are.
Backport of #10515

[xcode12.3] [CI][VSTS] Set to no output vars back to be in the env.

---

tools/devops/automation/templates/build/build.yml

If we set the variables as output variables they are not accessible by
the bash scripts resulting in a warning. This is a revert, all other are output vars and should be used the way they are.
Backport of #10515

[xcode12.4] [CI][VSTS] Set to no output vars back to be in the env.

---

tools/devops/automation/templates/build/build.yml

Just executed if:
* succeeded - previous step that installs the plugin.
* we do want to sign pkgs
* we are not a pr.
Contains is used because 'eq' is buggy in certain hosts.
Backport of #10516

[xcode12.4] [CI][VSTS] Do not use ESRP when no pkgs is present or in a PR.

---

.github/workflows/backport-trigger.yml

I updated the backport bot code to allow the use of a fork, but the default is false to minimize the impact in other teams.
Backport of #10530

[d16-9] [Actions] Backports should use forks.

---

dotnet/SingleProject.md
dotnet/targets/Xamarin.Shared.Sdk.targets
msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileAppManifestTaskBase.cs
msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DetectSigningIdentityTaskBase.cs
msbuild/Xamarin.Shared/Xamarin.Shared.targets
msbuild/Xamarin.iOS.Tasks.Core/Tasks/CompileAppManifestTaskCore.cs
tests/dotnet/MySingleView/Info.plist
tests/dotnet/MySingleView/MySingleView.csproj
tests/dotnet/UnitTests/DotNetUnitTests.csproj
tests/dotnet/UnitTests/ProjectTest.cs
tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/GeneratePlistTaskTests/GeneratePlistTaskTests_Core.cs

Our implementation of:
https://github.com/xamarin/xamarin-android/blob/051cad7972033b1b9c8b9fbea3be1b90c1c23fa9/Documentation/proposals/OneDotNetSingleProject.md
This adds the ability for a .NET 6 iOS project to look like:
```xml
<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup>
<TargetFramework>net6.0-ios</TargetFramework>
<ApplicationTitle>MyApp</ApplicationTitle>
<ApplicationId>com.companyname.myapp</ApplicationId>
<ApplicationVersion>1.0</ApplicationVersion>
</PropertyGroup>
</Project>
```
Also:
* Added a new test case.
* Added a bit of documentation.
Fixes https://github.com/xamarin/xamarin-macios/issues/10473.

[dotnet] Add support for some of the single-project MSBuild properties.

---

tools/devops/automation/templates/build/build.yml

The internal pool, for some reason, do not like the cred store. We need
this to fix the interaction with the maccore repo.
1. VSTS uses https
2. We need to set the pat and try no to modify all bash scripts.
We do so by changing the remote url of maccores git repo so that it
includes the pat.

[VSTS][CI] Fix issues with the internal pool and VSTS git usage.

---

tests/framework-test/iOS/framework-test-ios.csproj

This is part 1 of making framework-test build on Mac Catalyst.
Contributes to https://github.com/xamarin/xamarin-macios/issues/10440.

[tests] Use the 'Apple Developer' code signing key instead of 'iPhone Developer' for framework-test.

---

msbuild/Xamarin.Shared/Xamarin.Shared.targets

This is part 2 of making framework-test build on Mac Catalyst.
Contributes to https://github.com/xamarin/xamarin-macios/issues/10440.

[msbuild] Fix computing the frameworks directory for Mac Catalyst.

---

tools/devops/automation/scripts/GitHub.psm1

[CI][VSTS] Do not step over success statuses in rebuilds.

---

tools/devops/automation/scripts/GitHub.psm1

[d16-9] [CI][VSTS] Do not step over success statuses in rebuilds.

---

tools/linker/MonoTouch.Tuner/MonoTouchProfile.cs

This is required for Mac Catalyst, where Xamarin.iOS is a special case.

[mtouch] Hardcode 'Xamarin.iOS' as an SDK assembly for the linker.

---

tools/devops/automation/scripts/GitHub.psm1

[xcode12.3] [CI][VSTS] Do not step over success statuses in rebuilds.

---

tools/devops/automation/scripts/GitHub.psm1

[xcode12.4] [CI][VSTS] Do not step over success statuses in rebuilds.

---

msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ResolveFrameworksBase.cs
tests/xcframework-test/iOS/xcframework-test-ios.csproj
tests/xharness/Harness.cs

This fixes the xcframework-test on Mac Catalyst.
Contributes to https://github.com/xamarin/xamarin-macios/issues/10440.

[msbuild/tests] Fix support for XCFrameworks for Mac Catalyst.

---

dotnet/targets/Xamarin.Shared.Sdk.targets

Fixes: https://github.com/xamarin/xamarin-macios/issues/10575
Running `dotnet build -t:Run` on a new project fails with:
Xamarin.Shared.Sdk.targets(692,3): error MSB4018: The "GetMlaunchArguments" task failed unexpectedly.
Xamarin.Shared.Sdk.targets(692,3): error MSB4018: System.IO.DirectoryNotFoundException: Could not find a part of the path '/Users/jopepper/src/net6-samples/HelloiOS/bin/Debug/net6.0-ios/ios-x64/HelloiOS.app\Info.plist'.
Xamarin.Shared.Sdk.targets(692,3): error MSB4018:    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
Xamarin.Shared.Sdk.targets(692,3): error MSB4018:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
Xamarin.Shared.Sdk.targets(692,3): error …

[.NET 6] make sure Run target depends on Build

---

src/MediaToolbox/MTAudioProcessingTap.cs
src/avfoundation.cs
src/corebluetooth.cs
src/foundation.cs
src/generator.cs
src/uikit.cs
tests/introspection/ApiAvailabilityTest.cs
tests/introspection/Mac/introspection-mac.csproj
tests/introspection/dotnet/iOS/introspection.csproj
tests/introspection/dotnet/tvOS/introspection.csproj
tests/introspection/iOS/introspection-ios.csproj

Stop hardcoding minimum OS versions, we have this information already in
source format, so use that.
This also showed that we had a few unnecessary availability attributes, so I
removed those.

[introspection] Stop hardcoding minimum OS versions.

---

dotnet/.gitignore
dotnet/Makefile

Don't use install-location to specify where files should be installed, because
our notarization process replaces this value in the pkg manifest with the root
directory (without updating anything else), with the result that notarized
packages tries to install files in the wrong location.
Instead specify the full path for each individual file, so that the
install-location can be the root directory (and thus the notarization process
won't corrupt the package).

[dotnet] Don't use install-location in pkgs.

---

msbuild/Xamarin.iOS.Tasks.Core/Tasks/ArchiveTaskBase.cs

Check if the .app has a Frameworks directory before trying to iterate over any
*.framework directories it may have.
Backport of #10378

[d16-9] [msbuild] Don't try to find frameworks in a directory that doesn't exist.

---

Make.config
src/coreimage.cs
src/intents.cs
tests/introspection/iOS/iOSApiProtocolTest.cs
tests/introspection/iOS/iOSApiSelectorTest.cs

Moving to macOS 11.x (BigSur) requires us to bump the minimum/tested
version of simulators to the oldest supported by the required OS.
This means iOS 11.4, tvOS 11.4 and watchOS 5.0 (with iOS 12).
xharness needs to be updated in order for watchOS 5.0, which needs
series 3, to work properly.
Filed as https://github.com/xamarin/xamarin-macios/issues/10593

[xcode12.5] Bump minimum version of simulators (as required for BigSur)

---

NuGet.config
mk/xamarin.mk

bump maccore for dependencies updates
* xamarin/maccore@b5332e51dd Remove dependency on XmlDocSync repo/tools (#2391)
* xamarin/maccore@e2a8db0a93 Update NuGet.config to enforce a single feed (#2372)
* xamarin/maccore@1a2648bfea Keychain file computed incorrectly on Big Sur (#2388)
* xamarin/maccore@de616ca53e [mlaunch] Fix dependencies for Xcode 12.5 beta 1 (#2387)
* xamarin/maccore@e93375583c [Actions] Fix rebase trigger.
Diff: https://github.com/xamarin/maccore/compare/0dfeb85ff607f6d0bb4063de4f4b91c4161b8e55..b5332e51dd2c93a79f770139038304b7847d41bb

[main] Update NuGet feed

---

tests/monotouch-test/Security/KeyChainTest.cs
tests/monotouch-test/Security/RecordTest.cs

'GenericPassword' keychain items are unique by their Service+Account
properties [1]. This means that changing the Label property will not create a
different 'GenericPassword', which has a few consequences:
* It's possible to filter (and try to delete) using the Label property.
* It's possible to try to delete a 'GenericPassword' item, and have that
deletion attempt fail with 'no item found', and then subsequently trying to
add the same item will fail with a DuplicateItem, because the deletion
was filtered using the Label property.
The change I've made is to:
* Make the Label property much more descriptive, and unique per process. This
makes it easier to figure out where things come from in the Keychain Access
app.
* Make the Service property unique per process. This way these tests are …

[d16-9] [monotouch-test] Rework big parts of KeyChainTest. Fixes #xamarin/maccore@2365.

---

dotnet/targets/Xamarin.Shared.Sdk.targets

This allows for unnecessary code to be trimmed by default in an app. See https://github.com/dotnet/runtime/pull/47999.

Default InvariantGlobalization in Xamarin IOS

---

tools/devops/automation/templates/build/build.yml

[CI] Nugets should not stop the build.

---

tools/devops/automation/templates/build/build.yml

The issue is due to the fact that the uninstall ceerts has an always
condition, that means that it gets executed and results in a success.
Because is a batch project and not a state machine.. the following steps
believe that everything was a success making the steps execute.
For ref: https://github.com/xamarin/yaml-templates/blob/main/uninstall-certificates/v1.yml

[CI][VSTS] Do not run tests if the build fails.

---

src/coreimage.cs
src/intents.cs
tests/introspection/iOS/iOSApiProtocolTest.cs
tests/introspection/iOS/iOSApiSelectorTest.cs

Once you have BigSur installed, to work with xcode12.5, then you
need to bump the minimum simulator versions (to 11.4) and this picked up
a few mistakes in availability and when checking protocol conformance
The bots won't run into those issues, as long as `xcode12.5` is not
merged or while they run on macOS Catalina, but it's nice to have green
tests locally :)
Subset of 8513316015b1fca1d59f0ec47072befd2443acba already in `xcode12.5`

[main] Fix running introspection on iOS 11.4 simulators

---

msbuild/Xamarin.Mac.Tasks.Core/Tasks/DetectSdkLocationsTaskBase.cs
msbuild/Xamarin.iOS.Tasks.Core/Tasks/CompileAppManifestTaskCore.cs
msbuild/Xamarin.iOS.Tasks.Core/Tasks/DetectSdkLocationsTaskBase.cs
msbuild/Xamarin.iOS.Tasks.Core/Tasks/ResolveNativeWatchAppTaskBase.cs
tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/GeneratePlistTaskTests/GeneratePlistTaskTests_iOS.cs
tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/GeneratePlistTaskTests/GeneratePlistTaskTests_tvOS.cs
tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/GeneratePlistTaskTests/GeneratePlistTaskTests_watchOS.cs
tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/IBToolTaskTests.cs

This requires bumping Xamarin.MacDev.
* xamarin/Xamarin.MacDev@02d6d05 [Xamarin.MacDev] Add an AppleSdkVersion struct which replaces IPhoneSdkVersion and MacOSXSdkVersion. (#87)
* xamarin/Xamarin.MacDev@e7ec7ef [Xamarin.MacDev] Fail gracefully if trying to grab a PList entry from a file that doesn't exist. (#86)
Diff: https://github.com/xamarin/Xamarin.MacDev/compare/fae0237704b792004adf592d8c9038a9d46aafff..02d6d05be3506c89a3b4fa8a8ceb7f33712a8f46

[msbuild] Bump Xamarin.MacDev and use AppleSdkVersion instead of MacOSXSdkVersion/IPhoneSdkVersion.

---

tools/devops/automation/templates/build/build.yml

The issue is due to the fact that the uninstall ceerts has an always
condition, that means that it gets executed and results in a success.
Because is a batch project and not a state machine.. the following steps
believe that everything was a success making the steps execute.
For ref: https://github.com/xamarin/yaml-templates/blob/main/uninstall-certificates/v1.yml
Backport of #10623

[xcode12.4] [CI][VSTS] Do not run tests if the build fails.

---

tools/devops/automation/templates/build/build.yml

The issue is due to the fact that the uninstall ceerts has an always
condition, that means that it gets executed and results in a success.
Because is a batch project and not a state machine.. the following steps
believe that everything was a success making the steps execute.
For ref: https://github.com/xamarin/yaml-templates/blob/main/uninstall-certificates/v1.yml
Backport of #10623

[xcode12.5] [CI][VSTS] Do not run tests if the build fails.

---

tools/devops/automation/templates/build/build.yml

The issue is due to the fact that the uninstall ceerts has an always
condition, that means that it gets executed and results in a success.
Because is a batch project and not a state machine.. the following steps
believe that everything was a success making the steps execute.
For ref: https://github.com/xamarin/yaml-templates/blob/main/uninstall-certificates/v1.yml
Backport of #10623

[d16-9] [CI][VSTS] Do not run tests if the build fails.

---

msbuild/Xamarin.Shared/Xamarin.Shared.props
msbuild/Xamarin.Shared/Xamarin.Shared.targets
msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets

In .NET Mac Catalyst will be a platform on the same level as iOS or tvOS, so
reflect this in the build logic by setting _PlatformName to 'MacCatalyst'.
This makes the build logic a lot simpler for .NET.

[msbuild] Use '_PlatformName' == 'MacCatalyst' instead of '_IsMacCatalyst'.

---

dotnet/targets/Xamarin.Shared.Sdk.targets

The session id was missing when trying to read items from _AssembliesToAOT.items, which breaks the build from Windows

[dotnet] Execute ReadItemsFromFile remotely

---

tools/common/Driver.cs

* Store verbosity in only one place (ErrorHelper.Verbosity).
* Initialize to the default value in the Driver's static constructor.
There was an issue where the default verbosity wasn't set everywhere, because
ErrorHelper.Verbosity was only set when Driver.Verbosity was assigned, which
wouldn't happen if no -v/-q was passed on the command line. The result would
be that any files in $HOME that specifies a default verbosity would not be
taken into account in ErrorHelper.

[tools] Fix issue with default verbosity.

---

tools/mmp/driver.cs

Change the code to look in the right place for pig-config files.
`FrameworkLibDirectory` is:
https://github.com/xamarin/xamarin-macios/blob/4b0fd5529cb7728aaf6946be37e6080ee29e3874/tools/common/Driver.cs#L783-L786
and `GetProductSdkDirectory` is:
https://github.com/xamarin/xamarin-macios/blob/4b0fd5529cb7728aaf6946be37e6080ee29e3874/tools/common/Driver.cs#L864
and that's where we install `mono-2.pc`:
https://github.com/xamarin/xamarin-macios/blob/4b0fd5529cb7728aaf6946be37e6080ee29e3874/builds/Makefile#L699-L700
given that `XAMARIN_MACOS_SDK` is:
https://github.com/xamarin/xamarin-macios/blob/4b0fd5529cb7728aaf6946be37e6080ee29e3874/Make.config#L317
Backport of #9105

[xcode12.4] [mmp] Use the right pkg-config directory.

---

tools/dotnet-linker/Steps/GenerateMainStep.cs

The default was changed to be hybrid suspend, and due to bugs in Mono that
crashes:
https://github.com/dotnet/runtime/issues/47121
In the meantime we can go back to the older GC mode until Mono has fixed any
issues with the hybrid suspend mode.

[dotnet] Force the GC mode to be preemptive.

---

tools/common/Assembly.cs
tools/dotnet-linker/Steps/GatherFrameworksStep.cs

This way we link with any system frameworks referenced by P/Invokes.

[dotnet-linker] Compute per-assembly linker flags.

---

src/generator-filters.cs
src/generator.cs

This does not have a huge impact (e.g. size) by itself. However it helps
to find duplicates in non-generated (manual) bindings and that will (in
future PR) remove them, which means less (manual) work to update the
attributes for net6.
Before (iOS)
> [FAIL] Duplicates: 555 API with members duplicating type-level attributes
After (iOS)
> [FAIL] Duplicates : 64 API with members duplicating type-level attributes
Notes
* The above test will be added in a PR, one that has 0 failure :)
* Ideally the duplicated entries would be removed from binding files (as
they are not needed, just noise) but that more work and a common source
of merge conflicts
* Some dupes exists due to protocol members inlining (and we might want
to fix this later)
* Bots are not produce the generator diff right now. Here's …

[generator] Reduce the number of duplicate availability attributes in generated code

---

.gitignore
tools/devops/Makefile
tools/devops/build-samples.csx
tools/devops/build-samples.yml
tools/devops/provision-shared.csx
tools/devops/provision-xcode.csx
tools/devops/provision-xcode.csx.in
tools/devops/utils.csx

Sample tests are now running again https://dev.azure.com/xamarin/internal/_build/results?buildId=35481&view=results I’ll fix actual sample issues in another PR

[main] Get sample tests running again

---

Make.config
builds/.gitignore
builds/Makefile
builds/package-download/.gitignore
builds/package-download/download-packages.proj

These will soon be used to build a .NET version of libxamarin (we need the
dylibs shipped with the runtime packs to link libxamarin.dylib).
We also write out the version of the runtime packs
(BundledNETCorePlatformsPackageVersion) so that we can use the version later
in our Makefiles.

[builds] Download the runtime packs for our platforms.

---

tests/monotouch-test/Security/CertificateTest.cs
tests/monotouch-test/Security/KeyTest.cs
tests/monotouch-test/Security/RecordTest.cs

This fixes at least some variations of this failure:
* Protocol_17579: Add
Expected: Success
But was: DuplicateItem
In this test we try to delete any existing keychain items, but it seems that
may fail if the keychain item in question was created by a different app, in
which case we wouldn't have permission to delete it (but adding a new one
would still fail with a duplicate item error). Cleaning up any added keychain
items by the same test (and process) that added them avoids the permissions
problem.
Also clean up in other tests as well, to avoid filling up our keychain with
test stuff.
This PR is best reviewed by ignoring whitespace.

[monotouch-test] Clean up keychain items after test completions.

---

dotnet/targets/Xamarin.Shared.Sdk.targets
msbuild/Xamarin.Shared/Xamarin.Shared.props

In dotnet/runtime#47083, we are introducing the UseNativeHttpHandler feature switch. This change sets the default to true for devices.

Set UseNativeHttpHandler project default

---

tools/devops/automation/templates/build/build.yml

We do have continueOnError in the required steps, is enough to ensure tests are ran when they should.

[CI][VSTS] continueOnError is the correct way.

---

tools/devops/automation/scripts/GitHub.psm1
tools/devops/automation/templates/build/build.yml
tools/devops/automation/templates/build/download-artifacts.yml
tools/devops/automation/templates/build/publish-html.yml
tools/devops/automation/templates/build/stage.yml
tools/devops/automation/templates/build/upload-vsdrops.yml

Bring back the status of the API diff for PRs and commits. The comment will look similar to [this](https://github.com/xamarin/xamarin-macios/commit/816b11f3c981189872caaaffae471959e31104df#commitcomment-47300105) with the diff that a message has been added and a title for the pkgs to make the message to have a nicer format.
API diff can be accessed via vsdrops for team members or via gists. The [gist](https://gist.github.com/vs-mobiletools-engineering-service2/82268da7cd3786afa79a9d2e8baef5bb) is an example of what a user will see.
Backport of #10682

[xcode12.5] [CI][VSTS] Bring back the API diff from stable

---

tools/devops/automation/scripts/GitHub.psm1
tools/devops/automation/templates/build/build.yml
tools/devops/automation/templates/build/download-artifacts.yml
tools/devops/automation/templates/build/publish-html.yml
tools/devops/automation/templates/build/stage.yml
tools/devops/automation/templates/build/upload-vsdrops.yml

Bring back the status of the API diff for PRs and commits. The comment will look similar to [this](https://github.com/xamarin/xamarin-macios/commit/816b11f3c981189872caaaffae471959e31104df#commitcomment-47300105) with the diff that a message has been added and a title for the pkgs to make the message to have a nicer format.
API diff can be accessed via vsdrops for team members or via gists. The [gist](https://gist.github.com/vs-mobiletools-engineering-service2/82268da7cd3786afa79a9d2e8baef5bb) is an example of what a user will see.
Backport of #10682

[xcode12.4] [CI][VSTS] Bring back the API diff from stable

---

tools/devops/automation/scripts/GitHub.psm1
tools/devops/automation/templates/build/build.yml
tools/devops/automation/templates/build/download-artifacts.yml
tools/devops/automation/templates/build/publish-html.yml
tools/devops/automation/templates/build/stage.yml
tools/devops/automation/templates/build/upload-vsdrops.yml

Bring back the status of the API diff for PRs and commits. The comment will look similar to [this](https://github.com/xamarin/xamarin-macios/commit/816b11f3c981189872caaaffae471959e31104df#commitcomment-47300105) with the diff that a message has been added and a title for the pkgs to make the message to have a nicer format.
API diff can be accessed via vsdrops for team members or via gists. The [gist](https://gist.github.com/vs-mobiletools-engineering-service2/82268da7cd3786afa79a9d2e8baef5bb) is an example of what a user will see.
Backport of #10682

[d16-9] [CI][VSTS] Bring back the API diff from stable

---

tools/devops/automation/templates/build/build.yml

We do have continueOnError in the required steps, is enough to ensure tests are ran when they should.
Backport of #10693

[d16-9] [CI][VSTS] continueOnError is the correct way.

---

tools/devops/automation/templates/build/build.yml

We do have continueOnError in the required steps, is enough to ensure tests are ran when they should.
Backport of #10693

[xcode12.5] [CI][VSTS] continueOnError is the correct way.

---

Makefile

The name of the branch says it all.
Backport of #10692

[xcode12.5] [Makefile] Why copy-paste when you can 'make fix-xcode-select'

---

msbuild/Messaging/Xamarin.Messaging.Build.Contracts/Xamarin.Messaging.Build.Contracts.csproj
msbuild/Xamarin.MacDev.Tasks/Xamarin.MacDev.Tasks.csproj
msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Tasks.Windows.csproj
msbuild/Xamarin.iOS.Tasks/Xamarin.iOS.Tasks.csproj

Changes the HintPath to the Messaging assembly to use OutputPath instead, otherwise the build fails when that property is different than `bin\$(Configuration)\netstandard2.0`

[dotnet] Fixes Xamarin.Messaging HintPath

---

msbuild/Directory.Build.props
msbuild/Xamarin.MacDev.Tasks/Tasks/AOTCompile.cs
msbuild/Xamarin.MacDev.Tasks/Tasks/CompileNativeCode.cs
msbuild/Xamarin.MacDev.Tasks/Tasks/EmbedProvisionProfile.cs
msbuild/Xamarin.MacDev.Tasks/Tasks/LinkNativeCode.cs

- We need to create output files for the AOTCompile task on Windows and copy the AOT Compiler to the Mac since it is part of a NuGet package that will not exist on the Mac
- The EmbedProvisionProfile task needs to be run remotely so the embedded.mobileprovision file is included in the app bundle
- When copying input files to the Mac for LinkNativeCode we should skip files that already exist on the Mac because those on Windows are empty. If we copy those we are essentially replacing the real files by the empty ones from Windows.

[dotnet] Fixes builds for iOS physical devices from Windows

---

src/CoreMedia/CMSampleBuffer.cs

Fixes this crash in monotouch-test:
Process terminated. A callback was made on a garbage collected delegate of type 'Xamarin.Mac!CoreMedia.CMSampleBuffer+CMSampleBufferInvalidateCallback::Invoke'.
Repeat 2 times:
--------------------------------
at CoreMedia.CMSampleBuffer.CMSampleBufferInvalidate(IntPtr)
--------------------------------
at CoreMedia.CMSampleBuffer.Invalidate()
at MonoTouchFixtures.CoreMedia.SampleBufferTest.SetInvalidateCallback()
at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean, Boolean)
at NUnit.Framework.Internal.Reflect.InvokeMethod(System.Reflection.MethodInfo, System.Object, System.Object[])
at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(NUnit.Framework.Internal.TestExecutionContext)
at …

[CoreMedia] Store delegate in static variable to prevent premature garbage collection.

---

src/Resources.resx
src/xlf/Resources.cs.xlf
src/xlf/Resources.de.xlf
src/xlf/Resources.es.xlf
src/xlf/Resources.fr.xlf
src/xlf/Resources.it.xlf
src/xlf/Resources.ja.xlf
src/xlf/Resources.ko.xlf
src/xlf/Resources.pl.xlf
src/xlf/Resources.pt-BR.xlf
src/xlf/Resources.ru.xlf
src/xlf/Resources.tr.xlf
src/xlf/Resources.zh-Hans.xlf
src/xlf/Resources.zh-Hant.xlf

This fixes an issue where a composed error message would show up in two lines:
BTOUCH : error BI1079: bgen: Do not know how to make a signature for System.Boolean*
in parameter `inventoryAbortResultCodeFound' from iOSBinding.Easy2ReadProtocolMessage.FromRawData
Leaving customers confused (https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1280923),
because they wouldn't see the second part of the error.
After the fix:
BTOUCH : error BI1079: bgen: Do not know how to make a signature for System.Boolean* in parameter `inventoryAbortResultCodeFound' from iOSBinding.Easy2ReadProtocolMessage.FromRawData
---
Before:
After:
On another note, we should probably do this for all our other warning/error messages as well.

[bgen] Remove trailing newlines from warning/error messages.

---

Make.config
dotnet/targets/Xamarin.Shared.Sdk.targets
mk/rules.mk
runtime/Makefile
runtime/monotouch-debug.m
runtime/monotouch-main.m
tools/common/Target.cs

This also means linking with the runtime packs from .NET instead of the mono archive
(thus we have one less reliance on the mono archive).
We're also using the Xamarin.iOS code for our macOS launch sequence now, since
(at least at first) we're only going to support self-contained .NET macOS apps
(so no need to support a system-installed runtime, which simplifies things a
bit).

[runtime] Build a .NET-specific libxamarin-dotnet[-debug].[a|dylib].

---

src/AudioUnit/AudioComponent.cs
src/GameKit/GameKit.cs
src/avfoundation.cs
src/devicecheck.cs
src/foundation.cs
tests/monotouch-test/AVFoundation/CaptureDeviceTest.cs
tests/xtro-sharpie/MacCatalyst-AVFoundation.todo
tests/xtro-sharpie/MacCatalyst-AddressBook.ignore
tests/xtro-sharpie/MacCatalyst-AddressBook.todo
tests/xtro-sharpie/MacCatalyst-AudioToolbox.todo
tests/xtro-sharpie/MacCatalyst-DeviceCheck.todo
tests/xtro-sharpie/MacCatalyst-Foundation.ignore
tests/xtro-sharpie/MacCatalyst-Foundation.todo
tests/xtro-sharpie/MacCatalyst-GameKit.todo
tests/xtro-sharpie/MacCatalyst-MetalPerformanceShaders.todo
tests/xtro-sharpie/MacCatalyst-UIKit.todo
tests/xtro-sharpie/common-MetalPerformanceShaders.ignore
tests/xtro-sharpie/common-UIKit.ignore
tests/xtro-sharpie/iOS-MetalPerformanceShaders.todo
tests/xtro-sharpie/iOS-UIKit.ignore
tests/xtro-sharpie/macOS-MetalPerformanceShaders.todo
tests/xtro-sharpie/tvOS-MetalPerformanceShaders.todo
tests/xtro-sharpie/tvOS-UIKit.ignore

xtro tests are based on Apple's header files and report as _unknown_
bindings to API that are not found in headers - Catalyst in this case.
Removing them is required so the applications can be submitted to the
AppStore.

[catalyst] Remove "unknown" API inside existing frameworks

---

tools/common/Frameworks.cs

Also set to 13.0 (first Catalyst version) any framework that existed
earlier in iOS.

[mtouch] Remove the non-catalyst frameworks from mtouch

---

Make.config

[d16-9] [apidiff] Bump api-diff with xcode12.4 release as it's new reference

---

runtime/monotouch-debug.m

This makes it so that it's possible to attach to the debugger by setting the
\_\_XAMARIN_DEBUG_HOSTS\_\_/\_\_XAMARIN_DEBUG_PORT\_\_ environment variables, without
the need for enabling a setting somewhere else (like in
Settings.bundle/Root.plist on mobile devices).

[runtime] Always enable debugging in .NET/macOS and .NET/Mac Catalyst in debug versions of libxamarin.

---

tools/devops/automation/templates/build/publish-html.yml

Example:
* Wrong - https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210226.4/4505964/APIDiff/;/mac-api-diff.html
* Correct - https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210226.4/4505964/apidiff/;/mac-api-diff.html

[CI][VSTS] VSDrops urls are case-sensitive.

---

runtime/monotouch-debug.m

Fix this compiler warning:
monotouch-debug.m:524:12: warning: unused variable 'monotouch_debug_enabled' [-Wunused-variable]
NSString *monotouch_debug_enabled;

[runtime] Fix a compiler warning.

---

msbuild/Xamarin.Shared/Xamarin.Shared.props

This way we don't end up forcing Mac Catalyst apps to be signed (because if
the computed platform is 'iPhone', we enforce signing).

[msbuild] Don't compute the platform for Mac Catalyst.

---

src/Security/SslContext.cs
tests/introspection/ApiAvailabilityTest.cs

and not just methods even if we are generating them on both [1]
That spotted a single error inside `src/Security/SslContext.cs`
which this PR also fix. IOW there's no point in saying the API
was (a long time ago) available since our code to call it was
removed.
[1] which is something we should not need to do on .net since
* the compiler-based tooling does not need it on the getter/setter
* other tools needs to be updated (so it won't break any existing
use case)

[tests][intro] Run availability tests on properties too

---

tools/devops/automation/build-pipeline.yml
tools/devops/automation/templates/devices/build.yml
tools/devops/automation/templates/devices/stage.yml

Provisionator hits the login.keychain when looking for the github token credential used to download the provisioning profiles from dl.internalx.com during CI.
Provisionator first checks the environment before asking the keychain for the credential, so this change introduces the credential (backed by keyvault) as an envvar before invoking provisionator.

[CI] Circumvent login keychain with envvars

---

Make.config
runtime/launcher.m

This required fixing a couple of compiler warnings in code that's now compiled
with more warnings + warnings-as-errors enabled:
launcher.m:188:48: error: implicit conversion changes signedness: 'int' to 'unsigned long' [-Werror,-Wsign-conversion]
argv = (char **) malloc (sizeof (char *) * (n + 1));
~  ~~^~~
launcher.m:609:67: error: implicit conversion changes signedness: 'int' to 'unsigned long' [-Werror,-Wsign-conversion]
char **new_argv = (char **) malloc (sizeof (char *) * (new_argc + 1 /* null terminated */));
~  ~~~~~~~~~^~~
CFLAGS will:
* Enable all warnings (`-Wall`).
* Make all warnings errors.
* Enable a few more warnings not enabled with -Wall (`-Wconversion -Wdeprecated -Wuninitialized`).
* Enable strong stack protection (`-fstack-protector-strong`).
* Make it possible to use …

Use our [OBJC_]CFLAGS when compiling code for macOS.

---

tools/apidiff/.gitignore
tools/apidiff/Makefile
tools/devops/automation/scripts/GitHub.psm1
tools/devops/automation/templates/build/publish-html.yml

This is now possible since our reference is now `d16-9` which has (very
early versions of) the Xamarin.MacCatalyst (and Xamarin.iOS stubs)
assemblies.
This will become more useful when
1. bots resume the generation of commit-by-commit API diff; and
2. a real baseline is defined for the catalyst API coverage

[catalyst][tools] Add Xamarin.MacCatalyst to API diff

---

tools/devops/automation/templates/build/publish-html.yml

Example:
* Wrong - https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210226.4/4505964/APIDiff/;/mac-api-diff.html
* Correct - https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210226.4/4505964/apidiff/;/mac-api-diff.html
Backport of #10740

[xcode12.5] [CI][VSTS] VSDrops urls are case-sensitive.

---

tools/devops/automation/templates/build/publish-html.yml

Example:
* Wrong - https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210226.4/4505964/APIDiff/;/mac-api-diff.html
* Correct - https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210226.4/4505964/apidiff/;/mac-api-diff.html
Backport of #10740

[xcode12.4] [CI][VSTS] VSDrops urls are case-sensitive.

---

tools/devops/automation/templates/build/publish-html.yml

Example:
* Wrong - https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210226.4/4505964/APIDiff/;/mac-api-diff.html
* Correct - https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210226.4/4505964/apidiff/;/mac-api-diff.html
Backport of #10740

[d16-9] [CI][VSTS] VSDrops urls are case-sensitive.

---

dotnet/Makefile
dotnet/package/Microsoft.NET.Workload.MacCatalyst/package.csproj
dotnet/package/Microsoft.NET.Workload.iOS/package.csproj
dotnet/package/Microsoft.NET.Workload.macOS/package.csproj
dotnet/package/Microsoft.NET.Workload.tvOS/package.csproj
dotnet/package/microsoft.workloads.csproj

Fixes: https://github.com/xamarin/xamarin-macios/issues/10620
I have a prototype where I figured out how Maui would consume the iOS &
Android workloads:
https://github.com/jonathanpeppers/maui-workload
One issue I ran into was there isn't a `Microsoft.NET.Workload.iOS`
package on the NuGet feed:
<add key="xamarin" value="https://pkgs.dev.azure.com/azure-public/vside/_packaging/xamarin-impl/nuget/v3/index.json" />
We will also need these packages to insert them in the dotnet/installer
repo, when they are ready for us to do "real" insertions for .NET 6.
To make this work, I mostly had to create a `package.csproj` for the
workload packs and fix up the `Makefile`.
Now I get additional `.nupkg` files produced in:
% ls _build/nupkgs | grep Microsoft.NET.Workload …

[dotnet] produce .nupkg files for Workload packs

---

src/passkit.cs

Clicked merge too fast (that green things was API diff, not test results,
need more caffeine).
note: API present in headers but without version annotations.

[passkit] Fix intro tests

---

src/generator-typemanager.cs
src/generator.cs
tests/cecil-tests/MarshalAsTest.cs

The default marshalling size for characters in .NET is a single byte, and that
is potentially lossy (and causes tests to fail for non-ascii characters when using CoreCLR).

Turns out we need MarshalAs for characters as well.

---

src/GameKit/GameKit.cs
src/gamekit.cs
tests/xtro-sharpie/iOS-GameKit.todo
tests/xtro-sharpie/macOS-GameKit.todo
tests/xtro-sharpie/tvOS-GameKit.todo
tests/xtro-sharpie/watchOS-GameKit.todo

note: `FriendsList` used in the new API based on the category name as
the _usual_ name caused conflicts with existing async signatures.

[gamekit] Update for xcode12.5 beta 3

---

tools/dotnet-linker/Steps/GenerateMainStep.cs

We're now building the .NET version of libxamarin referencing the .NET version
of libmono, which means we don't need this workaround anymore.

[dotnet] We shouldn't need the workaround for mono_config_parse_memory anymore.

---

tests/monotouch-test/CoreMedia/BlockBufferTest.cs
tests/monotouch-test/Photos/LivePhotoEditingContextTest.cs

Assembly.GetType works differently between CoreCLR and Mono for nested types:
Mono accepts both '/' and '+' as the character separating the declaring type
from the nested type, while CoreCLR only accepts '+'.
So just switch to '+', since that works everywhere.

[tests] Adjust Assembly.GetType calls to find nested types due to different behavior in CoreCLR.

---

Make.config
src/Makefile

This way we can use C# 9 in any code platform code specific to .NET.

Build the .NET version of our platform assemblies with csc from .NET

---

msbuild/Xamarin.MacDev.Tasks.Core/Xamarin.MacDev.Tasks.Core.csproj

Code shared between msbuild and mtouch/mmp needs to share the
localization strings, otherwise the exception being thrown is of no help
to solve the issue.
THis happened if a wrong path was given for an `.xcframework` and
`FileCopier` reported an `MT1022` error.
Reference (not a fix for) https://github.com/xamarin/xamarin-macios/issues/10774

[msbuild] Fix localization when the error code is shared with mtouch/mmp

---

src/generate-type-forwarders/Program.cs

* Types can be `sealed`
* Types can be `static` (when both `sealed` and `abstract`)
* Events can be `static`
* Do not add `virtual` members to `sealed` types (fix `CS0549` errors)

[generate-type-forwarders] Fix stubs generation

---

src/Makefile

Silence warnings for both legacy and dotnet builds
```
build/maccatalyst/reference/Xamarin.iOS.cs(8014,68): warning CS0108: 'ABPeoplePickerNavigationController.Delegate' hides inherited member 'UINavigationController.Delegate'. Use the new keyword if hiding was intended.
build/maccatalyst/reference/Xamarin.iOS.cs(29868,37): warning CS0114: 'HKWorkoutType.Identifier' hides inherited member 'HKObjectType.Identifier'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword.
build/maccatalyst/reference/Xamarin.iOS.cs(17769,54): warning CS0108: 'CPTemplateApplicationScene.Delegate' hides inherited member 'UIScene.Delegate'. Use the new keyword if hiding was intended.
build/maccatalyst/reference/Xamarin.iOS.cs(17626,63): warning CS0108: …
```

[generate-type-forwarders] Silence build warnings

---

dotnet/Makefile

I noticed the new templates did not actually work from the installer
unless I did:
% sudo mv \
/usr/local/share/dotnet/template-packs/Microsoft.iOS.Templates.14.4.100-ci.main.1180+sha.bccef33d3.nupkg \
/usr/local/share/dotnet/template-packs/Microsoft.iOS.Templates.14.4.100-ci.main.1180.nupkg
I checked other templates like Android or ASP.NET, and they do not
currently have a hash like `+sha.bccef33d3` in the file name.
To fix this problem, I updated the file in the installers so we now
remove the `+sha.bccef33d3` portion from file name:
$(subst +$(NUGET_BUILD_METADATA),,$(notdir $(TEMPLATE_PACKS_$(4))))
I also found the `Microsoft.iOS.Bundle.*.zip` did not contain
`template-packs` at all, so I fixed this as well.

[dotnet] remove +sha from templates in installers

---

runtime/delegates.t4
runtime/trampolines-invoke.m
src/ObjCRuntime/Runtime.cs

The ctor we just called called it already.
Also, the static registrar doesn't have this call, so the dynamic registrar
shouldn't need it either.

[registrar] Remove redundant call to xamarin_register_nsobject from the dynamic registrar.

---

builds/Makefile

(Found while rebasing https://github.com/xamarin/xamarin-macios/pull/10115)
Currently, if building the mono sdks from source, we don't actually try to build the mac catalyst sdk, but we rely on its presence to do the install, which is problematic if we're not in download mode. Now package it like we do for ios & mac packages in that case. Also adapted MacCatalyst assembly fix to work if we build from source instead of supposing we work from a downloaded package.

Fix building Mono MacCatalyst sdk from source

---

runtime/delegates.t4
runtime/exports.t4
runtime/monotouch-main.m
runtime/runtime.m
src/ObjCRuntime/Runtime.cs

Any performance difference will be neglible compared to running the GC, so
there's no compelling reason to use the embedding API.
This makes things a bit easier with CoreCLR, since the new code works there too.
This also required a few changes in delegates.t4 to make code generation for
functions without arguments work correctly.

[runtime] Call into managed code to call GC.Collect instead of using embedding API.

---

runtime/trampolines-invoke.m
src/Foundation/NSObject2.cs
tools/common/StaticRegistrar.cs

I don't see why we should avoid calling xamarin_create_managed_ref from
NSObject's managed code, and then immediately call xamarin_create_managed_ref
upon return from NSObject's managed code.
This code is old ([1]), and from my reading of it, there's no specific reason
it was done this way.
So simplify the logic to call xamarin_create_managed_ref from a single place
(NSObject's managed code).
[1]: https://github.com/xamarin/maccore/commit/e59c45d3f9408d2b61f47ae90d126612fbb6351b

[runtime] Simplify calls to xamarin_create_managed_ref.

---

src/CoreFoundation/CFStream.cs

Fixes this fatal error at runtime:
> A callback was made on a garbage collected delegate of type 'Xamarin.Mac!CoreFoundation.CFStream+CFStreamCallback::Invoke'.

[CoreFoundation] Fix collected delegate in CFStream.

---

tests/xharness/AppBundleLocator.cs

Sometimes msbuild wants to restore packages during this process, which may
take a while.
Hopefully fixes errors like this:
Harness exception for 'Tests for C6353E8B-BFDA-4F54-93D9-FF0F838BF8EE': System.Exception: Unable to evaluate the property OutputPath.
at Xharness.AppBundleLocator.GetPropertyByMSBuildEvaluationAsync (System.Xml.XmlDocument csproj, System.String projectPath, System.String evaluateProperty, System.String dependsOnTargets, System.Collections.Generic.Dictionary`2[TKey,TValue] properties) [0x00327] in /Users/builder/azdo/_work/1/s/xamarin-macios/tests/xharness/AppBundleLocator.cs:109
at Xharness.AppBundleLocator.LocateAppBundle (System.Xml.XmlDocument projectFile, System.String projectFilePath, Microsoft.DotNet.XHarness.iOS.Shared.TestTarget target, System.String …

[xharness] Bump timeout to evaluate MSBuild properties by running msbuild.

---

tools/devops/automation/templates/build/stage.yml

The OneLocBuild requires a windows build agent. @mandel-macaque suggested that we change the configure build agent from ubuntu to windows since it should not need to be ubuntu. If the build does not complain, this will give us a great place to add the OneLocBuild task.

[Localization] Setting 'configure' to use Windows Build Agent

---

runtime/Makefile

Make variables can have dashes, which means we don't have to convert dashes in
rids to underscores to be able to compose variable names.
This speeds up make because now we don't have to execute hundreds of
subprocesses when parsing the makefile.
Before:
$ make -j16 > /dev/null && /usr/bin/time make && /usr/bin/time make && /usr/bin/time make
2.11 real         0.57 user         1.26 sys
2.15 real         0.57 user         1.28 sys
2.17 real         0.58 user         1.30 sys
After:
$ make -j16 > /dev/null && /usr/bin/time make && /usr/bin/time make && /usr/bin/time make
0.52 real         0.18 user         0.25 sys
0.52 real         0.18 user         0.25 sys
0.52 real         0.18 user         0.26 sys
So now it's ~4x faster (1.6s) for make to figure out there's nothing to do.

[runtime] Speed up make

---

runtime/runtime.m
runtime/trampolines-invoke.m
runtime/xamarin/runtime.h

Unify them into a single one (xamarin_print_all_exceptions), which takes the
GCHandle of the exception to create an NSString representation of.
This makes it easier to make this code work with CoreCLR.

[runtime] Simplify the various print_all_exceptions methods a bit.

---

runtime/exports.t4
runtime/mono-runtime.h.t4
runtime/monotouch-debug.h

This makes things a little bit easier to when starting work with CoreCLR.

[runtime] Move a few mono function declaration to the generated logic for mono function declarations instead of doing it manually.

---

Make.config
builds/Makefile
runtime/Makefile

It's been disabled for a while, which indicates that Apple has fixed the issue
on their side, and we don't need this code anymore.

[builds] Remove the code to optionally inject an x64 slice into our binaries.

---

runtime/runtime.m
runtime/xamarin/runtime.h
src/Foundation/NSObject2.cs
src/ObjCRuntime/Class.cs
src/ObjCRuntime/Runtime.cs
tests/xtro-sharpie/common-ObjCRuntime.ignore

* This is a straight forward port of native code to managed code, and
shouldn't have any significant side effects.
* Makes it possible to move more code from native to managed for
xamarin_create_managed_ref and xamarin_release_managed_ref in the future.

[runtime] Port the is_user_type function from native to managed code.

---

src/wkwebkit.cs

It hangs at `dealloc` time. THere's no documentation about the class
but it seems it might not be user-createable (even if that's uncommon
on classes where you can assign your own delegate)

[xcode12.5][webkit] Disable WKDownload init (default ctor)

---

runtime/Makefile
runtime/mono-runtime.m.t4

The diff might look a bit weird, because there's no changes specific to
CoreCLR - the difference is that we're in fact removing a special-case to link
with Mono: we used the DOTNET_$(rid)_LIBDIR variable to specify the directory
where to find libcoreclr, we now use DOTNET_CORECLR_$(rid)_LIBDIR when
building for CoreCLR, but that's handled by the default case, so no need to
add any special casing. We still override DOTNET_osx-<arch>_LIBDIR for MonoVM
(no change needed for that).
This also requires adding generated stubs for the Mono Embedding API when
building for CoreCLR, so that linking succeeds.

[runtime] Link the CoreCLR version of libxamarin with CoreCLR instead of Mono.

---

runtime/runtime.m
runtime/xamarin/runtime.h
src/Foundation/NSObject2.cs
src/ObjCRuntime/Runtime.cs

* Avoids a native->managed transition
* Avoids creating/destroying a GCHandle.
* Makes it possible to remove an argument from the call to
xamarin_release_managed_ref.
* Makes things easier for CoreCLR.

[runtime] Move the call to Runtime.UnregisterNSObject from native to managed code.

---

runtime/runtime.m
src/Foundation/NSObject2.cs

* Less poking into managed memory from native code.
* Makes things easier for CoreCLR support.

[runtime] Move setting the NSObject flags in xamarin_create_managed_ref from native to managed code.

---

runtime/runtime.m
runtime/xamarin/runtime.h
src/Foundation/NSObject2.cs

* We already switch to GC Safe mode anyway, so there were no benefits from
entering native code in a GC unsafe mode. In fact we used to switch to GC
Safe mode for every statement in xamarin_release_managed_ref, and now we can
execute everything in GC Safe mode without switching back and forth. This
also means there should be no difference in behavior.
* All parameters are blittable, so there's no extra marshalling cost.
* Easier for CoreCLR.

[runtime] Make xamarin_release_managed_ref a normal P/Invoke.

---

tools/devops/automation/templates/build/configure.yml

My recent PR added some things to the configure yaml that are incomplete and are breaking the CI.
I am adding the ContinueOnError to unblock the the CI.

[CI] Adding ContinueOnError to unblock the CI

---

dotnet/targets/Xamarin.Shared.Sdk.targets

- this property will be defined on single projects to use launch profiles capability required on VisualStudio
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1291515
When a single-project is loaded on VisualStudio, to enable the switch between target frameworks the LaunchProfiles capability need to be enabled. 
By default, it is enabled but this capability is removed by our SDKs because the HEAD projects (Android and iOS) does not use this IDE feature to display devices on the start button.
The _KeepLaunchProfiles property avoids that removal in order to have LaunchProfiles enabled on VisualStudio.
MAUI targets adds _KeepLaunchProfiles with the value true to enable it for single-project.

Avoids to remove the launch profiles capability when the _KeepLaunchProfiles property is true

---

runtime/delegates.t4
runtime/exports.t4
runtime/runtime.m
runtime/trampolines-invoke.m
runtime/xamarin/main.h
runtime/xamarin/runtime.h
src/Foundation/NSObject2.cs
src/ObjCRuntime/Runtime.cs
tools/common/StaticRegistrar.cs

Move the creation of an uninitialized NSObject from native to managed, which:
* Removes the need for the mono_object_new Embedding API.
* Removes one location where we write to managed memory from native code (to
write the handle + flags in the uninitialized NSObject).
* Makes things easier for CoreCLR.

[runtime] Move parts of NSObject creation from native to managed.

---

runtime/runtime.m

Our own functions support pointer-sized GCHandles, so this is one less place
to fix for CoreCLR.

[runtime] Use xamarin_gchandle_free instead of mono_gchandle_free.

---

dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets
dotnet/targets/Xamarin.Shared.Sdk.targets
tests/xharness/Harness.cs
tests/xharness/Jenkins/TestData.cs
tests/xharness/Jenkins/TestVariationsFactory.cs
tools/common/Application.cs
tools/common/Target.cs
tools/common/XamarinRuntime.cs
tools/dotnet-linker/LinkerConfiguration.cs
tools/dotnet-linker/dotnet-linker.csproj
tools/mmp/mmp.csproj
tools/mtouch/mtouch.csproj

Use a private property (prefixed with underscore) for now, until we can decide
on a better/general name.
Also add a variation to xharness to build monotouch-test with CoreCLR
(building works fine, but it crashes at startup, which is expected at this
point).

[dotnet] Add support for specifying the VM with the _XamarinRuntime property.

---

msbuild/Makefile

By creating a directory before trying to copy files into it.

[msbuild] Fix logic to copy windows files

---

runtime/exports.t4
runtime/runtime.m

Mono's way doesn't work with CoreCLR anyway.

[runtime] Resolve symlinks using API provided by NSString instead of Mono.

---

mk/quiet.mk
runtime/.gitignore
runtime/Makefile
runtime/coreclr-bridge.m
runtime/monotouch-main.m
runtime/monovm-bridge.m
runtime/xamarin/coreclr-bridge.h
runtime/xamarin/monovm-bridge.h
runtime/xamarin/runtime.h

This makes the CoreCLR launch sequence reach the xamarin_initialize method
before it runs into Mono Embedding API (and aborts).

[runtime] Move MonoVM-specific initialization to MonoVM-specific code.

---

runtime/runtime.m
src/ObjCRuntime/Runtime.cs

So that we can detect in managed code whether we're running with CoreCLR or
MonoVM.

[dotnet] Add an IsCoreCLR initialization flag.

---

dotnet/targets/Xamarin.Shared.Sdk.targets
msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ParseBundlerArgumentsTaskBase.cs
msbuild/Xamarin.Shared/Xamarin.Shared.targets
tools/dotnet-linker/LinkerConfiguration.cs

Add support for parsing --setenv from bundler arguments and passing them to
dotnet-linker so that the environment variables can be baked into the app at
launch (like they would be for mtouch/mmp).

[msbuild/dotnet] Add support for parsing --setenv from bundler arguments.

---

msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.ObjCBinding.CSharp.After.props
msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.ObjCBinding.CSharp.After.targets
msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Windows.props

- Fixed iOS Binding projects build in Windows 
- Fixing CoreiOSSdkDirectory definition for legacy project system

Fixes on iOS.Windows targets

---

tests/linker/ios/link sdk/LinkSdkRegressionTest.cs

The api does not longer allow you to pass a null ptr. Create a dummy
controller:
fixes https://github.com/xamarin/xamarin-macios/issues/10918

[Xcode12.5] Fix regression test not to crash. fixes #10918

---

src/uikit.cs

API was added in 14.5 not earlier.
fixes https://github.com/xamarin/xamarin-macios/issues/10920

[Xcode12.5] Add missing TV availability. #10920

---

runtime/coreclr-bridge.m
runtime/exports.t4
runtime/mono-runtime.h.t4
runtime/mono-runtime.m.t4
runtime/monotouch-main.m
runtime/monovm-bridge.m
runtime/runtime.m
runtime/xamarin/coreclr-bridge.h
runtime/xamarin/monovm-bridge.h
runtime/xamarin/runtime.h

We need to call coreclr_initialize/monovm_initialize at startup, so do that.
This is a partial implementation, in that we're not setting all the properties
that we should, and also the PINVOKE_OVERRIDE callback is not doing everything
it should either yet.
Ref: #10504.

[runtime/dotnet] Call coreclr_initialize/monovm_initialize at startup.

---

tools/devops/Makefile

The rule is needed to run the tests on older macs.

[CI] Add missing rule to generate the provisionator deps on older macs.

---

runtime/exports.t4
runtime/mono-runtime.m.t4
runtime/runtime.m

This also means that we don't have to generate CoreCLR wrappers for the corresponding
embedding API, so adjust the generated code accordingly.

[runtime] Don't install any logging/printing handlers for CoreCLR, there's no equivalent.

---

tools/apidiff/Makefile
tools/devops/automation/scripts/GitHub.psm1
tools/devops/automation/templates/build/publish-html.yml

Xamarin.MacCatalyst ships a `Xamarin.iOS.dll` assembly that contains
forwarders (to `Xamarin.MacCatalyst.dll`) and stubs that throws
`PlatformNotSupportedException`.
This is used to help code compatibility between both platforms - but
that requires exposing an identical surface and the best way to ensure
this is to compare (and report) them using `apidiff`
example: https://gist.github.com/spouliot/984c92ce97d2b294088606f0bf697ef8
part of https://github.com/xamarin/xamarin-macios/issues/10210

[apidiff] Compare Xamarin.iOS between iOS and MacCatalyst

---

tests/xharness/AppRunner.cs
tests/xharness/xharness.csproj

Reverts xamarin/xamarin-macios#10926 The runner broke with the async calls.

Revert "[Xharness] Bump to the latests build in main."

---

src/generate-type-forwarders/Program.cs

Example:
```diff
-CameraUnauthorized = 103
+CameraUnauthorized = 3
-CollaborationDataUnavailable = 304
+CollaborationDataUnavailable = 13
...
```
ref: https://gist.github.com/vs-mobiletools-engineering-service2/3ebe78b99d66d2f2addcbc1d5831e6cd

[generate-type-forwarders] Fix enum values

---

src/generate-type-forwarders/Program.cs

Examples
* Fix visibility, e.g. `protected`
```diff
-		public virtual System.IntPtr RawJointLandmarks {
+		protected virtual System.IntPtr RawJointLandmarks {
```
* Remove non-visible properties, e.g. `internal`
```diff
-		public virtual System.IntPtr _AddressBook {
-			get { throw new global::System.PlatformNotSupportedException (global::Constants.UnavailableOnMacCatalyst); }
-			set { throw new global::System.PlatformNotSupportedException (global::Constants.UnavailableOnMacCatalyst); }
-		}
```
* Fix `abstract` members
```diff
-public abstract ARSession Session { get; }
+public virtual ARSession Session { get; }
```

[generate-type-forwarders] Fix issues with properties stubs

---

runtime/exports.t4
runtime/runtime-internal.h
runtime/runtime.m
tests/monotouch-test/ObjCRuntime/ExceptionsTest.cs
tests/monotouch-test/dotnet/macOS/monotouch-test.csproj
tools/common/Application.cs
tools/common/Target.cs

This makes the mono_dllmap_insert function unnecessary for .NET, so remove it.
Ref: https://github.com/dotnet/runtime/issues/48110
Ref: https://github.com/dotnet/runtime/issues/43204
Ref: #10504

[runtime] Redirect to our objc_msgSend wrapper functions when needed for .NET code.

---

runtime/coreclr-bridge.m
runtime/delegates.t4
runtime/runtime-generated.h.t4
runtime/xamarin/runtime.h

If no exception handling is provided when calling a managed delegate from native
code, and the managed code throws, then we'll abort.
It's not entirely clear how we'll handle managed exceptions that go through native
code yet, so this makes the initial implementation easier. By making the exception
handling optional, it'll be easy to find all cases where we need to fix it later,
by making it non-optional. The alternative is to add exception handling code all
over the place that would potentially have to be updated when we figure out exactly
what needs to be done.

[runtime] Make the exception_gchandle argument optional for callbacks to managed code in CoreCLR.

---

msbuild/Makefile
tests/common/TestProjects/SystemMemoryReference/Entitlements.plist
tests/common/TestProjects/SystemMemoryReference/Info.plist
tests/common/TestProjects/SystemMemoryReference/Program.cs
tests/common/TestProjects/SystemMemoryReference/SystemMemoryReference.csproj
tests/msbuild/Xamarin.MacDev.Tests/ProjectsTests/SystemMemoryReference.cs

The [SDK conflict resolution code](https://github.com/dotnet/sdk/blob/3c1307d22747bac8c499a711d1bac39d7fdba541/src/Tasks/Common/src/ConflictResolution/ResolvePackageFileConflicts.cs#L54-L57) expects the FrameworkList.xml file to be located in `$(TargetFrameworkDirectory)/RedistList/FrameworkList.xml`.
Should fix
https://github.com/dotnet/runtime/issues/49211
https://github.com/dotnet/runtime/issues/49940
https://github.com/dotnet/runtime/issues/49477
https://github.com/xamarin/xamarin-macios/issues/10912
https://github.com/xamarin/xamarin-macios/issues/10839
https://github.com/xamarin/xamarin-macios/issues/10548
https://github.com/xamarin/xamarin-macios/issues/10592
https://github.com/mono/mono/issues/20805
https://github.com/mono/mono/issues/20894

Link FrameworkList.xml to a place where MSBuild SDK actually expects it

---

tools/apidiff/Makefile

We already have the _removed_ namespaces and listing all their types is
quite noisy which does not help reviewing changes/diff between the
assemblies.

[apidiff] Skip _removed_ types when comparing Xamarin.iOS.dll between Catalyst and iOS assemblies

---

src/generate-type-forwarders/Program.cs

Examples:
```diff
-public double MinimumDuration = 5---null---;
+public const double MinimumDuration = null;
```
```diff
public ---readonly--- Foundation.NSString RGB565;
```
Also handle `string` constants (quotes).

[generate-type-forwarders] Fix const/readonly fields

---

runtime/mono-runtime.h.t4
runtime/runtime.m
runtime/xamarin/monovm-bridge.h

The fields of the MonoObject struct is specific to MonoVM, so this makes sure
we don't accidentally poke into random memory on CoreCLR.

[runtime] Move the declaration of the MonoObject struct to MonoVM-specific code.

---

src/ObjCRuntime/Dlfcn.cs
src/ObjCRuntime/Runtime.cs
src/ObjCRuntime/Runtime.mac.cs

This also fixes a couple of bugs:
* We wouldn't use the arm64 version of NSLog on Xamarin.Mac.
* We would use a wrong xamarin_log declaration on Xamarin.Mac on older macOS
(the string argument would be UTF8 as opposed to Unicode, which is what the
native function expects).

[ObjCRuntime] Simplify Runtime.NSLog to always call xamarin_log.

---

runtime/runtime.m
runtime/xamarin/runtime.h

This way the argument names match the argument names in the corresponding Mono Embedding API.
This is just an argument rename, no functional changes.

[runtime] Fix argument name confusion in the xamarin_gchandle_new[_weakref] methods.

---

src/generate-type-forwarders/Program.cs

```diff
-public virtual FPUIActionExtensionContext ExtensionContext { get; }
+public FPUIActionExtensionContext ExtensionContext { get; }
```

[generate-type-forwarders] Fix `new virtual` properties

---

msbuild/Makefile
tests/common/TestProjects/SystemMemoryReference/Entitlements.plist
tests/common/TestProjects/SystemMemoryReference/Info.plist
tests/common/TestProjects/SystemMemoryReference/Program.cs
tests/common/TestProjects/SystemMemoryReference/SystemMemoryReference.csproj
tests/msbuild/Xamarin.MacDev.Tests/ProjectsTests/SystemMemoryReference.cs

The [SDK conflict resolution code](https://github.com/dotnet/sdk/blob/3c1307d22747bac8c499a711d1bac39d7fdba541/src/Tasks/Common/src/ConflictResolution/ResolvePackageFileConflicts.cs#L54-L57) expects the FrameworkList.xml file to be located in `$(TargetFrameworkDirectory)/RedistList/FrameworkList.xml`.
Should fix
https://github.com/dotnet/runtime/issues/49211
https://github.com/dotnet/runtime/issues/49940
https://github.com/dotnet/runtime/issues/49477
https://github.com/xamarin/xamarin-macios/issues/10912
https://github.com/xamarin/xamarin-macios/issues/10839
https://github.com/xamarin/xamarin-macios/issues/10548
https://github.com/xamarin/xamarin-macios/issues/10592
https://github.com/mono/mono/issues/20805
https://github.com/mono/mono/issues/20894
Backport of #10928

[d16-9] Link FrameworkList.xml to a place where MSBuild SDK actually expects it

---

src/generate-type-forwarders/Program.cs

Example:
```diff
-protected virtual void OnNewPersonComplete (ABNewPersonCompleteEventArgs e);
```

[generate-type-forwarders] Fix missing `protected internal` methods stubs

---

runtime/coreclr-bridge.m
runtime/monovm-bridge.m
runtime/runtime-internal.h
runtime/runtime.m
runtime/xamarin/runtime.h

* Move the existing logic to call Runtime.Initialize into the MonoVM code.
* Implement calling the managed Runtime.Initialize method from the CoreCLR bridge.
The call to Runtime.Initialize succeeds, which means we're now executing
managed code with CoreCLR for the first time.

[runtime] Implement calling the managed Runtime.Initialize method from the CoreCLR bridge.

---

src/generate-type-forwarders/Program.cs

and that requires ensuring all (implicit/explicit) interface members are
generated...
**Example**
Removed interfaces:
```csharp
IARAnchorCopying
Foundation.INSCoding
Foundation.INSCopying
Foundation.INSSecureCoding
```

[generate-type-forwarders] Add interfaces to types

---

msbuild/Xamarin.Shared/Xamarin.Shared.targets

There doesn't seem to have been any ill effects from the confusion, but it's
better done the right way.

[msbuild] Fix ItemName vs PropertyName confusion in task output.

---

runtime/Delegates.cs.t4
runtime/coreclr-bridge.m
runtime/delegates.inc.t4
runtime/delegates.t4
runtime/exports.t4
runtime/launcher.m
runtime/mono-runtime.h.t4
runtime/mono-runtime.m.t4
runtime/monotouch-main.m
runtime/monovm-bridge.m
runtime/runtime-generated.h.t4
runtime/runtime.m
runtime/xamarin/coreclr-bridge.h
runtime/xamarin/runtime.h
src/ObjCRuntime/Runtime.CoreCLR.cs
src/frameworks.sources

This requires a few things:
* [runtime] Add support for generating managed delegates only for CoreCLR.
However, since our managed code is shared between CoreCLR and MonoVM, the
best we can do is to make these CoreCLR-only delegates .NET-only.
* [runtime] Make it possible to implement Mono Embedding API in the CoreCLR bridge
By making it possible to skip the automatically generated Mono Embedding
* [runtime] Add a MonoObject implementation for CoreCLR.
We need a way to represent a managed object in native code, and since most
our existing runtime code uses MonoObjects, we use the same for the
CoreCLR bridge, just our own version of it. In Mono, the MonoObjects are
tracked by the GC (which scans the stack), but we can't make CoreCLR scan
the stack, so we use a reference counted version of …

[CoreCLR] Add support for mono_assembly_open.

---

tests/xharness/AppBundleLocator.cs

Sometimes msbuild wants to restore packages during this process, which may
take a while.
Hopefully fixes errors like this:
Harness exception for 'Tests for C6353E8B-BFDA-4F54-93D9-FF0F838BF8EE': System.Exception: Unable to evaluate the property OutputPath.
at Xharness.AppBundleLocator.GetPropertyByMSBuildEvaluationAsync (System.Xml.XmlDocument csproj, System.String projectPath, System.String evaluateProperty, System.String dependsOnTargets, System.Collections.Generic.Dictionary`2[TKey,TValue] properties) [0x00327] in /Users/builder/azdo/_work/1/s/xamarin-macios/tests/xharness/AppBundleLocator.cs:109
at Xharness.AppBundleLocator.LocateAppBundle (System.Xml.XmlDocument projectFile, System.String projectFilePath, Microsoft.DotNet.XHarness.iOS.Shared.TestTarget target, System.String …

[xcode12.5] [xharness] Bump timeout to evaluate MSBuild properties by running msbuild.

---

tests/xharness/AppBundleLocator.cs

Sometimes msbuild wants to restore packages during this process, which may
take a while.
Hopefully fixes errors like this:
Harness exception for 'Tests for C6353E8B-BFDA-4F54-93D9-FF0F838BF8EE': System.Exception: Unable to evaluate the property OutputPath.
at Xharness.AppBundleLocator.GetPropertyByMSBuildEvaluationAsync (System.Xml.XmlDocument csproj, System.String projectPath, System.String evaluateProperty, System.String dependsOnTargets, System.Collections.Generic.Dictionary`2[TKey,TValue] properties) [0x00327] in /Users/builder/azdo/_work/1/s/xamarin-macios/tests/xharness/AppBundleLocator.cs:109
at Xharness.AppBundleLocator.LocateAppBundle (System.Xml.XmlDocument projectFile, System.String projectFilePath, Microsoft.DotNet.XHarness.iOS.Shared.TestTarget target, System.String …

[d16-9] [xharness] Bump timeout to evaluate MSBuild properties by running msbuild.

---

src/ObjCRuntime/Runtime.cs

Make sure to free the weak GCHandles we create to track NSObjects, just
removing them from our dictionary doesn't cut it.

[ObjCRuntime] Fix a GCHandle leak.

---

msbuild/Makefile
tests/common/TestProjects/SystemMemoryReference/Entitlements.plist
tests/common/TestProjects/SystemMemoryReference/Info.plist
tests/common/TestProjects/SystemMemoryReference/Program.cs
tests/common/TestProjects/SystemMemoryReference/SystemMemoryReference.csproj
tests/msbuild/Xamarin.MacDev.Tests/ProjectsTests/SystemMemoryReference.cs

The [SDK conflict resolution code](https://github.com/dotnet/sdk/blob/3c1307d22747bac8c499a711d1bac39d7fdba541/src/Tasks/Common/src/ConflictResolution/ResolvePackageFileConflicts.cs#L54-L57) expects the FrameworkList.xml file to be located in `$(TargetFrameworkDirectory)/RedistList/FrameworkList.xml`.
Should fix
https://github.com/dotnet/runtime/issues/49211
https://github.com/dotnet/runtime/issues/49940
https://github.com/dotnet/runtime/issues/49477
https://github.com/xamarin/xamarin-macios/issues/10912
https://github.com/xamarin/xamarin-macios/issues/10839
https://github.com/xamarin/xamarin-macios/issues/10548
https://github.com/xamarin/xamarin-macios/issues/10592
https://github.com/mono/mono/issues/20805
https://github.com/mono/mono/issues/20894
Backport of #10928

[xcode12.5] Link FrameworkList.xml to a place where MSBuild SDK actually expects it

---

src/generate-type-forwarders/Program.cs

Examples
Modified properties:
```diff
-public virtual SceneKit.SCNScene Scene { get; set; }
+public override SceneKit.SCNScene Scene { get; set; }
```
Modified methods:
```diff
-public virtual void CancelRequest (Foundation.NSError error)
+public override void CancelRequest (Foundation.NSError error)
```

[generate-type-forwarders] Fix incorrect overrides on methods and properties

---

src/generate-type-forwarders/Program.cs

Removed method:
```csharp
public static GLKMesh[] FromAsset (ModelIO.MDLAsset asset, out ModelIO.MDLMesh[] sourceMeshes, out Foundation.NSError error);
```
Added method:
```csharp
public static GLKMesh[] FromAsset (ModelIO.MDLAsset asset, out ModelIO.MDLMesh sourceMeshes, out Foundation.NSError error);
```

[generate-type-forwarders] Fix parameter arrays used by-reference

---

src/generate-type-forwarders/Program.cs

The type implementation of an interface member does not need to be
`virtual` but, since it's done by _sealing_ the member.
Example
```diff
public virtual ---final--- int Count { get; }
```

[generate-type-forwarders] Fix final properties

---

tools/devops/automation/templates/agent-pool-selector.yml
tools/devops/automation/templates/build/build.yml
tools/devops/automation/templates/build/stage.yml

Since agent pools can contain a mix of OSes, stop targeting pools with Catalina in the name and instead target pools with more generic names that will become the production pools going forward
Pool migration:
VSEng-Xamarin-RedmondMacCatalinaBuildPool-iOS-Untrusted -> VSEng-Xamarin-RedmondMacBuildPool-iOS-Untrusted
VSEng-Xamarin-RedmondMacCatalinaBuildPool-iOS-Trusted -> VSEng-Xamarin-RedmondMacBuildPool-iOS-Trusted

Target new xamarin-macios agent pools

---

src/generate-type-forwarders/Program.cs

Output should be identical and since all other PR are merged it
should also produce an output with no breaking changes.

[generate-type-forwarders] Reduce string allocations

---

runtime/monotouch-main.m
tests/linker/CommonLinkAnyTest.cs

Those are called respectively inside `xamarin_vm_initialize` and
`xamarin_bridge_initialize` functions.
This fix the **AppContext.GetData always return null for iOS** issue
https://github.com/dotnet/runtime/issues/50290
Thanks for @filipnavara for diagnosing this quicker than anyone else!
Added unit tests to ensure `AppContext.GetData` can read back the values
we're providing at startup.

[dotnet] Call monovm_initialize before mono_jit_init

---

runtime/exports.t4
runtime/mono-runtime.m.t4
runtime/runtime.m

The implementation will be completely different, where the hook into CoreCLR
is in managed code.
We still need to initialize the framework_peer_release_lock mutex, so move
that code out of gc_enable_new_refcount.

[runtime] Don't start the toggle ref machinery in CoreCLR.

---

src/ObjCRuntime/Runtime.cs

Make sure to free the weak GCHandles we create to track NSObjects, just
removing them from our dictionary doesn't cut it.
Backport of #10967

[d16-9] [ObjCRuntime] Fix a GCHandle leak.

---

tests/xharness/GitHub.cs
tools/devops/automation/templates/build/build.yml

VSTS does not longer have a file with the pat yet it does allow to use
an env variable with the pat provided by the keyvault. Before this
change we have been running all the tests which results in several extra
hours when we do not need to. For example, if nothing was changed in
msbuild, do not run its tests which are 45 mins long.
Changes are:
* provide pat in the env.
* update xharness to use an env var, do not longer read from a file.
fixes: https://github.com/xamarin/xamarin-macios/issues/10923

[CI][XHarness] Ensure we filter the tests to run.

---

tests/linker/ios/link all/DataContractTest.cs

This reverts commit bc668916e7197ba5f9e0a6ea7f55df28234a183a.
Original issue https://github.com/dotnet/runtime/issues/41525 was solved a while ago.

Revert "[tests] Ignore linkall's DataContractTest in .NET due to a linker bug."

---

tests/linker/ios/link sdk/LinkSdkRegressionTest.cs

This reverts commit ae0649f4e59c0ea435429799eeeb5f4759a4195d.
Original issue https://github.com/dotnet/runtime/issues/41392 was fixed long ago

Revert "[tests] Ignore LinkSdkRegressionTest.AsQueryable_Enumerable due to an issue in .NET"

---

dotnet/targets/Xamarin.Shared.Sdk.props
dotnet/targets/Xamarin.Shared.Sdk.targets

We started using `$(SuppressTrimAnalysisWarnings)` by default, because
ILLink started emitting warnings by default in .NET 6 Preview 3.
7bf3e8d8 fixed *most* of these warnings except for `IL2026`:
https://github.com/dotnet/sdk/blob/16aedd6e72bd2f8dea01918478fc1368bc017fe9/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ILLink.targets#L52-L57
I get around 20 instances of this warning when building dotnet/maui.
`IL2026` occurs because this logic is evaluated much earlier than the
`PrepareForILLink` MSBuild target:
https://github.com/dotnet/sdk/blob/16aedd6e72bd2f8dea01918478fc1368bc017fe9/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ILLink.targets#L202
The MSBuild evaluation order right now is:
* Sdk/Sdk.props
* Microsoft.[platform].Sdk.props
* …

[dotnet] suppress IL2026 linker warning

---

tests/xharness/GitHub.cs
tools/devops/automation/templates/build/build.yml

VSTS does not longer have a file with the pat yet it does allow to use
an env variable with the pat provided by the keyvault. Before this
change we have been running all the tests which results in several extra
hours when we do not need to. For example, if nothing was changed in
msbuild, do not run its tests which are 45 mins long.
Changes are:
* provide pat in the env.
* update xharness to use an env var, do not longer read from a file.
fixes: https://github.com/xamarin/xamarin-macios/issues/10923

[CI][XHarness] Ensure we filter the tests to run. (#11035)

---

tests/xharness/GitHub.cs
tools/devops/automation/templates/build/build.yml

VSTS does not longer have a file with the pat yet it does allow to use
an env variable with the pat provided by the keyvault. Before this
change we have been running all the tests which results in several extra
hours when we do not need to. For example, if nothing was changed in
msbuild, do not run its tests which are 45 mins long.
Changes are:
* provide pat in the env.
* update xharness to use an env var, do not longer read from a file.
fixes: https://github.com/xamarin/xamarin-macios/issues/10923
Backport of #11035

[xcode12.5] [CI][XHarness] Ensure we filter the tests to run.

---

tests/xharness/AppRunner.cs

The main reason why we use the Tcp Tunnel is because we do have
networking issues, one of them is related to the DNS server. If we use
the tunnel we have made a choice and we are sure we will not need the
IPs.
This solves a case in which we have a network failure when we try
to retrieve the IP address using the DNS lookup.

[CI][Xharness] If we are use the tcp tunnel do not try to get IPs.

---

tools/devops/automation/templates/build/configure.yml

Changes to use PrBuild variable as check for running OneLocBuild task instead of checking if Build.SourceBranchName is set to 'merge'.

[Localization] Using PrBuild Variable

---

msbuild/Xamarin.MacDev.Tasks.Core/Tasks/LinkNativeCodeTaskBase.cs
tests/common/TestProjects/MyXamarinFormsApp/MyXamarinFormsApp.dotnet.csproj
tests/dotnet/MyXamarinFormsApp/MyXamarinFormsApp.csproj
tests/introspection/ApiPInvokeTest.cs
tests/introspection/dotnet/iOS/introspection.csproj
tests/introspection/dotnet/tvOS/introspection.csproj
tests/linker/ios/dont link/DontLinkRegressionTests.cs
tests/linker/ios/dont link/dotnet/iOS/dont link.csproj
tests/linker/ios/link all/AttributeTest.cs
tests/linker/ios/link all/LinkAllTest.cs
tests/linker/ios/link all/dotnet/iOS/link all.csproj
tests/linker/ios/link sdk/LinkSdkRegressionTest.cs
tests/linker/ios/link sdk/PclTest.cs
tests/linker/ios/link sdk/dotnet/iOS/link sdk.csproj
tests/monotouch-test/dotnet/iOS/monotouch-test.csproj
tests/monotouch-test/dotnet/macOS/monotouch-test.csproj

With P3 addition on ICU we must now link the native executable as C++.
Remove an old workaround, in many tests, referencing old (5.0/previews)
packages that caused native link time failures.
ref: https://github.com/mono/linker/issues/1139

[dotnet] Fix device builds

---

Make.config
tools/devops/automation/templates/agent-pool-selector.yml

Use the untrusted pool only when is a PR, use the trusted one in all other cases (we push to origin to build pkgs in some cases and we want to use the trusted pool).

[CI] Fix pool selector

---

src/ObjCRuntime/Runtime.cs

Make sure to free the weak GCHandles we create to track NSObjects, just
removing them from our dictionary doesn't cut it.
Backport of #10967

[xcode12.5] [ObjCRuntime] Fix a GCHandle leak.

---

tests/xharness/AppRunner.cs

The main reason why we use the Tcp Tunnel is because we do have
networking issues, one of them is related to the DNS server. If we use
the tunnel we have made a choice and we are sure we will not need the
IPs.
This solves a case in which we have a network failure when we try
to retrieve the IP address using the DNS lookup.
Backport of #11027

[d16-9] [CI][Xharness] If we are use the tcp tunnel do not try to get IPs.

---

tests/xharness/AppRunner.cs

The main reason why we use the Tcp Tunnel is because we do have
networking issues, one of them is related to the DNS server. If we use
the tunnel we have made a choice and we are sure we will not need the
IPs.
This solves a case in which we have a network failure when we try
to retrieve the IP address using the DNS lookup.
Backport of #11027

[xcode12.5] [CI][Xharness] If we are use the tcp tunnel do not try to get IPs.

---

Make.config
tools/devops/automation/templates/agent-pool-selector.yml

Use the untrusted pool only when is a PR, use the trusted one in all other cases (we push to origin to build pkgs in some cases and we want to use the trusted pool).
Backport of #11032

[d16-9] [CI] Fix pool selector

---

Make.config
tools/devops/automation/templates/agent-pool-selector.yml

Use the untrusted pool only when is a PR, use the trusted one in all other cases (we push to origin to build pkgs in some cases and we want to use the trusted pool).
Backport of #11032

[xcode12.5] [CI] Fix pool selector

---

system-dependencies.sh

Avoid this warning when checking for required tools/dependencies
```
You should have exactly CoreSimulator.framework version 732.18 (found 732.18
732.18). Execute './system-dependencies.sh --provision-xcode' to install the expected version.
```
Right version, but found two times ?
Because we're looking at a (now) fat framework so we get things twice
```
lipo -info /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator
Architectures in the fat file: /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator are: x86_64 arm64e
```
Solution ? make it uniq

[build] Fix incorrect warning about CoreSimulator.framework version

---

tools/dotnet-linker/Steps/GenerateMainStep.cs

This reverts commit abc3616873988ebaa11bf88cd304eeb0f0f0bc98.
The issue https://github.com/dotnet/runtime/issues/47121 was fixed recently.

Revert "[dotnet] Force the GC mode to be preemptive. (#10667)"

---

tests/linker/CommonLinkSdkTest.cs

This reverts commit dea6580c7855a747314d7008fdf1327a52010224.
This was fixed a while ago https://github.com/mono/linker/issues/1451 -> https://github.com/dotnet/runtime/issues/41390

Revert "[tests] Ignore CommonLinkSdkTest.TypeDescriptor_A7793 in .NET due to a linker bug."

---

tools/linker/MonoTouch.Tuner/PreserveSmartEnumConversionsSubStep.cs

This reverts commit 482151eea71da3c06749d34c129548ec6c822894.
This issue https://github.com/mono/linker/issues/1458 has been fixed a while ago.

Revert "[dotnet-linker] Make PreserveSmartEnumConversionsStep active for type as well to work around a linker bug."

---

tests/linker/ios/link sdk/Bug1820Test.cs

This reverts commit 9cbf14500b3182a076bcffa3e308d1d708c1ba86.
The original issue https://github.com/mono/linker/issues/1454 -> https://github.com/dotnet/runtime/issues/41389 was fixed a while ago.

Revert "[tests] Ignore the XmlSerializationTest.Bug1820_GenericList test in .NET due to a linker bug."

---

tools/devops/automation/templates/agent-pool-selector.yml
tools/devops/automation/templates/build/build.yml

Plan is to abandon the old pools and shift all jobs (Big Sur and Catalina) for main, XCode12.5, d16-9, etc. to the new pools
Note: Bot capacity in the new PR & CI pools is sufficient to merge this PR

Target new xamarin-macios multi-OS agent pools

---

eng/Version.Details.xml
eng/Versions.props

This pull request updates the following dependencies
[marker]: <> (Begin:df3e6147-3e41-4928-6775-08d8f479343c)
- **Subscription**: df3e6147-3e41-4928-6775-08d8f479343c
- **Build**: 20210402.5
- **Date Produced**: 4/2/2021 3:06 PM
- **Commit**: aee38a6dd446b512b1ae510d80d2ed1c1f24e79a
- **Branch**: refs/heads/release/6.0.1xx-preview3
[DependencyUpdate]: <> (Begin)
- **Updates**:
- **Microsoft.Dotnet.Sdk.Internal**: [from 6.0.100-preview.3.21201.23 to 6.0.100-preview.3.21202.5][1]
[1]: https://github.com/dotnet/installer/compare/df3d680...aee38a6
[DependencyUpdate]: <> (End)
[marker]: <> (End:df3e6147-3e41-4928-6775-08d8f479343c)
Backport of #11106

[6.0.1xx-preview3] [main] Update dependencies from dotnet/installer

---

tools/devops/automation/build-pipeline.yml

We are doing some black magic. We have several templates that
are executed with different parameters.
The problem with that is that templates cannot be used with the
matrix strategy, so we are doing a little trick based on the following:
1. We can create a template that expands.
2. We can use the each keyword, which allow a loop
3. yaml is a super set of json, therefore, it was jsond dictionaties
We use the parameters as yaml objs (simple json ones) and we pass them.
Now we can:
1. Add more tests with less typing.
2. Modify the tests when we manually trigger a build.
Yes! number 2 is very cool, do you want to remove a stage from a manual
build, just delete it. Do you want to change the device test labels,
just edit the object.

[CI] Black magic to make life better.

---

Make.config

~Backport of #11108~
Hardcode preview 3 branch name and revert dot on CURRENT_BRANCH_ALPHANUMERIC
This is to follow suit on versioning found in dotnet/maui#598

[6.0.1xx-preview3] [Make.config] Hardcode preview.3 on our versioning

---

tools/devops/automation/build-pipeline.yml

Lets not trigger builds for readmes and other docs.
Backport of #11104

[xcode12.5] [CI] Exclude builds for certain paths.

---

tools/devops/automation/build-pipeline.yml

Lets not trigger builds for readmes and other docs.
Backport of #11104

[d16-9] [CI] Exclude builds for certain paths.

---

Make.config

Reverts xamarin/xamarin-macios#11108
Not needed since we will only do this for previews and we will be hardcoding the branch name at branching time.

Revert "[Make.config] Allow '.' on CURRENT_BRANCH_ALPHANUMERIC to match android package names"

---

tools/devops/automation/templates/build/api-diff.yml
tools/devops/automation/templates/build/build.yml

Step fwd to group all API diff and get back the old generator and branch diffs.
Backport of #11112

[xcode12.5] [CI] Group all API diff in a template to make things manageable.

---

tools/devops/automation/templates/build/api-diff.yml
tools/devops/automation/templates/build/build.yml

Step fwd to group all API diff and get back the old generator and branch diffs.
Backport of #11112

[d16-9] [CI] Group all API diff in a template to make things manageable.

---

dotnet/targets/Xamarin.Shared.Sdk.targets

The original goal was to remove the `.dylib` from the app bundle.
However some are required, even in release, so that will need to be
fixed first [1]
[1] https://github.com/xamarin/xamarin-macios/issues/11145

[dotnet][msbuild] Do not copy `.pdb` files inside `.app` for release builds

---

tools/devops/automation/templates/build/configure.yml

We are trying to join the json rather than the collection of strings.
$tag is a collection we can join.
Backport of #11144

[d16-9] [CI] Fix wrong fwd labels.

---

tools/devops/automation/templates/build/configure.yml

We are trying to join the json rather than the collection of strings.
$tag is a collection we can join.
Backport of #11144

[xcode12.5] [CI] Fix wrong fwd labels.

---

tests/linker/ios/link all/Main.cs

The issue https://github.com/mono/linker/issues/1913 was fixed a while ago.

[tests] Revert manual preservation of InternalsVisibleToAttribute.ctor(string)

---

tools/devops/automation/templates/build/configure.yml

The 'isCreatePRSelected' is responsible for creating the PR. 
Turning it to false should stop OneLocBuild from creating PRs.
The only thing I am not sure of and would like to know from reviewers is:
the rest of the inputs are used for creating the PRs. If we are not creating a PR, 
I am not sure if Yaml will complain about these additional unused inputs
```isAutoCompletePrSelected: false
prSourceBranchPrefix: 'locfiles'
repoType: gitHub
gitHubPatVariable: '$(GitHub.Token)'
packageSourceAuth: patAuth
patVariable: '$(OneLocBuild--PAT)'

[Localization] Temporarily Stop OneLocBuild from making PRs

---

dotnet/targets/Xamarin.Shared.Sdk.targets

This worked fine up to P3 but failed with an early bump [1] to P4
where paths became invalid (missing a `/`) like:
`bin/iPhoneSimulator/Debug/net6.0-ios/iossimulator-x64/publish/../dont link.applibxamarin-dotnet-debug.dylib`
and did not copy the required `.dylib` [2] (and other stuff) inside the
app bundle.
[1] https://github.com/xamarin/xamarin-macios/pull/11127
[2] .dylib where the first thing to crash at startup
```
Termination Reason:    DYLD, [0x1] Library missing
Application Specific Information:
dyld: launch, loading dependent libraries
DYLD_SHARED_CACHE_DIR=/Users/builder/Library/Developer/CoreSimulator/Caches/dyld/19G2021/com.apple.CoreSimulator.SimRuntime.iOS-14-4.18D46
DYLD_ROOT_PATH=/Applications/Xcode_12.4.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/ …
```

[dotnet][msbuild] Fix RelativePath inside ResolvedFileToPublish

---

msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Windows.After.targets

There's no Hot Restart support for net6 yet, but we should still import those targets if the file exist, because are needed on the legacy iOS Sdk on Windows.

Reenable HotRestart targets for the legacy Sdk

---

dotnet/targets/Xamarin.Shared.Sdk.targets
runtime/runtime.m
tests/EmbeddedResources/ResourcesTest.cs
tests/common/DotNet.cs
tests/monotouch-test/Foundation/LocaleTest.cs
tools/dotnet-linker/LinkerConfiguration.cs
tools/dotnet-linker/Steps/GenerateMainStep.cs

and re-enable some tests for dotnet
Part of the fix for https://github.com/xamarin/xamarin-macios/issues/8906
Known Issues
* [some Calendar are not the expected ones](https://github.com/dotnet/runtime/issues/50859)
* [No support for tvOS](https://github.com/dotnet/runtime/issues/50912)

[dotnet] Add ICU support for iOS builds

---

tests/bgen/bgen-tests.csproj
tests/dotnet/UnitTests/DotNetUnitTests.csproj
tests/generator/generator-tests.csproj
tests/mmptest/mmptest.csproj
tests/msbuild/Xamarin.MacDev.Tests/Xamarin.MacDev.Tests.csproj
tests/mtouch/mtouch.csproj

Required to bump dotnet runtime to preview 4 as the binary log format
was updated (and this affects our ability to run some tests)
https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210407.33/4632319/sim/;/tests/vsdrops_index.html

Bump MSBuild.StructuredLogger to 2.1.404

---

tools/devops/automation/build-pipeline.yml

Because the maestro bot is not a team memeber AND cannot be added as
one, it will not trigger a PR build, but it will trigger an CI build. WE
make the changes to take those as PR builds and do them in the CI.

[CI] Re-enable CI on maestro branches.

---

tools/devops/automation/templates/build/publish-html.yml

We set the pipeline as a partial success BUT the github status as an error. We did fail.
Backport of #11170

[d16-9] [CI] Set status as error if one or more tests failed.

---

tools/common/Target.cs
tools/linker/MonoTouch.Tuner/ListExportedSymbols.cs

[dotnet] Handle `lib` prefix for P/Invokes for runtime native libraries

---

tests/common/PlatformInfo.cs

Otherwise a `[SupportedOSPlatformAttribute ("ios12,3")]` (should be a
dot, not a comma) would throw a `NullReferenceException` making it
harder to track down the error

[tests][introspection] Report error if no version is present in [SupportedOSPlatformAttribute]

---

dotnet/targets/Xamarin.Shared.Sdk.targets

With https://github.com/xamarin/xamarin-macios/pull/11158 we do not
load symbols from the dylibs - so we do not have to ship them.
This makes the size comparison, between legacy and dotnet, more accurate
since the dylibs were large binaries.
https://gist.github.com/spouliot/9cad974b73b982404421e634f2a3a2b7

[dotnet][msbuild] Stop publishing dylibs in release builds

---

tools/common/StaticRegistrar.cs

This avoid some computation that might not be needed.
It also avoids a `NullReferenceException` when updating to net6 preview 4
builds (where `ResolveType` can return `null` but the type reference was
enough to complete the job).

[static-registrar] Re-order some code in ToObjCParameterType

---

tools/devops/automation/templates/build/configure.yml

[d16-9] [CI] Add a tag to identify those auto-scheduled builds. fixes #11191

---

tools/devops/automation/templates/build/configure.yml

[xcode12.5] [CI] Add a tag to identify those auto-scheduled builds. fixes #11191

---

tools/devops/automation/templates/devices/build.yml

[d16-9] [CI] There is no reason to need to run these tests on device bots.

---

dotnet/package/microsoft.workloads.csproj

Context: https://github.com/dotnet/designs/pull/188/files#diff-8fcaa29d8e6f00b34b3cb1830d93f33e75f04424780a66a3c658c7021048e74fR125
The future `dotnet workload install` commands will be expecting that
the `.nupkg` for a workload will contain:
* `data/WorkloadManifest.json`
* `data/WorkloadManifest.targets`
This was done so that we don't interfere with NuGet's spec for layout
of a `.nupkg` file. You are allowed to put whatever you like in a
`/data/` folder.
The layout on disk in `/usr/local/share/dotnet`, etc. is unchanged, so
we don't need any changes to our installers, etc.
Android side:
https://github.com/xamarin/xamarin-android/pull/5843

[dotnet] move WorkloadManifest.* files to /data/ folder

---

tools/devops/automation/templates/devices/build.yml

[xcode12.5] [CI] There is no reason to need to run these tests on device bots.

---

src/Foundation/LinkerSafeAttribute.cs
tools/common/Tuning.cs
tools/mmp/Tuning.mmp.cs
tools/mtouch/Tuning.mtouch.cs

In this case we can obsolete the attribute on both legacy and dotnet
since the replacement attribute is available on both. However this does
require a small update to the legacy linker (and is part of the PR).
Fix https://github.com/xamarin/xamarin-macios/issues/10674

[linker] Obsolete 'LinkerSafeAttribute' in favor of `AssemblyMetadata`

---

dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets
src/AssemblyInfo.cs.in

Fix https://github.com/xamarin/xamarin-macios/issues/10673

[dotnet] Use `[AssemblyMetadata ("IsTrimmable", "True")]` in platforms assemblies

---

tools/devops/automation/post-build-pipeline.yml

The artifact upload task in post-build-pipeline.yaml was not indented
correctly and the automatic pipeline triggers were not firing as a
result.

[ci] Fix artifact upload in post build pipeline

---

tools/devops/automation/scripts/GitHub.psm1

On a pull request, Azure DevOps does not build the exact version of the code that you pushed,
but a version merged with your target branch. This means that the commit
we see in the Buid.Revision is not the one of the last commit of the PR,
which makes some statuses get "lost" and checks be missed.
We make a distintion on which variable to used base on the build reason.
PS: Change is clearer this way that add logic in the yml.

[CI][VSTS] Ensure statuses are set in the correct commit and not the merge commit.

---

runtime/coreclr-bridge.m
runtime/exports.t4
runtime/mono-runtime.h.t4
runtime/monotouch-main.m
runtime/runtime.m

Next failure is now:
> monotouchtest[27142:4675921] Xamarin.Mac: The method mono_profiler_install has not been implemented for CoreCLR.

[CoreCLR] Implement mono_assembly_get_object.

---

tools/devops/automation/templates/common/publish-html.yml

We only have one checkout which changes the path. This is a "feature" from VSTS.

[CI] Fix import issue in device test templates.

---

msbuild/Xamarin.Shared/Xamarin.Shared.props

Accept 'UseInterpreter' as an alternative for 'MtouchInterpreter', so that we
support the same variable name between iOS and Android.
Fixes https://github.com/xamarin/xamarin-macios/issues/11138.

[msbuild] Accept 'UseInterpreter' as an alternative for 'MtouchInterpreter'. Fixes #11138.

---

runtime/coreclr-bridge.m
runtime/exports.t4
runtime/monovm-bridge.m
runtime/runtime.m
runtime/shared.h
runtime/shared.m
runtime/xamarin/runtime.h

The current implementation is MonoVM-specific, and won't work with CoreCLR
(something else will have to be implemented for CoreCLR, which is tracked
here: https://github.com/xamarin/xamarin-macios/issues/11256).
Next failure is now (after #11254 is merged as well):
> monotouchtest[50744:5001174] Xamarin.Mac: The method mono_jit_exec has not been implemented for CoreCLR.

[runtime] Move the code to wrap every managed thread with an NSAutoreleasePool to the MonoVM bridge.

---

tools/devops/automation/scripts/GitHub.psm1

On a pull request, Azure DevOps does not build the exact version of the code that you pushed,
but a version merged with your target branch. This means that the commit
we see in the Buid.Revision is not the one of the last commit of the PR,
which makes some statuses get "lost" and checks be missed.
We make a distintion on which variable to used base on the build reason.
PS: Change is clearer this way that add logic in the yml.
Backport of #11250

[d16-9] [CI][VSTS] Ensure statuses are set in the correct commit and not the merge commit.

---

tests/xtro-sharpie/MacCatalyst-AVKit.ignore
tests/xtro-sharpie/MacCatalyst-AudioToolbox.todo
tests/xtro-sharpie/MacCatalyst-UIKit.ignore
tests/xtro-sharpie/MacCatalyst-UIKit.todo

Fixes:
?fixed-todo? Entry '!missing-pinvoke! AudioSessionAddPropertyListener is not bound' in 'MacCatalyst-AudioToolbox.todo' is not found in corresponding 'MacCatalyst-AudioToolbox.raw' file
?fixed-todo? Entry '!missing-pinvoke! AudioSessionGetProperty is not bound' in 'MacCatalyst-AudioToolbox.todo' is not found in corresponding 'MacCatalyst-AudioToolbox.raw' file
?fixed-todo? Entry '!missing-pinvoke! AudioSessionGetPropertySize is not bound' in 'MacCatalyst-AudioToolbox.todo' is not found in corresponding 'MacCatalyst-AudioToolbox.raw' file
?fixed-todo? Entry '!missing-pinvoke! AudioSessionInitialize is not bound' in 'MacCatalyst-AudioToolbox.todo' is not found in corresponding 'MacCatalyst-AudioToolbox.raw' file
?fixed-todo? Entry '!missing-pinvoke! AudioSessionSetActive is not bound' …

[xtro] Update MacCatalyst todos.

---

tools/devops/automation/templates/common/publish-html.yml

We only have one checkout which changes the path. This is a "feature" from VSTS.
Backport of #11249

[d16-9] [CI] Fix import issue in device test templates.

---

tools/devops/automation/templates/common/publish-html.yml

We only have one checkout which changes the path. This is a "feature" from VSTS.
Backport of #11249

[xcode12.5] [CI] Fix import issue in device test templates.

---

tools/devops/automation/templates/build/build-nugets.yml
tools/devops/automation/templates/build/build.yml
tools/devops/automation/templates/build/stage.yml
tools/devops/automation/templates/build/upload-azure.yml

We move from having a status per nugets to two statues:
1. xamarin-macios (Nugets built) -  to let us know that we did build
nugets.
2. xamarin-macios (Nuvets published) - to let us know tat we did pubish
the nugets.

[CI] Reduce the number of statuses when we build nugets.

---

tools/devops/automation/build-pipeline.yml

Remove those devices of Mac OS X that will not happen because we cannot
run the agent in such and old device. This is due to the fact that the
agent runs using c# and we do not support such and old OS.
Also add a new stage to run tests on catalina. ATM older OS as not
working, but Catalina should work with our trusted pool.

[CI] Remove Mac OS devices that will not happen.

---

tools/devops/automation/scripts/GitHub.psm1

On a pull request, Azure DevOps does not build the exact version of the code that you pushed,
but a version merged with your target branch. This means that the commit
we see in the Buid.Revision is not the one of the last commit of the PR,
which makes some statuses get "lost" and checks be missed.
We make a distintion on which variable to used base on the build reason.
PS: Change is clearer this way that add logic in the yml.
Backport of #11250

[xcode12.5] [CI][VSTS] Ensure statuses are set in the correct commit and not the merge commit.

---

tools/devops/automation/build-pipeline.yml

Remove those devices of Mac OS X that will not happen because we cannot
run the agent in such and old device. This is due to the fact that the
agent runs using c# and we do not support such and old OS.
Also add a new stage to run tests on catalina. ATM older OS as not
working, but Catalina should work with our trusted pool.
Backport of #11272

[d16-9] [CI] Remove Mac OS devices that will not happen.

---

tools/devops/automation/templates/governance-checks.yml

VSTS already provides a status per job, since the governance tests do
not give much feedback in the comments and just set a status, we can use
the default provided by the VSTS app.
The two statuses are:
It is also driving me crazy that we have two diff logos for the statuses.... but that is my problem :)

[CI][VSTS] Remove redundant status.

---

dotnet/targets/Xamarin.Shared.Sdk.props
dotnet/targets/Xamarin.Shared.Sdk.targets
msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.AppExtension.CSharp.targets
msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.CSharp.targets
msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.CSharp.targets
msbuild/Xamarin.Shared/Xamarin.Shared.ObjCBinding.targets
msbuild/Xamarin.Shared/Xamarin.Shared.targets
msbuild/Xamarin.iOS.Tasks.Core/Xamarin.MacCatalyst.CSharp.targets
msbuild/Xamarin.iOS.Tasks.Core/Xamarin.TVOS.AppExtension.CSharp.targets
msbuild/Xamarin.iOS.Tasks.Core/Xamarin.TVOS.CSharp.targets
msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.App.CSharp.targets
msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.AppExtension.CSharp.targets
msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.CSharp.targets
msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.AppExtension.CSharp.targets
msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.CSharp.targets
msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.props
msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.ObjCBinding.CSharp.targets
msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.WatchApp.CSharp.targets

The `$(_UsingXamarinSdk)` property has been renamed to help improve
external usability.  This change increases parity with the Android SDK,
which currently defines `$(UsingAndroidNETSdk)` for internal and
external use.  The property has also been moved so that it will be
set as early as possible, before the .NET Sdk targets are imported.

[msbuild] Rename $(_UsingXamarinSdk) to $(UsingAppleNETSdk)

---

src/ObjCRuntime/Runtime.CoreCLR.cs
src/ObjCRuntime/Runtime.cs
tests/xtro-sharpie/common-CoreFoundation.ignore

Fixes https://github.com/xamarin/xamarin-macios/issues/11239.

[ObjCRuntime] Print to stderr if using xamarin_log fails. Fixes #11239.

---

tools/devops/automation/scripts/GitHub.psm1
tools/devops/automation/templates/build/publish-html.yml

[xcode12.5] [CI] Remove duplicated status.

---

tools/devops/automation/templates/governance-checks.yml

VSTS already provides a status per job, since the governance tests do
not give much feedback in the comments and just set a status, we can use
the default provided by the VSTS app.
The two statuses are:
It is also driving me crazy that we have two diff logos for the statuses.... but that is my problem :) 
Backport of #11267

[xcode12.5] [CI][VSTS] Remove redundant status.

---

tools/devops/automation/templates/governance-checks.yml

VSTS already provides a status per job, since the governance tests do
not give much feedback in the comments and just set a status, we can use
the default provided by the VSTS app.
The two statuses are:
It is also driving me crazy that we have two diff logos for the statuses.... but that is my problem :) 
Backport of #11267

[d16-9] [CI][VSTS] Remove redundant status.

---

tools/devops/automation/build-pipeline.yml

Remove those devices of Mac OS X that will not happen because we cannot
run the agent in such and old device. This is due to the fact that the
agent runs using c# and we do not support such and old OS.
Also add a new stage to run tests on catalina. ATM older OS as not
working, but Catalina should work with our trusted pool.
Backport of #11272

[xcode12.5] [CI] Remove Mac OS devices that will not happen.

---

tools/devops/automation/scripts/GitHub.psm1

VSTS has so many little corner cases....
Backport of #11268

[xcode12.5] [CI] The env var is not provided in the CI builds, just PRs.

---

tools/devops/automation/scripts/GitHub.psm1

VSTS has so many little corner cases....
Backport of #11268

[d16-9] [CI] The env var is not provided in the CI builds, just PRs.

---

tools/common/Application.cs
tools/common/CoreResolver.cs
tools/common/StaticRegistrar.cs
tools/mmp/driver.cs
tools/mmp/resolver.cs

* Extract the code we use to configure the assembly resolver during a normal
mmp run to make it usable for --runregistrar.
* Configure the assembly resolver we use for --runregistrar.
* Pass the assembly resolver to the registrar so that it's actually used.
* Adjust the System.Void lookup to look everywhere even if we find a corlib,
since behavior changes a bit now that we're using an assembly resolver:
* Previous behavior:
1. In .NET mode, look for a corlib named System.Private.CoreLib, and fail to find it.
2. Look in all the loaded assemblies for System.Void (and find it in System.Runtime.dll).
* Broken behavior as a result of the resolver changes:
1. Find corlib as System.Private.CoreLib.dll
2. Fail to find System.Void in System.Private.CoreLib.dll, since we'd only look in corlib.
* …

[mmp] Use the resolver (and configure it correctly) when using --runregistrar.

---

src/ObjCRuntime/PlatformAvailability.cs
tests/common/TestRuntime.cs
tests/linker/ios/link all/LinkAllTest.cs
tests/xharness/Harness.cs

This exposed a few tests that are failing on dotnet (adjusted or fixed)
Also fix a typo in an exception message in `src/ObjCRuntime/PlatformAvailability.cs`
and a build warning in `tests/common/TestRuntime.cs`
Fix part of https://github.com/xamarin/xamarin-macios/issues/11243
And allows enabling the tvOS/dotnet link all tests

[tests][link all] Fix nunit silent exception causing some tests not to be enabled

---

dotnet/targets/Xamarin.Shared.Sdk.targets

Documentation
https://github.com/dotnet/runtime/blob/main/docs/workflow/trimming/feature-switches.md
Very small effect on the final app size.
Before
https://gist.github.com/spouliot/9f6fa4f15c117149905141f80fbad399
After
https://gist.github.com/spouliot/c9cefac8aa77c8c68edb9bbc77f553d0

[dotnet] Enable more trimming switches

---

msbuild/Xamarin.Shared/Xamarin.Shared.props

Accept 'UseInterpreter' as an alternative for 'MtouchInterpreter', so that we
support the same variable name between iOS and Android.
Fixes https://github.com/xamarin/xamarin-macios/issues/11138.
Backport of #11252

[release/6.0.1xx-preview4] [msbuild] Accept 'UseInterpreter' as an alternative for 'MtouchInterpreter'. Fixes #11138.

---

msbuild/Xamarin.iOS.Tasks/Xamarin.iOS.Tasks.csproj

There were 2 "problems":
1- Messaging depends on `System.Net.Mqtt` and not in `System.Net.Mqtt.Server`. It still worked because the latter depends on the former package, but we were restoring unnecessary dependencies.
2- We don't need an excplicit reference, since `Xamarin.Messaging.Build.Client` already depends on it, and by removing it we avoid having another dependency to keep up to date.

[msbuild] Removes explicit Mqtt dependency

---

msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets

We stopped converting full pdbs to mdbs on Windows, so we need to override the `DebugType` property to `portable` if it's `full`, otherwise the debugger won't work from Visual Studio.

[msbuild] Fixes DebugType for VS

---

tools/devops/automation/scripts/GitHub.psm1

Move logic one level up and re-use it in the other status.
Backport of #11311

[xcode12.5] [CI] Unify both failing statuses.

---

tests/xharness/GitHub.cs
tools/devops/automation/templates/build/build.yml

VSTS does not longer have a file with the pat yet it does allow to use
an env variable with the pat provided by the keyvault. Before this
change we have been running all the tests which results in several extra
hours when we do not need to. For example, if nothing was changed in
msbuild, do not run its tests which are 45 mins long.
Changes are:
* provide pat in the env.
* update xharness to use an env var, do not longer read from a file.
fixes: https://github.com/xamarin/xamarin-macios/issues/10923
Backport of #11047

[d16-10-preview2] [CI][XHarness] Ensure we filter the tests to run. (#11035)

---

tools/devops/automation/scripts/GitHub.psm1

Move logic one level up and re-use it in the other status.
Backport of #11311

[d16-9] [CI] Unify both failing statuses.

---

runtime/exports.t4
runtime/runtime.m
runtime/xamarin/runtime.h

Next failure is now (with #11271 as well):
> monotouchtest[83025:8899609] Xamarin.Mac: The method mono_gchandle_get_target has not been implemented for CoreCLR.
```
3   com.xamarin.monotouch-test    	0x00000001030a56a8 xamarin_assertion_message + 408 (runtime.m:1503)
4   com.xamarin.monotouch-test    	0x0000000103074a80 mono_gchandle_get_target + 32 (mono-runtime.m:1982)
5   com.xamarin.monotouch-test    	0x00000001030a7cbf xamarin_gchandle_get_target + 47 (runtime.m:2721)
6   com.xamarin.monotouch-test    	0x00000001030aabe9 xamarin_switch_gchandle + 137 (runtime.m:1834)
7   com.xamarin.monotouch-test    	0x00000001030add4a xamarin_retain_trampoline + 42 (trampolines.m:701)
```

[runtime] There's no need to attach/detach the current thread in CoreCLR.

---

msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets

This was making the linker to not behave correctly, and apps were crashing on the simulator.

[dotnet] Sets missing ILLink parameter from Windows

---

tools/common/Application.cs
tools/common/CoreResolver.cs
tools/common/StaticRegistrar.cs
tools/mmp/driver.cs
tools/mmp/resolver.cs

* Extract the code we use to configure the assembly resolver during a normal
mmp run to make it usable for --runregistrar.
* Configure the assembly resolver we use for --runregistrar.
* Pass the assembly resolver to the registrar so that it's actually used.
* Adjust the System.Void lookup to look everywhere even if we find a corlib,
since behavior changes a bit now that we're using an assembly resolver:
* Previous behavior:
1. In .NET mode, look for a corlib named System.Private.CoreLib, and fail to find it.
2. Look in all the loaded assemblies for System.Void (and find it in System.Runtime.dll).
* Broken behavior as a result of the resolver changes:
1. Find corlib as System.Private.CoreLib.dll
2. Fail to find System.Void in System.Private.CoreLib.dll, since we'd only look in corlib.
* …

[d16-10-preview2] [mmp] Use the resolver (and configure it correctly) when using --runregistrar.

---

tools/devops/automation/templates/mac/build.yml

We should not try to use donet.config because that file is generated. Make.config contains the same info.

[CI] Fix mac tests provisioning.

---

tools/devops/automation/build-pipeline.yml
tools/devops/automation/templates/mac/stage.yml

For some reason, some of the internal hosted pools have been set without
the OS version (WRONG WRONG). The simples way is to allow to skip this
check in those pools over re-configuring all bots.
Example of tests starting: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4684353&view=logs&j=ac718a0d-597a-528b-5222-a379ea9341a1
The commit does not fix the tests, just makes sure they run.
'We can lick gravity, but sometimes the paperwork is overwhelming.'

[CI] Workaorund misconfig pools.

---

tools/devops/automation/build-pipeline.yml
tools/devops/automation/templates/mac/stage.yml

For some reason, some of the internal hosted pools have been set without
the OS version (WRONG WRONG). The simples way is to allow to skip this
check in those pools over re-configuring all bots.
'We can lick gravity, but sometimes the paperwork is overwhelming.'

[Xcode12.5][CI] Workaround misconfig pools. (#11323)

---

tools/devops/automation/build-pipeline.yml
tools/devops/automation/templates/mac/stage.yml

For some reason, some of the internal hosted pools have been set without
the OS version (WRONG WRONG). The simples way is to allow to skip this
check in those pools over re-configuring all bots.
Example of tests starting: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4684353&view=logs&j=ac718a0d-597a-528b-5222-a379ea9341a1
The commit does not fix the tests, just makes sure they run.
'We can lick gravity, but sometimes the paperwork is overwhelming.'
Backport of #11323

[d16-10] [CI] Workaround misconfig pools.

---

tools/devops/automation/templates/mac/build.yml

We should not try to use donet.config because that file is generated. Make.config contains the same info.
Backport of #11324

[xcode12.5] [CI] Fix mac tests provisioning.

---

tools/devops/automation/templates/mac/build.yml

We should not try to use donet.config because that file is generated. Make.config contains the same info.
Backport of #11324

[d16-10] [CI] Fix mac tests provisioning.

---

src/appkit.cs
tests/xtro-sharpie/macOS-AppKit.ignore

Native headers show it's null_resettable.
```objc
/// If set, the receiver will inherit the appearance of that object, as well as use KVO to observe its effectiveAppearance for changes. Typically this is used for child windows that are shown from a parent window or specific view. Defaults to NSApp.
@property (weak, null_resettable) NSObject<NSAppearanceCustomization> *appearanceSource API_AVAILABLE(macos(10.14));
```

Make NSWindow appearanceSource null allowed

---

tools/devops/automation/templates/build/build-nugets.yml

On publish error we will show a warning.

[CI] Continue on error when we cannot publish a nuget.

---

runtime/coreclr-bridge.m
runtime/delegates.t4
runtime/exports.t4
runtime/runtime.m
runtime/shared.m
runtime/trampolines-invoke.m
runtime/trampolines.m
runtime/xamarin/runtime.h
runtime/xamarin/trampolines.h
src/ObjCRuntime/Runtime.CoreCLR.cs
tools/common/StaticRegistrar.cs

This also meant reviewing calling code to make sure that MonoObject\*s are
released when they should be, which snowballed, so it basically meant
reviewing every method that returns a MonoObject\* to make sure their callers
release the returned value.
Next failure is now:
> monotouchtest[92536:15163696] Xamarin.Mac: The method xamarin_get_nsobject_flags it not implemented yet for CoreCLR
```
3   com.xamarin.monotouch-test    	0x0000000100c7a068 xamarin_assertion_message + 408 (runtime.m:1527)
4   com.xamarin.monotouch-test    	0x0000000100c7c481 xamarin_get_nsobject_flags + 33 (runtime.m:229)
5   com.xamarin.monotouch-test    	0x0000000100c7f6a7 xamarin_switch_gchandle + 247 (runtime.m:1879)
6   com.xamarin.monotouch-test    	0x0000000100c828ea xamarin_retain_trampoline + 42 …
```

[CoreCLR] Implement xamarin_gchandle_get_target.

---

tools/devops/automation/templates/build/build-nugets.yml

On publish error we will show a warning.
Backport of #11336

[d16-10] [CI] Continue on error when we cannot publish a nuget.

---

tests/xtro-sharpie/MacCatalyst-AVKit.ignore
tests/xtro-sharpie/MacCatalyst-AudioToolbox.todo
tests/xtro-sharpie/MacCatalyst-UIKit.ignore
tests/xtro-sharpie/MacCatalyst-UIKit.todo

Fixes:
?fixed-todo? Entry '!missing-pinvoke! AudioSessionAddPropertyListener is not bound' in 'MacCatalyst-AudioToolbox.todo' is not found in corresponding 'MacCatalyst-AudioToolbox.raw' file
?fixed-todo? Entry '!missing-pinvoke! AudioSessionGetProperty is not bound' in 'MacCatalyst-AudioToolbox.todo' is not found in corresponding 'MacCatalyst-AudioToolbox.raw' file
?fixed-todo? Entry '!missing-pinvoke! AudioSessionGetPropertySize is not bound' in 'MacCatalyst-AudioToolbox.todo' is not found in corresponding 'MacCatalyst-AudioToolbox.raw' file
?fixed-todo? Entry '!missing-pinvoke! AudioSessionInitialize is not bound' in 'MacCatalyst-AudioToolbox.todo' is not found in corresponding 'MacCatalyst-AudioToolbox.raw' file
?fixed-todo? Entry '!missing-pinvoke! AudioSessionSetActive is not bound' …

[release/6.0.1xx-preview4] [xtro] Update MacCatalyst todos.

---

dotnet/targets/Xamarin.Shared.Sdk.targets
runtime/coreclr-bridge.m
runtime/xamarin/runtime.h
tools/common/Driver.cs
tools/mmp/Makefile

* The generated static registration code will eventually be different.
* The generated code has to be compiled with different compiler flags.
This also required adding a new overload of xamarin_mono_object_release for the generated
code to compile.

[dotnet] Build the partial static registrar for CoreCLR.

---

src/Foundation/NSObject2.cs

Calling into Objective-C for disposed objects may crash, and calling ToString
shouldn't crash.

[NSObject] Don't call into Objective-C (the Description property) for disposed objects.

---

src/generator.cs

* Remove 1 array allocation per print statement.
* Remove 2 string concatenations per print statement.
* Don't indent empty lines.
For the generated code for watchOS, this is the difference (time-wise I wasn't
able to measure anything significant, although the memory savings are
significant):
Before:
Allocation summary
Bytes        Count  Average Type name
535.485.544    7.115.025       75 System.String
145.340.480    2.270.945       64 IKVM.Reflection.CustomAttributeData
110.149.624    1.238.394       88 System.Char[]
...
Total memory allocated: 1.793.323.536 bytes in 28.827.325d objects
After:
Allocation summary
Bytes        Count  Average Type name
494.592.328    6.624.441       74 System.String
145.340.480    2.270.945       64 IKVM.Reflection.CustomAttributeData
99.345.984 …

[generator] Improve performance for the printing inner loop.

---

tests/monotouch-test/dotnet/macOS/Info.plist

This seems to be required when running monotouch-test with lldb (!) - no idea
why it doesn't fail otherwise.

[tests] Add a bluetooth usage description to monotouch-test/macOS.

---

runtime/runtime.m
runtime/xamarin/runtime.h

This seems to be a leftover from when we were implementing support for third-party crash reporters many, many moons ago.

[runtime] Remove dead code.

---

dotnet/targets/Xamarin.Shared.Sdk.targets
tests/dotnet/Makefile

Fixed by removal of
```
<InvariantGlobalization Condition="'$(InvariantGlobalization)' == ''">false</InvariantGlobalization>
```
which is (should be) the default.
All our local usage compare with it with `true` so this likely comes from
somewhere else (sdk / runtime).
It does not really have a huge impact on build size (and the small diff
is probably the source of the crash)
* fails (17,479,981): https://gist.github.com/spouliot/6f8defb8f940e68314ba167ea76dc9bf
* works (17,502,741): https://gist.github.com/spouliot/d06f0b1b95e114fe469ce49081c70e33
Also fix target to run a release (no debug) build, which is more helpful
"out of the box" :)
Tracking issue with: https://github.com/xamarin/xamarin-macios/issues/11366

[dotnet] Fix release builds on devices

---

dotnet/targets/Xamarin.Shared.Sdk.targets

We were documenting the wrong name (fix in https://github.com/dotnet/runtime/pull/52055) which lead Sebastien to change it to the wrong one in https://github.com/xamarin/xamarin-macios/commit/095b7e1105268d1a82f300a7f4fd449b4968de64
/cc @spouliot @marek-safar @steveisok

[dotnet][msbuild] Fix property for native http handler

---

msbuild/Xamarin.MacDev.Tasks.Core/Tasks/XamarinTask.cs

Build failures will now include things like this for quiet builds:
Tool xcrun execution finished (exit code = 1).
Undefined symbols for architecture x86_64:
"_GlobalizationNative_LoadICUData", referenced from:
-u command line option
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

[msbuild] Show tool output with high importance if the tool fails.

---

runtime/coreclr-bridge.m
runtime/mono-runtime.h.t4
runtime/monovm-bridge.m
runtime/runtime.m
runtime/trampolines-invoke.m
runtime/trampolines.m
runtime/xamarin/runtime.h

> monotouchtest[11840:18773601] Xamarin.Mac: The method mono_method_get_class has not been implemented for CoreCLR.
```
3   com.xamarin.monotouch-test          0x000000010ac2d3e8 xamarin_assertion_message + 408 (runtime.m:1521)
4   com.xamarin.monotouch-test          0x000000010abfcda1 mono_method_get_class + 33 (mono-runtime.m:2182)
5   com.xamarin.monotouch-test          0x000000010ac306b3 xamarin_check_for_gced_object + 51 (runtime.m:719)
6   com.xamarin.monotouch-test          0x000000010ac89e14 native_to_managed_trampoline_30(objc_object*, objc_selector*, _MonoObject**, unsigned int) + 212 (Microsoft.macOS.registrar.coreclr.x86_64.m:1360)
7   com.xamarin.monotouch-test          0x000000010ac89f9c -[__MonoMac_NSActionDispatcher xamarinApplySelector] + 44 …
```

[runtime] Implement xamarin_get_reflection_method_method for CoreCLR.

---

src/Makefile.generator

Ship all files published by 'dotnet publish' for bgen, not only files prefixed
by 'bgen*'. This way we ship Mono.Options.dll too (and we won't crash at
launch trying to look for it).
Fixes https://github.com/xamarin/xamarin-macios/issues/11269.
Backport of #11362

[release/6.0.1xx-preview4] [bgen] Ship all files published by 'dotnet publish' for bgen. Fixes #11269.

---

tools/devops/automation/build-pipeline.yml

This also brings in the latest changes for provisionator; specifically https://github.com/xamarin/provisionator/pull/402 to unblock builds.
Backport of #11377

[release/6.0.1xx-preview4] [CI] Enable setting provisionator channel as parameter

---

tools/devops/automation/build-pipeline.yml

This also brings in the latest changes for provisionator; specifically https://github.com/xamarin/provisionator/pull/402 to unblock builds.
Backport of #11377

[d16-10] [CI] Enable setting provisionator channel as parameter

---

dotnet/targets/Xamarin.Shared.Sdk.targets

so it must remain using invariant globalization until it becomes
available
ref: https://github.com/xamarin/xamarin-macios/issues/11392

[dotnet][p4] Catalyst does not support ICU (yet)

---

tests/monotouch-test/System.Net.Http/NetworkResources.cs
tests/monotouch-test/example.pac

[Tests] Update xamarin domain to make tests not fail.

---

tests/monotouch-test/System.Net.Http/NetworkResources.cs
tests/monotouch-test/example.pac

[release/6.0.1xx-preview4] [Tests] Update xamarin domain to make tests not fail.

---

tests/monotouch-test/System.Net.Http/NetworkResources.cs
tests/monotouch-test/example.pac

[d16-10] [Tests] Update xamarin domain to make tests not fail.

---

tests/monotouch-test/System.Net.Http/NetworkResources.cs
tests/monotouch-test/example.pac

[xcode12.5] [Tests] Update xamarin domain to make tests not fail.

---

tests/monotouch-test/System.Net.Http/NetworkResources.cs
tests/monotouch-test/example.pac

[d16-9] [Tests] Update xamarin domain to make tests not fail.

---

msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets

Backport:
* [dotnet] Fixes _RunILLink from Windows for Preview 4 (#11390)
There were some changes on the original target.
* [dotnet] Sets missing ILLink parameter from Windows (#11319)
This was making the linker to not behave correctly, and apps were crashing
on the simulator.

[release/6.0.1xx-preview4] [dotnet] Fixes _RunILLink from Windows for Preview 4

---

tools/mlaunch/Makefile

We don't need mlaunch for MacCatalyst.

[mlaunch] Don't ship for MacCatalyst.

---

Xamarin.iOS.sln
tests/mtouch/Makefile
tests/mtouch/SdkTest.cs
tests/mtouch/mtouchtests.csproj
tests/mtouch/mtouchtests.sln
tests/tests.sln
tests/xharness/Jenkins/NUnitTestTasksEnumerable.cs
tools/common/ErrorHelper.tools.cs

This makes it easier to test localized strings used in mtouch, since we don't have
to replicate the build for all the resources.
This required a few changes to avoid including code in the mtouch tests that already
exists in the mtouch executable.
Also rename the mtouch test project to mtouchtests.csproj.
This way the test project can reference the actual mtouch.csproj without
causing conflicts due to having two projects with the same name.

[tests] Make the mtouch test project reference the actual mtouch project.

---

runtime/coreclr-bridge.m
runtime/delegates.t4
runtime/exports.t4
runtime/runtime.m
runtime/trampolines.m
src/ObjCRuntime/Runtime.CoreCLR.cs

> monotouchtest[54859:22963055] Xamarin.Mac: The method mono_object_isinst has not been implemented for CoreCLR.
```
3   com.xamarin.monotouch-test    	0x0000000101777e78 xamarin_assertion_message + 408 (runtime.m:1516)
4   com.xamarin.monotouch-test    	0x0000000101747435 mono_object_isinst + 37 (mono-runtime.m:2038)
5   com.xamarin.monotouch-test    	0x000000010177b4de verify_cast(_MonoObject*, _MonoObject*, objc_class*, objc_selector*, _MonoObject*, void**) + 78 (runtime.m:694)
6   com.xamarin.monotouch-test    	0x000000010177b35d xamarin_check_for_gced_object + 125 (runtime.m:723)
7   com.xamarin.monotouch-test    	0x00000001017d4c84 native_to_managed_trampoline_30(objc_object*, objc_selector*, _MonoObject**, unsigned int) + 212 …
```

[runtime] Implement mono_object_get_class for CoreCLR.

---

runtime/coreclr-bridge.m
runtime/delegates.t4
runtime/exports.t4
src/ObjCRuntime/Runtime.CoreCLR.cs

> monotouchtest[8307:20722735] Xamarin.Mac: The method mono_runtime_invoke has not been implemented for CoreCLR.
```
* frame #0: 0x00007fff2059b462 libsystem_kernel.dylib`__pthread_kill + 10
frame #1: 0x00007fff205c9610 libsystem_pthread.dylib`pthread_kill + 263
frame #2: 0x00007fff2051c720 libsystem_c.dylib`abort + 120
frame #3: 0x0000000100044ab8 monotouchtest`xamarin_assertion_message(msg="The method %s has not been implemented for CoreCLR.\n") at runtime.m:1474:2
frame #4: 0x0000000100013f0d monotouchtest`mono_runtime_invoke(method=0x0000000100e5afe0, obj=0x0000000100e5afd0, params=0x00007ffeefbfdd28, exc=0x0000000000000000) at mono-runtime.m:1946:2
frame #5: 0x00000001000a1a69 monotouchtest`native_to_managed_trampoline_30(self=0x0000000100e5bad0, …
```

[runtime] Implement mono_object_isinst for CoreCLR.

---

tools/devops/automation/templates/build/build-nugets.yml

Do not publish the nugets that have been created in a PR build. The
build results can be accessed from the comment once completed. This way
we make sure that next builds do not have conflicts when publishing the
nugets.

[CI] Do not clutter the nuget feed with PR build nugets.

---

tools/devops/automation/publish-ci-html-results.yml
tools/devops/automation/publish-pr-html-results.yml
tools/devops/automation/templates/build/configure.yml
tools/devops/automation/templates/publish-html-result.yml

Create two pipelines that will be triggered when a new build is
completed and contains tests results. There are some important details:
1. pipeline triggers have to specify all branches or a subset. We use
tags to trigger for PRs.
2. Tags are and, not or, so we need to pipelines (lame lame).
Due to 2. we add a new tag to identify ci builds.

[CI] Create post pipelines that will publish html results.

---

builds/Makefile
dotnet/targets/Xamarin.Shared.Sdk.props
msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DetectSdkLocationCoreTaskBase.cs
msbuild/Xamarin.Shared/Xamarin.Shared.props
msbuild/Xamarin.Shared/Xamarin.Shared.targets
msbuild/Xamarin.iOS.Tasks.Core/Tasks/DetectSdkLocationsTaskBase.cs

We do this by setting the _XamarinSdkRoot variable in our .NET logic, which
our existing shared build logic reads, passes to the DetectSdkLocations task,
and then sets our override environment variable (MD_MTOUCH_SDK_ROOT /
XAMMAC_FRAMEWORK_PATH) to the install location, so that existing code (which
honors the override variable) continues to work as-is.
We also need to ship the buildinfo file in each Sdk NuGet.
Fixes https://github.com/xamarin/xamarin-macios/issues/10827.

[msbuild/dotnet] Fix build logic when using .NET to not try to use nor require any version of installed Xamarin.iOS/Xamarin.Mac. Fixes #10827.

---

tools/dotnet-linker/Steps/RegistrarStep.cs

So we generate this, inside `registrar.mm`, for a simple app
```objc
static const char *__xamarin_registration_assemblies []= {
"MySingleView",
"System.Runtime.Serialization.Formatters",
"System.Runtime",
"System.Private.CoreLib",
"Xamarin.iOS"
};
```
instead of
```objc
static const char *__xamarin_registration_assemblies []= {
"MySingleView",
"Microsoft.CSharp",
"Microsoft.VisualBasic.Core",
"Microsoft.VisualBasic",
"Microsoft.Win32.Primitives",
"Microsoft.Win32.Registry",
"System.AppContext",
"System.Buffers",
"System.Collections.Concurrent",
"System.Collections.Immutable",
"System.Collections.NonGeneric",
"System.Collections.Specialized",
"System.Collections",
"System.ComponentModel.Annotations",
"System.ComponentModel.DataAnnotations",
"System.ComponentModel.EventBasedAsync", …
```

[dotnet][linker] Only register assemblies that we're not deleting from the bundle

---

runtime/coreclr-bridge.m

This eases debugging when trying to figure out what went wrong.

[runtime] Print more information about the exception for unhandled managed exceptions.

---

tools/devops/automation/templates/build/build-nugets.yml

Do not publish the nugets that have been created in a PR build. The
build results can be accessed from the comment once completed. This way
we make sure that next builds do not have conflicts when publishing the
nugets.
Backport of #11428

[d16-10] [CI] Do not clutter the nuget feed with PR build nugets.

---

tests/dotnet/.gitignore
tests/dotnet/Makefile
tools/app-compare/AppComparer.cs

- Make git ignore the generated `report.md`
- Fix `.aotdata` reported total size in reports (was always 0)
- Add option to strip the dotnet app bundle (until [1]) so it's easier to compare with _oldnet_ sizes.
[1] https://github.com/xamarin/xamarin-macios/issues/11445

[tests][dotnet] A few helping touch to do size comparison

---

tools/devops/automation/templates/mac/build.yml

The test was merge with the xammac_tests in commit
https://github.com/xamarin/xamarin-macios/commit/93bbfe7a86abaaef369d884ad397f590ecd409af
but we did not have the tests running to know.
This should fix some of the failures we have in older macs.

[CI] Remove apitest from the tests executed in older macs.

---

runtime/coreclr-bridge.m
runtime/delegates.t4
runtime/exports.t4
runtime/monovm-bridge.m
src/ObjCRuntime/Runtime.CoreCLR.cs
tools/mtouch/Errors.resx
tools/mtouch/xlf/Errors.cs.xlf
tools/mtouch/xlf/Errors.de.xlf
tools/mtouch/xlf/Errors.es.xlf
tools/mtouch/xlf/Errors.fr.xlf
tools/mtouch/xlf/Errors.it.xlf
tools/mtouch/xlf/Errors.ja.xlf
tools/mtouch/xlf/Errors.ko.xlf
tools/mtouch/xlf/Errors.pl.xlf
tools/mtouch/xlf/Errors.pt-BR.xlf
tools/mtouch/xlf/Errors.ru.xlf
tools/mtouch/xlf/Errors.tr.xlf
tools/mtouch/xlf/Errors.zh-Hans.xlf
tools/mtouch/xlf/Errors.zh-Hant.xlf

> monotouchtest[57078:31039077] Xamarin.Mac: The method mono_method_signature has not been implemented for CoreCLR.
```
3   com.xamarin.monotouch-test          0x00000001002c5828 xamarin_assertion_message + 408 (runtime.m:1446)
4   com.xamarin.monotouch-test          0x0000000100294d61 mono_method_signature + 33 (mono-runtime.m:2090)
5   com.xamarin.monotouch-test          0x00000001002d2f2c xamarin_invoke_trampoline + 1132 (trampolines-invoke.m:183)
6   com.xamarin.monotouch-test          0x00000001002dc777 xamarin_arch_trampoline + 119 (trampolines-x86_64.m:491)
7   com.xamarin.monotouch-test          0x00000001002dd9de xamarin_x86_64_common_trampoline + 118 (trampolines-x86_64-asm.s:51)
8   com.xamarin.monotouch-test          0x00000001002ce421 …
```

[runtime] Implement mono_runtime_invoke for CoreCLR.

---

dotnet/Microsoft.iOS.Windows.Sdk/targets/Microsoft.iOS.Windows.Sdk.props
dotnet/targets/Xamarin.Shared.Sdk.props
msbuild/Xamarin.Shared/Xamarin.Shared.targets

This task ends up setting as env variable the Xamarin Sdk root directory on the Mac, but when building from Windows it was setting the Windows path, so instead we need to override it with the proper value on macOS.
This should not change the original behavior when building from macOS.

[dotnet] Fix _DetectSdkLocations from Windows

---

src/ILLink.LinkAttributes.xml.in

This is removed _too soon_ and we end up not linking with the native
library, which makes the build fail.
Fixes https://github.com/xamarin/xamarin-macios/issues/11456

[dotnet][linker] Do not remove `[LinkWith]` using xml

---

runtime/coreclr-bridge.m
runtime/delegates.t4
runtime/exports.t4
runtime/mono-runtime.h.t4
runtime/monovm-bridge.m
runtime/runtime.m
runtime/trampolines-invoke.m
runtime/xamarin/coreclr-bridge.h
runtime/xamarin/runtime.h
src/ObjCRuntime/Runtime.CoreCLR.cs

Next failure:
> monotouchtest[10753:31976403] Xamarin.Mac: The method mono_class_from_mono_type has not been implemented for CoreCLR
```
3   com.xamarin.monotouch-test    	0x00000001053353f8 xamarin_assertion_message + 408 (runtime.m:1448)
4   com.xamarin.monotouch-test    	0x00000001053041f1 mono_class_from_mono_type + 33 (mono-runtime.m:1832)
5   com.xamarin.monotouch-test    	0x0000000105343641 xamarin_invoke_trampoline + 3809 (trampolines-invoke.m:339)
6   com.xamarin.monotouch-test    	0x000000010534c667 xamarin_arch_trampoline + 119 (trampolines-x86_64.m:491)
7   com.xamarin.monotouch-test    	0x000000010534d8ce xamarin_x86_64_common_trampoline + 118 (trampolines-x86_64-asm.s:51)
8   com.xamarin.monotouch-test    	0x000000010533e0c1 xamarin_copyWithZone_trampoline2 + 113 …
```

[runtime] Implement mono_method_signature and related signature methods for CoreCLR.

---

tools/devops/automation/templates/mac/build.yml

The test was merge with the xammac_tests in commit
https://github.com/xamarin/xamarin-macios/commit/93bbfe7a86abaaef369d884ad397f590ecd409af
but we did not have the tests running to know.
This should fix some of the failures we have in older macs.
Backport of #11452

[d16-10] [CI] Remove apitest from the tests executed in older macs.

---

dotnet/WindowsTargets/Xamarin.Shared.Sdk.Before.targets
dotnet/targets/Xamarin.Shared.Sdk.props
msbuild/Xamarin.Shared/Xamarin.Shared.targets

This task ends up setting as env variable the Xamarin Sdk root directory on the Mac, but when building from Windows it was setting the Windows path, so instead we need to override it with the proper value on macOS.
This should not change the original behavior when building from macOS.
Backport of #11451.

[release/6.0.1xx-preview4] [dotnet] Fix _DetectSdkLocations from Windows.

---

tools/devops/automation/templates/mac/build.yml

We are using vms for older machines, this results in certain tests that required hardware to fail, how can we skip those? If we find that there is a manufacturer that matches a known VM vendor, we set it in an env var.
Once this is landed, we can change tests to be skipped in vms. I just have 2 vendors I have tested this with, if anyone has another, we can add it.

[CI] Detect if we are running a vm and set the vendor.

---

tools/dotnet-linker/SetupStep.cs
tools/dotnet-linker/dotnet-linker.csproj
tools/linker/CoreTypeMapStep.cs
tools/linker/RegistrarRemovalTrackingStep.cs
tools/mtouch/Tuning.mtouch.cs
tools/mtouch/mtouch.csproj

The newly extracted `RegistrarRemovalTrackingStep` can be used inside
`dotnet-linker` to remove the dynamic registrar (if not required by some
other code).
|    Size    | MySingleView.app |
| ----------:|------------------|
|  4,579,969 | legacy           |
| 11,182,125 | dotnet [before](https://gist.github.com/spouliot/746cd36877becd5de2ca9e255a402b87) |
| 10,760,493 | dotnet [after](https://gist.github.com/spouliot/9232bd1888c93a4664dca451d3d8481f) |

[linker] Split CoreTypeMapStep into two parts

---

tools/devops/automation/templates/build/configure.yml
tools/devops/automation/templates/build/stage.yml

I found out that we need to run OneLocBuild in every build since we need to publish the loc artifact every build once we are linked up with the Loc pipeline. 
Right now, we will only run the OneLocBuild task on Sundays and that is the only time we will be publishing the artifacts. 
(It will try to publish the artifacts every build, but since there is no OneLocBuild task running, there are no artifacts to publish).
This just moves the condition of checking for the schedule build reason from running the task to setting inputs.
*with help from @mandel-macaque

[Localization] Enabling OneLocBuild for every build

---

runtime/coreclr-bridge.m
runtime/delegates.t4
runtime/exports.t4
src/ObjCRuntime/Runtime.CoreCLR.cs

> monotouchtest[99604:32343536] Xamarin.Mac: The method xamarin_get_inativeobject_class it not implemented yet for CoreCLR
```
3   com.xamarin.monotouch-test          0x000000010379ae98 xamarin_assertion_message + 408 (runtime.m:1452)
4   com.xamarin.monotouch-test          0x00000001037abb29 xamarin_get_inativeobject_class + 25 (coreclr-bridge.m:117)
5   com.xamarin.monotouch-test          0x000000010379e229 xamarin_is_class_inativeobject + 25 (runtime.m:390)
6   com.xamarin.monotouch-test          0x00000001037a947e xamarin_invoke_trampoline + 4030 (trampolines-invoke.m:350)
7   com.xamarin.monotouch-test          0x00000001037b2507 xamarin_arch_trampoline + 119 (trampolines-x86_64.m:491)
8   com.xamarin.monotouch-test          0x00000001037b376e …
```

[runtime] Implement mono_class_is_delegate for CoreCLR.

---

tools/devops/automation/templates/mac/build.yml

The test was merge with the xammac_tests in commit
https://github.com/xamarin/xamarin-macios/commit/93bbfe7a86abaaef369d884ad397f590ecd409af
but we did not have the tests running to know.
This should fix some of the failures we have in older macs.
Backport of #11452

[release/6.0.1xx-preview4] [CI] Remove apitest from the tests executed in older macs.

---

runtime/coreclr-bridge.m
runtime/exports.t4
runtime/runtime.m
runtime/trampolines-invoke.m

This also meant reviewing calling code to make sure that the return value is
released when it should be.

[runtime] Implement mono_method_get_object for CoreCLR.

---

runtime/coreclr-bridge.m
runtime/exports.t4
runtime/runtime.m
runtime/trampolines.m

This also meant reviewing calling code to make sure that the return value is
released when it should be.

[runtime] Implement mono_class_get_type for CoreCLR.

---

tools/mtouch/TranslatedAssemblies/Errors.cs.resx
tools/mtouch/TranslatedAssemblies/Errors.de.resx
tools/mtouch/TranslatedAssemblies/Errors.es.resx
tools/mtouch/TranslatedAssemblies/Errors.fr.resx
tools/mtouch/TranslatedAssemblies/Errors.hu.resx
tools/mtouch/TranslatedAssemblies/Errors.it.resx
tools/mtouch/TranslatedAssemblies/Errors.ja.resx
tools/mtouch/TranslatedAssemblies/Errors.ko.resx
tools/mtouch/TranslatedAssemblies/Errors.nl.resx
tools/mtouch/TranslatedAssemblies/Errors.pl.resx
tools/mtouch/TranslatedAssemblies/Errors.pt-BR.resx
tools/mtouch/TranslatedAssemblies/Errors.pt-PT.resx
tools/mtouch/TranslatedAssemblies/Errors.ru.resx
tools/mtouch/TranslatedAssemblies/Errors.sv.resx
tools/mtouch/TranslatedAssemblies/Errors.tr.resx
tools/mtouch/TranslatedAssemblies/Errors.zh-Hans.resx
tools/mtouch/TranslatedAssemblies/Errors.zh-Hant.resx

Updated via:
```bash
git grep -rl "Behavior}" ./ | xargs sed -i '.back' 's/Behavior}/Behavior/g'
```

[Translations] Fix error message format with an extra brace.

---

runtime/coreclr-bridge.m
runtime/delegates.t4
runtime/exports.t4
runtime/trampolines.m
src/ObjCRuntime/Runtime.CoreCLR.cs
tools/common/StaticRegistrar.cs

This also meant reviewing calling code to make sure that the return value is
released when it should be.

[runtime] Implement mono_class_get_element_class for CoreCLR.

---

runtime/Makefile
runtime/runtime.m
runtime/trampolines-arm64-asm.s
runtime/trampolines-arm64-objc_msgSend.inc.s
runtime/trampolines-arm64-objc_msgSend.s
runtime/trampolines-arm64-objc_msgSendSuper.s
src/ObjCRuntime/DynamicRegistrar.cs
src/ObjCRuntime/Registrar.cs
tests/bindings-test/macOS/bindings-test.csproj
tests/monotouch-test/CoreFoundation/BundleTest.cs
tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
tests/monotouch-test/ObjCRuntime/TrampolineTest.cs
tests/test-libraries/testgenerator.cs
tests/xammac_tests/xammac_tests.csproj
tests/xharness/Harness.cs
tests/xharness/Jenkins/TestData.cs
tests/xharness/Jenkins/TestVariationsFactory.cs
tools/common/StaticRegistrar.cs
tools/common/Target.cs

* Implement our xamarin_dyn_objc_msgSend[Super] overrides for ARM64.
* Modify mmp to use those overrides.
* Fix an issue with the existing xamarin_arm64_common_trampoline that caused
exceptions to not unwind correctly.
* Add an ARM64 variation of xammac tests in xharness.
* Various test fixes.
There are two other issues that prevents xammac tests from turning green:
* https://github.com/xamarin/xamarin-macios/pull/11499
* https://github.com/xamarin/xamarin-macios/issues/11498
Once those are fixed/merged, then xammac tests will be green on ARM64, for both Debug and Release.
This PR is probably easiest to review commit-by-commit.

Improve support for ARM64 on macOS.

---

tests/monotouch-test/MediaAccessibility/ImageCaptioningTest.cs

This makes it so that ImageCaptioningTest.GetCaption doesn't fail because it
gets values it doesn't expect.

[tests] Make ImageCaptioningTest.SetCaption restore the original value at the end.

---

tests/xharness/Jenkins/TestData.cs
tests/xharness/Jenkins/TestVariationsFactory.cs

The CoreCLR version gets to the exact same place for ARM64 as the x86_64 version (good!).
The MonoVM version crashes at launch with:
```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_platform.dylib      	0x0000000190fbf6c8 _platform_memset_pattern16 + 296
1   libcoreclr.dylib              	0x00000001035a49a0 mono_arch_create_sdb_trampoline + 76
2   libcoreclr.dylib              	0x000000010356b6ac mini_get_breakpoint_trampoline + 80
3   libcoreclr.dylib              	0x0000000103595908 mono_arch_init + 48
4   libcoreclr.dylib              	0x00000001034db268 mini_init + 580
5   libcoreclr.dylib              	0x000000010352eae8 mono_jit_init_version + 20
6   com.xamarin.monotouch-test    	0x0000000102ca0498 xamarin_bridge_initialize + 192 (monovm-bridge.m:84)
7 …
```

[xharness] Add ARM64 variations for macOS/.NET using both MonoVM and CoreCLR.

---

runtime/coreclr-bridge.m
runtime/exports.t4
runtime/runtime.m
runtime/trampolines-invoke.m

This also meant reviewing calling code to make sure that the return value is
released when it should be.

[runtime] Implement mono_reflection_type_get_type for CoreCLR.

---

src/Foundation/NSObject2.cs
src/ObjCRuntime/Runtime.CoreCLR.cs
src/ObjCRuntime/Runtime.cs

We need additional API in CoreCLR to support toggle refs properly, and this is
in progress [1]. In the meantime, stub out parts of it, so that the process
doesn't abort. This way we'll have failing tests instead (and work in other
areas can progress, since the process doesn't abort).
[1]: https://github.com/dotnet/runtime/pull/52146

[CoreCLR] Stub out RegisterToggleRef for CoreCLR.

---

tools/devops/automation/build-pipeline.yml
tools/devops/automation/templates/build/configure.yml
tools/devops/automation/templates/build/stage.yml

This PR makes sure that when we are doing a scheduled build, we are not trying to upload test results.
This was occurring and causing issues for the localization drops/ localization team.
I ran the scheduled build in a different branch last night and the results were as expected!
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4750211&view=results

[CI] Adding changes to make sure tests are not run in scheduled builds

---

src/generator-attribute-manager.cs

Internally the generator uses `AvailabilityBaseAttribute` to make its
decisions. For `dotnet` we generated the newer `[SupportedOSPlatform]`
and `[UnsupportedOSPlatform]`.
A 3rd-party (dotnet) binding might refer to members decorated with the
newer attributes and fail the build with an error [1]. Avoiding the error
is easy (first block of the diff) but it does not make the _right_
decisions (e.g. if a member is unavailable for the platform) when
generating the code.
To fix this we need to be able to convert the new attributes into the
well know `AvailabilityBaseAttribute` subclasses. We have not spotted
such cases yet because
* the bindings pass our tests (good but extra code would not fail)
* API diff across legacy and dotnet is not yet done [2]
[1] …

[dotnet][generator] Fix creating 3rd party bindings

---

tools/linker/CoreOptimizeGeneratedCode.cs

Lack of `MONOTOUCH` define in the dotnet csproj [1] made this look for
the AppKit (XM) version.
[1] defining `MONOTOUCH` would have required several more changes.
Simplicity won!
|    Size    | MySingleView.app |
| ----------:|------------------|
|  4,579,985 | legacy           |
| 10,787,541 | dotnet [before](https://gist.github.com/02e072567595088522f376e522e22899) |
| 10,786,829 | dotnet [after](https://gist.github.com/afa5b7d4f9bb281646f050257034be11) |
There are other ways to achieve this with ILLink [2] but again:
Simplicity (by re-using) won!
[2] https://github.com/xamarin/xamarin-macios/issues/11477
```diff
--- a.cs	2021-05-12 14:17:13.000000000 -0400
+++ b.cs	2021-05-12 14:17:17.000000000 -0400
@@ -3764,13 +3764,6 @@
}
namespace UIKit
{
-	public class UIKitThreadAccessException : …
```

[dotnet][linker] Fix the elimitation of calls for `UIApplication::EnsureUIThread`

---

runtime/delegates.inc.t4
runtime/delegates.t4
runtime/mono-runtime.h.t4
runtime/trampolines.m
src/ObjCRuntime/Runtime.CoreCLR.cs

This is not the fastest implementation, but it's the simplest I could come up
with, with the target of sharing as much code as possible with MonoVM. It can
be improved later if we find out it's a slow path (these functions are not in
a common code path, very few API bindings end up here).

[runtime] Implement functions for getting and setting array elements for CoreCLR.

---

runtime/coreclr-bridge.m
runtime/delegates.t4
runtime/exports.t4
runtime/mono-runtime.h.t4
src/ObjCRuntime/Runtime.CoreCLR.cs

We need additional API in CoreCLR to support pending exception properly, and
this is in progress [1]. In the meantime, stub out parts of it, so that the
process doesn't abort. This way we'll have failing tests instead (and work in
other areas can progress, since the process doesn't abort).
[1]: https://github.com/dotnet/runtime/pull/52146

[CoreCLR] Stub out mono_runtime_set_pending_exception for CoreCLR.

---

tests/common/TestRuntime.cs
tests/introspection/ApiCtorInitTest.cs
tests/introspection/Mac/MacApiProtocolTest.cs
tests/introspection/Mac/MacApiSelectorTest.cs
tests/monotouch-test/CoreAnimation/CAOpenGLLayer.cs
tests/monotouch-test/ObjCRuntime/DelegateAndDataSourceTest.cs

There are a number of tests that do not work on VMs yet our older
machines are using virtualization. Ignore those tests since we cannot
assert if they work or not.
fixes https://github.com/xamarin/maccore/issues/2438

[Tests] Ignore tests that fail on VMs

---

runtime/runtime.m

Passing a 'MonoObject*' to a function that expects a GCHandle doesn't quite
work, so make sure to get a GCHandle for the exception we want to print
information about.

[runtime] Fix call to xamarin_print_all_exceptions.

---

runtime/exports.t4
runtime/trampolines.m

This makes it easier for CoreCLR. Also, at least for CoreCLR, it's unlikely to
be slower, since we'd have to compute the MONO_TYPE_* value in any
compatibility function.

[runtime] Refactor xamarin_get_nsnumber_converter to use string comparisons instead of mono_type_get_type.

---

src/MediaToolbox/MTAudioProcessingTap.cs

CoreCLR doesn't support it.
Ref: https://github.com/dotnet/runtime/issues/32963

[MediaToolbox] Don't use Action<T> in reverse P/Invokes.

---

tests/introspection/ApiPInvokeTest.cs

Those were likely removed when we excluded the tests from Catalyst

[tests][intro] Add back `[Test]` on some methods

---

tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
tests/monotouch-test/dotnet/iOS/monotouch-test.csproj
tests/monotouch-test/dotnet/macOS/monotouch-test.csproj
tests/monotouch-test/dotnet/tvOS/monotouch-test.csproj
tests/xharness/Jenkins/TestVariationsFactory.cs

The registrar removal was fixed recently but the test was still failing.
Turns out xharness modify the linker setting for this test (as the
linker is required for this optimization) but the newer dotnet csproj
did not have an entry (to modify).
Fixes https://github.com/xamarin/xamarin-macios/issues/10512

[dotnet][tests] Fix monotouch-test RegistrarRemoval

---

tools/devops/automation/scripts/bash/vsts-compare.sh
tools/devops/automation/templates/build/api-diff.yml
tools/devops/automation/templates/build/download-artifacts.yml
tools/devops/automation/templates/build/stage.yml
tools/devops/automation/templates/build/upload-vsdrops.yml

If can happen that when we bump xcode we do not get an api & generator
diff. This results in a set of cascading events that make the build
fail.
We know track when the result is not 0, store it in a var and pass that
variable to all the tempaltes that need it. The pwsh script already has
an if to check if the file if present and if not, it shows a warning.

[CI] If the api & generator is not built do not fail the build.

---

msbuild/Xamarin.MacDev.Tasks.Core/Tasks/MetalTaskBase.cs

This makes monotouch-test's Metal test file compile for Mac Catalyst.

[msbuild] Add support for smelting metal for Mac Catalyst.

---

runtime/coreclr-bridge.m
runtime/delegates.t4
runtime/monovm-bridge.m
runtime/trampolines.m
runtime/xamarin/runtime.h
src/ObjCRuntime/Runtime.CoreCLR.cs

* Remove a few unused xamarin_get_*_class functions.
* Make the remaining two (xamarin_get_[nsnumber|nsvalue]_type) return a
MonoType* instead of MonoClass* - that makes things slightly simpler for
CoreCLR (the MonoClass* return values from the previous functions were
always converted to MonoType*s anyway).
* Implement the xamarin_get_[nsnumber|nsvalue]_type functions.
* Make the existing mono_get_string_class use the new (and more generic)
xamarin_bridge_lookup_class method instead of the specific
xamarin_bridge_get_string_class (which can now be removed).

[runtime] Implement xamarin_get_[nsnumber|nsvalue]_type for CoreCLR.

---

Make.config

[d16-10] [apidiff] Bump definitions now that `xcode12.5` support is on stable

---

tests/introspection/ApiPInvokeTest.cs

* `QCall` seems to be gone
* `libSystem.Globalization.Native` symbols are part of the executable
since they come from a static library

[dotnet][tests][intro] Update ApiPInvokeTest

---

src/CoreGraphics/CGPDFOperatorTable.cs
tests/monotouch-test/CoreGraphics/PDFScannerTest.cs

* CoreCLR doesn't support generic Action delegates in reverse (P/Invokes), so
we need to find a different solution.
* The native CGPDFOperatorTable callback API is not very friendly to us,
because we can't pass it callback-specific data, which means that the
managed caller must conform to the FullAOT requirement of the managed
callback (must be a static function; must have a MonoPInvokeCallback
attribute).
* We can leverage the new function pointer syntax in C# 9 to make these
requirements enforced by the C# compiler (unmanaged function pointer +
UnmanagedCallersOnly attribute). The resulting API is still clunky to use,
but I don't see any way around that.
Fixes this monotouch-test failure with CoreCLR:
[FAIL] Tamarin : System.Runtime.InteropServices.MarshalDirectiveException : Cannot …

[CoreGraphics] Adjust CGPDFOperatorTable to not use a generic Action delegate.

---

src/AudioUnit/AUEnums.cs
src/UIKit/UIEnums.cs
src/authenticationservices.cs

They were not visible (or handled differently in `main`) but
become _small_ breaking changes once we released xcode12.5 support.

[src] Fix some breaking changes detected when bumping APIDIFF

---

src/ObjCRuntime/Runtime.CoreCLR.cs

Instead of passing a pointer to pointer to a pointer of a MonoObject to
xamarin_mono_object_retain, we pass a pointer to a MonoObject (like
xamarin_mono_object_retain expects).

[ObjCRuntime] Fix pointer logic with regards to MonoObject*s.

---

src/AudioUnit/AUEnums.cs
src/UIKit/UIEnums.cs
src/authenticationservices.cs

They were not visible (or handled differently in `main`) but
become _small_ breaking changes once we released xcode12.5 support.
Backport of #11567

[d16-10] [src] Fix some breaking changes detected when bumping APIDIFF

---

msbuild/Xamarin.iOS.Tasks.Core/Tasks/ValidateAppBundleTaskBase.cs

Due to incorrect update while adapting code for translations.
```
<data name="W0073" xml:space="preserve">
<value>The App Extension '{0}' has a CFBundleVersion ({1}) that does not match the main app bundle's CFBundleVersion ({2})
</value>
</data>
<data name="W0074" xml:space="preserve">
<value>The App Extension '{0}' has an unrecognized NSExtensionPointIdentifier value ('{1}').
</value>
</data>
```
Fixes https://github.com/xamarin/xamarin-macios/issues/11581

[msbuild] Fix error message MSBStrings.W0073 -> W0074

---

tools/common/StaticRegistrar.cs

This makes sure that we build the right thing, our shipped headers behave
differently whether CORECLR_RUNTIME is defined or not.

[registrar] Define CORECLR_RUNTIME when in the generated registrar code for CoreCLR

---

src/ObjCRuntime/Runtime.CoreCLR.cs

Fixes this unit test:
TestINativeObject: #b1
Expected: 0
But was: 140187942967200

[Runtime/CoreCLR] Only read/write a single byte for booleans when marshalling parameters in dynamic method calls for CoreCLR.

---

dotnet/targets/Xamarin.Shared.Sdk.targets

If the task that creates the native object files doesn't execute (because the
native object files already exists and are up-to-date), the resulting list of
native object files to link will be empty.
This typically happens for a rebuild: if a native linker error occurs when
linking the main executable, building again will result in a successful build,
because we wouldn't try to link the main executable again.

[dotnet] Don't use an Output property to retrieve the list of native object files to link.

---

runtime/Delegates.cs.t4
src/ILLink.Substitutions.ios.xml
src/ILLink.Substitutions.tvos.xml
src/Makefile
src/ObjCRuntime/Runtime.cs

CoreCLR is being added for macOS only. We can eliminate a lot of recent
code additions (about half a megabyte in the past week) by eliminate code
branches under `if (IsCoreCLR)`.
Unlike handling (non required at runtime) custom attributes the
`ILLink.Substitutions.xml` will vary quite a bit across platforms so we
use a unique file for each platform.

[dotnet][linker] Eliminate code that is only required for CoreCLR on iOS and tvOS

---

src/ObjCRuntime/Runtime.cs
tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
tests/monotouch-test/dotnet/macOS/monotouch-test.csproj
tests/test-libraries/Makefile
tests/test-libraries/custom-type-assembly/Makefile
tests/test-libraries/custom-type-assembly/custom-type-assembly.cs
tests/xammac_tests/xammac_tests.csproj

When checking whether a type is a user type or not, we might have to do a
dynamic check if the dynamic registrar is available. Otherwise we may run into
a situation where the static registrar ran during the app build, but then the
app loaded additional assemblies at runtime, and those assemblies contained
user types that were registered using the dynamic registrar, so the static
registrar doesn't know about those custom types (in other words: we need to
check at runtime).

[Runtime] Don't skip dynamic user type checking as long as dynamic registration is supported.

---

msbuild/Xamarin.iOS.Tasks.Core/Tasks/ValidateAppBundleTaskBase.cs

Due to incorrect update while adapting code for translations.
```
<data name="W0073" xml:space="preserve">
<value>The App Extension '{0}' has a CFBundleVersion ({1}) that does not match the main app bundle's CFBundleVersion ({2})
</value>
</data>
<data name="W0074" xml:space="preserve">
<value>The App Extension '{0}' has an unrecognized NSExtensionPointIdentifier value ('{1}').
</value>
</data>
```
Fixes https://github.com/xamarin/xamarin-macios/issues/11581
Backport of #11585

[d16-10] [msbuild] Fix error message MSBStrings.W0073 -> W0074

---

runtime/xamarin/coreclr-bridge.h

It just ends up flooding everything now because of the progress made.

[CoreCLR] Disable debug spew by default.

---

runtime/exports.t4
runtime/runtime.m
runtime/trampolines-invoke.m
tools/mtouch/Errors.resx

* One less Mono Embedding method used: good for CoreCLR.
* More consistent with the rest of our code / behavior.

[runtime] Throw a runtime exception instead of execution engine exception.

---

runtime/trampolines-arm64-objc_msgSend.inc.s

The value should never be used if everything is working fine, but if something
is wrong, then this value will at least get consistent behavior.
The visible result for us right now is that monotouch-test will fail with a
test failure instead of crashing.

[runtime] Be a bit defensive after handling Objective-C exceptions and return a consistent value.

---

src/ObjCRuntime/Runtime.cs
tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
tests/monotouch-test/dotnet/macOS/monotouch-test.csproj
tests/test-libraries/Makefile
tests/test-libraries/custom-type-assembly/Makefile
tests/test-libraries/custom-type-assembly/custom-type-assembly.cs
tests/xammac_tests/xammac_tests.csproj

When checking whether a type is a user type or not, we might have to do a
dynamic check if the dynamic registrar is available. Otherwise we may run into
a situation where the static registrar ran during the app build, but then the
app loaded additional assemblies at runtime, and those assemblies contained
user types that were registered using the dynamic registrar, so the static
registrar doesn't know about those custom types (in other words: we need to
check at runtime).
Backport of #11588.

[d16-10] [Runtime] Don't skip dynamic user type checking as long as dynamic registration is supported.

---

src/ObjCRuntime/Runtime.cs

Fixes this mmptest:
* Xamarin.ApiTest.ApiTest.AlwaysOptimizable(macOSMobile): All methods calling optimizable API must be optimizable
The method System.Boolean ObjCRuntime.Runtime::IsUserType(System.IntPtr) calls System.Boolean ObjCRuntime.Runtime::get_DynamicRegistrationSupported(), but it does not have a [BindingImpl (BindingImplOptions.Optimizable)] attribute.
* Xamarin.ApiTest.ApiTest.AlwaysOptimizable(macOSFull): All methods calling optimizable API must be optimizable
The method System.Boolean ObjCRuntime.Runtime::IsUserType(System.IntPtr) calls System.Boolean ObjCRuntime.Runtime::get_DynamicRegistrationSupported(), but it does not have a [BindingImpl (BindingImplOptions.Optimizable)] attribute.

[Runtime] Make Runtime.IsUserType optimizable.

---

tools/devops/automation/templates/build/download-artifacts.yml
tools/devops/automation/templates/build/publish-html.yml
tools/devops/automation/templates/build/stage.yml
tools/devops/automation/templates/build/upload-vsdrops.yml

AZP yaml variables vs parameter is hard. The template ignores the settings of the run time variables resulting in skipping the upload and we later have urls that point nowhere. Latests comment in the commit shows we fixed this.

[CI] Fix API diff uploads since they broke when we wanted to continue on failure.

---

tools/devops/automation/templates/build/publish-html.yml
tools/devops/automation/templates/build/stage.yml

Needed since it was forgotten in the original change.
Backport of #11570

[d16-10] [CI] If api & generator fail also ignore in publish html.

---

tools/devops/automation/templates/build/configure.yml
tools/devops/automation/templates/build/stage.yml

This PR syncs the Localization branch with main on every scheduled or manual build in main.
We need this to so that the Localization branch does not get out of sync with main when the Loc team auto-merges in the Localization branch on our Sunday builds. This would create merge conflicts and cause issues on their end as well!
Example of the step in ADO working as expected found [here](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4773438&view=logs&j=d4d86769-bae0-5955-544a-0740a81efd3c&t=37c7a955-b2ad-5a60-c99a-544de5935e6f&l=70). 
Help from @cadsit and inspired from our folks on the Akvelon INC team!

[Localization] Sync Localization branch with Main

---

tests/monotouch-test/Security/SecureTransportTest.cs

The underlying size of the SslCipherSuite is wrong, so the test fails.
Ref: https://github.com/xamarin/xamarin-macios/issues/11498

[monotouch-test] Ignore the SslSupportedCiphers test on .NET due to #11498.

---

runtime/delegates.t4
src/ObjCRuntime/Runtime.CoreCLR.cs

The native xamarin_bridge_get_method_declaring_type method and the
corresponding managed method (GetMethodDeclaringType) takes and returns a
MonoObject*, not a GCHandle.
Due to the wonders of void pointers, this worked just fine before - there's no
actual change to the compiled code - but the code is now more consistent and
less confusing.

[runtime] Fix declaration of xamarin_bridge_get_method_declaring_type.

---

tests/api-shared/ObjCRuntime/RegistrarTest.cs
tests/monotouch-test/ObjCRuntime/ExceptionsTest.cs
tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
tests/monotouch-test/ObjCRuntime/RuntimeTest.cs

This makes monotouch-test green when using CoreCLR, both when using the
dynamic and the static registrar.
Ref: https://github.com/xamarin/xamarin-macios/issues/10940

[monotouch-test] Ignore tests that require exception marshalling on CoreCLR for now, they fail.

---

runtime/coreclr-bridge.m
runtime/exports.t4
runtime/monovm-bridge.m
runtime/runtime.m
runtime/xamarin/runtime.h

This makes it simpler to implement the toggle ref logic for CoreCLR once we can
do that.

[runtime] Refactor the toggle ref code to separate MonoVM-specific code and generic logic.

---

runtime/exports.t4

We don't used these mono functions anymore.

[runtime] Remove the declarations for mono_jit_parse_options and mono_gc_max_generation.

---

tools/mmp/Makefile

We already define it in the generated code, so the native compiler shows a warning:
Microsoft.macOS.registrar.coreclr.x86_64.m:1:9: warning: 'CORECLR_RUNTIME' macro redefined [-Wmacro-redefined]
#define CORECLR_RUNTIME
^
<command line>:2:9: note: previous definition is here
#define CORECLR_RUNTIME 1
^

[mmp] Don't define CORECLR_RUNTIME when compiling the partial static registrar code

---

src/AdSupport/ASCompat.cs
src/adsupport.cs
src/frameworks.sources
tests/xtro-sharpie/MacCatalyst-AdSupport.ignore
tests/xtro-sharpie/MacCatalyst-AdSupport.todo

also found out an API was removed by Apple... turned it into
a stub for compatibility.

[catalyst][adsupport] Update xtro - framework is not available

---

src/ILLink.Substitutions.ios.xml
src/ILLink.Substitutions.tvos.xml
tests/linker/ios/link sdk/LinkSdkRegressionTest.cs

The debug code is removed only on release builds.
Unlike the _legacy_ linker the method itself is still present (not
removed) from the assembly - but it will be empty (no code).
Unit test was adapted to work under all conditions.
Fixes https://github.com/xamarin/xamarin-macios/issues/9613

[dotnet][linker] Use substitution files to remove UIButton debug code

---

src/Makefile

Before:
$ grep Revision build/*/Constants.cs
build/ios/Constants.cs:         internal const string Revision = "170 (main: cdef4823199";
build/mac/Constants.cs:         internal const string Revision = "170 (main: cdef4823199";
build/maccatalyst/Constants.cs: internal const string Revision = "170 (main: cdef4823199";
build/tvos/Constants.cs:        internal const string Revision = "170 (main: cdef4823199";
build/watch/Constants.cs:       internal const string Revision = "170 (main: cdef4823199";
After:
$ grep Revision build/*/Constants.cs
build/ios/Constants.cs:         internal const string Revision = "170 (main: 746748bec2d)";
build/mac/Constants.cs:         internal const string Revision = "170 (main: 746748bec2d)";
build/maccatalyst/Constants.cs: internal const string Revision = "170 …

[src] Fix revision part of version string to have matching parenthesis.

---

tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
tests/test-libraries/custom-type-assembly/Makefile

It's a bit weird to build it twice, but it's the most straight forward way of
making the test work if either the .NET build or the legacy build is disabled.

[tests] Build the custom-type-assembly separately for .NET

---

msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
msbuild/Xamarin.iOS.Tasks/Tasks/PrepareNativeReferences.cs

Fixes problems when building watchOS apps and binding libraries from Windows.
Backport of #11619

[d16-10] [msbuild] Fixes build errors from Windows

---

msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
msbuild/Xamarin.iOS.Tasks/Tasks/PrepareNativeReferences.cs

Fixes problems when building watchOS apps and binding libraries from Windows.

[msbuild] Fixes build errors from Windows

---

tests/Makefile
tests/common/Configuration.cs
tests/msbuild/Xamarin.MacDev.Tests/DotnetTest.cs
tests/xharness/Harness.cs
tests/xharness/IHarness.cs
tests/xharness/Jenkins/NUnitTestTasksEnumerable.cs
tests/xharness/Jenkins/TestSelector.cs
tests/xharness/Jenkins/TestTasks/BuildTool.cs
tests/xharness/Jenkins/TestTasks/BuildToolTask.cs
tests/xharness/Jenkins/TestTasks/MSBuild.cs

Allow to uses constants to ignore dotnet tests without creating a new project. 
Backport of #11604

[d16-10] [CI] Allow to ignore tests if dotnet is enabled.

---

runtime/exports.t4
runtime/mono-runtime.m.t4
runtime/monotouch-debug.m
runtime/monotouch-main.m
runtime/runtime.m

1. Mark numerous Mono Embedding API as used only by the MonoVM bridge.
2. Exclude unused code from the CoreCLR build.
* There's no tracing in CoreCLR, so no need to process the MONO_TRACE
environment variable (and set the trace options).
* There's no sdb debuggger, so that code can be skipped.
* The profiler support is very different, so skip that code too.
* We don't support AOT, nor aot data files, so skip that.
3. All of the Mono Embedding API now falls in either of these two categories:
* Only used by the MonoVM bridge.
* Has a CoreCLR implementation.
Which means that we don't need the code to generate dummy implementations
for methods that aren't in any of these two categories anymore.

[runtime] Deal with the rest of the Mono Embedding API for CoreCLR.

---

Localize/loc/pl/tools/mtouch/Errors.resx.lcl
Localize/loc/ru/tools/mtouch/Errors.resx.lcl
Localize/loc/tr/tools/mtouch/Errors.resx.lcl

LEGO: Pull request from lego/hb_dca0a672-370a-4b3c-b55f-cd146e93faf9_20210521101338226 to Localization with localized lcls

LEGO: Pull request from lego/hb_dca0a672-370a-4b3c-b55f-cd146e93faf9_20210521101338226 to Localization

---

tests/xharness/Harness.cs

Other tests are variations and therefore the logic of the test variation factory applies but the monotouch-tests for mac on dotnet do not fall in that area. Ignore if we do not have the build enabled.

[CI] Do not run monotouch mac dotnet if it is not dotnet enabled.

---

.github/workflows/localization-update.yml

This PR should allow us to receive PRs in main whenever the Loc team adds new translation to our lcl files in the 'Localization' branch.
Reasoning: The Loc team needs to be able to auto-merge these lcl file changes so they will do so in the 'Localization' branch.
We will create the PRs to main from the branch they are using to push into 'Localization' which has the prefix 'lego'. 
Therefore, we will look for 'lego/*'.

[Localization] Adding localize-update workflow

---

tests/xharness/Harness.cs

backport of https://github.com/xamarin/xamarin-macios/pull/11654

[CI] Do not run monotouch mac dotnet if it is not dotnet enabled. (#11654)

---

runtime/coreclr-bridge.m
runtime/monotouch-main.m
runtime/monovm-bridge.m
runtime/runtime-internal.h
runtime/xamarin/runtime.h
src/ObjCRuntime/Runtime.CoreCLR.cs

Implement a rudimentary way of tracking created and destroyed MonoObject*
instances, so that it's easy to find leaks.

[runtime] Add support for tracking created and destroyed MonoObject* instances for CoreCLR.

---

runtime/monotouch-main.m

The workaround doesn't work anymore anyway, this is printed on every launch:
> MonoTouch: Could not install sigaction override, unexpected sigaction implementation.
Ref: https://github.com/xamarin/maccore/commit/054bbdce96eccb353e19c0718f3187eee43b513f

[runtime] Don't include a workaround for a ancient bug anymore in .NET.

---

tools/mlaunch/Makefile

This makes us ship mlaunch in .NET again.
Backport of #11668

[release/6.0.1xx-preview5] [mlaunch] Fix conditional makefile logic.

---

runtime/trampolines.m

Before:
There were 257927 MonoObjects created, 144942 MonoObjects freed, so 112985 were not freed. (dynamic registrar)
There were 205700 MonoObjects created, 113865 MonoObjects freed, so 91835 were not freed. (static registrar)
After:
There were 257931 MonoObjects created, 235062 MonoObjects freed, so 22869 were not freed. (dynamic registrar)
There were 205700 MonoObjects created, 203983 MonoObjects freed, so 1717 were not freed. (static registrar)

[runtime] Return values from mono_array_get must be released.

---

src/ILLink.Substitutions.ios.xml
src/ILLink.Substitutions.tvos.xml
tests/linker/ios/link sdk/LinkSdkRegressionTest.cs

Both
* EnsureEventAndDelegateAreNotMismatched
* EnsureDelegateAssignIsNotOverwritingInternalDelegate
are helpers that will warn, on console, if ObjC delegates are mis-used
inside the application. Those message are not useful at runtime and we
can use ILLink's substitutions to remove the content of the checks for
release builds.

[dotnet][linker] Use substitutions to stub debug helpers in UIApplication

---

tools/devops/automation/templates/publish-html-result.yml

2 changes:
1. Make a better destination path, it was adding the full dir path
2. Remove txt files, they are large and logs that should be in vsdrops.

[CI] Remove txt files and use a better path for the static content.

---

tools/devops/automation/templates/build/sign-and-notarized.yml

We have had issues with the results from ESRP, call pkgutil to make sure everything was ok.

[CI] Verify the notarized pkgs.

---

tests/xharness/Program.cs

Fixes https://github.com/xamarin/maccore/issues/2444.

[xharness] Disable msbuild node reuse to fix issue with msbuild processes interfering with eachother.

---

tools/common/StaticRegistrar.cs

Before:
> There were 205700 MonoObjects created, 113865 MonoObjects freed, so 91835 were not freed. (static registrar)
After:
> There were 205700 MonoObjects created, 113982 MonoObjects freed, so 91718 were not freed. (static registrar)

[static registrar] Add a few missing calls to xamarin_mono_object_release for arrays.

---

dotnet/package/common.csproj

Context: https://github.com/xamarin/xamarin-android/pull/5948
Microsoft has rules for submitting signed NuGet packages with the
namespace `Microsoft.*` under the Microsoft + Xamarin organizations.
Some of these rules include:
* Package must be signed.
* Must include a license.
* `$(Authors)` should be `Microsoft`
* `$(PackageProjectUrl)` can't be blank.
* `$(Copyright)` must *exactly* say `© Microsoft Corporation. All rights reserved.`
If any of these are wrong, you'll get errors during `nuget push` such as:
Response status code does not indicate success:
400 (The package is not compliant with metadata requirements for Microsoft packages on NuGet.org.
Go to https://aka.ms/Microsoft-NuGet-Compliance for more information.
Policy violations: The package metadata is missing required …

[dotnet] publishing settings for NuGet.org

---

dotnet/package/common.csproj

Context: https://github.com/xamarin/xamarin-android/pull/5948
Microsoft has rules for submitting signed NuGet packages with the
namespace `Microsoft.*` under the Microsoft + Xamarin organizations.
Some of these rules include:
* Package must be signed.
* Must include a license.
* `$(Authors)` should be `Microsoft`
* `$(PackageProjectUrl)` can't be blank.
* `$(Copyright)` must *exactly* say `© Microsoft Corporation. All rights reserved.`
If any of these are wrong, you'll get errors during `nuget push` such as:
Response status code does not indicate success:
400 (The package is not compliant with metadata requirements for Microsoft packages on NuGet.org.
Go to https://aka.ms/Microsoft-NuGet-Compliance for more information.
Policy violations: The package metadata is missing required …

[release/6.0.1xx-preview5] [dotnet] publishing settings for NuGet.org

---

runtime/runtime.m
src/ObjCRuntime/Runtime.CoreCLR.cs
src/ObjCRuntime/Runtime.cs
tests/monotouch-test/ObjCRuntime/ExceptionsTest.cs
tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
tests/monotouch-test/ObjCRuntime/RuntimeTest.cs

This allows us to re-introduce a few tests.

[runtime] Intercept the objc_msgSend family of functions using CoreCLR's supported mechanisms.

---

tools/common/StaticRegistrar.cs

This involves storing the out parameter in an additional variable, so that we
can still access it after the method call.
Before:
There were 257927 MonoObjects created, 235060 MonoObjects freed, so 22867 were not freed. (dynamic registrar)
There were 205700 MonoObjects created, 203983 MonoObjects freed, so 1717 were not freed. (static registrar)
After:
There were 257935 MonoObjects created, 235064 MonoObjects freed, so 22871 were not freed. (dynamic registrar)
There were 205700 MonoObjects created, 204006 MonoObjects freed, so 1694 were not freed. (static registrar)

[static registrar] Add a missing call to xamarin_mono_object_release for out parameters.

---

tools/common/StaticRegistrar.cs

Before:
There were 258046 MonoObjects created, 235142 MonoObjects freed, so 22904 were not freed. (dynamic registrar)
There were 205804 MonoObjects created, 204193 MonoObjects freed, so 1611 were not freed. (static registrar)
After:
There were 258018 MonoObjects created, 235128 MonoObjects freed, so 22890 were not freed. (dynamic registrar)
There were 205809 MonoObjects created, 204221 MonoObjects freed, so 1588 were not freed. (static registrar)

[static registrar] Add a missing call to xamarin_mono_object_release for return values from mono_value_box.

---

src/ILLink.Substitutions.ios.xml

ref: https://github.com/xamarin/maccore/issues/2446

[dotnet][linker] Use signature (not name) for iOS substitutions (just like tvOS)

---

tests/xharness/Program.cs

Fixes https://github.com/xamarin/maccore/issues/2444.
Backport of #11689

[release/6.0.1xx-preview5] [xharness] Disable msbuild node reuse to fix issue with msbuild processes interfering with eachother.

---

runtime/monotouch-main.m

Due to the following reasons:
* Desktop apps like macOS and Mac catalyst can be launched directly from the
command line by users.
* It's trivial to set environment variables for desktop apps before launching
them.
* All the different command line arguments we support for mobile targets can
also be set using environment variables.
We don't need additional command line argument parsing for desktop platforms,
so just remove it.
The end result is that instead of doing this to run a specific unit test:
path/to/macOS/app/MacOS/Contents/theapp --app-arg --test --app-arg MyTestFixture
This will now work:
path/to/macOS/app/MacOS/Contents/theapp --test MyTestFixture
Which is how apps on desktop platforms should work anyway.

[runtime] Skip custom command line argument parsing for macOS and Mac Catalyst.

---

src/Foundation/NSAutoreleasePool.cs

It's not trivial to do now, because the existing constructors are public,
which the generator isn't able to re-create without modifications (to the
generator).
So just add a reminder instead.

[Foundation] Add reminder about NSAutoreleasePool.

---

runtime/trampolines.m

Before:
There were 258046 MonoObjects created, 235142 MonoObjects freed, so 22904 were not freed. (dynamic registrar)
There were 205804 MonoObjects created, 204193 MonoObjects freed, so 1611 were not freed. (static registrar)
After:
There were 258054 MonoObjects created, 235172 MonoObjects freed, so 22882 were not freed. (dynamic registrar)
There were 205804 MonoObjects created, 204193 MonoObjects freed, so 1611 were not freed. (static registrar)

[registrar] Return values from mono_value_box must be released.

---

.github/workflows/github-page-clean-up.yml

To keep the github  webpage small we remove the data once the PR has
been closed (that means closed or merged). The data will be kept in
vsdrops, the only links that will stop working are those from the github
static webpage.
Since we are interested in making the reviewer life better this is a
good compromise.
How to avoif merge conflicts:
We want to make sure we avoid merge conflicts, this is done using two
locks:
1. macios.ci-cleanup - Lock in the xamarin-macios action that will
ensure that we create a new branch to cleanup the data.
2. ci-results - Lock in the macios.ci action that will merge branhces
one by one.
This repo will create a new pr that cleans the data, the macios.ci repo
will execute an action when this new branch is created and will merge it
as soon as possible making …

[Actions] Clean data after a PR is closed.

---

tools/common/StaticRegistrar.cs

This fixes a memory corruption where we'd try to process out parameters when
an exception had occurred, and those out parameters weren't expected to be
processed.

[static registrar] Go straight to exception handling after invoking the managed method if an exception occurred.

---

runtime/runtime.m
runtime/trampolines.m
tools/common/StaticRegistrar.cs

Before:
There were 258046 MonoObjects created, 235142 MonoObjects freed, so 22904 were not freed. (dynamic registrar)
There were 205804 MonoObjects created, 204193 MonoObjects freed, so 1611 were not freed. (static registrar)
After:
There were 258054 MonoObjects created, 235172 MonoObjects freed, so 22882 were not freed. (dynamic registrar)
There were 205804 MonoObjects created, 205190 MonoObjects freed, so 614 were not freed. (static registrar)

[registrar] Make sure to release the return value from xamarin_get_parameter_type.

---

tests/Makefile
tests/common/DotNet.cs
tests/dotnet/Makefile
tests/dotnet/NativeDynamicLibraryReferencesApp/Makefile
tests/dotnet/NativeFileReferencesApp/Makefile
tests/dotnet/NativeFrameworkReferencesApp/Makefile
tests/dotnet/NativeXCFrameworkReferencesApp/Makefile
tests/monotouch-test/dotnet/macOS/Makefile
tests/perftest/Makefile
tests/xharness/Jenkins/TestTasks/MSBuildTask.cs

[release/6.0.1xx-preview5] [dotnet] Remove the .NET workload resolver workaround, it's not needed anymore.

---

runtime/trampolines-invoke.m

Before:
There were 258042 MonoObjects created, 235166 MonoObjects freed, so 22876 were not freed. (dynamic registrar)
There were 205804 MonoObjects created, 204219 MonoObjects freed, so 1585 were not freed. (static registrar)
After:
There were 258058 MonoObjects created, 235308 MonoObjects freed, so 22750 were not freed. (dynamic registrar)
There were 205804 MonoObjects created, 204219 MonoObjects freed, so 1585 were not freed. (static registrar)

[dynamic registrar] Out parameters must be released.

---

runtime/trampolines.m

Before:
There were 258042 MonoObjects created, 235166 MonoObjects freed, so 22876 were not freed. (dynamic registrar)
There were 205804 MonoObjects created, 204219 MonoObjects freed, so 1585 were not freed. (static registrar)
After:
There were 258050 MonoObjects created, 235177 MonoObjects freed, so 22873 were not freed. (dynamic registrar)
There were 205804 MonoObjects created, 204219 MonoObjects freed, so 1585 were not freed. (static registrar)

[runtime] The return value from mono_class_from_mono_type must be released.

---

runtime/runtime.m
runtime/trampolines-invoke.m

Before:
There were 258042 MonoObjects created, 235166 MonoObjects freed, so 22876 were not freed. (dynamic registrar)
There were 205804 MonoObjects created, 204219 MonoObjects freed, so 1585 were not freed. (static registrar)
After:
There were 258066 MonoObjects created, 246781 MonoObjects freed, so 11285 were not freed. (dynamic registrar)
There were 205804 MonoObjects created, 204491 MonoObjects freed, so 1313 were not freed. (static registrar)

[dynamic registrar] Free the return value from mono_signature_get_params and mono_signature_get_return_type.

---

runtime/coreclr-bridge.m
runtime/runtime.m
runtime/xamarin/coreclr-bridge.h
src/ObjCRuntime/Runtime.CoreCLR.cs
src/ObjCRuntime/Runtime.cs
tests/common/TestRuntime.cs
tests/monotouch-test/ObjCRuntime/RegistrarTest.cs

* This also required an empty implementation of the toggle ref machinery,
because the ObjectiveCMarshal.Initialize call to initialize unhandled
exception support requires passing toggle ref callbacks as well. The
complete implementation is more complex, and will come in an uncoming PR.
* The TestConstrainedGenericType test can now be re-enabled, after a few
updates.

[runtime] Complete support for exception marshalling on CoreCLR.

---

src/ObjCRuntime/Runtime.CoreCLR.cs

Fixes this unit test:
[FAIL] ManagedExceptionPassthrough :   exception
Expected: same as <System.ApplicationException: 3,14
at MonoTouchFixtures.ObjCRuntime.ExceptionsTest.ManagedExceptionTest.ThrowManagedException() in xamarin-macios/tests/monotouch-test/ObjCRuntime/ExceptionsTest.cs:line 128>
But was:  <System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.ApplicationException: 3,14
at MonoTouchFixtures.ObjCRuntime.ExceptionsTest.ManagedExceptionTest.ThrowManagedException() in xamarin-macios/tests/monotouch-test/ObjCRuntime/ExceptionsTest.cs:line 128
at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions) …

[ObjCRuntime] Unwrap TargetInvocationExceptions we get when invoking methods using reflection.

---

tests/monotouch-test/AVFoundation/AVAudioIONode.cs
tests/monotouch-test/AudioUnit/AUGraphTestMac.cs
tests/monotouch-test/AudioUnit/AudioUnit.cs

Fixes these failures when on a VM:
Xamarin.Mac.Tests.AudioUnitTests
[FAIL] GetCurrentDevice_Test :   Expected: True
at Xamarin.Mac.Tests.AudioUnitTests.GetCurrentDevice_Test () [0x00011] in /Users/builder/azdo/_work/1/s/xamarin-macios/tests/monotouch-test/AudioUnit/AudioUnit.cs:37
Xamarin.Mac.Tests.AudioUnitTests : 13 ms
Xamarin.Mac.Tests.AUGraphTests
[FAIL] DoTest : Did not see events after 1 second
at Xamarin.Mac.Tests.AUGraphTests.WaitOnGraphAndMixerCallbacks () [0x00050] in /Users/builder/azdo/_work/1/s/xamarin-macios/tests/monotouch-test/AudioUnit/AUGraphTestMac.cs:93
at Xamarin.Mac.Tests.AUGraphTests.DoTest () [0x0004c] in /Users/builder/azdo/_work/1/s/xamarin-macios/tests/monotouch-test/AudioUnit/AUGraphTestMac.cs:66
Xamarin.Mac.Tests.AUGraphTests : 3113 ms …

[monotouch-test] Ignore a few audio-related tests when we're running on a VM.

---

tests/common/Configuration.cs
tests/monotouch-test/ObjCRuntime/RegistrarTest.cs

It needs another assembly built from the source tree, so it won't work unless
executed from a source checkout. This way we don't try to run it on older
macOS versions, where the required assembly won't exist.

[tests] Only run the RegistrarTest.CustomUserTypeWithDynamicallyLoadedAssembly test from a source checkout.

---

dotnet/targets/Xamarin.Shared.Sdk.props
dotnet/targets/Xamarin.Shared.Sdk.targets

Tell .NET to not generate files we don't need:
* Runtime configuration file (*.runtimeconfig.json).
* Dependency file (*.deps.json).
* Reference assemblies for executable projects.
Fixes https://github.com/xamarin/xamarin-macios/issues/9687.

[dotnet] Tell .NET to not generate files we don't need. Fixes #9687.

---

tests/monotouch-test/CoreAnimation/LayerTest.cs
tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
tests/monotouch-test/mono/WeakReferenceTest.cs

This seems to be working again now.

[tests] Re-enable Mac Catalyst tests related to the GC not working.

---

runtime/monotouch-main.m
runtime/runtime.m
runtime/xamarin/runtime.h

While not strictly necessary to not leak (because the process is exiting
anyway), it makes it easier to read leak reports, because these dictionaries
won't show up as leaked memory anymore.
Before:
There were 258096 MonoObjects created, 258015 MonoObjects freed, so 81 were not freed. (dynamic registrar)
There were 205834 MonoObjects created, 205833 MonoObjects freed, so 1 were not freed. (static registrar)
After:
There were 258104 MonoObjects created, 258025 MonoObjects freed, so 79 were not freed. (dynamic registrar)
There were 205834 MonoObjects created, 205834 MonoObjects freed, so no leaked MonoObjects. (static registrar)

[runtime] Release the block_wrapper_queue and xamarin_wrapper_hash dictionaries upon process exit.

---

runtime/coreclr-bridge.m
runtime/xamarin/runtime.h
tools/common/StaticRegistrar.cs

* If the return value from xamarin_get_reflection_method_method is cached in a
static variable, we can only release at process exist.
* Otherwise just release at the end of the current method.
Before:
There were 258096 MonoObjects created, 246948 MonoObjects freed, so 11148 were not freed. (dynamic registrar)
There were 205834 MonoObjects created, 205214 MonoObjects freed, so 620 were not freed. (static registrar)
After:
There were 258092 MonoObjects created, 246945 MonoObjects freed, so 11147 were not freed. (dynamic registrar)
There were 205834 MonoObjects created, 205600 MonoObjects freed, so 234 were not freed. (static registrar)

[static registrar] Release the return value from xamarin_get_reflection_method_method in generated code.

---

runtime/coreclr-bridge.m

Before:
There were 258096 MonoObjects created, 246948 MonoObjects freed, so 11148 were not freed. (dynamic registrar)
There were 205834 MonoObjects created, 205214 MonoObjects freed, so 620 were not freed. (static registrar)
After:
There were 205834 MonoObjects created, 205222 MonoObjects freed, so 612 were not freed. (dynamic registrar)
There were 258100 MonoObjects created, 258019 MonoObjects freed, so 81 were not freed. (static registrar)

[runtime] Don't forget to free the method field in MonoMethodSignatures.

---

src/NativeTypes/Drawing.tt
src/NativeTypes/Primitives.tt
src/generator-enums.cs
src/generator-filters.cs
src/generator.cs
src/mapkit.cs
src/safariservices.cs
src/uikit.cs

In most cases this will generate the exact same IL [1].
However it will perform _better_ (like you expect) if the `==` operator
is overloaded (even more if the operator implementation is buggy).
A last, small benefit is that avoiding `==` means the linker is more
likely to be able to remove it from the final applications.
This PR only change the generated code. IOW not the generator code,
nor the manual bindings. Those should also be updated but requires
more work.
References:
[1] https://gist.github.com/spouliot/fb05e733e1f9f403de69ab3ab6bdac2b
[2] https://www.thomasclaudiushuber.com/2020/03/19/c-why-you-should-prefer-the-is-keyword-over-the-operator/

[generator] Use `is` instead of `==` when doing null checks

---

tests/xtro-sharpie/MacCatalyst-CoreMotion.ignore

The _missing_ API are for watchOS only and not available for Catalyst.

[catalyst][coremotion] Update xtro

---

tools/devops/automation/publish-pr-html-results.yml
tools/devops/automation/scripts/GitHub.psm1

We added the github pages to make the life of the reviews easier, the
issue we found is that we have a limited amount of space. Due to that we
are removing the generation from the ci.
Triggers in pipleines are disable by default, removing it will stop it
from being executed. The PR are triggered via a release pipeline we
called macios.glue

[CI] Do not generate github static pages on CI.

---

tests/common/TestRuntime.cs
tests/monotouch-test/ObjCRuntime/RuntimeTest.cs

Fixes these unit tests:
[FAIL] MX8029_b :   Message
Expected string length 217 but was 238. Strings differ at index 149.
Expected: "...lector: setIntArray:\n\tMethod: MonoTouchFixtures.ObjCRuntim..."
But was:  "...lector: setIntArray:\n\tMethod: System.Void MonoTouchFixture..."
----------------------------------------------^
at MonoTouchFixtures.ObjCRuntime.RuntimeTest.MX8029_b() in /Users/rolf/work/maccore/onedotnet/xamarin-macios/tests/monotouch-test/ObjCRuntime/RuntimeTest.cs:line 625
[FAIL] MX8033 :   Message
Expected string length 192 but was 207. Strings differ at index 129.
Expected: "...\n\tSelector: intArray\n\tMethod: MonoTouchFixtures.ObjCRuntim..."
But was:  "...\n\tSelector: intArray\n\tMethod: System.Int32[] MonoTouchFixt..."
------------------------------------------------^ …

[tests] Adjust MX8029_b and MX8033 tests to cope with slightly different exception message output for CoreCLR.

---

msbuild/Xamarin.Localization.MSBuild/README.md
src/README.md
tools/mtouch/README.md

The README.md file inside msbuild is now outdated since we switched Localization processes.
I also removed information about the source and mtouch localization from this README 
and added them to src and mtouch READMEs. I think this makes more sense, but I can change it back if preferred.

[Localization] Update Localization READMEs

---

runtime/coreclr-bridge.m

This makes it a bit easier to figure out what's going on.

[runtime] Show the typename of the MonoObjects we're leaking.

---

tools/devops/automation/templates/publish-html-result.yml

PR https://github.com/xamarin/xamarin-macios/pull/11754 created a 50+MB
for the generator diff that resulted in a 250 mb index file. This is too
large and github rejects the push. USing LFS fixes the issue.
fixes: https://github.com/xamarin/maccore/issues/2449

[CI] Use LFS for the static page checkout.

---

runtime/trampolines.m

No more leaks!
Before:
There were 205834 MonoObjects created, 205834 MonoObjects freed, so no leaked MonoObjects. (static registrar)
There were 258092 MonoObjects created, 258013 MonoObjects freed, so 79 were not freed. (dynamic registrar)
After:
✅ There were 205834 MonoObjects created, 205834 MonoObjects freed, so no leaked MonoObjects. (static registrar)
✅ There were 258100 MonoObjects created, 258100 MonoObjects freed, so no leaked MonoObjects. (dynamic registrar)

[runtime] Add missing release for call to mono_reflection_type_get_type.

---

tools/devops/automation/build-pipeline.yml

We have to list each readme as per vsts docs:
```
Tips:
* Wild cards are not supported with path filters.
* Paths are always specified relative to the root of the repository.
* If you don't set path filters, then the root folder of the repo is implicitly included by default.
* If you exclude a path, you cannot also include it unless you qualify it to a deeper folder. For example if you exclude /tools then you could include /tools/trigger-runs-on-these
* The order of path filters doesn't matter.
* Paths in Git are case-sensitive. Be sure to use the same case as the real folders.
* You cannot use variables in paths, as variables are evaluated at runtime (after the trigger has fired).
```
src:  https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#ci …

[CI] Ignore readme files and github actions.

---

runtime/coreclr-bridge.m
src/Foundation/NSObject2.cs
src/ObjCRuntime/Runtime.CoreCLR.cs
tests/common/TestRuntime.cs
tests/introspection/ApiCtorInitTest.cs
tests/monotouch-test/Foundation/ObjectTest.cs
tests/monotouch-test/ObjCRuntime/RuntimeTest.cs
tests/monotouch-test/UIKit/ControlTest.cs

The code contains comments explaining the new behavior.
Some tests that poked into the private 'flags' field on NSObject had to be
updated, because the field is now named differently in .NET.
I also added two more tests for toggle ref scenarios.

[runtime] Add support for toggle refs to CoreCLR.

---

tests/monotouch-test/HealthKit/QuantityTypeIdentifierTest.cs

It was introduced with Xcode 12.5, so ignore it on earlier OS versions.
Partial fix for #11504.

[monotouch-test] Ignore HKQuantityTypeIdentifier.AppleMoveTime on iOS versions where it didn't exist.

---

runtime/coreclr-bridge.m
tests/monotouch-test/ObjCRuntime/RuntimeTest.cs

Fixes https://github.com/xamarin/xamarin-macios/issues/11256.

[coreclr] Support for NSAutoreleasePools has now been implemented for background threads for both MonoVM and CoreCLR. Fixes #11256.

---

tests/common/TestRuntime.cs
tests/monotouch-test/AudioToolbox/SystemSoundTest.cs

Sometimes they work, sometimes they don't.
Just ignore them to avoid unreliable test results.
Partial fix for #11504.

[monotouch-test] Don't run SystemSound tests in the simulator.

---

tests/monotouch-test/monotouch-test.csproj

This means that we won't pick up generated *.cs files from the
monotouch-test/dotnet/macOS/monotouch-test.csproj project when building the
monotouch-test/monotouch-test.csproj project, which results in the C# compiler
complaining about duplicate types, or unknown types (because the generated
code is for .NET 6, while we might be compiling for legacy Xamarin).

[monotouch-test] Exclude any *.cs file in any obj subdirectory, not only the immediate subdirectory.

---

tests/dotnet/README.md
tests/dotnet/size-comparison/MySingleView/oldnet/MySingleView.csproj

Using the AOT LLVM-backend is recommended for release and should be used
when comparing sizes.
Also add some basic instruction to ease comparing `oldnet` and `dotnet`
app bundles since IL stripping is not yet available to dotnet builds (and
without considering this the _real_ numbers are a bit off)

[tests][dotnet] Update oldnet sample to use LLVM and add some instructions

---

tests/monotouch-test/AppDelegate.cs

Try to fix these warnings that show up at runtime by checking if the root view
controller is a UINavigationController, and doing the right thing:
> Unbalanced calls to begin/end appearance transitions for <...>

[monotouch-test] Try to fix a few runtime warnings about unbalanced calls to begin/end appearance transitions.

---

tests/monotouch-test/SystemConfiguration/CaptiveNetworkTest.cs

[monotouch-test] It doesn't look like the TryCopyCurrentNetworkInfo test works in the iOS 11 simulator either.

---

src/AudioToolbox/SystemSound.cs
tests/monotouch-test/AudioToolbox/SystemSoundTest.cs

This revealed an issue with the system sound bindings on CoreCLR (delegates to
P/Invokes can't be generic), which has also been fixed.

[monotouch-test] Use TestRuntime.RunAsync instead of AppDelegate.RunAsync  so that the system sound tests work on macOS as well.

---

src/CoreGraphics/CGAffineTransform.cs
src/NativeTypes/Drawing.tt

The linker cannot eliminate `Equals(Object)` [1] or `Equals(T)` [2] but it
can remove the `==` operator if unused. So avoiding `Equals` calling `==`
is beneficial.
Also avoid using properties inside `CGRect` and use the fields instead
so the getter can also be removed (if unused).
[1] it's an override on `System.Object` used in many places
[2] it's _generally_ present to satisfy `IEquatable<T>` also used in many places
```diff
--- a.cs	2021-06-01 21:20:46.000000000 -0400
+++ b.cs	2021-06-01 21:20:49.000000000 -0400
@@ -3222,22 +3222,18 @@
return $"xx:{xx:##0.0#} yx:{yx:##0.0#} xy:{xy:##0.0#} yy:{yy:##0.0#} x0:{x0:##0.0#} y0:{y0:##0.0#}";
}
-		public static bool operator ==(CGAffineTransform P_0, CGAffineTransform P_1)
-		{
-			if (P_0.xx == P_1.xx && P_0.xy == P_1.xy && P_0.yx == P_1.yx …
```

[coregraphics] Small refactor to ease removal of code by the linker

---

dotnet/targets/Xamarin.Shared.Sdk.targets

Make sure to set CopyToPublishDirectory=PreserveNewest on files we add to
'ResolvedFileToPublish', so that they're not copied unnecessarily (in the case
of the native executable it would also remove the code signature).
Fixes https://github.com/xamarin/xamarin-macios/issues/11611.

[dotnet] Make sure to set CopyToPublishDirectory=PreserveNewest on files we add to 'ResolvedFileToPublish'. Fixes #11611.

---

runtime/xamarin/monovm-bridge.h

This should have been disabled from the beginning.

[runtime] Disable LOG_MONOVM logging by default.

---

.editorconfig

An additional point here is that the 'utf-8' charset is specifically defined
to not include the byte-order-mark.
Ref: https://editorconfig.org

[editorconfig] Set the charset to utf-8.

---

tools/devops/automation/templates/build/configure.yml

- Currently, our Sunday builds need work, with respect to the OneLocBuild task.
- We want to try to keep the Localization branch up to date with main so that it does not get behind and cause issues for the Loc team.
- Right now, we try to merge main into Localization branch before the task is run but this causes merge conflicts: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4817479&view=logs&j=d4d86769-bae0-5955-544a-0740a81efd3c&t=37c7a955-b2ad-5a60-c99a-544de5935e6f&l=78
- Instead of this, we will try to remove the Localization branch and replace it with main right before our Sunday build.
We will need to replace the Localization branch every time we land an lcl translation file inside main: https://github.com/xamarin/xamarin-macios/issues/11791

[Localization] Changing the merge to a Pseudo Force Push

---

.github/workflows/localization-update.yml

Could I get a quick review on this?
I just want to point this Localization Github action to point to my test branch to make sure it is working before bringing the rest of changes to main.

[Test] Want to test this Github Action

---

dotnet/targets/Xamarin.Shared.Sdk.targets
msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets

The runtime issue has been fixed for a while now, so we don't need the
workaround anymore.
Ref: https://github.com/dotnet/runtime/issues/34637

[dotnet] Remove workaround for dotnet/runtime issue with incorrect dylibs.

---

dotnet/targets/Xamarin.Shared.Sdk.targets
tests/dotnet/UnitTests/ProjectTest.cs

Remove all the other ones from ResolvedFileToPublish.
This way we don't end up with multiple libxamarin-dotnet*.dylib files in the
app bundle.

[dotnet] Only publish a single libxamarin-dotnet*.dylib file.

---

tools/devops/automation/templates/build/configure.yml

I am kicking myself for this typo haha.
This is the first Sunday build since onboarding with the Loc team that we didn't have merge conflicts!
Therefore we should finally be able to get the Localization Translations in our repo!...
Inside the Job Preparation Parameters, we can see that `isScheduled` is true.
```
isScheduled:
Parsing expression: <eq(variables['Build.Reason'], 'Schedule')>
Evaluating: eq(variables['Build.Reason'], 'Schedule')
Expanded: eq('Schedule', 'Schedule')
Result: 'True'
```
However, the check to see if we want a PR containing the translated resx files is examining `isSchedule` is false
(since 'isSchedule' does not exist)
```
##[debug]INPUT_ISCREATEPRSELECTED: 'eq(variables.isSchedule, 'True')'
##[debug] Converted to bool: False
```

[Localization] Typo in the scheduled build

---

src/Foundation/NSDictionary.cs
src/MediaPlayer/MPNowPlayingInfoCenter.cs

Ironically my nullability changes caused this... because they are not
yet complete and the lack of `ArgumentNullException` in `TryGetValue`
was misinterpreted [0] as null-aware (instead of not correctly caught/
handled inside `NSDictionary`).
Fix https://github.com/xamarin/xamarin-macios/issues/11827
[0] https://github.com/xamarin/xamarin-macios/pull/10790

[mediaplayer] Fix MPNowPlayingInfoCenter.DefaultCenter.NowPlaying < iOS 11.1

---

src/Foundation/NSDictionary.cs
src/MediaPlayer/MPNowPlayingInfoCenter.cs

Ironically my nullability changes caused this... because they are not
yet complete and the lack of `ArgumentNullException` in `TryGetValue`
was misinterpreted [0] as null-aware (instead of not correctly caught/
handled inside `NSDictionary`).
Fix https://github.com/xamarin/xamarin-macios/issues/11827
[0] https://github.com/xamarin/xamarin-macios/pull/10790
Backport of #11847

[d16-10] [mediaplayer] Fix MPNowPlayingInfoCenter.DefaultCenter.NowPlaying < iOS 11.1

---

dotnet/Workloads/Microsoft.NET.Sdk.MacCatalyst/WorkloadManifest.targets
dotnet/Workloads/Microsoft.NET.Sdk.iOS/WorkloadManifest.targets
dotnet/Workloads/Microsoft.NET.Sdk.macOS/WorkloadManifest.targets
dotnet/Workloads/Microsoft.NET.Sdk.tvOS/WorkloadManifest.targets

Context: https://github.com/dotnet/sdk/pull/16208/files
Context: https://gist.github.com/sfoslund/12e1daff114bccc8a29ebb441bc461a5#detecting-installed-platforms
Context: https://github.com/xamarin/xamarin-android/issues/5941
The VS ProjectSystem needs a way to know during MSBuild evaluation
which platforms are supported by a workload--even if the workload is
not actually installed.
On Android, for example, we added the item group:
<SdkSupportedTargetPlatformIdentifier Include="android" DisplayName="Android" />
This enables the IDE to know that Android is supported.
In this repo, we need to make this change for the iOS, MacCatalyst,
macOS, and tvOS workloads.
/cc @sfoslund

[dotnet] add @(SdkSupportedTargetPlatformIdentifier)

---

dotnet/package/microsoft.workloads.csproj

This fixes a regression where the data/WorkloadManifest.* files were missing
from the Microsoft.NET.Sdk.<platform>.Manifest-6.0.100.<version> NuGets.
Updated contents are now:
$ unzip -l nupkgs/Microsoft.NET.Sdk.iOS.Manifest-6.0.100.*sha*.nupkg
Archive:  nupkgs/Microsoft.NET.Sdk.iOS.Manifest-6.0.100.14.5.100-preview.5.891+sha.130c40321.nupkg
Length      Date    Time    Name
---------  ---------- -----   ----
528  06-08-2021 20:38   _rels/.rels
845  06-08-2021 20:38   Microsoft.NET.Sdk.iOS.Manifest-6.0.100.nuspec
6434  09-27-2016 14:08   LICENSE
656  06-08-2021 18:36   data/WorkloadManifest.json
645  06-02-2021 06:24   data/WorkloadManifest.targets
594  06-08-2021 20:38   [Content_Types].xml
664  06-08-2021 20:38   package/services/metadata/core-properties/be25c66390ef48fa911d2e7a3f184c3c.p …

[dotnet] Fix the path to the workloads in one more location.

---

dotnet/package/microsoft.workloads.csproj

This fixes a regression where the data/WorkloadManifest.* files were missing
from the Microsoft.NET.Sdk.<platform>.Manifest-6.0.100.<version> NuGets.
Updated contents are now:
$ unzip -l nupkgs/Microsoft.NET.Sdk.iOS.Manifest-6.0.100.*sha*.nupkg
Archive:  nupkgs/Microsoft.NET.Sdk.iOS.Manifest-6.0.100.14.5.100-preview.5.891+sha.130c40321.nupkg
Length      Date    Time    Name
---------  ---------- -----   ----
528  06-08-2021 20:38   _rels/.rels
845  06-08-2021 20:38   Microsoft.NET.Sdk.iOS.Manifest-6.0.100.nuspec
6434  09-27-2016 14:08   LICENSE
656  06-08-2021 18:36   data/WorkloadManifest.json
645  06-02-2021 06:24   data/WorkloadManifest.targets
594  06-08-2021 20:38   [Content_Types].xml
664  06-08-2021 20:38   package/services/metadata/core-properties/be25c66390ef48fa911d2e7a3f184c3c.p …

[main] [dotnet] Fix the path to the workloads in one more location.

---

mk/xamarin.mk

* xamarin/maccore@0c0037229c [mlaunch] Add support for Xcode 13 beta 1. (#2453)
Diff: https://github.com/xamarin/maccore/compare/cddbd1915dcb27d8bf2d9b3b9cc4aeb22785698e..0c0037229c5867b012a77ed44af0e3e383d6d01d

Bump maccore to get fix for Xcode 13.

---

dotnet/Makefile
dotnet/Microsoft.MacCatalyst.Sdk/data/UnixFilePermissions.xml
dotnet/Microsoft.iOS.Sdk/data/UnixFilePermissions.xml
dotnet/Microsoft.macOS.Sdk/data/UnixFilePermissions.xml
dotnet/Microsoft.tvOS.Sdk/data/UnixFilePermissions.xml

NuGet doesn't support preserving the executable bit for files in *.nupkgs
(which are just zip files), so .NET implemented a [temporary
workaround](https://github.com/dotnet/sdk/pull/17299) for workload installs,
where they hardcoded files that should be executable.
This isn't really sustainable, and they'll remove their workaround, so we need
to use their supported method of specifying the file permissions: a
data/UnixFilePermissions.xml file.
Fixes https://github.com/xamarin/xamarin-macios/issues/11860.

[dotnet] Add a data/UnixFilePermissions.xml file to the sdk packs. Fixes #11860.

---

src/ILLink.LinkAttributes.xml.in

Fix warning
> resource ILLink.LinkAttributes.xml in Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065(26,6): warning IL2008: Could not resolve type 'ObjCRuntime.NotImplementedAttribute' [/Users/poupou/git/xamarin/xamarin-macios/tests/dotnet/size-comparison/MySingleView/dotnet/MySingleView.csproj]

[dotnet][linker] Fix incorrect namespace for `[NotImplementedAttribute]`

---

msbuild/Xamarin.MacDev.Tasks.Core/Tasks/GetFullPathTaskBase.cs
msbuild/Xamarin.MacDev.Tasks/Tasks/GetFullPath.cs
msbuild/Xamarin.Shared/Xamarin.Shared.targets

Revert a small part of #10409 so the path evaluation always happens on
the mac computer (even if the build is done from Windows)
Also dded a comment to avoid repeating that mistake again
Fixes https://github.com/xamarin/xamarin-macios/issues/11817

[windows][msbuild] Fix the use of a windows path inside `_PrepareDebugSymbolGeneration`

---

msbuild/Xamarin.iOS.Tasks/Tasks/MTouch.cs
tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/MTouchTaskTests.cs

The entire `.framework` directory needs to be copied back to Windows
when a native reference is a [xc]framework. Otherwise important files
will be missing and the app bundle will be unusable.
Fix https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1339824

[windows][msbuild] Copy entire directory when the native reference is a framework

---

dotnet/Makefile

Makes diagnostics easier when something goes wrong.

[dotnet] Create binlogs when creating NuGets.

---

msbuild/Xamarin.MacDev.Tasks.Core/Tasks/GetFullPathTaskBase.cs
msbuild/Xamarin.MacDev.Tasks/Tasks/GetFullPath.cs
msbuild/Xamarin.Shared/Xamarin.Shared.targets

Revert a small part of #10409 so the path evaluation always happens on
the mac computer (even if the build is done from Windows)
Also dded a comment to avoid repeating that mistake again
Fixes https://github.com/xamarin/xamarin-macios/issues/11817
Backport of #11870

[d16-10] [windows][msbuild] Fix the use of a windows path inside `_PrepareDebugSymbolGeneration`

---

msbuild/Xamarin.iOS.Tasks/Tasks/MTouch.cs
tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/MTouchTaskTests.cs

The entire `.framework` directory needs to be copied back to Windows
when a native reference is a [xc]framework. Otherwise important files
will be missing and the app bundle will be unusable.
Fix https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1339824
Backport of #11868

[d16-10] [windows][msbuild] Copy entire directory when the native reference is a framework

---

tools/devops/automation/templates/build/build.yml

This makes diagnosing build failures much, much easier.

[devops] Upload all the binlogs in xamarin-macios as artifacts after the build.

---

Make.config

This prevents a problem where:
a) A branch is created in origin based on this release branch.
b) The new branch is automatically built in CI, and produces packages which
are uploaded to NuGet.
c) Some other PR is merged into the same release branch.
d) The merged commit ends up with the same version number as the branch from
b), because we hardcoded branch name in the version number.
e) The CI for the merged commit tries to upload packages to NuGet, which
fails, because there already are packages on NuGet.
e) Hair pulling ensues.

[release/6.0.1xx-preview5] [dotnet] Don't allow any other branches to pretend to be release branches.

---

Make.config

If we hardcode a prelease identifier for a .NET release, we can easily end up
with multiple branches using the same version number, because the hardcoded
prerelease identifier ends up being the same for any other branches that are
created later from the release branch (one typical example would be backport
branches).
This is bad.
So try to prevent this, by hardcoding two values instead!
We'll hardcode the branch name where the hardcoded prerelease identifier
should be applied, and this way any other branches will not use the hardcoded
prerelease identifier.
Ref: https://github.com/xamarin/xamarin-macios/pull/11891.

Try to prevent identical version numbers across branches by matching hardcoded prerelease identifiers with hardcoded branch name.

---

dotnet/Makefile
dotnet/package/workaround-for-maccore-issue-2427/restore.csproj

We randomly run into a NuGet restore failure, which breaks the build, and is
quite annoying.
This might be due to a problem with multiple simultaneous restores, so this is
an attempt to first restore the packages we need, in a single serialized
restore, and once that's done we can process everything else in parallel.
Ref: https://github.com/xamarin/maccore/issues/2427
Ref: https://github.com/NuGet/Home/issues/10935

[dotnet] Try to implement a workaround for xamarin/maccore#2427.

---

msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
msbuild/Xamarin.MacDev.Tasks.Core/Tasks/GetDirectoriesTaskBase.cs
msbuild/Xamarin.MacDev.Tasks/Tasks/GetDirectories.cs
msbuild/Xamarin.Shared/Xamarin.Shared.targets
msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets

The iOS version of the cleaning tasks were much more comprehensive, so those
won out when there were any differences.
This also required moving the GetDirectoriesTask to shared code.

[msbuild] Share several cleaning targets between Xamarin.iOS and Xamarin.Mac.

---

tools/devops/automation/build-pipeline.yml
tools/devops/automation/templates/windows/build.yml
tools/devops/automation/templates/windows/stage.yml

Add a new stage for the windows integration tests. Very boring since it follows the same pattern for all other stages, custom stage.yml and custom build.yml job. 
Missing parts:
1 - Add the upload and download of the tests (will be in a diff pr).
2 - A valid pool with the mac agent present.

[CI] Add a new stage that will run windows integration tests.

---

src/CoreMidi/MidiCompat.cs
src/coremidi.cs

This is likely a leftover from a beta and can now cause rejections.

[coremidi] Remove incorrect `.ctor` on `MIDICISession`

---

src/mlcompute.cs
src/networkextension.cs
src/vision.cs

When used they can cause rejection from the app store (but in most
case the managed linker will remove them from the app code)

Remove extra (managed) setters on readonly (native) properties

---

src/CoreMidi/MidiCompat.cs
src/coremidi.cs

This is likely a leftover from a beta and can now cause rejections.
Backport of #11910

[d16-10] [coremidi] Remove incorrect `.ctor` on `MIDICISession`

---

tests/introspection/ApiSelectorTest.cs
tests/introspection/Mac/MacApiSelectorTest.cs

The base ApiSelectorTest class already handles these selectors, and does it
almost right, so just remove this special case and fix the base class logic.
Fixes these failures on macOS 10.15:
Introspection.MacApiSelectorTest
[FAIL] InstanceMethods :   4 errors found in 27001 instance selector validated:
Selector not found for CoreML.MLDictionaryFeatureProvider : encodeWithCoder: in Void EncodeTo(Foundation.NSCoder) on CoreML.MLDictionaryFeatureProvider
Selector not found for CoreML.MLMultiArray : encodeWithCoder: in Void EncodeTo(Foundation.NSCoder) on CoreML.MLMultiArray
Selector not found for CoreML.MLFeatureValue : encodeWithCoder: in Void EncodeTo(Foundation.NSCoder) on CoreML.MLFeatureValue
Selector not found for CoreML.MLSequence : encodeWithCoder: in Void EncodeTo(Foundation.NSCoder) …

[introspection] Handle a few Metal classes differently for 'encodeWithCoder:'. Fixes #11885.

---

src/CloudKit/CKCompat.cs
src/cloudkit.cs

Their usage can cause app store rejections.
Backport of #11909

[d16-10] [cloudkit] Remove obsoleted properties

---

tools/devops/automation/templates/build/stage.yml

The Build.SourceBranchName variable is documented to be the last segment of
the git ref. If the git ref is 'refs/heads/main', then Build.SourceBranchName
is 'main' (as expected). However, if the git ref is
'refs/heads/release/6.0.1xx-preview5', then Build.SourceName is
'6.0.1xx-preview5', and that's not what we want.
Instead use the Build.SourceBranch variable, which is the entire git ref, and
then we strip out the 'refs/heads/' part from the beginning. This way we get
the correct branch name.

[CI] Fix BRANCH_NAME to be the entire branch name.

---

mk/xamarin.mk

* xamarin/maccore@c7809739bd [Xamarin.Hosting] Add each platform as an exposed capability to the plugin manager. Fixes #xamarin/xamarin-macios@11901. (#2455)
Diff: https://github.com/xamarin/maccore/compare/9acbbed1f60788349c60437dba11531a866777a8..c7809739bd04c9c878ed5cfdd5208ad7135e13d4

Bump maccore to get mlaunch fix.

---

src/mlcompute.cs
src/networkextension.cs
src/vision.cs
tests/xtro-sharpie/common-Vision.ignore

When used they can cause rejection from the app store (but in most
case the managed linker will remove them from the app code)
Backport of #11907

[d16-10] Remove extra (managed) setters on readonly (native) properties

---

src/CoreFoundation/CFString.cs

`CFString` cache the native immutable string into it's `str` field and
use it to avoid p/invokes when possible.
`ToString` retrieved the string without setting `str` (if `null`) so it
missed opportunities to avoid the native calls.

[corefoundation] Fix `CFString.ToString` to cache the result

---

src/CoreFoundation/CFString.cs

* Avoid chaining constructors, so one can be eliminated (if the other is not used)
* Remove casts (`int` parameters does not need them for `nint` fields)
* Reduce metadata (when a `.ctor` can be eliminated, like MySingleView)
```diff
--- a.cs	2021-06-14 20:56:22.000000000 -0400
+++ b.cs	2021-06-14 20:56:25.000000000 -0400
@@ -5068,13 +5068,8 @@
public CFRange(int P_0, int P_1)
{
-			this = new CFRange((long)P_0, (long)P_1);
-		}
-
-		public CFRange(long P_0, long P_1)
-		{
-			loc = (nint)P_0;
-			len = (nint)P_1;
+			loc = P_0;
+			len = P_1;
}
public override string ToString()
```

[corefoundation] Simplify `CFRange`

---

src/Foundation/LinkerSafeAttribute.cs
tools/common/Tuning.cs

This was allowed to ease existing (3rd party) code migration into net6.
However the reverse can also happen: trying to use net6 code with the
legacy SDK. In such case it's possible other (newer) attributes are being
used to preserve members.
ref: https://github.com/dotnet/aspnetcore/issues/33269

[linker] Ignore `[AssemblyMetadata]` before net6

---

src/Foundation/LinkerSafeAttribute.cs
tools/common/Tuning.cs

This was allowed to ease existing (3rd party) code migration into net6.
However the reverse can also happen: trying to use net6 code with the
legacy SDK. In such case it's possible other (newer) attributes are being
used to preserve members.
ref: https://github.com/dotnet/aspnetcore/issues/33269
Backport of #11940

[d16-10] [linker] Ignore `[AssemblyMetadata]` before net6

---

tools/common/Driver.cs

Developers will now get the helpful:
> error MM0051: Xamarin.Mac 7.99.0 requires Xcode 12.0 or later. The current Xcode version (found in /Applications/Xcode_11.7.app/Contents/Developer) is 11.7.
instead of:
> error MM5309: Failed to execute the tool 'clang', it failed with an error code '1'. Please check the build log for details.
(and no clue from the build log that they need to upgrade their Xcode).
Xamarin.iOS projects still build fine with at least Xcode 11.3.1, so I've only
updated the minimum Xcode version for Xamarin.Mac.
Fixes https://github.com/xamarin/xamarin-macios/issues/11937.

[mmp] Set minimum Xcode to Xcode 12 to get a better error message. Fixes #11937.

---

tests/introspection/ApiCMAttachmentTest.cs
tests/linker/ios/link sdk/AsyncTest.cs
tests/linker/ios/link sdk/CryptoTest.cs
tests/linker/ios/link sdk/LinkSdkRegressionTest.cs
tests/monotouch-test/Foundation/UrlCredentialTest.cs
tests/monotouch-test/Security/CertificateTest.cs
tests/monotouch-test/Security/KeyTest.cs
tests/monotouch-test/Security/RecordTest.cs
tests/monotouch-test/Security/TrustTest.cs
tests/monotouch-test/System.Net.Http/MessageHandlers.cs

They should now work (even if some tests required more changes) and
will be able to validate other changes.
ref: https://github.com/dotnet/runtime/issues/36897

[tests] Re-enable tests ignored due to dotnet/runtime #36897

---

tests/linker/ios/link sdk/DllImportTest.cs

ref: https://github.com/dotnet/runtime/issues/41355
Unlike what we have today for legacy support for Ping was added in
https://github.com/dotnet/runtime/pull/52240

[tests][link sdk] Re-enable test for Ping for dotnet

---

src/CoreFoundation/CFString.cs
src/Foundation/NSString.cs
src/PrintCore/PrintCore.cs
src/generator.cs
tests/perftest/TollFreeBridge.cs

This is possible because both types are toll-free bridged [0].
How ?
* Renamed `CFString.LowLevelCreate` to `CreateNative` so it match `NSString` API
* Make it public so it can be used for generated/3rd party bindings
* Added a _safe_ `CFString.ReleaseNative` matching `NSString` API
* Update generator to use the new API (instead of the NSString version)
* Update manual bindings (using older API) to use the new API (few in PrintCore)
Why ?
It's no secret that p/invoke (C) are faster than calling a selector
(ObjC). In most cases we do not have a choice what to call... but in a
few, but commonly used, cases we can pick the fastest call.
In this case the difference is larger than the previous case [1] since there's
two call (create and release) involved.
|                 Method | …

Use `CFString` instead of `NSString` to get a handle from a (.net) `System.String`

---

tests/generator/sof20696157.cs

TL&DR: They were removed from headers so we can't use them for our tests.
Long Story:
To avoid app being rejected the selectors must be removed from the app.
This means the removal of the `[Export]` and `[Bind]` attributes inside
the platform assemblies. That, in turn, makes the binding generator
unable to create bindings for those types.
If some 3rd party bindings extended those types then they also need to
remove them (they will not be able to submit with the symbols anyway).
Stubs can be used, whether or not binary compatibility is provided for
the 3rd party bindings consumers.
Fix https://github.com/xamarin/xamarin-macios/issues/11947

[tests][generator] Remove references to iAd.framework types

---

tests/monotouch-test/dotnet/MacCatalyst/monotouch-test.csproj
tests/monotouch-test/dotnet/iOS/monotouch-test.csproj
tests/monotouch-test/dotnet/tvOS/monotouch-test.csproj

* It's easier to fix up the path to the linker description in xharness when
cloning project files. This way maybe we'll be able to remove the [hardcoded
logic in xharness][1] to handle ${ProjectDir}.
* .NET doesn't understand the ${ProjectDir} syntax, so this makes it possible
to build these projects from the command line.
[1]: https://github.com/dotnet/xharness/blob/b2297d610df1ae15fc7ba8bd8c9bc0a7192aaefa/src/Microsoft.DotNet.XHarness.iOS.Shared/Utilities/ProjectFileExtensions.cs#L1268

[monotouch-tests] Use a LinkDescription item to specify extra linker description files

---

msbuild/Xamarin.MacDev.Tasks.Core/Tasks/LinkNativeCodeTaskBase.cs

Fixes https://github.com/xamarin/xamarin-macios/issues/11954.

[msbuild] Treat extension-less files as static libraries when linking native code. Fixes #11954.

---

tests/mtouch/StringUtilsTest.cs
tools/common/StringUtils.cs

Previously quoting a string with a quote:
a"b
would result in:
"a\"""b"
There are way too many quotes there.
We'll now get:
"a\"b"
which is correct.

[tools] Fix quoting quotes in StringUtils.QuoteForProcess.

---

src/UIKit/UIApplication.cs

* `#enable nullable`
and add null-check for potentially `null` `args` parameter on `Main`
methods(s).
* Avoiding calls chaining
There were 4 `Main` overloads, 3 of them needed for the most simple app.
There's now only one needed.
* Obsolete the overload with `string` parameters
It's not type safe. It also makes it harder for the linker to mark the
app delegate type.
* Avoid creating `NSString` instances inside `Main` methods
`CFString` are cheaper, no initialization, simpler calling convention.
This also remove any trace of `NSString` in very simple apps, see below:
```diff
--- a.cs	2021-06-16 21:41:04.000000000 -0400
+++ b.cs	2021-06-16 21:41:06.000000000 -0400
@@ -3025,9 +3025,6 @@
public static extern nuint nuint_objc_msgSendSuper(IntPtr P_0, IntPtr P_1); …
```

[uikit] Simplify and fix (NRE) in `UIApplication`

---

tools/devops/automation/templates/build/build-nugets.yml
tools/devops/automation/templates/build/build.yml
tools/devops/automation/templates/build/publish-nugets.yml
tools/devops/automation/templates/build/sign-and-notarized.yml

This required reordering operations a bit, so that we can sign before publishing.
Fixes https://github.com/xamarin/xamarin-macios/issues/11952.

[CI] Sign *.nupkg too. Fixes #11952.

---

src/CoreFoundation/CFString.cs
src/CoreFoundation/NativeObject.cs
src/CoreImage/CIFilter.cs
src/CoreImage/CIImage.cs
src/generator.cs

then fix the impact this had on existing nullable-aware code,
including the generator
Also
* Hide `CFObject` empty (of public members) for future profiles
* Fix `CFString.ToString ()` to never return `null`

[corefoundation] Enable nullability on `CFString` and `NativeObject`

---

tests/dotnet/Makefile
tests/dotnet/README.md

to make sure the latest locally build nuget are used
Also document `make strip-dotnet` as a time-saver to analyze the binary
assemblies produced for dotnet

[tests][dotnet] Clear packages before building test apps

---

tests/monotouch-test/dotnet/MacCatalyst/monotouch-test.csproj
tests/monotouch-test/dotnet/extra-linker-defs.xml
tests/monotouch-test/dotnet/iOS/monotouch-test.csproj
tests/monotouch-test/dotnet/macOS/monotouch-test.csproj
tests/monotouch-test/dotnet/tvOS/monotouch-test.csproj

This reverts commit 29727d6a8da87f4e9f0db5bb7f8e24929078332d.
https://github.com/dotnet/runtime/issues/46908 was fixed and the other part of the workaround was removed in PR#11958

Revert "[tests] Preserve a required method in System.Private.CoreLib to work around a bug in .NET 6. (#10426)"

---

dotnet/targets/Microsoft.Sdk.DefaultItems.template.props
dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets

* This is the way Android does it:
https://github.com/xamarin/xamarin-android/blob/15b40af7d62e0e2003d2a009576834a71967dbb2/src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/Sdk/AutoImport.props#L23
* Makes it easier for the default inclusion logic to be used by
Xamarin.Legacy.Sdk (as explained in the fixed issue).
Fixes https://github.com/xamarin/xamarin-macios/issues/11990.

[dotnet] Only limit the default inclusion items with a condition on 'EnableDefault<Platform>Items'. Fixes #11990.

---

tests/xtro-sharpie/MacCatalyst-CoreText.todo
tests/xtro-sharpie/common-CoreText.ignore
tests/xtro-sharpie/iOS-CoreText.todo
tests/xtro-sharpie/macOS-CoreText.ignore
tests/xtro-sharpie/tvOS-CoreText.todo
tests/xtro-sharpie/watchOS-CoreText.todo

Added the invokes to be ignored as with macOS.

[CoreText] Add support for Xcode13 beta1.

---

src/pdfkit.cs
tests/xtro-sharpie/MacCatalyst-PDFKit.todo
tests/xtro-sharpie/iOS-PDFKit.todo
tests/xtro-sharpie/macOS-PDFKit.todo

Wasn't sure if the PdfAccessPermissions type should be ulong.
Sharpie gave it the ulong type and used the `(1uL << #)` but the original header used NSUInteger which according to [this](https://docs.microsoft.com/en-us/xamarin/cross-platform/macios/binding/objective-c-libraries?context=xamarin%2Fios&tabs=macos#simple-types) should be `nuint`

[PDFKit] Updating Xcode13 Beta 1

---

dotnet/Microsoft.MacCatalyst.Sdk/targets/Microsoft.MacCatalyst.Sdk.targets

Fix: https://github.com/dotnet/maui/issues/1238
ref: https://github.com/xamarin/xamarin-macios/pull/10724
It appears that target file is not currently resolving OS-dependent paths, so the final path contains the backslash used by Windows.
```
02:04:30.631     0>プロセス = "/usr/local/share/dotnet/dotnet"
MSBuild 実行可能ファイルのパス = "/usr/local/share/dotnet/sdk/6.0.100-preview.5.21302.13/MSBuild.dll"
コマンド ライン引数 = "/usr/local/share/dotnet/sdk/6.0.100-preview.5.21302.13/dotnet.dll run -v diag -f net6.0-maccatalyst --project MAUICameraSetting"
現在のディレクトリ = "/Users/yamachu/Projects/github.com/yamachu/MAUICameraSetting"
MSBuild バージョン = "17.0.0-preview-21302-02+018bed83d"
SDK 'Microsoft.NET.Sdk.Razor' を解決しています...
SDK 'Microsoft.NET.Sdk' を解決しています...
プロパティの再代入: …
```

[dotnet] Normalize run target assembly path on the Run target for Mac Catalyst

---

src/ILLink.Substitutions.ios.xml
src/ILLink.Substitutions.tvos.xml
src/ObjCRuntime/Dlfcn.cs
src/generator.cs

* Skip extraneous logic for generated entries where we know the full path is available
* Update generator to use the internal `_dlopen` that skips the checks
* This removes the code below (diff) for a simple application
* Use the linker substitution files to remove the warning on release builds
* If `dlopen` is used then `WarnOnce` method becomes a empty stub and
* field `warningShown` is also removed
```diff
--- a.cs	2021-06-22 20:59:25.000000000 -0400
+++ b.cs	2021-06-22 20:59:28.000000000 -0400
@@ -2023,44 +2023,14 @@
{
public static class System
{
-			public static readonly IntPtr Handle = Dlfcn.dlopen("/usr/lib/libSystem.dylib", 0);
+			public static readonly IntPtr Handle = Dlfcn._dlopen("/usr/lib/libSystem.dylib", 0);
}
}
public static class Dlfcn
{
-		private static bool …
```

[objcruntime] Refactor `Dlfcn.dlopen` to ease linking

---

dotnet/Microsoft.MacCatalyst.Templates/maccatalyst/.template.config/template.json
dotnet/Microsoft.iOS.Templates/ios/.template.config/template.json
dotnet/Microsoft.macOS.Templates/macos/.template.config/template.json
dotnet/Microsoft.tvOS.Templates/tvos/.template.config/template.json

Context: https://github.com/dotnet/templating/issues/3325
Context: https://github.com/dotnet/templating/wiki/Reference-for-template.json#content-manipulation
In current .NET 6 Preview 6 builds, there is an issue if a template
includes a binary file larger than ~8kb, it seems to get truncated when
`dotnet new` extracts the template.
A workaround is to use the `copyOnly` feature for binary files. Really,
we should be doing this anyway, because otherwise the templating system
considers replacing *text* in these binary files. It improves
performance to do this and would hopefully prevent a future bug of
random bytes getting replaced.

[dotnet] use copyOnly for .png files in templates

---

dotnet/Microsoft.MacCatalyst.Templates/maccatalyst/.template.config/template.json
dotnet/Microsoft.iOS.Templates/ios/.template.config/template.json
dotnet/Microsoft.macOS.Templates/macos/.template.config/template.json
dotnet/Microsoft.tvOS.Templates/tvos/.template.config/template.json

Context: https://github.com/dotnet/templating/issues/3325
Context: https://github.com/dotnet/templating/wiki/Reference-for-template.json#content-manipulation
In current .NET 6 Preview 6 builds, there is an issue if a template
includes a binary file larger than ~8kb, it seems to get truncated when
`dotnet new` extracts the template.
A workaround is to use the `copyOnly` feature for binary files. Really,
we should be doing this anyway, because otherwise the templating system
considers replacing *text* in these binary files. It improves
performance to do this and would hopefully prevent a future bug of
random bytes getting replaced.
Backport of #12016

[release/6.0.1xx-preview6] [dotnet] use copyOnly for .png files in templates

---

dotnet/Microsoft.MacCatalyst.Sdk/targets/Microsoft.MacCatalyst.Sdk.targets
dotnet/Microsoft.macOS.Sdk/targets/Microsoft.macOS.Sdk.targets

When we're using 'open' to launch apps, we need to use '--args ...' to pass any additional argument to the app, because otherwise 'open' will try to open those arguments as if they were files:
```
$ open "/Applications/Sublime Text.app" helloworld
The file /Users/rolf/test/helloworld does not exist.
```
(and doesn't launch Sublime Text).
while this works:
```
$ open "/Applications/Sublime Text.app" --args helloworld
```
in that it opens Sublime Text.
It's also possible to not append any other arguments, so this:
```
$ open "/Applications/Sublime Text.app" --args
```
while it looks weird, it works just fine.
Ref: https://github.com/dotnet/sdk/issues/18437

[dotnet] Fix launching macOS and Mac Catalyst apps with arguments.

---

src/Foundation/NSObject.mac.cs
src/generator.cs

NSObject.SetAsProxy is only available for macOS, so this makes the generated
code behave (and actually work) on all platforms.

[src] Remove the internal NSObject.SetAsProxy, and call the NSObject.IsDirectBinding setter directly.

---

dotnet/Microsoft.macOS.Sdk/targets/Microsoft.macOS.Sdk.targets

OutputPath is relative to the project directory, so it doesn't work when the
current directory isn't the same as the project directory.
TargetDir is an absolute directory.
Ref: #11994 / 096c75f425e54bd20b82fc601f3bce52c9b3f8bc (same for Mac Catalyst).

[dotnet] Use TargetDir instead of OutputPath for resolving assembly output directory.

---

tools/devops/automation/build-pipeline.yml

This change will trigger the scheduled build at 1800 UTC (8:00 pm in Spain, 2 pm EST) on every day-of-week from Monday through Friday and also on Sunday. This will give me more chances to debug what is going on with the OneLocBuild inputs!

[CI] Changing Cron Job's Occurrence

---

dotnet/targets/WorkloadManifest.MacCatalyst.template.json
dotnet/targets/WorkloadManifest.macOS.template.json

Context: https://github.com/dotnet/runtime/blob/36e0432547d7d734ef23fce40e8c278ef80c34c8/src/mono/nuget/Microsoft.NET.Workload.Mono.Toolchain.Manifest/WorkloadManifest.json.in
When using the MacCatalyst workload, you hit the build error:
error NETSDK1147: To build this project, the following workloads must be installed: microsoft-net-runtime-maccatalyst
I found an `extends` was missing in `WorkloadManifest.json`.
I also found the macOS workload needs to extend
`microsoft-net-runtime-mono-tooling`, because of its usage of
`<RuntimeConfigParserTask/>`

[dotnet] add missing workload dependencies

---

dotnet/targets/WorkloadManifest.MacCatalyst.template.json
dotnet/targets/WorkloadManifest.macOS.template.json

Context: https://github.com/dotnet/runtime/blob/36e0432547d7d734ef23fce40e8c278ef80c34c8/src/mono/nuget/Microsoft.NET.Workload.Mono.Toolchain.Manifest/WorkloadManifest.json.in
When using the MacCatalyst workload, you hit the build error:
error NETSDK1147: To build this project, the following workloads must be installed: microsoft-net-runtime-maccatalyst
I found an `extends` was missing in `WorkloadManifest.json`.
I also found the macOS workload needs to extend
`microsoft-net-runtime-mono-tooling`, because of its usage of
`<RuntimeConfigParserTask/>`
Backport of #12045

[release/6.0.1xx-preview6] [dotnet] add missing workload dependencies

---

builds/.gitignore
builds/Makefile

Hopefully this will solve issues with random curl errors (56) that happens
when trying to download .NET (and which break the build randomly).

[builds] Use the dotnet-install.sh script to install .NET locally.

---

.github/workflows/label-checker.yml

Although the github actions bot successfully automatically adds 2 labels to this PR, the PR check github action did not accept it. When I added a new label (or perhaps removed one and added it back) and then ran that check, it passed.
I think somewhere along the formation of the PR, the check is missing it. I propose adding github actions bot to the ignore labels portion

[CI] Adding GithubActions[bot] to Bypass Label Verification

---

tests/xtro-sharpie/xtro-sanity/Sanitizer.cs

To avoid things like the ones fixed in https://github.com/xamarin/xamarin-macios/pull/12088 we add a new
test to ensure that todo files do have content.
PS: PR will fail until https://github.com/xamarin/xamarin-macios/pull/12088 is merge, but that is a nice test :) 
Example output:
```
[14:56] Manuel de la Pena Saenz
rm -f *.unclassified
/Applications/Xcode_13.0.0-beta2.app/Contents/Developer/usr/bin/make -j8 classify-ios classify-tvos classify-watchos classify-macos classify-maccatalyst
mono64 --debug bin/Debug/xtro-sharpie.exe iphoneos15.0-arm64.pch ../../_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/lib/64bits/iOS/Xamarin.iOS.dll ../../_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/OpenTK-1.0.dll
mono64 --debug …
```

[xtro] Do not allow to leave empty todo files in xtro.

---

src/generator.cs

We can have ARM64 code everywhere now, so our conditions to select the correct
objc_msgSend overload must not think that we only need the ARM64 code paths on
a mobile device.
Old style:
if (Runtime.Arch == Arch.DEVICE) {
if (IntPtr.Size == 8) {
// arm64 codepath
} else {
// 32-bit arm codepath
}
} else if (IntPtr.Size == 8) {
// x86_64 codepath
} else {
// x86 codepath
}
New style:
if (global::ObjCRuntime.Runtime.IsARM64CallingConvention) {
// arm64 codepath
} else if (IntPtr.Size == 8) {
// x86_64 codepath
} else if (Runtime.Arch == Arch.DEVICE) {
// 32-bit arm codepath
} else {
// x86 codepath
}

[generator] Adjust generated code to not assume that only device-specific code can be ARM64.
