dotnet/macios

- dotnet/targets/Xamarin.Shared.Sdk.targets
aotdata files go next to the assemblies, not next to the executable. This does
not make a difference for mobile platforms (because it's the same location),
but it matters for Mac Catalyst / macOS, where assemblies are not located next
to the executable.
> [dotnet] aotdata files go in the same directory as the assemblies.

- dotnet/Workloads/Microsoft.NET.Sdk.MacCatalyst/WorkloadManifest.targets
Context: https://github.com/dotnet/runtime/blob/ae5ee8f02d6fc99469e1f194be45b5f649c2da1a/src/mono/nuget/Microsoft.NET.Workload.Mono.Toolchain.Manifest/WorkloadManifest.targets#L30-L32
Building dotnet/maui, I get warnings for any MacCatalyst projects:
WorkloadManifest.targets(22,9): warning MSB4011: "C:\src\maui\bin\dotnet\packs\Microsoft.NET.Runtime.RuntimeConfigParser.Task\6.0.0-preview.6.21352.12\Sdk\Sdk.props" cannot be imported again.
It was already imported at "C:\src\maui\bin\dotnet\sdk-manifests\6.0.100\microsoft.net.sdk.maccatalyst\WorkloadManifest.targets (8,2)". This is most likely a build authoring error. This subsequent import will be ignored.
I believe we can remove this `<Import/>` now, as the Mono workload is
doing the importing for MacCatalyst.
It appears that this is …
> [dotnet] don't import RuntimeConfigParser.Task for MacCatalyst

- dotnet/targets/Xamarin.Shared.Sdk.targets
* Don't copy runtime dylibs to the publish directory if we're linking statically.
* Don't copy static libraries to the publish directory, they're never needed at
runtime.
> [dotnet] Copy fewer runtime libraries to the publish directory.

- src/iosurface.cs
- tests/xtro-sharpie/MacCatalyst-IOSurface.ignore
- tests/xtro-sharpie/MacCatalyst-IOSurface.todo
- tests/xtro-sharpie/common-IOSurface.ignore
- tests/xtro-sharpie/iOS-IOSurface.todo
- tests/xtro-sharpie/macOS-IOSurface.todo
- tests/xtro-sharpie/tvOS-IOSurface.todo
I don't feel too confident with this one.
I added the missing p-invokes to the ignore since they are ignored in other platforms.
I added the two fields. They say they are supported in older versions and the iOS 11.4 intro test did not complain about them, but a good amount of other IOSurface* fields are in the common ignore and I am not sure why.
> [IOSurface] Updates for Xcode13 Beta 1

- msbuild/Directory.Build.props
We need this bump so we can fix a P1 in XamarinVS d16-11, which is referencing macios from d16-10
> Updated Xamarin.Messaging version

- runtime/coreclr-bridge.m
- runtime/delegates.t4
- runtime/monotouch-main.m
- runtime/runtime.m
- runtime/xamarin/runtime.h
- src/ObjCRuntime/Runtime.CoreCLR.cs
- tests/monotouch-test/ObjCRuntime/RuntimeTest.cs
To have consistent behavior in .NET, set the current directory to the root of
the app bundle for all platforms.
This is a breaking change for legacy Xamarin.Mac, which used to set the
current directory to the Contents/Resources subdirectory, but there's a simple
workaround for customers that depend on the old behavior (change it in Main
themselves), and I believe the consistent experience across platforms warrants
this change.
Note that we already had a breaking change here for macOS/.NET: we were
(unintentionally) setting the current directory to the Contents/MonoBundle
directory, which neither matched mobile platforms, nor the legacy Xamarin.Mac
behavior.
This solves the problem of what to do for Mac Catalyst apps, because there's
no need to choose between the macOS or the mobile …
> [runtime] Set the current directory to the root directory of the app bundle for all platforms in .NET.

- runtime/runtime.m
Return early when we're not going to try resolving anything, which means that
if we didn't find something by the end, we know that it's because we failed
(and not because we weren't supposed to try), and we log that.
This makes it easier to diagnose a few failure conditions.
> [runtime] Add logging when a P/Invoke can't be resolved in xamarin_pinvoke_override.

- src/ILLink.LinkAttributes.tvos.xml
- src/Makefile
Specialize the tvOS version of ILLink.LinkAttributes.xml, where we don't
include the "ObjCRuntime.AvailabilityAttribute" type (because it doesn't exist
in tvOS).
Fixes this linker warning:
resource ILLink.LinkAttributes.xml in Xamarin.TVOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065(37,6): warning IL2008: Could not resolve type 'ObjCRuntime.AvailabilityAttribute'
> [src] Specialize the tvOS version of ILLink.LinkAttributes.xml.

- mk/xamarin.mk
* xamarin/maccore@99ad0341f4 [Xamarin.Hosting] Improve error reporting when dlopen fails (#2466)
* xamarin/maccore@8dd9c68035 [Xamarin.Hosting] Xcode 13 b3 doesn't have IBFoundation anymore, but it does have AssetCatalogFoundation, which we must load. (#2467)
* xamarin/maccore@da6da4af29 [Xamarin.Hosting] Only warn if we try to load a framework that doesn't exist. (#2465)
* xamarin/maccore@5cec54f305 [Xamarin.Hosting] Add some helpful lldb commands when trying to figure out what Xcode does. (#2456)
Diff: https://github.com/xamarin/maccore/compare/c7809739bd04c9c878ed5cfdd5208ad7135e13d4..99ad0341f436c31dcd85abcb7375c3f71072eda3
> Bump maccore to get mlaunch fix for Xcode 13 b3.

- runtime/runtime.m
- src/ObjCRuntime/Runtime.iOS.cs
* Use the Apple-provided TARGET_OS_SIMULATOR define to determine if we're
running in a simulator, instead of checking the current architecture. This
way we properly detect ARM64-based simulators (and it'll work correctly in
the future).
* Always set Runtime.Arch = SIMULATOR for Mac Catalyst. The final value for
Runtime.Arch for Mac Catalyst is tracked in #10312, but this is a stop-gap
measure to make sure we have the same value between X64 and ARM64 on Mac
Catalyst, and until now we've had Runtime.Arch = SIMULATOR for X64, so just
go with that for now.
> [runtime] Fix Runtime.Arch to be consistent on Mac Catalyst and work properly on ARM-based simulators.

- src/ObjCRuntime/Runtime.cs
Fix Runtime.GetIsARM64CallingConvention to be the same on all platforms, and
also we can't use simulator/device to determine anything, since the simulator
can do ARM64 on an M1 now.
> [ObjCRuntime] Fix Runtime.GetIsARM64CallingConvention to be correct on M1.

- tools/devops/automation/scripts/bash/compare.sh
Surrounding a glob with quotes will make bash interpret the glob as a literal
filename, and not expand it, so move the quotes to not include the glob.
> [devops] Fix detection of breaking changes in the api comparison.

- dotnet/targets/Xamarin.Shared.Sdk.targets
- runtime/coreclr-bridge.m
We need to process the runtimeconfig.json file somehow when using CoreCLR, and
the embedding API we use (coreclr_initialize) won't parse it for us. So re-use
the logic we already have to process runtimeconfig.json for MonoVM (which
involves converting it to a binary format at build time, which we then process
at runtime).
> [dotnet] Create and parse runtimeconfig.bin when using CoreCLR.

- src/btouch.cs
Enable nullability in btouch.cs, and fix the resulting warnings.
Fixes these warnings (because there were already nullability annotations in
btouch.cs):
src/btouch.cs(640,26): warning CS8632: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.
src/btouch.cs(642,9): warning CS8632: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.
> [generator] Fix nullability warning.

- tests/generator/sof20696157.cs
TL&DR: They were removed from headers so we can't use them for our tests.
Long Story:
To avoid app being rejected the selectors must be removed from the app.
This means the removal of the `[Export]` and `[Bind]` attributes inside
the platform assemblies. That, in turn, makes the binding generator
unable to create bindings for those types.
If some 3rd party bindings extended those types then they also need to
remove them (they will not be able to submit with the symbols anyway).
Stubs can be used, whether or not binary compatibility is provided for
the 3rd party bindings consumers.
Fix https://github.com/xamarin/xamarin-macios/issues/11947
Backport of #11953
> [d16-10] [tests][generator] Remove references to iAd.framework types

- tests/xharness/Jenkins/Reports/HtmlReportWriter.cs
This fixes a problem where the html report wouldn't be re-generated if there
was a problem loading a device (which for instance could happen if xharness
was unable to create a required simulator).
> [xharness] Handle exceptions that occur while listing device candidates gracefully.

- src/imageio.cs
- tests/xtro-sharpie/MacCatalyst-ImageIO.todo
- tests/xtro-sharpie/iOS-ImageIO.todo
- tests/xtro-sharpie/macOS-ImageIO.todo
- tests/xtro-sharpie/tvOS-ImageIO.todo
- tests/xtro-sharpie/watchOS-ImageIO.todo
@spouliot the headers say iOS 19 which makes no sense (although is good to know apple is thinking that far ahead ;) So I added 15, I wonder if adding 19 and wait for the next beta is the correct way to go.
> [ImageIO] Add support for Xcode 13 beta 3.

- dotnet/targets/Xamarin.Shared.Sdk.targets
- runtime/runtime.m
- tests/monotouch-test/ObjCRuntime/RuntimeTest.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/11750.
This is a backport of #12060.
> [release/6.0.1xx-preview7] [dotnet] Enable autorelease pools for threadpools. Fixes #11750.

- dotnet/targets/WorkloadManifest.MacCatalyst.template.json
- dotnet/targets/WorkloadManifest.iOS.template.json
- dotnet/targets/WorkloadManifest.macOS.template.json
- dotnet/targets/WorkloadManifest.tvOS.template.json
Runtime pack entries should be included in all workload manifest files,
even though they will not yet be resolved from the packs folder due to
https://github.com/dotnet/sdk/issues/14044.  These changes will also
allow us to start producing .msi files for the runtime packs for an
eventual inclusion in the Visual Studio installer.
> [dotnet] Add runtime packs to workload manifests

- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
- msbuild/Xamarin.Shared/Xamarin.Shared.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
This brings the iOS logic to verify the signature in app extensions to Mac.
> [msbuild] Share the _CodesignVerify target between iOS and Mac.

- src/chip.cs
That API was removed in beta 3.
https://github.com/xamarin/xamarin-macios/wiki/CHIP-iOS-xcode13.0-beta3
but this was missed by https://github.com/xamarin/xamarin-macios/pull/12143
> [chip] Remove API to fix intro on macOS 12 beta 3

- src/AppKit/Enums.cs
- src/AppKit/XEnums.cs
- src/UIKit/UIEnums.cs
- src/appkit.cs
- src/xkit.cs
Second group of enums (there will be more!)
There should be no breaking changes.
> [AppKit/UIKit] Share the implementation of more enums between AppKit and UIKit.

- dotnet/Makefile
- dotnet/Workloads/SignList.xml
- dotnet/Workloads/vs-workload.template.props
- dotnet/targets/WorkloadManifest.MacCatalyst.template.json
- dotnet/targets/WorkloadManifest.iOS.template.json
- dotnet/targets/WorkloadManifest.macOS.template.json
- dotnet/targets/WorkloadManifest.tvOS.template.json
- tools/devops/automation/build-pipeline.yml
- tools/devops/automation/scripts/bash/build-nugets.sh
- tools/devops/automation/templates/build/build.yml
- tools/devops/automation/templates/build/publish-nugets.yml
- tools/devops/automation/templates/build/sign-and-notarized.yml
- tools/devops/automation/templates/build/stage.yml
- tools/devops/automation/templates/release/vs-insertion-prep.yml
Context: xamarin/yaml-templates#117
Updates the .NET 6 NuGet packaging steps to exclude package metadata,
as the .msi conversion tooling does not process .nupkg file names with
the `+sha.commit` metadata.
Two new stages have been added to facilitate the Visual Studio setup
authoring process.
The first stage named "Prepare Release" will sign the .NET 6 NuGet
package content (inside and out), convert relevant packages to .msi
installers, generate Visual Studio manifests for the .msi installers,
and push the signed packages to the `xamarin-impl` feed.
The new `SignList.xml` file is required for our NuGet signing templates.
The new `xamarin-workload.props` file contains version information
and other metadata required to generate a Visual Studio manifest.
The second stage starts with a [manual …
> [release/6.0.1xx-preview7] [CI] Add Prepare Release and VS Insertion stages (again)

- src/corelocation.cs
- tests/xtro-sharpie/MacCatalyst-CoreLocation.ignore
- tests/xtro-sharpie/macOS-CoreLocation.ignore
- tests/xtro-sharpie/tvOS-CoreLocation.ignore
- tests/xtro-sharpie/watchOS-CoreLocation.ignore
Headers only mention iOS 15.
It does not make sense on tvOS (does not move much) and it's not on
Mac (or Catalyst) as validated with macOS 12 beta 3.
> [corelocation] Update annotations to to fix intro on macOS 12 beta 3

- dotnet/targets/Xamarin.Shared.Sdk.targets
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/AOTCompileTaskBase.cs
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileNativeCodeTaskBase.cs
- tests/dotnet/MySimpleApp/iOS/Makefile
- tests/dotnet/MySimpleApp/shared.mk
- tests/monotouch-test/dotnet/iOS/Makefile
- tests/monotouch-test/dotnet/shared.mk
- tests/xharness/Jenkins/TestData.cs
- tests/xharness/Jenkins/TestVariationsFactory.cs
- tools/common/Application.cs
- tools/dotnet-linker/LinkerConfiguration.cs
- tools/dotnet-linker/Steps/ComputeAOTArguments.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/11379.
Backport of #12136
> [release/6.0.1xx-preview7] [dotnet/msbuild] Add support for using LLVM to build .NET apps. Fixes #11379.

- tests/linker/ios/link sdk/HttpClientHandlerTest.cs
Fixes https://github.com/xamarin/maccore/issues/2472.
> [link sdk] Fix incorrect test logic in HttpClientHandlerTest for Mac Catalyst. Fixes #xamarin/maccore@2472.

- src/AppKit/NSAccessibility.cs
- src/appkit.cs
Third group of enums (there will be more!)
There should be no breaking changes.
> [AppKit] Move NSAccessibility enums to be in the api definition.

- dotnet/Makefile
- dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalyst/AppDelegate.cs
- dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalyst/Main.cs
- dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalyst/SceneDelegate.cs
- dotnet/Templates/Microsoft.iOS.Templates/ios-controller/Controller1.cs
- dotnet/Templates/Microsoft.iOS.Templates/ios/AppDelegate.cs
- dotnet/Templates/Microsoft.iOS.Templates/ios/Main.cs
- dotnet/Templates/Microsoft.iOS.Templates/ios/SceneDelegate.cs
- dotnet/Templates/Microsoft.macOS.Templates/macos/AppDelegate.cs
- dotnet/Templates/Microsoft.macOS.Templates/macos/Main.cs
- dotnet/Templates/Microsoft.macOS.Templates/macos/ViewController.cs
- dotnet/Templates/Microsoft.macOS.Templates/macos/ViewController.designer.cs
- dotnet/Templates/Microsoft.tvOS.Templates/tvos/AppDelegate.cs
- dotnet/Templates/Microsoft.tvOS.Templates/tvos/Main.cs
- dotnet/Templates/Microsoft.tvOS.Templates/tvos/ViewController.cs
- dotnet/Templates/Microsoft.tvOS.Templates/tvos/ViewController.designer.cs
- dotnet/targets/Microsoft.MacCatalyst.Sdk.ImplicitNamespaceImports.props
- dotnet/targets/Microsoft.iOS.Sdk.ImplicitNamespaceImports.props
- dotnet/targets/Microsoft.macOS.Sdk.ImplicitNamespaceImports.props
- dotnet/targets/Microsoft.tvOS.Sdk.ImplicitNamespaceImports.props
- dotnet/targets/Xamarin.Shared.Sdk.props
- tests/monotouch-test/ImageIO/ImageMetadataTest.cs
- tests/monotouch-test/ImageIO/MutableImageMetadataTest.cs
Also update our templates to remove any using statements for implicitly imported
namespaces.
Fixes https://github.com/xamarin/xamarin-macios/issues/12084.
> [dotnet] Add support for implicit namespace imports. Fixes #12084.

- tests/linker/ios/link sdk/HttpClientHandlerTest.cs
Fixes https://github.com/xamarin/maccore/issues/2472.
Backport of #12179
> [release/6.0.1xx-preview7] [link sdk] Fix incorrect test logic in HttpClientHandlerTest for Mac Catalyst. Fixes #xamarin/maccore@2472.

- src/AppKit/Compat.cs
- src/AppKit/Enums.cs
- src/frameworks.sources
This makes it easier to include/exclude certain enums in Mac Catalyst (since
we can use [NoMacCatalyst] instead of littering the files with "#if
MACCATALYST").
It required moving a little bit of unrelated code out of the enums source
files, but this is a much smaller change than moving all of the enums out of
these files (see #12185 for how that ends up).
> [AppKit] Make the files containing enums API source files instead of Core source files.

- src/PassKit/PKCompat.cs
- src/frameworks.sources
- src/passkit.cs
It's not valid and macOS 12 complains.
Replaced by a stub to maintain binary compatibility.
> [passkit] Disable default ctor on PKPaymentAuthorizationViewController

- tools/siminstaller/Program.cs
We can access the correct simulators fixing https://github.com/xamarin/xamarin-macios/issues/11881
fixes #11881
> [Xcode13] Use the correct simulators on beta 3. Fixes #11881

- dotnet/Makefile
- dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalyst/AppDelegate.cs
- dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalyst/Main.cs
- dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalyst/SceneDelegate.cs
- dotnet/Templates/Microsoft.iOS.Templates/ios-controller/Controller1.cs
- dotnet/Templates/Microsoft.iOS.Templates/ios/AppDelegate.cs
- dotnet/Templates/Microsoft.iOS.Templates/ios/Main.cs
- dotnet/Templates/Microsoft.iOS.Templates/ios/SceneDelegate.cs
- dotnet/Templates/Microsoft.macOS.Templates/macos/AppDelegate.cs
- dotnet/Templates/Microsoft.macOS.Templates/macos/Main.cs
- dotnet/Templates/Microsoft.macOS.Templates/macos/ViewController.cs
- dotnet/Templates/Microsoft.macOS.Templates/macos/ViewController.designer.cs
- dotnet/Templates/Microsoft.tvOS.Templates/tvos/AppDelegate.cs
- dotnet/Templates/Microsoft.tvOS.Templates/tvos/Main.cs
- dotnet/Templates/Microsoft.tvOS.Templates/tvos/ViewController.cs
- dotnet/Templates/Microsoft.tvOS.Templates/tvos/ViewController.designer.cs
- dotnet/targets/Microsoft.MacCatalyst.Sdk.ImplicitNamespaceImports.props
- dotnet/targets/Microsoft.iOS.Sdk.ImplicitNamespaceImports.props
- dotnet/targets/Microsoft.macOS.Sdk.ImplicitNamespaceImports.props
- dotnet/targets/Microsoft.tvOS.Sdk.ImplicitNamespaceImports.props
- dotnet/targets/Xamarin.Shared.Sdk.props
- tests/monotouch-test/ImageIO/ImageMetadataTest.cs
- tests/monotouch-test/ImageIO/MutableImageMetadataTest.cs
Also update our templates to remove any using statements for implicitly imported
namespaces.
Fixes https://github.com/xamarin/xamarin-macios/issues/12084.
Backport of #12173
> [release/6.0.1xx-preview7] [dotnet] Add support for implicit namespace imports. Fixes #12084.

- dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalyst/AppDelegate.cs
- dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalyst/SceneDelegate.cs
- dotnet/Templates/Microsoft.iOS.Templates/ios-controller/Controller1.cs
- dotnet/Templates/Microsoft.iOS.Templates/ios/AppDelegate.cs
- dotnet/Templates/Microsoft.iOS.Templates/ios/SceneDelegate.cs
- dotnet/Templates/Microsoft.iOS.Templates/ioslib/Class1.cs
- dotnet/Templates/Microsoft.macOS.Templates/macos/AppDelegate.cs
- dotnet/Templates/Microsoft.macOS.Templates/macos/ViewController.cs
- dotnet/Templates/Microsoft.macOS.Templates/macos/ViewController.designer.cs
- dotnet/Templates/Microsoft.tvOS.Templates/tvos/AppDelegate.cs
- dotnet/Templates/Microsoft.tvOS.Templates/tvos/ViewController.cs
- dotnet/Templates/Microsoft.tvOS.Templates/tvos/ViewController.designer.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/12085 (final fix).
This PR is best reviewed by ignoring whitespace.
> [dotnet/templates] Use file-scoped namespaces. Fixes #12085.

- src/gamekit.cs
- tests/xtro-sharpie/MacCatalyst-GameKit.ignore
- tests/xtro-sharpie/MacCatalyst-GameKit.todo
The selector is not annotated by itself (wrt Catalyst) but it maps to
`presentFriendRequestCreatorFromViewController` which is not available
on Catalyst. That part is clear in the headers
```diff
+#if TARGET_OS_IOS && !TARGET_OS_MACCATALYST
+/**
+ *  presentFriendRequestCreatorFromViewController:
...
+#elif TARGET_OS_OSX
+/**
+ *  presentFriendRequestCreatorFromWindow:
```
> [gamekit] Remove `isPresentingFriendRequestViewController` from Catalyst

- msbuild/Xamarin.Shared/Xamarin.Shared.props
Fixes https://github.com/xamarin/xamarin-macios/issues/12158.
> [msbuild] Make sure DeviceSpecificOutputPath always has a trailing slash. Fixes #12158.

- src/AppKit/Enums.cs
- src/Foundation/Enum.cs
- src/UIKit/UIEnums.cs
- tests/xtro-sharpie/macOS-Foundation.ignore
Make the NSWritingDirection enum from Foundation the main version, and
deprecate the others (AppKit.NSWritingDirection,
UIKit.UITextWritingDirection).
This makes things a bit easier with Mac Catalyst, which ships both AppKit and UIKit.
Ref: https://github.com/xamarin/xamarin-macios/issues/6573
> [AppKit/UIKit/Foundation] Use NSWritingDirection from Foundation. Partial fix for #6573.

- src/generator-attribute-manager.cs
Lack of mapping results in an error if the attribute is used
```
error BI1055: bgen: Internal error: failed to convert type 'PrologueSnippetAttribute, Xamarin.iOS.BindingAttributes, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. Please file a bug report (https://github.com/xamarin/xamarin-macios/issues/new) with a test case.
```
Unit test will be added as part of https://github.com/xamarin/xamarin-macios/pull/12165
> [generator] Fix `[PrologueSnippetAttribute]`

- dotnet/targets/Xamarin.Shared.Sdk.targets
- tests/dotnet/UnitTests/ProjectTest.cs
So that CoreCLR can create crash dumps.
Fixes https://github.com/xamarin/xamarin-macios/issues/11432.
> [dotnet] Put the 'createdump' executable in the app bundle when using CoreCLR. Fixes #11432.

- tests/introspection/ApiSelectorTest.cs
- tests/introspection/iOS/iOSApiSelectorTest.cs
This was fixed for iOS 15 but also happens on macOS 12 so the case
was moved into the common, shared test sources.
> [tests] Fix introspection on macOS 12

- mk/xamarin.mk
* xamarin/maccore@7e6ffadb1f [Xamarin.Hosting] Only warn if we try to load a framework that doesn't exist. (#2473)
* xamarin/maccore@cc42300ec4 [Xamarin.Hosting] Xcode 13 b3 doesn't have IBFoundation anymore, but it does have AssetCatalogFoundation, which we must load. (#2474)
* xamarin/maccore@3e9801ee9a [Xamarin.Hosting] Improve error reporting when dlopen fails (#2475)
Diff: https://github.com/xamarin/maccore/compare/c67d7af80d005d8a1a4321e4e5d4d148918d960b..7e6ffadb1fe1a8e1444485a9915b04dcc07ab95b
> [d16-10] Bump maccore to get mlaunch fixes for Xcode 13 beta 3.

- tests/monotouch-test/Foundation/CalendarTest.cs
This is a bit of a shot in the dark, because I can't reproduce the issue, however:
* The test only fails on Mac Catalyst / .NET.
* The only place we're missing globalization data (such as time zone info) is on Mac Catalyst / .NET.
* The test needs time zone info, because it's converting a date from the local time zone to UTC.
* The test sometimes succeeds, sometimes fails (on the bots).
* I'm not in the same time zone as the bots.
My guess is that the lack of time zone info means that at certain times of the
day the test will fail, and exactly which times depend on the current time
zone where the test is executed.
Modifying the test to use UTC datetimes instead of local datetimes should make
the problem independent of the local time zone, and always have the same
behavior. And the test …
> [monotouch-test] Fix CalendarTest.TestOrdinality to use UTC instead of local datetimes. Fixes #xamarin/maccore@2471.

- dotnet/targets/Xamarin.Shared.Sdk.targets
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ParseBundlerArgumentsTaskBase.cs
- msbuild/Xamarin.Shared/Xamarin.Shared.targets
- runtime/monotouch-main.m
- runtime/monovm-bridge.m
- runtime/runtime.m
- runtime/xamarin/main.h
- runtime/xamarin/runtime.h
- tests/dotnet/MyInterpretedApp/AppDelegate.cs
- tests/dotnet/MyInterpretedApp/Entitlements.plist
- tests/dotnet/MyInterpretedApp/Info.plist
- tests/dotnet/MyInterpretedApp/MacCatalyst/Makefile
- tests/dotnet/MyInterpretedApp/MacCatalyst/MyInterpretedApp.csproj
- tests/dotnet/MyInterpretedApp/Main.cs
- tests/dotnet/MyInterpretedApp/Makefile
- tests/dotnet/MyInterpretedApp/iOS/Makefile
- tests/dotnet/MyInterpretedApp/iOS/MyInterpretedApp.csproj
- tests/dotnet/MyInterpretedApp/shared.csproj
- tests/dotnet/MyInterpretedApp/shared.mk
- tests/dotnet/MyInterpretedApp/tvOS/Makefile
- tests/dotnet/MyInterpretedApp/tvOS/MyInterpretedApp.csproj
- tests/monotouch-test/Metal/MTLDeviceTests.cs
- tests/monotouch-test/System.Net.Http/MessageHandlers.cs
- tools/common/Application.cs
- tools/common/Target.cs
- tools/dotnet-linker/LinkerConfiguration.cs
- tools/dotnet-linker/Steps/ComputeNativeBuildFlagsStep.cs
- tools/dotnet-linker/Steps/ExtractBindingLibrariesStep.cs
- tools/linker/MonoTouch.Tuner/ListExportedSymbols.cs
* Add support for the interpreter everywhere.
* Add support for the AOT compiler everywhere we didn't support it before,
because the interpreter needs it (at least System.Private.CoreLib.dll must
be AOT-compiled when using the interpreter).
* Do FullAOT compilation on Mac Catalyst/ARM64 if we're not using the
interpreter, since we can't use the JIT.
* Fix monotouch-test to be green on Mac Catalyst/ARM64.
Fixes https://github.com/xamarin/xamarin-macios/issues/11724.
Fixes https://github.com/xamarin/xamarin-macios/issues/11421.
> [dotnet] Add support for the interpreter + AOT when needed. Fixes #11421 and #11724.

- src/Foundation/EnumDesktop.cs
- src/Foundation/Enums.cs
- src/frameworks.sources
This also meant merging the definitions for NSDocumentType.
> [Foundation] Add EnumDesktop.cs to the API sources to handle it with the generator.

- dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalyst/AppDelegate.cs
- dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalyst/SceneDelegate.cs
- dotnet/Templates/Microsoft.iOS.Templates/ios-controller/Controller1.cs
- dotnet/Templates/Microsoft.iOS.Templates/ios/AppDelegate.cs
- dotnet/Templates/Microsoft.iOS.Templates/ios/SceneDelegate.cs
- dotnet/Templates/Microsoft.iOS.Templates/ioslib/Class1.cs
- dotnet/Templates/Microsoft.macOS.Templates/macos/AppDelegate.cs
- dotnet/Templates/Microsoft.macOS.Templates/macos/ViewController.cs
- dotnet/Templates/Microsoft.macOS.Templates/macos/ViewController.designer.cs
- dotnet/Templates/Microsoft.tvOS.Templates/tvos/AppDelegate.cs
- dotnet/Templates/Microsoft.tvOS.Templates/tvos/ViewController.cs
- dotnet/Templates/Microsoft.tvOS.Templates/tvos/ViewController.designer.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/12085 (final fix).
This PR is best reviewed by ignoring whitespace.
Backport of #12197
> [release/6.0.1xx-preview7] [dotnet/templates] Use file-scoped namespaces. Fixes #12085.

- dotnet/targets/Xamarin.Shared.Sdk.targets
- tests/dotnet/UnitTests/ProjectTest.cs
So that CoreCLR can create crash dumps.
Fixes https://github.com/xamarin/xamarin-macios/issues/11432.
Backport of #12210
> [release/6.0.1xx-preview7] [dotnet] Put the 'createdump' executable in the app bundle when using CoreCLR. Fixes #11432.

- src/imageio.cs
- tests/xtro-sharpie/MacCatalyst-ImageIO.todo
- tests/xtro-sharpie/iOS-ImageIO.todo
- tests/xtro-sharpie/macOS-ImageIO.todo
- tests/xtro-sharpie/tvOS-ImageIO.todo
- tests/xtro-sharpie/watchOS-ImageIO.todo
@spouliot the headers say iOS 19 which makes no sense (although is good to know apple is thinking that far ahead ;) So I added 15, I wonder if adding 19 and wait for the next beta is the correct way to go.
Backport of #12145
> [release/6.0.1xx-preview7] [ImageIO] Add support for Xcode 13 beta 3.

- tests/xharness/Jenkins/Jenkins.cs
Adding more and more tests make the tests take longer and longer...
> [xharness] Bump timeout for the .NET unit tests.

- tests/monotouch-test/Foundation/CalendarTest.cs
This is a bit of a shot in the dark, because I can't reproduce the issue, however:
* The test only fails on Mac Catalyst / .NET.
* The only place we're missing globalization data (such as time zone info) is on Mac Catalyst / .NET.
* The test needs time zone info, because it's converting a date from the local time zone to UTC.
* The test sometimes succeeds, sometimes fails (on the bots).
* I'm not in the same time zone as the bots.
My guess is that the lack of time zone info means that at certain times of the
day the test will fail, and exactly which times depend on the current time
zone where the test is executed.
Modifying the test to use UTC datetimes instead of local datetimes should make
the problem independent of the local time zone, and always have the same
behavior. And the test …
> [release/6.0.1xx-preview7] [monotouch-test] Fix CalendarTest.TestOrdinality to use UTC instead of local datetimes. Fixes #xamarin/maccore@2471.

- dotnet/Workloads/vs-workload.template.props
- tools/devops/automation/templates/release/vs-insertion-prep.yml
Context: https://github.com/xamarin/yaml-templates/pull/121
Backport of: https://github.com/xamarin/xamarin-macios/pull/12205
Uses new versions of the nuget-msi-convert templates to support creation
of .msi files for workload manifest packs via the `GenerateManifestMsi`
task available in the `Microsoft.DotNet.Build.Tasks.Workloads` arcade
sdk.
> [CI] Use NuGet to MSI conversion v2 (#12205)

- tools/devops/automation/build-pipeline.yml
Lets not create steps using templates that will not be ran anyway. This removes those 2 extra steps when we are building on a PR.
Example of a internal build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5025066&view=results
External build (this PR :) )
> [CI] Do not even try to do net6 publishing on not main builds.

- tests/generator/BGenTests.cs
Otherwise this happens when running tests from within the IDE:
```
error BI0000: Unexpected error - Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
File name: 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
at System.ReadOnlySpan`1[T].op_Implicit (T[] array) [0x00000] in <16786cfd571c4686983021cfcee42fb4>:0
at System.Reflection.TypeLoading.CoreTypes..ctor (System.Reflection.MetadataLoadContext loader, System.String coreAssemblyName) [0x0003d] in <49552709e6e14610b2a2f34b9d5f4c52>:0
at …
```
> [tests] Add dummy variable to put System.Runtime.CompilerServices.Unsafe.dll next to the test assembly.

- tests/monotouch-test/Foundation/CalendarTest.cs
Hopefully avoids random test failures like https://github.com/xamarin/maccore/issues/2471#issuecomment-887517838.
> [monotouch-test] Adjust CalendarTest.DateComponentsTest to use a specific time zone.

- dotnet/targets/Xamarin.Shared.Sdk.targets
- tests/EmbeddedResources/ResourcesTest.cs
- tests/linker/ios/link all/CalendarTest.cs
- tests/linker/ios/link sdk/CalendarTest.cs
- tests/linker/ios/link sdk/LinkSdkRegressionTest.cs
- tests/linker/ios/link sdk/LocaleTest.cs
- tests/monotouch-test/Foundation/LocaleTest.cs
- tools/linker/MonoTouch.Tuner/ListExportedSymbols.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/11392.
> [dotnet] Globalization works for Mac Catalyst now. Fixes #11392.

- dotnet/targets/Xamarin.Shared.Sdk.targets
There's no real change here, the code did exactly this in before, but it was a
side effect of '_SdkIsSimulator' being 'true' for Mac Catalyst, which isn't
obvious. Now the logic is explicit for all platforms.
> [dotnet] Make it clearer that the linker is off by default for Mac Catalyst (like it already is for macOS).

- dotnet/targets/Xamarin.Shared.Sdk.targets
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ParseBundlerArgumentsTaskBase.cs
- msbuild/Xamarin.Shared/Xamarin.Shared.targets
- runtime/monotouch-main.m
- runtime/monovm-bridge.m
- runtime/runtime.m
- runtime/xamarin/main.h
- runtime/xamarin/runtime.h
- tests/dotnet/MyInterpretedApp/AppDelegate.cs
- tests/dotnet/MyInterpretedApp/Entitlements.plist
- tests/dotnet/MyInterpretedApp/Info.plist
- tests/dotnet/MyInterpretedApp/MacCatalyst/Makefile
- tests/dotnet/MyInterpretedApp/MacCatalyst/MyInterpretedApp.csproj
- tests/dotnet/MyInterpretedApp/Main.cs
- tests/dotnet/MyInterpretedApp/Makefile
- tests/dotnet/MyInterpretedApp/iOS/Makefile
- tests/dotnet/MyInterpretedApp/iOS/MyInterpretedApp.csproj
- tests/dotnet/MyInterpretedApp/shared.csproj
- tests/dotnet/MyInterpretedApp/shared.mk
- tests/dotnet/MyInterpretedApp/tvOS/Makefile
- tests/dotnet/MyInterpretedApp/tvOS/MyInterpretedApp.csproj
- tests/monotouch-test/Metal/MTLDeviceTests.cs
- tests/monotouch-test/System.Net.Http/MessageHandlers.cs
- tools/common/Application.cs
- tools/common/Target.cs
- tools/dotnet-linker/LinkerConfiguration.cs
- tools/dotnet-linker/Steps/ComputeNativeBuildFlagsStep.cs
- tools/dotnet-linker/Steps/ExtractBindingLibrariesStep.cs
- tools/linker/MonoTouch.Tuner/ListExportedSymbols.cs
* Add support for the interpreter everywhere.
* Add support for the AOT compiler everywhere we didn't support it before,
because the interpreter needs it (at least System.Private.CoreLib.dll must
be AOT-compiled when using the interpreter).
* Do FullAOT compilation on Mac Catalyst/ARM64 if we're not using the
interpreter, since we can't use the JIT.
* Fix monotouch-test to be green on Mac Catalyst/ARM64.
Fixes https://github.com/xamarin/xamarin-macios/issues/11724.
Fixes https://github.com/xamarin/xamarin-macios/issues/11421.
Backport of #12211
> [release/6.0.1xx-preview7] [dotnet] Add support for the interpreter + AOT when needed. Fixes #11421 and #11724.

- src/ObjCRuntime/Runtime.cs
The getter just returns the runtime appcontext value, while the setter throws
a PlatformNotSupportedException pointing at our documentation about how to
change the value at build time.
> [ObjCRuntime] Implement Runtime.UseAutoreleasePoolInThreadPool for .NET.

- tests/xharness/Jenkins/Jenkins.cs
Adding more and more tests make the tests take longer and longer...
Backport of #12240
> [release/6.0.1xx-preview7] [xharness] Bump timeout for the .NET unit tests.

- tests/xtro-sharpie/xtro-sanity/Sanitizer.cs
A new check was added to ensure that empty .todo files are not added,
yet when the sanitizer removes all lines we get an error per empty file.
Since we are auto-sanitizing, we want to remove those empty files.
> [Xtro] If the sanitizer removed all selectors, remove the file.

- tools/devops/automation/post-build-pipeline.yml
Commit 2af23dbd introduced a new "Prepare Release" stage that will
sign .NET 6 NuGet packages, and push them to the xamarin-impl feed.
The post build pipeline that pushes build metadata to Maestro for
downstream dependency updating should run after this stage.  There is
no reason to push build information to Maestro without also pushing
packages to a feed for external consumption.
> [CI] Run post build job after prepare release

- tests/dotnet/Makefile
without LLVM https://gist.github.com/spouliot/a1fb4ad87b98c3bd0e59a0501b243e09
with LLVM https://gist.github.com/spouliot/f6e8281c8b546b56991777ad1e919e4d
This should become the default https://github.com/xamarin/xamarin-macios/issues/12147
so this commit is only part of `preview.7` (and not `main`)
> [test][dotnet] Manually enable LLVM for app size comparison

- dotnet/targets/Xamarin.Shared.Sdk.targets
- runtime/runtime.m
- tests/dotnet/UnitTests/ProjectTest.cs
List all the assemblies in the app bundle and pass them to MonoVM/CoreCLR's in
the TRUSTED_PLATFORM_ASSEMBLIES initialization property.
This way CoreCLR knows where to find System.Private.CoreLib.dll for fat apps
(it's in the runtimeidentifier-specific subdirectory, and by default CoreCLR
will only look next to libcoreclr.dylib).
Fixes https://github.com/xamarin/xamarin-macios/issues/12265.
> [runtime] List all assemblies in TRUSTED_PLATFORM_ASSEMBLIES as pass it to MonoVM/CoreCLR. Fixes #12265.

- dotnet/targets/Xamarin.Shared.Sdk.targets
- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.props
- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileEntitlementsTaskBase.cs
- msbuild/Xamarin.Shared/Xamarin.Shared.props
- msbuild/Xamarin.Shared/Xamarin.Shared.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.TVOS.AppExtension.Common.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.App.Common.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.AppExtension.Common.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.AppExtension.Common.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.props
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
- tests/dotnet/UnitTests/PostBuildTest.cs
- tests/dotnet/UnitTests/ProjectTest.cs
- tests/dotnet/UnitTests/TestBaseClass.cs
* Rearrange some MSBuild logic so that the packaging/archiving code for macOS
can also be used for Mac Catalyst.
* Make the .NET build logic package/archive when requested to do so.
* Add tests.
Partial fix for https://github.com/xamarin/xamarin-macios/issues/10413.
This PR is probably easiest to review commit-by-commit.
> [dotnet/msbuild] Fix packaging and archiving support in .NET. Partial fix for #10413.

- tools/mmp/driver.cs
This makes it possible to preserve embedded debug symbols for a release build:
by passing "--package-debug-symbols=true" to mmp. Previously we'd remove the
symbols unconditionally for release builds.
This also conserves the old behavior (strip symbols in release builds), unless
users have explicitly passed "--package-debug-symbols=true" to mmp (because
PackageManagedDebugSymbols defaults to the same value as EnableDebug).
Fixes https://github.com/xamarin/xamarin-macios/issues/12263.
> [mmp] Link symbols if and only if we're packaging debug symbols. Fixes #12263.

- tests/monotouch-test/SystemConfiguration/CaptiveNetworkTest.cs
Don't presume to be able to figure out whether we should get back network info
or not, so just remove the corresponding assert.
Fixes https://github.com/xamarin/xamarin-macios/issues/12278.
> [monotouch-test] Give up in CaptiveNetworkTest.TryCopyCurrentNetworkInfo. Fixes #12278.

- tests/monotouch-test/Foundation/CalendarTest.cs
Fixes https://github.com/xamarin/maccore/issues/2481.
> [monotouch-test] Use the same timezone for the calendar as we do for the time (UTC) in CalendarTest.DateComponentsTest. Fixes #xamarin/maccore@2481.

- dotnet/targets/Xamarin.Shared.Sdk.targets
- runtime/runtime.m
This adds support to compute the NATIVE_DLL_SEARCH_DIRECTORIES value and pass
it to the runtime. It's the last property listed in #10504, so this fixes that
issue.
Fixes https://github.com/xamarin/xamarin-macios/issues/10504
> [runtime] Implement computing and passing the NATIVE_DLL_SEARCH_DIRECTORIES runtime property. Fixes #10504.

- tools/dotnet-linker/Compat.cs
In mtouch and mmp's implementation of these functions, they take the assembly
name, not the assembly path.
So for .NET, we'd previouslyget input such as "Xamarin.iOS", think it was a
filename, strip the extension, and compare "Xamarin" to the platform assembly
name, which didn't work.
Fixes https://github.com/xamarin/xamarin-macios/issues/12276.
> [dotnet-tools] Fix Profile.Is[Product|Sdk]Assembly. Fixes #12276.

- tests/monotouch-test/HealthKit/CategoryTypeIdentifierTest.cs
- tests/monotouch-test/HealthKit/QuantityTypeIdentifierTest.cs
Fixes these test failures:
MonoTouchFixtures.HealthKit.CategoryTypeIdentifier
[FAIL] EnumValues_22351 : AppleWalkingSteadinessEvent could not be created: System.ArgumentNullException: Value cannot be null.
Parameter name: hkCategoryTypeIdentifier
at ObjCRuntime.NativeObjectExtensions.GetNonNullHandle (ObjCRuntime.INativeObject self, System.String argumentName) [0x00003] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/INativeObject.cs:27
at HealthKit.HKObjectType.GetCategoryType (Foundation.NSString hkCategoryTypeIdentifier) [0x00000] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/ios/native/HealthKit/HKObjectType.g.cs:111
at HealthKit.HKCategoryType.Create (HealthKit.HKCategoryTypeIdentifier kind) [0x00000] in …
> [monotouch-test] Teach HealthKit tests about new HKQuantityTypeIdentifiers/HKCategoryTypeIdnetifiers.

- tests/monotouch-test/ObjCRuntime/RuntimeTest.cs
Fixes this test failure on device:
[FAIL] CurrentDirectory :   Current directory at launch
Expected string length 97 but was 89. Strings differ at index 1.
Expected: "/private/var/containers/Bundle/Application/4824129A-8668-4CD9..."
But was:  "/var/containers/Bundle/Application/4824129A-8668-4CD9-9280-7F..."
> [monotouch-test] Resolve symlinks in paths before comparing them.

- mk/xamarin.mk
Fixes this build breakage:
cp -R ../../xamarin-macios/msbuild/Xamarin.iOS.Tasks.Windows/bin/Release/netstandard2.0/win/ msbuild/iOS
cp: ../../xamarin-macios/msbuild/Xamarin.iOS.Tasks.Windows/bin/Release/netstandard2.0/win/: No such file or directory
make[3]: *** [msbuild.zip] Error 1
make[2]: *** [release] Error 2
make[1]: *** [package] Error 2
make: *** [package] Error 2
* xamarin/maccore@e14b89f9eb Revert "Fixes for msbuild.zip creation (https://github.com/xamarin/maccore/pull/2483)" (https://github.com/xamarin/maccore/pull/2484)
Diff: https://github.com/xamarin/maccore/compare/49974a981858f73a3d84ee675a4dcd685988f40a..e14b89f9ebd4d1d0dbd2e62ea95cb6676b85da99
> Bump maccore.

- tests/xharness/Jenkins/TestTasks/RunTest.cs
Fixes a harness exception:
Harness exception for 'monotouch-test': System.ArgumentException: '', hexadecimal value 0x1D, is an invalid character.
at System.Xml.XmlEncodedRawTextWriter.InvalidXmlChar (System.Int32 ch, System.Char* pDst, System.Boolean entitize) [0x00026] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System.Xml/System/Xml/Core/XmlEncodedRawTextWriter.cs:1420
at System.Xml.XmlEncodedRawTextWriter.WriteCDataSection (System.String text) [0x00251] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System.Xml/System/Xml/Core/XmlEncodedRawTextWriter.cs:1370
at System.Xml.XmlEncodedRawTextWriter.WriteCData (System.String …
> [xharness] Gracefully handle any exceptions that may occur when parsing build logs.

- src/ObjCRuntime/Runtime.cs
... when a `StringBuilder` is used inside
* Runtime.PrintException
* Runtime.PrintAllExceptions
> [objcruntime] Avoid intermediate strings for formatting

- dotnet/targets/Xamarin.Shared.Sdk.targets
- runtime/runtime.m
- runtime/xamarin/main.h
- tools/common/Application.cs
- tools/common/Target.cs
- tools/dotnet-linker/LinkerConfiguration.cs
- tools/linker/MonoTouch.Tuner/ListExportedSymbols.cs
* Add support for Mono Components.
* Modify how we look up symbols from native libraries shipped with Mono: we keep
track of which native libraries we linked with, and depending on how we linked
to those assemblies, we look the symbols up at runtime in either the current executable
(if linking statically), or the actual library (where the P/Invoke says they're
supposed to be).
* This means that we have to propagate how libmono is linked from the MSBuild code
to the Application class so that our existing logic is able to correctly determine
which native mono lib to use.
* Modify how we list the P/Invokes we need to preserve by taking into account the
list of native libraries from Mono we have to link with (for .NET). For legacy
Xamarin, I've reverted the logic to how it was before we …
> [runtime/tools] Implement finding native support libraries when linking statically. Fixes #10950, #11145 and #12100.

- tests/introspection/ApiAvailabilityTest.cs
- tests/introspection/ApiPInvokeTest.cs
- tests/xharness/Harness.cs
* #10883 only applies to Mac Catalyst for legacy Xamarin.
* Ignore the ApiAvailabilityTest.LegacyAttribute test on Mac Catalyst as well.
* introspection is now green on .NET/Mac Catalyst, so enable it in xharness.
Fixes https://github.com/xamarin/xamarin-macios/issues/10215.
> [introspection] Make green on .NET/Mac Catalyst. Fixes #10215.

- src/ObjCRuntime/Runtime.cs
- tools/linker/MonoTouch.Tuner/RemoveCode.cs
Previously we'd only call Runtime.RegisterEntryAssembly in the simulator if
the dynamic registrar was available, but now we may call it on device as well
(still only if the dynamic registrar is available). So modify the linker to
keep Runtime.RegisterEntryAssembly even if we're executing on device, as long
as the dynamic registrar is around.
This ensures we get the same behavior both in the simulator and on device (and
desktop for that matter).
Fixes https://github.com/xamarin/xamarin-macios/issues/12327.
> [tools] Link away Runtime.RegisterEntryAssembly if and only if we've optimized away the dynamic registrar. Fixes #12327.

- builds/Makefile
- msbuild/Makefile
- src/Makefile
- src/Makefile.generator
- tests/Makefile
- tools/mmp/Makefile
- tools/siminstaller/Makefile
- tools/xibuild/Makefile
On CI we'll collect all the binlogs in the repository and make them available
for post-build analysis if need be, so this will make it easier to diagnose
build problems.
> Always create binlogs during the build.

- src/ObjCRuntime/Selector.cs
- src/appkit.cs
- src/foundation.cs
- src/generator.cs
- src/uikit.cs
- tests/xtro-sharpie/MacCatalyst-UIKit.todo
- tests/xtro-sharpie/common-Foundation.ignore
- tests/xtro-sharpie/iOS-UIKit.ignore
- tests/xtro-sharpie/macOS-AppKit.ignore
- tests/xtro-sharpie/tvOS-UIKit.ignore
This requires a small change to the generator since `Selector.FromHandle`
can return `null` but it does not means the invoked API can (and we are
interested in the later).
Fixed up existing API returning potentially `null` `Selector`, IOW adding
the missing `[NullAllowed]` on them and updating xtro.
> [objcruntime] Enable nullable on `Selector` class

- tests/introspection/ApiSelectorTest.cs
- tests/introspection/Mac/MacApiSelectorTest.cs
Move a few macOS special cases into base class so they will apply to
Catalyst too.
> [xcode13] Fix catalyst intro tests on macOS 12

- runtime/runtime.m
- runtime/xamarin/main.h
- runtime/xamarin/runtime.h
Setting the XAMARIN_LOG_MARSHALLED_EXCEPTIONS environment variable will now
make us print all exceptions that go through exception marshalling, and how
we'll handle them.
Fixes https://github.com/xamarin/xamarin-macios/issues/12343.
> [runtime] Add support for logging exceptions that go through exception marshalling using an environment variable. Fixes #12343.

- dotnet/targets/Xamarin.Shared.Sdk.targets
- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
- tests/common/BinLog.cs
- tests/dotnet/UnitTests/TemplateProjectTest.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/12325.
> [msbuild/dotnet] Don't overwrite the 'CreateAppBundleDependsOn' property, only add to it. Fixes #12325.

- src/Foundation/MonoTouchException.cs
and avoid potential `NullReferenceException` in some code paths.
Also remove multiple string concatenations by using `StringBuilder`
> [foundation] Enable nullable for `MonoTouchException`

- Make.config
Preview 7X turns out to be something like preview 7228, which isn't quite right.
> [release/6.0.xx-preview7] Fix version to be preview 7.X, not preview 7X.

- src/CoreFoundation/OSLog.cs
- tests/introspection/ApiAvailabilityTest.cs
There's no need in having availability attributes for versions earlier
than the current minimum.
Re-enable the `Introduced` test for _legacy_ Catalyst as it's fine since
it use the older attributes. It's still not possible to enable it for
`NET` until all manual bindings are updated.
> [corefoundation] Fix minimum version on MacCatalyst

- tests/common/mac/MacMain.fs
- tests/fsharp/FSharpTests.fs
- tests/fsharp/Main.fs
- tests/fsharp/dotnet/MacCatalyst/Info.plist
- tests/fsharp/dotnet/MacCatalyst/Makefile
- tests/fsharp/dotnet/MacCatalyst/fsharp.fsproj
- tests/fsharp/dotnet/Makefile
- tests/fsharp/dotnet/iOS/Info.plist
- tests/fsharp/dotnet/iOS/Makefile
- tests/fsharp/dotnet/iOS/fsharp.fsproj
- tests/fsharp/dotnet/macOS/Info.plist
- tests/fsharp/dotnet/macOS/Makefile
- tests/fsharp/dotnet/macOS/fsharp.fsproj
- tests/fsharp/dotnet/shared.fsproj
- tests/fsharp/dotnet/shared.mk
- tests/fsharp/dotnet/tvOS/Info.plist
- tests/fsharp/dotnet/tvOS/Makefile
- tests/fsharp/dotnet/tvOS/fsharp.fsproj
- tests/xharness/Harness.cs
- tests/xharness/TestProject.cs
Partial fix for https://github.com/xamarin/xamarin-macios/issues/10217.
> [tests] Add .NET version of the fsharp test.

- msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
The `_AdditionalTaskAssembly` prop was already fixed by https://github.com/xamarin/xamarin-macios/commit/7c66aa3829c31ca9a80542230a190c0af9004105, so we don't need to do this anymore. This breaks building from Windows because we're missing custom steps.
I missed adding this file to that commit.
Backport of #12362
> [release/6.0.1xx-preview7] [net6] Stops replacing custom linker steps on Windows

- msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
The `_AdditionalTaskAssembly` prop was already fixed by https://github.com/xamarin/xamarin-macios/commit/7c66aa3829c31ca9a80542230a190c0af9004105, so we don't need to do this anymore. This breaks building from Windows because we're missing custom steps.
I missed adding this file to that commit.
> [net6] Stops replacing custom linker steps on Windows

- msbuild/Xamarin.MacDev.Tasks/Tasks/LinkNativeCode.cs
This is an improvement on how we detect if the file that is going to be copied to the Mac is coming from the output path or not. Copying files from the Windows output dir to the Mac will make the build fail.
There were two problems:
- The paths we were comparing could contain different path separators.
- The item we are trying to copy may be in a folder that is inside the output dir.
For example:
- OutputFile = `obj\Debug\net6.0-ios\iossimulator-x64\nativelibraries/Foo`
- Item to copy: `obj/Debug/net6.0-ios/iossimulator-x64/nativelibraries/aot-output/x86_64/System.Private.CoreLib.dll.o`
> [net6] Fixes LinkNativeCode task execution from Windows

- src/AssetsLibrary/ALAsset.cs
- src/AudioUnit/AudioComponent.cs
- src/CoreFoundation/CFArray.cs
- src/CoreServices/LaunchServices.cs
- src/CoreText/Adapter.cs
- src/Foundation/NSArray.cs
- src/Foundation/NSMetadataItem.cs
- src/Foundation/NSSearchPath.cs
- src/ImageIO/CGImageDestination.cs
- src/ImageIO/CGImageSource.cs
- src/MediaAccessibility/MediaAccessibility.cs
- src/MobileCoreServices/UTType.cs
- src/NaturalLanguage/NLStrongDictionary.cs
- src/PrintCore/PrintCore.cs
- src/SceneKit/SCNSceneSource.cs
- src/Security/Certificate.cs
- src/Security/SslContext.cs
- src/SystemConfiguration/CaptiveNetwork.cs
- src/generator.cs
- tests/perftest/TollFreeBridge.cs
This is another example that p/invokes are much faster than calling
selectors.
Beside the generator the manual bindings were updated to use the newer
API and the old one was decorated as `[Obsolete]`.
|                        Method |          name |                value |            Mean |           Error |        StdDev |
|------------------------------ |-------------- |--------------------- |----------------:|----------------:|--------------:|
| CFArray_StringArrayFromHandle |         empty |                   () |        123.9 ns |        68.92 ns |       3.78 ns |
| NSArray_StringArrayFromHandle |         empty |                   () |      1,422.6 ns |        25.83 ns |       1.42 ns |
| CFArray_StringArrayFromHandle |           few |    (  (...).") [108] |      1,885.2 ns | …
> [generator] Use new `CFArray.StringArrayFromHandle` instead of the existing `NSArray` API

- tests/introspection/ApiBaseTest.cs
It's a `Phase` vs `PHASE` lookup that make the tests checking for
fields fail.
```
FieldExists: 3 errors found in 6603 fields validated: PHASESpatialCategoryDirectPathTransmission, PHASESpatialCategoryEarlyReflections, PHASESpatialCategoryLateReverb
```
> [tests][intro] Fix Phase tests on macOS 12 and iOS devices

- msbuild/Xamarin.MacDev.Tasks.Core/Xamarin.MacDev.Tasks.Core.csproj
Otherwise we'll end up showing a MissingManifestResourceException whenever we
try to show any of the mtouch errors from the msbuild targets.
> [msbuild] Fix the inclusion of the mtouch errors in the Xamarin.MacDev.Tasks.Core assembly.

- tests/monotouch-test/SafariServices/ReadingListTest.cs
This test adds entries to the global reading list in Safari, and there's no
API for the test to clean up after itself, so the reading list becomes an
endless list of entries after a whlie.
Beside the fact that this is somewhat annoying for people who actually use
their reading lists, it can also can end up consuming a significant amount of
space on the hard drive, because Safari will download each site to be
available offline.
> [monotouch-test] Ignore ReadingListTest.DefaultReadingList.

- src/ObjCRuntime/ErrorHelper.cs
- src/ObjCRuntime/RuntimeException.cs
- tools/mmp/mmp.csproj
also avoid intermediate/chained calls to help the linker eliminate
some methods
> [objcruntime] Enable nullable on `ErrorHelper` and `RuntimeException`

- tests/xtro-sharpie/AttributeHelpers.cs
- tests/xtro-sharpie/EnumCheck.cs
- tests/xtro-sharpie/iOS-CoreTelephony.ignore
- tests/xtro-sharpie/iOS-iAd.ignore
- tests/xtro-sharpie/macOS-Intents.todo
- tests/xtro-sharpie/macOS-QTKit.ignore
- tests/xtro-sharpie/macOS-SafariServices.ignore
Treat [Obsoleted] enums as [Obsolete] enums: ignore them. This makes it
possible to remove a few ignored entries.
> [xtro] Ignore Obsoleted enums in EnumCheck.

- tests/xtro-sharpie/MacCatalyst-SystemConfiguration.ignore
The todo in MacCatalyst are the ignored in macOS, how did I find out:
```bash
sort -o macOS-SystemConfiguration.sorted macOS-SystemConfiguration.ignore
sort -o MacCatalyst-SystemConfiguration.sorted MacCatalyst-SystemConfiguration.todo
comm -1 -2  MacCatalyst-SystemConfiguration.sorted macOS-SystemConfiguration.sorted >> MacCatalyst-SystemConfiguration.ignore
```
Results in the added ignore and an empty .todo. I added the ignore sorted to make comparing easier.
> [SystemConfiguration] Add support for xcode13 beta4.

- msbuild/Xamarin.Shared/Xamarin.Shared.targets
That's needed for Xamarin.Mac and was _lost_ when the task was merged
between XI and XM.
Fixes https://github.com/xamarin/xamarin-macios/issues/11784
> [msbuild] Set `UseSecureTimestamp` inside `_CodesignFrameworks` too

- tests/linker/ios/link sdk/ReflectionTest.cs
It's been enabled (on dotnet side) for a while, even in debug.
Fix https://github.com/xamarin/xamarin-macios/issues/9612
> [tests][linker] Re-enable the metadata reducer test case for dotnet

- tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
This works fine now. I'm fairly sure this was fixed when the the last
custom steps of the linker were ported for dotnet illink
Fix https://github.com/xamarin/xamarin-macios/issues/11540
> [tests][monotouch-test] Re-enable registrar test for conformsToProtocol for dotnet

- src/AudioUnit/AudioComponentDescription.cs
- src/SceneKit/Defs.cs
- src/Security/SecProtocolOptions.cs
- src/StoreKit/Enums.cs
- src/avfoundation.cs
- src/callkit.cs
- src/coreaudiokit.cs
- src/corelocation.cs
- src/fileprovider.cs
- src/intentsui.cs
- src/metal.cs
- src/passkit.cs
- src/photos.cs
- src/photosui.cs
- src/pushkit.cs
- src/scenekit.cs
- src/uikit.cs
- src/videosubscriberaccount.cs
- src/xkit.cs
Instead of this:
[Unavailable (PlatformName.MacCatalyst)]
[Advice ("This API is not available when using UIKit on macOS.")]
do this:
[NoMacCatalyst]
Except when the API is actually available (in which case add the correct availability attribute), or in manual binding code (where we still have to use `[Unavailable (...)]`, although not the `[Advice (...)]`).
> [src] Use [NoMacCatalyst] everywhere.

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ParseBundlerArgumentsTaskBase.cs
It makes typos much easier to find.
> [msbuild] Show a message in the ParseBundlerArguments task if we run into an argument we don't understand.

- dotnet/targets/Xamarin.Shared.Sdk.targets
'_MonoRuntimePackPath' already contains a trailing slash, so adding another
one made two, and that was too much for MSBuild to realize that it was really
the same file as the one with only one slash in the path, and those files
weren't removed from the build correctly.
This saves ~300kb from the app size comparison:
Before: https://gist.github.com/rolfbjarne/812f3ded1cf1a8bea45c7ca9b42bf95b
After: https://gist.github.com/rolfbjarne/22b23db0a162e9b9e366392b67063907
> [dotnet] Fix exclusion of mono components.

- src/CoreFoundation/CFArray.cs
- src/corefoundation.cs
- src/generator.cs
- tests/perftest/TollFreeBridge.cs
- tests/xtro-sharpie/common-CoreFoundation.ignore
Similar to https://github.com/xamarin/xamarin-macios/pull/12368
p/invoke are faster than selectors, so we use them inside generated
bindings and suggest (thru `[Obsolete]`) the use of `CFArray` in manual
bindings and 3rd-party code.
|                        Method |          name |               value |            Mean |            Error |          StdDev |
|------------------------------ |-------------- |-------------------- |----------------:|-----------------:|----------------:|
|       CFArray_ArrayFromHandle |         empty |                  () |        120.1 ns |         31.37 ns |         1.72 ns |
|       NSArray_ArrayFromHandle |         empty |                  () |      1,433.4 ns |        168.78 ns |         9.25 ns |
|       CFArray_ArrayFromHandle |           few |   ( …
> [generator] Use new CFArray.ArrayFromHandle instead of the existing NSArray API

- Make.config
The new version generates better attributes for Mac Catalyst.
Ref: https://github.com/xamarin/ObjectiveSharpie/pull/150
> Bump ObjectiveSharpie.

- dotnet/targets/Xamarin.Shared.Sdk.targets
Fixes https://github.com/xamarin/xamarin-macios/issues/12438.
> [dotnet] Don't use system resource keys if we're debugging. Fixes #12438.

- src/homekit.cs
Not 100% sure if this is correct. 
The headers showed that they are now deprecated, but Sharpie and the web docs do not reflect this. 
I will test in Xcode to be sure!
> [HomeKit] Updates for Xcode13 Beta 5

- Make.config
This way we follow what the rest of .NET and Android do.
When we branch for RC 1, we'll make main RC 2 (and so on).
Ref: https://github.com/xamarin/xamarin-android/pull/6187
> .NET: make main the 'rc.1' release.

- runtime/runtime.m
This avoids unnecessary and confusing logging which apparently claims that we
couldn't find a symbol, when we didn't even try (on purpose).
> [runtime] Skip early from xamarin_pinvoke_override to avoid a later logging statement.

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ACToolTaskBase.cs
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/IBToolTaskBase.cs
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/XcodeCompilerToolTask.cs
This unifies some code, and prepares for not loading the app manifest at all
(in the future there might not be an app manifest in the first place).
There should be no functional difference.
Due to indentation changes this is best reviewed by ignoring whitespace: https://github.com/xamarin/xamarin-macios/pull/12441/files?diff=split&w=1
> [msbuild] Move app manifest loading code from ACTool/IBTool to the base XcodeCompiler tool.

- dotnet/targets/Xamarin.Shared.Sdk.targets
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileAppManifestTaskBase.cs
- msbuild/Xamarin.Shared/Xamarin.Shared.targets
- tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/GeneratePlistTaskTests/GeneratePlistTaskTests_Core.cs
* Add an '_AppBundleManifest' property that specifies the final path to the
Info.plist in the app bundle.
* Remove the '_AppBundleManifestPath' property, it's not used anywhere.
* Adjust the CompileAppManifest task to take the final path to the Info.plist,
instead of computing it and returning it. This way the CompileAppManifest
task does not output anything back into MSBuild (which is important, because
the CompileAppManifest task won't execute if the output file is up-to-date,
and if it's not executed, any output properties won't be set either).
> [msbuild] Add a property that specifies the final path to the Info.plist in the app bundle

- dotnet/targets/Xamarin.Shared.Sdk.targets
- runtime/runtime.m
Mono and CoreCLR need this.
Fixes https://github.com/xamarin/xamarin-macios/issues/12444.
> [runtime] Set the RUNTIME_IDENTIFER and APP_CONTEXT_BASE_DIRECTORY app context values. Fixes #12444.

- tools/common/Target.cs
- tools/dotnet-linker/Steps/GenerateMainStep.cs
This is required for Hot Reload to work.
Fixes https://github.com/xamarin/xamarin-macios/issues/12378.
> [runtime] Set DOTNET_MODIFIABLE_ASSEMBLIES=debug when running an interpreted app with debug symbols. Fixes #12378.

- dotnet/Microsoft.iOS.Sdk/targets/Microsoft.iOS.Sdk.targets
- dotnet/Microsoft.tvOS.Sdk/targets/Microsoft.tvOS.Sdk.targets
.NET doesn't support executing other targets/tasks when doing "dotnet run".
However, we need to (like we do for our current "Run" target), so implement a
rather simplistic/hacky workaround by making "dotnet run" just do "dotnet
build /t:Run".
It doesn't support everything that "dotnet run" does (for instance it doesn't
support the /no-build flag), but it should work for most use cases.
Ref: https://github.com/dotnet/sdk/issues/18436
Ref: https://github.com/xamarin/xamarin-macios/issues/12459
> [dotnet] Implement a workaround for .NET's lack of extensibility for 'dotnet run'.

- src/ILLink.Substitutions.MacCatalyst.xml
- src/ILLink.Substitutions.macOS.xml
- src/Makefile
- tests/linker/ios/link sdk/AotBugs.cs
- tests/linker/ios/link sdk/Bug2096Test.cs
- tests/linker/ios/link sdk/CryptoTest.cs
- tests/linker/ios/link sdk/DllImportTest.cs
- tests/linker/ios/link sdk/HttpClientHandlerTest.cs
- tests/linker/ios/link sdk/LinkExtraDefsTest.cs
- tests/linker/ios/link sdk/LinkSdkRegressionTest.cs
- tests/linker/ios/link sdk/dotnet/Makefile
- tests/linker/ios/link sdk/dotnet/macOS/Info.plist
- tests/linker/ios/link sdk/dotnet/macOS/Makefile
- tests/linker/ios/link sdk/dotnet/macOS/link sdk.csproj
- tests/linker/ios/link sdk/dotnet/shared.csproj
- tests/linker/ios/link sdk/dotnet/shared.mk
- tests/xharness/Harness.cs
This required adding a linker substitution file for macOS (and I also added one for Mac Catalyst).
> [tests] Add .NET version of link sdk for macOS.

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/XcodeCompilerToolTask.cs
Refactor the logic to compute the target devices for IBTool/ACTool, so that it
doesn't depend on the existence of the input app manifest, but instead uses
values that either comes from the app manifest, or have a default.
This becomes an important distinction when we add support for multiple partial
app manifests, or none at all (where all the required values come from MSBuild
properties).
> [msbuild] Refactor the logic to compute the target devices for IBTool/ACTool.

- dotnet/Microsoft.MacCatalyst.Sdk/Sdk/AutoImport.props
- dotnet/Microsoft.iOS.Sdk/Sdk/AutoImport.props
- dotnet/Microsoft.macOS.Sdk/Sdk/AutoImport.props
- dotnet/Microsoft.tvOS.Sdk/Sdk/AutoImport.props
- dotnet/Microsoft.watchOS.Sdk/Sdk/AutoImport.props
- dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalyst/MacCatalystApp1.csproj
- dotnet/Templates/Microsoft.iOS.Templates/ios/iOSApp1.csproj
- dotnet/Templates/Microsoft.iOS.Templates/ioslib/iOSLib1.csproj
- dotnet/Templates/Microsoft.macOS.Templates/macos/macOSApp1.csproj
- dotnet/Templates/Microsoft.tvOS.Templates/tvos/tvOSApp1.csproj
- dotnet/targets/Microsoft.MacCatalyst.Sdk.ImplicitNamespaceImports.props
- dotnet/targets/Microsoft.iOS.Sdk.ImplicitNamespaceImports.props
- dotnet/targets/Microsoft.macOS.Sdk.ImplicitNamespaceImports.props
- dotnet/targets/Microsoft.tvOS.Sdk.ImplicitNamespaceImports.props
- dotnet/targets/Xamarin.Shared.Sdk.props
- tests/dotnet/UnitTests/TemplateTest.cs
* Add 'ImplicitUsings=true' to all the templates.
* Make the implicit global namespaces C#-only.
* Add the implicit global namespaces to the 'Using' itemgroup instead of the
'Import' itemgroup.
* Make sure the global namespaces are set from AutoImport.props, so that the
user may remove any global namespace they don't want in their project file
(by doing something like: `<Using Remove="Foundation" />`)
Ref: https://github.com/dotnet/sdk/issues/19521
Ref: https://github.com/dotnet/sdk/issues/19793
Fixes https://github.com/xamarin/xamarin-macios/issues/12457.
> [dotnet] Update logic for default global namespaces and fix the templates. Fixes #12457.

- tests/linker/ios/link sdk/LinkSdkRegressionTest.cs
Fixes these errors:
xamarin-macios/tests/linker/ios/link sdk/LinkSdkRegressionTest.cs(1140,41): error CS0246: The type or namespace name 'NSApplication' could not be found (are you missing a using directive or an assembly reference?)
xamarin-macios/tests/linker/ios/link sdk/LinkSdkRegressionTest.cs(1156,4): error CS0103: The name 'NSApplication' does not exist in the current context
xamarin-macios/tests/linker/ios/link sdk/LinkSdkRegressionTest.cs(1157,4): error CS0103: The name 'NSApplication' does not exist in the current context
> [tests] Fix the build for link sdk tests on .NET/macOS.

- dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets
- dotnet/targets/Xamarin.Shared.Sdk.targets
- tests/linker/BaseOptimizeGeneratedCodeTest.cs
- tests/linker/ios/link sdk/ReflectionTest.cs
- tests/xharness/Jenkins/TestVariationsFactory.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/12477.
> [dotnet] Make CoreCLR the only option for macOS. Fixes #12477.

- dotnet/targets/Xamarin.Shared.Sdk.targets
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ACToolTaskBase.cs
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ReadAppManifestTaskBase.cs
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/XcodeCompilerToolTask.cs
- msbuild/Xamarin.MacDev.Tasks/Tasks/ReadAppManifest.cs
- msbuild/Xamarin.Shared/Xamarin.Shared.targets
- msbuild/Xamarin.iOS.Tasks.Core/Tasks/CompileITunesMetadataTaskBase.cs
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
- tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/IBToolTaskTests.cs
* Read CFBundleDisplayName and CFBundleVersion and use them in the
_CompileITunesMetadata task.
* Read numerous other app manifest values and pass them to the ACTool and
IBTool tasks.
This makes it possible to not parse the Info.plist in these tasks, which will
become more complicated in the future, when we might either not have an
Info.plist, or have many partial ones.
Also enable nullability.
> [msbuild] Rename the GetMinimumOSVersion task to ReadAppManifest and make it read more properties from the app manifest.

- NuGet.config
- dotnet/package/common.csproj
- tools/devops/automation/templates/release/vs-insertion-prep.yml
We should now have the ability to push to the `dotnet6` feed that
contains the rest of the .NET 6 SDK Workload packages.  This should help
simplify workload acquisition.  The .nupkg files containing .msi the
.msi installers used for VS insertions will also now be pushed to this
feed.
> [ci] Push .NET 6 packages to dnceng dotnet6 feed

- dotnet/targets/Xamarin.Shared.Sdk.targets
- msbuild/Xamarin.Localization.MSBuild/MSBStrings.Designer.cs
- msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/FindAotCompilerTaskBase.cs
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/XamarinTask.cs
- msbuild/Xamarin.MacDev.Tasks/Tasks/FindAotCompiler.cs
The MonoAotCrossCompiler item group is empty when executing remotely from
Windows, so in that case we evaluate a csproj on the Mac side to compute the
AOT compiler path instead of relying in the task input from Windows.
Ref: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1362367
Backport of #12474
> [release/6.0.1xx-rc.1] [msbuild] Add a task to compute the path to the AOT compiler.

- src/AppKit/Enums.cs
- src/AppKit/NSEnumsExtensions.cs
- src/ObjCRuntime/NativeAttribute.cs
- src/ObjCRuntime/Runtime.cs
- src/UIKit/UIEnums.cs
- src/UIKit/UIEnumsExtensions.cs
- src/frameworks.sources
- src/generator-enums.cs
- src/generator.cs
- tests/generator/BGenTests.cs
- tests/generator/tests/nativeenum-extensions.cs
- tests/generator/tests/nativeenum.cs
Augment the Native attribute for enums to support custom conversion functions between
native values and managed values for enums. This makes it possible to have different
values in managed code for an enum compared to native code.
This is necessary to support different native enum values based on the architecture,
because in a few cases Apple has different enum values between x86_64 and ARM64.
Enum values are constants in managed code, and without this support it would be impossible
to translate these correctly to native code.
The updated Native attribute supports two new fields: ConvertToNative and ConvertToManaged,
which are managed functions of a specific signature that the generator will emit
calls to whenever needed to do the appropriate conversion.
Fixes …
> [src] Augment the Native attribute to support custom conversion functions. Fixes #12111.

- system-dependencies.sh
Special paths are protected by the OS. These paths are problematic
becasue the xpcproxy_sim might not have access to them, resulting in the
simulator tests failing (the process cannot return the PID used to
launch the app).
The problem with special folders.. is that they could be or not
translated or changed so we cannot hardcode them, yet we can use a small
apple script to return the path of the ones we know about (documents,
downloads, etc), get them and check if pwd is a substring.
The following is the example of a make all under the documents path:
```
make all
Touch.Unit is up-to-date.
opentk is up-to-date.
Xamarin.MacDev is up-to-date.
macios-binaries is up-to-date.
ikvm-fork is up-to-date.
maccore is up-to-date.
ios-api-docs is up-to-date.
mac-api-docs is up-to-date. …
```
> [Makefile] Prevent people from bulding in the wrong dir.

- msbuild/Xamarin.Shared/Xamarin.Shared.targets
- tests/dotnet/UnitTests/PostBuildTest.cs
Both the CompileProductDefinition and the CreateInstaller tasks must take the
final app manifest as input, because there may now be multiple input manifests
(or one day none at all), and the final app manifest is the only version that
is guaranteed to exist and contain everything.
> [msbuild] Both the CompileProductDefinition and the CreateInstaller tasks must take the final app manifest as input.

- tests/monotouch-test/dotnet/MacCatalyst/Makefile
- tests/xharness/Jenkins/TestVariationsFactory.cs
- tools/common/Application.cs
Mac Catalyst is just special.
Also add an xharness test variation and update a test amkefile.
Fixes https://github.com/xamarin/xamarin-macios/issues/12484.
> [tools] Pass the right arguments to the AOT compiler for Mac Catalyst. Fixes #12484.

- msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
The directory that contains illink.dll was renamed to net6.0
> [dotnet] Updates the path to illink when building from Windows

- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.props
Seems like it was broken as of https://github.com/xamarin/xamarin-macios/commit/7c15428fc20d9ebecb48f999654b701707461c72
If MtouchProfiling is not set for Xamarin.Mac apps, it would not have a value. This behavioural change was also not replicated in the IDE, which still sets `Profiling`.
Change the property so it inherits MtouchProfiling if Profiling is not set and detauls to false.
> Correct Xamarin.Mac profiling properties

- tests/monotouch-test/CoreServices/HttpMessageTest.cs
- tests/monotouch-test/System.Net.Http/MessageHandlers.cs
Fixes https://github.com/xamarin/maccore/issues/2160.
Fixes https://github.com/xamarin/maccore/issues/2491.
Fixes https://github.com/xamarin/maccore/issues/2493.
Fixes https://github.com/xamarin/maccore/issues/2304.
> [monotouch-test] Ignore several HttpMessageTest test cases in CI in case of network failures.

- tests/dotnet/Makefile
This should become the default https://github.com/xamarin/xamarin-macios/issues/12147
so this commit is only part of `rc.1` (and not `main`)
Backport of #12271
> [release/6.0.1xx-rc.1] [test][dotnet] Manually enable LLVM for app size comparison

- tests/mtouch/Cache.cs
- tests/xharness/.gitignore
- tests/xharness/TestProject.cs
- tests/xharness/xharness.csproj
Improve Cache.CreateTemporaryDirectory to move the deletion of the previous
root temporary directory to a background thread. In some cases this directory
can have a lot of files and directories, and deleting it synchronously can
cause a significant startup delay when running tests locally.
> [tests] Move deletion of existing temporary directory to the background.

- tools/devops/automation/build-pipeline.yml
- tools/devops/automation/templates/build/build.yml
Include the Agent-Cleanser template from `yaml-templates` to help keep disk space in check on the build agents.  iOS builds currently run against the following pools:
[VSEng-Xamarin-RedmondMacBuildPool-iOS-Trusted](https://devdiv.visualstudio.com/_settings/agentpools?poolId=367&view=agents)
[VSEng-Xamarin-RedmondMacBuildPool-iOS-Untrusted](https://devdiv.visualstudio.com/_settings/agentpools?poolId=366&view=agents)
Related PR: https://github.com/xamarin/yaml-templates/pull/129
> [CI] Build pipeline: Agent-Cleanser: yaml-template step

- msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
The directory that contains illink.dll was renamed to net6.0
Backport of #12501
> [release/6.0.1xx-rc.1] [dotnet] Updates the path to illink when building from Windows

- msbuild/Directory.Build.props
- msbuild/Xamarin.iOS.Tasks.Windows/Tasks/CompileAppManifest.cs
- msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
The changes are explained on each commit :), two the problems fixed on this PR are related to Maui Single Projects.
Backport of #12500
> [release/6.0.1xx-rc.1] Fixes Hot Restart build issues

- src/ObjCRuntime/Selector.cs
it's not often required.
Delaying it's retrieval allows the linker to remove additional code (and
lower the memory for each selector) if the app's code never uses the
selector name.
```diff
@@ -2990,8 +2985,6 @@
{
private IntPtr handle;
-		private string name;
-
public IntPtr Handle => handle;
public Selector(IntPtr P_0)
@@ -3001,13 +2994,11 @@
ThrowHelper.ThrowArgumentException("sel", "Not a selector handle.");
}
handle = P_0;
-			name = GetName(P_0);
}
internal Selector(IntPtr P_0, bool P_1)
{
handle = P_0;
-			name = GetName(P_0);
}
public sealed override bool Equals(object? P_0)
@@ -3029,14 +3020,6 @@
return handle.GetHashCode();
}
-		internal static string GetName(IntPtr P_0)
-		{
-			return Marshal.PtrToStringAuto(sel_getName(P_0));
-		}
-
-		[DllImport("/usr/lib/libobjc.dylib")]
- …
```
> [objcruntime] Do not pre-compute the `Selector.Name` property

- tools/devops/automation/build-pipeline.yml
The `templates/release/vs-insertion-prep.yml` template which includes
package signing and feed publishing should only run against official
branches.  The condition has been updated to check the branch name for
`main` or `release/` before running.
> [ci] Only sign and push on release branches

- msbuild/Makefile
- msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Tasks.Windows.csproj
- src/Makefile.generator
- src/bgen/bgen.csproj
- tools/devops/automation/templates/release/vs-insertion-prep.yml
Backport of: https://github.com/xamarin/xamarin-macios/pull/12547
Context: https://github.com/xamarin/yaml-templates/pull/131
Enables conversion and archiving of symbol files during the VS insertion
stage.  Symbol archiving steps will only run if both the
`symbolArtifactName` parameter is provided, and `archiveSymbols` is set
to true.  The `symbolConversionFilters` parameter can be used to filter
out paths of symbol files that should not be converted/archived.
> [ci] Opt in to symbol archiving during VS insertion (#12547)

- dotnet/Microsoft.iOS.Windows.Sdk/targets/Microsoft.iOS.Windows.Sdk.targets
The .NET 6 iOS projects will use the [dotnet-project system property pages](https://github.com/dotnet/project-system/tree/main/docs/repo/property-pages) system which requires the authored .xaml pages to be imported as MEF components. I'm hooking into the _Microsoft.iOS.Windows.Sdk.targets_ file to import [Xamarin.iOS.DesignTime.targets](https://github.com/xamarin/XamarinVS/blob/feature/dotnetpropertypages/src/Features/VisualStudio.Properties/VisualStudio.iOS.DotNetProperties/DesignTimeTargets/Xamarin.iOS.DesignTime.targets) which will import each .xaml property page as a _PropertyPageSchema_.
The property pages will be placed in the same directory as the designtime targets file.
Backport of #12556
> [release/6.0.1xx-rc.1] Import .NET 6 property page targets path in iOS sdk targets

- dotnet/Workloads/SignList.xml
Commit 91c6517f bumped to a new Mono.Options package version that
included symbol files, however it appears to be missing a Microsoft
digital signature.  We can fix this by signing the file ourselves rather
than skipping it.
> [ci] Authenticode sign Mono.Options.dll

- dotnet/Workloads/SignList.xml
Commit 91c6517f bumped to a new Mono.Options package version that
included symbol files, however it appears to be missing a Microsoft
digital signature.  We can fix this by signing the file ourselves rather
than skipping it.
Backport of #12585
> [release/6.0.1xx-rc.1] [ci] Authenticode sign Mono.Options.dll

- tests/xharness/Jenkins/Reports/HtmlReportWriter.cs
Substring will throw an exception if the string is not long enough (empty string probably due to a cat):
```
System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
```
> [XHarness] Ensure we do not crash with empty lines.

- src/AudioUnit/AudioComponentDescription.cs
I know we have a test to check other deprecated messages. I'll see if we can extend that to check these dotnet obsoletes as well.
> Fixing Main: Invalid Obsolete Message

- src/mailkit.cs
- tests/xtro-sharpie/macOS-MailKit.ignore
The framework is only available on macOS 12.
It's possible (my guess) that the selectors were renamed after Xcode 13
beta 5 was released. In that case a future (RC?) Xcode will have the
updated headers.
Most selectors are working as expected
```
NSLog (@"%@", [MEMessageAction markAsReadAction]);
Message Action: Destination: (null), Read Status: 1, Flag Change: (null), Message Color: 0
```
while the last 3 do not work, even from an ObjC application
```
NSLog (@"%@", [MEMessageAction flagAction]);
+[MEMessageAction flagAction]: unrecognized selector sent to class 0x7ffa601fc5d8
```
```
NSLog (@"%@", [MEMessageAction unflagAction]);
+[MEMessageAction unflagAction]: unrecognized selector sent to class 0x7ffa601fc5d8
```
```
NSLog (@"%@", [MEMessageAction …
```
> [mailkit] Disable some selector not working on macOS 12 beta 6

- src/avkit.cs
- tests/xtro-sharpie/MacCatalyst-AVKit.ignore
Web documentation mention them to be available. Introspection disagree.
Since they are all related to a single `VideoCallSupport` category, this
feature is likely not available to Catalyst.
> [avkit] Fix `VideoCallSupport` category failure on MacCatalyst 15

- src/frameworks.sources
- src/localauthenticationembeddedui.cs
- tests/xtro-sharpie/MacCatalyst-LocalAuthenticationEmbeddedUI.ignore
- tests/xtro-sharpie/macOS-LocalAuthenticationEmbeddedUI.todo
- tools/common/Frameworks.cs
No diffs for betas 1, 4, 5
Should I transfer the MacCatalyst.todo to .ignore? AFAICT, this framework doesn't have catalyst availability.
> [LocalAuthenticationEmbeddedUI] Update bindings for Xcode 13.0 beta 2 and 3

- dotnet/Makefile
- dotnet/Workloads/vs-workload.template.props
- tools/devops/automation/build-pipeline.yml
- tools/devops/automation/templates/release/vs-insertion-prep.yml
Since both tvOS and macOS are needed on Windows, we also need the .msi versions.
tvOS and macOS are needed on Windows so that we can built multi-targeted libraries.
This also needs to go to RC 1
> Generate msi files and VS setup authoring for all .NET 6 platforms

- dotnet/Makefile
- dotnet/Workloads/vs-workload.template.props
- tools/devops/automation/build-pipeline.yml
- tools/devops/automation/templates/release/vs-insertion-prep.yml
Since both tvOS and macOS are needed on Windows, we also need the .msi versions.
tvOS and macOS are needed on Windows so that we can built multi-targeted libraries.
This also needs to go to RC 1
Backport of #12581
> [release/6.0.1xx-rc.1] Generate msi files and VS setup authoring for all .NET 6 platforms

- src/AudioUnit/AudioUnit.cs
```
AudioUnit/AudioUnit.cs(42,7): warning CS0105: The using directive for 'System.Runtime.Versioning' appeared previously in this namespace
```
> [audiounit] remove duplicate `using System.Runtime.Versioning;` to avoid build warnings

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ParseBundlerArgumentsTaskBase.cs
- msbuild/Xamarin.Shared/Xamarin.Shared.targets
This way we'll honor a _BundlerVerbosity value passed on the command line.
This fixes an inconvenience when we have when we want to increase verbosity
for a test run, which can be done by setting 'MtouchExtraArgs=-v'. This works
fine until the test we want to run wants to use MtouchExtraArgs for its own
purposes (1). If we set MtouchExtraArgs on the command line, then that value
will be global and won't be able to be overridden by the test, and the test
will fail.
With this fix we can pass _BundlerVerbosity=1 directly when building the test
to avoid the whole problem.
1. For instance, most tests pass an argument in MtouchExtraArgs to use
dlsym for NUnit.Framework.dll, which contains a P/Invoke to a native function
that doesn't exist - see the tests/nunit.framework.targets file.
> [msbuild] Make the ParseBundlerArgumentsTaskBase take the verbosity as input as well.

- msbuild/Makefile
- msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Tasks.Windows.csproj
Commit 91c6517f missed a few symbol files because it was tested against
a version of Hot Restart assemblies that had already been inserted into
VS.  The Hot Restart package version bump in commit fbbaa7fc triggered
a couple of new SymbolCheck issues that can be fixed by bringing in the
previously missed pdbs.
> [build] Add missing Hot Restart symbol files.

- tests/monotouch-test/CoreFoundation/BundleTest.cs
Fixes this error when running on M1 (and Rosetta):
MonoTouchFixtures.CoreFoundation.BundleTest.TestGetBundleIdNull : 0.9134 ms
[FAIL] TestIsArchitectureLoadable :   arm64 Expected => false
Expected: False
But was:  True
at MonoTouchFixtures.CoreFoundation.BundleTest.TestIsArchitectureLoadable() in xamarin-macios/tests/monotouch-test/CoreFoundation/BundleTest.cs:line 375
> [tests] Remove assert that fails on M1 on Rosetta.

- msbuild/Xamarin.Shared/Xamarin.Shared.targets
- tests/common/DotNet.cs
- tests/msbuild/Xamarin.MacDev.Tests/TargetTests/CollectAppManifestsTests.cs
- tests/msbuild/Xamarin.MacDev.Tests/TestHelpers/BuildEngine.cs
Also add a test.
Fixes https://github.com/xamarin/xamarin-macios/issues/10646 (for the second time).
> [msbuild] Add a public target/property to make customers able to add to the PartialAppManifest item group in their own targets. Fixes #10646.

- tests/msbuild/Xamarin.MacDev.Tests/TargetTests/DetectSigningIdentityTests.cs
Add test case to verify that we pass the right bundle identifier to
DetectSigningIdentity when we're using a partial app manifest to set the
bundle identifier.
This proves that #12051 is already fixed.
> [tests] Add test case for making sure we have the right bundle identifier when executing DetectSigningIdentity. Fixes #12051.

- dotnet/SingleProject.md
- dotnet/targets/Xamarin.Shared.Sdk.targets
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileAppManifestTaskBase.cs
- msbuild/Xamarin.Shared/Xamarin.Shared.targets
Context: https://github.com/dotnet/maui/issues/1662
Context: https://github.com/xamarin/xamarin-android/pull/6139
Previously:
* `$(ApplicationVersion)` mapped to `CFBundleVersion`
* `$(AppleShortVersion)` mapped to `CFBundleShortVersionString`
To be able to leverage identical property names on iOS/Android,
we're changing this to:
* `$(ApplicationVersion)` maps to `CFBundleVersion`
* `$(ApplicationDisplayVersion)` maps to `CFBundleShortVersionString`
Lastly, let's allow `$(ApplicationDisplayVersion)` to set `$(Version)`,
so the various C# assembly-level attributes are all set to the same value.
> [dotnet] rename $(AppleShortVersion) to $(ApplicationDisplayVersion)

- src/Foundation/NSString2.cs
Also fix `compare:` undefined behavior if used with `nil`.
ref: https://github.com/xamarin/xamarin-macios/wiki/Nullability
> [foundation] Enable nullability on NSString manual bindings

- tests/linker/ios/link sdk/LinkSdkRegressionTest.cs
Ref: https://github.com/xamarin/xamarin-macios/issues/12640
> Relax the tvOS special folder checks to make them pass both on dotnet and legacy

- dotnet/targets/Xamarin.Shared.Sdk.props
Fixes https://github.com/xamarin/xamarin-macios/issues/12147.
> [dotnet] Enable LLVM by default for release builds. Fixes #12147.

- tests/introspection/ApiProtocolTest.cs
- tests/introspection/ApiSelectorTest.cs
- tests/introspection/Mac/MacApiProtocolTest.cs
- tests/introspection/Mac/MacApiSelectorTest.cs
I ran into these failures when running on an iOS 11.4.1 device (iPhone 7 / A1778).
> [tests] Adjust a few introspection checks to work on iOS 11.4.1

- msbuild/Xamarin.Shared/Xamarin.Shared.targets
- tests/dotnet/MyInterpretedApp/Info.plist
- tests/dotnet/MyInterpretedApp/shared.csproj
- tests/dotnet/MyPartialAppManifestApp/MacCatalyst/Info.plist
- tests/dotnet/MyPartialAppManifestApp/iOS/Info.plist
- tests/dotnet/MyPartialAppManifestApp/macOS/Info.plist
- tests/dotnet/MyPartialAppManifestApp/shared.csproj
- tests/dotnet/MyPartialAppManifestApp/tvOS/Info.plist
- tests/dotnet/MySimpleApp/MacCatalyst/Info.plist
- tests/dotnet/MySimpleApp/iOS/Info.plist
- tests/dotnet/MySimpleApp/macOS/Info.plist
- tests/dotnet/MySimpleApp/shared.csproj
- tests/dotnet/MySimpleApp/tvOS/Info.plist
- tests/dotnet/NativeDynamicLibraryReferencesApp/iOS/Info.plist
- tests/dotnet/NativeDynamicLibraryReferencesApp/macOS/Info.plist
- tests/dotnet/NativeDynamicLibraryReferencesApp/shared.csproj
- tests/dotnet/NativeFileReferencesApp/iOS/Info.plist
- tests/dotnet/NativeFileReferencesApp/macOS/Info.plist
- tests/dotnet/NativeFileReferencesApp/shared.csproj
- tests/dotnet/NativeFrameworkReferencesApp/iOS/Info.plist
- tests/dotnet/NativeFrameworkReferencesApp/macOS/Info.plist
- tests/dotnet/NativeFrameworkReferencesApp/shared.csproj
- tests/dotnet/NativeXCFrameworkReferencesApp/iOS/Info.plist
- tests/dotnet/NativeXCFrameworkReferencesApp/macOS/Info.plist
- tests/dotnet/NativeXCFrameworkReferencesApp/shared.csproj
- tests/dotnet/SimpleAppWithOldReferences/MacCatalyst/Info.plist
- tests/dotnet/SimpleAppWithOldReferences/iOS/Info.plist
- tests/dotnet/SimpleAppWithOldReferences/macOS/Info.plist
- tests/dotnet/SimpleAppWithOldReferences/shared.csproj
- tests/dotnet/SimpleAppWithOldReferences/tvOS/Info.plist
We either have defaults or MSBuild properties for the most important values that
were previously required to be in the Info.plist, so now it doesn't make sense anymore
to require an Info.plist, when for simple cases it will just be an empty file.
This allows us to simplify some of our test projects and remove a few empty Info.plist files.
> [msbuild] Don't require an Info.plist for .NET builds.

- tools/dotnet-linker/Steps/ConfigurationAwareStep.cs
Instead of something like this:
ILLINK : error MT2362: The linker step 'Registrar' failed during processing: One or more errors occurred. (The registrar cannot build a signature for type `Bindings.Test.Sf' in method `Sf()`.
) (The registrar cannot build a signature for type `Bindings.Test.Sf' in method `Sf_invoke()`. (TaskId:208)
) (The registrar cannot build a signature for type `Bindings.Test.Sdldl' in method `get_PSdldl()`. (TaskId:208)
) (The registrar cannot build a signature for type `Bindings.Test.Sdldl' in method `Bindings.Test.ObjCRegistrarTest.set_PSdldl`. (TaskId:208)
) (The registrar cannot build a signature for type `Bindings.Test.Sf' in method `get_PSf()`. (TaskId:208)
) (The registrar cannot build a signature for type `Bindings.Test.Sf' in method …
> [dotnet-linker] Improve output when we report an error we raised ourselves.

- dotnet/targets/Xamarin.Shared.Sdk.targets
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CodesignTaskBase.cs
- tests/test-libraries/Makefile
- tests/test-libraries/XTest-Info-iphoneos.plist
- tests/test-libraries/XTest-Info-iphonesimulator.plist
- tests/test-libraries/XTest-Info-maccatalyst.plist
- tests/test-libraries/XTest-Info-macos.plist
- tests/test-libraries/XTest-Info-tvos.plist
- tests/test-libraries/XTest-Info-tvsimulator.plist
- tests/test-libraries/XTest-Info-watchos.plist
- tests/test-libraries/XTest-Info-watchsimulator.plist
- tools/dotnet-linker/Steps/ExtractBindingLibrariesStep.cs
.NET/MSBuild don't handle symlinks properly [1], which means that we can't ask
.NET to copy frameworks to the app bundle, since frameworks may contain
symlinks.
In our case, the symptom was that instead of copying symlinks, the file the
symlink pointed to was copied instead, and then codesign complained about
invalid bundle format when we tried to sign the framework.
We fix this by having our own target (_CopyFrameworksToBundle) to copy
frameworks to the app bundle (instead of adding all the files in the
frameworks to the ResolvedFileToPublish item group), and then using 'ditto' to
copy the frameworks.
In order to create a test case for this, I also made the macOS and Mac
Catalyst versions of the XTest framework use symlinks:
* Create a proper XTest framework bundle hierarchy for macOS …
> [msbuild/dotnet] Don't use the built-in publishing logic in .NET to copy frameworks to the app bundle. Fixes #12369.

- src/CoreFoundation/Dispatch.cs
- tests/xtro-sharpie/common-CoreFoundation.ignore
Apple does this in their headers:
#define DISPATCH_ALIAS_V2(sym)	 __asm__("_" #sym "$V2")
dispatch_queue_t
dispatch_queue_create_with_target(const char *_Nullable label,
dispatch_queue_attr_t _Nullable attr, dispatch_queue_t _Nullable target)
DISPATCH_ALIAS_V2(dispatch_queue_create_with_target);
Which means that the native compiler will call
'dispatch_queue_create_with_target$V2' when the source code says to call
'dispatch_queue_create_with_target'.
The only place I've run into this problem, is when building for tvOS (device),
and targetting exactly tvOS 10.0 (neither earlier or later), in which case the
linker fails:
Undefined symbols for architecture arm64:
"_dispatch_queue_create_with_target", referenced from:
wrapper_managed_to_native_CoreFoundation_DispatchQueue_dispatch_queue_create_ …
> [CoreFoundation] The native 'dispatch_queue_create_with_target' function is actually called 'dispatch_queue_create_with_target$V2'.

- tools/devops/automation/build-pipeline.yml
Yaml does not show the diff between the diff scheduled triggers meaning we cannot filter. We are moving to a weekend execution and just the iOS 32b ones.
> [CI] Only execute iOS 32b on weekends.

- tools/devops/automation/templates/release/vs-insertion-prep.yml
Context: https://github.com/xamarin/yaml-templates/pull/134
The .NET 6 packs will now also be pushed to a public xamarin
`net6-maui-shipping` feed during the `VS Insertion` stage.
> [vs-insertion] Push packs to "shipping" feed

- tests/fsharplibrary/dotnet/shared.mk
F# projects aren't named *.csproj.
> [tests] Fix building fsharplibrary using the makefile.

- tests/introspection/dotnet/shared.csproj
- tests/linker/ios/dont link/dotnet/shared.csproj
- tests/linker/ios/link all/dotnet/shared.csproj
- tests/linker/ios/link sdk/dotnet/shared.csproj
This is to set the -dlsym:-nunit.framework.dll option, because nunit.framework.dll
contains a P/Invoke to a function that doesn't exist.
For some reason this is more of a problem in tvOS projects than iOS projects
(although it happens for iOS projects as well).
> [tests] Import nunit.framework.targets in more .NET test projects.

- tests/linker/ios/dont link/dotnet/shared.mk
This makes it identical to the 'link sdk' and 'link all' makefiles.
> [tests] Improve makefiles for .NET's dont link test.

- tests/xharness/Jenkins/TestVariationsFactory.cs
Skip:
* Any Thumb variation (Thumb code isn't supported anymore in .NET).
* Any AssemblyBuildTarget variation (compiling assemblies to dylibs [fastdev]
or frameworks - neither is supported/implemented for .NET).
This trims down the test list a bit.
> [xharness] Skip some device variations for .NET.

- tests/perftest/ManagedRuntime.cs
- tests/perftest/dotnet/perftest.csproj
Also add a 'SupportedOSPlatformVersion' value to the .NET perftest project
file, to cope with recent changes in our .NET support.
Ref: https://github.com/dotnet/runtime/issues/58939.
> [tests] Add perf test for calling Marshal.AllocHGlobal/FreeHGlobal.

- tests/monotouch-test/Foundation/NSMutableDictionary2Test.cs
Ref: https://github.com/xamarin/maccore/issues/1605
> [tests] Add debug spew to try to track down random test failure in NSMutableDictionary2Test.AddEntries.

- runtime/bindings.h
Defining xm_nint_t to be 32-bit sized only on i386 is not the right thing to do for armv7.
Strangely enough this caused just a single test failure:
MonoTouchFixtures.Foundation.CalendarTest
[FAIL] TestFindNextDateAfterDateMatching :   Expected: <Foundation.MonoTouchException>
But was:  null
at MonoTouchFixtures.Foundation.CalendarTest.TestFindNextDateAfterDateMatching()
and that happened because:
1. We use a wrapper function around objc_msgSend:
```c
void *
xamarin_IntPtr_objc_msgSend_IntPtr_IntPtr_nuint_exception (id self, SEL sel, void * p0, void * p1, xm_nuint_t p2, GCHandle *exception_gchandle)
{
@try {
return ((func_xamarin_IntPtr_objc_msgSend_IntPtr_IntPtr_nuint_exception) objc_msgSend) (self, sel, p0, p1, p2);
} @catch (NSException *e) {
xamarin_process_nsexception_using_mode (e, …
```
> [runtime] Use the correct underlying types for our own nfloat/n(u)int types.

- src/AudioUnit/AudioUnit.cs
- src/CoreFoundation/CFStream.cs
- src/CoreGraphics/CGFont.cs
- tests/introspection/ApiPInvokeTest.cs
This matters because we use the library defined by the P/Invoke to determine
which frameworks to link with, and if we get it wrong, things like this may
happen:
Undefined symbols for architecture arm64:
"_AudioObjectGetPropertyData", referenced from:
wrapper_managed_to_native_AudioUnit_AudioUnit_AudioObjectGetPropertyData_uint_AudioUnit_AudioObjectPropertyAddress__uint__intptr__uint__uint_ in Xamarin.MacCatalyst.dll.o
because we though that the AudioObjectGetPropertyData function was in the
AudioUnit framework, and not in CoreAudio where it really is, and thus we
didn't link with the CoreAudio framework.
Also add an introspection test to verify that the library our P/Invokes point
to is correct.
> [src] Fix the library for a few P/Invokes.

- src/ObjCRuntime/Runtime.cs
instead of the helper without the `bool` argument.
This way we can avoid the extra call (likely optimized), it's code and
metadata inside applications.
```diff
--- a.cs	2021-09-14 18:52:23.000000000 -0400
+++ b.cs	2021-09-14 18:52:26.000000000 -0400
@@ -1299,7 +1299,7 @@
private static bool HasNSObject(IntPtr P_0)
{
-			return TryGetNSObject(P_0) != null;
+			return TryGetNSObject(P_0, false) != null;
}
private static IntPtr GetHandleForINativeObject(IntPtr P_0)
@@ -1654,12 +1654,7 @@
return null;
}
-		public static NSObject TryGetNSObject(IntPtr P_0)
-		{
-			return TryGetNSObject(P_0, false);
-		}
-
-		internal static NSObject TryGetNSObject(IntPtr P_0, bool P_1 = false)
+		internal static NSObject TryGetNSObject(IntPtr P_0, bool P_1)
{
lock (lock_obj)
{
@@ -1712,7 +1707,7 @@
{
return …
```
> [objcruntime] Directly call the `Runtime.TryGetNSObject(IntPtr,bool)`

- src/Foundation/NSAutoreleasePool.cs
For historical reason `NSAutoreleasePool` is bound manually. However it
can still be optimized, which is nice since it's not a type that is
likely to be subclassed.
The default `IsDirectBinding`, from `NSObject`, does the right job.
Optimized code, inside app, will look like:
```csharp
[Export("init")]
public NSAutoreleasePool()
: base(NSObjectFlag.Empty)
{
base.Handle = Messaging.IntPtr_objc_msgSend(base.Handle, Selector.GetHandle("init"));
}
```
> [foundation] Allow the optimization of `NSAutoreleasePool` bindings

- dotnet/targets/Xamarin.Shared.Sdk.targets
- tools/dotnet-linker/MarkIProtocolHandler.cs
Fixes this test failure when running monotouch-test with the dynamic registrar and
linking has been enabled:
MonoTouchFixtures.ObjCRuntime.RegistrarTest
[FAIL] TestProtocolRegistration :   UIApplicationDelegate/17669
Expected: True
This is a port of what we do during linking for legacy Xamarin apps.
Ref: 682f54da87db7b2cc0b6e699751fde2e45a3346c
Fixes https://github.com/xamarin/xamarin-macios/issues/12644.
> [dotnet-linker] Mark protocol interfaces when using the dynamic registrar. Fixes #12644.

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ParseBundlerArgumentsTaskBase.cs
- tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/ParseBundlerArgumentsTests.cs
Fix parsing extra bundler arguments where a space separates the name and the
value of the argument, like this: '--xml file.xml' (as opposed to
'--xml:file.xml' or '--xml=file.xml').
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1385946.
> [msbuild] Fix parsing extra bundler arguments where a space separates the name and value of the argument.

- tests/introspection/ApiCMAttachmentTest.cs
> [introspection] Skip VideoToolbox classes in the ApiCMAttachmentTest on tvOS devices.

- src/CoreFoundation/CFArray.cs
- tests/perftest/NativeArrayPerf.cs
- tests/perftest/legacy/perftest-legacy.csproj
The added test case has not shown any major performance enhancement,
anything (if) is lost in the noise.
Beside the performance the change has two small size advantages
* `Create` does not call another method (less metadata)
* `GetCount` is now the p/invoke `CFArrayGetCount`
// * Summary *
BenchmarkDotNet=v0.12.1.1528-nightly, OS=macOS Big Sur 11.5.2 (20G95) [Darwin 20.6.0]
Intel Core i7-4790K CPU 4.00GHz (Haswell), 1 CPU, 8 logical and 4 physical cores
[Host] : Mono 6.12.0 (2020-02/3cf59ad33da), X64
Job=InProcess  Toolchain=InProcessEmitToolchain  IterationCount=3
LaunchCount=1  WarmupCount=3
| Method | Length |        Mean |       Error |    StdDev |
|------- |------- |------------:|------------:|----------:|
| Create |      0 |    255.4 ns |    53.68 ns |   2.94 ns |
| Create |      1 …
> [corefoundation] Optimize `CFArray`

- Make.config
- Make.versions
Context: https://devblogs.microsoft.com/dotnet/update-on-dotnet-maui/
Context: https://semvercompare.azurewebsites.net/?version=15.0.101-preview.9.1&version=15.0.100-rc.2.715
.NET MAUI (and underlying optional .NET workloads) will be in a
"preview" status until Q2 2022.
Going forward in xamarin-macios/main, our version number will be
`x.0.101-preview.9.*`.
We need to bump to 101, so the version number will be higher than the
currently released `15.0.100-rc.2.715`.
> [One .NET] use preview.9 version number

- tests/xtro-sharpie/Makefile
Do not add dependencies to targets that have been disabled via ifdef.
> [Xtro] Allow to run xtro with some platforms ignored.

- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
The BundleDependentFiles item group was added as a target input some time ago [1],
but nothing ever adds to it, so it's always empty. Googling doesn't show anything
relevant either, so this looks like dead code we can remove.
[1]: d7c2a45ca9351106f83fcf7f08c1b09a8a5fb563
Ref: https://github.com/xamarin/xamarin-macios/issues/11863#issuecomment-920917955
> [msbuild] Remove the BundleDependentFiles item group, it's not used.

- tests/generator/BGenTool.cs
Properly synchronize access to the current writer in the generator tests'
ThreadStaticTextWriter class.
Should fix this random failure:
Error Message:
System.NullReferenceException : Object reference not set to an instance of an object.
Stack Trace:
at Xamarin.Tests.ThreadStaticTextWriter.WriteLine(String value) in /Users/builder/azdo/_work/1/s/xamarin-macios/tests/generator/BGenTool.cs:line 478
at System.IO.TextWriter.SyncTextWriter.WriteLine(Object value)
at System.Console.WriteLine(Object value)
at Xamarin.Tests.BGenTool.Execute() in /Users/builder/azdo/_work/1/s/xamarin-macios/tests/generator/BGenTool.cs:line 235
at Xamarin.Tests.BGenTool.AssertExecute(String message) in /Users/builder/azdo/_work/1/s/xamarin-macios/tests/generator/BGenTool.cs:line 207
at …
> [tests] Fix a thread synchronization issue in the generator tests.

- msbuild/Xamarin.Localization.MSBuild/MSBStrings.Designer.cs
- msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileAppManifestTaskBase.cs
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ReadAppManifestTaskBase.cs
- tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/CompileAppManifestTaskTests.cs
- tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/ReadAppManifestTaskTests.cs
- tools/common/Application.cs
- tools/mtouch/Errors.designer.cs
- tools/mtouch/Errors.resx
* xamarin/Xamarin.MacDev@9e6e29f [Xamarin.MacDev] Return valid iOS/macOS versions when converting betweeen iOS and macOS versions for Mac Catalyst.
Diff: https://github.com/xamarin/Xamarin.MacDev/compare/41d91e0de0354f648a2c5e09d627d0ec1bd8a873..9e6e29f2a4e89b140cb37575168faccc70c45d5f
> [msbuild/tools] Add a better error message for when we fail to convert between iOS and macOS versions for Mac Catalyst.

- runtime/runtime.m
- tools/common/Target.cs
P/Invokes may point to a dylib, while the actual library linked into the .app
might be a static library, so make sure to compare without the extension.
This fixes an issue when linking with the static version of the runtime libraries.
> [runtime/tools] Change the 'xamarin_runtime_libraries' array to contain only the names of the runtime library in question.

- tools/linker/MonoTouch.Tuner/ListExportedSymbols.cs
When checking if we need to manually preserve a native symbol, we need to
check if a P/Invoke matches both static and dynamic libraries from the Mono
runtime, not just dynamic libraries.
> [dotnet-linker] Check if both static and dynamic libraries from the Mono runtime matches P/Invoke libraries.

- msbuild/Xamarin.Localization.MSBuild/MSBStrings.Designer.cs
- msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileAppManifestTaskBase.cs
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ReadAppManifestTaskBase.cs
- tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/CompileAppManifestTaskTests.cs
- tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/ReadAppManifestTaskTests.cs
- tools/common/Application.cs
- tools/mtouch/Errors.designer.cs
- tools/mtouch/Errors.resx
* xamarin/Xamarin.MacDev@9e6e29f [Xamarin.MacDev] Return valid iOS/macOS versions when converting betweeen iOS and macOS versions for Mac Catalyst.
Diff: https://github.com/xamarin/Xamarin.MacDev/compare/41d91e0de0354f648a2c5e09d627d0ec1bd8a873..9e6e29f2a4e89b140cb37575168faccc70c45d5f
Backport of #12767
> [release/6.0.1xx-preview9] [msbuild/tools] Add a better error message for when we fail to convert between iOS and macOS versions for Mac Catalyst.

- tools/mlaunch/Makefile
When we create a package, we only execute 'make install' with a custom install
directory (and not 'make all'). This means that we have to make sure 'make
install' actually copies mlaunch to the install directory, otherwise it won't
end up in the package.
So make sure to do this when we're using mlaunch from macios-binaries (it's
already handled correctly in maccore/tools/mlaunch when building mlaunch from
source).
> [mlaunch] Make sure to install mlaunch when the 'install' target is executed.

- runtime/runtime.m
- tools/common/Target.cs
P/Invokes may point to a dylib, while the actual library linked into the .app
might be a static library, so make sure to compare without the extension.
This fixes an issue when linking with the static version of the runtime libraries.
Backport of #12792
> [release/6.0.1xx-preview9] [runtime/tools] Change the 'xamarin_runtime_libraries' array to contain only the names of the runtime library in question.

- tools/linker/MonoTouch.Tuner/ListExportedSymbols.cs
When checking if we need to manually preserve a native symbol, we need to
check if a P/Invoke matches both static and dynamic libraries from the Mono
runtime, not just dynamic libraries.
Backport of #12791
> [release/6.0.1xx-preview9] [dotnet-linker] Check if both static and dynamic libraries from the Mono runtime matches P/Invoke libraries.

- msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
The working directory on the Zip task was causing relative paths to be used and the resulting zip file to have unnecessary sub folders
Fixes Bug #1396931: [Feedback] CopyDSYMFromMac fails because path is to long (https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1396931)
> Fix CopyDSYMFromMac target to copy *.DSYM to the right path in Windows

- tools/common/Application.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/12810.
Fixes https://github.com/mono/mono/issues/21210.
Backport of #12812
> [xcode13-ios] [tools] Keep passing 'direct-icalls' to the AOT compiler for legacy Xamarin. Fixes #12810.

- tools/common/Application.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/12810.
Fixes https://github.com/mono/mono/issues/21210.
> [tools] Keep passing 'direct-icalls' to the AOT compiler for legacy Xamarin. Fixes #12810.

- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.props
All the other code related to this property was removed a long time ago
(659a74cc369395958b9c00d107281ef94873d57d).
> [msbuild] Remove dead property (AotScope).

- msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
The working directory on the Zip task was causing relative paths to be used and the resulting zip file to have unnecessary sub folders
Fixes Bug #1396931: [Feedback] CopyDSYMFromMac fails because path is to long (https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1396931)
Backport of #12811
> [xcode13-ios] Fix CopyDSYMFromMac target to copy *.DSYM to the right path in Windows

- msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
The working directory on the Zip task was causing relative paths to be used and the resulting zip file to have unnecessary sub folders
Fixes Bug #1396931: [Feedback] CopyDSYMFromMac fails because path is to long (https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1396931)
Backport of #12811
> [release/6.0.1xx-preview9] Fix CopyDSYMFromMac target to copy *.DSYM to the right path in Windows

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileAppManifestTaskBase.cs
- tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/CompileAppManifestTaskTests.cs
- tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/GeneratePlistTaskTests/GeneratePlistTaskTests_Core.cs
So that any input app manifest is copied to Windows when doing remote builds.
> [msbuild] Make the CompileAppManifestTaskBase.AppManifest property an ITaskItem.

- src/CFNetwork/CFHTTPMessage.cs
The warning is new from .net 5 but the code is old and the change of the
method is not direct, EscapeDataString does not work as EscapeUriString.
Backport of #12779
> [xcode13-ios] [src] Ignore warning due to obsolete method.

- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
- msbuild/Xamarin.Shared/Xamarin.Shared.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
The iOS version is more advanced (has additional fixes for incremental
builds), so that's the one that got chosen.
> [msbuild] Share the *CompileTextureAtlas targets between Xamarin.iOS and Xamarin.Mac.

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/OptimizeImageTaskBase.cs
- msbuild/Xamarin.MacDev.Tasks/Tasks/OptimizeImage.cs
- msbuild/Xamarin.MacDev.Tasks/Tasks/OptimizePropertyList.cs
- msbuild/Xamarin.Shared/Xamarin.Shared.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
This brings .png and .plist optimization to macOS (but no behavior is changed,
because it's already disabled by default).
> [msbuild] Share the OptimizeImage and OptimizePropertyList tasks and targets between iOS and macOS.

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileAppManifestTaskBase.cs
- tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/CompileAppManifestTaskTests.cs
- tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/GeneratePlistTaskTests/GeneratePlistTaskTests_Core.cs
So that any input app manifest is copied to Windows when doing remote builds.
Backport of #12804
> [xcode13-ios] [msbuild] Make the CompileAppManifestTaskBase.AppManifest property an ITaskItem.

- dotnet/targets/Xamarin.Shared.Sdk.targets
- tests/dotnet/UnitTests/PublishTrimmedTest.cs
For executable projects, we must run the linker (otherwise we won't produce
something that can be executed).
We'll enable the linker by default in these cases, but if the developer has
manually disabled the linker (if the linker fails to execute for any reason,
it will suggest that the developer disables it), then we should show an error
explaining why.
Fixes https://github.com/xamarin/xamarin-macios/issues/12372.
> [dotnet] Show an error if we must link, but linking has been disabled. Fixes #12372.

- tools/mlaunch/Makefile
Remove the following warning:
```
make[3]: warning: -jN forced in submake: disabling jobserver mode.
/Applications/Xcode_13.0.0-beta5.app/Contents/Developer/usr/bin/make -C ../../../maccore/tools/mlaunch install -j8
make[3]: warning: -jN forced in submake: disabling jobserver mode.
/Applications/Xcode_13.0.0-beta5.app/Contents/Developer/usr/bin/make
../../_build/Microsoft.iOS.Sdk/tools/bin/mlaunch
../../_build/Microsoft.tvOS.Sdk/tools/bin/mlaunch
```
There is no need to pass the number of jobs to be used to a submake
commands as per the gnu make documentation:
```
The ‘-j’ option is a special case (see Parallel Execution). If you set it to some numeric value ‘N’ and your operating system supports it (most any UNIX system will; others typically won’t), the parent make and all the sub-makes …
```
> [Makefile] Remove warning in submake commands.

- src/CFNetwork/CFHTTPMessage.cs
> [src] Use the correct warning number.

- Make.config
Some code branches had names with dot at the end, some code paths didn't.
Now they're all dotted in the same place.
> Make the NuGet version code a bit more consistent.

- tests/dotnet/UnitTests/PartialAppManifestTest.cs
- tests/dotnet/UnitTests/PostBuildTest.cs
- tests/dotnet/UnitTests/ProjectTest.cs
- tests/dotnet/UnitTests/TemplateProjectTest.cs
- tests/dotnet/UnitTests/TestBaseClass.cs
As more tests have been written, helper methods have been added, so this is
just making existing code use newer helper methods.
> [tests] Simplify the test code for the .NET unit tests.

- src/CFNetwork/CFHTTPMessage.cs
Wrong number was used. 
Backport of #12838
> [xcode13-ios] [src] Use the correct warning number.

- src/foundation.cs
- tests/monotouch-test/Foundation/NSHostTest.cs
- tests/xtro-sharpie/macOS-Foundation.ignore
Removes the following warning during the builds:
```
warning CS8767: Nullability of reference types in type of parameter 'host' of 'bool NSHost.Equals(NSHost host)' doesn't match implicitly implemented member 'bool IEquatable<NSHost>.Equals(NSHost? other)' (possibly because of nullability attributes)
```
Test was added to ensure that we did not throw an exception.
Backport of #12839
> [xcode13-ios] [Foundation] Remove warning due to the Equals accepting a null value.

- src/Metal/MTLDevice.cs
- tests/monotouch-test/Metal/MTLDeviceTests.cs
* MTLCopyAllDevices returns a retained object, so we need to release it.
* MTLCopyAllDevicesWithObserver returns an observer (no need to provide one). This
means we can obsolete the 'ref NSObject' overload (the API doesn't make sense),
and instead add an 'out NSObject' overload.
* The returned observer from MTLCopyAllDevicesWithObserver is retained, so we must
release it.
* The returned array from MTLCopyAllDevicesWithObserver is a retained object, so
we need to release it.
* Simpify the supporting block code for the calls to MTLCopyAllDevicesWithObserver.
* Clean up the block we passed to MTLCopyAllDevicesWithObserver.
> [Metal] Fix a few issues in MTLDevice.

- msbuild/Xamarin.Localization.MSBuild/Xamarin.Localization.MSBuild.csproj
Fixes this problem:
error MSB4018: The "FindItemWithLogicalName" task failed unexpectedly.
error MSB4018: System.IO.FileLoadException: Could not load file or assembly 'Xamarin.Localization.MSBuild, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
error MSB4018: File name: 'Xamarin.Localization.MSBuild, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
error MSB4018: at Xamarin.MacDev.Tasks.FindItemWithLogicalNameTaskBase.Execute()
error MSB4018: at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
error MSB4018: at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
> [msbuild] Sign the localization assembly as well.

- tools/devops/automation/templates/build/build.yml
- tools/devops/automation/templates/devices/build.yml
- tools/devops/automation/templates/mac/build.yml
If cleaning takes longer than 1h then something is stuck somewhere, so let's
just ignore it and hope for the best for the rest of the test run.
> [devops] Set a 1h timeout on cleanup duties.

- tests/monotouch-test/ObjCRuntime/RuntimeTest.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/12687.
> [tests] Add a test to verify that AppDomain.CurrentDomain.BaseDirectory is always something. Fixes #12687.

- dotnet/targets/Xamarin.Shared.Sdk.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.props
- tools/common/Application.cs
- tools/dotnet-linker/LinkerConfiguration.cs
Implement support for the MtouchFloat32 MSBuild property, and do so in a way
that allows us to change the default in the future, if we so wish.
Fixes https://github.com/xamarin/xamarin-macios/issues/12524.
> [dotnet] Implement support for the MtouchFloat32 MSBuild property. Fixes #12524.

- msbuild/Xamarin.Localization.MSBuild/MSBStrings.Designer.cs
- msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CreateBindingResourcePackageBase.cs
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ResolveFrameworksBase.cs
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/XamarinTask.cs
- msbuild/Xamarin.Shared/Xamarin.Shared.targets
- tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/CreateBindingResourceTaskTests.cs
- tests/msbuild/Xamarin.MacDev.Tasks.Tests/TestHelpers/TestEngine.cs
- tools/common/Assembly.cs
- tools/common/PathUtils.cs
- tools/mtouch/Errors.designer.cs
- tools/mtouch/Errors.resx
Augment the CreateBindingResourcePackage to support creating a zipped binding
resource package (which is just a zipped version of the binding resource
package). This can either be manually chosen by the new 'Compressed' property,
or automatically detected (create a zipped version when there's a symlink in
the binding resource package).
The default is to not create a zipped version in legacy Xamarin, and
automatically detect for .NET.
The problem this is trying to solve is when creating a NuGet package - NuGet
doesn't handle symlinks correctly and it's not possible to create a NuGet with
symlinks. Instead we need to create a zipfile with all the binding resources.
The default has been chosen so that we automatically create a zip file when
it's required for .NET, while still maintaining old …
> [msbuild] Augment the CreateBindingResourcePackage to support creating a zipped binding resource package.

- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Tasks.csproj
- msbuild/Xamarin.iOS.Tasks/Xamarin.iOS.Tasks.csproj
Fixes these warnings, which we don't care about:
CSC : warning CS8002: Referenced assembly 'Xamarin.MacDev.Tasks.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name. [(...)/xamarin-macios/msbuild/Xamarin.iOS.Tasks/Xamarin.iOS.Tasks.csproj]
CSC : warning CS8002: Referenced assembly 'Xamarin.iOS.Tasks.Core, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name. [(...)/xamarin-macios/msbuild/Xamarin.iOS.Tasks/Xamarin.iOS.Tasks.csproj]
CSC : warning CS8002: Referenced assembly 'Xamarin.MacDev.Tasks, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name. [(...)/xamarin-macios/msbuild/Xamarin.iOS.Tasks/Xamarin.iOS.Tasks.csproj]
CSC : warning CS8002: Referenced assembly 'Xamarin.Localization.MSBuild, …
> [msbuild] Ignore CS8002 for the Xamarin.iOS.Tasks and Xamarin.Mac.Tasks projects.

- mk/xamarin.mk
Commits: 
* [Make] Set the nuget feeds to use in CI as a make variable. (#2522)
Diff: https://github.com/xamarin/maccore/compare/6f0bf5e2f40be0afe10b23995604808a5bc48959..0be9399a534a1b7d28275a1629d95ed092fbfaa8
> [Maccore] Bump maccore to bring the feed config.

- msbuild/Xamarin.Shared/Xamarin.Shared.targets
- tests/common/DotNet.cs
- tests/dotnet/MyClassLibrary/MyClassLibrary.csproj
- tests/dotnet/UnitTests/ApplePlatformExtensions.cs
- tests/dotnet/UnitTests/DotNetUnitTests.csproj
- tests/dotnet/UnitTests/PackTest.cs
Add support for 'dotnet pack', by:
1. Add a workaround for the fact that as soon as a project has a
'NativeReference' item, .NET's MSBuild logic wants to include a
'Native.$(AssemblyName).manifest' file in the NuGet. This obviously breaks,
because we don't create such a file, so we work around it by removing the
file in question from the corresponding item groups.
2. Add any binding resource packages to the NuGet.
3. Add tests.
Fixes https://github.com/xamarin/xamarin-macios/issues/12631.
> [dotnet] Add support for 'dotnet pack'. Fixes #12631.

- tools/linker/MobileProfile.cs
- tools/linker/MonoTouch.Tuner/MonoTouchProfile.cs
The "product assembly" is supposed to be Xamarin.iOS.dll, Xamarin.Mac.dll,
etc., not other assemblies, so fix the implementation to reflect this. The
original commit where MonoTouch.Dialog-1 and MonoTouch.NUnitLite were
introduced as platform assemblies is quite old [1], and doesn't explain much,
but I believe the intention was to make us treat these assemblies as *SDK*
assemblies and link them accordingly, so I made these assemblies SDK assemblies now.
Additionally remove "Xamarin.iOS" as a hardcoded platform assembly for Mac
Catalyst, because this particular code is exclusive to legacy Xamarin, and Mac
Catalyst support will only be included in our .NET release, which means this
code does not have any purpose here, and might even break something one day.
[1]: …
> [mtouch] Make 'MonoTouch.Dialog-1' and 'MonoTouch.NUnitLite' SDK assemblies, not product assemblies. Fixes #12862.

- tools/devops/automation/templates/release/publish-nugets.yml
Using a condition will result in the template being generated which
results in the security check to run. We need to use a template and not
a condition to avoid it.
> [CI] Cannot use condition.

- tests/bindings-framework-test/iOS/bindings-framework-test.csproj
- tests/bindings-framework-test/macOS/bindings-framework-test.csproj
- tests/bindings-xcframework-test/iOS/bindings-xcframework-test.csproj
- tests/bindings-xcframework-test/macOS/bindings-xcframework-test.csproj
- tests/framework-test/iOS/framework-test-ios.csproj
- tests/framework-test/macOS/framework-test-mac.csproj
- tests/mtouch/MTouch.cs
- tests/tests-mac.sln
- tests/tests.sln
- tests/xcframework-test/iOS/xcframework-test-ios.csproj
- tests/xcframework-test/macOS/xcframework-test-mac.csproj
- tests/xharness/Harness.cs
This fixes a problem where the build from the different projects could stomp
on eachother in the obj/bin folders. It's technically possible to make this
work by setting up custom [Base][Intermediate][OutputPath] properties in the
project files, but the simplest solution is to just make sure there's no more
than a single project per directory.
> [tests] Modify a few test directories with multiple projects to have the projects in subfolders.

- src/ImageIO/CGImageDestination.cs
> [CGImageDestination] Subclass NativeObject + numerous other code updates

- src/CoreFoundation/NativeObject.cs
- src/SearchKit/SearchKit.cs
> [SearchKit] Subclass NativeObject + numerous other code updates

- msbuild/Xamarin.Shared/Xamarin.Shared.targets
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1426870.
Backport of #13179
> [xcode13.1] [msbuild] Create the directory for the .stamp file for the _CreateBindingResourcePackage target before trying to create the .stamp file.

- tests/xtro-sharpie/MacCatalyst-Foundation.ignore
- tests/xtro-sharpie/MacCatalyst-Foundation.todo
Moved selectors in .todo to .ignore for various reasons specified in comments
This PR also marks the last of the Catalyst attribute fixes! 🎉
> [Foundation] Updates for Catalyst

- dotnet/targets/Microsoft.MacCatalyst.Sdk.ImplicitNamespaceImports.props
- dotnet/targets/Microsoft.iOS.Sdk.ImplicitNamespaceImports.props
- dotnet/targets/Microsoft.macOS.Sdk.ImplicitNamespaceImports.props
- dotnet/targets/Microsoft.tvOS.Sdk.ImplicitNamespaceImports.props
Context: https://github.com/dotnet/maui/pull/3018#pullrequestreview-792369556
In order for the .NET MAUI workload to properly implement implicit
global usings:
1. The .NET MAUI workload will add many `@(Using)` entries that
conflict with each platform's APIs.
2. We need *something* to identify `@(Using)` is for a specific
platform, so we can use a new `%(Platform)` metadata for this.
3. Late in .NET MAUI's MSBuild targets, we can do:
```xml
<ItemGroup Condition=" '$(UseMaui)' == 'true' and ('$(ImplicitUsings)' == 'true' or '$(ImplicitUsings)' == 'enable') ">
<Using Remove="@(Using->HasMetadata('Platform'))" />
</ItemGroup>
```
In .NET 7, we might have a nicer design around this, but for now this
is the plan for .NET 6.
> [dotnet] add %(Platform) to any global @(Using)

- src/CoreVideo/CVMetalTexture.cs
- src/CoreVideo/CVMetalTextureCache.cs
* Remove the internal (IntPtr) constructor.
> [CVMetalTexture] Subclass NativeObject + numerous other code updates

- src/Security/SecAccessControl.cs
* The implementation of SecAccessControl was a bit unconventional: it would
only create a native object when necessary. This breaks the usual pattern,
and the original commit doesn't explain anything, so just make this class as
any other classes (native instance created in the constructor).
> [SecAccessControl] Subclass NativeObject + a few other code updates

- src/CoreVideo/CVBuffer.cs
- src/CoreVideo/CVImageBuffer.cs
- src/CoreVideo/CVPixelBuffer.cs
* Remove the internal (IntPtr) and default constructor.
> [CV[Image|Pixel[Buffer] Subclass NativeObject + numerous other code updates

- src/ImageIO/CGImageSource.cs
- src/ImageIO/CGImageSource.iOS.cs
ownership, to avoid having to call NSObject.DangerousRelease manually later.
* Remove the internal (IntPtr) constructor.
> [CGImageSource] Subclass NativeObject + numerous other code updates

- src/PrintCore/PrintCore.cs
* Subclass NativeObject to reuse object lifetime code.ç
* Remove the PrintCore.NativeInvoke class and put the P/Invokes in the
PMPrintCoreBase class - no need for a separate class for the P/Invokes in
this class.
> [PrintCore] Subclass NativeObject + numerous other code updates

- src/CoreGraphics/CGFont.cs
> [CGFont] Subclass NativeObject + numerous other code updates

- src/Security/Certificate.cs
- src/Security/SecIdentity.cs
- src/Security/Trust.cs
- tests/introspection/ApiCMAttachmentTest.cs
- tests/monotouch-test/Security/IdentityTest.cs
ownership, to avoid having to call CFObject.CFRelease manually later.
* Remove the (IntPtr) …
> [SecIdentity] Subclass NativeObject + numerous other code updates

- src/CoreVideo/CVDisplayLink.cs
> [CVDisplayLink] Subclass NativeObject + numerous other code updates

- src/corelocation.cs
- tests/xtro-sharpie/MacCatalyst-CoreLocation.ignore
- tests/xtro-sharpie/MacCatalyst-CoreLocation.todo
Move .todo to .ignore to prevent breaking changes
Backport of #13173
> [xcode13.1] [CoreLocation] Updates for Catalyst

- tests/xtro-sharpie/MacCatalyst-CoreML.ignore
- tests/xtro-sharpie/MacCatalyst-CoreML.todo
Move .todo to .ignore because Catalyst availability is not documented
Backport of #13178
> [xcode13.1] [CoreML] Updates for Catalyst

- src/MediaToolbox/MTAudioProcessingTap.cs
> [MTAudioProcessingTap] Subclass NativeObject + numerous other code updates

- src/CoreVideo/CVPixelBufferPool.cs
* Remove the internal (IntPtr) constructor.
> [CVPixelBufferPool] Subclass NativeObject + numerous other code updates

- src/CFNetwork/CFHTTPStream.cs
- src/CoreFoundation/CFUrl.cs
> [CFUrl] Subclass NativeObject + numerous other code updates

- tests/xtro-sharpie/MacCatalyst-Foundation.ignore
- tests/xtro-sharpie/MacCatalyst-Foundation.todo
Moved selectors in .todo to .ignore for various reasons specified in comments
This PR also marks the last of the Catalyst attribute fixes! ?? 
Backport of #13199
> [xcode13.1] [Foundation] Updates for Catalyst

- src/CoreFoundation/CFProxySupport.cs
- src/CoreFoundation/CFRunLoop.cs
- src/CoreFoundation/CFSocket.cs
- src/Foundation/NSUrlSessionHandler.cs
* Make the (IntPtr, bool) constructor internal for .NET
* Make the CFRunLoopSourceCreate P/Invoke take a ref parameter to avoid manual
memory handling.
> [CFRunLoop] Subclass NativeObject + numerous other code updates

- src/CoreVideo/CVMetalTextureCache.cs
> [CVMetalTextureCache] Subclass NativeObject + numerous other code updates

- src/CoreGraphics/CGPath.cs
Fix the issue with:
```
CGPath? path1 = null;
var a = path1 != null;
var b = path1 == null;
```
```
error CS8604: Possible null reference argument for parameter 'path1' in 'bool CGPath.operator !=(CGPath path1, CGPath path2)'.
```
> Fix Nullability

- src/CoreText/CTTextTab.cs
> [CTTextTab] Subclass NativeObject + numerous other code updates

- src/CoreText/CTFrame.cs
> [CTFrame] Subclass NativeObject + numerous other code updates

- src/CoreGraphics/CGPDFDocument.cs
- src/CoreGraphics/CGPDFPage-2.cs
- src/CoreGraphics/CGPDFPage.cs
> [CGPDFPage] Subclass NativeObject + numerous other code updates

- src/CoreGraphics/CGPDFOperatorTable.cs
> [CGPDFOperatorTable] Subclass NativeObject + numerous other code updates

- src/CoreText/CTLine.cs
* Simplify block creation code a bit.
> [CTLine] Subclass NativeObject + numerous other code updates

- src/ImageIO/CGImageMetadata.cs
- src/ImageIO/CGMutableImageMetadata.cs
> [CG[Mutable]ImageMetadata] Subclass NativeObject + numerous other code updates

- src/CoreGraphics/CGContextPDF.cs
> [CGContextPDF] Enable nullability + a few other code updates

- src/CoreGraphics/CGPDFString.cs
> [CGPDFString] Enable nullability + a few other code updates

- src/CoreText/CTFontDescriptor.cs
* Use CFArray helper methods to reduce code duplication.
* Remove the internal (IntPtr) constructor.
> [CTFontDescriptor] Subclass NativeObject + numerous other code updates

- src/CoreText/CTFontCollection.cs
* Use CFArray helper methods to create managed array from native CFArrays.
> [CTFontCollection] Subclass NativeObject + numerous other code updates

- src/CoreText/CTGlyphInfo.cs
> [CTGlyphInfo] Subclass NativeObject + numerous other code updates

- src/CoreText/CTParagraphStyle.cs
> [CTParagraphStyle] Subclass NativeObject + numerous other code updates

- src/CoreText/CTFrame.cs
- src/CoreText/CTFramesetter.cs
> [CTFrameSetter] Subclass NativeObject + numerous other code updates

- src/naturallanguage.cs
Fixes:
> naturallanguage.cs(470,20): error CS8639: The typeof operator cannot be used on a nullable reference type
> [NaturalLanguage] Remove wrong XAMCORE_4_0 code.

- src/ImageIO/CGImageMetadataTag.cs
- tests/monotouch-test/ImageIO/ImageMetadataTagTest.cs
> [CGImageMetadataTag] Subclass NativeObject + numerous other code updates

- src/AudioToolbox/AudioBuffers.cs
> [AudioBuffers] Enable nullability + a few other fixes.

- src/AudioToolbox/AudioConverter.cs
> [AudioConverter] Enable nullability + a few other code updates

- src/Security/Authorization.cs
> [Security/Authorization] Enable nullability + a few other code updates

- src/CoreGraphics/CGPDFArray.cs
- src/CoreGraphics/CGPDFDictionary.cs
- src/CoreGraphics/CGPDFObject.cs
- src/CoreGraphics/CGPDFStream.cs
- tests/monotouch-test/CoreGraphics/PDFArrayTest.cs
- tests/monotouch-test/CoreGraphics/PDFObjectTest.cs
* Make CGPDFObject a common subclass for the CGPDF[Array|Dictionary|Stream]
classes, and keep the object lifetime code there.
* Make any (IntPtr) constructors internal for .NET
* Simplify block creation code a bit.
> [CGPDFObject] Make CGPDFObject a subclass of CGPDF[Array|Dictionary|Stream] + a few other fixes.

- tools/devops/automation/build-pipeline.yml
- tools/devops/automation/templates/mac/stage.yml
We do not have actual bots for 10.15 but we do have an image. So in that case we can state that the pool should be an image. Changes will ensure that the stage will find a device that does have the correct os version.
> [CI] Use a vimage for 10.15 since we do not have actual bots.

- src/AppKit/Enums.cs
* NSEventSubtype: add missing members, and make the underlying type 'short' for all platforms in .NET.
* NSSystemDefinedEvents, NSEventMouseSubtype: obsolete (and remove from .NET),
and point to NSEventSubtype.
> [AppKit] Fix a few enums for .NET according to current AppKit headers.

- src/Makefile
- src/Makefile.generator
- src/frameworks.sources
- src/iAd/ADCompat.cs
- src/iAd/iAd.cs
- src/iad.cs
- tools/common/Frameworks.cs
- tools/common/StaticRegistrar.cs
Also implement a way to use a different response file with HAS_<framework> defines for .NET.
This allows us to have different HAS_<framework> values for the .NET build
(to take into account frameworks that has been removed).
> [iAd] Remove this framework from .NET.

- src/AppKit/Enums.cs
Fixes this xtro failure:
> !unknown-native-enum! NSEventSubtype bound
Fixes https://github.com/xamarin/maccore/issues/2528.
> [AppKit] Remove NSEventSubtype from Mac Catalyst.

- src/AudioUnit/AudioUnit.cs
- src/ObjCRuntime/INativeObject.cs
> [AudioUnit] Enable nullability + a few other code updates

- src/AudioToolbox/AudioConverter.cs
Fixes this unintended breaking API change:
```diff
Type Changed: AudioToolbox.AudioConverter
-public AudioConverterError FillComplexBuffer (ref int outputDataPacketSize, AudioBuffers outputData, AudioStreamPacketDescription[] packetDescription);
+public AudioConverterError? FillComplexBuffer (ref int outputDataPacketSize, AudioBuffers outputData, AudioStreamPacketDescription[] packetDescription);
```
> [AudioToolbox] AudioConverter.FillComplexBuffer doesn't return a nullable value.

- src/AudioToolbox/SystemSound.cs
> [SystemSound] Enable nullability + a few other code updates

- src/AudioToolbox/MusicSequence.cs
- src/AudioUnit/AUGraph.cs
* Fix ownership logic: we can't call CFRetain on this type, but we can keep
track of whether we own it or not.
> [AUGraph] Enable nullability + a few other code updates

- src/AudioToolbox/MusicTrack.cs
Fixes this compile error:
> AudioToolbox/MusicTrack.cs(256,11): error CS8603: Possible null reference return.
> [AudioToolbox] Fix nullability issue to fix broken build.

- src/AudioToolbox/MusicTrack.cs
- src/AudioUnit/AudioComponent.cs
- src/AudioUnit/AudioUnit.cs
- src/Foundation/DictionaryContainer.cs
* Make the 'handle' field private.
> [AudioComponent] Enable nullability + a few other code updates

- src/ObjCRuntime/Class.cs
- src/ObjCRuntime/Runtime.cs
- src/gameplaykit.cs
- src/uikit.cs
* Make the 'handle' field private.
* Make the (IntPtr, bool) constructor internal for .NET
* Remove unused 'Construct' method.
> [Class] Enable nullability + fix a few code updates.

- Make.config
- README.md
- tools/apidiff/Makefile
Also fix make logic to only have a single rule per hash, which avoids a few make warnings about duplicate targets.
Update README with new releases.
> [api-diff] Bump to latest stable (xcode13.1 branch) + add support for different reference api urls for legacy iOS and Mac.

- src/Makefile
- src/Security/SslConnection.cs
- src/Security/SslContext.cs
Ref https://github.com/xamarin/xamarin-macios/issues/10470.
> [.NET/Security] Use [UnmanagedCallersOnly] instead of [MonoPInvokeCallback] for the managed callbacks called from native code.

- src/Makefile
- src/generate-frameworks-constants/Program.cs
- src/generate-frameworks-constants/generate-frameworks-constants.csproj
This way we can have different constants for frameworks for .NET (since some
frameworks have been removed for .NET).
> [src] Generate a .NET-specific version of Constants.<platform>.generated.cs.

- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.cs.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ja.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pl.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.tr.resx
- tools/mtouch/TranslatedAssemblies/Errors.cs.resx
- tools/mtouch/TranslatedAssemblies/Errors.ja.resx
- tools/mtouch/TranslatedAssemblies/Errors.pl.resx
- tools/mtouch/TranslatedAssemblies/Errors.tr.resx
> Localized file check-in by OneLocBuild Task: Build definition ID 14411: Build ID 5419189

- tools/devops/automation/scripts/GitHub.psm1
Sometimes you just need the whole thing, and this cuts down the number of
clicks to 20% (from 5 to 1) to get it, and it also avoids waiting for
intermediate (and slow) web pages to load.
> [devops] Add a download link to the Html Report entry in the GH summary comment.

- src/CoreBluetooth/CBCompat.cs
- src/CoreBluetooth/CBPeer.cs
- src/CoreBluetooth/CoreBluetooth.cs
- src/CoreBluetooth/Enums.cs
- src/CoreBluetooth/GuidWrapper.cs
- src/corebluetooth.cs
- tests/monotouch-test/CoreBluetooth/CentralManagerTest.cs
* Change all XAMCORE_4_0 defines to NET defines to get the new API version in
.NET.
* Remove some dead code.
* Change all the old-style [Availability] attributes to new-style [Obsoleted]
or [Deprecated].
* Adjust tests.
> [CoreBluetooth] Use new availability attributes and remove API that isn't in Apple's headers from .NET.

- src/Security/SecProtocolMetadata.cs
- src/Security/SecProtocolOptions.cs
- src/Security/SecureTransport.cs
- src/Security/SslContext.cs
- src/foundation.cs
- tests/monotouch-test/Security/SecProtocolMetadataTest.cs
- tests/monotouch-test/Security/SecureTransportTest.cs
* Remove the SslCipherSuite enum from .NET, it's complicated to implement
correctly on macOS for both x64 and arm64, and it's also obsolete, so just
remove it.
* Change the type for NSUrlSessionTaskTransactionMetrics.NegotiatedTlsCipherSuite
to be TlsCipherSuite instead of SslCipherSuite for .NET (this is in fact the
correct value according to the headers).
Fixes https://github.com/xamarin/xamarin-macios/issues/11498.
> [Security] Remove the SslCipherSuite enum from .NET. Fixes #11498.

- src/CoreGraphics/CGPath.cs
Make the MakeMutable function take into account that the input might have to
be released, offer a way to do so, and update all callsites.
Fixes https://github.com/xamarin/xamarin-macios/issues/11339.
> [CGPath] Fix leak when creating mutable CGPaths. Fixes #11339.

- tools/devops/automation/templates/mac/build.yml
We want to use release pipelines but they do not like failing tests. In
device tests we set those in the pipeline to green yet we add a comment,
we do the same with the mac tests.
> [CI] Do not set the stage to failure on mac tests fails.

- src/CoreGraphics/CGBitmapContext.cs
This way we don't leak the CGBitmapContext.
Fixes https://github.com/xamarin/xamarin-macios/issues/13309.
Backport of #13310
> [xcode13.1] [CGBitmapContext] Call the correct base constructor to specify ownership. Fixes #13309.

- tests/packaged-macos-tests.mk
Any failure stamp files are deleted before the failing target exists, so
checking for failure stamp files at a later point won't work.
> [tests] Fix checking for sub-test failures in packaged macOS tests.

- tests/packaged-macos-tests.mk
Make needs twice the amount of dollars to do the right thing.
> [tests] Fix macOS 10.15+ version check for Mac Catalyst to actually work.

- src/Foundation/DictionaryContainer.cs
* Add a [NotNullWhen] attribute to the 'key' parameter for the NullCheckAndRemoveKey
method, which means that if the method returns true, the 'key' parameter wasn't
null, and thus we can remove numerous ignored null check in call sites ("key!"
-> "key").
* Use CFString.CreateNative/ReleaseNative instead of other means to create native
strings (the fastest and least memory hungry option).
* Remove unnecessary IntPtr.Zero checks before calling NSArray.ArrayFromHandle.
* Use the null-safe NativeObjectExtensions.GetHandle extension method to get the
handle instead of checking for null (avoids some code duplication).
> [DictionaryContainer] Improve nullability + a few other code improvements.

- tools/devops/automation/build-pipeline.yml
The internal image is not longer supported and we do not have
self-hosted bots for the version of the OS.
We remove the tests since they wont pick up any agent.
> [CI] Remove 10.13 tests

- src/AudioToolbox/SystemSound.cs
- tests/monotouch-test/AudioToolbox/SystemSoundTest.cs
The supposed handle for system sounds is an uint, which does not match the
IntPtr handle INativeObject uses, so remove the INativeObject interface from
the SystemSound class.
> [SystemSound] Don't implement the INativeObject interface for .NET.

- src/AudioToolbox/AudioConverter.cs
- src/AudioToolbox/AudioFile.cs
- src/AudioToolbox/MusicPlayer.cs
- src/AudioToolbox/MusicSequence.cs
- src/AudioToolbox/MusicTrack.cs
- src/AudioUnit/AUGraph.cs
- src/AudioUnit/AudioComponent.cs
- src/AudioUnit/AudioUnit.cs
- src/CoreFoundation/NativeObject.cs
- src/Darwin/SystemLog.cs
- src/ObjCRuntime/DisposableObject.cs
- src/Security/Authorization.cs
- src/frameworks.sources
Add a new DisposableObject class, which is a new base class below
NativeObject, to be used for types that aren't reference counted, but still
disposable. NativeObject is now implemented on top of this type, adding
support for reference counting.
Also change several type to use DisposableObject as their base type, which
makes it possible to share a lot more code and delete a good chunk of
duplicated code.
> [src] Introduce DisposableObject and use it.

- src/Foundation/NSMutableData.cs
> [NSMutableData] Enable nullability + a few other code updates

- src/Foundation/NSZone.cs
* Make the (IntPtr, bool) constructor internal for .NET
> [NSZone] Enable nullability + a few other code updates

- src/corenfc.cs
* Update code to use the correct name for a few enums.
* Change XAMCORE_4_0 ifdefs to be NET ifdefs.
Fixes these errors when building for XAMCORE_4_0/.NET:
> corenfc.cs(821,96): error CS0246: The type or namespace name 'EncryptionId' could not be found (are you missing a using directive or an assembly reference?)
> corenfc.cs(838,36): error CS0246: The type or namespace name 'PollingRequestCode' could not be found (are you missing a using directive or an assembly reference?)
> corenfc.cs(838,68): error CS0246: The type or namespace name 'PollingTimeSlot' could not be found (are you missing a using directive or an assembly reference?)
> corenfc.cs(1035,3): error CS0246: The type or namespace name 'VasErrorCode' could not be found (are you missing a using directive or an assembly …
> [CoreNFC] Incorporate XAMCORE_4_0 changes into .NET.

- src/CoreServices/FSEvents.cs
- tests/monotouch-test/CoreServices/FSEventStreamTest.cs
The FSEventStreamCreate method takes a pointer to a structure with context information,
which contains a user-defined pointer value in addition to a few callbacks. Previously
we were passing the GCHandle as a pointer to this structure, which is obviously quite
wrong (as evidenced by a native crash when calling FSEventStreamCreate).
Changes:
* Modify the code to provide the expected context structure instead with the GCHandle
as a field in that structure.
* Add a release callback to the context structure to release the GCHandle.
* This avoids the need for storing the GCHandle as a field in the FSEventStream instance.
* It also avoids also the need for overriding Dispose to release said GCHandle.
* Modify the callback code to use the [UnmanagedCallersOnly] attribute for .NET
(ref: #10470). …
> [CoreServices] Fix FSEventStream to properly pass the managed context to the FSEventStreamCreate method. Fixes #13325.

- src/CoreServices/FSEvents.cs
- tests/monotouch-test/CoreServices/FSEventStreamTest.cs
The FSEventStreamCreate method takes a pointer to a structure with context information,
which contains a user-defined pointer value in addition to a few callbacks. Previously
we were passing the GCHandle as a pointer to this structure, which is obviously quite
wrong (as evidenced by a native crash when calling FSEventStreamCreate).
Changes:
* Modify the code to provide the expected context structure instead with the GCHandle
as a field in that structure.
* Add a release callback to the context structure to release the GCHandle.
* This avoids the need for storing the GCHandle as a field in the FSEventStream instance.
* It also avoids also the need for overriding Dispose to release said GCHandle.
* Modify the callback code to use the [UnmanagedCallersOnly] attribute for .NET
(ref: #10470). …
> [xcode13.1] [CoreServices] Fix FSEventStream to properly pass the managed context to the FSEventStreamCreate method. Fixes #13325.

- tools/devops/automation/build-pipeline.yml
The agent is not reporting the OS version property and returns only
11.0. This has been fixed in:
https://github.com/microsoft/azure-pipelines-agent/pull/3605
But this was not yet landed.
> [CI] Do not try to find the minor version until a bug is fixed.

- src/ObjCRuntime/DynamicRegistrar.cs
- src/ObjCRuntime/Registrar.cs
- tests/common/BundlerTool.cs
- tests/common/Profile.cs
- tests/common/Tool.cs
- tests/mtouch/MTouchTool.cs
- tests/mtouch/RegistrarTest.cs
- tests/mtouch/mtouchtests.csproj
- tools/common/StaticRegistrar.cs
* Stop using AvailabilityBaseAttribute, this type will disappear in .NET.
* Handle System.Runtime.Versioning.SupportedOSPlatformAttribute instead of our own availability attributes for .NET.
* Add tests (somewhat hacked together, but they work).
> [mtouch/mmp/dotnet-bundler] Rework getting the availability attributes so that it works for .NET as well.

- src/arkit.cs
- src/soundanalysis.cs
The [return: ...] syntax doesn't work for properties. The intention was clear
though, so fix the attribute syntax to do the right thing for .NET.
> [ARKit/SoundAnalysis] Fix BindAs attribute for .NET

- src/AddressBook/ABPerson.cs
- src/Foundation/NSData.cs
- src/Security/Trust.cs
* Remove the internal (IntPtr, bool) constructor, it has non-standard semantics and it's confusing.
> [NSData] Enable nullability + a few other code updates

- tools/compare-commits.sh
Removes this from the generator diff, which happens on every build:
diff --git a/build/common/bgen.exe.binlog b/build-new/common/bgen.exe.binlog
index fc4ecd1fe..3b0503171 100644
Binary files a/build/common/bgen.exe.binlog and b/build-new/common/bgen.exe.binlog differ
> [compare-commits] Ignore *.binlog files when creating a diff of the generated files.

- src/Makefile
mono-cil-strip is buggy, and may generate invalid assemblies.
Ref: https://github.com/dotnet/runtime/issues/61402#issuecomment-965753455
Fixes https://github.com/xamarin/xamarin-macios/issues/12749.
> [src] Use 'csc -refout' to generate reference assemblies instead of mono-cil-strip.

- src/glkit.cs
Fixes when building with XAMCORE_4_0:
> GLKit/GLTextureLoader.cs(207,39): error CS0117: 'GLKTextureLoader' does not contain a definition for 'GrayscaleAsAlpha'
> [GLKit] GLKTextureLoaderGrayscaleAsAlpha was available starting in macOS 10.14

- tests/introspection/Mac/MacApiCtorInitTest.cs
The logic seems to want to verify MPSPredicate on maOS 10.14, but not on macOS
10.15+. But checking for macOS 10.14 is always successful on macOS 10.15+,
which means that we can't check for macOS 10.14 before checking macOS 10.15.
So I moved the macOS 10.14 check to after the macOS 10.15 check, but that made
the macOS 10.14 check redundant, because both branches of the condition did
the same thing, so I removed the whole check.
Fixes this introspectionf failure:
[FAIL] DefaultCtorAllowed :   1 potential errors found in 1387 default ctor validated:
Default constructor not allowed for MetalPerformanceShaders.MPSPredicate : Could not initialize an instance of the type 'MetalPerformanceShaders.MPSPredicate': the native 'init' method returned nil.
> [introspection] Fix macOS 10.15 version checks.

- src/CoreGraphics/CGBitmapContext.cs
This way we don't leak the CGBitmapContext.
Fixes https://github.com/xamarin/xamarin-macios/issues/13309.
> [CGBitmapContext] Call the correct base constructor to specify ownership. Fixes #13309.

- tools/devops/automation/templates/mac/build.yml
Example: the macOS 10.15 tests here have been going on for 16+ hours after a deadlock: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5431191&view=logs&j=2fda2bbb-61e0-581a-db35-947a0a9403f6&t=e12f7fa3-cd7a-5af6-76e1-5ed4335dbce9 - these timeouts will fail faster. The macOS tests shouldn't even be close to hitting the 30-min timeout any time soon.
> [devops] Add a 30/60 minute timeout to the steps to install dependencies + run macOS tests.

- src/Darwin/SystemLog.cs
* Use 'nameof (parameter)' instaed of string constants.
> [SystemLog] Enable nullability + a few other fixes.

- tools/mtouch/Application.mtouch.cs
The previous "8.0" sdk version check is incorrect (that's "iOS 8.0", the first
iOS version to add support for user frameworks). However, it started kicking
in for watchOS 8.0, and now suddenly we're trying to build all watchOS
extensions with Mono.framework, which is not what we want.
Instead modify the code to:
* Split by platform, keep the existing behavior for iOS, tvOS and Mac Catalyst
(since "8.0" is the correct version check for all those platforms).
* Use the Mono framework in watchOS if either of the following are true:
* In the main watchOS extension if it has nested extensions.
* In any other extensions (because they'll be nested extensions).
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1430408
> [mtouch] Fix logic to determine whether we're using Mono.framework on watchOS.

- dotnet/Makefile
- dotnet/targets/WorkloadManifest.iOS.template.json
- msbuild/Makefile
- msbuild/Xamarin.HotRestart.PreBuilt/.gitignore
- msbuild/Xamarin.HotRestart.PreBuilt/Makefile
- msbuild/Xamarin.HotRestart.PreBuilt/Xamarin.PreBuilt.iOS/Info.plist
- msbuild/Xamarin.HotRestart.PreBuilt/Xamarin.PreBuilt.iOS/Xamarin.PreBuilt.iOS.csproj
Build the Xamarin.PreBuilt.iOS app bundle instead of using a prebuilt bundle.
This makes sure that we're always using the latest BCL.
Some accurate build massaging was needed, because:
* To build the prebuilt app we need the iOS workload installed (into our build-local
.NET installation).
* The iOS workload contains the Microsoft.iOS.Windows.Sdk pack.
* The Microsoft.iOS.Windows.Sdk pack contains the prebuilt app.
Thus we had a circular reference. Fortunately, the Microsoft.iOS.Windows.Sdk pack
is only required on Windows, which means we can break this circular reference by:
* Mark Microsoft.iOS.Windows.Sdk pack as only to be installed on Windows (unfortunately
it seems we have to list the exact runtime identifiers for the platforms where
to install the pack, so we can't do something like …
> [msbuild/dotnet] Build the Xamarin.PreBuilt.iOS app bundle.

- tests/common/mac/Mac.cs
- tests/introspection/Mac/MacApiCtorInitTest.cs
- tests/introspection/Mac/MacApiFieldTest.cs
* Mac.Is32BitMavericks is always false (we only run on 64-bit macOS), so remove corresponding code.
* Mac.IsElCapitanOrHigher is never used; remove
* Remove a few unused Mac.Version_* fields.
> [introspection] Remove a few version checks which are now constant values.

- tests/introspection/ApiCtorInitTest.cs
- tests/introspection/Mac/MacApiCtorInitTest.cs
- tools/common/Frameworks.cs
Fixes this launch crash when executing on macOS 10.15:
dyld: Library not loaded: /System/iOSSupport/System/Library/Frameworks/HomeKit.framework/Versions/A/HomeKit
Referenced from: /Users/runner/work/1/s/artifacts/mac-test-package/tests/./linker/ios/dont link/dotnet/MacCatalyst/bin/Debug/net6.0-maccatalyst/maccatalyst-x64/dont link.app/Contents/MacOS/dont link
Reason: image not found
> [tools] HomeKit was added to Mac Catalyst in 14.0, so mark it as such.

- tests/fsharp/dotnet/shared.fsproj
- tests/interdependent-binding-projects/dotnet/shared.csproj
- tests/introspection/dotnet/shared.csproj
- tests/linker/ios/dont link/dotnet/shared.csproj
- tests/linker/ios/link all/dotnet/shared.csproj
- tests/linker/ios/link sdk/dotnet/shared.csproj
- tests/monotouch-test/dotnet/shared.csproj
- tests/xcframework-test/dotnet/shared.csproj
The nunit.framework.targets file is already imported in the
tests/common/shared-dotnet.targets file, which all these files imports as
well.
> [tests] Don't import nunit.frameworks.target more than once.

- tests/common/shared-dotnet.mk
This is already the default for macOS apps, but this way it behaves the same
for Mac Catalyst as well.
> [tests] Automatically run/exit tests executed from the command line.

- tests/common/shared-dotnet.csproj
- tests/monotouch-test/Photos/FetchResultTest.cs
- tests/monotouch-test/UIKit/VibrancyEffectTest.cs
This means that the HAS_&lt;FRAMEWORK&gt; defines will now work in .NET test code
(as it already does in legacy test code).
> [tests] Add the compiler response files from src/ to the .NET test builds.

- tools/mtouch/mtouch.csproj
Fixes:
> CSC : warning CS2002: Source file '.../xamarin-macios/tools/mtouch/Errors.Designer.cs' specified multiple times [.../xamarin-macios/tools/mtouch/mtouch.csproj]
> [mtouch] Remove duplicated source file from project file.

- src/CoreAnimation/CADefs.cs
I see no reason for this method to be public.
> [CoreAnimation] Make CAGradientLayer.CreateColor private in .NET.

- tests/common/TestRuntime.cs
- tests/monotouch-test/SceneKit/SCNViewTests.cs
Hopefully fixes this crash:
0x7fff6fbad5fd - /usr/lib/system/libsystem_platform.dylib : _sigtramp
0x354861360 - Unknown
0x7fff71fb9707 - /System/iOSSupport/System/Library/Frameworks/SceneKit.framework/Versions/A/SceneKit : C3DEngineContextSetRenderContext
0x7fff720802c0 - /System/iOSSupport/System/Library/Frameworks/SceneKit.framework/Versions/A/SceneKit : -[SCNRenderer _initWithOptions:isPrivateRenderer:privateRendererOwner:clearsOnDraw:context:renderingAPI:]
0x7fff72126352 - /System/iOSSupport/System/Library/Frameworks/SceneKit.framework/Versions/A/SceneKit : -[SCNView _commonInit:]
0x7fff72126551 - /System/iOSSupport/System/Library/Frameworks/SceneKit.framework/Versions/A/SceneKit : -[SCNView initWithFrame:options:]
> [tests] Don't run SCNViewTests on a VM.

- tests/xtro-sharpie/Makefile
This makes it easier to use templated code.
> [xtro] Rename 'XMAC*'/'XCAT*/ to 'XMACOS*'/'XMACCATALYST*' to follow the OS naming pattern.

- msbuild/Xamarin.Shared/Xamarin.Shared.targets
This fixes an issue where we'd create the stamp file even if 'NoBindingEmbedding' wasn't set.
Also remove SkipBindingResourcePackage property, it doesn't show up anywhere
else in our code base, nor in the history, nor anywhere relevant in Google.
> [msbuild] Don't execute the entire _CreateBindingResourcePackage if 'NoBindingEmbedding!=true'.

- dotnet/Makefile
It appears that the package IDs for the manifests retain the main .NET version band, such as 100 and 200, and the packs use the full version of 101 or 203.
This PR just uses the version band for the manifest packages.
> Use the MANIFEST_VERSION_BAND for the manifests

- src/gamecontroller.cs
These all have equivalent SetX functions that already take the corresponding
GameController type, so this is just making the API consistent.
We could also make these getters + the corresponding Set* method a readwrite
property, but this way is exactly how Apple did it (both in Swift and
Objective-C).
> [GameController] Use existing GameController types instead of OpenTK types for a few property getters for .NET.

- dotnet/targets/Xamarin.Shared.Sdk.targets
Other code elsewhere assumes this is the case.
Ref: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1432957
> [dotnet] Make sure that the relative publish dir has a trailing slash.

- src/Foundation/NSUrlProtocol.cs
- src/Foundation/NSUrlProtocolClient.cs
Just like the XAMCORE_4_0 define says.
> [Foundation] Exclude NSUrlProtocolClient from macOS on .NET.

- tools/devops/automation/templates/build/build.yml
Install our test provisioning profiles + certificates before the build,
because we might need them during the build for the hotrestart prebuilt app.
Ref: https://github.com/xamarin/xamarin-macios/issues/13355.
> [devops] Install our provisioning profiles before the actual build as well.

- runtime/monotouch-main.m
- runtime/xamarin/runtime.h
- src/ObjCRuntime/Runtime.cs
- src/ObjCRuntime/Runtime.mac.cs
- tests/monotouch-test/ObjCRuntime/RuntimeTest.cs
This also adds the Runtime.OriginalWorkingDirectory to all platforms.
Fixes https://github.com/xamarin/xamarin-macios/issues/13392.
> [runtime] Implement storing the original working directory for later retrieval for .NET. Fixes #13392.

- tests/xtro-sharpie/Makefile
- tests/xtro-sharpie/xtro-sanity/Sanitizer.cs
This avoids the need to compute them, and makes it possible to have multiple sets
of platforms.
> [xtro-sanity] Pass the included platforms as command line arguments.

- dotnet/Workloads/Microsoft.NET.Sdk.iOS/WorkloadManifest.targets
- dotnet/targets/WorkloadManifest.iOS.template.json
This fixes an issue where dotnet restore would fail trying to find the pack.
Also make the aliased name look more like the other names.
> [dotnet] Import the aliased pack name, not the actual pack name.

- msbuild/Xamarin.Shared/Xamarin.Shared.targets
The '_AppExtensionRoot' contains the correct parent directory of the 'PlugIns'
directory for all platforms, so use that instead of appending 'PlugIns' to
'_AppBundlePath' - which is incorrect on macOS and Mac Catalyst, because the
'PlugIns' parent directory is '$(_AppBundlePath)/Contents' on those platforms.
Fixes https://github.com/xamarin/xamarin-macios/issues/13415.
> [msbuild] Use the correct logic to determine the PlugIns directory for all platforms. Fixes #13415.

- src/StoreKit/Enums.cs
From what I can see for current Apple API these XAMCORE_4_0 exclusions are
incorrect.
Fixes (when building with XAMCORE_4_0):
> storekit.cs(834,79): error CS0246: The type or namespace name 'SKProductStorePromotionVisibility' could not be found (are you missing a using directive or an assembly reference?)
> storekit.cs(838,16): error CS0246: The type or namespace name 'SKProductStorePromotionVisibility' could not be found (are you missing a using directive or an assembly reference?)
> [StoreKit] Remove XAMCORE_4_0 that seems incorrect.

- src/CoreAnimation/CAKeyFrameAnimation.cs
- src/Network/NWParameters.cs
- src/Network/NWProtocolStack.cs
Use the non-deprecated version, which will work in both legacy Xamarin and .NET.
> [src] Don't use deprecated API.

- tests/monotouch-test/UIKit/FontTest.cs
Fixes:
MonoTouchFixtures.UIKit.FontTest
CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
CoreText note: Set a breakpoint on CTFontLogSystemFontNameRequest to debug.
[FAIL] NullFonts :   WithSize
Expected: not null
But was:  null
at MonoTouchFixtures.UIKit.FontTest.NullFonts() in /Users/builder/azdo/_work/1/s/xamarin-macios/tests/monotouch-test/UIKit/FontTest.cs:line 165
> [tests] Adjust FontTest to cope with broken GameKit/UIKit/fontWithSize on certain macOS versions.

- src/security.cs
The kSecUseNoAuthenticationUI field is available on macOS, just deprecated,
and I don't see how having the field bound would be a breaking change like the
comment says (git history seems to indicate it's referring to the
Classic/Unified switchover - i.e. quite outdated), so add the field to macOS.
> [Security] Add kSecUseNoAuthenticationUI for macOS.

- src/LocalAuthentication/LAEnums.cs
- src/localauthentication.cs
- tests/xtro-sharpie/MacCatalyst-LocalAuthentication.todo
- tests/xtro-sharpie/MacCatalyst-LocalAuthenticationEmbeddedUI.ignore
- tests/xtro-sharpie/iOS-LocalAuthentication.todo
* LAContext.MaxBiometryFailures is available in macOS, just deprecated, so mark
it as such.
* Remove deprecated code from .NET.
* Update xtro definitions.
> [LocalAuthentication] Adjust code for .NET and fix availability of LAContext.MaxBiometryFailures

- tests/xtro-sharpie/Makefile
* Use proper dependency tracking, so that we'll only rebuild what needs to be rebuilt
when rebuilding. This required using a few stamp files. It also improves parallel
builds.
* Remove *.raw files before running xtro-sharpie, and only for the current platform.
This makes sure rebuilds of just some of the platforms work correctly (because
the *.raw files for other platforms are still around when needed).
* Build the u2todo project file instead of manually calling csc.
> [xtro] Improve makefile.

- dotnet/targets/Xamarin.Shared.Sdk.Publish.targets
- msbuild/Xamarin.Shared/Xamarin.Shared.targets
> [dotnet] Put packages (.ipa/.pkg) in the publish directory by default.

- src/CoreGraphics/CGImage.cs
- src/ImageIO/CGImageSource.cs
- tests/monotouch-test/ImageIO/CGImageSourceTest.cs
Otherwise we'll create a CGImage with a zero Handle, which is usually not the
right thing to do. Still, keep the old behavior for legacy Xamarin for the
sake of backwards compat.
> [CGImageSource] Change CreateThumbnail to return null if the thumbnail creation fails.

- src/Network/NWWebSocketOptions.cs
This ends up as actual code in all the constructors, so this saves a tiny bit
of code (most importantly it doesn't trigger an upcoming test that verifies
what constructors do).
> [NWWebSocketOptions] No need to initialize to default value.

- src/CoreFoundation/CFMessagePort.cs
* There's no need to initialize the contextHandle field to IntPtr.Zero, since
that's the default value anyway. This avoid adding useless code to all the
constructors.
* Fix removing the contextHandle entry from the messagePortContexts
dictionary, by not trying to remove it from the wrong dictionary.
> [CFMessagePort] Simplify construction and fix c&p error in Dispose.

- src/AppKit/Enums.cs
- tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.ignore
xtro also agrees that it shouldn't exist.
> [AppKit] Remove NSKey from .NET, it's not used anywhere in our API, nor can I find it in headers.

- src/ObjCRuntime/Runtime.cs
- src/ObjCRuntime/Runtime.mac.cs
We'll always be a self-contained app, with our libxamarin code linked
statically into the executable, so we can use plain P/Invokes.
Fixes https://github.com/xamarin/xamarin-macios/issues/13398.
> [ObjCRuntime] There's no need to look up our own functions dynamically for Xamarin.Mac in .NET. Fixes #13398.

- src/AppKit/Enums.cs
- src/xkit.cs
- tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.ignore
The former has been removed from the headers, so it's thoroughly deprecated,
and the latter is no longer needed anymore since it was only used by the
former.
> [AppKit] Remove the NSLayoutManager.LayoutOptions property and the NSGlyphStorageOptions enum in .NET.

- src/AVFoundation/Enums.cs
- tests/xtro-sharpie/api-annotations-dotnet/tvOS-AVFoundation.ignore
- tests/xtro-sharpie/tvOS-AVFoundation.ignore
None of these are deprecated, so no reason for them to not exist in .NET.
Also update the availability attributes according to current headers.
> [AVFoundation] Fix availability for a few enums

- src/appkit.cs
- src/generator.cs
- tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.ignore
The 'textView:draggedCell:inRect:event:' selector has been deprecated since
macOS 10.6, so just replace this with the recommended alternative.
> [AppKit] Change NSTextViewDelegate.DraggedCell to use the recommended signature for .NET

- src/scenekit.cs
> error BI1106: bgen: The parameter shadable in the method SceneKit.SCNBufferBindingHandler.Invoke exposes a model (SceneKit.SCNShadable). Please expose the corresponding protocol type instead (SceneKit.ISCNShadable)
> [SceneKit] Fix SCNBufferBindingHandler signature for .NET.

- tests/introspection/ApiFrameworkTest.cs
* Assert at the end of the test if there were any errors.
* Don't run this test for .NET, since we don't use a simlauncher in .NET.
> [introspection] Fix the ApiFrameworkTest.Simlauncher test to fail in case of errors.

- msbuild/Xamarin.Shared/Xamarin.Shared.targets
It's not needed, and may in some cases do the wrong thing: for instance, this
logic will automatically reference any *.dll files in the project directory,
which breaks the build if those *.dll files aren't actually assemblies.
> [msbuild] Don't use custom logic to handle facades in .NET.

- dotnet/targets/Xamarin.Shared.Sdk.Publish.targets
- dotnet/targets/Xamarin.Shared.Sdk.props
- tests/common/DotNet.cs
- tests/dotnet/UnitTests/PostBuildTest.cs
* We can't publish a simulator build, so show an error in that case.
* We can't change the default runtime identifier when publishing (to a
publishable runtime identifier), because by the time we know we're
publishing, it's too late to change the runtime identifier. This means that
it'll be required for app developers to specify a runtime identifier when
publishing to a mobile platform, since the current default runtime
identifier is for a simulator build.
Partial fix for https://github.com/xamarin/xamarin-macios/issues/12997.
> [dotnet] Show an error if an app developer tries to publish a simulator architecture.

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ResolveNativeReferencesBase.cs
- msbuild/Xamarin.Shared/Xamarin.Shared.targets
- tests/bindings-test/StructsAndEnums.cs
- tests/bindings-test/dotnet/shared.csproj
- tests/bindings-test/libtest.linkwith.cs
- tests/bindings-test2/dotnet/shared.csproj
- tests/dotnet/BindingOldStyle/ApiDefinition.cs
- tests/dotnet/BindingOldStyle/MacCatalyst/BindingOldStyle.csproj
- tests/dotnet/BindingOldStyle/MacCatalyst/Makefile
- tests/dotnet/BindingOldStyle/MyClass.cs
- tests/dotnet/BindingOldStyle/StructsAndEnums.cs
- tests/dotnet/BindingOldStyle/iOS/BindingOldStyle.csproj
- tests/dotnet/BindingOldStyle/iOS/Makefile
- tests/dotnet/BindingOldStyle/macOS/BindingOldStyle.csproj
- tests/dotnet/BindingOldStyle/macOS/Makefile
- tests/dotnet/BindingOldStyle/shared.csproj
- tests/dotnet/BindingOldStyle/shared.mk
- tests/dotnet/BindingOldStyle/tvOS/BindingOldStyle.csproj
- tests/dotnet/BindingOldStyle/tvOS/Makefile
- tests/dotnet/UnitTests/PackTest.cs
- tests/dotnet/UnitTests/ProjectTest.cs
- tests/test-libraries/Makefile
* Add support for xcframeworks with static libraries in them.
* Create a libtest.xcframework and a libtest2.xcframework for our tests.
* Make the .NET version of bindings-test and bindings-test2 use an xcframework
instead of a fat static library.
This is required for supporting ARM64 in the simulator, because then we won't
be able to create a fat static library for all the architectures we support
anymore, because there will be two ARM64 slices, one for device and one for
the simulator. By switching to an xcframework of static libraries, we don't
run into this problem.
> [msbuild/tests] Add support for xcframeworks with static libraries in them.

- src/Security/Authorization.cs
It looks like this was a latent bug that was uncovered due to unrelated code
changes. The problem is that the 'AuthorizationExecuteWithPrivileges' function
takes a null-terminated array as the arguments, and we were not
null-terminating the array we were passing (on purpose at least - it probably
have happened in the past by accident).
Fixes https://github.com/xamarin/xamarin-macios/issues/13465.
> [Security] Fix call to AuthorizationExecuteWithPrivileges to pass a null-terminated array for the arguments. Fixes #13465.

- src/Security/Authorization.cs
This looks like a c&p mistake from the initial implementation from 2012:
https://github.com/xamarin/maccore/commit/55d6a7dcb695859bfc4144ee030c45928b5bf711
> [Security] Fix setting the path to the icon for the authorization dialog when creating a new authorization reference.

- src/CoreGraphics/CGPDFScanner.cs
This got dropped by mistake at some point.
> [CoreGraphics] Add back CGPDFScanner's custom retain/release functions.

- tools/apidiff/Makefile
We don't create a Mac Catalyst version of Xamarin.iOS.dll anymore, so there's
nothing to run an api diff on.
> [apidiff] Remove logic referencing the Mac Catalyst version of Xamarin.iOS.dll.

- tests/common/PlatformInfo.cs
Change the logic to detect if an API is available to:
* First check if there are any applicable UnavailableOSPlatform attributes,
and only if an applicable attribute is found, then state that the API is
unavailable (we can't ascertain that an API is available from an
UnavailableOSPlatform attribute, only that it's unavailable).
* Once we know there are no applicable UnavailableOSPlatform attributes, we go
on to check for applicable SupportedOSPlatform attributes, and if one is
found, then we can say whether the API is available or not.
* If neither attributes were found, and we're building for Mac Catalyst, then
repeat the two above checks for iOS instead.
* If still nothing, then assume the API is available (while incorrect, it's
how our attributes are currently implemented).
This fixes …
> [tests] Fix checking availability for .NET.

- src/AppKit/Enums.cs
- tests/xtro-sharpie/macOS-AppKit.ignore
It turns out the enum is used a bit more than I thought.
Ref: https://discord.com/channels/732297728826277939/732297808148824115/913810268939759626
> [AppKit] Add NSKey back to the .NET profile.

- msbuild/Xamarin.Shared/Xamarin.Shared.targets
The GetNuGetShortFolderName task only exists in .NET builds, which means we
have to find another way to compute the path to resources in nugets for legacy
builds. Do it the simple way by hardcoding the possible values.
Fixes https://github.com/xamarin/xamarin-macios/issues/13469.
> [msbuild] Hardcode values for the nuget short folder name for legacy builds. Fixes #13469.

- Make.config
- tests/dotnet/UnitTests/global.json
Check for the x64 version of .NET to see if it's installed if the default
dotnet location doesn't exist (the x64 version will exist on an ARM64 mac when
installing the x64 version of .NET).
Also allow the .NET unit tests to be executed using any recentish version of
.NET.
> [dotnet] Check for the x64 version of .NET.

- dotnet/Makefile
- dotnet/targets/Microsoft.Sdk.Versions.template.props
- dotnet/targets/Xamarin.Shared.Sdk.targets
This way we don't have to update the runtime identifier validation when we add
support for new runtime identifiers.
We'll also have an item group that lists the valid runtime identifiers, which
is making it possible (although the item group is currently private) to query
the valid runtime identifiers (which is something the IDEs have expressed
interest in).
> [dotnet] Generate an itemgroup with the valid runtime identifiers and use it to detect invalid runtime identifiers.

- src/AVFoundation/AVAudioChannelLayout.cs
An out parameter works just as well.
> [AVAudioChannelLayout] Refactor a bit to avoid a static thread-local variable.

- tests/xharness/Jenkins/TestTasks/BuildProject.cs
This is in reaction to https://github.com/dotnet/xharness/pull/786 which adds a new sub-result to preserve behavior when the bump happens.
This is the only occurrence where we're comparing `TimedOut` via equality.
> Compare the `TestExecutingResult.TimedOut` flag only

- tools/devops/automation/templates/release/vs-insertion-prep.yml
We need to allow the release pipeline to access the artefacts.
> [CI] Use Build artifacts so that they are copied to the release pipeline.

- tests/common/TestRuntime.cs
- tests/introspection/Mac/introspection-mac.csproj
- tests/introspection/iOS/introspection-ios.csproj
- tests/linker/ios/dont link/dont link.csproj
- tests/linker/ios/link all/link all.csproj
- tests/linker/ios/link sdk/link sdk.csproj
- tests/linker/mac/dont link/dont link-mac.csproj
- tests/linker/mac/link all/link all-mac.csproj
- tests/linker/mac/link sdk/link sdk-mac.csproj
- tests/monotouch-test/Foundation/BundleTest.cs
- tests/monotouch-test/MobileCoreServices/UTTypeTest.cs
- tests/monotouch-test/UIKit/UIDocumentTest.cs
- tests/monotouch-test/UniformTypeIdentifiers/TypeTest.cs
Some tests fail when running on an M1, but in a x64_86 mode, so just ignore
those unless we're running on ARM64 (this will currently exclude them on
x86_64 hardware too, but that'll eventually not be a problem anymore when
there's no more x86_64 hardware, and just checking for ARM64 is easier than
checking for x86_64 mode on an ARM64 CPU).
> [monotouch-test] Ignore a few tests in non-ARM64 simulators.

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/GetFileSystemEntriesTaskBase.cs
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
- tests/common/DotNet.cs
- tests/dotnet/UnitTests/ProjectTest.cs
There can't be any files in the root directory of the app bundle for macOS and
Mac Catalyst, otherwise code signing will fail. The problem is that Mono will
create a crash report in the current directory if the process crashes, and the
current directory is the root directory of the app bundle, which means that if
running an app crashes, the next build will likely fail because of the crash
report.
We had logic to detect this and remove any crash reports, but our crash report
detection pattern wasn't good enough and let some files through. This PR
updates that pattern, and also improves the code to report warnings for any
other files in the app bundle's root directory.
> [msbuild] Improve logic to clean up the app bundle for macOS and Mac Catalyst apps before signing.

- tools/devops/automation/templates/build/build.yml
- tools/devops/automation/templates/mac/build.yml
- tools/devops/automation/templates/mac/stage.yml
Sometimes the make fails which results in errors further in the mac tests pipeline. We now check if we managed to do it and if not, we do not try to run the tests and let the user know.
> [CI] Check that the mac tests are indeed present.

- src/appkit.cs
I inversed the .NET conditional logic, thus keeping the old behavior for .NET
and making legacy have the new behavior
Fixes this API break:
.
> [AppKit] Fix unintentional breaking change in NSTextViewDelegate.DraggedCell.

- Make.config
- builds/Makefile
- builds/package-download/download-packages.proj
- dotnet/Makefile
- eng/Version.Details.xml
- eng/Versions.props
- tests/linker/ios/link sdk/LinkSdkRegressionTest.cs
We are in a situation where:
1. .NET MAUI is still in preview
2. We need dotnet/runtime fixes for MAUI, but we don't necessarily want all fixes to go into the .NET 6 service release.
The solution is to simplify use different builds/packs from dotnet/runtime.
Ref: https://github.com/xamarin/xamarin-android/pull/6542
> Use the '.NET 6 MAUI' channel for dotnet/runtime bits.

- src/Makefile
Make can get confused if a rule doesn't update the timestamp of a target file,
so make sure the target file's timestamp is updated in a few cases.
This hopefully fixes an infinite loop inside parallel make I've been running into.
> [src] Tweak makefile to try to avoid confusing make.

- tests/mtouch/RegistrarTest.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/13517.
> [tests] Update the MT4162_dotnet to use new-style .NET availability attributes. Fixes #13517.

- dotnet/targets/Xamarin.Shared.Sdk.targets
This enables removing all kinds of infrastructure attributes for example SupportedOSPlatformAttribute (like old XI did).
> Enable AggressiveAttributeTrimming

- tools/devops/automation/templates/build/publish-html.yml
We have added more files and the API seems to take long sometimes,
increate the timeots to avoid failures like in https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5532523&view=logs&j=704af8c3-a112-593d-cee6-636e1ea22709&t=62b5d5ee-dc4f-530c-7279-a3bef6bd6bc7
> [CI] Increate timeouts so that we do not have failures.

- src/generator.cs
This makes the generated code much smaller, and also avoids calling
Runtime.Arch for Mac Catalyst.
> [generator] Generate the same invoke code for Mac Catalyst like we already do for macOS.

- tools/devops/automation/templates/release/vs-insertion-prep.yml
This reverts commit 3977d7531d5876e6aadcd9eb013cad2c978c885f because it broke the release step because we cannot change the download type.
> Revert "[CI] Use Build artifacts so that they are copied to the release pipeline. (#13501)"

- tools/devops/automation/templates/mac/build.yml
Else the tests fail rather than post a status in github:
```
The term 'Set-GitHubStatus' is not recognized as a name of a
| cmdlet, function, script file, or executable program. Check
| the spelling of the name, or if a path was included, verify
| that the path is correct and try again.
```
> [CI] Add missing import directive.

- dotnet/targets/Xamarin.Shared.Sdk.targets
- tools/dotnet-linker/LinkerConfiguration.cs
- tools/dotnet-linker/Steps/ComputeNativeBuildFlagsStep.cs
Pass -dead_strip to the native linker like we do for legacy Xamarin:
* If there are no custom linker arguments.
* If all third-party bindings in the app has SmartLink = true (this doesn't
show up in the PR, but the logic exists for legacy Xamarin and is already
executed for .NET, the resulting Application.DeadStrip value just wasn't
taken into account).
This shrinks the app size a bot for a Hello World app:
* Before:     10.659.731 (https://gist.github.com/rolfbjarne/b5892a5c7fb8663d38e2b69f67bce90c)
* After:       9.940.240 (https://gist.github.com/rolfbjarne/8404394180fb9971bd2f1475b747c70a)
* Difference:   -719.491 (-6.7 %)
> [dotnet] Pass -dead_strip to the native linker when we can.

- src/System.Net.Http/CFNetworkHandler.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/8072.
> [CFNetworkHandler] Only use public API to set cookies in CookieContainers. Fixes #8072.

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/MergeAppBundlesTaskBase.cs
- tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/MergeAppBundleTaskTest.cs
Symlinks to directories are treated the same as other symlinks (as files), not
as directories. This way we don't end up re-creating a directory hierarchy
when we only have to create a symlink.
> [msbuild] Fix merging of apps with symlinks to directories.

- runtime/runtime.m
This works around dotnet/runtime's https://github.com/dotnet/runtime/issues/62735.
> [runtime] Make sure dlls come before exes in TRUSTED_PLATFORM_ASSEMBLIES.

- tools/dotnet-linker/Makefile
Make gets confused sometimes if running a rule doesn't update the timestamp of
the target of those rules (and make may in certain cases end up with an
infinite loop).
Avoid this by making sure to always update the timestamp of the
dotnet-linker.dll we build, even if MSBuild decides no re-compilation was
necessary.
> [dotnet-linker] Touch the build output to avoid make confusion.

- tools/dotnet-linker/Steps/StoreAttributesStep.cs
We must store the availability attributes when linking, so that the registrar
can access them when the linker is done linking the app.
* Xamarin.Registrar.MT4162_dotnet(iOS,"iOS",LinkAll)
Ref: https://github.com/xamarin/xamarin-macios/issues/13517
> [dotnet-linker] We must store the availability attributes when linking.

- src/AppKit/NSView.cs
Ref https://github.com/xamarin/xamarin-macios/issues/10470.
> [.NET/AppKit] Use [UnmanagedCallersOnly] instead of [MonoPInvokeCallback] for the managed callbacks called from native code.

- tests/linker/ios/link sdk/AotBugs.cs
There's no reason to call Assert.Inconclusive at the end up a test method,
because we won't get that far in the test method if it fails.
> [tests] Remove a few useless Assert.Inconclusive calls at the end of test methods.

- dotnet/targets/Xamarin.Shared.Sdk.targets
- msbuild/Xamarin.Shared/Xamarin.Shared.props
- msbuild/Xamarin.Shared/Xamarin.Shared.targets
- msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
- tests/msbuild/Xamarin.MacDev.Tests/TargetTests/TargetTests.cs
Our current behavior is to detect any None, BundleResource or Content item
that's named 'Info.plist', and assume that's the app manifest.
That doesn't quite work when we end up with multiple 'Info.plist' entries in any
of those item groups (one example being a framework as a BundleResource - all frameworks
have an Info.plist, and there's no good way to distinguish what the developer's intention
was).
So:
1. Implement a 'AppManifestDetectionEnabled' property to disable automatic app manifest
detection.
2. Add a public 'AppBundleManifest' property that specifies the app manifest
(this is just a renamed version of our previously private '_AppManifest' property).
This makes it possible for app developers to:
* Disable automatic app manifest detection.
* Still have an app manifest by …
> [msbuild] Rework how app manifest detection works

- tools/devops/automation/build-pipeline.yml
This change allows to have a parameter (false by default) that allows to
get a build to be able to do an insertion even when it is comming from a
not predefined branch.
Uses cases:
1. Trigger a buiild with no tests from a special branch to insert.
2. Work with the CI to test the deployment.
> [CI] Allow to force a build to be usable for insertions.

- src/appkit.cs
- tools/apidiff/Makefile
- tools/apidiff/merger.cs
- tools/compare-commits.sh
- tools/devops/automation/scripts/GitHub.psm1
- tools/devops/automation/scripts/bash/compare.sh
- tools/devops/automation/templates/build/publish-html.yml
- tools/devops/automation/templates/build/stage.yml
This PR gives us easy to inspect API Diffs from the current PR in Github!
Before, we would receive a link inside the "API & Generator Diff" which would download an html file 
with links that were not able to be opened. This was because the links lived inside Azure Devops
but the links were using relative paths.
Now, we will see a new section named "API Current PR diff" with the status message below it.
Then we will be able to download/open each html in devops or the appropriate gist. 
Here is an example of what will show when removing two selectors in foundation: https://github.com/xamarin/xamarin-macios/pull/13401#issuecomment-989538316
This PR also fixes a few issues with the Current API diff generation and fixes an issue with the html and md files inside
the apicomparison zip artifact …
> [ApiDiff] Add Current PR Diffs in a similar style as API Diffs

- src/VideoToolbox/VTUtilities.cs
* Use 'GetCheckedHandle' to check for disposed objects instead of doing it
manually.
> [VTUtilities] Enable nullability + a few other code updates.

- src/VideoToolbox/VTCompressionSession.cs
* Remove unnecessary destructor and Dispose method.
* Simplify some block code.
> [VTCompressionSession] Enable nullability + a few other code updates

- src/Foundation/NSUrlSessionHandler.cs
This was probably a c&p error.
Fixes https://github.com/xamarin/xamarin-macios/issues/13576.
> [Foundation] Fix return type for NSUrlSessionHandler.AutomaticDecompression. Fixes #13576.

- src/AppKit/Enums.cs
- tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.ignore
If NSFunctionKey isn't in Mac Catalyst in legacy Xamarin, it shouldn't be in
.NET either, so adjust the conditional logic accordingly.
Also make the NSFunctionKey enum a non-native enum in .NET, like it's in the
headers.
> [AppKit] Make sure NSFunctionKey doesn't come into Mac Catalyst in .NET.

- dotnet/targets/Xamarin.Shared.Sdk.targets
- msbuild/Xamarin.Localization.MSBuild/MSBStrings.Designer.cs
- msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/FilterStaticFrameworksTaskBase.cs
- msbuild/Xamarin.MacDev.Tasks/Tasks/FilterStaticFrameworks.cs
A later PR will include a test case for this.
> [msbuild/dotnet] Add a FilterStaticFramework task to filter out frameworks of static libraries from frameworks we copy to the app bundle.

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ComputeBundleResourceOutputPathsTaskBase.cs
- tests/dotnet/UnitTests/ProjectTest.cs
This PR addresses this issue: https://github.com/xamarin/maccore/issues/2530
If you build twice using DotNet.AssertBuild without cleaning in between, the project fails.
From tracing the binlogs, it looks like there is a file "scene.dae" that after the first build, failed to carry over it's metadata: primarily it's 'LogicalName'.
This caused an issue since the output file is composed of a directory + this logical name.
Thus with an empty LogicalName, the output file is a directory and causes the build to fail.
Inside the ComputeBundleResourceOutputPaths, it will now compute a default LogicalName of the filename if LogicalPath is not provided.
> [Dotnet] Fix building twice in a row issue

- tests/common/shared-dotnet.mk
- tests/dotnet/Makefile
This makes sure that MSBuild picks up rebuilt task assemblies.
> [tests] Shutdown build servers when rebuilding.

- src/AudioToolbox/AudioSession.cs
Ref: https://github.com/xamarin/xamarin-macios/issues/10470.
> [.NET/AudioSession] Use [UnmanagedCallersOnly] instead of [MonoPInvokeCallback] for the managed callbacks called from native code.

- tests/xharness/AppBundleLocator.cs
- tests/xharness/TestProject.cs
* Capture evaluation output, and write it all to the terminal when something
goes wrong. This way we can see the entire output next to the failure (often
there's a lot of stuff written to the terminal from different threads, and
this way we get all that matters written together).
* Only evaluate one project at a time, to avoid overloading the machine.
* Only execute `git ls-files` once at a time, to avoid overloading the machine.
* Bump evaluation timeout to 5 minutes.
* Also increase the time for git to list files in a directory to 60 seconds.
Hopefully this will fix errors like this:
* `Unable to evaluate the property OutputPath, build failed with exit code 0. Timed out: True`
* `System.Exception: Failed to list the files in the directory …
> [xharness] Improve how we execute external processes in certain cases

- src/VideoToolbox/VTCompressionSession.cs
- tests/monotouch-test/VideoToolbox/VTCompressionSessionTests.cs
Once upon a time there was a single VTCompressionSession.Create method, which
was [driving users insane][1] - they had to manually call CFRetain to avoid
crashes! What an abomination!!
Insane users are clearly not happy users, and we wanted happy users, so time
and effort went into creating a solution: a new Create overload was devised
and [implemented][1], taking extreme care to not break our brave and insane
existing users who had to manually call CFRetain. Because the fix would break
existing users - the now extraneous CFRetain would mean that their apps would
leak memory. *A lot* of it! That's bad, so we decided to make sure that didn't
happen.
Of course, dear old Murhpy wanted a say, so the new Create overload didn't do
as intended. In fact, it had the same insane behavior the old …
> [VTCompressionSession] Fix broken Create overloads for .NET.

- src/ObjCRuntime/Runtime.iOS.cs
This method exposes internal implementation details, and makes it difficult to
innovate in the runtime. Additionally it's purpose was always for diagnosis,
but I've never seen it used (not even for its intented purpose), so we can
just remove it for .NET.
> [src] Remove Runtime.GetSurfacedObjects in .NET.

- src/ObjCRuntime/Blocks.cs
This makes it clearer what kind of types the method can handle.
A delegate constraint requires a newer C# version, which is why we can't do it
for legacy Xamarin.
> [Blocks] Constrain the generic type for GetTarget and GetDelegateForBlock to delegates in .NET

- src/Makefile
We're only building for Mac Catalyst on .NET, and this generated file is
entirely surrounded in a "#if !NET" condition, so not generating/compiling it
won't make a difference.
> [src] No need to add the legacy version of the generated constants to the Mac Catalyst build.

- src/AVFoundation/AVCompat.cs
- src/AVFoundation/AVMetadataItemFilter.cs
- src/AVFoundation/AVPlayerLooper.cs
- src/AVFoundation/AVPlayerViewController.cs
- src/AVFoundation/AVTypes.cs
- src/AVFoundation/Enums.cs
- src/avfoundation.cs
- tests/monotouch-test/AVFoundation/AVPlayerLooperTest.cs
- tests/monotouch-test/AVFoundation/CaptureMetadataOutputTest.cs
- tests/monotouch-test/AVFoundation/MetadataObjectTest.cs
- tests/monotouch-test/AVFoundation/UtilitiesTest.cs
- tests/monotouch-test/CoreMedia/CMFormatDescriptionTest.cs
- tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-AVFoundation.ignore
- tests/xtro-sharpie/api-annotations-dotnet/common-AVFoundation.ignore
- tests/xtro-sharpie/api-annotations-dotnet/iOS-AVFoundation.ignore
- tests/xtro-sharpie/api-annotations-dotnet/macOS-AVFoundation.ignore
- tests/xtro-sharpie/api-annotations-dotnet/macOS-AVFoundation.todo
- tests/xtro-sharpie/macOS-AVFoundation.todo
- tests/xtro-sharpie/watchOS-AVFoundation.todo
This PR is probably best reviewed commit-by-commit, since it contains many small and discrete commits.
> [AVFoundation] Address all the XAMCORE_4_0 notes in AVFoundation for .NET.

- dotnet/targets/Xamarin.Shared.Sdk.targets
- tests/common/Configuration.cs
- tests/dotnet/UnitTests/TemplateProjectTest.cs
Don't add FileNativeReferences to the main libraries to link with, because we
pass that list of main libraries to the LinkNativeCodeTask, and we're already
passing the FileNativeReferences for a different task parameter.
This means that we end up adding the file native reference twice to the linker
arguments, and that's wasteful. It can also cause problems if those linker
arguments aren't always computed in the same way (once as a relative path,
once as an absolute path for instance).
Fixes https://github.com/xamarin/xamarin-macios/issues/13503.
> [dotnet] Don't add FileNativeReferences to the main libraries to link with. Fixes #13503.

- src/foundation.cs
These methods must be overridden, otherwise the app might crash, so making
them abstract forces developers to do the right thing.
Ref: https://bugzilla.xamarin.com/show_bug.cgi?id=50891
> [Foundation] Make NSStream.[Get|Set]Property abstract in .NET.

- tests/monotouch-test/Security/SecureTransportTest.cs
The "502 Bad Gateway" error occurs sometimes on the bots.
Maybe we should rename it "502 Bad Bot"?
> [tests] Allow 502 Bad Gateway as well in the SecureTransportTest.Tls12 test.

- src/uikit.cs
The source code claims that having the different protocol hierarchy reduces
duplicate code, but I can't see what kind of code duplication this would
remove. The incorrect hierarchy causes all the UIScrollViewDelegate members to
not be inlined in UICollectionViewController, UICollectionViewDelegate and
UICollectionViewSource, effectively breaking API / source code, because this
might happen in UICollectionViewController subclasses now:
MyUICollectionViewController.cs(105,24): error CS0115: 'MyUICollectionViewController.DraggingStarted(UIScrollView)': no suitable method found to override
MyUICollectionViewController.cs(111,24): error CS0115: 'MyUICollectionViewController.DraggingEnded(UIScrollView, bool)': no suitable method found to override
This also debunks the claim from the comment in …
> [UIKit] Use the correct protocol hierarchy for UICollectionViewDelegate for .NET.

- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.cs.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.de.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.es.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.fr.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.it.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ja.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ko.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pl.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pt-BR.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ru.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.tr.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hans.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hant.resx
> Localized file check-in by OneLocBuild Task: Build definition ID 14411: Build ID 5561912

- src/generator.cs
- tests/generator/BGenTests.cs
- tests/generator/tests/protocol-bind-property.cs
Take into account any Bind attributes on optional property getters and setters
on protocols when generating the Get* and Set* extension methods, so that we
use the right selector.
Fixes https://github.com/xamarin/xamarin-macios/issues/12727.
> [generator] Fix the selector in extension methods for protocol properties with Bind attributes. Fixes #12727.

- src/uikit.cs
- tests/monotouch-test/UIKit/TextFieldTest.cs
- tests/monotouch-test/UIKit/TextViewTest.cs
- tests/xtro-sharpie/api-annotations-dotnet/common-UIKit.ignore
Once upon a long time ago we decided to mark the properties in the
UITextInputTraits protocol as required in our API definition, because that way
we'd inline these properties in any class that implemented the
UITextInputTraits protocol, which made calling these properties much easier.
At a later point, we implemented better support for protocols, and now we
automatically generate extension methods for such properties (a corresponding
Get/Set method for the get/set property accessors), so we don't need these
inlined properties anymore.
However, removing them would be a breaking change, so we were stuck with these
redundant inlined properties, until .NET came along.
Ref: https://github.com/xamarin/maccore/commit/0e8057086362f7f9f22b68b9d174e8568b11bf7b
Fixes …
> [UIKit] Make UITextInputTraits members optional in .NET. Fixes #5831.

- src/appkit.cs
NSWindow.WindowController's type is supposed to be 'NSWindowController', not
'NSObject'. Fix this in .NET, since it's a breaking change.
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=40095.
> [AppKit] Fix NSWindow.WindowController's return type in .NET.

- src/webkit.cs
Fixes in https://bugzilla.xamarin.com/show_bug.cgi?id=46316.
> [WebKit] Fix the return types for WebUIDelegate.UIGetDragDestinationActionMask and WebUIDelegate.UIDragSourceActionMask in .NET.

- src/Makefile
Fix a c&p error with the dependencies for core-maccatalyst.dll.
This fixes a random build error:
> error CS2001: Source file 'xamarin-macios/src/build/dotnet/Constants.maccatalyst.generated.cs' could not be found.
> [src] Fix dependencies for core-maccatalyst.dll.

- msbuild/Xamarin.HotRestart.PreBuilt/Makefile
This fixes an issue where rebuilding in an already build working copy after a
.NET bump would fail.
> [msbuild] Make sure to update global.json/NuGet.config for the Xamarin.HotRestart.PreBuilt build whenever needed.

- src/Metal/MTLRenderCommandEncoder.cs
As a response to this issue: https://github.com/xamarin/xamarin-macios/issues/12648
`SetTileSamplerStates` and `SetTileBuffers` are methods only for iOS, but this whole file is contained inside an `#if MONOMAC`. Therefore, we should move this Monomac to cover just the Mac portion.
> [Metal] Exposing Selectors in iOS. Fixes  #12648

- msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
With the previous approach we were only copying the main app pdb to the Mac instead of all the involved pdb files (main app and referenced projects). This was causing the class libraries to not load the symbols and not hit any breakpoints while debugging
> Ensure we remotely copy all project pdbs and not only the main app one

- msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
With the previous approach we were only copying the main app pdb to the Mac instead of all the involved pdb files (main app and referenced projects). This was causing the class libraries to not load the symbols and not hit any breakpoints while debugging
Backport of #13650
> [release/6.0.2xx-preview12] Ensure we remotely copy all project pdbs and not only the main app one

- src/AVKit/Enums.cs
- src/Foundation/Enum.cs
- src/avkit.cs
- src/foundation.cs
- The tool I wrote to convert attributes [mellite](https://github.com/chamons/mellite) does single pass through each file
- This means files that define Foo and !Foo, each with availability attributes inside can not be proccessed
- These 2 locations were easy to fix by moving defines inside binding definations, so I did that
- About 10 other locations were not so easy, so those will be worked around by hand in the conversion process.
Part of https://github.com/xamarin/xamarin-macios/issues/10170
> Prepare for NET6 attribute conversion with hand fixes

- src/VideoToolbox/VTCompressionSession.cs
- tests/monotouch-test/VideoToolbox/VTCompressionSessionTests.cs
This makes the API nicer to use.
> [VideoToolbox] Add a VTCompressionSession.EncodeFrame overload that takes a CVImageBuffer instead of a handle to one.

- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.cs.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.de.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.es.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.fr.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.it.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ja.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ko.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pl.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pt-BR.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ru.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.tr.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hans.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hant.resx
> Localized file check-in by OneLocBuild Task: Build definition ID 14411: Build ID 5607500

- tools/devops/automation/scripts/GitHub.psm1
Fix the comment so that it does not look like
https://github.com/xamarin/xamarin-macios/commit/94863148dc43454779f639efca2c06780691bce7#commitcomment-63453915
> [CI] Fix comment aligment and add a warning sign.

- src/AudioUnit/AudioUnit.cs
- tests/monotouch-test/AudioToolbox/AudioUnitTest.cs
AudioUnit needs a GCHandle in the input callback, which means we have to create it
when SetInputCallback is called (like we already do for SetRenderCallback).
Fixes https://github.com/xamarin/xamarin-macios/issues/13637.
Backport of #13673
> [d17-1] [AudioUnit] Create a GCHandle when AudioUnit.SetInputCallback is called. Fixes #13637.

- src/ObjCRuntime/DisposableObject.cs
- tests/monotouch-test/AudioToolbox/AudioConverterTest.cs
- tests/monotouch-test/ObjCRuntime/DisposableObjectTest.cs
Ops...
Also add tests to avoid more oopses.
Fixes https://github.com/xamarin/xamarin-macios/issues/13646.
Backport of #13666
> [release/6.0.2xx-preview12] [ObjCRuntime] Fix the DisposableObject.Owns property to return the correct value. Fixes #13646.

- src/AudioUnit/AudioUnit.cs
- tests/monotouch-test/AudioToolbox/AudioUnitTest.cs
AudioUnit needs a GCHandle in the input callback, which means we have to create it
when SetInputCallback is called (like we already do for SetRenderCallback).
Fixes https://github.com/xamarin/xamarin-macios/issues/13637.
Backport of #13673
> [release/6.0.2xx-preview12] [AudioUnit] Create a GCHandle when AudioUnit.SetInputCallback is called. Fixes #13637.

- tests/xharness/Jenkins/Jenkins.cs
Fixes https://github.com/xamarin/maccore/issues/2538.
> [xharness] Bump timeout for the .NET tests to 3 hours. Fixes #xamarin/maccore@2538.

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CodesignTaskBase.cs
This way I don't keep having to figure out why the property must not be
removed, even though it's not (visibly) used.
> [msbuild] Add helpful comment about unused property

- src/AudioUnit/AudioUnit.cs
- tests/monotouch-test/AudioToolbox/AudioUnitTest.cs
AudioUnit needs a GCHandle in the input callback, which means we have to create it
when SetInputCallback is called (like we already do for SetRenderCallback).
Fixes https://github.com/xamarin/xamarin-macios/issues/13637.
> [AudioUnit] Create a GCHandle when AudioUnit.SetInputCallback is called. Fixes #13637.

- src/Foundation/NSObject.iOS.cs
- src/Foundation/NSObject.mac.cs
They're deprecated, because there's a better alternative (NSObject.PlatformAssembly).
> [Foundation] Remove the NSObject.[MonoTouchAssembly|MonoMacAssembly] fields in .NET.

- src/CoreAnimation/CATransform3D.cs
- src/SceneKit/SCNMatrix4.cs
- tests/monotouch-test/ObjCRuntime/TrampolineTest.cs
- tests/test-libraries/testgenerator.cs
Public fields shouldn't start with a lower-cased letter.
Also provide public properties in legacy Xamarin so that we can write
identical code for both, and obsolete the lower-cased fields.
> [CoreAnimation] Rename CATransform3D's fields to follow standard naming conventions for .NET.

- src/AudioToolbox/AudioFile.cs
Arrays are by default only marshaled to P/Invokes, any changes done to the array
in native code are not copied back to managed memory.
Ref: https://docs.microsoft.com/en-us/dotnet/framework/interop/marshaling-different-types-of-arrays
However, broken code tend to work just fine, because the runtime usually just passes
a pointer to the managed memory to the P/Invoke. This is fast (no need to copy memory
around), but it also has the side effect that any changes to the memory during execution
of the P/Invoke is observed in managed code as well.
For some reason the MonoTouchFixtures.AudioToolbox.AudioConverterTest test runs into
a scenario where this isn't the case, and the test ends up hanging.
So fix it by making the P/Invoke take a pointer to the AudioStreamPacketDescription
array instead …
> [AudioToolbox] Use unsafe code to marshal in/out arrays. Fixes #xamarin/maccore@2537.

- src/AppKit/Enums.cs
- tests/xtro-sharpie/Helpers.cs
- tests/xtro-sharpie/api-annotations-dotnet/common-AppKit.ignore
- tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.ignore
- tests/xtro-sharpie/common-AppKit.ignore
- tests/xtro-sharpie/macOS-AppKit.ignore
Also remove the Unscaled field, it's removed from the headers, and it was
deprecated before the earliest macOS version we support.
Also also fix a few xtro issues.
> [AppKit] Update NSWindowStyle deprecations according to headers.

- src/Foundation/Enum.cs
- src/foundation.cs
- tests/monotouch-test/Foundation/CalendarTest.cs
- tests/xtro-sharpie/api-annotations-dotnet/common-Foundation.ignore
It's our own enum, and all the API using it have been obsoleted/removed.
There doesn't seem to be any other usage of it on GitHub either (only our own
source code and documentation).
> [Foundation] Remove the NSDateComponentsWrappingBehavior in .NET.

- dotnet/BreakingChanges.md
- src/SceneKit/SCNMatrix4.cs
- src/SceneKit/SCNMatrix4_dotnet.cs
- src/frameworks.sources
- tests/monotouch-test/SceneKit/SCNMatrixTest.cs
* Implement a column-major version of SCNMatrix4 in .NET to match native code.
* This was done by copying the existing SCMatrix4 implementation, and modify it
as required (doing it with conditional compilation in the same file turned out
to be quite messy, so I opted for using different files for legacy Xamarin and
.NET).
* There was one major change: the matrix inversion algorithm is new (copied from
.NET instead), because the legacy Xamarin version showed strange results with
some test values.
* Add setters for SCNMatrix4.Column[0-3] for legacy Xamarin to match the .NET API.
* Add CreateFromColumns methods for legacy Xamarin to match the .NET API.
* Add tests for all the new API.
Fixes https://github.com/xamarin/xamarin-macios/issues/4652.
> [SceneKit] Make SCNMatrix4 column-major in .NET. Fixes #4652.

- mk/xamarin.mk
* xamarin/maccore@037cc66058 Setup MacCoolApp (NET6) to be duel x86_64/arm64 as required by submission tests now
* xamarin/maccore@3332ba19a0 [submission tests] Always build with /bl, even Legacy
* xamarin/maccore@6bb8bf46dd Fix a few submission test issues and document filters
* xamarin/maccore@b63ef4428c [devops] Add pipeline to test provisioning.
Diff: https://github.com/xamarin/maccore/compare/0be9399a534a1b7d28275a1629d95ed092fbfaa8..037cc660587eda859b2d735f571e8fc632e83d3b
> [maccore] Bump maccore to ease submission tests

- src/CoreData/Obsolete.cs
- src/coredata.cs
- src/foundation.cs
- tests/linker/ios/link sdk/LinkSdkRegressionTest.cs
- tests/monotouch-test/CoreData/FetchedResultsControllerTest.cs
- tests/monotouch-test/CoreData/ManagedObjectModelTest.cs
* Remove obsolete API from .NET.
* Change API marked with XAMCORE_4_0 due to naming problems to be in .NET.
* Change API marked with XAMCORE_4_0 due to using non-generic NSDictionary to be
in XAMCORE_5_0 instead (yay!). This is because of #13704, which can make using
generic NSDictionary in API buggy, and I feel it's a bit too risky to change this
for .NET with the time we have available (no time to fix #13704). Additionally,
moving this to XAMCORE_5_0 makes it possible to keep grepping for XAMCORE_4_0 to
see what's left. Update all the CoreData API to be better as defined by our XAMCORE_4_0
define. Mostly using generic NSSet/NSDictionary types instead of the non-generic
ones, and other misc naming improvements.
* Change API marked with XAMCORE_4_0 due to both of the above to do both of …
> [CoreData] Move CoreData into the .NET age.

- src/CoreGraphics/CGAffineTransform.cs
- src/CoreImage/CISampler.cs
- tests/monotouch-test/CoreGraphics/AffineTransformTest.cs
Rename the public fields in CGAffineTransform to:
* Follow our naming convention (public API should always start with an
upper-case letter).
* Use the same names as Apple's version to ease porting Swift/Objective-C
code.
Fixes https://github.com/xamarin/xamarin-macios/issues/13494.
> [CGAffineTransform] Rename public fields in .NET to follow Apple and managed naming conventions. Fixes #13494.

- src/appkit.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/8198.
> [AppKit] Make NSScrollView.DocumentView be an NSView in .NET. Fixes #8198.

- src/foundation.cs
The conditional code was always true pre-NET. There's no reason to change it
for NET, so the condition can just be completely removed.
Clearly this wasn't the intention, and the condition was intended to be false
on macOS, but it's too late now to fix this accidental breaking change when it
occurred over 6 years ago.
Ref: https://github.com/xamarin/maccore/commit/3bc5c33bbc7c0eaf32ba7bb412b76c087b1365c0
> [Foundation] Remove conditional code that wasn't conditional for NSValueTransformer.

- src/appkit.cs
- tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.ignore
The original name is quite bad.
> [AppKit] Rename NSTableView.DragImageForRowsWithIndexestableColumnseventoffset to NSTableView.DragImageForRows in .NET.

- src/foundation.cs
- tests/monotouch-test/Foundation/FileCoordinatorTest.cs
- tests/xtro-sharpie/api-annotations-dotnet/common-Foundation.ignore
Remove badly named API (or with typos) in .NET.
> [Foundation] Remove some obsolete NSObject API in .NET

- src/AudioUnit/AudioUnit.cs
- tests/monotouch-test/AudioToolbox/AudioUnitTest.cs
This makes it easier to figure out problems in consuming code, since it makes
it easier to identify where things start to go wrong.
Fixes https://github.com/xamarin/maccore/issues/2539.
> [AudioUnit] Improve a few AudioUnit methods to return the error code.

- src/intents.cs
- tests/xtro-sharpie/api-annotations-dotnet/macOS-Intents.ignore
But only some values, the rest aren't available, so remove those from .NET.
> [Intents] The INPersonRelationship enum was added to macOS 12.1 according to the documentation.

- src/intents.cs
- tests/xtro-sharpie/api-annotations-dotnet/macOS-Intents.ignore
According to the headers it's not available in macOS.
> [Intents] Remove INSetMessageAttributeIntentResponseCode from macOS in .NET.

- src/intents.cs
Fixes:
Introduced: 2 API with unneeded or incorrect version information
[FAIL] 10.15 (Intents.INPersonRelationship Son) < 12.1 (Intents.INPersonRelationship)
[FAIL] 10.15 (Intents.INPersonRelationship Daughter) < 12.1 (Intents.INPersonRelationship)
Fixes https://github.com/xamarin/maccore/issues/2540.
> [Intents] Adjust initial introduction to INPersonRelationship in macOS.

- tests/introspection/ApiAvailabilityTest.cs
- Disable check "[FAIL] Both '{t}' and '{m}' are marked with `{s}`." type and member on that type in NET
- Due to the behavior of NET6 style attributes, we are forced to duplicate availability attributes in many cases
- See https://github.com/xamarin/xamarin-macios/issues/10170 for details
> [tests] Disable attribute duplication check

- dotnet/BreakingChanges.md
- src/CFNetwork/CFHTTPAuthentication.cs
- src/CFNetwork/CFHTTPMessage.cs
- src/CFNetwork/CFHTTPStream.cs
- src/CFNetwork/CFHost.cs
- src/CoreFoundation/CFProxySupport.cs
- src/CoreFoundation/CFStream.cs
- src/Foundation/NSStream.cs
- src/System.Net.Http/CFContentStream.cs
- src/System.Net.Http/CFNetworkHandler.cs
- src/cfnetwork.cs
- tests/introspection/ApiCMAttachmentTest.cs
- tests/introspection/ApiFrameworkTest.cs
- tests/linker/ios/link sdk/LinkSdkRegressionTest.cs
- tests/monotouch-test/CoreFoundation/ProxyTest.cs
- tests/monotouch-test/CoreServices/HttpMessageTest.cs
- tests/xtro-sharpie/api-annotations-dotnet/common-CFNetwork.ignore
- tests/xtro-sharpie/api-annotations-dotnet/common-CoreServices.ignore
These types come from the CFNetwork.framework, but for some reason they were bound inside CoreServices many years ago.
This resolves a potential issue where we might end up linking with the
CoreServices framework instead of CFNetwork framework (because we use the
namespace of types to determine which framework they belong to).
> [CFNetwork] Move the CFHost and CFHTTP* types to the CFNetwork namespace in .NET.

- src/foundation.cs
Ref: https://github.com/xamarin/xamarin-macios/pull/13756/files#r786311588
> [Foundation] Rename parameter to NSItemProviderCompletionHandler to be more descriptive.

- src/CoreMidi/MidiServices.cs
- src/coremidi.cs
This enum isn't deprecated, so no reason for them to not exist in .NET.
Also update the availability attributes according to current headers.
Finally move the entire enum to be processed by the generator to simplify
availability attributes.
> [CoreMidi] Fix availability for MidiNetworkConnectionPolicy.

- src/appkit.cs
It's deprecated (since macOS 10.6), so just don't add it to avoid any conflicts with other API.
> [AppKit] Don't add NSTextInput.DoCommandBySelector in .NET.

- src/SpriteKit/SKAction.cs
- src/SpriteKit/SKUniform.cs
- src/spritekit.cs
- tests/monotouch-test/SpriteKit/UniformTest.cs
- tests/xtro-sharpie/api-annotations-dotnet/tvOS-SpriteKit.todo
This means removing numerous obsolete/deprecated methods where better/more
correct alternatives already exist.
Also fix one obsolete message and adjust the tests.
> [SpriteKit] Adopt XAMCORE_4_0 changes in .NET.

- src/StoreKit/Enums.cs
- src/storekit.cs
- tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-StoreKit.ignore
- tests/xtro-sharpie/api-annotations-dotnet/iOS-StoreKit.ignore
- tests/xtro-sharpie/iOS-StoreKit.ignore
This is mostly removing obsolete/removed API, except for
SKProduct.ContentVersion, where the XAMCORE_4_0 annotations were wrong and the
property is still alive and kicking.
> [StoreKit] Adopt XAMCORE_4_0 changes in .NET.

- src/homekit.cs
Ought to fix these introspection failures on macOS 10.15 with Mac Catalyst:
Introspection.iOSApiFieldTest
[FAIL] Could not open the library '/System/Library/Frameworks/HomeKit.framework/HomeKit' to find the field 'HMCharacteristicMetadataFormatArray':
[FAIL] Could not open the library '/System/Library/Frameworks/HomeKit.framework/HomeKit' to find the field 'HMCharacteristicMetadataFormatBool': dlopen(/System/Library/Frameworks/HomeKit.framework/HomeKit, 0): image not found
[FAIL] Could not open the library '/System/Library/Frameworks/HomeKit.framework/HomeKit' to find the field 'HMCharacteristicMetadataFormatData': dlopen(/System/Library/Frameworks/HomeKit.framework/HomeKit, 0): image not found
[FAIL] Could not open the library '/System/Library/Frameworks/HomeKit.framework/HomeKit' to …
> [HomeKit] Add missing availability attributes for a few HomeKit types for Mac Catalyst.

- tools/devops/automation/templates/devices/run-tests.yml
This is needed to fix a number of tests that will fail to build on CI with:
```
Task "Exec" (TaskId:108)
[23:06:37.9659920]   Task Parameter:Command=make -j8 -C /Users/xamarinqa/azdo/_work/142/s/xamarin-macios/tests/test-libraries (TaskId:108)
[23:06:37.9719390]   make -j8 -C /Users/xamarinqa/azdo/_work/142/s/xamarin-macios/tests/test-libraries (TaskId:108)
[23:06:38.6389370]   /bin/sh: /Users/xamarinqa/azdo/_work/142/s/xamarin-macios/builds/downloads/dotnet-sdk-6.0.200-preview.22063.5-osx-x64/dotnet: No such file or directory (TaskId:108)
[23:06:38.6394920]   make[3]: *** [.libs/FrameworksInRuntimesNativeDirectory.nupkg] Error 127 (TaskId:108)
[23:06:38.6395440]   make[2]: *** [all-recurse] Error 1 (TaskId:108)
[23:06:38.6395820]   make[1]: *** [all-recurse] Error 1 (TaskId:108) …
```
> [CI] Bootstrap dotnet.

- tools/devops/automation/build-pipeline.yml
- tools/devops/automation/templates/build/build.yml
- tools/devops/automation/templates/build/stage.yml
Allow to skip it for several reasons:
1. We might want to seepd up a build during a release.
2. We want to make the build.yml template for pflexible, later we will
have to instances, one for the diff one to run tests and build.
Running those in parallel should buy us an hour in the total build.
> [CI] Allow to optionally skip API diff.

- src/CoreGraphics/CGAffineTransform.cs
- src/CoreGraphics/CGPoint.cs
- src/CoreGraphics/CGRect.cs
- src/CoreGraphics/CGSize.cs
- src/CoreGraphics/CGVector.cs
- src/NativeTypes/Drawing.tt
- src/frameworks.sources
- tests/monotouch-test/CoreGraphics/AffineTransformTest.cs
- tests/monotouch-test/CoreGraphics/PointTest.cs
- tests/monotouch-test/CoreGraphics/RectTest.cs
- tests/monotouch-test/CoreGraphics/SizeTest.cs
- tests/monotouch-test/CoreGraphics/VectorTest.cs
- tests/monotouch-test/Foundation/ObjectTest.cs
- tests/monotouch-test/MediaPlayer/MediaItemArtworkTest.cs
- tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
- tests/xtro-sharpie/api-annotations-dotnet/common-UIKit.ignore
- tests/xtro-sharpie/api-annotations-dotnet/macOS-Foundation.ignore
* Use the native `NSStringFrom*` API so we can, eventually, use the
native code to parse them from `NSString` and also ensure increased
compatibility with any code that expects the native string representation
* Add unit tests for `ToString` methods
Also use [`System.HashCode`](https://docs.microsoft.com/en-us/dotnet/api/system.hashcode?view=net-6.0) to generate the hash code
> [net][coregraphics] Match native strings representation for structs

- src/quicklookthumbnailing.cs
This means using the correct namespace.
> [QuickLookThumbnailing] Adopt XAMCORE_4_0 changes in .NET.

- src/quicklookUI.cs
This means fixing a property name to follow our naming guidelines.
> [QuickLookUI] Adopt XAMCORE_4_0 change in .NET.

- src/AudioUnit/AudioComponentDescription.cs
- tests/monotouch-test/AudioUnit/AUAudioUnitFactoryTest.cs
- tests/monotouch-test/AudioUnit/AUGraphTestMac.cs
- tests/monotouch-test/AudioUnit/AudioUnit.cs
- tests/monotouch-test/AudioUnit/AudioUnitTest.cs
Strong names are always better!
> [AudioComponentDescription] Strong-type the ComponentSubType field in .NET.

- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.cs.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.de.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.es.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.fr.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.it.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ja.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ko.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pl.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pt-BR.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ru.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.tr.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hans.resx
- msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hant.resx
> Localized file check-in by OneLocBuild Task: Build definition ID 14411: Build ID 5659994

- src/MobileCoreServices/UTType.cs
- tests/monotouch-test/MobileCoreServices/UTTypeTest.cs
* Use `is` instead of `==` for null checks
* Use `ThrowHelper` to throw common exceptions
* Use faster `CFString` API (over the slower `NSString` variants)
> [mobilecoreservices] Modernize UTType

- src/MetalPerformanceShaders/MPSCompat.cs
- src/MetalPerformanceShaders/MPSEnums.cs
- src/MetalPerformanceShaders/MPSImageHistogram.cs
- src/MetalPerformanceShaders/MPSMatrixDescriptor.cs
- src/metalperformanceshaders.cs
This means removing obsolete/deprecated API.
> [MetalPerformanceShaders] Adopt XAMCORE_4_0 changes in .NET.

- src/Photos/Enums.cs
- src/Photos/PHCompat.cs
- src/photos.cs
- tests/monotouch-test/Photos/LivePhotoEditingContextTest.cs
This means removing obsolete/deprecated API.
> [Photos] Adopt XAMCORE_4_0 changes in .NET.

- src/PdfKit/Enums.cs
- src/PdfKit/PdfAnnotation.cs
- src/PdfKit/PdfCompat.cs
- src/pdfkit.cs
This mostly involves fixing naming mistakes and removing deprecated/obsolete
API.
> [PdfKit] Adopt XAMCORE_4_0 changes in .NET.

- src/Foundation/NSObject2.cs
Use an enum (valuetype) instead of a class.
> [net][foundation] Simplify `NSObjectFlag`

- src/CoreGraphics/CGContextPDF.cs
- src/Foundation/NSMutableDictionary.cs
- src/ImageIO/CGImageSource.cs
- src/Security/Certificate.cs
That makes it easier on the caller, e.g. `CGContextPDF`, to avoid
creating short-lived `NSString` instance without requiring a lot
of code.
Downside: it becomes ambiguious if `NSString` is used, e.g.
`SecCertificate` for the compiler to decide between `NSObject` and
`string` overloads (but it's easy to fix and has no other impact).
> [foundation] add `NSMutableDictionary` helper to avoid creating extra `NSString` instances

- Make.config
> [d17-1] [CI] Bump the min version of the simulators since Apple remove the old ones.

- Make.config
> [release/6.0.2xx-preview13] [CI] Bump the min version of the simulators since Apple remove the old ones.

- src/AssemblyInfo.cs.in
- src/Makefile
* Set the AssemblyVersion attribute for .NET (to the NuGet version).
* Use the NuGet version number for the AssemblyInformationalVersion attribute
in .NET.
* Use 'Microsoft.*' as the assembly title and assembly product in .NET (ref:
#13748).
* Remove the InternalsVisibleTo attribute to System.Net.Http in .NET, it's no
longer needed.
Fixes https://github.com/xamarin/xamarin-macios/issues/13739.
> Update assembly info for our platform assemblies. Fixes #13739.

- src/ARKit/ARCompat.cs
- src/arkit.cs
- tests/monotouch-test/ARKit/ARConfigurationTest.cs
For ARKit this just means removing obsolete/deprecated API.
> [ARKit] Adopt XAMCORE_4_0 changes in .NET.

- src/AVFoundation/AVCaptureDeviceDiscoverySession.cs
- src/avfoundation.cs
Co-Written by @dalexsoto 
This PR will allow us to use the correct enum types `AVMediaTypes` and `AVCaptureDeviceType`
> [AVFoundation] Allowing the use of AVMediaTypes and AVCaptureDeviceType

- src/System.Drawing/ColorKnownColorTypeForwarders.cs
- src/System.Drawing/PointSizeRectangleTypeForwarders.cs
Type forwarders are used to move types and be backwards compatible, but we're
not backwards compatible with anything in our first .NET release, so there's
no need for these type forwarders.
> Remove the type forwarders for System.Drawing types in .NET.

- src/CoreAnimation/CACompat.cs
- src/CoreAnimation/CAScrollLayer.cs
- src/CoreAnimation/CATextLayer.cs
- src/CoreAnimation/CATransform3D.cs
- src/coreanimation.cs
- tests/monotouch-test/CoreAnimation/CATextLayerTests.cs
- tests/monotouch-test/CoreAnimation/EmitterBehaviorTest.cs
- tests/xtro-sharpie/api-annotations-dotnet/common-CoreAnimation.ignore
* Mostly just removal of obsolete/deprecated API.
* Modified CAScrollLayer.ScrollMode to use the good name
(CAScrollLayer.ScrollMode) for the strongly typed enum, and then have a
WeakScrollMode property for the NSString version (like we do elsewhere).
> [CoreAnimation] Adopt XAMCORE_4_0 changes in .NET.

- src/ObjCRuntime/NativeHandle.cs
- tests/monotouch-test/ObjCRuntime/NativeHandleTest.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/13867.
> [ObjCRuntime] Add explicit conversion operators between NativeHandle and void*. Fixes #13867.

- src/ObjCRuntime/Registrar.cs
- tools/common/StaticRegistrar.cs
Since 32bits macOS support was dropped this is always `true` so it is not
needed anymore.
> [objcruntime] Remove `SupportsModernObjectiveC` from the registrar

- dotnet/package/common.csproj
Template package does not appear on nuget.org correctly, as `packageType` in nupkg is set to `DotnetPlatform`.
Disabled loading Microsoft.DotNet.SharedFramework.Sdk for template package build.
it doesn't seems to be needed and overwrites PackageType to DotnetPlatform, even though initially it is correctly set to 'PackageType'
I would recommend to consider disabling other targets from `common.csproj` that are not needed for template package build.
> ensure PackageType = Template for template packages

- dotnet/targets/Xamarin.Shared.Sdk.targets
It seems that MSBuild doesn't always automatically convert directory
separators for relative paths, so we have to do it ourselves.
Thanks to @lauxjpn for diagnosing this and coming up with a fix.
Fixes https://github.com/xamarin/xamarin-macios/issues/13838.
> [dotnet] Convert windows dir separators to mac dir separators for relative paths in the _StripAssemblyIL target. Fixes #13838.

- src/ObjCRuntime/Class.cs
It's already exposed publicly, by `GetHandle`, so it's an unneeded
extra call (and associated metadata)
> [objcruntime] Remove private `GetClassHandle`

- src/Foundation/NSKeyedArchiver.cs
- src/Foundation/NSKeyedUnarchiver.cs
- src/foundation.cs
* Use `is` instead of `==` for null checks
* Use `ThrowHelper` to throw common exceptions
* Use faster `CFString` API (over the slower `NSString` variants)
* Change bindings to generate `RequiresSecureCoding` property without extra manual bindings
> [foundation] Modernize and simplify NSKeyed[Una|A]rchiver

- src/CoreGraphics/CGContextPDF.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/13953.
> [CoreGraphics] Add missing nullability for a CGContextPDF constructor and the CGContextPDF.BeginPage method. Fixes #13953.

- src/ObjCRuntime/Runtime.cs
Fixes:
ObjCRuntime/Runtime.cs(64,15): warning CS0649: Field 'Runtime.MTRegistrationMap.protocol_wrapper_count' is never assigned to, and will always have its default value 0
ObjCRuntime/Runtime.cs(111,18): warning CS0649: Field 'Runtime.Trampolines.ctor_tramp' is never assigned to, and will always have its default value
ObjCRuntime/Runtime.cs(58,33): warning CS0649: Field 'Runtime.MTRegistrationMap.protocol_wrapper_map' is never assigned to, and will always have its default value
ObjCRuntime/Runtime.cs(63,15): warning CS0649: Field 'Runtime.MTRegistrationMap.skipped_map_count' is never assigned to, and will always have its default value 0
CoreText/CTStringAttributes.cs(104,37): warning CS0649: Field 'CTStringAttributeKey.WritingDirection' is never assigned to, and will always have its …
> [src] Fix numerous compiler warnings.

- dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalystbinding/ApiDefinition.cs
- dotnet/Templates/Microsoft.iOS.Templates/iosbinding/ApiDefinition.cs
- dotnet/Templates/Microsoft.macOS.Templates/macos/ViewController.cs
- dotnet/Templates/Microsoft.tvOS.Templates/tvos/ViewController.cs
- tests/dotnet/UnitTests/TemplateTest.cs
- tests/dotnet/UnitTests/TestBaseClass.cs
Also make the (NativeHandle) constructor protected instead of public, to make
it clearer that it's not for public consumption.
And modify the template tests to execute the template if we can.
Fixes https://github.com/xamarin/xamarin-macios/issues/13979.
> [dotnet] Fix templates to use NativeHandle instead of IntPtr. Fixes #13979.

- src/ObjCRuntime/Runtime.cs
Output before fix:
Xamarin.Mac: Processing managed exception for exception marshalling (mode: 2):
Failed to print exception: System.NullReferenceException: Object reference not set to an instance of an object.
at ObjCRuntime.Runtime.PrintException(Exception exc, Boolean isInnerException, StringBuilder sb)
at ObjCRuntime.Runtime.PrintAllExceptions(IntPtr exception_gchandle)
Output after fix:
Xamarin.Mac: Processing managed exception for exception marshalling (mode: 2):
Unable to print exception handle 0x102ca12b8: null exception
while not much more informative, it's at least not throwing a NullReferenceException that seems unexpected.
> [ObjCRuntime] Improve code to render an exception to avoid a NullReferenceException in case of invalid input.

- dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalystbinding/ApiDefinition.cs
- dotnet/Templates/Microsoft.iOS.Templates/iosbinding/ApiDefinition.cs
- dotnet/Templates/Microsoft.macOS.Templates/macos/ViewController.cs
- dotnet/Templates/Microsoft.tvOS.Templates/tvos/ViewController.cs
- tests/dotnet/UnitTests/TemplateTest.cs
- tests/dotnet/UnitTests/TestBaseClass.cs
Also make the (NativeHandle) constructor protected instead of public, to make
it clearer that it's not for public consumption.
And modify the template tests to execute the template if we can.
Fixes https://github.com/xamarin/xamarin-macios/issues/13979.
Backport of #14001
> [release/6.0.2xx-preview13] [dotnet] Fix templates to use NativeHandle instead of IntPtr. Fixes #13979.

- eng/Version.Details.xml
- eng/Versions.props
Downgrade the linker reference to use a 6.0.100 version, otherwise we might
end up building dotnet-linker.dll with a reference to illink.dll v6.0.200, and
then (trying to) execute on illink.dll v6.0.100, which fails with the
following unhelpful error:
> error ILLink : error IL1027: Custom step 'Xamarin.SetupStep' could not be found
This occurs because illink.dll v6.0.100 fails to load our custom step assembly
(dotnet-linker.dll) where the 'Xamarin.SetupStep' is, beacuse
dotnet-linker.dll references illink.dll v6.0.200.
> [dotnet] Downgrade the linker reference.

- src/CoreImage/CIFilter.cs
- src/coreimage.cs
* Use faster `CFString` API (over the slower `NSString` variants)
* Rework internal API to use handles whenever possible
* Better use (and dispose) of `NSNumber`
* Use `ThrowHelper` to throw common exceptions
> [coreimage] Modernize CIFilter

- dotnet/targets/Xamarin.Shared.Sdk.targets
This speeds up builds significantly when the linker is disabled.
Test case: building tests/dotnet/MySimpleApp for macOS.
* Before: 37s
* After: 9s
* Difference: 26s (4x faster)
Test case: run the .NET tests
* Before: 2h55
* After: 1h43
* Difference: 1h12 (1.7x faster)
Contributes towards https://github.com/xamarin/xamarin-macios/issues/10251.
Ref: https://github.com/dotnet/linker/issues/2089
> [dotnet] Ask the linker to not mark copied assemblies if we're in a 'don't link' scenario.

- runtime/runtime.m
- runtime/xamarin/runtime.h
It does exactly what you'd think it does: nothing helpful at all.
Make sure to use a GCHandle that's alive instead.
Output before fix:
Xamarin.Mac: Processing managed exception for exception marshalling (mode: 2):
Failed to print exception: System.NullReferenceException: Object reference not set to an instance of an object.
at ObjCRuntime.Runtime.PrintException(Exception exc, Boolean isInnerException, StringBuilder sb)
at ObjCRuntime.Runtime.PrintAllExceptions(IntPtr exception_gchandle)
Output after fix:
Xamarin.Mac: Processing managed exception for exception marshalling (mode: 2):
Failed to lookup the required marshalling information.
Additional information:
Selector: conformsToProtocol:
Type: ViewController
(ObjCRuntime.RuntimeException)
Failed to get the 'this' instance in a method …
> [runtime] Don't try to log an exception for GCHandle that has been freed.

- src/CoreImage/CIFilter.cs
- src/coreimage.cs
- tests/introspection/ApiCoreImageFiltersTest.cs
- tests/monotouch-test/CoreImage/CIFilter.cs
- tests/monotouch-test/CoreImage/FilterTest.cs
This is all removing obsolete/deprecated members.
> [CoreImage] Adopt XAMCORE_4_0 changes in .NET.

- runtime/runtime.m
- tests/monotouch-test/ObjCRuntime/ExceptionsTest.cs
This makes diagnosing what happens much easier in some cases.
Exhibit A, pre fix:
*** Terminating app due to uncaught exception 'ObjCRuntime.RuntimeException', reason: 'Failed to lookup the required marshalling information.
Additional information:
Selector: conformsToProtocol:
Type: ViewController
Exhibit B, post fix:
*** Terminating app due to uncaught exception 'ObjCRuntime.RuntimeException', reason: 'Failed to lookup the required marshalling information.
Additional information:
Selector: conformsToProtocol:
Type: ViewController
(ObjCRuntime.RuntimeException)
Failed to get the 'this' instance in a method call to templ.ViewController.InvokeConformsToProtocol. (ObjCRuntime.RuntimeException)
at Registrar.DynamicRegistrar.GetMethodDescriptionAndObject(Type type, IntPtr selector, Boolean …
> [runtime] Use the full managed description (including inner exceptions) as the reason when creating an NSException from a managed exception.

- src/appkit.cs
Rename NSWorkspace.OpenURL[s] to OpenUrl[s] in .NET to follow our naming guidelines.
> [AppKit] Rename NSWorkspace.OpenURL[s] to OpenUrl[s] in .NET.

- src/generator.cs
- tests/generator/BGenTests.cs
- tests/generator/tests/abstract-type.cs
We have a problem that's shown up a few times, where we're given an instance
of a native type, where the closest bound managed type is a type declared as
[Abstract] in the api definition. In this case, we want to create an instance
of the [Abstract] type to wrap the native instance, but that hasn't been
possible because the managed type is abstract.
Note: this is totally fine from the OS perspective: it might have created an
instance of a private subclass we haven't bound (or it might even be a public
subclass we just haven't bound yet).
The fix is to:
* Stop making [Abstract] classes in the api definition abstract classes in the generated code.
* Make the default constructor default to "protected" visibility for [Abstract] classes.
This way we can still create instances of these types at …
> [generator] Rework how we implement [Abstract] classes in .NET. Fixes #4969.

- dotnet/targets/Xamarin.Shared.Sdk.targets
Mono will eventually use functions from the Compression framework to
decompress ICU data files during the runtime's initialization. Prepare
for this by linking against the compression framework.
Also see https://developer.apple.com/documentation/compression?language=objc.
> Link against the Compression framework.

- dotnet/DefaultCompilationIncludes.md
Binding projects enable default compile items now, so the documentation saying
otherwise is outdated and must be rectified.
Ref: https://github.com/xamarin/xamarin-macios/commit/499a69e7720daf37cfb527f66127d46a89892ab9
> [dotnet] Update docs about default inclusion in binding projects.

- src/appkit.cs
- src/generator.cs
- tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.ignore
Also update/fix code to show the corresponding warning in the generator, and
make a note of why MKUserLocation/MKAnnotation is special.
> [AppKit] Use the correct interface for inlining protocols in our api definitions in .NET.

- src/appkit.cs
There's no need to have two methods doing the exact same thing.
> [AppKit] Remove NSImage.DrawInRect in .NET, because it's already implemented as NSImage.Draw.

- dotnet/BreakingChanges.md
- src/CFNetwork/Content.cs
- src/CFNetwork/MessageHandler.cs
- src/CFNetwork/WebRequestStream.cs
- src/CFNetwork/WebResponseStream.cs
- src/CFNetwork/WorkerThread.cs
This type has been obsolete for over 3 years, it hasn't been updated in many
more years, and there are multiple newer and better alternatives available.
This meant we could remove a few more other (private/related) types as well.
> [CFNetwork] Remove the MessageHandler type from .NET.

- src/webkit.cs
In all cases these members were sealed to avoid a duplicate selector error,
but all those duplications don't exist anymore in XAMCORE_3_0, so we can
unseal these members.
> [WebKit] Unseal a few members in XAMCORE_3_0+ that don't need to be sealed anymore.

- src/healthkit.cs
Remove the HKAnchoredObjectResultHandler2 delegate, and make the
HKAnchoredObjectResultHandler delegate have the correct signature in .NET.
> [HealthKit] Remove the HKAnchoredObjectResultHandler2 delegate in .NET.

- src/ObjCRuntime/DisposableObject.cs
- src/ObjCRuntime/INativeObject.cs
Not sure why it was added to `DisposableObject` but it seems the compiler
is not happy to use the extension method for the `NativeObject` subclass
even if it implement `INativeObject` (that might be the reason why?)
So remove it from `NativeObjectExtensions` for .net - as I guess it's too
late to remove from the recent `DisposableObject` in legacy.
The platform assemblies only use it for `NativeObject` subclass so it's
not an big issue... as I assume there's not many `INativeObject` user
code that does not use (or should be using) `NativeObject`.
Fix 1: avoid using `IntPtr` when `NativeHandle` is defined since the
compiler will add (not really needed) implicit conversions everywhere.
Fix 2: ensure the spirit/contract of `GetCheckedHandle` always work.
IOW the goal of `GetCheckedHandle` is …
> [objcruntime] Reduce duplication for `GetCheckedHandle` and fix it/them

- src/Foundation/NSRange.cs
- tests/monotouch-test/Foundation/NSRangeTest.cs
Where should tests for this live?
This avoids poor performance of GetHashCode and Equals that are used for the struct using reflection on the first field.
> Implement IEquatable<T> on NSRange

- dotnet/targets/Xamarin.Shared.Sdk.targets
- runtime/runtime.m
- runtime/xamarin/runtime.h
- src/ILLink.Substitutions.ios.xml
- src/ILLink.Substitutions.tvos.xml
- src/ObjCRuntime/Runtime.iOS.cs
- tools/common/Application.cs
* Make Runtime.Arch a readonly field.
* Tell the AOT compiler Runtime.Arch is a constant value.
* Tell the linker to stub out the method we use to fetch the current
architecture from native code (it turned out a bit complicated to set the
Arch field when it's readonly - the solution I came up with was to call a
P/Invoke).
Test case (size of the main executable): link all (debug)
* Before:  33.522.704 bytes
* After:   33.506.112 bytes
* Difference: -16.592 bytes (-0.05 %)
There were no size differences in release mode, nor were there any size
differences in the "don't link" test, neither for debug nor release mode.
Fixes https://github.com/xamarin/xamarin-macios/issues/5518.
> [runtime] Make Runtime.Arch a readonly field in .NET. Fixes #5518.

- src/appkit.cs
- tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.ignore
Also change the NSColorChanging.ChangeColor method to not be deprecated
anymore, Apple's headers say nothing of the sort.
> [AppKit] Make NSTextView implement the NSColorChanging protocol in .NET.

- runtime/runtime.m
- tests/monotouch-test/ObjCRuntime/ExceptionsTest.cs
- tools/common/Application.cs
When exception marshalling was originally implemented, for backwards
compatibility concerns it was only turned on by default for platforms that
really needed it (watchOS).
However, exception marshalling is by far the safest option, so in .NET we're
enabling it by default for all platforms (it's still possible to disable it
for those who wants to).
Ref: https://docs.microsoft.com/en-us/xamarin/ios/platform/exception-marshaling
> [tools/runtime] Enable exception marshalling by default for all platforms in .NET.

- src/metalperformanceshaders.cs
That's also how Swift defines it.
Fixes https://github.com/xamarin/xamarin-macios/issues/6530.
> [MetalPerformanceShaders] Make MPSCnnConvolutionDataSource.Load a method in .NET. Fixes #6530.

- tools/devops/automation/build-pipeline.yml
- tools/devops/automation/templates/release/vs-insertion-prep.yml
Use the new templates and sdk-insertion project to unify the vs load.
> [CI] Move to the new sdk-insertions workload.

- src/AppKit/NSColor.cs
- src/appkit.cs
- src/uikit.cs
- tests/monotouch-test/MapKit/PinAnnotationViewTest.cs
- tests/monotouch-test/UIKit/ColorTest.cs
Make the "Color" suffix consistent in NSColor and UIColor properties (by
removing the "Color" suffix for all such properties).
_We could also add the "Color" suffix everywhere, which matches Apple's Objective-C naming. We could also do what Swift does, which is not being consistent, some colors have "Color" suffix in Swift, some don't_
Fixes https://github.com/xamarin/xamarin-macios/issues/7945.
> [AppKit/Foundation] Make the "Color" suffix consistent in NSColor and UIColor properties. Fixes #7945.

- src/Makefile
Fixes random build errors like:
cp: build/dotnet/ios/ILLink.Substitutions.xml: clonefile failed: No such file or directory
> [src] Fix makefile to create directories before copying files into them.

- src/uikit.cs
- tests/xtro-sharpie/api-annotations-dotnet/common-UIKit.ignore
- tests/xtro-sharpie/common-UIKit.ignore
Implement the UIResponderStandardEditActions protocol, move the
corresponding API from UIResponder there, and make sure UIResponder implements
the new UIResponderStandardEditActions protocol (which should make this move a
non-breaking change, since the protocol is inlined in UIResponder).
> [UIKit] Implement the UIResponderStandardEditActions protocol.

- tools/common/Driver.cs
- tools/linker/CoreOptimizeGeneratedCode.cs
- tools/linker/MobileExtensions.cs
Thinks are working fine as-is (with this XAMCORE_4_0 variable set to false),
and I see no particular reason in the code to change it, nor does the original
implementation explain much (b2bcad7a947d502db1355f017966a897966c9bb1).
So just remove this XAMCORE_4_0 condition as if it had never existed.
> [tools] Remove XAMCORE_4_0 condition in linker source.

- src/javascriptcore.cs
- tests/monotouch-test/JavascriptCore/ValueTest.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/12549.
> [JavaScriptCore] Bind JSValue.ToArray as NSArray in .NET. Fixes #12549.

- src/generator.cs
Fixes:
src/generator.cs(915,4): warning CS0162: Unreachable code detected
src/generator.cs(918,5): warning CS0162: Unreachable code detected
src/generator.cs(921,5): warning CS0162: Unreachable code detected
src/generator.cs(923,5): warning CS0162: Unreachable code detected
> [generator] Make sure to not have dead code. Fixes a few compiler warnings.

- src/Foundation/NSProxy.cs
- tests/introspection/ApiFrameworkTest.cs
- tests/linker/ios/link sdk/LinkSdkRegressionTest.cs
- tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
The WebKit framework doesn't exist on tvOS.
> [Foundation] Remove a WebKit workaround for NSProxy on tvOS in .NET.

- src/Foundation/NSSecureCoding.cs
It represents a protocol, so it doesn't need to be instantiated.
> [Foundation] Make NSSecureCoding a static class in .NET.

- src/generator-typemanager.cs
- src/generator.cs
- tests/generator/BGenTests.cs
- tests/generator/tests/nint-delegates.cs
This makes us render this:
public delegate nfloat NSTableViewColumnWidth(NSTableView tableView, nint column);
instead of this:
public delegate nfloat NSTableViewColumnWidth(NSTableView tableView, IntPtr column);
Fixes https://github.com/xamarin/xamarin-macios/issues/14107.
> [bgen] Make sure to render nint/nuint in delegates as nint/nuint for .NET. Fixes #14107.

- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.AppExtension.CSharp.targets
- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.CSharp.targets
- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.FSharp.targets
- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.CSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.TVOS.AppExtension.CSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.TVOS.AppExtension.Common.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.TVOS.AppExtension.FSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.TVOS.CSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.TVOS.FSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.App.CSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.App.FSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.AppExtension.CSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.AppExtension.Common.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.AppExtension.FSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.CSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.FSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.AppExtension.CSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.AppExtension.FSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.CSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.FSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.WatchApp.CSharp.targets
- tests/common/TestProjects/SystemMemoryFromNetStandard2_0/Info.plist
- tests/common/TestProjects/SystemMemoryFromNetStandard2_0/Program.cs
- tests/common/TestProjects/SystemMemoryFromNetStandard2_0/SystemMemoryFromNetStandard2_0.csproj
- tests/common/TestProjects/SystemMemoryLibrary/SystemMemoryConsumer.cs
- tests/common/TestProjects/SystemMemoryLibrary/SystemMemoryLibrary.csproj
- tests/msbuild/Xamarin.MacDev.Tests/ProjectsTests/ProjectTest.cs
- tests/msbuild/Xamarin.MacDev.Tests/ProjectsTests/SystemMemoryReference.cs
We must set `ResolveAssemblyConflicts=true` before loading
Microsoft.Common.targets (which is loaded by Microsoft.CSharp.targets),
because otherwise we won'd do any conflict resolution at all, since the
variable isn't 'true' when it needs to be.
Also add test.
Fixes https://github.com/xamarin/xamarin-macios/issues/11691.
Fixes https://github.com/mono/mono/issues/20805.
> [msbuild] Make sure to set 'ResolveAssemblyConflicts=true' before importing Microsoft.CSharp.targets. Fixes #11691.

- src/Makefile
This fixes a random build error, because there's no rule that knows how create
these dependencies with a trailing slash.
> [src] Fix dependencies in makefile to not contain a trailing slash.

- src/generator-typemanager.cs
- src/generator.cs
- tests/generator/BGenTests.cs
- tests/generator/tests/nint-delegates.cs
This makes us render this:
public delegate nfloat NSTableViewColumnWidth(NSTableView tableView, nint column);
instead of this:
public delegate nfloat NSTableViewColumnWidth(NSTableView tableView, IntPtr column);
Fixes https://github.com/xamarin/xamarin-macios/issues/14107.
This is a backport of #14112.
> [release/6.0.2xx-preview13] [bgen] Make sure to render nint/nuint in delegates as nint/nuint for .NET. Fixes #14107.

- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Fixes https://github.com/xamarin/xamarin-macios/issues/14126.
> [msbuild] Provide a stamp file when codesign on-demand resources. Fixes #14126.

- src/Foundation/NSObject2.cs
- src/ObjCRuntime/Registrar.cs
- src/ObjCRuntime/Runtime.cs
- src/UIKit/UIButton.cs
Instead have the callers uses string interpolation. The compiler (current
and future) is able to optimize this or, at worse, will end up with a
call to `String.Format`.
> [runtime] Remove `NSLog (string format, params object?[] args)` overload

- src/Network/NWProtocolDefinition.cs
- src/appkit.cs
- src/avfoundation.cs
- src/externalaccessory.cs
- src/gamekit.cs
- src/metal.cs
- src/spritekit.cs
- src/uikit.cs
- tests/introspection/ApiAvailabilityTest.cs
- tests/introspection/ApiSelectorTest.cs
- tests/introspection/Mac/MacApiSelectorTest.cs
- tests/introspection/iOS/iOSApiSelectorTest.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/13957.
> [src/introspection] Adjust tests and availability attributes to work run on iOS/tvOS 12.4. Fixes #13957.

- dotnet/targets/Xamarin.Shared.Sdk.targets
- runtime/exports.t4
- runtime/monotouch-main.m
- tools/common/Application.cs
- tools/dotnet-linker/LinkerConfiguration.cs
* Propagate the IsAppExtension variable correctly.
* Don't try to call mono_domain_set_config for app extensions in .NET.
It doesn't look like it's needed, and it also immediately aborts anyway, so
if it turns out to be needed, another solution would have to be implemented.
Fixes https://github.com/xamarin/xamarin-macios/issues/13742.
> [dotnet/runtime] Fix a few issues with regards to extensions in .NET. Fixes #13742.

- dotnet/targets/Xamarin.Shared.Sdk.targets
- msbuild/Xamarin.Shared/Xamarin.Shared.targets
Fixes https://github.com/xamarin/xamarin-macios/issues/13417.
> [dotnet] Sign the 'createdump' executable. Fixes #13417.

- dotnet/targets/Xamarin.Shared.Sdk.targets
We need to use better default values for `$(VerifyDependencyInjectionOpenGenericServiceTrimmability)`.
This feature switch ensures that DynamicallyAccessedMembers are applied correctly to open generic types used in Dependency Injection.
In the base SDK, this switch is enabled when `PublishTrimmed=true`. However, iOS apps don't set `PublishTrimmed=true` until a Target. So devs are missing out on this validation.
Conversely, in published apps, we don't want to pay the cost of doing this validation. It was showing up in startup profiles on Android. So turning the feature switch off in Release builds (builds without debugging enabled).
Port of https://github.com/xamarin/xamarin-android/commit/90f546cacc15ca6693020ac2e92aa737315ea0a4
cc @rolfbjarne @jonathanpeppers 
Note, in Android we used …
> Default VerifyDependencyInjectionOpenGenericServiceTrimmability

- src/ObjCRuntime/Class.cs
The split [1] was done to ease nullability annotations since there's no
syntax to cover this specific case with custom attributes.
However we don't need three methods for the split. Two are enough :)
[1] https://github.com/xamarin/xamarin-macios/pull/13281
> [objcruntime] Simplified earlier split of internal `Lookup` method

- src/ObjCRuntime/Class.cs
That was mentioned
> Remove the (IntPtr) constructor for .NET
inside https://github.com/xamarin/xamarin-macios/pull/13281
but not actually done inside that PR
> [net][objcruntime] Remove `Class (IntPtr)` for .net profile

- src/ObjCRuntime/Runtime.cs
- tests/monotouch-test/ObjCRuntime/RuntimeTest.cs
- tools/common/StaticRegistrar.cs
- tools/mtouch/Errors.designer.cs
- tools/mtouch/Errors.resx
As a part of the breaking changes in .NET, we introduced a new type,
`ObjCRuntime.NativeHandle`, to represent native handles.
This meant that constructors taking taking `IntPtr handle`:
```cs
public class MyUIViewController : UIViewController {
protected MyUIViewController (IntPtr handle)
: base (handle)
{
}
}
```
would have to be ported to take `NativeHandle handle`:
```cs
public class MyUIViewController : UIViewController {
protected MyUIViewController (NativeHandle handle)
: base (handle)
{
}
}
```
The unfortunate part is that there will be no compiler warnings or errors
flagging this, so users won't know to do it unless they either read the
documentation (🤣) or run into the problem, googles for a while, runs into
someone else who had the same problem, and applies their (probably …
> [ObjCRuntime] Keep accepting IntPtr constructors in .NET as an alternative to NativeHandle constructors. Fixes #14046.

- src/ObjCRuntime/Class.cs
- src/ObjCRuntime/Runtime.cs
- tests/linker/ios/link all/PreserveTest.cs
inside it's _only_ caller and remove the API.
Remove old test that was already not useful (since the method could not
be removed anyway for quite a while).
> [objcruntime] Inline the use of the `Class.LookupFullName` method

- src/CoreFoundation/CFArray.cs
This allow the linker to remove the helper API (code and metadata) from
smaller apps.
> [corefoundation] Skip intermediate call inside `CFArray.DefaultConvert`

- msbuild/Makefile
Hopefully fixes random build failures like this:
> xamarin-macios/msbuild/Versions.ios.g.cs(3,1): error CS1022: Type or namespace definition, or end-of-file expected
> [msbuild] Generate Versions.*.g.cs before running msbuild to build the solution.

- src/AppKit/NSColor.cs
- src/NativeTypes/Primitives.tt
- tests/monotouch-test/AppKit/NSColor.cs
There's no corresponding System.Runtime.InteropServices.NFloat.CopyArray method in .NET.
It turned out that the API where we used CopyArray don't need to use CopyArray at all, the same can be accomplished faster and simpler by using unsafe code.
> [nfloat] Obsolete nfloat.CopyArray in legacy Xamarin and stop using it.

- tests/common/PlatformInfo.cs
This fixes the CheckManagedFilters tests on Mac Catalyst on older macOS versions:
[FAIL] CheckManagedFilters :   Managed filters not found for CIAreaMinMax, CIAreaMinMaxRed, CIAttributedTextImageGenerator, CIBarcodeGenerator, CIBicubicScaleTransform, CIBlendWithBlueMask, CIBlendWithRedMask, CIBokehBlur, CICameraCalibrationLensCorrection, CIColorCubesMixedWithMask, CIColorCurves, CICoreMLModelFilter, CIDepthBlurEffect, CIDepthToDisparity, CIDisparityToDepth, CIDither, CIDocumentEnhancer, CIEdgePreserveUpsampleFilter, CIGaborGradients, CIGuidedFilter, CIKeystoneCorrectionCombined, CIKeystoneCorrectionHorizontal, CIKeystoneCorrectionVertical, CIKMeans, CILabDeltaE, CIMeshGenerator, CIMix, CIMorphologyGradient, CIMorphologyMaximum, CIMorphologyMinimum, CIMorphologyRectangleMaximum, …
> [tests] Use the correct OS version for Mac Catalyst.

- dotnet/BundleContents.md
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CollectBundleResourcesTaskBase.cs
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ComputeBundleLocationTaskBase.cs
- msbuild/Xamarin.Shared/Xamarin.Shared.targets
- tests/dotnet/BundleStructure/BundleResourceD.txt
- tests/dotnet/BundleStructure/BundleResourceE.txt
- tests/dotnet/BundleStructure/BundleResourceF.txt
- tests/dotnet/BundleStructure/BundleResourceG.txt
- tests/dotnet/BundleStructure/BundleResourceH.txt
- tests/dotnet/BundleStructure/ContentD.txt
- tests/dotnet/BundleStructure/ContentE.txt
- tests/dotnet/BundleStructure/ContentF.txt
- tests/dotnet/BundleStructure/ContentG.txt
- tests/dotnet/BundleStructure/ContentH.txt
- tests/dotnet/BundleStructure/EmbeddedResourceD.txt
- tests/dotnet/BundleStructure/EmbeddedResourceE.txt
- tests/dotnet/BundleStructure/EmbeddedResourceF.txt
- tests/dotnet/BundleStructure/EmbeddedResourceG.txt
- tests/dotnet/BundleStructure/EmbeddedResourceH.txt
- tests/dotnet/BundleStructure/shared.csproj
- tests/dotnet/UnitTests/BundleStructureTest.cs
Add support for the PublishFolderType metadata on Content and BundleResource
items, which makes it possible to change the location in the app bundle for
these items (this was possible to do before with the Link metadata), but most
importantly it also makes it possible to choose to *not* bundle these items in
the app bundle (which was not possible before with the Link metadata, nor any
other means).
At first I thought setting CopyToPublishDirectory /
CopyToOutputDirectory=Never would accomplish that, but it turns out we don't
honor those, and since we already have this behavior of ignoring
CopyToPublishDirectory / CopyToOutputDirectory in legacy Xamarin, I didn't
want to change it in .NET.
So I added support for honoring the PublishFolderType metadata instead, which
is new and we already …
> [dotnet] Add support for the PublishFolderType metadata on Content and BundleResource items.

- src/Foundation/NSObject2.cs
Using NativeHandle avoids implicit casts [1]
[1] likely not an issue with JIT/AOT optimization, less sure for the
interpreter. No harm in not having those in the product assembly.
> [foundation] Fix some `IntPtr` -> `NativeHandle` inside `NSObject`

- src/ObjCRuntime/Runtime.cs
so the linker can remove more overloads from most/small applications.
In case of `ErrorHelper.CreateError` then the API was already accepting a
`null` exception so the extra code was not needed.
> [objcruntime] Use more direct calls in `Runtime`

- src/ObjCRuntime/Runtime.iOS.cs
- src/ObjCRuntime/Runtime.mac.cs
Found while looking [1] at the strings inside the assemblies.
The diff for before/after the PR is
```diff
-Version mismatch between the native Xamarin.iOS runtime and Xamarin.iOS.dll. Please reinstall Xamarin.iOS.
+Version mismatch between the native Microsoft.iOS runtime and Microsoft.iOS.dll. Please reinstall Microsoft.iOS.
```
[1] https://github.com/xamarin/xamarin-macios/issues/14188
> [net] Fix the product/assemblies names in error messages

- src/ObjCRuntime/DisposableObject.cs
- src/SearchKit/SearchKit.cs
It is not really needed. The only caller `SKIndex` was already clearing
the handle by calling `Dispose(bool)` which called `ClearHandle`.
If it really becomes needed then it can be reintroduced in the future.
> [net][objcruntime] Remove `DisposableObject.ClearHandle`

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DSymUtilTaskBase.cs
Just log these messages as normal messages, because they're not very actionable.
Ref: #13652.
> [msbuild] Don't report 'unable to open object file:' from dsymutil as warnings.

- src/CoreGraphics/CGColorConverter.cs
These types aren't used anywhere in the exposed API, nor do they do anything
useful today.
> [CoreGraphics] Remove CGColorConversionInfo and CGColorConversionInfoTriple from .NET.

- msbuild/Xamarin.HotRestart.PreBuilt/Makefile
- tests/common/shared-dotnet.mk
This way it's easier to copy-paste the path to the these files from terminal output
and open/run it (with a relative/partial path you'll need to know the current directory,
which is just an annoying thing to figure out sometimes).
> [tests/msbuild] Use full path to binlogs and executables.

- dotnet/targets/Xamarin.Shared.Sdk.targets
We don't sign each rid-specific bundle, but we sign the final merged app bundle instead.
This means that we must store the list of files to codesign from the rid-specific
build and load those lists before running codesign on the merged app bundle.
Fixes https://github.com/xamarin/xamarin-macios/issues/14155.
> [msbuild/dotnet] Make codesigning createdump work in universal apps. Fixes #14155.

- Make.config
- tools/apidiff/Makefile
- tools/devops/automation/templates/build/publish-html.yml
There was a large change to rename a lot of our Xamarin assemblies to Microsoft
ie) Xamarin.iOS -> Microsoft.iOS
There is a mismatch with some of the prerequisites in our tools/apidiff/Makefile where dependencies 
are looking for ...Microsoft.iOS... but they are still named ...Xamarin.iOS...
This PR takes any remaining "Xamarin" names and changes them to "Microsoft" for all dotnet related rules.
We will also change other dotnet rules to use the new naming convention of "macOS" and "tvOS"
The only exception is to the Xamarin.PLATFORM.dll's coming from the zip - those remain as Xamarin.iOS.dll
We should expect to see the gists showing up in ApiDiffs from this PR!
> [ApiDiffs] More renaming to enable ApiDiffs

- runtime/Makefile
This fixes an issue where the build would continue if the server in question
serves an error page (and eventually fail with weird errors because the error
page wouldn't be valid C code).
> [runtime] Ask curl to fail (--fail) if fetching the URL fails for coreclrhost.h.

- src/UIKit/UIApplication.cs
Hide the obsolete UIApplication.Main overload that takes string parameters
from intellisense. This overload is used *a lot*, so it's not worth it to
remove it, since it would break a lot of user code.
> [UIKit] Hide the obsolete UIApplication.Main overload.

- dotnet/Templates/Microsoft.iOS.Templates/ios-controller/.template.config/template.json
All templates except one were named "... (Preview)".
Now the one outlier has joined the rest.
> [dotnet] Name all templates as preview templates.

- src/AssetsLibrary/ALAsset.cs
This PR aims to bring nullability changes to AssetsLibrary.
1. Changing any `== null` or `!= null` to `is null` and `is not null`
* In this case, use updated features to replace "== null"
> [assetslibrary] Add nullability to (generated and manual) bindings

- src/VideoToolbox/VTDecompressionSession.cs
We already have a better overload that does not need manual reference counting.
> [VideoToolbox] Remove VTDecompressionSession.Create overload requiring manual reference counting.

- src/CoreGraphics/CGAffineTransform.cs
- src/SceneKit/SCNQuaternion.cs
- src/Simd/MatrixFloat2x2.cs
- src/Simd/MatrixFloat3x3.cs
- src/Simd/MatrixFloat3x3RM.cs
- tests/monotouch-test/Asserts.cs
Hoping that one day we'll have a System.Numerics.Matrix3x3 type we can replace our
RMatrix3 type with:
* Add all API in OpenTK.Matrix3 that also exists in equivalent form in System.Numerics.Matrix4x4.
* Remove all API that doesn't exist in equivalent form in System.Numerics.Matrix4x4.
For NMatrix2 and NMatrix3:
* Change the fields to be M## instead of R#C# (this is how System.Numerics does
it, and also how we do it in other matrix types).
* Add obsolete and hidden R#C# versions of the fields to ease migrating existing
code to .NET (but let's try to remove these in xamcore 5).
* Add properties in legacy Xamarin recommending users to use the new naming.
* A few other API additions to add equivalent API to the matrix types in System.Numerics.
For CGAffineMatrix:
* Add obsolete and hidden …
> [CoreGraphics] Improve matrix types for .NET. Fixes #14125.

- src/appkit.cs
These APIs are marked as deprecated in the headers (i.e. they still exist), so
mark them as such.
> [AppKit] Mark deprecated API as deprecated, not obsolete.

- Make.config
- dotnet/BreakingChanges.md
- msbuild/Makefile
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileAppManifestTaskBase.cs
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/XamarinTask.cs
- msbuild/Xamarin.MacDev.Tasks.Core/Xamarin.MacDev.Tasks.Core.csproj
- msbuild/Xamarin.iOS.Tasks.Core/Tasks/CompileAppManifestTaskCore.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/14108.
> [msbuild] Store the .NET version in the app's Info.plist when building an app using .NET. Fixes #14108.

- tests/Makefile
- tests/common/Configuration.cs
Fixes this failure:
++ DOTNET_CSC_COMMAND=/Users/builder/azdo/_work/1/s/xamarin-macios/builds/downloads/dotnet-sdk-6.0.300-preview.22118.1-osx-x64/dotnet
++ exec /Users/builder/azdo/_work/1/s/xamarin-macios/builds/downloads/dotnet-sdk-6.0.300-preview.22118.1-osx-x64/sdk/6.0.300-preview.22118.1/Roslyn/bincore/csc.dll
test.config: line 22: /Users/builder/azdo/_work/1/s/xamarin-macios/builds/downloads/dotnet-sdk-6.0.300-preview.22118.1-osx-x64/sdk/6.0.300-preview.22118.1/Roslyn/bincore/csc.dll: Permission denied
make[1]: *** [mac-test-package.zip] Error 1
make: *** [package-tests] Error 2
> [tests] Fix packaging mac tests by generating valid bash code for test.config.

- src/avfoundation.cs
- tests/xtro-sharpie/api-annotations-dotnet/tvOS-AVFoundation.ignore
These API were never valid for tvOS, and now we can completely remove them in .NET.
> [AVFoundation] Remove the AVAssetsDownloadTaskKeys and AVAssetDownloadOptions API in .NET for tvOS.

- src/metal.cs
MTLRenderCommandEncoder.SetViewports and
MTLRenderCommandEncoder.SetScissorRects aren't deprecated/obsoleted anywhere as
far as I can tell, so unmark them as such.
> [Metal] De-obsolete two MTLRenderCommandEncoder members.

- src/modelio.cs
It looks like these were bound by mistake for iOS, so take the opportunity now
to remove these binding mistakes.
> [ModelIO] Remove MDLVoxxelArray API in iOS that don't exist in iOS for .NET.

- src/Network/NWProtocolDefinition.cs
- src/Network/NWProtocolOptions.cs
- tests/monotouch-test/Network/NWBrowserTest.cs
- tests/monotouch-test/Network/NWConnectionTest.cs
- tests/monotouch-test/Network/NWEstablishmentReportTest.cs
- tests/monotouch-test/Network/NWListenerTest.cs
- tests/monotouch-test/Network/NWPathTest.cs
- tests/monotouch-test/Network/NWProtocolIPOptionsTest.cs
- tests/monotouch-test/Network/NWProtocolOptionsTest.cs
- tests/monotouch-test/Network/NWProtocolStackTest.cs
- tests/monotouch-test/Network/NWProtocolTlsOptionsTest.cs
- tests/monotouch-test/Network/NWResolutionReportTest.cs
- tests/monotouch-test/Security/ProtocolOptionsTest.cs
All the obsolete API has replacement API that works just fine.
> [Network] Remove obsolete API from .NET.

- src/Foundation/NSUrlSessionHandler.cs
- tests/monotouch-test/System.Net.Http/MessageHandlers.cs
It's better to use the TrustOverrideForUrl property instead, which already exists.
> [Foundation] Remove NSUrlSessionHandler.TrustOverride in .NET.

- tests/monotouch-test/GLKit/BaseEffectTest.cs
- tests/monotouch-test/GLKit/EffectPropertyMaterialTest.cs
The [Culture ("en")] attribute means: only run this test if the culture is
"en". This usually meant not running this test (apparently we don't run often
with culture = "en"), leading to outdated tests that happened to fail when
actually run under culture = "en" (such as on older macOS bots).
So change these tests to actually change the culture to "en" (by using the
SetCulture attribute), and also fix them.
> [monotouch-test] Fix the BaseEffectTest and EffectPropertyMaterialTest tests.

- tests/xtro-sharpie/.gitignore
- tests/xtro-sharpie/Makefile
- tests/xtro-sharpie/xtro-sharpie.csproj
Generate a proj file that contains variables for the current pch and assembly,
and include this proj file in the main xtro-sharpie project file. This way we
can use these variables for the pch and assembly arguments in the run
configurations, so we don't have to update the project file every time these
change (in particular the pch file changes name with every Xcode bump).
> [xtro] Generate a proj file that contains variables for the current pch and assembly.

- src/AVFoundation/Enums.cs
- src/AVKit/Enums.cs
- src/AudioToolbox/Enums.cs
- src/AudioUnit/AUEnums.cs
- src/CoreImage/Enums.cs
- src/CoreWlan/Enums.cs
- src/MediaPlayer/MediaPlayer.cs
- src/TVServices/TVEnums.cs
It's not necessary, the generator will generate the .NET-style attributes.
> [src] Remove .NET-style availability attributes from API definitions.

- tools/dotnet-linker/LinkerConfiguration.cs
- tools/mtouch/Errors.designer.cs
- tools/mtouch/Errors.resx
* Better text.
* Better number ("7000" is more like "this is kind of normal" - while "6999"
was more like "something quite expected happened").
* Use resources to make it localizable.
> [dotnet-linker] Improve the error message from the linker when we run into a problem.

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DSymUtilTaskBase.cs
- msbuild/Xamarin.Shared/Xamarin.Shared.targets
- msbuild/Xamarin.iOS.Tasks.Core/Tasks/MTouchTaskBase.cs
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
These properties aren't used.
This also allows us to remove the CompiledArchitectures output property from
the MTouch task, because it's not longer used anymore either.
> [msbuild] Remove the AppBundleDir and Architectures properties from the DSymUtil task.

- tests/cecil-tests/Helper.cs
- tests/cecil-tests/ObsoleteTest.cs
- tests/common/Configuration.cs
* Check implementation assemblies instead of reference assemblies.
* Try to print the source code location for failing API (this required processing
the implementation assemblies, because the reference assemblies don't have debug
information where the source code location is stored).
* Don't report API that has [EditorBrowsable (None)] attributes, presumably we
decided to keep these for compatibility, while highly discouraging their
continued use. Also stop doing this for the next time we can do a breaking
change, maybe we can remove these APIs then.
* Don't report API that has [UnsupportedOSPlatform ("...#.#") attributes (with
a version number), presumably this is API that is still valid for some OS
versions.
* Enable the test for all APIs (no ignores anymore). It's ✅ due to numerous
PRs …
> [cecil-tests] Improve the obsolete member test. Fixes #13621.

- src/ObjCRuntime/Runtime.cs
This avoid three `int` fields that requires initialization inside the
`.cctor` and the custom version parsing code.
> [objcruntime] Simplify `Runtime.CheckSystemVersion`

- src/AudioToolbox/AudioClassDescription.cs
- src/AudioToolbox/AudioConverter.cs
- src/AudioToolbox/AudioFile.cs
- src/AudioToolbox/AudioFileGlobalInfo.cs
- src/AudioToolbox/AudioFileStream.cs
- src/AudioToolbox/AudioFormat.cs
- src/AudioToolbox/AudioFormatAvailability.cs
- src/AudioToolbox/AudioQueue.cs
- src/AudioToolbox/AudioServices.cs
- src/AudioToolbox/AudioSession.cs
- src/AudioToolbox/AudioToolbox.cs
- src/AudioToolbox/AudioType.cs
- src/AudioToolbox/MusicPlayer.cs
- src/AudioToolbox/MusicSequence.cs
- src/AudioToolbox/MusicTrack.cs
- src/AudioToolbox/SystemSound.cs
This PR aims to bring nullability changes to <FRAMEWORK>.
> [audiotoolbox] Add nullability to (generated and manual) bindings

- tests/introspection/ApiCMAttachmentTest.cs
Fixes:
Introspection.ApiCMAttachmentTest
[FAIL] CheckFailAttachments : System.InvalidOperationException : Could not create the new instance for type CGEvent.
at Introspection.ApiCMAttachmentTest.GetINativeInstance(Type t) in xamarin-macios/tests/introspection/ApiCMAttachmentTest.cs:line 498
at Introspection.ApiCMAttachmentTest.CheckFailAttachments() in xamarin-macios/tests/introspection/ApiCMAttachmentTest.cs:line 572
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
> [introspection] Fix ApiCMAttachmentTest on macOS / Mac Catalyst.

- tests/monotouch-test/Foundation/UbiquitousKeyValueStoreTest.cs
Fixes:
MonoTouchFixtures.Foundation.NSUbiquitousKeyValueStoreTest
[FAIL] Indexer :   key 1
Expected: <value>
But was:  null
> [monotouch-test] Fix UbiquitousKeyValueStoreTest to work on newer versions of macOS.

- tests/monotouch-test/MediaAccessibility/ImageCaptioningTest.cs
Also improve assert messages a bit to not have multiple asserts with the same message.
> [monotouch-test] Adjust ImageCaptioningTest to work on older versions of macOS for Mac Catalyst.

- src/AudioUnit/AUGraph.cs
- src/AudioUnit/AUParameter.cs
- src/AudioUnit/AUScheduledAudioFileRegion.cs
- src/AudioUnit/AudioComponent.cs
- src/AudioUnit/AudioComponentDescription.cs
- src/AudioUnit/AudioUnit.cs
- src/AudioUnit/AudioUnitUtils.cs
- src/AudioUnit/ClassInfoDictionary.cs
- src/AudioUnit/ExtAudioFile.cs
This PR aims to bring nullability changes to AudioUnit.
> [audiounit] Add nullability to (generated and manual) bindings

- src/AuthenticationServices/ASAuthorization.cs
- src/AuthenticationServices/ASAuthorizationRequest.cs
- src/AuthenticationServices/PublicPrivateKeyAuthentication.cs
This PR aims to bring nullability changes to AuthenticationServices.
2. Changing any `== null` or `!= null` to `is null` and `is not null`
> [authenticationservices] Add nullability to (generated and manual) bindings

- .github/workflows/pwsh-ci.yml
- tools/devops/automation/scripts/APIDiff.Tests.ps1
- tools/devops/automation/scripts/APIDiff.psm1
The new module is not yet used. This is a first step, review the code, next create a PR in which the module is used. We add a yaml to have a github action ensuring the pwsh tests are run, that way we at least have a way to validate the pwsh used in the azure pipeline without using the pipeline.
> [CI] Separate API diff from the test comment to move running the tests in a diff agent.

- tools/apidiff/Makefile
- tools/devops/automation/scripts/bash/compare.sh
- tools/devops/automation/templates/build/api-diff.yml
Previously, if there were issues in the CI during the tools/apidiff Makefile rules, the CI would not report any errors/warnings in the CI overview. This makes it difficult to spot if there is an issue. This PR gives us orange warnings that are easier to spot in the CI overview as such:
> [ApiDiff] Let the CI show warnings when ApiDiff has make issues

- src/CallKit/CXProvider.cs
I am adding nullable enable to all manual files that are not "API_SOURCES" in src/frameworks.sources and making the required nullability changes. In this case, only one file does not have the header.
> [callkit] Add nullability to (generated and manual) bindings

- tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-ARKit.ignore
- tests/xtro-sharpie/xtro-sanity/Sanitizer.cs
It exists, but does nothing on Mac Catalyst.
"This framework ignores calls from Mac apps built with Mac Catalyst."
Ref: https://developer.apple.com/documentation/arkit?language=objc
Also augment xtro to not be confused when encountering lines starting with '#'
that has no other text.
> [ARKit] Ignore this framework on Mac Catalyst.

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/InstallNameToolTaskBase.cs
This fixes an issue where we'd create files on mac containing windows directory separators.
Ref: [Teams link](https://teams.microsoft.com/l/message/19:5b7decdb4a714a13bad3ff714961f6fe@thread.skype/1646345177907?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=0056f60b-301f-43ac-bbcf-f356d3c42c92&parentMessageId=1646159601280&teamName=VS%20Client%20Experiences&channelName=MaciOS%20%F0%9F%8D%8E&createdTime=1646345177907)
> [msbuild] Handle relative paths with wrong directory separator character for metadata passed to the InstallNameTool task.

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/InstallNameToolTaskBase.cs
This fixes an issue where we'd create files on mac containing windows directory separators.
Ref: [Teams link](https://teams.microsoft.com/l/message/19:5b7decdb4a714a13bad3ff714961f6fe@thread.skype/1646345177907?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=0056f60b-301f-43ac-bbcf-f356d3c42c92&parentMessageId=1646159601280&teamName=VS%20Client%20Experiences&channelName=MaciOS%20%F0%9F%8D%8E&createdTime=1646345177907)
Backport of #14302
> [release/6.0.2xx-preview14] [msbuild] Handle relative paths with wrong directory separator character for metadata passed to the InstallNameTool task.

- src/AddressBookUI/ABAddressFormatting.cs
- src/AddressBookUI/ABNewPersonViewController.cs
- src/AddressBookUI/ABPeoplePickerNavigationController.cs
- src/AddressBookUI/ABPersonViewController.cs
- src/AddressBookUI/ABUnknownPersonViewController.cs
- src/AddressBookUI/DisplayedPropertiesCollection.cs
- src/addressbookui.cs
This PR aims to bring nullability changes to AddressBookUI.
1. I am looking for any `!missing-null-allowed!` in this frameworks ignore files and applying them
2. I am adding `nullable enable` to all manual files that are not "API_SOURCES" in src/frameworks.sources and making the required nullability changes
3. Changing all `throw new ArgumentNullException ("object"));` to `ObjCRuntime.ThrowHelper.ThrowArgumentNullException (nameof (object));` for size saving optimization as well to mark that this framework contains nullability changes
4. Changing any `== null` or `!= null` to `is null` and `is not null`
*Note, I'd like extra focus on the DisplayedPropertiesCollection method changes
Inside …
> [addressbookui] Add nullability to (generated and manual) bindings

- tools/devops/automation/templates/build/build.yml
> [release/6.0.2xx-preview14] [CI] Ensure we have dotnet 3.x to be able to run ESRP.

- src/AddressBookUI/ABNewPersonViewController.cs
Landing https://github.com/xamarin/xamarin-macios/pull/14221 bronke main with the following nullability error:
```
AddressBookUI/ABNewPersonViewController.cs(95,82): warning CS8604: Possible null reference argument for parameter 'addressbook' in 'ABGroup.ABGroup(NativeHandle handle, ABAddressBook addressbook)'.
AddressBookUI/ABNewPersonViewController.cs(95,82): error CS8604: Possible null reference argument for parameter 'addressbook' in 'ABGroup.ABGroup(IntPtr handle, ABAddressBook addressbook)'.
```
This is because https://github.com/xamarin/xamarin-macios/pull/1422 was merged without being in sync with main, the lastests tests were ran 9 days before the PR was landed. Tests passed because ce24fe5f817171c747508ac60b55769cda5b6dcf was landed later and it enabled nullability in the …
> [AddressBookUI] Fix nullability compilation error.

- tools/devops/automation/build-pipeline.yml
- tools/devops/automation/templates/build/stage.yml
Provide an extra parameter that allows to choose the agent pool to be used for a manually triggered build. The UI will allow to select 3 possible values:
* automatic - Default, the pipeline will decide
* ci - Use the bot pool used for the CI
* pr - Use the bot pool dedicated for PRs
The following is the UI that will be shown in VSTS
> [CI] Allow to override the pool that will be used in a manual build.

- src/AppKit/NSColor.cs
- src/NativeTypes/Primitives.tt
- tests/monotouch-test/AppKit/NSColor.cs
Fix conversion between nfloat and [U]IntPtr to use a numeric conversion
instead of copying memory.
Otherwise things like this:
var number = (nint) (nfloat) 10;
Console.WriteLine (number);
yields:
0x4024000000000000
instead of:
0xa
> [nfloat] Fix conversion to and from [U]IntPtr.

- tools/devops/automation/templates/build/build.yml
This is needed to make the CI work
Backport of #14323
> [release/6.0.2xx-preview13] [CI] Ensure we have dotnet 3.x to be able to run ESRP.

- tests/monotouch-test/ObjCRuntime/DelegateAndDataSourceTest.cs
The default constructor doesn't work (it's already obsolete).
Fixes:
Xamarin.Mac.Tests.DelegateAndDataSourceTest
[FAIL] DelegateAndDataSourceAllowsNull : 1 failing types
1 failing types:
PassKit.PKPaymentAuthorizationViewController: Could not initialize an instance of the type 'PassKit.PKPaymentAuthorizationViewController': the native 'init' method returned nil.
It is possible to ignore this condition by setting ObjCRuntime.Class.ThrowOnInitFailure to false.
at Xamarin.Mac.Tests.DelegateAndDataSourceTest.DelegateAndDataSourceAllowsNull () [0x0026c] in /Users/builder/azdo/_work/1/s/xamarin-macios/tests/monotouch-test/ObjCRuntime/DelegateAndDataSourceTest.cs:90
> [tests] Don't try to create an instance of PKPaymentAuthorizationViewController.

- tests/monotouch-test/System.Net.Http/MessageHandlers.cs
Fixes two test failures on tvOS with all optimizations enabled:
MonoTests.System.Net.Http.MessageHandlerTest.DnsFailure
[FAIL] DnsFailure(System.Net.Http.SocketsHttpHandler) :   Exception
Expected: instance of <System.Net.Http.HttpRequestException>
But was:  <System.MissingMethodException: No parameterless constructor defined for type 'System.Net.Http.SocketsHttpHandler'.
at System.RuntimeType.CreateInstanceMono(Boolean , Boolean )
at System.RuntimeType.CreateInstanceDefaultCtor(Boolean , Boolean )
at System.Activator.CreateInstance(Type , Boolean , Boolean )
at System.Activator.CreateInstance(Type , Boolean )
at System.Activator.CreateInstance(Type )
at MonoTests.System.Net.Http.MessageHandlerTest.GetHandler(Type ) in /Users/builder/azdo/_work/1/s/xamarin-macios/tests/monotouch-test/Syste …
> [tests] Don't use reflection to create HttpClient handlers.

- msbuild/Xamarin.Shared/Xamarin.Shared.props
I think this is what makes most sense, since they're both desktop platforms.
> [msbuild] Make the default value for NoDSymUtil the same for Mac Catalyst as it is for macOS.

- dotnet/targets/Xamarin.Shared.Sdk.props
- dotnet/targets/Xamarin.Shared.Sdk.targets
- tests/dotnet/AppWithGenericLibraryReference/AppDelegate.cs
- tests/dotnet/AppWithGenericLibraryReference/Library/AppDelegate.cs
- tests/dotnet/AppWithGenericLibraryReference/Library/MacCatalyst/Library.csproj
- tests/dotnet/AppWithGenericLibraryReference/Library/MacCatalyst/Makefile
- tests/dotnet/AppWithGenericLibraryReference/Library/Makefile
- tests/dotnet/AppWithGenericLibraryReference/Library/iOS/Library.csproj
- tests/dotnet/AppWithGenericLibraryReference/Library/iOS/Makefile
- tests/dotnet/AppWithGenericLibraryReference/Library/macOS/Library.csproj
- tests/dotnet/AppWithGenericLibraryReference/Library/macOS/Makefile
- tests/dotnet/AppWithGenericLibraryReference/Library/shared.csproj
- tests/dotnet/AppWithGenericLibraryReference/Library/shared.mk
- tests/dotnet/AppWithGenericLibraryReference/Library/tvOS/Library.csproj
- tests/dotnet/AppWithGenericLibraryReference/Library/tvOS/Makefile
- tests/dotnet/AppWithGenericLibraryReference/MacCatalyst/AppWithGenericLibraryReference.csproj
- tests/dotnet/AppWithGenericLibraryReference/MacCatalyst/Makefile
- tests/dotnet/AppWithGenericLibraryReference/Makefile
- tests/dotnet/AppWithGenericLibraryReference/iOS/AppWithGenericLibraryReference.csproj
- tests/dotnet/AppWithGenericLibraryReference/iOS/Makefile
- tests/dotnet/AppWithGenericLibraryReference/macOS/AppWithGenericLibraryReference.csproj
- tests/dotnet/AppWithGenericLibraryReference/macOS/Makefile
- tests/dotnet/AppWithGenericLibraryReference/shared.csproj
- tests/dotnet/AppWithGenericLibraryReference/shared.mk
- tests/dotnet/AppWithGenericLibraryReference/tvOS/AppWithGenericLibraryReference.csproj
- tests/dotnet/AppWithGenericLibraryReference/tvOS/Makefile
- tests/dotnet/UnitTests/ProjectTest.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/13482.
> [dotnet] Only validate the RuntimeIdentifier if we need/use it. Fixes #13482.

- tests/common/TestRuntime.cs
- tests/monotouch-test/CoreVideo/CVDisplayLinkTest.cs
The new bots do not have a display and that makes certain mac tests
fail. Added a new TestRuntime function to let us know if we are on vsts
and ignore accordingly.
fixes https://github.com/xamarin/maccore/issues/2546
> [Tests] Ignore certain tests that do not longer work on bots.

- tests/xharness/Xharness.Tests/Jenkins/MarkdownReportWriterTests.cs
- tests/xharness/xharness.csproj
I don't expect anything changed since Nov 19th but there might be miniature API changes this week so want to bump now and then after.
> Bump Microsoft.DotNet.XHarness.iOS.Shared to `1.0.0-prerelease.22157.2`

- src/CoreServices/FSEvents.cs
- tests/monotouch-test/CoreServices/FSEventStreamTest.cs
Implements support for `FSEventStreamCreateFlags.UseExtendedData`, fixing #12007.
When `.UseExtendedData` is specified, the event data type changes from `CFString` to `CFDictionary`; the dictionary contains the path (`path` key) and inode (`fileID` key) information for the file and may be extended in the future with other fields. Previously this was crashing because we assumed `CFString` always.
Further add a convenience constructor for monitoring a single path, add the missing `UnscheduleFromRunLoop` APIs, and add `SetDispatchQueue` to allow using dispatch queues directly instead of run loops.
Finally, this PR adds a fairly exhaustive file system test which covers the existing (non-extended) and fixed (extended) creation modes, along with using a dispatch queue instead of run loop.
Fixes …
> FSEventStream: fix crash when asking for extended data; support dispatch queues (#12007)

- msbuild/Xamarin.MacDev.Tasks.Core/LoggingExtensions.cs
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CodesignTaskBase.cs
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/LinkNativeCodeTaskBase.cs
- msbuild/Xamarin.MacDev.Tasks/Tasks/LinkNativeCode.cs
- tools/common/PathUtils.cs
This fixes an issue where we'd do logic with Windows-style paths on macOS, and that's
never the right thing to do.
For the LinkNativeCode task, this would manifest as this error when building from windows:
> ld: file too small (length=0) file 'obj/Debug/net6.0-ios/iossimulator-x64/nativelibraries/libSystem.Native.dylib' for architecture x86_64
because the 'ShouldCopyToBuildServer' method would return incorrect results.
For the Codesign task, it would manifest as an exception trying to create a
directory with an empty string (because the directory name of a windows-style
path is an empty string on macOS).
Since this exception was quite useless (just getting the exception message
didn't tell me much about what caused the exception, because it had no stack
trace information), I've also …
> [release/6.0.2xx-preview14] [msbuild] Fix a few paths to have consistently macOS paths.

- msbuild/Xamarin.MacDev.Tasks.Core/LoggingExtensions.cs
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CodesignTaskBase.cs
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/LinkNativeCodeTaskBase.cs
- msbuild/Xamarin.MacDev.Tasks/Tasks/LinkNativeCode.cs
- tools/common/PathUtils.cs
This fixes an issue where we'd do logic with Windows-style paths on macOS, and that's
never the right thing to do.
For the LinkNativeCode task, this would manifest as this error when building from windows:
> ld: file too small (length=0) file 'obj/Debug/net6.0-ios/iossimulator-x64/nativelibraries/libSystem.Native.dylib' for architecture x86_64
because the 'ShouldCopyToBuildServer' method would return incorrect results.
For the Codesign task, it would manifest as an exception trying to create a
directory with an empty string (because the directory name of a windows-style
path is an empty string on macOS).
Since this exception was quite useless (just getting the exception message
didn't tell me much about what caused the exception, because it had no stack
trace information), I've also …
> [msbuild] Fix a few paths to have consistently macOS paths.

- src/CoreServices/FSEvents.cs
- src/Foundation/NSArray.cs
- tests/monotouch-test/CoreServices/FSEventStreamTest.cs
Introduce `FSEventStreamCreateOptions` to avoid a slew of .ctor overrides, and make it easier to specify `DeviceToWatch` and `SinceWhenId`. `SinceWhenId` was previously only exposed on the "low level" .ctor, and it's a rather important parameter for supporting events that may have happened while the application was not running.
Make the existing constructors wrap `FSEventStreamCreateOptions` to avoid API break.
This is a followup to #14318. When using device-relative watches, files can be tracked via a tuple of their device ID and inode instead of paths. #14318 exposes inode data on `FSEvent`.
> FSEventStream: bind FSEventStreamCreateRelativeToDevice, FSEventStreamGetDeviceBeingWatched

- tools/devops/automation/templates/common/setup.yml
- tools/devops/automation/templates/mac/build.yml
If we have an issue unlocking the UI prompt we continue on error. This
is considered a warning in the pipeline, but doing so teaches users to
ignore warnings and will result in us ignoring real actual issues.
Setting the step to not have a warning will ensure that we only see
warnings that we care about.
> [CI] Do not show a warning if we cannot disable the lock screen.

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CodesignTaskBase.cs
Fixes this build failure:
1>/Users/<user>/Library/Caches/Xamarin/mtbs/builds/MauiApp16/SessionId/obj\Debug\net6.0-ios\ios-arm64\device-builds\iphone14.5-15.2.1\Entitlements.xcent: cannot read entitlement data
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.117\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error : /usr/bin/codesign exited with code 1
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.117\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error :
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.117\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error : Failed to codesign '/Users/<user>/Library/Caches/Xamarin/mtbs/builds/MauiApp16/SessionId/bin/Debug/net6.0-ios/ios-arm64/device-builds/iphone14.5-15.2.1/MauiAp …
> [msbuild] Make sure to not use windows-style paths for resource rules and entitlements.

- dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalyst/AppDelegate.cs
- dotnet/Templates/Microsoft.iOS.Templates/ios/AppDelegate.cs
The .NET 6 Mac Catalyst and iOS templates have a default of a white background and the text has no mask. That makes the text impossible to see if you're using dark mode (since the label will be white, making the whole screen white) and, since it has no mask, it will stay static in position on the screen even if you rotate or change the window size, depending on the platform.
This updates the templates to get rid of the default white background (or it should use whatever the system has) which fixes the text issue, and adds an `AutoresizingMask` to the label so it will always be centered.
> Update code-behind templates to correctly support Dark Mode, bind text to the center of the screen.

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CodesignTaskBase.cs
Fixes this build failure:
1>/Users/<user>/Library/Caches/Xamarin/mtbs/builds/MauiApp16/SessionId/obj\Debug\net6.0-ios\ios-arm64\device-builds\iphone14.5-15.2.1\Entitlements.xcent: cannot read entitlement data
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.117\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error : /usr/bin/codesign exited with code 1
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.117\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error :
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.117\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error : Failed to codesign '/Users/<user>/Library/Caches/Xamarin/mtbs/builds/MauiApp16/SessionId/bin/Debug/net6.0-ios/ios-arm64/device-builds/iphone14.5-15.2.1/MauiAp …
> [release/6.0.2xx-preview14] [msbuild] Make sure to not use windows-style paths for resource rules and entitlements.

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DittoTaskBase.cs
For reasons I don't quite understand, ditto might fail when executed by XMA:
Target Name=_CopyDirectoriesToBundle Project=C:\Users\rolf\source\iOSApp4\iOSApp4.csproj
Building target "_CopyDirectoriesToBundle" completely.
Output file "bin\Debug\net6.0-ios\iossimulator-x64\publish\..\device-builds\iphone11.6-14.8.1\iOSApp4.app\\Frameworks\\ArcGIS-arm64.framework/ArcGIS-arm64" does not exist.
Output file "bin\Debug\net6.0-ios\iossimulator-x64\publish\..\device-builds\iphone11.6-14.8.1\iOSApp4.app\\Frameworks\\Runtimecore.framework/Runtimecore" does not exist.
Ditto
Assembly = C:\Users\rolf\source\maui\bin\dotnet\packs\Microsoft.iOS.Sdk\15.2.303-ci.ditto-windows.56\tools\msbuild\iOS\..\iOS\Xamarin.iOS.Tasks.dll
Parameters
Destination = …
> [msbuild] Pass full paths to 'ditto'.

- src/CFNetwork/CFHTTPAuthentication.cs
- src/CFNetwork/CFHTTPMessage.cs
- src/CFNetwork/CFHTTPStream.cs
The last cfnetwork PR found [here](https://github.com/xamarin/xamarin-macios/pull/14341) included adding `#nullable enable` and nullability changes to files that are !Net. This enabled Warnings as Errors and included other async and await changes that were not easy to test at the moment.
Thus, this PR does not edit files that are !Net and just brings over the better error throwing changes!
> [cfnetwork] Add nullability to (generated and manual) bindings - Version 2

- tools/devops/automation/templates/build/build.yml
- tools/devops/automation/templates/tests/build.yml
- tools/devops/automation/templates/tests/run-tests.yml
Or make files canculate the version of the nuget based on the hash of
the source, because VSTS does a merge of the branhc rather than checking
out, the version calculated in the tests bot via de makefiles is
different to the one that was used in the build bots.
We solve this by creating the rollback file at build time so that it is
consumed by the test bot.
> [CI] Build the rollback file in the build bot.

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DittoTaskBase.cs
For reasons I don't quite understand, ditto might fail when executed by XMA:
Target Name=_CopyDirectoriesToBundle Project=C:\Users\rolf\source\iOSApp4\iOSApp4.csproj
Building target "_CopyDirectoriesToBundle" completely.
Output file "bin\Debug\net6.0-ios\iossimulator-x64\publish\..\device-builds\iphone11.6-14.8.1\iOSApp4.app\\Frameworks\\ArcGIS-arm64.framework/ArcGIS-arm64" does not exist.
Output file "bin\Debug\net6.0-ios\iossimulator-x64\publish\..\device-builds\iphone11.6-14.8.1\iOSApp4.app\\Frameworks\\Runtimecore.framework/Runtimecore" does not exist.
Ditto
Assembly = C:\Users\rolf\source\maui\bin\dotnet\packs\Microsoft.iOS.Sdk\15.2.303-ci.ditto-windows.56\tools\msbuild\iOS\..\iOS\Xamarin.iOS.Tasks.dll
Parameters
Destination = …
> [release/6.0.2xx-preview14] [msbuild] Pass full paths to 'ditto'.

- msbuild/Xamarin.MacDev.Tasks/Tasks/Ditto.cs
Possible fix for https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1492635
If the `ITaskItem` input property of the task is a folder path, the `TaskRunner` doesn't know how to copy the folder content to Mac. Let's use the `GetAdditionalItemsToBeCopied` method to tell the `TaskRunner` to copy all the folder content to Mac.
Backport of #14375
> [release/6.0.2xx-preview14] [DittoTask] If Source is a folder, add all its content as ITaskItem

- msbuild/Xamarin.Shared/Xamarin.Shared.props
There's no reason to spend time running 'strip' or 'dsymutil' for simulator builds,
so default to not doing it.
> [msbuild] Disable native strip + dsymutil for simulator builds by default.

- tools/devops/automation/build-pipeline.yml
- tools/devops/automation/templates/build/stage.yml
Provide an extra parameter that allows to choose the agent pool to be used for a manually triggered build. The UI will allow to select 3 possible values:
* automatic - Default, the pipeline will decide
* ci - Use the bot pool used for the CI
* pr - Use the bot pool dedicated for PRs
The following is the UI that will be shown in VSTS
Backport of #14320
> [release/6.0.2xx-preview14] [CI] Allow to override the pool that will be used in a manual build.

- src/generator.cs
- tests/generator/tests/nativeenum.cs
Fixes NRE in GetNativeEnumToManagedExpression when a native enum
with MaxValue is used on delegates.
> [generator] Avoid NRE when using native enums on delegates

- dotnet/Templates/Microsoft.iOS.Templates/ios-controller/.template.config/localize/templatestrings.en.json
When adding support for localizing template strings, this wasn't included
because it was merged after the template localization work started.
> [dotnet] Update template strings.

- tests/common/mac/ProjectTestHelpers.cs
- tests/mmptest/src/NativeReferencesTests.cs
- tests/msbuild/Xamarin.MacDev.Tests/MSBuild-Smoke.cs
Use already existing logic in the Configuration class to find files on disk.
Also remove some dead code and use Path.Combine instead of string
concatenation to compute paths.
Fixes https://github.com/xamarin/maccore/issues/2553.
> [tests] Simplify some logic in mmptest and msbuild tests.

- tools/devops/automation/templates/build/stage.yml
The build steps do not longer run tests which resulted in the api diff not uploading.
> [CI] Re-enable the upload of the api diff.

- tools/devops/automation/build-pipeline.yml
The infra teams are working on the devices which results in no bots with a device. This ends up making the jobs wait for ever.
Backport of #14353
> [release/6.0.2xx-preview13] [CI] Disable the device tests until we have sorted out the pipeline pool.

- msbuild/Directory.Build.props
This should fix a bug where Hot Restart doesn't work with net6 because of a strong naming exception on build time
> Updated Messaging and Hot Restart versions

- tests/Makefile
The advantage of writing the label after each test is that the test result will also
be printed, which means it's possible to see if any tests failed during the test
run, as opposed to having to wait until the entire test run is completed (which can
take a while) to realize that pretty much every test failed with some silly mistake
which could have been quickly fixed before re-running the tests.
> [tests] Print labels after each MSBuild test when running from the command line.

- Make.config
Because that's what Xcode 13.3 requires.
> Bump the min macOS version to 12.0.

- tests/Makefile
- tests/xharness/AppBundleLocator.cs
- tests/xharness/Harness.cs
This makes it line up with our other make variables (SYSTEM_MSBUILD,
SYSTEM_MONO, SYSTEM_CSC, etc.), and also prepares for removing the version
from the DOTNET6 variable (so that it becomes just DOTNET).
> [dotnet] Rename the DOTNET make variable to SYSTEM_DOTNET.

- tests/common/TestRuntime.cs
Fixes https://github.com/xamarin/maccore/issues/2557.
> [tests] Augment TestRuntime.IgnoreInCI to detect Azure DevOps. Fixes #2557.

- tests/dotnet/UnitTests/AssetsTest.cs
Ref: https://github.com/xamarin/maccore/issues/2559
> [tests] Add better diagnostics for failure to parse json document in AssetTest.
