dotnet/macios

mk/xamarin.mk

* xamarin/maccore@8287d19786 [submission] Only be optionally quiet.
* xamarin/maccore@5fe27fdd36 [submission] Add makefile target to add all the certs.
* xamarin/maccore@98670dcf31 [submission] Write results as tests are executed.
Diff: https://github.com/xamarin/maccore/compare/696db0a953d62adc90cfbeaf42ebd1c901e7276b..8287d1978617996f5a0f1c83c9264cc582c957fe
Backport of #14417

[xcode13.3] Bump maccore.

---

tools/Makefile
tools/nnyeah/Makefile

Adding the needed Makefile and the dir to the parent one so that the
tool is also built in the CI.

[nnyeah] Add tool to be made via makefiles.

---

CODEOWNERS

Yeah Steve!

---

dotnet/DefaultCompilationIncludes.md
dotnet/targets/Microsoft.Sdk.DefaultItems.template.props
tests/dotnet/BundleStructure/MacCatalyst/Resources/ResourceClass.cs
tests/dotnet/BundleStructure/MacCatalyst/Resources/Welcome.resx
tests/dotnet/BundleStructure/iOS/Resources/ResourceClass.cs
tests/dotnet/BundleStructure/iOS/Resources/Welcome.resx
tests/dotnet/BundleStructure/macOS/Resources/ResourceClass.cs
tests/dotnet/BundleStructure/macOS/Resources/Welcome.resx
tests/dotnet/BundleStructure/tvOS/Resources/ResourceClass.cs
tests/dotnet/BundleStructure/tvOS/Resources/Welcome.resx

Fixes https://github.com/xamarin/xamarin-macios/issues/14442.

[dotnet] Don't include @(Compile) and @(EmbeddedResource) items in @(BundleResource) items by default. Fixes #14442.

---

msbuild/Directory.Build.props

Previous PR has been automatically closed and not merged so opening this new one
Backport of #14569

[release/6.0.3xx-rc1] Updated Xamarin.Messaging to 1.5.24

---

msbuild/Directory.Build.props

Previous PR has been automatically closed and not merged so opening this new one

Updated Xamarin.Messaging to 1.5.24

---

src/Security/Items.cs

It seems this SecItem key was missed, so implement it.

[Security] Expose kSecurityUseDataProtectionKeychain in the SecRecord class.

---

msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CodesignTaskBase.cs

When XVS creates output/stamp files on Windows, the paths must be relative,
because otherwise XVS will append the full macOS path to the current Windows
directory and get garbage.
XVS also expects only files as output, so don't return any directories.
Fixes part of https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1505990/.

[msbuild] Make codesigned output files relative, and don't list directories.

---

msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileAppManifestTaskBase.cs
msbuild/Xamarin.iOS.Tasks.Core/Tasks/CompileAppManifestTaskCore.cs

* Move logic to validate the UIDeviceFamily value to shared code.
* Remove logic related to watchOS 1 apps, it's been dead for a while.
* Change logic to not overwriting any existing UIDeviceFamily values in the customer's
Info.plist.
This makes the code more platform-agnostic and easier to work with across all platforms
(such as adding new validations).

[msbuild] Move logic to validate the UIDeviceFamily to shared code in the CompileAppManifest task.

---

src/uikit.cs
tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-UIKit.todo
tests/xtro-sharpie/api-annotations-dotnet/iOS-UIKit.ignore
tests/xtro-sharpie/api-annotations-dotnet/tvOS-UIKit.ignore
tests/xtro-sharpie/iOS-UIKit.ignore
tests/xtro-sharpie/tvOS-UIKit.ignore

- Fixes https://github.com/xamarin/xamarin-macios/issues/14646
- I checked UIDocument and AppKit versions and those are not nullable.

Add nullability on one UndoManager API

---

tools/devops/automation/templates/build/api-diff-stage.yml
tools/devops/automation/templates/build/build-stage.yml
tools/devops/automation/templates/build/build.yml

Because we moved the tests to a diff job, the variables were missing.

[CI] Fix variables to show the correct bot in the comments.

---

tools/devops/automation/scripts/GitHub.psm1
tools/devops/automation/templates/build/api-diff-github-comment.yml
tools/devops/automation/templates/build/api-diff-stage.yml
tools/devops/automation/templates/build/artifact-github-comment.yml
tools/devops/automation/templates/build/build-stage.yml
tools/devops/automation/templates/build/build.yml

Add the hash of the project in the comment footer so that we can know
what we did build. Later we can use this to filter outdated comments.

[CI] Add the hash that was used to build in the commit.

---

.github/workflows/pwsh-ci.yml
tools/devops/automation/scripts/APIDiff.Tests.ps1
tools/devops/automation/scripts/Artifacts.Tests.ps1
tools/devops/automation/scripts/GitHub.Tests.ps1
tools/devops/automation/scripts/MLaunch.Tests.ps1
tools/devops/automation/scripts/StaticPages.Tests.ps1
tools/devops/automation/scripts/System.Tests.ps1
tools/devops/automation/scripts/VSTS.Tests.ps1

Older tests that broke during the EO have been skipped and will fix in a diff commit, fixing tests is not the scope of the change.

[CI] Improve the action used to run tests on the pwsh.

---

tools/devops/automation/templates/build/api-diff.yml

Similar to https://github.com/xamarin/xamarin-macios/pull/14745 but for the other api diff.

[CI] Add a status for the API diff from stable.

---

tools/devops/automation/templates/loc-translations.yml

We cannot push with a https remote in a EO compliant vm, this solves the issue.

[CI] Fix the push to the localization branch.

---

tests/dotnet/MySimpleApp/shared.mk

This way the 'make run' target in this project knows what to run.

[tests] Set the test name for the MySimpleApp test project.

---

.github/fabricbot_readme.md

Copied from https://github.com/dotnet/maui/blob/main/.github/fabricbot_readme.md.

Add fabricbot readme.

---

tests/xharness/Jenkins/TestTasks/TestTask.cs

We are going to be changing code in xharness. Is a good time to clean
thigns a little, make code more modern then enable nullability.
Try to get as much help from the new features and try to clean alittle
debt we have from the last time we moved code.

[Xharness] Clean test task code.

---

tests/xharness/Jenkins/TestTasks/AggregatedRunSimulatorTask.cs

Cleaning up xharness before new features are added.

[Xharness]Enable nullability and update C# to new code patterns.

---

tools/nnyeah/nnyeah/Errors.Designer.cs
tools/nnyeah/nnyeah/Errors.resx
tools/nnyeah/nnyeah/Program.cs

I had trouble figuring out what arguments the integration test was missing before looking at the source/asking.

[Nnyeah] Improve error messages for missing required arguments

---

tests/mtouch/Cache.cs

Following my comments here: https://github.com/xamarin/xamarin-macios/pull/14913/files

[Tools] Enable nullability on Cache.cs.

---

.github/workflows/maestro-changelog.yml

And add that changelog as a comment to the PR. If there already is a comment
with a changelog, then update that comment instead.

[actions] Add GitHub action to compute the changelog for maestro bumps.

---

tools/devops/automation/scripts/GitHub.psm1

This way we don't run into rate limits as easily.

[devops] Authenticate requests to GitHub.

---

msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.cs.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.de.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.es.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.fr.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.it.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ja.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ko.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pl.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pt-BR.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ru.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.tr.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hans.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hant.resx
tools/mtouch/TranslatedAssemblies/Errors.cs.resx
tools/mtouch/TranslatedAssemblies/Errors.de.resx
tools/mtouch/TranslatedAssemblies/Errors.es.resx
tools/mtouch/TranslatedAssemblies/Errors.fr.resx
tools/mtouch/TranslatedAssemblies/Errors.it.resx
tools/mtouch/TranslatedAssemblies/Errors.ja.resx
tools/mtouch/TranslatedAssemblies/Errors.ko.resx
tools/mtouch/TranslatedAssemblies/Errors.pl.resx
tools/mtouch/TranslatedAssemblies/Errors.pt-BR.resx
tools/mtouch/TranslatedAssemblies/Errors.ru.resx
tools/mtouch/TranslatedAssemblies/Errors.tr.resx
tools/mtouch/TranslatedAssemblies/Errors.zh-Hans.resx
tools/mtouch/TranslatedAssemblies/Errors.zh-Hant.resx

Localized file check-in by OneLocBuild Task: Build definition ID 14411: Build ID 6156518

---

tools/nnyeah/tests/integration/IntegrationExamples.cs

- Also do a brief rename GetNETPlatform -> GetNetPlatform suggested in last PR

[nnyeah] Optionally run integration test nnyeah in-process

---

tools/nnyeah/Makefile
tools/nnyeah/tests/integration/IntegrationExamples.cs

- I also removed Makefile from the dependencies of the library as it was causing rebuilds every time unnecessarily (unsure why)

[nnyeah] Integration tests run against dotnet tool from nupkg

---

tools/nnyeah/integration/API/IntegrationAPI.cs
tools/nnyeah/integration/Consumer/Consumer.cs
tools/nnyeah/tests/unit/CompileALibrary.cs

Added tests for boolean operations on nint/nuint/nfloat
Had to ignore a test that was triggered code that @chamons is working on

[nnyeah] added tests for boolean operators

---

tools/nnyeah/integration/API/IntegrationAPI.cs

Added more tests for implicit operators.

[nnyeah] implicit operator tests

---

tools/nnyeah/integration/Consumer/Consumer.cs

Dear Steve, make sure you actually invoke the code.

[nnyeah] added missing test invocations

---

tests/xharness/AppRunner.cs

I don't remember why I excluded watch apps, and it seems to work locally, so
let's see how it goes. Hopefully we'll get better diagnostics when something
goes wrong.

[xharness] Redirect stdout/stderr for watch apps.

---

tools/devops/automation/build-pull-request.yml
tools/devops/automation/templates/main-stage.yml
tools/devops/automation/templates/sign-and-notarized/setup.yml
tools/devops/automation/templates/sign-and-notarized/sign-and-notarized.yml
tools/devops/automation/templates/variables.yml
tools/devops/automation/templates/vsts-variables.yml

Create two diff pipelines, one for CI and the other one for PRs. All code is shared except the default parameter values (we cannot share that).

[CI] Split the pipeline in two, one for CI and a second one for PRs.

---

tools/devops/automation/build-pull-request.yml

[net7.0] [CI] Allow to build PRs agains net* branches.

---

src/CoreFoundation/CFProxySupport.cs

[net7.0] [CI] Fix credscan false positive.

---

tools/devops/automation/build-pull-request.yml
tools/devops/automation/templates/build/sign-and-notarized.yml
tools/devops/automation/templates/common/setup.yml

Bring the minimun amount of changes needed to be able to build the
release/6.0.0.3xx branch.

[CI] Backport changes need to trigger builds for PRs.

---

tests/introspection/ApiProtocolTest.cs
tests/introspection/Mac/MacApiProtocolTest.cs
tests/introspection/Mac/MacApiSelectorTest.cs
tests/introspection/iOS/iOSApiProtocolTest.cs

This is a backport of #15230 and #15265.

[release/6.0.4xx] [tests] Backport a few introspection fixes.

---

tools/nnyeah/integration/API/IntegrationAPI.cs
tools/nnyeah/integration/Consumer/Consumer.cs

Needed to do a check to ensure that private classes get processed and processed correctly. Yup and yup.

[nnyeah] test for private classes fixing #15223

---

tools/devops/automation/scripts/GitHub.psm1
tools/devops/automation/templates/build/api-diff-process-results.yml

Ensure that the comments use the correct url. We had two issues:
1. We did not use $this.Hash when we had it.
2. We used the wrong vsts env var on CI.

[CI] Fix api diff comment

---

tools/devops/automation/templates/tests/run-tests.yml

The step takes time and it will be ignored unless we need to debug the
bots/pipeline.

[CI] Just collect sim logs on debug.

---

tools/devops/automation/scripts/VSTS.psm1
tools/devops/automation/scripts/bots-info.ps1

We have several issues with reports. VSTS UI is not very good at this,
yet we do the scripts to take care of it. Added a script that allows to
show all the bots based on a capability.
Example
```
pwsh bots-info.ps1 -Token "$YOURTOKEN" -PoolName "VSEng-Xamarin-RedmondMacBuildPool-iOS-Untrusted" -Capability "XcodeChannel"
```
Output:
```
VSEng-Xamarin-RedmondMacBuildPool-iOS-Untrusted bots:
Name: BOT-0189.Catalina; XcodeChannel=Stable
Name: BOT-0202.Catalina; XcodeChannel=Stable
Name: XAMBOT-1098.Monterey; XcodeChannel=Beta
Name: XAMBOT-1104.Monterey; XcodeChannel=Beta
Name: XAMBOT-1042.Monterey; XcodeChannel=Beta
Name: XAMBOT-1043.Monterey; XcodeChannel=Beta
Name: XAMBOT-1108.Monterey; XcodeChannel=Beta
Name: XAMBOT-1107.Monterey; XcodeChannel=Beta
Name: XAMBOT-1109.Monterey; …
```

[CI] Provide a script to help when doing bot reports.

---

tools/devops/automation/templates/tests/stage.yml

[xcode14] [CI] Change logic to take into account that CI has no labels.

---

tools/devops/automation/build-pipeline.yml
tools/devops/automation/build-pull-request.yml
tools/devops/automation/templates/build/api-diff-stage.yml
tools/devops/automation/templates/build/build-stage.yml
tools/devops/automation/templates/tests/stage.yml

[release/6.0.4xx] [CI] Add support to choose the xcodeChannel to be used.

---

runtime/monotouch-debug.m

This has been dead code for over 9 years!

[runtime] Remove dead code.

---

src/CoreMedia/CMSync.cs

fixes https://github.com/xamarin/xamarin-macios/issues/15530

[CoreMedia] Fix xtro for xcode 14.

---

tests/xtro-sharpie/api-annotations-dotnet/tvOS-CoreText.ignore

Issue for fixed in https://github.com/xamarin/xamarin-macios/pull/15552

[Xtro] Clean file that was missed due to xtro bug.

---

src/CoreText/CTFont.cs
tests/xtro-sharpie/api-annotations-dotnet/tvOS-CoreText.ignore

Add missint attrs to fix https://github.com/xamarin/maccore/issues/2607

[Xcode14] Add missing availability on dotnet. fixes #2607

---

tools/devops/automation/templates/build/build-pkgs.yml
tools/devops/automation/templates/common/teardown.yml
tools/devops/automation/templates/tests/build.yml

[xcode14] [CI] Make sure we do not have pkgs from other builds.

---

Make.config
NuGet.config
eng/Version.Details.xml
eng/Versions.props

We had a bunch of conflicting CI changes, I just took Xcode14 as the source of truth for those.

[xcode14] Merge release/6.0.400 into xcode14

---

dotnet/targets/Microsoft.Sdk.DefaultItems.template.props

Just happened to come across this when reading through the targets. Been duplicated for 2 years it looks like so 🤷

Remove duplicated SceneKitAsset declarations

---

Make.config

[xcode14] Bump to Xcode 14 Beta 6

---

configure

This way we can enable/disable each platform separately (at least for .NET).

[configure] Treat each platform separately.

---

tools/devops/automation/templates/sign-and-notarized/setup.yml

[net7.0] [CI] Bump microbuild.

---

tools/devops/automation/templates/sign-and-notarized/setup.yml

[xcode14] [CI] Bump microbuild.

---

src/wkwebkit.cs
tests/xtro-sharpie/api-annotations-dotnet/common-WebKit.ignore
tests/xtro-sharpie/common-WebKit.ignore

[WebKit] Added missing properties related to UIKit

---

tools/devops/automation/scripts/bash/collect-and-upload-crash-reports.sh

Fix echo command so that the text to be printed isn't interpreted as a
comment.
Really everything should be quoted in bash :/

[devops] Fix echo command that prints a comment.

---

runtime/monovm-bridge.m

This reverts commit f7bb07efc0ea36f298eb9bed14f453542c9fcf4d.
This workaround is no longer needed, since the dotnet/runtime hash we're using
contains this fix.
Fixes https://github.com/xamarin/xamarin-macios/issues/15585.

Revert "[debugger] Work around a debugger issue when using the interpreter.". Fixes #15585.

---

tools/devops/automation/scripts/TestResults.Tests.ps1

$Env:PWD doesn't seem to work on the bots, so try something else.

[devops] Fix tests.

---

tools/devops/automation/templates/tests/publish-html.yml

Even if it's just to say we couldn't compute a test summary.

[devops] Always send off a test summary.

---

src/CoreMedia/CMBufferQueue.cs
src/CoreMedia/CMCustomBlockAllocator.cs
src/CoreMedia/CMSampleBuffer.cs

Only out of band change - I changed the sense of `is null` to `is not null` because it removes the casts and cleans up the code.

[.NET/CoreMedia] Use [UnmanagedCallersOnly] instead of [MonoPInvokeCallback] Partial Fix for #10470

---

src/foundation.cs
tests/xtro-sharpie/api-annotations-dotnet/macOS-Foundation.todo
tests/xtro-sharpie/macOS-Foundation.todo

- Fixes https://github.com/xamarin/xamarin-macios/issues/15932

[foundation] Add lowPowerModeEnabled to macOS

---

tools/devops/automation/scripts/bash/generate-workload-rollback.sh
tools/devops/automation/templates/build/build-pkgs.yml
tools/devops/automation/templates/tests/run-tests.yml

Also move bash code from yml to a .sh file for easier reading, writing and
debugging.

[devops] Only add platforms we're building for into WorkloadRollback.json.

---

tools/devops/automation/scripts/TestResults.Tests.ps1

Fix tests after latest changes (in 5902c865b7ea5c33aa70d354a42bd01069878814).

[devops] Fix tests after latest changes.

---

.github/workflows/autoformat.yml
tests/cecil-tests/AttributeTest.cs
tests/cecil-tests/GenericPInvokes.cs
tests/cecil-tests/Helper.cs
tests/cecil-tests/Test.cs
tests/common/Configuration.cs
tests/common/ExecutionHelper.cs
tests/common/Profile.cs
tests/mtouch/Cache.cs
tools/common/ApplePlatform.cs
tools/common/TargetFramework.cs

All other changes should be whitespace only (https://github.com/xamarin/xamarin-macios/pull/16103/files?w=1).

Autoformat cecil-tests.csproj.

---

tools/common/Frameworks.cs

Fixes https://github.com/xamarin/xamarin-macios/issues/16084

[ShareWithYou] Fix linker problem due to a bad yy. Fixes #16084

---

tools/common/Frameworks.cs

Fixes https://github.com/xamarin/xamarin-macios/issues/16084
Backport of #16137

[net7.0-xcode14] [ShareWithYou] Fix linker problem due to a bad yy. Fixes #16084

---

tools/common/Frameworks.cs

Fixes https://github.com/xamarin/xamarin-macios/issues/16084
Backport of #16137

[release/7.0.1xx-xcode14-rc2] [ShareWithYou] Fix linker problem due to a bad yy. Fixes #16084

---

tools/common/Frameworks.cs

Fixes https://github.com/xamarin/xamarin-macios/issues/16084
Backport of #16137

[xcode14.1] [ShareWithYou] Fix linker problem due to a bad yy. Fixes #16084

---

dotnet/Workloads/vs-workload.template.props

Also only include platforms we're shipping from this branch.

[7.0.1xx-rc2] Make the vsman's target name unique for this branch.

---

dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalyst/.template.config/localize/templatestrings.en.json
dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalyst/.template.config/template.json
dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalystbinding/.template.config/localize/templatestrings.cs.json
dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalystbinding/.template.config/localize/templatestrings.de.json
dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalystbinding/.template.config/localize/templatestrings.en.json
dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalystbinding/.template.config/localize/templatestrings.es.json
dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalystbinding/.template.config/localize/templatestrings.fr.json
dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalystbinding/.template.config/localize/templatestrings.it.json
dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalystbinding/.template.config/localize/templatestrings.ja.json
dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalystbinding/.template.config/localize/templatestrings.ko.json
dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalystbinding/.template.config/localize/templatestrings.pl.json
dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalystbinding/.template.config/localize/templatestrings.pt-BR.json
dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalystbinding/.template.config/localize/templatestrings.ru.json
dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalystbinding/.template.config/localize/templatestrings.tr.json
dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalystbinding/.template.config/localize/templatestrings.zh-Hans.json
dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalystbinding/.template.config/localize/templatestrings.zh-Hant.json
dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalystbinding/.template.config/template.json

This increases the consistency with how other templates are named.

[dotnet] Improve name and descripting in a few existing templates a little bit.

---

DOWNLOADS.md
tools/list-xamarin-versions.csharp

Also fix the script that computes DOWNLOADS.md to actually use the correct
DOWNLOADS.md location.

Update DOWNLOADS.md with new releases.

---

msbuild/Directory.Build.props
msbuild/Xamarin.MacDev.Tasks/Tasks/BTouch.cs
msbuild/Xamarin.MacDev.Tasks/Tasks/CreateBindingResourcePackage.cs
msbuild/Xamarin.MacDev.Tasks/Tasks/PackLibraryResources.cs
msbuild/Xamarin.MacDev.Tasks/Tasks/PrepareNativeReferences.cs

[release/6.0.4xx-xcode14] Updated Xamarin.Messaging to 1.8.6

---

msbuild/Directory.Build.props
msbuild/Xamarin.MacDev.Tasks/Tasks/BTouch.cs
msbuild/Xamarin.MacDev.Tasks/Tasks/CreateBindingResourcePackage.cs
msbuild/Xamarin.MacDev.Tasks/Tasks/PackLibraryResources.cs
msbuild/Xamarin.MacDev.Tasks/Tasks/PrepareNativeReferences.cs

[release/7.0.1xx-xcode14-rc2] Updated Xamarin.Messaging to 1.8.6

---

tools/devops/.yamllint.yml
tools/devops/Makefile
tools/devops/automation/build-cronjob.yml
tools/devops/automation/build-pipeline.yml
tools/devops/automation/build-pull-request.yml
tools/devops/automation/templates/build/api-diff-build-and-detect.yml
tools/devops/automation/templates/build/build-nugets.yml
tools/devops/automation/templates/build/build-pkgs.yml
tools/devops/automation/templates/common/checkout.yml
tools/devops/automation/templates/common/mac-agent-logs.yml
tools/devops/automation/templates/mac/build.yml
tools/devops/automation/templates/main-stage.yml
tools/devops/automation/templates/release/vs-insertion-prep.yml
tools/devops/automation/templates/sign-and-notarized/artifact-github-comment.yml
tools/devops/automation/templates/sign-and-notarized/dotnet-signing.yml
tools/devops/automation/templates/sign-and-notarized/setup.yml
tools/devops/automation/templates/sign-and-notarized/upload-azure.yml
tools/devops/automation/templates/tests/run-tests.yml
tools/devops/automation/templates/tests/stage.yml
tools/devops/automation/templates/variables.yml
tools/devops/automation/templates/vsts-variables.yml
tools/devops/automation/templates/windows/build.yml

Also fix all our yaml files according to yamllint. This is mostly whitespace changes.
To review without whitespace changes: https://github.com/xamarin/xamarin-macios/pull/16298/files?diff=split&w=1

[devops] Add a makefile target to run yamllint on our yaml files.

---

src/ObjCRuntime/NativeAttribute.cs
tools/autoformat.sh
tools/common/BuildTasks.cs
tools/linker/MobileResolveMainAssemblyStep.cs
tools/linker/MonoTouch.Tuner/MetadataReducerSubStep.cs
tools/linker/MonoTouch.Tuner/MonoTouchMarkStep.cs
tools/linker/MonoTouch.Tuner/MonoTouchProfile.cs
tools/linker/MonoTouch.Tuner/MonoTouchSweepStep.cs
tools/linker/MonoTouch.Tuner/RemoveAttributes.cs
tools/linker/MonoTouch.Tuner/RemoveCode.cs
tools/linker/RemoveRejectedTypesStep.cs
tools/mtouch/Application.mtouch.cs
tools/mtouch/Assembly.mtouch.cs
tools/mtouch/AssemblyResolver.cs
tools/mtouch/BitcodeConverter.cs
tools/mtouch/BuildTasks.mtouch.cs
tools/mtouch/Target.mtouch.cs
tools/mtouch/Tuning.mtouch.cs
tools/mtouch/mtouch.cs
tools/mtouch/mtouch.csproj

This also required modifying mtouch.csproj, otherwise the wrong settings would
be applied.

[autoformat] Add mtouch.csproj.

---

tools/devops/automation/templates/main-stage.yml

This is a follow-up to dbcf1cadf823e05071588cc6088504094a6e4be1.

[devops] Add 'net8.0' and 'release-test/*' as release branches.

---

tools/apidiff/Makefile

[release/7.0.1xx-xcode14] [api-diff] Add api-diff.md to the all-markdowns target.

---

tools/apidiff/Makefile

[release/7.0.1xx-xcode13.3] [api-diff] Add api-diff.md to the all-markdowns target.

---

tests/Makefile
tests/package-mac-tests.sh
tests/packaged-macos-tests.mk

For instance don't build for Mac Catalyst if Mac Catalyst isn't enabled.

[tests] Only package macOS tests for enabled platforms.

---

tests/xtro-sharpie/macOS-CoreLocation.ignore

Fixes https://github.com/xamarin/xamarin-macios/issues/16442.

[Xtro] Add missing ignore in legacy.

---

tools/apidiff/Makefile

Backport of #16380
Backport of #16440

[net7.0-xcode14] [release/6.0.4xx-xcode14.1] [api-diff] Add api-diff.md to the all-markdowns target.

---

tools/apidiff/Makefile

[release/6.0.4xx-xcode14.1] [api-diff] Add api-diff.md to the all-markdowns target.

---

tests/common/TestRuntime.cs
tests/monotouch-test/HealthKit/CategoryTypeIdentifierTest.cs
tests/monotouch-test/HealthKit/QuantityTypeIdentifierTest.cs

Fixes https://github.com/xamarin/xamarin-macios/issues/16443.

[monotouch-test] Update QuantityTypeIdentifier.EnumValues_22351 after recent API additions. Fixes #16443.

---

src/webkit.cs

[WebKit] Fix capitalization mistakes in type DomDocument

---

tools/devops/automation/templates/build/build.yml
tools/devops/automation/templates/mac/build.yml
tools/devops/automation/templates/tests/build.yml

[xcode14.1] [DevOps] Update the version of the provisionator template to deal with the new storage.

---

tools/devops/automation/templates/build/build.yml
tools/devops/automation/templates/mac/build.yml
tools/devops/automation/templates/tests/build.yml

[release/6.0.4xx-xcode14.1] [DevOps] Update the version of the provisionator template to deal with the new storage.

---

tools/devops/automation/templates/build/build.yml
tools/devops/automation/templates/mac/build.yml
tools/devops/automation/templates/tests/build.yml

[release/7.0.1xx] [DevOps] Update the version of the provisionator template to deal with the new storage.

---

tools/devops/automation/templates/main-stage.yml
tools/devops/automation/templates/sign-and-notarized/funnel.yml
tools/devops/automation/templates/sign-and-notarized/upload-azure.yml
tools/devops/automation/templates/variables.yml

Be ready for possible container changes:
"By failing to prepare, you are preparing to fail."

[DevOps] Allow to set the azure storage to be used via variables.

---

tools/devops/automation/templates/sign-and-notarized/upload-azure.yml

[release/7.0.1xx] [DevOps] Update statuses urls for the new storage.

---

tools/devops/automation/templates/sign-and-notarized/upload-azure.yml

[release/6.0.4xx-xcode14.1] [DevOps] Update statuses urls for the new storage.

---

tools/devops/automation/templates/sign-and-notarized/upload-azure.yml

[xcode14.1] [DevOps] Update statuses urls for the new storage.

---

dotnet/targets/Xamarin.Shared.Sdk.targets

Ref: https://github.com/xamarin/xamarin-macios/issues/16609

[dotnet] Show a better error when trying to launch an app using 'dotnet run' on Windows.

---

tools/devops/automation/templates/build/build.yml
tools/devops/automation/templates/mac/build.yml
tools/devops/automation/templates/tests/build.yml

[release/7.0.1xx-xcode13.3] [DevOps] Update the version of the provisionator template to deal with the new storage.

---

tools/devops/automation/templates/build/build.yml
tools/devops/automation/templates/mac/build.yml
tools/devops/automation/templates/tests/build.yml

[release/7.0.1xx-xcode14] [DevOps] Update the version of the provisionator template to deal with the new storage.

---

tools/devops/automation/templates/build/build.yml
tools/devops/automation/templates/mac/build.yml
tools/devops/automation/templates/tests/build.yml

[release/6.0.4xx] [DevOps] Update the version of the provisionator template to deal with the new storage.

---

tools/devops/automation/build-cronjob.yml
tools/devops/automation/build-pipeline.yml
tools/devops/automation/build-pull-request.yml

[release/6.0.4xx-xcode14.1] [CI] Go back to the stable bots

---

tools/devops/automation/build-cronjob.yml
tools/devops/automation/build-pipeline.yml
tools/devops/automation/build-pull-request.yml

[xcode14.1] [CI] Go back to the stable bots

---

src/avfoundation.cs

[AVFoundation] Fix inputs -> Inputs

---

tools/devops/automation/templates/build/build.yml
tools/devops/automation/templates/mac/build.yml
tools/devops/automation/templates/tests/build.yml

[release/6.0.4xx-xcode14.1] [DevOps] Update the way we pass the token to the provisionator task.

---

tools/devops/automation/templates/build/build.yml
tools/devops/automation/templates/mac/build.yml
tools/devops/automation/templates/tests/build.yml

[release/7.0.1xx] [DevOps] Update the way we pass the token to the provisionator task.

---

src/avfoundation.cs
tools/devops/automation/templates/main-stage.yml

This will allow to know the owner of the stage.

[DevOps] Allow to pass a prefix to be used in the display names.

---

tools/devops/automation/templates/common/mac-agent-logs.yml

[release/7.0.1xx] [devops] Continue if there are any errors gathering agent logs.

---

tests/linker/ios/link sdk/LinkSdkRegressionTest.cs

Fixes this test:
SpecialFolder: MyVideos
Expected: False
But was: True

[link sdk] Update the SpecialFolders tests according to changes in .NET 8.

---

src/webkit.cs
tests/monotouch-test/AudioUnit/AudioUnitTest.cs

[WebKit] defaultChecked -> DefaultChecked

---

msbuild/Makefile

Ema pinpointed this commit to bee the root causing reflection issues on the windows side
https://gist.github.com/Redth/e60fcf1b790eb9efe3e476788bff5693#file-remotesimoutput-log-L13-L26
Backport of #16418

[release/6.0.4xx-xcode14.1] [msbuild] Partial revert of ad8cdb3

---

msbuild/Directory.Build.props

We need this for 17.5 Preview 2 so feel free to backport it to the needed branches

Updated Xamarin.Messaging to 1.8.49

---

msbuild/Directory.Build.props

We need this for 17.5 Preview 2 so feel free to backport it to the needed branches
Backport of #16899

[xcode14.1] Updated Xamarin.Messaging to 1.8.49

---

msbuild/Directory.Build.props

We need this for 17.5 Preview 2 so feel free to backport it to the needed branches
Backport of #16899

[release/7.0.1xx] Updated Xamarin.Messaging to 1.8.49

---

msbuild/Directory.Build.props

We need this for 17.5 Preview 2 so feel free to backport it to the needed branches
Backport of #16899

[release/6.0.4xx-xcode14.1] Updated Xamarin.Messaging to 1.8.49

---

src/ObjCRuntime/Runtime.cs
src/Simd/MatrixDouble4x4.cs
src/Simd/MatrixFloat2x2.cs
src/Simd/MatrixFloat3x3.cs
src/Simd/MatrixFloat4x3.cs
src/Simd/MatrixFloat4x4.cs
src/Simd/VectorDouble3.cs
src/Simd/VectorFloat3.cs
tests/monotouch-test/AppDelegate.cs

This is code from PRs that were started before we started autoformatting the
files in question, and then merged afterwards.

[autoformat] Update some new code.

---

tests/linker/mac/LinkAnyTest.cs
tests/monotouch-test/Foundation/UrlSessionTest.cs

[tests] Allow for timeouts in CI in a few tests.

---

dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalyst-viewcontroller/ViewController1.cs
dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalystbinding/ApiDefinition.cs
dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalystbinding/StructsAndEnums.cs
dotnet/Templates/Microsoft.iOS.Templates/ios-viewcontroller/ViewController1.cs
dotnet/Templates/Microsoft.iOS.Templates/iosbinding/ApiDefinition.cs
dotnet/Templates/Microsoft.iOS.Templates/iosbinding/StructsAndEnums.cs
dotnet/Templates/Microsoft.macOS.Templates/macos-viewcontroller/ViewController1.cs
dotnet/Templates/Microsoft.macOS.Templates/macosbinding/ApiDefinition.cs
dotnet/Templates/Microsoft.macOS.Templates/macosbinding/StructsAndEnums.cs
dotnet/Templates/Microsoft.tvOS.Templates/tvos-viewcontroller/ViewController1.cs
dotnet/Templates/Microsoft.tvOS.Templates/tvosbinding/ApiDefinition.cs
dotnet/Templates/Microsoft.tvOS.Templates/tvosbinding/StructsAndEnums.cs
msbuild/Xamarin.HotRestart.PreBuilt/Xamarin.PreBuilt.iOS/Main.cs
runtime/bindings-generator.cs
src/uikit.cs
tools/autoformat.sh

Without whitespace changes: https://github.com/xamarin/xamarin-macios/pull/16974/files?w=1

[autoformat] Add the rest of the repository.

---

src/foundation.cs

Don't put availability attributes inside a platform condition, because we need
all availability attributes to be visible when building all platforms,
otherwise we won't generate the correct attributes for other platforms.

[Foundation] Fix availability attributes to be the same for all platforms.

---

src/Foundation/NSObject2.cs

NSObject_Disposer.Drain isn't reentry-safe, and there's a rather impressive
(and not in a good way) case where this can happen: if a native dealloc method
ends up processing the main thread's runloop somehow.
The fix makes the Drain function detect reentrancy, and just re-schedule a
call to itself on the run loop. I believe should be safe - either the dealloc
method will process the runloop again a few times, in which case we'll just
re-schedule the drain call every time, until the dealloc method finishes
processing the runloop, and then the next drain call will actually drain.
Fixes https://github.com/xamarin/xamarin-macios/issues/16587.

[Foundation] Handle re-entrancy in NSObject_Disposer.Drain. Fixes #16587.

---

Make.config

The .NET 6 release branch is release/6.0.4xx-xcode14.2.

Unmake release/6.0.4xx-xcode14.1 as a release branch.

---

Make.config

The .NET 7 release branch is release/7.0.1xx-xcode14.2.

Unmake release/7.0.1xx as a release branch.

---

msbuild/Xamarin.MacDev.Tasks/Tasks/CompileAppManifestTaskBase.cs
msbuild/Xamarin.MacDev.Tasks/Tasks/CompileEntitlementsTaskBase.cs
msbuild/Xamarin.MacDev.Tasks/Tasks/ResolveNativeReferencesBase.cs
msbuild/Xamarin.MacDev.Tasks/Tasks/WriteAppManifestTaskBase.cs
msbuild/Xamarin.iOS.Tasks.Windows/Tasks/CompileAppManifest.cs

This requires a few nullability updates in our code as well.
* xamarin/Xamarin.MacDev@14d5361 Enable nullability in PListObject.cs
Diff: https://github.com/xamarin/Xamarin.MacDev/compare/ac2647b6436972218f07555487abb564506c9eb5..14d53612d4624459a7ae617141c45e940ada6df5

Bump Xamarin.MacDev.

---

tests/common/Configuration.cs
tests/generator/BGenTests.cs
tests/generator/BGenTool.cs

Make it assert on the exact list of attributes we're expecting. This makes it
much easier to see what changed.

[tests] Improve the Bug35176 generator test.

---

tests/cecil-tests/cecil-tests.csproj
tests/dotnet/UnitTests/DotNetUnitTests.csproj
tests/dotnet/UnitTests/PartialAppManifestTest.cs
tests/dotnet/UnitTests/ProjectTest.cs
tests/dotnet/UnitTests/TestBaseClass.cs

Also make any nullability warnings show up as errors.

[tests] Fix a few nullability issues in cecil-tests and the .NET tests.

---

src/Foundation/NSCalendar.cs
src/GameKit/GKCompat.cs
tests/cecil-tests/ObsoleteTest.cs

* Hide all obsolete API using the EditorBrowsable atribute.
* Iterate over everything with availability attributes in the test.

[src/tests] Improve the cecil test checking for obsolete API.

---

dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.cs.json
dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.de.json
dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.es.json
dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.fr.json
dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.it.json
dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.ja.json
dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.ko.json
dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.pl.json
dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.pt-BR.json
dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.ru.json
dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.tr.json
dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.zh-Hans.json
dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.zh-Hant.json
dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.cs.json
dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.de.json
dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.es.json
dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.fr.json
dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.it.json
dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.ja.json
dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.ko.json
dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.pl.json
dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.pt-BR.json
dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.ru.json
dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.tr.json
dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.zh-Hans.json
dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.zh-Hant.json

Localized file check-in by OneLocBuild Task: Build definition ID 17751: Build ID 7141571

---

tests/cecil-tests/ApiAvailabilityTest.cs

[tests] Enable some of the asserts in the Cecil.Tests.ApiAvailabilityTest.AttributeConsistency test.

---

tests/xharness/Jenkins/Jenkins.cs

We keep adding more and more tests...

[xharness] Bump the timeout for the .NET tests.

---

src/ObjCRuntime/Runtime.CoreCLR.cs

And fix the resulting build errors+warnings.

[ObjCRuntime] Enable nullability in Runtime.CoreCLR.cs

---

src/Security/SecProtocolOptions.cs

[dotnet] replace strings in pinvokes

---

msbuild/Directory.Build.props

[xcode14.2] Updated MessagingVersion to 1.9.0

---

msbuild/Directory.Build.props

[xcode14.1] Updated MessagingVersion to 1.9.0

---

src/webkit.cs

There's no reason to have multiple partial interfaces in the same code file,
so just merge them.

[WebKit] Merge partial interfaces.

---

tools/mtouch/TranslatedAssemblies/Errors.cs.resx
tools/mtouch/TranslatedAssemblies/Errors.de.resx
tools/mtouch/TranslatedAssemblies/Errors.es.resx
tools/mtouch/TranslatedAssemblies/Errors.fr.resx
tools/mtouch/TranslatedAssemblies/Errors.it.resx
tools/mtouch/TranslatedAssemblies/Errors.ja.resx
tools/mtouch/TranslatedAssemblies/Errors.ko.resx
tools/mtouch/TranslatedAssemblies/Errors.pl.resx
tools/mtouch/TranslatedAssemblies/Errors.pt-BR.resx
tools/mtouch/TranslatedAssemblies/Errors.ru.resx
tools/mtouch/TranslatedAssemblies/Errors.tr.resx
tools/mtouch/TranslatedAssemblies/Errors.zh-Hans.resx
tools/mtouch/TranslatedAssemblies/Errors.zh-Hant.resx

Localized file check-in by OneLocBuild Task: Build definition ID 17751: Build ID 7198107

---

DOWNLOADS.md

Fixes https://github.com/xamarin/xamarin-macios/issues/16625.

Update DOWNLOADS.md with new releases. Fixes #16625.

---

Localize/loc/cs/dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.json.lcl
Localize/loc/cs/dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.json.lcl
Localize/loc/de/dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.json.lcl
Localize/loc/de/dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.json.lcl
Localize/loc/es/dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.json.lcl
Localize/loc/es/dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.json.lcl
Localize/loc/fr/dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.json.lcl
Localize/loc/fr/dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.json.lcl
Localize/loc/it/dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.json.lcl
Localize/loc/it/dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.json.lcl
Localize/loc/ja/dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.json.lcl
Localize/loc/ja/dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.json.lcl
Localize/loc/ko/dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.json.lcl
Localize/loc/ko/dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.json.lcl
Localize/loc/pl/dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.json.lcl
Localize/loc/pl/dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.json.lcl
Localize/loc/pt-BR/dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.json.lcl
Localize/loc/pt-BR/dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.json.lcl
Localize/loc/ru/dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.json.lcl
Localize/loc/ru/dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.json.lcl
Localize/loc/tr/dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.json.lcl
Localize/loc/tr/dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.json.lcl
Localize/loc/zh-Hans/dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.json.lcl
Localize/loc/zh-Hans/dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.json.lcl
Localize/loc/zh-Hant/dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.json.lcl
Localize/loc/zh-Hant/dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.json.lcl

LEGO: Pull request from lego/hb_dca0a672-370a-4b3c-b55f-cd146e93faf9_20230119113721181 to Localization with localized lcls

LEGO: Pull request from lego/hb_dca0a672-370a-4b3c-b55f-cd146e93faf9_20230119113721181 to Localization

---

msbuild/Directory.Build.props

[release/7.0.1xx] Updated MessagingVersion to 1.9.0

---

msbuild/Directory.Build.props

[release/6.0.4xx-xcode14.1] Updated MessagingVersion to 1.9.0

---

dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.cs.json
dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.de.json
dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.es.json
dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.fr.json
dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.it.json
dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.ja.json
dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.ko.json
dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.pl.json
dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.pt-BR.json
dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.ru.json
dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.tr.json
dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.zh-Hans.json
dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.zh-Hant.json
dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.cs.json
dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.de.json
dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.es.json
dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.fr.json
dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.it.json
dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.ja.json
dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.ko.json
dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.pl.json
dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.pt-BR.json
dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.ru.json
dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.tr.json
dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.zh-Hans.json
dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.zh-Hant.json

Localized file check-in by OneLocBuild Task: Build definition ID 17751: Build ID 7255787

---

tools/autoformat.sh
tools/devops/provision-brew-packages.csx

Ref: https://github.com/xamarin/xamarin-macios/pull/17403

[autoformat] Fix line endings for localization output.

---

tests/introspection/ApiSelectorTest.cs

[tests] Remove workaround for issue #14802.

---

src/ILLink.Descriptors.xml
src/Makefile

Ref: https://github.com/xamarin/xamarin-macios/pull/14803
Ref: https://github.com/dotnet/runtime/pull/68265

[src] Remove workaround for a Mono bug that's been fixed in .NET 7+.

---

msbuild/Directory.Build.props
msbuild/Xamarin.MacDev.Tasks/MsBuildTasks/Delete.cs
msbuild/Xamarin.MacDev.Tasks/MsBuildTasks/Exec.cs
msbuild/Xamarin.MacDev.Tasks/MsBuildTasks/RemoveDir.cs
msbuild/Xamarin.iOS.Tasks/Tasks/CopyArchiveFiles.cs
msbuild/Xamarin.iOS.Tasks/Tasks/ResolveUniversalTypeIdentifiers.cs
msbuild/Xamarin.iOS.Tasks/Tasks/VerifyXcodeVersion.cs

[release/7.0.1xx-xcode14.2] Update Xamarin.Messaging to 1.9.17

---

msbuild/Directory.Build.props
msbuild/Xamarin.MacDev.Tasks/MsBuildTasks/Delete.cs
msbuild/Xamarin.MacDev.Tasks/MsBuildTasks/Exec.cs
msbuild/Xamarin.MacDev.Tasks/MsBuildTasks/RemoveDir.cs
msbuild/Xamarin.iOS.Tasks/Tasks/CopyArchiveFiles.cs
msbuild/Xamarin.iOS.Tasks/Tasks/ResolveUniversalTypeIdentifiers.cs
msbuild/Xamarin.iOS.Tasks/Tasks/VerifyXcodeVersion.cs

[xcode14.2] Update Xamarin.Messaging to 1.9.17

---

msbuild/Directory.Build.props
msbuild/Xamarin.MacDev.Tasks/MsBuildTasks/Delete.cs
msbuild/Xamarin.MacDev.Tasks/MsBuildTasks/Exec.cs
msbuild/Xamarin.MacDev.Tasks/MsBuildTasks/RemoveDir.cs
msbuild/Xamarin.iOS.Tasks/Tasks/CopyArchiveFiles.cs
msbuild/Xamarin.iOS.Tasks/Tasks/ResolveUniversalTypeIdentifiers.cs
msbuild/Xamarin.iOS.Tasks/Tasks/VerifyXcodeVersion.cs

[release/6.0.4xx-xcode14.2] Update Xamarin.Messaging to 1.9.17

---

msbuild/Directory.Build.props
msbuild/Xamarin.MacDev.Tasks/MsBuildTasks/Delete.cs
msbuild/Xamarin.MacDev.Tasks/MsBuildTasks/Exec.cs
msbuild/Xamarin.MacDev.Tasks/MsBuildTasks/RemoveDir.cs
msbuild/Xamarin.iOS.Tasks/Tasks/CopyArchiveFiles.cs
msbuild/Xamarin.iOS.Tasks/Tasks/ResolveUniversalTypeIdentifiers.cs
msbuild/Xamarin.iOS.Tasks/Tasks/VerifyXcodeVersion.cs

[release/7.0.2xx] Update Xamarin.Messaging to 1.9.17

---

src/MapKit/MapKit.cs

[MapKit] Make MKMapRect.World static

---

mk/xamarin.mk

Ref: https://github.com/xamarin/maccore/commit/645f1813c5106d67f05d8c2174e0363b76a68991

Bump mlaunch to fix an unneccessary warning.

---

src/bgen/AttributeManager.cs
src/bgen/Generator.cs
src/bgen/MarshalInfo.cs
src/bgen/MemberInformation.cs
tests/monotouch-test/CoreBluetooth/CentralManagerTest.cs

Remove more indirections that make the code more complicated to follow that it really needs to be.

[Generator] Remove not needed method that adds indirection.

---

src/bgen/AttributeManager.cs
src/bgen/Generator.cs

Group all attr methods in the attr manager class.

[Generator] Move all attr related methods to the attr manager.

---

src/bgen/Generator.cs
src/bgen/MarshalTypeList.cs
src/generator.csproj

Use a class that we can have to store the types and a single place to locate the types to load.
Later we can use the class to write tests and move to a Dictionary implementation that passes the tests and is more efficient.

[Generator] Use a specialized class to store the marshal types.

---

tools/devops/automation/templates/main-stage.yml
tools/devops/automation/templates/release/vs-insertion-prep.yml

Do not skip the msi conversion since that will be needed in the unified pipeline BUT skip pushing to the internal nuget feeds.

[CI] Do not skip the insertion but the nuget push.

---

tools/devops/automation/templates/release/vs-insertion-prep.yml

We do not longer use it and makes noise in the CI.

[CI] Remove step that is not longer used and is always ignored.

---

mk/xamarin.mk

Ref: https://github.com/xamarin/maccore/commit/52cb0860321f80c36ae2e1733c377b889ec8736b
Backport of #17587

[xcode14.2] [release/7.0.2xx] Bump mlaunch to get fix for Xcode 14.3 beta 1.

---

mk/xamarin.mk

Ref: https://github.com/xamarin/maccore/commit/52cb0860321f80c36ae2e1733c377b889ec8736b
Backport of #17587

[release/7.0.1xx-xcode14.2] [release/7.0.2xx] Bump mlaunch to get fix for Xcode 14.3 beta 1.

---

mk/xamarin.mk

Ref: https://github.com/xamarin/maccore/commit/52cb0860321f80c36ae2e1733c377b889ec8736b

Bump mlaunch to get fix for Xcode 14.3 beta 1.

---

dotnet/targets/Xamarin.Shared.Sdk.targets

Fixes https://github.com/xamarin/xamarin-macios/issues/16836.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1751368.
Backport of #17606

[release/8.0.1xx-preview1] [dotnet] Include the marshal-ilgen component. Fixes #16836.

---

.github/workflows/autoformat.yml
.github/workflows/autoformat2.yml

This adds some extra testing to the actions and also makes sure we get any
updates.

[actions] Switch to using the autoformat actions instead of inline logic.

---

tests/monotouch-test/CoreServices/FSEventStreamTest.cs

Ref: https://github.com/xamarin/maccore/issues/2630

[tests] Improve diagnostic output in FSEventStreamTest.

---

src/ObjCRuntime/TransientString.cs
src/UIKit/UIApplication.cs
tests/cecil-tests/BlittablePInvokes.cs

handling of string array for args

[dotnet] UIMain changes

---

src/CoreGraphics/CGEvent.cs

Not sure what the lifetime of this is. I don't see a way to remove a tap so in theory this is a leak.

[dotnet] mac CoreGraphics pinvokes

---

src/ObjCRuntime/TransientString.cs
src/Security/Authorization.cs

Modded AllocStringArray to allow nullable strings.

[dotnet] security pinvoke and nullable string arrays

---

tools/devops/automation/templates/variables.yml
tools/devops/automation/templates/windows/build.yml
tools/devops/automation/templates/windows/reserve-mac.yml

[release/6.0.4xx-xcode14.2] [CI] The DropsPAT was removed, change it to a new one.

---

tools/devops/automation/build-pipeline.yml
tools/devops/automation/build-pull-request.yml
tools/devops/automation/templates/release/vs-insertion-prep.yml

This reverts commit f4ebf2f75edd6fe2ee5b19db095062b7113d7c1b.
This changes does not work when not in a PR. Needs to be reverted

Revert "[CI] Set a variable to be able to avoid collision between templates. (#17664)"

---

tools/common/Make.common
tools/common/SdkVersions.cs

Also make it an error if the SdkVersions.cs file was updated, so this doesn't
go unnoticed again.

[tools] Commit the regenerated SdkVersions.cs

---

msbuild/ILMerge.targets

[xcode14.2] Added Merq and Merq.Core to ILMerge since they're now required and loaded by Messaging

---

tests/common/TestRuntime.cs
tests/linker/mac/LinkAnyTest.cs
tests/monotouch-test/Foundation/UrlSessionTest.cs

Backport of #16945 and #17649.

[release/7.0.2xx] [tests] Allow for timeouts in CI in a few tests.

---

tests/common/TestRuntime.cs
tests/linker/mac/LinkAnyTest.cs
tests/monotouch-test/Foundation/UrlSessionTest.cs

Backport of #16945 and #17649.

[xcode14.2] [tests] Allow for timeouts in CI in a few tests.

---

tests/common/TestRuntime.cs
tests/linker/mac/LinkAnyTest.cs
tests/monotouch-test/Foundation/UrlSessionTest.cs

Backport of #16945 and #17649.

[release/6.0.4xx-xcode14.2] [tests] Allow for timeouts in CI in a few tests.

---

tools/devops/automation/templates/variables.yml
tools/devops/automation/templates/windows/build.yml
tools/devops/automation/templates/windows/reserve-mac.yml

[xcode14.2] [CI] The DropsPAT was removed, change it to a new one.

---

msbuild/ILMerge.targets

[main] Added Merq and Merq.Core to ILMerge since they're now required and loaded by Messaging

---

dotnet/generate-workloadmanifest-json.csharp
tests/dotnet/Net7_0SimpleApp/AppDelegate.cs
tests/dotnet/Net7_0SimpleApp/MacCatalyst/Makefile
tests/dotnet/Net7_0SimpleApp/MacCatalyst/Net7_0SimpleApp.csproj
tests/dotnet/Net7_0SimpleApp/Makefile
tests/dotnet/Net7_0SimpleApp/iOS/Makefile
tests/dotnet/Net7_0SimpleApp/iOS/Net7_0SimpleApp.csproj
tests/dotnet/Net7_0SimpleApp/macOS/Makefile
tests/dotnet/Net7_0SimpleApp/macOS/Net7_0SimpleApp.csproj
tests/dotnet/Net7_0SimpleApp/shared.csproj
tests/dotnet/Net7_0SimpleApp/shared.mk
tests/dotnet/Net7_0SimpleApp/tvOS/Makefile
tests/dotnet/Net7_0SimpleApp/tvOS/Net7_0SimpleApp.csproj
tests/dotnet/UnitTests/ProjectTest.cs

[release/8.0.1xx-preview2] [net8.0] [tests] Add a .NET 7 test app.

---

src/Darwin/SystemLog.cs
tests/cecil-tests/BlittablePInvokes.cs

[dotnet] final blittable pinvoke

---

tests/cecil-tests/BlittablePInvokes.cs

Tests fail, especially reflection based tests.
Wouldn't you like it if a test came with a blueprint on how to fix the issue you created? Yes, of course you would. So here it is.

[dotnet] future proof the test

---

Localize/loc/de/tools/mtouch/Errors.resx.lcl
Localize/loc/ru/tools/mtouch/Errors.resx.lcl
Localize/loc/tr/tools/mtouch/Errors.resx.lcl

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230310121620938 to Localization with localized lcls

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230310121620938 to Localization

---

tools/devops/automation/templates/sign-and-notarized/upload-azure.yml

Because the template is know shared between pipelines, we need tone more precise.
backport of https://github.com/xamarin/xamarin-macios/pull/17762

[CI] Download the minimum number of artefacts

---

Localize/loc/es/tools/mtouch/Errors.resx.lcl
Localize/loc/fr/tools/mtouch/Errors.resx.lcl

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230311142210535 to Localization with localized lcls

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230311142210535 to Localization

---

Localize/loc/cs/tools/mtouch/Errors.resx.lcl

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230312012342646 to Localization with localized lcls

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230312012342646 to Localization

---

tools/devops/automation/templates/sign-and-notarized/funnel.yml

[release/8.0.1xx-preview2] [CI] Allow to debug the env in the upload jobs.

---

src/Makefile
src/dotnet.tmpl.csproj

* Use the right TFM.
* Compute the right assembly name.

[src] Improve the generated project files a little bit.

---

eng/Version.Details.xml
eng/Versions.props

Ref: https://github.com/dotnet/runtime/pull/83208

[maestro] Update emscripten subscription according to upstream changes to use more stable name.

---

tools/devops/automation/templates/main-stage.yml

Following the steps here: https://github.com/xamarin/xamarin-macios/issues/17870
This PR will finalize the process of removing the Localization from the xamarin-macios-ci pipeline since we are running the localization steps inside the xamarin-macios-translations pipeline

[Localization] Remove the loc parameter from main-stage.yml

---

tools/devops/automation/templates/common/setup.yml

[CI] Fix GitHub ssh host key

---

tools/devops/automation/templates/common/setup.yml

[release/7.0.1xx-xcode14.2] [CI] Fix GitHub ssh host key

---

tools/devops/automation/templates/common/setup.yml

[release/6.0.4xx-xcode14.2] [CI] Fix GitHub ssh host key

---

tools/devops/automation/templates/common/setup.yml

[xcode14.2] [CI] Fix GitHub ssh host key

---

mk/xamarin.mk

Bump maccore to get fix for mlaunch:
* https://github.com/rolfbjarne/maccore/commit/3ce5b1e181ab0ff4b98995608a083959e7e57760
Backport of #17898

[release/8.0.1xx-preview3] Bump maccore.

---

mk/xamarin.mk

Bump maccore to get fix for mlaunch:
* https://github.com/rolfbjarne/maccore/commit/3ce5b1e181ab0ff4b98995608a083959e7e57760
Backport of #17898

[release/7.0.2xx] Bump maccore.

---

tools/devops/automation/templates/sign-and-notarized/funnel.yml

Manual backport of https://github.com/xamarin/xamarin-macios/pull/17920 needed to test the megapipeline.

[release/8.0.1xx-preview3][CI] Fix image override issue with the image. (#17920)

---

tools/devops/automation/templates/sign-and-notarized/funnel.yml

Manual backport of https://github.com/xamarin/xamarin-macios/pull/17920 needed to test the megapipeline.

[release/8.0.1xx-preview2][CI] Fix image override issue. VSEng mentioned a vImage when it is not.

---

Make.config

Bump to stable version of Xcode 14.3
Backport of #17953

[release/7.0.2xx-xcode14.3] Bump to stable Xcode 14.3

---

Make.config

Bump to stable version of Xcode 14.3

[main] Bump to stable Xcode 14.3

---

Make.config

Bump to stable version of Xcode 14.3
Backport of #17953

[xcode14.3] Bump to stable Xcode 14.3

---

Localize/loc/ru/tools/mtouch/Errors.resx.lcl
Localize/loc/tr/tools/mtouch/Errors.resx.lcl

There were two places that with merge conflicts from this PR: https://github.com/xamarin/xamarin-macios/pull/17902
Maybe there could be a cecil test to catch `<<<<<<< HEAD` or other parts of a merge conflict?

[Localization] Resolve Merge Conflicts

---

Localize/loc/ru/tools/mtouch/Errors.resx.lcl
Localize/loc/tr/tools/mtouch/Errors.resx.lcl

Continuation of this PR: https://github.com/xamarin/xamarin-macios/pull/17963

[Localization] Two more merge conflicts to remove

---

eng/Version.Details.xml
eng/Versions.props

[release/8.0.1xx-preview3] Update dependencies from xamarin/xamarin-macios

---

msbuild/Directory.Build.props

[release/6.0.4xx-xcode14.3] Update Messaging and Hot Restart versions

---

msbuild/Directory.Build.props

[xcode14.3] Update Messaging and Hot Restart versions

---

msbuild/Directory.Build.props

[release/7.0.2xx-xcode14.3] Update Messaging and Hot Restart versions

---

Localize/loc/cs/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/de/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/es/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/fr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/it/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/ja/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/ko/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/pl/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/pt-BR/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/ru/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/tr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/zh-Hans/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/zh-Hant/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230412101449471 to Localization with localized lcls

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230412101449471 to Localization

---

Localize/loc/cs/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/de/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/es/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/it/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/pl/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/pt-BR/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/tr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/zh-Hans/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/zh-Hant/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230413100709480 to Localization with localized lcls

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230413100709480 to Localization

---

tools/devops/automation/scripts/localizationBomRemoval.ps1
tools/devops/automation/templates/loc-translations.yml

Followed the steps outlined here by the Loc team to remove the BOMs from our check-in: https://ceapex.visualstudio.com/CEINTL/_workitems/edit/816066

[Localization] Remove BOM

---

tools/common/StaticRegistrar.cs

This has no real effect, it just makes the generated code looks less silly.
Instead of something like:
class MyObjectiveCClass : NSObject<NSCopying, NSCopying, NSCopying>
we'll now generate this:
class MyObjectiveCClass : NSObject<NSCopying>

[static registrar] Avoid listing protocols more than once in generated code.

---

tests/monotouch-test/AppDelegate.cs

[release/6.0.4xx-xcode14.2] [tests] Find a workaround for #xamarin/maccore@2668.

---

tests/monotouch-test/AppDelegate.cs

[release/7.0.2xx] [tests] Find a workaround for #xamarin/maccore@2668.

---

tests/xharness/BCLTestImportTargetFactory.cs
tests/xharness/Jenkins/TestVariationsFactory.cs
tests/xharness/TestImporter/ProjectDefinition.cs
tests/xharness/TestImporter/Templates/ITemplatedProject.cs
tests/xharness/TestImporter/Templates/Managed/XamariniOSTemplate.cs
tests/xharness/TestProject.cs
tests/xharness/Xharness.Tests/Tests/BCLTestImportTargetFactoryTest.cs

It's not being used for anything at all, it's only passing empty strings around.

[xharness] Remove the MtouchExtraArgs parameters/properties/fields in numerous places.

---

Localize/loc/es/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/it/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/ru/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/zh-Hans/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/zh-Hant/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230504153138819 to Localization with localized lcls

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230504153138819 to Localization

---

Localize/loc/cs/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/de/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/fr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/ja/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/ko/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/pl/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/pt-BR/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/tr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230506030659907 to Localization with localized lcls

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230506030659907 to Localization

---

src/Foundation/NSUserDefaults.cs
src/foundation.cs
tests/xtro-sharpie/api-annotations-dotnet/common-Foundation.ignore
tests/xtro-sharpie/common-Foundation.ignore

Fixes https://github.com/xamarin/xamarin-macios/issues/18243.

[Foundation] Fix nullability issues in NSUserDefaults. Fixes #18243.

---

Localize/loc/cs/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/de/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/es/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/fr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/it/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/ja/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/ko/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/pl/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/pt-BR/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/ru/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/tr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/zh-Hans/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/zh-Hant/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl

Until, we can try a VSEng PAT for the Pipeline as seen in this [PR](https://github.com/xamarin/xamarin-macios/pull/18122#issuecomment-1533558542), I will continue to bring the [not-yet usable] translation strings manually!

[Localization] Bring More Translations Manually

---

Localize/loc/es/dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalyst-view/.template.config/localize/templatestrings.json.lcl

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230511030559465 to Localization with localized lcls

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230511030559465 to Localization

---

tests/monotouch-test/CoreGraphics/CGEventTests.cs

[monotouch-test] Adjust the CGEventTest to handle successful tap creation.

---

src/servicemanagement.cs
tests/xharness/IAppBundleInformationParserExtensions.cs

The autoformatter was down for a litle while, and these issues crept in.

Auto-format source code.

---

src/Resources.resx
src/bgen/Filters.cs
tests/generator/BGenTool.cs

Remove some warnings that started to happen "recently".

[Generator] Remove nullability warnings.

---

dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalyst-view/.template.config/localize/templatestrings.es.json
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.cs.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.de.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.es.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.fr.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.it.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ja.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ko.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pl.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pt-BR.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ru.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.tr.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hans.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hant.resx
tools/mtouch/TranslatedAssemblies/Errors.cs.resx
tools/mtouch/TranslatedAssemblies/Errors.de.resx
tools/mtouch/TranslatedAssemblies/Errors.es.resx
tools/mtouch/TranslatedAssemblies/Errors.fr.resx
tools/mtouch/TranslatedAssemblies/Errors.it.resx
tools/mtouch/TranslatedAssemblies/Errors.ja.resx
tools/mtouch/TranslatedAssemblies/Errors.ko.resx
tools/mtouch/TranslatedAssemblies/Errors.pl.resx
tools/mtouch/TranslatedAssemblies/Errors.pt-BR.resx
tools/mtouch/TranslatedAssemblies/Errors.ru.resx
tools/mtouch/TranslatedAssemblies/Errors.tr.resx
tools/mtouch/TranslatedAssemblies/Errors.zh-Hans.resx
tools/mtouch/TranslatedAssemblies/Errors.zh-Hant.resx

Localized file check-in by OneLocBuild Task: Build definition ID 17751: Build ID 7800490

---

Localize/loc/es/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/es/tools/mtouch/Errors.resx.lcl
Localize/loc/ko/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/ko/tools/mtouch/Errors.resx.lcl

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230524100928308 to Localization with localized lcls

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230524100928308 to Localization

---

Localize/loc/de/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/de/tools/mtouch/Errors.resx.lcl
Localize/loc/pt-BR/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/pt-BR/tools/mtouch/Errors.resx.lcl
Localize/loc/tr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/tr/tools/mtouch/Errors.resx.lcl
Localize/loc/zh-Hans/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/zh-Hans/tools/mtouch/Errors.resx.lcl

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230524223818093 to Localization with localized lcls

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230524223818093 to Localization

---

Localize/loc/zh-Hant/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/zh-Hant/tools/mtouch/Errors.resx.lcl

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230525101014441 to Localization with localized lcls

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230525101014441 to Localization

---

Localize/loc/cs/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/cs/tools/mtouch/Errors.resx.lcl
Localize/loc/fr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/fr/tools/mtouch/Errors.resx.lcl
Localize/loc/it/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/it/tools/mtouch/Errors.resx.lcl
Localize/loc/ja/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/ja/tools/mtouch/Errors.resx.lcl
Localize/loc/pl/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/pl/tools/mtouch/Errors.resx.lcl
Localize/loc/ru/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/ru/tools/mtouch/Errors.resx.lcl

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230525221314601 to Localization with localized lcls

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230525221314601 to Localization

---

tools/devops/automation/build-lego.yml

Let's try using this new PAT from VSEng in our automation to bring translations from the Localization branch in PRs.
Tested here on a test branch: https://github.com/xamarin/xamarin-macios/pull/18326

[Localization] Change PAT for automated PRs

---

tools/devops/automation/templates/windows/build.yml

Also make the tests log to stdout so that we can see what happened (i.e. went
wrong) from the logs.

[devops] Collect test results and upload them for the Windows tests.

---

builds/package-download/download-packages.csproj
src/bgen/bgen.csproj
tools/mlaunch/download-mlaunch.csproj

[release/7.0.2xx-xcode14.3] Use the current version of .NET in a few projects.

---

builds/package-download/download-packages.csproj
src/bgen/bgen.csproj
tools/mlaunch/download-mlaunch.csproj

[release/7.0.3xx] Use the current version of .NET in a few projects.

---

.github/workflows/backport-trigger.yml

Use latest [backport-trigger](https://github.com/xamarin/.github/blob/main/.github/workflows/backport-trigger.yml) and in turn the latest [backport-action](https://github.com/xamarin/backport-bot-action/blob/main/.github/workflows/backport-action.yml). Remove dependency on outdated `backport-bot-action`
**NOTE:** With this change the `/sudo backport` comment triggering the backport needs to be the first thing in the comment

Migrate to backport-action

---

tools/devops/automation/templates/governance-checks.yml

This allows to later get the result and generate the exception list based on it.

[CI] Upload the policheck result to be able to later decide what to exclude.

---

msbuild/Makefile

We don't support watchOS on .NET, so this is just useless code.

[msbuild] Remove some logic for watchOS on .NET.

---

src/AssemblyInfo.cs.in
src/Makefile

Android does the same.
Contributes towards https://github.com/xamarin/xamarin-macios/issues/18343.

[net8.0] [src] Add the RequiresPreviewFeatures attribute if we're using an unstable version of Xcode. Contributes towards #18343.

---

msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.cs.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.de.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.es.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.fr.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.it.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ja.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ko.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pl.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pt-BR.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ru.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.tr.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hans.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hant.resx
tools/mtouch/TranslatedAssemblies/Errors.cs.resx
tools/mtouch/TranslatedAssemblies/Errors.de.resx
tools/mtouch/TranslatedAssemblies/Errors.es.resx
tools/mtouch/TranslatedAssemblies/Errors.fr.resx
tools/mtouch/TranslatedAssemblies/Errors.it.resx
tools/mtouch/TranslatedAssemblies/Errors.ja.resx
tools/mtouch/TranslatedAssemblies/Errors.ko.resx
tools/mtouch/TranslatedAssemblies/Errors.pl.resx
tools/mtouch/TranslatedAssemblies/Errors.pt-BR.resx
tools/mtouch/TranslatedAssemblies/Errors.ru.resx
tools/mtouch/TranslatedAssemblies/Errors.tr.resx
tools/mtouch/TranslatedAssemblies/Errors.zh-Hans.resx
tools/mtouch/TranslatedAssemblies/Errors.zh-Hant.resx

Localized file check-in by OneLocBuild Task: Build definition ID 17751: Build ID 8130882

---

src/healthkit.cs

Fixes https://github.com/xamarin/xamarin-macios/issues/18622.

[HealthKit] Add nullability attributes to HKSampleQueryResultsHandler. Fixes #18622.

---

mk/xamarin.mk

[release/7.0.3xx] [mlaunch] Bump to a version that works with Xcode 15.

---

mk/xamarin.mk

[xcode14.3] [mlaunch] Bump to a version that works with Xcode 15.

---

.github/policies/resourceManagement.yml

Otherwise we might end up with a bot fight:
https://github.com/xamarin/xamarin-macios/issues/18598#issuecomment-1669416345

[GitOps] Ignore any comments by msftbot.

---

Localize/loc/ru/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230810095854002 to Localization with localized lcls

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230810095854002 to Localization

---

.github/workflows/update-single-platform-branches.yml

Add:
* Only .NET (no legacy) - but all platforms.
* Only legacy (no .NET) - both platforms.
* Xamarin.iOS only.
* Xamarin.Mac only.

[actions] Add more variations to the single-platform variation testing.

---

Localize/loc/es/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/ja/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/tr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/zh-Hant/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230810215528985 to Localization with localized lcls

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230810215528985 to Localization

---

Localize/loc/cs/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/fr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/pl/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230811095824329 to Localization with localized lcls

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230811095824329 to Localization

---

Localize/loc/de/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/it/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/ko/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/zh-Hans/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230811215811100 to Localization with localized lcls

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230811215811100 to Localization

---

Localize/loc/pt-BR/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230812094919202 to Localization with localized lcls

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230812094919202 to Localization

---

tools/create-dotnet-linker-launch-json/create-dotnet-linker-launch-json.csproj
tools/dotnet-linker/dotnet-linker.csproj

Just use whatever .NET version we're using to build with.

[dotnet] Stop hardcoding the .NET version in a few more projects.

---

dotnet/targets/Xamarin.Shared.Sdk.targets

Ref: https://github.com/xamarin/xamarin-macios/issues/17408

[dotnet] Fix typo when loading support for App Extensions on Mac Catalyst.

---

tools/apidiff/Makefile

New commits in rolfbjarne/api-tools:
* rolfbjarne/api-tools@c7d5208 Use the current .NET version to build.
* rolfbjarne/api-tools@254f0e0 [mono-api-info] Add support for comparing function pointers.
* rolfbjarne/api-tools@ebc175f Update the .editorconfig file
Diff: https://github.com/rolfbjarne/api-tools/compare/373fc1b50a23bf933aaeea7485ed7fb82c2cc268..c7d5208967d6d46fdebcac82ade488f00e1fcc50

Bump api-tools.

---

tests/monotouch-test/CoreServices/FSEventStreamTest.cs

Try to make CoreServices.FSEventStreamTest better by using shorter duration locks,
and re-checking success condition after timing out in case there’s a race condition.
Also improve exception reporting/logging a bit.
Ref: https://github.com/xamarin/maccore/issues/2630

[tests] Try to make CoreServices.FSEventStreamTest behave better.

---

tools/dotnet-linker/DocumentionComments.cs

This is a follow-up to #18854
The code that we use to generate method signatures still isn't working properly. Method signatures that contain constructed generic types are incorrect (this is a problem for example for UIGestureRecognizer subclasses in MAUI). We are also handling multidimensional arrays incorrectly.
Instead of implementing the signature builder ourselves, we can utilize the `DocCommentId.GetDocCommentId (member)` method from Mono.Cecil.Rocks.
```c#
void Method(IEnumerable<int> arg) { }
// before
[DynamicDependency ("Method(System.Collections.Generic.IEnumerable`1<System.Int32>)", typeof (MyClass))]
// after
[DynamicDependency ("Method(System.Collections.Generic.IEnumerable{System.Int32})", typeof (MyClass))]
```

[NativeAOT] Replace custom method signature builder with DocCommentId

---

msbuild/ILMerge.targets

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1877179/.

[release/8.0.1xx-rc1] [msbuild] Bundle System.Collections.Immutable.dll and System.Reflection.Metadata.dll in Xamarin.iOS.Tasks.dll.

---

msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.cs.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.de.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.es.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.fr.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.it.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ja.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ko.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pl.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pt-BR.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ru.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.tr.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hans.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hant.resx
tools/mtouch/TranslatedAssemblies/Errors.cs.resx
tools/mtouch/TranslatedAssemblies/Errors.de.resx
tools/mtouch/TranslatedAssemblies/Errors.es.resx
tools/mtouch/TranslatedAssemblies/Errors.fr.resx
tools/mtouch/TranslatedAssemblies/Errors.it.resx
tools/mtouch/TranslatedAssemblies/Errors.ja.resx
tools/mtouch/TranslatedAssemblies/Errors.ko.resx
tools/mtouch/TranslatedAssemblies/Errors.pl.resx
tools/mtouch/TranslatedAssemblies/Errors.pt-BR.resx
tools/mtouch/TranslatedAssemblies/Errors.ru.resx
tools/mtouch/TranslatedAssemblies/Errors.tr.resx
tools/mtouch/TranslatedAssemblies/Errors.zh-Hans.resx
tools/mtouch/TranslatedAssemblies/Errors.zh-Hant.resx

Localized file check-in by OneLocBuild Task: Build definition ID 17751: Build ID 8349044

---

tools/common/Frameworks.cs
tools/common/StaticRegistrar.cs
tools/common/Target.cs

[tools] Skip more types and namespaces when using Xcode 15.

---

tools/common/Frameworks.cs
tools/common/StaticRegistrar.cs
tools/common/Target.cs

[release/7.0.3xx] [tools] Skip more types and namespaces when using Xcode 15.

---

src/appkit.cs
tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-UIKit.ignore

Fixes https://github.com/xamarin/xamarin-macios/issues/12871.

[AppKit] Implement a few missing fields for NSToolbar. Fixes #12871.

---

Localize/loc/ja/tools/mtouch/Errors.resx.lcl
Localize/loc/ko/tools/mtouch/Errors.resx.lcl

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230909094918303 to Localization with localized lcls

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230909094918303 to Localization

---

Localize/loc/tr/tools/mtouch/Errors.resx.lcl
Localize/loc/zh-Hant/tools/mtouch/Errors.resx.lcl

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230909215004328 to Localization with localized lcls

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230909215004328 to Localization

---

Localize/loc/cs/tools/mtouch/Errors.resx.lcl
Localize/loc/es/tools/mtouch/Errors.resx.lcl
Localize/loc/fr/tools/mtouch/Errors.resx.lcl
Localize/loc/pt-BR/tools/mtouch/Errors.resx.lcl
Localize/loc/ru/tools/mtouch/Errors.resx.lcl
Localize/loc/zh-Hans/tools/mtouch/Errors.resx.lcl

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230910095932037 to Localization with localized lcls

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230910095932037 to Localization

---

Localize/loc/de/tools/mtouch/Errors.resx.lcl
Localize/loc/it/tools/mtouch/Errors.resx.lcl
Localize/loc/pl/tools/mtouch/Errors.resx.lcl

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230910215639275 to Localization with localized lcls

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20230910215639275 to Localization

---

tests/monotouch-test/CoreServices/FSEventStreamTest.cs

Ref: https://github.com/xamarin/maccore/issues/2630

[tests] Add some debug code to track down a random test failure.

---

tests/monotouch-test/CoreServices/FSEventStreamTest.cs

Maybe this will improve/fix https://github.com/xamarin/maccore/issues/2630.

[tests] Improve cleanup in FSEventStreamTest.

---

src/bgen/Generator.cs
tests/generator/BGenTests.cs
tests/generator/tests/internal-delegate.cs

Fixes https://github.com/xamarin/xamarin-macios/issues/15299.

[generator] Honor [Internal] on delegates. Fixes #15299.

---

mk/xamarin.mk

Ref: https://github.com/dotnet/xharness/issues/1075

Bump mlaunch to get fix for ARM64 calling convention.

---

tools/mtouch/TranslatedAssemblies/Errors.cs.resx
tools/mtouch/TranslatedAssemblies/Errors.de.resx
tools/mtouch/TranslatedAssemblies/Errors.es.resx
tools/mtouch/TranslatedAssemblies/Errors.fr.resx
tools/mtouch/TranslatedAssemblies/Errors.it.resx
tools/mtouch/TranslatedAssemblies/Errors.ja.resx
tools/mtouch/TranslatedAssemblies/Errors.ko.resx
tools/mtouch/TranslatedAssemblies/Errors.pl.resx
tools/mtouch/TranslatedAssemblies/Errors.pt-BR.resx
tools/mtouch/TranslatedAssemblies/Errors.ru.resx
tools/mtouch/TranslatedAssemblies/Errors.tr.resx
tools/mtouch/TranslatedAssemblies/Errors.zh-Hans.resx
tools/mtouch/TranslatedAssemblies/Errors.zh-Hant.resx

Localized file check-in by OneLocBuild Task: Build definition ID 17751: Build ID 8441644

---

msbuild/Directory.Build.props

The latest version has Component Governance fixes in it: https://github.com/xamarin/isignsharp/pull/52/files
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1869900
Backport of #19046

[xcode14.3] Updating Xamarin.iOS.HotRestart.Client to 1.0.125

---

msbuild/Directory.Build.props

The latest version has Component Governance fixes in it: https://github.com/xamarin/isignsharp/pull/52/files
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1869900
Backport of #19046

[net8.0] Updating Xamarin.iOS.HotRestart.Client to 1.0.125

---

Localize/loc/ja/tools/mtouch/Errors.resx.lcl
Localize/loc/ko/tools/mtouch/Errors.resx.lcl
Localize/loc/pt-BR/tools/mtouch/Errors.resx.lcl
Localize/loc/zh-Hans/tools/mtouch/Errors.resx.lcl

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20231012095835056 to Localization with localized lcls

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20231012095835056 to Localization

---

mk/xamarin.mk

[release/8.0.1xx] Bump mlaunch to get device support for iOS 17.

---

mk/xamarin.mk

[release/8.0.1xx-rc2] Bump mlaunch to get device support for iOS 17.

---

mk/xamarin.mk

Diff: https://github.com/xamarin/maccore/compare/ec9db0a40e..bfaf53ffa1

[xcode14.3] Bump mlaunch to get device support for iOS 17.

---

Localize/loc/de/tools/mtouch/Errors.resx.lcl
Localize/loc/es/tools/mtouch/Errors.resx.lcl
Localize/loc/it/tools/mtouch/Errors.resx.lcl
Localize/loc/ja/tools/mtouch/Errors.resx.lcl
Localize/loc/ko/tools/mtouch/Errors.resx.lcl
Localize/loc/pt-BR/tools/mtouch/Errors.resx.lcl
Localize/loc/zh-Hans/tools/mtouch/Errors.resx.lcl

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20231012215545808 to Localization with localized lcls

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20231012215545808 to Localization

---

Localize/loc/fr/tools/mtouch/Errors.resx.lcl
Localize/loc/zh-Hant/tools/mtouch/Errors.resx.lcl

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20231013102539627 to Localization with localized lcls

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20231013102539627 to Localization

---

mk/xamarin.mk

[release/8.0.1xx-rc2.1] Bump mlaunch to get device support for iOS 17.

---

Localize/loc/cs/tools/mtouch/Errors.resx.lcl
Localize/loc/pl/tools/mtouch/Errors.resx.lcl
Localize/loc/ru/tools/mtouch/Errors.resx.lcl
Localize/loc/tr/tools/mtouch/Errors.resx.lcl

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20231013215752948 to Localization with localized lcls

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20231013215752948 to Localization

---

dotnet/Workloads/SignList.xml

[release/8.0.1xx-rc2] [sign] Update SignList to match mlaunch list

---

dotnet/Workloads/SignList.xml

[release/8.0.1xx] [sign] Update SignList to match mlaunch list

---

dotnet/Workloads/SignList.xml

[release/8.0.1xx-rc2.1] [sign] Update SignList to match mlaunch list

---

Localize/loc/de/tools/mtouch/Errors.resx.lcl
Localize/loc/es/tools/mtouch/Errors.resx.lcl
Localize/loc/it/tools/mtouch/Errors.resx.lcl
Localize/loc/ja/tools/mtouch/Errors.resx.lcl
Localize/loc/ko/tools/mtouch/Errors.resx.lcl
Localize/loc/pt-BR/tools/mtouch/Errors.resx.lcl
Localize/loc/zh-Hans/tools/mtouch/Errors.resx.lcl

Bring changes from Localization branch #20231012.7

---

Localize/loc/cs/tools/mtouch/Errors.resx.lcl
Localize/loc/pl/tools/mtouch/Errors.resx.lcl
Localize/loc/ru/tools/mtouch/Errors.resx.lcl
Localize/loc/tr/tools/mtouch/Errors.resx.lcl

Bring changes from Localization branch #20231013.4

---

tools/mtouch/TranslatedAssemblies/Errors.cs.resx
tools/mtouch/TranslatedAssemblies/Errors.de.resx
tools/mtouch/TranslatedAssemblies/Errors.es.resx
tools/mtouch/TranslatedAssemblies/Errors.fr.resx
tools/mtouch/TranslatedAssemblies/Errors.it.resx
tools/mtouch/TranslatedAssemblies/Errors.ja.resx
tools/mtouch/TranslatedAssemblies/Errors.ko.resx
tools/mtouch/TranslatedAssemblies/Errors.pl.resx
tools/mtouch/TranslatedAssemblies/Errors.pt-BR.resx
tools/mtouch/TranslatedAssemblies/Errors.ru.resx
tools/mtouch/TranslatedAssemblies/Errors.tr.resx
tools/mtouch/TranslatedAssemblies/Errors.zh-Hans.resx
tools/mtouch/TranslatedAssemblies/Errors.zh-Hant.resx

Localized file check-in by OneLocBuild Task: Build definition ID 17751: Build ID 8543391

---

Localize/loc/ja/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/ru/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/zh-Hans/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/zh-Hant/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20231018095607687 to Localization with localized lcls

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20231018095607687 to Localization

---

Localize/loc/cs/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/de/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/es/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/it/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/pl/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/pt-BR/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20231018215636451 to Localization with localized lcls

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20231018215636451 to Localization

---

Localize/loc/fr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20231019095614926 to Localization with localized lcls

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20231019095614926 to Localization

---

Make.config
Makefile
builds/Makefile
dotnet/Makefile
mk/versions.mk
runtime/Makefile
src/Makefile
tools/common/Make.common

Was messing around with worktrees but our repo failed to build due to not identifying the proper git directory.
Fixes #18276

[build] Add support for worktree checkouts

---

Localize/loc/cs/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/de/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/es/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/it/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/pl/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/pt-BR/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl

Bring changes from Localization branch #20231018.4

---

src/NearbyInteraction/Enums.cs
src/nearbyinteraction.cs
tests/xtro-sharpie/api-annotations-dotnet/iOS-NearbyInteraction.ignore
tests/xtro-sharpie/api-annotations-dotnet/iOS-NearbyInteraction.todo
tests/xtro-sharpie/iOS-NearbyInteraction.ignore
tests/xtro-sharpie/iOS-NearbyInteraction.todo
tests/xtro-sharpie/watchOS-NearbyInteraction.ignore
tests/xtro-sharpie/watchOS-NearbyInteraction.todo

[release/8.0.1xx] [NerabyInteraction] Add support for xcode 15.

---

src/metalkit.cs
tests/xtro-sharpie/api-annotations-dotnet/iOS-MetalKit.todo
tests/xtro-sharpie/api-annotations-dotnet/macOS-MetalKit.todo
tests/xtro-sharpie/api-annotations-dotnet/tvOS-MetalKit.todo
tests/xtro-sharpie/iOS-MetalKit.todo
tests/xtro-sharpie/macOS-MetalKit.todo
tests/xtro-sharpie/tvOS-MetalKit.todo

[release/8.0.1xx] [MetalKit] Add support for Xcode 15.

---

src/storekit.cs
tests/xtro-sharpie/api-annotations-dotnet/tvOS-StoreKit.todo
tests/xtro-sharpie/tvOS-StoreKit.todo

[release/8.0.1xx] [Storekit] Add support for xcode 15.

---

src/safariservices.cs
tests/introspection/iOS/iOSApiProtocolTest.cs

[release/8.0.1xx] [MacCatalyst] Fix intro failures in catalyst on sonoma.

---

Localize/loc/ko/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/tr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20231025101855299 to Localization with localized lcls

LEGO: Pull request from lego/hb_2334f352-33a3-4aa6-b434-972a89595681_20231025101855299 to Localization

---

msbuild/Directory.Build.props

Updated to 1.1.0 to bring important changes and fixes on isignsharp:
- https://github.com/xamarin/isignsharp/pull/53
- https://github.com/xamarin/isignsharp/pull/54
- https://github.com/xamarin/isignsharp/pull/55
Backport of #19345

[release/8.0.1xx] [main] Updated Hot Restart client version

---

msbuild/Directory.Build.props

Updated to 1.1.0 to bring important changes and fixes on isignsharp:
- https://github.com/xamarin/isignsharp/pull/53
- https://github.com/xamarin/isignsharp/pull/54
- https://github.com/xamarin/isignsharp/pull/55

[main] Updated Hot Restart client version

---

src/uikit.cs

[UIKit] Add missing attrs for catalyst.

---

src/uikit.cs

Fixes #19353
Backport of #19355

[release/8.0.1xx] [UIKit] Add missing attrs for catalyst.

---

Localize/loc/ko/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Localize/loc/tr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl

Bring changes from Localization branch #20231025.9

---

src/bgen/BindingTouch.cs
src/bgen/ReferenceFixer.cs
src/bgen/SearchPathsAssemblyResolver.cs
src/generator.csproj

Placed the classes into their own cs files.

[Generator] Refactor ReferenceFixer and SearchPathsAssemblyResolver

---

src/bgen/BindingTouch.cs
src/bgen/TypeCache.cs

Pass the objects needed by the cache but not BT, that should help us in the future on how we are initializing the entire execution.

[Generator] Do not couple BindingTouch to the TypeCache.

---

src/bgen/BindingTouch.cs
src/bgen/NamespaceManager.cs

Lets remove little by little the need to have an object with all the knowledge, BT has a God complex that is not helping us.

[Generator] Remove the BT reference from the NSManager.

---

msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ko.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.tr.resx

Localized file check-in by OneLocBuild Task: Build definition ID 17751: Build ID 8672659

---

msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ko.resx
msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.tr.resx

Localized file check-in by OneLocBuild Task: Build definition ID 17751: Build ID 8641933

---

src/bgen/Generator.cs
src/bgen/Nomenclator.cs
tests/generator/NomenclatorTests.cs

Moved the method to the right object and add tests.

[Generator] The Nomenclator does know how to get the name of a type.

---

src/AppKit/Enums.cs
tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.ignore

Fixes https://github.com/xamarin/xamarin-macios/issues/19555.

[AppKit] Update the NSBezelStyle enum according to latest headers. Fixes #19555.

---

tests/EmbeddedResources/dotnet/shared.csproj
tests/bindings-test/ProtocolTest.cs
tests/bindings-test/dotnet/shared.csproj
tests/common/TestRuntime.cs
tests/monotouch-test/AVFoundation/UtilitiesTest.cs
tests/monotouch-test/Asserts.cs
tests/monotouch-test/AudioToolbox/AudioQueueTest.cs
tests/monotouch-test/AudioUnit/AudioUnitTest.cs
tests/monotouch-test/CoreFoundation/ProxyTest.cs
tests/monotouch-test/CoreGraphics/AffineTransformTest.cs
tests/monotouch-test/CoreMedia/BlockBufferTest.cs
tests/monotouch-test/Metal/MTLDeviceTests.cs
tests/monotouch-test/ModelIO/MDLAnimatedValueTypesTests.cs
tests/monotouch-test/NaturalLanguage/NLTaggerTest.cs
tests/monotouch-test/ObjCRuntime/ClassTest.cs
tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
tests/monotouch-test/SystemConfiguration/CaptiveNetworkTest.cs
tests/monotouch-test/UIKit/DirectionalEdgeInsetsTest.cs
tests/monotouch-test/UIKit/EdgeInsetsTest.cs
tests/monotouch-test/UIKit/FloatRangeTest.cs
tests/monotouch-test/dotnet/shared.csproj
tests/monotouch-test/mono/ConfigTest.cs

And also make sure we don't introduce any new warnings by making them errors.

[tests] Fix all the remaining warnings in monotouch-test, EmbeddedResources and bindings-test.

---

tests/cecil-tests/BlittablePInvokes.cs

The current reults are hard/impossible to understand by a human. Fix the way we report the error so that we go from:
```
(AVFoundation.AVAudioVoiceProcessingOtherAudioDuckingConfiguration ObjCRuntime.Messaging::AVAudioVoiceProcessingOtherAudioDuckingConfiguration_objc_msgSend(System.IntPtr,System.IntPtr), )
```
to
```
AVFoundation.AVAudioVoiceProcessingOtherAudioDuckingConfiguration ObjCRuntime.Messaging::AVAudioVoiceProcessingOtherAudioDuckingConfiguration_objc_msgSend(System.IntPtr,System.IntPtr) - The return type is AVFoundation.AVAudioVoiceProcessingOtherAudioDuckingConfiguration: (EnableAdvancedDucking: has a [MarshalAs] attribute)
at no match Mono.Cecil.MethodDefinition
```
fulle example here: https://gist.github.com/mandel-macaque/30f54ac5b0e22454d57644d2b7b94eca

[Tests] Fix the Blittable tests in cecil to provide a reason for the failure.

---

builds/Versions-MacCatalyst.plist.in
builds/Versions-iOS.plist.in
builds/Versions-macOS.plist.in
builds/Versions-tvOS.plist.in

[build] Add missing versions.

---

msbuild/Directory.Build.props

Updating HotRestart package version in order to pick up recent changes to isignsharp.

Updating HotRestart package version

---

tools/devops/automation/templates/windows/build.yml

[release/8.0.1xx-xcode15.1] [CI] Ensure that we use the upload prefix for the config file.

---

tests/package-mac-tests.sh

Funny how hard boolean logic is 😐
Ref: 7003d324ef8d159f92b043500c9614f17b0ecca2

[tests] Fix condition to not build packaged macOS tests in parallel in CI.

---

configure
tools/devops/automation/templates/build/api-diff-stage.yml
tools/devops/automation/templates/build/build-mac-tests-stage.yml
tools/devops/automation/templates/build/build-stage.yml
tools/devops/automation/templates/main-stage.yml

[release/8.0.1xx-xcode15.1] Add config stage for CI

---

tests/Makefile

We already build the msbuild solution with .NET, so this is just playing
catchup.

[tests] Build the msbuild tests with .NET.

---

tests/cecil-tests/Helper.cs

Add the ability to automatically update the source code for known failures in
cecil-tests if a specific environment variable is set.

[tests] Add the ability to automatically update known failures in cecil-tests.

---

tools/devops/automation/templates/build/api-diff-stage.yml

When we have a warning we get a different error result. What we want to do is continure when we succeed and when we have a warning.

[CI] Only upload when we have a warning or a success.

---

tools/devops/automation/templates/build/api-diff-stage.yml
tools/devops/automation/templates/build/build-mac-tests-stage.yml
tools/devops/automation/templates/build/build-stage.yml
tools/devops/automation/templates/mac/stage.yml
tools/devops/automation/templates/main-stage.yml
tools/devops/automation/templates/release/vs-insertion-prep.yml
tools/devops/automation/templates/sign-and-notarized/funnel.yml
tools/devops/automation/templates/sign-and-notarized/prepare-pkg-stage.yml
tools/devops/automation/templates/tests/stage.yml
tools/devops/automation/templates/windows/stage.yml

Following https://github.com/xamarin/xamarin-macios/pull/19491 , this change moves the AgentPoolSelector to the Config stage since it is deterministic per build.
backport of #19546

[release/8.0.1xx-xcode15.1] Centralize AgentPoolSelector

---

tests/monotouch-test/Foundation/UserDefaultsTest.cs

Also do some cleanup in a related test.
Ref: https://github.com/xamarin/maccore/issues/2488

[tests] Adjust UserDefaultsTest.Ctor_UserName to try to fix a random test failure.

---

src/AudioToolbox/AudioFile.cs
tests/cecil-tests/BlittablePInvokes.KnownFailures.cs

[AudioToolbox] Make P/Invokes in AudioFile.cs have blittable signatures.

---

tools/devops/automation/build-pipeline.yml

We do not have M1 bots in the untrusted pool

[tests] Update configuration mac_14_m1 -> mac_14_x64

---

mk/xamarin.mk
src/Makefile

[ADR] Fix verbosity

---

tools/devops/automation/templates/governance-checks.yml

Ref: https://github.com/opensource-microsoft/docs/blob/main/docs/tools/cg/announcements.md#mend-aka-whitesource-retirement-as-a-vulnerability-provider

[devops] Remove the Whitesource task.

---

tools/devops/automation/templates/governance-checks.yml

Ref: https://github.com/opensource-microsoft/docs/blob/main/docs/tools/cg/announcements.md#mend-aka-whitesource-retirement-as-a-vulnerability-provider
Backport of #20088

[release/8.0.1xx-xcode15.1] [devops] Remove the Whitesource task.

---

tools/devops/automation/templates/governance-checks.yml

Ref: https://github.com/opensource-microsoft/docs/blob/main/docs/tools/cg/announcements.md#mend-aka-whitesource-retirement-as-a-vulnerability-provider
Backport of https://github.com/xamarin/xamarin-macios/pull/20088

[release/7.0.3xx][devops] Remove the Whitesource task.

---

tools/devops/automation/templates/governance-checks.yml

Ref: https://github.com/opensource-microsoft/docs/blob/main/docs/tools/cg/announcements.md#mend-aka-whitesource-retirement-as-a-vulnerability-provider
Backport of #20088

[release/9.0.1xx-preview1] [devops] Remove the Whitesource task.

---

tools/devops/automation/scripts/Governance.psm1
tools/devops/automation/scripts/MaciosCI.psd1
tools/devops/automation/templates/common/configure.yml
tools/devops/automation/templates/governance/apiscan.yml
tools/devops/automation/templates/governance/general.yml
tools/devops/automation/templates/governance/stage.yml
tools/devops/automation/templates/governance/tsa-upload.yml
tools/devops/automation/templates/main-stage.yml

Revert the revert and fix the code.

[CI] Create governance stage to run APIScan in parallel.

---

src/Accessibility/AXHearingUtilities.cs
tests/cecil-tests/BlittablePInvokes.KnownFailures.cs

[Accessibility] Make P/Invokes have blittable signatures.

---

tools/devops/automation/templates/mac/build.yml
tools/devops/automation/templates/tests/build.yml
tools/devops/automation/templates/tests/run-tests.yml
tools/devops/automation/templates/windows/build.yml

Bring all the changes for the retry logic found in main to have the release branch greener.

[CI][net8.0.1xx-xcode15] Backport retry logic.

---

tools/devops/automation/templates/sign-and-notarized/upload-azure.yml

We have had a few errros when performing the upload with the old version of the task. Bump to the new own to see if it is more stable.

[CI] Bump AzureFileCopy task version.

---

tools/devops/automation/templates/build/build.yml

Mono does give issues we should retry before we fail.

[CI] Retry the installation of products.

---

tests/dotnet/UnitTests/ProjectTest.cs

Follow up to https://github.com/xamarin/xamarin-macios/pull/20054

[dotnet] Fix sourcelink test failure

---

msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx
msbuild/Xamarin.MacDev.Tasks/Tasks/CollectBundleResources.cs
tools/common/PathUtils.cs

Ref: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1935561
Fixes https://github.com/xamarin/xamarin-macios/issues/20053.

[msbuild] Detect problems with long paths, and try to show a bit more helpful information. Fixes #20053.

---

runtime/runtime.m

The stack trace from unhandled exception is now:
Unhandled managed exception: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (System.ArgumentOutOfRangeException)
at System.Collections.Generic.List`1[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].get_Item(Int32 index)
at CrashiOS.RootViewController.GetItem() in /Users/rolf/test/bugs/StackTraceIssue/CrashiOS/RootViewController.cs:line 19
at CrashiOS.RootViewController.<.ctor>b__1_0(Object _, EventArgs _) in /Users/rolf/test/bugs/StackTraceIssue/CrashiOS/RootViewController.cs:line 12
at UIKit.UIBarButtonItem.Callback.Call(NSObject sender) in xamarin-macios/src/UIKit/UIBarButtonItem.cs:line 33
--- End of stack trace from …

[release/8.0.1xx-xcode15.1] [runtime] Fix conserving stack trace when re-throwing marshalled exceptions. Fixes #19417.

---

docs/apple-privacy-manifest.md

Fix Apple Privacy Manifest doc typos

---

.github/workflows/yamllint.yml

Execute yamllint on the pipelines code and post a github formatted result in a comment.

[CI] Run yamllint as an action to post.

---

src/CoreMedia/CMBufferQueue.cs
tests/cecil-tests/BlittablePInvokes.KnownFailures.cs

[CoreMedia] Make the P/Invokes in CMBufferQueue have blittable signatures.

---

src/CoreMedia/CMAttachmentBearer.cs
tests/cecil-tests/BlittablePInvokes.KnownFailures.cs

[CoreMedia] Make the remaining P/Invokes in have blittable signatures.

---

tools/devops/automation/templates/governance/apiscan.yml

[release/9.0.1xx-preview3] [APIScan] Do not use pats.

---

docs/apple-privacy-manifest.md

Update documentation for binding projects

Apple Privacy Manifest doc updates

---

.github/workflows/autoformat.yml
.github/workflows/autoformat2.yml

This bumps the required node version from v16 to v20.

[actions] Bump autoformat[-push] to their latest versions.

---

.github/workflows/update-single-platform-branches.yml

It only took me two and a half months to notice the action wasn't working...

[actions] Add permissions block to the 'update-single-platform-branches' action.

---

Make.config

[release/8.0.1xx-xcode15.0] Don't use azureedge.net CDN

---

Make.config

[release/7.0.3xx] Don't use azureedge.net CDN

---

Make.config

[release/8.0.1xx-xcode15.1] Don't use azureedge.net CDN

---

src/CoreText/CTRunDelegate.cs
tests/cecil-tests/BlittablePInvokes.KnownFailures.cs

[CoreText] Make P/Invokes in CTRunDelegate have blittable signatures.

---

Make.config

[release/7.0.3xx] Use legacy mono-sdks from download.mono-project.com

---

Make.config

[release/8.0.1xx-xcode15.1] Use legacy mono-sdks from download.mono-project.com

---

Make.config

[release/8.0.1xx-xcode15.0] Use legacy mono-sdks from download.mono-project.com

---

tools/devops/automation/templates/sign-and-notarized/upload-azure.yml

Update the service connection used to upload to one backed by managed identity.

Update service connection

---

src/ObjCRuntime/Class.cs
src/ObjCRuntime/Protocol.cs
src/ObjCRuntime/Runtime.CoreCLR.cs
src/ObjCRuntime/Runtime.cs
src/ObjCRuntime/Selector.cs
tests/cecil-tests/BlittablePInvokes.KnownFailures.cs

[ObjCRuntime] Make P/Invokes have blittable signatures.

---

mk/xamarin.mk

* xamarin/maccore@7dbab91212 [mlaunch] Bump to .NET 8.
* xamarin/maccore@79ae2e4e7e [Mlaunch] Create Vulcan ready files of mlaunch.
* xamarin/maccore@f8f70b23a4 [mlaunch] List devices as they're found in --listdev.
Diff: https://github.com/xamarin/maccore/compare/39a7e52166..7dbab91212

Bump mlaunch.

---

tools/devops/automation/templates/sign-and-notarized/upload-azure.yml

Backport of https://github.com/xamarin/xamarin-macios/pull/20554

[release/9.0.1xx-preview4] Update service connection

---

tools/devops/automation/templates/sign-and-notarized/upload-azure.yml

Manual backport of https://github.com/xamarin/xamarin-macios/pull/20554

[release/8.0.1xx-xcode15.1] Update service connection

---

tools/devops/automation/scripts/VSTS.psm1

[release/8.0.1xx-xcode15.1] [CI] Do not fail a build if we could not set the tags.

---

tools/devops/automation/scripts/VSTS.psm1

[release/8.0.1xx-xcode15.0] [CI] Do not fail a build if we could not set the tags.

---

tests/monotouch-test/ImageIO/CGImageSourceTest.cs

The exact results seem to depend on a lot of factors, so just accept them all.

[monotouch-test] Be a bit more lenient with expected results in CGImageSourceTest.

---

.github/workflows/bump-global-json.yml

Include the PR number and title in the commit message.
This makes GitHub emails a bit more descriptive (since there are often
multiple PRs where global.json is bumped).

[actions] Improve commit message in the bump-global-json action.

---

tools/devops/automation/templates/tests/stage.yml

Ref: https://twcdot.visualstudio.com/Data/_workitems/edit/116722

[devops] Disable CodeQL on arm64, it's causing problems.

---

system-dependencies.sh
tools/siminstaller/Makefile
tools/siminstaller/Program.cs
tools/siminstaller/siminstaller.csproj

In addition to being good by itself, by fixing all the resulting nullability
warnings, this random problem goes away:
Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
at xsiminstaller.MainClass.Main (System.String[] args) [0x006ca] in /Users/builder/azdo/_work/4/s/xamarin-macios/tools/siminstaller/Program.cs:228
[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
at xsiminstaller.MainClass.Main (System.String[] args) [0x006ca] in /Users/builder/azdo/_work/4/s/xamarin-macios/tools/siminstaller/Program.cs:228
Also use HttpClient instead of WebClient (which is deprecated).

[siminstaller] Convert to .NET project.

---

tools/devops/automation/build-pipeline.yml
tools/devops/automation/build-pull-request.yml
tools/devops/automation/templates/common/publis-pipeline-artifact.yml
tools/devops/governance/CredScanSuppressions.json
tools/devops/governance/PoliCheckExclusions.xml
tools/devops/governance/baselines.gdnbaselines
tools/devops/governance/suppress.gdnsuppress
tools/devops/governance/tsa_config.gdntsa

Move the config files to the macios repo since they have no private info.

[CI] Reduce dependecies on the maccore repo.

---

tools/devops/automation/templates/release/vs-insertion-prep.yml
tools/devops/automation/templates/sign-and-notarized/sign-and-notarized.yml

On draft waiting for https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9845350&view=results

[CI] Disable CodeQL for signing since it gives problems.

---

tools/devops/automation/build-pipeline.yml
tools/devops/automation/templates/release/vs-insertion-prep.yml

We have had issues with the signing steps, allow us to grab all bin logs to be able to debug.

[CI] Ensure that the signing jobs do upload binlogs.

---

src/automaticassessmentconfiguration.cs
tests/xtro-sharpie/api-annotations-dotnet/iOS-AutomaticAssessmentConfiguration.todo
tests/xtro-sharpie/api-annotations-dotnet/macOS-AutomaticAssessmentConfiguration.todo
tests/xtro-sharpie/iOS-AutomaticAssessmentConfiguration.todo
tests/xtro-sharpie/macOS-AutomaticAssessmentConfiguration.todo

Note: there were no changes in beta 2 and beta 3.

[AutomaticAssessmentConfiguration] Implement Xcode 16.0 beta 1, beta 2 and beta 3 changes.

---

src/Contacts/CNEnums.cs
tests/xtro-sharpie/api-annotations-dotnet/iOS-Contacts.todo
tests/xtro-sharpie/api-annotations-dotnet/macOS-Contacts.todo
tests/xtro-sharpie/iOS-Contacts.todo
tests/xtro-sharpie/macOS-Contacts.todo
tests/xtro-sharpie/watchOS-Contacts.todo

Note: there were no changes in beta 2 and beta 3.

[Contacts] Implement Xcode 16.0 beta 1, beta 2 and beta 3 changes.

---

src/iosurface.cs
tests/xtro-sharpie/api-annotations-dotnet/iOS-IOSurface.todo
tests/xtro-sharpie/api-annotations-dotnet/macOS-IOSurface.todo
tests/xtro-sharpie/api-annotations-dotnet/tvOS-IOSurface.todo
tests/xtro-sharpie/iOS-IOSurface.todo
tests/xtro-sharpie/macOS-IOSurface.todo
tests/xtro-sharpie/tvOS-IOSurface.todo

[IOSurface] Implement Xcode 16.0 beta 1, beta 2 and beta 3 changes.

---

src/callkit.cs
tests/xtro-sharpie/api-annotations-dotnet/iOS-CallKit.todo
tests/xtro-sharpie/iOS-CallKit.todo
tests/xtro-sharpie/watchOS-CallKit.todo

[CallKit] Implement Xcode 16.0 beta 1, beta 2 and beta 3 changes.

---

src/fileprovider.cs
tests/xtro-sharpie/api-annotations-dotnet/iOS-FileProvider.todo
tests/xtro-sharpie/api-annotations-dotnet/macOS-FileProvider.todo
tests/xtro-sharpie/iOS-FileProvider.todo
tests/xtro-sharpie/macOS-FileProvider.todo

Note: there were no changes in beta 3.

[FileProvider] Implement Xcode 16.0 beta 1, beta 2 and beta 3 changes.

---

src/linkpresentation.cs
tests/xtro-sharpie/api-annotations-dotnet/iOS-LinkPresentation.todo
tests/xtro-sharpie/api-annotations-dotnet/macOS-LinkPresentation.todo
tests/xtro-sharpie/api-annotations-dotnet/tvOS-LinkPresentation.todo
tests/xtro-sharpie/iOS-LinkPresentation.todo
tests/xtro-sharpie/macOS-LinkPresentation.todo
tests/xtro-sharpie/tvOS-LinkPresentation.todo

[LinkPresentation] Implement Xcode 16.0 beta 1, beta 2 and beta 3 changes.

---

src/mediaaccessibility.cs
tests/xtro-sharpie/api-annotations-dotnet/iOS-MediaAccessibility.todo
tests/xtro-sharpie/api-annotations-dotnet/macOS-MediaAccessibility.todo
tests/xtro-sharpie/api-annotations-dotnet/tvOS-MediaAccessibility.todo
tests/xtro-sharpie/iOS-MediaAccessibility.todo
tests/xtro-sharpie/macOS-MediaAccessibility.todo
tests/xtro-sharpie/tvOS-MediaAccessibility.todo

[MediaAccessibility] Implement Xcode 16.0 beta 1, beta 2 and beta 3 changes.

---

tools/devops/automation/build-pipeline.yml
tools/devops/automation/templates/build/build-pkgs.yml
tools/devops/automation/templates/build/build-stage.yml
tools/devops/automation/templates/build/build.yml
tools/devops/automation/templates/main-stage.yml

I have cleaned the yaml files while I was trying to debug the issue with the provisioning of the simulators on Xcode 16. We should  back port this change there.

[CI] Clean a number of yamllint issues and update a name to help debug.

---

NuGet.config
eng/Version.Details.xml
eng/Versions.props
global.json

Reverts xamarin/xamarin-macios#20900
merged this too soon, it breaks windows tests

Revert "[release/8.0.1xx-xcode15.4] Update dependencies from dotnet/installer"

---

dotnet/generate-workloadmanifest-json.csharp
dotnet/generate-workloadmanifest-targets.csharp

Manual backport of https://github.com/xamarin/xamarin-macios/pull/20795

[release/8.0.1xx-xcode15.4] [dotnet] Fix workload reference to .NET 8 packages.

---

dotnet/generate-workloadmanifest-json.csharp
dotnet/generate-workloadmanifest-targets.csharp

Reverts xamarin/xamarin-macios#20929 this is not needed the error was at insertion time

Revert "[release/8.0.1xx-xcode15.4] [dotnet] Fix workload reference to .NET 8 packages."

---

eng/Version.Details.xml
eng/Versions.props

darc update-dependencies --id 233261

[release/9.0.1xx-preview7] Bump dependencies to coherent build

---

dotnet/targets/Xamarin.Shared.Sdk.targets

(cherry picked from commit 201d2dbfcf4bda0fce35ae8b25fe093570819c78)

[release/9.0.1xx-preview7] [xcsync] Add open argument

---

tools/xcsync/Makefile

(cherry picked from commit fe3949ea394ded05c39e3f47e8b056698e5030b3)

[net9.0] [xcsync] Rename xcsync script to dotnet-xcsync

---

src/bgen/Generator.cs
src/bgen/TypeManager.cs
tests/generator/BGenTests.cs
tests/generator/tests/delegate-nullable-return.cs

Fixes https://github.com/xamarin/xamarin-macios/issues/17109.

[bgen] Fix generating delegates with nullable return types. #17109.

---

NuGet.config
eng/Version.Details.xml
eng/Versions.props

[release/9.0.1xx-rc1] [net9.0] Bump .NET Xcode 15.4 packages to latest

---

src/imageio.cs
tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-ImageIO.todo
tests/xtro-sharpie/api-annotations-dotnet/iOS-ImageIO.todo
tests/xtro-sharpie/api-annotations-dotnet/macOS-ImageIO.todo
tests/xtro-sharpie/api-annotations-dotnet/tvOS-ImageIO.todo
tests/xtro-sharpie/iOS-ImageIO.todo
tests/xtro-sharpie/macOS-ImageIO.todo
tests/xtro-sharpie/tvOS-ImageIO.todo
tests/xtro-sharpie/watchOS-ImageIO.todo

Note: there were no changes in beta 5 or beta 6.

[ImageIO] Implement Xcode 16 beta 4-6 changes.

---

tools/devops/automation/scripts/VSTS.psm1

Keep working towards simplifying the configuration script.

[CI] Move the step that sets the vsts labels.

---

tests/xtro-sharpie/api-annotations-dotnet/iOS-ContactProvider.ignore
tests/xtro-sharpie/api-annotations-dotnet/iOS-ContactProvider.todo
tests/xtro-sharpie/iOS-ContactProvider.ignore
tests/xtro-sharpie/iOS-ContactProvider.todo

For all intents and purposes it's Swift only.

[ContactProvider] Don't bind this framework.

---

tests/bgen/bgen-tests.csproj
tests/generator/BGenTests.cs

And make warnings report as errors, so this doesn't happen again.

[bgen] Fix compiler warnings.

---

tools/devops/automation/build-pipeline.yml
tools/devops/automation/build-pull-request.yml
tools/devops/automation/templates/main-stage.yml
tools/devops/automation/templates/pipelines/run-tests-pipeline.yml
tools/devops/automation/templates/sign-and-notarized/funnel.yml
tools/devops/automation/templates/sign-and-notarized/upload-azure.yml
tools/devops/automation/templates/tests-stage.yml
tools/devops/automation/templates/variables.yml

[release/8.0.1xx-xcode15.4] [CI] Remove Azure Storage usage

---

builds/Makefile

😡 https://github.com/dotnet/sdk/issues/11432

[builds] Fix restoring ilrepack.

---

eng/Version.Details.xml
eng/Versions.props

[main] Bump to the correct .NET 8/Xcode 15.0 version

---

tools/devops/automation/templates/tests/stage.yml

* Dump once, but correctly sorted, taking values with newlines into account.
* Dump the bot's IP address as well.

[devops] Improve environment dumping.

---

tools/devops/automation/run-post-ci-build-macos-tests.yml
tools/devops/automation/run-post-pr-build-macos-tests.yml
tools/devops/automation/templates/pipelines/run-macos-tests-pipeline.yml
tools/devops/automation/templates/pipelines/run-tests-pipeline.yml
tools/devops/automation/templates/tests-stage.yml

Reverts xamarin/xamarin-macios#21247 
This is a revert of a revert that was not needed.

Revert "Revert "[CI] Split the sim tests and the macOS tests. (#21215)""

---

tools/devops/automation/scripts/show_env.ps1

Also show:
* The network configuration
* The load on the system / cpu usage (top)

[devops] Add a bit more info when showing the enviroment.

---

tests/monotouch-test/ObjCRuntime/RegistrarTestGenerated.cs

Also remove some outdated watchOS ignores.
Ref: https://github.com/xamarin/xamarin-macios/issues/19781

[tests] Ignore a few tests that fail on Mac Catalyst/arm64.

---

tools/devops/automation/run-post-pr-build-api-scan.yml
tools/devops/automation/templates/governance/apiscan.yml
tools/devops/automation/templates/governance/stage.yml
tools/devops/automation/templates/pipelines/run-api-scan.yml

Allow the pipeline to run correctly. We could not test it before we landed the yaml, this commit fixes all the issues we have.

[CI] Fix errors in the new apiscan pipelines.

---

tests/monotouch-test/ObjCRuntime/RegistrarTestGenerated.cs

Ref: https://github.com/xamarin/xamarin-macios/issues/19781

[tests] Ignore a few tests that fail on iOS Simulator/arm64.

---

tests/monotouch-test/ObjCRuntime/RegistrarTestGenerated.cs

Ref: https://github.com/xamarin/xamarin-macios/issues/19781
Backport of #21322 and #21403.

[net9.0] [tests] Ignore a few tests that fail on desktop/arm64.

---

dotnet/BundleContents.md

Ref: https://github.com/xamarin/xamarin-macios/issues/20947

[dotnet] Improve documentation about the PublishFolderType metadata a bit.

---

tests/test-libraries/nugets/DynamicLibrariesInRuntimesNativeDirectory/Makefile
tests/test-libraries/nugets/FrameworksInRuntimesNativeDirectory/Makefile
tests/test-libraries/nugets/XCFrameworkWithStaticLibraryInRuntimesNativeDirectory/Makefile
tests/test-libraries/nugets/shared.mk

Also avoid the 'nuget' binary, which requires Mono.

[tests] Simplify/unify code to build test NuGets.

---

.gitmodules
Make.config
mk/versions.mk
runtime/Makefile

Remove the macios-binaries dependency.

---

msbuild/Directory.Build.props

Brings some important fixes on client and agent side to handle agent status notifications better
Diff: https://github.com/xamarin/Xamarin.Messaging/compare/a3a1e00e5a89ec27bc9e19ddc596e2e63e3ac017..6b35d9de966802709767d61306917642ff72f622

Update Xamarin.Messaging to 2.2.10

---

tests/common/ConfigurationXUnit.cs
tests/rgen/Microsoft.Macios.Generator.Tests/BindingSourceGeneratorGeneratorTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/Extensions/BaseTypeDeclarationSyntaxExtensionsTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/Extensions/MemberDeclarationSyntaxExtensionsTests.cs

There is no need to write a line per platform when we can use an attribvute for that.

[Rgen] Simplify the way we execute tests on all platforms.

---

src/appkit.cs
tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.ignore

Fixes https://github.com/xamarin/xamarin-macios/issues/21598.

[AppKit] Fix nullability for numerous NSView members. Fixes #21598.

---

src/uikit.cs
tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-UIKit.ignore
tests/xtro-sharpie/api-annotations-dotnet/iOS-UIKit.ignore
tests/xtro-sharpie/api-annotations-dotnet/tvOS-UIKit.ignore

Fixes https://github.com/xamarin/xamarin-macios/issues/21598.

[UIKit] Fix nullability for numerous UIView members. Fixes #21598.

---

docs/api/CoreLocation/CLLocationManager.xml
src/corelocation.cs
tests/introspection/ApiTypoTest.cs

Fixes https://github.com/xamarin/xamarin-macios/issues/21641.

[CoreLocation] Fix misspelled field. Fixes #21641.

---

tests/common/ConfigurationXUnit.cs
tests/rgen/Microsoft.Macios.Generator.Tests/Extensions/NamedTypeSymbolExtensionsTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/Extensions/TypeSymbolExtensionsTests.cs

Add a new attribute that will take an IEnumerable with parameters of data driven tests and generate the needed parameters per platform.
PS: I got tired on tying a foreach ;)

[RGen] Simplify the use of IEnumerables on all platforms in xUnit.

---

src/rgen/Microsoft.Macios.Generator/AttributesNames.cs
src/rgen/Microsoft.Macios.Generator/DataModel/CodeChanges.cs
src/rgen/Microsoft.Macios.Generator/DataModel/CodeChangesEqualityComparer.cs
src/rgen/Microsoft.Macios.Generator/DataModel/Method.cs
src/rgen/Microsoft.Macios.Generator/DataModel/MethodComparer.cs
src/rgen/Microsoft.Macios.Generator/DataModel/MethodsEqualityComparer.cs
src/rgen/Microsoft.Macios.Generator/DataModel/Parameter.cs
tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/CodeChangesComparerTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/CodeChangesTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/MethodComparerTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/MethodEqualityComparerTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/MethodTests.cs

Track the following data from new methods:
1. Method class owner.
2. Method name.
3. Method return type.
4. Method parameters.

[Rgen] Update data model to detect changes in methods.

---

src/Network/NWProxyConfig.cs
src/bgen/Caches/TypeCache.cs
src/frameworks.sources
src/webkit.cs
tests/xtro-sharpie/api-annotations-dotnet/common-WebKit.ignore

Fixes https://github.com/xamarin/xamarin-macios/issues/19259.

[WebKit] Add WKWebsiteDataStore.ProxyConfigurations. Fixes #19259.

---

dotnet/targets/dotnet-xcsync.targets

Redirect users to the documention for the .NET Global tool

Remove xcsync target functionality

---

DOWNLOADS.md

Update DOWNLOADS doc regarding legacy Xamarin deprecation.

---

Make.config
mk/xamarin-reset.sh
mk/xamarin.mk
src/Makefile
tools/devops/automation/build-pipeline.yml
tools/devops/automation/build-pull-request.yml
tools/devops/automation/run-post-ci-build-vs-insertion.yml
tools/devops/automation/templates/common/checkout.yml
tools/devops/automation/templates/pipelines/api-diff-pipeline.yml
tools/devops/automation/templates/pipelines/build-pipeline.yml
tools/devops/automation/templates/pipelines/run-api-scan.yml
tools/devops/automation/templates/pipelines/run-macos-tests-pipeline.yml
tools/devops/automation/templates/pipelines/run-tests-pipeline.yml

Requires https://dev.azure.com/devdiv/DevDiv/_git/macios-adr/pullrequest/597524

Build ADR from macios-adr

---

dotnet/Makefile
dotnet/Workloads/SignList.xml

This is a follow-up to b4ba75d000aefb45817582daad237ec726659724.

[dotnet] Fix paths to the zipped prebuilt app bundle.

---

tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-AVFoundation.todo
tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-MLCompute.todo
tests/xtro-sharpie/api-annotations-dotnet/common-MapKit.ignore
tests/xtro-sharpie/api-annotations-dotnet/iOS-AVFoundation.todo
tests/xtro-sharpie/api-annotations-dotnet/macOS-AVFoundation.todo
tests/xtro-sharpie/api-annotations-dotnet/macOS-MLCompute.todo
tests/xtro-sharpie/xtro-sharpie/DeprecatedCheck.cs

This fixes a few unnecessary ignores we have.

[xtro] Don't treat APIs that are deprecated far in the future as actually deprecated.

---

tests/monotouch-test/AVFoundation/AVAudioSinkNodeTest.cs
tests/monotouch-test/AVFoundation/AVAudioSourceNodeTest.cs

Fixes https://github.com/xamarin/maccore/issues/2956.

[tests] Apple fixed audio recording in the simulator, so remove corresponding ignores.

---

src/rgen/Microsoft.Macios.Generator/DataModel/Event.cs
tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/ClassCodeChangesTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/CodeChangesComparerTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/EventEqualityComparerTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/EventTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/InterfaceCodeChangesTests.cs

Add the supported platforms as part of the data model and update tests accodingly.

[RGen] Add the platform availability as part of the event data model.

---

tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/EnumMemberCodeChangesTests.cs

Two PRs changed the same test, one update the string, the other one added new tests. The CI ran but it was not merged with main resulting in the tests passing in the PR but failing on main

[RGen] Fix failing tests after a PR merge race.

---

src/rgen/Microsoft.Macios.Bindings.Analyzer/Microsoft.Macios.Bindings.Analyzer.csproj
src/rgen/Microsoft.Macios.Generator/Attributes/BindingTypeData.cs
src/rgen/Microsoft.Macios.Generator/AttributesNames.cs
src/rgen/Microsoft.Macios.Generator/DataModel/CodeChanges.cs
src/rgen/Microsoft.Macios.Generator/Extensions/SemanticModelExtensions.cs
src/rgen/Microsoft.Macios.Generator/Extensions/TypeSymbolExtensions.cs
tests/rgen/Microsoft.Macios.Generator.Tests/AttributesNamesTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/ClassCodeChangesTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/CodeChangesComparerTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/CodeChangesEqualityComparerTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/InterfaceCodeChangesTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/Extensions/SemanticModelExtensionsTests.cs

This addition allows the code emitters to access the binding type configuration.

[Rgen] Add the BindingData struct as part as the code struct.

---

src/rgen/Microsoft.Macios.Generator/DataModel/Method.cs
tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/ClassCodeChangesTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/CodeChangesComparerTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/InterfaceCodeChangesTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/MethodComparerTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/MethodEqualityComparerTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/MethodTests.cs

The data is needed to generate the code AND we want to regenerate the code if the data is changedo by the user.

[Rgen] Add the export attribute data in the method data model.

---

src/rgen/Microsoft.Macios.Generator/DataModel/Property.cs
tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/PropertyTests.cs

Calculate the named based on the property name and store it to not recalcualte it.

[Rgen] Provide a property that will return the name of the backing field for a property.

---

tools/apidiff/Makefile
tools/apidiff/report-status.sh
tools/devops/automation/build-pull-request.yml

Github is not rendering the emojis correctly withut a space, for example: https://github.com/xamarin/xamarin-macios/pull/21911#issuecomment-2575277732

[API] Add a space aroud the emojis.

---

src/rgen/Microsoft.Macios.Generator/DataModel/BindingInfo.cs
src/rgen/Microsoft.Macios.Generator/DataModel/CodeChanges.cs
src/rgen/Microsoft.Macios.Generator/Emitters/ClassEmitter.cs
src/rgen/Microsoft.Macios.Generator/Extensions/SemanticModelExtensions.cs
tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/BindingInfoTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/ClassCodeChangesTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/CodeChangesComparerTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/CodeChangesEqualityComparerTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/InterfaceCodeChangesTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/Extensions/SemanticModelExtensionsTests.cs

The name is not ideal, you can confuse BindingTypeData with BindingData. BindingInfo is easier to understand.

[Rgen] Refactor BindingData to BindingInfo and add some extra tests.

---

tools/compare-commits.sh
tools/devops/automation/scripts/bash/compare.sh

Also automatically figure out the target branch for the PR in question in script.
Then change CI to use this functionality instead of duplicating it.

[tools] Fix computing api diff from a PR in the compare-commits.sh.

---

src/Makefile.generator

[src] Fix verbosity when building bgen.csproj.inc.

---

tools/devops/automation/scripts/GitHub.psm1

The PR CI might get executed due to other triggers that are not the CI one, for example the commnad '/azp run' uses a PR trigger and not a CI one.
The IsPR method had a bug in which it would correctly return true due to the trigger used for the build, but the PRIds array would be empty.
If we find a trigger that represents a PR we now update the PR Ids accordingly. This fixes an error in which we would get the following:
```pwsh
InvalidOperation: Cannot index into a null array.
```
An example of the error can be found in the build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=10815634&view=logs&j=600d49c6-e96b-5e8b-2c3a-9f351e2e5848&t=f7d6b16e-fe1e-5522-9638-9daa7906620a

[CI] Improve the IsPR method to account for other trigger types.

---

tests/xharness/Jenkins/TestServer.cs

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2320249.

[xharness] Validate input when serving files in the web view.

---

scripts/rsp-to-csproj/README.md
scripts/rsp-to-csproj/fragment.mk
scripts/rsp-to-csproj/rsp-to-csproj.cs
scripts/rsp-to-csproj/rsp-to-csproj.csproj
src/Makefile
src/ObjCRuntime/RegistrarHelper.cs
tests/Makefile

This involved creating a tool that takes a response file and generates the corresponding
csproj.
These are fully functional project files, that build successfully (but not necessarily
correctly, I haven't verified that part).

[src] Create a csproj for each of the assemblies built during the build of the platform assemblies.

---

msbuild/Directory.Build.props

[release/9.0.1xx] Update HotRestart.Client to 17.14.51-gd03e25086a

---

src/rgen/Microsoft.Macios.Generator/Extensions/TypeSymbolExtensions.Core.cs
src/rgen/Microsoft.Macios.Transformer/Attributes/ExportData.cs
src/rgen/Microsoft.Macios.Transformer/AttributesNames.cs
tests/rgen/Microsoft.Macios.Transformer.Tests/DataModel/ExportDataTests.cs

Add the code that will parse an attribute data for a Foundation.ExportAttribute.

[Rge] Implement the code in the transformer to parse Export attrs.

---

src/rgen/Microsoft.Macios.Transformer/CompilationResult.cs
src/rgen/Microsoft.Macios.Transformer/Main.cs
src/rgen/Microsoft.Macios.Transformer/Transformer.cs
tests/rgen/Microsoft.Macios.Transformer.Tests/TransformerTests.cs

Allow the command line to be used with more than one rsp. That allows to pass all the rsp for the different platforms we support allowing us to merge the compilation results later to be used by the transformation.

[Rgen] Compile all platforms provided in parallel.

---

tools/devops/automation/templates/release/vs-insertion-prep.yml

Increasing timeout https://github.com/xamarin/yaml-templates/blob/main/sign-artifacts/jobs/v2.yml#L43

[release/9.0.1xx] [CI] Increase timeout for the signing artifacts

---

tests/common/Configuration.cs
tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/BaseTypeDataTests.cs
tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/ExportDataTests.cs
tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/FieldDataTests.cs
tests/rgen/Microsoft.Macios.Transformer.Tests/BaseTransformerTestClass.cs
tests/rgen/Microsoft.Macios.Transformer.Tests/Microsoft.Macios.Transformer.Tests.csproj
tests/rgen/Microsoft.Macios.Transformer.Tests/SyntaxTreeExtensions.cs
tests/rgen/Microsoft.Macios.Transformer.Tests/TransformerTests.cs

We provide the apidefinition rsp file for each of the platforms under test to ensure that we are testing our code against a real world scenario.

[Rgen] Use the api definiton for the transformer tests.

---

dotnet/Workloads/SignList.xml
tools/devops/automation/templates/release/vs-insertion-prep.yml

Increasing timeout https://github.com/xamarin/yaml-templates/blob/main/sign-artifacts/jobs/v2.yml#L43

[CI] Increase timeout for the signing artifacts

---

src/ObjCBindings/BindingTypeTag.cs
src/ObjCBindings/ExportTag.cs
src/rgen/Microsoft.Macios.Generator/DataModel/Binding.Generator.cs
src/rgen/Microsoft.Macios.Generator/DataModel/BindingInfo.cs
src/rgen/Microsoft.Macios.Generator/DataModel/Method.Generator.cs
src/rgen/Microsoft.Macios.Generator/DataModel/Property.Generator.cs
tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/ClassBindingTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/InterfaceCodeChangesTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/MethodTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/PropertyTests.cs

This way we can later decide if we perform the UI thread check.

[Rgen] Allow to mark bindings as thread safe.

---

src/rgen/Microsoft.Macios.Transformer/Attributes/BindData.cs
src/rgen/Microsoft.Macios.Transformer/Attributes/CoreImageFilterData.cs
src/rgen/Microsoft.Macios.Transformer/Attributes/CoreImageFilterPropertyData.cs
src/rgen/Microsoft.Macios.Transformer/AttributesNames.cs
tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/CoreImageFilterDataTests.cs
tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/CoreImageFilterPropertyTests.cs

We need to be able to parse it to convert it to the new API.

[Rgen] Add the code needed to parse the core image property attr in the transformer.

---

src/rgen/Microsoft.Macios.Transformer/Attributes/ErrorDomainData.cs
tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/ErrorDomainDataTests.cs

Allow to parse the ErrorDomain from the API definitions.

[Rgen] Add support to parse the error domain attr.

---

src/rgen/Microsoft.Macios.Transformer/Attributes/NativeData.cs
tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/NativeDataTests.cs

Not to be confused with the NativeNameAttribute, which is different.

[Rgen] Add code to parse the NativeAttribute.

---

src/rgen/Microsoft.Macios.Transformer/DataModel/Method.Transformer.cs
src/rgen/Microsoft.Macios.Transformer/DataModel/Property.Transformer.cs

Making the signature match between the two projects allows to share a number of delegates between them.

[RGen] Update signature ot the TryCreate methods to match those in the generator.

---

Directory.Build.props
msbuild/Messaging/Xamarin.Messaging.Build/Xamarin.Messaging.Build.csproj
msbuild/Xamarin.MacDev.Tasks/Xamarin.MacDev.Tasks.csproj
tests/msbuild/Xamarin.MacDev.Tasks.Tests/Xamarin.MacDev.Tasks.Tests.csproj

Fix component governance issue: https://devdiv.visualstudio.com/DevDiv/_componentGovernance/113130/alert/10507368?typeId=15046935&pipelinesTrackingFilter=0

[Messaging/MacDev] Update System.Drawing.Common and System.Security.Cryptography.Xml

---

mk/xamarin.mk

This was found by S360 ComponetGovernance https://devdiv.visualstudio.com/DevDiv/_componentGovernance/113130/alert/10507368?typeId=15046935&pipelinesTrackingFilter=0

[adr] Bump adr to get update to a transient dependency

---

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.ObjCRuntime.cs
tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryObjCRuntimeTests.cs

Add a factory method to create the throw exception in case of a null.

[Rgen] Add factory method for the throw null arg exception.

---

src/spritekit.cs

* Remove all !NET code.
* Rearrange conditional conditions to make the code formatters format the code
correctly.
* Autoformat.
This PR might be easier to view with whitespace changes disabled.

[SpriteKit] Clean conditional code.

---

src/rgen/Microsoft.Macios.Generator/DataModel/Binding.Generator.cs
src/rgen/Microsoft.Macios.Generator/DataModel/Binding.cs
src/rgen/Microsoft.Macios.Transformer/DataModel/Binding.Transformer.cs
tests/rgen/Microsoft.Macios.Transformer.Tests/DataModel/BindingPropertyTests.cs

Update the transformer code to parse the properties from a binding. This adds a all properties that the binding has that are either a property or a field.

[Rgen] Add properties to the data model in the transformer.

---

tools/devops/automation/build-pipeline.yml
tools/devops/automation/build-pull-request.yml
tools/devops/automation/templates/main-stage.yml

Looks like windows is slower than unix in this case.

[CI] Move configuration job to linux.

---

src/rgen/Microsoft.Macios.Generator/Extensions/TypeSymbolExtensions.Core.cs
tests/rgen/Microsoft.Macios.Generator.Tests/Extensions/TypeSymbolExtensionsInheritanceTests.cs

Nullable NSObject were not being considered as NSObjects. Updated the method and added test that explicitly test that path.

[RGen] Fix bug in the extension that returned the type information.

---

tests/rgen/Microsoft.Macios.Generator.Tests/Extensions/CompilationExtensionsTest.cs

Enusre that the platform is present before we yield a value.

[Rgen] Ensure that the GetUINamespaces test works when platforms are disabled.

---

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Runtime.cs
src/rgen/Microsoft.Macios.Generator/Extensions/ArgumentSyntaxExtensions.cs
tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryRuntimeTests.cs

Add the two needed invocations to get a string and a string array from a native call.

[Rgen] Add factory methods to retrieve strings from a handle.

---

src/rgen/Microsoft.Macios.Generator/DataModel/Property.Generator.cs
src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfo.cs
src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Property.cs
src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Runtime.cs
src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.cs
src/rgen/Microsoft.Macios.Generator/Emitters/ClassEmitter.cs
src/rgen/Microsoft.Macios.Generator/Extensions/ArgumentSyntaxExtensions.cs
tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/ExpectedAppKitPropertyTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/ExpectedThreadSafeAppKitPropertyTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/ExpectedThreadSafeUIKitPropertyTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/ExpectedUIKitPropertyTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/iOSExpectedPropertyTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/macOSExpectedPropertyTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/tvOSExpectedPropertyTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryPropertyTests.cs

This commit adds support to getter in properties that do not need a return value. This includes string and string [] properties.

[Rgen] Start generating simple getter calls.

---

src/Directory.Build.props
src/Makefile
src/stylecop.ruleset

This makes it easy to reformat code using StyleCop!
I'll start enabling rules in separate PRs.

[src] Add optional StyleCop validation.

---

scripts/generate-workloadmanifest-json/generate-workloadmanifest-json.cs

Improve listing older tooling workloads we might depend on by not hardcoding
version numbers.
Ref: https://github.com/dotnet/maui/issues/27318

[dotnet] Improve listing older tooling workloads we might depend on.

---

NuGet.config

[release/10.0.1xx-preview2] Add a 9.0.3 feed.

---

src/rgen/Microsoft.Macios.Generator/Emitters/Documentation.cs
src/rgen/Microsoft.Macios.Generator/Emitters/EnumEmitter.cs
src/rgen/Microsoft.Macios.Generator/IO/TabbedWriter.cs
tests/cecil-tests/Documentation.KnownFailures.txt
tests/rgen/Microsoft.Macios.Generator.Tests/SmartEnum/Data/ExpectedAVCaptureDeviceTypeEnum.cs
tests/rgen/Microsoft.Macios.Generator.Tests/SmartEnum/Data/ExpectedAVCaptureSystemPressureLevel.cs
tests/rgen/Microsoft.Macios.Generator.Tests/SmartEnum/Data/ExpectedCustomLibraryEnum.cs
tests/rgen/Microsoft.Macios.Generator.Tests/SmartEnum/Data/ExpectedCustomLibraryEnumInternal.cs
tests/rgen/Microsoft.Macios.Generator.Tests/SmartEnum/Data/ExpectedMacOSAVMediaCharacteristics.cs
tests/rgen/Microsoft.Macios.Generator.Tests/SmartEnum/Data/ExpectediOSAVMediaCharacteristics.cs

Add the documentation to the smart enum extension class and its methods.

[RGen] Add docs to the SmartEnum generated methods.

---

src/AVFoundation/Events.cs
src/AudioToolbox/AudioType.cs
src/AudioUnit/AudioUnit.cs
src/CoreFoundation/CFStream.cs
src/GameKit/GameKit2.cs
src/Metal/Defs.cs
src/PrintCore/Defs.cs
src/stylecop.ruleset

Also fix any resulting warnings.

[src] Enable stylecop's SA1132 (do not combine fields) warning.

---

CODE-OF-CONDUCT.md

Ref: https://github.com/dotnet/org-policy-violations/issues/5660

Add a Code of Conduct.

---

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Runtime.cs
tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryRuntimeTests.cs

Add the factory method to be used to generate the code needed to get a smart enum from a handle.

[Rgen] Add factory method to retrieve the smart enum values from a handle.

---

src/AddressBook/ABPerson.cs
src/CoreFoundation/DispatchBlock.cs
src/CoreGraphics/CGPDFContentStream.cs
src/CoreGraphics/CGPDFDocument.cs
src/CoreGraphics/CGPath.cs
src/CoreText/CTFontDescriptor.cs
src/CoreText/CTFramesetter.cs
src/CoreText/CTLine.cs
src/CoreText/CTTypesetter.cs
src/Darwin/SystemLog.cs
src/ImageIO/CGImageMetadata.cs
src/ImageIO/CGMutableImageMetadata.cs
src/ObjCRuntime/Runtime.cs
src/SearchKit/SearchKit.cs
src/rgen/Microsoft.Macios.Bindings.Analyzer/NativeObjectHandleAnalyzer.cs
tests/rgen/Microsoft.Macios.Bindings.Analyzer.Tests/NativeObjectHandleAnalyzerTests.cs

Replace usages of Runtime.ThrowOnNull with GetNonNullHandle extension method
Update analyzer tests

[dev/filipnavara/handle-gchole] Fix analyzer tests, replace Runtime.ThrowOnNull

---

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Runtime.cs
src/rgen/Microsoft.Macios.Generator/Extensions/ArgumentSyntaxExtensions.cs
tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryRuntimeTests.cs

Create a factory method that will return an object creation for a type info and the provided parameters.

[Rgen] Add a factory fof object creation expressions.

---

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Runtime.cs
tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryRuntimeTests.cs

Factory method that takes a C# expression and calls the GetHandle () method.

[Rgen] Factory method that will generate the call of the GetHandle method.

---

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Runtime.cs
tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryRuntimeTests.cs

Add the new invocation needed for some bindings and add tests for it an NSObject.

[Rgen] Add factory method for the GetINativeObject invocation.

---

src/Makefile

The rsp files need to be re-created when frameworks.sources changes.

[src] Fix dependencies for our main rsp files.

---

tests/xtro-sharpie/Makefile

At the moment there's nothing useful for us here, seems to be a Swift-only framework.

[TranslationUIProvider] Ignore this framework.

---

src/bgen/Filters.cs

Ensure that we keep alive the value variable.

[BGen] Fix GC.Collect issues in the CIImage setters.

---

Make.config

[xcode16.3] Bump to Xcode 16.3 RC 2

---

tools/devops/automation/build-pipeline.yml
tools/devops/automation/build-pull-request.yml
tools/devops/automation/templates/api-diff-stage.yml
tools/devops/automation/templates/common/configure.yml
tools/devops/automation/templates/common/load_configuration.yml
tools/devops/automation/templates/main-stage.yml
tools/devops/automation/templates/pipelines/api-diff-pipeline.yml
tools/devops/automation/templates/pipelines/build-pipeline.yml
tools/devops/automation/templates/pipelines/run-api-scan.yml
tools/devops/automation/templates/pipelines/run-macos-tests-pipeline.yml
tools/devops/automation/templates/pipelines/run-tests-pipeline.yml
tools/devops/automation/templates/tests-stage.yml
tools/devops/automation/templates/tests/build.yml
tools/devops/automation/templates/tests/publish-html.yml
tools/devops/automation/templates/tests/publish-results.yml
tools/devops/automation/templates/tests/run-tests.yml
tools/devops/automation/templates/tests/stage.yml

* Remove a few unused parameters.
* Try to define parameters in a single location unless otherwise needed.

[devops] Cleanup variables and parameters a bit.

---

tools/devops/automation/templates/build/build-mac-tests-stage.yml
tools/devops/automation/templates/build/build-mac-tests.yml
tools/devops/automation/templates/build/build-pkgs.yml
tools/devops/automation/templates/build/build-stage.yml
tools/devops/automation/templates/build/build.yml
tools/devops/automation/templates/common/configure.yml
tools/devops/automation/templates/common/load_configuration.yml
tools/devops/automation/templates/common/mac-agent-logs.yml
tools/devops/automation/templates/common/publish-pipeline-artifact.yml
tools/devops/automation/templates/common/teardown.yml
tools/devops/automation/templates/governance/apiscan.yml
tools/devops/automation/templates/governance/stage.yml
tools/devops/automation/templates/main-stage.yml
tools/devops/automation/templates/pipelines/run-api-scan.yml
tools/devops/automation/templates/pipelines/run-macos-tests-pipeline.yml
tools/devops/automation/templates/tests-stage.yml
tools/devops/automation/templates/tests/build.yml

Remove the default value for all parameters, so that we don't forget passing it anywhere.

[devops] Propagate 'use1ES' everywhere.

---

src/bgen/Generator.cs

Make things easier by declaring the variable with the using clause, that fixes the warnings and makes the binding code simpler.

[BGen] Fix the GC.KeepAlive issues with the BindAs attr.

---

NuGet.config
eng/Version.Details.xml
eng/Versions.props

Add .NET 9 sub and remove some leftovers from #22549 .NET 8 deps removal

[net10.0][dependencies] Include .NET 9 latest stable subscription

---

src/Foundation/EnumDesktop.cs
src/Foundation/NSAttributedString.mac.cs
src/foundation.cs
tests/cecil-tests/ConstructorTest.KnownFailures.cs
tests/cecil-tests/SetHandleTest.KnownFailures.cs
tests/introspection/ApiSelectorTest.cs

Improve and simplify the manually bound constructors for NSAttributedString by

[Foundation] Improve and simplify the manually bound constructors for NSAttributedString slightly.

---

src/rgen/Microsoft.Macios.Bindings.Analyzer/Microsoft.Macios.Bindings.Analyzer.csproj
src/rgen/Microsoft.Macios.Generator/DataModel/DelegateParameter.Generator.cs
src/rgen/Microsoft.Macios.Generator/DataModel/DelegateParameter.cs
src/rgen/Microsoft.Macios.Transformer/DataModel/DelegateParameter.Transformer.cs
tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/DelegateInfoTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/TestDataFactory.cs

We want to be able to also force a type from a parameter delegate.

[RGen] Allow to mark delegate parameters are ForcedTypes

---

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Dlfcn.cs
src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.ObjCRuntime.cs
src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Runtime.cs
src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.cs
tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryRuntimeTests.cs

Start by updating the method usage and later we will add the fully qualified global usage.

[RGen] Move to use the factory method to later make it global.

---

src/Foundation/NSUserDefaults.cs
src/foundation.cs
tests/cecil-tests/ApiAvailabilityTest.cs
tests/cecil-tests/ConstructorTest.KnownFailures.cs
tests/cecil-tests/SetHandleTest.KnownFailures.cs
tests/introspection/ApiSelectorTest.cs

Improve and simplify the manually bound constructors for NSUserDefaults by

[Foundation] Improve and simplify the manually bound constructors for NSUserDefaults slightly.

---

src/Foundation/NSThread.cs
tests/cecil-tests/ConstructorTest.KnownFailures.cs
tests/cecil-tests/SetHandleTest.KnownFailures.cs
tests/xtro-sharpie/api-annotations-dotnet/common-Foundation.ignore

Improve and simplify the manually bound constructors for NSThread by

[Foundation] Improve and simplify the manually bound constructors for NSThread slightly.

---

.github/workflows/autoformat2.yml

The comment hasn't proven to be very useful, so just skip it.

[actions] Don't notify when code is autoformatted anymore.

---

src/Foundation/NSHttpCookie.cs
tests/cecil-tests/ConstructorTest.KnownFailures.cs
tests/cecil-tests/SetHandleTest.KnownFailures.cs
tests/monotouch-test/Foundation/CookieTest.cs

Improve and simplify the manually bound constructors for NSHttpCookie by

[Foundation] Improve and simplify the manually bound constructors for NSHttpCookie slightly.

---

tests/monotouch-test/Network/NWBrowserTest.cs

* Improve logging.
* Try to make it more reliable on CI.

[tests] Improve the NWBrowerTest.TestStateChangesHandler test a bit.

---

tests/monotouch-test/Network/NWBrowserTest.cs

Fixes https://github.com/dotnet/macios/issues/22782.

[tests] Improve MonoTouchFixtures.Network.NWBrowserTest.TestStateChangesHandler to work on bots. Fixes #22782.

---

tools/devops/automation/templates/main-stage.yml

It seems variables can't be used here.

[devops] Fix condition to run the insertion stage.

---

src/rgen/Microsoft.Macios.Generator/Configuration.cs
src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfo.cs
src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Dlfcn.cs
src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.ObjCRuntime.cs
src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Runtime.cs
src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.cs

This will allow to change the use of global alieases in a single place yet still allow the method to override the static class value if needed.

[Rgen] Add a single location to control certain code generation config.

---

macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.cs.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.de.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.es.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.fr.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.it.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ja.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ko.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pl.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pt-BR.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ru.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.tr.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hans.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hant.resx

Localized file check-in by OneLocBuild Task: Build definition ID 14411: Build ID 11633941

---

msbuild/Xamarin.Shared/Xamarin.Shared.props

Ref: https://github.com/dotnet/macios/pull/22685#pullrequestreview-2868474755

[msbuild] Fix mistake: it's 'EnableProfiler', not 'EnableProfiling'.

---

msbuild/Xamarin.MacDev.Tasks/Tasks/ComputeCodesignItems.cs
tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/ComputeCodesignItemsTaskTests.cs

1. There's no need to codesign a symlink, because:
a. A symlink can only point to another file or directory inside the app
bundle (not outside of it).
b. That other file or directory should already be in the list of files to sign.
2. We're already skipping files and directories that are symlinks, but we
weren't skipping normal files or directories inside a symlinked directory.
This is now fixed.
Example 1:
MyBundle.app/Contents/Frameworks/XTest.framework/XTest -> MyBundle.app/Contents/Frameworks/XTest.framework/Versions/A/Resources/XTest
This file (MyBundle.app/Contents/Frameworks/XTest.framework/XTest) was already not signed.
Example 2:
MyBundle.app/Contents/Frameworks/XTest.framework/Libraries -> MyBundle.app/Contents/Frameworks/XTest.framework/Versions/A/Libraries …

[msbuild] Improve ComputeCodesignItems to take symlinked directories into account. Fixes #20193.

---

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Trampoline.cs
src/rgen/Microsoft.Macios.Generator/Emitters/TrampolineEmitter.cs
src/rgen/Microsoft.Macios.Generator/Nomenclator.cs
tests/rgen/Microsoft.Macios.Generator.Tests/Classes/ClassGenerationTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/ExpectedTrampolinePropertyTestsTrampolines.cs
tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryTrampolineTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/NomenclatorTests.cs

Add the native invoker class for the trampolines and the constructor and create methods. The invoke method will be added in comming PRs.

[RGen] Generate constructor and create method for the native invoker.

---

macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.cs.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.de.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.es.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.fr.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.it.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ja.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ko.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pl.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pt-BR.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ru.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.tr.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hans.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hant.resx

Localized file check-in by OneLocBuild Task: Build definition ID 14411: Build ID 11681430

---

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Trampoline.cs
tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryTrampolineTests.cs

All out parameters have to have a default value in the Invoke of the NI* classes. Ref parameters do not need to be init, same with in params.

[RGen] Factory method to perform the init of our params in the native invoke.

---

tests/cecil-tests/CecilExtensions.cs
tests/cecil-tests/SetHandleTest.KnownFailures.cs
tests/cecil-tests/SetHandleTest.cs

Fix the remaining known issues in the SetHandle test by ignoring obsolete API
and special-casing the single special case we shouldn't fix.

[tests] Fix the remaining known issues in the SetHandle test.

---

src/CoreMidi/MidiServices.cs
src/CoreMidi/MidiThruConnection.cs

This simplifies the code a little bit.

[CoreMidi] Add a GetCheckedHandle method in a couple of classes, and use it.

---

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.KnownTypes.cs
src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.ObjCRuntime.cs
src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Runtime.cs
src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Trampoline.cs
src/rgen/Microsoft.Macios.Generator/Emitters/TrampolineEmitter.cs
tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/ExpectedTrampolinePropertyTestsTrampolines.cs
tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryObjCRuntimeTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryRuntimeTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryTrampolineTests.cs

The changes will get the native object representations (string -> NSString) so that we can call the native invoker.

[RGen] Generate the lowering of the parameters for the native invoker.

---

macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.cs.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.de.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.es.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.fr.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.it.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ja.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ko.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pl.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pt-BR.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ru.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.tr.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hans.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hant.resx

Localized file check-in by OneLocBuild Task: Build definition ID 14411: Build ID 11769411

---

macios/Localize/loc/cs/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/fr/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/it/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/ja/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/ko/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/pl/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/pt-BR/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/ru/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/tr/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/zh-Hans/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl

LEGO: Pull request from lego/hb_5df43909-4a19-4f55-bc3f-9ea8fccf3c82_20250617175543712 to main with localized lcls

LEGO: Pull request from lego/hb_5df43909-4a19-4f55-bc3f-9ea8fccf3c82_20250617175543712 to main

---

macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.cs.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.de.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.es.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.fr.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.it.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ja.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ko.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pl.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pt-BR.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ru.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.tr.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hans.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hant.resx

Localized file check-in by OneLocBuild Task: Build definition ID 14411: Build ID 11793019

---

macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.cs.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.de.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.es.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.fr.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.it.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ja.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ko.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pl.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pt-BR.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ru.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.tr.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hans.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hant.resx

Localized file check-in by OneLocBuild Task: Build definition ID 14411: Build ID 11794572

---

macios/Localize/loc/cs/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/de/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/ko/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/pt-BR/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/zh-Hant/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl

LEGO: Pull request from lego/hb_5df43909-4a19-4f55-bc3f-9ea8fccf3c82_20250620053646603 to main with localized lcls

LEGO: Pull request from lego/hb_5df43909-4a19-4f55-bc3f-9ea8fccf3c82_20250620053646603 to main

---

tools/devops/automation/templates/build/build.yml
tools/devops/automation/templates/tests/publish-html.yml

[release/9.0.1xx] [devops] Don't fail the build if failing to add GitHub comments.

---

macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.cs.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.de.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.es.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.fr.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.it.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ja.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ko.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pl.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pt-BR.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ru.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.tr.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hans.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hant.resx
macios/tools/mtouch/TranslatedAssemblies/Errors.cs.resx
macios/tools/mtouch/TranslatedAssemblies/Errors.de.resx
macios/tools/mtouch/TranslatedAssemblies/Errors.es.resx
macios/tools/mtouch/TranslatedAssemblies/Errors.fr.resx
macios/tools/mtouch/TranslatedAssemblies/Errors.it.resx
macios/tools/mtouch/TranslatedAssemblies/Errors.ja.resx
macios/tools/mtouch/TranslatedAssemblies/Errors.ko.resx
macios/tools/mtouch/TranslatedAssemblies/Errors.pl.resx
macios/tools/mtouch/TranslatedAssemblies/Errors.pt-BR.resx
macios/tools/mtouch/TranslatedAssemblies/Errors.ru.resx
macios/tools/mtouch/TranslatedAssemblies/Errors.tr.resx
macios/tools/mtouch/TranslatedAssemblies/Errors.zh-Hans.resx
macios/tools/mtouch/TranslatedAssemblies/Errors.zh-Hant.resx

Localized file check-in by OneLocBuild Task: Build definition ID 14411: Build ID 11826800

---

macios/Localize/loc/cs/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/cs/macios/tools/mtouch/Errors.resx.lcl
macios/Localize/loc/de/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/de/macios/tools/mtouch/Errors.resx.lcl
macios/Localize/loc/es/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/es/macios/tools/mtouch/Errors.resx.lcl
macios/Localize/loc/fr/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/fr/macios/tools/mtouch/Errors.resx.lcl
macios/Localize/loc/it/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/it/macios/tools/mtouch/Errors.resx.lcl
macios/Localize/loc/ja/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/ja/macios/tools/mtouch/Errors.resx.lcl
macios/Localize/loc/ko/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/ko/macios/tools/mtouch/Errors.resx.lcl
macios/Localize/loc/pl/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/pl/macios/tools/mtouch/Errors.resx.lcl
macios/Localize/loc/pt-BR/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/pt-BR/macios/tools/mtouch/Errors.resx.lcl
macios/Localize/loc/ru/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/ru/macios/tools/mtouch/Errors.resx.lcl
macios/Localize/loc/tr/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/tr/macios/tools/mtouch/Errors.resx.lcl
macios/Localize/loc/zh-Hans/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/zh-Hans/macios/tools/mtouch/Errors.resx.lcl
macios/Localize/loc/zh-Hant/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/zh-Hant/macios/tools/mtouch/Errors.resx.lcl

LEGO: Pull request from lego/hb_5df43909-4a19-4f55-bc3f-9ea8fccf3c82_20250625181348299 to main with localized lcls

LEGO: Pull request from lego/hb_5df43909-4a19-4f55-bc3f-9ea8fccf3c82_20250625181348299 to main

---

macios/Localize/loc/pt-BR/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/pt-BR/macios/tools/mtouch/Errors.resx.lcl

LEGO: Pull request from lego/hb_5df43909-4a19-4f55-bc3f-9ea8fccf3c82_20250627055157560 to main with localized lcls

LEGO: Pull request from lego/hb_5df43909-4a19-4f55-bc3f-9ea8fccf3c82_20250627055157560 to main

---

macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.cs.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.de.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.es.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.fr.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.it.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ja.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ko.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pl.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pt-BR.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ru.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.tr.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hans.resx
macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hant.resx

Localized file check-in by OneLocBuild Task: Build definition ID 14411: Build ID 11894735

---

macios/Localize/loc/cs/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/de/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/es/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/ja/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/pl/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/tr/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/zh-Hant/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl

LEGO: Pull request from lego/hb_5df43909-4a19-4f55-bc3f-9ea8fccf3c82_20250705173640733 to main with localized lcls

LEGO: Pull request from lego/hb_5df43909-4a19-4f55-bc3f-9ea8fccf3c82_20250705173640733 to main

---

macios/Localize/loc/it/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/ko/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/pt-BR/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/ru/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/zh-Hans/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl

LEGO: Pull request from lego/hb_5df43909-4a19-4f55-bc3f-9ea8fccf3c82_20250705053716651 to main with localized lcls

LEGO: Pull request from lego/hb_5df43909-4a19-4f55-bc3f-9ea8fccf3c82_20250705053716651 to main

---

src/WebKit/WKContentRuleList.cs
src/WebKit/WKContentRuleListStore.cs
src/frameworks.sources
src/metalfx.cs
src/phase.cs
src/webkit.cs
tests/cecil-tests/Documentation.KnownFailures.txt
tests/common/TestRuntime.cs
tests/introspection/ApiCMAttachmentTest.cs
tests/introspection/ApiCtorInitTest.cs
tests/introspection/ApiFieldTest.cs
tests/introspection/ApiPInvokeTest.cs
tests/introspection/ApiProtocolTest.cs
tests/introspection/ApiSelectorTest.cs
tests/introspection/ApiTypoTest.cs
tests/introspection/CoreSelectorTest.cs
tests/introspection/iOSApiSelectorTest.cs
tests/xtro-sharpie/api-annotations-dotnet/iOS-MetalFX.ignore
tests/xtro-sharpie/api-annotations-dotnet/macOS-MetalFX.ignore

It's now green on: iPhone 15 Pro with iOS 18.5.
Also tested on iPad Pro 11'' with iOS 26.0 beta 2, almost all green except a few issues in iOS 26.0.

[src/introspection] Make introspection pass on device.

---

msbuild/ILMerge.targets

[release/9.0.1xx] [msbuild] Merge System.Formats.Asn1.dll ito the task assembly as well.

---

tools/devops/automation/templates/common/checkout.yml
tools/devops/automation/templates/windows/stage.yml

Hopefully fixes this:
> ##[error]The term 'pwsh.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

[devops] Install Powershell Core if it's not already installed.

---

msbuild/ILMerge.targets

[msbuild] Merge System.Formats.Asn1.dll ito the task assembly as well.

---

src/CoreVideo/CVOpenGLESTexture.cs
src/CoreVideo/CVOpenGLESTextureCache.cs
src/frameworks.sources
tests/cecil-tests/Documentation.KnownFailures.txt

Fixes https://github.com/dotnet/macios/issues/23301.

[src] Add CVOpenGLESTexture.cs and CVOpenGLESTextureCache.cs to the build.

---

tests/xtro-sharpie/xtro-sanity/Sanitizer.cs

* Make it clear when logging that a failure was sanitized.
* Fail if there were any failures that weren't sanitized.

[xtro] Improve AUTO_SANITIZE behavior.

---

src/rgen/Microsoft.Macios.Generator/DataModel/Property.Generator.cs
src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.KnownTypes.cs
src/rgen/Microsoft.Macios.Generator/Emitters/ProtocolEmitter.cs
src/rgen/Microsoft.Macios.Generator/Formatters/TypeInfoFormatter.cs
src/rgen/Microsoft.Macios.Generator/IO/TabbedStringBuilderExtensions.cs
tests/rgen/Microsoft.Macios.Generator.Tests/IO/TabbedStringBuilderTests.cs
tests/rgen/Microsoft.Macios.Generator.Tests/Protocols/Data/ExpectedIAVAudio3DMixing.cs
tests/rgen/Microsoft.Macios.Generator.Tests/Protocols/Data/IAVAudio3DMixing.cs

Emit the required properites of a protocol. The emitter follows the pattern that bgen uses when it creates a _Get{PropertyName} and _Set{PropertyName} that are later called by the property.
The following is an example of a code generated property :
```csharp
[SupportedOSPlatform ("macos")]
[SupportedOSPlatform ("ios")]
[SupportedOSPlatform ("tvos")]
[SupportedOSPlatform ("maccatalyst13.1")]
[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
internal static global::AVFoundation.AVAudio3DMixingSourceMode _GetSourceMode (this IAVAudio3DMixing self)
{
global::AVFoundation.AVAudio3DMixingSourceMode ret;
ret = (global::AVFoundation.AVAudio3DMixingSourceMode) (long) global::ObjCRuntime.Messaging.IntPtr_objc_msgSend (self.Handle, …
```

[RGen] Emit required property implementations for protocols.

---

macios/Localize/loc/de/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/es/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/fr/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/ko/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/pl/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/ru/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/tr/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/zh-Hant/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl

LEGO: Pull request from lego/hb_5df43909-4a19-4f55-bc3f-9ea8fccf3c82_20250805180315201 to main with localized lcls

LEGO: Pull request from lego/hb_5df43909-4a19-4f55-bc3f-9ea8fccf3c82_20250805180315201 to main

---

macios/src/TranslatedAssemblies/Resources.cs.resx
macios/src/TranslatedAssemblies/Resources.de.resx
macios/src/TranslatedAssemblies/Resources.es.resx
macios/src/TranslatedAssemblies/Resources.fr.resx
macios/src/TranslatedAssemblies/Resources.it.resx
macios/src/TranslatedAssemblies/Resources.ja.resx
macios/src/TranslatedAssemblies/Resources.ko.resx
macios/src/TranslatedAssemblies/Resources.pl.resx
macios/src/TranslatedAssemblies/Resources.pt-BR.resx
macios/src/TranslatedAssemblies/Resources.ru.resx
macios/src/TranslatedAssemblies/Resources.tr.resx
macios/src/TranslatedAssemblies/Resources.zh-Hans.resx
macios/src/TranslatedAssemblies/Resources.zh-Hant.resx

Localized file check-in by OneLocBuild Task: Build definition ID 14411: Build ID 12118224

---

macios/Localize/loc/cs/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl

LEGO: Pull request from lego/hb_5df43909-4a19-4f55-bc3f-9ea8fccf3c82_20250806175158745 to main with localized lcls

LEGO: Pull request from lego/hb_5df43909-4a19-4f55-bc3f-9ea8fccf3c82_20250806175158745 to main

---

macios/src/TranslatedAssemblies/Resources.cs.resx
macios/src/TranslatedAssemblies/Resources.de.resx
macios/src/TranslatedAssemblies/Resources.es.resx
macios/src/TranslatedAssemblies/Resources.fr.resx
macios/src/TranslatedAssemblies/Resources.it.resx
macios/src/TranslatedAssemblies/Resources.ja.resx
macios/src/TranslatedAssemblies/Resources.ko.resx
macios/src/TranslatedAssemblies/Resources.pl.resx
macios/src/TranslatedAssemblies/Resources.pt-BR.resx
macios/src/TranslatedAssemblies/Resources.ru.resx
macios/src/TranslatedAssemblies/Resources.tr.resx
macios/src/TranslatedAssemblies/Resources.zh-Hans.resx
macios/src/TranslatedAssemblies/Resources.zh-Hant.resx

Localized file check-in by OneLocBuild Task: Build definition ID 14411: Build ID 12118479

---

macios/src/TranslatedAssemblies/Resources.cs.resx
macios/src/TranslatedAssemblies/Resources.de.resx
macios/src/TranslatedAssemblies/Resources.es.resx
macios/src/TranslatedAssemblies/Resources.fr.resx
macios/src/TranslatedAssemblies/Resources.it.resx
macios/src/TranslatedAssemblies/Resources.ja.resx
macios/src/TranslatedAssemblies/Resources.ko.resx
macios/src/TranslatedAssemblies/Resources.pl.resx
macios/src/TranslatedAssemblies/Resources.pt-BR.resx
macios/src/TranslatedAssemblies/Resources.ru.resx
macios/src/TranslatedAssemblies/Resources.tr.resx
macios/src/TranslatedAssemblies/Resources.zh-Hans.resx
macios/src/TranslatedAssemblies/Resources.zh-Hant.resx

Localized file check-in by OneLocBuild Task: Build definition ID 14411: Build ID 12118774

---

macios/Localize/loc/it/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/ja/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/pt-BR/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
macios/Localize/loc/zh-Hans/macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl

LEGO: Pull request from lego/hb_5df43909-4a19-4f55-bc3f-9ea8fccf3c82_20250806055201362 to main with localized lcls

LEGO: Pull request from lego/hb_5df43909-4a19-4f55-bc3f-9ea8fccf3c82_20250806055201362 to main

---

macios/Localize/loc/cs/macios/src/Resources.resx.lcl
macios/Localize/loc/de/macios/src/Resources.resx.lcl
macios/Localize/loc/es/macios/src/Resources.resx.lcl
macios/Localize/loc/it/macios/src/Resources.resx.lcl
macios/Localize/loc/ja/macios/src/Resources.resx.lcl
macios/Localize/loc/ko/macios/src/Resources.resx.lcl
macios/Localize/loc/pl/macios/src/Resources.resx.lcl
macios/Localize/loc/pt-BR/macios/src/Resources.resx.lcl
macios/Localize/loc/ru/macios/src/Resources.resx.lcl
macios/Localize/loc/tr/macios/src/Resources.resx.lcl
macios/Localize/loc/zh-Hant/macios/src/Resources.resx.lcl

LEGO: Pull request from lego/hb_5df43909-4a19-4f55-bc3f-9ea8fccf3c82_20250808054301798 to main with localized lcls

LEGO: Pull request from lego/hb_5df43909-4a19-4f55-bc3f-9ea8fccf3c82_20250808054301798 to main

---

src/rgen/Microsoft.Macios.Bindings.Analyzer/Microsoft.Macios.Bindings.Analyzer.csproj
src/rgen/Microsoft.Macios.Generator/Attributes/BindFromData.cs
src/rgen/Microsoft.Macios.Generator/Attributes/BindingTypeData.cs
src/rgen/Microsoft.Macios.Generator/Attributes/ExportData.cs
src/rgen/Microsoft.Macios.Generator/Attributes/FieldData.cs
src/rgen/Microsoft.Macios.Generator/Attributes/ForcedTypeData.cs
src/rgen/Microsoft.Macios.Generator/Extensions/AttributeDataExtensions.cs

The new Location property will be used by the analyzer to be abble to point the diagnostics to the correct attribute location.

[RGen] Track the location of attributes.

---

macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.cs.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.de.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.es.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.fr.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.it.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.ja.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.ko.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.pl.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.pt-BR.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.ru.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.tr.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.zh-Hans.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.zh-Hant.resx

Localized file check-in by OneLocBuild Task: Build definition ID 14411: Build ID 12194762

---

src/rgen/Microsoft.Macios.Generator/DataModel/Accessor.Generator.cs
src/rgen/Microsoft.Macios.Generator/DataModel/Binding.Generator.cs
src/rgen/Microsoft.Macios.Generator/DataModel/Constructor.Generator.cs
src/rgen/Microsoft.Macios.Generator/DataModel/Method.Generator.cs
src/rgen/Microsoft.Macios.Generator/DataModel/Parameter.Generator.cs
src/rgen/Microsoft.Macios.Generator/DataModel/Property.Generator.cs

This new property will later be used for the analyzer to provide correct warning/error locations.

[RGen] Add a Location property to the binding structs.

---

src/rgen/Microsoft.Macios.Bindings.Analyzer/Microsoft.Macios.Bindings.Analyzer.csproj
src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.Designer.cs
src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.resx
src/rgen/Microsoft.Macios.Bindings.Analyzer/RgenDiagnostics.cs
src/rgen/Microsoft.Macios.Generator/BindingSourceGeneratorGenerator.cs
src/rgen/Microsoft.Macios.Generator/DataModel/AsyncResultInfo.cs
src/rgen/Microsoft.Macios.Generator/DataModel/Binding.Generator.cs
src/rgen/Microsoft.Macios.Generator/Emitters/AsyncResultEmitter.cs
src/rgen/Microsoft.Macios.Generator/Emitters/BGenStrongDictionaryKeysEmitter.cs
src/rgen/Microsoft.Macios.Generator/Emitters/CategoryEmitter.cs
src/rgen/Microsoft.Macios.Generator/Emitters/ClassEmitter.cs
src/rgen/Microsoft.Macios.Generator/Emitters/EnumEmitter.cs
src/rgen/Microsoft.Macios.Generator/Emitters/EventTypeEmitter.cs
src/rgen/Microsoft.Macios.Generator/Emitters/ProtocolEmitter.cs
src/rgen/Microsoft.Macios.Generator/Emitters/StrongDictionaryEmitter.cs
src/rgen/Microsoft.Macios.Generator/Emitters/StrongDictionaryKeysEmitter.cs
src/rgen/Microsoft.Macios.Generator/Extensions/NamedTypeSymbolExtensions.cs
src/rgen/Microsoft.Macios.Generator/RgenDiagnostics.cs

This will open the door for the analyzer to create the binding structs and then use a validator to validate the bindings.

[RGen] Allow the analyzer project to use the full data model.

---

macios/Localize/loc/cs/macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.resx.lcl
macios/Localize/loc/de/macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.resx.lcl
macios/Localize/loc/es/macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.resx.lcl
macios/Localize/loc/fr/macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.resx.lcl
macios/Localize/loc/it/macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.resx.lcl
macios/Localize/loc/ja/macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.resx.lcl
macios/Localize/loc/ko/macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.resx.lcl
macios/Localize/loc/pl/macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.resx.lcl
macios/Localize/loc/pt-BR/macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.resx.lcl
macios/Localize/loc/ru/macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.resx.lcl
macios/Localize/loc/tr/macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.resx.lcl
macios/Localize/loc/zh-Hans/macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.resx.lcl
macios/Localize/loc/zh-Hant/macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.resx.lcl

LEGO: Pull request from lego/hb_5df43909-4a19-4f55-bc3f-9ea8fccf3c82_20250817055029698 to main with localized lcls

LEGO: Pull request from lego/hb_5df43909-4a19-4f55-bc3f-9ea8fccf3c82_20250817055029698 to main

---

msbuild/Directory.Build.props

Applied fixes:
https://dev.azure.com/devdiv/DevDiv/_git/ClientTools.Platform/pullrequest/663026
https://dev.azure.com/devdiv/DevDiv/_git/ClientTools.Platform/pullrequest/663383

Update Messaging to 18.0.280-ga047b642b9

---

msbuild/Directory.Build.props

Applied fixes:
https://dev.azure.com/devdiv/DevDiv/_git/ClientTools.Platform/pullrequest/663026
https://dev.azure.com/devdiv/DevDiv/_git/ClientTools.Platform/pullrequest/663383

[release/10.0.1xx-rc.1] Update Messaging to 18.0.280-ga047b642b9

---

macios/Localize/loc/cs/macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.resx.lcl
macios/Localize/loc/fr/macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.resx.lcl
macios/Localize/loc/it/macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.resx.lcl
macios/Localize/loc/ja/macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.resx.lcl
macios/Localize/loc/pl/macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.resx.lcl
macios/Localize/loc/zh-Hans/macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.resx.lcl
macios/Localize/loc/zh-Hant/macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.resx.lcl

LEGO: Pull request from lego/hb_5df43909-4a19-4f55-bc3f-9ea8fccf3c82_20250822174058692 to main with localized lcls

LEGO: Pull request from lego/hb_5df43909-4a19-4f55-bc3f-9ea8fccf3c82_20250822174058692 to main

---

macios/Localize/loc/de/macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.resx.lcl
macios/Localize/loc/es/macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.resx.lcl
macios/Localize/loc/ko/macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.resx.lcl

LEGO: Pull request from lego/hb_5df43909-4a19-4f55-bc3f-9ea8fccf3c82_20250822053813334 to main with localized lcls

LEGO: Pull request from lego/hb_5df43909-4a19-4f55-bc3f-9ea8fccf3c82_20250822053813334 to main

---

macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.cs.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.de.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.es.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.fr.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.it.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.ja.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.ko.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.pl.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.pt-BR.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.ru.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.tr.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.zh-Hans.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.zh-Hant.resx

Localized file check-in by OneLocBuild Task: Build definition ID 14411: Build ID 12255359

---

src/Foundation/NSData.cs
tests/monotouch-test/Foundation/NSDataTest.cs

This API will be used in upcoming bindings.

[src] Add support for storing and retrieving any struct in an NSData instance.

---

macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.cs.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.de.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.es.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.fr.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.it.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.ja.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.ko.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.pl.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.pt-BR.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.ru.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.tr.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.zh-Hans.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.zh-Hant.resx

Localized file check-in by OneLocBuild Task: Build definition ID 14411: Build ID 12317343

---

macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.cs.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.de.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.es.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.fr.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.it.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.ja.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.ko.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.pl.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.pt-BR.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.ru.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.tr.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.zh-Hans.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.zh-Hant.resx

Localized file check-in by OneLocBuild Task: Build definition ID 14411: Build ID 12321123

---

system-dependencies.sh

* Don't pass '-buildVersion X.Y' when installing simulators for beta versions of Xcode, because this happens:
$ xcodebuild -downloadPlatform iOS -buildVersion 26.0
iOS 26.0 is not available for download
which presumably is because there's no stable version of iOS 26.0 yet. Get
around this by just not passing the desired build version to xcodebuild, and
instead let xcodebuild decide.
* There's no need for the beta 1 workaround for installing the metal toolchain anymore.

[system-dependencies] Update for Xcode 26.0 specifics.

---

macios/Localize/loc/ja/macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.resx.lcl
macios/Localize/loc/pt-BR/macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.resx.lcl
macios/Localize/loc/tr/macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.resx.lcl
macios/Localize/loc/zh-Hans/macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.resx.lcl

LEGO: Pull request from lego/hb_5df43909-4a19-4f55-bc3f-9ea8fccf3c82_20250904175908445 to main with localized lcls

LEGO: Pull request from lego/hb_5df43909-4a19-4f55-bc3f-9ea8fccf3c82_20250904175908445 to main

---

macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.cs.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.de.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.es.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.fr.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.it.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.ja.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.ko.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.pl.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.pt-BR.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.ru.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.tr.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.zh-Hans.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.zh-Hant.resx

Localized file check-in by OneLocBuild Task: Build definition ID 14411: Build ID 12347956

---

macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.cs.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.de.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.es.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.fr.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.it.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.ja.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.ko.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.pl.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.pt-BR.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.ru.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.tr.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.zh-Hans.resx
macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.zh-Hant.resx

Localized file check-in by OneLocBuild Task: Build definition ID 14411: Build ID 12360389

---

tools/devops/automation/build-pipeline.yml
tools/devops/automation/templates/pipelines/build-pipeline.yml

Workaround while we investigate the main branch breakage

[signing] Use workaround to unblock our builds

---

mk/xamarin.mk

Fixes https://github.com/dotnet/macios/issues/23833.

Bump mlaunch to get fix for #23833.

---

macios/src/TranslatedAssemblies/Resources.cs.resx
macios/src/TranslatedAssemblies/Resources.de.resx
macios/src/TranslatedAssemblies/Resources.es.resx
macios/src/TranslatedAssemblies/Resources.fr.resx
macios/src/TranslatedAssemblies/Resources.it.resx
macios/src/TranslatedAssemblies/Resources.ja.resx
macios/src/TranslatedAssemblies/Resources.ko.resx
macios/src/TranslatedAssemblies/Resources.pl.resx
macios/src/TranslatedAssemblies/Resources.pt-BR.resx
macios/src/TranslatedAssemblies/Resources.ru.resx
macios/src/TranslatedAssemblies/Resources.tr.resx
macios/src/TranslatedAssemblies/Resources.zh-Hans.resx
macios/src/TranslatedAssemblies/Resources.zh-Hant.resx

Localized file check-in by OneLocBuild Task: Build definition ID 14411: Build ID 12418071

---

macios/Localize/loc/fr/macios/src/Resources.resx.lcl
macios/Localize/loc/ja/macios/src/Resources.resx.lcl

LEGO: Pull request from lego/hb_5df43909-4a19-4f55-bc3f-9ea8fccf3c82_20250920173632207 to main with localized lcls

LEGO: Pull request from lego/hb_5df43909-4a19-4f55-bc3f-9ea8fccf3c82_20250920173632207 to main

---

src/avfoundation.cs

Fixes https://github.com/dotnet/macios/issues/8735.

[AVFoundation] Improve documentation for AVFileTypes.Mpeg3. Fixes #8735.

---

src/webkit.cs

Fixes https://github.com/dotnet/macios/issues/9984.

[WebKit] Improve documentation for WKHttpCookieStore.[Add|Remove]Observer. Fixes #9984.

---

msbuild/Xamarin.MacDev.Tasks/Tasks/CollectBundleResources.cs
tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/CollectBundleResourcesTaskTests.cs

[release/10.0.1xx-rc.2] [msbuild] Improve detection of resources that would end up outside the app bundle.

---

tools/common/Frameworks.cs

Fixes https://github.com/dotnet/macios/issues/15138.

[tools] ShazamKit is now available in the simulator. Fixes #15138.
