Make.config, Makefile, builds/Makefile, dotnet/Makefile, src/Makefile, system-dependencies.sh, tests/Makefile, tests/common/Configuration.cs, tests/generator/BGenTool.cs, tests/generator/GeneratorTests.cs, tests/test-libraries/custom-type-assembly/Makefile, tools/devops/Makefile, tools/devops/automation/templates/tests/run-tests.yml, tools/devops/build-provisioning.csx.in, tools/devops/device-tests-provisioning.csx.in, tools/devops/mac-tests-provisioning.csx.in, tools/dotnet-linker/Makefile, tools/mmp/Makefile, tools/mtouch/Makefile
Also rename DOTNET_VERSION to SYSTEM_DOTNET_VERSION to make it clear what it's
referring to (and to not clash with DOTNET6_VERSION which has now been renamed
to DOTNET_VERSION).
.NET 7 is right around the corner.
=> [.NET] Rename several DOTNET6_* variables to to DOTNET_*.

dotnet/package/common.csproj, msbuild/Xamarin.HotRestart.PreBuilt/Makefile, src/Makefile, tests/test-libraries/custom-type-assembly/Makefile
This makes it easier to bump to 'net7.0' when that time comes.
=> [dotnet] Use a variable for 'net6.0' instead of hardcoding it.

dotnet/targets/Xamarin.Shared.Sdk.targets, msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DittoTaskBase.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/Ditto.cs, msbuild/Xamarin.Shared/Xamarin.Shared.targets
Sometimes we want to copy the entire input directory from Windows to the Mac
when executing the Ditto task remotely, and sometimes we don't.
In particular we do not want to copy the input directory when the directory on
Windows is an incomplete mirror of what's on the Mac - one scenario being when
copying the app bundle to prepare for IPA creation. The .app directory on
Windows is not complete - all the files are there (maybe? not quite sure, but
that's beside the point here), but some may be empty, because when we only
care about the timestamp for a file, we'll create an empty file on Windows to
mirror the actual file on Mac. Copying this incomplete directory to the Mac,
overwriting the correct files there, will break things badly.
However, sometimes we're not mirroring a directory on …
=> [msbuild] Only conditionally copy entire input directory from Windows in the Ditto task.

tests/dotnet/UnitTests/AssetsTest.cs
Hopefully fixes https://github.com/xamarin/maccore/issues/2559.
=> [tests] Don't try to parse stderr from assetutil. Fixes #xamarin/maccore@2559.

tests/common/Configuration.cs
When running on older macOS bots, we specifically execute tests outside of the source tree, and the tests expect that so they may fail if they end up finding a checkout.
Fixes the following xammac/monotouch test on older macOS versions:
MonoTouchFixtures.ObjCRuntime.RegistrarTest
[FAIL] CustomUserTypeWithDynamicallyLoadedAssembly :   existence
Expected: file or directory exists
But was:  "/Users/runner/work/1/s/xamarin-macios/tests/test-libraries/custom-type-assembly/.libs/macos/custom-type-assembly.dll"
=> [tests] There's no need to have different logic to compute the source root path on Azure DevOps.

tools/devops/automation/templates/tests/run-tests.yml
This makes stdout much more readable.
It also fixes https://github.com/xamarin/maccore/issues/2562.
=> [devops] Stop asking *all* tests print *all* stack traces.

tests/Makefile, tests/dotnet/UnitTests/BundleStructureTest.cs
Fixes https://github.com/xamarin/maccore/issues/2548.
=> [tests] Store symlinks in zips. Fixes #xamarin/maccore@2548.

.github/fabricbot.json
This initial config file tells the author of an issue that if anybody adds the
`need-info` label, they have 7 days to answer before we close the issue due
to lack of response.
=> [fabricbot] Add initial config file.

tools/nnyeah/nnyeah/Program.cs
We generate a .dll and we should be pointing to dotnet instead of mono.
=> [nnyeah] Update usage to dotnet.

tools/devops/automation/templates/common/mac-agent-logs.yml
It can happen that we use the same agent for more than one bot, if that
is the case, we need to make sure that we do not have the same name for
the logs. We use the job id + job name for that.
=> [CI] Add the job id to the agent logs.

Make.config
This was supposed to happen in d3643414e7900134df13f1962f0ffba85965c25e, but
it looks like due to a merge conflict, this remaining part disappeared.
=> [dotnet] Complete rename of DOTNET to SYSTEM_DOTNET.

msbuild/Xamarin.Localization.MSBuild/MSBStrings.Designer.cs, msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx, msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ComputeCodesignItemsTaskBase.cs, tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/ComputeCodesignItemsTaskTests.cs
We may end up trying to codesign the same item multiple times when codesigning
universal .NET apps. Avoid this by deduplicating items to codesign.
Fixes https://github.com/xamarin/xamarin-macios/issues/14522.
=> [msbuild] Deduplicate items in ComputeCodesignItems. Fixes #14522.

tools/nnyeah/Makefile
This reverts commit 073165fef6f08eb277137e7213a8bf5e0d95878b.
Fixes this build error:
```
/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(1232,5): error MSB3971: The reference assemblies for ".NETFramework,Version=v5.0" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK. [/Users/rolf/work/maccore/dotnet/xamarin-macios/tools/nnyeah/nnyeah/nnyeah.csproj]
gmake[2]: *** [Makefile:9: bin/Debug/net5.0/nnyeah.dll] Error 1
```
=> Revert "[nnyeah] Fix makefile to use msbuild. (#14533)"

tests/mmptest/mmptest.csproj
As long as the variable is set, we're using the system installation for testing.
=> [mmptest] Fix TESTS_USE_SYSTEM logic.

dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets, tests/common/shared-dotnet.csproj, tests/dotnet/CentralPackageVersionsApp/AppDelegate.cs, tests/dotnet/CentralPackageVersionsApp/MacCatalyst/CentralPackageVersionsApp.csproj, tests/dotnet/CentralPackageVersionsApp/MacCatalyst/Makefile, tests/dotnet/CentralPackageVersionsApp/Makefile, tests/dotnet/CentralPackageVersionsApp/Packages.props, tests/dotnet/CentralPackageVersionsApp/README.md, tests/dotnet/CentralPackageVersionsApp/iOS/CentralPackageVersionsApp.csproj, tests/dotnet/CentralPackageVersionsApp/iOS/Makefile, tests/dotnet/CentralPackageVersionsApp/macOS/CentralPackageVersionsApp.csproj, tests/dotnet/CentralPackageVersionsApp/macOS/Makefile, tests/dotnet/CentralPackageVersionsApp/shared.csproj, tests/dotnet/CentralPackageVersionsApp/shared.mk, tests/dotnet/CentralPackageVersionsApp/tvOS/CentralPackageVersionsApp.csproj, tests/dotnet/CentralPackageVersionsApp/tvOS/Makefile, tests/dotnet/UnitTests/ProjectTest.cs
This unbreaks Central Package Management via https://github.com/microsoft/MSBuildSdks/tree/main/src/CentralPackageVersions which is being worked on for NuGet, see https://github.com/NuGet/Home/issues/6764
Fixes https://github.com/xamarin/xamarin-macios/issues/14452
=> Set IsImplicitlyDefined="true" on the System.Runtime.InteropServices.NFloat.Internal PackageReference

tools/devops/automation/build-pipeline.yml, tools/devops/automation/templates/tests/stage.yml
The internal bots are giving issues running xtro, public ones are ok.
There is no real reason to use the internal pool to run tests and we can
debug the bots in that pool better.
We move to run tests in the public bots unless told otherwise (when
using devices for example).
=> [CI] Use public bots to run tests.

tests/xharness/Harness.cs
Fixes https://github.com/xamarin/maccore/issues/2561.
=> [xharness] Honor the TESTS_USE_SYSTEM environment variable in addition to the --use-system command-line argument.

dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets, tests/common/shared-dotnet.csproj, tests/dotnet/CentralPackageVersionsApp/AppDelegate.cs, tests/dotnet/CentralPackageVersionsApp/MacCatalyst/CentralPackageVersionsApp.csproj, tests/dotnet/CentralPackageVersionsApp/MacCatalyst/Makefile, tests/dotnet/CentralPackageVersionsApp/Makefile, tests/dotnet/CentralPackageVersionsApp/Packages.props, tests/dotnet/CentralPackageVersionsApp/README.md, tests/dotnet/CentralPackageVersionsApp/iOS/CentralPackageVersionsApp.csproj, tests/dotnet/CentralPackageVersionsApp/iOS/Makefile, tests/dotnet/CentralPackageVersionsApp/macOS/CentralPackageVersionsApp.csproj, tests/dotnet/CentralPackageVersionsApp/macOS/Makefile, tests/dotnet/CentralPackageVersionsApp/shared.csproj, tests/dotnet/CentralPackageVersionsApp/shared.mk, tests/dotnet/CentralPackageVersionsApp/tvOS/CentralPackageVersionsApp.csproj, tests/dotnet/CentralPackageVersionsApp/tvOS/Makefile, tests/dotnet/UnitTests/ProjectTest.cs
This unbreaks Central Package Management via https://github.com/microsoft/MSBuildSdks/tree/main/src/CentralPackageVersions which is being worked on for NuGet, see https://github.com/NuGet/Home/issues/6764
Fixes https://github.com/xamarin/xamarin-macios/issues/14452
Backport of #14532
=> [release/6.0.3xx-rc1] Set IsImplicitlyDefined="true" on the System.Runtime.InteropServices.NFloat.Internal PackageReference

mk/xamarin.mk
* xamarin/maccore@5958360612 [mlaunch] Fix booting simulator devices when the simulator app is already running in Xcode 13.3. Fixes #14560.
Diff: https://github.com/xamarin/maccore/compare/8287d1978617996f5a0f1c83c9264cc582c957fe..59583606121bcc15bad6580f3b0ee6ced8d0bdeb
=> [xcode13.3] Bump maccore.

mk/xamarin.mk
* xamarin/maccore@1c5dfc89f0 [mlaunch] Fix booting simulator devices when the simulator app is already running in Xcode 13.3. Fixes #14560.
* xamarin/maccore@4eb40042c1 Support --killdev with PID argument
Diff: https://github.com/xamarin/maccore/compare/8287d1978617996f5a0f1c83c9264cc582c957fe..1c5dfc89f0a104d5ef4fcf839ca2d02acf547415
=> [release/6.0.3xx-rc1] Bump maccore.

tools/devops/automation/templates/common/setup.yml
This is what Azure Devops defines:
* Build.SourceBranchName: the last path component of the branch.
* Build.SourceBranch: the complete ref spec for the branch.
We want the branch name without the 'refs/heads/' part. Unfortunately we can't
use Build.SourceBranchName, because for a branch name like
'release/6.0.3xx-rc1' the last path component is '6.0.3xx-rc1', not
'release/6.0.3xx-rc' - in other words it doesn't have all the information we
need.
That means we need to use the Build.SourceBranch value instead, and remove the
'refs/heads/' part. We already compute BRANCH_NAME like this everywhere else,
so just copy that implementation.
Backport of #14568
=> [main] [devops] Fix computing the BRANCH_NAME variable.

tests/xtro-sharpie/Makefile
This way there's no need for custom code for testing using a system install.
=> [xtro] Simplify makefile a bit by using the [IOS|MAC]_DESTDIR variable.

src/foundation.cs, tests/monotouch-test/Foundation/UrlTest.cs, tests/xtro-sharpie/api-annotations-dotnet/common-Foundation.ignore, tests/xtro-sharpie/common-Foundation.ignore
The headers do not say that a null parameter is allowed, but the
documentation and tests state otherwise:
https://developer.apple.com/documentation/foundation/nsurl/1572047-urlwithstring
The URL string with which to initialize the NSURL object. Must be a URL that conforms to RFC 2396. This method parses URLString according to RFCs 1738 and 1808.
=> [Foundation] Allow null parameters when creating a NSUrl from a string.

tests/mtouch/Makefile
The corresponding project was renamed some time ago, but not all places that
used the derived Make variable were updated at the same time as they should
have been.
=> [tests] Fix dependencies to build the mtouch tests.

tests/mtouch/MiscTests.cs
Our latest mono bump (in fd772aa82b972b8999caaafe4e34806621c7d360), brought in
these new public symbols. Accept them for now, but hopefully we'll be able to
make them private at some point.
Fixes https://github.com/xamarin/xamarin-macios/issues/14604.
=> [tests] Adjust the Xamarin.Tests.Misc.PublicSymbols test to accept Brotli-related symbols.

src/IOSurface/IODefs.cs, src/IOSurface/IOSurface.cs, src/IOSurface/IOSurfacePropertyKey.cs
This PR aims to bring nullability changes to IOSurface.
=> [iosurface] Add nullability to (generated and manual) bindings

tools/devops/automation/templates/tests/build.yml
* Move the logic to create the Xamarin.iOS and Xamarin.Mac symlinks together,
so easier spot differences (both expected and unexpected).
* Fix an issue with the logic where we'd make
/Library/Frameworks/Xamarin.iOS.framework/Versions/git point to
/Library/Frameworks/Xamarin.Mac.framework/Versions/Current.
=> [devops] Rework and fix issue with making local symlinks point to global installs.

tools/mtouch/Application.mtouch.cs
The bug in the AOT compiler is being fixed, but until then we can just ignore
the warning, with the idea of removing this code once the AOT bug has been
fixed.
Fixes these MTouch test failures:
* Xamarin.MTouch.BuildWithCulture("sl_SI"):
No warnings expected, but got:
Native linking warning: warning: '/Users/builder/azdo/_work/2/s/xamarin-macios/tests/mtouch/bin/Debug/tmp-test-dir/Xamarin.Tests.BundlerTool.CreateTemporaryDirectory107/mtouch-test-cache/arm64/Xamarin.iOS.dll.o' was built with class_ro_t pointer signing enabled, but previous .o files were not
* Xamarin.MTouch.BuildWithCulture("ur_IN"):
No warnings expected, but got:
Native linking warning: warning: '/Users/builder/azdo/_work/2/s/xamarin-macios/tests/mtouch/bin/Debug/tmp-test-dir/Xamarin.Tests.BundlerTool.CreateTemporaryDirect …
=> [mtouch] Ignore linker warning due to a bug in the AOT compiler we already know about.

tests/generator/Makefile, tests/mmptest/Makefile, tests/mtouch/Makefile, tests/sampletester/Makefile, tests/xharness/Jenkins/TestTasks/NUnitExecuteTask.cs
Fixes this NUnit warning:
> labels=All is deprecated and will be removed in a future release. Please use labels=Before instead.
We don't follow the suggestion from the warning, because the advantage of
writing the label after each test is that the test result will also be
printed, which means it's possible to see if any tests failed during the test
run, as opposed to having to wait until the entire test run is completed
(which can take a while) to realize that pretty much every test failed with
some silly mistake which could have been quickly fixed before re-running the
tests.
=> [tests] Request labels after each test from NUnit.

Make.config
Since we're not planning on any more breaking changes after RC 1, we can
ensure we don't have any accidental breaking changes by using the RC 1
assemblies as the baseline.
=> Use the tip of the 6.0.3xx-rc1 branch as the baseline for .NET API diffs.

tools/mlaunch/nupkg/build/Microsoft.DotNet.Mlaunch.targets
We started hitting this now when XHarness targets 6.0 and 7.0
=> Extract mlaunch nupkg only once when multi-targeting

src/foundation.cs, src/mapkit.cs, src/quicklook.cs, src/quicklookUI.cs
- A number of small correction in foundation and mapkit
- The [quicklook PR](https://github.com/xamarin/xamarin-macios/pull/14491) was completed reverted and redone
- Instead of trying to remove duplication (which can't be done since they are in different namespaces), I just took the originals and slapped attributes [NoMac] or NoEverythingElse on everything.
In the future we can do a better quicklook job, but this is good enough, and we have time pressure due to branching. 
API diff run locally. Only green additions, and each of those was confirmed to be either valid addition from a define removal or unrelated to a define removal PR.
=> Fix multiple API mistakes made in define removal

msbuild/Directory.Build.props
Includes an important fix for an MSBuild hang when the connection to the Mac can't be established
=> Updated Xamarin.Messaging version to 1.5.27

src/GameKit/GKScore.cs, src/GameKit/GameKit2.cs
This PR aims to bring nullability changes to GameKit.
Changing any == null or != null to is null and is not null
=> [gamekit] Add nullability to (generated and manual) bindings

src/ImageKit/Enums.cs
This PR aims to bring nullability changes to ImageKit.
=> [imagekit] Add nullability to (generated and manual) bindings

src/InputMethodKit/Enums.cs
This PR aims to bring nullability changes to InputMethodKit.
* This one was not in the src/frameworks.source either, but I will document this to fix later!
=> [inputmethodkit] Add nullability to (generated and manual) bindings

src/MLCompute/MLHelpers.cs
This PR aims to bring nullability changes to MLCompute.
=> [mlcompute] Add nullability to (generated and manual) bindings

builds/Makefile
This wasn't caught when we renamed DOTNET6_VERSION to DOTNET_VERSION (probably
because it was in the process of being added in a different PR).
=> [builds] Don't use DOTNET6_VERSION anymore, it's DOTNET_VERSION.

msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DittoTaskBase.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/Ditto.cs
Fixes this warning from the Codesign task:
C:\Users\rolf\...\Microsoft.iOS.Sdk\15.4.200-...\tools\msbuild\iOS\Xamarin.Shared.targets(2045,3): Cannot create 'C:\Users\rolf\source\iOSApp4\bin\Debug\net6.0-ios\ios-arm64\device-builds\iphone14.2-15.3.1\iOSApp4.app\Frameworks\ArcGIS-arm64.framework' because a file or directory with the same name already exists.
C:\Users\rolf\...\Microsoft.iOS.Sdk\15.4.200-...\tools\msbuild\iOS\Xamarin.Shared.targets(2045,3): Cannot create 'C:\Users\rolf\source\iOSApp4\bin\Debug\net6.0-ios\ios-arm64\device-builds\iphone14.2-15.3.1\iOSApp4.app\Frameworks\Runtimecore.framework' because a file or directory with the same name already exists.
which occurs when the Codesign task asks XVS to create output files for files from
inside ditto'ed directories, and if XVS …
=> [msbuild] Don't create output files for ditto'ed directories on Windows.

Make.config, tests/test-libraries/custom-type-assembly/Makefile, tests/test-libraries/custom-type-assembly/custom-type-assembly.csproj, tests/xammac_tests/xammac_tests.csproj
* Make the custom-type-assembly library build using assemblies relative to
MAC_DESTDIR, instead of poking into $(TOP)/_mac-build (for legacy Xamarin).
* Build the custom-type-assembly using a project file for .NET (and use our
local .NET).
* Change the default for [IOS|MAC]_DESTDIR when TESTS_USE_SYSTEM is set to
point to the system installation.
* Make sure 'MSBuildSDKsPath' isn't set when building the custom-type-assembly
(set by xibuild), it breaks a lot of things.
=> [tests] A few test fixes to make testing system installs better.

dotnet/targets/Xamarin.Shared.Sdk.props
This enables Visual Studio to set a specific `RuntimeIdentifier` for each platform when building all target frameworks in a MAUI project.
=> [dotnet] Adds platform specific RID options

dotnet/generate-target-platforms.csharp
Our min OS target versions are different between legacy Xamarin and .NET
(former supports earlier versions). The list of versions in the Versions.plist
contain all the versions supported by legacy Xamarin, but that's not correct
for .NET, so don't list any version in Version.plist that's lower than the
minimum OS version we support for a given platform.
=> [dotnet] Don't list OS versions we don't support.

tests/linker/CommonLinkAllTest.cs
=> [tests] Stop hardcoding system assembly version number in linker tests.

src/MediaAccessibility/MAImageCaptioning.cs, src/MediaAccessibility/MediaAccessibility.cs
This PR aims to bring nullability changes to MediaAccessibility.
=> [mediaaccessibility] Add nullability to (generated and manual) bindings

src/MediaToolbox/MTAudioProcessingTap.cs, src/MediaToolbox/MTFormatNames.cs, src/MediaToolbox/MTProfessionalVideoWorkflow.cs
This PR aims to bring nullability changes to MediaToolbox.
=> [mediatoolbox] Add nullability to (generated and manual) bindings

src/JavaScriptCore/Extensions.cs
This PR aims to bring nullability changes to JavaScriptCore.
=> [javascriptcore] Add nullability to (generated and manual) bindings

msbuild/Directory.Build.props
This should fix a bug where Hot Restart doesn't work with net6 because of a strong naming exception on build time
We need this in xcode13.3 to bump then in XamarinVS in order to service release 17.1 with this fix
Backport of #14682
=> [xcode13.3] Updated Hot Restart client version

src/Makefile, src/btouch.cs, tests/cecil-tests/AttributeTest.cs, tests/generator/BGenTool.cs, tests/generator/GeneratorTests.cs, tools/common/TargetFramework.cs, tools/mmp/Makefile, tools/mtouch/Makefile
This minimizes the code changes required for .NET 7.
=> [tools] Make the TargetFramework.DotNet* variables version-agnostic.

msbuild/Xamarin.Mac.Tasks.Core/Tasks/CompileAppManifestTaskCore.cs, msbuild/Xamarin.Mac.Tasks.Core/Xamarin.Mac.Tasks.Core.csproj, msbuild/Xamarin.Mac.Tasks/Tasks/CompileAppManifest.cs, msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Tasks.csproj, msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileAppManifestTaskBase.cs, msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DittoTaskBase.cs, msbuild/Xamarin.MacDev.Tasks.Core/Xamarin.MacDev.Tasks.Core.csproj, msbuild/Xamarin.MacDev.Tasks/Xamarin.MacDev.Tasks.csproj, msbuild/Xamarin.iOS.Tasks.Core/Tasks/CompileAppManifestTaskCore.cs, msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Tasks.Core.csproj, msbuild/Xamarin.iOS.Tasks.Windows/Tasks/CompileAppManifest.cs, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Tasks.Windows.csproj, msbuild/Xamarin.iOS.Tasks/Tasks/CompileAppManifest.cs, msbuild/Xamarin.iOS.Tasks/Xamarin.iOS.Tasks.csproj
This also meant:
* Using 'latest' as the C# language version for all msbuild/ project files.
* Enabling warnaserror for nullability warnings.
* Fix any nullability warnings in the CompileAppManifest files.
* Fix a nullability warning in the Ditto task.
* Fix any '== null' or '!= null' to use 'is null' and 'is not null'.
=> [msbuild] Enable nullability for the CompileAppManifest task.

src/AssemblyInfo.cs.in
Problem:
* Assembly A is compiled referencing Microsoft.*.dll v1.0.0.123
* Assembly B is compiled referencing assembly A, and Microsoft.*.dll v1.0.0.0
The C# compiler doesn't like this, and says something like:
> error CS1705: Assembly 'A' with identity 'A, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'Microsoft.iOS, Version=1.0.0.123, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' which has a higher version than referenced assembly 'Microsoft.iOS' with identity 'Microsoft.iOS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'
The C# compiler is right: you need all your local references to be at least
the version of any indirect references, otherwise you're compiling using
outdated API.
On the other hand, we know that [1] we don't have any API …
=> [dotnet] Use only the first three parts of our product version as the assembly version.

src/MultipeerConnectivity/Compat.cs, src/MultipeerConnectivity/MCSession.cs
This PR aims to bring nullability changes to MultipeerConnectivity.
=> [multipeerconnectivity] Add nullability to (generated and manual) bindings

src/NativeTypes/NMath.cs, src/NativeTypes/test.cs
This PR aims to bring nullability changes to NativeTypes.
=> [nativetypes] Add nullability to (generated and manual) bindings

src/MessageUI/MessageUI2.cs
This PR aims to bring nullability changes to MessageUI.
2. Changing any `== null` or `!= null` to `is null` and `is not null`
=> [messageui] Add nullability to (generated and manual) bindings

src/MobileCoreServices/UTType.cs
This PR aims to bring nullability changes to MobileCoreServices.
=> [mobilecoreservices] Add nullability to (generated and manual) bindings

src/MetricKit/MXMetaData.cs, src/MetricKit/MXMetric.cs, src/MetricKit/MXMetricManager.cs, src/MetricKit/MXMetricPayload.cs
This PR aims to bring nullability changes to MetricKit.
=> [metrickit] Add nullability to (generated and manual) bindings

msbuild/Directory.Build.props
Changed from 1.5.* to 1.6.* to match the versioning used in XamarinVS main branch (1.5.* now remains only for 17.2 based branches)
=> Updated Xamarin.Messaging to 1.6.1

tools/devops/automation/scripts/GitHub.psm1
Add a prefix that lets us know if the comment comes from a PR build
(using the public bots) or a CI build (using the private bots).
=> [CI] Add a prefix to the comment headers.

msbuild/Directory.Build.props
It includes a change revert because of threading freeze issues.
An issue has been detected in Xamarin.Messaging 1.5.26 and 1.6.1 that makes the code unstable and sensitive to thread freeze issues, so we are reverting back the changes until we can stabilize it.
This delays the fix of a bug in MSBuild command line builds for iOS remote builds.
=> Update Messaging to 1.6.2 (revert changes)

msbuild/Directory.Build.props
An issue has been detected in Xamarin.Messaging 1.5.26 and 1.6.1 that makes the code unstable and sensitive to thread freeze issues, so we are reverting back the changes until we can stabilize it.
This delays the fix of a bug in MSBuild command line builds for iOS remote builds.
=> Revert Messaging to 1.5.25: Threading issues

src/Foundation/NSUrlSessionHandler.cs
The behaviour from apple is wrong, PUT and POST are differnet in that PUT is idempotent.
Calling PUT several times successively has the same effect (that is no side effect),
where successive identical POST may have additional effects
We should not let the native code cache the calls.
Related issue: https://github.com/xamarin/maccore/issues/2571
=> [Foundation] Ensure that post requests are not cached by the native code.

src/Foundation/NSUrlSessionHandler.cs
The behaviour from apple is wrong, PUT and POST are differnet in that PUT is idempotent.
Calling PUT several times successively has the same effect (that is no side effect),
where successive identical POST may have additional effects
We should not let the native code cache the calls.
Related issue: https://github.com/xamarin/maccore/issues/2571 
Backport of #14729
=> [d17-2] [Foundation] Ensure that post requests are not cached by the native code.

tools/devops/automation/build-pipeline.yml, tools/devops/automation/scripts/GitHub.psm1, tools/devops/automation/templates/common/clean.yml, tools/devops/automation/templates/common/configure.yml
Since we have several builds per PR and several comments per build, the
comments sections are getting very noise. To fix that, we use GitHub
GraphQL to query all the comments for a PR (includes PR comments and
commit comments), filter them by user and title and minimize them
accordingly.
=> [CI] Set all comments as oudated after every build.

tools/devops/automation/scripts/bash/compare.sh, tools/devops/automation/templates/build/api-diff.yml
To avoid issues when setting automerging we add a status for the API
diff. If human intervention is needed to check the changes the status
will be set to error, this way the automerging wont happen. We set the
status to error even when we only have a warning, better safe than
sorry.
=> [CI] Add a status for the PR API diff.

tools/devops/automation/templates/build/api-diff-github-comment.yml
The dlls were renamed, the links were not, and the files use the name of the dll.
=> [CI] Fix the links for the API diff in dotnet.

tools/devops/automation/build-pipeline.yml, tools/devops/automation/scripts/GitHub.Tests.ps1, tools/devops/automation/scripts/GitHub.psm1, tools/devops/automation/scripts/MaciosCI.psd1, tools/devops/automation/scripts/TestResults.psm1, tools/devops/automation/templates/build/build.yml, tools/devops/automation/templates/tests/run-tests.yml
We have been leaving statueses as pending, the main reason is that when
we ran the tests, we set the wrong status. This was complicated because
we wrote comments AND set the statuses mixing two operations. We now
have the status and the comment separated for easy debugging and more
flexibility.
=> [CI] Clean the statuses mess.

tools/devops/automation/scripts/GitHub.psm1, tools/devops/automation/templates/build/api-diff.yml
I miss calculated the url of the statues for a CI build vs a PR build.
=> [CI] Fix the API diff statuses on CI

tools/devops/automation/templates/release/vs-insertion-prep.yml
Context: https://github.com/xamarin/yaml-templates/pull/185
Opts in to the new DateTime based MSI versioning to fix a recent issue
we saw with an MSI version moving backwards.
=> [build] Use new MSI versioning schema

tools/devops/automation/scripts/update-locproject.ps1
Full paths are valid and local paths are error prone because they depend on the number of checkouts done by vsts.
=> [CI] Do not use relative paths in the updated json.

msbuild/Directory.Build.props
Contains a fix to control build verbose logging of underlying Xamarin.Messaging libraries
=> Updated Xamarin.Messaging to 1.6.3

src/ObjCRuntime/Runtime.cs
Augment Runtime.GetNSObject to optionally create a new instance even if an
existing instance was found, if the existing instance isn't compatible with
the requested instance type.
Partial fix for https://github.com/xamarin/xamarin-macios/issues/13531.
=> [ObjCRuntime] Augment Runtime.GetNSObject to optionally create a new instance even if an existing instance was found.

src/ObjCRuntime/Runtime.cs
* We can remove entries in the object_map when the target is null (and we
don't need the corresponding GCHandle anymore, so it can be freed).
* When replacing an existing entry, we have to free the GCHandle.
=> [ObjCRuntime] Fix GCHandle leak in our NSObject map.

runtime/coreclr-bridge.m, src/Foundation/NSObject2.cs, src/ObjCRuntime/Runtime.CoreCLR.cs, src/ObjCRuntime/Runtime.cs
* We now create a tracking GCHandle for all NSObjects, not only the toggled ones.
CoreCLR will notify us when a tracked GCHandle's target enters finalization, and
we need to be notified for all NSObjects, not just the toggled ones.
* Augment the tracking callback to know about non-toggled objects, and in that
case report that the tracking GCHandle is a weak GCHandle.
* There's no need to store the tracking GCHandle in a field in the NSObject instance,
since we store it in our runtime object_map.
* Remove one place where we set the InFinalizerQueue flag, since it's no longer
required there (this reverts a previous attempt at fixing this problem - 0622ae4af2482cb9e66e8bceced4e669ab25909b)
- we only set the InFinalizerQueue flag in the …
=> [CoreCLR] Rework how we track the lifetime of managed NSObjects.

msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CreateInstallerPackageTaskBase.cs
The output directory might or might not be where the app bundle is: by default
it is, but if someone sets the PkgPackageDir variable to provide an alternate
directory for the pkg, then that won't be where we'll find the app bundle.
The good news is that we already have a property that tells us where the app
bundle is (the 'AppBundleDir' property), so just use that instead.
Also:
* Make sure that the output directory exists before we try to write to it.
* Only pass full paths to productbuild, which for some reason doesn't seem to
like relative paths.
Fixes https://github.com/xamarin/xamarin-macios/issues/14751.
=> [msbuild] Just use the 'AppBundleDir' variable to find the app bundle in the CreateInstallerPackage task. Fixes #14751.

runtime/runtime.m
If we try to process any exceptions, we'll throw an Objective-C exception,
which will likely be unhandled because we're pretty much at the top of the
stack, and when we handle this Objective-C exception we'll try to convert it
into a managed exception and throw that, and since there are no managed frames
on the stack we'll end up converting it to an Objective-C exception, which
we'll try to throw, and so on, eventually running into a stack overflow.
This is unnecessary, so just abort directly.
=> [runtime] Don't try process managed exceptions in xamarin_initialize.

src/ILLink.Descriptors.xml, src/Makefile
See https://github.com/xamarin/xamarin-android/issues/6626. The same issue applies to XI.
=> Workaround FirstChanceExceptionEventArgs being trimmed

tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
We can't return unretained INativeObjects to Objective-C, because they might
be freed at any point when the GC collects the managed object. Instead return
retained objects, that way they're not freed even if the GC collects the
managed object.
This fixes a random crash in the TestRegistrar.TestINativeObject when the GC
would run just after we've returned an INativeObject to native code, and later
used that native handle thinking it would still be valid.
Fixes https://github.com/xamarin/maccore/issues/2572.
=> [tests] Fix registrar tests to not return unretained INativeObjects to Objective-C. Fixes #xamarin/maccore@2572.

tools/devops/automation/templates/tests/run-tests.yml
We have a significant amount of logic using BUILD_REVISION to determine
whether we're in CI or not, so just set this variable to the current commit
hash.
=> [devops] Set the BUILD_REVISION variable when running the tests.

src/ObjCRuntime/Registrar.cs, tests/bindings-test/RegistrarBindingTest.cs, tests/mtouch/RegistrarTest.cs, tools/common/StaticRegistrar.cs
Fix lookup of block proxy attributes to look in protocols declared on base classes.
Broken pseudo code:
class BaseApplicationDelegate : NSObject, IUIApplicationDelegate {}
class MyApplicationDelegate : BaseApplicationDelegate {
[Export("application:didReceiveRemoteNotification:fetchCompletionHandler:")]
public void DidReceiveRemoteNotification (UIApplication application, NSDictionary userInfo, Action<UIBackgroundFetchResult> completionHandler) { }
}
the static registrar wouldn't figure out that the DidReceiveRemoteNotification method
comes from the UIApplicationDelegate, because it would only look in protocols defined
on MyApplicationDelegate, not any base classes.
The fix is to look in base classes too.
Also:
* Fix a boolean logic error when matching parameters between methods in another …
=> [static registrar] Fix lookup of block proxy attributes.

tools/devops/LocProject.json.in, tools/devops/automation/scripts/update-locproject.ps1, tools/devops/automation/templates/loc-translations.yml
Allow the Lcl paths to be updated to the correct paths and should stop OneLocBuild trying to move our lcl files which is happening every day in PRs like this: https://github.com/xamarin/xamarin-macios/pull/14806
Here is the updated LocProject.json that is generated: https://gist.github.com/tj-devel709/70bbb9e12345502f42d598834f26196c
=> [Localization] Update the Lcl paths

.github/fabricbot.json
Hi team, this PR introduces some updates to FabricBot to help us automate some steps in our triaging. A lot of these were brought over from the MAUI fabricbot.json but modified to fit into our workflow. As the person who has done the least amount of triaging on this team, feel free to let me know modifications / "things won't work because of ..." things!
While I cannot link the UI here, **if you want to see the items in the UI, you can download this json file and import it here** with FabricBot's UI Tool: https://portal.fabricbot.ms/bot/
When a `need-info` label is added, we send out a message saying the issue will be closed in 7 days if no info is provided
* This one is already implemented by @rolfbjarne and shows up here: https://github.com/xamarin/xamarin-macios/issues/14725#issuecommen …
=> [fabricbot] Update FabricBot with more useful commands

Make.config, Make.versions
Also bump our version band to try to avoid confusion.
=> Stop branding main as a release branch for .NET.

tools/devops/automation/scripts/bash/compare.sh, tools/devops/automation/scripts/bash/vsts-compare.sh, tools/devops/automation/templates/build/api-diff.yml
Due to a bug in azp we have some builds that fail due to
https://developercommunity.visualstudio.com/t/intermittent-quote-failure-in-bash-taskvariable-su/1391412
In order to work around it, we use a env var which is set. If the
interpolation did not work, we consider the build a failure to be
re-triggered.
=> [CI] Do not use variable interpolation.

msbuild/Xamarin.Localization.MSBuild/MSBStrings.Designer.cs, msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx, msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CreateBindingResourcePackageBase.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/CreateBindingResourcePackage.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/13393.
Backport of #14702.
=> [release/6.0.3xx-rc3] [msbuild] Copy binding resource files back to Windows. Fixes #13393.

src/ObjCRuntime/Runtime.cs
This may in some cases delay loading big chunks of .NET's globalization code
at startup until after reaching user's Main method.
=> [ObjCRuntime] Specify the string comparison to use when comparing strings in Runtime.IsARM64CallingConvention.

tools/devops/LocProject.json.in, tools/devops/automation/scripts/update-locproject.ps1, tools/devops/automation/templates/loc-translations.yml
From my conversations with the Loc team in an issue found here: https://ceapex.visualstudio.com/CEINTL/_workitems/edit/595781
the OneLocBuild tool cannot process paths that begin with the repo name. If we checkout only one repo in Azure Devops, this is not an issue, but we were checking out multiple repos (xamarin-macios and maccore) and when we checkout more than one repo, the Build.SourceDirectory starts one level higher than the repos - hence we need to begin our paths with our repo name. This was an issue and caused OneLocBuild to point to different paths than we wanted. 
This PR makes sure that we only checkout xamarin-macios in the localization job and makes the appropriate changes changing the paths. We also need to revert a PR: https://github.com/xamarin/xamarin-macios/pull/14811, …
=> [Localization] Use a self checkout and revert the explicit lcl paths

tools/devops/automation/build-pipeline.yml, tools/devops/automation/templates/build/prepare-pkg-stage.yml
We do not have any special requirements to perform the signing except
for the fact that needs to be EO complient. The new vm allows us to be
EO complient and reduces the number of real bots that we use.
=> [CI] Move the sing and notarize steps to a VM.

Make.versions, src/AssemblyInfo.cs.in
This is a follow up to 92ee92eeb57f470eea28a2119f7d329be6a24030, where we
changed the assembly version from four digits to three digits (i.e not include
the build number), because our managed API should be identical for (released)
versions where only the build number changes.
In this PR we go a bit further, because we're not supposed to have any API
differences unless the first two parts of the product version changes, which
means that we should only use need the two first parts of our product version
as the assembly version.
=> [dotnet] Use only the first two parts of our product version as the assembly version.

tools/common/CompilerFlags.cs, tools/common/Target.cs, tools/mtouch/Target.mtouch.cs
This also required a fix to not treat symbols that don't exist for a
particular abi as required.
Fixes https://github.com/xamarin/xamarin-macios/issues/14193.
=> [mtouch] Preserve the xamarin_dyn_* functions when we're handling Objective-C exceptions by unwinding managed code. Fixes #14193.

dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalyst/.template.config/localize/templatestrings.en.json, dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalyst/.template.config/template.json, dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalystbinding/.template.config/localize/templatestrings.en.json, dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalystbinding/.template.config/template.json, dotnet/Templates/Microsoft.iOS.Templates/ios-controller/.template.config/localize/templatestrings.en.json, dotnet/Templates/Microsoft.iOS.Templates/ios-controller/.template.config/template.json, dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/.template.config/localize/templatestrings.en.json, dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/.template.config/template.json, dotnet/Templates/Microsoft.iOS.Templates/ios/.template.config/localize/templatestrings.en.json, dotnet/Templates/Microsoft.iOS.Templates/ios/.template.config/template.json, dotnet/Templates/Microsoft.iOS.Templates/iosbinding/.template.config/localize/templatestrings.en.json, dotnet/Templates/Microsoft.iOS.Templates/iosbinding/.template.config/template.json, dotnet/Templates/Microsoft.iOS.Templates/ioslib/.template.config/localize/templatestrings.en.json, dotnet/Templates/Microsoft.iOS.Templates/ioslib/.template.config/template.json, dotnet/Templates/Microsoft.macOS.Templates/macos/.template.config/localize/templatestrings.en.json, dotnet/Templates/Microsoft.macOS.Templates/macos/.template.config/template.json, dotnet/Templates/Microsoft.tvOS.Templates/tvos/.template.config/localize/templatestrings.en.json, dotnet/Templates/Microsoft.tvOS.Templates/tvos/.template.config/template.json
Removes the "(Preview)" string from the title of the .NET templates.
Backport of #14842
=> [release/6.0.3xx] [dotnet/Templates] Remove preview language

src/PrintCore/Defs.cs, src/PrintCore/PrintCore.cs
This PR aims to bring nullability changes to PrintCore.
=> [printcore] Add nullability to (generated and manual) bindings

src/Photos/PHAssetChangeRequest.cs, src/Photos/PHAssetCreationRequest.cs, src/Photos/PHChangeRequest.cs, src/Photos/PHCompat.cs, src/Photos/PHFetchResult.cs, src/Photos/PHLivePhoto.cs, src/Photos/PHPhotoLibrary.cs
This PR aims to bring nullability changes to Photos.
=> [photos] Add nullability to (generated and manual) bindings

src/ReplayKit/RPBroadcastConfiguration.cs
This PR aims to bring nullability changes to ReplayKit.
2. Changing any `== null` or `!= null` to `is null` and `is not null`
=> [replaykit] Add nullability to (generated and manual) bindings

src/SensorKit/SRSensor.cs
This PR aims to bring nullability changes to SensorKit.
1. Changing any `== null` or `!= null` to `is null` and `is not null`
=> [sensorkit] Add nullability to (generated and manual) bindings

src/SpriteKit/SKNode.cs, src/SpriteKit/SKShapeNode.cs, src/SpriteKit/SKWarpGeometryGrid.cs
This PR aims to bring nullability changes to SpriteKit.
1. Changing any `== null` or `!= null` to `is null` and `is not null`
=> [spritekit] Add nullability to (generated and manual) bindings

src/System.ComponentModel/CancelEventArgs.cs
This PR aims to bring nullability changes to System.ComponentModel.
=> [systemcomponentmodel] Add nullability to (generated and manual) bindings

src/QuickLook/Thumbnail.cs
This PR aims to bring nullability changes to QuickLook.
=> [quicklook] Add nullability to (generated and manual) bindings

tools/nnyeah/nnyeah/Program.cs
- Errors were written with Write and then Exit which at least in VSCode would exit before the write flushed to the console
- WriteLine seems better behaved
=> [nnyeah] Fix race on error message output

tests/introspection/ApiSelectorTest.cs
- Fixes https://github.com/xamarin/xamarin-macios/issues/14905 by skipping with a link to https://github.com/xamarin/xamarin-macios/issues/14802
=> [introspection] Fix failures on older iOS/tvOS

src/Foundation/NSUrl.cs, tests/monotouch-test/Network/NSUrlTest.cs
- Fixes: https://github.com/xamarin/xamarin-macios/issues/14786
Before fix test crashed with same:
```
System.NullReferenceException: Object reference not set to an instance of an object.
at Foundation.NSUrl.op_Implicit(NSUrl url)
```
=> Fix crash with NSUrl implicit conversion and null

tools/nnyeah/nnyeah/nnyeah.csproj
- .NET5 on my mac has inconsistent debugging due to lack of support for apple's arm arch
- The tool is going to run against NET6, so why built it on NET5
=> [nnyeah] Bump to NET6

tools/nnyeah/Makefile
We need to be able to embed the dlls as a resource to compare the diff
assemblies. To do so we are going to ensure that we have called make in
the root dir so that the needed deps are present. This change is not yet
in the csproj, that will be a diff commit.
=> [Nnyeah] Ensure that we have all the needed xamarin-macios dlls when using make.

tools/apidiff/Makefile
Makes it easier to copy-paste commands to debug them with an IDE.
=> [apidiff] Pass full paths to mono-api-info and mono-api-html.

msbuild/Xamarin.HotRestart.PreBuilt/Xamarin.PreBuilt.iOS/Xamarin.PreBuilt.iOS.csproj
This new version contains a fix for incremental deployments when using Xamarin iOS Hot Restart.
=> Bumps Xamarin.HotRestart.Application to 1.1.5

msbuild/Xamarin.HotRestart.PreBuilt/Xamarin.PreBuilt.iOS/Xamarin.PreBuilt.iOS.csproj
This new version contains a fix for incremental deployments when using Xamarin iOS Hot Restart.
Backport of #14925
=> [release/6.0.3xx-rc3] Bumps Xamarin.HotRestart.Application to 1.1.5

src/foundation.cs
=> [Foundation] Make NSUserDefaults.VolatileDomainNames a property in XAMCORE_5_0.

Make.versions, msbuild/Xamarin.HotRestart.PreBuilt/Xamarin.PreBuilt.iOS/Xamarin.PreBuilt.iOS.csproj
This new version contains a fix for incremental deployments when using Xamarin iOS Hot Restart.
Backport of #14925
=> [release/6.0.3xx] Bumps Xamarin.HotRestart.Application to 1.1.5

tools/apidiff/Makefile
This also makes it easier to switch to .NET 5(+) versions of mono-api-info and mono-api-html
when that happens.
=> [apidiff] Use variables to reduce code duplication.

tools/apidiff/Makefile
We only care about what each type does, not what any base types might have
done (nothing we can do about that anyway).
=> [apidiff] Ignore inherited interfaces.

Make.versions, mk/xamarin.mk
* xamarin/maccore@29a1c1382e [mlaunch] Redirect stdout and stderr through a pty when launching in the simulator. Fixes #14834.
* xamarin/maccore@749e84cb16 [mlaunch] Make minor improvements to Main.cs
Diff: https://github.com/xamarin/maccore/compare/cf9f7409e9a79d0d0835863cc9f5afe77ba5e74a..29a1c1382e005e568b57d1b45e3877c8081dfc8b
Fixes https://github.com/xamarin/xamarin-macios/issues/14834.
Backport of #14946.
=> [release/6.0.3xx] Bump maccore to get fix for #14834.

mk/xamarin.mk
* xamarin/maccore@b457f4bdee [xcode13.3] [mlaunch] Redirect stdout and stderr through a pty when launching in the simulator. Fixes #14834.
Diff: https://github.com/xamarin/maccore/compare/59583606121bcc15bad6580f3b0ee6ced8d0bdeb..b457f4bdee9138998a3e875bfbca6993f73a47ff
Fixes https://github.com/xamarin/xamarin-macios/issues/14834.
Backport of #14946.
=> [xcode13.3] Bump maccore to get fix for #14834.

mk/xamarin.mk
* xamarin/maccore@29a1c1382e [mlaunch] Redirect stdout and stderr through a pty when launching in the simulator. Fixes #14834.
Diff: https://github.com/xamarin/maccore/compare/749e84cb162b945dafa85fd6dffe80a727a491cf..29a1c1382e005e568b57d1b45e3877c8081dfc8b
Fixes https://github.com/xamarin/xamarin-macios/issues/14834.
=> Bump maccore to get fix for #14834.

Make.config, Make.versions, dotnet/VERSIONS.md, system-dependencies.sh
Adjust our versioning scheme so that the NuGet version is
`Major.Minor.CommitDistance`. The previous scheme ("Major.Minor.&lt;fixed-ish
version&gt;") causes problems on branches producing stable builds, because each
new commit would end up with the same NuGet version, and we wouldn't be able
to push those to a NuGet feed because there might already be an existing
version there.
By using the commit distance in the NuGet version we ensure that every commit
has a different version.
=> Adjust versioning scheme for .NET to make the third field the commit distance.

tools/apidiff/Makefile
When we compare assemblies with different names (such as Xamarin.iOS vs
Microsoft.iOS, or Microsoft.iOS vs Microsoft.MacCatalyst), we need to adjust
one the xml definitions to match the other with regards to the assembly name.
=> [apidiff] Fix comparison of assemblies with different names.

tools/nnyeah/integration/Makefile, tools/nnyeah/nnyeah/Program.cs, tools/nnyeah/nnyeah/Reworker.cs
Reworker previous to this PR was very Lazy is it's init process. In
many ways this was beneficial, but was tricky to get right and made
nullability attributes a nightmare to add. It also included multiple "null objects"
that would show errors only at the end of a conversion when writing the file.
I replaced it with a single-pass init system, where the module is read
and all required attributes are fetched before processing begins.
Two requirements to consider:
- We don't want to ModuleDefinition.ReadModule to be repeated
- We don't want to fetch all of the attributes if reworking is not
necessary, but need the ModuleDefination to know that
A static factory method `CreateReworker` only returns a reworker
if work is required. This way, there is never a half-loaded state
to consider.
Other: …
=> [nnyeah] Refactor reworker to a 1-pass initialization

msbuild/Xamarin.MacDev.Tasks.Core/Tasks/AOTCompileTaskBase.cs, tools/common/Execution.cs, tools/common/StringUtils.cs
Following my comments on https://github.com/xamarin/xamarin-macios/pull/14913/files
=> [Tools] Enable nullability on StringUtils.

.gitmodules, Make.config, mk/versions.mk, tools/apidiff/Makefile
Switch to getting mono-api-[info|html] from a newly created repository we
control and where we can easily fix issues, since mono/mono isn't getting many
fixes anymore. In the past I know I've been reluctant to look at these tools,
just because of the hassle of setting things up to debug, and then the
paperwork to get the fixes in mono/mono, and then backported to the branch
where we need them.
This repo has a few other benefits:
* The tools are built using normal projects, which means they're easy to debug
in an IDE (mono/mono's code has generated project files, which used in-tree versions
of the BCL, and it got quite complex quite fast).
* One fewer dependency on the mono archive, so we're getting closed to be able
to drop it completely when we drop support for legacy Xamarin.
* #13669 …
=> [apidiff] Switch to getting mono-api-[info|html] from rolfbjarne/api-tools.

Make.config
=> [make] Add better error message when the required Xcode isn't installed.

tools/devops/automation/scripts/bash/compare.sh
It's only an error if it has breaking changes (which is handled elsewhere).
=> [devops] A PR API diff with changes isn't an error.

tests/xharness/Jenkins/Jenkins.cs
Both 'IncludeXtro' and 'IncludeDotNet' must be set to run the .NET xtro tests
(which means they're ignored if either is false).
=> [xharness] Fix logic to include the .NET xtro tests.

tests/xharness/Jenkins/Jenkins.cs, tools/devops/automation/templates/common/configure.yml
Which alo means there's no need to select them if .NET is enabled.
=> [xharness/devops] Enable .NET tests by default.

tools/devops/automation/templates/sign-and-notarized/dotnet-signing.yml
By doing this in our builds we reduce the time spent in the xma CI signing dlls that should have been signed.
=> [CI] Sign the contents of the bundle.zip to be used in xma.

src/VideoSubscriberAccount/VSAccountManager.cs, src/VideoSubscriberAccount/VSAccountMetadataRequest.cs, src/VideoSubscriberAccount/VSAccountProviderAuthenticationScheme.cs
This PR aims to bring nullability changes to VideoSubscriberAccount.
=> [videosubscriberaccount] Add nullability to (generated and manual) bindings

ISSUE_TEMPLATE.md
Point to a new document in the wiki explaining how to get version information
and build logs.
The wiki allows us to have longer explanations with screenshots, and it also
explains how to get a binary build log.
=> Update the issue template.

tools/apidiff/Makefile
There will always be an API diff between:
* legacy Xamarin.\*.dll assemblies and .NET Microsoft.\*.dll assemblies.
* Microsoft.iOS.dll and Microsoft.MacCatalyst.dll
so don't bother with logic to detect empty diffs, just assume they will never
be empty.
=> [apidiff] Remove detection of empty diffs for cases we know that will never happen.

tests/linker/ios/link all/LinkAllTest.cs, tests/linker/ios/link sdk/CryptoTest.cs, tests/monotouch-test/System.Net.Http/NetworkResources.cs
* Handle 502 and 503 errors in the TrustUsingOldPolicy and TrustUsingNewCallback tests. Fixes:
[FAIL] TrustUsingOldPolicy : System.Net.WebException : The remote server returned an error: (503) Service Unavailable.
[FAIL] TrustUsingNewCallback : System.Net.WebException : The remote server returned an error: (503) Service Unavailable.
* Add more http and https urls to try (and don't use microsoft.com). Hopefully fixes:
[FAIL] WebClient_SSL_Leak : At least one url should work
This is a follow-up to #14943.
=> [tests] Adjust a few linker tests to cope with unreliable networks.

msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.Messaging.Apple.targets
This should fix an annoying warning where the user builds an iOS project offline and get a message about that target couldn't be executed
=> Avoid executing _VerifyXcodeVersion when there's no connection to a Mac

runtime/monotouch-main.m, runtime/runtime.m, runtime/xamarin/runtime.h
Handle managed exceptions a bit better when we know there won't be any other
managed frames further up the stack (such as in the main method). In this
case, there's no use in trying to convert the managed exception into an
Objective-C exception, because we already know the process will be terminated.
Instead just print the exception to stderr, and abort immediately.
This means we'll actually get some useful information printed to stderr.
=> [runtime] Handle fatal managed exceptions a bit better in the runtime.

src/ObjCRuntime/Runtime.CoreCLR.cs, tools/mtouch/Errors.designer.cs, tools/mtouch/Errors.resx
A stack trace like this isn't all that helpful:
*** Terminating app due to uncaught exception 'System.Reflection.TargetException', reason: 'Object does not match target type. (System.Reflection.TargetException)
at System.Reflection.RuntimeConstructorInfo.CheckConsistency(Object target)
at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at ObjCRuntime.Runtime.InvokeMethod(MethodBase method, Object instance, IntPtr native_parameters) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.CoreCLR.cs:line 655
at ObjCRuntime.Runtime.InvokeMethod(MonoObject* methodobj, MonoObject* instanceobj, IntPtr native_parameters) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runt …
=> [Runtime] Provide better diagnostics if we fail to invoke a method in CoreCLR.

.github/workflows/localization_branch_sync.yml, tools/devops/automation/templates/loc-translations.yml
In the localization process, we try to delete the Localization branch, and then create a new Localization branch from main in order to sync main and Localization. In this seemingly random instance, the Localization branch was not able to be deleted https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6164579&view=logs&j=ee797c9a-308f-58f3-15cb-bf937fe4c606&t=83c41547-0a37-55a1-12ce-d2da371355ea. 
This caused us not to be able to push to the localization branch. If this happens again, let's force-with-lease the push to override this.
I will also be turning off the github action that also syncs the Localization branch in a similar manner since we do not need two automations that do the same thing.
=> [Localization] Use force-with-lease

tools/nnyeah/tests/unit/CompileALibrary.cs, tools/nnyeah/tests/unit/utils/Compiler.cs
- 'Error while attempting to map member System.IntPtr Foundation.NSObject::get_Handle() in old assembly'
- Also fix a strange directory name created by Cache.CreateTemporaryDirectory being called from async test method
=> [nnyeah] Add unit test showing most common nuget failure

Make.config, Make.versions, system-dependencies.sh
This is just a quick fix with as few changes as possible to auto-bump the versions so we don't have to do it manually.
=> [release/6.0.4xx] Automatically bump commit distance.

src/CoreMotion/CMCompat.cs, src/CoreMotion/CMDeviceMotion.cs, src/CoreMotion/CMMagnetometer.cs, src/CoreMotion/CMSensorDataList.cs, src/CoreMotion/Defs.cs, src/CoreMotion/Extras.cs
This PR aims to bring nullability changes to CoreMotion.
=> [coremotion] Add nullability to (generated and manual) bindings

dotnet/targets/Xamarin.Shared.Sdk.targets, tests/dotnet/UnitTests/ProjectTest.cs
This also means that we shouldn't load the linker's output. Note that we need
to check _LoadLinkerOutput even if we've already disabled the linker, because
there may be linker output from a previous (connected) build, and we don't
want to load that.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1542438.
=> [dotnet] Make sure to not run the linker when we're on a disconnected Windows build.

tests/linker/ios/link all/LinkAllTest.cs, tests/linker/ios/link sdk/CryptoTest.cs, tests/linker/ios/link sdk/LinkSdkRegressionTest.cs, tests/linker/mac/LinkAnyTest.cs, tests/monotouch-test/System.Net.Http/NetworkResources.cs
This is a backport of #14943 and #15018.
=> [release/6.0.4xx] Adjust a few tests to cope with broken networks.

tools/nnyeah/nnyeah/Errors.Designer.cs, tools/nnyeah/nnyeah/Errors.resx, tools/nnyeah/nnyeah/MemberNotFoundException.cs, tools/nnyeah/nnyeah/Program.cs, tools/nnyeah/nnyeah/TypeNotFoundException.cs
- Due to https://github.com/microsoft/vstest/issues/3658 it is not possible to test code that exits the process on error
- Create a base class for nnyeah exceptions that we want to explicitly report (and not crash), ConversionException
- Move Main to Main2 and wrap it in a try/catch for this exception
- ~~I did not catch everything as for now I want to crash with stack trace on unexpected failures~~
=> [nnyeah] Centralize error handling

src/appkit.cs
- Fixes https://github.com/xamarin/xamarin-macios/issues/15069
=> [AppKit] Add constructors for NSMenuToolbarItem classes

tests/introspection/ApiSelectorTest.cs
- Fixes https://github.com/xamarin/xamarin-macios/issues/14905 by skipping with a link to https://github.com/xamarin/xamarin-macios/issues/14802
Backport of #14911
=> [release/6.0.4xx] [introspection] Fix failures on older iOS/tvOS

dotnet/targets/Xamarin.Shared.Sdk.targets, tests/dotnet/UnitTests/ProjectTest.cs
This also means that we shouldn't load the linker's output. Note that we need
to check _LoadLinkerOutput even if we've already disabled the linker, because
there may be linker output from a previous (connected) build, and we don't
want to load that.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1542438.
Backport of #15076
=> [release/6.0.4xx] [dotnet] Make sure to not run the linker when we're on a disconnected Windows build.

tests/linker/ios/link all/LinkAllTest.cs, tests/linker/ios/link sdk/CryptoTest.cs, tests/linker/ios/link sdk/LinkSdkRegressionTest.cs, tests/linker/mac/LinkAnyTest.cs, tests/monotouch-test/System.Net.Http/NetworkResources.cs
This only affects tests, and is just in case we need to do more releases from this branch to get better test results.
This is a backport of #14943 and #15018.
Backport of #15077
=> [d17-2] Adjust a few tests to cope with broken networks.

tools/devops/automation/templates/sign-and-notarized/dotnet-signing.yml
The files of the bundle.zip are being re-zipped inside a 'bundle' folder after signing, which is wrong since everything else is expecting the files directly inside the zip file without parent folders (as we were doing before)
=> Fix bundle.zip structure in 'Sign bundle.zip' step

src/appkit.cs
Remove code that we needed at some point due to memory related issues. These
issues were fixed several years ago (newrefcount), so we no longer need this
code (in fact it causes problems, see #15089).
=> [appkit] Remove leftover code made obsolete by newrefcount.

msbuild/Xamarin.Shared/Xamarin.Shared.targets, tests/dotnet/UnitTests/ProjectTest.cs
The current directory at launch is the root directory of the app bundle. This
means that any files written to the current directory when an app is executed,
will be placed there. This becomes a problem when the app is rebuilt (and
resigned), because a valid macOS app bundle doesn't have any files in the root
directory of the app bundle, so signing fails.
We have logic to automatically crash crash reports from the app bundle, but it
turns out this is a more common problem with other types of files (and
folders), so improve the logic a bit:
* Add support for setting a property to automatically clean up everything from
an app bundle we don't think should be there (which is anything not in a
Contents/ subdirectory).
* Use the same property to add support for disabling any cleaning (we already …
=> [msbuild] Improve logic to clean up app bundle for unwanted files.

msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
The compiled entitlements should be placed in the intermediate Hot Restart app bundle so those can be picked up by the HotRestart Codesign task. Prior to this change, entitlements set in the project wouldn't be included in the app, making things like Keychain Access fail, even though it was configured.
Fixes https://developercommunity.visualstudio.com/t/Unable-to-use-MSAL-with-locally-connecte/1573064
=> [msbuild] Fixes Hot Restart compiled Entitlements output path

src/CoreFoundation/CFArray.cs, src/corefoundation.cs, tests/perftest/NativeArrayPerf.cs
Calling `Dlfcn.GetIntPtr` is quite slow and doing for each element of
an native array slows them down.
**Before**
```
BenchmarkDotNet=v0.12.1, OS=macOS 12.3.1 (21E258) [Darwin 21.4.0]
Apple M1, 1 CPU, 8 logical and 8 physical cores
.NET Core SDK=        6.0.100 [/usr/local/share/dotnet/sdk]
[Host] : .NET Core 6.0 (CoreCLR 6.0.522.21309, CoreFX 6.0.522.21309), Arm64 RyuJIT
Job=InProcess  Toolchain=InProcessEmitToolchain  IterationCount=3
LaunchCount=1  WarmupCount=3
```
|              Method | Length |            Mean |         Error |       StdDev |
|-------------------- |------- |----------------:|--------------:|-------------:|
| ArrayFromHandleFunc |      0 |       102.93 ns |     10.035 ns |     0.550 ns |
| ArrayFromHandleFunc |      1 |       559.07 ns |      0.533 ns |     0.029 ns …
=> [corefoundation] Cache `kCFNull` to avoid native calls

src/ObjCRuntime/Runtime.cs
This is computed **twice** _per instance_, when the instance is
* created: `NSObject.CreateManagedRef`
* released: `NSObject.ReleaseManagedRef`
However its (boolean) value remains identical for all instances of the same type.
This shows up as consuming a lot of time in the logs attached to https://github.com/xamarin/xamarin-macios/issues/15145
Basically two things are cached
* the selector for `xamarinSetGCHandle:flags:`, which makes it 15% faster;
* some platforms, but not macOS, have an optimization for the `Selector.GetHandle` API
* the result is cached into a `Dictionrary<IntPtr,bool>`
Note that the optimizations are not specific to CoreCLR nor macOS (so they are not fixes for the CoreCLR performance regression of the above mentioned issue).
OTOH it will also help performance for …
=> [perf] Cache `Runtime.IsUserType` results

tools/devops/automation/build-pipeline.yml, tools/devops/automation/build-pull-request.yml, tools/devops/automation/templates/main-stage.yml, tools/devops/automation/templates/sign-and-notarized/prepare-pkg-stage.yml, tools/devops/automation/templates/sign-and-notarized/setup.yml, tools/devops/automation/templates/sign-and-notarized/sign-and-notarized.yml
Passing the steps as a param does.
=> [CI] Using templates does not allow to run the pipeline without access to ESRP.

src/ModelIO/MDLAnimatedQuaternion.cs, src/ModelIO/MDLAnimatedValueTypes.cs
This PR aims to bring nullability changes to ModelIO.
1. Changing any `== null` or `!= null` to `is null` and `is not null`
=> [modelio] Add nullability to (generated and manual) bindings

dotnet/targets/Microsoft.Sdk.DefaultItems.template.props
One problem we hit when trying to build `net6.0-ios` projects from
a .NET 7 SDK & iOS workload, was that we ended up importing *two*
`AutoImport.props` files.
These are imported for any pack in `WorkloadManifest.json` declared as
an SDK:
"packs": {
"Microsoft.iOS.Sdk": {
"kind": "sdk",
So the way this has to work is that ny `<ItemGroup>` must be conditioned so
that `$(TargetFrameworkVersion)` matches the expected .NET SDK version.
I used `[MSBuild]::VersionEquals()` for all checks, because the value
is `v6.0` and the helper method properly handles this case for us.
When this change ships in a .NET 6 servicing release, we can then
update our .NET 7 packages to rely on this change.
This is equivalent to Android's change here:
https://github.com/xamarin/xamarin-android/commit/38b3fa6f2b5e7dea …
=> [release/6.0.4xx] [dotnet] Condition default inclusion on the target framework version.

dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets
'BundledNETCorePlatformsPackageVersion' will be 7.0 when building with .NET 7
and using the 'net6.0-*' TFM, but we still need the package reference in that
case. So change the condition to go off TargetFrameworkVersion instead.
=> [dotnet] Change condition when to include the System.Runtime.InteropServices.NFloat.Internal package reference.

tests/introspection/ApiPInvokeTest.cs
So there's no need to ignore tests for that particular scenario.
=> [tests] We're not implementing Mac Catalyst for legacy Xamarin.iOS.

dotnet/targets/Xamarin.Shared.Sdk.targets
The _BTouchCompileCommand property is never used, so we can just delete it.
=> [dotnet] Remove some dead build logic.

src/carplay.cs
In Objective-C constructors are automatically visible in derived classes as
well, but we need to replicate such constructors explicitly in derived
classes.
Fixes https://github.com/xamarin/xamarin-macios/issues/15169.
=> [CarPlay] Propagate constructors to derived classes. Fixes #15169.

dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets
'BundledNETCorePlatformsPackageVersion' will be 7.0 when building with .NET 7
and using the 'net6.0-*' TFM, but we still need the package reference in that
case. So change the condition to go off TargetFrameworkVersion instead.
Backport of #15183
=> [release/6.0.4xx] [dotnet] Change condition when to include the System.Runtime.InteropServices.NFloat.Internal package reference.

tools/nnyeah/tests/unit/CompileALibrary.cs
After the ctor work, failing test reported in issue [15120](https://github.com/xamarin/xamarin-macios/issues/15120) now passes
=> [nnyeah] Test now passes. Fixes #15120

msbuild/Messaging/Xamarin.Messaging.Build/TaskRunner.cs
With remote builds, a dedicated dotnet location is being used so the right versioning can be used and managed from VS in Windows. This dedicated dotnet location requires a custom .home location so the donet and nuget caches doesn't conflict with the global installation.
We need to consider and use this custom .home location when running dotnet commands remotely so the right caches are used
This should fix Bug: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1543495
=> Allow overriding HOME variable in dotnet remote builds

dotnet/targets/Microsoft.Sdk.DefaultItems.template.props
One problem we hit when trying to build `net6.0-ios` projects from
a .NET 7 SDK & iOS workload, was that we ended up importing *two*
`AutoImport.props` files.
These are imported for any pack in `WorkloadManifest.json` declared as
an SDK:
"packs": {
"Microsoft.iOS.Sdk": {
"kind": "sdk",
So the way this has to work is that ny `<ItemGroup>` must be conditioned so
that `$(TargetFrameworkVersion)` matches the expected .NET SDK version.
I used `[MSBuild]::VersionEquals()` for all checks, because the value
is `v6.0` and the helper method properly handles this case for us.
When this change ships in a .NET 6 servicing release, we can then
update our .NET 7 packages to rely on this change.
This is equivalent to Android's change here:
https://github.com/xamarin/xamarin-android/commit/38b3fa6f2b5e7dea …
=> [dotnet] Condition default inclusion on the target framework version.

tests/monotouch-test/HomeKit/HMCharacteristicTest.cs
Failing test example: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6258744&view=logs&j=2fda2bbb-61e0-581a-db35-947a0a9403f6&t=600bbb3b-ca38-5b81-eb71-a3c932424b24&l=18562
=> [CI] Ignore test on macOS because the class is not present. Fixes test failures.

tools/devops/automation/build-cronjob.yml
We already have 2 pipelines which is making the logic easier since we can tell when we are in a CI or a PR build. The same idea is going to work with cron jobs, making it very easy to indentify those jobs that fail and fix the translators or ios32 issues.
=> [CI] Add another pipeline just for cronjobs so that we can easily identify those builds.

runtime/trampolines.m, tests/monotouch-test/ObjCRuntime/Messaging.cs, tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
Fix 'skip_nested_brace' to not double skip characters.
Also add a test.
Fixes https://github.com/xamarin/xamarin-macios/issues/15253.
=> [runtime] Fix 'skip_nested_brace' to not read past the string. Fixes #15253.

tools/devops/automation/templates/build/build.yml
There is no need to provision the simulators on a build. Provisioning
simuatlors is giving problems with the EO pool after an upgrade to macOS
12.4.
We remove the provisioning from the build BUT not from the tests since
those tests are executed in non EO complient machines.
=> [CI] Do not provision simulators on builds.

tools/nunit3-console-3.10.0, tools/nunit3-console-3.11.1, tools/nunit3-console-3.9.0
We're putting all packages in the xamarin-macios/packages directory, and that
includes the nunit3-console package, so we need to point these shell scripts
that way.
Also make them behave the same with regards to stsack traces and the --debug
option to mono.
=> [tools] Fix nunit3-console shell scripts.

msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DSymUtilTaskBase.cs
Apple removed the -z / --minimize option in Xocde 13.3, so now if you use it
you get a warning: "ignoring unknown option: -z".
So just don't pass -z when using Xcode >= 13.3
Ref: https://github.com/dotnet/runtime/issues/66770
Ref: https://github.com/llvm/llvm-project/commit/5d07dc897707f877c45cab6c7e4b65dad7d3ff6d
=> [msbuild] Only pass -z to dsymutil when using Xcode 13.2 or earlier.

tools/nnyeah/nnyeah/AssemblyComparator/TypeReworker.cs, tools/nnyeah/nnyeah/Reworker.cs, tools/nnyeah/tests/unit/ClassHandleUnitTests.cs
This is very similar code to the `get_ClassHandle` case, so I refactored the code to handle it in the same way.
In the code to ensure that a method is `get_Handle` or `get_ClassHandle`, I added one extra layer of safety by asking if the declaring type is `NSObject` first.
Tests pass.
=> [nnyeah] Added correct mapping for NSObject.Handle fixing #15261

src/SceneKit/SCNMatrix4_dotnet.cs, src/SceneKit/SCNVector3.cs, src/SceneKit/SCNVector4.cs, tests/bindings-test/StructsAndEnums.cs, tests/monotouch-test/Asserts.cs, tests/monotouch-test/SceneKit/SCNMatrixTest.cs, tests/monotouch-test/SceneKit/SCNVector3Test.cs, tests/monotouch-test/SceneKit/SCNVector4Test.cs, tests/monotouch-test/monotouch-test.csproj, tests/test-libraries/libtest.h, tests/test-libraries/libtest.m, tests/test-libraries/rename.h, tests/xammac_tests/xammac_tests.csproj, tools/devops/automation/templates/tests/run-tests.yml
When we changed SCNMatrix4 to be column-major instead of row-major in .NET, there
were several other related changes we should have done but didn't do. In particular
we should have made transformation operations based on column-vectors instead of
row-vectors.
In legacy Xamarin, a vector would be transformed by a transformation matrix by doing
matrix multiplication like this:
[ x y z w] * [ 11 21 31 41 ]
| 12 22 32 42 |
| 13 23 33 43 |
[ 14 24 34 41 ]
In this case the vector is a row-vector, and it's the left operand in the multiplication.
When using column-major matrices, we want to use column-vectors, where the vector
is the right operand, like this:
[ 11 21 31 41 ] * [ x ]
| 12 22 32 42 |   | y |
| 13 23 33 43 |   | z |
[ 14 24 34 41 ]   [ w ]
This affects numerous APIs in SCNMatrix4, …
=> [release/6.0.3xx] [SceneKit] Fix SCNMatrix4 in .NET. Fixes #15094.

src/Foundation/NSObject2.cs, src/ObjCRuntime/Runtime.cs
Note that the call to native code still _always_ happen (not cached) since the application could use `class_addProtocol` to add conformance to a protocol at runtime.
So the cache is limited to the .net specific reflection code that is present (only) when the dynamic registrar is included inside applications. This is the default for macOS apps, but not iOS / tvOS or MacCatalyst apps.
The linker/trimmer will remove the caching code when the dynamic registrar is removed. IOW this PR should not have any impact, performance or size, for most iOS apps (where the dynamic registrar is removed by default).
Fix https://github.com/xamarin/xamarin-macios/issues/14065
Running Dope on macOS, a 2 minutes benchmark, shows the following times (in seconds and percentage) spent calling this API:
* …
=> [foundation] Cache parts of `NSObject.ConformsToProtocol`

.github/workflows/label-checker.yml, .github/workflows/localization-update.yml, .github/workflows/pwsh-ci.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: nathannaveen <42319948+nathannaveen@users.noreply.github.com>
=> chore: Set permissions for GitHub actions

tests/common/TestProjects/BasicPCLTest/MyLibrary/MyLibrary.csproj, tests/common/TestProjects/MyAppWithPackageReference/MyAppWithPackageReference.csproj, tests/common/TestProjects/MyAppWithPackageReference/MyAppWithPackageReference.dotnet.csproj, tests/common/TestProjects/MyExtensionWithPackageReference/MyExtensionWithPackageReference.csproj, tests/common/TestProjects/MyExtensionWithPackageReference/MyExtensionWithPackageReference.dotnet.csproj, tests/mmptest/src/PackageReferenceTests.cs
Bump the version to fix:
* https://github.com/xamarin/xamarin-macios/security/dependabot/1
* https://github.com/xamarin/xamarin-macios/security/dependabot/2
The dependency is in a tests, but this way we make the warning fo away.
=> [Tests] Bump Newtonsoft.Json version

tools/devops/automation/templates/build/build.yml
There are certain bots misbehaving and taking longer. We believ ethat it
might be due to some throttiling depending on their positio in the lab.
We are increasing the timeout for those cases.
=> [CI] Bump the build timeout.

tools/devops/automation/build-pipeline.yml
Other teams in xamarin/microsoft do no use forks but use dev branches.
The correct thing in our repo is to use forks, yet other developers
insist in not following our developement practices. The fact that this
branches are created results in 2 builds:
- One for CI
- On for the PR
It is harder to educate other developers than it is to ignore their
branches, therefore we have added the pattern dev/* to the exclude
list for branches in the CI build.
=> [CI] Ignore branches that start with dev/*

tools/nnyeah/nnyeah/ConstructorTransforms.cs, tools/nnyeah/nnyeah/Reworker.cs
For this one, there are a number of objects in macios that do not descend from `NSObject` but instead descend from `DisposableObject` so now we special case those too.
=> [nnyeah] Manage DisposableObject

tests/xharness/Jenkins/TestVariationsFactory.cs
=> Fix introspection selection when old simulators are present.

tools/devops/automation/templates/common/configure.yml, tools/devops/automation/templates/tests/stage.yml
Since we are generating jobs in parallel, we want to not even create the jobs which is more efficient than letting xharness skip the tests.
=> [CI] Allow to skip all tests in the parallel implementation.

tools/devops/automation/build-cronjob.yml, tools/devops/automation/build-pipeline.yml, tools/devops/automation/build-pull-request.yml, tools/devops/automation/templates/build/api-diff-stage.yml, tools/devops/automation/templates/build/build-stage.yml, tools/devops/automation/templates/main-stage.yml, tools/devops/automation/templates/tests/stage.yml
Allow to pass the xcode channel we are going to be using. This is to
ensure that we do not try to build the xcode14 branch in beta bots. At
the moment all bots are using the Beta channel, but once the lab has
been updated we should be able to move main to Stable.
=> [CI] Allow to pass the xcode channel.

tools/devops/automation/templates/tests/stage.yml
When the label is not present we set the value to false. We also needed
to make sure that the project is checked out when we try to write the
comment.
This should be backported to xcode14.
Backport of #15404
=> [xcode14] [CI] Fix the skip of tests.

tools/devops/automation/build-cronjob.yml, tools/devops/automation/build-pipeline.yml, tools/devops/automation/build-pull-request.yml
Xcode14 broke actool. We have created two diff bot images:
- Stable: Contains the latests stable xcode (xcode13.4)
- Beta: Contains the latests beta xcode OR will allow it to be
installed.
By doing this we mitigate the possible issues that the new Xcode might
create. Some of the bots have already been migrated.
This commit SHOULD NOT be backported to xcode14.
=> [CI] Use the Stable Xcode channel in main related branches.

tools/nnyeah/nnyeah/ConstructorTransforms.cs, tools/nnyeah/tests/unit/ConstructorTransformTests.cs
Turns out that if you have a lot of instance fields that are initialized in line, these get added to the ctor and it makes it substantially larger but doesn't break the reworking process. I can think of a couple cases where constructors will break but (1) they're aren't practically detectable and (2) they would still break here:
```
public class SomeClass : NSObject {
static HashSet<IntPtr> cache = new HashSet<IntPtr>();
static IntPtr CacheAdd (IntPtr handle) {
cache.Add (handle);
return handle;
}
public SomeClass(IntPtr handle) : base (CacheAdd (handle)) { }
}
```
This will generate a small constructor that will not convert correctly - at least the call to CacheAdd() will fail because of a type mismatch. However, since the typical use case is to just call the `base` and otherwise ignore …
=> [nnyeah] removed constructor size limit

tools/siminstaller/Program.cs
The url to download the list of simulators that are available has changed, and
the format changed slightly as well.
=> [siminstaller] Adjust according to recent Xcode changes.

.github/workflows/bump-global-json.yml, Makefile
Otherwise we have to do this manually, which becomes tedious quite fast.
See commit list: https://github.com/xamarin/xamarin-macios/pull/15426/commits for an example.
This logic has been tested here: https://github.com/xamarin/xamarin-macios/pull/15455
=> [actions] Add action to re-generate global.json for a dotnet/installer bump.

tools/devops/automation/post-build-pipeline.yml
It looks like this is needed for the post-build pipeline to kick in and publish builds to meastro.
Backport of #15129
=> [release/6.0.3xx] [devops] Fix the post-build pipeline after dependent pipeline rename.

tools/devops/automation/post-build-pipeline.yml
It looks like this is needed for the post-build pipeline to kick in and publish builds to meastro.
Backport of #15129
=> [release/6.0.4xx] [devops] Fix the post-build pipeline after dependent pipeline rename.

tools/devops/automation/templates/build/build-stage.yml
We have logic that depend on this variable to determine whether we're in CI or not.
Backport of #15374
=> [release/6.0.3xx] [devops] Make sure BUILD_REVISION is set to something during the build.

tools/devops/automation/templates/build/build-stage.yml
We have logic that depend on this variable to determine whether we're in CI or not.
Backport of #15374
=> [release/6.0.4xx] [devops] Make sure BUILD_REVISION is set to something during the build.

tests/api-shared/ObjCRuntime/Registrar.cs
This makes sure that adding FindType overloads won't break the tests.
=> [tests] Be explicit about parameters when looking for the Class.FindType method.

tools/devops/automation/post-build-pipeline.yml
We can't use the global.json located in the root of our repo, because makes it
required to use the exact .NET version we're referencing in our
eng/Versions.Details.xml file. So in order to not use it, we set the working
directory to the parent directory of xamarin-macios.
Otherwise this happens:
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
* You intended to execute a .NET program:
The application 'build' does not exist.
* You intended to execute a .NET SDK command:
A compatible installed .NET SDK for global.json version [6.0.301-rtm.22280.1] from [D:\a\1\s\xamarin-macios\global.json] was not found.
6.0.201 [C:\hostedtoolcache\windows\dotnet\sdk]
Install the [6.0.301-rtm.22280.1] .NET SDK or update …
=> [devops] Fix publishing in the presence of our global.json

tools/devops/automation/post-build-pipeline.yml
We can't use the global.json located in the root of our repo, because makes it
required to use the exact .NET version we're referencing in our
eng/Versions.Details.xml file. So in order to not use it, we set the working
directory to the parent directory of xamarin-macios.
Otherwise this happens:
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
* You intended to execute a .NET program:
The application 'build' does not exist.
* You intended to execute a .NET SDK command:
A compatible installed .NET SDK for global.json version [6.0.301-rtm.22280.1] from [D:\a\1\s\xamarin-macios\global.json] was not found.
6.0.201 [C:\hostedtoolcache\windows\dotnet\sdk]
Install the [6.0.301-rtm.22280.1] .NET SDK or update …
=> [devops] Fix publishing in the presence of our global.json (second part)

tools/common/StaticRegistrar.cs
C# method names generated by the C# compiler can have all sorts of invalid
characters, so just sanitize this a bit.
Fixes errors like these:
/Users/builder/azdo/_work/2/s/xamarin-macios/tests/dotnet/MySimpleApp/iOS/obj/Debug/net7.0-ios/iossimulator-x64/linker-cache/pinvokes.mm:23:70: error: use of undeclared identifier 'NSOperatingSystemVersion_objc_msgSend_stret'
typedef struct trampoline_struct_ppp(*func_xamarin_pinvoke_wrapper_<NSOperatingSystemVersion_objc_msgSend_stret>g____PInvoke|6_0) (void * basePtr, void * selector);
^
/Users/builder/azdo/_work/2/s/xamarin-macios/tests/dotnet/MySimpleApp/iOS/obj/Debug/net7.0-ios/iossimulator-x64/linker-cache/pinvokes.mm:23:114: error: expected ')'
typedef struct trampoline_struct_ppp(*func_xamarin_pinvoke_wrapper_<NSOperatingSystemVersion_objc_msg …
=> [registrar] Improve naming of generated P/Invoke wrappers.

msbuild/Xamarin.Mac.Tasks/Tasks/PrepareNativeReferences.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/PrepareNativeReferences.cs, msbuild/Xamarin.Shared/Xamarin.Shared.targets
I've chosen the iOS implementation, since it's a bit more advanced to support
remote builds (the Mac implementation didn't do anything at all).
This should have no effect, since we don't support remote builds for macOS
anyways.
=> [msbuild] Unify the PrepareNativeReferences task between iOS and Mac.

tools/nnyeah/nnyeah/Reworker.cs, tools/nnyeah/tests/unit/ConstructorTransformTests.cs
In working on the sidebar navigation tool, we were getting compile errors with a needed reference to Microsoft.iOS. @rolfbjarne noted that the assembly had two references to it, one without a public key.
There were two mistakes:
1 - The code was making an incomplete AssemblyNameReference, because for some reason the only available constructor in Cecil doesn't give you the option of setting the public key (fixed this by using the `Parse` method which does create a much more complete reference)
2 - The code was calling `ReplacePlatformAssemblyReference` too late and as a result as adding in another copy of the new platform assembly reference.
Added a test to ensure that when we make that change we get exactly one copy of the platform assembly.
=> [nnyeah] limit to one reference to Microsoft.iOS

Make.config
=> [release/6.0.4xx] A .NET 'servicing' release is also a stable release.

runtime/trampolines.m, tests/monotouch-test/ObjCRuntime/Messaging.cs, tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
Fix 'skip_nested_brace' to not double skip characters.
Also add a test.
Fixes https://github.com/xamarin/xamarin-macios/issues/15253.
Backport of #15257
=> [release/6.0.3xx] [runtime] Fix 'skip_nested_brace' to not read past the string. Fixes #15253.

msbuild/Xamarin.iOS.Tasks/Tasks/CompileAppManifest.cs
The exclusion of partial app manifests happened here, but the commit doesn't explain why:
https://github.com/xamarin/xamarin-macios/commit/f4a4b232f8130a9172f6ac86c52a64c42d227bd5#diff-178de6110858688b9f7c2e8e57a873f5ac9498b355a456bfc18547ab2df876bc
It's certainly wrong if the partial app manifest is a part of the project, but
this exclusion might be because partial app manifests might be added as a part
of the build as well.
So change the logic to copy partial app manifests from Windows if they exist
there.
Fixes https://github.com/xamarin/xamarin-macios/issues/15267.
Backport of #15328
=> [release/6.0.4xx] [msbuild] Copy partial app manifests to build server if they exists on Windows. Fixes #15267.

msbuild/Xamarin.iOS.Tasks/Tasks/CompileAppManifest.cs
The exclusion of partial app manifests happened here, but the commit doesn't explain why:
https://github.com/xamarin/xamarin-macios/commit/f4a4b232f8130a9172f6ac86c52a64c42d227bd5#diff-178de6110858688b9f7c2e8e57a873f5ac9498b355a456bfc18547ab2df876bc
It's certainly wrong if the partial app manifest is a part of the project, but
this exclusion might be because partial app manifests might be added as a part
of the build as well.
So change the logic to copy partial app manifests from Windows if they exist
there.
Fixes https://github.com/xamarin/xamarin-macios/issues/15267.
Backport of #15328
=> [release/6.0.3xx] [msbuild] Copy partial app manifests to build server if they exists on Windows. Fixes #15267.

dotnet/targets/Xamarin.Shared.Sdk.targets, tests/common/DotNet.cs, tests/dotnet/UnitTests/ProjectTest.cs
Validating that projects are only restored using valid runtime identifiers
have turned out to be an interesting rabbit hole.
Nobody seems to dispute the fact that it's a correct validation, the problem
is that it apparently turns out quite complicated to not do the wrong thing
for projects with multiple target frameworks.
In some scenarios apparently the Restore target might want to restore all
target frameworks, which breaks down if whatever the user wants to do requires
setting a runtime identifier, because then that runtime identifier is set for
all target frameworks.
So for the sake of simplicity, we're going to try removing this validation for
the Restore target (we're keeping it for the Build target).
There are thus two potential scenarios:
1. The Restore succeeds using invalid …
=> [release/6.0.4xx] [dotnet] Accept invalid runtime identifiers for Restore.

dotnet/targets/Xamarin.Shared.Sdk.targets, tests/common/DotNet.cs, tests/dotnet/UnitTests/ProjectTest.cs
Validating that projects are only restored using valid runtime identifiers
have turned out to be an interesting rabbit hole.
Nobody seems to dispute the fact that it's a correct validation, the problem
is that it apparently turns out quite complicated to not do the wrong thing
for projects with multiple target frameworks.
In some scenarios apparently the Restore target might want to restore all
target frameworks, which breaks down if whatever the user wants to do requires
setting a runtime identifier, because then that runtime identifier is set for
all target frameworks.
So for the sake of simplicity, we're going to try removing this validation for
the Restore target (we're keeping it for the Build target).
There are thus two potential scenarios:
1. The Restore succeeds using invalid …
=> [release/6.0.3xx] [dotnet] Accept invalid runtime identifiers for Restore.

src/Foundation/NSObject2.cs
CoreCLR does not like running into methods declared as internal calls:
[MethodImplAttribute (MethodImplOptions.InternalCall)]
and will fail with an error, even if the method is never executed, just encountered by the JIT:
ECall methods must be packaged into a system module
In the early days of .NET support we solved this by adding an indirection for
CoreCLR, where the internal call was hidden inside a managed call that would
never be executed at runtime. This seems to work fine in most cases, except
when the debugger attached, when I'm guessing the JIT is more aggressive, and
looks further ahead (and fails).
On the other hand, in the early days of .NET support on macOS the managed code
had to work for both Mono and CoreCLR without modification (since the same
implementation assembly would …
=> [release/6.0.4xx] [CoreCLR] Avoid having any internal calls in managed code for CoreCLR. Fixes #15343.

dotnet/Makefile
We must use the sdk manifest band when computing the path into sdk-manifests
to install workloads, otherwise they won't be found after installation.
This is a problem when building with .NET 6.0.301, because we want to install
into the sdk-manifests/6.0.300 directory, not sdk-manifests/6.0.301 directory.
=> [dotnet] Use the correct manifest version band.

src/AssemblyInfo.cs.in, src/Makefile
This is a workaround to create assemblies with a higher version than the
stable versions we released for Xcode 13.3. The stable versions we released
for Xcode 13.3 has a <osmajor>.<osminor>.300 version number, but that version
scheme has been changed, where the third digit from now on will always be 0 in
the assembly version. However, this means that until Apple releases new OS
versions (and we bind those versions), the assembly version will be lower than
the stable version wherever we've implemented the new versioning scheme. This
complicates testing, so just bump the third digit to 600 until we're using a
new Xcode (and thus presumably new OS versions as well). This workaround can
be removed at that point, but implement it so that it will just be
skipped/ignored if it isn't removed.
=> [src] Adjust AssemblyVersion for .NET with Xcode 13.3.

runtime/monovm-bridge.m
There's a bug in the Mono runtime where the interpreter does not disable optimizations when the debugger is attached, which leads to the interpreter optimizing code and the debugger ending up rather confused.
The bug is fixed in the Mono runtime (https://github.com/dotnet/runtime/pull/71436), but there's no immediate way for the runtime to release this fix, so here we're implementing a workaround that disables interpreter optimizations if the debugging is enabled. It's somewhat clunky because the Mono external API wasn't designed for this, so we have to abuse the API a bit to accomplish the effect we want.
This is somewhat risky (since we're changing the startup path in a pretty big way), but there's an escape hatch via an environment variable, and also the workaround will not be in …
=> [release/6.0.3xx] [debugger] Work around a debugger issue when using the interpreter.

tools/devops/automation/templates/build/api-diff-build-and-detect.yml, tools/devops/automation/templates/build/build.yml
For some reason the C# compilers crash a lot during the build in src/ when
building for the API diff (but not the normal build!). So test the theory that
we're overloading the bot in question (OOM maybe?) by slowing down a bit.
I have to say that if this works and the theory is proven, it's kind of sad
that after over a decade doing -j8 the bot situation has gotten worse...
Backport of #15471
=> [xcode14] [devops] Try parallelize less during the API diff build.

tests/xtro-sharpie/xtro-sanity/Sanitizer.cs
When working on the bindings we can use the "AUTO_SANITIZE" env var to
let xtro know that we want the lines that have been fixed to be removed,
unfortunatly this mode has a bug. When we autosanitized we should do the
same as the skip and not return the lines that have been cleaned as the
return code.
Returning the error code meant that when we did make all, the
first target (classic) would work, but the second target would not
because the first one failed.
Doing this allows to work on the bindings and have AUTO_SANITIZE work
both for classic and dotnet when doing make all.
=> [Xtro] Ensure that when we do auto sanitize we do not return a fail.

tools/nnyeah/nnyeah/Reworker.cs, tools/nnyeah/tests/unit/DependencyRemovedTests.cs
The code that creates the `NativeIntegerAttribute` class was putting the wrong attribute onto it (`AttributeTargets` instead of `AttributeUsageAttribute`).
Added a test for all the attributes on `NativeIntegerAttribute`
=> [nnyeah] fix incorrect attribute

tools/devops/automation/templates/tests/build.yml
=> [xcode14] [CI] Remove older pkgs in the system to make sure we are not running the tests with an older version.

msbuild/Xamarin.iOS.Tasks.Windows/Tasks/PrepareAppBundle.cs
Hot Restart expects the archived-expanded-entitlements.xcent to be empty. If any entitlements are added to that file, the new app signature will be invalid.
These changes ensure that file will be an empty plist when extracting the PreBuilt app.
Partial fix for https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1550700
Backport of #15558
=> [release/6.0.4xx] Ensure the Hot Restart bundle does not have any entitlements set

msbuild/Xamarin.iOS.Tasks.Windows/Tasks/PrepareAppBundle.cs
Hot Restart expects the archived-expanded-entitlements.xcent to be empty. If any entitlements are added to that file, the new app signature will be invalid.
These changes ensure that file will be an empty plist when extracting the PreBuilt app.
Partial fix for https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1550700
Backport of #15558
=> [release/6.0.3xx] Ensure the Hot Restart bundle does not have any entitlements set

msbuild/Xamarin.iOS.Tasks.Windows/Tasks/PrepareAppBundle.cs
Hot Restart expects the archived-expanded-entitlements.xcent to be empty. If any entitlements are added to that file, the new app signature will be invalid.
These changes ensure that file will be an empty plist when extracting the PreBuilt app.
Partial fix for https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1550700
=> Ensure the Hot Restart bundle does not have any entitlements set

tools/nnyeah/nnyeah/InstructionExtensions.cs, tools/nnyeah/nnyeah/MethodTransformations.cs, tools/nnyeah/nnyeah/Transformation.cs
Fixed an issue that prevented the geo sample from working.
There are three tightly entwined changes in this.
The first is adding special case mapping from `AVMediaType` -> `AVMediaTypes`.
This is fairly straight forward in that the old code will have calls to things like `AVMediaType.Video`, which is a method that doesn't exist in .NET 6 and returns the NSString equivalent of "Video". The change is to replace the call to the property with the following code:
```
ldc.i4 someConstant
call AVMediaExtensions.GetConstant ()
```
which is equivalent to the old code. Sorry about the magic numbers. Without putting in a reference to AVFoundation (no thanks), this seemed to be a reasonable concession.
The second change is that Cecil needs to know if we change a branch target, so whenever we make a …
=> [nnyeah] Fix for branch targets and AVMediaTypes

tools/mlaunch/Makefile
- A side effect of https://github.com/xamarin/xamarin-macios/commit/ac1fa258168e16b6ece16f510135ebdf0d23b1ee is that the permission of bin/mlaunch is no longer +x for non-root, which means it is unusable.
This was with the fix:
```
% ls -la _ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mlaunch 
-rwxr-xr-x  1 donblas  staff  165 Jun 17 15:25 _ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mlaunch
```
and this is from an xcode14 build locally:
```
% ls -la _ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mlaunch
-rwxr--r--  1 donblas  staff  165 Jul 14 08:06 _ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mlaunch
```
Backport of #15566
=> [d17-3] [mlaunch] Fix permisisons after extracting from nuget

tools/mlaunch/Makefile
- A side effect of https://github.com/xamarin/xamarin-macios/commit/ac1fa258168e16b6ece16f510135ebdf0d23b1ee is that the permission of bin/mlaunch is no longer +x for non-root, which means it is unusable.
This was with the fix:
```
% ls -la _ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mlaunch 
-rwxr-xr-x  1 donblas  staff  165 Jun 17 15:25 _ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mlaunch
```
and this is from an xcode14 build locally:
```
% ls -la _ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mlaunch
-rwxr--r--  1 donblas  staff  165 Jul 14 08:06 _ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mlaunch
```
=> [mlaunch] Fix permisisons after extracting from nuget

msbuild/Messaging/Xamarin.Messaging.Build/TaskRunner.cs, msbuild/Xamarin.MacDev.Tasks.Core/Tasks/BTouchTaskBase.cs, msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ComputeRemoteGeneratorPropertiesTaskBase.cs, msbuild/Xamarin.MacDev.Tasks.Core/Tasks/FindAotCompilerTaskBase.cs
Overriding HOME is dangerous because it could cause unwanted side effects, like breaking the keychain API logic.
For this reason, we need to use a custom environment variable to store the custom home used by the XMA dotnet SDK.
This custom home should be passed everywhere as environment settings when we invoke the dotnet tool
=> [d17-3] Set custom home env var from XMA Build Agent

msbuild/Messaging/Xamarin.Messaging.Build/TaskRunner.cs, msbuild/Xamarin.MacDev.Tasks.Core/Tasks/BTouchTaskBase.cs, msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ComputeRemoteGeneratorPropertiesTaskBase.cs, msbuild/Xamarin.MacDev.Tasks.Core/Tasks/FindAotCompilerTaskBase.cs
Overriding HOME is dangerous because it could cause unwanted side effects, like breaking the keychain API logic.
For this reason, we need to use a custom environment variable to store the custom home used by the XMA dotnet SDK.
This custom home should be passed everywhere as environment settings when we invoke the dotnet tool
=> Set custom home env var from XMA Build Agent

src/appkit.cs
- Fixes https://github.com/xamarin/xamarin-macios/issues/15565
=> [appkit] Add missing NullAllowed on NSSavePanel.AllowedFileTypes

tests/introspection/iOS/iOSApiPInvokeTest.cs
- Both tests directly asserted there were no errors, and tried to print results from an unused 'failed_api' variable.
- However, details were being written via `ReportError` in the base class's 'error_output' that was not being printed
- AssertIfErrors on the base class prints that, and asserts that there are no errors so it works for both these cases
I checked the other tests that asserted against 0 errors, and they all seems to have valid test data to report, and thus
appear fine.
=> [tests] Fix MonoNativeFunctionWrapper/MonoPInvokeCallback to report specific errors

msbuild/Xamarin.iOS.Tasks/Model/DataItem.cs, msbuild/Xamarin.iOS.Tasks/Model/DataSet.cs
Fixes these warnings:
msbuild/Xamarin.iOS.Tasks/Model/DataItem.cs(25,31): warning CS0169: The field 'DataItem.UnsupportedData' is never used [xamarin-macios/msbuild/Xamarin.iOS.Tasks/Xamarin.iOS.Tasks.csproj]
msbuild/Xamarin.iOS.Tasks/Model/DataSet.cs(12,31): warning CS0169: The field 'DataSet.JsonData' is never used [xamarin-macios/msbuild/Xamarin.iOS.Tasks/Xamarin.iOS.Tasks.csproj]
=> [msbuild] Ignore CS0169 in a few places.

tests/msbuild/Xamarin.MacDev.Tasks.Tests/Xamarin.MacDev.Tasks.Tests.csproj
Fixes these compiler warnings:
xamarin-macios/src/ObjCRuntime/ErrorHelper.cs(22,17): warning CS0436: The type 'ProductException' in 'xamarin-macios/tests/msbuild/Xamarin.MacDev.Tasks.Tests/../../../tools/common/error.cs' conflicts with the imported type 'ProductException' in 'Xamarin.iOS.Tasks, Version=15.11.0.465, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'. Using the type defined in 'xamarin-macios/tests/msbuild/Xamarin.MacDev.Tasks.Tests/../../../tools/common/error.cs'. [xamarin-macios/tests/msbuild/Xamarin.MacDev.Tasks.Tests/Xamarin.MacDev.Tasks.Tests.csproj]
xamarin-macios/tools/common/error.cs(10,34): warning CS0436: The type 'ErrorHelper' in 'xamarin-macios/tests/msbuild/Xamarin.MacDev.Tasks.Tests/../../common/ErrorHelper.tests.cs' conflicts with the imported type …
=> [tests] Don't include ErrorHelper.cs nor error.cs in Xamarin.MacDev.Tasks.Tests.

msbuild/Xamarin.iOS.Tasks.Windows/Tasks/PrepareAppBundle.cs
Hot Restart expects the archived-expanded-entitlements.xcent to be empty. If any entitlements are added to that file, the new app signature will be invalid.
These changes ensure that file will be an empty plist when extracting the PreBuilt app.
Partial fix for https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1550700
Backport of #15558
=> [release/7.0.1xx-preview7] Ensure the Hot Restart bundle does not have any entitlements set

tools/nnyeah/nnyeah/AssemblyConverter.cs, tools/nnyeah/nnyeah/Errors.Designer.cs, tools/nnyeah/nnyeah/Errors.resx, tools/nnyeah/nnyeah/Program.cs, tools/nnyeah/tests/integration/IntegrationExamples.cs
Added code to automagically find the legacy `Xamarin.platform.dll` file instead of requiring it on the command line.
As noted in the code comments, this is using the name of the Microsoft platform assembly to determine the platform. Pulling the platform out of the input assembly was both unreliable and at a place where we don't have the context to handle it gracefully and it's also slow since we're forcing a double load of the assembly in cecil. If the assembly has not platform dependencies, we will handle that at a place that is designed to handle it and the tool will exit without error having done no work.
Augmented existing tests to use this code.
=> [nnyeah] Added code to look up the legacy platform dll instead of requiring it.

src/healthkitui.cs
Should be in 13,0 no 9 as inferred from the iOS attr.
=> [HealthKitUI] Add support for xcode14 beta4.

src/UIKit/UIEnums.cs, src/uikit.cs
This change should have 0/null/nine/nada changes in the API. The goal is
to remove the preprocessor directives to ensure that the xcode14
bindings have a smaller diff and are easier to review.
Backport of #15601
=> [xcode14] [UIKit] Remove the preprocessor directives for watchOS.

src/generator.cs
- In the [Xcode 14 Photo PR](https://github.com/xamarin/xamarin-macios/pull/15608) a test is failing with this:
```
ILLINK : error MT2362: The linker step 'Registrar' failed during processing: One or more errors occurred. (The type 'Photos.PHPersistentObjectChangeDetails' (used as a return type in Photos.PHPersistentChange.ChangeDetails) is not available in MacCatalyst 16.0 (it was introduced in MacCatalyst 16.0.0). Please build with a newer MacCatalyst SDK (usually done by using the most recent version of Xcode). [/Users/donblas/Programming/xamarin-macios/tests/dotnet/MySimpleApp/MacCatalyst/MySimpleApp.csproj]
) (The type 'Photos.PHObjectType' (used as a parameter in Photos.PHPersistentChange.ChangeDetails) is not available in MacCatalyst 16.0 (it was introduced in MacCatalyst 16.0.0). …
```
=> [generator] Do not zero-extend implied catalyst attributes

src/generator.cs
- In the [Xcode 14 Photo PR](https://github.com/xamarin/xamarin-macios/pull/15608) a test is failing with this:
```
ILLINK : error MT2362: The linker step 'Registrar' failed during processing: One or more errors occurred. (The type 'Photos.PHPersistentObjectChangeDetails' (used as a return type in Photos.PHPersistentChange.ChangeDetails) is not available in MacCatalyst 16.0 (it was introduced in MacCatalyst 16.0.0). Please build with a newer MacCatalyst SDK (usually done by using the most recent version of Xcode). [/Users/donblas/Programming/xamarin-macios/tests/dotnet/MySimpleApp/MacCatalyst/MySimpleApp.csproj]
) (The type 'Photos.PHObjectType' (used as a parameter in Photos.PHPersistentChange.ChangeDetails) is not available in MacCatalyst 16.0 (it was introduced in MacCatalyst 16.0.0). …
```
=> [xcode14] [generator] Do not zero-extend implied catalyst attributes

tools/nnyeah/nnyeah/Errors.Designer.cs, tools/nnyeah/nnyeah/Errors.resx, tools/nnyeah/nnyeah/Program.cs
Output:
```
% dotnet nnyeah --help
-h, -?, --help             
-i, --input=VALUE          
-o, --output=VALUE         
-v, --verbose              
-f, --force-overwrite      
-s, --suppress-warnings    
-x, --xamarin-assembly=VALUE
-m, --microsoft-assembly=VALUE
nnyeah is a tool for converting legacy Xamarin assemblies (pre .NET 6)
to work with .NET 6 or later. It does this by scanning the --input assembly for
dependencies of legacy methods, types, or fields and converts them to references
in the --microsoft-assembly and writes the result in the --ouput assembly.
nnyeah attempts to find the legacy Xamarin assembly automatically. If it can't
find it, you will need to supply a path to it with the --xamarin-assembly
argument.
nnyeah needs to have a path to target Microsoft assembly using the …
```
=> [nnyeah] better help, change priority of processing help request.

msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
The directory that contains illink.dll is now net7.0
=> [net7.0] Updates the path to illink when building from Windows

msbuild/Xamarin.Mac.Tasks/Tasks/CreateEmbeddedResources.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/CreateEmbeddedResources.cs, msbuild/Xamarin.Shared/Xamarin.Shared.targets
I've chosen the iOS implementation, since it's a bit more advanced to support
remote builds (the Mac implementation didn't do anything at all).
This should have no effect, since we don't support remote builds for macOS
anyways.
=> [msbuild] Unify the CreateEmbeddedResources task between iOS and Mac.

dotnet/targets/Xamarin.Shared.Sdk.targets, msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets, msbuild/Xamarin.MacDev.Tasks.Core/Tasks/BundlerToolTaskBase.cs, msbuild/Xamarin.Shared/Xamarin.Shared.targets, msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets, tests/ComputeRegistrarConstant.targets, tests/common/shared-dotnet.csproj, tests/monotouch-test/dotnet/MacCatalyst/monotouch-test.csproj, tests/monotouch-test/dotnet/macOS/monotouch-test.csproj, tests/monotouch-test/dotnet/shared.csproj, tests/monotouch-test/dotnet/tvOS/monotouch-test.csproj, tests/monotouch-test/monotouch-test.csproj, tests/xammac_tests/xammac_tests.csproj, tests/xharness/Jenkins/TestData.cs, tests/xharness/Jenkins/TestVariationsFactory.cs
However, passing --registrar:... to mtouch/mmp will override any MSBuild property.
=> [dotnet] Make it possible to specify the registrar using a 'Registrar' property in MSBuild.

tests/msbuild/Xamarin.MacDev.Tests/TestHelpers/LogEvent.cs
This should improve output from the quite useless:
[22:15:50.7076240] Xamarin.Tests.LogEvent
[22:15:50.7076470] Xamarin.Tests.LogEvent
[22:15:50.7076660] Xamarin.Tests.LogEvent
[22:15:50.7076850] Xamarin.Tests.LogEvent
to something better.
=> [tests] Improve output when writing log events in test logs.

tools/compare-commits.sh, tools/devops/automation/scripts/bash/compare.sh
Fix an issue when doing API comparison for PRs with multiple commits, where we'd only do the comparison for the last commit, by not ignoring the provided base hash in the compare-commits script.
=> [tools] Fix issue when doing api comparison for PRs with multiple commits

runtime/trampolines.m
Allow code like this
```csharp
[DllImport(Constants.ObjectiveCLibrary, EntryPoint = "objc_msgSendSuper")
static extern IntPtr IntPtr_objc_msgSendSuper(IntPtr receiver, IntPtr selector);
[DllImport(Constants.ObjectiveCLibrary, EntryPoint = "objc_msgSendSuper")]
static extern void void_objc_msgSendSuper(IntPtr receiver, IntPtr selector, IntPtr arg);
[Export("selectedTextRange")]
public new IntPtr SelectedTextRange
{
get { return IntPtr_objc_msgSendSuper(SuperHandle, Selector.GetHandle("selectedTextRange")); }
set => void_objc_msgSendSuper(SuperHandle, Selector.GetHandle("setSelectedTextRange:"), value);
}
```
to work on the dynamic registrar since it already work with the static one.
This allows the simulators (which defaults to dynamic) to share the same code which is useful for …
=> [runtime] Allow `IntPtr` for native objects in the dynamic registrar. Fixes #15708

msbuild/Xamarin.MacDev.Tasks/Tasks/Archive.cs, msbuild/Xamarin.iOS.Tasks.Windows/Zip.cs
- Fix AppExtensionReferences ItemSpec in Archive:
when the build is a remote build, we need to fix the ItemSpec of the AppExtensionReferences items so it uses the build server path correctly
- Shorten temp directory for remote zip extractions to avoid long path potential conflicts
Fixes Feedbak Ticket issue: https://developercommunity.visualstudio.com/t/Xamarin-iOS-project-wont-archive-anymor/1587820
=> Fixed remote archiving with iOS app extensions

msbuild/Makefile
This is because we use the iOS assemblies for all other platforms except for
macOS.
=> [msbuild] Build for iOS if any platform except macOS is enabled.

DOWNLOADS.md, Make.config
Also update the list of packages.
=> Bump api references to latest 6.0.4xx / d17-3 builds.

tools/devops/automation/templates/build/build-pkgs.yml, tools/devops/automation/templates/tests/run-tests.yml
Make the binlog artifact name unique across build attempts, so that uploading the binlog archive doesn't fail in subsequent build attempts:
> ##[error]Artifact all-binlogs-test-simulator_cecil-6594281 already exists for build 6594281.
=> [devops] Make the binlog artifact name unique.

dotnet/targets/Xamarin.Shared.Sdk.Publish.targets, msbuild/Xamarin.Shared/Xamarin.Shared.props, msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.props
Don't blindly set the BuildIpa and CreatePackage values, but instead only set
them (when publishing) if they're not already set.
This makes it possible to publish and not create a package.
Fixes https://github.com/xamarin/xamarin-macios/issues/15696.
=> [dotnet] Honor existing values for BuildIpa and CreatePackage. Fixes #15696.

tests/monotouch-test/SceneKit/SCNMatrixTest.cs
This seems to happen on macOS 10.15 only for some reason.
=> [tests] Adjust MonoTouchFixtures.SceneKit.Invert to cope with tiny expected differences.

tests/common/mac/ProjectTestHelpers.cs, tests/mmptest/src/PackageReferenceTests.cs
NuGet seems to struggle with the network on the bots for this particular test,
so ignore the test if there are any nuget failures.
Fixes https://github.com/xamarin/maccore/issues/2612.
=> [tests] Ignore any NuGet failures in PackageReferenceTests.SatellitesFromNuget. Fixes #xamarin/maccore@2612.

tests/dotnet/UnitTests/ProjectTest.cs
This reverts commit dd2f4742123adcb83c7a5a8985baa6b9041d782d.
The dotnet/runtime changes that required these changes apparently aren't in RC 1.
=> [release/7.0.1xx-rc1] Revert "[tests] Update expected error message texts."

msbuild/Xamarin.Shared/Xamarin.Shared.props, tests/dotnet/AutoDetectEntitlements/AppDelegate.cs, tests/dotnet/AutoDetectEntitlements/MacCatalyst/AutoDetectEntitlements.csproj, tests/dotnet/AutoDetectEntitlements/MacCatalyst/Entitlements.plist, tests/dotnet/AutoDetectEntitlements/MacCatalyst/Makefile, tests/dotnet/AutoDetectEntitlements/Makefile, tests/dotnet/AutoDetectEntitlements/iOS/AutoDetectEntitlements.csproj, tests/dotnet/AutoDetectEntitlements/iOS/Entitlements.plist, tests/dotnet/AutoDetectEntitlements/iOS/Makefile, tests/dotnet/AutoDetectEntitlements/macOS/AutoDetectEntitlements.csproj, tests/dotnet/AutoDetectEntitlements/macOS/Entitlements.plist, tests/dotnet/AutoDetectEntitlements/macOS/Makefile, tests/dotnet/AutoDetectEntitlements/shared.csproj, tests/dotnet/AutoDetectEntitlements/shared.mk, tests/dotnet/AutoDetectEntitlements/tvOS/AutoDetectEntitlements.csproj, tests/dotnet/AutoDetectEntitlements/tvOS/Entitlements.plist, tests/dotnet/AutoDetectEntitlements/tvOS/Makefile, tests/dotnet/UnitTests/ProjectTest.cs, tests/msbuild/Xamarin.MacDev.Tests/DotnetTest.cs, tests/msbuild/Xamarin.MacDev.Tests/ProjectsTests/ProjectTest.cs
Also provide a way out by setting EnableDefaultCodesignEntitlements=false.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1595888.
=> [msbuild] Automatically detect any Entitlements.plist files in the root project in .NET.

msbuild/Xamarin.MacDev.Tasks.Core/Tasks/FindAotCompilerTaskBase.cs
Compute the .NET version to use when generating the project file to compute
the AOT compiler.
Also include a way to always force the computation, even on macOS (this eases
testing).
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1597624.
=> [msbuild] Fix the FindAotCompiler task for .NET 7.

runtime/runtime.m
It's fairly frequent (due to various types of coding errors) to have the
call to '[self release]' in xamarin_release_managed_ref crash. These
crashes are typically very hard to diagnose, because it can be hard to
figure out which object caused the crash. So now we store the native
object in a static variable, so that it can be read using lldb from a core
dump.
Ref: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1481312.
=> [runtime] Add some debugging aid to xamarin_release_managed_ref.

runtime/bindings.h, runtime/bindings.m, src/UIKit/UIApplication.cs
Wrap the call to UIApplicationMain in a @try/@catch handler, and convert any
Objective-C exceptions to a managed exception.
This way the managed Main method (which calls UIApplication.Main) will be able
to catch any Objective-C exceptions.
=> [UIKit] Wrap the call to UIApplicationMain in a @try/@catch handler.

dotnet/Workloads/Microsoft.NET.Sdk.MacCatalyst/WorkloadManifest.targets, dotnet/Workloads/Microsoft.NET.Sdk.iOS/WorkloadManifest.targets, dotnet/Workloads/Microsoft.NET.Sdk.macOS/WorkloadManifest.targets, dotnet/Workloads/Microsoft.NET.Sdk.tvOS/WorkloadManifest.targets, dotnet/Workloads/vs-workload.template.props, dotnet/targets/WorkloadManifest.MacCatalyst.template.json, dotnet/targets/WorkloadManifest.iOS.template.json, dotnet/targets/WorkloadManifest.macOS.template.json, dotnet/targets/WorkloadManifest.tvOS.template.json, tools/devops/automation/templates/release/vs-insertion-prep.yml
Context: https://github.com/xamarin/yaml-templates/pull/180
Context: https://github.com/xamarin/yaml-templates/pull/195
Context: https://github.com/xamarin/yaml-templates/pull/199
Context: https://github.com/xamarin/xamarin-macios/pull/15761
Updates the build to use the latest MSI generation template. The v3
template uses the latest changes from arcade which include a large
refactoring, support for multi-targeting, and support for workload pack
group MSIs.
The build will now produce two different VS Drop artifacts.  The MSI and
VSMAN files generated for SDK packs have been split out into a new
`vsdrop-multitarget-signed` artifact, allowing us to include multiple
versions of the SDK packs in VS.
All of the SDK packs have been renamed to include a `.net6` suffix to
match the pack aliases …
=> [ci] Add support to net6.0 for multi-targeting in VS

Make.config
We're pretty much always using a preview version of .NET, so this gets old
fast.
=> [dotnet] Disable warning about using a preview version of .NET.

src/CoreMidi/MidiServices.cs
Ref: https://github.com/xamarin/xamarin-macios/issues/10470.
=> [.NET/CoreMidi] Use [UnmanagedCallersOnly] instead of [MonoPInvokeCallback] Partial Fix for #10470

tools/common/Target.cs
Ref: https://github.com/dotnet/runtime/issues/74628.
=> [tools] Don't call mono_marshal_ilgen_init in .NET.

dotnet/Workloads/Microsoft.NET.Sdk.MacCatalyst/WorkloadManifest.targets, dotnet/Workloads/Microsoft.NET.Sdk.iOS/WorkloadManifest.targets, dotnet/Workloads/Microsoft.NET.Sdk.macOS/WorkloadManifest.targets, dotnet/Workloads/Microsoft.NET.Sdk.tvOS/WorkloadManifest.targets, dotnet/Workloads/vs-workload.template.props, dotnet/targets/WorkloadManifest.MacCatalyst.template.json, dotnet/targets/WorkloadManifest.iOS.template.json, dotnet/targets/WorkloadManifest.macOS.template.json, dotnet/targets/WorkloadManifest.tvOS.template.json, tools/devops/automation/templates/release/vs-insertion-prep.yml
Context: https://github.com/xamarin/yaml-templates/pull/180
Context: https://github.com/xamarin/yaml-templates/pull/195
Context: https://github.com/xamarin/yaml-templates/pull/199
Context: https://github.com/xamarin/xamarin-macios/pull/15761
Updates the build to use the latest MSI generation template. The v3
template uses the latest changes from arcade which include a large
refactoring, support for multi-targeting, and support for workload pack
group MSIs.
The build will now produce two different VS Drop artifacts.  The MSI and
VSMAN files generated for SDK packs have been split out into a new
`vsdrop-multitarget-signed` artifact, allowing us to include multiple
versions of the SDK packs in VS.
All of the SDK packs have been renamed to include a `.net6` suffix to
match the pack aliases …
=> [main] [ci] Add support to main for multi-targeting in VS

dotnet/Workloads/vs-workload.template.props, tools/devops/automation/templates/release/vs-insertion-prep.yml
Context: https://github.com/xamarin/yaml-templates/pull/180
Context: https://github.com/xamarin/yaml-templates/pull/195
Context: https://github.com/xamarin/yaml-templates/pull/199
Context: https://github.com/xamarin/xamarin-macios/pull/15761
Updates the build to use the latest MSI generation template. The v3
template uses the latest changes from arcade which include a large
refactoring, support for multi-targeting, and support for workload pack
group MSIs.
The build will now produce two different VS Drop artifacts.  The MSI and
VSMAN files generated for SDK packs have been split out into a new
`vsdrop-multitarget-signed` artifact, allowing us to include multiple
versions of the SDK packs in VS.
=>  [ci] Add support to net7.0 for multi-targeting in VS

tests/common/shared-dotnet.mk
Allow setting CONFIG to specify the Configuration to build when building .NET
test apps from the command line.
=> [tests] Allow setting CONFIG to specify the Configuration to build.

dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets
Besides excluding the API definition and core source files from the compilation list, we also need to re-add them as 'None' items so they're still shown in the IDE
Fix related to: https://github.com/xamarin/xamarin-macios/issues/15690
=> Add 'None' build action to ObjC binding items

Make.config, NuGet.config, builds/Makefile, builds/package-download/download-packages.proj, dotnet/targets/Xamarin.Shared.Sdk.targets, eng/Version.Details.xml, eng/Versions.props, tools/common/Target.cs
Stop relying on dotnet/installer to provide dotnet/runtime bumps.
Ref: https://github.com/xamarin/xamarin-android/pull/7319
=> Bump to dotnet/runtime/release/7.0-rc1@06aceb70.

dotnet/generate-workloadmanifest-json.csharp
Fixes a string replacement related typo in the generated pack name for
`Microsoft.@PLATFORM@.Windows.Sdk.Aliased.net7`.
=> [workloads] Fix manifest.json platform replacement

dotnet/targets/WorkloadManifest.iOS.template.json
Commit 246aa834 missed a manifest pack entry when renaming packs to
include a `.net6` suffix, producing an invalid manifest and causing MSI
conversion to fail.  Fix this by making sure to use  the `.net6` suffix
everywhere.
Failing build context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6627063&view=logs&j=b4ea4e02-2fcb-5a4a-1d1d-96cc58456a90&t=1ef5c69d-aeda-5369-a23d-e57771ac0882&l=119
=> [workloads] Fix iOS.Windows.Sdk.Aliased.net6 pack name

tools/devops/automation/templates/sign-and-notarized/sign-and-notarized.yml
Make sure bash doesn't ignore any errors during signing. This makes it easier
to diagnose signing failures, because they don't show up in weird ways later.
=> [devops] Make sure no errors are ignored during signing.

dotnet/targets/Xamarin.Shared.Sdk.props, tests/common/shared-dotnet.csproj, tests/linker/ios/link all/dotnet/shared.csproj
ARM64-based macOS machines are becoming more and more common, and as such it
makes sense to include ARM64 builds in the app bundle when building for
release.
Universal builds are much slower than single-architecture builds, which is why
we don't make debug builds universal.
Fixes https://github.com/xamarin/xamarin-macios/issues/15620.
=> [dotnet] Make relase builds for desktop universal by default. Fixes #15620.

msbuild/Xamarin.Localization.MSBuild/Xamarin.Localization.MSBuild.csproj, msbuild/Xamarin.MacDev.Tasks/Xamarin.MacDev.Tasks.csproj
Fixes:
CSC : warning CS2002: Source file 'xamarin-macios/msbuild/Xamarin.Localization.MSBuild/MSBStrings.Designer.cs' specified multiple times [xamarin-macios/msbuild/Xamarin.Localization.MSBuild/Xamarin.Localization.MSBuild.csproj]
CSC : warning CS2002: Source file 'xamarin-macios/tools/mtouch/Errors.Designer.cs' specified multiple times [xamarin-macios/msbuild/Xamarin.MacDev.Tasks/Xamarin.MacDev.Tasks.csproj]
=> [msbuild] Fix a few duplicate compile items warnings.

msbuild/Messaging/Xamarin.Messaging.Build/Xamarin.Messaging.Build.csproj, msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Tasks.csproj, msbuild/Xamarin.MacDev.Tasks/Xamarin.MacDev.Tasks.csproj, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Tasks.Windows.csproj, msbuild/Xamarin.iOS.Tasks/Xamarin.iOS.Tasks.csproj
Fixes these NuGet warnings:
xamarin-macios/msbuild/Xamarin.MacDev.Tasks/Xamarin.MacDev.Tasks.csproj : warning NU1603: Xamarin.Messaging.Build.Common 1.6.24 depends on Merq (>= 1.1.0) but Merq 1.1.0 was not found. An approximate best match of Merq 1.1.4 was resolved.
xamarin-macios/msbuild/Xamarin.MacDev.Tasks/Xamarin.MacDev.Tasks.csproj : warning NU1603: Xamarin.Messaging.Core 1.6.24 depends on Merq (>= 1.1.0) but Merq 1.1.0 was not found. An approximate best match of Merq 1.1.4 was resolved.
xamarin-macios/msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Tasks.Windows.csproj : warning NU1603: Xamarin.iOS.HotRestart.Client 1.0.93 depends on Merq (>= 1.1.1) but Merq 1.1.1 was not found. An approximate best match of Merq 1.1.4 was resolved. …
=> [msbuild] Ignore NU1603 for XVS package references.

tools/devops/automation/templates/sign-and-notarized/sign-and-notarized.yml
There's no builder.keychain on the bots that submit signing requests.
=> [devops] Stop doing things that don't work.

runtime/delegates.t4, src/ObjCRuntime/Runtime.cs, tests/api-shared/ObjCRuntime/RegistrarTest.cs, tools/common/StaticRegistrar.cs
This avoids one case where we we embed metadata tokens to a different assembly
in the generated static registrar code.
This is required for supporting per-assembly static registration
(https://github.com/xamarin/xamarin-macios/issues/12067).
=> [runtime] Use a custom native -> managed trampoline for calling NSObject.InvokeConformsToProtocol from the generated static registrar code.

src/UIKit/UIGestureRecognizer.cs
Simplifies code and makes bug easier to fix.
=> [UIkit] Add generic callbacks for UIGestureRecognizer

src/ObjCRuntime/Runtime.cs
A managed string can contain embedded nulls, while a native UTF8 string won't,
which means that we can't depend on finding a different character between the
two strings to determine whether we've reached the end of the native UTF8
string or not.
=> [Runtime] Fix comparing a pointer to a UTF8 string with a managed string with embedded nulls.

msbuild/Messaging/Xamarin.Messaging.Build/Xamarin.Messaging.Build.csproj, msbuild/Xamarin.iOS.Tasks/Xamarin.iOS.Tasks.csproj
Fixes:
/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2218,5): warning MSB3277: Found conflicts between different versions of "System.Reflection.Metadata" that could not be resolved. [xamarin-macios/msbuild/Xamarin.iOS.Tasks/Xamarin.iOS.Tasks.csproj]
/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2218,5): warning MSB3277: There was a conflict between "System.Reflection.Metadata, Version=1.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Reflection.Metadata, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". [xamarin-macios/msbuild/Xamarin.iOS.Tasks/Xamarin.iOS.Tasks.csproj] …
=> [msbuild] Ignore MSB3246 in a few places.

Make.config, NuGet.config, builds/Makefile, builds/package-download/download-packages.proj, dotnet/targets/Xamarin.Shared.Sdk.targets, eng/Version.Details.xml, eng/Versions.props, tools/devops/automation/scripts/bash/install-workloads.sh, tools/devops/automation/templates/tests/run-tests.yml
Stop relying on dotnet/installer to provide dotnet/runtime bumps.
Ref: https://github.com/xamarin/xamarin-android/pull/7319
=> Bump to dotnet/runtime/release/7.0@608da95f.

dotnet/Makefile
Hopefully fixes a random build error due to parallel make:
cp: ../_build/Microsoft.macOS.Sdk//targets/Microsoft.macOS.Sdk.Versions.props: No such file or directory
make: *** [_pkg/Microsoft.macOS.Sdk.12.3.386-ci.pr.gh15868.pkg] Error 1
make: *** Waiting for unfinished jobs....
=> [dotnet] Fix a few typos in variable names.

tools/devops/automation/scripts/bash/install-workloads.sh, tools/devops/automation/templates/tests/run-tests.yml
This makes it easier to both read & write bash code (syntax highlighting in
the script file, shellscript to validate, etc.), as well as testing out the
script locally.
=> [devops] Move bash script from yaml to it's own bash file.

src/CoreServices/LaunchServices.cs
Because LaunchServices is only included as a manual binding inside CoreServices, it does not seem that we have everything bound inside the LaunchServices Xcode headers.
Beta 1 and 2 diff files preserved here: https://gist.github.com/tj-devel709/49de4b471559eb9504b4b67b0db2b389
Beta 1 has changes introducing MacCatalyst in 2 already existing classes that are not bound by us. Beta 2 has a new enum value that this PR includes.
=> [LaunchServices] Updates for Xcode14 Beta 4

msbuild/Xamarin.Shared/Xamarin.Shared.targets
_AppBundlePath is relative by default, but if AppBundleDir is set to an
absolute path (or the root path used to compute AppBundleDir is an absolute
path), then we must ensure _AppBundlePath is still a relative path, because
our code depends on this.
Note that there are no tests for this, because:
* The problem is that our code concatenates a path + _AppBundlePath.
* This works fine on macOS, because it still looks like a valid path.
* It does not work fine on Windows, because the resulting path ends up with a
drive letter in the middle.
* We currently don't have any tests on Windows.
Fixes https://github.com/xamarin/xamarin-macios/issues/15130.
=> [msbuild] Make sure '_AppBundlePath' is always relative. Fixes #15130.

dotnet/targets/Xamarin.Shared.Sdk.targets, tests/dotnet/BundleStructure/shared.csproj, tests/dotnet/UnitTests/BundleStructureTest.cs, tests/test-libraries/frameworks/Makefile
Since executables in frameworks usually don't have dots, `%(Filename)` will be
the entire filename, because `%(Extension)` is empty. However, if the
executable happens to have a dot, then we need to include the extension:
`%(Filename)%(Extension)`.
Fixes https://github.com/xamarin/xamarin-macios/issues/15727.
=> [dotnet] Fix issue with frameworks with dots. Fixes #15727.

msbuild/Xamarin.Shared/Xamarin.Shared.targets, tests/dotnet/UnitTests/ProjectTest.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/15014.
=> [msbuild] Compute _AppContainerDir from AppBundleDir if AppBundleDir is set by the developer. Fixes #15014.

src/ObjCRuntime/Runtime.CoreCLR.cs, tests/monotouch-test/ObjCRuntime/Messaging.cs, tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
CoreCLR complains that enum values aren't blittable when passed to
Marshal.StructureToPtr, so unwrap enum values first.
Fixes https://github.com/xamarin/xamarin-macios/issues/15744.
=> [CoreCLR] Handle ref/out enum values as parameters. Fixes #15744.

msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
We use illink.dll from the executing .NET version: if we're building with .NET
7, then we're using illink from .NET 7. This means we can't hard-code 'net6.0'
when computing the path to illink.dll for remote builds.
Backport of #15876.
Fixes https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/1611403.
=> [release/6.0.4xx][msbuild] Take the .NET version into account when computing the illink.dll location.

src/CoreFoundation/CFRunLoop.cs
=> [.NET/CoreFoundation] Use [UnmanagedCallersOnly] instead of [MonoPInvokeCallback] Partial Fix for #10470

tools/devops/automation/scripts/TestResults.psm1
* Special characters in powershell are rather, hrm, _uncommon_, in that
they're prefixed with a backtick instead of backslash. Fix code accordingly.
* Use 'Write-Debug' instead of 'Write-Host' in a few places.
* Simplified/improved a few debug statements to make them clearer/less redundant.
* Added tabs in a few places to make debug statements indent properly.
* Fixed a typo.
=> [devops] Improve debug statements.

tools/devops/automation/scripts/TestResults.psm1
Also simplify the code a bit to reduce duplicated code.
=> [devops] Fix double closing details tag when creating test results.

msbuild/Messaging/Xamarin.Messaging.Build/Xamarin.Messaging.Build.csproj, msbuild/Xamarin.Localization.MSBuild/Xamarin.Localization.MSBuild.csproj, msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Tasks.csproj, msbuild/Xamarin.MacDev.Tasks/Xamarin.MacDev.Tasks.csproj, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Tasks.Windows.csproj, msbuild/Xamarin.iOS.Tasks/Xamarin.iOS.Tasks.csproj
/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(1733,5): warning : ProjectReference 'xamarin-macios/msbuild/Messaging/Xamarin.Messaging.Build/Xamarin.Messaging.Build.csproj' was resolved using '.NETFramework,Version=v4.7.2' instead of the project target framework '.NETStandard,Version=v2.0'. This project may not be fully compatible with your project. [xamarin-macios/msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Tasks.Windows.csproj]
=> [msbuild] Use 'netstandard2.0' as the target framework in every project.

dotnet/targets/Xamarin.Shared.Sdk.targets, msbuild/Xamarin.MacDev.Tasks/Tasks/FindAotCompilerTaskBase.cs
This makes debugging issues much easier.
=> [msbuild] Add support for keeping temporary output when looking for AOT compilers.

msbuild/Xamarin.MacDev.Tasks/Tasks/CompileEntitlementsTaskBase.cs
Also remove the 'MergeProfileEntitlements' property, since its value is always
'true' and thus the property is redundant.
=> [msbuild] Enable nullability in the CompileEntitlements task.

tools/devops/Makefile, tools/devops/device-tests-provisioning.csx.in, tools/devops/mac-tests-provisioning.csx.in
Only install the XI and/or XM package if the corresponding part of the build is enabled.
Also don't install either if the legacy Xamarin build is disabled.
=> [devops] Only install XI/XM package if corresponding build is enabled.

tools/devops/automation/scripts/bash/create-legacy-ios-mac-sdk-symlinks.sh, tools/devops/automation/templates/tests/build.yml
* Move the bash in the yml file to a separate script file to ease reading, writing & debugging.
* Don't install any symlinks if legacy Xamarin isn't enabled.
* Only install the iOS / macOS symlink if the corresponding build is enabled.
=> [devops] Don't create legacy iOS/Mac symlinks unless legacy build is enabled.

msbuild/Directory.Build.props
Brings an SSH fix for an issue when the keys are missing: https://github.com/xamarin/Xamarin.Messaging/pull/461
=> Updated Xamarin.Messaging to 1.7.14

msbuild/Xamarin.MacDev.Tasks/Tasks/DetectSigningIdentityTaskBase.cs, msbuild/Xamarin.Shared/Xamarin.Shared.props, msbuild/Xamarin.Shared/Xamarin.Shared.targets, tests/common/DotNet.cs, tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/DetectSigningIdentityTaskTests.cs
This is the behavior in legacy Xamarin (for mobile projects): if a project
contains a CodesignEntitlements=Entitlements.plist property, we require a
provisioning profile (and failing the build if none is found).
In .NET, the expected behavior is that if a file is in the project directory,
it should be detected automatically and handled accordingly. We didn't do this
for the initial release of .NET, but we implemented it later
(https://github.com/xamarin/xamarin-macios/pull/15729).
However, this turned out to be complicated, because many templates provide an
Entitlements.plist file, and now suddenly just the presence of such a file
would require a provisioning profile, which also means setting up the whole
rigmarole of Apple's certificates and provisioning profiles (and even
potentially …
=> [msbuild] Only require a provisioning profile if we have non-empty entitlements.

tests/monotouch-test/Security/RecordTest.cs
Probably regressed after 61e8ce443f2e9472d25c8670aead43bee18fe934.
Fixes https://github.com/xamarin/maccore/issues/2618.
=> [tests] Adjust test for tvOS and watchOS.

msbuild/Xamarin.Localization.MSBuild/MSBStrings.Designer.cs, msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.cs.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.de.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.es.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.fr.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.it.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ja.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ko.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pl.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pt-BR.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ru.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.tr.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hans.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hant.resx, msbuild/Xamarin.MacDev.Tasks/Tasks/CreateBindingResourcePackageBase.cs, tests/dotnet/UnitTests/TemplateTest.cs, tests/mmptest/src/BindingProjectNoEmbeddingTests.cs, tests/msbuild/Xamarin.MacDev.Tests/ProjectsTests/NativeReferencesNoEmbedding.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/15489.
=> [msbuild] Remove MS7068 so allow creating binding projects without native libraries. Fixes #15489.

msbuild/Xamarin.Localization.MSBuild/MSBStrings.Designer.cs, msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx, msbuild/Xamarin.MacDev.Tasks/Tasks/CompileEntitlementsTaskBase.cs, msbuild/Xamarin.Shared/Xamarin.Shared.targets, tests/dotnet/Entitlements/AppDelegate.cs, tests/dotnet/Entitlements/MacCatalyst/Entitlements.csproj, tests/dotnet/Entitlements/MacCatalyst/Entitlements.plist, tests/dotnet/Entitlements/MacCatalyst/Makefile, tests/dotnet/Entitlements/Makefile, tests/dotnet/Entitlements/iOS/Entitlements.csproj, tests/dotnet/Entitlements/iOS/Entitlements.plist, tests/dotnet/Entitlements/iOS/Makefile, tests/dotnet/Entitlements/macOS/Entitlements.csproj, tests/dotnet/Entitlements/macOS/Entitlements.plist, tests/dotnet/Entitlements/macOS/Makefile, tests/dotnet/Entitlements/shared.csproj, tests/dotnet/Entitlements/shared.mk, tests/dotnet/Entitlements/tvOS/Entitlements.csproj, tests/dotnet/Entitlements/tvOS/Entitlements.plist, tests/dotnet/Entitlements/tvOS/Makefile, tests/dotnet/UnitTests/ProjectTest.cs, tests/dotnet/UnitTests/TestBaseClass.cs, tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/CompileEntitlementsTaskTests.cs
* Add support for specifying custom entitlements with an MSBuild item group.
* Use this new support to automatically add the 'com.apple.security.cs.allow-jit'
entitlement to .NET desktop apps when building for release, since all apps that
go through notarization will need it in order to be able to use the JIT.
It's possible to override the default behavior by adding something like this to the project file:
<ItemGroup>
<CustomEntitlements Include="com.apple.security.cs.allow-jit" Type="Remove" />
</ItemGroup>
Fixes https://github.com/xamarin/xamarin-macios/issues/15745.
=> [msbuild] Automatically add the 'com.apple.security.cs.allow-jit' entitlement for desktop release builds. Fixes #15745.

tools/devops/automation/templates/common/upload-vsts-tests.yml, tools/devops/automation/templates/tests/run-tests.yml
Don't try to publish test results unless there are any tests results.
Fixes this [horribly/amusingly incorrect error][1] in the publish task:
##[error]Error: Failed find: ENOENT: no such file or directory, lstat '/System/Library/Frameworks/iTunesLibrary.framework/Versions/Versions'
##[section]Finishing: Publish NUnit Device Test Results
Also stop failing the task on failing tests, because we already have another task that fail if there are failing tests (the task that runs the tests).
[1]: https://github.com/microsoft/azure-pipelines-tasks/issues/16786
=> [devops] Don't try to publish test results unless there are any tests results.

tools/devops/automation/scripts/bash/collect-and-upload-crash-reports.sh
Otherwise this happens if the directory is empty:
+ test -d /Users/runner/Library/Logs/DiagnosticReports
+ zip -9rj /Users/runner/work/1/s/crash-reports.zip /Users/runner/Library/Logs/DiagnosticReports
zip error: Nothing to do! (try: zip -9rj /Users/runner/work/1/s/crash-reports.zip . -i /Users/runner/Library/Logs/DiagnosticReports)
=> [devops] Improve check for crash reports before collecting them.

tools/devops/automation/templates/mac/build.yml
The 'Expand tests.' step sometimes fails with:
> ##[error]Bash exited with code '1'.
Which is very unhelpful. Make bash more verbose to see if we can figure out what's going wrong.
=> [devops] Add some debug code to figure out a random error.

tests/monotouch-test/Security/RecordTest.cs
Probably regressed after 61e8ce443f2e9472d25c8670aead43bee18fe934.
Fixes https://github.com/xamarin/maccore/issues/2618.
Backport of #15939
=> [release/6.0.4xx-xcode14] [tests] Adjust test for tvOS and watchOS.

tests/Makefile
This was used in the old Xamarin days.
=> [tests] We do not need qa-dependencies.zip anymore.

tools/Makefile
Because we use mtouch and mmp to build the partial static registrar code for .NET.
Eventually we'll look into generating the partial static registrar some other
way, but that's for another time.
=> [tools] We still need to build mtouch+mmp for .NET.

Makefile
Just do `make show-versions`:
$ make show-versions
Building:
The legacy package(s):
Xamarin.iOS 15.13.0.132
Xamarin.Mac 8.13.0.132
The .NET NuGet(s):
Microsoft.iOS 15.4.436-ci.show-versions+sha.405ff7c275
Microsoft.tvOS 15.4.436-ci.show-versions+sha.405ff7c275
Microsoft.MacCatalyst 15.4.436-ci.show-versions+sha.405ff7c275
Microsoft.macOS 12.3.436-ci.show-versions+sha.405ff7c275
=> Make it easy to figure out which versions we're building.

msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
Adds missing css files needed on Maui Blazor apps and avoids copying unnecessary files into the bundle (overdue task since the .NET migration).
Backport of #15979
=> [release/6.0.4xx] [msbuild] Hot Restart fixes

msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
Adds missing css files needed on Maui Blazor apps and avoids copying unnecessary files into the bundle (overdue task since the .NET migration).
Backport of #15979
=> [release/6.0.4xx-xcode14] [msbuild] Hot Restart fixes

msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
Adds missing css files needed on Maui Blazor apps and avoids copying unnecessary files into the bundle (overdue task since the .NET migration).
Backport of #15979
=> [release/7.0.1xx-xcode14-rc2] [msbuild] Hot Restart fixes

msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
Adds missing css files needed on Maui Blazor apps and avoids copying unnecessary files into the bundle (overdue task since the .NET migration).
Backport of #15979
=> [release/7.0.1xx-rc2] [msbuild] Hot Restart fixes

.github/workflows/autoformat.yml, .github/workflows/autoformat2.yml
Implement a GitHub action to automatically format our source code.
This is implemented in two steps:
1. A restricted action is used to check if the code has any formatting issues, and if so, creates a patch to fix the code.
2. Another action is used to commit and push the patch (and add a comment to the PR notifying the submitter about the problems found).
This is because the first action will call 'dotnet format', which might be insecure in that it can execute code from the repository. This is not safe in a context that is allowed to push commits (because there are secrets in the environment) - so anyone could create a PR that would be executed as a part of 'dotnet format' and then look for our secrets and make them public. The restricted action's environment does not have any secrets, …
=> [actions] Add GitHub action to automatically format code.

tests/cecil-tests/EnumTest.cs, tests/cecil-tests/Helper.cs, tests/cecil-tests/MarshalAsTest.cs, tests/cecil-tests/Test.cs, tests/common/Configuration.cs
And not legacy assemblies if the legacy build is disabled.
=> [tests] Update the cecil tests to run on .NET assemblies.

tools/devops/device-tests-provisioning.csx.in
We use mono in a number of places.
=> [devops] We still need Mono even if the legacy Xamarin build is disabled.

src/CoreMedia/CMBufferQueue.cs
'bool' isn't a blittable type, so it can't be used in an
[UnmanagedCallersOnly] method.
FWIW it's a bug in the C# compiler to not complain about this:
https://github.com/dotnet/roslyn/issues/64086.
Fixes this crash in the AOT compiler:
> * Assertion at /Users/runner/work/1/s/src/mono/mono/mini/aot-compiler.c:5142, condition `is_ok (error)' not met, function:add_wrappers, method CoreMedia.CMBufferQueue:GetDataReady (intptr,intptr) with UnmanagedCallersOnlyAttribute has non-blittable parameters or return type assembly:<unknown assembly> type:<unknown type> member:(null)
Also exclude some unused delegates from .NET code.
=> [CoreMedia] Don't use 'bool' in an [UnmanagedCallersOnly] method.

tests/monotouch-test/Security/RecordTest.cs
Probably regressed after 61e8ce443f2e9472d25c8670aead43bee18fe934.
Fixes https://github.com/xamarin/maccore/issues/2618.
Backport of #15939
=> [release/7.0.1xx-xcode14-rc2] [tests] Adjust test for tvOS and watchOS.

tests/monotouch-test/Security/RecordTest.cs
Probably regressed after 61e8ce443f2e9472d25c8670aead43bee18fe934.
Fixes https://github.com/xamarin/maccore/issues/2618.
Backport of #15939
=> [release/7.0.1xx-rc2] [tests] Adjust test for tvOS and watchOS.

tools/devops/Makefile, tools/devops/automation/scripts/bash/configure-platforms.sh, tools/devops/automation/templates/common/configure.yml, tools/devops/automation/templates/sign-and-notarized/funnel.yml, tools/devops/automation/templates/sign-and-notarized/prepare-pkg-stage.yml
Change package signing so that we only try to sign packages for platforms that aren't disabled.
This makes the 'Prepare packages' job green in Azure Devops.
The 'Prepare Release' job still fails in the 'Convert NuGet to MSI' step (for
the branch I've been working on), because the package names are too long for
MSIs. This should be resolved for a proper release branch (i.e. when this PR
is merged), because package names are much shorter in a release branch.
Example results: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6711641&view=results
Backport of #16028.
Backport of #16039
=> [release/7.0.1xx-xcode14-rc2] Make package signing work with some platforms disabled.

tools/apidiff/Makefile
Don't try to compare legacy vs .NET for platforms that aren't included in the build, because this happens:
> make: *** No rule to make target 'output/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html', needed by 'output/api-diff.html'.  Stop.
We do this by not hardcoding the list of legacy platforms, but instead starting with DOTNET_PLATFORMS variable (which won't contain platforms that aren't included in the build), and then removing any .NET-only platforms (i.e. Mac Catalyst).
Also fix the `update-refs` target to not try to update refs for platforms that aren't enabled.
Fixes https://github.com/xamarin/xamarin-macios/issues/16011.
=> [release/6.0.4xx-xcode14] [apidiff] Don't compare to legacy platforms that aren't included in the build. Fixes #16011.

tools/apidiff/Makefile
Don't try to compare legacy vs .NET for platforms that aren't included in the build, because this happens:
> make: *** No rule to make target 'output/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html', needed by 'output/api-diff.html'.  Stop.
We do this by not hardcoding the list of legacy platforms, but instead starting with DOTNET_PLATFORMS variable (which won't contain platforms that aren't included in the build), and then removing any .NET-only platforms (i.e. Mac Catalyst).
Also fix the `update-refs` target to not try to update refs for platforms that aren't enabled.
Fixes https://github.com/xamarin/xamarin-macios/issues/16011.
Backport of #16029
=> [release/7.0.1xx-xcode14-rc2] [release/6.0.4xx-xcode14] [apidiff] Don't compare to legacy platforms that aren't included in the build. Fixes #16011.

tools/apidiff/Makefile
Don't try to compare legacy vs .NET for platforms that aren't included in the build, because this happens:
> make: *** No rule to make target 'output/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html', needed by 'output/api-diff.html'.  Stop.
We do this by not hardcoding the list of legacy platforms, but instead starting with DOTNET_PLATFORMS variable (which won't contain platforms that aren't included in the build), and then removing any .NET-only platforms (i.e. Mac Catalyst).
Also fix the `update-refs` target to not try to update refs for platforms that aren't enabled.
Fixes https://github.com/xamarin/xamarin-macios/issues/16011.
Backport of #16029
=> [net7.0-xcode14] [release/6.0.4xx-xcode14] [apidiff] Don't compare to legacy platforms that aren't included in the build. Fixes #16011.

tools/apidiff/Makefile
Don't try to compare legacy vs .NET for platforms that aren't included in the build, because this happens:
> make: *** No rule to make target 'output/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html', needed by 'output/api-diff.html'.  Stop.
We do this by not hardcoding the list of legacy platforms, but instead starting with DOTNET_PLATFORMS variable (which won't contain platforms that aren't included in the build), and then removing any .NET-only platforms (i.e. Mac Catalyst).
Also fix the `update-refs` target to not try to update refs for platforms that aren't enabled.
Fixes https://github.com/xamarin/xamarin-macios/issues/16011.
Backport of #16029
=> [main] [release/6.0.4xx-xcode14] [apidiff] Don't compare to legacy platforms that aren't included in the build. Fixes #16011.

tools/devops/Makefile, tools/devops/automation/scripts/bash/configure-platforms.sh, tools/devops/automation/templates/common/configure.yml, tools/devops/automation/templates/sign-and-notarized/funnel.yml, tools/devops/automation/templates/sign-and-notarized/prepare-pkg-stage.yml
Change package signing so that we only try to sign packages for platforms that aren't disabled.
This makes the 'Prepare packages' job green in Azure Devops.
The 'Prepare Release' job still fails in the 'Convert NuGet to MSI' step (for
the branch I've been working on), because the package names are too long for
MSIs. This should be resolved for a proper release branch (i.e. when this PR
is merged), because package names are much shorter in a release branch.
Example results: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6711641&view=results
Backport of #16028.
=> Make package signing work with some platforms disabled.

.github/workflows/autoformat2.yml
Get the head repository using the correct syntax when trying to publish
autoformatted changes. This action is a 'workflow_run' action, and not a
'pull_request' action, and as such we must look in the 'workflow_run' object
for the data we need.
This will hopefully make the action able to publish results back to a fork.
=> [actions] Get the head repository using the correct syntax.

tests/common/BundlerTool.cs, tests/mtouch/MTouch.cs, tools/common/Application.cs, tools/mtouch/Application.mtouch.cs, tools/mtouch/BuildTasks.mtouch.cs, tools/mtouch/Errors.designer.cs, tools/mtouch/Errors.resx, tools/mtouch/Target.mtouch.cs, tools/mtouch/mtouch.cs
Apple has deprecated bitcode, and will apparently reject app submissions
containing bitcode starting with Xcode 14. So automatically disable bitcode if
building using Xcode 14+ (and show a warning so that app developers can remove
the 'MtouchEnableBitcode' property from their project files).
Fixes https://github.com/xamarin/xamarin-macios/issues/15210.
Backport of #15804
=> [release/7.0.1xx-xcode14-rc2] [mtouch] Automatically disable bitcode if using Xcode 14+. Fixes #15210.

tests/common/BundlerTool.cs, tests/mtouch/MTouch.cs, tools/common/Application.cs, tools/mtouch/Application.mtouch.cs, tools/mtouch/BuildTasks.mtouch.cs, tools/mtouch/Errors.designer.cs, tools/mtouch/Errors.resx, tools/mtouch/Target.mtouch.cs, tools/mtouch/mtouch.cs
Apple has deprecated bitcode, and will apparently reject app submissions
containing bitcode starting with Xcode 14. So automatically disable bitcode if
building using Xcode 14+ (and show a warning so that app developers can remove
the 'MtouchEnableBitcode' property from their project files).
Fixes https://github.com/xamarin/xamarin-macios/issues/15210.
Backport of #15804
=> [main] [mtouch] Automatically disable bitcode if using Xcode 14+. Fixes #15210.

dotnet/Workloads/vs-workload.template.props
The iOS and tvOS workloads are/will be included in the release/6.0.4xx-xcode14
branch.
=> [6.0.4xx] [dotnet] Don't include iOS and tvOS in vs-workload.props anymore.

msbuild/Messaging/Xamarin.Messaging.Build/Xamarin.Messaging.Build.csproj
The Build Agent is a console app so it can't target netstandard. Changing it back to net472 for now
=> Fixed Build Agent

msbuild/Messaging/Xamarin.Messaging.Build/Xamarin.Messaging.Build.csproj
The Build Agent is a console app so it can't target netstandard. Changing it back to net472 for now
Backport of #16083
=> [release/7.0.1xx-rc2] Fixed Build Agent

msbuild/Messaging/Xamarin.Messaging.Build/Xamarin.Messaging.Build.csproj
The Build Agent is a console app so it can't target netstandard. Changing it back to net472 for now
Backport of #16083
=> [release/7.0.1xx-xcode14-rc2] Fixed Build Agent

msbuild/Messaging/Xamarin.Messaging.Build/Xamarin.Messaging.Build.csproj
The Build Agent is a console app so it can't target netstandard. Changing it back to net472 for now
Backport of #16083
=> [main] Fixed Build Agent

tools/devops/automation/templates/build/build-pkgs.yml, tools/devops/automation/templates/tests/run-tests.yml
Only upload 'macOS' and 'Mac Catalyst' packages to the 'package' artifact in this branch, so that the VS insertion logic won't try to insert the iOS and tvOS workloads, since those will come from a different branch (`release/6.0.4xx-xcode14`).
=> [6.0.4xx] [devops] Only upload 'macOS' and 'Mac Catalyst' packages to the 'package' artifact.

dotnet/Makefile
Attempt to improve consistency in generated workload manifest MSI versions by more closely following the four digit versioning schema used by Android and MAUI.  This change should only affect preview versioned workload manifests, as stable manifest MSIs will now use the three digit NuGet package version as the MSI version.
The previous version passed to the MSI version generation task in arcade contained the commit distance twice, and now the commit distance is only used in the fourth version part.
Before:
Version="15.4.1167.1167"
After:
Version="15.4.0.1167"
Compared to Android/MAUI:
Version="33.0.0.151"
Version="7.0.0.6683"
With these changes the arcade task should weigh the time delta between builds more heavily, which should produce MSI versions that increment more consistently and by …
=> [build] Improve generated manifest MSI versions

dotnet/Makefile
Attempt to improve consistency in generated workload manifest MSI versions by more closely following the four digit versioning schema used by Android and MAUI.  This change should only affect preview versioned workload manifests, as stable manifest MSIs will now use the three digit NuGet package version as the MSI version.
The previous version passed to the MSI version generation task in arcade contained the commit distance twice, and now the commit distance is only used in the fourth version part.
Before:
Version="15.4.1167.1167"
After:
Version="15.4.0.1167"
Compared to Android/MAUI:
Version="33.0.0.151"
Version="7.0.0.6683"
With these changes the arcade task should weigh the time delta between builds more heavily, which should produce MSI versions that increment more consistently and by …
=> [release/7.0.1xx-xcode14-rc2] [build] Improve generated manifest MSI versions

msbuild/Xamarin.MacDev.Tasks/Tasks/ArchiveTaskBase.cs, tests/monotouch-test/Foundation/FileManagerTest.cs, tests/monotouch-test/Foundation/UrlTest.cs, tools/common/Driver.cs, tools/devops/mac-tests-provisioning.csx.in
Context: dotnet/runtime#68610
Context: https://github.com/xamarin/xamarin-android-tools/commit/0be567a9
In Mono and .NET prior to .NET 8, the
[`System.Environment.SpecialFolder`][0]`.Personal` enum value would refer to
`$HOME` on Unix platforms.
This will be changing in .NET 8, such that
`Environment.SpecialFolder.Personal` will instead refer to
`$XDG_DOCUMENTS_DIR` (if set) or `$HOME/Documents`.  This is for "semantic
compatibility" with .NET on Windows.
Replace usage of `Environment.SpecialFolder.Personal` with
`Environment.SpecialFolder.UserProfile`, so that our code continues to work as
expected under .NET 8.
[0]: https://docs.microsoft.com/en-us/dotnet/api/system.environment.specialfolder?view=net-6.0
=> Use Environment.SpecialFolder.UserProfile, not SpecialFolder.Personal.

msbuild/Xamarin.Shared/Xamarin.Shared.targets
Add a public 'CompileImageAssetsDependsOn' property, so that MAUI can inject tasks that
must be completed before we compile image assets:
```xml
<PropertyGroup>
<CompileImageAssetsDependsOn>
$(CompileImageAssetsDependsOn);
ResizetizeCollectItems;
</CompileImageAssetsDependsOn>
</PropertyGroup>
```
Fixes https://github.com/xamarin/xamarin-macios/issues/16065.
=> [msbuild] Add a public 'CompileImageAssetsDependsOn' property. Fixes #16065.

msbuild/Xamarin.Shared/Xamarin.Shared.targets
Add a public 'CompileImageAssetsDependsOn' property, so that MAUI can inject tasks that
must be completed before we compile image assets:
```xml
<PropertyGroup>
<CompileImageAssetsDependsOn>
$(CompileImageAssetsDependsOn);
ResizetizeCollectItems;
</CompileImageAssetsDependsOn>
</PropertyGroup>
```
Fixes https://github.com/xamarin/xamarin-macios/issues/16065.
Backport of #16089
=> [release/7.0.1xx-xcode14-rc2] [msbuild] Add a public 'CompileImageAssetsDependsOn' property. Fixes #16065.

msbuild/Xamarin.Shared/Xamarin.Shared.targets
Add a public 'CompileImageAssetsDependsOn' property, so that MAUI can inject tasks that
must be completed before we compile image assets:
```xml
<PropertyGroup>
<CompileImageAssetsDependsOn>
$(CompileImageAssetsDependsOn);
ResizetizeCollectItems;
</CompileImageAssetsDependsOn>
</PropertyGroup>
```
Fixes https://github.com/xamarin/xamarin-macios/issues/16065.
Backport of #16089
=> [release/7.0.1xx-rc2] [msbuild] Add a public 'CompileImageAssetsDependsOn' property. Fixes #16065.

msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
The .NET 7 linker targets will set _TrimmerDefaultAction instead of
TrimmerDefaultAction, so if TrimmerDefaultAction isn't set (which it will be
for .NET 6), then use _TrimmerDefaultAction (which should be set for .NET 7).
Unfortunately for .NET 8 it seems I've misplaced my crystal ball, so we'll
have to wait a bit to see what happens then.
Ref: https://github.com/xamarin/xamarin-macios/issues/16125.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1621047.
Backport of #16126
=> [main] [6.0.4xx] [msbuild] Use _TrimmerDefaultAction if TrimmerDefaultAction isn't set.

dotnet/Workloads/SignList.targets
=> [ci] Only try to sign nested zips if they exist

msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
The .NET 7 linker targets will set _TrimmerDefaultAction instead of
TrimmerDefaultAction, so if TrimmerDefaultAction isn't set (which it will be
for .NET 6), then use _TrimmerDefaultAction (which should be set for .NET 7).
Unfortunately for .NET 8 it seems I've misplaced my crystal ball, so we'll
have to wait a bit to see what happens then.
Ref: https://github.com/xamarin/xamarin-macios/issues/16125.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1621047.
=> [6.0.4xx] [msbuild] Use _TrimmerDefaultAction if TrimmerDefaultAction isn't set.

msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
The .NET 7 linker targets will set _TrimmerDefaultAction instead of
TrimmerDefaultAction, so if TrimmerDefaultAction isn't set (which it will be
for .NET 6), then use _TrimmerDefaultAction (which should be set for .NET 7).
Unfortunately for .NET 8 it seems I've misplaced my crystal ball, so we'll
have to wait a bit to see what happens then.
Ref: https://github.com/xamarin/xamarin-macios/issues/16125.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1621047.
Backport of #16126
=> [release/6.0.4xx-xcode14] [msbuild] Use _TrimmerDefaultAction if TrimmerDefaultAction isn't set.

dotnet/Workloads/SignList.targets
=> [release/7.0.1xx-rc2] [ci] Only try to sign nested zips if they exist

dotnet/Workloads/SignList.targets
=> [release/7.0.1xx-xcode14-rc2] [ci] Only try to sign nested zips if they exist

dotnet/Workloads/SignList.targets
=> [release/6.0.4xx-xcode14] [ci] Only try to sign nested zips if they exist

dotnet/targets/Xamarin.Shared.Sdk.targets, tests/dotnet/UnitTests/ProjectTest.cs
Fixes this problem when building universal Mac Catalyst apps on Windows:
Target Name=_CollectRidSpecificCodesignItems Project=D:\a\_work\1\s\src\Graphics\samples\GraphicsTester.Skia.Mac\GraphicsTester.Skia.Mac.csproj
ReadItemsFromFile
Assembly = D:\a\_work\1\s\bin\dotnet\packs\Microsoft.MacCatalyst.Sdk\15.4.1173-rc.2\tools\msbuild\iOS\..\iOS\Xamarin.iOS.Tasks.dll
Parameters
File = obj\Release\net7.0-macos\codesignitems-osx-x64.items
Errors
D:\a\_work\1\s\bin\dotnet\packs\Microsoft.macOS.Sdk\12.3.1173-rc.2\targets\Xamarin.Shared.Sdk.targets(1303,3): error MSB4018: The "ReadItemsFromFile" task failed unexpectedly.
System.IO.FileNotFoundException: Could not find file 'D:\a\_work\1\s\src\Graphics\samples\GraphicsTester.Skia.Mac\obj\Release\net7.0-macos\codesignitems-osx-x64.items'.
File name: …
=> [release/7.0.1xx-xcode14-rc2] [dotnet] Don't try to collect RID-specific items to codesign unless we're connected to (or building on) a Mac.

dotnet/targets/Xamarin.Shared.Sdk.targets, tests/dotnet/UnitTests/ProjectTest.cs
Fixes this problem when building universal Mac Catalyst apps on Windows:
Target Name=_CollectRidSpecificCodesignItems Project=D:\a\_work\1\s\src\Graphics\samples\GraphicsTester.Skia.Mac\GraphicsTester.Skia.Mac.csproj
ReadItemsFromFile
Assembly = D:\a\_work\1\s\bin\dotnet\packs\Microsoft.MacCatalyst.Sdk\15.4.1173-rc.2\tools\msbuild\iOS\..\iOS\Xamarin.iOS.Tasks.dll
Parameters
File = obj\Release\net7.0-macos\codesignitems-osx-x64.items
Errors
D:\a\_work\1\s\bin\dotnet\packs\Microsoft.macOS.Sdk\12.3.1173-rc.2\targets\Xamarin.Shared.Sdk.targets(1303,3): error MSB4018: The "ReadItemsFromFile" task failed unexpectedly.
System.IO.FileNotFoundException: Could not find file 'D:\a\_work\1\s\src\Graphics\samples\GraphicsTester.Skia.Mac\obj\Release\net7.0-macos\codesignitems-osx-x64.items'.
File name: …
=> [release/7.0.1xx-rc2] [dotnet] Don't try to collect RID-specific items to codesign unless we're connected to (or building on) a Mac.

dotnet/targets/Xamarin.Shared.Sdk.targets, tests/dotnet/UnitTests/ProjectTest.cs
Fixes this problem when building universal Mac Catalyst apps on Windows:
Target Name=_CollectRidSpecificCodesignItems Project=D:\a\_work\1\s\src\Graphics\samples\GraphicsTester.Skia.Mac\GraphicsTester.Skia.Mac.csproj
ReadItemsFromFile
Assembly = D:\a\_work\1\s\bin\dotnet\packs\Microsoft.MacCatalyst.Sdk\15.4.1173-rc.2\tools\msbuild\iOS\..\iOS\Xamarin.iOS.Tasks.dll
Parameters
File = obj\Release\net7.0-macos\codesignitems-osx-x64.items
Errors
D:\a\_work\1\s\bin\dotnet\packs\Microsoft.macOS.Sdk\12.3.1173-rc.2\targets\Xamarin.Shared.Sdk.targets(1303,3): error MSB4018: The "ReadItemsFromFile" task failed unexpectedly.
System.IO.FileNotFoundException: Could not find file 'D:\a\_work\1\s\src\Graphics\samples\GraphicsTester.Skia.Mac\obj\Release\net7.0-macos\codesignitems-osx-x64.items'.
File name: …
=> [dotnet] Don't try to collect RID-specific items to codesign unless we're connected to (or building on) a Mac.

dotnet/targets/Xamarin.Shared.Sdk.targets, tests/dotnet/UnitTests/ProjectTest.cs
targets/Xamarin.Shared.Sdk.targets(754,3): error MSB4018: The "Xamarin.MacDev.Tasks.ILStrip" task failed unexpectedly.
targets/Xamarin.Shared.Sdk.targets(754,3): error MSB4018: System.ArgumentException: 'Assemblies' is required. (Parameter 'Assemblies')
targets/Xamarin.Shared.Sdk.targets(754,3): error MSB4018:    at ILStrip.Execute()
targets/Xamarin.Shared.Sdk.targets(754,3): error MSB4018:    at ILStripTasks.ILStripBase.Execute() in /Users/rolf/work/maccore/main/xamarin-macios/msbuild/Xamarin.iOS.Tasks/Tasks/ILStripBase.cs:line 18
targets/Xamarin.Shared.Sdk.targets(754,3): error MSB4018:    at Xamarin.MacDev.Tasks.ILStrip.Execute() in /Users/rolf/work/maccore/main/xamarin-macios/msbuild/Xamarin.iOS.Tasks/Tasks/ILStrip.cs:line 16 …
=> [release/7.0.1xx-xcode14-rc2] [dotnet] Don't try to ILStrip assemblies unless we're connected to a Mac.

dotnet/targets/Xamarin.Shared.Sdk.targets, tests/dotnet/UnitTests/ProjectTest.cs
targets/Xamarin.Shared.Sdk.targets(754,3): error MSB4018: The "Xamarin.MacDev.Tasks.ILStrip" task failed unexpectedly.
targets/Xamarin.Shared.Sdk.targets(754,3): error MSB4018: System.ArgumentException: 'Assemblies' is required. (Parameter 'Assemblies')
targets/Xamarin.Shared.Sdk.targets(754,3): error MSB4018:    at ILStrip.Execute()
targets/Xamarin.Shared.Sdk.targets(754,3): error MSB4018:    at ILStripTasks.ILStripBase.Execute() in /Users/rolf/work/maccore/main/xamarin-macios/msbuild/Xamarin.iOS.Tasks/Tasks/ILStripBase.cs:line 18
targets/Xamarin.Shared.Sdk.targets(754,3): error MSB4018:    at Xamarin.MacDev.Tasks.ILStrip.Execute() in /Users/rolf/work/maccore/main/xamarin-macios/msbuild/Xamarin.iOS.Tasks/Tasks/ILStrip.cs:line 16 …
=> [dotnet] Don't try to ILStrip assemblies unless we're connected to a Mac.

dotnet/Workloads/SignList.targets
=> [main] [ci] Only try to sign nested zips if they exist

tools/devops/automation/build-cronjob.yml, tools/devops/automation/build-pipeline.yml, tools/devops/automation/build-pull-request.yml
The 10.15 bots are going away in a few months, and in any case macOS 10.15 is
not supported by Apple anymore, so stop testing on macOS 10.15.
=> [devops] Stop testing on macOS 10.15.

dotnet/targets/Xamarin.Shared.Sdk.targets, tests/dotnet/UnitTests/ProjectTest.cs
targets/Xamarin.Shared.Sdk.targets(754,3): error MSB4018: The "Xamarin.MacDev.Tasks.ILStrip" task failed unexpectedly.
targets/Xamarin.Shared.Sdk.targets(754,3): error MSB4018: System.ArgumentException: 'Assemblies' is required. (Parameter 'Assemblies')
targets/Xamarin.Shared.Sdk.targets(754,3): error MSB4018:    at ILStrip.Execute()
targets/Xamarin.Shared.Sdk.targets(754,3): error MSB4018:    at ILStripTasks.ILStripBase.Execute() in /Users/rolf/work/maccore/main/xamarin-macios/msbuild/Xamarin.iOS.Tasks/Tasks/ILStripBase.cs:line 18
targets/Xamarin.Shared.Sdk.targets(754,3): error MSB4018:    at Xamarin.MacDev.Tasks.ILStrip.Execute() in /Users/rolf/work/maccore/main/xamarin-macios/msbuild/Xamarin.iOS.Tasks/Tasks/ILStrip.cs:line 16 …
=> [release/7.0.1xx-rc2] [dotnet] Don't try to ILStrip assemblies unless we're connected to a Mac.

msbuild/Xamarin.MacDev.Tasks/Tasks/DetectSigningIdentityTaskBase.cs, tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/DetectSigningIdentityTaskTests.cs
This way XVS will copy the corresponding file to the mac during a build.
Target Name=_DetectSigningIdentity Project=C:\Users\admin\source\repos\iOSApp4\iOSApp4\iOSApp4.csproj
DetectSigningIdentity
Assembly = C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.0.515\tools\msbuild\iOS\..\iOS\Xamarin.iOS.Tasks.dll
Parameters
AppBundleName = iOSApp4
BundleIdentifier = com.companyname.iOSApp4
CodesignEntitlements = Entitlements.plist
RequireCodeSigning = False
SdkIsSimulator = True
SdkPlatform = iPhoneSimulator
SessionId = ...
TargetFrameworkMoniker = .NETCoreApp,Version=v6.0,Profile=ios
DetectSigningIdentity: 2022-09-28T04:17:13.3947732-07:00 - Started
DetectSigningIdentity: 2022-09-28T04:17:13.3947732-07:00 - Initializing
[xma][info]: Trying to get a Build Connection for …
=> [release/6.0.4xx-xcode14] [msbuild] Make DetectSigningIdentity.CodesignEntitlements an ITaskItem property.

msbuild/Xamarin.MacDev.Tasks/Tasks/DetectSigningIdentityTaskBase.cs, tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/DetectSigningIdentityTaskTests.cs
This way XVS will copy the corresponding file to the mac during a build.
Target Name=_DetectSigningIdentity Project=C:\Users\admin\source\repos\iOSApp4\iOSApp4\iOSApp4.csproj
DetectSigningIdentity
Assembly = C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.0.515\tools\msbuild\iOS\..\iOS\Xamarin.iOS.Tasks.dll
Parameters
AppBundleName = iOSApp4
BundleIdentifier = com.companyname.iOSApp4
CodesignEntitlements = Entitlements.plist
RequireCodeSigning = False
SdkIsSimulator = True
SdkPlatform = iPhoneSimulator
SessionId = ...
TargetFrameworkMoniker = .NETCoreApp,Version=v6.0,Profile=ios
DetectSigningIdentity: 2022-09-28T04:17:13.3947732-07:00 - Started
DetectSigningIdentity: 2022-09-28T04:17:13.3947732-07:00 - Initializing
[xma][info]: Trying to get a Build Connection for …
=> [release/7.0.1xx-rc2] [msbuild] Make DetectSigningIdentity.CodesignEntitlements an ITaskItem property.

msbuild/Xamarin.MacDev.Tasks/Tasks/DetectSigningIdentityTaskBase.cs, tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/DetectSigningIdentityTaskTests.cs
This way XVS will copy the corresponding file to the mac during a build.
Target Name=_DetectSigningIdentity Project=C:\Users\admin\source\repos\iOSApp4\iOSApp4\iOSApp4.csproj
DetectSigningIdentity
Assembly = C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.0.515\tools\msbuild\iOS\..\iOS\Xamarin.iOS.Tasks.dll
Parameters
AppBundleName = iOSApp4
BundleIdentifier = com.companyname.iOSApp4
CodesignEntitlements = Entitlements.plist
RequireCodeSigning = False
SdkIsSimulator = True
SdkPlatform = iPhoneSimulator
SessionId = ...
TargetFrameworkMoniker = .NETCoreApp,Version=v6.0,Profile=ios
DetectSigningIdentity: 2022-09-28T04:17:13.3947732-07:00 - Started
DetectSigningIdentity: 2022-09-28T04:17:13.3947732-07:00 - Initializing
[xma][info]: Trying to get a Build Connection for …
=> [release/7.0.1xx-xcode14-rc2] [msbuild] Make DetectSigningIdentity.CodesignEntitlements an ITaskItem property.

Make.config
=> [xcode14.1] Bump API references to Xcode 14 stable release for iOS, tvOS and watchOS.

src/uikit.cs
=> [UIKit] Change UITextInput.SelectedTextRange to not be ArgumentSemantic.Copy. Fixes #15677.

src/AVFoundation/AVAudioFormat.cs, src/avfoundation.cs, tests/monotouch-test/AVFoundation/AVAudioFormatTest.cs
The property returns a pointer to a struct, not the struct itself.
Fixes https://github.com/xamarin/xamarin-macios/issues/8892.
=> [AVFoundation] Fix the AVAudioFormat.StreamDescription binding. Fixes #8892.

tools/common/Frameworks.cs
The SensorKit framework isn't available on all devices (for instance iPads),
and as such we can't link with it strongly.
This seems to be a bug in Apple's toolchain, because Xcode runs into the same
problem if you try to use an app referencing SensorKit on an iPad.
Fixes https://github.com/xamarin/xamarin-macios/issues/9938.
=> [tools] Always weak link the SensorKit framework. Fixes #9938.

tools/devops/automation/scripts/bash/build-nugets.sh
Depending on the enabled platforms, we might not have files with all the listed extensions.
=> [net7.0] [devops] Don't fail building nugets if we dno't have files of every possible extension.

msbuild/Xamarin.Localization.MSBuild/MSBStrings.Designer.cs, msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx, msbuild/Xamarin.MacDev.Tasks/Tasks/ResolveNativeReferencesBase.cs
Fixes an issue where we'd end up trying to link with the managed assembly instead:
> ld: warning: ignoring file .../bin/Debug/net6.0-ios/MyBinding.dll, building for iOS Simulator-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00 0x04 0x00 0x00 0x00 0xFF 0xFF 0x00 0x00 )
Also add a warning if we run into other types of libraries in the future to
make it easier to diagnose.
=> [msbuild] Fix processing static libraries in binding sidecars.

Make.config
Clang will by default emit objc_msgSend stubs in Xcode 14, which ld from
earlier Xcodes doesn't understand. We disable this by passing
-fno-objc-msgsend-selector-stubs to clang.
Ref: https://developer.apple.com/videos/play/wwdc2022/110363/
Ref: https://www.wwdcnotes.com/notes/wwdc22/110363/
Ref: https://github.com/llvm/llvm-project/issues/56034
Fixes https://github.com/xamarin/xamarin-macios/issues/16223.
=> Disable objc_msgSend stubs in clang. Fixes #16223.

Make.config
Clang will by default emit objc_msgSend stubs in Xcode 14, which ld from
earlier Xcodes doesn't understand. We disable this by passing
-fno-objc-msgsend-selector-stubs to clang.
Ref: https://developer.apple.com/videos/play/wwdc2022/110363/
Ref: https://www.wwdcnotes.com/notes/wwdc22/110363/
Ref: https://github.com/llvm/llvm-project/issues/56034
Fixes https://github.com/xamarin/xamarin-macios/issues/16223.
Backport of #16231
=> [release/7.0.1xx-xcode14-rc2] Disable objc_msgSend stubs in clang. Fixes #16223.

Make.config
Clang will by default emit objc_msgSend stubs in Xcode 14, which ld from
earlier Xcodes doesn't understand. We disable this by passing
-fno-objc-msgsend-selector-stubs to clang.
Ref: https://developer.apple.com/videos/play/wwdc2022/110363/
Ref: https://www.wwdcnotes.com/notes/wwdc22/110363/
Ref: https://github.com/llvm/llvm-project/issues/56034
Fixes https://github.com/xamarin/xamarin-macios/issues/16223.
Backport of #16231
=> [net7.0-xcode14] Disable objc_msgSend stubs in clang. Fixes #16223.

Makefile
This is important when not building all platforms, because not all types of
files are produced for every platform.
=> [release] Only try to copy files to the package directory if they exist.

.github/workflows/autoformat2.yml
actions/github-script was recently updated from 3.1.0 to 6.3.1 (69de14c668b776631fc5c829c02403738c848e65), but unfortunately there were breaking changes:
* https://github.com/actions/github-script#breaking-changes
* https://github.com/actions/github-script/issues/242#issuecomment-1049167283
This would manifest as:
TypeError: Cannot read properties of undefined (reading 'listWorkflowRunArtifacts')
Error: Unhandled error: TypeError: Cannot read properties of undefined (reading 'listWorkflowRunArtifacts')
at eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6.3.1/dist/index.js:13340:16), <anonymous>:3:38)
at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6.3.1/dist/index.js:13341:12)
at main …
=> [autoformat] Update to cope with breaking changes in actions/github-script.

.github/workflows/update-single-platform-branches.yml
We have four branches that test releasing a single platform:
release/release-test-only-dotnet-$platform
In these branches, only the given platform is enabled (these are also
.NET-only branches), with the idea that we're testing the build and publish of
a single platform. These branches have a 'release/' prefix, so that the go
through as much as possible of our release pipeline.
Hopefully by testing and making sure the following builds and publishes correctly:
* All platforms (the default for our build)
* Each platform by itself
Building and publishing more than one (but less than all four) platforms also
work.
This PR will automatically update these four branches from main every
Saturday, so that we'll be able to find and fix any problems that occur before
release date.
=> [actions] Update the single-platform test branch every Saturday.

src/Foundation/NSArray.cs, src/Foundation/NSArray_1.cs, tests/monotouch-test/Foundation/ArrayTest.cs, tests/monotouch-test/Foundation/NSArray1Test.cs
For NSArray, implement:
* A ToArray () method that returns an NSArray[].
* A ToArray<T> () method that returns a T[].
* The IEnumerable<NSObject> interface.
For NSArray<T>, implement:
* A ToArray () method that returns a T[].
This should make NSArray much better to work with from managed code.
=> [Foundation] Add NSArray.ToArray and implement IEnumerable<NSObject>.

msbuild/Xamarin.MacDev.Tasks/Tasks/FindAotCompilerTaskBase.cs
The build command doesn't support a parameter to specify a NuGet.config, so we need to restore the temp project first, so we pass the NuGet.config file to use the sources from, in case it exists (e.g: the NuGet.config from the XMA dotnet path).
This is useful to support auhtorized NuGet feeds
Fixes Bug #1611102 - [XVS][MAUI] Failed to build .NET MAUI (net6.0) with iOS Simulator: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1611102
=> Ensure we restore the temp csproj to compute AOT compiler path

src/uikit.cs
=> [release/6.0.4xx-xcode14] [UIKit] Change UITextInput.SelectedTextRange to not be ArgumentSemantic.Copy. Fixes #15677.

src/uikit.cs
=> [release/7.0.1xx-rc2] [UIKit] Change UITextInput.SelectedTextRange to not be ArgumentSemantic.Copy. Fixes #15677.

src/uikit.cs
=> [release/7.0.1xx-xcode14-rc2] [UIKit] Change UITextInput.SelectedTextRange to not be ArgumentSemantic.Copy. Fixes #15677.

tests/linker/ios/link all/InterfacesTest.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/9566.
=> [tests] Enable tests for interfaces being linked away. Fixes #9566.

msbuild/Xamarin.MacDev.Tasks/Tasks/FindAotCompilerTaskBase.cs
The build command doesn't support a parameter to specify a NuGet.config, so we need to restore the temp project first, so we pass the NuGet.config file to use the sources from, in case it exists (e.g: the NuGet.config from the XMA dotnet path).
This is useful to support auhtorized NuGet feeds
Fixes Bug #1611102 - [XVS][MAUI] Failed to build .NET MAUI (net6.0) with iOS Simulator: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1611102
Backport of #16280
=> [release/7.0.1xx-rc2] Ensure we restore the temp csproj to compute AOT compiler path

msbuild/Xamarin.MacDev.Tasks/Tasks/FindAotCompilerTaskBase.cs
The build command doesn't support a parameter to specify a NuGet.config, so we need to restore the temp project first, so we pass the NuGet.config file to use the sources from, in case it exists (e.g: the NuGet.config from the XMA dotnet path).
This is useful to support auhtorized NuGet feeds
Fixes Bug #1611102 - [XVS][MAUI] Failed to build .NET MAUI (net6.0) with iOS Simulator: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1611102
Backport of #16280
=> [release/6.0.4xx-xcode14] Ensure we restore the temp csproj to compute AOT compiler path

tools/devops/automation/post-build-pipeline.yml
* Add net8.0, because that's coming soon.
* Add release-test/\*, because we want to run some automated tests on various
release configurations, and all the release/\* branches are branch-protected,
which means CI can't commit any such branch without going through a pull
request (which needs to be approved, etc.), and that's not very automated at
all. So add a branch pattern to the post-build pipeline that isn't
branch-protected.
=> [devops] Add more post-build pipeline branches.

.github/workflows/update-single-platform-branches.yml
=> [actions] Use a non-protected branch for release branch testing.

msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
…gs for remote builds
From net7, the original ILLInk targets are adding a new link attribute pointing to a supressions file inside the ILLink tasks folder, e.g: '--link-attributes "C:\Program Files\dotnet\sdk\7.0.100-rc.2.22477.23\Sdks\Microsoft.NET.ILLink.Tasks\build\6.0_suppressions.xml"'.
For remote builds, we need to replace the original dotnet folder with the XMA dotnet folder in the Mac, so in our override targets we replace this value before passing it to the ILLink task
=> [illink] Ensure we replace the dotnet SDK path in the _ExtraTrimmerArgs for remote builds

msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
.gs for remote builds
From net7, the original ILLInk targets are adding a new link attribute pointing to a supressions file inside the ILLink tasks folder, e.g: '--link-attributes "C:\Program Files\dotnet\sdk\7.0.100-rc.2.22477.23\Sdks\Microsoft.NET.ILLink.Tasks\build\6.0_suppressions.xml"'.
For remote builds, we need to replace the original dotnet folder with the XMA dotnet folder in the Mac, so in our override targets we replace this value before passing it to the ILLink task
Backport of #16294
=> [release/6.0.4xx-xcode14] [illink] Ensure we replace the dotnet SDK path in the _ExtraTrimmerArgs for remote builds

system-dependencies.sh, tests/test-dependencies.sh, tools/Makefile, tools/devops/add-summaries.sh, tools/devops/automation/templates/tests/build.yml, tools/devops/provision-brew-packages.csx
Also make the build go into the tools/devops directory, which will run
shellcheck on the bash files. This also required fixing a couple of issues in
one of the bash scripts.
We currently don't use yamllint, but that's coming very soon.
=> [system-dependencies] Check for and install shellcheck and yamllint.

msbuild/Xamarin.Shared/Xamarin.Shared.targets
Only sign the app bundle if codesigning is enabled.
This fixes a bug where we'd still try to sign an app bundle, even if the user
disabled code signing by setting EnableCodeSigning=false, if the default logic
was to sign the app bundle.
Fixes https://github.com/xamarin/xamarin-macios/issues/16197.
=> [msbuild] Only sign the app bundle if codesigning is enabled. Fixes #16197.

dotnet/targets/Xamarin.Shared.Sdk.props
Hardcode 'true' as the default value for GenerateSatelliteAssembliesForCore,
because .NET gets it wrong when building from inside VS (Windows).
When building using either VSMac or the command line (either from Windows or
Mac), the `MSBuildRuntimeType` property is set to `Core`, and as a result, the
default value for `GenerateSatelliteAssembliesForCore` is `true`:
```xml
<GenerateSatelliteAssembliesForCore Condition=" '$(GenerateSatelliteAssembliesForCore)' == '' and '$(MSBuildRuntimeType)' == 'Core' ">true</GenerateSatelliteAssembliesForCore>
```
See: https://github.com/dotnet/sdk/blob/00100960bf06cb595daba647673cd0329be896f4/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets#L41
This is the correct behavior.
However, when building from inside Visual Studio (for …
=> [dotnet] Hardcode 'true' as the default value for GenerateSatelliteAssembliesForCore. Fixes #16193.

tests/monotouch-test/ARKit/AREnvironmentProbeAnchorTest.cs, tests/monotouch-test/ARKit/ARReferenceObjectTest.cs
Looks like some of these tests are working in the simulator now.
I also confirmed that ARReferenceObjectTest.MarshallingTest test should be
ignored in the simulator by verifying that Xcode gets the same behavior we do
(i.e. it doesn't work).
Fixes https://github.com/xamarin/xamarin-macios/issues/9531.
=> [tests] Re-enable tests that were disabled in Xcode 12 beta 1. Fixes #9531.

tests/mtouch/Makefile, tools/mtouch/.gitignore, tools/mtouch/Constants.cs.in, tools/mtouch/Makefile, tools/mtouch/mtouch.csproj
Generate own constants file, instead of relying on platform-specific files in
src/, which may or may not exist depending on the enabled platforms.
=> [mtouch] Generate own constants file.

src/avfoundation.cs
Add an overload to AVAssetImageGenerator.GenerateCGImagesAsynchronously that
takes a callback we call with a managed CGImage instance instead of a CGImage handle.
This makes the API a bit easier to use.
Ref: https://github.com/xamarin/xamarin-macios/issues/16314
=> [AVFoundation] Improve the callback in AVAssetImageGenerator.GenerateCGImagesAsynchronously.

tests/xtro-sharpie/xtro-sanity/Sanitizer.cs, tools/common/ApplePlatform.cs
We can't process a common-fx.ignore file for a given framework if that
framework isn't included in any of the platforms we're building for.
Example: we can't process common-AppKit.ignore when only iOS is enabled,
because none of the errors listed in common-AppKit.ignore will be reported for
an iOS build.
=> [xtro] Fix processing common files when not all platforms are selected.

tests/dotnet/UnitTests/ProjectTest.cs
This test requires another platform to be enabled in addition to the current
platform being tested: that other platform is iOS when testing macOS, and
macOS for all other platforms.
This can be seen in the target frameworks for the referenced library projects:
MacCatalyst/Library.csproj:     <TargetFrameworks>net$(BundledNETCoreAppTargetFrameworkVersion)-macos;netstandard2.1</TargetFrameworks>
iOS/Library.csproj:             <TargetFrameworks>net$(BundledNETCoreAppTargetFrameworkVersion)-macos;netstandard2.1</TargetFrameworks>
macOS/Library.csproj:           <TargetFrameworks>net$(BundledNETCoreAppTargetFrameworkVersion)-ios;netstandard2.1</TargetFrameworks>
tvOS/Library.csproj:            <TargetFrameworks>net$(BundledNETCoreAppTargetFrameworkVersion)-macos;netstandard2.1</TargetFramework …
=> [test] Adjust ProjectTest.AppWithGenericLibraryReference to not fail when only macOS is enabled.

release/Makefile
We need to create a bundle.zip file even if we don't build for iOS (if for
instance we build for tvOS only).
=> [release] Always create bundle.zip.

builds/Makefile
Unfortunately builds fail often in CI due to random network errors. So try to
make downloading with curl a bit more resilient by re-trying downloads a few
times before giving up.
=> [builds] Retry downloads if they fail.

tools/devops/automation/templates/build/api-diff-process-results.yml
This way the api diff job can be re-run and not fail because the artifact
already exists:
> ##[error]Artifact 'DropMetadata-ChangeDetection' already exists. If the build is producing multiple Drops, the Drop Metadata Container Name should be unique for each Drop.
=> [devops] Add the job attempt to the api diff container name.

tools/devops/automation/scripts/bash/build-nugets.sh
We won't produce any *.msi files when building for macOS only for instance.
=> [devops] Don't fail if the build didn't produce any *.msi files.

tests/common/TestRuntime.cs, tests/monotouch-test/ObjCRuntime/ExceptionsTest.cs
Ignore ExceptionsTest.ManagedExceptionPassthrough on ARM64 desktop until we
fix the underlying bug.
Ref: https://github.com/xamarin/xamarin-macios/issues/16264
=> [tests] Ignore ExceptionsTest.ManagedExceptionPassthrough on ARM64 desktop.

src/uikit.cs
=> [net7.0] [UIKit] Change UITextInput.SelectedTextRange to not be ArgumentSemantic.Copy. Fixes #15677.

tools/apidiff/Makefile
=> [net7.0] [api-diff] Add api-diff.md to the all-markdowns target.

tests/test-libraries/frameworks/Makefile
Fixes this:
Making all in frameworks
/bin/sh: .libs/tvos-arm64/FrameworksInRuntimesNativeDirectory1.dll: No such file or directory
make[2]: *** [.libs/tvos-arm64/FrameworksInRuntimesNativeDirectory1.dll] Error 1
=> [tests] Add dependency so that we don't try to write a file in a directory that doesn't exist.

Make.config, builds/Makefile
* Use a variable for the curl command to avoid duplicating all the retry logic.
* Pass --retry-all-failures to curl to retry harder.
Hopefully fixes these errors:
curl: (56) LibreSSL SSL_read: error:02FFF036:system library:func(4095):Connection reset by peer, errno 54
make: *** [downloads/ios-release-Darwin-2a19f878dab8d2e62123e0bf29453de553f5402a.7z] Error 56
=> [builds] Improve curl commands to retry harder in case of failures.

tools/devops/automation/templates/build/api-diff-stage.yml, tools/devops/automation/templates/build/build-stage.yml, tools/devops/automation/templates/build/build.yml, tools/devops/automation/templates/common/configure.yml, tools/devops/automation/templates/mac/stage.yml, tools/devops/automation/templates/sign-and-notarized/funnel.yml, tools/devops/automation/templates/tests/stage.yml
Remove support/logic for the following labels:
* run-internal-tests
* skip-external-tests
* trigger-device-tests
because they didn't actually do anything.
Also use underscores instead of dashes in output variables, because these
variables are also exported as environment variables, and environment variable
names can't contain dashes (bash can't access them).
=> [devops] Increase bash compatibility and clean variables a bit.

tools/devops/automation/scripts/bash/collect-and-upload-crash-reports.sh
Fix crash report collection to not try to zip up the
~/Library/Logs/DiagnosticReports directory if there's nothing in it, because
it creates a warning in Azure DevOps:
+ zip -9rj /Users/builder/azdo/_work/2/s/crash-reports.zip /Users/builder/Library/Logs/DiagnosticReports
zip error: Nothing to do! (try: zip -9rj /Users/builder/azdo/_work/2/s/crash-reports.zip . -i /Users/builder/Library/Logs/DiagnosticReports)
##[error]Bash exited with code '12'.
Also remove some debug spew, and make it possible to create a crash report
collection locally by writing the zip file to the current directory if
SYSTEM_DEFAULTWORKINGDIRECTORY isn't set.
=> [devops] Fix crash report collection when there's nothing to collect.

msbuild/Xamarin.MacDev.Tasks/.gitignore, msbuild/Xamarin.MacDev.Tasks/Xamarin.MacDev.Tasks.csproj, tests/mmptest/mmptest.csproj, tools/dotnet-linker/dotnet-linker.csproj, tools/mmp/mmp.csproj, tools/mtouch/README.md, tools/mtouch/mtouch.csproj, tools/nnyeah/nnyeah/nnyeah.csproj
The Xamarin.MacDev.Tasks.sln solution is built with dotnet, while other projects
are still built with msbuild. This becomes a problem when generating Errors.designer.cs,
because depending on the runtime the output is different.
This means that the Errors.designer.cs will sometimes randomly change (depending
on which project re-generated the file), leaving the file modified in git. This is
quite annoying, but it also breaks the api comparison, which depends on the build
not leaving modified files behind. So for now, we generate Errors.designer.cs separately
for Xamarin.MacDev.Tasks.sln to not conflict with the mtouch version.
Also fix capitalization in numerous places to be consistent (it's Errors.designer.cs,
not Errors.Designer.cs).
=> [msbuild] Fix dirty working copy with Errors.designer.cs.

tests/monotouch-test/System.Net.Http/MessageHandlers.cs
Fixes a problem where any exception would crash the process, because the
callback was executed on a background thread, and there was no other managed
frame catching the managed exception:
MonoTests.System.Net.Http.MessageHandlerTest.RejectSslCertificatesWithCustomValidationCallbackNSUrlSessionHandler
2022-10-21 07:02:23.557 monotouchtest[91107:28076542] *** Terminating app due to uncaught exception 'NUnit.Framework.AssertionException', reason: '  Expected: None
But was:  RemoteCertificateChainErrors
(NUnit.Framework.AssertionException)
at NUnit.Framework.Assert.ReportFailure(String message)
at NUnit.Framework.Assert.ReportFailure(ConstraintResult result, String message, Object[] args)
at NUnit.Framework.Assert.AreEqual(Object expected, Object actual)
at …
=> [tests] Handle managed exceptions in a networking callback.

msbuild/Makefile
Ema pinpointed this commit to bee the root causing reflection issues on the windows side
https://gist.github.com/Redth/e60fcf1b790eb9efe3e476788bff5693#file-remotesimoutput-log-L13-L26
=> [release/7.0.1xx-xcode14][msbuild] Partial revert of ad8cdb3

msbuild/Makefile
Ema pinpointed this commit to bee the root causing reflection issues on the windows side
https://gist.github.com/Redth/e60fcf1b790eb9efe3e476788bff5693#file-remotesimoutput-log-L13-L26
Backport of #16418
=> [net7.0-xcode14.1] [release/7.0.1xx-xcode14][msbuild] Partial revert of ad8cdb3

Make.config
Current versions in this branch:
Microsoft.iOS 16.1.1419-net7.0-xcode14.1+sha.51ad25e7b64
Microsoft.tvOS 16.1.1419-net7.0-xcode14.1+sha.51ad25e7b64
Microsoft.MacCatalyst 16.1.1419-net7.0-xcode14.1+sha.51ad25e7b64
Microsoft.macOS 13.0.1974-net7.0-xcode14.1+sha.51ad25e7b64
Compare with the `release/6.0.4xx-xcode14.1` branch version numbers (from #16431):
Microsoft.iOS 16.1.179+sha.2107639a131
Microsoft.tvOS 16.1.179+sha.2107639a131
Microsoft.MacCatalyst 16.1.179+sha.2107639a131
Microsoft.macOS 13.0.734+sha.2107639a131
the buffer is >1000 commits.
=> [net7.0-xcode14.1] Make the buffer bigger between .NET 6 and .NET 7 nugets for Xcode 14.1

Make.config
Current release versions in this branch:
Microsoft.iOS 16.1.179+sha.2107639a131
Microsoft.tvOS 16.1.179+sha.2107639a131
Microsoft.MacCatalyst 16.1.179+sha.2107639a131
Microsoft.macOS 13.0.734+sha.2107639a131
Compare with the net7.0-xcode14.1 branch version numbers (from #16430):
Microsoft.iOS 16.1.1419-net7.0-xcode14.1+sha.51ad25e7b64
Microsoft.tvOS 16.1.1419-net7.0-xcode14.1+sha.51ad25e7b64
Microsoft.MacCatalyst 16.1.1419-net7.0-xcode14.1+sha.51ad25e7b64
Microsoft.macOS 13.0.1974-net7.0-xcode14.1+sha.51ad25e7b64
the buffer is >1000 commits.
=> [6.0.4xx-xcode14.1] Make this a release branch.

src/HomeKit/HMCompat.cs, src/homekit.cs, tests/introspection/iOS/iOSApiCtorInitTest.cs, tests/xtro-sharpie/api-annotations-dotnet/iOS-HomeKit.ignore, tests/xtro-sharpie/iOS-HomeKit.ignore
Fixes xamarin/xamarin-macios#16415
HMAccessorySetupManager was removed by mistake when we had to remove matter related objects due to submission tests.
We have kept the Matter APIs removed and just enabled PerformAccessorySetup Submission tests are happy using Xcode 14.1 RC1
https://gist.github.com/dalexsoto/243b0da224c613e9afc9706c54f882a1
=> [xcode14.1][HomeKit] Brings back HMAccessorySetupManager

msbuild/Messaging/Xamarin.Messaging.Build/Xamarin.Messaging.Build.csproj
We recently switched from building the msbuild tasks with 'msbuild' to use
'dotnet build' instead.
One difference between the two methods is that 'dotnet build' doesn't copy
referenced assemblies to the output path.
This turns out to be a problem because we zip up the output from the
Xamarin.Messaging.Build project, and expect it to contain everything required
to load the Xamarin.Messaging.Build assembly (this zip file is shipped with
our VS (Windows) support, and during remote execution copied to the connected
mac and then the build from Windows will load the assembly on the Mac in order
to do stuff on the Mac).
Another problem is that we include MSBuild assemblies from the
'$(MSBuildBinPath)' location, which is now different (we used to pick up
Mono's MSBuild assemblies, and that …
=> [msbuild] Fix creating Build.zip.

tools/compare-commits.sh
Fix undefined array access due to empty bash array when running on bots by
always creating a non-empty array (of color arguments to git).
=> [compare-commits] Fix undefined array access when running on bots.

msbuild/Directory.Build.props
=> [release/7.0.1xx-xcode13.3] Updated Xamarin.Messaging to 1.8.26

msbuild/Directory.Build.props
=> [net7.0-xcode14] Updated Xamarin.Messaging to 1.8.26

msbuild/Directory.Build.props
=> [release/7.0.1xx-xcode14] Updated Xamarin.Messaging to 1.8.26

msbuild/Directory.Build.props
=> [release/6.0.4xx-xcode14] Updated Xamarin.Messaging to 1.8.26

msbuild/Directory.Build.props
=> [net7.0] Updated Xamarin.Messaging to 1.8.26

msbuild/Directory.Build.props
=> [release/6.0.4xx-xcode14.1] Updated Xamarin.Messaging to 1.8.26

msbuild/Directory.Build.props
=> Updated Xamarin.Messaging to 1.8.26

msbuild/Directory.Build.props
=> [net7.0-xcode14.1] Updated Xamarin.Messaging to 1.8.26

msbuild/Directory.Build.props
=> [xcode14.1] Updated Xamarin.Messaging to 1.8.26

msbuild/Directory.Build.props
=> [release/6.0.4xx] Updated Xamarin.Messaging to 1.8.26

tools/apidiff/Makefile
We can only compare Microsoft.iOS.dll and Microsoft.MacCatalyst.dll when all of the following are true:
* .NET is enabled.
* iOS is enabled.
* Mac Catalyst is enabled.
So adjust (and simplify a bit) our logic accordingly.
=> [apidiff] Fix when to compare Microsoft.iOS.dll vs Microsoft.MacCatalyst.dll.

tools/devops/automation/scripts/bash/configure-decisions.sh, tools/devops/automation/templates/build/build-pkgs.yml, tools/devops/automation/templates/build/build-stage.yml, tools/devops/automation/templates/build/build.yml, tools/devops/automation/templates/common/configure.yml, tools/devops/automation/templates/mac/stage.yml
* Don't run these tests if neither macOS nor Mac Catalyst is enabled.
* Honor `skip-all-tests` to skip these tests.
* Change the `skip-packaged-xamarin-mac-tests` label to `skip-packaged-macos-tests` since Xamarin.Mac is disappearing soon.
* Add a `run-packaged-macos-tests` to mirror `skip-packaged-macos-tests` (this is useful when using `skip-all-tests` to only run these tests).
=> [devops] Only run tests on other macOS versions in certain scenarios.

src/ObjCRuntime/Runtime.cs, tests/monotouch-test/ObjCRuntime/RegistrarTest.cs, tests/monotouch-test/ObjCRuntime/RuntimeTest.cs
Objective-C has an optimization where creating an empty dictionary would
return the same instance every time (probably to a constant empty dictionary).
This causes a problem with how we've bound generic dictionaries, because all
empty dictionaries would have the same native handle, even if we'd bound them
with different managed types.
This surfaces in unfortunate ways when we try to look up a managed instance
given a native handle, we find that we already have a managed instance, but
the managed instance is of the wrong type.
Example code:
var a = new NSDictionary ();
var b = new NSDictionary<NSString, NSString> ();
var c = new NSDictionary<NSString, NSObject> ();
Console.WriteLine ($"a: 0x{a.Handle:X}");
Console.WriteLine ($"b: 0x{b.Handle:X}");
Console.WriteLine ($"c: 0x{c.Handle:X}"); …
=> [ObjCRuntime] Change Runtime.GetNSObject<T> to create a new instance if the existing one is of the wrong type. Fixes #13704.

src/ObjCRuntime/Runtime.cs, tests/monotouch-test/ObjCRuntime/RegistrarTest.cs, tests/monotouch-test/ObjCRuntime/RuntimeTest.cs
Objective-C has an optimization where creating an empty dictionary would
return the same instance every time (probably to a constant empty dictionary).
This causes a problem with how we've bound generic dictionaries, because all
empty dictionaries would have the same native handle, even if we'd bound them
with different managed types.
This surfaces in unfortunate ways when we try to look up a managed instance
given a native handle, we find that we already have a managed instance, but
the managed instance is of the wrong type.
Example code:
var a = new NSDictionary ();
var b = new NSDictionary<NSString, NSString> ();
var c = new NSDictionary<NSString, NSObject> ();
Console.WriteLine ($"a: 0x{a.Handle:X}");
Console.WriteLine ($"b: 0x{b.Handle:X}");
Console.WriteLine ($"c: 0x{c.Handle:X}"); …
=> [xcode14.1] [ObjCRuntime] Change Runtime.GetNSObject<T> to create a new instance if the existing one is of the wrong type. Fixes #13704.

tools/devops/automation/templates/build/build.yml, tools/devops/automation/templates/mac/build.yml, tools/devops/automation/templates/tests/build.yml
=> [release/7.0.1xx-xcode13.3] Update all provisionator call sites to use AUTH_TOKEN_GITHUB_COM

tools/devops/automation/templates/build/build.yml, tools/devops/automation/templates/mac/build.yml, tools/devops/automation/templates/tests/build.yml
=> [net7.0] Update all provisionator call sites to use AUTH_TOKEN_GITHUB_COM

tools/devops/automation/templates/build/build.yml, tools/devops/automation/templates/mac/build.yml, tools/devops/automation/templates/tests/build.yml
=> [net7.0-xcode14] Update all provisionator call sites to use AUTH_TOKEN_GITHUB_COM

Make.config, dotnet/Makefile
Stable MSIs are versioned like non-stable MSIs, except that:
* We define the commit distance as the number of commits since the branch
bacame a release branch (and started using stable branding). Technically
this is the number of commits since the NUGET_RELEASE_BRANCH variable
changed (which will be incorrect for non-stable branches, but in that case
we shouldn't use this number in those scenarios).
* We use the above-mentioned commit distance as the third number in the MSI
version (as opposed to the fourth number in non-stable branches.)
Note: we detect if we're building a stable release by checking if the
NUGET_PRERELEASE_IDENTIFIER is empty (we can't use NUGET_RELEASE_BRANCH,
because this variable will be set for PRs to the release branch, while
NUGET_PRERELEASE_IDENTIFIER will only be …
=> [release/6.0.4xx-xcode14.1] [dotnet] Adjust stable MSI versioning.

Make.config, dotnet/Makefile
Stable MSIs are versioned like non-stable MSIs, except that:
* We define the commit distance as the number of commits since the branch
bacame a release branch (and started using stable branding). Technically
this is the number of commits since the `NUGET_RELEASE_BRANCH` variable
changed (which will be incorrect for non-stable branches, but in that case
we shouldn't use this number in those scenarios).
* We use the above-mentioned commit distance as the third number in the MSI
version (as opposed to the fourth number in non-stable branches.)
Note: we detect if we're building a stable release by checking if the
`NUGET_PRERELEASE_IDENTIFIER` is empty (we can't use `NUGET_RELEASE_BRANCH`,
because this variable will be set for PRs to the release branch, while
`NUGET_PRERELEASE_IDENTIFIER` will …
=> [dotnet] Adjust stable MSI versioning.

tools/devops/automation/templates/build/build.yml, tools/devops/automation/templates/mac/build.yml, tools/devops/automation/templates/tests/build.yml
=> [release/6.0.4xx-xcode14] Update all provisionator call sites to use AUTH_TOKEN_GITHUB_COM

tools/devops/automation/templates/build/build.yml, tools/devops/automation/templates/mac/build.yml, tools/devops/automation/templates/tests/build.yml
=> Update all provisionator call sites to use AUTH_TOKEN_GITHUB_COM

tools/devops/automation/templates/build/build.yml, tools/devops/automation/templates/mac/build.yml, tools/devops/automation/templates/tests/build.yml
=> [net7.0-xcode14.1] Update all provisionator call sites to use AUTH_TOKEN_GITHUB_COM

tools/devops/automation/templates/build/build.yml, tools/devops/automation/templates/mac/build.yml, tools/devops/automation/templates/tests/build.yml
=> [release/6.0.4xx-xcode14.1] Update all provisionator call sites to use AUTH_TOKEN_GITHUB_COM

tools/devops/automation/templates/build/build.yml, tools/devops/automation/templates/mac/build.yml, tools/devops/automation/templates/tests/build.yml
=> [release/6.0.4xx] Update all provisionator call sites to use AUTH_TOKEN_GITHUB_COM

tools/devops/automation/templates/build/build.yml, tools/devops/automation/templates/mac/build.yml, tools/devops/automation/templates/tests/build.yml
=> [xcode14.1] Update all provisionator call sites to use AUTH_TOKEN_GITHUB_COM

tests/monotouch-test/System.Net.Http/MessageHandlers.cs
Fixes a problem where any exception would crash the process, because the
callback was executed on a background thread, and there was no other managed
frame catching the managed exception:
MonoTests.System.Net.Http.MessageHandlerTest.RejectSslCertificatesWithCustomValidationCallbackNSUrlSessionHandler
2022-10-21 07:02:23.557 monotouchtest[91107:28076542] *** Terminating app due to uncaught exception 'NUnit.Framework.AssertionException', reason: '  Expected: None
But was:  RemoteCertificateChainErrors
(NUnit.Framework.AssertionException)
at NUnit.Framework.Assert.ReportFailure(String message)
at NUnit.Framework.Assert.ReportFailure(ConstraintResult result, String message, Object[] args)
at NUnit.Framework.Assert.AreEqual(Object expected, Object actual)
at …
=> [net7.0-xcode14.1] [tests] Handle managed exceptions in a networking callback.

tests/monotouch-test/System.Net.Http/MessageHandlers.cs
Fixes a problem where any exception would crash the process, because the
callback was executed on a background thread, and there was no other managed
frame catching the managed exception:
MonoTests.System.Net.Http.MessageHandlerTest.RejectSslCertificatesWithCustomValidationCallbackNSUrlSessionHandler
2022-10-21 07:02:23.557 monotouchtest[91107:28076542] *** Terminating app due to uncaught exception 'NUnit.Framework.AssertionException', reason: '  Expected: None
But was:  RemoteCertificateChainErrors
(NUnit.Framework.AssertionException)
at NUnit.Framework.Assert.ReportFailure(String message)
at NUnit.Framework.Assert.ReportFailure(ConstraintResult result, String message, Object[] args)
at NUnit.Framework.Assert.AreEqual(Object expected, Object actual)
at …
=> [xcode14.1] [tests] Handle managed exceptions in a networking callback.

Make.config, builds/Makefile, tools/apidiff/Makefile, tools/apidiff/README.md, tools/devops/automation/templates/build/api-diff-build-and-detect.yml, tools/devops/automation/templates/main-stage.yml
Update the download of API references to:
* Use `dl.internalx.com` links instead of `bosstoragemirror.blob.core.windows.net`
links (the relative path stays the same).
* Require a GitHub PAT in order to download from dl.internalx.com. This PAT
can either be provided through a file (recommended for local use) or through
the environment.
* Document these changes.
Also backport #16394, which these changes require.
Backport of #16548.
=> [release/6.0.4xx-xcode14.1] [apidiff] Change to use dl.internalx.com with a GitHub PAT for API reference downloads.

Make.config, builds/Makefile, tools/apidiff/Makefile, tools/apidiff/README.md, tools/devops/automation/templates/build/api-diff-build-and-detect.yml, tools/devops/automation/templates/main-stage.yml
Update the download of API references to:
* Use `dl.internalx.com` links instead of `bosstoragemirror.blob.core.windows.net`
links (the relative path stays the same).
* Require a GitHub PAT in order to download from dl.internalx.com. This PAT
can either be provided through a file (recommended for local use) or through
the environment.
* Document these changes.
Also backport #16394, which these changes require.
Backport of #16548.
=> [release/6.0.4xx-xcode14] [apidiff] Change to use dl.internalx.com with a GitHub PAT for API reference downloads.

tools/devops/automation/post-build-pipeline.yml
We don't need the binlogs in order to produce a successful build (only to
diagnose a failing build).
=> [devops] Make publishing binlogs nonfatal.

tests/monotouch-test/System.Net.Http/MessageHandlers.cs
Fixes a problem where any exception would crash the process, because the
callback was executed on a background thread, and there was no other managed
frame catching the managed exception:
MonoTests.System.Net.Http.MessageHandlerTest.RejectSslCertificatesWithCustomValidationCallbackNSUrlSessionHandler
2022-10-21 07:02:23.557 monotouchtest[91107:28076542] *** Terminating app due to uncaught exception 'NUnit.Framework.AssertionException', reason: '  Expected: None
But was:  RemoteCertificateChainErrors
(NUnit.Framework.AssertionException)
at NUnit.Framework.Assert.ReportFailure(String message)
at NUnit.Framework.Assert.ReportFailure(ConstraintResult result, String message, Object[] args)
at NUnit.Framework.Assert.AreEqual(Object expected, Object actual)
at …
=> [release/6.0.4xx-xcode14.1] [tests] Handle managed exceptions in a networking callback.

Make.config, builds/Makefile, tools/apidiff/Makefile, tools/apidiff/README.md, tools/devops/automation/templates/build/api-diff-build-and-detect.yml, tools/devops/automation/templates/main-stage.yml
Update the download of API references to:
* Use `dl.internalx.com` links instead of `bosstoragemirror.blob.core.windows.net`
links (the relative path stays the same).
* Require a GitHub PAT in order to download from dl.internalx.com. This PAT
can either be provided through a file (recommended for local use) or through
the environment.
* Document these changes.
Also backport #16394, which these changes require.
Backport of #16548.
=> [net7.0-xcode14.1] [apidiff] Change to use dl.internalx.com with a GitHub PAT for API reference downloads.

Make.config, builds/Makefile, tools/apidiff/Makefile, tools/apidiff/README.md, tools/devops/automation/templates/build/api-diff-build-and-detect.yml, tools/devops/automation/templates/main-stage.yml
Update the download of API references to:
* Use `dl.internalx.com` links instead of `bosstoragemirror.blob.core.windows.net`
links (the relative path stays the same).
* Require a GitHub PAT in order to download from dl.internalx.com. This PAT
can either be provided through a file (recommended for local use) or through
the environment.
* Document these changes.
Also backport #16394, which these changes require.
Backport of #16548.
=> [xcode14.1] [apidiff] Change to use dl.internalx.com with a GitHub PAT for API reference downloads.

tests/common/TestRuntime.cs, tests/monotouch-test/ObjCRuntime/ExceptionsTest.cs
Ignore ExceptionsTest.ManagedExceptionPassthrough on ARM64 desktop until we
fix the underlying bug.
Ref: https://github.com/xamarin/xamarin-macios/issues/16264
Backport of #16384
=> [xcode14.1] [tests] Ignore ExceptionsTest.ManagedExceptionPassthrough on ARM64 desktop.

tests/common/TestRuntime.cs, tests/monotouch-test/ObjCRuntime/ExceptionsTest.cs
Ignore ExceptionsTest.ManagedExceptionPassthrough on ARM64 desktop until we
fix the underlying bug.
Ref: https://github.com/xamarin/xamarin-macios/issues/16264
Backport of #16384
=> [release/6.0.4xx-xcode14.1] [tests] Ignore ExceptionsTest.ManagedExceptionPassthrough on ARM64 desktop.

tests/common/TestRuntime.cs, tests/monotouch-test/ObjCRuntime/ExceptionsTest.cs
Ignore ExceptionsTest.ManagedExceptionPassthrough on ARM64 desktop until we
fix the underlying bug.
Ref: https://github.com/xamarin/xamarin-macios/issues/16264
Backport of #16384
=> [release/7.0.1xx] [tests] Ignore ExceptionsTest.ManagedExceptionPassthrough on ARM64 desktop.

tests/bindings-test/dotnet/shared.csproj, tests/bindings-test2/dotnet/shared.csproj, tests/fsharplibrary/dotnet/shared.fsproj
The NUnitLite package is already included in the shared-dotnet.csproj file,
which these projects import.
=> [tests] Remove a few duplicated package references.

Make.config
There's no release coming from main, so unset the prerelease identifier.
=> Unset the prerelease identifier.

mk/versions.mk, mk/xamarin.mk
Also add copy make target to bump the current maccore hash from maccore.
* xamarin/maccore@893e01ae00 Update provisionator bootstrap
* xamarin/maccore@7fa40752e4 Merge xcode14 into main.
* xamarin/maccore@140923bddf Merge remote-tracking branch 'xamarin/xcode14' into merge-xcode14-into-main
* xamarin/maccore@4e3eab455c Use Environment.SpecialFolder.UserProfile, not SpecialFolder.Personal.
* xamarin/maccore@9a347bd708 [certificates] Update la_dev_apple.p12, la_distr_apple.p12 and la_mac_installer_distr.p12
* xamarin/maccore@bcdd779e58 [devops] Install Mono too.
* xamarin/maccore@75a03ccbfc [xcode14] Merge main into xcode14
* xamarin/maccore@7690a80a2f [submission] Fix submission test makefile
* xamarin/maccore@813beaf11a Don't build mlaunch from the …
=> Switch maccore to track main and bump.

dotnet/Makefile
The `%(Version)` metadata declared in `vs-workload.props` should always
be a four part version, this was missed when reviewing commit https://github.com/xamarin/xamarin-macios/commit/9f1dc519ea2211df8a4440336c3e867455bc4691.
Fix this by adding a trailing `.0` to stable branded packages.
For "Preview" branded manifest packs, the fourth part of the version
should be the commit distance (e.g. 16.1.0.5).
For "Stable" branded manifest packs, the third part of the version
should be the commit distance (e.g. 16.1.5.0).
See the following for more info on `vs-workload.props` versioning:
https://github.com/xamarin/sdk-insertions/wiki/How-to-create-a-new-insertion#msi-generation-and-vs-versioning-requirements
=> [dotnet] Always use a four part VS component version

dotnet/Makefile
The `%(Version)` metadata declared in `vs-workload.props` should always
be a four part version, this was missed when reviewing commit https://github.com/xamarin/xamarin-macios/commit/9f1dc519ea2211df8a4440336c3e867455bc4691.
Fix this by adding a trailing `.0` to stable branded packages.
For "Preview" branded manifest packs, the fourth part of the version
should be the commit distance (e.g. 16.1.0.5).
For "Stable" branded manifest packs, the third part of the version
should be the commit distance (e.g. 16.1.5.0).
See the following for more info on `vs-workload.props` versioning:
https://github.com/xamarin/sdk-insertions/wiki/How-to-create-a-new-insertion#msi-generation-and-vs-versioning-requirements
Backport of #16633
=> [release/7.0.1xx] [dotnet] Always use a four part VS component version

dotnet/targets/Xamarin.Shared.Sdk.targets, tools/common/CompilerFlags.cs
Don't disable compact unwind info in the native linker, it may break C++
exception handling.
We originally disabled compact unwind info to fix a warning from the native
linker, this will have to be solved another way (in any case extra build
warnings is preferrable compared to an app crashing at runtime due to broken
C++ exception handling).
This partially reverts c05e774612a95bf3830509d55a25784d3805344e.
Fixes https://github.com/xamarin/xamarin-macios/issues/16546.
=> [dotnet/tools] Don't disable compact unwind info. Fixes #16546.

dotnet/Makefile
The `%(Version)` metadata declared in `vs-workload.props` should always
be a four part version, this was missed when reviewing commit https://github.com/xamarin/xamarin-macios/commit/9f1dc519ea2211df8a4440336c3e867455bc4691.
Fix this by adding a trailing `.0` to stable branded packages.
For "Preview" branded manifest packs, the fourth part of the version
should be the commit distance (e.g. 16.1.0.5).
For "Stable" branded manifest packs, the third part of the version
should be the commit distance (e.g. 16.1.5.0).
See the following for more info on `vs-workload.props` versioning:
https://github.com/xamarin/sdk-insertions/wiki/How-to-create-a-new-insertion#msi-generation-and-vs-versioning-requirements
Backport of #16633
=> [release/6.0.4xx-xcode14.1] [dotnet] Always use a four part VS component version

tools/devops/automation/build-cronjob.yml, tools/devops/automation/build-pipeline.yml, tools/devops/automation/build-pull-request.yml, tools/devops/automation/publish-pr-html-results.yml, tools/devops/automation/templates/build/api-diff-stage.yml, tools/devops/automation/templates/build/build-stage.yml, tools/devops/automation/templates/build/build.yml, tools/devops/automation/templates/common/checkout.yml, tools/devops/automation/templates/common/setup.yml, tools/devops/automation/templates/common/teardown.yml, tools/devops/automation/templates/mac/build.yml, tools/devops/automation/templates/release/vs-insertion-prep.yml, tools/devops/automation/templates/sign-and-notarized/funnel.yml, tools/devops/automation/templates/sign-and-notarized/setup.yml, tools/devops/automation/templates/sign-and-notarized/upload-azure.yml, tools/devops/automation/vs-insertion.yml
In an attempt to unify the build of all the SDKs we need to be rename all shared resources between the CIs to all use the same name.
This commit renames the resource to use the pattern used by MAUI.
Partial fix for https://github.com/xamarin/sdk-insertions/issues/39
=> [DevOps] Rename the yaml-templates resources to match the MAUI repo.

tools/devops/automation/templates/common/checkout.yml, tools/devops/automation/templates/loc-translations.yml, tools/devops/automation/templates/sign-and-notarized/funnel.yml, tools/devops/automation/templates/sign-and-notarized/setup.yml, tools/devops/automation/templates/sign-and-notarized/upload-azure.yml, tools/devops/automation/templates/windows/reserve-mac.yml
Move to use a template to perform the checkout. The new template allows to perform the checkout using a resource alias, which later can be used to use the template outside this repo. 
Partial fix for https://github.com/xamarin/sdk-insertions/issues/41
=> [DevOps] Use the checkout template for the unified pipeline to work.

msbuild/Xamarin.Shared/Xamarin.Shared.targets
Building a binding project from Windows without a Mac connection doesn't work,
because we need to execute bgen. Currently we just skip every task and target
that doesn't work from Windows, but that means nothing at all happens, which
is confusing (in particular if the binding project is referenced by other
projects, which will also fail to build).
So make it more explicit that a connection to a Mac is required to build a
binding project by showing a warning when there's no connection (and not an
error because that could break existing workflows for customers).
Ref: https://github.com/xamarin/xamarin-macios/issues/16611
=> [msbuild] Show an error when trying to build a binding project from Windows without a Mac connection.

tools/devops/automation/templates/build/build.yml
This makes sure we're at the right maccore hash before adding provisioning
profile (in particular we want to be at the hash where the PR branch is at,
not the tip of main (which is the default)).
=> [devops] Reset dependencies before adding provisioning profiles.

tools/common/Application.cs, tools/common/StaticRegistrar.cs, tools/common/Target.cs, tools/dotnet-linker/Steps/RegistrarStep.cs, tools/mmp/driver.cs, tools/mtouch/BuildTasks.mtouch.cs, tools/mtouch/Target.mtouch.cs
This is a step towards having a registration map (and initialization method) for each assembly.
Ref: https://github.com/xamarin/xamarin-macios/issues/11309
=> [registrar] Deduplicate the code to compute the initialization method name for the generated static registrar code.

tools/devops/automation/templates/build/build.yml, tools/devops/automation/templates/mac/build.yml, tools/devops/automation/templates/tests/build.yml
=> [xcode14.1] [DevOps] Update the way we pass the token to the provisionator task.

tools/devops/automation/scripts/GitHub.psm1, tools/devops/automation/templates/build/api-diff-process-results.yml, tools/devops/automation/templates/build/build.yml, tools/devops/automation/templates/common/clean.yml, tools/devops/automation/templates/common/status.yml, tools/devops/automation/templates/mac/build.yml, tools/devops/automation/templates/sign-and-notarized/artifact-github-comment.yml, tools/devops/automation/templates/sign-and-notarized/upload-azure.yml, tools/devops/automation/templates/tests/build.yml, tools/devops/automation/templates/tests/publish-html.yml, tools/devops/automation/templates/tests/run-tests.yml, tools/devops/automation/templates/tests/stage.yml
The template can be run by a diff pipeline, that means that the project and the commit wont point to xmarin/xamarin-macios. We use the URI to calculate the org and the repo to be passed to the pwh objects.
Fixes https://github.com/xamarin/sdk-insertions/issues/43
=> [DevOps] Use the project URI to calculate the project.

mk/xamarin.mk
* xamarin/maccore@ce1fd64f90 [xcode14] Update provisionator bootstrap
* xamarin/maccore@75a03ccbfc [xcode14] Merge main into xcode14
Diff: https://github.com/xamarin/maccore/compare/0837e7caffb2e42efcd183cb1d71998fb6022e2c..ce1fd64f905cc6d96ddeed0eb2a77fb0d8715ac2
=> [xcode14.1] Bump maccore.

tests/linker/ios/link sdk/CryptoTest.cs
Fixes this test in .NET 8:
AesCreate: System.Security.Cryptography.Algorithms,
Expected: String starting with "System.Security.Cryptography.Algorithms, "
But was: "System.Security.Cryptography, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
=> [tests] Fix conditional logic for .NET 7+.

tools/devops/automation/scripts/bash/install-workloads.sh
It's often desired to run the install-workloads.sh script locally, in order to
diagnose problems with it.
So improve it a bit by:
* Adding a few comments explaining things.
* Don't assume we're in the correct directory.
* Figure out BUILD_SOURCESDIRECTORY if it's not already set.
* Validate a bit and show more helpful errors.
Hopefully future me will be grateful!
=> [devops] Augment the install-workloads.sh script to make it easier to run locally.

tests/api-shared/CoreFoundation/CFNotificationCenterTest.cs
Hopefully fixes https://github.com/xamarin/maccore/issues/1440.
=> [tests] Make CFNotificationCenterTest.TestNullNameAndObserver wait for notifications. Hopefully fixes #xamarin/maccore@1440.

mk/xamarin.mk
* xamarin/maccore@ce1fd64f90 [xcode14] Update provisionator bootstrap
* xamarin/maccore@75a03ccbfc [xcode14] Merge main into xcode14
Diff: https://github.com/xamarin/maccore/compare/0837e7caffb2e42efcd183cb1d71998fb6022e2c..ce1fd64f905cc6d96ddeed0eb2a77fb0d8715ac2
=> [release/7.0.1xx] Bump maccore to get provisionator fixes.

Make.config
MSIs has a limit:
> Relative package path exceeds the maximum length (182): Microsoft.MacCatalyst.Manifest-8.0.100-alpha.1,version=128.67.51819,chip=x86,productarch=neutral\Microsoft.NET.Sdk.MacCatalyst.Manifest-8.0.100-alpha.1.16.1.555-net8.0-preview.1-x86.msi
So use a shorter prerelease identifier to try to not reach this limit.
=> [dotnet] Shorten prerelease identifier to make package names shorter.

tools/devops/automation/templates/sign-and-notarized/upload-azure.yml
Azure pipelines has this terrible design in which the path of the checkout is different depending if you checkout a single repo or several.
In this case, we have no issues on macios because we do know we have not been checkout with anyother repo in the upload step, that is not the case when working on the unified pipeline. Rather than adding some complicated logic, we are going to be checking out the yaml templates so that we have the same working directory structure.
=> [DevOps] Checkout the yaml repos to fix an issue with the working dir.

tests/monotouch-test/AudioUnit/AudioUnitTest.cs
There was a PR race:
1. I created a PR to autoformat monotouch-test code.
2. Another PR added incorrectly formatted code to monotouch-test.
3. The first PR was merged, everything was fine.
4. The second PR was merged (it was green) - but its code hadn't been
autoformatted.
5. Now there's incorrectly formatted code in the repo, which will show up in
every new PR.
=> [autoformat] Autoformat after a PR race.

tests/xtro-sharpie/Makefile, tests/xtro-sharpie/xtro-report/Reporter.cs
There was a typo in the target name for creating the html report for .NET
('report-dotnet' vs 'dotnet-report').
Also print out the full path the html report when it's created, makes it much
easier to open the file from the command line because I can c&p the entire
path.
=> [xtro] Fix targets file and print out full path to the html report.

tests/monotouch-test/AudioUnit/AudioUnitTest.cs, tools/devops/automation/templates/main-stage.yml
Allow to add a dependency before our build. This is used in the unified pipeline to try to download the binaries if it can rather than building from scratch.
=> [DevOps] Allow to pass extra dependencies for the build stage.

tests/common/TestRuntime.cs, tests/monotouch-test/System.Net.Http/MessageHandlers.cs
Ignore certificate chain errors on bots in MessageHandlerTest.RejectSslCertificatesWithCustomValidationCallbackNSUrlSessionHandler.
Fixes https://github.com/xamarin/maccore/issues/2626.
=> [monotouch-test] Ignore certificate chain errors on bots. Fixes #xamarin/maccore@2626.

runtime/exports.t4, runtime/monovm-bridge.m
MonoVM in .NET 6+ supports automatic autorelease pools on threadpool threads
just like CoreCLR does, so we can remove our custom mono profiler hooks to
accomplish this.
Fixes https://github.com/xamarin/xamarin-macios/issues/11788.
=> [runtime] Use the built-in support in MonoVM for autorelease pools on threadpool threads. Fixes #11788.

tools/devops/automation/templates/tests/build.yml, tools/devops/automation/templates/tests/run-tests.yml
There's no need to:
* Check for HD space.
* Make mlaunch verbose.
* Reset launchctl.
if something else already went wrong in a test run.
=> [devops] Skip a few steps if something goes wrong.

dotnet/targets/Xamarin.Shared.Sdk.targets, tools/common/CompilerFlags.cs
Don't disable compact unwind info in the native linker, it may break C++
exception handling.
We originally disabled compact unwind info to fix a warning from the native
linker, this will have to be solved another way (in any case extra build
warnings is preferrable compared to an app crashing at runtime due to broken
C++ exception handling).
This partially reverts c05e774612a95bf3830509d55a25784d3805344e.
Fixes https://github.com/xamarin/xamarin-macios/issues/16546.
Backport of #16623
=> [xcode14.1] [dotnet/tools] Don't disable compact unwind info. Fixes #16546.

src/uikit.cs, tests/monotouch-test/AudioUnit/AudioUnitTest.cs
Changing properties to be internal
Fixes #16665
=> [UIKit] Fix properties in UIConfigurationColorTransformer Type

tests/common/mac/ApiDefinition.cs, tests/common/mac/BindingProjectWithNoTag.csproj, tests/common/mac/Component1.fs, tests/common/mac/MobileBinding.csproj, tests/common/mac/MyClass.cs, tests/common/mac/ProjectTestHelpers.cs, tests/common/mac/StructsAndEnums.cs, tests/common/mac/SystemMonoExample.csproj, tests/common/mac/Today/TodayViewController.cs, tests/common/mac/UnifiedExample.csproj, tests/common/mac/UnifiedLibrary.csproj, tests/common/mac/XM45Binding.csproj, tests/common/mac/XM45Example.csproj, tests/common/mac/XM45Library.csproj, tests/mmptest/src/ExtensionTests.cs, tests/mmptest/src/PackageReferenceTests.cs, tests/mmptest/src/XM45Example.csproj
When the autoformatter runs into the '%...%' pattern in *.cs files, it will
re-format the text (to '% ... %'), but that breaks our text replacement logic.
So instead use a valid C# identifier as a replacement token, in which case the
autoformatter won't confuse our replacement logic.
=> [tests] Use a different identifier than '%...%' for replacement text.

dotnet/Makefile
Fixes this random build error:
/bin/sh: Workloads/Microsoft.NET.Sdk.macOS/WorkloadManifest.targets.tmp: No such file or directory
make[1]: *** [Workloads/Microsoft.NET.Sdk.macOS/WorkloadManifest.targets] Error 1
make[1]: *** Waiting for unfinished jobs....
=> [dotnet] Make sure to create a directory before we try to put files into it.

tests/monotouch-test/PassKit/PassLibraryTest.cs
PKPassLibrary.GetPasses randomly returns null for no apparent rhyme or reason
on our bots, so just ignore the test in that case.
Maybe if someone can reproduce locally one day we'll be able to investigate
and figure out what's happening.
Fixes https://github.com/xamarin/maccore/issues/2598.
=> [tests] Ignore PassLibraryTest.PassLibraryTest on bots if PKPassLibrary.GetPasses returns null. Fixes #xamarin/maccore@2598.

src/PassKit/PKEnums.cs, src/appkit.cs, src/avfoundation.cs, src/btouch.cs, src/carplay.cs, src/contacts.cs, src/coredata.cs, src/coreimage.cs, src/gamecontroller.cs, src/healthkit.cs, src/mapkit.cs, src/metal.cs, src/notificationcenter.cs, src/pdfkit.cs, src/scenekit.cs, src/sharedwithyou.cs, src/soundanalysis.cs, src/uikit.cs, src/usernotifications.cs, src/xkit.cs, tests/monotouch-test/AudioUnit/AudioUnitTest.cs
Fixes these warnings:
appkit.cs(13128,8): warning CS0108: 'NSResponder.RestoreUserActivityState(NSUserActivity)' hides inherited member 'NSUserActivityRestoring.RestoreUserActivityState(NSUserActivity)'. Use the new keyword if hiding was intended.
appkit.cs(19500,12): warning CS0109: The member 'NSTextView.Editable' does not hide an accessible member. The new keyword is not required.
appkit.cs(19503,12): warning CS0109: The member 'NSTextView.Selectable' does not hide an accessible member. The new keyword is not required.
appkit.cs(27481,14): warning CS0108: 'NSFontAssetRequest.Progress' hides inherited member 'NSProgressReporting.Progress'. Use the new keyword if hiding was intended.
appkit.cs(5342,8): warning CS0108: 'NSController.DiscardEditing()' hides inherited member …
=> [generator] Fix warnings in api definitions.

msbuild/Xamarin.iOS.Tasks/Tasks/ValidateAppBundleTaskBase.cs
I've made some small edits to the ValidateWatchApp method to allow for a native watchOS app that was created in Xcode 14 that uses a single project instead of an extension to be bundled into a Xamarin app. 
Should fix #16142 and progress on #10070
=> Fix native watchOS app bundling when using newer Xcode 14 watchOS project. Fixes #16142.

tools/devops/automation/scripts/GitHub.Tests.ps1, tools/devops/automation/scripts/GitHub.psm1, tools/devops/automation/templates/build/api-diff-build-and-detect.yml, tools/devops/automation/templates/build/build-stage.yml, tools/devops/automation/templates/common/setup.yml, tools/devops/automation/templates/mac/build.yml, tools/devops/automation/templates/sign-and-notarized/artifact-github-comment.yml, tools/devops/automation/templates/sign-and-notarized/upload-azure.yml, tools/devops/automation/templates/tests/build.yml, tools/devops/automation/templates/tests/publish-html.yml, tools/devops/automation/templates/tests/run-tests.yml, tools/devops/automation/templates/variables.yml
A lot of code in our repo uses the presence of the BUILD_REVISION environment
variable to determine whether we're running in CI or not, so just set the
variable globally once so that it's always set - that way we never forget to
set it.
Note that the exact value of the variable doesn't matter, only that it's set.
Also change one place in the yaml that was depending on the contents of the
BUILD_REVISION to use the Azure Devops variable BUILD_SOURCEVERSION instead
(like we do everywhere else in our yaml code).
=> [devops] Set BUILD_REVISION globally.

msbuild/Xamarin.iOS.Tasks/Tasks/ValidateAppBundleTaskBase.cs
I've made some small edits to the ValidateWatchApp method to allow for a native watchOS app that was created in Xcode 14 that uses a single project instead of an extension to be bundled into a Xamarin app. 
Should fix #16142 and progress on #10070
Backport of #16690
=> [main] Fix native watchOS app bundling when using newer Xcode 14 watchOS project. Fixes #16142.

tests/package-mac-tests.sh
The random build failure it causes aren't worth it for the speed gain.
=> [tests] Don't build packaged macOS tests in parallel in CI.

src/Foundation/NSAttributedString.iOS.cs, src/foundation.cs, tests/xtro-sharpie/api-annotations-dotnet/iOS-UIKit.ignore, tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.ignore, tests/xtro-sharpie/api-annotations-dotnet/tvOS-UIKit.ignore, tests/xtro-sharpie/iOS-UIKit.ignore, tests/xtro-sharpie/macOS-AppKit.ignore, tests/xtro-sharpie/tvOS-UIKit.ignore, tests/xtro-sharpie/watchOS-UIKit.ignore
The 'initWithFileURL:options:documentAttributes:error:' was deprecated in iOS
9, and a new alternative (initWithURL:options:documentAttributes:error:) was
added. At the time, we implemented automatic detection of the current OS, and
would choose one version or the other depending on which was available.
We won't support anything below iOS 9 anymore, which means that keeping the
backwards-compatible constructor is useless, so just remove the corresponding
code and expose the new alternative directly.
On another note, this constructor uses a 'ref NSError' argument instead of an
'out NSError' on mobile platforms (likely due to the generator not having
proper 'out' parameter support when this constructor was implemented), so
improve to use 'out' parameters in XAMCORE_5_0 (and macOS, where it …
=> [Foundation] Remove support for '[NSAttributedString initWithFileURL:options:documentAttributes:error:]'.

src/foundation.cs, tests/xtro-sharpie/api-annotations-dotnet/iOS-UIKit.ignore, tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.ignore, tests/xtro-sharpie/api-annotations-dotnet/tvOS-UIKit.ignore, tests/xtro-sharpie/iOS-UIKit.ignore, tests/xtro-sharpie/macOS-AppKit.ignore, tests/xtro-sharpie/tvOS-UIKit.ignore, tests/xtro-sharpie/watchOS-UIKit.ignore
Unify the code for the following functions:
* NSAttributedString.GetData[FromRange]
* NSAttributedString.GetFileWrapper[FromRange]
These functions use 'ref' arguments instead of 'out' arguments for mobile
platforms (likely due to the generator not having proper 'out' parameter
support when these functions were implemented), so improve to use 'out'
parameters in XAMCORE_5_0 (and macOS, where they already use 'out'
parameters).
Also fix nullability.
Ref: https://github.com/xamarin/xamarin-macios/issues/15216
=> [Foundation] Unify a few NSAttributedString functions.

msbuild/Xamarin.Shared/Xamarin.Shared.targets
Fixes #16377 
MSbuild has the ability to run `Target` partially. However in order to make sure we can use this, both the `Inputs` and `Outputs` need to have a 1-1 mapping. MSBuild will then use this mapping to figure out which files have actually changed.
Then it will call the Target with only those files. 
In Xamarin.Android we make use of stamp files to provide this 1-1 mapping. We have a `pre` Target which will calculate an ItemGroup which will include a StampFile piece of metadata. We then use this new ItemGroup for both the `Inputs` and `Outputs`, thus meeting the 1-1 requirement. 
This PR updates the `_UnpackLibraryResources` to run partially. This will hopefully reduce the build time on incremental builds.
=> [msbuild] Don't process assemblies over and over again in the UnpackLibraryResources target. Fixes #16377.

msbuild/Xamarin.MacDev.Tasks/MsBuildTasks/Delete.cs
The `Delete` task should not need to copy any files to the remote server.
Lets try to set this up by implementing the `ShouldCopyToBuildServer` method.
This should help reduce build times if it works.
=> Do not copy files to build server for a Delete.

Make.config, dotnet/generate-workloadmanifest-json.csharp, runtime/Makefile, runtime/xamarin-support.m, src/Makefile, tests/test-libraries/Makefile, tests/test-libraries/frameworks/Makefile, tools/mtouch/Makefile
There are no changes for 32-bit watchOS, because watchOS support is likely to
go away completely anyways.
=> Add automatic support for not building iOS 32-bit stuff when min iOS version is >= 11.0

tools/common/StaticRegistrar.cs
Change the static registrar to fail gracefully if it can't compute a metadata token
for a given metadata item, and instead fall back to doing the lookup of whatever
we need at runtime.
This is a step towards making per-assembly static registrar working.
Ref: https://github.com/xamarin/xamarin-macios/issues/12067.
=> [static registrar] Handle metadata token lookup failure gracefully.

src/avfoundation.cs, src/coregraphics.cs, src/generator-enums.cs, src/generator.cs
Unify generation/copying of Obsolete attributes from api definitions to generated code.
This reduces code dupliation a bit, but it will also result in more
"[EditorBrowsable (Never)]" attributes (which we weren't generating in a few
cases).
In addition we're now copying Obsolete attributes for smart fields to the
generated code.
=> [generator] Unify generation/copying of Obsolete attributes.

tools/devops/automation/build-cronjob.yml
I have been testing these changes inside the xamarin-macios-translations pipeline.
The last run was green (found [here](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6984912&view=results)). I had to use some placeholder code for the actual calls for the OneLocBuild task that will communicate with the Loc Team but it reached those points as expected!
This PR also rips out calls to the main-stage.yml template to only use the stages necessary for the OneLocBuild run over the weekend!
I think these changes are set to see if the main branch can trigger the OneLocBuild Task over the weekend build!
=> [Localization] Change the Cron Job to trigger weekend scheduled build

tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/GeneratePlistTaskTests/GeneratePlistTaskTests_watchOS.cs, tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/GeneratePlistTaskTests/GeneratePlistTaskTests_watchOS_WatchKitApp.cs, tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/GeneratePlistTaskTests/GeneratePlistTaskTests_watchOS_WatchKitExtension.cs
Fixes these tests:
```
* Xamarin.MacDev.Tasks.GeneratePlistTaskTests_watchOS_WatchKitExtension(True).BuildMachineOSBuild: System.InvalidOperationException : Invalid platform: WatchOS
* Xamarin.MacDev.Tasks.GeneratePlistTaskTests_watchOS_WatchKitExtension(True).BundleDevelopmentRegion: System.InvalidOperationException : Invalid platform: WatchOS
* Xamarin.MacDev.Tasks.GeneratePlistTaskTests_watchOS_WatchKitExtension(True).BundleExecutable: System.InvalidOperationException : Invalid platform: WatchOS
* Xamarin.MacDev.Tasks.GeneratePlistTaskTests_watchOS_WatchKitExtension(True).BundleIdentifier: System.InvalidOperationException : Invalid platform: WatchOS
* Xamarin.MacDev.Tasks.GeneratePlistTaskTests_watchOS_WatchKitExtension(True).BundleInfoDictionaryVersion: …
```
=> [tests] Don't run watchOS tests for .NET.

src/CoreLocation/CLEnums.cs, src/watchkit.cs
Fixes these test failures:
1) Failed : Cecil.Tests.EnumTest.NoAvailabilityOnError("/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/32bits/iOS/Xamarin.iOS.dll")
CoreLocation.CLError.HistoricalLocationError
Expected: <empty>
But was:  < "CoreLocation.CLError.HistoricalLocationError" >
at Cecil.Tests.EnumTest.NoAvailabilityOnError (System.String assemblyPath) [0x00067] in /Users/builder/azdo/_work/3/s/xamarin-macios/tests/cecil-tests/EnumTest.cs:29
2) Failed : Cecil.Tests.EnumTest.NoAvailabilityOnError("/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/64bits/iOS/Xamarin.iOS.dll")
CoreLocation.CLError.HistoricalLocationError
Expected: <empty>
But was:  < "CoreLocation.CLError.HistoricalLocationError" >
at Cecil.Tests.EnumTest.NoAvailabilityOnError (System.String …
=> [src] Remove availability attributes on error enums.

tests/monotouch-test/VideoToolbox/VTCompressionSessionTests.cs
Fixes:
MonoTouchFixtures.VideoToolbox.VTCompressionSessionTests.TestCallback
[FAIL] TestCallback(True) :   timed out
Expected: True
at MonoTouchFixtures.VideoToolbox.VTCompressionSessionTests.TestCallback(Boolean stronglyTyped) in /Users/builder/azdo/_work/3/s/xamarin-macios/tests/monotouch-test/VideoToolbox/VTCompressionSessionTests.cs:line 171
[FAIL] TestCallback(False) :   timed out
Expected: True
at MonoTouchFixtures.VideoToolbox.VTCompressionSessionTests.TestCallback(Boolean stronglyTyped) in /Users/builder/azdo/_work/3/s/xamarin-macios/tests/monotouch-test/VideoToolbox/VTCompressionSessionTests.cs:line 171
at InvokeStub_VTCompressionSessionTests.TestCallback(Object, Object, IntPtr*)
=> [tests] Adjust MonoTouchFixtures.VideoToolbox.VTCompressionSessionTests.TestCallback to ignore timeouts in CI.

tests/bindings-test/iOS/bindings-test.csproj, tests/bindings-test/macOS/bindings-test.csproj, tests/common/TestRuntime.cs, tests/linker/ios/link sdk/AsyncTest.cs
Fixes:
[FAIL] Bug12221 : System.AggregateException : One or more errors occurred. (Response status code does not indicate success: 403 (Forbidden).)
----> System.Net.Http.HttpRequestException : Response status code does not indicate success: 403 (Forbidden).
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
at System.Threading.Tasks.Task.Wait()
at LinkSdk.AsyncTests.Bug12221() in /Users/builder/azdo/_work/1/s/xamarin-macios/tests/linker/ios/link sdk/AsyncTest.cs:line 25
at System.Reflection.MethodInvoker.InterpretedInvoke(Object , Span`1 , BindingFlags )
--HttpRequestException
at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage , …
=> [tests] Improve AsyncTests.Bug12221 to not fail on 403 errors on the bots.

tools/devops/automation/scripts/VSTS.psm1
Also add 'run-packaged-macos-tests' to the labels we care about.
This fixes an issue where the label combination
'skip-all-tests,run-packaged-macos-tests' would not run any tests.
=> [devops] Update according to renamed label.

tools/apidiff/Makefile
This fixes an issue where emojis weren't rendered as such in some browsers,
because the browser would use a different character set than utf8.
=> [apidiff] Generate a complete and valid html file for api-diff.html.

dotnet/targets/Xamarin.Shared.Sdk.targets, tools/common/CompilerFlags.cs
Don't disable compact unwind info in the native linker, it may break C++
exception handling.
We originally disabled compact unwind info to fix a warning from the native
linker, this will have to be solved another way (in any case extra build
warnings is preferrable compared to an app crashing at runtime due to broken
C++ exception handling).
This partially reverts c05e774612a95bf3830509d55a25784d3805344e.
Fixes https://github.com/xamarin/xamarin-macios/issues/16546.
Backport of #16623
Backport of #16624
=> [release/7.0.1xx] [dotnet/tools] Don't disable compact unwind info. Fixes #16546.

dotnet/targets/Xamarin.Shared.Sdk.targets, tools/common/CompilerFlags.cs
Don't disable compact unwind info in the native linker, it may break C++
exception handling.
We originally disabled compact unwind info to fix a warning from the native
linker, this will have to be solved another way (in any case extra build
warnings is preferrable compared to an app crashing at runtime due to broken
C++ exception handling).
This partially reverts c05e774612a95bf3830509d55a25784d3805344e.
Fixes https://github.com/xamarin/xamarin-macios/issues/16546.
Backport of #16623
Backport of #16624
=> [release/6.0.4xx-xcode14.1] [dotnet/tools] Don't disable compact unwind info. Fixes #16546.

tests/monotouch-test/MediaAccessibility/ImageCaptioningTest.cs
=> [tests] Adjust ImageCaptioningTest to skip network-related failures in CI.

tests/monotouch-test/System.Net.Http/MessageHandlers.cs
Fixes:
[FAIL] TestNSurlSessionHandlerCookieContainerSetCookie :   Cookies received from server.
Expected: 1
But was:  0
at MonoTests.System.Net.Http.MessageHandlerTest.TestNSurlSessionHandlerCookieContainerSetCookie() in /Users/builder/azdo/_work/3/s/xamarin-macios/tests/monotouch-test/System.Net.Http/MessageHandlers.cs:line 233
[FAIL] TestNSUrlSessionHandlerCookies :   Failed to get managed cookies
Expected: True
at MonoTests.System.Net.Http.MessageHandlerTest.TestNSUrlSessionHandlerCookies () [0x000aa] in /Users/builder/azdo/_work/3/s/xamarin-macios/tests/monotouch-test/System.Net.Http/MessageHandlers.cs:144
Fixes https://github.com/xamarin/maccore/issues/2197.
=> [tests] Adjust TestNSurlSessionHandlerCookieContainer* tests to not fail in CI in case of network problems. Fixes #2197.

src/Foundation/NSDate.cs, tests/monotouch-test/Asserts.cs, tests/monotouch-test/Foundation/DateTest.cs
We recently tried to fix NSDate's conversion operators with DateTime
(3c65ab17569baf9f9acd8b6e2ded19aeb4fdfe7b), but unfortunately a corner case
was missed.
The new approach in the above-mentioned commit would get the individual
date/time components for a given date and use the appropriate constructor for
the other type to re-construct the date/time in question.
However, one case was missed: when converting from NSDate to DateTime, we'd
get a fractional number of milliseconds. This fractional number could be
something like 999.99 milliseconds, and when converting that to the int the
DateTime constructor expected for the number of milliseconds, then DateTime
would throw an exception, because the number of milliseconds could only be
between 0 and 999.
I've solved this by not using …
=> [Foundation] Fix NSDate's explicit conversion operators with DateTime.

tests/cecil-tests/EnumTest.cs
Also remove some unnecessary null-checking code.
=> [tests] Adjust the NoAvailabilityOnError cecil test to look in and work with .NET assemblies as well.

src/ObjCRuntime/Runtime.CoreCLR.cs, tools/mtouch/Errors.designer.cs, tools/mtouch/Errors.resx
Don't add a dot after showing another exception message, because that another
exception message might also add a dot.
Example:
> An exception occurred while trying to invoke the function System.Void VisualStudioMac.AppDelegate.DidFinishLaunching (Foundation.NSNotification): Object of type 'CoreLocation.CLLocationManager' cannot be converted to type 'Foundation.NSNotification'..
=> [ObjCRuntime] Fix double dots in exception message.

src/foundation.cs
This simplifies the code a little bit.
Ref: https://github.com/xamarin/xamarin-macios/issues/14489
=> [Foundation] Remove some conditional logic from NSAttributedString's API definition.

tests/common/TestRuntime.cs
Fixes this warning:
> xamarin-macios/tests/common/TestRuntime.cs(1321,4): warning CS0162: Unreachable code detected
=> [tests] Move code to avoid unreachable code warning.

tools/common/Application.cs, tools/common/Driver.cs
tools/common/Driver.cs(302,14): warning CS0649: Field 'Driver.Jobs' is never assigned to, and will always have its default value 0
=> [tools] Exclude Driver.Concurrency from .NET.

src/Foundation/NSAttributedString.cs, src/Foundation/NSAttributedString.iOS.cs, src/Foundation/NSAttributedString.mac.cs
This also makes the set of constructors for NSAttributedString identical
between all platforms.
Ref: https://github.com/xamarin/xamarin-macios/issues/14489
=> [Foundation] Share custom constructor code between iOS and macOS for NSAttributedString.

tools/dotnet-linker/Steps/ExtractBindingLibrariesStep.cs
We don't want to pass -force_load unncessarily to the native linker, because
that defeats -dead_strip and makes apps bigger than necessary. So make sure to
honor the correct value for native libraries from binding libraries.
Fixes https://github.com/xamarin/xamarin-macios/issues/16861.
=> [dotnet-linker] Only enable ForceLoad for native binding libraries if that's actually requested in the binding library. Fixes #16861.

tests/common/TestRuntime.cs
Fixes these warnings:
xamarin-macios/tests/common/TestRuntime.cs(1228,8): warning CA1422: This call site is reachable on: 'MacCatalyst' 13.3 and later. 'ABAuthorizationStatus.Denied' is obsoleted on: 'maccatalyst' 9.0 and later (Use the 'Contacts' API instead.).
xamarin-macios/tests/common/TestRuntime.cs(1227,8): warning CA1422: This call site is reachable on: 'MacCatalyst' 13.3 and later. 'ABAuthorizationStatus.Restricted' is obsoleted on: 'maccatalyst' 9.0 and later (Use the 'Contacts' API instead.).
xamarin-macios/tests/common/TestRuntime.cs(1221,8): warning CA1422: This call site is reachable on: 'MacCatalyst' 13.3 and later. 'ABAuthorizationStatus.NotDetermined' is obsoleted on: 'maccatalyst' 9.0 and later (Use the 'Contacts' API instead.).
=> [tests] Ignore CA1422 for some code.

tests/common/TestRuntime.cs
Fixes this warning:
> warning CS0618: 'NSString.FromHandle(NativeHandle)' is obsolete: 'Use of 'CFString.FromHandle' offers better performance.'
=> [tests] Use CFString.FromHandle instead of NSString.FromHandle.

tools/common/PathUtils.cs
Fixes:
tools/common/PathUtils.cs(175,10): warning CS8981: The type name 'timespec' only contains lower-cased ascii characters. Such names may become reserved for the language.
tools/common/PathUtils.cs(180,10): warning CS8981: The type name 'stat' only contains lower-cased ascii characters. Such names may become reserved for the language.
=> [tools] Rename a few lowercased types to fix compiler warning.

tools/devops/automation/templates/loc-translations.yml
In our localization process, the Loc team builds the translations (in the not-user-readable .lcl files) and merges them into the 'Localization' branch from a 'Lego/...' branch. After this happens, our 'Get Localization Translations' github action takes that commits and creates a PR into main with those changes. It is really important that this github action works because we will later delete the 'Localization' branch and create a new one from the 'main' branch so that the branches stay in sync. 
There worked fine, but there is now a 'isDeletePrSourceBranchSelected' input to the OneLocBuild task that defaults to true that deletes the 'Lego/...' branch right after the commit to 'Localization' is made. Due to this, the github action cannot bring the commit to 'main' because the 'Lego/...' …
=> [Localization] Set OneLocBuild Task to not delete Lego Branch

tests/xharness/TestLabel.cs
While this value isn't used directly in xharness, we can add a
'skip-packaged-macos-tests' label for a PR, which xharness will try to match
with a test label, so the test label must exist, otherwise all tests will
fail.
=> [xharness] Packaged macOS tests are a thing now.

tests/monotouch-test/PassKit/PassLibraryTest.cs
PKPassLibrary.GetPasses randomly returns null for no apparent rhyme or reason
on our bots, so just ignore the test in that case.
Maybe if someone can reproduce locally one day we'll be able to investigate
and figure out what's happening.
Fixes https://github.com/xamarin/maccore/issues/2598.
Backport of #16738
=> [release/7.0.1xx] [tests] Ignore PassLibraryTest.PassLibraryTest on bots if PKPassLibrary.GetPasses returns null. Fixes #xamarin/maccore@2598.

msbuild/Xamarin.MacDev.Tasks/Tasks/CompileAppManifestTaskBase.cs
Return early after a failure, in order to fix a nullability problem where the
out variable from a method call can be null if the function returns false - in
which case we can't keep doing things, we need to return, because the
subsequent code doesn't handle the potential null value from the out
parameter.
=> [msbuild] Fix nullability issue.

dotnet/generate-vs-workload.csharp
Context: https://github.com/xamarin/yaml-templates/pull/204
Context: https://github.com/xamarin/xamarin-android/pull/7471
Updates the VSMAN files generated for our .NET workload to support Visual Studio on windows-arm64.
=> [build] Add support for Visual Studio on win-arm64

src/Foundation/MonoTouchException.cs
Hopefully fixes this problem:
Unhandled managed exception: Failed to print exception: System.NullReferenceException: Object reference not set to an instance of an object
at Foundation.MonoTouchException.AppendNativeStackTrace (System.Text.StringBuilder sb) [0x0002f] in /Library/Frameworks/Xamarin.iOS.framework/Versions/16.0.0.72/src/Xamarin.iOS/Foundation/MonoTouchException.cs:51
at Foundation.MonoTouchException.get_Message () [0x00039] in /Library/Frameworks/Xamarin.iOS.framework/Versions/16.0.0.72/src/Xamarin.iOS/Foundation/MonoTouchException.cs:43
at ObjCRuntime.Runtime.PrintException (System.Exception exc, System.Boolean isInnerException, System.Text.StringBuilder sb) [0x0000f] in /Library/Frameworks/Xamarin.iOS.framework/Versions/16.0.0.72/src/Xamarin.iOS/ObjCRuntime/Runtime.cs:528 …
=> [Foundation] Improve null-checking in MonoTouchException.AppendNativeStackTrace.

src/Foundation/NSAttributedString.iOS.cs, src/Foundation/NSAttributedString.mac.cs, src/appkit.cs, src/uikit.cs, src/xkit.cs
This also allows us to unify the code between all platforms.
There are no changes in the public API, because I'm only changing internal types.
Ref: #14489.
=> [Foundation] Create a new NSAttributedStringDocument type to match Apple's headers.

tests/bcl-test/common-monotouch_corlib_test.dll.ignore, tests/bcl-test/macOS-xammac_net_4_5_corlib_test.dll.ignore
It looks like some timezone data has changed, so this test is now failing.
Mono will probably not be updated, so just ignore the test.
Fixes https://github.com/xamarin/maccore/issues/2629.
=> [tests] Ignore the MonoTests.System.TimeZoneInfoTest+IsDaylightSavingTimeTests.Bug_16395 test. Fixes #xamarin/maccore@2629.

dotnet/generate-vs-workload.csharp
Context: https://github.com/xamarin/yaml-templates/pull/204
Context: https://github.com/xamarin/xamarin-android/pull/7471
Updates the VSMAN files generated for our .NET workload to support Visual Studio on windows-arm64.
Backport of ##16935.
=> [release/7.0.1xx] [build] Add support for Visual Studio on win-arm64.

.github/workflows/maestro-changelog.yml
Fixes this:
SyntaxError: Unexpected identifier
at new AsyncFunction (<anonymous>)
Error: Unhandled error: SyntaxError: Unexpected identifier
at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6.3.3/dist/index.js:13356:16)
at main (/home/runner/work/_actions/actions/github-script/v6.3.3/dist/index.js:13452:26)
at Module.858 (/home/runner/work/_actions/actions/github-script/v6.3.3/dist/index.js:13429:1)
at __webpack_require__ (/home/runner/work/_actions/actions/github-script/v6.3.3/dist/index.js:24:31)
at startup (/home/runner/work/_actions/actions/github-script/v6.3.3/dist/index.js:43:19)
at /home/runner/work/_actions/actions/github-script/v6.3.3/dist/index.js:49:18
at Object.<anonymous> (/home/runner/work/_actions/actions/github-script/v6.3.3/dist/index.js:52:10)
at …
=> [actions] Fix parsing problem in the changelog action.

src/Foundation/NSFastEnumerationState.cs, src/Foundation/NSFastEnumerator.cs
The NSFastEnumerator protocol in Objective-C works like this:
1. A selector is called on the collection in question, where we give the
native method a pointer to a state structure. Upon return, the state
structure will have two important pointers: one to a C array with the
pointers to enumerate, and another pointer that points to a value
determining whether the collection was modified since enumeration started.
2. In the original managed implementation, we'd store the state (a struct) as
an instance field of NSFastEnumerator.
This works fine... most of the time. Unfortunately most of the time isn't good
enough, because this may happen:
a. The native iterator function might store a pointer into the state structure
itself as the pointer to check for a modified collection.
b. The GC runs, …
=> [release/6.0.4xx-xcode14.1] [Foundation] Fix random memory access / memory corruption in NSFastEnumerator. Fixes #xamarin/maccore@1347.

src/Foundation/NSFastEnumerationState.cs, src/Foundation/NSFastEnumerator.cs
The NSFastEnumerator protocol in Objective-C works like this:
1. A selector is called on the collection in question, where we give the
native method a pointer to a state structure. Upon return, the state
structure will have two important pointers: one to a C array with the
pointers to enumerate, and another pointer that points to a value
determining whether the collection was modified since enumeration started.
2. In the original managed implementation, we'd store the state (a struct) as
an instance field of NSFastEnumerator.
This works fine... most of the time. Unfortunately most of the time isn't good
enough, because this may happen:
a. The native iterator function might store a pointer into the state structure
itself as the pointer to check for a modified collection.
b. The GC runs, …
=> [xcode14.1] [Foundation] Fix random memory access / memory corruption in NSFastEnumerator. Fixes #xamarin/maccore@1347.

dotnet/generate-vs-workload.csharp
Context: https://github.com/xamarin/yaml-templates/pull/204
Context: https://github.com/xamarin/xamarin-android/pull/7471
Updates the VSMAN files generated for our .NET workload to support Visual Studio on windows-arm64.
Backport of ##16935.
=> [release/6.0.4xx-xcode14.1] [build] Add support for Visual Studio on win-arm64.

.gitmodules
Bump Xamarin.MacDev to get a fix for .NET 8: the value of
Environment.SpecialFolder.Personal will change.
* xamarin/Xamarin.MacDev@fc05c31 [net7.0] Use Environment.SpecialFolder.UserProfile, not SpecialFolder.Personal.
Diff: https://github.com/xamarin/Xamarin.MacDev/compare/0717ac3c249595b48860904ce77000a6115affbe..fc05c313e7fb09db30b3182fd8adc3a562a593c6
=> [release/7.0.1xx] Bump Xamarin.MacDev.

.gitmodules
Bump Xamarin.MacDev to get a fix for .NET 8: the value of
Environment.SpecialFolder.Personal will change.
* xamarin/Xamarin.MacDev@616d0a5 [net6.0] Use Environment.SpecialFolder.UserProfile, not SpecialFolder.Personal.
Diff: https://github.com/xamarin/Xamarin.MacDev/compare/0717ac3c249595b48860904ce77000a6115affbe..616d0a561e604b6ff2057651bb46767643f02b3f
=> [release/6.0.4xx-xcode14.1] Bump Xamarin.MacDev.

tests/linker/CommonLinkAnyTest.cs, tools/dotnet-linker/BackingFieldDelayHandler.cs
The BackingFieldDelayHandler will temporarily remove the body of Dispose
methods, and then for every field accessed in the Dispose method that was
preserved by the linker, we'll keep the corresponding code in the Dispose
method (otherwise we'd remove the code).
This is a way to remove fields that are _only_ accessed (and nulled out) in
the Dispose method.
However, we were running into a problem with determining if a field was marked
by the linker: if the field is in a generic type, and that field was not
marked by the linker, the linker might have actually removed the field from
the containing type before we're processing the Dispose methods, and we'd find
a null field definition where no null field definition was expected
(eventually resulting in an ArgumentNullException).
Fix this by …
=> [dotnet-linker] Handle null fields in BackingFieldDelayHandler as unmarked fields. Fixes #16957.

tests/cecil-tests/ObsoleteTest.cs
That's the time to fix those exceptions.
=> [tests] We don't want exceptions to the obsolete test to apply anymore in XAMCORE_5_0 in cecil-tests.

tests/cecil-tests/GenericPInvokes.cs
Improve performance in Cecil.Tests.GenericPInvokesTest by creating fewer
strings.
This saves about 1m07s seconds on my machine, from 2m10s to 1m03s, so ~52%
faster.
=> [tests] Improve performance a bit in Cecil.Tests.GenericPInvokesTest.

tests/linker/CommonLinkAnyTest.cs, tools/dotnet-linker/BackingFieldDelayHandler.cs
The BackingFieldDelayHandler will temporarily remove the body of Dispose
methods, and then for every field accessed in the Dispose method that was
preserved by the linker, we'll keep the corresponding code in the Dispose
method (otherwise we'd remove the code).
This is a way to remove fields that are _only_ accessed (and nulled out) in
the Dispose method.
However, we were running into a problem with determining if a field was marked
by the linker: if the field is in a generic type, and that field was not
marked by the linker, the linker might have actually removed the field from
the containing type before we're processing the Dispose methods, and we'd find
a null field definition where no null field definition was expected
(eventually resulting in an ArgumentNullException).
Fix this by …
=> [release/7.0.1xx] [dotnet-linker] Handle null fields in BackingFieldDelayHandler as unmarked fields. Fixes #16957.

src/Foundation/MonoTouchException.cs
Hopefully fixes this problem:
Unhandled managed exception: Failed to print exception: System.NullReferenceException: Object reference not set to an instance of an object
at Foundation.MonoTouchException.AppendNativeStackTrace (System.Text.StringBuilder sb) [0x0002f] in /Library/Frameworks/Xamarin.iOS.framework/Versions/16.0.0.72/src/Xamarin.iOS/Foundation/MonoTouchException.cs:51
at Foundation.MonoTouchException.get_Message () [0x00039] in /Library/Frameworks/Xamarin.iOS.framework/Versions/16.0.0.72/src/Xamarin.iOS/Foundation/MonoTouchException.cs:43
at ObjCRuntime.Runtime.PrintException (System.Exception exc, System.Boolean isInnerException, System.Text.StringBuilder sb) [0x0000f] in /Library/Frameworks/Xamarin.iOS.framework/Versions/16.0.0.72/src/Xamarin.iOS/ObjCRuntime/Runtime.cs:528 …
=> [xcode14.1] [Foundation] Improve null-checking in MonoTouchException.AppendNativeStackTrace.

src/Foundation/NSObject2.cs
NSObject_Disposer.Drain isn't reentry-safe, and there's a rather impressive (and not in a good way) case where this can happen: if a native dealloc method ends up processing the main thread's runloop somehow.
The fix makes the Drain function detect reentrancy, and just re-schedule a call to itself on the run loop. I believe should be safe - either the dealloc method will process the runloop again a few times, in which case we'll just re-schedule the drain call every time, until the dealloc method finishes processing the runloop, and then the next drain call will actually drain.
Fixes https://github.com/xamarin/xamarin-macios/issues/16587.
Backport of #17014.
=> [xcode14.1] [Foundation] Handle re-entrancy in NSObject_Disposer.Drain. Fixes #16587.

src/CoreMidi/MidiServices.cs
Closes #16979
The only `MidiPacket` constructor ever used internally is the one accepting an `IntPtr` argument. Therefore `bytes` will always have the default empty array value. Because of this, in the `Bytes` get accessor `bytes` is not null, but empty and indexing into `bytes` on line 848 throws the exception. The other option would have been to remove the empty array default value that was added in #15098, but the length check seemed like the safer, although maybe slightly less performant, option.
=> [CoreMidi] Fixed MidiPacket.Bytes IndexOutOfRangeException. Fixes #16979.

.github/workflows/maestro-changelog.yml
We don't need to escape newlines in the changelog message anymore, since it's
not a json-formatted string anymore, it's just plain text.
=> [actions] Fix newlines in changelog generation.

src/CoreMidi/MidiServices.cs
Closes #16979
The only `MidiPacket` constructor ever used internally is the one accepting an `IntPtr` argument. Therefore `bytes` will always have the default empty array value. Because of this, in the `Bytes` get accessor `bytes` is not null, but empty and indexing into `bytes` on line 848 throws the exception. The other option would have been to remove the empty array default value that was added in #15098, but the length check seemed like the safer, although maybe slightly less performant, option.
Backport of #16992
=> [release/7.0.1xx] [CoreMidi] Fixed MidiPacket.Bytes IndexOutOfRangeException. Fixes #16979.

src/CoreMidi/MidiServices.cs
Closes #16979
The only `MidiPacket` constructor ever used internally is the one accepting an `IntPtr` argument. Therefore `bytes` will always have the default empty array value. Because of this, in the `Bytes` get accessor `bytes` is not null, but empty and indexing into `bytes` on line 848 throws the exception. The other option would have been to remove the empty array default value that was added in #15098, but the length check seemed like the safer, although maybe slightly less performant, option.
Backport of #16992
=> [xcode14.1] [CoreMidi] Fixed MidiPacket.Bytes IndexOutOfRangeException. Fixes #16979.

src/Foundation/NSObject2.cs
NSObject_Disposer.Drain isn't reentry-safe, and there's a rather impressive
(and not in a good way) case where this can happen: if a native dealloc method
ends up processing the main thread's runloop somehow.
The fix makes the Drain function detect reentrancy, and just re-schedule a
call to itself on the run loop. I believe should be safe - either the dealloc
method will process the runloop again a few times, in which case we'll just
re-schedule the drain call every time, until the dealloc method finishes
processing the runloop, and then the next drain call will actually drain.
Fixes https://github.com/xamarin/xamarin-macios/issues/16587.
Backport of #17014.
=> [release/7.0.1xx] [Foundation] Handle re-entrancy in NSObject_Disposer.Drain. Fixes #16587.

src/CoreGraphics/CGColor.cs, src/CoreGraphics/CGColorSpace.cs, src/CoreGraphics/CGContext.cs, src/CoreGraphics/CGFunction.cs, src/CoreGraphics/CGGradient.cs, src/CoreGraphics/CGImage.cs, src/CoreGraphics/CGPath.cs, src/CoreText/CTFont.cs
manual marshaling arrays for blitability
In short, all pinvokes that took arrays have been changed pointers to the array type that we're using. Consequently, the pinvoke becomes `unsafe` and the calling code needs an `unsafe`/`fixed` block. Not as pretty, but straightforward.
This cuts out about 20 failures in the blitability pinvoke test.
=> [dotnet] handle arrays to make blittable

dotnet/targets/Xamarin.Shared.Sdk.targets
Cache the AOT compiler path, to avoid an expensive recomputation on every
build. This is even more expensive when building remotely from Windows, so
store the cached value on Windows.
Fixes https://github.com/xamarin/xamarin-macios/issues/16774.
=> [dotnet] Cache the AOT compiler path. Fixes #16774.

Make.config, tools/apidiff/Makefile
=> [release/7.0.1xx] Bump API references to the Xcode 14.1 release.

tests/cecil-tests/Makefile
Use .NET to build cecil-tests, using the appropriate verbosity, and creating a
binlog as well.
=> [tests] Use .NET to build cecil-tests.

Make.config, tools/apidiff/Makefile
=> [release/7.0.1xx-xcode14.2] Bump API references to the Xcode 14.1 release.

tests/cecil-tests/ConstructorTest.cs
This depends on #16977 being merged first.
=> [tests] Assert that we don't have any private IntPtr constructors in cecil-tests.

tests/cecil-tests/Test.cs
We had custom code with Console.WriteLine for macOS 10.12 for a while, but that was removed here:
a93bcdec341ddb3812d26b9c6acfb5c0ec2898c9
So there's no need to skip the test that verifies we don't call Console.WriteLine anymore.
=> [tests] Remove ignore due to custom code that's been gone for almost two years.

src/ObjCRuntime/TransientString.cs, src/Security/SecProtocolMetadata.cs, src/frameworks.sources
- Renamed NativeString.cs -> TransientString.cs
- Added an encoding parameter for available Marshal methods
- Added encoding in the ctor
- Handled security strings
=> [dotnet] security string pinvokes

tests/bcl-test/common-monotouch_corlib_test.dll.ignore, tests/bcl-test/macOS-xammac_net_4_5_corlib_test.dll.ignore
It looks like some timezone data has changed, so this test is now failing.
Mono will probably not be updated, so just ignore the test.
Fixes https://github.com/xamarin/maccore/issues/2629.
Backport of #16956
=> [xcode14.2] [tests] Ignore the MonoTests.System.TimeZoneInfoTest+IsDaylightSavingTimeTests.Bug_16395 test. Fixes #xamarin/maccore@2629.

dotnet/targets/Xamarin.Shared.Sdk.targets, msbuild/Xamarin.MacDev.Tasks/Tasks/FindAotCompilerTaskBase.cs
Use a more unique property name than _AOTCompiler (use _XamarinAOTCompiler
instead) to try to prevent any problems if somebody else tries to use
'_AOTCompiler' somewhere.
Ref: https://github.com/xamarin/xamarin-macios/pull/17033#discussion_r1047823981
=> [msbuild/dotnet] Use a more unique property name than _AOTCompiler.

src/CloudKit/Enums.cs
* The iOS attribute is incorrect (iOS 10.10 doesn't exist), so fix that
according to headers (should be iOS 10.0).
* When looking at the header, I realized the enum is deprecated, so fix that
too.
=> [CloudKit] Update availability attributes for CKShareParticipantType.

builds/create-csproj-for-all-packagereferences.sh, dotnet/targets/Xamarin.Shared.Sdk.targets, tests/dotnet/AppWithNativeDynamicLibrariesInPackageReference/AppDelegate.cs, tests/dotnet/AppWithNativeDynamicLibrariesInPackageReference/MacCatalyst/AppWithNativeDynamicLibrariesInPackageReference.csproj, tests/dotnet/AppWithNativeDynamicLibrariesInPackageReference/Makefile, tests/dotnet/AppWithNativeDynamicLibrariesInPackageReference/macOS/AppWithNativeDynamicLibrariesInPackageReference.csproj, tests/dotnet/AppWithNativeDynamicLibrariesInPackageReference/shared.csproj, tests/dotnet/UnitTests/ProjectTest.cs, tests/test-libraries/nugets/DynamicLibrariesInRuntimesNativeDirectory/DynamicLibrariesInRuntimesNativeDirectory.csproj, tests/test-libraries/nugets/DynamicLibrariesInRuntimesNativeDirectory/Makefile, tests/test-libraries/nugets/DynamicLibrariesInRuntimesNativeDirectory/Xamarin.Tests.DynamicLibrariesInRuntimesNativeDirectory.targets, tests/test-libraries/nugets/Makefile
Dynamic libraries might be deployed in subdirectories such as libclrjit.dylib from the nuget package cefglue.common:
Contents/MonoBundle/CefGlueBrowserProcess/libclrjit.dylib
The library ID for that library should be:
@executable_path/../MonoBundle/CefGlueBrowserProcess/libclrjit.dylib
Instead of:
@executable_path/../MonoBundle/libclrjit.dylib
Beside the library ID being wrong, when it's combined with the nuget package microsoft.netcore.app.runtime.osx-x64 providing a library with the same name, both uses the same `ReidentifiedPath`, which can cause a failure in the InstallNameTool tasks that are run in parallel operating on the same temporary file.
The following patch uses the `RelativePath` for the tempory file used by `InstallNameTool` so that there are no clashes with other files with …
=> Fix libs reidentification deployed in a subdirectory

tests/mtouch/Makefile, tests/mtouch/mtouchtests.csproj, tools/common/.gitignore, tools/common/Make.common, tools/common/ProductConstants.cs.in, tools/common/SdkVersions.cs, tools/common/SdkVersions.cs.in, tools/dotnet-linker/dotnet-linker.csproj, tools/mmp/mmp.csproj, tools/mtouch/mtouch.csproj
We need parts of tools/common/SdkVersions.cs when building tests on Windows.
In order to simplify our Windows-life, we're going to check in the generated
SdkVersions.cs file, that way it won't have to be re-generated on Windows (the
logic is very make-based, and not easily executed on Windows).
However, parts of SdkVersions.cs would change every commit, which would make
the above solution rather annoying. So split out those parts into a new file
(ProductConstants.cs), which is still generated during the build (and not
checked in).
=> [tools] Split tools/common/SdkVersions.cs in two files.

src/UIKit/UIDevice.cs
This requires the fix for https://github.com/dotnet/roslyn-analyzers/issues/6204
to be shipped in .NET 7 first. This will likely happen in .NET 7.0.200, which we'll
likely ship from main, thus I'm merging this into main.
Fixes https://github.com/xamarin/xamarin-macios/issues/16250.
=> [dotnet] Add [SupportedOSPlatformGuard] attributes to UIDevice.CheckSystemVersion. Fixes #16250.

src/MapKit/MKOverlayRenderer.cs, src/MapKit/MKOverlayView.cs, src/frameworks.sources
MKRoadWidthAtZoomScale is a P/Invoke we decided to put in the MKOverlayView
class a long time ago.
This is problematic, because the P/Invoke is available on more platforms than
MKOverlayView (and the MKOverlayView class is deprecated, while the P/Invoke
is not), which it impossible to get the availability attributes right.
So instead move the P/Invoke to the MKOverlayRenderer class (but keep the old
code around until XAMCORE_5_0 for backwards compat reasons). The
MKOverlayRenderer class is the replacement for the deprecated MKOverlayView
class, and it's also available on all the platforms the P/Invoke is available,
so the availability attributes are now trivial.
=> [MapKit] Move MKOverlayView.MKRoadWidthAtZoomScale to MKOverlayRenderer.

src/CoreGraphics/CGEnums.cs, src/Foundation/Enum.cs, src/GameKit/GameKit.cs, src/Security/Enums.cs, src/UIKit/UIEnums.cs, src/authenticationservices.cs, src/avfoundation.cs, src/cloudkit.cs, src/corebluetooth.cs, src/coredata.cs, src/coreimage.cs, src/corelocation.cs, src/corevideo.cs, src/foundation.cs, src/gamekit.cs, src/generator.cs, src/intents.cs, src/mediaplayer.cs, src/metal.cs, src/modelio.cs, src/photos.cs, src/replaykit.cs, src/security.cs, src/spritekit.cs, src/storekit.cs, src/uikit.cs, src/xkit.cs, tests/generator/BGenTests.cs
This hasn't been a problem until now because we've always had tvOS attributes on
most API, but when bumping min OS versions for .NET 8, we'll also remove a lot of
redundant availabilty attributes. This would break a case where a type is unavailable
on all platforms except tvOS (but without any tvOS availability attribute), and then
we'd get the (implied) iOS (un)availability attribute.
=> [generator] tvOS attributes aren't implied from iOS attributes.

src/Security/Items.cs, src/UIKit/NSLayoutManager.cs, src/XKit/Types.cs, src/generator-attributes.cs, src/generator.cs, tests/cecil-tests/ApiAvailabilityTest.cs
* Change the generator to not write the version in SupportedOSPlatform
attributes unless it's greater than min OS version.
* Fix a few redundant Mac Catalyst availability versions.
* Uncomment the test to verify that availability attributes don't include
useless version information.
Fixes https://github.com/xamarin/xamarin-macios/issues/11029.
=> [src/generator/tests] Verify that availability attributes don't include useless version information. Fixes #11029.

src/Foundation/Enums.cs, src/Foundation/NSAttributedStringDocumentAttributes.cs, src/generator-enums.cs, src/xkit.cs
This simplifies our code somewhat, and in XAMCORE_5_0 we can simplify even more.
Ref: https://github.com/xamarin/xamarin-macios/issues/14489
=> [Foundation] Make NSAttributedStringDocumentType a strongly-typed enum.

tests/framework-test/dotnet/shared.csproj
Fixes:
xamarin-macios/tests/framework-test/dotnet/shared.csproj(43,3): warning MSB4011: "xamarin-macios/tests/nunit.framework.targets" cannot be imported again. It was already imported at "xamarin-macios/tests/common/shared-dotnet.csproj (69,2)". This is most likely a build authoring error. This subsequent import will be ignored.
=> [tests] Remove duplicated Import to fix build warning.

src/Foundation/NSAttributedStringDocumentAttributes.cs, src/foundation.cs, src/xkit.cs
Move the remaining field in NSAttributedStringDocumentReadingOptionKeys into
NSAttributedStringDocumentReadingOptionKey to share more code, and update code
accordingly.
Also remove redundant [Internal] attributes on
NSAttributedStringDocumentReadingOptionKey fields, because the type itself is
[Internal].
This has no effect on public API, because it's all internal.
=> [Foundation] Unify NSAttributedStringDocumentReadingOptionKeys and NSAttributedStringDocumentReadingOptionKey.

src/Foundation/NSUrlSessionHandler.cs
Completely remove a workaround for an issue with the thread pool in Mono.
We've previously turned this workaround off by default, and we got no reports
of any problems.
Fixes https://github.com/xamarin/xamarin-macios/issues/7080.
=> [Foundation] Remove workaround for broken thread pool in Mono. Fixes #7080.

src/Network/NWAdvertiseDescriptor.cs, src/Network/NWBrowserDescriptor.cs, src/Network/NWConnection.cs, src/Network/NWContentContext.cs, src/Network/NWEndpoint.cs, src/Network/NWFramerMessage.cs, src/Network/NWListener.cs, src/Network/NWPrivacyContext.cs, src/Network/NWProtocolDefinition.cs, src/Network/NWProtocolFramerOptions.cs, src/Network/NWProtocolQuicOptions.cs, src/Network/NWQuicMetadata.cs, src/Network/NWTxtRecord.cs, src/Network/NWWebSocketOptions.cs, src/Network/NWWebSocketResponse.cs, src/ObjCRuntime/TransientString.cs
fix all pinvokes in the Network package that use strings
Guiding principle for this PR: be unobtrusive
This meant making the changes as minor as possible
- if the pinvoke gets called once and doesn't return `string`, change the `string` args to `IntPtr` and inline the `string` -> `TransientString` conversion.
- if the pinvoke is used in an expression method body (`public int SomeFunc (string s) => SomePInvoke (s);`), then I wrote a wrapper function for it that keeps the original signature
- if the function returns a string, I renamed the pinvoke with `Ptr` or `_ptr` on the end, changed it to return `IntPtr`, then wrote an adapter that uses calls is, allocates a new string and frees the original using `TransientString.ToStringAndFree`
=> [dotnet] blitable network pinvokes

src/CoreGraphics/CGContext.cs, src/CoreGraphics/CGDataProvider.cs, src/CoreGraphics/CGPDFContentStream.cs, src/CoreGraphics/CGPDFDictionary.cs, src/CoreGraphics/CGPDFDocument.cs, src/CoreGraphics/CGPDFOperatorTable.cs
converted all pinvokes in CoreGraphics to use `IntPtr` instead of `string`.
=> [dotnet] CoreGraphics convert strings in pinvokes

src/xkit.cs
NSCocoaVersionDocumentAttribute has always been available on macOS.
=> [XKit] Remove incorrect availability attribute.

tests/common/shared-dotnet.csproj, tests/common/shared-dotnet.mk
Make the helper makefiles for .NET tests more helpful by adding support for
universal apps, and also document the most relevant targets.
=> [tests] Make the helper makefiles for .NET tests more helpful.

src/CoreFoundation/CFMutableString.cs, src/CoreFoundation/CFString.cs, src/CoreFoundation/Dispatch.cs, src/CoreFoundation/DispatchSource.cs, src/CoreFoundation/OSLog.cs
sanitized the pinvokes that use string.
Note: I did *not* address the pinvokes that take callback functions - that will be addressed in a later PR.
=> [dotnet] sanitized pinvokes that use string

eng/Versions.props, tests/xtro-sharpie/Makefile, tests/xtro-sharpie/Program.cs, tests/xtro-sharpie/Runner.cs, tests/xtro-sharpie/xtro-sharpie.csproj
Add support to xtro-sharpie for where to look for referenced assemblies, and
adjust assembly resolution to only look in those directories.
This makes sure xtro-sharpie loads the expected references, and fixes a
problem where the (broken) assembly resolution wouldn't find a .NET assembly
because it doesn't exist in legacy Xamarin (where it would look by default).
Fixes this problem that showed up in a different PR (due to new .NET API
referencing the System.Runtime.Loader assembly, which doesn't exist in legacy
Xamarin):
mono64 --debug bin/Debug/xtro-sharpie.exe --output-directory api-annotations-dotnet appletvos16.1-arm64.pch ../../_build/Microsoft.tvOS.Runtime.tvos-arm64/runtimes/tvos-arm64/lib/net7.0/Microsoft.tvOS.dll
Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: …
=> [xtro] Improve assembly resolution to not load incorrect assemblies.

msbuild/Xamarin.MacDev.Tasks/Xamarin.MacDev.Tasks.csproj
Fixes:
> CSC : warning CS2002: Source file 'xamarin-macios/msbuild/Xamarin.MacDev.Tasks/Errors.designer.cs' specified multiple times
=> [msbuild] Fix a compile warning about file being added twice.

msbuild/Xamarin.Mac.Tasks/Tasks/Mmp.cs, msbuild/Xamarin.Mac.Tasks/Tasks/MmpTaskBase.cs
We no longer need two have overridable logic for remote builds, so the
non-abstract task class and the abstract base class can be merged.
First out is the Mmp task.
=> [msbuild] Merge the Mmp and MmpTaskBase classes.

tests/monotouch-test/Network/NWPathMonitorTest.cs
Otherwise the process may crash later on:
apitest.KernelNotificationTest
=================================================================
Native Crash Reporting
=================================================================
Got a term while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================
=================================================================
Native stacktrace:
=================================================================
0x1050093d6 - /Users/rolf/work/maccore/msbuild/xamarin-macios/tests/xammac_tests/bin/x86/Debug/xammac_tests.app/Contents/MacOS/xammac_tests : mono_dump_native_crash_info
0x104ffcf3e - …
=> [tests] NWPathMonitors must be cancelled.

tools/devops/automation/templates/sign-and-notarized/funnel.yml, tools/devops/automation/templates/sign-and-notarized/upload-azure.yml
We have noticed that the azure upload steps fail when they are executed in a on prem windows machine. The infra team does not know what this is happening. To work around it we are taking the following stes:
- Move the upload to a hosted image, which does work.
- Donot download all artefacts, since hosted images only have a 10 gb hdd. We download all but the not needed files using negative match patterns.
=> [CI] Move the upload to a hosted image.

Make.config
This is necessary because Xcode 14.2 does not ship with an updated SDK for
tvOS, which means that the MSI for tvOS from this branch needs to have a
higher version numer than the tvOS MSI from the release/7.0.1xx-xcode14.1
branch - and that's accomplished by hardcoding a starting point.
Should fix this error:
> ##[error]VALIDATEMANIFEST : error : PackageDiffVersionsAreMonotonicallyIncreasing failed : Package versions should never decrease (16.1.3.0 is less than the baseline version 16.1.21.0). : [manifest=VisualStudioPreview/17.5.0-pre.3.0+33305.110.main][item=tvos,version=16.1.3.0]
=> [release/7.0.1xx-xcode14.2] Bump the hardcoded start for the MSI stable commit distance calculation.

src/CFNetwork/CFHTTPMessage.cs, src/CFNetwork/Content.cs, src/CFNetwork/MessageHandler.cs, src/CFNetwork/WebRequestStream.cs, src/CFNetwork/WebResponseStream.cs, src/CFNetwork/WorkerThread.cs
Add nullability to the files. Although this files won't be present in the new dotnet versions, it is good to add them for classic. Also, if we move all files to have nullability enabled we should be able to pass it as a flag and remove the need to use '#nullable enable' which people can forget.
=> [CFNetwork] Add nullability to forgotten files.

tests/bgen/bgen-tests.csproj, tests/dotnet/UnitTests/DotNetUnitTests.csproj, tests/generator/generator-tests.csproj, tests/mmptest/mmptest.csproj, tests/msbuild/Xamarin.MacDev.Tests/Xamarin.MacDev.Tests.csproj, tests/mtouch/mtouchtests.csproj
To get new log format:
> System.NotSupportedException : Unsupported log file format. Latest supported version is 14, the log file has version 15.
=> Bump to MSBuild.StructuredLogger v2.1.758.

tests/bgen/bgen-tests.csproj, tests/dotnet/UnitTests/DotNetUnitTests.csproj, tests/generator/generator-tests.csproj, tests/mmptest/mmptest.csproj, tests/msbuild/Xamarin.MacDev.Tests/Xamarin.MacDev.Tests.csproj, tests/mtouch/mtouchtests.csproj
To get new log format:
> System.NotSupportedException : Unsupported log file format. Latest supported version is 14, the log file has version 15.
Backport of #17229
=> [release/7.0.2xx] Bump to MSBuild.StructuredLogger v2.1.758.

src/foundation.cs
But we can't just remove it, so obsolete it until we can.
=> [Foundation] [NSTask launchedTaskWithLaunchPath:arguments:] is not available on Mac Catalyst.

src/AudioUnit/AUEnums.cs
Mark this field as obsolete on Mac Catalyst to match iOS, but also completely
remove it in XAMCORE_5_0, since I can't find it in the headers anymore
anyways.
=> [AudioUnit] Make AudioUnitParameterType.AUDCFilterDecayTime obsolete on Mac Catalyst.

dotnet/targets/Xamarin.Shared.Sdk.props
=> [dotnet] Ensure any trimmer components are restored properly.

msbuild/Xamarin.Shared/Xamarin.Shared.targets
Fixes #16377 
MSbuild has the ability to run `Target` partially. However in order to make sure we can use this, both the `Inputs` and `Outputs` need to have a 1-1 mapping. MSBuild will then use this mapping to figure out which files have actually changed.
Then it will call the Target with only those files. 
In Xamarin.Android we make use of stamp files to provide this 1-1 mapping. We have a `pre` Target which will calculate an ItemGroup which will include a StampFile piece of metadata. We then use this new ItemGroup for both the `Inputs` and `Outputs`, thus meeting the 1-1 requirement. 
This PR updates the `_UnpackLibraryResources` to run partially. This will hopefully reduce the build time on incremental builds. 
Backport of #16416
=> [release/7.0.2xx] [msbuild] Don't process assemblies over and over again in the UnpackLibraryResources target. Fixes #16377.

dotnet/targets/Xamarin.Shared.Sdk.props
=> [release/7.0.2xx] [dotnet] Ensure any trimmer components are restored properly.

dotnet/targets/Xamarin.Shared.Sdk.props
=> [release/7.0.1xx-xcode14.2] [dotnet] Ensure any trimmer components are restored properly.

dotnet/targets/Xamarin.Shared.Sdk.props
=> [release/6.0.4xx-xcode14.2] [dotnet] Ensure any trimmer components are restored properly.

dotnet/targets/Xamarin.Shared.Sdk.props
=> [release/6.0.4xx] [dotnet] Ensure any trimmer components are restored properly.

dotnet/targets/Xamarin.Shared.Sdk.props
=> [release/7.0.1xx] [dotnet] Ensure any trimmer components are restored properly.

dotnet/targets/Xamarin.Shared.Sdk.props
=> [release/6.0.4xx-xcode14.1] [dotnet] Ensure any trimmer components are restored properly.

src/generator.cs, tests/generator/BGenTests.cs, tests/generator/BGenTool.cs, tests/generator/tests/no-availability-for-accessors.cs
Previously API definitions like this:
string Property {
get;
[NoiOS]
set;
}
would generate a setter for every platform, even iOS.
This is rather unexpected, so fix the generator to honor No* attributes on
property getters and setters.
=> [generator] Don't generate accessors with No* availability attributes on them.

tests/dotnet/Net6_0SimpleApp/MacCatalyst/Net6_0SimpleApp.csproj, tests/dotnet/Net6_0SimpleApp/iOS/Net6_0SimpleApp.csproj, tests/dotnet/Net6_0SimpleApp/macOS/Net6_0SimpleApp.csproj, tests/dotnet/Net6_0SimpleApp/tvOS/Net6_0SimpleApp.csproj
.NET 6 doesn't define the minimum supported OS version property, which means
we can't use the existing logic to automatically determine the min OS version
to use as the default SupportedOSPlatformVersion in the .NET 6, so hardcode
the value.
=> [tests] Hardcode the SupportedOSPlatformVersion for the .NET 6 tests.

builds/create-csproj-for-all-packagereferences.sh, dotnet/targets/Xamarin.Shared.Sdk.targets, tests/dotnet/AppWithNativeDynamicLibrariesInPackageReference/AppDelegate.cs, tests/dotnet/AppWithNativeDynamicLibrariesInPackageReference/MacCatalyst/AppWithNativeDynamicLibrariesInPackageReference.csproj, tests/dotnet/AppWithNativeDynamicLibrariesInPackageReference/Makefile, tests/dotnet/AppWithNativeDynamicLibrariesInPackageReference/macOS/AppWithNativeDynamicLibrariesInPackageReference.csproj, tests/dotnet/AppWithNativeDynamicLibrariesInPackageReference/shared.csproj, tests/dotnet/UnitTests/ProjectTest.cs, tests/test-libraries/nugets/DynamicLibrariesInRuntimesNativeDirectory/DynamicLibrariesInRuntimesNativeDirectory.csproj, tests/test-libraries/nugets/DynamicLibrariesInRuntimesNativeDirectory/Makefile, tests/test-libraries/nugets/DynamicLibrariesInRuntimesNativeDirectory/Xamarin.Tests.DynamicLibrariesInRuntimesNativeDirectory.targets, tests/test-libraries/nugets/Makefile
Dynamic libraries might be deployed in subdirectories such as libclrjit.dylib from the nuget package cefglue.common:
Contents/MonoBundle/CefGlueBrowserProcess/libclrjit.dylib
The library ID for that library should be:
@executable_path/../MonoBundle/CefGlueBrowserProcess/libclrjit.dylib
Instead of:
@executable_path/../MonoBundle/libclrjit.dylib
Beside the library ID being wrong, when it's combined with the nuget package microsoft.netcore.app.runtime.osx-x64 providing a library with the same name, both uses the same `ReidentifiedPath`, which can cause a failure in the InstallNameTool tasks that are run in parallel operating on the same temporary file.
The following patch uses the `RelativePath` for the tempory file used by `InstallNameTool` so that there are no clashes with other files with …
=> [release/7.0.2xx] Fix libs reidentification deployed in a subdirectory

src/AppKit/NSWindow.cs, src/appkit.cs, tests/cecil-tests/ConstructorTest.cs, tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.ignore
This simplifies our manual bindings a little bit.
=> [AppKit] Bind an NSWindow(IntPtr) constructor in the API definition.

.github/fabricbot.json
New workflows:
1. When a `move-to-vs-feedback` label is applied to an issue, tell the user to use the VS Feedback tool instead.
2. If issue is commented on within 3 days, mark as `needs-attention`.
3. If issue is inactive for 3 days, close the issue.
This is a shameless copy of https://github.com/dotnet/maui/commit/05c5e202a367b966f1dab542e988f40a07d8eeb1.
=> [fabricbot] Add bot rule to manage 'move-to-vs-feedback' issues

.github/fabricbot.json, docs/bug-repro.md
Handle the 'need-repro' label like the 'need-info' label:
* Add a comment that we need a repro, and how to get one.
* Close the issue if no comments within 7 days.
* Add a 'need-attention' label if reporter comments.
Also add a document explaining how to create a repro, modeled after (copied)
MAUI's document (https://github.com/dotnet/maui/blob/main/.github/repro.md).
=> [fabricbot] Handle the 'need-repro' label.

src/generator.cs, tests/common/Configuration.cs, tests/common/Profile.cs, tests/generator/BGenTests.cs, tests/generator/BGenTool.cs, tests/generator/tests/attributes-from-inlined-protocols.cs
In the following scenario:
* Type T is not available on a platform (say tvOS).
* Protocol P is available on said platform.
* A member M of P has its own availability attribute for said platform (for
instance if P is available on tvOS 11.0, and the member is available on tvOS
12.0).
* The protocol P is inlined into the type T.
We'd include the SupportedOSPlatform attribute from the inlined member on
generated code on other platforms (so the iOS assembly would say that the
inlined member M in T is available on tvOS).
Fixes https://github.com/xamarin/xamarin-macios/issues/17268.
=> [generator] Fix an issue with regards to attributes from inlined protocols. Fixes #17268.

tools/common/Frameworks.cs
Apple provides the headers to target PushToTalk (so using PushToTalk in code
builds just fine for the simulator in Xcode), but it doesn't work at runtime.
I believe it's better to allow the same thing in our bindings, for two reasons:
* Apple prints out a helpful error message at runtime, instead of our rather
incomprehensible build error.
* Apple might implement simulator support in the future, in which case we
won't need to do anything else.
=> [tools] Enable the PushToTalk framework in the simulator.

src/AudioUnit/AUEnums.cs
The ifdefs here were confusing, so I cleaned them up a bit.
Note that No* attributes in enum members won't prevent the enum members from
being generated, they'll just get an unavailable attribute, so adding No*
attributes to an enum member is not a breaking change (which allows for some
of this cleanup).
Contributes towards #14802.
=> [AudioUnit] Cleanup ifdefs in AUEnums.

msbuild/Makefile, msbuild/Messaging/Xamarin.Messaging.Build/Xamarin.Messaging.Build.csproj
Mono has a networking bug that NuGet often triggers, leading to build failures like this:
[...]
GET https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/825db618-e3eb-4426-ba54-b1d6e6c944d8/nuget/v3/flat2/system.threading.tasks.extensions/index.json
GET https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/49e5305d-d845-4a14-9d69-6f5dbfb9570c/nuget/v3/flat2/system.threading.tasks.extensions/index.json
GET https://pkgs.dev.azure.com/xamarin/6fd3d886-57a5-4e31-8db7-52a1b47c07a8/_packaging/bcd6855c-070e-4cb7-a698-ac197b93cd87/nuget/v3/flat2/system.threading.tasks.extensions/index.json
NotFound https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/9d6ecda8-a4ca-4c13-8c0c-939b925b1f31/nuget/v3/flat2/system.runt …
=> [release/7.0.1xx] [msbuild] Build the solution using .NET instead of msbuild.

msbuild/Makefile, msbuild/Messaging/Xamarin.Messaging.Build/Xamarin.Messaging.Build.csproj
Mono has a networking bug that NuGet often triggers, leading to build failures like this:
[...]
GET https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/825db618-e3eb-4426-ba54-b1d6e6c944d8/nuget/v3/flat2/system.threading.tasks.extensions/index.json
GET https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/49e5305d-d845-4a14-9d69-6f5dbfb9570c/nuget/v3/flat2/system.threading.tasks.extensions/index.json
GET https://pkgs.dev.azure.com/xamarin/6fd3d886-57a5-4e31-8db7-52a1b47c07a8/_packaging/bcd6855c-070e-4cb7-a698-ac197b93cd87/nuget/v3/flat2/system.threading.tasks.extensions/index.json
NotFound https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/9d6ecda8-a4ca-4c13-8c0c-939b925b1f31/nuget/v3/flat2/system.runt …
=> [release/7.0.1xx-xcode14.2] [msbuild] Build the solution using .NET instead of msbuild.

msbuild/Makefile, msbuild/Messaging/Xamarin.Messaging.Build/Xamarin.Messaging.Build.csproj
Mono has a networking bug that NuGet often triggers, leading to build failures like this:
[...]
GET https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/825db618-e3eb-4426-ba54-b1d6e6c944d8/nuget/v3/flat2/system.threading.tasks.extensions/index.json
GET https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/49e5305d-d845-4a14-9d69-6f5dbfb9570c/nuget/v3/flat2/system.threading.tasks.extensions/index.json
GET https://pkgs.dev.azure.com/xamarin/6fd3d886-57a5-4e31-8db7-52a1b47c07a8/_packaging/bcd6855c-070e-4cb7-a698-ac197b93cd87/nuget/v3/flat2/system.threading.tasks.extensions/index.json
NotFound https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/9d6ecda8-a4ca-4c13-8c0c-939b925b1f31/nuget/v3/flat2/system.runt …
=> [release/7.0.2xx] [msbuild] Build the solution using .NET instead of msbuild.

msbuild/Makefile, msbuild/Messaging/Xamarin.Messaging.Build/Xamarin.Messaging.Build.csproj
Mono has a networking bug that NuGet often triggers, leading to build failures like this:
[...]
GET https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/825db618-e3eb-4426-ba54-b1d6e6c944d8/nuget/v3/flat2/system.threading.tasks.extensions/index.json
GET https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/49e5305d-d845-4a14-9d69-6f5dbfb9570c/nuget/v3/flat2/system.threading.tasks.extensions/index.json
GET https://pkgs.dev.azure.com/xamarin/6fd3d886-57a5-4e31-8db7-52a1b47c07a8/_packaging/bcd6855c-070e-4cb7-a698-ac197b93cd87/nuget/v3/flat2/system.threading.tasks.extensions/index.json
NotFound https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/9d6ecda8-a4ca-4c13-8c0c-939b925b1f31/nuget/v3/flat2/system.runt …
=> [release/6.0.4xx-xcode14.2] [msbuild] Build the solution using .NET instead of msbuild.

src/foundation.cs
Since it doesn't work anyway, there's no reason to show it.
=> [Foundation] Hide NSTask.LaunchFromPath from intellisense for Mac Catalyst.

src/AudioUnit/AudioComponent.cs
According to the compilation compilation directives, these two APIs are only
available on macOS, so update the availability attributes accordingly.
=> [AudioUnit] Adjust availability attributes according to conditional compilation directives.

src/gamekit.cs
So that all platforms know which other platforms the API is available on.
=> [GameKit] Move availability attributes out of conditional code.

src/foundation.cs
This ensures that all platform assemblies know that the member doesn't exist
on macOS.
=> [Foundation] There's no reason to conditionally exclude code for macOS when the member has a NoMac attribute.

src/mediaplayer.cs
The API for MPMediaItem/MPMediaEntity varies wildly between platforms (for
historical reasons), so move availability attributes around a bit so that they
match reality a bit better: MPMediaEntity is not available on macOS, only
MPMediaItem is.
=> [MediaPlayer] Adjust availability attributes for MPMediaItem/MPMediaEntity.

src/NearbyInteraction/NICompat.cs, src/nearbyinteraction.cs
ARKit is in a weird spot on Mac Catalyst: it exists, but it doesn't do
anything. Since it doesn't actually work, we don't have bindings for ARKit.
This means that while the method '[NISession setARSession:]' technically
exists on Mac Catalyst, we can't bind it properly, since the type of the
parameter (ARSession) isn't available in our bindings for Mac Catalyst.
Due to how we hack around the lack of ARSession in our source code, we ended
up binding the method with an NSObject argument instead. This is still wrong,
so here I'm removing that method from the API.
But of course, removing that API is a breaking change, so until then the
method is obsoleted and hidden, and only removed in XAMCORE_5_0.
Also hide a few other obsoleted API in NISession, and remove those as well in
XAMCORE_5_0.
=> [NearbyInteraction] Remove NISession.SetARSession from Mac Catalyst.

tests/packaged-macos-tests.mk
I've started seeing more random network delays on these tests recently - which
the tests themselves handle, but the test run ends up taking much longer, and
we need to give the test run more time to finish.
=> [tests] Bump the timeout to 10min for monotouch-test/xammac_tests on older macOS bots.

src/healthkit.cs
There's no trace of this in the headers, so I assume it's something that
happened in a beta and then got removed, and we didn't notice to update our
bindings.
=> [HealthKit] Remove HKSeriesBuilder compliance of NSSecureCoding.

system-dependencies.sh
=> [release/7.0.1xx] [system-dependencies] Add diagnostics for duplicate sim download error.

system-dependencies.sh
=> [release/7.0.1xx-xcode14.2] [system-dependencies] Add diagnostics for duplicate sim download error.

system-dependencies.sh
=> [release/7.0.2xx] [system-dependencies] Add diagnostics for duplicate sim download error.

system-dependencies.sh
=> [release/6.0.4xx-xcode14.1] [system-dependencies] Add diagnostics for duplicate sim download error.

system-dependencies.sh
=> [release/6.0.4xx-xcode14.2] [system-dependencies] Add diagnostics for duplicate sim download error.

src/CoreText/CTFontCollection.cs, src/CoreText/CTFontDescriptor.cs, src/CoreText/CTRunDelegate.cs
For these set of changes, I'm converting a delegate type to `delegate* unmanaged<....>` and where necessary adding in the `[UnmanagedCallersOnly]` attribute.
=> [dotnet] CoreFont delegates

tools/common/Make.common
Try to fix #xamarin/maccore@2637 by making sure a file's timestamp changes
after make runs the corresponding target.
Otherwise it seems make may run into some sort of infinite loop.
Ref: https://github.com/xamarin/maccore/issues/2637
=> [tools] Try to fix #xamarin/maccore@2637 by making sure a file's timestamp changes.

dotnet/targets/Xamarin.Shared.Sdk.targets
The bug manifests like this:
> Could not create an native instance of the type WindowsAzure.Messaging.SBNotificationHub: the native class hasn't been loaded.
which happens because the SBNotificationHub doesn't exist in the final
executable. We asked the linker to link with the static library containing
this type, but the linker didn't link with the library because it didn't need
any of the symbols in it.
We should have collected all the exported Objective-C types from this library
and asked the native linker to keep them, but that didn't happen because:
1. We collect bound Objective-C classes from binding libraries here (the
ListExportedSymbolsStep): https://github.com/xamarin/xamarin-macios/blob/608765e2c9e474c494958844a94354f90fa42f36/tools/linker/MonoTouch.Tuner/ListExportedSymbols.cs#L …
=> [dotnet] Change the order of the linker steps. Fixes #17347.

msbuild/Directory.Build.props
=> Updated Xamarin.Messaging to 1.9.5

msbuild/Directory.Build.props
=> [release/6.0.4xx-xcode14.2] Updated Xamarin.Messaging to 1.9.5

tests/cecil-tests/AttributeTest.cs, tests/cecil-tests/ObsoleteTest.cs
* Fix an issue where it would not compute the correct grouping key for each member,
effectively grouping unrelated members together and coming up with weird and incorrect
results.
* Make it match failures exactly, which makes it possible to detect (and report,
which it now does) when a known failure is fixed.
* Ignore any hidden members (EditorBrowsableState.Never), because they're most
likely mistakes.
* Ignore any members in AppKit and UIKit, because these namespaces have a lot of
conflicting availability attributes. This is tracked in a separate bug (#17292).
=> [tests] Improve the AttributeTest.FindSupportedOnElementsThatDoNotExistInThatAssembly cecil test.

msbuild/Directory.Build.props
=> [release/7.0.1xx-xcode14.2] Updated Xamarin.Messaging to 1.9.5

msbuild/Directory.Build.props
=> [xcode14.2] Updated Xamarin.Messaging to 1.9.5

msbuild/Directory.Build.props
=> [release/7.0.2xx] Updated Xamarin.Messaging to 1.9.5

msbuild/Directory.Build.props
=> [release/7.0.1xx] Updated Xamarin.Messaging to 1.9.5

src/Foundation/Enum.cs
It's a [Flags] enum, so it makes sense to have an option to have no flags.
=> [Foundation] Add a 'None' option to NSKeyValueObservingOptions.

tools/common/Assembly.cs
We used to show this:
> ILLINK warning MT1302: Could not extract the native library 'StaticLibrary.a' from '~/Downloads/BindingTest/obj/Debug/net7.0-ios/iossimulator-x64/linker-cache/StaticLibrary.a'. Please ensure the native library was properly embedded in the managed assembly (if the assembly was built using a binding project, the native library must be included in the project, and its Build Action must be 'ObjcBindingNativeLibrary').
now we show the assembly:
> ILLINK warning MT1302: Could not extract the native library 'StaticLibrary.a' from '~/Downloads/BindingTest/obj/Debug/net7.0-ios/iossimulator-x64/linker-cache/BindingLibrary.dll'. Please ensure the native library was properly embedded in the managed assembly (if the assembly was built using a binding project, the native library …
=> [tools] Fix MT1302 to show the correct path to the assembly.
