dotnet/macios

- tests/HtmlTransform.xslt
Should fix this test error:
```
warning: failed to load external entity "../../xamarin-macios/tests/HtmlTransform.xslt"
cannot parse ../../xamarin-macios/tests/HtmlTransform.xslt
make[4]: *** [test-ios-tasks] Error 4
```
> [tests] Move HtmlTransform.xslt here from maccore.

- msbuild/Xamarin.Mac.Tasks/Tasks/CompileAppManifest.cs
- msbuild/Xamarin.Mac.Tasks/Tasks/Mmp.cs
- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.AppExtension.CSharp.targets
- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.AppExtension.Common.props
- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.AppExtension.Common.targets
- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.props
- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Tasks.csproj
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CodesignTaskBase.cs
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileAppManifestTaskBase.cs
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/IBToolTaskBase.cs
- msbuild/Xamarin.iOS.Tasks.Core/Tasks/CompileAppManifestTaskBase.cs
- runtime/Makefile
- runtime/launcher.m
- runtime/libxammac.csproj
- runtime/main-internal.h
- runtime/runtime-internal.h
- runtime/runtime.m
- src/FinderSync/Enums.cs
- src/NotificationCenter/NCEnums.cs
- src/appkit.cs
- src/findersync.cs
- src/foundation.cs
- src/frameworks.sources
- src/notificationcenter.cs
- tools/mmp/driver.cs
Reviewed here - https://github.com/xamarin/xamarin-macios/pull/76
> [Mac] Add support for os x extensions

- builds/Makefile
- configure
- runtime/COOP.md
- runtime/README.md
- runtime/delegates.t4
- runtime/exports.t4
- runtime/monotouch-debug.m
- runtime/monotouch-main.m
- runtime/runtime.m
- runtime/shared.m
- runtime/trampolines-invoke.m
- runtime/trampolines-x86_64.m
- runtime/trampolines.m
- runtime/xamarin-support.m
- runtime/xamarin/runtime.h
- src/Foundation/NSObject.iOS.cs
- src/Foundation/NSObject.mac.cs
- src/Foundation/NSObject2.cs
- src/MonoTouch.Dialog-1.templ.csproj
- src/MonoTouch.Dialog-1.tvos.templ.csproj
- src/MonoTouch.Dialog-1.unified.templ.csproj
- src/MonoTouch.NUnitLite.templ.csproj
- src/MonoTouch.NUnitLite.tvos.templ.csproj
- src/MonoTouch.NUnitLite.unified.templ.csproj
- src/MonoTouch.NUnitLite.watchos.templ.csproj
- src/ObjCRuntime/Runtime.cs
- tools/common/StaticRegistrar.cs
- tools/mtouch/Application.cs
- tools/mtouch/Makefile
- tools/mtouch/Target.cs
This has been run on wrench: https://wrench.internalx.com/Wrench/ViewLane.aspx?lane_id=3278&host_id=243&revision_id=767129, and fails exactly like master currently does.
> Add support for the GC in cooperative mode.

- mk/xamarin.mk
It ends up in an infinite loop of submakes.
> [mk] Don't use sub-make to clone maccore.

- tests/mtouch/MTouch.cs
- tools/mtouch/Application.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=40606
> [mtouch] Tweak error message for MT0073 and MT0074. Fixes #40606.

- msbuild/Xamarin.Mac.Tasks/Tasks/IBTool.cs
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/IBToolTaskBase.cs
- msbuild/Xamarin.iOS.Tasks.Core/Tasks/IBToolTaskBase.cs
> [msbuild] Make Mac IBTool logic consistent with iOS logic

- runtime/Delegates.cs.t4
- runtime/EXCEPTIONS.md
- runtime/delegates.t4
- runtime/exports.t4
- runtime/mono-runtime.h.t4
- runtime/monotouch-main.m
- runtime/runtime-internal.h
- runtime/runtime.m
- runtime/trampolines-i386.m
- runtime/trampolines-internal.h
- runtime/trampolines-invoke.m
- runtime/trampolines-varargs.m
- runtime/trampolines-x86_64.m
- runtime/trampolines.m
- runtime/xamarin/runtime.h
- src/ObjCRuntime/Runtime.cs
- tools/common/StaticRegistrar.cs
- tools/mtouch/OldStaticRegistrar.cs
- tools/mtouch/mtouch.cs
There's a wrench lane for this: https://wrench.internalx.com/Wrench/ViewTable.aspx?lane_id=3392&host_id=243
> Handle any exceptions when returning from managed code back to our native runtime.

- src/AudioUnit/AUParameter.cs
- src/AudioUnit/AUParameterNode.cs
- src/AudioUnit/AudioUnit.cs
- src/audiounit.cs
- tests/monotouch-test/AudioUnit/AUParameterNodeTest.cs
commit 1f207bd3f3df363cb5a74e59b93acd8eb6e1fec2 in xamarin/maccore
introduced some breaking changes, this fixes them
> [AudioUnit] Fix some breaking changes

- src/appkit.cs
Add NSAccessibilityElement as a class and rename the NSAccessibilityElement protocol to NSAccessibilityElementProtocol to match Swift
> XM] Add NSAccessibilityElement as a class

- src/NativeTypes/Drawing.tt
- tests/monotouch-test/CoreGraphics/RectTest.cs
- tests/monotouch-test/monotouch-test.csproj
https://bugzilla.xamarin.com/show_bug.cgi?id=41684
> [CoreGraphics] Fix CGRect.Inflate to work correctly, and add tests. Fixes #41684.

- src/UIKit/NSLayoutConstraint.cs
- src/UIKit/UIApplication.cs
- src/UIKit/UIEnums.cs
- src/UIKit/UIFont.cs
- src/UIKit/UITraitCollection.cs
- src/WatchKit/WKInterfaceDevice.cs
- src/frameworks.sources
- src/uikit.cs
Of note: NSLayoutConstraints.cs provides the generic methods, as the
generator currently does not know how to either annotate generic
return types (necesary to build), nor does it have "where" support.
UITraitCollection - re-indented to follow the tab convention.
> [Review][iOS10,UIKit] Small API introductions.

- src/CallKit/CXProvider.cs
- src/Constants.iOS.cs.in
- src/callkit.cs
- src/frameworks.sources
- tests/introspection/ApiTypoTest.cs
- tests/introspection/iOS/iOSApiProtocolTest.cs
- tools/common/Frameworks.cs
- tools/mtouch/Makefile
FIXME: This Api is supposed to be available on macOS 10.12
per apple headers but it uses types that are only available
in iOS filled radar://26786260 with apple
https://trello.com/c/afWXDZ3A
> [CallKit] Add CallKit framework iOS beta 1

- src/Constants.iOS.cs.in
- src/frameworks.sources
- src/speech.cs
- tools/common/Frameworks.cs
- tools/mtouch/Makefile
FIXME: `SFSpeechRecordingRecognitionRequest` is not in the public api
filled radar://26799291 https://trello.com/c/s6s6YKua
> [Speech] Add Speech Framework from Xcode 8 Beta 1

- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.XM45.targets
- tests/mmptest/src/MMPTest.cs
- Centralize fix I made for XM 4.5 to apply to both and write larger test
- https://bugzilla.xamarin.com/show_bug.cgi?id=42001
> [XM] - XM Mobile should not resolve from the GAC either

- src/Constants.iOS.cs.in
- src/frameworks.sources
- src/messages.cs
- tests/introspection/ApiTypoTest.cs
- tests/introspection/iOS/iOSApiProtocolTest.cs
- tests/monotouch-test/Messages/MSMessageTest.cs
- tests/monotouch-test/monotouch-test.csproj
- tools/common/Frameworks.cs
- tools/mtouch/Makefile
_Note: I could not build because of https://bugzilla.xamarin.com/show_bug.cgi?id=41786. This PR is for review only._
> [messages] New framework in iOS 10.0 beta1

- tests/monotouch-test/AddressBookUI/AddressFormattingTest.cs
- tests/monotouch-test/Contacts/MutableContactTest.cs
- tests/monotouch-test/ImageIO/ImageMetadataTagTest.cs
- tests/monotouch-test/QuickLook/PreviewControllerTest.cs
- tests/monotouch-test/Security/SecureTransportTest.cs
- tests/monotouch-test/Security/TrustTest.cs
- tests/monotouch-test/SystemConfiguration/NetworkReachabilityTest.cs
- some might be Apple bugs and need to be reverted later
> [tests][monotouch] More adjustments for iOS10 related failures/changes

- src/contacts.cs
- src/foundation.cs
- src/gameplaykit.cs
- src/modelio.cs
- src/networkextension.cs
- src/wkwebkit.cs
- tests/introspection/ApiProtocolTest.cs
- tests/introspection/iOS/iOSApiProtocolTest.cs
- tests/monotouch-test/ModelIO/MDLMaterialProperty.cs
- Added missing NSCopying, NSCoding and NSSecureCoding.
- Filled radar://26939747 with Apple - https://trello.com/c/6aIzLH4a
> [introspection] Fix bindings so the tests pass

- src/cloudkit.cs
This fixes bugs:
* https://bugzilla.xamarin.com/show_bug.cgi?id=42163
* https://bugzilla.xamarin.com/show_bug.cgi?id=42125
> [CloudKit] Fix bugs 42125 and 42163, a couple of missing NullAlloweds

- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
> [msbuild] Allow customization of IPA package directory & path

- src/iAd/iAd.cs
- src/iad.cs
Also add missing [ErrorDomain] for ADClientErrorDomain
> [iAd] Add deprecations for iOS 10 beta 1

- tools/common/MachO.cs
- tools/mtouch/Application.cs
- tools/mtouch/Makefile
- tools/mtouch/mtouch.csproj
This is WIP. We are reenabling the symbolication and updating its output to the new definition.
> [Fix] Reenable the symbolication to allow debugging and update its implementation.

- runtime/monotouch-debug.m
Don't call any COOP macros when configuring the debugger/profiler.
This occurs before the root domain has been created, which means
that the current thread can't be attached.
Since the COOP macros assert that the thread is attached,
we end up aborting:
Jun 29 13:35:56 Rolfs-Mac-Pro monotouchtest[97569]: Cannot enter GC safe region if the thread is not attached
Thread 2 Crashed:
0   libsystem_kernel.dylib        	0x08753572 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x0871b654 pthread_kill + 101
2   libsystem_c.dylib             	0x084a962d abort + 156
3   com.xamarin.monotouch-test.watchkitapp.watchkitextension	0x0033901f monoeg_log_default_handler + 159
4   com.xamarin.monotouch-test.watchkitapp.watchkitextension	0x00339087 monoeg_g_log + 103 (goutput.c:114)
5 …
> [runtime] Fix watchOS debugging.

- tests/linker-ios/link sdk/AsyncTest.cs
- tests/linker-ios/link sdk/CryptoTest.cs
- tests/linker-ios/link sdk/LinkSdkRegressionTest.cs
- tests/linker-ios/link sdk/PclTest.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=41538
> [link sdk] Update tests to work on watchOS. Fixes #41538.

- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
> [msbuild] Replaced uses of $(_IpaOutputDir) with $(IpaPackageDir)

- tools/mtouch/mtouch.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=41666
> [mtouch] Make sure to reference mono_profiler_startup_log so that the native linker doesn't remove the symbol. Fixes #41666.

- src/Constants.iOS.cs.in
- src/Constants.tvos.cs.in
- src/Constants.watch.cs.in
- src/Foundation/DictionaryContainer.cs
- src/UserNotifications/UNNotificationAttachment.cs
- src/UserNotifications/UNNotificationResponse.cs
- src/frameworks.sources
- src/generator.cs
- src/usernotifications.cs
- src/usernotificationsui.cs
- tests/introspection/iOS/iOSApiProtocolTest.cs
- tests/monotouch-test/CoreGraphics/FunctionTest.cs
- tests/monotouch-test/CoreMedia/CMTimeTests.cs
- tools/common/Frameworks.cs
- tools/mtouch/Makefile
This PR adds two things [Do not merge yet]
- DictionaryContainer (StrongSictionary) enhancements to support CGRect/CGSize/CGPoint and CMTime with tests on actually using it on a custom subclass
- Adds UserNotifications framework, introspection tests passes.
> [Review][UserNotifications/UI] Add UserNotifications/UI framework xcode 8 beta 1

- src/WKWebKit/Defs.cs
- src/wkwebkit.cs
- tests/introspection/ApiSelectorTest.cs
Also adjust introspection tests for the new NSSecureCoding
conformance of some existing types.
> [wkwebkit] Update for iOS 10 beta 1

- src/CoreGraphics/CGColorSpace.cs
- src/coregraphics.cs
- tests/monotouch-test/CoreGraphics/ColorSpaceTest.cs
> [coregraphics] Added new CGColorSpace API from iOS 10 beta 1

- src/Constants.mac.cs.in
- src/Constants.tvos.cs.in
- src/Foundation/NSObject.mac.cs
- src/Photos/Enums.cs
- src/Photos/PHAssetChangeRequest.cs
- src/Photos/PHAssetCreationRequest.cs
- src/Photos/PHCompat.cs
- src/Photos/PHFetchResult.cs
- src/Photos/PHPhotoLibrary.cs
- src/frameworks.sources
- src/photos.cs
- tests/apitest/src/EveryFrameworkSmokeTest.cs
Also enable photos.framework on tvOS and macOS
> [photos] Update for iOS 10 beta 1

- src/MediaPlayer/MPMediaItem.cs
- src/MediaPlayer/MPNowPlayingInfoCenter.cs
- src/MediaPlayer/MediaPlayer.cs
- src/mediaplayer.cs
- tests/monotouch-test/MediaPlayer/MPNowPlayingInfoCenterTest.cs
- tests/monotouch-test/MediaPlayer/MediaItemTest.cs
- tests/monotouch-test/monotouch-test.csproj
Part 2 will come tomorrow, I just wanted to split the review work ;)
> [mediaplayer] Update for iOS 10 beta 1 - Part 1

- src/AppKit/Enums.cs
- src/ObjCRuntime/PlatformAvailability.cs
- src/appkit.cs
- tests/apitest/apitest.csproj
- tests/apitest/src/AppKit/NSSlider.cs
- tests/introspection/Mac/MacApiSignatureTest.cs
I did some of these by hand, so please double check for silly mistakes.
> Appkit for Xcode Beta 2

- src/foundation.cs
- src/intents.cs
> [foundation] Add a few types to complete bindings for Intents.framework

- src/callkit.cs
* All removals included in this commit are because members
got deprecated and will be removed on a future release no
point on having them around anymore
> [CallKit] Update to Xcode8 Beta 2

- src/speech.cs
* About radar://26799291 https://trello.com/c/s6s6YKua
the member using the private API has been removed from
the public API, still no response in the radar heh
> [Speech] Update to Xcode8 beta 2

- src/Makefile
Based on https://github.com/marek-safar/xamarin-macios/tree/cycle8 with XM fixes.
> [build] Fixes System.Drawing.Primitives facades to be proxy for appropriate profiles. Fixes #42557

- src/Intents/INIntentResolutionResult.cs
- src/Intents/INPriceRange.cs
- src/intents.cs
* Some availability attributes were added by Apple
and are now fixed accordingly but still we have
some more members that need instrospection tests
to be run on macOS 10.12 to be completly sure or
wait for a future beta and hope they are fixed
> [Intents] Update intents to Xcode 8 Beta 3

- src/UIKit/NSLayoutConstraint.cs
- src/uikit.cs
- Fix missing [Internal] attribute.
- Fix styling.
> [uikit] NSLayoutContraints fixes

- builds/Makefile
- Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=42692
> Build System.Security for XM Mobile

- tools/common/StaticRegistrar.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=42673
> [registrar] Make sure we include the headers for NS[U]Integer / CGFloat to compile. Fixes #42673.

- builds/Makefile
to pick up mono/mono@44d346f73a684738c00775c1fd6ee56877019898
Fixes [#42625](https://bugzilla.xamarin.com/show_bug.cgi?id=42625)
> Bump mono and watch-mono

- src/MultipeerConnectivity/Enums.cs
- src/multipeerconnectivity.cs
xtro results do not show any missing/extra API
> [tvos][multipeerconnectivity] Decorate API with [TV (10,0)]

- src/ReplayKit/RPEnums.cs
- src/replaykit.cs
xtro results do not show any missing/extra API
> [tvos][replaykit] Decorate API with [TV (10,0)]

- src/photos.cs
- tests/xtro-sharpie/common.pending
xtro results do not show any missing/extra API
> [tvos][photos] Decorate API with [TV (10,0)]

- src/PassKit/PKEnums.cs
- src/frameworks.sources
- src/passkit.cs
- tests/introspection/ApiTypoTest.cs
Note: several ArgumentSemantic were updated in the header files
> [passkit] Update for beta 1-2 for iOS and watchOS

- tests/mmptest/src/MMPTest.cs
- tools/common/StaticRegistrar.cs
- tools/mmp/driver.cs
Also implements https://bugzilla.xamarin.com/show_bug.cgi?id=42889
> Xcode8 xm static registrar

- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.TVOS.AppExtension.FSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.TVOS.FSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.App.FSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.AppExtension.FSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.FSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.AppExtension.FSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.FSharp.targets
https://bugzilla.xamarin.com/show_bug.cgi?id=42828
Not sure if this is the right fix, but it works for me.
With the latest xbuild 12 & 14, the other targets don't resolve correctly
> Fixes #42828

- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.TVOS.AppExtension.FSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.TVOS.FSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.App.FSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.AppExtension.FSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.FSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.AppExtension.FSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.FSharp.targets
> Cycle8 fix42828

- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.FSharp.targets
re #512 Somehow I missed the Mac .targets
> Add F# targets to Xamarin.Mac.FSharp.targets

- src/usernotifications.cs
* Mostly removal of ArgumentSemantic on value types;
* Removal of "minimalActions"
> [usernotifications] Update for beta 4

- tests/mmptest/src/MMPTest.cs
- tools/common/StaticRegistrar.cs
These are fixes already done in the xcode8 branch.
> [XM] Fix the static registrar.

- src/SpriteKit/SKUniform.cs
* Add missing 'virtual' on SpriteKit.SKUniform properties
> [spritekit] Fix small breaking changes that sneaked in PR #498

- src/SpriteKit/SKUniform.cs
Somehow I missed the last two missing 'virtual' in PR #548 ?!?
> [spritekit] Fix small breaking changes that sneaked in PR #498 (part 2)

- tests/linker-ios/link sdk/DllImportTest.cs
Latest iOS 10, tvOS 10 and watchOS 3 uses a newer libsqlite version.
It's not clear is macOS 10.12 also does (and that could affect the
test when using the simulators)
> [tests] Fix LinkSDK DllImportTest on newer OS

- src/SceneKit/Defs.cs
- src/SceneKit/SCNNode.cs
- src/modelio.cs
- src/scenekit.cs
- tests/introspection/ApiTypoTest.cs
- tests/xtro-sharpie/Helpers.cs
- tests/xtro-sharpie/common.pending
* Fixed reports of xtro tests
* Fixed some members that are @required members of an existing protocol (XAMCORE_4_0)
* Added some new typo fixes to Introspection tests
* Fixed `SCNNode.EnumerateChildNodes` delegate signature
> [Scenekit] Update SceneKit to Xcode8 Beta 4

- src/intents.cs
* TODO: We need to bind NSMeasurement<T> in order to enable some members
> [Intents] Update to Xcode8 Beta 4

- tests/introspection/Mac/MacApiCtorInitTest.cs
- Hopefully kill https://bugzilla.xamarin.com/show_bug.cgi?id=42267
> [XM] Fix "random" crash in introspection tests

- docs/website/Makefile
- docs/website/README.md
- docs/website/binding_objc_libs.md
- docs/website/binding_types_reference_guide.md
- docs/website/mtouch-errors.md
This makes it possible to have a single PR with both the feature and the
documentation changes.
> [docs] Ease tracking updates to code that requires change to the web site documentation

- src/CloudKit/CKRecord.cs
- src/CloudKit/CKUserIdentityLookupInfo.cs
- src/CloudKit/Enums.cs
- src/cloudkit.cs
- src/frameworks.sources
- tests/introspection/ApiSelectorTest.cs
- tests/introspection/ApiTypoTest.cs
- tests/monotouch-test/CloudKit/CKDiscoverUserInfosOperationTest.cs
- tests/monotouch-test/CloudKit/CKFetchNotificationChangesOperationTest.cs
- tests/monotouch-test/CloudKit/CKFetchRecordChangesOperationTest.cs
- tests/monotouch-test/CloudKit/CKFetchRecordZonesOperationTest.cs
- tests/monotouch-test/CloudKit/CKFetchRecordsOperationTest.cs
- tests/monotouch-test/CloudKit/CKFetchSubscriptionsOperationTest.cs
- tests/monotouch-test/CloudKit/CKMarkNotificationsReadOperationTest.cs
- tests/monotouch-test/CloudKit/CKModifyBadgeOperationTest.cs
- tests/monotouch-test/CloudKit/CKModifyRecordZonesOperationTest.cs
- tests/monotouch-test/CloudKit/CKModifyRecordsOperationTest.cs
- tests/monotouch-test/CloudKit/CKModifySubscriptionsOperationTest.cs
- tests/monotouch-test/CloudKit/CKQueryOperationTest.cs
- tests/monotouch-test/CloudKit/CKUserIdentityLookupInfoTest.cs
- tests/monotouch-test/monotouch-test.csproj
Update the CloudKit bindings to the code in Xcode 8 beta 3.
> [CloudKit] Update bindings for Xcode 8.

- src/HealthKit/Enums.cs
- src/HealthKit/HKObjectType.cs
- src/healthkit.cs
- tests/introspection/ApiTypoTest.cs
- tests/introspection/iOS/iOSApiProtocolTest.cs
- tests/monotouch-test/HealthKit/AnchoredObjectQueryTest.cs
- ElectrodermalActivity enum value was missing so it is [iOS (8,0), Watch (2,0)].
- Ran introspection on iOS 9.3.
> [healthkit] Update for iOS 10 beta 1

- src/VideoToolbox/VTDefs.cs
> [videotoolbox] Update for beta 5

- src/callkit.cs
- src/intents.cs
- src/videosubscriberaccount.cs
* Updates Intents to Xcode 8 Beta 5
* Updates CallKit to Xcode 8 Beta 5
* Adds some missing keys to VideoSubscriberAccount Framework
> Update Intents and CallKit to Xcode 8 Beta 5 and a small addition

- tests/mmptest/src/MMPTest.cs
- tools/mmp/Makefile
- tools/mmp/driver.cs
- https://bugzilla.xamarin.com/show_bug.cgi?id=43364
- Fixed via a hack for now. Fixed https://bugzilla.xamarin.com/show_bug.cgi?id=43419 to clean up later
> [XM] Fix native dependnecy processing by mmp when linker is disabled

- tools/linker/Descriptors/mscorlib.xml
- tools/mmp/linker/Descriptors/mscorlib.xml
Fix for test failure observed in https://github.com/xamarin/xamarin-macios/pull/612#issuecomment-240138379
> [linker] Update mscorlib.xml to include Mono.RuntimeStructs

- src/AVFoundation/AVAssetDownloadUrlSession.cs
- src/AVFoundation/Enums.cs
- src/avfoundation.cs
- tests/monotouch-test/AVFoundation/AVAssetDownloadUrlSessionTests.cs
- tests/monotouch-test/AVFoundation/AVCapturePhotoBracketSettingsTest.cs
- tests/monotouch-test/monotouch-test.csproj
Update the bindings. Please do not review until https://github.com/xamarin/xamarin-macios/pull/591 has landed.
> [AVFoundation] Update bindings for Xcode 8.

- msbuild/Xamarin.MacDev.Tasks.Core/MsBuildTasks/CopyBase.cs
See https://github.com/Microsoft/msbuild/issues/928
> [msbuild] Add forward compatibility with symlinks support

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ArchiveTaskBase.cs
- msbuild/Xamarin.iOS.Tasks.Core/Tasks/ArchiveTaskBase.cs
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=43489
> [msbuild] Add the Insights API Key to the iOS archive manifest

- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
- msbuild/tests/MyActionExtension/Info.plist
- msbuild/tests/MyActionExtension/MyActionExtension.csproj
- msbuild/tests/MyDocumentPickerExtension/Info.plist
- msbuild/tests/MyDocumentPickerExtension/MyDocumentPickerExtension.csproj
- msbuild/tests/MyKeyboardExtension/Info.plist
- msbuild/tests/MyKeyboardExtension/MyKeyboardExtension.csproj
- msbuild/tests/MyTabbedApplication/Info.plist
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=43264
> [msbuild] Always codesign iOS frameworks

- src/corelocation.cs
- https://bugzilla.xamarin.com/show_bug.cgi?id=43593
> [XM] Add CoreLocation APIs that exist on macOS

- tests/mmptest/src/MMPTest.cs
- tools/common/StaticRegistrar.cs
Cherry pick of two commits: 
https://github.com/xamarin/xamarin-macios/commit/88d83532ef13cb4ac5f8c4bef965d9f6f18e849c
https://github.com/xamarin/xamarin-macios/commit/798aca0767eb18fc84a22fe5498aa9bdf61e302e
> Fixup C8 static registrar to work w\ Xcode 8

- runtime/launcher.m
- runtime/runtime.m
- runtime/xamarin/main.h
- tools/mmp/driver.cs
- https://bugzilla.xamarin.com/show_bug.cgi?id=23482
> [XM] Add support for disabling lldb attach on crash

- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Another fix for https://bugzilla.xamarin.com/show_bug.cgi?id=43264
> [msbuild] Always codesign *.dylibs, even for Simulator builds

- src/appkit.cs
- https://bugzilla.xamarin.com/show_bug.cgi?id=43542
- Quick hand test here - https://gist.github.com/chamons/05f94781ec910869343f114fe7b4edbe
> [XM] Add NSOpenGLLayer binding

- src/ObjCRuntime/Runtime.cs
Native code can provide the same native method for blocks
with different managed signatures, so it's not enough
to hash by method address, we need to take the target type
of the delegate into account as well.
https://bugzilla.xamarin.com/show_bug.cgi?id=34513
> Take target type into account when caching delegates for blocks. Fixes #34513.

- src/foundation.cs
- tests/introspection/Mac/MacApiSelectorTest.cs
- https://bugzilla.xamarin.com/show_bug.cgi?id=38118
> [XM] Missing NSUserNotification bindings

- src/CoreMidi/MidiServices.cs
- tests/monotouch-test/CoreMidi/MidiEndpointTest.cs
- tests/monotouch-test/monotouch-test.csproj
https://bugzilla.xamarin.com/show_bug.cgi?id=43582
- Thanks to @olegoid for the actual investigation and fix
- Added test that verifies the fix
> [Midi] Fix bug 43582 - MidiEndpoint throws, bad dispose of GCHandle

- src/photos.cs
reference:
https://trello.com/c/ZLOvAFWp/232-avcam-rawexpose-phphotolibrary-requestauthorizationasync
> [photos] Add an async version of PHPhotoLibrary.RequestAuthorization

- src/CoreAnimation/CATransform3D.cs
Obsolete the version requiring a non used argument and add one accepting
no argument.
https://bugzilla.xamarin.com/show_bug.cgi?id=43058
> [coreanimation] Provide better API for CATransform3D.Invert. Fixes #43058

- src/photos.cs
This adds Abstract to some classes for XAMCORE_4_0
and tvOS added in 10.0
> [Photos] Add Abstract attributes to a couple of classes

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DetectSigningIdentityTaskBase.cs
Now that dylibs and frameworks are required to be signed in order to
run on the Simulator, we cannot allow the DetectSigningIdentity task
to return success if it didn't find a codesign key.
"Fixes" https://bugzilla.xamarin.com/show_bug.cgi?id=44033
> [msbuild] Even iOS Simulator builds now require signing certificates

- src/VideoToolbox/VTCompressionSession.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=44073
> [videotoolbox] VTCompressionOutputCallback allows a null CMSampleBufferRef. Fixes #44073

- src/appkit.cs
- https://bugzilla.xamarin.com/show_bug.cgi?id=44200
> [XM] Add [NullAllowed] to some NSResponder based APIs

- src/generator.cs
- src/uikit.cs
Build diff on generator change: https://gist.github.com/dalexsoto/6294a8537867c6a0b9d07ef40109bc1c
> [UIKit] re-enable the iOS 10 API that were waiting on bug 43579 fix

- builds/Makefile
- Bump mono to get https://github.com/mono/mono/commit/377041fd6ec7a75d55e451d4752be1048b836c13
> [XM] Enable System.Numerics.Vector assembly

- src/ObjCRuntime/DynamicRegistrar.cs
- tests/common/mac/ProjectTestHelpers.cs
- tests/mmptest/src/ClassicTests.cs
- tests/mmptest/src/MMPTest.cs
- tests/mmptest/src/NativeReferencesTests.cs
- tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
- Fix https://bugzilla.xamarin.com/show_bug.cgi?id=44565
- Which is really 44309 in a second branch picked up by QA.
> Fix registrar spam in xcode8

- src/CoreWlan/Enums.cs
- src/corewlan.cs
http://forums.xamarin.com/discussion/comment/222095/#Comment_222095
https://bugzilla.xamarin.com/show_bug.cgi?id=44501
> Added CWWiFiClient class.

- src/Foundation/NSAttributedString.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=44455
> [Foundation] Add a few missing NSAttributedString methods to watchOS. Fixes #44455.

- tools/mtouch/Application.cs
The nested Parallel.ForEach loops don't take into account the outer
MaxDegreeOfParallelism value, causing us to spawn more concurrent tasks than
we want to.
So refactor the code to have one static list of tasks, which each subtask adds
to.
> [mtouch] Don't use nested Parallel.ForEach loops.

- src/Security/Tls/AppleTlsContext.cs
Bump Mono to pickup the BCL part of the fix.
commit 2a3e4002ead94aae6796c7eb7af9a850398beb51
Author: Martin Baulig <martin.baulig@xamarin.com>
Date:   Fri Sep 23 17:42:05 2016 +0200
[AppleTls]: Flush the write queue before finishing the handshake.
It is possible for SSLHandshake() to return SslStatus.Success while we're still
having a pending write (AsyncOperationStatus.WantWrite).
This is because our managed write callback must never return 'WouldBlock', so
SSLHandshake() things that all data have been sent while we still have them in
our write queue.
When this happens, we currently flush the write queue then call SSLHandshake()
again via AsyncOperationStatus.WantWrite -> AsyncOperationStatus.Continue.
This returns SslStatus.Protocol on iOS 10.
(cherry picked from commit …
> [AppleTls]: Disallow calling SSLHandshake() again after the handshake has finished

- src/webkit.cs
- https://bugzilla.xamarin.com/show_bug.cgi?id=32975
> [XM] Add missing Javascript bindings in webkit.cs

- src/Security/Items.cs
- tests/monotouch-test/Security/RecordTest.cs
https://trello.com/c/uw7KfZB3
* Added Certificate ctor and getter/setter
* Added Identity ctor and getter/setter
* Added SecRecord ctor and getter/setter
> [Security] Add convenience Certificate, Key and Identity ctors to SecRecord

- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.AppExtension.CSharp.targets
- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.CSharp.targets
- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.CSharp.props
- msbuild/Xamarin.ObjcBinding.Tasks/Xamarin.ObjcBinding.CSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.MonoTouch.CSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.AppExtension.CSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.CSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.ObjCBinding.CSharp.props
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.WatchApp.CSharp.targets
This should fix issue: https://github.com/NuGet/Home/issues/3516
> [msbuild] Set $(CscDebugFileExt) also, whenever overriding $(CscToolExe)

- src/GameKit/GameKit.cs
- src/gamekit.cs
Low Hanging Fruit bindings - enabling gamekit bindings for mac that were already done for iOS
> [Mac] Activate gamekit bindings shared with iOS

- src/AppKit/Enums.cs
- tests/xtro-sharpie/osx.ignore
- https://bugzilla.xamarin.com/show_bug.cgi?id=40494
> [XM] Add missing NSNotification bits

- src/AppKit/NSView.cs
- src/appkit.cs
- src/foundation.cs
- https://bugzilla.xamarin.com/show_bug.cgi?id=27349
- Designed to be implemented by any NSObject you pass into AddToolTip.
> [XM] Add NSTooltipOwner to NSObject

- src/AudioToolbox/MusicSequence.cs
- src/CoreFoundation/CFMessagePort.cs
- src/CoreMedia/CMBufferQueue.cs
- src/ObjCRuntime/DynamicRegistrar.cs
- src/ObjCRuntime/Runtime.cs
See each commit, changes should be non-invasive.
> Performance improvements

- src/appkit.cs
- https://bugzilla.xamarin.com/show_bug.cgi?id=38652
> [XM] Add missing NSResponder APIs

- tests/mtouch/MTouch.cs
- tests/mtouch/MTouchTool.cs
- tools/common/CompilerFlags.cs
- tools/mtouch/Application.cs
- tools/mtouch/Target.cs
Building a dylib is somewhat useless unless it ends up in the app bundle.
> [mtouch] Bundle libpinvokes.dylib in the app.

- msbuild/Xamarin.iOS.Tasks.Core/Tasks/MTouchTaskBase.cs
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=45240
> [msbuild] Fixed parsing of --gcc_flags=... for mtouch

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/PrepareNativeReferencesTaskBase.cs
- tests/msbuild-mac/src/MSBuild-Smoke.cs
- https://bugzilla.xamarin.com/show_bug.cgi?id=45762
> Fix binding project LinkWithAttributes generation to prevent rebuilds

- tools/mtouch/Target.cs
Found out it was missing by breaking 9locally) something else :)
> [mtouch] Fix MT1009 to report the inner exception

- docs/website/mtouch-errors.md
- src/ObjCRuntime/Registrar.cs
- tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
- tools/common/StaticRegistrar.cs
- tools/mtouch/error.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=44926
> [static registrar] Fix registration of generic types. Fixes #44926.

- src/appkit.cs
- https://bugzilla.xamarin.com/show_bug.cgi?id=46162
> [xm] Fix multiple NullAllowed issues in NSMenu

- msbuild/Xamarin.iOS.Tasks.Core/Tasks/CompileAppManifestTaskBase.cs
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=44257
> [msbuild] Add watch-companion to UIRequiredDeviceCapabilities for watchOS1 extensions (#868)

- src/cloudkit.cs
xcode8.2 beta 1 cloudkit changes
> [Mac 10.12.2] CloudKit nullability info

- tests/mtouch/MTouch.cs
Convert MT1016 and MT1017 to newer test syntax, and at the same time change
them to not disable the managed linker.
For these tests it doesn't matter if they're linked or not, but linking is
much faster (20s vs 82s for both tests).
> [mtouch tests] Convert MT1016 and MT1017 tests to use new test syntax and link them.

- tools/common/StaticRegistrar.cs
- Generalized the hack a bit. If we continue to need them
we can make it more data driven
> [XM] Fix static registrar under Xcode 8.2 with another hack

- src/Photos/Enums.cs
- src/photos.cs
Update Photos to Xcode 8.2 Beta 2
> [Photos] Update Photos to Xcode 8.2 Beta 2

- src/HomeKit/HMEnums.cs
- src/HomeKit/HMHome.cs
- tests/introspection/ApiTypoTest.cs
[HomeKit] Update to Xcode 8.2 Beta 2
> [HomeKit] Update to Xcode 8.2 Beta 2

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ACToolTaskBase.cs
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/IBToolTaskBase.cs
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/XcodeCompilerToolTask.cs
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=44674
> [msbuild] Log warnings and errors for the ibtool --link stage as well

- tests/apitest/src/DelegateAndDataSourceTest.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=46624
> [apitest] Skip IKPictureTaker. Fixes #46624.

- src/btouch.cs
- src/generator.cs
This allows us to remove a few ifdefs, which is a required step
in order to create an ikvm-based generator.
> [generator] Add a CurrentPlatform field to BindingTouch.

- src/Makefile
> Add missing watch drawing sources

- src/appkit.cs
- src/notificationcenter.cs
- src/spritekit.cs
- src/webkit.cs
- tests/.gitignore
- tests/introspection/Mac/MacApiProtocolTest.cs
- tests/xharness/Harness.cs
- tests/xharness/Jenkins.cs
- tests/xharness/MacUnifiedTarget.cs
- tests/xharness/TestProject.cs
- Previous to this we were only running 64-bit tests, which caused us
to make mistakes
> [XM] Add 32-bit variants of apitest and introspection and fix bindings

- src/ObjCRuntime/Runtime.mac.cs
- tests/common/mac/ConsoleProgram.cs
- tests/common/mac/ConsoleXM.targets
- tests/common/mac/ConsoleXMApp.csproj
- tests/mmptest/src/MMPTest.cs
- https://bugzilla.xamarin.com/show_bug.cgi?id=43932
> [XM] Fall back to side by side loading of libxammac.dylib

- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/PropertyListEditorTaskBase.cs
- msbuild/Xamarin.MacDev.Tasks.Core/Xamarin.MacDev.Tasks.Core.csproj
- msbuild/Xamarin.MacDev.Tasks/Tasks/PropertyListEditor.cs
- msbuild/Xamarin.MacDev.Tasks/Xamarin.MacDev.Tasks.csproj
- msbuild/Xamarin.iOS.Tasks.Core/Tasks/MTouchTaskBase.cs
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
- msbuild/tests/Xamarin.iOS.Tasks.Tests/TaskTests/PropertyListEditorTaskTests.cs
- msbuild/tests/Xamarin.iOS.Tasks.Tests/Xamarin.iOS.Tasks.Tests.csproj
This is a convenience Task for customers and isn't currently used
by the core MSBuild targets.
> [msbuild] Added a PropertyListEditor task which works like PlistBuddy

- src/appkit.cs
- src/avfoundation.cs
- src/foundation.cs
- src/imagekit.cs
- src/qtkit.cs
- tests/introspection/ApiFieldTest.cs
- tests/introspection/Mac/MacApiFieldTest.cs
- Teach test to check SkipNotification since a number of corrections require XAMCORE_4_0
> [XM] Fix XM bindings to include Notifications and update test

- tools/common/TargetFramework.cs
Add support for specifying the profile with the target framework,
and support using "Version=" before the version:
Xamarin.Mac,Version=v2.0,Profile=Mobile.
> TargetFramework: add support for profile.

- msbuild/Xamarin.iOS.Tasks.Core/Tasks/CreateDebugConfigurationTaskBase.cs
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=48515
> [msbuild] Don't rewrite MonoTouchDebugConfiguration.txt unless it has changed

- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.TVOS.AppExtension.Common.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.AppExtension.Common.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.AppExtension.Common.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Patch #2 for https://bugzilla.xamarin.com/show_bug.cgi?id=49097
> [msbuild] Prevent rebuilds from re-codesigning if the app bundle is unchanged

- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
> [msbuild] Use $(DeviceSpecificOutputPath) instead of $(AppBundleDir)\..\

- msbuild/Xamarin.iOS.Tasks.Core/Tasks/ParseDeviceSpecificBuildInformationTaskBase.cs
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=50454
> [msbuild] Properly clean device-specific output directories

- tests/bcl-test/Mono.Data.Sqlite/Mono.Data.Sqlite.csproj.template
- tests/bcl-test/Mono.Security/Mono.Security.csproj.template
- tests/bcl-test/System.ComponentModel.DataAnnotations/System.ComponentModel.DataAnnotations.csproj.template
- tests/bcl-test/System.Core/System.Core.csproj.template
- tests/bcl-test/System.Data/System.Data.csproj.template
- tests/bcl-test/System.Json/System.Json.csproj.template
- tests/bcl-test/System.Net.Http/System.Net.Http.csproj.template
- tests/bcl-test/System.Numerics/System.Numerics.csproj.template
- tests/bcl-test/System.Runtime.Serialization/System.Runtime.Serialization.csproj.template
- tests/bcl-test/System.ServiceModel.Web/System.ServiceModel.Web.csproj.template
- tests/bcl-test/System.Transactions/System.Transactions.csproj.template
- tests/bcl-test/System.Web.Services/System.Web.Services.csproj.template
- tests/bcl-test/System.Xml.Linq/System.Xml.Linq.csproj.template
- tests/bcl-test/System.Xml/System.Xml.csproj.template
- tests/bcl-test/System/System.csproj.template
- tests/bcl-test/mscorlib/mscorlib-split.csproj.template
- tests/bcl-test/mscorlib/mscorlib.csproj.template
And also define the FULL_AOT_RUNTIME conditional constant.
> Bump mono to get fix for System.Core tests.

- src/appkit.cs
- tests/apitest/apitest.csproj
- tests/apitest/src/AppKit/NSToolbarItem.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=50426
> Add NSToolbarItemGroup binding

- docs/website/mtouch-errors.md
- tests/xharness/AppRunner.cs
- tests/xharness/Harness.cs
- tests/xharness/Program.cs
- tools/mtouch/error.cs
The new error message / number is used in mlaunch.
> [xharness] Add support for uninstalling apps from device.

- src/ObjCRuntime/ErrorHelper.cs
- tools/common/StaticRegistrar.cs
Xamarin.Registrar.MT4161 : Unexpected error/warning with --registrar:static:
error MT0000: Unexpected error - Please file a bug report at http://bugzilla.xamarin.com
> [mtouch] Fix infinite recursion after d1102c80.

- src/MobileCoreServices/UTType.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=51299
> Fix inverted null check in MobileCoreServices

- src/error.cs
- src/generator.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=51212
Generator gets a TypeLoadException when the runtime can't load a
bad struct, we now provide a better error msg.
> [generator] Provide a better error than BI0000 when gets a TypeloadException in NeedStret

- tests/xharness/Harness.cs
We're shipping mlaunch now, which means we have other file system locations
where it might be.
Also don't look in Xamarin Studio anymore, it will always be an old version,
instead check the system's Xamarin.iOS version.
> [xharness] Update where we look for mlaunch.

- tests/xharness/Jenkins.cs
Unexpected exceptions are now caught in a more central location
(TestTask.RunInternalAsync), which means it's not necessary to catch
unexpected exceptions in other places (so those catch handlers have been
removed).
Additionally we now set the failure message when such an exception occurs, in
addition to writing the full exception details to a custom log file.
> [xharness] Improve handling and reporting of unexpected exceptions.

- tests/xharness/PListExtensions.cs
- tests/xharness/SolutionGenerator.cs
- tests/xharness/Target.cs
- tests/xharness/TodayExtensionTarget.cs
- tests/xharness/WatchOSTarget.cs
Minor tweaks to make the solutions/project files usable from the IDE, and not
only the command line.
> [xharness] Fix generation of today extension projects to work from Xamarin Studio.

- tools/common/Assembly.cs
Simplify code a bit to avoid constant null checking and also take advantage of
the fact that HashSet.Add returns if the value was added or not (to avoid a
Contains check).
> [mtouch] Simplify code a bit.

- tests/mac-binding-project/Makefile
- https://bugzilla.xamarin.com/show_bug.cgi?id=50634
> [XM] Rework binding project test to try to fix build machine issues

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CodesignTaskBase.cs
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
First step for https://bugzilla.xamarin.com/show_bug.cgi?id=51298
> [msbuild] batch codesign resources to improve performance

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CodesignTaskBase.cs
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=51298
> [msbuild] Parallelized codesigning of *.dylibs and frameworks

- docs/website/mtouch-errors.md
https://bugzilla.xamarin.com/show_bug.cgi?id=51772
> [docs] Update text about MT5211. Fixes #51772.

- src/generator.cs
Eventually these ifdefs will be replaced with normal ifs.
> [generator] Replace target-specific ifdefs with feature-specific ifdefs.

- tests/xharness/Jenkins.cs
This is a backport of 9e8b43a.
https://bugzilla.xamarin.com/show_bug.cgi?id=46097
> [jenkins] Make jenkins non-parallel. Fixes #46097.

- src/generator.cs
Because that won't work when those ifdefs are converted to normal ifs.
> [generator] Don't use type initializers with ifdefs.

- tests/mac-binding-project/Makefile
- https://bugzilla.xamarin.com/show_bug.cgi?id=50634
> [XM] [C9] Rework binding project test to try to fix build machine issues.

- tools/common/Application.cs
Cecil cannot save an assembly more than once without reloading its
debugging symbols. There was code for this, in the special case where
an assembly could be saved more than once. However the order of the
operations changed and the code to reload symbols was now located too
late.
https://bugzilla.xamarin.com/show_bug.cgi?id=51667
> [mtouch] Reload symbols before saving an assembly again (when needed). Fixes #51667

- tools/mmp/Makefile
- tools/mtouch/Makefile
Make sure mtouch/mmp rebuild cecil when anything changes in cecil.
> [mtouch/mmp] Fix cecil dependencies.

- runtime/launcher.m
- runtime/runtime.m
- runtime/xamarin/main.h
- tests/monotouch-test/Contacts/ContactStoreTest.cs
- tests/xammac_tests/xammac_tests.csproj
- tests/xharness/Harness.cs
- tools/mmp/aot.cs
- tools/mmp/driver.cs
- tools/mmp/tests/aot.cs
Also:
- Add an environmental flag XM_FORCE_AOT to allow for easy testing. 
- Add xammac_tests to Makefile/jenkins
> [XM] Add hybrid/standard AOT option and improve AOT code

- src/MediaPlayer/MPMediaItemArtwork.cs
- src/MediaPlayer/MPMediaItemProperty.cs
- src/MediaPlayer/MPRemoteCommandCenter.cs
- src/MediaPlayer/MPSkipIntervalCommand.cs
- src/MediaPlayer/MediaPlayer.cs
- src/mediaplayer.cs
Make new MediaPlayer APIs 64 bit only and remove from classic
> Remove MediaPlayer from XM Classic and 32-bit Unified (#1579)

- tests/mtouch/RegistrarTest.cs
Change how the registrar calls mtouch a bit, so that we don't use API that
throws an exception with the entire output in the exception message.
The problem is that if the process has a lot of output, XS slows down to a
crawl when showing the exception message in the test result pad.
Instead print the output to the terminal.
> [mtouch tests] Refactor registrar tests a little bit to not cause trouble in Xamarin Studio.

- src/Security/Enums.cs
- src/Security/Items.cs
- src/Security/SecAccessControl.cs
- src/security.cs
- tests/introspection/ApiTypoTest.cs
There's a lot of noise from the header diff, e.g. tabs changed to spaces,
but very few actual changes.
Note that there's more macOS specific code to review but this PR
handles iOS, tvOS and watchOS changes.
> [security] Add new API for beta 1

- src/HomeKit/HMEnums.cs
> [homekit] Update watchOS API availability for Xcode 8.3

- docs/website/mtouch-errors.md
- src/ObjCRuntime/Registrar.cs
- tests/mtouch/RegistrarTest.cs
- tools/mtouch/error.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=52530
> [mtouch] Add docs and improve MT4146 to be an error if we can detect the generated code won't compile. Fixes #52530.

- runtime/monotouch-debug.m
At the beginning of dawn, not long after the big bang, we used to vibrate the
phone if there was a problem when connecting to the debugger in the IDE, and
the number of times the phone vibrated indicated a certain error condition.
This innovative debugging technique was at some point replaced with more
intuitive (albeit less innovative) error reporting, however the *_connect_*
family of functions continued returning the number of times the phone should
vibrate, even if the caller was now soundlessly ignoring this information.
After many years someone had the wonderful idea of running a static analyzer
on the code, and now the unused return value is not so silent anymore:
monotouch-debug.m:663:5: warning: Value stored to 'rv' is never read
rv = monotouch_connect_usb ();
^ …
> [runtime] Remove unused return value from the *_connect_* debug functions.

- src/Foundation/NSString.cs
- src/btouch.cs
Generator diff: https://gist.github.com/rolfbjarne/f6c0e32960eacbafd38238e623d3321a
> [generator] Remove unnecessary code.

- src/ObjCRuntime/Stret.cs
Remove any platform-specific ifdefs for the generator's stret detection code.
There are still ifdefs in this file, because it's shared with the platform
assemblies.
Generator diff: https://gist.github.com/rolfbjarne/3034666fb99278eb2486da8579271488
> [generator] Remove any platform-specific ifdefs for the generator stret detection code.

- src/ObjCRuntime/Messaging.mac.cs
Now to master since it passed C9.
> Add C8->C9 objc_msgSend fixes for XM classic (#1697)

- src/CFNetwork/Content.cs
- src/Darwin/SystemLog.cs
- src/btouch.cs
- src/generator-enums.cs
- src/generator.cs
Generator diff for the generator changes: https://gist.github.com/rolfbjarne/ac7b166a308dc5b04bae29487114e9b8 (no relevant changes).
> Fix a few culture-aware string comparisons to be culture-unaware.

- src/AppKit/NSPrintInfo.cs
- src/appkit.cs
- src/frameworks.sources
Return the expected types instead of IntPtrs
> [52501] Add helper properties for the NSPrintInfo PrintCore methods

- Versions-ios.plist.in
- Versions-mac.plist.in
Add feature-list as a new feature to our new list of features.
https://trello.com/c/4pg3fuc8/676-move-away-from-version-check
> Add an array of features to our Versions.plist.

- src/generator-typemanager.cs
- src/generator.cs
Generator diff: https://gist.github.com/9f1923146eb4a7eb456263290a8388bf
> [generator] Add a TypeManager.IsOutParameter method to abstract away ikvm and reflection differences.

- src/btouch.cs
Generator diff: https://gist.github.com/rolfbjarne/41871e60066053e5d29b4ed1b1221117
> [generator] Load the correct platform Xamarin.Mac platform assemblies.

- src/generator-enums.cs
- src/generator-typemanager.cs
- src/generator.cs
Generator diff: https://gist.github.com/rolfbjarne/94dbf673e284197845766cc698a64ff3
> [generator] Add a TypeManager.GetUnderlyingEnumType to abstract away ikvm and reflection differences.

- tests/mtouch/RegistrarTest.cs
- tools/common/StaticRegistrar.cs
- tools/mtouch/error.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=52868
> [registrar] Fix generic argument check to allow INativeObject. Fixes #52868.

- src/generator.cs
Attribute.IsDefined doesn't work with IKVM.
Generator diff: https://gist.github.com/rolfbjarne/412bb9c0e6327887a8d71f8f79951e24
> [generator] Use AttributeManager.HasAttribute instead of Attribute.IsDefined.

- msbuild/Xamarin.iOS.Tasks.Core/Tasks/ParseDeviceSpecificBuildInformationTaskBase.cs
Related to https://bugzilla.xamarin.com/show_bug.cgi?id=52847
> [msbuild] Make a build error more clearly worded

- src/generator-attributes.cs
- src/generator-typemanager.cs
- src/generator.cs
Generator diff: https://gist.github.com/rolfbjarne/1ff230ac03cad6b81061c2814a5a895e
> [generator] Add a TypeManager.GetUnderlyingNullableType to abstract away ikvm and reflection differences.

- src/Makefile.generator
- src/ObjCRuntime/Stret.cs
- tools/common/TargetFramework.cs
Generator diff: https://gist.github.com/rolfbjarne/fa9d91f13a6421135e089bed8e1ccefe
> [generator] Don't define 'GENERATOR', since IKVM sources use the same name (for something else).

- Make.config
Bump Xamarin Studio to get fix for bug #52648 causing build failures.
https://bugzilla.xamarin.com/show_bug.cgi?id=52648
> Bump Xamarin Studio to get fix for bug #52648.

- Versions-ios.plist.in
Partial fix for https://bugzilla.xamarin.com/show_bug.cgi?id=53279
> [mlaunch] Added feature keys to Versions-ios.plist.in

- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=53303
> [msbuild] Use stamp files to force container app's _CompileToNative

- src/ObjCRuntime/ErrorHelper.cs
- tools/common/StaticRegistrar.cs
We ran into a couple crashes while getting error info for a different crash
This lets us catch the exception if that happens and output an error for the new crash.
> [XM] Static Registrar CreateException fix

- Versions-ios.plist.in
- Versions-mac.plist.in
> [Versions-ios.plist.in] added sgen-concurrent-gc

- src/generator.cs
- tests/generator/Makefile
- tests/generator/bug42742.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=42742
The Advice attribute used in our bindings was not making
into the generated code. This fixes it.
Also added unit test for it
Build diff: https://gist.github.com/dalexsoto/b3f7a5d7d2b0809eb93ad23d04d06ff7
> [generator] The [Advice] attribute doesn't make it to the generated code. Fixes #42742

- tests/fsharp/FSharpTests.fs
Added F# Test for bug [#52866](https://bugzilla.xamarin.com/show_bug.cgi?id=52866)
> [test][fsharp] Add F# test for bug 52866

- docs/website/generator-errors.md
- src/btouch.cs
- src/error.cs
- tests/generator/Makefile
- tests/generator/nowarn.cs
- tests/generator/warnaserror.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=52573
* Added nowarn and warnaserror to btouch/bmac
* Added generator tests
build diff: https://gist.github.com/dalexsoto/e5a11f8c03d5e7364ad1a35072db064f
> [generator] Fix bug 52573 - Add nowarn and warnaserror to btouch/bmac

- src/uikit.cs
Here are the 3 rules of thumb that have been applied:
- Never put OS version information in the message.
- Always put methods and properties between ' '.
- Use proper sentences and punctuation.
This will all be summarized in our wiki.
> [uikit] Update all Obsoleted and Deprecated messages

- msbuild/Xamarin.iOS.Tasks.Core/Tasks/GetDirectoriesTaskBase.cs
- msbuild/Xamarin.iOS.Tasks.Core/Tasks/GetFilesTaskBase.cs
- msbuild/Xamarin.iOS.Tasks.Core/Tasks/GetFullPathTaskBase.cs
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Tasks.Core.csproj
- msbuild/Xamarin.iOS.Tasks/Tasks/GetDirectories.cs
- msbuild/Xamarin.iOS.Tasks/Tasks/GetFiles.cs
- msbuild/Xamarin.iOS.Tasks/Tasks/GetFullPath.cs
- msbuild/Xamarin.iOS.Tasks/Xamarin.iOS.Tasks.csproj
This is a back-port of https://github.com/xamarin/xamarin-macios/pull/1895 to the d15-1 branch
> D15 1 msbuild vs fixes

- docs/website/mtouch-errors.md
- tools/mtouch/Application.cs
- tools/mtouch/error.cs
The old one makes it sounds the linker is doing magic ;-)
> [mtouch] Provide a more accurate description of the MT0091 error

- src/Foundation/Enum.cs
- src/foundation.cs
Requested in https://forums.xamarin.com/discussion/comment/263094 and trivial to knock out.
> Add NSFileManager.UnmountVolume

- tests/mmptest/src/FrameworkLinksTests.cs
- tools/common/Assembly.cs
- Broken by https://github.com/xamarin/xamarin-macios/commit/d20ccf5bc6bd5ed06571d09b424f3d5cd3121e5d
> [macos] Fix XM projects with p/invokes into non-system frameworks

- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=54687
> [msbuild] Enable device-specific builds for appex's

- tools/mmp/Tuning.cs
Same that was done for `mtouch` in
https://github.com/xamarin/xamarin-macios/pull/1947
> [mmp] Show more information when a MM2001 error occurs

- tools/common/Assembly.cs
- Fixup comment in https://github.com/xamarin/xamarin-macios/pull/1968 that was missed
> [macos] Refactor framework skipping logic in mmp

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/IBToolTaskBase.cs
- msbuild/tests/IBToolTaskTests/GenericAndDeviceSpecific/Info.plist
- msbuild/tests/IBToolTaskTests/GenericAndDeviceSpecific/View.xib
- msbuild/tests/IBToolTaskTests/GenericAndDeviceSpecific/View~ipad.xib
- msbuild/tests/Xamarin.iOS.Tasks.Tests/TaskTests/IBToolTaskTests.cs
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=54914
> [msbuild] Avoid Dictionary clashes in IBToolTask's mapping dictionary

- tools/mmp/Makefile
https://bugzilla.xamarin.com/show_bug.cgi?id=53927
> [mmp] Build and install pdb files. Fixes #53927.

- tests/mtouch/MTouch.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=54578
> [tests] Bump mono to get fix for bug #54578 and add test case.

- tests/mtouch/MTouch.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=54578
> [d15-2] [tests] Bump mono to get fix for bug #54578 and add test case.

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileSceneKitAssetsTaskBase.cs
CompileSceneKitAssetsTaskBase tries to set `DefiningProjectFullPath`
metadata on a new TaskItem, if it is available on the original one.
But with msbuild, this is a reserved metadata and cannot be set.
If we create the new item based on the original one, then we get the
metadata too. And we also get a `OriginalItemSpec`, which we don't need
and can remove.
This fixes a regression caused by msbuild/XS switching to use the
msbuild implementations of `Microsoft.Build.{Tasks,Utilities}.{v4.0,v12.0}`
assemblies (-> `.Core`) instead of the xbuild ones.
It manifested as:
`error MSB4018: System.ArgumentException: "DefiningProjectFullPath" is a reserved item metadata, and cannot be modified or deleted.`
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=55480 …
> [msbuild] Fix samples build with msbuild

- tests/mtouch/MTouch.cs
- tools/mtouch/Application.cs
This dramatically decreases the size of watchOS apps built for debug when
using frameworks, because it ends up removing all the bitcode from
Mono.framework.
https://bugzilla.xamarin.com/show_bug.cgi?id=55256
> [mtouch] Add support for stripping bitcode from frameworks when not needed. Fixes #55256.

- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.AppExtension.CSharp.targets
- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.CSharp.targets
- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.CSharp.props
https://bugzilla.xamarin.com/show_bug.cgi?id=36258
> [msbuild] Define __MACOS__ for Xamarin.Mac. Fixes #36258.

- tools/common/CompilerFlags.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=55698
> [mtouch] Look for dynamic libraries in the container app. Fixes #55698.

- tools/common/CompilerFlags.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=55698
> [mtouch] Look for dynamic libraries in the container app. Fixes #55698. (#2052)

- tests/xharness/Jenkins.cs
We run the xammac tests both in Debug and Release mode now, but those two
modes can't be run in parallel, so make sure they don't.
https://bugzilla.xamarin.com/show_bug.cgi?id=56161
> [xharness] Make sure different variations of the xammac tests aren't run in parallel. Fixes #56161.

- tests/xharness/Jenkins.cs
This chunk of code is repeated 30 lines below.
> [xharness] Remove duplicated code.

- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
- tests/mmptest/mmptest.csproj
- tests/mmptest/src/Extensions.cs
- tests/mmptest/src/NativeReferencesTests.cs
- https://bugzilla.xamarin.com/show_bug.cgi?id=56098
- Moderate test cleanup in separate commit to make writing test easier / fix duplication.
> [macos] Fix Multiple Native References

- src/webkit.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=32612
> [macos][webkit] Bind WebView.SetSelectedDomRange Fixes #32612

- tools/mtouch/Application.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=56679
> [mtouch] Fix condition to detect a mix of dylibs and frameworks for the same library. Fixes #56679.

- tools/common/Assembly.cs
- tools/linker/MonoTouch.Tuner/ListExportedSymbols.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=53420
> [mmp] Add unusual checks necessary to process obfuscated code. Fixes #53420.

- jenkins/nunit-summary.xslt
This makes the failed tests show up in the html report itself, and it will
also show the failure message and stack trace in the produced log.
https://bugzilla.xamarin.com/show_bug.cgi?id=51661
> [xharness] Improve translation from xml to log file. Partially fixes #51661.

- src/btouch.cs
- src/generator-typemanager.cs
- src/generator.cs
Simplify code a little bit by having a single variable that says whether we're
compiling third-party code or not.
> [generator] Simplify code a little bit.

- src/ObjCRuntime/Registrar.cs
- tests/mtouch/RegistrarTest.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=55568
> [registrar] Detect more invalid characters in selectors so that we can report better errors. Fixes #55568.

- Make.config
@spouliot I've made a new request to clean up the commits.
> bumped the max version of visual studio for mac

- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
- msbuild/tests/Xamarin.iOS.Tasks.Tests/ProjectsTests/Extensions/WatchKit2.cs
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=56345
> [msbuild] Properly generate dSYMs for WatchKit2 appex's

- src/ObjCRuntime/Dlfcn.cs
- src/generator-enums.cs
- src/generator.cs
- tests/generator/Makefile
- tests/generator/fieldenumtests.cs
Fixes Bugs:
* https://bugzilla.xamarin.com/show_bug.cgi?id=57535
* https://bugzilla.xamarin.com/show_bug.cgi?id=57537
New Features:
* Added Smart Enum support to [Field]
* Added [Native] enum support to [Field]
* Added enum support to [Field]
* Added uint support to [Field]
Also fixed a bug in Smart Enums support when computing the library name
taking into account third party bindings and some special cases, this is
needed because we ended up generating invalid code when Smart Enum support
was used in third party bindings.
Also added Field Enum generation test.
Build diff: https://gist.github.com/dalexsoto/2b30972e53e7fe3d51ac168dd22627d3
> [generator] Add enum support for [FieldAttribute], Fixes 57537 and 57535.

- tests/mtouch/MTouch.cs
- tools/common/Target.cs
Previously the assumption was that if an assembly not using dlsym references a
native symbol, it's not a required symbol. This is true as far as the native
linker goes: the native linker will see that the native symbol is referenced
by the AOT-compiled code, and it won't be removed.
However, we use also this exact logic to create the list of functions we ask
the native strip command to preserve, and in this case we need to include all
symbols needed in all assemblies that looks up native functions using dlsym.
https://bugzilla.xamarin.com/show_bug.cgi?id=57826
> [mtouch] If a P/Invoke is used by any assembly that looks up the native symbol using dlsym, it's a required symbol. Fixes #57826.

- src/eventkit.cs
- tests/xtro-sharpie/osx.pending
Also added `EKEventStore` ctor to Mac found by xtro
> [EventKit] Update to Xcode 9 Beta 1

- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.TVOS.ObjCBinding.CSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.ObjCBinding.CSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.ObjCBinding.CSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Tasks.Core.csproj
- tests/bindings-test/bindings-test.csproj
- tests/common/ConditionalCompilation.cs
- tests/monotouch-test/monotouch-test.csproj
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=57764
> [msbuild] Don't define __IOS__ for tvOS binding projects

- src/generator.cs
Generator diff (no change): https://gist.github.com/rolfbjarne/02444b88124a0fda857f10745f6ffc40
> [generator] Fix a few BindAs typos.

- src/ARKit/ARPointCloud.cs
This fails on my mono, and the code looks wrong, so I'm not sure how it compiles anywhere.
> [ARKit] Fix compiler error.

- src/generator.cs
Diff: https://gist.github.com/rolfbjarne/11f60b56f72a5f6093674ae4b7c3e6d2
> [generator] Print nicer type names.

- Make.config
- src/homekit.cs
- tests/common/TestRuntime.cs
- tests/introspection/iOS/iOSApiCtorInitTest.cs
- tests/introspection/iOS/iOSApiProtocolTest.cs
- tests/monotouch-test/AddressBookUI/AddressFormattingTest.cs
- tests/monotouch-test/MediaPlayer/VolumeViewTest.cs
- tests/monotouch-test/Security/TrustTest.cs
- Updated Visual Studio max version in Make.config.
- Fixed iOS introspection tests.
> Bump to Xcode 9 beta 3

- src/AppKit/Enums.cs
- src/AppKit/NSApplication.cs
- src/AppKit/NSComboBox.cs
- src/AppKit/NSTextContainer.cs
- src/CoreGraphics/CGPDFOperatorTable.cs
- src/CoreImage/CIFilter.cs
- src/Foundation/Enum.cs
- src/Foundation/NSItemProvider.cs
- src/Foundation/NSObject.mac.cs
- src/Security/Enums.cs
- src/appkit.cs
- src/avfoundation.cs
- src/corebluetooth.cs
- src/foundation.cs
- src/gamekit.cs
- src/scenekit.cs
- src/webkit.cs
They were not run on bots due to an SDK issue.
> Xcode9 - Fix many "typo" test failures on macOS 10.13

- docs/website/Makefile
- docs/website/binding_objc_libs.md
- docs/website/binding_types_reference_guide.md
- docs/website/generator-errors.md
- docs/website/mmp-errors.md
- docs/website/mtouch-errors.md
- docs/website/xamarin-analysis-doc-tool/xamarin-analysis-doc.cs
- docs/website/xamarin-ios-analysis.md
update docs to match publishing standards - to be reviewed
> [docs] xamarin now requires markdown+yaml

- src/mapkit.cs
Add support for `[RequiresSuper]` filed in
https://bugzilla.xamarin.com/show_bug.cgi?id=58350
> [mapkit] Update for beta 4

- tests/mtouch/MTouch.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=57831
> [tests] Add the HFS+ equivalent of a memory barrier. Fixes #57831.

- src/Security/SslContext.cs
- src/Security/Tls/AppleTlsContext.cs
- Major leak will be fixed in https://github.com/mono/mono/pull/5300
- https://bugzilla.xamarin.com/show_bug.cgi?id=56814
> Fix a few minor memory leaks in AppleTLS

- Make.config
Fix this build problem when running make from somewhere in maccore:
> fatal: '../../../xamarin-macios/Make.config' is outside repository
> fatal: '../../../xamarin-macios/Make.config' is outside repository
> Pass --git-dir to git when calculating commit distance.

- tests/xharness/Simulators.cs
30 seconds should be enough for both.
> [xharness] Add a timeout for loading simulators/devices.

- tools/mmp/driver.cs
- tools/mtouch/Target.cs
- https://bugzilla.xamarin.com/show_bug.cgi?id=58574
> Pass -Wunguarded-availability-new to quiet a new clang warning

- tests/mmptest/src/MMPTest.cs
- Test for https://bugzilla.xamarin.com/show_bug.cgi?id=58296
- Was fixed via https://github.com/xamarin/xamarin-macios/commit/e6c8223a8e6bf7ebde17e55e0f47a241dd09f855 already
> [macos] Add system dynamic mmp test

- tests/xharness/Jenkins.cs
- tests/xharness/Simulators.cs
This speeds the launch up a little bit.
> [xharness] Load simulators and devices in parallel.

- src/appkit.cs
- https://bugzilla.xamarin.com/show_bug.cgi?id=58653
> [macos] NSApplication.Terminate should allow null

- tests/xharness/Harness.cs
- tests/xharness/Jenkins.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=58348
> [xharness] watchOS tests need to run in a clean environment. Works around #58348.

- src/UIKit/UITypes.cs
- src/foundation.cs
- src/generator-typemanager.cs
- src/generator.cs
- src/uikit.cs
- tests/monotouch-test/UIKit/DirectionalEdgeInsetsTest.cs
- tests/monotouch-test/monotouch-test.csproj
- Add NSDirectionalEdgeInsets type.
- Includes DirectionalEdgeInsetsTest.
> [uikit] UIView/UIScrollView/UIViewController up to Xcode 9 beta 4

- tests/monotouch-test/SceneKit/NodeTest.cs
> [tests] Remove workaround for radar #32688391.

- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.msbuild.targets
- tests/mmptest/src/MMPTest.cs
- https://bugzilla.xamarin.com/show_bug.cgi?id=58703
- Was broken on msbuild but undetected due to https://bugzilla.xamarin.com/show_bug.cgi?id=53164
> [macos] System mono should resolve non-XM libraries from system

- src/Foundation/Enum.cs
- src/Foundation/NSMetadataItem.cs
- src/Foundation/NSProgress.cs
- src/foundation.cs
- src/frameworks.sources
- src/generator.cs
- src/mapkit.cs
- src/uikit.cs
- tests/introspection/ApiProtocolTest.cs
- tests/introspection/ApiTypoTest.cs
- tests/introspection/Mac/MacApiCtorInitTest.cs
- tests/introspection/Mac/MacApiSelectorTest.cs
- tests/introspection/iOS/iOSApiSelectorTest.cs
- tests/monotouch-test/Foundation/UrlSessionTaskTest.cs
Includes betas 1-5.
Rebased from https://github.com/xamarin/xamarin-macios/pull/2235 after accidentally pulling some extra commits into that PR
> [Foundation] Update for xcode9

- src/wkwebkit.cs
- https://bugzilla.xamarin.com/show_bug.cgi?id=58758
> [macos] Add WKUIDelegate runOpenPanelWith bindings

- src/wkwebkit.cs
- https://bugzilla.xamarin.com/show_bug.cgi?id=58758
> [macos] Add WKUIDelegate runOpenPanelWith bindings (#2495)

- docs/website/mtouch-errors.md
- tests/mtouch/MTouch.cs
- tools/common/Driver.cs
- tools/mmp/driver.cs
- tools/mtouch/mtouch.cs
Also add tests.
https://bugzilla.xamarin.com/show_bug.cgi?id=58849
> [mtouch] Print verbosity using an invariant culture. Fixes #58849.

- src/UIKit/UIEnums.cs
- src/uikit.cs
- UIKeyCommand
- UINavigationBar
- UINavigationItem
- UIPasteboard
- UITableViewHeaderFooterView
> [uikit] Update for Xcode 9 beta 5 - Part 3

- src/coredata.cs
This seems to revert some nullability changes from beta 5.
> [coredata] Update to beta 6

- src/coreml.cs
Fix our rdar 33643011 where additional setters were added in the headers
but did not exists.
> [coreml] Update to beta 6

- src/videosubscriberaccount.cs
- tests/introspection/ApiProtocolTest.cs
Only b1 and b2 introduced some additions/changes
> [videosubscriberaccount] Update to beta 6

- tests/xharness/Harness.cs
It works fine for me locally, so let's see what Jenkins says.
> [xharness] Re-enable the watchOS tests.

- src/ARKit/ARPointCloud.cs
- src/arkit.cs
- tests/monotouch-test/ARKit/ARPointCloudTest.cs
- tests/monotouch-test/monotouch-test.csproj
- Add last missing selector.
- Add tests for manual code.
> [arkit] Update for Xcode 9 beta 5 - Part 2

- src/foundation.cs
- src/uikit.cs
As suggested here: https://github.com/xamarin/xamarin-macios/pull/2527#discussion_r134670981
> [foundation/uikit] Inline NSItemProvider_UIKitAdditions in NSItemProvider

- src/UIKit/UIEnums.cs
- src/uikit.cs
- tests/introspection/iOS/iOSApiProtocolTest.cs
Bindings for the following headers:
-  UIActivity.h
-  UIActivityItemProvider.h
-  UIAlertController.h
-  UIApplication.h
-  UIBarButtonItem.h
-  UIButton.h
-  UICollectionViewLayout.h
-  UIColor.h
-  UIControl.h
-  UIDocumentMenuViewController.h
-  UIFontMetrics.h
-  UIGestureRecognizer.h
-  UIGraphicsImageRenderer.h
-  UIInputViewController.h
> [uikit] Update for Xcode 9 - Part 5

- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.props
PR for adding support for the filtering in msbuild:
https://github.com/mono/msbuild/pull/23
> [mac][msbuild] Opt-in to filtering out denied assemblies

- src/coreml.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=58097
> [coreml][watchos] Enable API using CoreVideo on watchOS. Fix #58097

- tests/Makefile
- tests/xharness/Harness.cs
- tests/xharness/Jenkins.cs
- tests/xharness/Program.cs
This is useful for VSTS, which allows for showing a file in markdown format on
the front page of a build.
> [xharness] Add support for writing a summary in markdown format.

- src/uikit.cs
- Fixes introspection tests on tvOS 10.
> [uikit] Fix UIColor and UIInputViewController tvOS availability

- src/storekit.cs
- Fixes introspection tests on tvOS 10.
> [storekit] Fix SKCloudServiceSetupMessageIdentifier and SKProductStorePromotionController tvOS availability

- src/coredata.cs
reference:
https://trello.com/c/dlSRYPFx
> [coredata] Enable new fields since rdar #33878590 is fixed w/beta 6

- tests/xtro-sharpie/xtro-sharpie.csproj
Without this you can't debug using the custom configurations.
> [xtro] Fix StartWorkingDirectory to enable debugging

- src/UIKit/UIEnums.cs
- src/foundation.cs
- src/uikit.cs
- tests/introspection/iOS/iOSApiProtocolTest.cs
- tests/xtro-sharpie/ios.ignore
- tests/xtro-sharpie/ios.pending
- tests/xtro-sharpie/tvos.pending
NSAttributedString.h
NSFileProviderExtension.h
NSLayoutAnchor.h
UIAccessibility.h
UIAccessibilityAdditions.h
UIAccessibilityContainer.h
UIAccessibilityContentSizeCategoryImageAdjusting.h
UIAccessibilityCustomRotor.h
UIAccessibilityLocationDescriptor.h
UITabBar.h
UINavigationBar.h
UIScreen.h
> [uikit] Update for Xcode 9 - Part 6

- src/CoreImage/Enums.cs
- src/coreimage.cs
- tests/introspection/ApiTypoTest.cs
- tests/introspection/iOS/iOSApiSelectorTest.cs
- tests/xtro-sharpie/Helpers.cs
- tests/xtro-sharpie/common.pending
Filters are not complete (ref: #57350)
https://bugzilla.xamarin.com/show_bug.cgi?id=57350
> [coreimage] Add new headers API up to beta 6

- src/metal.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=58054
> [Metal] Implement API using IOSurface now that IOSurface is implemented. Partially fixes #58054.

- runtime/bindings-generator.cs
- src/ARKit/ARPointCloud.cs
- src/ModelIO/MIEnums.cs
- src/Simd/MatrixFloat2x2.cs
- src/Simd/MatrixFloat3x3.cs
- src/Simd/MatrixFloat4x4.cs
- src/Simd/VectorFloat2.cs
- src/Simd/VectorFloat3.cs
- src/Simd/VectorFloat4.cs
- src/Simd/VectorInt4.cs
- src/Vision/VNUtils.cs
- src/arkit.cs
- src/frameworks.sources
- src/spritekit.cs
- src/vision.cs
- tests/monotouch-test/ARKit/ARPointCloudTest.cs
- tests/monotouch-test/Asserts.cs
- tests/monotouch-test/Simd/VectorFloat2Test.cs
- tests/monotouch-test/Simd/VectorFloat3Test.cs
- tests/monotouch-test/Simd/VectorFloat4Test.cs
- tests/monotouch-test/Simd/VectorInt4Test.cs
- tests/monotouch-test/SpriteKit/SKTransformNodeTest.cs
- tests/monotouch-test/monotouch-test.csproj
Also use the new simd vector types in SpriteKit/ARKit/Vision.
> Implement Simd vector types (VectorFloat2/3/4/VectorInt4).

- tools/common/Frameworks.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=59333
> [mtouch] Teach mtouch about the 'IOSurface' framework for tvOS. Fixes #59333.

- src/Security/SslContext.cs
- src/Security/Tls/AppleTlsContext.cs
- Major leak will be fixed in https://github.com/mono/mono/pull/5300
- https://bugzilla.xamarin.com/show_bug.cgi?id=56814
> Fix a few minor memory leaks in AppleTLS (#2403)

- tests/common/mac/ProjectTestHelpers.cs
- tests/common/mac/XM45Example.csproj
- tests/mmptest/mmptest.csproj
- tests/mmptest/src/NetStandardTests.cs
- Disabled for now due to https://bugzilla.xamarin.com/show_bug.cgi?id=53164
> macOS tests for NetStandard2 support

- tests/common/mac/NetStandard/Class1.cs
- tests/common/mac/NetStandard/NetStandardLib.csproj
- 5df88694326bb2a94c5116f4be75805ab03438a0 did not include these files
- Since the test was disabled we did not notice
> Add missing netstandard test files

- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.props
PR for adding support for the filtering in msbuild:
https://github.com/mono/msbuild/pull/23
> [mac][msbuild] Opt-in to filtering out denied assemblies (#2482)

- src/appkit.cs
- https://bugzilla.xamarin.com/show_bug.cgi?id=59635
> Add [NullAllowed] to NSWindow.Toolbar

- tests/xharness/Simulators.cs
Based on local experiments, sometimes it takes over a minute now 😞
> [xharness] Bump the device listing timeout to 2 minutes.

- src/appkit.cs
NSApplicationLaunchUserNotificationKey is missing
This replaces PR #2765
> Fix bug 58243 new PR

- docs/website/mtouch-errors.md
Remove duplicated MT4171/MT4172 documentation, and fix some formatting to be proper markdown.
> [docs] Fix doc formatting.

- Make.config
The previous one was a pretty old 5.4 build by now.
> Bump min Mono version to 5.4.0.201

- Make.config
> [d15-5] Bump min Mono version to 5.4.0.201

- src/AudioUnit/AudioComponent.cs
- src/Constants.mac.cs.in
- src/Foundation/NSObject.mac.cs
- src/corebluetooth.cs
- src/externalaccessory.cs
- src/foundation.cs
- src/safariservices.cs
- src/spritekit.cs
- src/wkwebkit.cs
- tests/apitest/src/EveryFrameworkSmokeTest.cs
- tests/introspection/ApiTypoTest.cs
- tests/introspection/Mac/MacApiCtorInitTest.cs
- tests/introspection/Mac/MacApiFieldTest.cs
- tests/introspection/Mac/MacApiProtocolTest.cs
- tests/introspection/Mac/MacApiWeakPropertyTest.cs
- tools/common/StaticRegistrar.cs
- tools/linker/ObjCExtensions.cs
- tools/mmp/linker/MonoMac.Tuner/MonoMacNamespaces.cs
- Cherry pick https://github.com/xamarin/xamarin-macios/pull/2815 to d15-5
> Fix a number of introspection test failures on 10.13 (#2815)

- msbuild/Xamarin.MacDev.Tasks/Tasks/GetPropertyListValue.cs
Spotted this while auditing code...
> [msbuild] Properly subclass GetPropertyListValueTaskBase

- tools/common/StaticRegistrar.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=59965
> [registrar] Fix casing of PDFKit's header path. Fixes #59965.

- src/replaykit.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=60068
Fixes introspection tests cused by API differences between beta 1 and beta 2
> [ReplayKit] Update to Xcode 9.1 Beta 2 & also Fixes bug #60068

- src/Security/Tls/AppleCertificateHelper.cs
https://github.com/xamarin/xamarin-macios/pull/2850 for XM
> Fix AppleTLS SecTrustResult by cherry picking fix + bump mono d15-4

- .gitmodules
Updated reference to mono/mono@fbc487f 
https://github.com/mono/mono/compare/9b466abc495c3c4af9146de7a4f3a202fe878230...2017-06
> Updated reference to mono/mono@fbc487f

- tests/xharness/Jenkins.cs
This isn't meant to be accurate, just more helpful than not showing anything at all in the test summary.
> [xharness] Try to guess a failure reason by parsing the run log.

- src/avfoundation.cs
- src/foundation.cs
- src/networkextension.cs
> Remove annoying warnings CS0105, CS0109 and CS0618 from our builds

- src/CoreText/Adapter.cs
- src/CoreText/CTFont.cs
- src/CoreText/CTFontManager.cs
- src/CoreText/CTStringAttributes.cs
- src/coretext.cs
- tests/introspection/ApiTypoTest.cs
Adds what is new to Xcode 9
All 4CC codes were generated with this tool https://gist.github.com/dalexsoto/7f1bbab252672b14f819 as always :D
> [CoreText] Adds API bindings from Xcode 9 Beta 1 to stable

- tools/mmp/driver.cs
- https://bugzilla.xamarin.com/show_bug.cgi?id=60294
> [macos][mmp] Update mmp's help to note registrar and fix aot mistake

- src/UIKit/UIGestureRecognizer.cs
It's not necessary to manually preserve these classes, since they will be
preserved if they're used, and if they're not used, then they're not needed.
The `Conditional = true` parameter suggests the original intent was for the
linker to magically figure out when to link away these classes, but the
Conditional parameter is ignored for classes (conditional on what exactly?),
so these classes were never linked away.
These classes all have manually exported `Activated` methods, and for these
methods the `[Preserve]` attribute is required (and already present).
This saves ~23kb (Release) / ~31kb (Debug) for a minimalistic test app
(details below).
Size comparison
===============
Test project: https://github.com/rolfbjarne/TestApp/tree/minimalistic-test-app …
> [UIKit] Remove [Preserve] attributes from various classes related to gesture recognizers.

- Make.config
This builds and works fine for me locally.
> bumped max Mono version to 5.8.99

- tests/Makefile
- tests/bcl-test/Mono.CSharp/Info-mac.plist
- tests/bcl-test/Mono.CSharp/Info.plist
- tests/bcl-test/Mono.CSharp/Makefile
- tests/bcl-test/Mono.CSharp/Mono.CSharp-mac.csproj.template
- tests/bcl-test/Mono.CSharp/Mono.CSharp.csproj.template
- tests/xharness/Harness.cs
This branch needs PR https://github.com/mono/mono/pull/5875 to land to get the tests passing/ignored on iOS. We need to look at how to deal with this on TVOS.
> [XHarness] Add Mono.CSharp tests on ios.

- tests/common/ExecutionHelper.cs
- tests/mtouch/MTouch.cs
- tests/mtouch/MTouchTool.cs
- tests/mtouch/RegistrarTest.cs
This amounts to running the MT4162 test with the linker enabled.
https://bugzilla.xamarin.com/show_bug.cgi?id=59617
> [tests][mtouch] Add test case for bug #59617.

- tests/xharness/Log.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=59208
> [xharness] Try to fix apparently impossible infinite loop. Might fix bug #59208.

- src/passkit.cs
- tests/introspection/ApiTypoTest.cs
Update (again) a typo in a constant
> [passkit] Update up to Xcode 9.2 beta 2

- src/generator.cs
- tests/generator/ErrorTests.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=57804
generator diff: https://gist.github.com/dalexsoto/f66bd7679aa7af3f4b70737a9bf82058
> [generator] Fix slightly incorrect error message when trying to use ref/out parameters with BindAs attributes, fixes 57804.

- docs/website/binding_types_reference_guide.md
- docs/website/generator-errors.md
- src/generator.cs
- tests/generator/ErrorTests.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=57094
Build diff: https://gist.github.com/dalexsoto/c2e5392caebd041352d80dc4761b7e9b
> [generator] Improve BI1014 - include name of unsupported field and update valid types on docs, fixes bug 57094.

- tests/Makefile
- tests/xharness/Harness.cs
- tests/xharness/Jenkins.cs
- tests/xharness/Log.cs
- tests/xharness/Program.cs
This means running all the tests in a single step with xharness, which means
we'll run the tests much faster, because xharness supports parallel
build/execution of tests, as well as executing simulator tests in the optimal
order (by grouping tests in the same simulator, so the simulator doesn't have
to be cleaned/reset between every test).
Example of how this will look like: https://wrench.internalx.com/Wrench/ViewLane.aspx?lane_id=4189&host_id=379&revision_id=920382
Additionally the html report will be uploaded/updated every 10 minutes while the tests are running, which means it's possible to view the progress during the test run.
> [tests] Run the tests on Wrench like we do on Jenkins.

- mk/versions.mk
This will also tell you nicely if you're missing it.
> Enforce the right macios-binaries hash.

- src/coreanimation.cs
- tests/introspection/Mac/MacApiCtorInitTest.cs
- tests/introspection/Mac/MacApiProtocolTest.cs
- Cherry pick #3065 to xcode 9.2
> Fix test failures on 10.13 (#3065)

- src/appkit.cs
- src/uikit.cs
- https://bugzilla.xamarin.com/show_bug.cgi?id=60935
- This allows subclassing to work
> [macOS] NSGestureRecognizer.State should be get/set like UIKit's

- Make.config
- src/StoreKit/Enums.cs
- src/storekit.cs
[storekit] Update for Xcode 9.2 final.
> Bump to xcode 9.2 final

- tools/install-source/Makefile
The build is too noisy. Lets reduce the verbosity since we know that the tool works fine.
> [Tools] Reduce the verbosity of install sources which is in debugging mode

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ACToolTaskBase.cs
- msbuild/tests/Bug60536/AppDelegate.cs
- msbuild/tests/Bug60536/Assets.xcassets/AppIcon.appiconset/Contents.json
- msbuild/tests/Bug60536/Assets.xcassets/AppIcon.appiconset/Contents.json~
- msbuild/tests/Bug60536/Assets.xcassets/Contents.json
- msbuild/tests/Bug60536/Bug60536.csproj
- msbuild/tests/Bug60536/Bug60536.sln
- msbuild/tests/Bug60536/Entitlements.plist
- msbuild/tests/Bug60536/Info.plist
- msbuild/tests/Bug60536/LaunchScreen.storyboard
- msbuild/tests/Bug60536/Main.cs
- msbuild/tests/Bug60536/Main.storyboard
- msbuild/tests/Bug60536/ViewController.cs
- msbuild/tests/Bug60536/ViewController.designer.cs
- msbuild/tests/Xamarin.iOS.Tasks.Tests/ProjectsTests/Bug60536.cs
- msbuild/tests/Xamarin.iOS.Tasks.Tests/Xamarin.iOS.Tasks.Tests.csproj
This is in response to https://bugzilla.xamarin.com/show_bug.cgi?id=60536
> [msbuild] Catch json parser exceptions to provide better error reporting

- src/appkit.cs
- https://bugzilla.xamarin.com/show_bug.cgi?id=61101
> [macos] NSView.LocationInView should accept null

- src/CoreGraphics/CGPath.cs
- tests/monotouch-test/CoreGraphics/PathTest.cs
Fixes issue https://github.com/xamarin/xamarin-macios/issues/3089
> [CoreAnimation] Ensure that we increase the handle refenrece count in MakeMutable. Fixes #3089

- src/AppKit/ActionDispatcher.cs
https://github.com/xamarin/xamarin-macios/pull/3091 with an additional [Preserve]
> Fix behaviour of NSMenuItem.Activated on top of modal windows.

- src/AVFoundation/AVAssetDownloadStorageManagementPolicy.cs
- src/AVFoundation/AVPlayerItem.cs
- src/AVFoundation/Enums.cs
- src/avfoundation.cs
- src/frameworks.sources
- tests/xtro-sharpie/common-AVFoundation.ignore
- tests/xtro-sharpie/iOS-AVFoundation.ignore
- tests/xtro-sharpie/macOS-AVFoundation.ignore
- tests/xtro-sharpie/macOS-AVFoundation.todo
- tests/xtro-sharpie/tvOS-AVFoundation.todo
xtro data files updated
reference:
https://bugzilla.xamarin.com/show_bug.cgi?id=60924
> [avfoundation] Add some missing API detected by xtro. Also fix #60924

- docs/website/mmp-errors.md
- docs/website/mtouch-errors.md
- tests/common/mac/ProjectTestHelpers.cs
- tests/mmptest/src/MMPTest.cs
- tools/common/Application.cs
- tools/mmp/Application.cs
- tools/mtouch/Application.cs
Return a build error if Deployment Target is too low
Add an mmptest for the change
> [MMP][60534] MMP Should check that Deployment Target is not below min version

- src/Photos/Enums.cs
- src/medialibrary.cs
- tests/xtro-sharpie/Helpers.cs
- tests/xtro-sharpie/macOS-MediaLibrary.todo
- tests/xtro-sharpie/macOS-Photos.todo
> [macos][photos] Add some missing error codes and constants for XM

- src/gameplaykit.cs
- tests/xtro-sharpie/macOS-GameplayKit.todo
> [macos][gameplaykit] Add missing 'unapplyGameModelUpdate:' API for XM

- tests/monotouch-test/ExternalAccessory/AccessoryManagerTest.cs
- tests/monotouch-test/GameplayKit/GKAgent3DTest.cs
- tests/monotouch-test/MetalPerformanceShaders/KernelTest.cs
- tests/monotouch-test/MetalPerformanceShaders/MPSImageHistogramEqualizationTest.cs
- tests/monotouch-test/MetalPerformanceShaders/MPSImageHistogramSpecificationTest.cs
- tests/monotouch-test/MetalPerformanceShaders/MPSImageHistogramTest.cs
- tests/monotouch-test/Photos/LivePhotoEditingContextTest.cs
- tests/monotouch-test/SceneKit/GeometrySourceTest.cs
Largely related to somewhat recent frameworks/API additions to XM
> [tests][macos] Enable more tests to be executed on macOS (XM)

- tools/linker/MonoTouch.Tuner/MonoTouchTypeMap.cs
Caching the result of checking whether a type is a CIFilter or not in a
dictionary makes the total time spent in the method go down to approximately a
third (11ms to 3ms) when linking monotouch-test on my machine.
> [linker] Speed up checking for CIFilter subclass.

- src/CoreGraphics/CGPath.cs
- tests/monotouch-test/CoreGraphics/PathTest.cs
backporting https://github.com/xamarin/xamarin-macios/pull/3228
> [CoreGraphics] Fix issue with the MakeMutable in CGPath where ref count was leaking. (#3228)

- src/generator.cs
- tests/generator/BGenTests.cs
- tests/generator/bug57531.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=57531
Adds support for [Async] inside categories.
Build diff: https://gist.github.com/dalexsoto/3a414cb7289ad442cf2e685b5dfc9895
> [generator] Support [Async] inside categories, fixes bugzilla #57531

- src/MediaToolbox/MTProfessionalVideoWorkflow.cs
- src/frameworks.sources
- tests/monotouch-test/MediaToolbox/ProfessionalVideoWorkflowTest.cs
- tests/xtro-sharpie/macOS-MediaToolbox.todo
- added unit test (not much to test)
- xtro data updated
> [macos][mediatoolbox] Add a macOS specific API for XM

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DetectSigningIdentityTaskBase.cs
Backport of https://github.com/xamarin/xamarin-macios/pull/3262
> [msbuild] Add missing {1} in LogMessage

- tests/mtouch/MTouch.cs
- tools/mtouch/Makefile
Fixes https://github.com/xamarin/xamarin-macios/issues/3265.
> [mtouch] Make sure the xamarin_localized_string_format* functions are available in simlauncher. Fixes #3265.

- tests/mtouch/MTouch.cs
Simplify/refactor code to fetch symbols from a binary to reuse an existing
function instead of manually calling `nm` every time.
> [tests][mtouch] Simplify code to fetch symbols from a binary (nm).

- docs/website/Makefile
- docs/website/mmp-errors.md
- docs/website/mtouch-errors.md
- docs/website/optimizations.md
* Show final link to official documentation in error help.
* Add makefile targets to copy docs to the documentation repo.
> Update docs about build optimizations.

- src/avkit.cs
- tests/xtro-sharpie/tvOS-AVKit.todo
Diff files:
- https://github.com/xamarin/xamarin-macios/wiki/AVKit-tvOS-xcode9.3-beta1
> [AVKit] Update to Xcode 9.3 Beta 1

- docs/website/mmp-errors.md
- docs/website/mtouch-errors.md
- tools/common/Application.cs
- tools/common/CoreResolver.cs
- tools/common/StaticRegistrar.cs
- tools/mmp/driver.cs
- tools/mmp/resolver.cs
By convention, the first assembly is the target platform assembly
> [Mmp] Allow multiple assemblies to be passed to generate the registrar

- docs/website/mtouch-errors.md
- src/Makefile.generator
- src/ObjCRuntime/BindingImplAttribute.cs
- src/frameworks.sources
- src/generator-enums.cs
- src/generator-filters.cs
- src/generator.cs
- tests/introspection/ApiTypoTest.cs
- tests/linker-ios/link sdk/OptimizeGeneratedCodeTest.cs
- tools/common/Driver.cs
- tools/linker/CoreMarkStep.cs
- tools/linker/CoreOptimizeGeneratedCode.cs
- tools/linker/CoreRemoveAttributes.cs
- tools/linker/MobileExtensions.cs
- tools/linker/MonoTouch.Tuner/PreserveSmartEnumConversionsSubStep.cs
- tools/mmp/Makefile
- tools/mmp/mmp.csproj
- tools/mtouch/Makefile
- tools/mtouch/mtouch.csproj
Add a [BindingImpl] attribute, and change the linker to look for it to search
for optimizable code.
> Add a BindingImpl attribute and use to to teach the linker look for it to search for optimizable code.

- tests/xharness/Jenkins.cs
Partial backport/adaptation of
https://github.com/xamarin/xamarin-macios/commit/8d854a0f3d
> [xharness] Backport the xharness changes needed to produce html reports by xtro on bots

- src/pdfkit.cs
Api diff:
- https://github.com/xamarin/xamarin-macios/wiki/PDFKit-iOS-xcode9.3-beta1
> [PDFKit] Update bindings to Xcode 9.3 Beta 1

- src/safariservices.cs
- tests/xtro-sharpie/macOS-SafariServices.todo
Api diff:
- https://github.com/xamarin/xamarin-macios/wiki/SafariServices-macOS-xcode9.3-beta1
> [SafariServices] Update to Xcode 9.3 Beta 1

- src/iAd/iAd.cs
Diff files:
* https://github.com/xamarin/xamarin-macios/wiki/iAd-iOS-xcode9.3-beta1
> [iAd] Update bindings to Xcode 9.3 Beta 1

- src/MediaPlayer/MPVolumeSettings.cs
- src/mediaplayer.cs
Diff files:
* https://github.com/xamarin/xamarin-macios/wiki/MediaPlayer-iOS-xcode9.3-beta1
* https://github.com/xamarin/xamarin-macios/wiki/MediaPlayer-tvOS-xcode9.3-beta1
> [MediaPlayer] Update bindings to Xcode 9.3 Beta 1

- src/wkwebkit.cs
- tests/xtro-sharpie/iOS-WebKit.todo
- tests/xtro-sharpie/macOS-WebKit.todo
- All of the various NSSecureCoding were already handled by our code
- https://github.com/xamarin/xamarin-macios/wiki/WebKit-iOS-xcode9.3-beta1 and https://github.com/xamarin/xamarin-macios/wiki/WebKit-macOS-xcode9.3-beta1
> [WKWebKit] Update to Xcode 9.3 Beta 1

- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
> [msbuild] Always codesign libraries and frameworks

- src/videotoolbox.cs
- tests/xtro-sharpie/iOS-VideoToolbox.ignore
- tests/xtro-sharpie/iOS-VideoToolbox.todo
- tests/xtro-sharpie/macOS-VideoToolbox.todo
- tests/xtro-sharpie/tvOS-VideoToolbox.ignore
- tests/xtro-sharpie/tvOS-VideoToolbox.todo
- tests/xtro-sharpie/watchOS-VideoToolbox.ignore
- https://github.com/xamarin/xamarin-macios/wiki/VideoToolbox-iOS-xcode9.3-beta1
> [VideoToolbox] Update to Xcode 9.3 Beta 1

- tests/linker-ios/dont link/dont link.csproj
- tests/xharness/Harness.cs
- tests/xharness/Jenkins.cs
- tests/xharness/TestProject.cs
This also requires a few csproj and xharness tweaks.
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=53181.
> [tests] Run dont link, link all and link sdk tests in both Debug and Release in the simulator. Fixes #53181.

- src/generator.cs
Generator diff: https://gist.github.com/rolfbjarne/269ab7f24060ccd844fa1c140f43fec8
> [generator] The generated block code is also generated, so add the corresponding attributes.

- tests/linker/ios/link sdk/OptimizeGeneratedCodeTest.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/3395.
> [tests] Tweak the new IntPtrSizeTest for release builds. Fixes #3395.

- tests/xtro-sharpie/iOS-PassKit.ignore
- tests/xtro-sharpie/iOS-PassKit.todo
> [xtro][passkit] Clean xtro todo for a missing designated initializer

- src/webkit.cs
- src/wkwebkit.cs
- tests/xtro-sharpie/macOS-WebKit.todo
Fix remaining xtro todo on webkit
> [webkit] Add NSUserInterfaceValidations conformance to WebView and WKWebView

- src/appkit.cs
- tests/xtro-sharpie/macOS-AppKit.todo
https://github.com/xamarin/xamarin-macios/wiki/AppKit-macOS-xcode9.3-beta2
> [Appkit] Update to Xcode 9.3 beta 2

- src/StoreKit/StoreProductParameters.cs
- src/storekit.cs
- tests/xtro-sharpie/iOS-StoreKit.todo
- tests/xtro-sharpie/tvOS-StoreKit.todo
Diff file
- https://github.com/xamarin/xamarin-macios/wiki/StoreKit-iOS-xcode9.3-beta2
> [StoreKit] Update to Xcode 9.3 Beta 2

- tests/xharness/ProjectFileExtensions.cs
Fixes various build errors in the System.IdentityModel,
System.IO.Compression[.FileSystem], System.Security and System.ServiceModel
tests.
> [xharness] Fixing cloning of XM projects with custom elements.

- src/Foundation/Enums.cs
- src/foundation.cs
- tests/monotouch-test/Foundation/NSLinguisticAnalysisTest.cs
- tests/xtro-sharpie/common-Foundation.ignore
Fixes bug https://bugzilla.xamarin.com/show_bug.cgi?id=35009
> [Foundation] Add missing NSLinguisticAnalysis category. Fixes 35009.

- tests/xtro-sharpie/macOS-FinderSync.ignore
- tests/xtro-sharpie/macOS-FinderSync.todo
This depends on https://github.com/xamarin/xamarin-macios/pull/2315
> [FinderSync] Fix xtro output

- src/metalkit.cs
- tests/xtro-sharpie/macOS-MetalKit.todo
Backport of https://github.com/xamarin/xamarin-macios/pull/3561
> [metalkit] Add 'MTKTextureLoader' missing bindings (fix xtro) (#3561)

- docs/website/mmp-errors.md
- docs/website/mtouch-errors.md
- tests/mmptest/src/MMPTest.cs
- tools/mmp/driver.cs
- https://github.com/xamarin/xamarin-macios/issues/3325
> Warn when building 32-bit macOS applications

- docs/website/mmp-errors.md
- docs/website/mtouch-errors.md
- tests/mmptest/src/MMPTest.cs
- tools/mmp/driver.cs
- https://github.com/xamarin/xamarin-macios/issues/3325
> [d15-7] Warn when building 32-bit macOS applications (#3564)

- src/appkit.cs
- https://github.com/xamarin/xamarin-macios/issues/3686
> Fix missing [NullAllowed] on NSWindow.FieldEditor

- .gitmodules
> Fixed target branch for llvm

- tests/monotouch-test/CoreMidi/MidiThruConnectionTests.cs
https://github.com/xamarin/xamarin-macios/pull/3696#pullrequestreview-102346431
> [monotouch-test] Enhance MidiThruConnectionTests.FindTest from #3696 comments

- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.props
- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.CSharp.props
- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.CSharp.targets
- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.Common.props
- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.Common.targets
- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.TargetFrameworkFix.targets
- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Tasks.csproj
- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.xbuild.targets
- tests/bindings-test/ApiDefinition.cs
- tests/bindings-test/ApiProtocol.cs
- tests/common/mac/ProjectTestHelpers.cs
- tests/mmptest/mmptest.csproj
- tests/mmptest/src/BindingProjectTests.cs
- tests/mmptest/src/MMPTest.cs
- tests/mmptest/src/NativeReferencesTests.cs
- tests/test-libraries/testgenerator.cs
- https://github.com/xamarin/xamarin-macios/issues/3608
- Refactor and clean up msbuild to be more consistent between binding and "normal" workloads
- Comment on the inconsistencies that are too large to fix in one PR
- Write some actual tests for binding projects to detect regressions
- Due to lack of redirect support these tests are only xbuild current, but I ran tests with msbuild to validate locally
> [macOS][msbuild] Fix binding projects under Full to resolve to correct libs

- tests/introspection/Mac/MacCoreImageFiltersTest.cs
- tests/monotouch-test/CoreMidi/MidiThruConnectionTests.cs
- tests/monotouch-test/Foundation/NSDataTest.cs
> [tests] Backport test fixes so bots don't report them on every backports

- src/Security/SecAccessControl.cs
> [security] Adding new SecAccessControlCreateFlags

- tests/linker/ios/link sdk/LinkSdkRegressionTest.cs
Also improve corresponding asserts to show the actual/expected values.
> [link sdk] Tweak test to work when running as an extension.

- src/appkit.cs
Fixes xamarin/xamarin-macios#3776
> [AppKit] Adds [NullAllowed] to NSTableView.RegisterNib

- src/Foundation/NSUrlSessionHandler.cs
Cherry-Pick from https://github.com/xamarin/xamarin-macios/pull/3731
>  [Foundation] Ensure that we do not dispose the needed data in the NSUrlSessionHandler

- tools/mtouch/Application.cs
This allows to search the path and fixes the issues we have in VS for Windows. Please create a sample app (nothing to complicated) and pass --msym as an extra parameter.
I have tested this with enviroment:
```
Microsoft Visual Studio Enterprise 2017 
Version 15.6.2
VisualStudio.15.Release/15.6.2+27428.2005
Microsoft .NET Framework
Version 4.7.02046
Installed Version: Enterprise
Visual F# Tools 10.1 for F# 4.1   00369-60000-00001-AA710
Microsoft Visual F# Tools 10.1 for F# 4.1
Application Insights Tools for Visual Studio Package   8.11.10212.1
Application Insights Tools for Visual Studio
ASP.NET and Web Tools 2017   15.0.40301.0
ASP.NET and Web Tools 2017
ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.
ASP.NET Web Frameworks and Tools 2017 …
```
> [Mtouch] Pass ShellExecute true in CopyMSymData. Fixes 3653

- jenkins/compare.sh
- jenkins/run-tests.sh
Ref: https://github.com/xamarin/xamarin-macios/pull/3855#issuecomment-378441993
> [jenkins] Don't succeed if something went wrong when creating API or generator diff.

- jenkins/.gitignore
- jenkins/build-api-diff.sh
- jenkins/build.sh
- jenkins/compare.sh
- jenkins/provision-deps.sh
- jenkins/run-tests.sh
- tests/Makefile
- tools/compare-commits.sh
* [jenkins] Create comment file for PR builds.
> [d15-7] [jenkins] Create comment file for PR builds. (#3799)

- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
> [msbuild] Fixed TargetDevice typo

- src/appkit.cs
> Fix stack overflow in NSApplication.NextEvent binding

- src/SpriteKit/ObsoleteCompat.cs
- src/SpriteKit/SKAction.cs
- src/spritekit.cs
https://github.com/xamarin/xamarin-macios/issues/3944
> [spritekit] Fix SKActionTimingFunction delegate signature. Fixes #3944

- ISSUE_TEMPLATE.md
Link back to our [Submitting Bugs & Suggestions](https://github.com/xamarin/xamarin-macios/wiki/Submitting-Bugs-&-Suggestions)
Provide link for [support[(https://www.xamarin.com/support)], i.e. help/questions that are not bugs or suggestions
Inspired by https://github.com/Microsoft/TypeScript/issues/new
> Provide some guidance on the top of our issue template

- src/btouch.cs
- tests/generator/BGenTests.cs
- tests/generator/BGenTool.cs
- More fixes for https://github.com/xamarin/xamarin-macios/issues/3948
> Teach bmac to handle reletive references, in particular -r:System.Drawing

- mk/xamarin.mk
Before:
$ make print-versions
*** mono             git@github.com:mono/mono.git                  a0228295dcef711f8bbbf4f6f619c194e109c0e6 (2018-02)
*** fsharp           git@github.com:fsharp/fsharp.git              7171700877115e2243b4edbc4e2eb88d019e02b0 (master)
*** Touch.Unit       git@github.com:spouliot/Touch.Unit.git        1c41c75983ed840e9dc7079b5d4b0c31d1565359 (master)
*** opentk           git@github.com:mono/opentk.git                396bc90c7ac2e7ce442840a5e8bd91e5e79b381e (master)
*** Xamarin.MacDev   git@github.com:xamarin/Xamarin.MacDev         2cff0d741273341d156de6ce6095808126effd3b (master)
*** guiunit          git@github.com:mono/guiunit.git               1306b0d420bd69efcd8f1951c5c68dc7065ce9eb ()
*** macios-binaries  git@github.com:xamarin/macios-binaries …
> Fix print-versions for README dependencies.

- tests/xharness/Jenkins.cs
- tests/xharness/Process_Extensions.cs
Also log any added/changed/removed environment variables for launched
processes (compared to xharness itself).
> [xharness] Improve logging of launched processes to not log the same information twice.

- tests/xharness/Simulators.cs
Things become unpredictable (and bad) otherwise.
> [xharness] Don't load simulators multiple times at the same time.

- tests/xharness/Log.cs
This should make some logs show up faster when running locally in server mode.
> [xharness] Override Flush in LogFile to implement Flush as expected.

- src/ObjCRuntime/Class.cs
While NSObject may now flag internally whether it is a custom type, this still has to be looked up each time a new instance of that type is created.
The dynamic registrar has a fast lookup for whether a type is a custom type or not, but `IsCustomType` first checks the static registrar regardless. `GetClassHandle` already caches the class handles, so this extends it to include whether or not the type is custom so then `IsCustomType` can use the cached path.
This test case is improved from `0.27ms` per to `0.09ms` per new view when using the dynamic registrar.
```csharp
public class Button
: NSView
{
public Button()
{
checkbox = new NSButton
{
AllowsMixedState = true,
ControlSize = NSControlSize.Small,
Title = string.Empty,
TranslatesAutoresizingMaskIntoConstraints = false
}; …
```
> Improve IsCustomType performance

- jenkins/compare.sh
Makes it harder to accidentially skip reviewing changes.
> [jenkins] Use different emojiis depending on the result of the api/generator diffs.

- tests/mtouch/SdkTest.cs
It seems Cecil doesn't search next to the current assembly for any assembly
references, which means that it may fail to resolve assemblies in certain
circumstances:
Failed files
Expected: <empty>
But was:
Failed to process /work/maccore/xcode10/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/lib/mono/2.1/OpenTK.dll: Failed to resolve assembly: 'monotouch, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'
Failed to process /work/maccore/xcode10/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/lib/mono/Xamarin.TVOS/OpenTK-1.0.dll: Failed to resolve assembly: 'Xamarin.TVOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'
Failed to process …
> [tests] Fix Xamarin.Linker.SdkTest.NoAssemblyReferenceInAttributes. Fixes #4241.

- src/usernotificationsui.cs
- tests/xtro-sharpie/iOS-UserNotificationsUI.todo
Diff can be found here: 
https://github.com/xamarin/xamarin-macios/wiki/UserNotificationsUI-iOS-xcode10-beta1
> [UserNotificationsUI] Update the fro Xcode 10.

- system-dependencies.sh
This is how it looks like now:
> [system-dependencies] Explain/document how to skip failing dependency checks by setting certain environment variables.

- src/AppKit/Enums.cs
- src/AppKit/NSSharingService.cs
- src/appkit.cs
- tests/xtro-sharpie/macOS-AppKit.ignore
- tests/xtro-sharpie/macOS-AppKit.todo
Also convert `NSSharingServiceName` to a smart-enum, add some missing
values and adapt helper method to use the smart-enum (future-proofing it)
> [macos][appkit] Update for beta 3

- src/healthkit.cs
- tests/xtro-sharpie/watchOS-HealthKit.todo
Somehow some of the APIs added there weren't reported as missing by xtro.
> [healthkit] Update for Xcode 10 beta 3

- src/frameworks.sources
- src/iAd/ADBannerView.cs
- src/iad.cs
- tests/monotouch-test/iAd/BannerViewTest.cs
- tests/xtro-sharpie/iOS-iAd.ignore
- tests/xtro-sharpie/iOS-iAd.todo
I'd appreciate feedback on what to do with the pinvoke I added in the ignore file. Not sure about its correct place or what to do with it.
> [iAd] Xcode 10 beta 3 support.

- src/WebKit/Enums.cs
- src/uikit.cs
- src/webkit.cs
Allso adds UIKit UIWebView deprecations
> [WebKit] Update bindings to Xcode 10 Beta 1, Nothing on beta 2 or 3

- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
- msbuild/Xamarin.MacDev.Tasks.Core/PlatformUtils.cs
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ACToolTaskBase.cs
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileSceneKitAssetsTaskBase.cs
- msbuild/Xamarin.MacDev.Tasks.Core/Xamarin.MacDev.Tasks.Core.csproj
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Fixes https://github.com/xamarin/xamarin-macios/issues/4467
> [msbuild] Xcode10 changed the copySceneKitAssets command-line arguments

- src/arkit.cs
- tests/xtro-sharpie/iOS-ARKit.ignore
- tests/xtro-sharpie/iOS-ARKit.todo
Inlined protocol member. No constructor in interfaces in C#.
> [arkit] Update for Xcode 10 beta 4

- tools/mmp/Tuning.cs
- tools/mtouch/Tuning.cs
> Pass features not available on iOS to linker

- builds/Makefile
- tests/mmptest/src/LinkerTests.cs
- tools/mmp/driver.cs
Fixes https://github.com/mono/mono/issues/9576
> Include libmono-system-native on Xamarin.Mac

- jenkins/Jenkinsfile
- tests/common/TestRuntime.cs
Implement support for slack notifications.
Notifications will only be sent when something fails, and unfortunately I wasn't able to make notifications ping due to https://github.com/jenkinsci/slack-plugin/issues/353.
> [jenkins] Implement support for slack notifications.

- src/SceneKit/SCNMatrix4.cs
In relation to https://github.com/xamarin/xamarin-macios/issues/4525, adding an "advice" to remind everyone this is a row major matrix.
> [scenekit] Add advice to SCNMatrix4

- msbuild/Xamarin.Mac.Tasks.Core/Tasks/MmpTaskBase.cs
- msbuild/Xamarin.iOS.Tasks.Core/Tasks/MTouchTaskBase.cs
- msbuild/tests/AppWithExtraArgumentThatOverrides/AppDelegate.cs
- msbuild/tests/AppWithExtraArgumentThatOverrides/AppWithExtraArgumentThatOverrides.csproj
- msbuild/tests/AppWithExtraArgumentThatOverrides/AppWithExtraArgumentThatOverrides.sln
- msbuild/tests/AppWithExtraArgumentThatOverrides/Assets.xcassets/AppIcon.appiconset/Contents.json
- msbuild/tests/AppWithExtraArgumentThatOverrides/Assets.xcassets/Contents.json
- msbuild/tests/AppWithExtraArgumentThatOverrides/Entitlements.plist
- msbuild/tests/AppWithExtraArgumentThatOverrides/Info.plist
- msbuild/tests/AppWithExtraArgumentThatOverrides/LaunchScreen.storyboard
- msbuild/tests/AppWithExtraArgumentThatOverrides/Main.cs
- msbuild/tests/AppWithExtraArgumentThatOverrides/Main.storyboard
- msbuild/tests/AppWithExtraArgumentThatOverrides/ViewController.cs
- msbuild/tests/AppWithExtraArgumentThatOverrides/ViewController.designer.cs
- msbuild/tests/Xamarin.iOS.Tasks.Tests/ProjectsTests/ResponseFileArguments.cs
- msbuild/tests/Xamarin.iOS.Tasks.Tests/Xamarin.iOS.Tasks.Tests.csproj
- tests/mmptest/src/LinkerTests.cs
- tools/mmp/driver.cs
- https://github.com/xamarin/xamarin-macios/issues/4594
- There were being adding _before_ the response file
which meant options that were overriding defaults were
not being honored
> Order additional arguments after response file

- src/Network/NWParameters.cs
> [Network] Bug fix the NWParameter constructors

- msbuild/Xamarin.Mac.Tasks.Core/Tasks/MmpTaskBase.cs
- msbuild/Xamarin.iOS.Tasks.Core/Tasks/MTouchTaskBase.cs
- msbuild/tests/AppWithExtraArgumentThatOverrides/AppDelegate.cs
- msbuild/tests/AppWithExtraArgumentThatOverrides/AppWithExtraArgumentThatOverrides.csproj
- msbuild/tests/AppWithExtraArgumentThatOverrides/AppWithExtraArgumentThatOverrides.sln
- msbuild/tests/AppWithExtraArgumentThatOverrides/Assets.xcassets/AppIcon.appiconset/Contents.json
- msbuild/tests/AppWithExtraArgumentThatOverrides/Assets.xcassets/Contents.json
- msbuild/tests/AppWithExtraArgumentThatOverrides/Entitlements.plist
- msbuild/tests/AppWithExtraArgumentThatOverrides/Info.plist
- msbuild/tests/AppWithExtraArgumentThatOverrides/LaunchScreen.storyboard
- msbuild/tests/AppWithExtraArgumentThatOverrides/Main.cs
- msbuild/tests/AppWithExtraArgumentThatOverrides/Main.storyboard
- msbuild/tests/AppWithExtraArgumentThatOverrides/ViewController.cs
- msbuild/tests/AppWithExtraArgumentThatOverrides/ViewController.designer.cs
- msbuild/tests/Xamarin.iOS.Tasks.Tests/ProjectsTests/ResponseFileArguments.cs
- msbuild/tests/Xamarin.iOS.Tasks.Tests/Xamarin.iOS.Tasks.Tests.csproj
- tests/mmptest/src/LinkerTests.cs
- tools/mmp/driver.cs
- https://github.com/xamarin/xamarin-macios/issues/4594
- There were being adding _before_ the response file which meant options that were overriding defaults were not being honored
> [d15-9] Order additional arguments after response file (#4607)

- system-dependencies.sh
This is an additional fix for https://github.com/xamarin/maccore/issues/952.
> [system-dependencies] Remove any cached files by xcodebuild before checking if first launch task needs executing.

- docs/website/mmp-errors.md
- docs/website/mtouch-errors.md
- tests/mmptest/src/MMPTest.cs
- tools/mmp/driver.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/4569.
> [mmp] Show an error if trying to build a 32-bit app with Xcode 10. Fixes #4569.

- src/coreimage.cs
- src/generator-filters.cs
- tests/monotouch-test/CoreImage/FilterTest.cs
https://github.com/xamarin/xamarin-macios/issues/4226
> [coreimage] Add generator support for CIVector[] and enable it in CIMeshGenerator. Fix #4226

- tests/xharness/Harness.cs
- tests/xharness/xharness.csproj
This also required a minor fix to allow relative directories as the root
directory.
> [xharness] Add project configurations to run & debug Makefile generation.

- tests/bcl-test/System.Net.Http/System.Net.Http.csproj.template
- tests/linker/ios/link sdk/AsyncTest.cs
Fixes https://github.com/xamarin/maccore/issues/977.
> [tests] Fix System.Net.Http and link sdk tests

- msbuild/Xamarin.Mac.Tasks.Core/Tasks/MmpTaskBase.cs
- msbuild/Xamarin.iOS.Tasks.Core/Tasks/MTouchTaskBase.cs
- msbuild/tests/AppWithExtraArgumentThatOverrides/AppDelegate.cs
- msbuild/tests/AppWithExtraArgumentThatOverrides/AppWithExtraArgumentThatOverrides.csproj
- msbuild/tests/AppWithExtraArgumentThatOverrides/AppWithExtraArgumentThatOverrides.sln
- msbuild/tests/AppWithExtraArgumentThatOverrides/Assets.xcassets/AppIcon.appiconset/Contents.json
- msbuild/tests/AppWithExtraArgumentThatOverrides/Assets.xcassets/Contents.json
- msbuild/tests/AppWithExtraArgumentThatOverrides/Entitlements.plist
- msbuild/tests/AppWithExtraArgumentThatOverrides/Info.plist
- msbuild/tests/AppWithExtraArgumentThatOverrides/LaunchScreen.storyboard
- msbuild/tests/AppWithExtraArgumentThatOverrides/Main.cs
- msbuild/tests/AppWithExtraArgumentThatOverrides/Main.storyboard
- msbuild/tests/AppWithExtraArgumentThatOverrides/ViewController.cs
- msbuild/tests/AppWithExtraArgumentThatOverrides/ViewController.designer.cs
- msbuild/tests/Xamarin.iOS.Tasks.Tests/ProjectsTests/ResponseFileArguments.cs
- msbuild/tests/Xamarin.iOS.Tasks.Tests/Xamarin.iOS.Tasks.Tests.csproj
- tests/mmptest/src/LinkerTests.cs
- tools/mmp/driver.cs
- https://github.com/xamarin/xamarin-macios/issues/4594
- There were being adding _before_ the response file which meant options that were overriding defaults were not being honored
> Order additional arguments after response file (#4607) (#4612)

- src/foundation.cs
- tests/monotouch-test/Foundation/NSMutableDictionary2Test.cs
- tests/monotouch-test/Foundation/NSMutableDictionaryTest.cs
- tests/xtro-sharpie/common-Foundation.ignore
Fixes https://github.com/xamarin/xamarin-macios/issues/4813.
> [Foundation] Bind NSMutableDictionary's addEntriesFromDictionary:. Fixes #4813.

- jenkins/compare.sh
See https://github.com/xamarin/xamarin-macios/pull/4844#issuecomment-423031121 for an example of incorrect output.
> [jenkins] Remove duplicated diff lines in GH comment.

- msbuild/Xamarin.iOS.Tasks.Core/Tasks/CompileAppManifestTaskBase.cs
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.AppExtension.Common.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Backport of #4873.
/cc @spouliot
> [xcode10.1] [msbuild] Implement support for faking the watchOS 4.3 SDK. Fixes #4810.

- docs/website/mmp-errors.md
- tests/mmptest/src/LinkerTests.cs
- tools/mmp/driver.cs
- https://github.com/xamarin/xamarin-macios/issues/4825
> Add mmp error when combining partial static registrar and linking

- tests/xharness/AppRunner.cs
- tests/xharness/Jenkins.cs
* Use timestamp in more log paths.
* Create numbered log subdirectories to make things nicer to look at in a
terminal (thousands of subdirectories can be annoying to shift through; this
way there's an additional subdirectory level).
> [xharness] Improve logging a bit.

- docs/website/mtouch-errors.md
Fixes https://github.com/xamarin/xamarin-macios/issues/4445.
> [docs] Improve documentation for MT5216. Fixes #4445.

- tests/monotouch-test/mono/MonoWeakReferenceTest.cs
Fixes an issue when executed with interpreter. Now, the test is closer
to what we do in the runtime test:
https://github.com/mono/mono/blob/831e73abcd5b9e10b4aaff7872b8d68e8e0f60fd/mono/tests/weak-fields.cs
https://github.com/mono/mono/blob/831e73abcd5b9e10b4aaff7872b8d68e8e0f60fd/mono/mini/TestHelpers.cs
> [tests] improve MonoWeakReferenceTest to avoid false pinning

- .gitmodules
- Make.config
- fsharp/.gitignore
- fsharp/Makefile
- mk/versions.mk
It's still possible to build from source if desired.
Also remove the fsharp submodule (it will be cloned manually only if building
from source).
> Get the F# binaries from macios-binaries instead of building them every time.

- Make.config
- Makefile
- builds/Makefile
- fsharp/Makefile
- msbuild/Makefile
- opentk/Makefile.include
- runtime/Makefile
- src/Makefile
- src/Makefile.generator
- tests/Makefile
- tests/package-mac-tests.sh
- tests/test-libraries/Makefile
- tools/apidiff/Makefile
- tools/install-source/Makefile
- tools/mlaunch/Makefile
- tools/mmp/Makefile
- tools/mmp/tests/Makefile
- tools/mtouch/Makefile
Cloning is faster when supported, and it also saves disk space.
> Clone files if possible whenever it makes sense.

- tests/apitest/src/EveryFrameworkSmokeTest.cs
- tests/introspection/Mac/MacApiFieldTest.cs
- tests/introspection/Mac/MacApiProtocolTest.cs
- tests/introspection/Mac/MacCoreImageFiltersTest.cs
- tests/monotouch-test/CoreFoundation/DispatchTests.cs
- tests/monotouch-test/NaturalLanguage/NLTaggerTest.cs
Public bots were updated today.
Fixes https://github.com/xamarin/maccore/issues/1106
Fixes https://github.com/xamarin/maccore/issues/1107
> [tests] Fix some tests to succeed when run on macOS 10.14

- src/CoreGraphics/CGImage.cs
Added an extra overload to the Xamarin.Mac ScreenShot functionality allowing to pass additional options
> added ScreenImage overload for Xamarin Mac allowing for more options

- src/Foundation/NSUrlSessionHandler.cs
If the challenge is for basic authentication then try to get the
credentials for this authentication type.
Also handle multiple WWW-Authenticate headers, such as:
WWW-Authenticate: Negotiate,  NTLM
If the credentials provided on the NSUrlSessionHandler are not
available for a specific authentication type, or if the authentication
method is not supported, then reject the protection space. This allows
the next authentication challenge to be sent to the DidReceiveChallenge
method. Also handle a null reference exception that could occur if
there were no credentials available for the authentication type.
> NSUrlSessionHandler - basic auth and multiple auth headers

- tests/xharness/Jenkins.cs
aka. mixed mode. Depends on https://github.com/xamarin/xamarin-macios/pull/5050
> [tests] enable monotouch-test with --interpreter=-mscorlib on Jenkins

- tests/mmptest/src/MMPTest.cs
- tests/mmptest/src/NetStandardTests.cs
- tests/mmptest/src/PackageReferenceTests.cs
- tests/msbuild-mac/src/RoslynSmokeTests.cs
- https://github.com/xamarin/xamarin-macios/issues/4110
> [mac] Enable various msbuild only tests that were disabled

- docs/website/mmp-errors.md
- tools/mmp/driver.cs
- https://github.com/xamarin/xamarin-macios/issues/5121
> [mmp] Fix typo

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ArchiveTaskBase.cs
- msbuild/Xamarin.iOS.Tasks.Core/Tasks/ArchiveTaskBase.cs
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
This is part of https://devdiv.visualstudio.com/DevDiv/_workitems/edit/705977
> [msbuild] Pass ProjectGuid and ProjectTypeGuids to Archive task

- tests/Makefile
- tests/xharness/BCLTestImporter/BCLTestImportTargetFactory.cs
- tests/xharness/Harness.cs
- tests/xharness/Jenkins.cs
- tests/xharness/TestProject.cs
- tools/bcl-test-importer/BCLTestImporter/BCLTestProjectGenerator.cs
This reverts commit 7277bbcd2b8a9977ec7640b84249c294a3f74371, it breaks building & running the new BCL tests.
> Revert "[xharness] Only build the BCL tests when we need them. (#5139)"

- jenkins/prepare-packaged-macos-tests.sh
It seems curl can randomly fail with error 56, so if that happens, try again a
few more times before giving up.
Fixes https://github.com/xamarin/maccore/issues/1098.
> [jenkins] If provisioning fails with error 56, try again a few more times. Fixes maccore#1098.

- tests/xtro-sharpie/Helpers.cs
- tests/xtro-sharpie/SelectorCheck.cs
- Fixes #4018: [xtro] Report incorrect 'ArgumentSemantic' enum value usage
(https://github.com/xamarin/xamarin-macios/issues/4018).
> [xtro] Report incorrect 'ArgumentSemantic' enum value usage

- tests/xharness/Process_Extensions.cs
Using fewer threads is always good.
> [xharness] Implement Process.WaitForExitAsync and use it instead of creating background threads.

- builds/create-shared-library.sh
- tools/mmp/driver.cs
Fixes: https://github.com/mono/mono/issues/11870
Context: https://github.com/mono/mono/pull/11676
> [mono-2018-10] add libz dependency

- src/AudioUnit/AudioUnit.cs
Fixes xamarin/xamarin-macios#5217
Unfortunately I could not come up with a good test for this, we could create a package and let the reporter of #5217 test it.
Thoughts? 💭
> [AudioUnit] Adds 'Latency' property [get|set]ter to AudioUnit object

- Make.config
- builds/.gitignore
- builds/Makefile
- configure
We don't consume it yet, that will come in separate pull requests as the
necessary bits are included in the package.
> [builds] Download & extract the mono sdk package.

- jenkins/add-commit-comment.sh
- jenkins/add-commit-status.sh
- jenkins/vsts-device-tests-set-status.sh
> [CI] Add scripts to set github status from Azure DevOps (when running the device tests).

- tools/common/MachO.cs
Also remove some duplicated code.
> [MachO] Add support for ARM64e and ARM64_32.

- jenkins/utils.groovy
Fixes https://github.com/xamarin/maccore/issues/898.
> [jenkins] Specify repo manually for GitHub statuses to fix maccore#898.

- src/CFNetwork/MessageHandler.cs
The MessageHandler class suffers from the CVE 2018-8292. this commit
fixes the issue by ensuring that the we donot use autoredirect from
CFNetwork and perform the first request. If the response is a redirect,
follow it wihout the Autherization headers.
> [CFNetwork] Fix CVE 2018-8292 on Mac OS X.

- src/CFNetwork/MessageHandler.cs
The MessageHandler class suffers from the CVE 2018-8292. this commit
fixes the issue by ensuring that the we donot use autoredirect from
CFNetwork and perform the first request. If the response is a redirect,
follow it wihout the Autherization headers.
Backport of #5271.
> [d16-0] [CFNetwork] Fix CVE 2018-8292 on Mac OS X.

- Make.config
- builds/Makefile
This PR might be best reviewed commit-by-commit.
> [builds] Consume llvm + cross compilers from mono's package.

- jenkins/Jenkinsfile
This is one of the entries listed here: https://github.com/xamarin/xamarin-macios/issues/3904.
> [jenkins] Add links to the packages in the GitHub comment.

- src/AppKit/NSApplication.cs
Fixes typos in an error message.
> Fix error message

- jenkins/Jenkinsfile
- tests/xharness/GitHub.cs
This makes it much less probable to hit any rate limits, because authenticated
rate limits are much higher (5000 requests/hour vs 60 requests/hour).
> [xharness] Add support for GitHub authentication, and use it in Jenkins.

- tests/bcl-test/BCLTests/common-SystemCoreTests.ignore
- tools/bcl-test-importer/BCLTestImporter/BCLTestProjectGenerator.cs
Fixes https://github.com/xamarin/maccore/issues/1143
> [XHarness] Reenable System.Core tests on ios/tvos/watchos

- tools/bcl-test-importer/BCLTestImporter/BCLTestProjectGenerator.cs
Fixes  https://github.com/xamarin/maccore/issues/1130
> [XHarness] Reenable SystemLinqXunit on watchOS and TvOS.

- tests/bcl-test/BCLTests/templates/common/TestRunner.NUnit/NUnitTestRunner.cs
There are a number of tests that use a TestFixtureSetup method that
fails. While the xml results report these errors, if a user runs xharness locally,
he will not get the errors reported. This issue meant that we had
different errors reported in jenkis and locally.
> [XHarness] Report issues with the TestFixtureSetup

- tests/xharness/Simulators.cs
Context: https://github.com/mono/mono/issues/10641
> [xharness] recognize newer watches

- src/CoreMedia/CMTextMarkupAttributes.cs
- src/coremedia.cs
- tests/xtro-sharpie/common-CoreMedia.ignore
> added BaseFontSizePercentageRelativeToVideoHeight to CMTextMarkupAttributes

- src/watchkit.cs
- tests/xtro-sharpie/watchOS-WatchKit.todo
diff: https://github.com/xamarin/xamarin-macios/wiki/WatchKit-watchOS-xcode10.2-beta1
And yup [Watch (5,1)] xtro seems to agree
> [WatchKit] Update bindings to Xcode 10.2 Beta 1

- jenkins/compare.sh
- tools/compare-commits.sh
Example result with failing api comparison / generator diff: https://github.com/xamarin/xamarin-macios/commit/1c3cf87d49abbd08a1f5a201875e54a6d718dce2#commitcomment-32059225
> [jenkins] Try to give better information when api comparison / generator diff fails.

- src/UIKit/UIGuidedAccessRestriction.cs
- src/uikit.cs
- tests/common/TestRuntime.cs
- tests/monotouch-test/UIKit/GuidedAccessRestrictionTest.cs
- tests/xtro-sharpie/iOS-UIKit.todo
- tests/xtro-sharpie/tvOS-UIKit.ignore
- tests/xtro-sharpie/tvOS-UIKit.todo
diffs:
* https://github.com/xamarin/xamarin-macios/wiki/UIKit-iOS-xcode10.2-beta1
* https://github.com/xamarin/xamarin-macios/wiki/UIKit-tvOS-xcode10.2-beta1
* https://github.com/xamarin/xamarin-macios/wiki/UIKit-watchOS-xcode10.2-beta1
> [UIKit] Update bindings to Xcode 10.2 Beta 1

- Make.config
- jenkins/Jenkinsfile
Also cherry-pick a commit in relevant code from master, to minimize merge
problems later.
> Xcode 10.2 requires macOS Mojave, so make Mojave the main build bot version.

- tests/monotouch-test/UIKit/GestureRecognizerTest.cs
- WIP PR https://github.com/xamarin/xamarin-macios/pull/5462 more investigation needed so ignore test which is preventing green builds
> [tests] Ignore failing GestureRecognizerTest for now

- src/CoreMedia/CMSampleBuffer.cs
- src/CoreMedia/CoreMedia.cs
- tests/introspection/ApiTypoTest.cs
- tests/monotouch-test/CoreMedia/EnumTest.cs
- tests/monotouch-test/CoreMedia/SampleBufferTest.cs
- tests/xtro-sharpie/common-CoreMedia.ignore
- tests/xtro-sharpie/iOS-CoreMedia.todo
- tests/xtro-sharpie/macOS-CoreMedia.todo
- tests/xtro-sharpie/tvOS-CoreMedia.todo
Most additions are block-based alternatives to callback API. However,
the way we bind them, it produce identical API so they are ignored.
> [coremedia] Update for xcode 10.2 beta 1

- src/Foundation/NSString.cs
- tests/monotouch-test/Foundation/NSStringTest.cs
Fixes #5134
@rolfbjarne any guidance on where new tests would go?
> [NSString] Add overloads which are optimized for substring handling

- src/generator.cs
No need for an if statement if the code is equal in both the true and false path.
> [generator] Code simplification.

- tests/xharness/Extensions.cs
- tests/xharness/Simulators.cs
According to simctl this shouldn't be possible (you get an error if you try),
but it happened on my system somehow, so cope with it.
> [xharness] Ignore duplicated device pairs.

- src/appkit.cs
> [AppKit] Add NullAllowed attribute to NSScrollView.DocumentView

- tools/mtouch/BuildTasks.mtouch.cs
> [mtouch] Quote MONO_PATH if needed in debug spew.

- tests/xharness/Extensions.cs
- tests/xharness/Jenkins.cs
- tests/xharness/xharness.css
- tests/xharness/xharness.js
Sometimes you just want to build.
> [xharness] Add commands to only build tests.

- tools/mtouch/Target.cs
Clang will automatically compile .bc files into object code if needed, but
it's done serially. If we do the compilation ourselves, it'll be parallelized.
This makes the dontlink tests build in half the time when building for watchOS
/ Release (it drops from ~15 minutes to ~7 minutes).
> [mtouch] Compile .bc files into .o files before passing them to the clang.

- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CodesignTaskBase.cs
- tests/common/mac/ProjectTestHelpers.cs
- tests/mmptest/src/MMPTest.cs
- https://github.com/xamarin/xamarin-macios/issues/4288
There is some IDE work needed to full support hardened runtime, but this is enough to allow people to support it if they are willing to use a text editor on their csproj.
> [xm] Support UseHardenendRuntime in code signing

- tools/siminstaller/Program.cs
* Improve the behavior when we fail to download the .dvtdownloadableindex file
to report a "Not Found" if we get a "Forbidden" (403) response, since that's
what it really is.
* Improve the behavior when we fail to download the .dvtdownloadableindex file
to check if the requested simulators are already installed instead of always
failing. This makes it possible to manually install the required simulators
if needed (Apple might not have published simulators for the Xcode version
we're using), and this would allow any checks to pass if the required
simulators are already installed.
* Improve the code to modify the PackageInfo XML to not use simple string
replacement (it's too fragile), use proper XML parsing instead.
* Fix "time left" math, I have no idea what my previous math was doing.
> [siminstaller] Improve failure scenarios.

- src/metalperformanceshaders.cs
Fixes macOS 10.13 introspection tests, confirmed each of said change with docs.
> [MetalPerformanceShaders] Fix some availability attributes

- Make.config
- src/wkwebkit.cs
- [webkit] Update for Xcode 10.2 beta 4
> Bump for Xcode 10.2 beta 4

- jenkins/Jenkinsfile
Updates the jenkinsFile to include generating [ci-checkout.json](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/dependency-info/7e2421b1775bd41ecd9be9218e6b95c03fb3c7b6/7/package/ci-checkout.json) and [dependency-info.json](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/dependency-info/7e2421b1775bd41ecd9be9218e6b95c03fb3c7b6/7/package/dependency-info.json).
> Add Additional Metadata Generation During Builds

- tests/bcl-test/BCLTests/templates/common/TestRunner.Core/TcpTextWriter.cs
Following this
http://xamarin-storage/jenkins/xamarin-macios/mono-2018-10/221f3e4a375d565d24087afbfcb1d6bc824c1ca9/2478649/device-tests/jenkins-results/tests/index.html
we need to ensure that we have a split to get the host. Just happens on
iOs and tvOS since they are the only ones using tcp.
> [XHarness] Fix the hostname parsing on devices.

- tools/mtouch/Target.cs
In both cases we use a different binaries for a few assemblies. They
include support for SRE and a few other things that are not normally
usable on iOS. That's totally fine and not something that can be fixed
(unless you stop using the feature). So this PR simply ignore that
specific case so we don't warn about things that can't be changed (and
are not a problem)
E.g.
```
Warning MT0109: The assembly 'mscorlib.dll' was loaded from a different path than the provided path (provided path: /Users/poupou/git/intr/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/mscorlib.dll, actual path: /Users/poupou/git/intr/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/lib/mono/Xamarin.iOS/repl/mscorlib.dll). (MT0109) …
```
> [mtouch] Avoid MT0109 warnings when --repl (or --interpreter) is used

- src/Foundation/Enum.cs
> [Foundation] Fix incorrect value for NSUrlRequestNetworkServiceType.ResponsiveData. Fixes #5836.

- Make.config
Backport of #5851.
/cc @spouliot
> [master] [apidiff] Update the references (URL) to 16.0 final releases

- Make.config
> [d16-1] Allow for current VS stable.

- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
- https://github.com/xamarin/xamarin-macios/issues/5061
> [msbuild][mac] Fix forcing provisioning profile when entitlements set

- runtime/trampolines-invoke.m
This avoids calling it multiple times in a loop further down in the method.
> [runtime] Get the domain at the top of xamarin_invoke_trampoline.

- src/btouch.cs
- src/error.cs
- src/generator.cs
It makes it clearer that warnings are warnings.
> [bgen] Use ErrorHelper.Warning instead of ErrorHelper.Show to show warnings.

- docs/website/mmp-errors.md
- docs/website/mtouch-errors.md
* Fix formatting for a few errors.
* Add a few missing mtouch errors.
It looks like all of this is due to incorrect merges.
> [docs] Fix issues that look like merge problems in the mtouch/mmp docs.

- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
- https://github.com/xamarin/xamarin-macios/issues/5061
Backport of #5912.
/cc @chamons
> [d16-1] [msbuild][mac] Fix forcing provisioning profile when entitlements set

- src/CloudKit/CKCompat.cs
- src/CoreAnimation/CACompat.cs
- src/CoreBluetooth/CBCompat.cs
- src/GameKit/GKCompat.cs
- src/GameplayKit/GKCompat.cs
- src/MetalPerformanceShaders/MPSCompat.cs
- src/PdfKit/PdfCompat.cs
- src/UIKit/Compat.cs
- src/Vision/VNCompat.cs
- src/avfoundation.cs
- src/cloudkit.cs
- src/coreanimation.cs
- src/corebluetooth.cs
- src/frameworks.sources
- src/gamekit.cs
- src/gameplaykit.cs
- src/metalperformanceshaders.cs
- src/pdfkit.cs
- src/vision.cs
- src/xkit.cs
- tests/monotouch-test/CoreAnimation/EmitterBehaviorTest.cs
- tests/xtro-sharpie/common-AVFoundation.ignore
https://github.com/xamarin/xamarin-macios/issues/5913
> Remove private API

- src/CloudKit/CKCompat.cs
- src/CoreAnimation/CACompat.cs
- src/CoreBluetooth/CBCompat.cs
- src/GameKit/GKCompat.cs
- src/GameplayKit/GKCompat.cs
- src/MetalPerformanceShaders/MPSCompat.cs
- src/PdfKit/PdfCompat.cs
- src/UIKit/Compat.cs
- src/Vision/VNCompat.cs
- src/avfoundation.cs
- src/cloudkit.cs
- src/coreanimation.cs
- src/corebluetooth.cs
- src/frameworks.sources
- src/gamekit.cs
- src/gameplaykit.cs
- src/metalperformanceshaders.cs
- src/pdfkit.cs
- src/vision.cs
- src/xkit.cs
- tests/monotouch-test/CoreAnimation/EmitterBehaviorTest.cs
- tests/xtro-sharpie/common-AVFoundation.ignore
https://github.com/xamarin/xamarin-macios/issues/5913
Backport of #5915.
/cc @spouliot
> [d16-1] Remove private API

- src/generator.csproj
No actual changes here (as can be seen by ignoring whitespace in the diff),
this just makes me happier when modifying the csproj in VSfM and the entire
file doesn't end up changed.
> [generator] Format csproj like VSfM likes to do it.

- tests/xharness/Jenkins.cs
To simplify the life of the monitorer, if we get a crash with a HE0038
we will propagate the result to the html and will provide a link to the
issue so that it is easy to report it.
> [XHarness] Show when we have a watch HE0038 error.

- tests/xharness/Jenkins.cs
Works around https://github.com/xamarin/maccore/issues/1613.
Backport of #6067.
> [d16-2] [xharness] Don't run monotouch-test/interpreter for now.

- tests/xharness/Jenkins.cs
> [d16-2] [xharness] "Skipped" really meant "DeviceNotFound", so rename things to avoid confusion.

- tests/xharness/Jenkins.cs
Works around https://github.com/xamarin/maccore/issues/1613.
> [xharness] Don't run monotouch-test/interpreter for now.

- src/appkit.cs
- https://github.com/xamarin/xamarin-macios/issues/6044
> [mac] Add NSSegmentedCell.SetTooltip NullAllowed

- tests/common/ExecutionHelper.cs
- tests/mtouch/MTouch.cs
Fixes https://github.com/xamarin/maccore/issues/1629
> [XHarness] Fix mtouch tests to use the new style bcl tests.

- tests/Makefile
Backport of #6034.
/cc @rolfbjarne @mandel-macaque
> [d16-2] [Jenkins] Do not run device tests in the internal jenkins instance.

- tests/introspection/iOS/iOSApiSelectorTest.cs
I ran into this on a watch device with watchOS 4.3.1.
> [introspection] Adjust rules for INParameter.

- tests/interdependent-binding-projects/Main.cs
- tests/xharness/AppRunner.cs
Fixes: https://github.com/xamarin/xamarin-macios/issues/5767
> [XHarness] If no test are ran, consider it as a failed ran.

- tests/xharness/AppRunner.cs
- tests/xharness/Harness.cs
- tests/xharness/Jenkins.cs
- tests/xharness/Log.cs
I find myself wanting timestamps if I don't have them much more than wanting
them gone when I do.
Worst case scenario: timestamps can still be disabled for specific logs if
such a desire ever becomes overwhelming.
> [xharness] Timestamp all the things.

- src/generator.cs
Note that the 'needsPtrZeroCheck' variable is not accurately named anymore,
but given that the code is somewhat impenetrable I wasn't able to come up with
a better name.
Also simplify two consecutive and identical null checks to a single check.
> [generator] Check if an object/pointer is null before trying to call release on it.

- tests/xtro-sharpie/xtro-sanity/Sanitizer.cs
Going through each failure one-by-one after fixing something that fixed many
entries is annoying, so automate the process.
> [xtro] Implement support for auto-sanitizing the .ignore files by defining an environment variable.

- tests/xharness/AppRunner.cs
- tests/xharness/BCLTestImporter/BCLTestImportTargetFactory.cs
- tests/xharness/Jenkins.cs
- tests/xharness/TestProject.cs
- tools/bcl-test-importer/BCLTestImporter/BCLTestProjectGenerator.cs
mscorlib has many tests and need some extra time, especially on watchOS, so
bump the timeout by 2 (from 15 to 30 minutes).
> [xharness] Add TimeoutMultiplier and multiply mscorlib's timeout by 2.

- tests/xharness/Jenkins.cs
Backport of #6102.
Fixes #6167.
> [d16-2] [xharness] Don't report tests whose device were not found if there were no such tests.

- tests/bcl-test/templates/common/TestRunner.Core/TestRunner.cs
- tests/bcl-test/templates/common/TestRunner.NUnit/NUnitTestRunner.cs
- tests/bcl-test/templates/common/TestRunner.xUnit/XUnitTestRunner.cs
- tests/bcl-test/templates/iOSApp/ViewController.cs
- tests/bcl-test/templates/macOS/MacTestMain.cs
- tests/bcl-test/templates/today/TodayExtensionMain.cs
- tests/bcl-test/templates/tvOSApp/ViewController.cs
- tests/bcl-test/templates/watchOS/Extension/InterfaceController.cs
Fixes https://github.com/mono/mono/issues/14729
> Fix wrong cast to IList

- src/ReplayKit/RPEnums.cs
Added new enum value
Also removed availability attributes from other values - since they are
not helpful for error codes (e.g. you don't want warnings for them, nor
do you want to add version checks around them)
> [replaykit] Update for xcode 11 beta 1

- src/WatchConnectivity/WCEnums.cs
- src/watchconnectivity.cs
- tests/xtro-sharpie/watchOS-WatchConnectivity.todo
Add new API for CompanionApp (watchOS only)
> [watchconnectivity] Update for xcode 11 beta 1

- src/Constants.mac.cs.in
- src/devicecheck.cs
- src/frameworks.sources
- tests/xtro-sharpie/macOS-DeviceCheck.todo
- tools/common/Frameworks.cs
- tools/common/Target.cs
Added support for macOS 10.15 and for iOS simulator (>= 13)
> [devicecheck] Update for xcode 11 beta 1

- src/cloudkit.cs
- src/coreimage.cs
reference
https://github.com/xamarin/xamarin-macios/issues/6324
> [tvos] Fix introspection tests when running on tvOS 10.2. Fixes #6324

- src/usernotifications.cs
- tests/xtro-sharpie/iOS-UserNotifications.todo
- tests/xtro-sharpie/macOS-UserNotifications.todo
- tests/xtro-sharpie/tvOS-UserNotifications.todo
- tests/xtro-sharpie/watchOS-UserNotifications.todo
> [usernotifications] Update for Xcode 11 beta 1

- src/messageui.cs
> [messageui] Update for Xcode 11 beta 1

- tests/mmptest/src/MMPTest.cs
Re-running the same UnifiedTestConfig instance with just some of the
configuration changed doesn't work as expected, because in subsequent builds
there are files already in the build directory, and things break in unexpected
ways.
So create a new UnifiedTestConfig instance for every test variation.
Fixes https://github.com/xamarin/xamarin-macios/issues/6257.
> [xcode11][mmptest] Split a few tests into test cases / several tests. Fixes #6257.

- src/appkit.cs
> [Appkit] Add 'NullAllowed' to 'NSSegmentedControl.SetLabel'

- src/corenfc.cs
Input feedback https://github.com/xamarin/xamarin-macios/pull/6370#pullrequestreview-252101174
Output feedback https://github.com/xamarin/maccore/issues/1785
> [corenfc] Fix some names and typos

- tests/xharness/Jenkins.cs
Nuget might freak out if multiple nuget processes run at the same time, so
make sure that doesn't happen.
Hint: review without whitespace to ignore the code that was indented when I
wrapped it in a using block.
Fixes https://github.com/xamarin/maccore/issues/1779.
> [xharness] Serialize access to nuget. Fixes xamarin/maccore#1779.

- src/uikit.cs
> [uikit] Add some `advice` to UISearchController's constructors

- src/JavaScriptCore/Enums.cs
> [javascriptcore] Update for Xcode 11 beta 1

- src/videosubscriberaccount.cs
- tests/xtro-sharpie/iOS-VideoSubscriberAccount.todo
- tests/xtro-sharpie/tvOS-VideoSubscriberAccount.todo
> [videosubscriberaccount] Update for Xcode 11 beta 1

- Make.config
Commits are:
* https://github.com/mono/mono/commit/e6f5369c2d24aa2de511a52c8a58956c3283c4e4 [2019-02] Fix time zone transition out of DST (#15444)
Complete diff is https://github.com/mono/mono/compare/346da980446da491277cbf3a8fbbe1989d614fb3...e6f5369c2d24aa2de511a52c8a58956c3283c4e4
> [Master] Bump mono to pick up TZ/DST fixes.

- src/MediaAccessibility/MAImageCaptioning.cs
- src/frameworks.sources
- tests/monotouch-test/MediaAccessibility/ImageCaptioningTest.cs
- tests/xtro-sharpie/iOS-MediaAccessibility.todo
- tests/xtro-sharpie/macOS-MediaAccessibility.todo
- tests/xtro-sharpie/tvOS-MediaAccessibility.todo
No change in beta 2
Unit tests added - but new API behaviour is not quite what I expected.
Maybe future docs will make this clearer...
> [mediaaccessibility] Update for Xcode 11 beta 1

- src/uikit.cs
- tests/README.md
> [tests/README.md] Fix a typing error 

- src/callkit.cs
Full API was added in UIKit for Mac. No other changes present.
Complete [diff](https://github.com/xamarin/xamarin-macios/wiki/CallKit-iOS-xcode11-beta1)
> [CallKit] Update for Xcode 11 beta 1 & beta 2.

- src/uikit.cs
- tests/monotouch-test/MapKit/PinAnnotationViewTest.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/6462
> [xammac-test/MapKit/PinAnnotationView] Changed assertion of PinTintColor property to work on other language than English

- tests/sampletester/Configuration.cs
- tools/devops/build-samples.csx
Also synchronize configuration file creation to not run into threading issues.
Fixes https://github.com/xamarin/maccore/issues/1811.
> [tests] Provision dotnet for the sample tests. Fixes xamarin/maccore#1811.

- src/quicklook.cs
- tests/xtro-sharpie/iOS-QuickLook.todo
Changes for b1-3, no updates from b3 according to wiki page.
> [quicklook] Update for Xcode11 beta 1-3

- src/identitylookup.cs
No change in beta 2 and beta 3
> [identitylookup] Update for Xcode 11 beta 1

- src/identitylookupui.cs
No change in beta 2 and beta 3
> [identitylookupui] Update for Xcode 11 beta 1

- tests/mmptest/regression/Makefile
- tests/mmptest/regression/link-preserve-assembly/LinkPreserveAssembly.cs
- tests/mmptest/regression/link-preserve-assembly/link-preserve-assembly.csproj
Fixes part of https://github.com/xamarin/xamarin-macios/issues/4975.
> [mmptest] Port link-preserve-assembly to Unified. Partial fix for #4975.

- tests/mmptest/regression/Makefile
- tests/mmptest/regression/link-remove-attributes-1/LinkRemoveAttributes.cs
- tests/mmptest/regression/link-remove-attributes-1/link-remove-attributes-1.csproj
Fixes part of https://github.com/xamarin/xamarin-macios/issues/4975.
> [mmptest] Port link-remove-attributes-1 to Unified. Partial fix for #4975.

- tests/mmptest/regression/Makefile
- tests/mmptest/regression/link-safe-1/LinkSafeAssembly.cs
- tests/mmptest/regression/link-safe-1/link-safe-1.csproj
Fixes part of https://github.com/xamarin/xamarin-macios/issues/4975.
> [mmptest] Port link-safe-1 to Unified. Partial fix for #4975.

- src/callkit.cs
- tests/xtro-sharpie/iOS-CallKit.todo
No change in beta 2 and 3
Initial PR https://github.com/xamarin/xamarin-macios/pull/6470 missed the single new API (hint: check `xtro` files)
> [callkit] Update for xcode beta 1

- src/coreaudiokit.cs
- tests/xtro-sharpie/iOS-CoreAudioKit.todo
No change in beta 2 and beta 3
> [coreaudiokit] Update for Xcode 11 beta 1

- tests/xharness/Jenkins.cs
This would have caught/avoided #6593.
> [xharness] Run the mtouch tests when anything in runtime/ changes.

- src/arkit.cs
Apple keep changing its mind heh, breaking change expected, type introduced in iOS 13
> [ARKit] Update to Xcode 11 Beta 4

- src/foundation.cs
- tests/introspection/ApiTypoTest.cs
This also removes properties unavailable on 10.15
> [Tests] Fix introspection tests in catalina

- src/photosui.cs
- tests/xtro-sharpie/iOS-PhotosUI.todo
> [PhotosUI] Add Xcode 11 Beta 1 Binding 

- Make.config
- src/frameworks.sources
- src/iTunesLibrary/ITCompat.cs
- src/ituneslibrary.cs
- tests/xtro-sharpie/macOS-iTunesLibrary.todo
diff : https://github.com/xamarin/xamarin-macios/wiki/iTunesLibrary-macOS-xcode11-beta1
It probably needs more work but we can discuss about it here 😄
> [xcode11] [ItunesLibrary] macOS b1 bindings

- Make.config
> [d16-3] [Provisioning] Use correct public VSMac url.

- builds/Makefile
- Port of https://github.com/xamarin/xamarin-macios/pull/6529 to d16-3
> [package] Remove creation of files/symlinks under /Developer

- src/uikit.cs
- https://github.com/xamarin/xamarin-macios/issues/6649
> [uikit] Add [NullAllowed] to UIButton.SetAttributedTitle

- tests/linker/ios/link all/LinkAllTest.cs
- tests/linker/ios/link sdk/CryptoTest.cs
Backport of #6694.
/cc @mandel-macaque @dalexsoto
> [d16-3] [tests] wrench is long gone

- tests/linker/ios/link all/LinkAllTest.cs
- tests/linker/ios/link sdk/CryptoTest.cs
Backport of #6694.
/cc @mandel-macaque @dalexsoto
> [xcode11] [tests] wrench is long gone

- src/uikit.cs
https://github.com/xamarin/xamarin-macios/issues/6702
> [UIKit] add [BindAs] UIWindowSceneSessionRole to fix #6702

- src/soundanalysis.cs
Guess I closed the previous pull request for this one too many times, so I created a new one.
> [SoundAnalysis] Add Xcode11 Beta 5 binding

- src/pdfkit.cs
- tests/xtro-sharpie/iOS-PdfKit.todo
> [pdfkit] Update for Xcode 11 beta 1

- src/quartzcomposer.cs
- tests/xtro-sharpie/macOS-QuartzComposer.todo
> [quartzcomposer] Update for Xcode 11 beta 1

- src/EventKit/EKEnums.cs
- src/eventkit.cs
- tests/xtro-sharpie/iOS-EventKit.todo
- tests/xtro-sharpie/macOS-EventKit.todo
- tests/xtro-sharpie/watchOS-EventKit.todo
Finally a lot of noise but not that much to change as I understood.
> [xcode11] [EventKit] bindings for all platforms

- src/ImageKit/Enums.cs
> [macos][imagekit] Update for Xcode 11 beta 1

- tests/linker/ios/link sdk/LinkSdkRegressionTest.cs
- tools/linker/MobileMarkStep.cs
reference: https://github.com/xamarin/xamarin-macios/issues/6346
> [linker] Fix NRE when System.Linq.Queryable is used. Fix #6346

- src/generator.cs
The generator will create special *Appearance types (these are nested
classes). If we've bound a type with the same *Appearance name, we can end up
in a situation where the csc compiler uses the the type we don't want due to
C#'s resolution rules - this happens if the bound *Appearance type is
referenced from the containing type of the special *Appearance type. So always
reference the bound *Appearance types using global:: syntax.
Fixes https://github.com/xamarin/xamarin-macios/issues/6834.
> [generator] Reference bound *Appearance types using global:: syntax. Fixes #6834.

- ISSUE_TEMPLATE.md
Added an instruction to find the build logs of the application in Visual Studio
> Instruction to find the build logs

- mk/xamarin.mk
To get fix for installing certificates and provisioning profiles for tests.
Diff: https://github.com/xamarin/maccore/compare/809b2def3933d59811c3761e55c64351be94f6d3..48beb56b92d3455e711c7de74513d41ede28f48c
> Bump maccore.

- src/Foundation/NSUrlSessionHandler.cs
- tests/monotouch-test/System.Net.Http/MessageHandlers.cs
This is a cherry-pick from master of 4cfca09260af84209fefd33d06449812d1fadf79 and 4a08c6c7b298e447f92159b919dc8ef50b8ed40d
> [Foundation] Expose the usage of cellular data in the NSUrlSessionHandler.

- builds/.gitignore
- builds/Makefile
- jenkins/Jenkinsfile
- mac-entitlements.plist
- runtime/.gitignore
- runtime/Makefile
- tests/common/ProductTests.cs
- tools/common/MachO.cs
- tools/mtouch/Application.cs
* Add a dummy x86_64 slice to all our native libraries that don't have one,
since the notarization servers require it.
* Notarize our packages in the Jenkinsfile.
> Implement notarization.

- Versions-ios.plist.in
- Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/959179
- Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/956758
> Update Versions info for iOS/tvOS 12.3 & 12.4 + watchOS 5.3

- docs/website/generator-errors.md
- src/corenfc.cs
- src/generator.cs
- tests/generator/BGenTests.cs
- tests/generator/ErrorTests.cs
- tests/generator/generator-tests.csproj
- tests/generator/tests/diamond-protocol-errors.cs
- tests/generator/tests/diamond-protocol.cs
- tests/xtro-sharpie/iOS-CoreNFC.ignore
Fixes https://github.com/xamarin/xamarin-macios/issues/6366.
> [generator] Handle inheriting the same member from multiple protocols. Fixes #6366.

- src/modelio.cs
- tests/xtro-sharpie/common-ModelIO.ignore
Fixes tests broken by https://github.com/xamarin/xamarin-macios/pull/6991.
> [ModelIO] Fix xtro broken by #6991.

- msbuild/tests/Xamarin.iOS.Tasks.Tests/TargetTests/TargetTests.cs
- msbuild/tests/Xamarin.iOS.Tasks.Tests/TaskTests/IBToolTaskTests.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/6970.
> [msbuild] Update a few msbuild tests to Xcode 11 behavior. Fixes #6970.

- Make.config
- docs/website/mmp-errors.md
- docs/website/mtouch-errors.md
- tools/mmp/driver.cs
Also bump system mono to a version whose pkg-config executable actually works
on Catalina.
> [mmp] Don't ignore failures to execute pkg-config.

- tests/monotouch-test/CoreBluetooth/CentralManagerTest.cs
Tests were failing because the manager was getting dispose and the
delegate was not. We ran into the failure because there was a device
close to the lab with the UUID that was being used.
The change uses a even more common UUID (heart monitor), which should
increase the chances to pick up a device and re-orgs the disposal of the
manager and the delegate.
This was confirmed with a BLE device, watchOS does not like us to try
and access it as a bluetooth device and is 'hacky'.
Fixes: https://github.com/xamarin/xamarin-macios/issues/7108
> [Tests] Make the CoreBluetooth tests more reliable.

- src/ObjCRuntime/TrampolineBlockBase.cs
- src/frameworks.sources
- src/generator.cs
This saves 107kb (0.7%) in Xamarin.iOS.dll (managed code and metadata).
Release (AOT) size reduction will vary depending on how much the linker can remove.
```
-rwxr-xr-x  1 poupou  staff  15963136 26 Sep 10:16 _ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/lib/32bits/Xamarin.iOS.dll
-rwxr-xr-x  1 poupou  staff  12301824 26 Sep 10:16 _ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/lib/mono/Xamarin.iOS/Xamarin.iOS.dll
-rwxr-xr-x  1 poupou  staff  17126912 26 Sep 10:16 _ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/lib/64bits/Xamarin.iOS.dll
-rwxr-xr-x  1 poupou  staff  8375296 26 Sep 10:13 _ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/lib/mono/Xamarin.TVOS/Xamarin.TVOS.dll
-rwxr-xr-x  1 poupou  staff  11671040 26 Sep …
```
> [generator] Reduce code duplication in trampolines by introducing a new base type

- tools/common/StaticRegistrar.cs
Several functions were 100% identical except for their signature. However
the signature were over-specialized and simplifying them allows the
(already) present code merge feature to achieve much better results.
Final size impact will vary based on the API used (both the managed and
native linker can remove some) but the more API you use the more likely
the application included duplicate code.
**Before**
`tools/mtouch/Xamarin.iOS.registrar.ios.x86_64.m` has `native_to_managed_trampoline_[1..379]`
```
find tools/ -name Xamarin.*.a | xargs ls -l
-rw-r--r--  1 poupou  staff  4143148 11 Oct 15:09 tools//mmp/Xamarin.Mac.registrar.full.a
-rw-r--r--  1 poupou  staff  4139052 11 Oct 15:09 tools//mmp/Xamarin.Mac.registrar.full.x86_64.a
-rw-r--r--  1 poupou  staff  4143160 11 Oct 15:09 …
```
> [registrar] Increase code sharing in generated `native_to_managed_trampoline_*` functions

- tests/sampletester/Samples.cs
A few fixes have been merged to ios-samples and xamarin-form-samples that should fix errors in azure devops.
> [sampletester] Bump sampletester for ios-samples and xamarin-form-samples to tip of master

- builds/.gitignore
- builds/Makefile
https://github.com/xamarin/xamarin-macios/commit/a7fd4552dc798bcde67db57b4ce56fd1850b20ab was slightly wrong, it should have broken all tests around notarization (which are presumably not done for PRs).
Also adding a missing dependency.
> [build] fix Makefile around x86-64-slice

- tests/sampletester/Samples.cs
Bump prebuilt-apps for SampleTester to latest on master. Fixes have been merged to prebuilt-apps which should resolve CI failures.
> [SampleTester] Bump prebuilt-apps for SampleTester

- src/homekit.cs
- tests/xtro-sharpie/iOS-HomeKit.todo
- tests/xtro-sharpie/tvOS-HomeKit.todo
- tests/xtro-sharpie/watchOS-HomeKit.todo
Bindings for HomeKit for Xcode11.2
> [HomeKit] Xcode11.2 bindings

- src/photos.cs
- tests/xtro-sharpie/macOS-Photos.todo
Diff: https://github.com/xamarin/xamarin-macios/wiki/Photos-macOS-xcode11.2-beta2
Ref: https://github.com/xamarin/maccore/issues/1797
> [Photos] Update to Xcode 11.2 beta 2.

- src/AppKit/NSCollectionLayoutAnchor.cs
> [AppKit] Fix new warnings

- src/uikit.cs
- tests/xtro-sharpie/iOS-UIKit.todo
- tests/xtro-sharpie/tvOS-UIKit.todo
Add UIKit bindings for xcode11.2b2
> [UIKit] Add UIKit bindings for xcode11.2b2

- src/storekit.cs
- tests/xtro-sharpie/iOS-StoreKit.todo
- tests/xtro-sharpie/tvOS-StoreKit.todo
Add StoreKit bindings for xcode11.2b2
> [StoreKit] Add StoreKit bindings for xcode11.2b2

- jenkins/Jenkinsfile
Issues with the last PR:
- pkgs.flatten() not approved (approved between of https://jenkins.internalx.com/view/All/job/xamarin-build-tasks-master/324/console and https://jenkins.internalx.com/view/All/job/xamarin-build-tasks-master/325/console)
- Uploading an empty glob fails in WAStoragePlugin
> Notarization tweaks (take 2)

- mk/xamarin.mk
diff: https://github.com/xamarin/maccore/compare/3e141c6779fe3d0d76f6960ed0e3edb729374f78...f56575dcc2ec2d8975ea328feeeea697b7b2194b
> [master] bump maccore
