src/generator.cs
The PrintAttributes method defaults to not printing anything, and when then
asked to not print platform attributes, it still adds up to doing nothing, so
just remove this redundant method call.
=> [generator] Remove redundant calls to PrintAttributes.

src/btouch.cs, src/generator.cs, src/metal.cs, tests/cecil-tests/ApiAvailabilityTest.cs, tests/cecil-tests/AttributeTest.cs, tests/generator/BGenTests.cs, tests/generator/tests/newer-availability-in-inlined-protocol.cs
Protocols with one set of introduced attributes ([TV (12, 0)]) inlined in
types that were introduced in a different version ([TV (10, 0)]) would always
use the attributes from the type.
This is wrong if the protocol was introduced after the type, in which case we
should instead use the introduced attributes from the protocol.
Fix this by choosing the latest introduced attribute when we have multiple to
choose from.
This required passing a bit more information around so that we always know if
a member is being inlined in another type.
This PR will also print availability attributes on the protocol members themselves:
[Protocol]
interface IProtocol
{
[TV (12, 0)] // this was not printed before
[Export ("someProperty")]
string SomeProperty { get; set; }
}
Also add and improve some tests. …
=> [generator] Fix an issue where we'd not copy attributes from inlined protocols.

src/bgen/bgen.csproj, src/generator-nullability-info-context.cs, src/generator.csproj, tests/bgen/bgen-tests.csproj, tests/generator/NullabilityContextTests.cs, tests/generator/generator-tests.csproj
This is the first part of a 2 or more changes that will allow the APIs to use ? as a way to mark a nullable field, parameter, property and return method.
The way it works follows the documentation from the runtime that can be found here: https://github.com/dotnet/roslyn/blob/main/docs/features/nullable-metadata.md
The tldr; of the documentation is as follows:
1. If we are looking at a value type, the compiler converts int? into Nullable<int>. This was already considered in the old code.
2. If we are inspecting a generic type we have to look for the information in two different attributes added by the compiler: - NullableAttribute: Each type reference in metadata may have an associated NullableAttribute with a byte[] where each byte represents nullability: 0 for oblivious, 1 for not …
=> [Generator] Add support for nullability. Part 1.

src/generator.cs
Everything compiles as expected and we do have: https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/value-tuples
=> [Generator] Remove dead code.

src/AppKit/NSView.cs
Maybe a bad merge or we missed it.
=> [AppKit] Remove nullability warning.

src/Foundation/NSHost.cs
* Enable nullability in NSHost, and fix misc issues.
* Add an explicit interface overload for IEquatable<NSHost>.Equals. Fixes this compiler warning:
error CS8767: Nullability of reference types in type of parameter 'host' of 'bool NSHost.Equals(NSHost host)' doesn't match implicitly implemented member 'bool IEquatable<NSHost>.Equals(NSHost? other)
=> [AppKit] Enable nullability in NSHost.

src/Makefile
The code to handle (and ignore) warnings was getting out of hand, so I've
unified it between all platforms. We now ignore the same warnings on every
platform, and have much fewer variables to reason about.
=> [src] Unify the list of warnings we skip.

runtime/coreclr-bridge.m, runtime/delegates.t4, runtime/exports.t4, runtime/runtime.m, src/ObjCRuntime/Blocks.cs, src/ObjCRuntime/Runtime.CoreCLR.cs, src/ObjCRuntime/Runtime.cs, src/ObjCRuntime/TrampolineBlockBase.cs
This makes it possible to simplify and remove a good chunk of related code.
Especially for CoreCLR this should be a minor perf improvement, because we'll do fewer transitions between managed and native code.
=> [runtime] Remove native usage of MonoReferenceQueue and use a ConditionalWeakTable in managed code instead.

Make.config
Fixes:
> ##[error]The nuget command failed with exit code(1) and error(System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 409 (Conflict - The feed already contains 'Microsoft.MacCatalyst.Ref 16.2.1020+sha.fadaa6ffe'. (DevOps Activity ID: 384C96F7-56C7-4433-8E9F-B96CFDB61942)).
Versions are now:
```
$ make show-versions
Building:
The .NET NuGet(s):
Microsoft.iOS 16.2.2020+sha.fadaa6ffee
Microsoft.tvOS 16.1.2517+sha.fadaa6ffee
Microsoft.MacCatalyst 16.2.2020+sha.fadaa6ffee
Microsoft.macOS 13.1.2020+sha.fadaa6ffee
```
=> [release/7.0.2xx] Hardcode a version bump to make sure versions are repeated across release branches.

tools/devops/automation/templates/main-stage.yml
The trnalsations are meant to be done per week using the cron job. The cron job does not use the main stage template, ergo we can simplify the stage by removing the translations.
=> [CI] Remove the translations from the main stage.

src/bgen/GeneratedTypes.cs, src/bgen/Generator.cs, src/generator.csproj
Moved the code out, also made a small improvement by reducing the number of lookups are needed to get the GeneratedType.
=> [Generator] Move GeneratedTypes out and enable nullability.

tests/bgen/bgen-tests.csproj, tests/dotnet/UnitTests/DotNetUnitTests.csproj, tools/nnyeah/tests/nnyeah-tests.csproj
The older version of Microsoft.NET.Test.Sdk depends on an older version of
Newtonsoft.Json, which triggers automated security warnings.
Ref: https://devdiv.visualstudio.com/DevDiv/_componentGovernance/113130/alert/7090885?typeId=12169115
=> [tests] Bump Microsoft.NET.Test.Sdk version to latest stable.

dotnet/targets/Xamarin.Shared.Sdk.props
This will allow the latest runtime identifier values to be evaluated in time during the MSBuild property evaluation phase.
Related and dependent of this PR: https://github.com/xamarin/XamarinVS/pull/13606
Backport of #17466
=> [release/6.0.4xx-xcode14.2] Imports the .user.env file if exists and the build is from VS

dotnet/targets/Xamarin.Shared.Sdk.props
This will allow the latest runtime identifier values to be evaluated in time during the MSBuild property evaluation phase.
Related and dependent of this PR: https://github.com/xamarin/XamarinVS/pull/13606
Backport of #17466
=> [release/7.0.1xx-xcode14.2] Imports the .user.env file if exists and the build is from VS

dotnet/targets/Xamarin.Shared.Sdk.props
This will allow the latest runtime identifier values to be evaluated in time during the MSBuild property evaluation phase.
Related and dependent of this PR: https://github.com/xamarin/XamarinVS/pull/13606
=> Imports the .user.env file if exists and the build is from VS

msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.props, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
.ation property
This is needed in order to read the correct value of the "IsHotRestartBuild" property set by the VS extension. Doing it in a PropertyGroup at evaluation was not getting the correct value since it was not being set as an MSBuild global property
This PR is related to this other one in the XVS extension: https://github.com/xamarin/XamarinVS/pull/13612
Backport of #17470
=> [xcode14.2] [win] Add Hot Restart define constant in a target instead of an evaluation property

msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.props, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
.ation property
This is needed in order to read the correct value of the "IsHotRestartBuild" property set by the VS extension. Doing it in a PropertyGroup at evaluation was not getting the correct value since it was not being set as an MSBuild global property
This PR is related to this other one in the XVS extension: https://github.com/xamarin/XamarinVS/pull/13612
Backport of #17470
=> [release/6.0.4xx-xcode14.2] [win] Add Hot Restart define constant in a target instead of an evaluation property.

msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.props, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
…ation property
This is needed in order to read the correct value of the "IsHotRestartBuild" property set by the VS extension. Doing it in a PropertyGroup at evaluation was not getting the correct value since it was not being set as an MSBuild global property
This PR is related to this other one in the XVS extension: https://github.com/xamarin/XamarinVS/pull/13612
=> [win] Add Hot Restart define constant in a target instead of an evaluation property

msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.props, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
.ation property
This is needed in order to read the correct value of the "IsHotRestartBuild" property set by the VS extension. Doing it in a PropertyGroup at evaluation was not getting the correct value since it was not being set as an MSBuild global property
This PR is related to this other one in the XVS extension: https://github.com/xamarin/XamarinVS/pull/13612
Backport of #17470
=> [release/7.0.1xx-xcode14.2] [win] Add Hot Restart define constant in a target instead of an evaluation property.

src/CoreServices/FSEvents.cs, src/Makefile, src/SceneKit/SCNMatrix4_dotnet.cs, src/SceneKit/SCNVector3.cs, src/SceneKit/SCNVector4.cs, tools/add-apple-links-to-docs.sh
Also fix XML comments to be valid and not produce compiler warnings.
Unfortunately XML comments can't be conditionally compiled
(https://github.com/dotnet/csharplang/discussions/295), so we have to 
duplicate a lot of content that is just slightly different.
Fixes https://github.com/xamarin/xamarin-macios/issues/17395.
=> [src] Create XML documentation when building our platform assemblies for .NET. Fixes #17395.

msbuild/Xamarin.MacDev.Tasks/Tasks/CompileAppManifestTaskBase.cs, tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/CompileAppManifestTaskTests.cs
Modify the code to add Xcode (DT*) variables to the Info.plist:
* Do it for all platforms, not only mobile platforms. Apple uses these fields to
determine if an app was built with a prerelease or old version of Xcode, and will
reject any app submissions if this validation fails.
* Change the behavior to do not distinguish simulator builds, a bit of testing
in Xcode shows that Xcode always adds these values to the Info.plist, even for
simulator builds. This is probably something that changed in Xcode a *long* time
ago, since this code is old (from the initial import of the build logic from MonoDevelop
around 10 years ago).
* Also bump Xamarin.MacDev to get a related fix:
* xamarin/Xamarin.MacDev@74c95ee [Xamarin.MacDev] Always fetch the DTSDKBuild …
=> [msbuild] Add DT* entries to the Info.plist for all platforms. Fixes #13300.

src/CoreFoundation/CFMessagePort.cs, src/CoreFoundation/CFNotificationCenter.cs, src/CoreFoundation/CFProxySupport.cs, src/CoreFoundation/CFSocket.cs, src/CoreFoundation/Dispatch.cs, src/CoreFoundation/OSLog.cs, tests/cecil-tests/BlittablePInvokes.cs
Updates the pinvokes in CoreFoundation to have blittable types.
I intentionally did *not* do `CFReadStream` and `CFWriteStream` as the changes needed for those are may create a breaking API change, so those should probably be their own PR for closer scrutiny.
Please look closely at CFProxySupport as that was the least straightforward of the changes.
=> [DotNet] CoreFoundation Pinvokes

dotnet/Workloads/WorkloadManifest.MacCatalyst.template.targets, dotnet/Workloads/WorkloadManifest.iOS.template.targets, dotnet/Workloads/WorkloadManifest.macOS.template.targets, dotnet/Workloads/WorkloadManifest.tvOS.template.targets
Hopefully fixes https://github.com/xamarin/xamarin-macios/issues/16400.
=> [dotnet] Only include the Xamarin.Shared.Sdk.MultiTarget.targets file if it exists. Fixes #16400.

dotnet/Workloads/WorkloadManifest.MacCatalyst.template.targets, dotnet/Workloads/WorkloadManifest.iOS.template.targets, dotnet/Workloads/WorkloadManifest.macOS.template.targets, dotnet/Workloads/WorkloadManifest.tvOS.template.targets
Hopefully fixes https://github.com/xamarin/xamarin-macios/issues/16400.
Backport of #17498
=> [release/7.0.2xx] [dotnet] Only include the Xamarin.Shared.Sdk.MultiTarget.targets file if it exists. Fixes #16400.

tools/dotnet-linker/Makefile, tools/dotnet-linker/dotnet-linker.csproj
Hopefully works around https://github.com/dotnet/runtime/issues/82241.
=> [release/8.0.1xx-preview1] [dotnet-linker] Make this a .NET 7 app to work around the fact that the linker is still a .NET 7 app.

src/bgen/AttributeManager.cs, src/bgen/Generator.cs, src/bgen/Nomenclator.cs, src/generator.csproj, tests/bgen/bgen-tests.csproj, tests/generator/NomenclatorTests.cs, tests/generator/NullabilityContextTests.cs, tests/generator/ReflectionTest.cs, tests/generator/generator-tests.csproj
Naming could be problematic when generating code, move the logic out of the generator class to a helper class whose only job is to name classes and keep track of names.
=> [Generator] Move naming logic to its own class and add tests.

msbuild/Directory.Build.props
Applies the following changes from Xamarin.Messaging:
xamarin/Xamarin.Messaging#543
xamarin/Xamarin.Messaging#541
It includes fixes for SSH keys handling, UX improvements when SSH is disabled on the Mac and also when the user is not logged in on the Mac
=> Updated Xamarin.Messaging to 1.9.40

src/CoreFoundation/CFReadStream.cs, src/CoreFoundation/CFStream.cs, src/CoreFoundation/CFWriteStream.cs
This turned out a bit more complex than usual, because the delegate we want to
remove from the call to the P/Invoke is a part of the public API.
I worked around this by adding new API that uses the new P/Invoke, and having
the old API throw an exception until we can remove it, but only in .NET 8,
which seems like the earliest we should do this kind of behavioral breaking
change.
=> [CoreFoundation] Fix CFStream to use blittable P/Invokes in .NET 8.

msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
From net8, ILLink is not part of dotnet/sdk anymore but part of dotnet/runtime: https://github.com/dotnet/runtime/tree/main/src/tools/illink/src/ILLink.Tasks
This means that now it's a NuGet package called `Microsoft.NET.ILLink.Tasks` and it's installed as part of the dotnet SDK installation
This affects the remote builds since we were looking on the dotnet SDK installation folder used by XMA (/Library/Caches/Xamarin/XMA/SDKs/dotnet) to find the 'illink.dll' assembly, but now that file is located in the NuGet packages folder used by XMA (/Library/Caches/Xamarin/XMA/SDKs/.home).
This change consists of adding some new MSBuild properties to calculate the right path of the 'illink.dll' assembly depending on if it's included in the SDK or not
This should fix Bug #1748997 - [XVS][.NET 8] Build …
=> [net8] Fix ILLink for net8 remote builds

src/ImageIO/CGImageMetadata.cs
We don't typically own input parameters, so make sure to pass 'false' for the
'owns' parameter to Runtime.GetNSObject.
This fixes a crash due to overreleasing these objects.
Also make the block creation code optimizable.
=> [ImageIO] We don't typically own input parameters.

msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
From net8, ILLink is not part of dotnet/sdk anymore but part of dotnet/runtime: https://github.com/dotnet/runtime/tree/main/src/tools/illink/src/ILLink.Tasks
This means that now it's a NuGet package called `Microsoft.NET.ILLink.Tasks` and it's installed as part of the dotnet SDK installation
This affects the remote builds since we were looking on the dotnet SDK installation folder used by XMA (/Library/Caches/Xamarin/XMA/SDKs/dotnet) to find the 'illink.dll' assembly, but now that file is located in the NuGet packages folder used by XMA (/Library/Caches/Xamarin/XMA/SDKs/.home).
This change consists of adding some new MSBuild properties to calculate the right path of the 'illink.dll' assembly depending on if it's included in the SDK or not
This should fix Bug #1748997 - [XVS][.NET 8] Build …
=> [release/8.0.1xx-preview1] [net8] Fix ILLink for net8 remote builds

src/ObjCRuntime/Class.cs, tests/cecil-tests/BlittablePInvokes.cs
Removed a flavor of `class_addMethod` that is unused.
Ignored a few cases that are going to be in .NET and/or may break AOT optimizations
Now all iOS pivots pass, 17 macOS remain.
=> [dotnet] Remove dead method, add some ignores

src/ImageIO/CGImageAnimation.cs
These CGImageAnimation.AnimateImage functions are one-directional only, in
that they're only used to call into Objective-C from managed code, and not
into managed code from Objective-C. This means we can remove any block code
related to the latter scenario, since it's not needed.
=> [ImageIO] Simplify the block code in CGImageAnimation.

tools/devops/automation/templates/main-stage.yml
This reverts commit 59aebf259cf936604d72621e3cb6dd8585620d6c.
We actually do need to keep this task inside our normal builds for the Loc team to identify if there are new translations through the localizationDrop artifact. The other pipeline that runs this task on the cron job is used for a separate part of the localization process that creates the PRs with the usable translations.
https://github.com/xamarin/maccore/wiki/Localization#the-translation-process
=> [Localization] Revert "[CI] Remove the translations from the main stage. (#17453)"

src/bgen/Generator.cs, tools/linker/CoreOptimizeGeneratedCode.cs
Contributes towards https://github.com/xamarin/xamarin-macios/issues/15783.
=> [generator] Use the new Block API that makes BlockLiteral disposable.

dotnet/Workloads/SignList.xml, msbuild/Directory.Build.props
Includes latest fixes like support for retry and reconnect, new telemetry, bug fixing, etc.
Also added Merq.Core.dll to dotnet/Workloads/SignList.xml because now it comes as part of Xamarin.Messaging
=> [main] Updated Xamarin.Messaging to 1.9.59

dotnet/Workloads/SignList.xml, msbuild/Directory.Build.props
Includes latest fixes like support for retry and reconnect, new telemetry, bug fixing, etc.
Also added Merq.Core.dll to dotnet/Workloads/SignList.xml because now it comes as part of Xamarin.Messaging
=> [xcode14.2] Updated Xamarin.Messaging to 1.9.59

src/AddressBook/ABAddressBook.cs, src/CoreGraphics/CGPDFArray.cs, src/CoreText/CTFontManager.cs, src/CoreText/CTLine.cs, src/ImageIO/CGImageAnimation.cs, src/Network/NWBrowser.cs, src/Network/NWConnection.cs, src/Network/NWConnectionGroup.cs, src/Network/NWEthernetChannel.cs, src/Network/NWFramer.cs, src/Network/NWFramerMessage.cs, src/Network/NWMulticastGroup.cs, src/Network/NWParameters.cs, src/Network/NWTxtRecord.cs, src/Network/NWWebSocketRequest.cs, src/Network/NWWebSocketResponse.cs, src/Security/SecTrust.cs, src/UIKit/UIAccessibility.cs, src/UIKit/UIGuidedAccessRestriction.cs
This is mostly converting 'bool' arguments to 'byte' arguments, and 'string'
arguments to 'IntPtr' with custom utf8->string conversions.
This is necessary in order to convert all block callbacks to use
UnmanagedCallersOnly function pointers (which can't have non-blittable types
in their signature).
Contributes towards https://github.com/xamarin/xamarin-macios/issues/15783.
=> [src] Refactor block code to use blittable callbacks.

src/AppKit/NSButton.cs, src/appkit.cs
If a wrapper type has a custom field (with a non-default value), we need to
mark the instance as dirty, to make it participate in the toggle-ref
machinery, and not get collected as long as the corresponding native instance
is around (otherwise the GC will collect the value in the field).
Fixes https://github.com/xamarin/xamarin-macios/issues/17635.
=> [AppKit] Make sure NSButtons are treated as toggled objects after setting a field. Fixes #17635.

Make.config
=> [xcode14.2] [Sim] Bump min simulator versions for ventura.

Make.config
=> [release/7.0.1xx-xcode14.2] [Sim] Bump min simulator versions for ventura.

Make.config
=> [release/6.0.4xx-xcode14.2] [Sim] Bump min simulator versions for ventura.

src/ObjCRuntime/Blocks.cs
A ref struct has a few limitations that makes a lot of sense for blocks:
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/ref-struct,
so by making BlockLiteral a ref struct, we're getting the C# compiler to help
us not writing broken code by accident.
The limitations also mean that it's a breaking change, so we can't do it
before XAMCORE_5_0.
=> [ObjCRuntime] Make BlockLiteral a ref struct in XAMCORE_5_0.

tests/common/TestRuntime.cs, tests/monotouch-test/Foundation/UrlSessionTest.cs
Should fix random test failures like this:
MonoTouchFixtures.Foundation.UrlSessionTest
[FAIL] CreateDataTaskAsync :   CreateDataTask a Exception
Expected: null
But was:  <Foundation.NSErrorException: Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." UserInfo={_kCFStreamErrorCodeKey=57, NSUnderlyingError=0x6000011f4990 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "(null)" UserInfo={NSErrorPeerAddressKey=<CFData 0x600003deaa80 [0x7ff865b1f1c0]>{length = 16, capacity = 16, bytes = 0x100201bb6007a9b70000000000000000}, _kCFStreamErrorCodeKey=57, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <5E766082-B379-491A-BCB0-EA1B36E54A8B>.<15>, _NSURLErrorRelatedURLSessionTaskErrorKey=("LocalDataTask …
=> [tests] Adjust UrlSessionTests to ignore more failure scenarios in CI.

src/ImageIO/CGImageMetadata.cs
This is necessary in order to convert all block callbacks to use
UnmanagedCallersOnly function pointers (which can't have non-blittable types
in their signature).
Contributes towards https://github.com/xamarin/xamarin-macios/issues/15783.
=> [ImageIO] Refactor block code to use blittable callbacks.

src/bgen/Generator.cs, src/bgen/TrampolineInfo.cs
We try to pass another name to the TrampolineInfo constructor, but it's
ignored, and 'Invoke' is always used, so just hardcode 'Invoke' everywhere
instead.
This makes the code a little bit simpler.
=> [generator] The trampoline name is always 'Invoke', so simplify code accordingly.

tests/monotouch-test/MediaAccessibility/ImageCaptioningTest.cs
=> [release/7.0.2xx] [tests] Adjust ImageCaptioningTest to skip network-related failures in CI.

tests/common/TestRuntime.cs, tests/linker/mac/LinkAnyTest.cs, tests/monotouch-test/Foundation/UrlSessionTest.cs
Backport of #16945 and #17649.
=> [release/7.0.1xx-xcode14.2] [tests] Allow for timeouts in CI in a few tests.

tests/monotouch-test/MediaAccessibility/ImageCaptioningTest.cs
=> [release/7.0.1xx-xcode14.2] [tests] Adjust ImageCaptioningTest to skip network-related failures in CI.

tests/monotouch-test/MediaAccessibility/ImageCaptioningTest.cs
=> [release/6.0.4xx-xcode14.2] [tests] Adjust ImageCaptioningTest to skip network-related failures in CI.

tests/common/shared-dotnet.mk
It doesn't work at all with paths with spaces. Instead call into the shell to
compute the filename.
Also fix a couple of other quoting issues.
=> [tests] Don't use 'notdir' to compute the filename of a path.

Make.config, builds/Makefile, builds/package-download/download-packages.csproj, dotnet/Makefile, eng/Versions.props, tools/devops/automation/scripts/bash/install-workloads.sh
* Use a separate variable for Mono's and Emscripten's manifest version band,
so that they can diverge (this is a decision from the corresponding teams,
we don't control it).
* Have a separate variable for our own manifest version band, so that it's
easier to hard code it if we want to.
* Rename a few variables to make them clearer.
* Remove hardcoded rc.2 logic, we're not using any rc.2 versions right now, so
that's dead code.
* A few other minor changes.
=> [dotnet] Rework how we handle manifest version bands.

system-dependencies.sh
Downloading watchOS 9.1 Simulator (20S75): Error: Error Domain=SimDiskImageErrorDomain Code=5 "Duplicate of F879602F-0F22-47F5-8252-FF177B9032A0" UserInfo={NSLocalizedDescription=Duplicate of F879602F-0F22-47F5-8252-FF177B9032A0, unusableErrorDetail=}
This is a backport of #16845.
=> [xcode14.2] [system-dependencies] Add diagnostics for duplicate sim download error.

dotnet/Workloads/SignList.xml, msbuild/Directory.Build.props, msbuild/ILMerge.targets
- Updated Messaging to 1.9.59: includes latest fixes like support for retry and reconnect, new telemetry, bug fixing, etc.
- Added Merq and Merq.Core to ILMerge since they're now required and loaded by Messaging
- Added Merq.Core.dll to dotnet/Workloads/SignList.xml because now it comes as part of Xamarin.Messaging
Backport of #17685
=> [release/8.0.1xx-preview2] [net8.0] Updated Xamarin.Messaging and added Merq to ILMerge

dotnet/Workloads/SignList.xml, msbuild/Directory.Build.props, msbuild/ILMerge.targets
- Updated Messaging to 1.9.59: includes latest fixes like support for retry and reconnect, new telemetry, bug fixing, etc.
- Added Merq and Merq.Core to ILMerge since they're now required and loaded by Messaging
- Added Merq.Core.dll to dotnet/Workloads/SignList.xml because now it comes as part of Xamarin.Messaging
=> [release/6.0.4xx-xcode14.2] Updated Xamarin.Messaging and added Merq to ILMerge

tools/devops/automation/templates/build/build.yml
Because the variable is an output variable, we need to provide the name of the step that creates the variable. This is nto needed in other stages because we are setting the variable via the env vars of the stage.
=> [CI] Fix the GIT_HASH variable inside the buildjob.

tools/devops/automation/templates/release/vs-insertion-prep.yml
Without the extra condition, the stage iwll run always when the stage dependency was skipped or cancelled.
=> [CI] Ensure that the condition also include the dependency of the stage.

tools/devops/automation/templates/release/vs-insertion-prep.yml
Without the extra condition, the stage iwll run always when the stage dependency was skipped or cancelled.
Backport of #17703
=> [net8.0] [CI] Ensure that the condition also include the dependency of the stage.

tools/devops/automation/templates/main-stage.yml
This reverts commit 59aebf259cf936604d72621e3cb6dd8585620d6c.
We actually do need to keep this task inside our normal builds for the Loc team to identify if there are new translations through the localizationDrop artifact. The other pipeline that runs this task on the cron job is used for a separate part of the localization process that creates the PRs with the usable translations.
https://github.com/xamarin/maccore/wiki/Localization#the-translation-process
Backport of #17537
=> [release/8.0.1xx-preview2] [Localization] Revert "[CI] Remove the translations from the main stage. (#17453)"

tests/monotouch-test/MediaAccessibility/ImageCaptioningTest.cs
=> [xcode14.2] [tests] Adjust ImageCaptioningTest to skip network-related failures in CI.

tests/monotouch-test/Network/NWBrowserTest.cs
Exceptions on background threads will crash the process.
=> [monotouch-test] Fix NWBrowserTest to not throw assertions on background threads.

tests/monotouch-test/ObjCRuntime/EveryFrameworkSmokeTest.cs
It expects the executable to be linked will every system framework we've
bound, which doesn't happen when linker is enabled for all assemblies.
=> [tests] Adjust EveryFrameworkSmokeTest to not run when every assembly is linked.

tests/xharness/Jenkins/Jenkins.cs
We keep adding more and more tests...
Backport of #17110
=> [release/7.0.2xx] [xharness] Bump the timeout for the .NET tests.

tests/monotouch-test/AppKit/NSTextInputClient.cs
Fixes:
apitest.NSTextInputClient
[FAIL] NSTextInputClient_ShouldGetBaselineDelta :   NSTextInputClient_ShouldGetBaselineDelta - Returned wrong baseline delta value
Expected: True
at apitest.NSTextInputClient.NSTextInputClient_ShouldGetBaselineDelta () [0x0000e] in /Users/builder/azdo/_work/3/s/xamarin-macios/tests/monotouch-test/AppKit/NSTextInputClient.cs:108
[FAIL] NSTextInputClient_ShouldGetFirstRect :   NSTextInputClient_ShouldGetFirstRect - Returned wrong rect
Expected: {X=0,Y=0,Width=12,Height=14}
But was:  {X=0,Y=0,Width=0,Height=14}
at apitest.NSTextInputClient.NSTextInputClient_ShouldGetFirstRect () [0x00030] in /Users/builder/azdo/_work/3/s/xamarin-macios/tests/monotouch-test/AppKit/NSTextInputClient.cs:84
=> [tests] Fix NSTextInputClient tests on macOS Ventura.

msbuild/Xamarin.Shared/Xamarin.Shared.targets, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
This makes it easier to consume other tasks in the future that already takes
'_SdkIsSimulator'. It also documents exactly why we hardcode
_SdkIsSimulator=false for Hot Restart.
=> [msbuild] Set the '_SdkIsSimulator' property for HotRestart builds.

src/bgen/Generator.cs, src/bgen/TrampolineInfo.cs, tests/monotouch-test/Photos/LivePhotoEditingContextTest.cs
Change the generated block callbacks so that we only use blittable types (so
that the callbacks can become [UnmanagedCallersOnly]).
This involved two changes:
* Use pointer types instead of ref/out types ('int*' instead of 'ref/out
int').
* Use 'byte' instead of 'bool'.
Contributes towards https://github.com/xamarin/xamarin-macios/issues/15783.
=> [generator] Generate block callback signatures using only blittable types.

dotnet/targets/Xamarin.Shared.Sdk.targets, msbuild/Xamarin.iOS.Tasks/Tasks/GetMlaunchArgumentsTaskBase.cs
Environment variables can be specified using the MlaunchEnvironmentVariables
item group, and any other mlaunch argument can be specified using the
MlaunchAdditionalArguments item group.
Also add support for the XamarinDebugPort and XamarinDebugHosts properties to
make it easy to set the corresponding environment variable using the command
line (since setting item groups using the command line isn't trivial).
Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1755574.
=> [dotnet] Add support for passing environment variables and custom arguments when launching apps with mlaunch.

dotnet/targets/Xamarin.Shared.Sdk.targets
Also don't hardcode the trailing directory separator as a forward slash,
because we might be executing on Windows (which is the real purpose behind
this change).
=> [dotnet] Change _IntermediateDecompressionDir to always have a trailing directory separator.

dotnet/targets/Xamarin.Shared.Sdk.targets, msbuild/Xamarin.iOS.Tasks/Tasks/GetMlaunchArgumentsTaskBase.cs
Environment variables can be specified using the MlaunchEnvironmentVariables
item group, and any other mlaunch argument can be specified using the
MlaunchAdditionalArguments item group.
Also add support for the XamarinDebugPort and XamarinDebugHosts properties to
make it easy to set the corresponding environment variable using the command
line (since setting item groups using the command line isn't trivial).
Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1755574.
Backport of #17730
=> [release/7.0.2xx] [dotnet] Add support for passing environment variables and custom arguments when launching apps with mlaunch.

dotnet/targets/Xamarin.Shared.Sdk.targets, msbuild/Xamarin.iOS.Tasks/Tasks/GetMlaunchArgumentsTaskBase.cs
Environment variables can be specified using the MlaunchEnvironmentVariables
item group, and any other mlaunch argument can be specified using the
MlaunchAdditionalArguments item group.
Also add support for the XamarinDebugPort and XamarinDebugHosts properties to
make it easy to set the corresponding environment variable using the command
line (since setting item groups using the command line isn't trivial).
Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1755574.
Backport of #17730
=> [release/7.0.1xx-xcode14.2] [dotnet] Add support for passing environment variables and custom arguments when launching apps with mlaunch.

NuGet.config, dotnet/targets/Xamarin.Shared.Sdk.targets, msbuild/Xamarin.iOS.Tasks/Tasks/GetMlaunchArgumentsTaskBase.cs
Environment variables can be specified using the MlaunchEnvironmentVariables
item group, and any other mlaunch argument can be specified using the
MlaunchAdditionalArguments item group.
Also add support for the XamarinDebugPort and XamarinDebugHosts properties to
make it easy to set the corresponding environment variable using the command
line (since setting item groups using the command line isn't trivial).
Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1755574.
Backport of #17730
=> [release/8.0.1xx-preview2] [dotnet] Add support for passing environment variables and custom arguments when launching apps with mlaunch.

tests/xammac_tests/xammac_tests.csproj, tools/devops/automation/build-pipeline.yml, tools/devops/automation/build-pull-request.yml, tools/devops/automation/templates/build/api-diff-stage.yml, tools/devops/automation/templates/build/build-stage.yml, tools/devops/automation/templates/main-stage.yml, tools/devops/automation/templates/tests/stage.yml, tools/siminstaller/Program.cs
We are getting a `System.IO.IOException: Resource busy`
when trying to detach with hdiutil on Ventura. When reaching
this spot we are really done with the mounted resource so
let's force detaching and in the event that it fails let's
just log since at this point the simulator is installed.
Bump bots to use the Ventura images, and Add `macOSName`
parameter to our yaml templates.
`macOSName` maps to the `macOS.Name` capability in our bots, this
way we can set the macOS name we want to use on the bots in bot build and tests.
=> [CI] [siminstaller] Bump bots to use the Ventura and make siminstaller more resilient

src/CoreFoundation/CFReadStream.cs, src/CoreFoundation/CFStream.cs, src/CoreFoundation/CFWriteStream.cs
Their format is NETMAJOR_MINOR_OR_GREATER, not NETMAJOR_OR_GREATER.
=> [src] Fix usage of OR_GREATER defines.

src/Makefile
This is automatically done by 'dotnet build', but we don't use 'dotnet build'
to build our platform assemblies, so we have to do it manually since we want
to use these defines in our code.
=> [src] Define NETX_Y_OR_GREATER flags for our platform assemblies.

Make.config, create-make-config.sh
Encode the .NET version we're targeting in the third NuGet version number by
adding X000 (where X is the .NET version) to the commit distance.
This accomplishes a few goals:
* We automatically compute a different NuGet version depending on the .NET version we're targeting.
* Versions are sorted correctly (.NET 7 nugets have a higher version number than .NET 6 nugets).
* It's possible to see which .NET version a NuGet is targeting from the version.
The downside is:
* The scheme breaks down if we need more than three digits for the commit
distance (possible solution: add another zero, so we add X0000 instead of
X000).
=> Encode the .NET version we're targeting in the third NuGet version number.

dotnet/generate-vs-workload.csharp
Context: https://github.com/xamarin/yaml-templates/pull/251
The VS manifest files generated during MSI conversion will now be split up using the workload pack type rather than a substring match.
=> [vs-workload] Remove @(MultiTargetPackNames)

tools/devops/automation/scripts/bash/clean-bot.sh, tools/devops/automation/scripts/bash/clean-simulator-runtime.sh
If there are more than one simulator runtime for a given platform, then remove
all of them.
This will hopefully fix a few problems we're having with hard drive space
issues (we end up with a lot of identical simulator runtimes downloaded).
=> [devops] Clean simulator runtimes from bots.

src/Foundation/NSObject.mac.cs, src/homekit.cs, tests/common/TestRuntime.cs, tests/introspection/ApiCtorInitTest.cs, tests/introspection/ApiSelectorTest.cs, tests/introspection/ApiTypoTest.cs, tests/introspection/Mac/MacApiCtorInitTest.cs, tests/introspection/iOS/iOSApiProtocolTest.cs, tests/monotouch-test/AppKit/NSTextInputClient.cs, tests/monotouch-test/CoreBluetooth/CentralManagerTest.cs, tests/monotouch-test/EventKit/CalendarTest.cs, tests/monotouch-test/HealthKit/HKAppleWalkingSteadinessTest.cs, tests/monotouch-test/MetalPerformanceShaders/MnistTest.cs, tests/monotouch-test/Network/NWPathMonitorTest.cs, tests/monotouch-test/ObjCRuntime/DelegateAndDataSourceTest.cs, tests/monotouch-test/System.Net.Http/MessageHandlers.cs, tools/devops/automation/build-pipeline.yml, tools/devops/automation/build-pull-request.yml
Added Ventura machines to macTestConfigurations within both the
build-ci-pipeline and the build-pr-pipelines.
This is a backport of #17349, #16743, and #16777.
=> [release/7.0.1xx-xcode14.2] Add ventura to mac tests configurations.

src/Foundation/NSObject.mac.cs, src/homekit.cs, tests/common/TestRuntime.cs, tests/introspection/ApiCtorInitTest.cs, tests/introspection/ApiSelectorTest.cs, tests/introspection/ApiTypoTest.cs, tests/introspection/Mac/MacApiCtorInitTest.cs, tests/introspection/iOS/iOSApiProtocolTest.cs, tests/monotouch-test/AppKit/NSTextInputClient.cs, tests/monotouch-test/CoreBluetooth/CentralManagerTest.cs, tests/monotouch-test/EventKit/CalendarTest.cs, tests/monotouch-test/HealthKit/HKAppleWalkingSteadinessTest.cs, tests/monotouch-test/MetalPerformanceShaders/MnistTest.cs, tests/monotouch-test/Network/NWPathMonitorTest.cs, tests/monotouch-test/ObjCRuntime/DelegateAndDataSourceTest.cs, tests/monotouch-test/System.Net.Http/MessageHandlers.cs, tools/devops/automation/build-pipeline.yml, tools/devops/automation/build-pull-request.yml
Added Ventura machines to macTestConfigurations within both the
build-ci-pipeline and the build-pr-pipelines.
This is a backport of #17349, #16743, and #16777.
=> [release/7.0.2xx] Add ventura to mac tests configurations.

system-dependencies.sh
Also fix a condition that would cause the script to provision simulator
runtimes as long as --provision-xcode was *not* passed to the script.
=> [system-dependencies] Improve detection of existing simulator runtimes.

tests/cecil-tests/ApiAvailabilityTest.cs, tests/cecil-tests/AttributeTest.cs, tests/cecil-tests/BlittablePInvokes.cs, tests/cecil-tests/Helper.cs
We have some code that verifies a list of failures against a known set of
failures and:
* Fails if any known failure is fixed.
* Fails if there any new (unknown) failures.
Create a helper method that contains this logic, since it's duplicated quite a
few times across various tests.
=> [tests] Share code to verify failures.

dotnet/targets/Xamarin.Shared.Sdk.targets
This is helpful when doing a command-line -t:Run build, because it's not
possible to set an item group from the command line.
=> [dotnet] Add support for setting an MSBuild property to pass additional mlaunch arguments.

dotnet/Makefile
Context: https://github.com/xamarin/sdk-insertions/issues/56
Updates the VS component version for all workloads to use the NuGet versions commit distance as the third version part.
=> [vs-workload] Update VS Component versions

dotnet/targets/Xamarin.Shared.Sdk.targets
This is helpful when doing a command-line -t:Run build, because it's not
possible to set an item group from the command line.
Backport of #17866
=> [release/8.0.1xx-preview3] [dotnet] Add support for setting an MSBuild property to pass additional mlaunch arguments.

msbuild/Xamarin.iOS.Tasks/Tasks/GetMlaunchArgumentsTaskBase.cs
Because depending on other options the default can be either 'true' or
'false', and this way we always ask mlaunch to do the right thing.
Also ensure any additional arguments are added last, so they can override any
other argument.
=> [msbuild] Always pass --wait-for-exit:<value> to mlaunch.

msbuild/Xamarin.iOS.Tasks/Tasks/GetMlaunchArgumentsTaskBase.cs
Because depending on other options the default can be either 'true' or
'false', and this way we always ask mlaunch to do the right thing.
Also ensure any additional arguments are added last, so they can override any
other argument.
Backport of #17865
=> [release/8.0.1xx-preview3] [msbuild] Always pass --wait-for-exit:<value> to mlaunch.

tools/devops/automation/templates/common/setup.yml
=> [release/8.0.1xx-preview3] [CI] Fix GitHub ssh host key

tools/devops/automation/templates/common/setup.yml
=> [release/7.0.2xx] [CI] Fix GitHub ssh host key

dotnet/Makefile
Context: https://github.com/xamarin/sdk-insertions/issues/56
Updates the VS component version for all workloads to use the NuGet versions commit distance as the third version part.
Backport of #17883
=> [release/8.0.1xx-preview3] [vs-workload] Update VS Component versions

msbuild/Directory.Build.props, msbuild/ILMerge.targets
=> [release/6.0.4xx-xcode14.2] Updated Xamarin.Messaging to 1.9.94

msbuild/Directory.Build.props, msbuild/ILMerge.targets
=> [release/7.0.2xx] Updated Xamarin.Messaging to 1.9.94

msbuild/Directory.Build.props, msbuild/ILMerge.targets
=> [release/8.0.1xx-preview3] Updated Xamarin.Messaging to 1.9.94

msbuild/Directory.Build.props, msbuild/ILMerge.targets
=> Updated Xamarin.Messaging to 1.9.94

dotnet/BundleContents.md, msbuild/Xamarin.MacDev.Tasks/Tasks/ComputeBundleLocationTaskBase.cs, tests/dotnet/BundleStructure/shared.csproj, tests/dotnet/UnitTests/BundleStructureTest.cs
This fixes a warning when documentation is enabled for a project:
> The file '~/.nuget/packages/fsharp.core/6.0.0/contentFiles/any/netstandard2.1/FSharp.Core.xml' does not specify a 'PublishFolderType' metadata, and a default value could not be calculated. The file will not be copied to the app bundle.
This doesn't change any behavior (as the warning says, the file wasn't copied
to the app bundle before either), but it makes the behavior explicitly
documented and silences the warning.
Fixes https://github.com/xamarin/xamarin-macios/issues/14939.
Fixes https://github.com/xamarin/xamarin-macios/issues/15897.
=> [dotnet/msbuild] Don't bundle *.xml files that match any assemblies. Fixes #14939 and fixes #15897.

msbuild/Directory.Build.props, msbuild/ILMerge.targets
=> [xcode14.2] Updated Xamarin.Messaging to 1.9.94

docs/configuration-properties.md
Fixes #17738
Addresses the initial issue of just documenting which properties are tied to which configuration. But to make the documentation more helpful, we should provide further context about what exactly these properties mean. However, this isn't trivial as some properties are a bit cryptic..once further info is acquired, it will be integrated in a later revision.
=> [docs] Document properties for configurations

msbuild/Xamarin.iOS.Tasks/Tasks/GetMlaunchArgumentsTaskBase.cs
Because depending on other options the default can be either 'true' or
'false', and this way we always ask mlaunch to do the right thing.
Also ensure any additional arguments are added last, so they can override any
other argument.
Backport of #17865
=> [release/7.0.2xx] [msbuild] Always pass --wait-for-exit:<value> to mlaunch.

tools/devops/automation/templates/windows/build.yml
We need the upload prefix. The parameter uses the default which will be empty in this repo but will have the correct prefix in the unified pipeline.
=> [CI] Fix the windows tests in the unified pipeline.

Make.config
Bump to stable version of Xcode 14.3
Backport of #17953
=> [release/6.0.4xx-xcode14.3] Bump to stable Xcode 14.3

msbuild/Directory.Build.props
=> [release/7.0.2xx] Fixed remote and local build issues

msbuild/Directory.Build.props, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
=> [release/6.0.4xx-xcode14.3] Fixed remote and local build issues

msbuild/Directory.Build.props, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
=> [release/7.0.2xx-xcode14.3] Fixed remote and local build issues

msbuild/Directory.Build.props, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
=> Fixed remote and local build issues

msbuild/Directory.Build.props, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
=> [xcode14.3] Fixed remote and local build issues

msbuild/Directory.Build.props, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
=> [release/6.0.4xx-xcode14.2] Fixed remote and local build issues

msbuild/Directory.Build.props, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
=> [release/8.0.1xx-preview3] Fixed remote and local build issues

msbuild/Directory.Build.props, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
=> [xcode14.2] Fixed remote and local build issues

tools/devops/automation/build-cronjob.yml, tools/devops/automation/templates/loc-translations.yml
This PR does a few things to help the Localization process happen more efficiently:
1) Add a cron job
* One will run on Sundays (as before) and this one will set the new variable to be true and will create a PR into main with the usable translations
* The other will run after each weekday at around midnight and will allow the Loc team to see our newly added error codes much faster but will not look for the new localization for us to use each day.
2) Allow us to manually run the pipeline and create the Localization PR with the new usable translations whenever we want (for example if there was an error on the weekly build and we don't want to wait until the next weekend to get the new strings)
=> [Localization] Run the OneLoc Task more efficiently  

NuGet.config, tools/devops/automation/templates/windows/build.yml
1. Keep the .NET 6 feed, because even though we've dropped support for .NET 6, parts of the build may still need access to the feed.
> Workload installation failed: microsoft.maccatalyst.sdk::16.2.19 is not found in NuGet feeds [long list of feeds, but not the right one]
2. Pass a runsettings to 'dotnet test' to tell it to use the .NET version we've downloaded, otherwise it will try to use any .NET version installed on the system (🤦‍♂️) - which doesn't work because we need to use .NET 8, and the system only has .NET 7.
=> [net8.0] Fix the Windows tests

dotnet/targets/Xamarin.Shared.Sdk.targets
If the `RecursiveDir` metadata is empty, the GetDirectoryName method throws an error because it isn't a valid path. This can happen on VS design time builds.
=> [msbuild] Get RecursiveDir directory name only if it isn't empty

dotnet/targets/Xamarin.Shared.Sdk.targets
If the `RecursiveDir` metadata is empty, the GetDirectoryName method throws an error because it isn't a valid path. This can happen on VS design time builds.
Backport of #17988
=> [xcode14.3] [msbuild] Get RecursiveDir directory name only if it isn't empty

dotnet/targets/Xamarin.Shared.Sdk.targets
If the `RecursiveDir` metadata is empty, the GetDirectoryName method throws an error because it isn't a valid path. This can happen on VS design time builds.
Backport of #17988
=> [release/7.0.2xx-xcode14.3] [msbuild] Get RecursiveDir directory name only if it isn't empty

tools/devops/automation/build-cronjob.yml, tools/devops/automation/templates/loc-translations.yml
Pipelines didn't like the scheduled variables so let's try using the schedule displayName instead
=> [Localization] Remove Schedule Variables and use displayName

tools/devops/automation/build-lego.yml
This fixes a syntax issue to allow the [xamarin.macios-legoChanges](https://devdiv.visualstudio.com/DevDiv/_build?definitionId=18272&_a=summary) pipeline to bring over the Loc changes from the Localization branch in PRs similar to the one below!
https://github.com/xamarin/xamarin-macios/pull/17998
=> [Localization] Use backticks and include label and milestone

src/Foundation/NSUrlSessionHandler.cs
Preserve all members of WrappedNSInputStream, and mark it as a non-direct
binding class, so that the linker doesn't trim away any virtual overrides,
since they're actually necessary.
Fixes https://github.com/xamarin/xamarin-macios/issues/15860.
=> [Foundation] Preserve all members of WrappedNSInputStream. Fixes #15860.

tests/dotnet/UnitTests/ProjectTest.cs
Fixes this test failure when building only for iOS (and similar for tvOS):
Xamarin.Tests.DotNetProjectTest.LibraryReferencingBindingLibrary(iOS): Existence
Expected: file or directory exists
But was: "/Users/builder/azdo/_work/4/s/xamarin-macios/tests/dotnet/LibraryReferencingBindingLibrary/iOS/bin/Debug/net7.0-ios/BindingWithDefaultCompileInclude.resources.zip"
=> [tests] Fix assumption that we'll always produce a compressed binding resource package in the ProjectTest.LibraryReferencingBindingLibrary test.

tests/cecil-tests/Helper.cs, tests/common/Configuration.cs
This fixes a test failure when not including all platforms:
Cecil.Tests.BlittablePInvokes.CheckForNonBlittablePInvokes: Known failures that aren't failing anymore - remove these from the list of known failures: In the file tests/cecil-tests/BlittablePInvokes.cs, read the guide carefully.
Expected: <empty>
But was: < "AudioUnit.AudioComponentStatus AudioUnit.AudioUnit::AudioOutputUnitPublish(AudioUnit.AudioComponentDescription,System.IntPtr,System.UInt32,System.IntPtr)", ...
=> [tests] Fix BlittablePInvokes.CheckForNonBlittablePInvokes to not verify known failures unless building for all platforms.

src/Foundation/NSObject.mac.cs, src/homekit.cs, tests/common/TestRuntime.cs, tests/introspection/ApiCtorInitTest.cs, tests/introspection/ApiSelectorTest.cs, tests/introspection/ApiTypoTest.cs, tests/introspection/Mac/MacApiCtorInitTest.cs, tests/introspection/iOS/iOSApiProtocolTest.cs, tests/monotouch-test/AppKit/NSTextInputClient.cs, tests/monotouch-test/CoreBluetooth/CentralManagerTest.cs, tests/monotouch-test/EventKit/CalendarTest.cs, tests/monotouch-test/HealthKit/HKAppleWalkingSteadinessTest.cs, tests/monotouch-test/MetalPerformanceShaders/MnistTest.cs, tests/monotouch-test/Network/NWPathMonitorTest.cs, tests/monotouch-test/ObjCRuntime/DelegateAndDataSourceTest.cs, tests/monotouch-test/System.Net.Http/MessageHandlers.cs, tests/xammac_tests/xammac_tests.csproj, tools/devops/automation/build-pipeline.yml, tools/devops/automation/build-pull-request.yml
Added Ventura machines to macTestConfigurations within both the
build-ci-pipeline and the build-pr-pipelines.
This is a backport of #17349.
---------
=> [xcode14.2] Add ventura to mac tests configurations

src/Foundation/NSUrlSessionHandler.cs
Preserve all members of WrappedNSInputStream, and mark it as a non-direct
binding class, so that the linker doesn't trim away any virtual overrides,
since they're actually necessary.
Fixes https://github.com/xamarin/xamarin-macios/issues/15860.
Backport of #18011
=> [release/7.0.2xx-xcode14.3] [Foundation] Preserve all members of WrappedNSInputStream. Fixes #15860.

src/Foundation/NSUrlSessionHandler.cs
Preserve all members of WrappedNSInputStream, and mark it as a non-direct
binding class, so that the linker doesn't trim away any virtual overrides,
since they're actually necessary.
Fixes https://github.com/xamarin/xamarin-macios/issues/15860.
Backport of #18011
=> [xcode14.3] [Foundation] Preserve all members of WrappedNSInputStream. Fixes #15860.

tools/devops/automation/templates/windows/build.yml
Failing to install .NET or the corresponding workloads is a failure that should not
be ignored.
=> [devops] Don't ignore setup failures in the windows tests.

msbuild/Xamarin.iOS.Tasks.Windows/Tasks/PrepareAppBundle.cs, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.props, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
This makes it easier to write tests that verify the files written in this paths,
because the tests can specify these output directories instead of evaluating a project
file or duplicating the logic to compute them.
Additionally, the tests can also easily make sure the output is cleaned up once the test is done.
=> [msbuild] Honor any existing values for HotRestartSignedAppOutputDir and HotRestartAppBundlePath.

msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
This makes writing tests easier, because we won't need a functioning code signing
setup in order to verify other parts of a build.
=> [msbuild] Allow setting EnableCodeSigning=false to disable code signing for Hot Restart.

msbuild/Directory.Build.props
There is a new version of `Xamarin.Messaging`, so updating nugget package to that.
=> Update MessagingVersion in Directory.Build.props

Make.config, NuGet.config, builds/Makefile, builds/package-download/download-packages.csproj, eng/Version.Details.xml, eng/Versions.props, global.json
Also fix a duplicated entry for 'Microsoft.NET.Workload.Emscripten.net7.Manifest-7.0.100',
and run 'darc update-dependencies' to update the dependencies.
Backport of #18026
=> [release/7.0.2xx-xcode14.3] [maestro] Make 'Microsoft.NETCore.App.Ref' depend on 'Microsoft.Dotnet.Sdk.Internal'.

dotnet/targets/Xamarin.Shared.Sdk.targets, msbuild/Xamarin.MacDev.Tasks/Tasks/CreateDebugConfigurationTaskBase.cs, msbuild/Xamarin.Shared/Xamarin.Shared.targets, runtime/monotouch-debug.m
The timeout can be given:
* By setting the __XAMARIN_DEBUG_CONNECT_TIMEOUT__ environment variable for the app when launching it.
* By passing the XamarinDebugConnectTimeout MSBuild property to 'dotnet run' or 'dotnet build /t:Run'.
* By setting the IOSDebugConnectTimeout MSBuild property at build time.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1778177.
=> [runtime] Add support for passing on a connect timeout to sdb.

msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets, tools/devops/automation/scripts/show_env.ps1, tools/devops/automation/templates/build/api-diff-process-results.yml, tools/devops/automation/templates/common/setup.yml, tools/devops/automation/templates/governance-checks.yml, tools/devops/automation/templates/mac/build.yml, tools/devops/automation/templates/sign-and-notarized/funnel.yml, tools/devops/automation/templates/windows/build.yml
We are trying to minimize as much as possible the size of the expanded yaml, the show  env code was present in several locations
Ref, we are tyring to remove the following error:
> __built-in-schema.yml: Maximum object size exceeded. Reduce the size of your YAML pipeline.
> If you have large inline scripts, for example, can you factor them out and check them in?
=> [CI] Remove code repetition in an attempt to reduce the size of the yaml

src/bgen/Generator.cs, tests/generator/BGenTests.cs, tests/generator/bug18025.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/18025.
=> [bgen] Check for null (no) namespace when matching namespace to framework. Fixes #18025.

tests/common/TestRuntime.cs
=> [tests] Ignore DNS lookup failures in CI.

dotnet/targets/Xamarin.Shared.Sdk.targets, msbuild/Xamarin.MacDev.Tasks/Tasks/CreateDebugConfigurationTaskBase.cs, msbuild/Xamarin.Shared/Xamarin.Shared.targets, runtime/monotouch-debug.m
The timeout can be given:
* By setting the __XAMARIN_DEBUG_CONNECT_TIMEOUT__ environment variable for the app when launching it.
* By passing the XamarinDebugConnectTimeout MSBuild property to 'dotnet run' or 'dotnet build /t:Run'.
* By setting the IOSDebugConnectTimeout MSBuild property at build time.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1778177.
Backport of #18037
=> [release/7.0.2xx-xcode14.3] [runtime] Add support for passing on a connect timeout to sdb.

tools/class-redirector/class-redirector-tests/CodeTests.cs
I wanted to make sure that multiple classes work correctly.
In all the previous tests, I was looking at either 1 class or the first class. Great, that works, but keep in mind that the code initializes the class handles looks like this:
```
ClassHandles.SomeObjCName = map [const].handle
```
I'm not really writing this code, since I'm writing directly in IL. The code that I generate looks like this:
```
ldarg map
ldc.i4 const
sizeof ObjCRuntime.Runtime/MTClassMap
mul
add
ldfld ObjCRuntime.Runtime/MTClassMap::handle
```
So what does that do?
1 - puts the address of the start of the map on the stack
2 - puts a constant (the index of the item we care about) on the stack
3 - puts the size of the MTClassMap on the stack
4 - multiply 2 & 3, leaving the result on the stack (this is the offset in …
=> [dotnet] Added one more test to ensure that multiple types in a file work.

tests/common/TestRuntime.cs
=> [release/7.0.2xx-xcode14.3] [tests] Ignore DNS lookup failures in CI.

Make.config, NuGet.config, builds/Makefile, builds/package-download/download-packages.csproj, eng/Version.Details.xml, eng/Versions.props
=> [release/7.0.2xx] [maestro] Make 'Microsoft.NETCore.App.Ref' depend on 'Microsoft.Dotnet.Sdk.Internal'.

msbuild/Xamarin.MacDev.Tasks/Tasks/CompileAppManifestTaskBase.cs, msbuild/Xamarin.Shared/Xamarin.Shared.targets, tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/CompileAppManifestTaskTests.cs, tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/GeneratePlistTaskTests/GeneratePlistTaskTests_Core.cs
We don't need the SdkPlatform input, because we can compute it from other input properties.
=> [msbuild] Simplify the CompileAppManifest a bit by removing the SdkPlatform input property.

tools/devops/automation/templates/build/build-mac-tests-stage.yml, tools/devops/automation/templates/build/build-mac-tests.yml, tools/devops/automation/templates/build/build-pkgs.yml, tools/devops/automation/templates/build/build.yml, tools/devops/automation/templates/mac/build.yml, tools/devops/automation/templates/mac/stage.yml, tools/devops/automation/templates/main-stage.yml
This has a few benefits:
* We can get packages build sooner, since the main build stage is faster
(about 10 minutes faster, since that's how long it takes to build the macOS
tests).
* We can re-start the macOS test building stage without having to re-do the
entire main build stage (which would also cause a re-run of all the other
tests).
* It's easier to see if the macOS test failed to build, since they're not as
hidden (we can make them red instead of orange since they won't cause
packages to fail to build/publish anymore).
=> [devops] Split building the macOS tests from the main build stage.

Make.config, NuGet.config, builds/Makefile, builds/package-download/download-packages.csproj, eng/Version.Details.xml, eng/Versions.props, global.json, tests/dotnet/UnitTests/ProjectTest.cs
=> [release/6.0.4xx-xcode14.2] [maestro] Make 'Microsoft.NETCore.App.Ref' depend on 'Microsoft.Dotnet.Sdk.Internal'.

msbuild/Xamarin.MacDev.Tasks/Tasks/ReadAppManifestTaskBase.cs, msbuild/Xamarin.Shared/Xamarin.Shared.targets, tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/ReadAppManifestTaskTests.cs
The ReadAppManifest task doesn't need the SdkVersion, because it's only used to compute
the path to the sdk on disk, and that path can be calculated without an sdk version
now:
$ ls -la /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs
total 0
drwxrwxr-x  4 rolf  staff  128 Dec 14 10:58 .
drwxr-xr-x  5 rolf  staff  160 Nov 11 01:38 ..
drwxrwxr-x  8 rolf  staff  256 Dec 14 10:48 iPhoneOS.sdk
lrwxr-xr-x  1 rolf  staff   12 Dec 14 10:56 iPhoneOS16.2.sdk -> iPhoneOS.sdk
In fact, the path with the version just symlinks to the path without.
=> [msbuild] Remove the SdkVersion property in the ReadAppManifest task.

tests/common/TestRuntime.cs
=> [xcode14.2] [tests] Ignore DNS lookup failures in CI.

tests/introspection/ApiProtocolTest.cs, tests/introspection/ApiSelectorTest.cs
The corresponding API fixes are available in our Xcode 14.3 branch, so this is
just to make sure the current branch (supporting Xcode 14.2) doesn't have test
failures when executing on a later version of macOS.
Fixes:
Introspection.MacApiProtocolTest
[FAIL] Coding :   1 types conforms to NSCoding but does not implement INSCoding: CAEdrMetadata
Expected: 1
But was:  0
[FAIL] CAEdrMetadata conforms to NSCoding but does not implement INSCoding
at Introspection.ApiProtocolTest.Coding() in /Users/builder/azdo/_work/5/s/xamarin-macios/tests/introspection/ApiProtocolTest.cs:line 611
[FAIL] Copying :   1 types conforms to NSCopying but does not implement INSCopying: CAEdrMetadata
Expected: 1
But was:  0
[FAIL] CAEdrMetadata conforms to NSCopying but does not implement INSCopying
at …
=> [release/7.0.2xx] [tests] Update introspection to run on latest Ventura version.

Make.config, NuGet.config, builds/Makefile, builds/package-download/download-packages.csproj, eng/Version.Details.xml, eng/Versions.props, global.json
Also fix a duplicated entry for 'Microsoft.NET.Workload.Emscripten.net7.Manifest-7.0.100',
and run 'darc update-dependencies' to update the dependencies.
Backport of #18026
=> [xcode14.3] [maestro] Make 'Microsoft.NETCore.App.Ref' depend on 'Microsoft.Dotnet.Sdk.Internal'.

tests/common/TestRuntime.cs
=> [release/6.0.4xx-xcode14.2] [tests] Ignore DNS lookup failures in CI.

tests/common/TestRuntime.cs
=> [xcode14.3] [tests] Ignore DNS lookup failures in CI.

Make.config, NuGet.config, builds/Makefile, builds/package-download/download-packages.csproj, eng/Version.Details.xml, eng/Versions.props, global.json, tests/dotnet/UnitTests/ProjectTest.cs
=> [release/6.0.4xx-xcode14.3] [maestro] Make 'Microsoft.NETCore.App.Ref' depend on 'Microsoft.Dotnet.Sdk.Internal'.

tests/xharness/TestLabel.cs
We already have support for 'run-windows-tests' and 'skip-windows-tests' labels: 3e86254ef8f91b41eafcecdf3934fc74c7f115d9.
=> [xharness] Add support for tests labeled 'Windows'.

dotnet/targets/Xamarin.Shared.Sdk.targets, tests/dotnet/UnitTests/ProjectTest.cs
This makes it unnecessary to special-case this file for it to copied correctly
when building on Windows (once we've fixed the Windows build to use
ResolvedFileToPublish as the source of truth, like we do on macOS).
This is the first part of a fix for https://github.com/xamarin/xamarin-macios/issues/17579.
=> [dotnet] Include the parsed runtimeconfig.bin into ResolvedFileToPublish. Contributes towards #17579.

tools/devops/automation/scripts/clean_past_comments.ps1
Fixes:
Import-Module : The specified module 'MaciosCI.psd1' was not loaded because no valid module file was found in any module directory.
At D:\a\1\s\xamarin-macios\tools\devops\automation\scripts\clean_past_comments.ps1:21 char:1
+ Import-Module MaciosCI.psd1
=> [devops] Use fully qualified path to load MaciosCI.psd1.

src/bgen/AttributeFactory.ConstructorArguments.cs, tests/generator/ConstructorArgumentsTests.cs, tests/generator/generator-tests.csproj
Also fix a nullability warning.
Fixes these warnings:
"tests/generator/generator-tests.csproj" (default target) (1:7) ->
(CoreCompile target) ->
tests/generator/AttributeFactoryTests.cs(43,29): warning CS0436: The type 'AttributeFactory' in 'tests/generator/../../src/bgen/AttributeFactory.cs' conflicts with the imported type 'AttributeFactory' in 'bgen, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'tests/generator/../../src/bgen/AttributeFactory.cs'.
tests/generator/AttributeFactoryTests.cs(44,29): warning CS0436: The type 'AttributeFactory' in 'tests/generator/../../src/bgen/AttributeFactory.cs' conflicts with the imported type 'AttributeFactory' in 'bgen, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in …
=> [tests] Remove files from the generator tests to fix compiler warnings.

tests/introspection/ApiTypeTest.cs
=> [introspection] Ignore the AddressBook namespace for Mac Catalyst when checking static cctors.

Localize/loc/cs/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/de/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/es/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/fr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/it/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/ja/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/ko/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/pl/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/pt-BR/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/ru/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/tr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/zh-Hans/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/zh-Hant/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
As mentioned in this issue: https://github.com/xamarin/maccore/issues/2658
These are being brought over to main in a PR, but then are automatically closed by `vs-mobiletools-engineering-service2` as you can see here: https://github.com/xamarin/xamarin-macios/pull/18036
I am still looking into this peculiar behavior, but am bringing over the new translations until then!
=> [Localization] Bring over more translations

tests/introspection/ApiTypeTest.cs
=> [release/6.0.4xx-xcode14.3] [introspection] Ignore the AddressBook namespace for Mac Catalyst when checking static cctors.

tests/introspection/ApiTypeTest.cs
=> [release/7.0.2xx] [introspection] Ignore the AddressBook namespace for Mac Catalyst when checking static cctors.

tests/introspection/ApiTypeTest.cs
=> [release/7.0.2xx-xcode14.3] [introspection] Ignore the AddressBook namespace for Mac Catalyst when checking static cctors.

tests/introspection/ApiTypeTest.cs
=> [release/7.0.3xx] [introspection] Ignore the AddressBook namespace for Mac Catalyst when checking static cctors.

tests/introspection/ApiTypeTest.cs
=> [xcode14.3] [introspection] Ignore the AddressBook namespace for Mac Catalyst when checking static cctors.

tests/introspection/ApiTypeTest.cs
=> [xcode14.2] [introspection] Ignore the AddressBook namespace for Mac Catalyst when checking static cctors.

tests/introspection/ApiTypeTest.cs
=> [release/6.0.4xx-xcode14.2] [introspection] Ignore the AddressBook namespace for Mac Catalyst when checking static cctors.

tests/introspection/ApiProtocolTest.cs, tests/introspection/ApiSelectorTest.cs
The corresponding API fixes are available in our Xcode 14.3 branch, so this is
just to make sure the current branch (supporting Xcode 14.2) doesn't have test
failures when executing on a later version of macOS.
Fixes:
Introspection.MacApiProtocolTest
[FAIL] Coding :   1 types conforms to NSCoding but does not implement INSCoding: CAEdrMetadata
Expected: 1
But was:  0
[FAIL] CAEdrMetadata conforms to NSCoding but does not implement INSCoding
at Introspection.ApiProtocolTest.Coding() in /Users/builder/azdo/_work/5/s/xamarin-macios/tests/introspection/ApiProtocolTest.cs:line 611
[FAIL] Copying :   1 types conforms to NSCopying but does not implement INSCopying: CAEdrMetadata
Expected: 1
But was:  0
[FAIL] CAEdrMetadata conforms to NSCopying but does not implement INSCopying
at …
=> [release/6.0.4xx-xcode14.2] [release/7.0.2xx] [tests] Update introspection to run on latest Ventura version.

tools/devops/automation/templates/windows/build.yml
Because Windows sometimes gives this random and somewhat cute error:
Unhandled exception: System.IO.FileNotFoundException: Retrieving the COM class factory for component with CLSID {177F0C4A-1CD3-4DE7-A32C-71DBBB9FA36D} failed due to the following error: 8007007e The specified module could not be found. (0x8007007E).
at System.RuntimeTypeHandle.AllocateComObject(Void* pClassFactory)
at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
at Microsoft.DotNet.Workloads.Workload.List.VisualStudioWorkloads.GetVisualStudioInstances()
at Microsoft.DotNet.Workloads.Workload.List.VisualStudioWorkloads.GetInstalledWorkloads(IWorkloadResolver workloadResolver, SdkFeatureBand sdkFeatureBand, InstalledWorkloadsCollection installedWorkloads)
at …
=> [devops] Ignore any errors when printing the system's .NET version on Windows.

src/appkit.cs, tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.ignore, tests/xtro-sharpie/macOS-AppKit.ignore
Fixes https://github.com/xamarin/xamarin-macios/issues/18115.
=> [AppKit] Add a few missing NullAllowed attributes. Fixes #18115.

runtime/runtime.m
=> [runtime] Always look for dynamic libraries relative to the root directory first. Fixes #xamarin/maccore@2668.

tools/devops/automation/templates/windows/build.yml
Because Windows sometimes gives this random and somewhat cute error:
Unhandled exception: System.IO.FileNotFoundException: Retrieving the COM class factory for component with CLSID {177F0C4A-1CD3-4DE7-A32C-71DBBB9FA36D} failed due to the following error: 8007007e The specified module could not be found. (0x8007007E).
at System.RuntimeTypeHandle.AllocateComObject(Void* pClassFactory)
at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
at Microsoft.DotNet.Workloads.Workload.List.VisualStudioWorkloads.GetVisualStudioInstances()
at Microsoft.DotNet.Workloads.Workload.List.VisualStudioWorkloads.GetInstalledWorkloads(IWorkloadResolver workloadResolver, SdkFeatureBand sdkFeatureBand, InstalledWorkloadsCollection installedWorkloads)
at …
=> [release/7.0.2xx-xcode14.3] [devops] Ignore any errors when printing the system's .NET version on Windows.

tools/devops/automation/templates/windows/build.yml
Because Windows sometimes gives this random and somewhat cute error:
Unhandled exception: System.IO.FileNotFoundException: Retrieving the COM class factory for component with CLSID {177F0C4A-1CD3-4DE7-A32C-71DBBB9FA36D} failed due to the following error: 8007007e The specified module could not be found. (0x8007007E).
at System.RuntimeTypeHandle.AllocateComObject(Void* pClassFactory)
at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
at Microsoft.DotNet.Workloads.Workload.List.VisualStudioWorkloads.GetVisualStudioInstances()
at Microsoft.DotNet.Workloads.Workload.List.VisualStudioWorkloads.GetInstalledWorkloads(IWorkloadResolver workloadResolver, SdkFeatureBand sdkFeatureBand, InstalledWorkloadsCollection installedWorkloads)
at …
=> [xcode14.3] [devops] Ignore any errors when printing the system's .NET version on Windows.

src/CoreMidi/MidiThruConnectionParams.cs
Otherwise the static registrar won't know that the native name is different
from the managed name in generated registrar code (and the generated registrar
code won't compile).
=> [CoreMidi] Sprinkle a few more NativeName attributes for various structs.

tests/bindings-test/Messaging.cs, tests/monotouch-test/ObjCRuntime/Messaging.cs
This fixes ~1600 warnings like these:
warning CS0436: The type 'Messaging' in 'xamarin-macios/tests/monotouch-test/ObjCRuntime/Messaging.cs' conflicts with the imported type 'Messaging' in 'bindings-test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'
=> [tests] Make any ObjCRuntime.Messaging internal.

dotnet/targets/Xamarin.Shared.Sdk.targets
=> [dotnet] Add a missing IsMacEnabled check before executing a task in the _ComputeLinkerArguments target.

tests/cecil-tests/BlittablePInvokes.cs
The calli instruction calls a function pointer on the stack, not a specific
managed function, so include it when looking for calls to managed functions.
=> [tests] Fix finding instructions that take methods in cecil-tests.

Localize/loc/cs/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/de/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/es/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/it/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/pl/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/pt-BR/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/tr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/zh-Hans/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/zh-Hant/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
When bringing over the translations in this [PR](https://github.com/xamarin/xamarin-macios/pull/18105), I brought over a few and did not notice that the old ones were still there. This removes the duplicates
=> [Localization] Remove Duplicate Translations

tools/devops/automation/scripts/localizationBomRemoval.ps1, tools/devops/automation/templates/loc-translations.yml
Please see the issue - https://github.com/xamarin/xamarin-macios/issues/18099
This PR updates the custom powershell script to try to remove the BOM.
After this lands, I will manually run the pipeline to create a new Localization PR in main and see if the BOM is removed.
You can see the ticket from the Loc team here which specifies this change - https://ceapex.visualstudio.com/CEINTL/_workitems/edit/816066
=> [Localization] Use new custom powershell script for removing BOM - Part 2

tests/monotouch-test/SpriteKit/SKTransformNodeTest.cs
=> [tests] Allow a little bit of leeway when testing floating point numbers in SKTransformNodeTest.

tests/common/AppDelegate.cs
=> [tests] Find a workaround for #xamarin/maccore@2668.

runtime/runtime.m
=> [release/7.0.2xx-xcode14.3] [runtime] Always look for dynamic libraries relative to the root directory first. Fixes #xamarin/maccore@2668.

runtime/runtime.m
=> [release/7.0.3xx] [runtime] Always look for dynamic libraries relative to the root directory first. Fixes #xamarin/maccore@2668.

runtime/runtime.m
=> [release/6.0.4xx-xcode14.3] [runtime] Always look for dynamic libraries relative to the root directory first. Fixes #xamarin/maccore@2668.

runtime/runtime.m
=> [release/6.0.4xx-xcode14.2] [runtime] Always look for dynamic libraries relative to the root directory first. Fixes #xamarin/maccore@2668.

dotnet/targets/Xamarin.Shared.Sdk.targets
=> [release/6.0.4xx-xcode14.3] [dotnet] Add a missing IsMacEnabled check before executing a task in the _ComputeLinkerArguments target.

dotnet/targets/Xamarin.Shared.Sdk.targets
=> [release/7.0.2xx] [dotnet] Add a missing IsMacEnabled check before executing a task in the _ComputeLinkerArguments target.

dotnet/targets/Xamarin.Shared.Sdk.targets
=> [release/7.0.3xx] [dotnet] Add a missing IsMacEnabled check before executing a task in the _ComputeLinkerArguments target.

tests/Makefile
We have tests to execute on macOS even if only Mac Catalyst is enabled, so
package those tests in that case as well.
=> [tests] Package macOS tests even if only Mac Catalyst is enabled.

tests/monotouch-test/SpriteKit/SKTransformNodeTest.cs
=> [release/6.0.4xx-xcode14.3] [tests] Allow a little bit of leeway when testing floating point numbers in SKTransformNodeTest.

tests/monotouch-test/SpriteKit/SKTransformNodeTest.cs
=> [release/6.0.4xx-xcode14.2] [tests] Allow a little bit of leeway when testing floating point numbers in SKTransformNodeTest.

tests/monotouch-test/SpriteKit/SKTransformNodeTest.cs
=> [release/7.0.2xx-xcode14.3] [tests] Allow a little bit of leeway when testing floating point numbers in SKTransformNodeTest.

tests/common/AppDelegate.cs
=> [release/7.0.2xx-xcode14.3] [tests] Find a workaround for #xamarin/maccore@2668.

tests/monotouch-test/AppDelegate.cs
=> [release/6.0.4xx-xcode14.3] [tests] Find a workaround for #xamarin/maccore@2668.

tests/monotouch-test/SpriteKit/SKTransformNodeTest.cs
=> [release/7.0.3xx] [tests] Allow a little bit of leeway when testing floating point numbers in SKTransformNodeTest.

tests/common/AppDelegate.cs
=> [release/7.0.3xx] [tests] Find a workaround for #xamarin/maccore@2668.

tests/monotouch-test/SpriteKit/SKTransformNodeTest.cs
=> [release/7.0.2xx] [tests] Allow a little bit of leeway when testing floating point numbers in SKTransformNodeTest.

dotnet/targets/Xamarin.Shared.Sdk.targets
=> [release/6.0.4xx-xcode14.2] [dotnet] Add a missing IsMacEnabled check before executing a task in the _ComputeLinkerArguments target.

tools/common/Application.cs, tools/common/Driver.cs, tools/common/StaticRegistrar.cs, tools/dotnet-linker/Steps/RegistrarStep.cs, tools/mmp/driver.cs, tools/mtouch/BuildTasks.mtouch.cs
Removed the default argument value
Added `Application.ClassMapPath`
Added options and setter for `ClassMapPath`
Integrated usage.
Note that the test for whether or not to write the file is based on whether the path passed in is `null` or empty, so this should cause no immediate problems.
=> [dotnet] Use the type_map_path arg

tests/monotouch-test/SpriteKit/SKTransformNodeTest.cs
=> [release/8.0.1xx-preview4] [tests] Allow a little bit of leeway when testing floating point numbers in SKTransformNodeTest.

tests/common/AppDelegate.cs
=> [release/8.0.1xx-preview4] [tests] Find a workaround for #xamarin/maccore@2668.

runtime/runtime.m
=> [release/7.0.2xx] [runtime] Always look for dynamic libraries relative to the root directory first. Fixes #xamarin/maccore@2668.

tests/xharness/Harness.cs, tests/xharness/TestProject.cs
When cloning projects, we need to list all the files in the original project
directory and manually include some of them in the cloned project (because in
.NET some files from the project directory are included automatically, and if
we clone a project and put the cloned project in a different directory, those
files won't be picked up automatically by the build anymore).
The previous code to list the files in the project directory would run 'git
ls-files' for each project directory. This is rather slow, since it happens
quite a few times. Instead modify the logic to run 'git ls-files' once for the
entire tests/ directory, store the result, and then when we need to list files
in a particular project directory, just look in that stored list for the
applicable files.
This is much, much …
=> [xharness] Improve listing files in the repository.

dotnet/targets/Xamarin.Shared.Sdk.targets
The name is `HasMetadata`, not `HasMetadataValue` (https://learn.microsoft.com/en-us/visualstudio/msbuild/item-functions?view=vs-2022).
=> Fix the name of the item function.

tests/xharness/Jenkins/TestData.cs, tests/xharness/Jenkins/TestVariationsFactory.cs
Make the code that creates test variations set a single BundlingArguments
property, and then when we generate the corresponding test project we set both
MtouchExtraArgs and MonoBundlingExtraArgs. The property that doesn't apply to
the current platform will just be ignored.
=> [xharness] Unify MtouchExtraArgs and MonoBundlingExtraArgs handling when creating test variations.

dotnet/targets/Xamarin.Shared.Sdk.targets
=> [release/7.0.2xx-xcode14.3] [dotnet] Add a missing IsMacEnabled check before executing a task in the _ComputeLinkerArguments target.

dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalyst-view/.template.config/localize/templatestrings.es.json
This change didn't really get rid of the non-breaking space and caused extra changes after we built xamarin-macios.
=> [Localization] Revert change to non-breaking space

tests/test-libraries/custom-type-assembly/Makefile
'dotnet build' doesn't work when MSBUILD_EXE_PATH is set (which we do in some places
for legacy tests), so make sure to unset MSBUILD_EXE_PATH before running 'dotnet
build'.
=> [tests] Fix running dotnet with MSBUILD_EXE_PATH.

src/ObjCRuntime/Registrar.cs, tests/monotouch-test/AppKit/DerivedEventTest.cs, tests/monotouch-test/ObjCRuntime/RegistrarTest.cs, tests/xharness/Jenkins/TestVariationsFactory.cs
Add a 'release + all optimization' test variation of monotouch-test for macOS
and Mac Catalyst.
=> [xharness] Add a release + all optimization test variation of monotouch-test for desktop.

tools/devops/automation/templates/tests/publish-html.yml
That way we can re-run it when something does go wrong (instead of rerunning the _entire pipeline_).
=> [devops] Fail the 'Add summaries' task if something goes wrong.

tests/dotnet/Windows/InstallDotNet.csproj
Hopefully fixes:
MSBuild version 17.4.1+9a89d02ff for .NET
D:\AzDO\_work\_tool\dotnet\sdk\7.0.102\MSBuild.dll --property:DisableImplicitNuGetFallbackFolder=true -bl:D:\AzDO\_work\2\s/xamarin-macios/tests/dotnet/Windows/install.binlog -consoleloggerparameters:Summary -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,D:\AzDO\_work\_tool\dotnet\sdk\7.0.102\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,D:\AzDO\_work\_tool\dotnet\sdk\7.0.102\dotnet.dll -maxcpucount -restore -verbosity:m -verbosity:quiet D:\AzDO\_work\2\s/xamarin-macios/tests/dotnet/Windows/InstallDotNet.csproj
EXEC : error : NU3004: The package is not signed. [D:\AzDO\_work\2\s\xamarin-macios\tests\dotnet\Windows\InstallDotNet.csproj]
=> [tests] Install workloads on Windows without checking the signature of the packages.

runtime/Makefile
This way the runtime libraries are always up-to-date after building after
making local commits.
=> [runtime] Re-generate product.h when the current commit changes.

dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalyst-view/.template.config/localize/templatestrings.es.json, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.cs.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.de.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.es.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.fr.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.it.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ja.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ko.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pl.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pt-BR.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ru.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.tr.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hans.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17751: Build ID 7737739

src/webkit.cs
Note that both the headers and the documentation are incorrect in this case. All of the `WebView.*Delegate` objects are documented as non-nullable, but in all cases it's wrong. The binding for the other `Delegate`s allows `null`s in Xamarin.
Failure to remove the `EditingDelegate` reference may result in a crash when the `WebView` object gets disposed:
```
16  xamarin_release_managed_ref + 108 (eM Client + 63772) [0x100ecf91c]
16  -[Xilium_CefGlue_CefWebView release] + 32 (eM Client + 116128) [0x100edc5a0]
16  xamarin_invoke_objc_method_implementation + 140 (eM Client + 73400) 
[0x100ed1eb8]
16  -[WebView dealloc] + 112 (WebKitLegacy + 166520) [0x1ccf72a78]
16  -[WebView(WebPrivate) _close] + 364 (WebKitLegacy + 167048) [0x1ccf72c88]
16  WebCore::FrameLoader::detachFromParent() + 48 …
```
=> Fix nullability of WebView.EditingDelegate

tests/xharness/Jenkins/TestVariationsFactory.cs
This is because the SetTopLevelPropertyGroupValue method doesn't always work
as expected (it doesn't always set seomthing), while SetProperty does.
Fixing the SetTopLevelPropertyGroup method is somewhat complex, since it lives
in the dotnet/xharness repository, so instead use the SetProperty method,
which is our own (working) version.
=> [xharness] Use our own SetProperty to set properties instead of the SetTopLevelPropertyGroupValue extension method.

tests/monotouch-test/Security/SecProtocolMetadataTest.cs
Fixes https://github.com/xamarin/maccore/issues/2040.
=> [monotouch-test] Ignore network failures in CI for SecProtocolMetadataTest.TlsDefaults. Fixes #xamarin/maccore@2040.

msbuild/Xamarin.iOS.Tasks/Tasks/MTouchTaskBase.cs, tools/autoformat.sh
The autoformat action doesn't necessarily run on macOS, and sed's syntax is
different between macOS and Linux - so make sure to cope with these
differences.
Also execute the nullability fixes in a separate subshell to not interfere
with the rest of the script.
This fixes an issue where autoformat would fail with:
+ sed -i '' -e 's/!= null/is not null/g' -e 's/== null/is null/g' builds/fix-maccatalyst-assembly/Program.cs
sed: can't read : No such file or directory
=> [autoformat] Fix running sed on Linux.

tests/monotouch-test/MediaAccessibility/ImageCaptioningTest.cs
This check is passing a remote url to an API that wants a url to a local file
(file:// url), and this is supposed to fail (it's not a network hiccup if it
fails).
However, sometimes it doesn't fail... for unknown reasons. So instead change
the test's expectations so that it passes whether using a remote url fails
with an error or not.
=> [monotouch-test] Adjust ImageCaptioningTest.GetCaption to don't care if we get an error or not.

src/bgen/BindingTouch.cs, src/bgen/Filters.cs, src/bgen/bgen.csproj
Also make nullability warnings errors, so we don't add any more nullability issues.
Fixes:
src/bgen/Filters.cs(215,9): warning CS8602: Dereference of a possibly null reference.
src/bgen/Filters.cs(242,23): warning CS8604: Possible null reference argument for parameter 'str' in 'string StringExtensions.Capitalize(string str)'.
src/bgen/BindingTouch.cs(528,29): warning CS8604: Possible null reference argument for parameter 'item' in 'bool List<string>.Contains(string item)'.
=> [bgen] Fix a few nullability warnings.

src/ObjCRuntime/Class.cs
Use NSLog instead of Console.WriteLine for tracing, because this makes it easier to trace what happens during a test run:
* NUnit will capture anything written to Console.Out/Console.Error during a
test run.
* Nothing will be printed if the process crashes during a test run.
* NSLog statements will be printed as they are executed, which makes it much
better for figuring out what happened just before a crash when running unit
tests.
=> [src] Use NSLog instead of Console.WriteLine in tracing statements.

dotnet/Makefile, dotnet/targets/AutoImport.template.props
Context: https://aka.ms/maui-support-policy
Context: https://github.com/xamarin/xamarin-android/commit/25cb50d78ac929b03d2ec6f1a4c0a7aeb9bcebc3
Context: https://github.com/dotnet/sdk/pull/32426
dotnet/sdk#32426 adds support for an optional workload to specify that it is no longer supported by adding an item to the `@(EolWorkload)` item group:
<ItemGroup Condition=" '$(TargetPlatformIdentifier)' == 'iOS' and $([MSBuild]::VersionEquals($(TargetFrameworkVersion), '6.0')) ">
<EolWorkload Include="ios" Url="https://aka.ms/maui-support-policy" />
</ItemGroup>
This will cause `dotnet build` to issue a new NETSDK1202 build warning:
dotnet\sdk\6.0.409\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(35,5):
warning NETSDK1202: The workload 'ios' is out of support and will …
=> [dotnet] add metadata about .NET 6 EOL

msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx, msbuild/Xamarin.MacDev.Tasks/Tasks/FindAotCompilerTaskBase.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/FindILLink.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/XamarinBuildTask.cs, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
When building from Windows, we need to pass the path to the illink assembly located on the Mac to the linker task. The educated guess we've been using is a bit fragile and has been getting us problems almost on each new .NET major release. On top of that, from .NET 8 the linker is in a separate NuGet package, so the assembly is no longer located in the SDK directory on the Mac.
The fix is to follow the same approach we use to find the AOT compiler on the Mac by running a target that finds that information on the remote Mac, and brings it back to Windows, where it is cached and use across build.
Created a new XamarinBuildTask class to share most of the code needed for this approach.
=> [dotnet] Fix linker path on Windows

dotnet/targets/Xamarin.Shared.Sdk.targets
Given the following truths:
* A task will (try to) connect to a Mac if its SessionId property isn't empty.
* The BuildSessionId property is always set on Windows when building from an IDE (even if not connected to a remote Mac).
It stands to reason that we can't use BuildSessionId to distinguish between
connected/not conected status on Windows. Instead introduce a new property,
BuildSessionIdIfConnected, which is only set if connected to a Mac (i.e. if
'IsMacEnabled=true').
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1808448 (second attempt).
=> [msbuild] Fix calling the GetFileSystemEntries task on Windows when not connected to a Mac.

tools/devops/automation/build-pull-request.yml
That step is failing or Prs with the following messsage:
`
##[error]The signing feature is not available for your organization yet.
`
Yet we do not need or care about the sbom on a pr. We can remove it and that way not get the error and use less resources.
=> [DevOps] Do not sign the sbom on the prs.

tools/create-dotnet-linker-launch-json/Program.cs, tools/create-dotnet-linker-launch-json/README.md, tools/create-dotnet-linker-launch-json/create-dotnet-linker-launch-json.csproj, tools/create-dotnet-linker-launch-json/create-dotnet-linker-launch-json.sln
This tool takes a binlog as input, and creates a launch.json for dotnet-linker
that will execute the linker as was done in the binlog.
This is very useful for debugging custom linker steps, since they can be
debugged in VSCode now.
=> [tools] Add helper tool to create launch.json for dotnet-linker.

msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx, msbuild/Xamarin.MacDev.Tasks/Tasks/FindAotCompilerTaskBase.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/FindILLink.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/XamarinBuildTask.cs, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
When building from Windows, we need to pass the path to the illink
assembly located on the Mac to the linker task. The educated guess we've
been using is a bit fragile and has been getting us problems almost on
each new .NET major release. On top of that, from .NET 8 the linker is
in a separate NuGet package, so the assembly is no longer located in the
SDK directory on the Mac.
The fix is to follow the same approach we use to find the AOT compiler
on the Mac by running a target that finds that information on the remote
Mac, and brings it back to Windows, where it is cached and use across
build.
Created a new XamarinBuildTask class to share most of the code needed
for this approach.
Backport of #18285.
=> [release/7.0.2xx-xcode14.3] [dotnet] Fix linker path on Windows

dotnet/targets/Xamarin.Shared.Sdk.targets
Given the following truths:
* A task will (try to) connect to a Mac if its SessionId property isn't empty.
* The BuildSessionId property is always set on Windows when building from an IDE (even if not connected to a remote Mac).
It stands to reason that we can't use BuildSessionId to distinguish between
connected/not conected status on Windows. Instead introduce a new property,
BuildSessionIdIfConnected, which is only set if connected to a Mac (i.e. if
'IsMacEnabled=true').
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1808448 (second attempt).
Backport of #18287
=> [release/7.0.2xx-xcode14.3] [msbuild] Fix calling the GetFileSystemEntries task on Windows when not connected to a Mac.

src/ObjCRuntime/Blocks.cs, src/ObjCRuntime/Runtime.cs
We can be asked to keep the same block+delegate pair alive multiple times, so
add support for keeping track how many times a block must be freed once the
corresponding delegate is collected by the GC.
Fixes https://github.com/xamarin/xamarin-macios/issues/18161.
Backport of #18277
=> [release/7.0.2xx-xcode14.3] [runtime] Add support for keeping the same block alive multiple times. Fixes #18161.

tests/monotouch-test/Metal/MTLArgumentEncoderTest.cs
The test fails on iOS 12.4, and works on iOS 16.5, so for now ignore if <iOS
13.0.
=> [monotouch-test] Ignore MTLArgumentEncoderTest on older devices.

tests/Makefile
If only some platforms are enabled, some of the commands to find files to add
to package-test-libraries.zip won't find any files at all.
Asking 'zip' to add no files fails with:
zip error: Nothing to do!
and there's no way to add 'zip' to ignore this error condition.
However, we can instead try to not call zip at all when we don't find any
files, and we do that by using:
"find ... -exec zip"
instead of:
"find .. | zip ..."
=> [tests] Fix adding no files to package-test-libraries.zip.

tests/monotouch-test/MediaAccessibility/ImageCaptioningTest.cs
* This test creates a file in the temp directory, so make sure the file name
is unique enough to not clash with any other test runs running concurrently.
Fixes this problem:
> SetCaption: System.IO.IOException : IO_SharingViolation_File, /var/folders/r7/kvhxkfw54qlc5y72d620783h0000gn/T/basn3p08.png
* Also delete the temporary file at the end of the test.
This PR is best viewed by ignoring whitespace, since it indents a big chunk of
code.
=> [tests] Adjust ImageCaptioningTest to clean up after itself and support concurrent execution.

dotnet/targets/Xamarin.Shared.Sdk.targets, msbuild/Xamarin.MacDev.Tasks/Tasks/GetFileSystemEntries.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/GetFileSystemEntriesTaskBase.cs
Make the GetFileSystemEntries task capable of copying files to the Mac, and
enable this new behavior when inspecting references for binding resources.
Otherwise the task might not find anything, if the files aren't copied to the
Mac (this happens if the files originate from NuGets instead of referenced
projects).
Ref:
* https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1808448 (third attempt)
* https://github.com/xamarin/xamarin-macios/issues/18308
Backport of #18324
=> [release/7.0.2xx-xcode14.3] [msbuild] Make the GetFileSystemEntries task capable of copying files to the Mac.

msbuild/Directory.Build.props, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
- Update Hot Restart client to 1.0.119: bring latest isignsharp fix https://github.com/xamarin/isignsharp/commit/71220d490a83761a63bf005e326d3834e8b18d00
- Added missing app markers back:
- Added .stamp files to make incremental deployments work again and to avoid re-installing the application. We use .stamp files to know which files to copy on incremental deployments and also to avoid unnecessary app installations
- Added .hotrestartapp file back to identify the main app entry point. We need this since the main entry point to dynamically load the app might change between Forms and MAUI (could be a .dll or an .exe), so we need a way to let the Hot Restart app to know which is the main assembly to load
- Fixed outputs in _CodesignHotRestartAppBundle target: the codesign was being executed …
=> [main] Hot Restart fixes

tools/devops/automation/templates/tests/run-tests.yml, tools/devops/automation/templates/tests/stage.yml
The final result is the same, but because a matrix strategy is a native element of azure pipeline, it does not get expanded. This makes our pipeline to be reduce to under 10.000 lines of yaml when it was around 40.000. This should unblock the dev of https://github.com/xamarin/xamarin-macios/pull/18279
=> [CI] Use the template to generate a matrix strategy which reduces the yaml explosion.

dotnet/Microsoft.MacCatalyst.Sdk/targets/Microsoft.MacCatalyst.Sdk.targets, dotnet/Microsoft.macOS.Sdk/targets/Microsoft.macOS.Sdk.targets
* Add support for forwarding our debugging msbuild properties to their
corresponding environment variables (the XamarinDebug* properties).
* Add support for passing --stdout/--stderr/--stdin to open to redirect
to/from a file. This is particularly useful for debugging debugging.
* Add support for passing -a (to always create a new instance of the app).
This is useful when debugging (when the developer would always want a new
instance, instead of opening an existing instance).
* Also add support for any other argument using the 'OpenArguments' property.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1825427.
=> [dotnet] Add support for asking more of 'open' when launching desktop apps.

msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
Backport of #18334.
Ref: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1827733
=> [release/7.0.2xx-xcode14.3] [msbuild] Add a missing 'UsingTask' for the FindILLink task.

dotnet/Microsoft.MacCatalyst.Sdk/targets/Microsoft.MacCatalyst.Sdk.targets, dotnet/Microsoft.macOS.Sdk/targets/Microsoft.macOS.Sdk.targets
* Add support for forwarding our debugging msbuild properties to their
corresponding environment variables (the XamarinDebug* properties).
* Add support for passing --stdout/--stderr/--stdin to open to redirect
to/from a file. This is particularly useful for debugging debugging.
* Add support for passing -a (to always create a new instance of the app).
This is useful when debugging (when the developer would always want a new
instance, instead of opening an existing instance).
* Also add support for any other argument using the 'OpenArguments' property.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1825427.
Backport of #18366
=> [release/7.0.2xx-xcode14.3] [dotnet] Add support for asking more of 'open' when launching desktop apps.

msbuild/Directory.Build.props, msbuild/Makefile, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Tasks.Windows.csproj
We need to update the `System.Diagnostics.Tracer` package to version `2.1.0-alpha` due to an issue with the `ChecksumAlgorithm` property of older versions.
=> Update Messaging and HotRestart versions

tools/devops/automation/templates/governance-checks.yml
Fixes these warnings in Azure DevOps:
* Please upgrade the version of this build task in your build to major version: 2. For more information, please see: https://aka.ms/gdn-v1-deprecation
Governance Checks • Governance Checks • PoliCheck
* Please upgrade the version of this build task in your build to major version: 2. For more information, please see: https://aka.ms/gdn-v1-deprecation
Governance Checks • Governance Checks • Post Analysis
=> [devops] Upgrade the PoliCheck and PostAnalysis tasks to v2.

tests/monotouch-test/CoreFoundation/BundleTest.cs
It seems the actual app name might be "PublicStaging.app" on device now.
Fixes:
MonoTouchFixtures.CoreFoundation.BundleTest
[FAIL] TestExecutableUrl :
Expected: String containing "monotouchtest.app/monotouchtest"
But was:  "file:///private/var/containers/Bundle/Application/4B2AD441-C411-42D4-ACCB-4E964A905A17/PublicStaging.app/monotouchtest"
[FAIL] TestResourcesDirectoryUrl :
Expected: String containing "monotouchtest.app/"
But was:  "file:///private/var/containers/Bundle/Application/4B2AD441-C411-42D4-ACCB-4E964A905A17/PublicStaging.app/"
[FAIL] TestSupportFilesDirectoryUrl :
Expected: String containing "monotouchtest.app/"
But was:  "file:///private/var/containers/Bundle/Application/4B2AD441-C411-42D4-ACCB-4E964A905A17/PublicStaging.app/"
[FAIL] TestUrl :
Expected: String containing …
=> [tests] Adjust BundleTest to cope with a differently named app.

tests/common/TestRuntime.cs
Fixes:
MonoTouchFixtures.AVFoundation.CaptureMetadataOutputTest
[PASS] Defaults
[PASS] Flags
[FAIL] MetadataObjectTypesTest : System.NotImplementedException : The method or operation is not implemented.
at TestRuntime.CheckXcodeVersion(Int32 major, Int32 minor, Int32 build) in xamarin-macios/tests/common/TestRuntime.cs:line 483
at MonoTouchFixtures.AVFoundation.CaptureMetadataOutputTest.MetadataObjectTypesTest() in xamarin-macios/tests/monotouch-test/AVFoundation/CaptureMetadataOutputTest.cs:line 131
at System.Reflection.MethodInvoker.InterpretedInvoke(Object , Span`1 , BindingFlags )
=> [tests] Update the Xcode version check for Xcode 13.3.

tests/monotouch-test/Phase/PhaseObjectTest.cs
Fixes:
MonoTouchFixtures.Phase.PhaseObjectTest
[FAIL] ForwardTest :   length
Expected: 1
But was:  <System.Func`1[System.Single]>
[FAIL] RigthTest :   length
Expected: 1
But was:  <System.Func`1[System.Single]>
[FAIL] UpTest :   length
Expected: 1
But was:  <System.Func`1[System.Single]>
=> [tests] System.Numerics.Vector3.Length is a method, not a property, so treat it as such.

dotnet/targets/Xamarin.Shared.Sdk.props
This property will be required when building for a net7.0-* target framework
using .NET 8 (preview 6 - preview 5 does not need this fix)
Backport of #18411
=> [dotnet] Set _RequiresILLinkPack=true so that we always restore the ILLink package.

msbuild/Directory.Build.props, msbuild/Makefile, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Tasks.Windows.csproj
We need to update the `System.Diagnostics.Tracer` package to version `2.1.0-alpha` due to an issue with the `ChecksumAlgorithm` property of older versions.
Cherry-pick: https://github.com/xamarin/xamarin-macios/pull/18310
=> Update Messaging and System.Diagnostics.Tracer versions

msbuild/Xamarin.MacDev.Tasks/Tasks/CreateBindingResourcePackageBase.cs
This fixes a build problem on windows when a project has a project reference
to a binding project. The binding resource package from the binding project
would lack the manifest, and thus the main project wouldn't detect it as a
binding resource package, effectively not seeing any native resource from the
binding project.
Fixes https://github.com/xamarin/xamarin-macios/issues/18402.
=> [msbuild] Make sure to copy the manifest from a binding resource package back to Windows. Fixes #18402.

msbuild/Xamarin.MacDev.Tasks/Tasks/CreateBindingResourcePackageBase.cs
This fixes a build problem on windows when a project has a project reference
to a binding project. The binding resource package from the binding project
would lack the manifest, and thus the main project wouldn't detect it as a
binding resource package, effectively not seeing any native resource from the
binding project.
Fixes https://github.com/xamarin/xamarin-macios/issues/18402.
Backport of #18419.
=> [release/7.0.2xx-xcode14.3] [msbuild] Make sure to copy the manifest from a binding resource package back to Windows. Fixes #18402.

msbuild/Directory.Build.props, msbuild/Makefile, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Tasks.Windows.csproj
We need to update the `System.Diagnostics.Tracer` package to version `2.1.0-alpha` due to an issue with the `ChecksumAlgorithm` property of older versions.
Cherry-pick: https://github.com/xamarin/xamarin-macios/pull/18310
Backport of #18416
=> [release/8.0.1xx-preview5] Update Messaging and System.Diagnostics.Tracer versions

tools/common/Make.common
This fixes a frequent issue where building locally again would create test
apps where the registrar would fail due to mismatched runtime versions.
=> [tools] Automatically re-create ProductConstants.cs when the current commit changes.

dotnet/Microsoft.iOS.Windows.Sdk/targets/Microsoft.iOS.Windows.Sdk.props, dotnet/targets/Xamarin.Shared.Sdk.targets, tests/common/BinLog.cs, tests/dotnet/UnitTests/MlaunchTest.cs
Add public targets to compute the mlaunch command lines for installing and launching mobile apps.
These new targets are:
* ComputeMlaunchInstallArguments
* ComputeMlaunchRunArguments
As part of this change, also create a few new public properties:
* MlaunchPath
* MlaunchRunArguments
* MlaunchInstallArguments
* MlaunchRunScript
* MlaunchInstallScript
If the *Script variables are set, the corresponding target will create a
script file with the path to mlaunch + the corresponding arguments.
Otherwise, it's also possible to get the arguments directly from the build
log.
Fixes https://github.com/xamarin/xamarin-macios/issues/18359.
=> [dotnet] Add targets to compute mlaunch arguments for installing and launching mobile apps. Fixes #18359.

dotnet/targets/Xamarin.Shared.Sdk.targets
It seems this target has more problems than at first I thought, so make it
easier to opt-out of it by just setting a property in the csproj.
More investigation is needed, but I'm keeping the target on by default for
now, since it solves a real-world problem as well.
Ref: https://github.com/xamarin/xamarin-macios/issues/18445
=> [dotnet] Add a property to opt-out of the _CopyLocalBindingResources logic easily.

dotnet/targets/Xamarin.Shared.Sdk.targets
It seems this target has more problems than at first I thought, so make it
easier to opt-out of it by just setting a property in the csproj.
More investigation is needed, but I'm keeping the target on by default for
now, since it solves a real-world problem as well.
Ref: https://github.com/xamarin/xamarin-macios/issues/18445
Backport of #18443
=> [release/7.0.2xx-xcode14.3] [dotnet] Add a property to opt-out of the _CopyLocalBindingResources logic easily.

msbuild/Xamarin.MacDev.Tasks/Tasks/Zip.cs
The zip file might be used later directly on Windows (for instance it might be
embedded inside a binding assembly as an embedded resource), so make sure to
copy it back to Windows.
Fixes https://github.com/xamarin/xamarin-macios/issues/18402 part 2.
Backport of #18447
=> [release/7.0.2xx-xcode14.3] [msbuild] Copy the zip file back to Windows from the Zip task for remote builds. Fixes #18402.

dotnet/Microsoft.iOS.Windows.Sdk/targets/Microsoft.iOS.Windows.Sdk.props, dotnet/targets/Xamarin.Shared.Sdk.targets, tests/common/BinLog.cs, tests/dotnet/UnitTests/MlaunchTest.cs
Add public targets to compute the mlaunch command lines for installing
and launching mobile apps.
These new targets are:
* ComputeMlaunchInstallArguments
* ComputeMlaunchRunArguments
As part of this change, also create a few new public properties:
* MlaunchPath
* MlaunchRunArguments
* MlaunchInstallArguments
* MlaunchRunScript
* MlaunchInstallScript
If the *Script variables are set, the corresponding target will create a
script file with the path to mlaunch + the corresponding arguments.
Otherwise, it's also possible to get the arguments directly from the
build log.
Fixes https://github.com/xamarin/xamarin-macios/issues/18359.
Backport of #18446.
=> [release/7.0.2xx-xcode14.3] [dotnet] Add targets to compute mlaunch arguments for installing and launching mobile apps. Fixes #18359.

src/bgen/Generator.cs
Also don't create the instance directly from third-party bindings, the
required constructor might not be public - use Runtime.GetINativeObject
instead.
Fixes part 4 of https://github.com/xamarin/xamarin-macios/issues/18452.
=> [bgen] Make the generated code check for zero handle before creating an INativeObject wrapper instance. Fixes part of #18452.

src/avfoundation.cs, tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-AVFoundation.todo, tests/xtro-sharpie/api-annotations-dotnet/iOS-AVFoundation.todo, tests/xtro-sharpie/api-annotations-dotnet/macOS-AVFoundation.todo, tests/xtro-sharpie/api-annotations-dotnet/tvOS-AVFoundation.todo, tests/xtro-sharpie/iOS-AVFoundation.todo, tests/xtro-sharpie/macOS-AVFoundation.todo, tests/xtro-sharpie/tvOS-AVFoundation.todo
* The 'copyCGImageAtTime:actualTime:error:' selector is deprecated, so replicate that.
* Bind the 'generateCGImageAsynchronouslyForTime:completionHandler:' selector.
Fixes parts 1 and 2 of https://github.com/xamarin/xamarin-macios/issues/18452.
=> [AVFoundation] Fix a few issues with the AVAssetImageGenerator bindings. Partial fix for #18452.

src/Foundation/NSUrlSessionHandler.cs, tests/dotnet/UnitTests/MlaunchTest.cs, tests/monotouch-test/System.Net.Http/MessageHandlers.cs
=> NSUrlSessionHandler should propagate network exceptions

src/bgen/Generator.cs
There's no purpose to catching an exception just to throw it, so remove the
entire try/catch handler.
src/bgen/Generator.cs(1284,4): warning CA2200: Re-throwing caught exception changes stack information
=> [bgen] Remove useless catch/(re)throw.

msbuild/Xamarin.HotRestart.PreBuilt/Makefile
This makes it easy to copy-paste the path to the binlog to open it in a binlog
viewer.
=> [msbuild] Print the binlog if the prebuilt app failed to build.

.gitignore, Directory.Build.props, Make.config, dotnet/Makefile, dotnet/targets/Microsoft.Sdk.Versions.template.props, dotnet/targets/Xamarin.Shared.Sdk.targets, msbuild/Directory.Build.props
Detect if we're using a non-stable Xcode, and in that case produce packages
that show an error if they're used and the EnablePreviewFeatures flag isn't
enabled.
Also add logic to set this flag for our own build, otherwise all our tests
would fail.
This is the same as Android does.
Contributes towards https://github.com/xamarin/xamarin-macios/issues/18343.
=> [net8.0] [build] Require using EnablePreviewFeatures=true when using preview releases. Contributes towards #18343.

msbuild/Xamarin.MacDev.Tasks/LinkerOptions.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/LinkNativeCodeTaskBase.cs, tests/dotnet/BundleStructure/AppDelegate.cs, tests/dotnet/BundleStructure/shared.csproj, tests/dotnet/UnitTests/BundleStructureTest.cs, tests/test-libraries/libraries/Makefile
For a given dylib named '/path/to/libMyLibrary.dylib', we pass this to the native linker:
-L/path/to -lMyLibrary
however, that doesn't work unless the dylib's name starts with 'lib'.
So detect this, and if the dylib doesn't start with 'lib' (say it's just
'MyLibrary.dylib'), then just pass the path to the dylib as-is to the native
linker:
/path/to/MyLibrary.dylib
Fixes https://github.com/xamarin/xamarin-macios/issues/15044.
=> [msbuild/dotnet] Handle dylibs that don't start with 'lib' better. Fixes #15044.

dotnet/targets/Xamarin.Shared.Sdk.targets, tests/common/DotNet.cs, tests/dotnet/UnitTests/BundleStructureTest.cs, tools/dotnet-linker/LinkerConfiguration.cs, tools/dotnet-linker/Steps/GenerateMainStep.cs
Add HybridGlobalization flag in SDK and load icudt_hybrid.dat file when HybridGlobalization is on.
Contributes to https://github.com/dotnet/runtime/issues/80689
cc @SamMonoRT
=> [iOS] HybridGlobalization set flag in SDK

msbuild/Xamarin.iOS.Tasks/Tasks/ILStripBase.cs
Any assembly that's not already on the Mac must be copied there, so do that.
We detect if an assembly exist on the Mac by checking the file size of the
file on Windows: a 0-length file is an output file from an assembly that exist
on the Mac, otherwise it doesn't and must be copied.
Fixes https://github.com/xamarin/xamarin-macios/issues/17009.
Fixes https://github.com/xamarin/xamarin-macios/issues/14841.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1817898.
=> [msbuild] Fix ILStripping of resource assemblies on Windows.

msbuild/Xamarin.iOS.Tasks/Tasks/ILStrip.cs
Any assembly that's not already on the Mac must be copied there, so do that.
We detect if an assembly exist on the Mac by checking the file size of the
file on Windows: a 0-length file is an output file from an assembly that exist
on the Mac, otherwise it doesn't and must be copied.
Fixes https://github.com/xamarin/xamarin-macios/issues/17009.
Fixes https://github.com/xamarin/xamarin-macios/issues/14841.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1817898.
Backport of #18508.
=> [release/7.0.3xx] [msbuild] Fix ILStripping of resource assemblies on Windows.

dotnet/targets/Xamarin.Shared.Sdk.targets, runtime/coreclr-bridge.m, runtime/monotouch-main.m
Since NativeAOT generates native libraries and executables that do not rely on assemblies they were compiled from, all managed assemblies can be excluded from the application bundle.
This reduces the size of the application bundle by `3,17Mb` (or ~19% compared to the baseline)
| MAUI ios app | Base | This PR | diff (%) |
|--------------|-----------|-----------|----------|
| SOD (Mb)     | 50,13 | 41,93 | -16,3%      |
| .ipa (Mb)    | 16,59  | 13,43  | -19%      |
Fixes: https://github.com/xamarin/xamarin-macios/issues/18472
=> Exclude assemblies from NativeAOT app bundles

msbuild/Xamarin.iOS.Tasks.Windows/Tasks/DetectHotRestartSigningIdentity.cs
The detection of signing identities should fail if we could not build a valid app id. This code originally checked for null (`AppId == null`) and was replaced by `is not null` as part of https://github.com/xamarin/xamarin-macios/commit/36af0292043a63897311c035bb0d4afb7a1a44b2#diff-ff4502eb16b65dc59bb7de2bf980024260e83d7b97fef727c9c033374f2b3533R106.
=> [msbuild] Fix null check when validating Hot Restart app identifier

dotnet/targets/Xamarin.Shared.Sdk.targets
Alternative to #18530, see https://github.com/xamarin/xamarin-macios/pull/18530#discussion_r1258565808
Contributes to #18482
=> Fix _DefaultLinkMode for NativeAOT.

eng/Version.Details.xml, eng/Versions.props, global.json
This reverts commit a2ce5f3485337c3ff24f635fa28980eb27ab2782.
This is a temporary revert until we figure out why ILLink breaks MAUI with
```
ILLink : unknown error IL7000: An error occured while executing the custom linker steps. Please review the build log for more information. [/Users/builder/azdo/_work/2/s/src/Essentials/samples/Samples/Essentials.Sample.csproj::TargetFramework=net8.0-ios]
ILLINK : error MT2301: The linker step 'Setup' failed during processing: Failed to parse PList data type: dict [/Users/builder/azdo/_work/2/s/src/Essentials/samples/Samples/Essentials.Sample.csproj::TargetFramework=net8.0-ios]
```
As seen here https://dev.azure.com/xamarin/public/_build/results?buildId=91068&view=logs&j=3a2c3e05-58d9-5668-2c58-02c61841ec5f&t=0d23cc4d-c509-5473-9e43-147360f36c68
=> [net8.0] Revert "[net8.0] Update dependencies from dotnet/installer #18525)"

eng/Version.Details.xml, eng/Versions.props
This pull request updates the following dependencies
[marker]: <> (Begin:34d10fbb-96e7-4139-42ad-08db73ee5f69)
- **Subscription**: 34d10fbb-96e7-4139-42ad-08db73ee5f69
- **Build**: 20230630.11
- **Date Produced**: June 30, 2023 5:09:35 PM UTC
- **Commit**: 43ae6c749407e47fdf5fa07295119b87f7328ea6
- **Branch**: refs/heads/release/7.0.3xx
[DependencyUpdate]: <> (Begin)
- **Updates**:
- **Microsoft.tvOS.Sdk**: [from 16.4.7089 to 16.4.7090][4]
[4]: https://github.com/xamarin/xamarin-macios/compare/663e05acb1...43ae6c7494
[DependencyUpdate]: <> (End)
[marker]: <> (End:34d10fbb-96e7-4139-42ad-08db73ee5f69)
Backport of #18527
=> [release/8.0.1xx-preview7] [net8.0] Update dependencies from xamarin/xamarin-macios

msbuild/Messaging/Xamarin.Messaging.Build/TaskRunner.cs, msbuild/Xamarin.MacDev.Tasks/Extensions/TaskExtensions.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/BTouchTaskBase.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/ComputeRemoteGeneratorPropertiesTaskBase.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/XamarinBuildTask.cs
. the Build Agent and remote tasks
DOTNET_ROOT and DOTNET_HOST_PATH are being deprecated as a mechanism to store the location of dotnet. PATH will be used instead, so we should ensure that the existing code that makes usage of these variables is adapted to the new guidelines. More information:
https://github.com/dotnet/roslyn/commit/f454d6960e979b6643f805f66f619650024a3f34
https://github.com/dotnet/runtime/issues/88754#issuecomment-1632957579
Additionally, to avoid confusion, we are using a dedicate DOTNET_CUSTOM_PATH variable with the path of the dotnet used by the XMA Build Agent, so it can be used internally by the tasks without mixing it with the existing dotnet variables
Backport of #18567
=> [release/8.0.1xx-preview7] [dotnet][xma] Ensure we don't use DOTNET_ROOT and DOTNET_HOST_PATH in.

msbuild/Messaging/Xamarin.Messaging.Build/TaskRunner.cs, msbuild/Xamarin.MacDev.Tasks/Extensions/TaskExtensions.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/BTouchTaskBase.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/ComputeRemoteGeneratorPropertiesTaskBase.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/XamarinBuildTask.cs
. the Build Agent and remote tasks
DOTNET_ROOT and DOTNET_HOST_PATH are being deprecated as a mechanism to store the location of dotnet. PATH will be used instead, so we should ensure that the existing code that makes usage of these variables is adapted to the new guidelines. More information:
https://github.com/dotnet/roslyn/commit/f454d6960e979b6643f805f66f619650024a3f34
https://github.com/dotnet/runtime/issues/88754#issuecomment-1632957579
Additionally, to avoid confusion, we are using a dedicate DOTNET_CUSTOM_PATH variable with the path of the dotnet used by the XMA Build Agent, so it can be used internally by the tasks without mixing it with the existing dotnet variables
Backport of #18567
=> [net8.0] [dotnet][xma] Ensure we don't use DOTNET_ROOT and DOTNET_HOST_PATH in.

tests/xharness/Harness.cs
This commit fixes the code that was added in
https://github.com/xamarin/xamarin-macios/pull/16361.
The previous change uses the version number that is part of the config file in the current build machine. That is correct when we are working when we are running the tests in the same machine that built them. That IS NOT THE CASE when building on CI.
Back when the CI did the separation to accommodate the EO we noticed that if the workload is built in a diff machine, the versions were not to be trusted, that is why the CI sets and enviroment variable to track the version that was built in the original step. This change check if we are on the CI, if we are we trust the version given by the previos machine, else we use the config one.
=> [Xharness] Fix path to mlaunch when using mlaunch from a .NET SDK pack on CI.

tests/common/Configuration.cs
Similar to PR https://github.com/xamarin/xamarin-macios/pull/18600 we need to use the same verison as the one found in the workload file in CI and not that one from the make.config.
=> [Tests] Use the correct nuget version on CI

dotnet/Makefile, dotnet/Workloads/SignVerifyIgnore.txt, tools/devops/automation/scripts/bash/build-nugets.sh, tools/devops/automation/templates/release/vs-insertion-prep.yml
The `MicroBuildCodesignVerify@3` task has been added to validate the
signing status of the MSI files required for VS insertions. This will
allow us to identify any potential signing issues earlier.
=> [ci] Run Codesign Verification after MSI creation

tests/introspection/ApiBaseTest.cs
The issue relies in the fact that this code path was not executed when using classic because in the classic version of the SDK we added the availavility attrs both in the property, the getters and the setters. With dotnet, we only add the attr in the property.
The code uses the GetProperty method which does not return internal/private properties which means that some of those properties are not correctly skipped when on dotnet. This was discovered while working on xcode 15.
=> [Introspection] Fix intro skip when the properties are internal.

src/UIKit/UIMenu.cs, src/frameworks.sources, src/uikit.cs
This API was missed because the old sim intro tests are not running and we missed it. This was found while working on xcode15. The tvOS attr is missing which defaults to the min version of tvOS when it should be 15.
Added a compat implementation so that the API remains.
=> [UIKit] Fix UIKit selector on TvOS

tools/common/Frameworks.cs
It seems that Apple will completely remove the NewsstandKit framework from iOS 17.
This poses a problem for existing apps that link with NewsstandKit: they will
crash at launch.
Solve this by always linking weakly with the NewsstandKit framework; this way
any apps that link with it will keep working if the framework ends up being
removed by Apple.
Fixes https://github.com/xamarin/xamarin-macios/issues/18606.
Fixes https://github.com/dotnet/maui/issues/16316.
=> [tools] Always link weakly with NewsstandKit. Fixes #18606.

src/UIKit/UIMenu.cs, tools/common/Frameworks.cs
Apple completely removed the NewsstandKit framework in Xode 15.
This effectively adds basic support for using Xcode 15 with .NET 7.
While this technically won't be a supported scenario, we have tests that
ensures .NET 7 apps can be built with .NET 8, and .NET 8 will ship with Xcode
15 support. This means that in order to make these tests work, we'll otherwise
have to have Xcode 14.3 installed both locally and on bots (in addition to
Xcode 15 of course), which is a rather big nightmare.
It's much easier to must try to make Xcode 15 work with .NET 7.
=> [tools] Don't link with NewsstandKit if we're using Xcode 15+.

tools/common/Frameworks.cs
It seems that Apple will completely remove the NewsstandKit framework from iOS 17.
This poses a problem for existing apps that link with NewsstandKit: they will
crash at launch.
Solve this by always linking weakly with the NewsstandKit framework; this way
any apps that link with it will keep working if the framework ends up being
removed by Apple.
Fixes https://github.com/xamarin/xamarin-macios/issues/18606.
Fixes https://github.com/dotnet/maui/issues/16316.
Backport of #18621
=> [release/7.0.3xx] [tools] Always link weakly with NewsstandKit. Fixes #18606.

src/Foundation/NSObject2.cs, tools/dotnet-linker/AppBundleRewriter.cs, tools/dotnet-linker/CecilExtensions.cs, tools/dotnet-linker/Steps/ManagedRegistrarStep.cs
Closes #18357
This PR implements the idea described in the linked issue:
Whenever there's an NSObject constructor that we call from a registrar callback, we need to create
a separate constructor that will first set the `handle` and `flags` values of the NSObject before
calling the original constructor. Here's an example of the code we generate:
```csharp
// The original constructor:
public .ctor (T0 p0, T1 p1, ...) { /* ... */ }
// The generated constructor with pre-initialization: 
public .ctor (T0 p0, T1 p1, ..., IntPtr handle, IManagedRegistrar dummy) {
this.handle = (NativeHandle)handle;
this.flags = 2; // Flags.NativeRef == 2
this..ctor (p0, p1, ...);
}
```
- This code can't be expressed in C# and it can only be expressed directly in IL.
- The reason we need to do this is because the …
=> MSR: Generate additional constructors to reduce usage of reflection

tools/common/Frameworks.cs
It seems that Apple will completely remove the NewsstandKit framework from iOS 17.
This poses a problem for existing apps that link with NewsstandKit: they will
crash at launch.
Solve this by always linking weakly with the NewsstandKit framework; this way
any apps that link with it will keep working if the framework ends up being
removed by Apple.
Fixes https://github.com/xamarin/xamarin-macios/issues/18606.
Fixes https://github.com/dotnet/maui/issues/16316.
Backport of #18621
=> [xcode14.3] [tools] Always link weakly with NewsstandKit. Fixes #18606.

tools/common/Frameworks.cs
Apple completely removed the NewsstandKit framework in Xode 15.
This effectively adds basic support for using Xcode 15 with .NET 7.
While this technically won't be a supported scenario, we have tests that
ensures .NET 7 apps can be built with .NET 8, and .NET 8 will ship with Xcode
15 support. This means that in order to make these tests work, we'll otherwise
have to have Xcode 14.3 installed both locally and on bots (in addition to
Xcode 15 of course), which is a rather big nightmare.
It's much easier to must try to make Xcode 15 work with .NET 7.
Backport of #18626
=> [xcode14.3] [tools] Don't link with NewsstandKit if we're using Xcode 15+.

configure, src/UIKit/UIMenu.cs
I can never remember which one is the right one, so just make them both work.
=> [configure] Make 'macos' work like 'mac'.

builds/Makefile
We always need to have a local .NET, because our T4 scripts are executed using
.NET (which is needed even if we're not building anyhing for .NET).
=> [builds] Always download .NET.

tools/common/Frameworks.cs
Apple completely removed the NewsstandKit framework in Xode 15.
This effectively adds basic support for using Xcode 15 with .NET 7.
While this technically won't be a supported scenario, we have tests that
ensures .NET 7 apps can be built with .NET 8, and .NET 8 will ship with Xcode
15 support. This means that in order to make these tests work, we'll otherwise
have to have Xcode 14.3 installed both locally and on bots (in addition to
Xcode 15 of course), which is a rather big nightmare.
It's much easier to must try to make Xcode 15 work with .NET 7.
Backport of #18626
=> [release/7.0.3xx] [tools] Don't link with NewsstandKit if we're using Xcode 15+.

src/AppKit/Compat.cs, src/Foundation/NSArray.cs, src/Foundation/NSDictionary.cs, src/Foundation/NSMutableDictionary.cs, src/Foundation/NSObject2.cs, src/Foundation/NSUrlProtocol.cs, src/bgen/Generator.cs, tests/generator/BGenTests.cs, tests/generator/ghissue18645.cs, tests/mmp-regression/link-frameworks-1/LinkFrameworks1.cs
The way the generator names private fields for selectors results on not compilable code when there are two selectoors A and B such that selector B == AHandle.
That is, if selector A is "user", selector B will be "userHandle". This happens because Handle is quite a common postfix in security when working with user accounts (userHandler and others) and we need to ensure that the Handle postfix added by the generator is unique.
As stated in the bug we could try to fix this by keeping track of the variables in the context in wich the generator is creating code. The problem with such approach is that it will make very hard to predict the name of the fields making the manual code harder to write. The PR contains examples of such manual code.
To fix the situation we have moved from using Handle …
=> [Generator] Ensure that selectors fields do not have overlapping names. Fixes #18645

tools/devops/automation/build-pipeline.yml, tools/devops/automation/build-pull-request.yml, tools/devops/automation/scripts/bash/configure-build.sh, tools/devops/automation/templates/build/api-diff-build-and-detect.yml, tools/devops/automation/templates/build/api-diff-stage.yml, tools/devops/automation/templates/build/build-mac-tests-stage.yml, tools/devops/automation/templates/build/build-mac-tests.yml, tools/devops/automation/templates/build/build-pkgs.yml, tools/devops/automation/templates/build/build-stage.yml, tools/devops/automation/templates/build/build.yml, tools/devops/automation/templates/common/configure.yml, tools/devops/automation/templates/mac/stage.yml, tools/devops/automation/templates/main-stage.yml, tools/devops/automation/templates/release/vs-insertion-prep.yml, tools/devops/automation/templates/sign-and-notarized/funnel.yml, tools/devops/automation/templates/sign-and-notarized/prepare-pkg-stage.yml, tools/devops/automation/templates/sign-and-notarized/upload-azure.yml, tools/devops/automation/templates/tests/stage.yml
It's rather rare now that we need to disable .NET from the CI, so just remove the option. It can still be disabled directly in the code when needed.
Also this fixes an issue where we'd build with .NET enabled even if disabled in the code, because we'd always pass --enable-dotnet to configure.
=> [devops] Remove option to disable .NET from CI.

builds/Makefile
We always need to have a local .NET, because our T4 scripts are executed using
.NET (which is needed even if we're not building anyhing for .NET).
=> [xcode14.3] [builds] Always download .NET.

tests/common/Configuration.cs, tests/xharness/Harness.cs
Additionally parse files in reverse order, because any variables at the end
should take precedence (when parsing config files the first time variable is
found is the one we use).
=> [tests] Parse configure.inc for build settings as well.

tests/common/BinLog.cs
Our test projects may be using an earlier version of .NET (in particular
Touch.Unit and MonoTouch.Dialog often are), so ignore any warnings about
out-of-support workloads.
Fixes test failures like:
Xamarin.Tests.BundleStructureTest.Build(MacCatalyst,"maccatalyst-x64;maccatalyst-arm64",All,"Debug"): Warnings
Expected is <System.Collections.Generic.List`1[System.String]> with 22 elements, actual is <System.String[28]>
Values differ at index [22]
Extra: < "The workload 'maccatalyst' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/maui-support-policy for more information about the support policy.", "The workload 'maccatalyst' is out of support and will not receive security updates in the future. Please refer to …
=> [tests] Filter out any warnings about out-of-support workloads.

tools/devops/automation/scripts/bash/configure-platforms.sh
This fixes an issue where we'd try to sign the legacy Xamarin packages even if
the legacy build was disabled.
=> [devops] Fix setting the INCLUDE_LEGACY* variables when legacy isn't enabled.

dotnet/targets/Xamarin.Shared.Sdk.targets, tests/dotnet/UnitTests/ProjectTest.cs, tests/introspection/ApiPInvokeTest.cs, tools/linker/MonoTouch.Tuner/ListExportedSymbols.cs
It's possible to create a provisioning profile for Mac Catalyst that doesn't
allow dylibs in the app. It seems a significant number of people run into this
problem when publishing their apps, so avoid it by linking Mono and Xamarin
statically by default instead.
The downside is that build time might increase a little bit.
An upside however is that the app size might decrese somewhat.
Fixes https://github.com/xamarin/xamarin-macios/issues/14686.
=> [dotnet] Link Mono and Xamarin statically in Mac Catalyst by default. Fixes #14686.

tests/common/BinLog.cs
Our test projects may be using an earlier version of .NET (in particular
Touch.Unit and MonoTouch.Dialog often are), so ignore any warnings about
out-of-support workloads.
Fixes test failures like:
Xamarin.Tests.BundleStructureTest.Build(MacCatalyst,"maccatalyst-x64;maccatalyst-arm64",All,"Debug"): Warnings
Expected is <System.Collections.Generic.List`1[System.String]> with 22 elements, actual is <System.String[28]>
Values differ at index [22]
Extra: < "The workload 'maccatalyst' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/maui-support-policy for more information about the support policy.", "The workload 'maccatalyst' is out of support and will not receive security updates in the future. Please refer to …
=> [release/7.0.3xx] [tests] Filter out any warnings about out-of-support workloads.

tools/common/Rewriter.cs, tools/dotnet-linker/dotnet-linker.csproj
This also fixes a compiler warnings:
> tools/common/Rewriter.cs(333,25): warning CS8604: Possible null reference argument for parameter 'path1' in 'string Path.Combine(string path1, string path2)'.
And make nullability warnings in dotnet-linker show up as errors to prevent
future introduction of nullability warnings.
=> [tools] Remove some dead code in the class redirector rewriter.

src/spritekit.cs
Breaking change
Modified methods:
public SKAction FollowPath (CoreGraphics.CGPath path, bool offset, bool ~orient~ orientToPath, double sec)
public SKAction FollowPath (CoreGraphics.CGPath path, bool offset, bool ~orient~ orientToPath, System.Runtime.InteropServices.NFloat speed)
=> [SpriteKit] Fix breaking change in SKAction.FollowPath.

tests/common/DotNet.cs, tools/nnyeah/tests/nnyeah-tests.csproj
Improve assertion when a .NET test fails executing 'dotnet' by including more
information (any errors in particular) in the assert message.
=> [tests] Improve assertion when a .NET test fails executing 'dotnet'.

tests/monotouch-test/ObjCRuntime/BlocksTest.cs
We use the AOT compiler on ARM64 on Mac Catalyst, so these tests have to be excluded on Mac Catalyst.
=> [monotouch-test] Fix BlocksTest to work on maccatalyst-arm64.

tools/common/StaticRegistrar.cs, tools/dotnet-linker/AppBundleRewriter.cs, tools/dotnet-linker/Steps/ManagedRegistrarStep.cs
We can determine the exact constructor to call when creating INativeObject instances
in the generated code, so do exactly that. This avoids a lot of slow reflection,
and also makes the constructor call visible for any linkers.
=> [registrar] Call INativeObject ctors directly in the managed static registrar.

dotnet/targets/Xamarin.Shared.Sdk.targets, msbuild/Xamarin.MacDev.Tasks/Tasks/LinkNativeCodeTaskBase.cs, tools/common/Application.cs, tools/common/CompilerFlags.cs, tools/common/Driver.cs, tools/mmp/aot.cs, tools/mmp/driver.cs
* Only ask for the classic linker if we're using Xcode 15+.
* Implement a way out of the enforcing the classic linker.
=> [net8.0-xcode15] [tools] Improve enforcement of the classic linker.

dotnet/targets/Xamarin.Shared.Sdk.props
The .mobile.props file is a file created and written by the mobile VS extension to store property values that needs to be read early enough in the build chain, as in design time builds, and that can't be set by CPS because of a limitation in the project system. See more information here: https://github.com/xamarin/XamarinVS/pull/13606
Initially it was named .user.env file and then was renamed in another PR as part of a feedback from the project system team. See more information here: https://github.com/xamarin/XamarinVS/pull/13628
Because this file was saved in the intermediate output path, it was meant to be imported automatically by MSBuild, however we recently detected that this was not happening reliably. Because of this, some things like C# Hot Reload for iOS stopped working because …
=> [remote] Explicitly import .mobile.props file

tools/dotnet-linker/Steps/ManagedRegistrarStep.cs
This is a bit non-obvious, but we later use the presence of such a stored list
to determine if we need to generate the __Registrar__ type in the assembly.
The problem is that we need to generate the __Registrar__ type even if no
trampolines were created, because we use it for numerous other purposes as
well (type lookup for instance).
Fixes https://github.com/xamarin/xamarin-macios/issues/18570.
=> [tools] Store list of trampolines even if it's empty. Fixes #18570.

tools/common/StaticRegistrar.cs
* Remove unusued code.
* Rename method to make it follow the common TryGet... pattern.
=> [tools] Minor code clean up in dotnet-linker.

tools/devops/automation/templates/tests/run-tests.yml
This seems to happen fairly often:
+ xcrun simctl diagnose -b -X --output=/Users/builder/azdo/_work/1/s/diagnostic-sim-output/output
Error creating archive at '/Users/builder/azdo/_work/1/s/diagnostic-sim-output/output.tar.gz'. Files are still in /Users/builder/azdo/_work/1/s/diagnostic-sim-output/output
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=17):
Unable to write or file already exists
File exists
The output directory is empty (created in the line before), so I have no idea what's going on.
An archive with the diagnostic info still seems to be created though, so just
ignore any failures from 'simctl diagnose' instead of bubbling them up to
Azure DevOps. This makes our test runs not show up with warnings.
=> [devops] 'simctl diagnose' tend to return an error code, so make sure it doesn't bubble up to the CI.

tests/common/Configuration.cs, tests/xharness/Harness.cs, tests/xharness/IHarness.cs, tests/xharness/Targets/Target.cs
Setting test configuration variables using the environment is useful when
running tests on a Windows machine (easier than having to deal with make).
Also refactor the code a bit to not use constants, and more consistent naming.
=> [tests/xharness] Add support for setting test configuration using environment variables.

src/build/generator-frameworks.g.cs, src/generate-frameworks.csharp
This makes it easier to run some tests on Windows, because the tests reference
this file and by having it checked in it doesn't need to be generated (which
we currently do using make, which isn't trivial on Windows).
Also adjust the generated output slightly to make it easier on the eyes.
=> [src] Add generated file listing frameworks to git to simplify build on Windows.

dotnet/targets/Xamarin.Shared.Sdk.props, dotnet/targets/Xamarin.Shared.Sdk.targets, tests/dotnet/UnitTests/ProjectTest.cs
The gist is:
- If you enable `<PublishAot>true</PublishAot>` then the NativeAOT build targets get included.
- Unless `NativeCompilationDuringPublish` is disabled, the NativeAOT targets are chained through `BeforeTargets` attribute to some publish targets (computing the resolved publish paths). Xamarin runs those publish targets even for non-publish builds, so it brings the whole ILC compilation along. That's undesirable.
- The `RunILLink` property is set unconditionally by the NativeAOT build integration. If we don't fix it then ILLink never runs, and neither do all the custom steps to generate registrars and `main()`.
Update: Apparently, we still need to fix runtime pack resolution for iOS-like platforms with `PublishAotUsingRuntimePack=true`.
=> Fix non-NativeAOT builds with PublishAot=true in the project file

dotnet/targets/Xamarin.Shared.Sdk.targets
* Don't strip resource assemblies, there's no code in them to strip anyways.
* Use the relative path inside the app bundle when computing the intermediate
location for stripped assemblies, so that if we were to find two identically
named assemblies in different directories, they're handled correctly (by
putting them in different intermediate locations, instead of overwriting
eachother).
Fixes https://github.com/xamarin/xamarin-macios/issues/17262.
=> [dotnet] Fix assembly stripping of resource assemblies. Fixes #17262.

dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets, dotnet/targets/Xamarin.Shared.Sdk.props, dotnet/targets/Xamarin.Shared.Sdk.targets
This PR enables trim warnings with NativeAOT by default.
In our current ILLink+ILC setup, we first need to suppress the warnings for ILLink, after which we need to enable them for ILC. 
For this reason, setting up `SuppressTrimAnalysisWarnings` properly needs to happen very early as it will get overwritten by https://github.com/dotnet/runtime/blob/45acd380b37c9ee883070a70a2ef2cb7eca77683/src/tools/illink/src/ILLink.Tasks/build/Microsoft.NET.ILLink.targets#L54-L59 
Verified with building an iOS application that the trim warnings are displayed only during ILC trimming (after `Generating native code` message below):
```                 
../dotnet publish -c Release -r ios-arm64 -bl /p:PublishAot=true /p:PublishAotUsingRuntimePack=true
MSBuild version 17.7.0+5785ed5c2 for .NET
Determining …
```
=> NativeAOT: Do not suppress trim warnings by default with NativeAOT

tests/common/Tool.cs, tests/dotnet/UnitTests/ProjectTest.cs, tests/generator/BGenTests.cs, tests/generator/BGenTool.cs, tools/devops/automation/scripts/VSTS.Tests.ps1, tools/devops/automation/scripts/VSTS.psm1, tools/devops/automation/scripts/bash/configure-platforms.sh, tools/devops/automation/scripts/run-generator-tests-on-windows.ps1, tools/devops/automation/templates/windows/build.yml
We'll soon change the generator to execute locally on Windows, even for remote builds. As a stepping stone towards that goal, this PR adds the generator tests to the list of tests we run on Windows.
=> Run the generator tests on Windows.

dotnet/targets/Xamarin.Shared.Sdk.targets, tools/dotnet-linker/AppBundleRewriter.cs, tools/dotnet-linker/ApplyPreserveAttributeBase.cs, tools/dotnet-linker/CecilExtensions.cs, tools/dotnet-linker/DocumentionComments.cs, tools/dotnet-linker/Steps/ManagedRegistrarStep.cs, tools/linker/ApplyPreserveAttribute.cs, tools/mtouch/Errors.designer.cs, tools/mtouch/Errors.resx
Add partial support for the `[Preserve]` attribute for NativeAOT. This is done by injecting an equivalent `[DynamicDependency]` attribute. The partial support comes from the fact that there's no way to map a conditional preserve attribute (`[Preserve (Conditional = true)]`) to a `[DynamicDependency]` attribute, so we report a warning instead.
For non-conditional `[Preserve]` attributes, we'll now add a `[DynamicDependency]` attribute to the assembly's module constructor for the type/member in question, effectively rooting it.
This makes it possible to fully link all our test suites when NativeAOT (otherwise NativeAOT would just link out all the tests, leaving the test suites empty - and unfortunately green, so this was a rather accidental discovery).
=> [NativeAOT] Add support for [Preserve] attributes

tests/common/DotNet.cs, tests/dotnet/UnitTests/PackTest.cs
* A property set on the command line is set for all projects that are built,
including projects referenced by the main project.
* If the main project references more than one project, those referenced
projects may be built in parallel.
* This means multiple projects might have the same IntermediateOutputPath if
set on the command line, and thus accessing files in the directory
simultaneously, which is a bad idea.
Fix this by manually disabling build parallelism in tests that set
IntermediateOutputPath.
Fixes https://github.com/xamarin/maccore/issues/2567.
=> [tests] Disable build parallelism when setting IntermediateOutputPath as a property for the build.

dotnet/targets/Xamarin.Shared.Sdk.targets
This PR unifies the way `ObjCRuntime` features are passed to trimming tools by using `RuntimeHostConfigurationOption`.
---
Fixes: https://github.com/xamarin/xamarin-macios/issues/18483
=> Use RuntimeHostConfigurationOption for ObjCRuntime features

Make.config, eng/Version.Details.xml, eng/Versions.props
Changes: https://github.com/dotnet/runtime/compare/e897946596...034d27f4a9
Because the .NET SDK has switched over to internal code flow, we have to subscribe to runtime directly
xamarin-android also did this: https://github.com/xamarin/xamarin-android/pull/8284
=> [release/8.0.1xx-rc1] Bump dotnet/runtime manually.

src/AudioUnit/AudioComponent.cs, src/Foundation/DictionaryContainer.cs, src/Foundation/NSConnection.cs, src/bgen/Generator.cs
Ref #18779
- We can get rid of Activator.CreateInstance in `DictionaryContainer.GetStrongDictionary<T>` by passing a factory method
- For the cases where we need to use Activator.CreateInstance we need to add `[DynamicallyAccessedMembers(...)]` to the type parameter
=> Avoid using Activator.CreateInstance

tools/common/StaticRegistrar.cs, tools/mtouch/Errors.designer.cs, tools/mtouch/Errors.resx
Apple completely removed the NewsstandKit framework and the
PKDisbursementAuthorizationController[Delegate] types in Xode 15, so let's not
generate any corresponding code in the static registrar.
This effectively adds basic support for using Xcode 15 with .NET 7 (take 2).
Backport of #18812.
=> [release/7.0.3xx] [registrar] Skip registering types removed in Xcode 15.

msbuild/Xamarin.MacDev.Tasks/Tasks/AOTCompileTaskBase.cs
This might fix #17825, but even if it doesn't, it's a good thing to do to not
overload machines.
Ref: https://github.com/xamarin/xamarin-macios/issues/17825
=> [msbuild] Limit the number of concurrent AOT compilers to the number of processors.

tools/common/StaticRegistrar.cs, tools/mtouch/Errors.designer.cs, tools/mtouch/Errors.resx
Apple completely removed the NewsstandKit framework and the
PKDisbursementAuthorizationController[Delegate] types in Xode 15, so let's not
generate any corresponding code in the static registrar.
This effectively adds basic support for using Xcode 15 with .NET 7 (take 2).
=> [registrar] Skip registering types removed in Xcode 15.

msbuild/Xamarin.MacDev.Tasks/Tasks/AOTCompileTaskBase.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/14904.
=> [msbuild] Pass MONO_PATH using --path instead of an environment variable. Fixes #14904.

tools/common/StaticRegistrar.cs, tools/mtouch/Errors.designer.cs, tools/mtouch/Errors.resx
Apple completely removed the NewsstandKit framework and the
PKDisbursementAuthorizationController[Delegate] types in Xode 15, so let's not
generate any corresponding code in the static registrar.
This effectively adds basic support for using Xcode 15 with .NET 7 (take 2).
=> [xcode14.3] [registrar] Skip registering types removed in Xcode 15.

tools/common/StaticRegistrar.cs, tools/mtouch/Errors.designer.cs, tools/mtouch/Errors.resx
Apple completely removed the NewsstandKit framework and the
PKDisbursementAuthorizationController[Delegate] types in Xode 15, so let's not
generate any corresponding code in the static registrar.
This effectively adds basic support for using Xcode 15 with .NET 7 (take 2).
Backport of #18812
=> [release/8.0.1xx-rc1] [registrar] Skip registering types removed in Xcode 15.

dotnet/targets/Xamarin.Shared.Sdk.targets
=> Improve consumption of NativeAOT linker flags

tests/common/DotNet.cs, tests/common/shared-dotnet.csproj, tests/dotnet/UnitTests/ProjectTest.cs
Some time ago we added a workaround for an msbuild bug that has since been fixed (since the initial .NET 7 release). This workaround involved writing build properties to a file instead of passing them on the command line.
We no longer need the workaround, but it turnes out we still need to be able to pass build properties in a file (because we have a test that needs this behavior). We'll also soon run into a scenario where we need to be able to specify a build property on the command line (`TargetFrameworks`) - the build won't work if specified in a file.
So add support for both, and make the test that needs to specify the build property on the command line say so explicitly.
=> [tests] Add support for specifying whether build properties should be specified on the command line or in a file.

dotnet/targets/Xamarin.Shared.Sdk.targets
In some cases ld will crash otherwise:
0  0x102a1871c  __assert_rtn + 140
1  0x102a21688  ld::tool::SymbolTableAtom<arm64>::classicOrdinalForProxy(ld::Atom const*) (.cold.3) + 0
2  0x10291daf8  ld::tool::SymbolTableAtom<arm64>::classicOrdinalForProxy(ld::Atom const*) + 248
3  0x10291d15c  ld::tool::SymbolTableAtom<arm64>::addImport(ld::Atom const*, ld::tool::StringPoolAtom*) + 204
4  0x10291c824  ld::tool::SymbolTableAtom<arm64>::encode() + 416
5  0x102907b6c  ___ZN2ld4tool10OutputFile20buildLINKEDITContentERNS_8InternalE_block_invoke.387 + 36
6  0x185df2874  _dispatch_call_block_and_release + 32
7  0x185df4400  _dispatch_client_callout + 20
8  0x185e060c8  _dispatch_root_queue_drain + 956
9  0x185e066c0  _dispatch_worker_thread2 + 164
10  0x185fa0038  _pthread_wqthread + 228
A linker …
=> [dotnet] Always pass -lobjc to the native linker.

tools/dotnet-linker/AppBundleRewriter.cs, tools/dotnet-linker/DocumentionComments.cs
I noticed that we're generating invalid DynamicDependency attributes for generic types and methods. For example for the `void Activated(T sender)` method of `UIKit.UIGestureRecognizer.Callback<T>`:
```c#
// before:
[DynamicDependency("Activated(T)", typeof(UIKit.UIGestureRecognizer.Callback<>))]
// after:
[DynamicDependency("Activated(`0)", "UIKit.UIGestureRecognizer.Callback`1", "Microsoft.MacCatalyst")]
```
=> [NativeAOT] Fix transforming [Preserve] into [DynamicDependency] for generic types and generic methods

tests/monotouch-test/SpriteKit/SKTransformNodeTest.cs
Fixes https://github.com/xamarin/maccore/issues/2701.
=> [xcode14.3] [tests] Allow a little bit of leeway when testing floating point numbers in SKTransformNodeTest.

Make.config, builds/Makefile, dotnet/Makefile, msbuild/Makefile, msbuild/Xamarin.HotRestart.PreBuilt/Makefile, runtime/Makefile, src/Makefile, src/Makefile.generator, tests/Makefile, tests/common/Configuration.cs, tests/xharness/Harness.cs, tests/xtro-sharpie/Makefile, tools/apidiff/Makefile, tools/devops/automation/scripts/VSTS.Tests.ps1, tools/devops/automation/scripts/VSTS.psm1, tools/devops/automation/scripts/bash/configure-platforms.sh, tools/devops/automation/scripts/run-generator-tests-on-windows.ps1, tools/dotnet-linker/Makefile, tools/mlaunch/Makefile, tools/mmp/Makefile, tools/mtouch/Makefile
We're going to change the pack names to support multi-targeting, so ahead
of the pack name change I'm changing the existing logic to use a variable
for the pack name in most places (this will make the rename much easier and
simpler).
These changes should have no effect by themselves.
=> [dotnet] Parameterize the pack names.

tools/devops/automation/templates/main-stage.yml
This makes it easier to test release logic using temporary branches.
=> [release/7.0.1xx-xcode14] [devops] Add 'release-test/*' as a release branch.

docs/multi-target-framework.md
Document the plan to:
* Compile against an earlier version of our bindings.
* https://github.com/dotnet/sdk/issues/30103
* Consume preview packages for a preview version of Xcode.
* https://github.com/xamarin/xamarin-macios/issues/18343
=> [docs] Document how we plan to do multi targeting.

Localize/loc/cs/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/de/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/es/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/fr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/it/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/ja/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/ko/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/pl/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/pt-BR/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/ru/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/tr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/zh-Hans/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/zh-Hant/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
These are lcl files (first part out of two of the localization process) that contain the not-yet-usable translations. Bringing these manually since there is an error in the pipeline that should be bringing these over.
=> [Localization] Manually bring over lcl files

tools/devops/automation/build-lego.yml
In my Localization inspection, I wanted to figure out why the automated PRs I was creating in Pipelines were auto-closing themselves a few hours after creating them - [example](https://github.com/xamarin/xamarin-macios/pull/18713).
There are a few different steps in the localization process and long story short is that I am creating these PRs from the Localization branch. Each commit into main runs a tool that alerts the Loc team and it syncs up our Localization branch to our main branch which temporarily deletes our Localization branch thus closing the automated PR!
This PR creates a new unique branch for each Localization PR so that we can keep updating the Loc team, but also make sure syncing the Localization branch will not delete this PR.
Testing this created this PR below: …
=> [Localization] Create a new branch for the automated PRs

dotnet/targets/Xamarin.Shared.Sdk.targets
Fixes this linker failure when compiling monotouch-test:
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Errors
xamarin-macios/builds/downloads/dotnet-sdk-8.0.100-rc.2.23428.11/packs/Microsoft.macOS.Sdk/13.3.8852-net8-rc2/targets/Xamarin.Shared.Sdk.targets(1527,3): clang++ exited with code 1:
ld: library not found for -lswiftCore
clang: error: linker command failed with exit code 1 (use -v to see invocation) [/Users/rolf/work/maccore/net8.0/xamarin-macios/tests/dotnet/MySimpleApp/macOS/MySimpleApp.csproj]
=> [dotnet] Pass path to native swift libraries when linking NativeAOT apps for macOS.

msbuild/ILMerge.targets
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1877179/.
Backport of #18892
=> [msbuild] Bundle System.Collections.Immutable.dll and System.Reflection.Metadata.dll in Xamarin.iOS.Tasks.dll.

tools/dotnet-linker/ApplyPreserveAttributeBase.cs
`None` seems to be equivalent to not having the attribute at all. The type will be stripped by ILLink and ILC. The `PublicConstructors | NonPublicConstructors` seems to be a better option to keep the type while making it possible to trim as much of its members as possible.
This change resolves two warnings:
```
ILLink : warning IL2037: <Module>..cctor(): No members were resolved for 'None' on type 'Microsoft.Maui.Controls.Handlers.Compatibility.FrameRenderer.FrameView'.
ILC : warning IL2037: <Module>..cctor(): No members were resolved for '0' on type 'Microsoft.Maui.Controls.Handlers.Compatibility.FrameRenderer.FrameView'. 
```
(Note: these warnings will still be present for _static_ classes which don't have a static constructor)
@rolfbjarne I believe we don't need …
=> [NativeAOT] Preserve all constructors instead of no members

tools/devops/automation/scripts/bash/configure-platforms.sh, tools/devops/automation/scripts/run-generator-tests-on-windows.ps1, tools/devops/automation/templates/build/api-diff-stage.yml, tools/devops/automation/templates/build/build-mac-tests-stage.yml, tools/devops/automation/templates/build/build-stage.yml, tools/devops/automation/templates/common/configure.yml, tools/devops/automation/templates/mac/stage.yml, tools/devops/automation/templates/release/vs-insertion-prep.yml, tools/devops/automation/templates/sign-and-notarized/funnel.yml, tools/devops/automation/templates/sign-and-notarized/prepare-pkg-stage.yml, tools/devops/automation/templates/tests/stage.yml, tools/devops/automation/templates/windows/stage.yml
This way we compute the correct version numbers in configure-platforms.sh.
Also tell the configure job that we're a PR, so that we undo the merge and don't use the wrong hash for the version calculations.
=> [devops] Set the BRANCH_NAME variable before configuring the build.

src/ObjCRuntime/Runtime.CoreCLR.cs
Use unsafe code to copy a struct instead of reflection, this is faster, and
also fully AOT-compatible.
Contributes towards https://github.com/xamarin/xamarin-macios/issues/18629.
=> [ObjCRuntime] Use unsafe code to copy a struct instead of reflection.

dotnet/targets/Xamarin.Shared.Sdk.targets
If anything we're supposed to link with *.o files, not publish them, but since
we're currently not handling any *.o files, just explicitly remove them from
the build. This avoids a warning where ComputeBundleLocation would issue a
warning about not knowing what to do with them.
Contributes towards https://github.com/xamarin/xamarin-macios/issues/18629.
=> [NativeAOT] Don't publish any *.o files that comes from NativeAOT.

msbuild/ILMerge.targets, tests/msbuild/Xamarin.MacDev.Tasks.Tests/Xamarin.MacDev.Tasks.Tests.csproj, tests/xharness/Jenkins/NUnitTestTasksEnumerable.cs
This is one more step towards dropping Mono, and also solves a random network
failure when doing 'nuget restore' with Mono (due to a bug in Mono).
=> [xharness] Use .NET to build the MSBuild test projects.

tests/cecil-tests/ApiTest.cs, tests/cecil-tests/Helper.cs, tests/monotouch-test/ARKit/ARConfigurationTest.cs
This test uses reflection to figure out if there are any ARConfiguration
subclasses that don't implement a particular method. The reflection usage is
problematic when trimming apps, and this is really what the Cecil tests are
for, so just re-implement the entire tests as a Cecil test.
=> [tests] Move the ARConfigurationTest.Subclasses test from monotouch-test to cecil-test.

src/ObjCRuntime/Blocks.cs, src/ObjCRuntime/Runtime.cs
This makes it possible to call the generic
Marshal.GetDelegateForFunctionPointer<T> method instead of the non-generic
Marshal.GetDelegateForFunctionPointer method, which is easier for AOT
compilers to handle (no reflection for
Marshal.GetDelegateForFunctionPointer<T>).
Contributes towards https://github.com/xamarin/xamarin-macios/issues/18629.
=> [src] Make Runtime.GetDelegateForBlock a generic method to pass the delegate type.

builds/Mono.framework-Info.plist, builds/Mono.framework-tvos.Info.plist, builds/Mono.framework-watchos.Info.plist, runtime/Xamarin.framework-iphoneos.Info.plist, runtime/Xamarin.framework-iphonesimulator.Info.plist, runtime/Xamarin.framework-tvos.Info.plist, runtime/Xamarin.framework-tvsimulator.Info.plist, runtime/Xamarin.framework-watchos.Info.plist, runtime/Xamarin.framework-watchsimulator.Info.plist
Bump the min OS version to match our actual min OS version.
=> [net8.0-xcode15] [runtime] Bump the min OS version in the Info.plist in Xamarin.framework.

tools/dotnet-linker/AppBundleRewriter.cs, tools/dotnet-linker/Steps/ManagedRegistrarStep.cs
This PR implements a workaround for the following build warning:
```
ILC: Method '[Microsoft.iOS]Foundation.NSObject.RegisterToggleRef(NSObject,native int,bool)' will always throw because:
Invalid IL or CLR metadata in 'Void Foundation.NSObject.RegisterToggleRef(Foundation.NSObject, IntPtr, Boolean)'
```
Ref #18524
=> [NativeAOT] Fix ILC warning for NSObject.RegisterToggleRef

src/appkit.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/18916.
=> [AppKit] Add missing NSView.ClipsToBounds. Fixes #18916.

tools/common/Frameworks.cs, tools/common/StaticRegistrar.cs, tools/common/Target.cs
Makes the iTravel submission test compile successfully.
=> [xcode14.3] [tools] Skip more types and namespaces when using Xcode 15.

tools/devops/automation/templates/release/vs-insertion-prep.yml
Correctly match Microsoft.iOS.Windows.Sdk.*.nupkg when selecting nupkgs to publish.
=> [release/7.0.1xx-xcode13.3-multi-targeting] Fix nupkg pattern matching.

tools/devops/automation/templates/release/vs-insertion-prep.yml
Correctly match Microsoft.iOS.Windows.Sdk.*.nupkg when selecting nupkgs to publish.
=> [release/7.0.1xx-xcode14-multi-targeting] Fix nupkg pattern matching.

tools/devops/automation/templates/main-stage.yml
We don't have any tests on Windows in this branch anyways, so it's just
useless consumption of bots (and the code fails too, making builds red).
=> [release/7.0.1xx-xcode14] Turn off tests on Windows.

tools/devops/automation/templates/main-stage.yml
We don't have any tests on Windows in this branch anyways, so it's just
useless consumption of bots (and the code fails too, making builds red).
=> [release/7.0.1xx-xcode13.3] Turn off tests on Windows.

dotnet/targets/Xamarin.Shared.Sdk.targets, tests/dotnet/UnitTests/BundleStructureTest.cs, tests/dotnet/UnitTests/ProjectTest.cs
Make bundling the 'createdump' utility opt-in by setting BundleCreateDump=true.
Fixes: https://github.com/xamarin/xamarin-macios/issues/16189
=> [dotnet] Make bundling the 'createdump' utility opt-in. Fixes #16189.

src/ObjCRuntime/Runtime.cs, src/ObjCRuntime/Runtime.mac.cs
In Xamarin.Mac we have some code to support unusual ways of creating app
bundles while including Xamarin.Mac, and also dynamic loading of the Mono
runtime.
In .NET, we don't support these unusual app bundle creating logic for any
platform, and the Mono runtime isn't even an option for macOS, so exclude some
of the corresponding code from .NET.
This fixes a few warnings in NativeAOT about this code not being trimmer-safe.
=> [ObjCRuntime] Remove unnecessary macOS code from .NET.

src/bgen/AttributeManager.cs, tests/bgen/Makefile, tests/common/Configuration.cs, tests/generator/BGenTests.cs, tests/generator/tests/obsoletedosplatform.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/18966.
=> [bgen] Add support for converting ObsoletedOSPlatform attributes. Fixes #18966.

dotnet/targets/Xamarin.Shared.Sdk.targets, tests/dotnet/UnitTests/BundleStructureTest.cs
Copy the pdb for our platform assembly to the app bundle if we're in Debug
mode.
Fixes https://github.com/xamarin/xamarin-macios/issues/11879.
=> [dotnet] Copy the pdb for our platform assemblies to the app bundle. Fixes #11879.

mk/xamarin.mk
* xamarin/maccore@ce1fd64f90 [xcode14] Update provisionator bootstrap
* xamarin/maccore@75a03ccbfc [xcode14] Merge main into xcode14
Diff: https://github.com/xamarin/maccore/compare/0837e7caffb2e42efcd183cb1d71998fb6022e2c..ce1fd64f905cc6d96ddeed0eb2a77fb0d8715ac2
=> [release/7.0.1xx-xcode14] Bump maccore to get fix for updating the provisionator.

mk/xamarin.mk
* xamarin/maccore@f474dd1a7e Update provisionator bootstrap
Diff: https://github.com/xamarin/maccore/compare/9a347bd708eb0ef975cf52cefdb23cb3a83d2690..f474dd1a7ebad9fb083a322fde61117d68680f7b
=> [release/7.0.1xx-xcode13.3] Bump maccore to get fix for updating the provisionator.

tests/dotnet/UnitTests/PostBuildTest.cs
This reverts commit 7691231a86104f711cfa7077fd1fb6fab479d069.
Fixes https://github.com/xamarin/xamarin-macios/issues/18733.
=> [net8.0] Revert "[tests] Ignore tests that publish universal apps."

tests/common/AppDelegate.cs
This reverts commit bc272a944601d469f3944f7cf70f538723881e69.
This workaround is no longer necessary.
Fixes https://github.com/xamarin/xamarin-macios/issues/18164.
=> [net8.0] Revert "[tests] Find a workaround for #xamarin/maccore@2668."

Make.config, runtime/Makefile, tests/mtouch/MTouch.cs, tests/mtouch/MTouchTool.cs, tests/test-libraries/Makefile, tools/common/Application.cs, tools/mtouch/Makefile
Only i386 is gone from watchOS 4.0, not armv7k.
Fixes https://github.com/xamarin/xamarin-macios/issues/18902.
=> [xcode15] Add back armv7k support for watchOS. Fixes #18902.

tests/linker/ios/link all/LinkAllTest.cs, tests/linker/mac/link all/LinkAllTest.cs
By moving the test from a macOS-specific location to a general location, it
becomes obvious that the test behaves the same on all platforms (which the
issue was about: it looked like we had different behavior on macOS vs the
other platforms, and the issue requested validation that this was correct - by
running the test on all platforms, with no platform-specific code, it
demonstrates that there's no macOS-specific behavior).
Fixes https://github.com/xamarin/xamarin-macios/issues/12468.
=> [tests] Move a calendar test from being macOS-specific to run on all platforms. Fixes #12468.

tests/dotnet/size-comparison/common.mk
Make it simpler to use a custom 'appcompare' tool (or just one built locally),
by supporting setting the APPCOMPARE variable to the appcompare command to
execute.
=> [tests] Make it simpler to use a custom 'appcompare' tool.

msbuild/Xamarin.MacDev.Tasks/Tasks/CodesignTaskBase.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/ComputeCodesignItemsTaskBase.cs, tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/ComputeCodesignItemsTaskTests.cs
When figuring out whether something needs to be (re)signed or not, we must
also take into account that the signing identity may have changed (for
instance a release build will often have a different signing identity than a
debug build).
Do this by storing the command line to sign for each item we need to sign in
the stamp file, and if the stored contents don't match the new command line
to sign, then we must resign the item.
This is rather obnoxious to write unit tests for (since we'd need to have two
different signing identities available on the bots), so I've only done local
testing.
Fixes https://github.com/xamarin/xamarin-macios/issues/16124.
Backport of #18750
=> [release/7.0.3xx] [msbuild] Store the command line to sign in the stamp file. Fixes #16124.

msbuild/Xamarin.MacDev.Tasks/Tasks/AOTCompileTaskBase.cs
This might fix #17825, but even if it doesn't, it's a good thing to do to not
overload machines.
Ref: https://github.com/xamarin/xamarin-macios/issues/17825
Backport of #18793.
=> [release/7.0.3xx] [msbuild] Limit the number of concurrent AOT compilers to the number of processors.

tools/devops/automation/scripts/bash/install-workloads.sh
Some of our tests (such as the MSBuild tests), are built with .NET, and thus
need some version of .NET installed to be buildable.
Note that in this case we don't need any workloads, so we still skip that part.
=> [devops] Skip installing workloads, not .NET itself, if .NET isn't enabled.

tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/DetectSdkLocationsTaskTests.cs
This fixes a few test failures when only macOS is the enabled platform.
=> [tests] Ignore a few tests that require iOS if iOS isn't available.

tests/xharness/Jenkins/NUnitTestTasksEnumerable.cs
This fixes an issue where we'd try to run the mtouch tests when only macOS is
the enabled platform.
=> [xharness] Ignore the mtouch tests if iOS isn't enabled.

dotnet/targets/Xamarin.Shared.Sdk.targets, msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx, msbuild/Xamarin.MacDev.Tasks/Tasks/AOTCompileTaskBase.cs, tests/dotnet/RebuildTestAppWithLibraryReference/AppDelegate.cs, tests/dotnet/RebuildTestAppWithLibraryReference/Library/Library.cs, tests/dotnet/RebuildTestAppWithLibraryReference/Library/MacCatalyst/Library.csproj, tests/dotnet/RebuildTestAppWithLibraryReference/Library/MacCatalyst/Makefile, tests/dotnet/RebuildTestAppWithLibraryReference/Library/Makefile, tests/dotnet/RebuildTestAppWithLibraryReference/Library/iOS/Library.csproj, tests/dotnet/RebuildTestAppWithLibraryReference/Library/iOS/Makefile, tests/dotnet/RebuildTestAppWithLibraryReference/Library/macOS/Library.csproj, tests/dotnet/RebuildTestAppWithLibraryReference/Library/macOS/Makefile, tests/dotnet/RebuildTestAppWithLibraryReference/Library/shared.csproj, tests/dotnet/RebuildTestAppWithLibraryReference/Library/shared.mk, tests/dotnet/RebuildTestAppWithLibraryReference/Library/tvOS/Library.csproj, tests/dotnet/RebuildTestAppWithLibraryReference/Library/tvOS/Makefile, tests/dotnet/RebuildTestAppWithLibraryReference/MacCatalyst/Makefile, tests/dotnet/RebuildTestAppWithLibraryReference/MacCatalyst/RebuildTestAppWithLibraryReference.csproj, tests/dotnet/RebuildTestAppWithLibraryReference/Makefile, tests/dotnet/RebuildTestAppWithLibraryReference/iOS/Makefile, tests/dotnet/RebuildTestAppWithLibraryReference/iOS/RebuildTestAppWithLibraryReference.csproj, tests/dotnet/RebuildTestAppWithLibraryReference/macOS/Makefile, tests/dotnet/RebuildTestAppWithLibraryReference/macOS/RebuildTestAppWithLibraryReference.csproj, tests/dotnet/RebuildTestAppWithLibraryReference/shared.csproj, tests/dotnet/RebuildTestAppWithLibraryReference/shared.mk, tests/dotnet/RebuildTestAppWithLibraryReference/tvOS/Makefile, tests/dotnet/RebuildTestAppWithLibraryReference/tvOS/RebuildTestAppWithLibraryReference.csproj, tests/dotnet/UnitTests/RebuildTest.cs, tests/dotnet/UnitTests/TestBaseClass.cs
If an assembly changes, then we must AOT compile that assembly again (which we already
did), in addition to any assembly that references the modified assembly (which we
didn't do).
So rework the AOTCompile target: remove the Inputs and Outputs (because the dependency
tracking is too complicated for MSBuild to resolve), and instead move the logic to
detect if an assembly must be AOT-compiled again into the AOTCompile task.
Note that this PR has a custom port to .NET 8: #18518.
Fixes https://github.com/xamarin/xamarin-macios/issues/17708.
Backport of #18509
=> [release/7.0.3xx] [msbuild] Re-aot referencing assemblies. Fixes #17708.

src/bgen/AttributeManager.cs, tests/bgen/Makefile, tests/common/Configuration.cs, tests/generator/BGenTests.cs, tests/generator/tests/obsoletedosplatform.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/18966.
Backport of #18972
=> [release/7.0.3xx] [bgen] Add support for converting ObsoletedOSPlatform attributes. Fixes #18966.

src/cloudkit.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/19013.
=> [CloudKit] Expose the CKQueryOperationMaximumResults field. Fixes #19013.

tests/common/Configuration.cs, tests/dotnet/UnitTests/PackTest.cs, tests/dotnet/UnitTests/ProjectTest.cs
With multi-targeting, we can end up supporting a newer target framework than
the current one (when including support for preview versions of Xcode), but we
can't build Mac Catalyst projects using these newer target frameworks, because
it would require using the corresponding Xcode version, which may not be
available (in particular on bots).
Fixes these test failures:
Xamarin.Tests.DotNetProjectTest.MultiTargetLibrary(MacCatalyst): 'dotnet build' failed with exit code 1
Full command: /Users/builder/azdo/_work/2/s/xamarin-macios/builds/downloads/dotnet-sdk-8.0.100-rc.1.23422.1/dotnet build /Users/builder/azdo/_work/2/s/xamarin-macios/tests/dotnet/MultiTargetingLibrary/MacCatalyst/MultiTargetingLibrary.csproj /p:_BundlerVerbosity=1 "/p:AllTheTargetFrameworks=\"net8.0-maccatalyst16.4;net7.0-ma …
=> [tests] Don't build Mac Catalyst projects using a target framework later than the current one.

dotnet/Makefile, dotnet/generate-workloadmanifest-targets.csharp
We might actually support a newer OS version than the one we're building for,
if we're supporting a preview version in a stable release. In this case, we
need to make sure to load the correct sdk when we run into errors, so that we
show the correct error messages.
Xamarin.Tests.DotNetProjectTest.InvalidTargetPlatformVersion(MacCatalyst): Error message
Expected string length 92 but was 87. Strings differ at index 84.
Expected: "...ormVersion for MacCatalyst. Valid versions include:\n16.4\n17.0"
But was: "...ormVersion for MacCatalyst. Valid versions include:\n17.0"
=> [dotnet] Load the current, not latest, sdk for the error logic in WorkloadManifest.targets.

tools/dotnet-linker/Steps/ManagedRegistrarLookupTablesStep.cs
Protocol wrapper types may be nested types, so make sure to look in nested
types when looking for protocol wrapper types.
Fixes https://github.com/xamarin/xamarin-macios/issues/18973.
=> [registrar] Look in nested types when looking for protocol wrapper types to register. Fixes #18973.

src/uikit.cs, tests/xtro-sharpie/api-annotations-dotnet/iOS-UIKit.ignore, tests/xtro-sharpie/api-annotations-dotnet/tvOS-UIKit.ignore, tests/xtro-sharpie/iOS-UIKit.ignore, tests/xtro-sharpie/tvOS-UIKit.ignore
Fixes https://github.com/xamarin/xamarin-macios/issues/19019.
=> [UIKit] Make UIView.HitTest's return value nullable. Fixes #19019.

dotnet/Makefile
The `@(ShortNames)` items in `vs-workload.props` need to be consistent
across branches that depend on eachother in order to generate valid VS
manifests, as this item group is used to construct the VS component IDs
that correspond with each workload pack.
This means that in the .NET 8 branches, we also need `@(ShortNames)`
items for all .NET 7 pack names that are trimmed when building various
.NET 7 branches.
The generated `vs-workload.props` file has been updated to include such
entries, for example:
<ShortNames Include="Microsoft.iOS.Ref.net8.0-16.4">
<Replacement>Microsoft.iOS.Ref</Replacement>
</ShortNames>
<ShortNames Include="Microsoft.iOS.Ref.net7.0-16.0">
<Replacement>Microsoft.iOS.Ref</Replacement>
</ShortNames>
<ShortNames Include="Microsoft.iOS.Ref.net7.0-16.4"> …
=> [vs-workload] Add @(ShortNames) items for net7.0

src/ObjCRuntime/Dlfcn.cs, tests/xtro-sharpie/api-annotations-dotnet/macOS-CoreFoundation.ignore
Fixes this:
ObjCRuntime/Dlfcn.cs(102,20): warning CS0649: Field 'Dlfcn.Dl_info.dli_fbase' is never assigned to, and will always have its default value
ObjCRuntime/Dlfcn.cs(103,20): warning CS0649: Field 'Dlfcn.Dl_info.dli_sname' is never assigned to, and will always have its default value
ObjCRuntime/Dlfcn.cs(104,20): warning CS0649: Field 'Dlfcn.Dl_info.dli_saddr' is never assigned to, and will always have its default value
ObjCRuntime/Dlfcn.cs(101,20): warning CS0649: Field 'Dlfcn.Dl_info.dli_fname' is never assigned to, and will always have its default value
The warning is new, after we removed the referencing code from .NET in a recent commit.
=> [src] Exclude more code from .NET to fix compiler warning.

dotnet/targets/Xamarin.Shared.Sdk.props
The .mobile.props file is a file created and written by the mobile VS extension to store property values that needs to be read early enough in the build chain, as in design time builds, and that can't be set by CPS because of a limitation in the project system. See more information here: https://github.com/xamarin/XamarinVS/pull/13606
Initially it was named .user.env file and then was renamed in another PR as part of a feedback from the project system team. See more information here: https://github.com/xamarin/XamarinVS/pull/13628
Because this file was saved in the intermediate output path, it was meant to be imported automatically by MSBuild, however we recently detected that this was not happening reliably. Because of this, some things like C# Hot Reload for iOS stopped working because …
=> [release/7.0.3xx] [remote] Explicitly import .mobile.props file (#18718)

tests/dotnet/UnitTests/ProjectTest.cs
Improve a test about warnings to list all the underlying linker warnings,
instead of just stating that a specific assembly has any linker warnings.
=> [tests] Improve a test about warnings to list all the underlying warnings.

tests/monotouch-test/CoreServices/FSEventStreamTest.cs
They fail randomly, and there doesn't seem to be a way to fix that as far as I
can figure out.
Fixes https://github.com/xamarin/maccore/issues/2630.
=> [tests] Ignore the FSEventStream tests on the bots. Fixes xamarin/maccore@2630.

msbuild/Xamarin.MacDev.Tasks/Tasks/ResolveNativeReferences.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/ResolveNativeReferencesBase.cs, tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/ResolveNativeReferencesTaskTest.cs
It looks like ResolveNativeReferences was always intended to execute remotely
from Windows (when used in the _ExpandNativeReferences target, the task is
given a session id, and only called when IsMacEnabled=true), but the task
itself never implemented the code to execute remotely.
Weirdly enough this was never an issue, because the task never did something
that had to be done on a Mac.
That is, until recently, when the task learned to decompress zip files, by
executing /usr/bin/unzip.
Obviously this doesn't work on Windows, so fix it by adding support for the
task to execute remotely.
Fixes https://github.com/xamarin/xamarin-macios/issues/19027.
=> [msbuild] Add support to the ResolveNativeReferences task to execute remotely. Fixes #19027.

dotnet/targets/Xamarin.Shared.Sdk.targets, tests/dotnet/UnitTests/ProjectTest.cs
ILLink doesn't handle library projects the way we need: the library is
automatically treated as a root assembly, with the entry point as the root.
This doesn't work, because library projects don't have an entry point.
In earlier versions of .NET (and Xamarin), we'd solved this by a custom linker
step that would manually root everything that needed to be rooted, but that
doesn't work anymore because we hit this sanity check in ILLink:
> ILLink : error IL1034: Root assembly 'MyExtension, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have entry point.
Technically this happens because the library project is configured as a root
assembly, where the entry point is the root point (and in that regards the
sanity check is rather sane).
The best solution would be if we could just …
=> [dotnet] Work around an expectation mismatch between ILLink and library projects. Fixes #19037.

tests/xharness/Harness.cs
When parsing configuration files, our logic works on a first-come-wins basis,
where the first time we find a variable, that's the value we get.
In the makefiles it's the opposite: the final value is the last time a
variable is set.
This means we must parse configuration files in the reverse order, otherwise this:
INCLUDE_IOS=
INCLUDE_IOS=1
will get the opposite result of what we want.
=> [xharness] Fix parsing configuration files.

msbuild/Xamarin.MacDev.Tasks/Tasks/ResolveNativeReferences.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/ResolveNativeReferencesBase.cs, tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/ResolveNativeReferencesTaskTest.cs
It looks like ResolveNativeReferences was always intended to execute remotely
from Windows (when used in the _ExpandNativeReferences target, the task is
given a session id, and only called when IsMacEnabled=true), but the task
itself never implemented the code to execute remotely.
Weirdly enough this was never an issue, because the task never did something
that had to be done on a Mac.
That is, until recently, when the task learned to decompress zip files, by
executing /usr/bin/unzip.
Obviously this doesn't work on Windows, so fix it by adding support for the
task to execute remotely.
Fixes https://github.com/xamarin/xamarin-macios/issues/19027.
Backport of #19047.
=> [release/7.0.3xx] [msbuild] Add support to the ResolveNativeReferences task to execute remotely. Fixes #19027.

tests/mtouch/MTouch.cs, tests/xharness/Jenkins/RunDeviceTasksFactory.cs, tests/xharness/Jenkins/RunSimulatorTasksFactory.cs, tests/xharness/Jenkins/TestSelector.cs, tests/xharness/TestLabel.cs, tools/devops/automation/build-pipeline.yml, tools/devops/automation/build-pull-request.yml, tools/devops/automation/templates/main-stage.yml, tools/devops/automation/templates/tests/build.yml, tools/devops/automation/templates/tests/run-tests.yml, tools/devops/automation/templates/tests/stage.yml
This fixes an issue where we wouldn't enable the mtouch tests, because we
check if iOS is enabled to enable them, and it turns out iOS isn't enabled by
default, only 64-bit iOS.
This is rather unintuitive, so just remove the 32-bit/64-bit distinction in
xharness and Azure Pipeline, since our support for 32-bit iOS is very rapidly
going away (with Xcode 15 support) anyway.
=> [tests] Remove the 32-bit/64-bit difference for iOS tests.

dotnet/Makefile
Adds `.xcode15` to the VS manifest file name to avoid conflicts with the
main .NET 8 branch.
The manifests produced by this branch will now have the following names:
Microsoft.NET.Sdk.iOS.MacCatalyst.macOS.tvOS.Workload.net8.0.xcode15.vsman
Microsoft.NET.Sdk.iOS.MacCatalyst.macOS.tvOS.Workload.net8.0.xcode15.multitarget.vsman
=> [release-test/net8.0-xcode15-multi-targeting] Update vsman name

eng/Version.Details.xml, eng/Versions.props
We'll get new builds automatically, but not existing ones.
=> [release/8.0.1xx-rc2] Bump the xamarin-macios/7.0.3xx dependency manually.

Make.config, eng/Version.Details.xml, eng/Versions.props
Changes: https://github.com/dotnet/runtime/compare/287c10d2539d47268a1083c4d533cf84124900cf...1757497f37245d1756870fb1c0b3221c0d235d54
Because the .NET SDK has switched over to internal code flow, we have to
subscribe to runtime directly.
This initial bump I did manually by removing CoherentParentDependency, then I ran the command:
$ darc update-dependencies --id 193757
Looking up build with BAR id 193757
cbell
Updating 'Microsoft.NET.Runtime.MonoTargets.Sdk': '7.0.7' => '8.0.0-rc.2.23471.3' (from build '20230921.3' of 'https://github.com/dotnet/runtime')
Updating 'Microsoft.NETCore.App.Ref': '8.0.0-rc.1.23419.3' => '8.0.0-rc.2.23471.3' (from build '20230921.3' of 'https://github.com/dotnet/runtime')
Checking for coherency updates...
Using 'Strict' coherency mode. If this fails, a second …
=> [release/8.0.1xx-rc2] Bump dotnet/runtime manually.

Make.config
The duplicated code probably happened during a merge conflict, which wasn't
resolved correctly.
=> Remove duplicated make logic.

tools/dotnet-linker/Steps/ManagedRegistrarLookupTablesStep.cs
There is an issue with managed static registrar and explicitly rooted assemblies (through linker descriptor files) where the linker does not emit the created module initializer.
This was originally reported in: https://github.com/dotnet/runtime/issues/92106
and a smaller repro can be set up in: `tests/dotnet/MySingleView` test project with the following changes:
1. Add a descriptor xml - `Roots.xml`
```xml
<linker>
<assembly fullname="MySingleView" preserve="All" />
</linker>
```
2. Include the root descriptor in the `MySingleView.csproj`
```xml
<ItemGroup>
<TrimmerRootDescriptor Condition="'$(_RootSelf)' == 'true'" Include="Roots.xml" />
</ItemGroup>
```
3.  Publish/run the app on a device
```bash
dotnet publish -c Release -r ios-arm64 -p:PublishAot=true …
```
=> NativeAOT: Mark module constructors in MSR 

src/Foundation/NSObject2.cs
Fixes #8439
Could only adjust the debugger visibility of the IsDirectBinding member because the targets of the DebuggerBrowsable attribute does not include methods..
Ref: https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.debuggerbrowsableattribute?view=net-7.0
=> [Foundation] Improve visibility of NSObject members in intellisense

msbuild/Xamarin.Shared/Xamarin.Shared.targets
"IsHotRestartBuild" is an MSBuild global property set by the VS extension or manually when running a CLI build, however for multi target frameworks builds it could happen that if the global value has been set to true, it will remain true for all the inner builds and affect other target frameworks that are not compatible with Hot Restart (e.g: MacCatalyst).
This commit adds an extra target "_DetectBuildType", which will set the correct value for "IsHotRestartBuild" and "IsRemoteBuild", so any other target that uses those properties can be sure that the values are the right ones for the current build run.
Fixes Bug #1886158 - [MAUI][.NET8] MAUI/MAUI Blazor project build on local device failed with error 'The "CompileAppManifest" task failed unexpectedly'.: …
=> [net8.0] [hotrestart] Ensure we set the correct value for the "IsHotRestartBuild" property

msbuild/Xamarin.Shared/Xamarin.Shared.targets
"IsHotRestartBuild" is an MSBuild global property set by the VS extension or manually when running a CLI build, however for multi target frameworks builds it could happen that if the global value has been set to true, it will remain true for all the inner builds and affect other target frameworks that are not compatible with Hot Restart (e.g: MacCatalyst).
This commit adds an extra target "_DetectBuildType", which will set the correct value for "IsHotRestartBuild" and "IsRemoteBuild", so any other target that uses those properties can be sure that the values are the right ones for the current build run.
Fixes Bug #1886158 - [MAUI][.NET8] MAUI/MAUI Blazor project build on local device failed with error 'The "CompileAppManifest" task failed unexpectedly'.: …
=> [release/7.0.3xx] [hotrestart] Ensure we set the correct value for the "IsHotRestartBuild" property

msbuild/Xamarin.Shared/Xamarin.Shared.targets
"IsHotRestartBuild" is an MSBuild global property set by the VS extension or manually when running a CLI build, however for multi target frameworks builds it could happen that if the global value has been set to true, it will remain true for all the inner builds and affect other target frameworks that are not compatible with Hot Restart (e.g: MacCatalyst).
This commit adds an extra target "_DetectBuildType", which will set the correct value for "IsHotRestartBuild" and "IsRemoteBuild", so any other target that uses those properties can be sure that the values are the right ones for the current build run.
Fixes Bug #1886158 - [MAUI][.NET8] MAUI/MAUI Blazor project build on local device failed with error 'The "CompileAppManifest" task failed unexpectedly'.: …
=> [release/8.0.1xx-rc2] [hotrestart] Ensure we set the correct value for the "IsHotRestartBuild" property

msbuild/Xamarin.Shared/Xamarin.Shared.targets
"IsHotRestartBuild" is an MSBuild global property set by the VS extension or manually when running a CLI build, however for multi target frameworks builds it could happen that if the global value has been set to true, it will remain true for all the inner builds and affect other target frameworks that are not compatible with Hot Restart (e.g: MacCatalyst).
This commit adds an extra target "_DetectBuildType", which will set the correct value for "IsHotRestartBuild" and "IsRemoteBuild", so any other target that uses those properties can be sure that the values are the right ones for the current build run.
Fixes Bug #1886158 - [MAUI][.NET8] MAUI/MAUI Blazor project build on local device failed with error 'The "CompileAppManifest" task failed unexpectedly'.: …
=> [hotrestart] Ensure we set the correct value for the "IsHotRestartBuild" property

dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets, tests/dotnet/UnitTests/ProjectTest.cs
Reverts xamarin/xamarin-macios#18669 per discussion in MAUI about sdk defaults.
See https://github.com/dotnet/maui/pull/16355 for more information. Consult teams thread for more information:
https://teams.microsoft.com/l/message/19:989ffa44998147aca4ceaf7482967668@thread.skype/1696009594958?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=0056f60b-301f-43ac-bbcf-f356d3c42c92&parentMessageId=1696009594958&teamName=VS%20Client%20Experiences&channelName=MAUI%20🌺&createdTime=1696009594958 (MSFT only)
=> Revert "[MacCatalyst] Added Default Entitlements for MacCatalyst projects"

msbuild/Directory.Build.props
The latest version has Component Governance fixes in it: https://github.com/xamarin/isignsharp/pull/52/files
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1869900
Backport of #19046
=> [release/7.0.3xx] Updating Xamarin.iOS.HotRestart.Client to 1.0.125

dotnet/targets/Xamarin.Shared.Sdk.targets, tests/dotnet/UnitTests/ProjectTest.cs, tests/introspection/ApiPInvokeTest.cs, tools/linker/MonoTouch.Tuner/ListExportedSymbols.cs
It's possible to create a provisioning profile for Mac Catalyst that doesn't
allow dylibs in the app. It seems a significant number of people run into this
problem when publishing their apps, so avoid it by linking Mono and Xamarin
statically by default instead.
The downside is that build time might increase a little bit.
An upside however is that the app size might decrese somewhat.
Fixes https://github.com/xamarin/xamarin-macios/issues/14686.
Backport of #18619
=> [release/7.0.3xx] [dotnet] Link Mono and Xamarin statically in Mac Catalyst by default. Fixes #14686.

tools/devops/automation/templates/sign-and-notarized/setup.yml
=> [release/8.0.1xx] [CI] Ensure we use python 3 before we install the ESRP plugin.

tools/devops/automation/templates/sign-and-notarized/setup.yml
=> [xcode14.3] [CI] Ensure we use python 3 before we install the ESRP plugin.

tools/devops/automation/templates/sign-and-notarized/setup.yml
=> [release/8.0.1xx-rc2] [CI] Ensure we use python 3 before we install the ESRP plugin.

tools/devops/automation/templates/sign-and-notarized/setup.yml
=> [release/7.0.3xx] [CI] Ensure we use python 3 before we install the ESRP plugin.

dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets, tests/dotnet/UnitTests/ProjectTest.cs
Reverts xamarin/xamarin-macios#18669 per discussion in MAUI about sdk defaults.
See https://github.com/dotnet/maui/pull/16355 for more information. Consult teams thread for more information:
https://teams.microsoft.com/l/message/19:989ffa44998147aca4ceaf7482967668@thread.skype/1696009594958?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=0056f60b-301f-43ac-bbcf-f356d3c42c92&parentMessageId=1696009594958&teamName=VS%20Client%20Experiences&channelName=MAUI%20??&createdTime=1696009594958 (MSFT only)
Backport of #19125
=> [release/8.0.1xx] Revert "[MacCatalyst] Added Default Entitlements for MacCatalyst projects"

dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets, tests/dotnet/UnitTests/ProjectTest.cs
Reverts xamarin/xamarin-macios#18669 per discussion in MAUI about sdk defaults.
See https://github.com/dotnet/maui/pull/16355 for more information. Consult teams thread for more information:
https://teams.microsoft.com/l/message/19:989ffa44998147aca4ceaf7482967668@thread.skype/1696009594958?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=0056f60b-301f-43ac-bbcf-f356d3c42c92&parentMessageId=1696009594958&teamName=VS%20Client%20Experiences&channelName=MAUI%20??&createdTime=1696009594958 (MSFT only)
Backport of #19125
=> [release/8.0.1xx-rc2.1] Revert "[MacCatalyst] Added Default Entitlements for MacCatalyst projects"

src/automaticassessmentconfiguration.cs, tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-AutomaticAssessmentConfiguration.ignore, tests/xtro-sharpie/api-annotations-dotnet/macOS-AutomaticAssessmentConfiguration.ignore, tests/xtro-sharpie/macOS-AutomaticAssessmentConfiguration.ignore
Fixes https://github.com/xamarin/xamarin-macios/issues/19133.
=> [AutomaticAssessmentConfiguration] Add missing constructors to AEAssessmentApplication. Fixes #19133.

dotnet/targets/Xamarin.Shared.Sdk.props, tests/xharness/Jenkins/TestVariationsFactory.cs
We couldn't do universal builds using NativeAOT, because .NET had a sanity
check that was a bit too eager and caused unnecessary build failures. We've
now been able to add an escape hatch to that sanity check, so let's use it.
This makes universal builds using NativeAOT work, so we can also enable/add
corresponding test variations in xharness.
Also ask the runtime to allow SelfContained without a RuntimeIdentifier (the
runtime has an overeager sanity check that doesn't apply to us, so we must
skip it). Fixes #19142.
Fixes https://github.com/xamarin/xamarin-macios/issues/19142.
Fixes https://github.com/xamarin/xamarin-macios/issues/19206.
Backport of #19183
=> [release/8.0.1xx] [dotnet] Complete support for universal builds when using NativeAOT.

tests/dotnet/Windows/InstallDotNet.csproj
The documented URL for downloading a script to install .NET
(https://dot.net/v1/dotnet-install.[ps1|sh]) is rather unreliable and fails
quite often. So add support for a fallback URL - which is just the url the
documented URL redirects to - and use that if the main URL doesn't work.
Hopefully this will decrease the number of times the Windows tests fail
because we couldn't download the install script.
Backport of #19212
=> [release/8.0.1xx-rc2.1] [tests] Implement a workaround for an unreliable url to download a command-line installer for .NET.

tests/dotnet/Windows/InstallDotNet.csproj
The documented URL for downloading a script to install .NET
(https://dot.net/v1/dotnet-install.[ps1|sh]) is rather unreliable and fails
quite often. So add support for a fallback URL - which is just the url the
documented URL redirects to - and use that if the main URL doesn't work.
Hopefully this will decrease the number of times the Windows tests fail
because we couldn't download the install script.
Backport of #19212
=> [release/7.0.3xx] [tests] Implement a workaround for an unreliable url to download a command-line installer for .NET.

msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx, msbuild/Xamarin.MacDev.Tasks/Tasks/CreateBindingResourcePackageBase.cs
This fixes makes this rather unhelpful error:
error MSB4018: The "CreateBindingResourcePackage" task failed unexpectedly.
error MSB4018: System.Exception: Could not lstat 'mylib.a': 2
error MSB4018:    at Xamarin.Utils.PathUtils.IsSymlink(String file) in /Users/rolf/work/maccore/main/xamarin-macios/tools/common/PathUtils.cs:line 222
error MSB4018:    at Xamarin.Utils.PathUtils.IsSymlinkOrContainsSymlinks(String directoryOrFile) in /Users/rolf/work/maccore/main/xamarin-macios/tools/common/PathUtils.cs:line 229
error MSB4018:    at Xamarin.MacDev.Tasks.CreateBindingResourcePackageBase.ContainsSymlinks(ITaskItem[] items) in /Users/rolf/work/maccore/main/xamarin-macios/msbuild/Xamarin.MacDev.Tasks/Tasks/CreateBindingResourcePackageBase.cs:line 110
error MSB4018:    at …
=> [msbuild] Report a better error if a NativeResource doesn't exist on disk.

dotnet/targets/Xamarin.Shared.Sdk.targets, msbuild/Xamarin.iOS.Tasks/Tasks/ILStripBase.cs
The current logic doesn't work on Windows for some reason.
Also avoid extra slash in _StrippedAssemblyDirectory, because
DeviceSpecificIntermediateOutputPath already has a trailing slash.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1864985.
Backport of #19181
=> [release/8.0.1xx] [dotnet/msbuild] Create directory in the ILStrip task instead of using MSBuild logic.

dotnet/targets/Xamarin.Shared.Sdk.targets, msbuild/Xamarin.iOS.Tasks/Tasks/ILStripBase.cs
The current logic doesn't work on Windows for some reason.
Also avoid extra slash in _StrippedAssemblyDirectory, because
DeviceSpecificIntermediateOutputPath already has a trailing slash.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1864985.
Backport of #19181
=> [release/8.0.1xx-rc2.1] [dotnet/msbuild] Create directory in the ILStrip task instead of using MSBuild logic.

msbuild/Xamarin.MacDev.Tasks/Tasks/ResolveNativeReferencesBase.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/XamarinTask.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/19173.
Backport of #19227.
=> [release/7.0.3xx] [msbuild] Copy the entire frameworks to the Mac when building remotely in the ResolveNativeReferences task. Fixes #19173.

msbuild/Xamarin.MacDev.Tasks/Tasks/ResolveNativeReferencesBase.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/XamarinTask.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/19173.
Backport of #19227
=> [release/8.0.1xx-rc2.1] [msbuild] Copy the entire frameworks to the Mac when building remotely in the ResolveNativeReferences task. Fixes #19173.

msbuild/Xamarin.MacDev.Tasks/Tasks/ResolveNativeReferencesBase.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/XamarinTask.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/19173.
Backport of #19227
=> [release/8.0.1xx] [msbuild] Copy the entire frameworks to the Mac when building remotely in the ResolveNativeReferences task. Fixes #19173.

Localize/loc/ja/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/ru/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/zh-Hans/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/zh-Hant/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
=> Bring changes from Localization branch #20231018.2

mk/xamarin.mk
=> [release/8.0.1xx-rc2.1] Bump mlaunch to get fix for older devices.

mk/xamarin.mk
=> [release/8.0.1xx] Bump mlaunch to get fix for older devices.

mk/xamarin.mk
=> [xcode14.3] Bump mlaunch to get fix for older devices.

mk/xamarin.mk
=> [release/7.0.3xx] Bump mlaunch to get fix for older devices.

mk/xamarin.mk
=> Bump mlaunch to get fix for older devices.

src/xkit.cs
Both headers and documentation agree that:
* The TextLists and LineBreakStrategy properties are available in all OS
versions we support, so adjust the availability attributes accordingly.
* While the NSLineBreakStrategy enum is supposedly not available in all OS
versions we support, the NSLineBreakStrategy.PushOut enum value is. This
doesn't make much sense, so I've made our enum available in all OS versions
+ the PushOut enum value as well. All the other enum values are only
available in iOS 14+ (according to docs + headers).
Fixes https://github.com/xamarin/xamarin-macios/issues/19209.
=> [AppKit/UIKit] Adjust a few availability attributes in NS[Mutable]ParagraphStyle. Fixes #19209.

mk/xamarin.mk
=> [release/7.0.3xx] Bump mlaunch to get resource fix.

mk/xamarin.mk
=> [release/8.0.1xx] Bump mlaunch to get resource fix.

mk/xamarin.mk
=> Bump mlaunch to get resource fix.

mk/xamarin.mk
=> [release/8.0.1xx-rc2.1] Bump mlaunch to get resource fix.

Localize/loc/fr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
=> Bring changes from Localization branch #20231019.4

mk/xamarin.mk
=> [xcode14.3] Bump mlaunch to get resource fix.

msbuild/Directory.Build.props
Reverts xamarin/xamarin-macios#19130
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1907373
Per discussion with @mauroa and @emaf this was wrongly back ported to this branch and it was meant only on the legacy xcode14.3 branch.
=> Revert "[release/7.0.3xx] Updating Xamarin.iOS.HotRestart.Client to 1.0.125"

msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.cs.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.de.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.es.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.fr.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.it.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ja.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ko.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pl.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pt-BR.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ru.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.tr.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hans.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17751: Build ID 8579266

dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets, dotnet/targets/Xamarin.Shared.Sdk.targets, tests/dotnet/UnitTests/ProjectTest.cs
When migrating Xamarin projects to .NET projects, somewhat frequently people
will leave the MtouchArch/XamMacArch properties in their project files with
old values. This won't work, since we use RuntimeIdentifier(s) now to control
the target architecture, so remove support for MtouchArch/XamMacArch, and show
an error if we detect that they're set.
This will hopefully prevent some really confusing problems, especially in the IDEs.
Example: https://github.com/xamarin/xamarin-macios/issues/19258
=> [dotnet] Remove support for MtouchArch and XamMacArch.

msbuild/Xamarin.MacDev.Tasks/Tasks/ResolveNativeReferencesBase.cs
Look for any binding resource packages (a directory named AssemblyName.resources
or a compressed version named AssemblyName.resources.zip) next to any references,
and copy those to the remote Mac when doing remote builds.
Fixes https://github.com/xamarin/xamarin-macios/issues/19229.
=> [msbuild] Look for and copy binding resource packages to the remote Mac in the ResolveNativeReferences task. Fixes #19229.

msbuild/Xamarin.iOS.Tasks.Windows/Tasks/ComputeHotRestartBundleContents.cs, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.props, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
1. Move the signing to after we copy files that must be signed into the app bundle
that will be signed: we sign in the _CodesignHotRestartAppBundle target, so this
means the targets _CopyHotRestartBundleResources and _CopyFilesToHotRestartSignedAppDirContents
must execute first.
2. Try to clear up some confusion about the directories involved. The HotRestartSignedAppOutputDir
property indicates the location of the _signed_ app bundle, which means no files
should be added there. Instead files that should be signed (or present when the
app launches) must be placed in the HotRestartAppBundlePath directory.
3. Document each property involved to try to avoid more mistakes in the future.
Fixes https://github.com/xamarin/xamarin-macios/issues/19278.
=> [msbuild] Copy files to be signed into the correct directory for Hot Restart. Fixes #19278.

dotnet/targets/Xamarin.Shared.Sdk.targets, msbuild/Xamarin.MacDev.Tasks/Tasks/FilterStaticFrameworksTaskBase.cs, msbuild/Xamarin.Shared/Xamarin.Shared.targets, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
The main problem is that an app with unsigned executable code will fail any signing
verification, and the app won't install on device.
This is implemented by doing two changes:
1. Augment the FilterStaticFrameworks task to only filter out frameworks with
static libraries (and thus keeping everything that's not a static framework, even
if it's not even a framework).
2. Execute the FilterStaticFrameworks task to filter out static frameworks from
the entire list of files to bundle in the hot restart app bundle.
=> [msbuild] Don't add frameworks with static libraries to Hot Restart apps.

msbuild/Xamarin.Shared/Xamarin.Shared.targets
This fixes an issue where xcframeworks weren't properly resolved for Hot Restart.
=> [msbuild] Enable the _ExpandNativeReferences target for Hot Restart.

src/appkit.cs
It doesn't exist there, and it also fails a test:
[FAIL] StaticMethods :   1 errors found in 3389 static selector validated:
AppKit.NSImage : imageWithSymbolName:bundle:variableValue:
Expected: 0
But was:  1
=> [AppKit] Remove [NSImage imageWithSymbolName:bundle:variableValue:] from Mac Catalyst.

dotnet/targets/Xamarin.Shared.Sdk.targets, msbuild/Xamarin.MacDev.Tasks/Tasks/FilterStaticFrameworksTaskBase.cs, msbuild/Xamarin.Shared/Xamarin.Shared.targets, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
The main problem is that an app with unsigned executable code will fail any signing
verification, and the app won't install on device.
This is implemented by doing two changes:
1. Augment the FilterStaticFrameworks task to only filter out frameworks with
static libraries (and thus keeping everything that's not a static framework, even
if it's not even a framework).
2. Execute the FilterStaticFrameworks task to filter out static frameworks from
the entire list of files to bundle in the hot restart app bundle.
Backport of #19300
=> [release/8.0.1xx] [msbuild] Don't add frameworks with static libraries to Hot Restart apps.

msbuild/Xamarin.MacDev.Tasks/Tasks/ResolveNativeReferencesBase.cs
Look for any binding resource packages (a directory named AssemblyName.resources
or a compressed version named AssemblyName.resources.zip) next to any references,
and copy those to the remote Mac when doing remote builds.
Fixes https://github.com/xamarin/xamarin-macios/issues/19229.
Backport of #19325
=> [release/8.0.1xx] [msbuild] Look for and copy binding resource packages to the remote Mac in the ResolveNativeReferences task. Fixes #19229.

msbuild/Xamarin.MacDev.Tasks/Tasks/ResolveNativeReferencesBase.cs
Look for any binding resource packages (a directory named AssemblyName.resources
or a compressed version named AssemblyName.resources.zip) next to any references,
and copy those to the remote Mac when doing remote builds.
Backport of #19325.
=> [release/7.0.3xx] [msbuild] Look for and copy binding resource packages to the remote Mac in the ResolveNativeReferences task. Fixes #19229.

NuGet.config, eng/Version.Details.xml, eng/Versions.props, tools/dotnet-linker/dotnet-linker.csproj
* The 'Microsoft.NET.Workload.Emscripten.Current.Manifest-8.0.100.Transport' dependency was renamed to 'Microsoft.NET.Workload.Emscripten.Current.Manifest-8.0.100'
* Add a separate dependency for 'Microsoft.NET.ILLink', since it can have a different version than 'Microsoft.NET.ILLink.Tasks'.
* Update using the '.NET 8' and '.NET 8.0.1xx' channels.
Backport of #19347
=> [release/8.0.1xx] [maestro] Fix a few issues with the maestro subscriptions.

msbuild/Xamarin.iOS.Tasks.Windows/Tasks/ComputeHotRestartBundleContents.cs, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.props, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
1. Move the signing to after we copy files that must be signed into the app bundle
that will be signed: we sign in the _CodesignHotRestartAppBundle target, so this
means the targets _CopyHotRestartBundleResources and _CopyFilesToHotRestartSignedAppDirContents
must execute first.
2. Try to clear up some confusion about the directories involved. The HotRestartSignedAppOutputDir
property indicates the location of the _signed_ app bundle, which means no files
should be added there. Instead files that should be signed (or present when the
app launches) must be placed in the HotRestartAppBundlePath directory.
3. Document each property involved to try to avoid more mistakes in the future.
Fixes https://github.com/xamarin/xamarin-macios/issues/19278.
Backport of #19302
=> [release/8.0.1xx] [msbuild] Copy files to be signed into the correct directory for Hot Restart. Fixes #19278.

tests/monotouch-test/Foundation/UserDefaultsTest.cs
Try to fix a few random test failures in UserDefaultsTests by making sure they
won't fail if another process is running the test at the same time by adding
the PID to any machine-wide identifiers.
Might fix:
* https://github.com/xamarin/maccore/issues/2488
* https://github.com/xamarin/maccore/issues/2725
=> [tests] Try to fix a few random test failures in UserDefaultsTests.

src/uikit.cs
Both headers and documentation agree that these members were introduced with
the type itself, so we can just remove our member-specific availability
attributes and inherit from the parent (class) instead.
Fixes https://github.com/xamarin/xamarin-macios/issues/19377.
=> [UIKit] Adjust availability attributes for UIButtonConfiguration.[Sub]TitleLineBreakMode. Fixes ##19377.

src/uikit.cs
The UIContextMenuInteraction type is a bit uncommon: the delegate is passed as
an argument to the constructor, instead of setting the 'delegate' property
later on (in fact, the 'delegate' property is read-only).
Typically, the generated WeakDelegate property will store the value in an instance field:
object? __mt_WeakDelegate_var;
public virtual NSObject? WeakDelegate {
get {
NSObject? ret = /* ... */;
MarkDirty ();
__mt_WeakDelegate_var = ret;
return ret!;
}
}
And in order to have the same behavior in the UIContextMenuInteraction we need to
store the delegate passed to the constructor as well, so do that.
Otherwise the GC will eventually collect the delegate, and things stop working.
Ref: https://github.com/dotnet/maui/pull/18449
=> [UIKit] Store the delegate in a local variable in the UIContextMenuInteraction.

Make.config, dotnet/VERSIONS.md
Long versions are sometimes problematic on Windows, because of MAX_PATH
issues. Versions for release builds don't contain the pre-release part, and
are thus usually short, but pre-release versions (which include an arbitrarily
long branch name) can get too long for Windows. This is a complication when
testing a release pipeline/process: we have to use final versioning just for
testing. This isn't ideal, so we special-case branch names that start with
`release-test/rt/`:
* Example: `iOS 15.1.123-rt` (and nothing else). This makes these versions
exactly 3 characters longer than the release version, which is hopefully
enough to avoid MAX_PATH issues on Windows.
=> Add special versioning rules for 'release-test/rt/' branches to have shorter versioning.

tools/devops/automation/templates/sign-and-notarized/funnel.yml
This fixes this error in Azure DevOps:
* [PR] bundle.zip — bundle.zip not found.
* [PR] msbuild.zip — msbuild.zip not found.
=> [devops] Add the bundle.zip and msbuild.zip files to the 'package' artifact.

docs/nativeaot.md
Fixes https://github.com/xamarin/xamarin-macios/issues/18585.
=> [docs] Document NativeAOT support. Fixes #18585.

tools/devops/automation/templates/main-stage.yml, tools/devops/automation/templates/sign-and-notarized/upload-azure.yml, tools/devops/automation/templates/windows/build.yml
Use yaml's support for multiline keys (?:) to avoid an enormously long line
for a compile-time Azure DevOps expression.
Ref: https://github.com/microsoft/azure-pipelines-yaml/issues/533#issuecomment-1007398866
Also fix a few other cases with long lines.
=> [devops] Avoid long lines in yaml.

tests/common/BinLog.cs
We no longer need this workaround.
Fixes https://github.com/xamarin/xamarin-macios/issues/18568.
=> [tests] Revert workaround for bug in MSBuild[.StructuredLogger]. Fixes #18568.

dotnet/Makefile, dotnet/targets/Microsoft.Sdk.Versions.template.props, dotnet/targets/Xamarin.Shared.Sdk.targets
This way we can avoid hardcoding the .NET version later in the build targets.
=> [dotnet] Store the .NET version we target in a generated props file.

tools/devops/automation/templates/sign-and-notarized/funnel.yml, tools/devops/automation/templates/sign-and-notarized/upload-azure.yml
Readd the statuses for bundle.zip and msbuild.zip, we use them as api
references when doing the api diff.
This is a partial revert of 3bc4dfde9f88c803628439aa98c593557cc355db, since we
do not need the nugets.
=> [CI] Readd the statuses for bundle.zip and msbuild.zip

tools/devops/automation/templates/sign-and-notarized/setup.yml
=> [release/8.0.1xx] [CI] Pin the python version to 3.11 until ESRP fixes their deps.

Make.config, tools/apidiff/Makefile
The released commit for .NET 8 isn't the exact same commit as the one
referenced here, because the build.zip file wasn't produced in that commit -
this was fixed, so it's a few commits later. There were no API changes between
these commits though, so the API references are identical.
Backport of #19434
=> [release/8.0.1xx] Bump api references for .NET 8 and legacy Xamarin.

runtime/launcher.m, runtime/runtime.m, runtime/shared.m, runtime/trampolines.m, runtime/xamarin-support.m, runtime/xamarin/runtime.h
Calling the direct functions instead of sending messages is slightly faster,
and additionally it may make some static analyzers think we've enabled ARC for
our Objective-C code (which we don't, because we need to manually manage
reference counting).
These direct functions aren't in any public header (they're in a private header),
but they're documented as part of ARC here: https://clang.llvm.org/docs/AutomaticReferenceCounting.html#runtime-support,
and clang emits references to these methods from user code, so it should be safe for us to use them.
Fixes https://github.com/xamarin/xamarin-macios/issues/19413.
=> [runtime] Use objc_[retain|release|autorelease] instead of sending messages.

Make.config, tools/apidiff/Makefile
The released commit for .NET 8 isn't the exact same commit as the one
referenced here, because the build.zip file wasn't produced in that commit -
this was fixed, so it's a few commits later. There were no API changes between
these commits though, so the API references are identical.
=> Bump api references for .NET 8 and legacy Xamarin.

Make.config, tools/apidiff/Makefile
The released commit for .NET 8 isn't the exact same commit as the one
referenced here, because the build.zip file wasn't produced in that commit -
this was fixed, so it's a few commits later. There were no API changes between
these commits though, so the API references are identical.
Backport of #19434.
=> [xcode14.3] Bump api references for .NET 8 and legacy Xamarin.

src/generator.csproj, tools/mmp/Makefile, tools/mmp/mmp.csproj, tools/mtouch/Makefile, tools/mtouch/mtouch.csproj
This reduces a source dependency on the legacy Mono package.
=> Use Mono.Options NuGet instead of building from source in a few projects.

tools/apidiff/Makefile
Bump api-tools to be able to handle newer reference xmls (#19436).
New commits in rolfbjarne/api-tools:
* rolfbjarne/api-tools@1fbbe00 [mono-api-html] Render abstract members correctly with the 'abstract' keyword.
* rolfbjarne/api-tools@6c37358 [mono-api-html] Handle default interface members better.
* rolfbjarne/api-tools@6d4007a [mono-api-html] Allow changing the base type if the old base type is a super class of the new base type.
* rolfbjarne/api-tools@cbc1e08 [mono-api-html] Fix compiler warning about obsolete formatter-based serialization attributes.
* rolfbjarne/api-tools@c7d5208 Use the current .NET version to build.
* rolfbjarne/api-tools@254f0e0 [mono-api-info] Add support for comparing function pointers.
* rolfbjarne/api-tools@ebc175f Update the .editorconfig file
Diff: …
=> [xcode14.3] Bump api-tools

tests/cecil-tests/ApiTest.cs
When run in the terminal using 'dotnet test', the text passed to Assert.Ignore is show in red, which makes it look like a failure and is always confusing.
Before:
After:
=> [tests] Don't pass a message to Assert.Ignore.

tools/devops/automation/templates/variables.yml
Otherwise our build logs ends up being huge, and takes a long time to download
(or just completely crashes the browser).
=> [devops] Set System.Debug to false by default.

src/Makefile.generator
The build is somewhat frequently failing on the bots with this:
> /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/NuGet.targets(131,5): error : Could not find file "/Users/builder/azdo/_work/2/a/change-detection/tmp/src/xamarin-macios/packages/mono.options/6.12.0.148/qo8orsfq.fp5"
Although I haven't been able to reproduce it, I believe it to be a race
condition between building the .NET version of the generator and the legacy
Xamarin version of the generator: if they both try to restore NuGet packages
at the same time, things may break.
Fix this by introducing an artificial dependency between the generators, so
that they're not built simultaneously, but instead sequentially.
This might make the build a few seconds slower, but predicable builds on the
bots …
=> [src] Try to fix race condition with regards to restoring NuGet packages.

src/ModelIO/MDLMaterial.cs, src/frameworks.sources
Looks like we forgot to add this file to the build when we bound the
corresponding APIs.
=> [ModelIO] Include MDLMaterial.cs in the build.

tools/mmp/driver.cs, tools/mmp/resolver.cs
Lately I've been seeing an increase in a build failure on boths due to
pkg-config crashing when generating the partial static registrar code in mmp.
Turns out it's not necessary to run pkg-config when generating the partial
static registrar code, so just skip it in that case.
Example crash:
Process exited with code 134, command:
/Library/Frameworks/Mono.framework/Versions/Current/bin/pkg-config --variable=prefix mono-2
mono_os_sem_post: semaphore_signal failed with error 15
=================================================================
Native Crash Reporting
=================================================================
Got a abrt while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application. …
=> [mmp] Don't run pkg-config when generating partial static registrar code.

tools/devops/automation/templates/variables.yml
Otherwise our build logs ends up being huge, and takes a long time to download
(or just completely crashes the browser).
Backport of #19468
=> [release/8.0.1xx] [devops] Set System.Debug to false by default.

tests/mtouch/MTouch.cs, tools/common/Assembly.cs
We currently detect/resolve binding resource packages (the sidecar) in two places:
* The ResolveNativeReferences MSBuild task.
* Inside mtouch/mmp/dotnet-linker.
Which means we end up passing every native library or framework twice to the native linker.
This is usually not a problem, the native linker will ignore duplicated
arguments, except when building remotely from Windows, in which case the build
process may end up with native libraries in different locations, because files
may end up in multiple places on the remote Mac if using absolute paths (see
https://github.com/xamarin/xamarin-macios/issues/18997 for a thorough explanation).
So completely remove the logic to detect/resolve binding resource packages in
mtouch/mmp/dotnet-linker, which will avoid the issue completely.
A few …
=> [release/8.0.1xx] [tools] Don't detect/resolve binding resource packages in mtouch/mmp/dotnet-linker. Fixes #19378.

tools/mmp/driver.cs, tools/mmp/resolver.cs
Lately I've been seeing an increase in a build failure on boths due to
pkg-config crashing when generating the partial static registrar code in mmp.
Turns out it's not necessary to run pkg-config when generating the partial
static registrar code, so just skip it in that case.
Example crash:
Process exited with code 134, command:
/Library/Frameworks/Mono.framework/Versions/Current/bin/pkg-config --variable=prefix mono-2
mono_os_sem_post: semaphore_signal failed with error 15
=================================================================
Native Crash Reporting
=================================================================
Got a abrt while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application. …
=> [release/8.0.1xx] [mmp] Don't run pkg-config when generating partial static registrar code.

src/uikit.cs
The UIContextMenuInteraction type is a bit uncommon: the delegate is passed as
an argument to the constructor, instead of setting the 'delegate' property
later on (in fact, the 'delegate' property is read-only).
Typically, the generated WeakDelegate property will store the value in an instance field:
object? __mt_WeakDelegate_var;
public virtual NSObject? WeakDelegate {
get {
NSObject? ret = /* ... */;
MarkDirty ();
__mt_WeakDelegate_var = ret;
return ret!;
}
}
And in order to have the same behavior in the UIContextMenuInteraction we need to
store the delegate passed to the constructor as well, so do that.
Otherwise the GC will eventually collect the delegate, and things stop working.
Ref: https://github.com/dotnet/maui/pull/18449
Backport of #19386
=> [release/8.0.1xx] [UIKit] Store the delegate in a local variable in the UIContextMenuInteraction.

msbuild/Xamarin.MacDev.Tasks/Tasks/DetectSigningIdentityTaskBase.cs, msbuild/Xamarin.Shared/Xamarin.Shared.targets
It's a duplicate of the ProvisioningProfile property, so use that instead.
=> [msbuild] Remove the CodesignProvision property from the DetectSigningIdentity task.

src/bgen/Caches/TypeCache.cs, src/bgen/Generator.cs
The dictionary needs to be init after the TypeCache. It is only natural for the TypeCache to be the owner of the dictionary.
We make the dictionary readonly to stop other code from introducing mistakes by modifying it.
=> [Generator] Move the NSValue create map to the TypeCache.

builds/create-csproj-for-all-packagereferences.sh, msbuild/Xamarin.MacDev.Tasks/Tasks/ResolveNativeReferencesBase.cs, tests/dotnet/AppWithXCFrameworkWithStaticLibraryInPackageReference/AppDelegate.cs, tests/dotnet/AppWithXCFrameworkWithStaticLibraryInPackageReference/MacCatalyst/AppWithXCFrameworkWithStaticLibraryInPackageReference.csproj, tests/dotnet/AppWithXCFrameworkWithStaticLibraryInPackageReference/MacCatalyst/Makefile, tests/dotnet/AppWithXCFrameworkWithStaticLibraryInPackageReference/Makefile, tests/dotnet/AppWithXCFrameworkWithStaticLibraryInPackageReference/iOS/AppWithXCFrameworkWithStaticLibraryInPackageReference.csproj, tests/dotnet/AppWithXCFrameworkWithStaticLibraryInPackageReference/iOS/Makefile, tests/dotnet/AppWithXCFrameworkWithStaticLibraryInPackageReference/macOS/AppWithXCFrameworkWithStaticLibraryInPackageReference.csproj, tests/dotnet/AppWithXCFrameworkWithStaticLibraryInPackageReference/macOS/Makefile, tests/dotnet/AppWithXCFrameworkWithStaticLibraryInPackageReference/shared.csproj, tests/dotnet/AppWithXCFrameworkWithStaticLibraryInPackageReference/shared.mk, tests/dotnet/AppWithXCFrameworkWithStaticLibraryInPackageReference/tvOS/AppWithXCFrameworkWithStaticLibraryInPackageReference.csproj, tests/dotnet/AppWithXCFrameworkWithStaticLibraryInPackageReference/tvOS/Makefile, tests/dotnet/UnitTests/ProjectTest.cs, tests/test-libraries/nugets/Makefile, tests/test-libraries/nugets/XCFrameworkWithStaticLibraryInRuntimesNativeDirectory/Library.cs, tests/test-libraries/nugets/XCFrameworkWithStaticLibraryInRuntimesNativeDirectory/Makefile, tests/test-libraries/nugets/XCFrameworkWithStaticLibraryInRuntimesNativeDirectory/XCFrameworkWithStaticLibraryInRuntimesNativeDirectory.csproj
The ResolveNativeReferences task would incorrectly set Kind=Framework for static
libraries and dylibs if these files came from an XCFramework in the runtimes/native
directory in a NuGet (as opposed to a binding project, or the NuGet built from a
binding project).
Fix this by properly assigning the Kind and PublishFolderType metadata for such static
libraries and dylibs.
Also add a test.
=> [msbuild] Fix resolving static libraries inside an XCFramework in a NuGet.

tools/devops/automation/templates/sign-and-notarized/setup.yml
=> [release/7.0.3xx] [CI] Pin the python version to 3.11 until ESRP fixes their deps.

Directory.Build.props, tests/bgen/bgen-tests.csproj, tests/dotnet/UnitTests/DotNetUnitTests.csproj, tests/generator/generator-tests.csproj, tests/mmptest/mmptest.csproj, tests/msbuild/Xamarin.MacDev.Tests/TestHelpers/BuildEngine.cs, tests/msbuild/Xamarin.MacDev.Tests/Xamarin.MacDev.Tests.csproj, tests/mtouch/mtouchtests.csproj, tools/create-dotnet-linker-launch-json/create-dotnet-linker-launch-json.csproj, tools/nnyeah/tests/nnyeah-tests.csproj
Also store the version globally to avoid having to update so many places in future bumps.
=> Bump MSBuild.StructuredLogger to v2.2.100

tests/msbuild/Xamarin.MacDev.Tests/TargetTests/CollectAppManifestsTests.cs
Make RuntimeIdentifier explicit in
CollectAppManifestsTests.PartialAppManifest, because we later try to look for
a path that depends on the runtime identifier, and setting the runtime
identifier explicitly is easier than figuring out the default runtime
identifier (which depends on the host architecture).
Fixes this failure on arm64 machines:
1) Failed : Xamarin.MacDev.Tasks.CollectAppManifestsTests.PartialAppManifest
App manifest existence
Expected: file or directory exists
But was:  "xamarin-macios/tests/msbuild/Xamarin.MacDev.Tests/bin/Debug/net472/tmp-test-dir/Xamarin.MacDev.Tasks.CollectAppManifestsTests.PartialAppManifest/bin/Debug/net8.0-macos/osx-x64/PartialAppManifest.app/Contents/Info.plist"
at Xamarin.MacDev.Tasks.CollectAppManifestsTests.PartialAppManifest () [0x0011d] in …
=> [tests] Set RuntimeIdentifier in CollectAppManifestsTests.PartialAppManifest

tests/dotnet/UnitTests/ProjectTest.cs, tests/linker/ios/link all/PreserveTest.cs, tests/monotouch-test/CoreMedia/BlockBufferTest.cs, tools/dotnet-linker/ApplyPreserveAttributeBase.cs
Closes #19505 
We transform `[Preserve(AllMembers = true)]` into `[DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(T))]`. There is difference between which members are preserved in these two cases. The `DynamicallyAccessedMemberTypes.All` preserves many more, especially nested types and their members. This manifested with the `IL3050` AOT analysis warning we got from ILC when building any app:
1. `NSObject_Disposer` has `[Preserve(AllMembers = true)]`
2. `NSObject_Disposer` is a subclass of NSObject
3. `NSObject` has nested enums `Flags` and `XamarinGCHandleFlags`
4. the base class `Enum` has a public static method `GetValues(Type)`
5. the `GetValues` method is annotated with `RequiresDynamicCode` and ILC produces a warning because even though it isn't used anywhere in the …
=> [NativeAOT] Improve the transformation of [Preserve(AllMembers = true)]

tests/dotnet/UnitTests/ProjectTest.cs, tests/dotnet/UnitTests/TestBaseClass.cs
It seems targets are ran in a different order in .NET 9, which means that we
ran into a different one that the one we expected. So fix that error, which
means we're now getting the error the test is checking for again.
Fixes:
Xamarin.Tests.DotNetProjectTest.InvalidArchProperty(TVOS,"MtouchArch","arm64"): Error count
Expected: 1
But was: 2
Xamarin.Tests.DotNetProjectTest.InvalidArchProperty(MacCatalyst,"MtouchArch","x64"): Error count
Expected: 1
But was: 2
Xamarin.Tests.DotNetProjectTest.InvalidArchProperty(MacOSX,"XamMacArch","x64"): Error message
Expected string length 172 but was 50. Strings differ at index 0.
Expected: "The property 'XamMacArch' is deprecated, please remove it fro..."
But was: "Could not parse TargetArchitectures 'x64'\n "
-----------^ …
=> [tests] Fix an issue with the ProjectTest.InvalidArchProperty test.

msbuild/Xamarin.MacDev.Tasks/Tasks/LinkNativeCodeTaskBase.cs, tests/dotnet/AppWithNativeDynamicLibrariesInPackageReference/MacCatalyst/Makefile, tests/dotnet/AppWithNativeDynamicLibrariesInPackageReference/macOS/Makefile, tests/dotnet/AppWithNativeDynamicLibrariesInPackageReference/shared.mk, tests/dotnet/UnitTests/ProjectTest.cs
We add the dylib location as an rpath if the app has any location, so make
sure to correctly detect dylibs in native references.
Fixes https://github.com/xamarin/xamarin-macios/issues/19520.
=> [msbuild] Detect any dylibs in NativeReferences. Fixes #19520.

configure
* fail if there are unknown parameters and --ignore-unknown-params is not provided
=> Add --ignore-unknown-params

builds/Makefile
This is one small step towards removing legacy Xamarin one day, since it
removes .NET logic that depends on legacy Xamarin logic.
=> [builds] Create Versions.plist/buildinfo for .NET independently of the legacy Xamarin versions.

src/intents.cs, src/scenekit.cs, tests/Makefile, tests/mtouch/MTouch.cs, tests/xharness/GitHub.cs, tests/xharness/Jenkins/ErrorKnowledgeBase.cs, tests/xharness/Jenkins/Reports/HtmlReportWriter.cs, tests/xharness/Jenkins/ResourceManager.cs, tests/xharness/Jenkins/TestSelector.cs, tests/xharness/Jenkins/TestTasks/BuildProject.cs, tests/xharness/MonoNativeInfo.cs, tests/xharness/Program.cs, tests/xharness/ProjectFileExtensions.cs, tests/xharness/Properties/AssemblyInfo.cs, tests/xharness/SimulatorLoaderFactory.cs, tests/xharness/Targets/Target.cs, tests/xharness/Targets/TodayExtensionTarget.cs, tests/xharness/Targets/WatchOSTarget.cs, tests/xharness/TestImporter/Platform.cs, tests/xharness/TestLabel.cs, tests/xharness/TestPlatformExtensions.cs, tests/xharness/TestProject.cs, tests/xharness/TestTargetExtensions.cs, tests/xharness/Xharness.Tests/Jenkins/JenkinsDeviceLoadterTests.cs, tests/xharness/Xharness.Tests/Tests/TestPlatformExtensionsTests.cs, tests/xharness/Xharness.Tests/Xharness.Tests.csproj, tests/xharness/xharness.csproj, tools/common/SdkVersions.cs, tools/common/SdkVersions.in.cs
* Convert xharness.csproj and Xharness.Tests.csproj to .NET/sdk-style projects.
* Fix numerous nullability issues that came up.
* Adjust Make logic to do the correct thing now that the executable is named differently.
* Port usage of WebClient to HttpClient, since WebClient is deprecated.
* Find an alternative solution to System.Web.MimeMapping.GetMimeMapping, which
doesn’t exist in .NET.
* Fix misc other warnings and errors.
=> [xharness] Convert to .NET.

tools/devops/automation/templates/build/api-diff-stage.yml, tools/devops/automation/templates/build/build-mac-tests-stage.yml, tools/devops/automation/templates/build/build-stage.yml, tools/devops/automation/templates/main-stage.yml
Following #19491 , this change moves the AgentPoolSelector to the Config stage since it is deterministic per build.
=> Centralize AgentPoolSelector

msbuild/Xamarin.MacDev.Tasks/Tasks/LinkNativeCodeTaskBase.cs, tests/dotnet/AppWithNativeDynamicLibrariesInPackageReference/MacCatalyst/Makefile, tests/dotnet/AppWithNativeDynamicLibrariesInPackageReference/macOS/Makefile, tests/dotnet/AppWithNativeDynamicLibrariesInPackageReference/shared.mk, tests/dotnet/UnitTests/ProjectTest.cs
We add the dylib location as an rpath if the app has any location, so make
sure to correctly detect dylibs in native references.
Fixes https://github.com/xamarin/xamarin-macios/issues/19520.
Backport of #19560
=> [release/8.0.1xx] [msbuild] Detect any dylibs in NativeReferences. Fixes #19520.

mk/xamarin.mk
Related new commits in xamarin/maccore:
* xamarin/maccore@39a7e52166 [mlaunch] Show all output from a failing devicectl command.
* xamarin/maccore@f29148cb58 [mlaunch] Add support for killing apps on device using devicectl. Fixes #xamarin/xamarin-macios@19577.
* xamarin/maccore@632997797a [mlaunch] Fix launching apps on device using a bundle id when using devicectl.
Diff: https://github.com/xamarin/maccore/compare/699ed5eaf2..39a7e52166
=> Bump mlaunch.

src/bgen/BindingTouch.cs, src/bgen/README.md, src/bgen/bgen.csproj
As soon as we moved to have a build of the generator that used dotnet we opened the door to a number of developer life improvements. The very first one of those is the poissibility to attach the dotnet debugger to the bgen process and that way be able to debug.
In order to do that, this PR has changed two small things:
1. Added code in the main method of the generator that will block the tool until a debugger is attached.
2. Changed the csproj to add the previously mentioned code only when the enviroment variable XAMMACIOS_DEBUGGER is set. This way the code does not reach our customers.
A README has been added explaining how to debug the processes via Visual Studio. Any other IDE that support the dotnet debugger can be used this way.
=> [Generator] Allow to have a way to attach to the generator.

tools/devops/automation/templates/main-stage.yml, tools/devops/automation/templates/release/vs-insertion-prep.yml
Once we move to the configure stage we have the situation in which we cannot longer have a simple condition to decide if we are preparing a released based in a single previos stage.
The issue we have is that templates cannot be used to create condition expressions and the expressions API from AZP does nor provide a map function (would have been ideal to do some mapping from the depends on object to an array).
The way we are going to fix the template is by taking a collection of stages we depend on, as we did, plus the name of the stage that builds the pacakges, that way we ensure that the condition will continue to work.
=> [CI] Ensure that the new dependencies are correcly managed.

msbuild/.gitignore, msbuild/Makefile, msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Tasks.csproj, msbuild/Xamarin.MacDev.Tasks/Tasks/XamarinTask.cs, msbuild/Xamarin.MacDev.Tasks/Xamarin.MacDev.Tasks.csproj, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Tasks.Windows.csproj, msbuild/Xamarin.iOS.Tasks/Xamarin.iOS.Tasks.csproj, tools/devops/automation/templates/tests/run-tests.yml
This is a step (among many) towards merging the iOS and Mac task assemblies
into a single assembly, which would simplify and speed up our build quite a
bit.
=> [msbuild] Use a single generated versions file for all platforms.

src/AppKit/NSGraphics.cs, tests/cecil-tests/BlittablePInvokes.KnownFailures.cs, tests/monotouch-test/AppKit/NSGraphics.cs
Also introduce a few other improvements:
* Add an varation that takes an 'out bool' instead of a 'ref bool'. According
to the documentation the value is out-only.
* Name this variation according to our guidelines (with a verb).
* Deprecate the old version.
Contributes towards https://github.com/xamarin/xamarin-macios/issues/15684.
=> [AppKit] Make NSGraphics.NSBestDepth P/Invoke blittable.

dotnet/targets/Xamarin.Shared.Sdk.props, dotnet/targets/Xamarin.Shared.Sdk.targets
This is useful to compute the path to the Mac's Xamarin SDK from Windows: we
can compute the relative path on Windows, and then just prepend the Mac's path
to .NET.
=> [dotnet] Compute the path to the Xamarin SDK root as a relative path to .NET's root directory.

.gitmodules
New commits in migueldeicaza/MonoTouch.Dialog:
* migueldeicaza/MonoTouch.Dialog@5898074 [MonoTouch.Dialog] Use 'BundledNETCoreAppTargetFrameworkVersion' in TargetFramework to avoid having to bump every year.
Removed commits from migueldeicaza/MonoTouch.Dialog:
* migueldeicaza/MonoTouch.Dialog@f500f9a Bump to .NET 8.
Diff: https://github.com/migueldeicaza/MonoTouch.Dialog/compare/f500f9a48dbf856c693b255078e1507cf1e8edde..5898074d6e62109c85e587977230c1a521cb9bb2
New commits in spouliot/Touch.Unit:
* spouliot/Touch.Unit@92a0726 [Touch.Client] Use 'BundledNETCoreAppTargetFrameworkVersion' in TargetFramework to avoid having to bump every year.
* spouliot/Touch.Unit@afbf9d4 [Touch.Client] Silence numerous warnings about using native API too early, where it's not supported, or when obsoleted.
* …
=> Bump Touch.Unit and MonoTouch.Dialog.

src/Foundation/NSArray_1.cs
NSArray<T>.FromNSObjects will never return a null object, because
NSArray.FromObjects won't (according to Apple's headers).
Fixes https://github.com/xamarin/xamarin-macios/issues/19622.
=> [Foundation] NSArray<T>.FromNSObjects will never return null objects. Fixes #19622.

src/bgen/Generator.cs, src/bgen/TypeManager.cs, tests/generator/BGenTests.cs, tests/generator/BGenTool.cs, tests/generator/issue19612.cs
This fixes a regression in .NET 8, where we changed the temporary assembly name when
building using a project file / MSBuild - we started compiling the temporary binding
code in MSBuild instead of in the generator, and in the process we changed the name
of the temporary assembly. This broke logic in bgen that compared the assembly name
to check if a given type is from the temporary assembly or not.
Fix this by checking the actual temporary assembly instead of the name of the assembly
instead.
Fixes https://github.com/xamarin/xamarin-macios/issues/19612.
Backport of #19619.
=> [release/8.0.1xx] [bgen] Fix assembly comparison. Fixes #19612.

src/ObjCRuntime/Runtime.cs
This will hopefully give more information for this random failure:
```
'System.InvalidCastException', reason: 'Arg_InvalidCastException (System.InvalidCastException)
at ObjCRuntime.Runtime.ConstructNSObject[NSDictionary](IntPtr , Type , MissingCtorResolution , IntPtr , RuntimeMethodHandle )
at ObjCRuntime.Runtime.GetNSObject[NSDictionary](IntPtr , IntPtr , RuntimeMethodHandle , Boolean )
at ObjCRuntime.Runtime.GetNSObject[NSDictionary](IntPtr , IntPtr , RuntimeMethodHandle )
at ObjCRuntime.Runtime.GetNSObject[NSDictionary](IntPtr )
at CoreFoundation.CFNotificationCenter.NotificationCallback(IntPtr centerPtr, IntPtr observer, IntPtr name, IntPtr obj, IntPtr userInfo)
```
Ref: https://github.com/xamarin/maccore/issues/2633
=> [ObjCRuntime] Throw a more descriptive InvalidCastException when failing to create an instance of the appropriate type in Runtime.CreateNSObject.

tests/xharness/Jenkins/NUnitTestTasksEnumerable.cs
It seems it's getting close to 5 minutes for slower bots, once in a while
hitting it, causing unnecessary test failures.
=> [xharness] Bump the timeout for the cecil tests.

tests/monotouch-test/Security/KeyChainTest.cs, tests/monotouch-test/Security/RecordTest.cs
* Try again if we get a DuplicateItem error in MonoTouchFixtures.Security.KeyChainTest.Add_Certificate, hopefully fixes this random test failure:
MonoTouchFixtures.Security.KeyChainTest
[FAIL] Add_Certificate :   Add_Certificate
Expected: Success
But was:  DuplicateItem
at MonoTouchFixtures.Security.KeyChainTest.Add_Certificate() in /Users/builder/azdo/_work/2/s/xamarin-macios/tests/monotouch-test/Security/KeyChainTest.cs:line 49
Ref: https://github.com/xamarin/maccore/issues/2394
* Use a unique account name in MonoTouchFixtures.Security.RecordTest.Protocol_17579, hopefully fixes this random test failure:
MonoTouchFixtures.Security.RecordTest
[FAIL] Protocol_17579 :   Add
Expected: Success
But was:  DuplicateItem
at MonoTouchFixtures.Security.RecordTest.Protocol(SecProtocol protocol) in …
=> [monotouch-test] Improve security tests a little bit.

tests/run-with-timeout.csharp
Improve the run-with-timeout script to trigger a crash report (by sending
SIGABRT to the target process before SIGKILL) if launch/execution times out.
This will hopefully help in diagnosing startup/execution hangs.
=> [tests] Improve the run-with-timeout script to trigger a crash report if launch/execution times out.

src/bgen/Generator.cs
Previously we used the presence of the [Protocolize] attribute to detect
Delegate properties returning protocols that should be specially handled if
the delegate in question supported events (in particular the Delegate property
would get additional code to ensure the developer didn't use both the event
pattern and the delegate pattern, because then one or the other wouldn't work
properly).
However, the presence of the [Protocolize] attribute does not take into
account that there's another way to declare that a Delegate property uses a
protocol: the property could use the protocol directly as the property type,
without a [Protocolize] attribute.
So change the logic to detect either the [Protocolize] attribute or an actual
protocol.
This is a slight breaking change in that we'll now add the …
=> [bgen] Adjust logic to handle protocol-backed events.

tests/EmbeddedResources/dotnet/shared.csproj, tests/bindings-test/dotnet/shared.csproj, tests/monotouch-test/dotnet/shared.csproj
This cuts down a lot of the warnings we get when building monotouch-test, in
particular the availability warnings, which we don't care about since these
are test projects.
=> [tests] Ignore numerous warnings in the EmbeddedResources, bindings-test and monotouch-test test projects.

src/Makefile.generator
The current logic to generate bgen.csproj.inc depends on having bgen.csproj in
the same directory; but in this case we want the bgen.csproj.inc in a
different directory (the temporary build directory).
Work around this by copying bgen.csproj to the temporary build directory.
=> [src] Fix generating bgen.csproj.inc.

tests/bindings-test/Messaging.cs, tests/common/TestRuntime.cs, tests/monotouch-test/AVFoundation/AVAudioFormatTest.cs, tests/monotouch-test/AudioUnit/AUParameterNodeTest.cs, tests/monotouch-test/CoreFoundation/DispatchBlockTests.cs, tests/monotouch-test/CoreFoundation/NetworkTest.cs, tests/monotouch-test/CoreGraphics/CGEventTests.cs, tests/monotouch-test/CoreVideo/CVDisplayLinkTest.cs, tests/monotouch-test/Foundation/CoderTest.cs, tests/monotouch-test/Foundation/NSDictionaryTest.cs, tests/monotouch-test/Foundation/NSMutableDictionaryTest.cs, tests/monotouch-test/Foundation/NSOperatingSystemVersionTest.cs, tests/monotouch-test/Foundation/NSTextListTest.cs, tests/monotouch-test/Foundation/UrlTest.cs, tests/monotouch-test/MetalPerformanceShaders/MnistTest.cs, tests/monotouch-test/Network/NWBrowserTest.cs, tests/monotouch-test/Network/NWPathMonitorTest.cs, tests/monotouch-test/ObjCRuntime/ClassTest.cs, tests/monotouch-test/ObjCRuntime/DisposableObjectTest.cs, tests/monotouch-test/ObjCRuntime/RuntimeTest.cs, tests/monotouch-test/SceneKit/SCNMatrixTest.cs, tests/monotouch-test/SceneKit/StructTest.cs, tests/monotouch-test/Security/CertificateTest.cs, tests/monotouch-test/SpriteKit/UniformTest.cs, tests/monotouch-test/System.Net.Http/MessageHandlers.cs, tests/monotouch-test/System.Net.Http/NetworkResources.cs
Fix a variety of compiler warnings:
* Unused variables.
* Nullability issues.
* Unreachable code.
* Duplicated using statements.
* Unnecessary 'async' modifiers.
* Ignored warnings when the code is correct as-is.
* Misc other issues.
=> [monotouch-test] Fix a variety of compiler warnings.

tools/devops/automation/templates/windows/stage.yml
The arm64 macs are the only ones configured to be used as remote macs.
=> [devops] Filter remote macs to arm64 macs

src/avfoundation.cs, src/bgen/AttributeManager.cs, src/bgen/Attributes.cs, src/bgen/Extensions/ExtensionMethods.cs, src/bgen/Generator.cs, src/bgen/Models/MemberInformation.cs
Remove support for the UnifiedInternal attribute from the generator, and remove
all usages of it in our api definitions - just use the Internal attribute.
The UnifiedInternal attribute was used to mark something as internal for
Unified Xamarin code, while still keeping it as public in Classic Xamarin
code.
Classic Xamarin has been dead for quite a few years ago now though, so there's
no need to keep his code around anymore.
=> [src] Remove the UnifiedInternal attribute.

src/CoreMidi/MidiServices.cs
It's inherently unsafe, because it may return a pointer to inside a managed
array - which points to random memory if the GC collects or moves the array.
So obsolete the property, and remove it for XAMCORE_5_0.
=> [CoreMidi] Obsolete the MidiPacket.Bytes property.

src/Makefile, src/Makefile.generator
Add a few platform-specific helper make targets to only build certain platforms.
Building everything can take a while, so being able to selectively choose
which platforms to build for during development can speed things up.
=> [src] Add a few helper make targets.

dotnet/targets/Xamarin.Shared.Sdk.targets
We're calling the _CreateAssetPackManifest target during the build for legacy
Xamarin apps, but somehow this seems to have been skipped over when
implementing .NET support.
The reason this has not showed up before is that it requires:
* OnDemand resources.
* An AdHoc provisioning profile (and a distribution certificate).
The last part makes it rather complicated to write a unit test, so this has
been verified manually.
Fixes https://github.com/xamarin/xamarin-macios/issues/19669.
=> [dotnet] Call the _CreateAssetPackManifest target during the build. Fixes #19669.

src/AudioToolbox/SystemSound.cs, tests/cecil-tests/BlittablePInvokes.KnownFailures.cs
=> [AudioToolbox] Make P/Invokes in SystemSound.cs have blittable signatures.

src/bgen/Generator.cs
This is a follow-up to 2bd23381e64494f4dbdcfcd71d161365d111a780: there was
some missing logic that caused nothing to be done for Delegate fields backed
by a protocol interface.
=> [bgen] Fix logic to handle protocol-backed events.

src/UIKit/UITraitChangeObservable.cs, src/UIKit/UITraitOverrides.cs, src/frameworks.sources, src/uikit.cs, tests/monotouch-test/UIKit/UITraitOverrides.cs, tests/xtro-sharpie/api-annotations-dotnet/iOS-UIKit.ignore, tests/xtro-sharpie/api-annotations-dotnet/tvOS-UIKit.ignore, tests/xtro-sharpie/iOS-UIKit.ignore, tests/xtro-sharpie/tvOS-UIKit.ignore
There are a few issues with the bindings, because the typedef `UITrait` in the headers is defined like this:
```objective-c
typedef Class<UITraitDefinition> UITrait
```
which means: "A Class that implements the UITraitDefinition protocol", and not "The UITraitDefinition" protocol", which is how it was bound.
This means the corresponding bindings are incorrect, so fix them. In some cases it's not possible to fix the API, so new ones had to be implemented in order to maintain backwards compatibility.
Fixes https://github.com/xamarin/xamarin-macios/issues/19410.
=> [UIKit] Fix broken UITrait bindings. Fixes #19410.

dotnet/targets/Xamarin.Shared.Sdk.targets
We're calling the _CreateAssetPackManifest target during the build for legacy
Xamarin apps, but somehow this seems to have been skipped over when
implementing .NET support.
The reason this has not showed up before is that it requires:
* OnDemand resources.
* An AdHoc provisioning profile (and a distribution certificate).
The last part makes it rather complicated to write a unit test, so this has
been verified manually.
Fixes https://github.com/xamarin/xamarin-macios/issues/19669.
Backport of #19681
=> [release/8.0.1xx] [dotnet] Call the _CreateAssetPackManifest target during the build. Fixes #19669.

src/appkit.cs
[NSFontDescriptor fontDescriptorWithDesign:] takes an NSString, not the enum
value, so use BindAs to bind correctly.
Fixes https://github.com/xamarin/xamarin-macios/issues/19659.
Backport of #19663
=> [release/8.0.1xx-xcode15.1] [AppKit] Fix binding for NSFontDescriptor.Create. Fixes #19659.

tests/common/DotNet.cs
This makes it much easier to understand what's happening when there's a failure to parse a binlog.
This happens rather frequently, these have all happened:
* Truncated binlogs because a build timed out.
* Binlog version is higher than expected.
* Bugs in the binlog reader.
* Bugs in the binlog writer.
=> [tests] Handle failures to parse a binlog and render a descriptive message.

src/CoreMidi/MidiServices.cs, tests/monotouch-test/CoreMidi/MidiClientTest.cs
Fix sending MidiPacket when MidiPacket has been created using a pointer to a byte[] rather than a byte[] passed as a reference.
MidiPacket.bytes is intiailized to a Array.Empty<byte> so it is never null, and so packet.BytePointer is never used.
We therefore need to check for ByteArray.Length being 0.
Midipacket.bytes is never 0 when intiailized to a 0 length byte[] as that constructor checked for 0 length byte[]
Backport of #18981
=> [release/8.0.1xx] Fix sending MidiPacket when MidiPacket has been created using a point.

msbuild/Xamarin.MacDev.Tasks/Tasks/ParseBundlerArgumentsTaskBase.cs, tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/ParseBundlerArgumentsTests.cs
The backslash character is pretty common on Windows (since it's a path separator),
but the argument parser will treat it as an escape character, and just skip it.
This is obviously wrong, so just replace backslashes with forward slashes, which
should work just as well on Windows, and will also be parsed correctly.
The downside is that now there's no way to escape characters, but that should be a
very rare problem (much rarer than backslash characters), and there are other
ways around the problem (set the actual target property instead of going through
the MtouchExtraArgs property for instance):
=> [msbuild] Handle backslash characters better on Windows in the ParseBundlerArguments task.

src/UIKit/UITraitChangeObservable.cs
> warning CS1587: XML comment is not placed on a valid language element
=> [src] Rearrange code to avoid compiler warning.

tools/mtouch/mtouch.csproj, tools/mtouch/packages.config
The packages in packages.config for mtouch don't seem be used anymore (the
localization process for mtouch doesn't use the xliff localization workflow
anymore), so just remove the file.
=> [mtouch] Remove packages.config, doesn't seem to be used anymore.

dotnet/Makefile
Fix 'make install-system' to use 'dotnet workload install' + a rollback file
instead of packages.
This actually works...
=> [dotnet] Fix 'make install-system' to use 'dotnet workload install' instead of packages.

builds/Makefile
This makes scripting easier in some cases.
=> [builds] Create a stable path to the local .NET version.

tests/dotnet/MyCatalystApp/MyCatalystApp.csproj
The default RuntimeIdentifier for Mac Catalyst is maccatalyst-arm64 if running
on an ARM64 machine, which is what our unit tests assume. Hardcoding the
RuntimeIdentifier in the project file prevents the default from being used,
and makes the unit tests fail when running on an ARM64 machine.
=> [tests] Use the default RuntimeIdentifier in MyCatalystApp

tests/cecil-tests/Helper.cs
Using Assert.IsEmpty generates a hideous error message that is not easy for a human to read. Instead of doing IsEmpty, we use the more elegant approach of create a Assert.Multiple wich does a much nicer job when printing the failures.
An full example of the difference can be found here:
https://gist.github.com/mandel-macaque/fd08a17067a3deb28d0bd10b67265628
A small example:
Old output
```
Cecil.Tests.ApiAvailabilityTest.AttributeConsistency(_build/Microsoft.MacCatalyst.Ref/ref/net8.0/Microsoft.MacCatalyst.dll): 2 API with inconsistent availability attributes:
[FAIL] AVFoundation.AVSampleBufferVideoRenderer.get_HasSufficientMediaDataForReliablePlaybackStart() is marked both supported and obsoleted in the same version (maccatalyst17.0)
[FAIL] System.Boolean …
```
=> [Tests] Make cecil test failures readable.

src/CoreMidi/MidiThruConnection.cs, src/ObjCRuntime/TransientCFString.cs, src/UIKit/UIApplication.cs, src/frameworks.sources, tests/cecil-tests/CecilExtensions.cs
In order to make it easier to pass C-style strings to P/Invokes, we introduced
a TransientString struct some time ago.
This works quite well, so I implemented the same for CFStrings - a
TransientCFString struct - and started using it in a few places. The idea
would be to slowly start migrating our codebase to this new pattern.
Instead of:
var ptr = CFString.CreateNative ("somestring");
try {
CallPInvoke (ptr);
} finally {
CFString.ReleaseNative (ptr);
}
we'll do:
using var ptr = new TransientCFString ("somestring");
CallPInvoke (ptr);
=> [src] Add a TransientCFString struct.

tests/cecil-tests/ApiAvailabilityTest.cs, tests/cecil-tests/Helper.cs
The ToString of a named tuple does not make sense for a human, this tests, while it does find issues with the API, it does not help the developer to find the real reason.
This PR has 2 important fixes.
1. Add a generic constrain to the Assert.Failures. The developer that wrote the code got lucky and always used T that are IComparable. I mean lucky, because the OrderBy from Linq needs T to be IComparable, and I am surprise we never got a rutime error with the test.
2. Use a record type with a reasonable ToString.
The following gist contains a diff between the output with the fix and without it.
https://gist.github.com/mandel-macaque/ee1adab1bf0568a6e95d47e7f3b7970a
The diff is:
New code:
```
AVFoundation.AVAudioSessionRouteSharingPolicy …
```
=> [Tests] Make the test FindMissingObsoleteAttributes usable.

tests/cecil-tests/MarshalAsTest.cs
As with others, make the results more readable, in this case we just need to re-use the already present method.
Diff in the ouputs can be found here:
https://gist.github.com/mandel-macaque/7015b2f9c7dfc857caa72f7c1ea19b0a
In this case we move to have the enumerated list.
=> [Tests] Move to use the Helpers method to report MarshalAsTest failures.

tests/cecil-tests/ApiAvailabilityTest.cs
Add a much nicer error message and reuse code. There is not need to add [Fail] at all in the messages.
Example of the changes: https://gist.github.com/mandel-macaque/255597f2390804a5a1c2675959b2f35c
=> [Tests] Reuse the Helper assert method for the consistency tests.

builds/Makefile
Use the .NET version (the `*_NUGET_VERSION` variables) instead of the
Xamarin.iOS/Xamarin.Mac versions (the `IOS_PACKAGE_VERSION` /
`MAC_PACKAGE_VERSION` variables) for the buildinfo file we put in our .NET
NuGets.
This also means we can share the same logic for all .NET platforms, instead of
having to special-case macOS.
Besides this being the correct value to put in the file (the Xamarin versions
have nothing to do with the .NET versions), it also decouples legacy logic
from .NET logic, which makes it easier to remove legacy logic when that time
comes.
=> [builds] Use .NET versions for the buildinfo file we put in .NET NuGets.

builds/Makefile, builds/Versions-MacCatalyst.plist.in, builds/Versions-iOS.plist.in, builds/Versions-macOS.plist.in, builds/Versions-tvOS.plist.in, dotnet/Makefile, dotnet/generate-target-platforms.csharp
In .NET the 4 platforms are 4 separate products, so it makes sense that each
Versions.plist only contains information for the corresponding platform.
This means we can share the same logic for all .NET platforms, instead of
having to special-case macOS.
It also decouples legacy logic from .NET logic, which makes it easier to
remove legacy logic when that time comes.
=> [builds] Create a separate Versions.plist.in for each .NET platform.

tools/devops/automation/templates/windows/build.yml
This prevents it from taking 16 hours if something goes wrong.
=> [devops] Add a 30-minute timeout for the .NET tests on Windows

tests/xharness/Jenkins/TestTasks/BuildProjectTask.cs, tests/xharness/Jenkins/TestTasks/MSBuildTask.cs
The main reason is that NuGet isn't safe to execute in parallel, so we need to
serially restore all projects, before they can be built in parallel.
This hopefully fixes a problem where the build would randomly fail because
NuGet would corrupt the packages folder when executed in parallel.
=> [xharness] Execute 'dotnet restore' before 'dotnet build'.

tests/Makefile, tools/devops/automation/templates/main-stage.yml
A few facts:
* We very rarely bump Mono (which is really the only time we should run the BCL tests).
* At the moment we're not shipping legacy Xamarin packages from main anymore.
* The BCL tests only apply to legacy Xamarin.
means that there's no need to run the BCL tests on every commit, we can just
run them manually *if* we happen to ever bump Mono again *and* we start
shipping legacy Xamarin packages from main again.
=> [tests] Disable the BCL tests by default.

tests/common/Configuration.cs, tests/dotnet/UnitTests/WindowsTest.cs
This makes it nicer to run 'dotnet test' on macOS, because we won't try to
(and fail to) run any Windows-specific tests.
=> [tests] Automatically ignore Windows tests on non-Windows platforms.

tests/dotnet/UnitTests/RegistrarTest.cs
This is because it doesn't work on arm64 - it's trying to verify that we
handle a specific error condition gracefully, but we're rather evil in trying
to trigger the error condition (being kind doesn't trigger the error), and the
AOT compiler detects the same thing we do and errors out before we get a
chance to show our nice error.
In short: make this an x64-only test.
=> [tests] Fix the InvalidStaticRegistrarValidation test to only run on x64.

tools/devops/automation/templates/main-stage.yml
Move the governance stage after the build to later be able to use APIScan.
=> [CI] Move governance tests after the build.

tools/devops/automation/templates/tests/run-tests.yml
This saves 3-5 minutes for every test run.
=> [devops] Don't download artifacts twice, once is enough.

tools/devops/automation/templates/windows/stage.yml
Remote tests on macOS should currently not take more than a couple of hours,
so adjust the timeout accordingly.
This avoids the CI waiting 16 hours before timing out if something goes wrong.
=> [devops] Adjust timeouts for remote testing on Macs.

src/foundation.cs, tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-Foundation.ignore, tests/xtro-sharpie/api-annotations-dotnet/common-Foundation.ignore, tests/xtro-sharpie/api-annotations-dotnet/macOS-Foundation.ignore, tests/xtro-sharpie/api-annotations-dotnet/tvOS-Foundation.ignore, tests/xtro-sharpie/common-Foundation.ignore, tests/xtro-sharpie/macOS-Foundation.ignore, tests/xtro-sharpie/tvOS-Foundation.ignore
Fixes https://github.com/xamarin/xamarin-macios/issues/19837.
=> [Foundation] Bind a few missing notifications. Fixes #19837.

src/AudioToolbox/AudioServices.cs, src/AudioToolbox/SystemSound.cs, tests/cecil-tests/BlittablePInvokes.KnownFailures.cs, tests/monotouch-test/AudioToolbox/SystemSoundTest.cs
=> [AudioToolbox] Make P/Invokes in AudioServices.cs have blittable signatures.

msbuild/Directory.Build.props, msbuild/Xamarin.MacDev.Tasks/MsBuildTasks/Copy.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/CompileSceneKitAssetsTaskBase.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/DittoTaskBase.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/SmartCopy.cs, msbuild/Xamarin.iOS.Tasks/Tasks/FindWatchOS2AppBundleTaskBase.cs
Changes:
- Updated Xamarin.Messaging to 1.13.8: bring fix for potential NullReferenceException in TaskRunner.FixReferencedItems: https://github.com/xamarin/Xamarin.Messaging/pull/694
- Updated MSBuild tasks that uses TaskRunner.FixReferencedItems from Xamarin.Messaging: update needed to match new Xamarin.Messaging API changes
=> [xma] Updated Xamarin.Messaging

tools/devops/automation/templates/build/build.yml
We are not seeing builds that take longer that 2 hours. Lets try to kill the build in those cases in which something out of the ordinaty happens like in https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8939582
=> [CI] Make the timeout to be closer to reality.

tools/devops/automation/templates/build/build.yml
We are not seeing builds that take longer that 2 hours. Lets try to kill the build in those cases in which something out of the ordinaty happens like in https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8939582
Backport of #19865
=> [release/8.0.1xx-xcode15.1] [CI] Make the timeout to be closer to reality.

tests/monotouch-test/Vision/VNGetCameraRelativePositionTest.cs, tools/mmp/Tuning.mmp.cs
Looks like this was substep was only added to mtouch, never to mmp, so let's fix that.
This also makes it possible to remove a test that was only there for the
linker to keep some required methods so that the test app would build
correctly.
Fixes https://github.com/xamarin/xamarin-macios/issues/19712.
=> [mmp] Add PreserveSmartEnumConversionsSubStep to the linker sub steps. Fixes #19712.

msbuild/Xamarin.MacDev.Tasks/MsBuildTasks/Copy.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/CompileSceneKitAssetsTaskBase.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/SmartCopyTaskBase.cs
Ensure the input properties that are meant to be fixed with the TaskRunner.FixReferencedItems invocation, might never be null
=> Avoid passing null to TaskRunner.FixReferencedItems

src/AudioToolbox/AudioSession.cs
=> [AudioToolbox] Make P/Invokes in AudioSession.cs have blittable signatures.

src/UIKit/UITraitChangeObservable.cs
The breaking change happened in fc0d09424e85fc30d2a88816b7c20b265e1f210f -
which was a fix to privatize APIss that weren't supposed to be public.
Unfortunately it's too late, because we've already released these APIs, so we
have to keep them public to preserve binary compatibility.
=> [UIKit] Fix breaking change in UITraitChangeObservable.

tests/monotouch-test/ObjCRuntime/TrampolineTest.cs
This reverts commit b0d8122eb749a5f6a63809ed4b3ef6afce70424e.
Fixes https://github.com/xamarin/xamarin-macios/issues/19653.
=> [net9.0] Revert "Ignore test triggering .NET regression."

builds/Versions-MacCatalyst.plist.in, builds/Versions-iOS.plist.in, builds/Versions-macOS.plist.in, builds/Versions-tvOS.plist.in, dotnet/generate-target-platforms.csharp, versions-check.csharp
The `SdkSupportedTargetPlatformVersion` item group is used for (at least) two things:
1. Generate the `_OR_GREATER` preprocessing symbols:
https://github.com/dotnet/sdk/blob/bfd2919bc446cad68d11de90cec4025d3683591c/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.BeforeCommon.targets#L230-L237
2. Validate the TargetPlatformVersion:
https://github.com/dotnet/sdk/blob/bfd2919bc446cad68d11de90cec4025d3683591c/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.TargetFrameworkInference.targets#L233-L246
The problem is that these two uses aren't equivalent.
Take for example the following scenario:
We release bindings for iOS 10, and a library developer takes advantage of the
bindings for the new iOS version, while at the same time supporting
multi-targeting to older …
=> [dotnet] Differentiate between "OS version we support as TargetPlatformVersion" and "OS version we support or have supported".

tools/devops/automation/templates/release/auth-feed.yml
The AzDo Task 'NuGet authenticate' version 0 (NuGetAuthenticate@0) is deprecated. This task will be removed. From January 31, 2024, onwards it may no longer be available.
=> Upgrade NuGetAuthenticate task to version 1

msbuild/Xamarin.MacDev.Tasks/MsBuildTasks/Copy.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/CompileSceneKitAssetsTaskBase.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/SmartCopyTaskBase.cs
Ensure the input properties that are meant to be fixed with the TaskRunner.FixReferencedItems invocation, might never be null
Backport of #19871.
=> [release/8.0.1xx-xcode15.1] Avoid passing null to TaskRunner.FixReferencedItems

tools/devops/automation/templates/windows/build.yml
The prefix goes in the container, not the file.
Backport of #19896
=> [release/8.0.1xx-xcode15.1] [CI] Use the prefix in the artifact name, not the file.

Make.config, dotnet/Makefile, dotnet/generate-workloadmanifest-json.csharp, eng/Version.Details.xml, eng/Versions.props, tests/dotnet/UnitTests/ProjectTest.cs
.NET 7 will be out of support by the time .NET 9 is released, so we can just
drop it already.
=> [net9.0] Drop support for .NET 7.

tools/devops/automation/templates/windows/build.yml
The prefix goes in the container, not the file.
=> [CI] Use the prefix in the artifact name, not the file.

Make.versions, dotnet/Makefile, dotnet/generate-target-platforms.csharp, dotnet/targets/Xamarin.Shared.Sdk.targets, tests/dotnet/UnitTests/ProjectTest.cs, tests/dotnet/UnitTests/TestBaseClass.cs
We've used to ignore the target platform version (the "17.0" part in "net8.0-ios17.0")
since our initial .NET relaese - customers could specify any valid OS version between
the minimum and maximum versions, and we'd completely ignore the value [1].
The purpose of the target platform version is to specify which bindings to choose:
"net8.0-ios17.0" would mean that the developer wants packages that have bindings
for iOS 17.0 (and earlier iOS versions, but not later iOS versions).
So saying "net8.0-ios11.0" would technically mean that the developer would want our
bindings for iOS 11.0 (and earlier iOS versions, but not later iOS versions). The
problem is that we don't ship any such thing... we shipped iOS 17.0 bindings in .NET
8, and that's it, you can't choose to build with something that …
=> [dotnet] Add warning when the TargetPlatformVersion isn't supported

msbuild/Xamarin.Shared/Xamarin.Shared.props
By default on macOS and MacCatalyst native symbols were never stripped.
However, as more customers are trying out NativeAOT deployment model with these platforms, the application bundle size started to be an important metric.
This PR enables native symbol stripping on macOS and MacCatalyst by default when using NativeAOT.
---
Fixes https://github.com/xamarin/xamarin-macios/issues/19864
=> NativeAOT: Enable native symbols stripping when targeting macOS with NativeAOT

msbuild/Xamarin.MacDev.Tasks/Tasks/DetectSigningIdentityTaskBase.cs, msbuild/Xamarin.Shared/Xamarin.Shared.targets, tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/DetectSigningIdentityTaskTests.cs
Take the CustomEntitlements item group into account in DetectSigningIdentity
when determining whether the app has entitlements (and would thus require a
provisioning profile).
=> [msbuild] Take the CustomEntitlements item group into account in DetectSigningIdentity.

dotnet/targets/Xamarin.Shared.Sdk.targets, tests/common/Configuration.cs, tests/dotnet/UnitTests/ProjectTest.cs, tests/mtouch/MTouch.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/19860.
Backport of #19900.
=> [release/8.0.1xx-xcode15.1] [dotnet] Fix typo causing universal builds to not keep any symbols when stripped. Fixes #19860.

msbuild/Xamarin.MacDev.Tasks/Tasks/DetectSigningIdentityTaskBase.cs, msbuild/Xamarin.Shared/Xamarin.Shared.targets, tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/DetectSigningIdentityTaskTests.cs
Take the CustomEntitlements item group into account in DetectSigningIdentity
when determining whether the app has entitlements (and would thus require a
provisioning profile).
Backport of #19919
=> [release/8.0.1xx-xcode15.1] [msbuild] Take the CustomEntitlements item group into account in DetectSigningIdentity.

tests/Makefile, tools/devops/automation/templates/main-stage.yml
A few facts:
* We very rarely bump Mono (which is really the only time we should run the BCL tests).
* At the moment we're not shipping legacy Xamarin packages from main anymore.
* The BCL tests only apply to legacy Xamarin.
means that there's no need to run the BCL tests on every commit, we can just
run them manually *if* we happen to ever bump Mono again *and* we start
shipping legacy Xamarin packages from main again.
Backport of #19802.
=> [release/8.0.1xx-xcode15.1] [tests] Disable the BCL tests by default.

msbuild/Xamarin.MacDev.Tasks/Tasks/CompileEntitlementsTaskBase.cs, tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/CompileEntitlementsTaskTests.cs
Otherwise custom entitlements won't end up in the archived entitlements (as
they should, just as if they were provided in an Entitlements.plist file).
=> [msbuild] Correctly add custom entitlements to the archived entitlements.

tests/common/DotNet.cs, tests/common/shared-dotnet.csproj, tests/dotnet/UnitTests/ProjectTest.cs, tests/dotnet/UnitTests/TestBaseClass.cs, tests/dotnet/UnitTests/WindowsTest.cs, tests/dotnet/Windows/collect-binlogs.sh, tools/devops/automation/scripts/MaciosCI.psd1, tools/devops/automation/scripts/RemoteMac.psm1, tools/devops/automation/scripts/fetch-remote-binlogs.ps1, tools/devops/automation/scripts/prepare-for-remote-tests.sh, tools/devops/automation/scripts/run-remote-windows-tests.ps1, tools/devops/automation/templates/windows/build.yml, tools/devops/automation/templates/windows/reserve-mac.yml, tools/devops/automation/templates/windows/stage.yml
Also add a single test that builds a simple project remotely.
This PR might be best reviewed commit-by-commit.
Fixes https://github.com/xamarin/xamarin-macios/issues/13924.
=> [tests] Add infrastructure to run tests on Windows that need a remote Mac. Fixes #13924.

msbuild/Messaging/Xamarin.Messaging.Build/Xamarin.Messaging.Build.csproj, msbuild/Xamarin.HotRestart.PreBuilt/Xamarin.PreBuilt.iOS/Xamarin.PreBuilt.iOS.csproj, msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Tasks.csproj, msbuild/Xamarin.MacDev.Tasks/Xamarin.MacDev.Tasks.csproj, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Tasks.Windows.csproj, msbuild/Xamarin.iOS.Tasks/Xamarin.iOS.Tasks.csproj
This is required to avoid GitInfo until these two PRs have been merged and
flowed to us:
* https://github.com/xamarin/XamarinVS/pull/14408
* https://github.com/xamarin/Xamarin.Messaging/pull/700
See also #19935.
=> [msbuild] Explicitly exclude any GitInfo package references we've pulled in.

msbuild/Makefile, msbuild/Messaging/Xamarin.Messaging.Build/BuildAgent.cs, msbuild/Messaging/Xamarin.Messaging.Build/Xamarin.Messaging.Build.csproj
* The calculation GitInfo does is horribly wrong for us - it seems to pick a
tag the most recent tag and parse it to pick out a version number:
* This means for any given release it'll use the previous tag - because we
don't necessarily tag until after the release build has been committed.
* It's not a stable version: a build is made (finding one tag), a new tag
is pushed, and if the same commit is built, it may find the new tag,
thus creating a new version number.
* We may have multiple tags for any given commit.
* The version calculation is also wrong: right now it finds the tag
`xamarin-ios-15.5.0.5-4407-gd45f4e90a6`, and comes up with the version
number 0.5.0.4407.
* I didn't investigate deeply, but GitInfo also touches .git/index and
.git/HEAD somehow, which causes us to rebuild …
=> [msbuild] Remove usage of GitInfo in Xamarin.Messaging.Build.

dotnet/targets/Xamarin.Shared.Sdk.targets, tests/common/Configuration.cs, tests/dotnet/UnitTests/ProjectTest.cs, tests/mtouch/MTouch.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/19860.
=> [dotnet] Fix typo causing universal builds to not keep any symbols when stripped. Fixes #19860.

msbuild/Xamarin.MacDev.Tasks/Tasks/CompileEntitlementsTaskBase.cs, tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/CompileEntitlementsTaskTests.cs
Otherwise custom entitlements won't end up in the archived entitlements (as
they should, just as if they were provided in an Entitlements.plist file).
Backport of #19920
=> [release/8.0.1xx-xcode15.1] [msbuild] Correctly add custom entitlements to the archived entitlements.

msbuild/Xamarin.MacDev.Tasks/Tasks/CompileEntitlementsTaskBase.cs, tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/CompileEntitlementsTaskTests.cs
We need to process custom entitlements just like if they came from an
Entitlements.plist file - which means replacing terms such as
`$(AppIdentifierPrefix)` and `$(TeamIdentifierPrefix)` with their correct value
depending on the provisioning profile.
Backport of #19942
=> [release/8.0.1xx-xcode15.1] [msbuild] Process custom entitlements as if they came from an Entitlements.plist file.

src/AudioToolbox/AudioConverter.cs, tests/monotouch-test/AudioToolbox/AudioConverterTest.cs
When resizing an array to a certain number of elements, we need to compute the
number of elements and use that to resize the array (and not use the size of
each element as the number of elements).
We also need to recompute the number of elements after calling the P/Invoke
(which may have changed the total size) - otherwise resizing the array is
entirely redundant (because the number of elements wouldn't change).
=> [AudioToolbox] Fix computing array size.

msbuild/Xamarin.MacDev.Tasks/Tasks/XamarinBuildTask.cs
* We don't need the .NET logo (nor any welcome messages), since this is
entirely done in the background.
* We don't need workload updates either.
=> [msbuild] Disable certain .NET behaviors we don't need when doing stuff on a remote Mac.

.github/workflows/backport-trigger.yml
Provide permission block to allow GITHUB_TOKEN access to continue working after 2024-02-01
Guidance: https://docs.opensource.microsoft.com/github/apps/permission-changes/
Not sure if any other GitHub action yaml files under .github/workflows also need to be updated
Backport of #19969
=> [release/8.0.1xx] GITHUB_TOKEN read-only change: Include permissions block

.github/workflows/backport-trigger.yml
Provide permission block to allow GITHUB_TOKEN access to continue working after 2024-02-01
Guidance: https://docs.opensource.microsoft.com/github/apps/permission-changes/
Not sure if any other GitHub action yaml files under .github/workflows also need to be updated
=> GITHUB_TOKEN read-only change: Include permissions block

.github/workflows/backport-trigger.yml
Provide permission block to allow GITHUB_TOKEN access to continue working after 2024-02-01
Guidance: https://docs.opensource.microsoft.com/github/apps/permission-changes/
Not sure if any other GitHub action yaml files under .github/workflows also need to be updated
Backport of #19969
=> [release/8.0.1xx-xcode15.1] GITHUB_TOKEN read-only change: Include permissions block

dotnet/Makefile
Fixes build error:
make: *** No rule to make target '../.git/HEAD', needed by `Workloads/Microsoft.NET.Sdk.iOS/WorkloadManifest.targets'.  Stop.
Refs:
https://github.com/xamarin/xamarin-macios/issues/18276
https://github.com/xamarin/xamarin-macios/pull/19240
=> [build] Fix worktree support

tests/dotnet/Windows/collect-binlogs.sh, tools/devops/automation/scripts/prepare-for-remote-tests.sh
This fixes an issue where the zip of all the binlogs we'd collect for the
Windows test run also contained all the binlogs from all other jobs completed
at that point (because they were downloaded as artifacts).
=> [devops] Don't collect (and re-upload) binlogs from artifacts we've downloaded from previous builds.

tests/common/Configuration.cs
The RootPath property would only look for the `.git` folder, not a `.git` file. Added additional logic to detect the `.git` file and that it contains a valid path. The return value is still the parent folder of the `.git` file or directory.
=> Enable `dotnet test` in worktree

src/HealthKit/HKAppleWalkingSteadiness.cs, tests/cecil-tests/BlittablePInvokes.KnownFailures.cs
Also fix a bug where we'd only return the error from
HKAppleWalkingSteadinessClassificationForQuantity if the P/Invoke _succeeded_
(in which case there wouldn't be an error of course). Instead always create an
NSError from the error output.
Contributes towards #15684.
=> [HealthKit] Make P/Invokes have blittable signatures.

msbuild/Xamarin.MacDev.Tasks/MsBuildTasks/Copy.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/CompileSceneKitAssetsTaskBase.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/SmartCopyTaskBase.cs
Ensure the input properties that are meant to be fixed with the TaskRunner.FixReferencedItems invocation, might never be null
Backport of #19871.
=> [release/7.0.3xx] Avoid passing null to TaskRunner.FixReferencedItems

tools/devops/automation/templates/windows/stage.yml
The location of the variable changed when the `configure` jobs were centralized into a single stage.
=> [release/8.0.1xx-xcode15.1] Fix windows integration tests condition

tests/dotnet/UnitTests/WindowsTest.cs
This is a test case for https://github.com/xamarin/xamarin-macios/issues/19278.
Ref: https://github.com/xamarin/xamarin-macios/issues/19926.
=> [tests] Add a test case for not modifying app after it's been signed.

dotnet/targets/Xamarin.Shared.Sdk.targets, msbuild/Xamarin.Shared/Xamarin.Shared.targets
Currently for universal apps we build the project once for each RuntimeIdentifier,
and each time we end up building any referenced projects as well.
It's not necessary to build referenced (library) projects on a per-RID basis, because
the RID isn't taken into account.
So optimize this:
1. Build project references in the containing build, before the RID-specific build.
This is accomplished by adding a dependency on the ResolveReferences target (which
also needs the BuildOnlySettings target to run first in order to actually build
any referenced projects).
2. Set "BuildProjectReferences=false" when running the RID-specific build, so
that any project references aren't built.
3. Also change how we override the BuildDependsOn property: we now have special
logic for library projects, where we …
=> [dotnet] Don't build library projects multiple times for universal apps.

msbuild/Xamarin.MacDev.Tasks/BundleResource.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/CollectBundleResources.cs
Fix nullability by allowing the method to take a null string. Return that a null string is an illegal name.
=> [MSBuild] Fix nullability that broke main.

.github/workflows/maestro-changelog.yml
Hopefully fixes a permission error:
response: {
Error: Unhandled error: HttpError: Resource not accessible by integration
url: 'https://api.github.com/repos/xamarin/xamarin-macios/issues/20075/comments',
=> [actions] Give pull-requests:write permissions to the changelog editor/creator.

.github/workflows/bump-global-json.yml
=> [release/7.0.3xx] [actions] Fix permissions for the global.json action after default credential change.

.github/workflows/bump-global-json.yml
=> [release/8.0.1xx-xcode15.1] [actions] Fix permissions for the global.json action after default credential change.

.github/workflows/maestro-changelog.yml
=> [release/8.0.1xx-xcode15.1] [actions] Fix permissions for the changelog action after default permissions change.

src/uikit.cs, tests/monotouch-test/UIKit/TextViewTest.cs
Apparently, in earlier versions of iOS, returning an empty dictionary from
UITextView.TypingAttributes would crash, so we added a workaround where we'd
return null instead of an empty dictionary.
However, I can't reproduce any such crashes anymore, and this workaround is
causing other problems, so remove it.
But do this in a backwards compatible way (just in case the removal ends up
crashing apps after all):
* Add a new TypingAttributes2 binding with the behavior we want (a better name
wouldn't be unwelcome!)
* Mark the existing TypingAttributes as obsolete, pointing to
TypingAttributes2.
* Make the TypingAttributes property behave as we want in XAMCORE_5_0, and at
that point  mark TypingAttributes2 as obsolete and point back to
TypingAttributes.
* Remove TypingAttributes2 in XAMCORE_6_0. …
=> [UIKit] Remove presnippet for UITextView.TypingAttributes. Fixes #12709.

Localize/loc/cs/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/de/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/es/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/fr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/it/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/ja/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/ko/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/pl/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/pt-BR/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/ru/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/tr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/zh-Hans/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, Localize/loc/zh-Hant/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl, msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.cs.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.de.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.es.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.fr.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.it.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ja.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ko.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pl.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pt-BR.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ru.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.tr.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hans.resx, msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hant.resx, msbuild/Xamarin.MacDev.Tasks/Tasks/AOTCompile.cs
While cyclic assembly references are unusual they are supported by the runtime and encountered in practice. In our project we use a version of Xamarin.Forms retargeted for a modern .NET (as a stopgap solution before an update to full MAUI stack). Xamarin.Forms historically come with such an assembly cycle: `Xamarin.Forms.Core.dll` -> `Xamarin.Forms.Platform.dll` -> `Xamarin.Forms.Platform.iOS.dll` -> `Xamarin.Forms.Core.dll`. This is produced by first compiling `Xamarin.Forms.Core.dll` against a dummy `Xamarin.Forms.Platform.dll` (`netstandard2.0` assembly). Then the Platform assemblies are built, and finally forwarder versions of `Xamarin.Forms.Platform.dll` are created for each platform. This is all packaged into NuGets in such a way that each TFM gets the same `Xamarin.Forms.Core.dll` …
=> Update AOTCompile task to handle cycles in up-to-date check

tools/devops/automation/templates/tests/publish-html.yml
The two removed parameters are never used and AFAIK env in the pwsh is overriding the global env of the job.
=> [CI] Fix the job that publishes the test results.

tools/devops/automation/templates/mac/build.yml
This tests are fast, they usually do not fail, but if they do is due to networking.
=> [CI] Retry running the mac tests on CI if they fail.

tools/devops/automation/templates/windows/build.yml
Sometimes we have some failures that are solved with a retry. They are not common and tests are fast so we can retry.
=> [CI] Allow to do a retry to run the windows integration tests.

tests/common/shared-dotnet.csproj, tests/dotnet/UnitTests/WindowsTest.cs
By default, the build will just continue if a remote connection couldn't be
established. For tests that require a remote connection, this often results in
weird errors later on in the build, so improve this by immediately verifying
that we were able to establish a remote connection and telling the developer
where to look for more information.
=> [tests] Verify that we have a remote connection in tests that require a remote connection.

tools/devops/automation/templates/windows/build.yml, tools/devops/automation/templates/windows/reenable-mac.yml, tools/devops/automation/templates/windows/stage.yml
Split the re-enabling of the macOS bot for the Windows tests to its own job,
so that we can stop running the tests job even if the reservation job failed.
=> [devops] Split the re-enabling of the macOS bot for Windows tests to its own job.

tests/dotnet/UnitTests/Extensions.cs
IsEmpty does not provide a formated way to see the errors and makes it really hard to parse the informaiton. Assert.Multiple is much nicer and a better way to get the data.
=> [Tests] Use Assert.Multiple over IsEmpty to get nicer output.

src/ObjCRuntime/Registrar.cs, src/ObjCRuntime/Stret.cs
Since watchOS is the only platform left supporting 32-bit CPUs.
=> [src] Remove any 32-bit logic not applicable to watchOS.

tests/dotnet/Windows/collect-binlogs.sh
Collect info to try to track down this random failure:
[...]
[xma][info]: Uploaded Build.zip 100%
[xma][info]: Successfully copied /tmp/Build-1.13.0.8-992eab55-04bf-44f3-b12d-df4b6ec5efb7/Build.zip
[xma][info]: Checking integrity of uploaded file /tmp/Build-1.13.0.8-992eab55-04bf-44f3-b12d-df4b6ec5efb7/Build.zip...
[xma][info]: Executing SSH command: '/usr/bin/shasum -a 256 "/tmp/Build-1.13.0.8-992eab55-04bf-44f3-b12d-df4b6ec5efb7/Build.zip" | awk "{ print $1 }"'
[xma][info]: Trying to copy to '/tmp/Build-1.13.0.8-992eab55-04bf-44f3-b12d-df4b6ec5efb7/Build.zip' to cache...
[xma][info]: Executing SSH command: 'mkdir -p "/Users/builder/Library/Caches/Xamarin/XMA/Cache"'
[xma][info]: Executing SSH command: 'cp -f "/tmp/Build-1.13.0.8-992eab55-04bf-44f3-b12d-df4b6ec5efb7/Build.zip" …
=> [tests] Collect info about installed XMA build agents to try to track down an installation failure.

dotnet/Makefile, dotnet/Microsoft.MacCatalyst.Sdk/Sdk/Sdk-eol.props, dotnet/Microsoft.MacCatalyst.Sdk/targets/Microsoft.MacCatalyst.Sdk.props, dotnet/Microsoft.iOS.Sdk/Sdk/Sdk-eol.props, dotnet/Microsoft.iOS.Sdk/targets/Microsoft.iOS.Sdk.props, dotnet/Microsoft.macOS.Sdk/Sdk/Sdk-eol.props, dotnet/Microsoft.macOS.Sdk/targets/Microsoft.macOS.Sdk.props, dotnet/Microsoft.tvOS.Sdk/Sdk/Sdk-eol.props, dotnet/Microsoft.tvOS.Sdk/targets/Microsoft.tvOS.Sdk.props, dotnet/generate-workloadmanifest-targets.csharp, dotnet/targets/Microsoft.Sdk.Eol.targets, tests/dotnet/UnitTests/ProjectTest.cs
If a project tried to use a .NET 6 project (say TargetFramework=net6.0-ios), then
we used to show these rather unhelpful errors:
error NETSDK1147: To build this project, the following workloads must be installed: wasm-tools-net6
error NETSDK1147: To install these workloads, run the following command: dotnet workload restore
The underlying problem is that we don't support .NET 6 anymore, so with this fix we now show:
error NETSDK1202: The workload 'net6.0-ios' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/maui-support-policy for more information about the support policy.
which is much more helpful.
References:
* https://github.com/dotnet/sdk/pull/32426
* https://github.com/xamarin/xamarin-android/pull/8047
Fixes …
=> [dotnet] Show a better error when using a .NET framework version we don't support.

tests/introspection/iOS/iOSApiCtorInitTest.cs
The Skip* overrides in introspection are of the type "Do we skip? If not, then
I don't know, and we should call base", but the implementation of
iOSApiCtorInitTest.SkipCheckShouldReExposeBaseCtor is wrong, it just says to
not skip for every type except the one the method knows about.
So adjust the logic to call base if
iOSApiCtorInitTest.SkipCheckShouldReExposeBaseCtor has no knowledge of the
type in question.
=> [introspection] Fix calling base in iOSApiCtorInitTest.SkipCheckShouldReExposeBaseCtor.

.github/policies/resourceManagement.yml
Currently a descriptive comment is automatically added to an issue when either
the 'need-info' or the 'need-repro' label is added to an issue, requesting
more info or a test project, respectively, and then when the reporter (or
anyone else) comments something, the `need-info`/`need-repro` label is removed
and a `need-attention` label is added.
However, sometimes this can get repetitive if the reporter replies frequently,
or someone else steps in and answers questions or asks unrelated questions,
and we have to add back the `need-info` or `need-repro` every time.
So add an opt-out: if the label `no-auto-reply` is set, then don't add that
descriptive comment.
The label is single-use: it'll be removed when a `need-info` or `need-repro`
labels is added.
=> [GitOps] Add an opt-out for automated comments for need-* labels.

src/CoreFoundation/CFWriteStream.cs, tests/xtro-sharpie/api-annotations-dotnet/common-CoreFoundation.ignore, tests/xtro-sharpie/common-CoreFoundation.ignore
Ref: https://github.com/xamarin/maccore/commit/aa13dcb506f1d18f7b167c10b1438af4eddec666
First line in the description is:
> Fixed CFWriteStream.DoGetProperty to call CFWriteStreamCopyProperty (and not CFReadStreamCopyProperty)
But that's not what the actual change does.. so change it to do the right thing.
=> [CoreFoundation] Fix CFWriteStream.DoGetProperty to actually get the property.

src/CoreFoundation/CFSocket.cs, tests/cecil-tests/BlittablePInvokes.KnownFailures.cs
=> [CoreFoundation] Make P/Invokes in CFSocket have blittable signatures.

Make.config, dotnet/Makefile, dotnet/generate-workloadmanifest-json.csharp, dotnet/generate-workloadmanifest-targets.csharp, dotnet/package/microsoft.ref.csproj, dotnet/package/microsoft.runtime.csproj, dotnet/package/microsoft.sdk.csproj, dotnet/targets/Microsoft.Sdk.DefaultItems.template.props, dotnet/targets/Microsoft.Sdk.Versions.template.props, dotnet/targets/Xamarin.Shared.Sdk.targets, release/Makefile, tools/apidiff/Makefile
This is the first step towards [multi-targeting support][1]. In order to
support multi-targeting, it must be possible to install several versions of
our packs simultaneously, and that also means that it becomes a lot easier to
visualize and work with the version we want to support if the packs were named
in a helpful way.
In particular, this PR changes the sdk, ref and runtime pack names to contain
the target framework + target platform version.
This will be the new names:
* iOS
* Microsoft.iOS.Sdk.net8.0_17.0
* Microsoft.iOS.Ref.net8.0_17.0
* Microsoft.iOS.Runtime.ios-arm64.net8.0_17.0
* Microsoft.iOS.Runtime.iossimulator-arm64.net8.0_17.0
* Microsoft.iOS.Runtime.iossimulator-x64.net8.0_17.0
* tvOS
* Microsoft.tvOS.Sdk.net8.0_17.0
* Microsoft.tvOS.Ref.net8.0_17.0
* …
=> [release/8.0.1xx-xcode15.0] [dotnet] Rename packs to contain target framework.

.github/policies/resourceManagement.yml
For any pull request with the 'community' label:
1. After 21 days of inactivity: give a warning that the pull request is out of date and will be closed.
2. After 28 days of inactivity: close the pull request.
Only check once a week (every Monday - there's no hurry here), so there may be
an additional 6 days until the inactivity workflow is triggered (if the last
action occurred on a Tuesday)
Unanswered question: I'm not sure if the first action will be considered as
some activity, in which case the second action will only happen in 21 + 28
days = 49 days. It doesn't really matter; the important part is that pull
requests are automatically closed after some time (and 49 days - even 55 days
- is still way better than now, which can be years).
=> [GitOps] Automatically close inactive community pull requests after 28 days.

src/CoreGraphics/CGFunction.cs, tests/cecil-tests/BlittablePInvokes.KnownFailures.cs
=> [CoreGraphics] Make P/Invokes in CGFunction have blittable signatures.

msbuild/Xamarin.MacDev.Tasks/Tasks/AOTCompile.cs
This particular condition shouldn't happen, but occasional build errors in the
wild (with exception stack traces) seem to indicate otherwise, so be a bit
defensive here.
=> [msbuild] Add a check for actually having anything to AOTCompile.

tests/cecil-tests/Documentation.cs, tests/cecil-tests/Helper.cs
Of course all our public APIs aren't documented, so there's a *huge* list
of known failures.
But at least this way we won't add more undocumented APIs by accident
(although new APIs will show up every time we add more bindings, in particular
in Xcode season).
=> [tests] Add test to verify that all our public APIs are documented.

dotnet/targets/Xamarin.Shared.Sdk.targets, msbuild/Xamarin.MacDev.Tasks/Tasks/Unzip.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/XamarinTask.cs
The extracted files show up in the build later on, and if only the 0-length
mirror file exists on Windows, it'll be copied as such to the Mac, producing
incorrect build results.
=> [msbuild] Copy extracted files from the DecompressXpcServices target back to Windows.

tests/Makefile, tests/bgen/Makefile, tests/cecil-tests/Makefile, tests/dotnet/Makefile, tests/dotnet/UnitTests/Makefile, tests/generator/Makefile, tests/mtouch/Makefile, tools/devops/automation/scripts/Makefile
I keep forgetting which makefile / test suite uses which run-* target, so just
make both work everywhere.
=> [tests] Make the 'run-tests' and 'run-unit-tests' targets equivalent.

tools/devops/automation/templates/governance/stage.yml
We have split the workloads in two pools:
1. VSEngSS-MicroBuild2022-1ES - Signing dedicated.
2. MAUI-1ESPT-Windows2022 - APIScan dedicated.
This allows to manage machines better and we could request better machines if needed for APIScan.
=> [CI] Use the APIScan dedicated pool.

tests/common/DotNet.cs
This makes it easier to find it on disk when something goes wrong.
=> [tests] Show the binlog we failed to parse.

tools/devops/automation/templates/tests/build.yml
We have sometimes issues with the network when trying to install the profiles, for example build https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9172524
We add a retry to that the tests do not fail due to a network issue.
=> [CI] Sometimes we have issues when installing the profiles.

msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx, msbuild/Xamarin.MacDev.Tasks/Tasks/Codesign.cs, msbuild/Xamarin.Shared/Xamarin.Shared.targets
We currently have an issue with codesigning duplicated files in parallel
(#20193). The proper fix is somewhat complex, so this implements a simple
workaround for customers, where they can just disable parallelism if they run
into this problem (and since it's simple, it's easier to backport too).
Additionally, it's not a bad idea to be able to configure the level of parallelism.
Ref: #20193.
=> [msbuild] Make the level of parallelism in the codesign task configureable.

dotnet/generate-workloadmanifest-targets.csharp, tests/dotnet/UnitTests/ProjectTest.cs
If a project tried to use a .NET 9 project (say TargetFramework=net9.0-ios), then
we used to show these rather unhelpful errors:
error NETSDK1147: The target platform identifier ios was not recognized.
The underlying problem is that we don't support .NET 9 yet, so with this fix we now show:
error NETSDK1202: The current .NET SDK does not support targeting .NET 9.0. Either target .NET 8.0 or lower, or use a version of the .NET SDK that supports .NET 9.0. Download the .NET SDK from https://aka.ms/dotnet/download
which is much more helpful.
This is accomplished by loading our workload even when using newer .NET
versions we don't support, because the .NET build logic will show the better
error later on.
=> [dotnet] Show a better error when using a .NET framework version we don't support yet.

src/audiounit.cs, src/coreaudiokit.cs, src/modelio.cs, src/scenekit.cs
> warning CS1587: XML comment is not placed on a valid language element
=> [src] Fix unintentional xml doc comment.

dotnet/Makefile, dotnet/targets/Microsoft.Sdk.DefaultItems.template.props
The build will load all the AutoImport.props files from all sdk packs (in our
AutoImport.props file we load the Microsoft.Sdk.DefaultItems.props file). This
file is supposed to include all the default items an sdk pack wants to include
by default, properly conditioned so that multiple versions of the sdk pack
don't end up including the same item more than once.
In the past, conditioning on the .NET version worked, because there would only
be one version of a sdk pack installed per .NET version. However this changed
with multi-targeting, now we can have numerous versions of an sdk pack
installed for every .NET version, which means the condition needs to be
updated, on all versions of the sdk pack.
This is already implemented for the `main` and `release/8.0.1xx-xcode15.0`
branches, but we …
=> [release/8.0.1xx-xcode15.1] Only load default items if the workload we loaded matches exactly.

tests/monotouch-test/System.Net.Http/MessageHandlers.cs
We've recently had a few test failures like this:
MonoTests.System.Net.Http.MessageHandlerTest.GHIssue16339
[FAIL] GHIssue16339() :   IsSuccessStatusCode #1
Expected: True
which doesn't provide much info into what went wrong.
It turns out this particular assert for IsSuccessStatusCode is redundant,
because we assert on the exact StatusCode a bit later, and if that assert
fails, we'll know a bit more.
So just remove this redundant assert for IsSuccessStatusCode.
=> [tests] Adjust MessageHandlerTest.GHIssue16339 slightly.

dotnet/targets/Xamarin.Shared.Sdk.targets, msbuild/Xamarin.MacDev.Tasks/Tasks/AOTCompile.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/Codesign.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/ScnTool.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/SymbolStrip.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/XamarinParallelTask.cs, msbuild/Xamarin.Shared/Xamarin.Shared.targets
This deduplicates some code, and also ensures we specifiy a max limit to the
level of parallelism. This fixes an issue in the AOTCompile and ScnTool tasks,
where we'd have no limit, launching as many subprocesses as tasks there are to
execute. In particular for the AOTCompile task, this can put a rather heavy
burden on build machines, slowing everything down to a crawl.
Fixes https://github.com/xamarin/xamarin-macios/issues/20210.
=> [msbuild] Make the level of parallelism configurable in all tasks that call Parallel.ForEach. Fixes #20210.

msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx, msbuild/Xamarin.MacDev.Tasks/Tasks/CodesignTaskBase.cs, msbuild/Xamarin.Shared/Xamarin.Shared.targets
We currently have an issue with codesigning duplicated files in parallel
(#20193). The proper fix is somewhat complex, so this implements a simple
workaround for customers, where they can just disable parallelism if they run
into this problem (and since it's simple, it's easier to backport too).
Additionally, it's not a bad idea to be able to configure the level of parallelism.
Ref: #20193.
Backport of #20242.
=> [release/8.0.1xx-xcode15.1] [msbuild] Make the level of parallelism in the codesign task configureable.

Make.config, mk/rules.mk, runtime/Makefile, tests/test-libraries/Makefile, tests/test-libraries/frameworks/Makefile, tests/test-libraries/libraries/Makefile
Once upon a time we needed to special case a higher min OS version that the
min OS version we supported for certain compiler/linker arguments, because we
used features not supported in the min OS version we supported.
That time has passed; in all cases our min OS version is now higher than the
special-cased min OS versions passed to native compilers/linkers, so we can
just use the actual min OS version we support.
=> [runtime] Fix min OS versions in various compiler and linker arguments.

src/CoreGraphics/CGColorSpace.cs
Per Apple docs for the `CGColorSpaceCreatePattern(CGColorSpaceRef baseSpace)`, the `baseSpace` _should_ be null when creating the color pattern. So, allow `null` here.
Fixes https://github.com/xamarin/xamarin-macios/issues/20293
=> Allow null for CGColorSpace.CreatePattern

tests/bgen/Makefile
Make it appropriately quiet, and pass the project.
This makes the run-tests target work when there's also a .sln in the same
directory (which gets created automatically when opening the project in
VSCode).
=> [tests] Improve running bgen tests from the terminal.

src/CoreGraphics/CGColorSpace.cs
Per Apple docs for the `CGColorSpaceCreatePattern(CGColorSpaceRef baseSpace)`, the `baseSpace` _should_ be null when creating the color pattern. So, allow `null` here.
Fixes https://github.com/xamarin/xamarin-macios/issues/20293
Backport of #20294
=> [release/8.0.1xx-xcode15.1] Allow null for CGColorSpace.CreatePattern

dotnet/targets/Xamarin.Shared.Sdk.targets, tests/bindings-test/ApiDefinition.cs, tests/bindings-test/RuntimeTest.cs, tests/test-libraries/libtest.m, tests/test-libraries/rename.h, tools/dotnet-linker/dotnet-linker.csproj
Fixes https://github.com/xamarin/xamarin-macios/issues/20061.
Backport of #20066
=> [release/8.0.1xx-xcode15.1] [dotnet-linker] Add ProcessExportedFields to the list of steps we execute. Fixes #20061.

runtime/runtime.m
The stack trace from unhandled exception is now:
Unhandled managed exception: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (System.ArgumentOutOfRangeException)
at System.Collections.Generic.List`1[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].get_Item(Int32 index)
at CrashiOS.RootViewController.GetItem() in /Users/rolf/test/bugs/StackTraceIssue/CrashiOS/RootViewController.cs:line 19
at CrashiOS.RootViewController.<.ctor>b__1_0(Object _, EventArgs _) in /Users/rolf/test/bugs/StackTraceIssue/CrashiOS/RootViewController.cs:line 12
at UIKit.UIBarButtonItem.Callback.Call(NSObject sender) in xamarin-macios/src/UIKit/UIBarButtonItem.cs:line 33
--- End of stack trace from …
=> [runtime] Fix conserving stack trace when re-throwing marshalled exceptions. Fixes #19417.

docs/configuration-properties.md, msbuild/Xamarin.Shared/Xamarin.Shared.props
Fixes https://github.com/xamarin/xamarin-macios/issues/20235
=> [msbuild] Disable stripping symbols by default for Debug builds

src/Foundation/NSUrlSessionHandler.cs
Calling [Try]SetResult on a default TaskCompletionSource will call any
continuations on the same thread.
This can lead to deadlocks (thus the hack to run TrySetResult in a background
thread), so avoid it by configuring the TaskCompletionSource to call
continutations asynchronously.
Ref: https://devblogs.microsoft.com/premier-developer/the-danger-of-taskcompletionsourcet-class/
=> [Foundation] Fix hack in NSUrlSessionHandler to avoid a deadlock.
