tests/Makefile, tests/cecil-tests/Documentation.cs, tests/common/Configuration.cs
Our tool to inject documentation for Apple APIs live in maccore, so if that
part of the build isn't enabled, we'll get a lot of false positives.
Instead just ignore the test if the Xamarin bits (in maccore) aren't enabled.
=> [tests] Ignore the VerifyEveryVisibleMemberIsDocumented test if the Xamarin bits aren't enabled.

src/Compression/Enums.cs
Also document all the members.
Fixes https://github.com/xamarin/xamarin-macios/issues/20319.
=> [Compression] Add missing enum members. Fixes #20319.

msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx, msbuild/Xamarin.MacDev.Tasks/Tasks/DetectSdkLocationCore.cs
Some people may use VSCode, or the command line, and talking about VS is confusing.
Fixes https://github.com/xamarin/xamarin-macios/issues/19818.
=> [msbuild] Adjust error message when we can't find Xcode to not talk about VS. Fixes #19818.

src/ObjCRuntime/Runtime.CoreCLR.cs, tests/dotnet/UnitTests/TrimmerWarningsTest.cs
=> [ObjCRuntime] Suppress trimmer warnings for certain Runtime members.

src/AVFoundation/AVSpeechSynthesizer.cs, src/avfoundation.cs, src/frameworks.sources
The callback may be called multiple times, which means the async version won't
work correctly.
So obsolete and hide the Async binding for now, and remove in XAMCORE_5_0.
References:
* https://discord.com/channels/732297728826277939/732297808148824115/1219903715939582022
* https://developer.apple.com/documentation/avfaudio/avspeechsynthesizer/3141659-writeutterance?language=objc
Fixes https://github.com/xamarin/xamarin-macios/issues/20338.
=> [AVFoundation] Obsolete AVSpeechSynthesizer.WriteUtteranceAsync. Fixes #20338.

docs/apple-privacy-manifest.md, docs/required-reasons-bcl.md, docs/required-reasons-dotnet-maui.md, docs/required-reasons-macios.md
From https://developer.apple.com/news/?id=3d8a9yyh
> Starting March 13: If you upload a new or updated app to App Store Connect that uses an API requiring approved reasons, we'll will send you an email letting you know if you’re missing reasons in your app’s privacy manifest. This is in addition to the existing notification in App Store Connect.
> 
> Starting May 1: You’ll need to include approved reasons for the listed APIs used by your app’s code to upload a new or updated app to App Store Connect. If you’re not using an API for an allowed reason, please find an alternative. And if you add a new third-party SDK that’s on the list of commonly used third-party SDKs, these API, privacy manifest, and signature requirements will apply to that SDK. Make sure to use a version of the SDK that …
=> Add documentation on how to provide the Apple Privacy Manifest

src/ObjCRuntime/DynamicRegistrar.cs, tests/dotnet/UnitTests/TrimmerWarningsTest.cs
=> [ObjCRuntime] Suppress trimmer warnings for certain DynamicRegistrar members.

msbuild/Xamarin.MacDev.Tasks/Tasks/CompileAppManifest.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/ReadAppManifest.cs, tools/common/Application.cs
Error messages aren't meant to be an exercise in mental capacity, so make
things easier for developers to figure out which versions are valid and which
are not by sorting them.
So instead of this:
Valid Mac Catalyst versions are: 15.0, 13.3.1, 16.2, 14.3, 15.5, 13.1, 16.0, 17.2, 14.1, 15.3, 16.5, 14.6, 13.4, 17.0, 16.3, 15.6, 13.2, 14.4, 16.1, 14.2, 15.4, 16.6, 13.5, 14.7, 17.1, 15.2, 14.0, 16.4, 13.3, 14.5
We now get:
Valid Mac Catalyst versions are: 13.1, 13.2, 13.3, 13.3.1, 13.4, 13.5, 14.0, 14.1, 14.2, 14.3, 14.4, 14.5, 14.6, 14.7, 15.0, 15.2, 15.3, 15.4, 15.5, 15.6, 16.0, 16.1, 16.2, 16.3, 16.4, 16.5, 16.6, 17.0, 17.1, 17.2
=> [tools] Sort list of versions before showing them in an error message.

src/ObjCRuntime/Blocks.cs, tests/dotnet/UnitTests/TrimmerWarningsTest.cs
* Extract code the trimmer wants to warn about into a separate method.
* Suppress the trimmer warning we get.
Contributes towards #10405.
=> [ObjCRuntime] Refactor the Block.SetupBlock(Delegate,Delegate) implementation a bit.

tools/devops/automation/templates/mac/stage.yml
16.6666 hours is *way* too much.
=> [devops] There's no reason for the macOS tests to take more than two hours, so adjust timeout accordingly.

src/bgen/Models/MarshalTypeList.cs
Fixes this warning:
The type AudioToolbox.AudioBuffers does not have a constructor that takes two (ObjCRuntime.NativeHandle, bool) arguments but a constructor that takes two (System.IntPtr, bool) parameters was found (and will be used instead). It's highly recommended to change the signature of the (System.IntPtr, bool) constructor to be (ObjCRuntime.NativeHandle, bool).
which comes from here:
at ObjCRuntime.Runtime.GetIntPtr_BoolConstructor(Type type) in xamarin-macios/src/ObjCRuntime/Runtime.cs:line 1754
at ObjCRuntime.Runtime.ConstructINativeObject[AudioBuffers](IntPtr ptr, Boolean owns, Type type, MissingCtorResolution missingCtorResolution, IntPtr sel, RuntimeMethodHandle method_handle) in xamarin-macios/src/ObjCRuntime/Runtime.cs:line 1607
at …
=> [bgen] Provide correct initialization for AudioBuffers.

src/AppKit/NSEvent.cs, src/appkit.cs, tests/monotouch-test/AppKit/NSEvent.cs
Create a better binding for `[NSEvent eventWithGCEvent:]` by binding it as
`NSEvent.Create(CGEvent)` instead of `NSEvent.EventWithGCEvent(IntPtr)`.
Partial fix for https://github.com/xamarin/xamarin-macios/issues/12650.
=> [AppKit] Create a better binding for [NSEvent eventWithGCEvent:].

src/CoreGraphics/CGEvent.cs, tests/monotouch-test/CoreGraphics/CGEventTests.cs, tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-CoreGraphics.ignore, tests/xtro-sharpie/api-annotations-dotnet/macOS-CoreGraphics.ignore, tests/xtro-sharpie/macOS-CoreGraphics.ignore
Also deprecate CGEventPostToPSN in documentation, but not formally using
attributes, because Apple only documented the deprecation of CGEventPostToPSN
in a header comment, and not their API documentation, nor using attributes.
=> [CoreGraphics] Bind CGEventPostToPid.

msbuild/Xamarin.MacDev.Tasks/Tasks/ACTool.cs
This fixes an issue where we'd compute a LogicalName property that was outside
of the app bundle, resulting in broken resources in the app bundle (in
particular the app icon would be missing).
So instead of something like this:
LogicalName: ../../../../../../../../../tmp/testapp/obj/Debug/net8.0-ios/iossimulator-arm64/actool/bundle/Assets.car
we'll now get:
LogicalName: Assets.car
and the icons will be correctly embedded in the app bundle.
Fixes https://github.com/xamarin/xamarin-macios/issues/20330.
=> [msbuild] Use the fully resolved path when computing the relative path for the LogicalName property. Fixes #20330.

src/appkit.cs
EventArgs does nothing in a category method, so this is effectively removing dead code.
=> [src] Remove EventArgs attribute on a category method.

src/ObjCRuntime/Runtime.cs
There's no change in behavior, because string.Equals(string,string) already does ordinal comparison, but:
* "Use overloads that explicitly specify the string comparison rules for string operations.""
* "Use an overload of the String.Equals method to test whether two strings are equal."
Ref: https://learn.microsoft.com/en-us/dotnet/standard/base-types/best-practices-strings
=> [ObjCRuntime] Fix string comparison to be ordinal.

msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx, msbuild/Xamarin.MacDev.Tasks/Tasks/FindItemWithLogicalName.cs
I've seen multiple cases of the following error:
>  A bundle identifier is required. Either add an 'ApplicationId' property in the project file, or add a 'CFBundleIdentifier' entry in the project's Info.plist file.
In all cases this has been been because the build fails to find Info.plist,
when it's actually there.
One source of this problem was found and fixed with #20374, but that's not the
problem in other scenarios.
So I'm adding a bit more diagnostic output to the FindItemWithLogicalName
task, to try to track down why the task fails to find `Info.plist`.
=> [msbuild] Add more diagnostic output to FindItemWithLogicalName.

dotnet/targets/Microsoft.Sdk.DefaultItems.template.props
The 'MSBuild::MakeRelative' path takes the current directory into account.
Given the following example:
$([MSBuild]::MakeRelative('/Users/rolf/testproject/','Info.plist'))
returns:
1. `/Info.plist` if the current directory is the root directory (`/`).
2. `Info.plist` otherwise.
This is a problem, because we specifically look for "Info.plist" during the
build, and if we don't find it, we may end up with this error:
> A bundle identifier is required. Either add an 'ApplicationId' property in the project file, or add a 'CFBundleIdentifier' entry in the project's Info.plist file.
The fix is to instead of use the relative `Info.plist` path in the call to
`[MSBuild]::MakeRelative`, use the full path instead:
$([MSBuild]::MakeRelative('/Users/rolf/testproject/','/Users/rolf/testproject/Info.plist …
=> [dotnet] Compute relative paths using absolute paths.

src/coremidi.cs
These delegates are never used in the api definitions, and thus they're not
copied to the generated code. This means that their removal will not change
any public APIs.
=> [CoreMidi] Remove unused delegates.

src/AVFoundation/AVAudioSourceNode.cs, src/AVFoundation/AVCompat.cs, src/avfoundation.cs, src/bgen/Generator.cs, src/frameworks.sources, tests/monotouch-test/AVFoundation/AVAudioSourceNodeTest.cs
The signature of the callback provided when creating AVAudioSourceNode instances
was wrong, so the callback would get corrupted data, causing crashes.
Fix the callback to have the right signature (not too difficult), and also make the
existing signature work (a bit more complicated).
Note that this is the second time we've tried to fix the delegate signature for the
AVAudioSourceNode callbacks, but now with tests, so hoping there won't be a third
time.
Fixes https://github.com/xamarin/xamarin-macios/issues/19868.
=> [AVFoundation] Fix delegate signature for AVAudioSourceNode callbacks.

src/CoreGraphics/CGEvent.cs, tests/xtro-sharpie/api-annotations-dotnet/macOS-CoreGraphics.ignore
* Bind CGEventTapCreateForPid.
* Remove an obsolete CGEvent.CreateTap overload from XAMCORE_5_0.
* Unify/deduplicate code to keep track of taps.
* Make TapData disposable to not depend on the GC to come around.
* Add API documentation.
=> [CoreGraphics] Bind CGEventTapCreateForPid and misc other improvements.

dotnet/targets/Xamarin.Shared.Sdk.targets
It seems we might not always link with the Security framework by default, so
link with it explicitly.
Fixes https://github.com/xamarin/xamarin-macios/issues/20406.
=> [dotnet] Automatically link with the Security framework. Fixes #20406.

tests/cecil-tests/Documentation.cs
There's no way to add xml documentation to them.
=> [tests] Don't verify that the 'value__' enum fields have xml documentation.

tests/cecil-tests/Documentation.cs
There's no way to add xml documentation to them.
=> [tests] Don't verify that delegate members have xml documentation.

src/CoreGraphics/CGEvent.cs, src/CoreGraphics/CGEventTypes.cs, src/frameworks.sources, tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-CoreGraphics.ignore, tests/xtro-sharpie/api-annotations-dotnet/macOS-CoreGraphics.ignore, tests/xtro-sharpie/macOS-CoreGraphics.ignore
Also expose both getter and setter methods using the enum itself, so we don't
have to make getter and setter properties for each of the enum fields.
This required making CGEventField a public enum, so do that.
And finally document all the new APIs, and some of the old ones.
Fixes https://github.com/xamarin/xamarin-macios/issues/12650.
=> [CoreGraphics] Bind CGEventSetIntegerValueField and CGEventSetDoubleValueField. Fixes #12650.

tests/monotouch-test/System.Net.Http/MessageHandlers.cs
MonoTests.System.Net.Http.MessageHandlerTest.GHIssue16339
[FAIL] GHIssue16339() :   ReasonPhrase #1
Expected string length 2 but was 11. Strings differ at index 0.
Expected: "OK"
But was:  "Bad Gateway"
=> [tests] Ignore the MessageHandlerTest.GHIssue16339 test if we're in CI and have a bad network.

src/Makefile
We have a minor behavioral difference between bgen and csc:
* In bgen, `--warnaserror:` enables all warnings.
* In csc, `--warnaserror:` does nothing.
So we now pass:
* `--warnaserror:` to bgen.
* `--warnaserror+` to csc.
=> [src] Fix making all warnings errors.

src/bgen/BindingTouch.cs, src/bgen/Generator.cs, tests/generator/BGenTests.cs
This was mostly copied from the existing API documentation.
=> [bgen] Generate xml documentation for the generated ClassHandle property.

Make.config
To reduce reliance on xamjenkinsartifact.
Also remove MIN_XM_MONO_URL, it is not used anymore.
=> Use Mono MDK package from download server

dotnet/targets/Xamarin.Shared.Sdk.props, dotnet/targets/Xamarin.Shared.Sdk.targets, msbuild/Xamarin.Shared/Xamarin.Shared.targets
We can determine whether we're building for the simulator or not as soon as we know
the RuntimeIdentifier, so do that, and set _SdkIsSimulator accordingly.
In legacy Xamarin we had to execute a target in order to compute _SdkIsSimulator
(_DetectSdkLocations), but with this change we won't have to in .NET anymore, which
makes it possible to simplify some logic.
The first thing we do here is to also move the computation of the trimmer configuration
to right after computing _SdkIsSimulator (because we only need to know three things
to compute the default trimmer mode: the target platform + whether we're building
for the simulator or not + the configuration, and those are all known at this point
now).
This will make it possible to stop suppressing trimmer warnings depending on the
trimming …
=> [dotnet] Compute _SdkIsSimulator and the trimmer configuration earlier in the build.

tools/devops/automation/templates/common/checkout.yml
It shouldn't take more than a few minutes to undo the GitHub merge.
=> [devops] Add a timeout to the 'undo GitHub merge' step.

tests/dotnet/Windows/collect-binlogs.sh, tools/devops/automation/scripts/clean-for-remote-tests.sh
Also collect more logs to help diagnose any transient failures.
=> [devops] Terminate any existing builders and brokers when preparing Macs for remote testing.

Make.config
To reduce reliance on xamjenkinsartifact.
Also remove MIN_XM_MONO_URL, it is not used anymore.
Backport of #20442.
=> [release/8.0.1xx-xcode15.1] Use Mono MDK package from download server

Make.config
To reduce reliance on xamjenkinsartifact.\r
Also remove MIN_XM_MONO_URL, it is not used anymore.
Backport of #20442.
=> [release/7.0.3xx] Use Mono MDK package from download server

Make.config
To reduce reliance on xamjenkinsartifact.
Also remove MIN_XM_MONO_URL, it is not used anymore.
Backport of #20442.
=> [release/8.0.1xx-xcode15.0] Use Mono MDK package from download server

dotnet/targets/Xamarin.Shared.Sdk.targets
By adding the 'LinkWithSwiftSystemLibraries=true' property in a project file, we'll
now add the location of Swift's system libraries to the linker arguments.
Fixes https://github.com/xamarin/xamarin-macios/issues/18848.
=> [dotnet] Add support for linking with Swift system libraries. Fixes #18848.

msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx, src/Resources.Designer.cs, src/Resources.resx, tests/mtouch/MTouch.cs, tests/mtouch/RegistrarTest.cs, tools/mtouch/Errors.designer.cs, tools/mtouch/Errors.resx
Stop using the term 'Xamarin' in our error messages.
🙈 🙊 🙉
Note: this may not be complete, since we compute error messages in numerous
places, and those aren't fixed here (if there are any that still says
'Xamarin' in any way).
=> [docs] Stop using the term 'Xamarin'.

tests/cecil-tests/Documentation.cs
We have enough APIs to document to think about documenting APIs people
shouldn't be using.
=> [tests] Don't verify that obsolete or hidden members have xml documentation.

tools/dotnet-linker/Makefile
Makes diagnosing build issues much easier.
=> [tools] Create a binlog when building dotnet-linker.

src/GameplayKit/GKHybridStrategist.cs, src/ObjCRuntime/ObsoleteConstants.cs, src/frameworks.sources, src/gameplaykit.cs, tests/introspection/ApiCtorInitTest.cs, tests/introspection/ApiProtocolTest.cs, tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-GameplayKit.ignore, tests/xtro-sharpie/api-annotations-dotnet/iOS-GameplayKit.ignore, tests/xtro-sharpie/api-annotations-dotnet/tvOS-GameplayKit.ignore, tests/xtro-sharpie/iOS-GameplayKit.ignore, tests/xtro-sharpie/tvOS-GameplayKit.ignore
The GKHybridStrategist type doesn't exist in iOS. This was probably a type
initially introduced in a beta version, and then removed in a later beta
version, and then we didn't notice.
=> [GameplayKit] Remove the bindings for GKHybridStrategist.

tools/common/PathUtils.cs
Fixes:
xamarin-macios/tools/common/PathUtils.cs(297,34): warning CA1416: This call site is reachable on all platforms. 'RegistryKey.GetValue(string?, object?)' is only supported on: 'windows'. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)
xamarin-macios/tools/common/PathUtils.cs(294,32): warning CA1416: This call site is reachable on all platforms. 'RegistryKey.OpenSubKey(string)' is only supported on: 'windows'. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)
xamarin-macios/tools/common/PathUtils.cs(294,32): warning CA1416: This call site is reachable on all platforms. 'Registry.LocalMachine' is only supported on: 'windows'. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)
=> [tools] Add OS check to fix availability warnings.

tools/devops/automation/publish-pr-html-results.yml, tools/devops/automation/templates/variables.yml, tools/devops/automation/vs-insertion.yml
Replace the manually updated PAT `$(pat--xamarinc--build-access)` with the built in `$(System.AccessToken)`.
This PR is untested but from the documentation I have read it should work for requesting anything within the same DevOps tenant and project aka DevDiv.
- [Predefined variables - Azure Pipelines | Microsoft Learn](https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
- [Understand job access tokens - Azure Pipelines | Microsoft Learn](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/access-tokens?view=azure-devops&tabs=yaml#job-authorization-scope)
=> Update to use System.AccessToken

dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalyst/csharp/MacCatalystApp1.csproj, dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalystbinding/csharp/MacCatalystBinding1.csproj, dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalystlib/csharp/MacCatalystLib1.csproj, dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/iOSTabbedApp1.csproj, dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/iOSApp1.csproj, dotnet/Templates/Microsoft.iOS.Templates/iosbinding/csharp/iOSBinding1.csproj, dotnet/Templates/Microsoft.iOS.Templates/ioslib/csharp/iOSLib1.csproj, dotnet/Templates/Microsoft.macOS.Templates/macos/csharp/macOSApp1.csproj, dotnet/Templates/Microsoft.macOS.Templates/macosbinding/csharp/macOSBinding1.csproj, dotnet/Templates/Microsoft.macOS.Templates/macoslib/csharp/macOSLib1.csproj, dotnet/Templates/Microsoft.tvOS.Templates/tvos/csharp/tvOSApp1.csproj, dotnet/Templates/Microsoft.tvOS.Templates/tvosbinding/csharp/tvOSBinding1.csproj, dotnet/Templates/Microsoft.tvOS.Templates/tvoslib/csharp/tvOSLib1.csproj, dotnet/targets/Xamarin.Shared.Sdk.props, dotnet/targets/Xamarin.Shared.Sdk.targets
As we have solved all trimming warnings in the our workloads, we can now go
all in on trimming.
Early in .NET 6 we hid many trimming warnings as we did not yet plan to solve
them:
<SuppressTrimAnalysisWarnings Condition=" '$(SuppressTrimAnalysisWarnings)' == '' ">true</SuppressTrimAnalysisWarnings>
Ref: https://github.com/xamarin/xamarin-macios/issues/10405
These warnings were not *actionable* at the time for customers, as
many warnings were from our code.
Going forward, let's stop suppressing these warnings if `TrimMode=full`.
We can also enable trimming for new projects:
* `dotnet new ios|tvos|macos|maccatalyst`
These will have the `TrimMode` property set to `Full` by default for `Release`
builds:
```xml
<PropertyGroup Condition="'$(Configuration)' == 'Release'"> …
```
=> [dotnet] Embrace trimming.

tools/devops/automation/publish-pr-html-results.yml, tools/devops/automation/templates/variables.yml, tools/devops/automation/vs-insertion.yml
Reverts xamarin/xamarin-macios#20476
Usage of `System.AccessToken` in this instance fails with `needs Edit build quality permissions`.
=> Revert "Update to use System.AccessToken"

dotnet/Makefile
Make sure Microsoft.\<platform\>.Sdk.DefaultItems.props is rebuilt if the
current hash changes.
This fixes a local rebuild issue, where we'd rebuild
Microsoft.\<platform\>.Sdk.Versions.props, but not
Microsoft.\<platform\>.Sdk.DefaultItems.props.
A build failure like this would thus result:
tools/msbuild/iOS/Xamarin.Shared.targets(606,3): error : A bundle identifier is required. Either add an 'ApplicationId' property in the project file, or add a 'CFBundleIdentifier' entry in the project's Info.plist file.
because:
* We store the current git hash in both of the files mentioned above.
* We only include default items in a build if the git hashes match.
* Since the files weren't both rebuilt, they'd contain different hashes, and
thus we wouldn't include Info.plist in the build, leading to …
=> [dotnet] Fix dependencies for Microsoft.<platform>.Sdk.DefaultItems.props.

dotnet/targets/Xamarin.Shared.Sdk.targets
It seems we might not always link with the Security framework by default, so
link with it explicitly.
Fixes https://github.com/xamarin/xamarin-macios/issues/20406.
Backport of #20413
=> [release/8.0.1xx-xcode15.1] [dotnet] Automatically link with the Security framework. Fixes #20406.

docs/website/generator-errors.md
Note that this document is currently not published on our documentation web site.
* Consolidate on a single way to specify message arguments (* instead of {...}).
* Mark messages that will only be show in legacy as such (but keep them)
* Escape star characters in headers.
* Remove mentions of Xamarin.
* Misc other updates.
=> [docs] Review and update the 'Binding errors' document.

src/Resources.Designer.cs, src/Resources.resx, src/bgen/Attributes.cs, src/bgen/Enums.cs, src/bgen/Generator.cs, tests/generator/BGenTests.cs, tests/generator/ErrorTests.cs, tests/generator/tests/errordomain-nolibraryname.cs, tests/generator/tests/errordomain.cs
The generator needs a library name for the generated `_domain` field.
Here's an example for the generated `ARErrorCodeExtensions` class ("ARKit" is
the library name):
```cs
[Field ("ARErrorDomain", "ARKit")]
static NSString? _domain;
```
In order to find the library name, the generator would look at the first enum
field with a `[Field]` attribute, and get the `LibraryName` property from that
`[Field]` attribute. Unfortunately error enums don't necessarily have `[Field]`
attributes on their enum fields. This works fine for our own bindings, because
the generator will fall back to the enum's namespace, but for third-party
bindings this would be the result:
> error BI1042: bgen: Missing '[Field (LibraryName=value)]' for ErrorDomainNS.EWithDomain. (e.g."__Internal")
Note that the error …
=> [bgen] Fix support for ErrorDomain enums in third-party bindings.

src/AVFoundation/AVEdgeWidths.cs, src/AVFoundation/AVTypes.cs, src/Accelerate/vImageTypes.cs, src/AppKit/Defs.cs, src/AudioToolbox/AudioFormat.cs, src/AudioToolbox/AudioQueue.cs, src/AudioToolbox/MusicTrack.cs, src/AudioUnit/AudioUnit.cs, src/CoreAnimation/CATransform3D.cs, src/CoreGraphics/CGVector.cs, src/CoreMotion/CMMagnetometer.cs, src/CoreMotion/Defs.cs, src/Foundation/NSDecimal.cs, src/Foundation/NSOperatingSystemVersion.cs, src/MapKit/MapKit.cs, src/Metal/Defs.cs, src/ModelIO/MDLStructs.cs, src/UIKit/UIScrollView.cs, src/UIKit/UITypes.cs, src/UIKit/UIView.cs, src/XKit/Types.cs
This is in preparation for XML documentation: in order to provide XML
documentation for each field, they need to be separate statements.
=> [src] Expand multi-field single statements into multiple statements.

tools/devops/automation/templates/tests/stage.yml
Waiting 16.6 hours for a test run to time out if something goes wrong is way too long.
=> [devops] Each test run shouldn't take more than a couple of hours, so set 3h as the upper bound.

dotnet/generate-workloadmanifest-json.csharp, dotnet/generate-workloadmanifest-targets.csharp
The latest .NET 8 stable release doesn't support multi targeting yet, so we
need to use pre-multi-targeting pack names to make VS insertions work
correctly.
=> [release/9.0.1xx-preview4] [dotnet] Rename the dependency of the latest .NET 8 packs to match the latest .NET 8 stable release.

eng/Version.Details.xml, eng/Versions.props
Changes: https://github.com/xamarin/xamarin-macios/compare/492e53f5b423c6e9cbdb48f3d57c92a1f97b5005...06fea905cf900ab5296b08d7b67dadddc733dd65
Changes: https://github.com/xamarin/xamarin-macios/compare/3c6e720de354facc6f9e36d54f6f7363639a4a48...cf27e95d7d0428aac83c9dcc9dc591aab4aa30f7
Bumps to the the latest version of release/8.0.1xx-xcode15.0, and the version of release/8.0.1xx-xcode15.1 currently in VS main.
=> Bump .NET 8 dependencies for .NET 9 Preview 4

eng/Version.Details.xml, eng/Versions.props
Changes: https://github.com/xamarin/xamarin-macios/compare/492e53f5b423c6e9cbdb48f3d57c92a1f97b5005...06fea905cf900ab5296b08d7b67dadddc733dd65
Changes: https://github.com/xamarin/xamarin-macios/compare/3c6e720de354facc6f9e36d54f6f7363639a4a48...cf27e95d7d0428aac83c9dcc9dc591aab4aa30f7
Bumps to the the latest version of release/8.0.1xx-xcode15.0, and the version of release/8.0.1xx-xcode15.1 currently in VS main.
Backport of #20519.
=> [release/9.0.1xx-preview4] Bump .NET 8 dependencies for .NET 9 Preview 4

src/OpenGL/CGLPixelFormat.cs, src/OpenGLES/EAGLContext.cs, tests/cecil-tests/BlittablePInvokes.KnownFailures.cs
=> [OpenGL/OpenGLES] Make P/Invokes have blittable signatures.

src/bgen/Generator.cs, tests/generator/ExpectedXmlDocs.MacCatalyst.xml, tests/generator/ExpectedXmlDocs.iOS.legacy.xml, tests/generator/ExpectedXmlDocs.iOS.xml, tests/generator/ExpectedXmlDocs.macOS.legacy.xml, tests/generator/ExpectedXmlDocs.macOS.xml, tests/generator/ExpectedXmlDocs.tvOS.legacy.xml, tests/generator/ExpectedXmlDocs.tvOS.xml, tests/generator/tests/xmldocs.cs
This was mostly copied from the existing API documentation.
=> [bgen] Generate xml documentation for generated default constructors.

Make.config
=> [release/9.0.1xx-preview4] Use legacy mono-sdks from download.mono-project.com

src/GLKit/Defs.cs, tests/cecil-tests/BlittablePInvokes.KnownFailures.cs
This was complicated a bit because it uses a non-blittable struct we can't
change because it's public API. So introduce an internal temporary blittable
struct.
Contributes towards #15684.
=> [GLKit] Make the GLKVertexAttributeParametersFromModelIO P/Invoke have a blittable signature.

tools/devops/automation/templates/build/build.yml
It doesn't look like we need it anymore, and in any case it fails to install on ARM64:
> ##[error]Download URL for .Net Core sdk version 5.0.408 could not be found for the following OS platforms (rid): osx-arm64,osx-arm64
From: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9486716&view=logs&jobId=2ad83a99-f770-5ec5-96c6-63e16b4bb697&j=2ad83a99-f770-5ec5-96c6-63e16b4bb697&t=5c4dfcb8-6d0a-532a-9705-12b94c390bf5
=> [devops] Remove installation of .NET 5.

tools/devops/automation/run-post-ci-build-tests.yml, tools/devops/automation/run-post-pr-build-tests.yml, tools/devops/automation/templates/mac/stage.yml, tools/devops/automation/templates/tests-stage.yml, tools/devops/automation/templates/tests/publish-results.yml, tools/devops/automation/templates/tests/stage.yml, tools/devops/automation/templates/windows/stage.yml
1Es is problematic and has a lot of issues on how we use the matrix strategies. We have two options, either wait for 1ES to implement the needed changes or move all the tests out to two different pipelines that won't need to be 1ES complient.
In the long run moving out of the build piepline is going to give us more flexibility and will move the project away from depending on a thridparty to fix the yaml issues.
Even when landing this PR we will not have the tests removed, we will do that after we have been able to test that things work as expected.
=> [CI] Split tests to a post-build pipeline.

tools/devops/automation/templates/tests/run-tests.yml
If the script to install powershell is executed with Rosetta, this happens:
$ arch -x86_64 brew install powershell
Warning: Not upgrading powershell, the latest version is already installed
Error: Cannot install under Rosetta 2 in ARM default prefix (/opt/homebrew)!
To rerun under ARM use:
arch -arm64 brew install ...
To install under x86_64, install Homebrew into /usr/local.
which can be seen on the bots:
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9496253&view=logs&j=1acdac53-199e-5330-5c52-bf5d9d7be24b&t=ca94b18d-fa43-5a35-82db-a681bd2b1a78.
So escape Rosetta when installing powershell.
Backport of #20530.
=> [release/9.0.1xx-preview4] [devops] Escape Rosetta when installing powershell.

msbuild/Xamarin.MacDev.Tasks/Tasks/ComputeRemoteGeneratorProperties.cs
If the project in question needs a custom NuGet.config, this NuGet.config file
will be in a base directory of where the .NET executable is located. I'm not
certain what the current directory is when executing `dotnet` in this task, so
make it explicit in case it's a different path.
This in particular might affect us for remote tests using .NET previews:
/Users/builder/Library/Caches/Xamarin/mtbs/builds/bindingsframeworktest/8b36a8b30efab69178e7774426ff34b9aded7e20a789eb18f485be2f81a2dccd/obj/Debug/net9.0-ios/ComputeRemoteGeneratorProperties/ComputeRemoteGeneratorProperties.csproj : error NU1102: Unable to find package Microsoft.NET.ILLink.Tasks with version (>= 9.0.0-preview.4.24223.11)
/Users/builder/Library/Caches/Xamarin/mtbs/builds/bindingsframeworktest/8b36a8b30efab69178e7774426ff34b9 …
=> [msbuild] Set the working directory before executing 'dotnet build' in the ComputeRemoteGeneratorProperties task.

tools/devops/automation/build-pipeline.yml, tools/devops/automation/build-pull-request.yml, tools/devops/automation/templates/pipelines/build-pipeline.yml
Make the live of the mantianers better by using inheritance for the build pipelines. This later will make the move to the 1ES template easier since we refactored the yaml of the pipelines to be as small as possible.
=> [CI] Simplify the split of the pipelines via extensions

runtime/shared.m, src/ObjCRuntime/Blocks.cs
We're using two different functions to atomically decrement a reference count,
the native `atomic_fetch_sub` and the managed `Interlocked.Decrement`.
Unfortunately the return value is not the same: `atomic_fetch_sub` returns the
original value before the subtraction, while `Interlocked.Decrement` returns
the subtracted value, while our code assumed the functions behaved the same.
This resulted in a memory leak, because we'd incorrectly expect `0` to be
returned from `atomic_fetch_sub` when the reference count reaches zero, and
thus not detect when the descriptor a block should be freed.
The fix is to update the expected return value from `atomic_fetch_sub` to be
`1` instead of `0`.
Fixes https://github.com/xamarin/xamarin-macios/issues/20503.
=> [runtime] Fix memory leak with BlockLiteral descriptors. Fixes #20503.

tools/devops/automation/scripts/bash/clean-simulator-runtime.sh
Attempt to fix simulator runtimes disappearing by:
* Detaching all the currently loaded runtimes.
* Killing the simdiskimaged and CoreSimulatorService services.
Hopefully this will make the simdiskimaged service restart, and reload the
simulator runtimes.
=> [devops] Attempt to fix simulator runtimes disappearing.

msbuild/Xamarin.Shared/Xamarin.Shared.targets
This looks like an incorrect merge conflict resolution: the property
_UnpackLibraryResourcesDependsOn was declared twice, the second time
overwriting the first.
Pick the first declaration, since it's the newest and more complete one
(70a5d0d09ab).
=> [msbuild] Fix duplicated property declaration.

src/bgen/Generator.cs, tests/generator/ExpectedXmlDocs.MacCatalyst.xml, tests/generator/ExpectedXmlDocs.iOS.legacy.xml, tests/generator/ExpectedXmlDocs.iOS.xml, tests/generator/ExpectedXmlDocs.macOS.legacy.xml, tests/generator/ExpectedXmlDocs.macOS.xml, tests/generator/ExpectedXmlDocs.tvOS.legacy.xml, tests/generator/ExpectedXmlDocs.tvOS.xml
This was mostly copied from the existing API documentation.
=> [bgen] Generate xml documentation for the extension class we generate for protocols.

src/AudioUnit/AudioComponentDescription.cs, tests/cecil-tests/BlittablePInvokes.KnownFailures.cs
This makes any P/Invokes that uses this struct have a blittable signature.
Contributes towards #15684.
=> [AudioUnit] Remove unnecessary MarshalAs attributes from the AudioComponentDescription struct.

tools/devops/automation/scripts/bash/clean-simulator-runtime.sh
Attempt to fix simulator runtimes disappearing by:
* Detaching all the currently loaded runtimes.
* Killing the simdiskimaged and CoreSimulatorService services.
Hopefully this will make the simdiskimaged service restart, and reload the
simulator runtimes.
Backport of #20559.
=> [release/8.0.1xx-xcode15.0] [devops] Attempt to fix simulator runtimes disappearing.

dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalyst/visualbasic/SceneDelegate.vb, dotnet/Templates/Microsoft.iOS.Templates/ios/visualbasic/SceneDelegate.vb
VB doesn't support default interface members, and will show an error for all
unimplemented interface members, even if they have a default implementation.
This is a problem for the VB templates, because they make use of protocol
interfaces, which will soon have interface members with default
implementations.
In order to get around this, change the VB templates to use the model class
instead of the protocol interfaces.
=> [dotnet] Make the VB templates compile use models instead of protocol interfaces.

src/Foundation/NSUrlSessionHandler.cs
Use 'Foundation' as the namespace for NSUrlSessionHandler for all platforms
(so that we have the same API across all platforms).
But only in XAMCORE_5_0, since this is a breaking change.
=> [Foundation] Use 'Foundation' as the namespace for NSUrlSessionHandler for all platforms.

tests/monotouch-test/ObjCRuntime/EveryFrameworkSmokeTest.cs, tests/monotouch-test/Security/SecureTransportTest.cs
We've recently started using more and more ARM64 bots, so these tests are
failing in those cases.
Fixes:
MonoTouchFixtures.Security.SecureTransportTest
[FAIL] SslSupportedCiphers :   3224092716
Expected: True
at MonoTouchFixtures.Security.SecureTransportTest.SslSupportedCiphers () [0x000de] in <f08bd76ea2204d929c96e3bd36ae955a>:0
Xamarin.Mac.Tests.EveryFrameworkSmokeTests
[FAIL] ExpectedLibrariesAreLoaded : QTKitLibrary (/System/Library/Frameworks/QTKit.framework/QTKit) failed to load but this was not expected
at Xamarin.Mac.Tests.EveryFrameworkSmokeTests.ExpectedLibrariesAreLoaded () [0x000e6] in <f08bd76ea2204d929c96e3bd36ae955a>:0
=> [tests] Fix misc ARM64 issues when running legacy Xamarin tests.

msbuild/Xamarin.MacDev.Tasks/Tasks/ResolveNativeReferences.cs
The code incorrectly assumed that the contents of a compressed xcframework would
always be a framework, but this is incorrect (it can be a dynamic library (.dylib),
static library (.a) or a framework (.framework).
Fix this by:
* Change variable and parameter names to clearly indicate that the output from
an xcframework is a native library.
* Unify code to handle metadata for native libraries from xcframeworks, so that
the code isn't duplicated (or even worse, different) between compressed and non-compressed
xcframeworks.
The latter point fixes a problem where we'd compute the incorrect path to the static
library inside a compressed xcframework.
PR #20546 contains a test case that triggers this.
=> [msbuild] Fix issue referencing static libraries from compressed xcframeworks.

Makefile, tools/devops/automation/scripts/TestResults.Tests.ps1, tools/devops/automation/scripts/TestResults.psm1
Currently we get a message saying all the tests failed catastrophically.
Example: https://github.com/xamarin/xamarin-macios/pull/20434#issuecomment-2100258803
This is both confusing and scary, so change the comment to say that the build
failed instead.
=> [devops] Improve GitHub comment when the build fails.

tools/devops/automation/templates/build/build.yml
It doesn't look like we need it anymore, and in any case it fails to install on ARM64:
> ##[error]Download URL for .Net Core sdk version 5.0.408 could not be found for the following OS platforms (rid): osx-arm64,osx-arm64
From: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9486716&view=logs&jobId=2ad83a99-f770-5ec5-96c6-63e16b4bb697&j=2ad83a99-f770-5ec5-96c6-63e16b4bb697&t=5c4dfcb8-6d0a-532a-9705-12b94c390bf5
Backport of #20527.
=> [release/9.0.1xx-preview4] [devops] Remove installation of .NET 5.

tools/devops/automation/templates/build/api-diff-process-results.yml
The API diff command fials due to the fact that it creates the comment file inside sources, by moving the file to the artifacts staging directory we fix the problem and ensure that the comment is removed after each build.
Ps: I also fixed all the indentation issues in the file that were reported by yamllint.
=> [CI] Fix the API diff failing

tools/devops/automation/scripts/bash/clean-simulator-runtime.sh
Attempt to fix simulator runtimes disappearing by:
* Detaching all the currently loaded runtimes.
* Killing the simdiskimaged and CoreSimulatorService services.
Hopefully this will make the simdiskimaged service restart, and reload the
simulator runtimes.
Backport of #20559.
=> [release/8.0.1xx-xcode15.1] [devops] Attempt to fix simulator runtimes disappearing.

msbuild/Xamarin.MacDev.Tasks/Tasks/ResolveNativeReferences.cs, msbuild/Xamarin.Shared/Xamarin.Shared.ObjCBinding.targets, msbuild/Xamarin.Shared/Xamarin.Shared.targets, tests/bindings-framework-test/dotnet/shared.csproj, tests/bindings-xcframework-test/dotnet/shared.csproj
A `*.framework/` native reference and a `*.framework` reference are the same
thing, so treat them the same. We accomplish this by removing any trailing
path separators (both windows style and non-windows-style for consistency)
before doing any processing.
Fixes https://github.com/xamarin/xamarin-macios/issues/15430.
=> [tests] Ignore trailing slashes in NativeReference items. Fixes #15430.

Make.config, eng/Version.Details.xml, eng/Versions.props, global.json
dotnet/installer is no longer producing a `Microsoft.Dotnet.Sdk.Internal`
"package" for the SDK, which we're using to get the .NET version to provision
.NET.
So use `VS.Tools.Net.Core.SDK.Resolver` instead, as this is a component
inserted into Visual Studio that contains the same version number.
We may have to change this again in the future, as dotnet/installer is in the
process of merging and/or moving to dotnet/sdk.
Ref:
* https://github.com/xamarin/xamarin-android/pull/8949
* [MS Teams thread](https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1715789991637?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1715789991637&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Respon …
=> [net9.0] [maestro] Depend on 'VS.Tools.Net.Core.SDK.Resolver' instead of 'Microsoft.Dotnet.Sdk.Internal'.

.github/policies/resourceManagement.yml
Also stop mentioning VSMac.
Ref: https://github.com/dotnet/maui/pull/22152
=> [GitOps] Tell people using VSCode what to do when the move-to-vs-feedback label is applied.

tests/common/shared-dotnet.csproj
There's no target named `SayHello`, the correct name is `_SayHello` (where we
establish a connection to the remote mac).
=> [tests] Correctly run the VerifyRemoteConnection target.

tools/devops/automation/scripts/bash/export-mono-filenames.sh
API diff currently fails with:
** Error: Working directory isn't clean:
HEAD detached at origin/pull/20587/head
Untracked files:
(use "git add <file>..." to include in what will be committed)
tmp.txt
So clean up after ourselves in a previous step to avoid this.
=> [devops] Clean up temporary files to fix api diff.

runtime/shared.m, src/ObjCRuntime/Blocks.cs
We're using two different functions to atomically decrement a reference count,
the native `atomic_fetch_sub` and the managed `Interlocked.Decrement`.
Unfortunately the return value is not the same: `atomic_fetch_sub` returns the
original value before the subtraction, while `Interlocked.Decrement` returns
the subtracted value, while our code assumed the functions behaved the same.
This resulted in a memory leak, because we'd incorrectly expect `0` to be
returned from `atomic_fetch_sub` when the reference count reaches zero, and
thus not detect when the descriptor a block should be freed.
The fix is to update the expected return value from `atomic_fetch_sub` to be
`1` instead of `0`.
Fixes https://github.com/xamarin/xamarin-macios/issues/20503.
Backport of #20556.
=> [release/8.0.1xx-xcode15.1] [runtime] Fix memory leak with BlockLiteral descriptors. Fixes #20503.

tools/devops/automation/templates/build/api-diff-process-results.yml
Fixes this failure:
> 🔥 Unable to find the contents for the comment: D:\a\1\a\change-detection\results\gh-comment.md does not exist :fire
This is a partial revert of #20601, which broke the API diff.
=> [devops] Look in the correct directory for the API diff results.

tests/cecil-tests/Documentation.cs
So instead of this:
> Cecil.Tests.Documentation+AssemblyApi: Documented API not found in the platform assembly. This probably indicates that the code to compute the doc name for a given member is incorrect.
we'll get:
> T:Foundation.SomeType: Documented API not found in the platform assembly. This probably indicates that the code to compute the doc name for a given member is incorrect.
=> [cecil-tests] Fix assertion message to use the doc id instead of the typename of a tuple.

src/ObjCRuntime/Blocks.cs, tools/mtouch/Errors.designer.cs, tools/mtouch/Errors.resx
The validation verifies that the function pointer for a block callback is the
same the return value from the method's
MethodInfo.MethodHandle.GetFunctionPointer() method.
In actual code, it's equivalent to validating that the following always prints "Equal: true":
```cs
[UnmanagedCallersOnly]
public static void Invoke () {}
static void Test ()
{
delegate* unmanaged<void> fptr1 = &Invoke;
IntPtr fptr2 = GetType ().GetMethod ("Invoke").MethodHandle.GetFunctionPointer ();
Console.WriteLine ($"fptr1: 0x{((IntPtr) fptr1).ToString ("x")}");
Console.WriteLine ($"fptr2: 0x{fptr2.ToString ("x")}");
Console.WriteLine ($"Equal: ((IntPtr) fptr1) == fptr2}"); // prints "Equal: true" for me
}
```
However, this isn't documented, and some feedback indicates it's certainly not
a valid assumption for …
=> [Blocks] Remove a block callback validation that's apparently too eager.

runtime/runtime.m, runtime/trampolines.m, tests/bindings-test/ApiDefinition.cs, tests/bindings-test/RuntimeTest.cs, tests/bindings-test/dotnet/shared.csproj, tests/common/TestRuntime.RunAsync.cs, tests/test-libraries/libSwiftTest.swift
Fixes https://github.com/xamarin/xamarin-macios/issues/18562.
=> [runtime] Add support for additional type encodings. Fixes #18562.

src/AudioUnit/AUGraph.cs, tests/cecil-tests/BlittablePInvokes.KnownFailures.cs
=> [AudioUnit] Make P/Invokes in AUGraph.cs have blittable signatures.

msbuild/Messaging/Xamarin.Messaging.Build/Xamarin.Messaging.Build.csproj, msbuild/Xamarin.Localization.MSBuild/Properties/AssemblyInfo.cs, msbuild/Xamarin.Localization.MSBuild/Xamarin.Localization.MSBuild.csproj, msbuild/Xamarin.MacDev.Tasks/Xamarin.MacDev.Tasks.csproj, tools/devops/automation/templates/build/api-diff-process-results.yml
Version the Xamarin.Localization.MSBuild assembly correctly (instead of
hardcoding a 1.0.0 version - implicitly so because no version was set), so
that we can load multiple versions of the assembly into the same process.
Fixes https://github.com/xamarin/xamarin-macios/issues/20062.
=> [msbuild] Version the Xamarin.Localization.MSBuild assembly. Fixes #20062.

src/appkit.cs
This property is available starting in macOS 10.14, not macOS 14.0.
=> [AppKit] Fix availability attribute for NSSplitViewItem.CanCollapseFromWindowResize.

.github/workflows/bump-global-json.yml
.NET updates come from dotnet/sdk now, so update the bump-global-json
GitHub Action accordingly.
=> [actions] .NET updates come from dotnet/sdk now.

runtime/coreclr-bridge.m, runtime/exports.t4, runtime/monovm-bridge.m, runtime/runtime.m, runtime/xamarin/runtime.h, tests/dotnet/ExceptionalTestApp/AppDelegate.cs, tests/dotnet/ExceptionalTestApp/MacCatalyst/ExceptionalTestApp.csproj, tests/dotnet/ExceptionalTestApp/MacCatalyst/Makefile, tests/dotnet/ExceptionalTestApp/Makefile, tests/dotnet/ExceptionalTestApp/iOS/ExceptionalTestApp.csproj, tests/dotnet/ExceptionalTestApp/iOS/Makefile, tests/dotnet/ExceptionalTestApp/macOS/ExceptionalTestApp.csproj, tests/dotnet/ExceptionalTestApp/macOS/Makefile, tests/dotnet/ExceptionalTestApp/shared.csproj, tests/dotnet/ExceptionalTestApp/shared.mk, tests/dotnet/ExceptionalTestApp/tvOS/ExceptionalTestApp.csproj, tests/dotnet/ExceptionalTestApp/tvOS/Makefile, tests/dotnet/UnitTests/ProjectTest.cs, tests/dotnet/UnitTests/TestBaseClass.cs
Call mono_unhandled_exception to raise AppDomain.UnhandledException when managed exceptions are unhandled.
Partial fix for #15252 (for MonoVM, still pending for CoreCLR, which needs https://github.com/dotnet/runtime/issues/102730 fixed first).
=> [runtime] Call mono_unhandled_exception to raise AppDomain.UnhandledException.

tests/monotouch-test/ImageIO/CGImageSourceTest.cs
The exact results seem to depend on a lot of factors, so just accept them all.
Backport of #20640
=> [release/8.0.1xx-xcode15.1] [monotouch-test] Be a bit more lenient with expected results in CGImageSourceTest.

tests/dotnet/UnitTests/BundleStructureTest.cs
Fix BundleStructure when building for only tvOS by detecting whether the
bindings are zipped or not by detecting the presence of the zip file, instead
of computing it based on the current platform (which becomes problematic,
because whether or not a binding project produces a zip file may depend on
whether other platforms are enabled or not).
=> [tests] Fix BundleStructure when building for only tvOS.

src/GameController/GCMouse.cs, src/frameworks.sources, src/gamecontroller.cs
GCMouse doesn't conform to NSCoding/NSSecureCoding, so fix the API definition.
Since this would be a breaking change, also add compat code to preserve binary
compatibility.
Fixes this test:
Introspection.MacApiSelectorTest
[FAIL] InstanceMethods :   1 errors found in 33428 instance selector validated:
Selector not found for GameController.GCMouse : encodeWithCoder: in Void EncodeTo(Foundation.NSCoder) on GameController.GCMouse
Expected: 0
But was:  1
[FAIL] Selector not found for GameController.GCMouse : encodeWithCoder: in Void EncodeTo(Foundation.NSCoder) on GameController.GCMouse
at Introspection.ApiSelectorTest.InstanceMethods() in /Users/rolf/work/maccore/net9.0/xamarin-macios/tests/introspection/ApiSelectorTest.cs:line 1121
Backport of #20641
=> [release/8.0.1xx-xcode15.1] [GameController] GCMouse doesn't conform to NSCoding/NSSecureCoding.

tests/cecil-tests/BlittablePInvokes.KnownFailures.cs, tests/cecil-tests/BlittablePInvokes.cs, tests/cecil-tests/Helper.cs
This is mostly to ensure that in XAMCORE_5_0 we fix all APIs with MarshalAs
attributes, because in order to not break binary compatibility, we can't fix
all of these failures right now.
Additionally it ensures we don't add more APIs with MarshalAs attributes.
=> [cecil-tests] Add new test to verify that we don't have any MarshalAs attributes.

tools/devops/automation/templates/build/build.yml
It doesn't look like we need it anymore, and in any case it fails to install on ARM64:
> ##[error]Download URL for .Net Core sdk version 5.0.408 could not be found for the following OS platforms (rid): osx-arm64,osx-arm64
From: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9486716&view=logs&jobId=2ad83a99-f770-5ec5-96c6-63e16b4bb697&j=2ad83a99-f770-5ec5-96c6-63e16b4bb697&t=5c4dfcb8-6d0a-532a-9705-12b94c390bf5
Backport of #20527
=> [release/8.0.1xx-xcode15.1] [devops] Remove installation of .NET 5.

tools/devops/automation/templates/build/build-pkgs.yml, tools/devops/automation/templates/build/build-stage.yml, tools/devops/automation/templates/build/build.yml, tools/devops/automation/templates/main-stage.yml, tools/devops/automation/templates/pipelines/build-pipeline.yml
There are now two post build pipelines that run the tests when a new build has complited building the nuget packages and dependencies. This allows the project to have a cleaner build pipeline to onboard on the 1ES template.
=> [CI] Remove all references to the tests in the build pipelines.

tools/devops/automation/templates/build/build.yml
It doesn't look like we need it anymore, and in any case it fails to install on ARM64:
> ##[error]Download URL for .Net Core sdk version 5.0.408 could not be found for the following OS platforms (rid): osx-arm64,osx-arm64
From: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9486716&view=logs&jobId=2ad83a99-f770-5ec5-96c6-63e16b4bb697&j=2ad83a99-f770-5ec5-96c6-63e16b4bb697&t=5c4dfcb8-6d0a-532a-9705-12b94c390bf5
Backport of #20527
=> [release/8.0.1xx-xcode15.0] [devops] Remove installation of .NET 5.

src/GameController/GCExtendedGamepadSnapshot.cs, src/GameController/GCMotion.cs, src/gamecontroller.cs, tests/cecil-tests/BlittablePInvokes.KnownFailures.cs
Make a few GameController structs blittable, which requires some workarounds
to the fact that these changes would be breaking changes - we're keeping the
old structs, and instead introduce internal blittable versions which are then
used in the api definitions (and thus generated P/Invokes).
=> [GameController] Make a few structs blittable.

runtime/coreclr-bridge.m, runtime/runtime.m, tests/mtouch/MiscTests.cs
=> [runtime] Use strnlen instead of strlen.

src/AVFoundation/AVSampleBufferExtensions.cs, src/ImageIO/CGImageMetadata.cs, src/Metal/Defs.cs, src/Network/NWFramer.cs, src/ObjCRuntime/Class.cs, tests/cecil-tests/BlittablePInvokes.KnownFailures.cs
In these cases the APIs in question aren't used in P/Invokes at the moment,
but that may change, so just make as much as we can blittable by removing any
MarshalAs attributes.
=> [src] Remove a few MarshalAs attributes in various APIs.

src/CoreFoundation/CFProxySupport.cs
The Xcode 16 release notes have this note:
CFNetwork Resolved Issues
* Fixed: CFNetworkExecuteProxyAutoConfigurationScript and
CFNetworkExecuteProxyAutoConfigurationURL have always returned a +1
retained CF type object, but the function declarations were not
decorated with the CF_RETURNS_RETAINED attribute until iOS 18, macOS 15,
tvOS 18, and visionOS 2.
For C-based languages, the clang static analyzer might note if the
object is leaked. No source code changes are required, but they are
encouraged to fix the leak.
For Swift, this changes the return type of these functions from
Unmanaged<> to the actual CF type returned, which will require a source
change to fix when compiling with newer SDKs. However, Swift programs
compiled with older SDKs will continue to work on the new OSes, though …
=> [CoreFoundation] Fix memory leak in CFProxySupport.

tools/devops/automation/templates/mac/build.yml, tools/devops/automation/templates/mac/stage.yml, tools/devops/automation/templates/tests/publish-html.yml, tools/devops/automation/templates/tests/publish-results.yml
There is no need to pass the GIT_HASH variable from job to job since it is calculated by the checkout template in the fix_commit step. We just need to update the variables usage.
=> [CI] Fix the comments by using the variable from the checkout template.

tools/devops/automation/scripts/GitHub.psm1, tools/devops/automation/scripts/TestResults.Tests.ps1, tools/devops/automation/scripts/TestResults.psm1
This check is redundant now, because the post-build test pipeline just won't
run in this case.
This fixes an issue where the GitHub comment reports 0 tests passing, because
we'd detect that the tests failed to build even when they didn't.
=> [devops] Remove logic to detect if the tests failed to build before reporting results.

dotnet/targets/Xamarin.Shared.Sdk.targets
The canonical property we use for the interpreter is `MtouchInterpreter` - and
the interpreter is enabled if `MtouchInterpreter` is set to any value (the
`MtouchInterpreter` value is used to select which assemblies to interpret, the
only way to completely disable the interpreter is to not set
`MtouchInterpreter` at all).
So fix a couple of cases of wrong comparison:
* Don't use `UseInterpreter` - which is used to compute a specific value for
`MtouchInterpreter` - because developers don't have to set `UseInterpreter`
to enable the interpreter, they can set `MtouchInterpreter` directly.
* Don't compare `MtouchInterpreter` with `true`: that only checks if the
assembly "true" is interpreted (which it rarely is).
Fixes https://github.com/dotnet/runtime/issues/96920.
This is a backport of …
=> [release/8.0.1xx-xcode15.1] [dotnet] Fix detecting if the interpreter is enabled.

dotnet/targets/Xamarin.Shared.Sdk.targets
This PR enables the dedup optimization in FullAOT mode only. The optimization can only run in FullAOT mode with complete application context. Without it, the AOT compiler may fail to collect all generic instances, and the runtime can't find them as they are searched in the dedup assembly.
This PR updates the SDK targets to enable dedup optimization in FullAOT mode only. This change doesn't depend on any runtime changes.
This PR also introduces partial AOT tests. They inspect the bundle for `aot-instances.dll`, which shouldn't be generated in a partial AOT compilation setup. Additionally, basic functionality is tested by asserting at app startup.
This change should be backported to .NET 8 as well.
Fixes https://github.com/dotnet/runtime/issues/99248
Backport of #20687
=> [release/8.0.1xx-xcode15.1] Enable dedup optimization in FullAOT mode only 

src/ObjCRuntime/Blocks.cs, tools/mtouch/Errors.designer.cs, tools/mtouch/Errors.resx
The validation verifies that the function pointer for a block callback is the
same the return value from the method's
MethodInfo.MethodHandle.GetFunctionPointer() method.
In actual code, it's equivalent to validating that the following always prints "Equal: true":
```cs
[UnmanagedCallersOnly]
public static void Invoke () {}
static void Test ()
{
delegate* unmanaged<void> fptr1 = &Invoke;
IntPtr fptr2 = GetType ().GetMethod ("Invoke").MethodHandle.GetFunctionPointer ();
Console.WriteLine ($"fptr1: 0x{((IntPtr) fptr1).ToString ("x")}");
Console.WriteLine ($"fptr2: 0x{fptr2.ToString ("x")}");
Console.WriteLine ($"Equal: ((IntPtr) fptr1) == fptr2}"); // prints "Equal: true" for me
}
```
However, this isn't documented, and some feedback indicates it's certainly not
a valid assumption for …
=> [release/8.0.1xx-xcode15.1] [Blocks] Remove a block callback validation that's apparently too eager.

src/foundation.cs, tests/xtro-sharpie/api-annotations-dotnet/common-Foundation.ignore, tests/xtro-sharpie/common-Foundation.ignore
Fixes https://github.com/xamarin/xamarin-macios/issues/20745.
=> [Foundation] Add missing properties to NSCharacterSet. Fixes #20745.

tools/devops/automation/build-pipeline.yml, tools/devops/automation/build-pull-request.yml
The configuration was giving issues in one of the jobs with binaries. Using the default fixes the issue.
=> [CI] Use the default credscan setup except for the exclusion.

msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx, msbuild/Xamarin.MacDev.Tasks/Tasks/Archive.cs, msbuild/Xamarin.Shared/Xamarin.Shared.targets
* Set the Architectures array, which Xcode does. This requires passing RuntimeIdentifier(s)
to the task, so do that.
* Set SchemeName, which Xcode does.
This is a partial fix for https://github.com/xamarin/xamarin-macios/issues/20714.
=> [msbuild] Update values we put in the generated Info.plist for Xcode archives.

tools/devops/automation/build-pipeline.yml, tools/devops/automation/build-pull-request.yml
The configuration was giving issues in one of the jobs with binaries. Using the default fixes the issue.
Backport of #20765
=> [release/9.0.1xx-preview6] [CI] Use the default credscan setup except for the exclusion.

tools/devops/automation/templates/release/vs-insertion-prep.yml
Fixes 
> "PowerArgs.ValidationArgException: File not found - D:\a\_work\1\s\xamarin-macios\tools\devops\governance\CredScanSuppressions.csk"
The real issue is that the file does indeed not exist but in reality it is looking for 'CredScanSuppressions.json' which does not exist because there is not checkout of the repo happening when this step is run.
=> [release/9.0.1xx-preview6] [CI] Fix credscan in the sign step

src/AVFoundation/AVTypes.cs, src/avfoundation.cs, tests/cecil-tests/BlittablePInvokes.cs
We need the backwards compatible code for the
AVSampleCursorAudioDependencyInfo struct (i.e. use the
AVSampleCursorAudioDependencyInfo_Blittable version), so adjust the ifdefs
accordingly - which wasn't obvious at first, because __IOS__ is defined for
Mac Catalyst.
Also fix the corresponding test, because it would cache the result of
computing whether a struct was blittable or not, but that's not true across
platforms ("AVSampleCursorAudioDependencyInfo" is blittable on iOS, but not on
Mac Catalyst). The result was that the test would incorrectly pass if we
processed Microsoft.iOS.dll before Microsoft.MacCatalyst.dll. The fix is to
cache per platform, instead of using a global cache.
=> [src] Fix definition of AVSampleCursorAudioDependencyInfo for Mac Catalyst.

dotnet/Workloads/SignList.xml, msbuild/Directory.Build.props, msbuild/ILMerge.targets, msbuild/Makefile, msbuild/Messaging/Xamarin.Messaging.Build/BuildAgent.cs, msbuild/Messaging/Xamarin.Messaging.Build/Handlers/CopyItemMessageHandler.cs, msbuild/Messaging/Xamarin.Messaging.Build/Xamarin.Messaging.Build.csproj, msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx, msbuild/Xamarin.MacDev.Tasks/Tasks/VerifyXcodeVersion.cs, msbuild/Xamarin.Shared/Xamarin.Shared.targets, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.Messaging.Apple.targets, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Tasks.Windows.csproj
This reverts commit f8552e929419ffb609fb6c5d5d6b2e11f93a3a59.
This change is only supposed to be released with .NET 9, and we might
release new .NET 8 updates from main. Thus we need to make sure these
changes are only in the net9.0 branch (they already are).
=> Revert "Migrate Messaging Build agent to .NET 8 (#20705)"

builds/Makefile, dotnet/generate-workloadmanifest-json.csharp, dotnet/generate-workloadmanifest-targets.csharp
The stable .NET 8 workload we're releasing is calling its Sdk pack
'Microsoft.iOS.Sdk.net8'. This means the pack has to be named the same across
everything we're releasing, so special-case the Sdk pack in preview 6 to use
the same Sdk pack name.
New WorkloadManifest.json: https://gist.github.com/rolfbjarne/eeee0cee3c6cb328f7853dbe49ed0d50
Diff with previous one: https://gist.github.com/rolfbjarne/f2c25d2956d39e380e4cc9f922083117
=> [release/9.0.1xx-preview6] [dotnet] Fix workload reference to .NET 8 packages.

tools/devops/automation/templates/tests/stage.yml
Disable the autoinjected governance checks in the tests templates since they timeout on the mac.
ref: https://docs.opensource.microsoft.com/tools/cg/index.html
=> [CI] Disable the governance checks on the tests.

builds/Makefile
This way it can easily be overridden when building from the command line (to
provide a different url if the normal url doesn't work for some temporary
reason).
=> [build] Parameterize the .NET download script url.

src/Foundation/NSArray.cs, src/Foundation/NSArray_1.cs, src/Foundation/NSDictionary.cs, src/Foundation/NSIndexSet.cs, src/Foundation/NSMutableArray_1.cs, src/Foundation/NSMutableDictionary.cs, src/Foundation/NSMutableOrderedSet_1.cs, src/Foundation/NSMutableSet_1.cs, src/Foundation/NSOrderedSet.cs, src/Foundation/NSOrderedSet_1.cs, src/Foundation/NSSet.cs, src/Foundation/NSSet_1.cs, tests/monotouch-test/Foundation/NSArray1Test.cs, tests/monotouch-test/Foundation/NSMutableArray1Test.cs, tests/monotouch-test/Foundation/NSMutableOrderedSet1Test.cs, tests/monotouch-test/Foundation/NSMutableSet1Test.cs, tests/monotouch-test/Foundation/NSOrderedSet1Test.cs, tests/monotouch-test/Foundation/NSSet1Test.cs
When finding an enumerator for the given code:
```cs
var collection = new NSSet<NSNumber> ();
foreach (var item in collection) {
// ...
}
```
the C# compiler will first look for any `GetEnumerator` methods. The non-generic `NSSet` class defines a `IEnumerator<NSObject> GetEnumerator<NSObject> ()` method, which, since the generic `NSSet<T>` class doesn't define such a method, is selected.
The end result is that the type of the foreach element is `NSObject`
(`GetEnumerator`'s return type') - which is somewhat unexpected:
```cs
var collection = new NSSet<NSNumber> ();
foreach (var item in collection) {
Console.WriteLine (item.LongValue); // error CS1061: 'NSObject' does not contain a definition for 'LongValue'
}
```
The fix is to define a  `IEnumerator<T> GetEnumerator<T> ()` method in the …
=> [Foundation] Make the generic collection classes' generic GetEnumerator methods public.

src/bgen/Generator.cs, tests/cecil-tests/ProtocolTest.cs, tools/common/StaticRegistrar.cs
Also fix the MustSetBackwardsCompatibleCodeGenerationToFalse test to skip
protocols that actually set BackwardsCompatibleCodeGeneration=false.
=> [src/tools] Propagate the BackwardsCompatibleCodeGeneration field from Protocol attributes in bindings to the generated code.

tools/siminstaller/Makefile
The C# build server makes trouble for us, because:
* We're using parallel make, and parallel make will start a jobserver, managed
by file descriptors, where these file descriptors must be closed in all
subprocesses for make to realize it's done.
* 'dotnet build' might have started a build server
* The build server does not close any file descriptors it may have inherited
when daemonizing itself.
* Thus the build server (which will still be alive after we're done building)
might have a file descriptor open which make is waiting for.
* The proper fix is to fix the build server to close its file descriptors.
* The intermediate working is to shut down the build server instead. An
alternative solution would be to pass /p:UseSharedCompilation=false to
'dotnet pack' to disable the usage of the …
=> [siminstaller] Don't use the C# compiler server.

tests/monotouch-test/AVFoundation/CaptureMetadataOutputTest.cs
Apple says the bug on their side causing a runtime crash has been fixed since
macOS 12, so unignore the code and add a version check for macOS 12.
Fixes https://github.com/xamarin/maccore/issues/2345.
=> [monotouch-test] Remove ignore for Mac Catalyst.

builds/Makefile, dotnet/generate-workloadmanifest-json.csharp, dotnet/generate-workloadmanifest-targets.csharp
The stable .NET 8 workload we're releasing is calling its Sdk pack 'Microsoft.iOS.Sdk.net8'. This means the pack has to be named the same across everything we're releasing, so special-case the Sdk pack accordingly.
New WorkloadManifest.json:
https://gist.github.com/rolfbjarne/eeee0cee3c6cb328f7853dbe49ed0d50
Diff with previous one:
https://gist.github.com/rolfbjarne/f2c25d2956d39e380e4cc9f922083117
Backport of #20795.
=> [net9.0] [dotnet] Fix workload reference to .NET 8 packages.

src/bgen/Makefile
Add a simple makefile to the src/bgen directory that only builds and tests
bgen.
This is very useful when working on bgen to make sure your changes are at
building and working.
=> [bgen] Add simple makefile.

tests/dotnet/Windows/collect-binlogs.sh, tools/devops/automation/scripts/prepare-for-remote-tests.sh
This way we're using the same NuGet configuration even when executing outside
of XMA's .NET directory.
Also collect a bit more diagnostic info.
=> [devops] Copy XMA's NuGet.config to XMA's home directory.

dotnet/targets/Xamarin.Shared.Sdk.targets, msbuild/Xamarin.MacDev.Tasks/Tasks/ParseBundlerArguments.cs, msbuild/Xamarin.Shared/Xamarin.Shared.targets, tools/common/Application.cs, tools/common/Driver.cs, tools/dotnet-linker/LinkerConfiguration.cs
Ignore a few warnings by default, when reporting about types that we couldn't register because they're deprecated/removed.
Also add a way to re-enable these warnings.
Fixes https://github.com/xamarin/xamarin-macios/issues/20670.
=> [tools] Ignore a few warnings by default. Fixes #20670.

tools/devops/automation/templates/release/vs-insertion-prep.yml
We need to depend on both stages, else we run as soon as the convert is skipped. Makes no sense but VSTS is like this.
Waiting for https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9845461&view=results
=> [CI] We must pass the signing too in order to be able to push nugets.

system-dependencies.sh, tools/devops/automation/templates/tests/build.yml, tools/devops/automation/templates/tests/stage.yml
Split installing new and old simulators, so that we can choose to only install
the old simulators if we want so.
And then only install the old simulators when we're doing beta builds, because
that's the only time we need them.
=> [system-dependencies] Split simulator installation.

tests/dotnet/Windows/InstallDotNet.csproj, tests/test-libraries/nugets/FrameworksInRuntimesNativeDirectory/FrameworksInRuntimesNativeDirectory.csproj, tests/test-libraries/nugets/XCFrameworkWithStaticLibraryInRuntimesNativeDirectory/XCFrameworkWithStaticLibraryInRuntimesNativeDirectory.csproj, tests/xharness/Xharness.Tests/Xharness.Tests.csproj, tests/xharness/xharness.csproj, tests/xtro-sharpie/Makefile, tests/xtro-sharpie/xtro-sharpie/xtro-sharpie.csproj
* xtro: Fix how we build the u2todo project to actually build the correct project.
* Don't import eng/Versions.props in several test projects, it's already
imported in a Directory.Build.props further up the directory hierarchy.
=> [tests] Fix a couple of minor issues.

system-dependencies.sh
In particular we don't need the visionOS simulator/platform.
=> [system-dependencies] Only download the simulators for platforms we target.

dotnet/targets/Xamarin.Shared.Sdk.targets, tests/dotnet/MySimpleApp/Directory.Build.props, tests/dotnet/UnitTests/ProjectTest.cs
When building universal apps, each inner build must add the runtime identifier
to the output path, otherwise the inner builds may conflict with eachother,
overwriting eachother's files.
That's bad.
So we explicitly set `AppendRuntimeIdentifierToOutputPath` to `true` when
building inner builds.
=> [dotnet] Force 'AppendRuntimeIdentifierToOutputPath=true' for the inner build of universal apps.

tests/Directory.Build.targets
This way any tests using the previous .NET version still works.
=> [dotnet] Limit custom dotnet/runtime selection to the current .NET version.

tools/devops/automation/templates/build/build.yml
The system-dependencies.sh script has been updated to install latest and older simulators separately, so --provision-simulators will only provision the latest simulators (using 'xcodebuild -downloadPlatform ...').
This works on all machines, for both PRs and non-PRs, so make it the actual code path in both cases.
=> [devops] Simplify logic to provision simulators.

src/CoreGraphics/CGColorConversionInfo.cs, src/Foundation/NSArray.cs, src/MetalPerformanceShaders/MPSStateResourceList.cs, src/ObjCRuntime/Messaging.cs, src/UIKit/UIAppearance.cs, tests/monotouch-test/CoreGraphics/ColorConversionInfoTest.cs
Move the architecture-specific vargs implementation of
UIAppearance.GetAppareance into a more generic way of calling objc_msgSend
with variadic arguments.
This prepares the way for more APIs with variadic arguments (which is coming
in Xcode 16).
=> [src] Implement a more generic way of calling objc_msgSend with variadic arguments.

tests/monotouch-test/Network/NWPathTest.cs
* Remove code to test NWPath.EnumerateInterfaces, because this method is already tested elsewhere.
* Assume that if the test fails to find any gateways, it might be because the
current machine doesn't have any (which happens on one of my machines), and
in that case ignore the test.
=> [tests] Simplify NWPathTest.EnumerateGatewayTest

dotnet/targets/Xamarin.Shared.Sdk.targets, msbuild/Xamarin.Shared/Xamarin.Shared.targets, tools/dotnet-linker/LinkerConfiguration.cs
As discussed in https://github.com/xamarin/xamarin-macios/pull/20828#discussion_r1668352050  removing icu related files.
ICU lib files were removed by https://github.com/xamarin/xamarin-macios/commit/ed1b6e55c08d3996665bd70d23fbe506cdcb3a4c.
Contributes to https://github.com/dotnet/runtime/issues/99521
=> [net9.0] Globalization clean up icu files

src/AVKit/Enums.cs, src/avkit.cs, tests/xtro-sharpie/api-annotations-dotnet/iOS-AVKit.todo, tests/xtro-sharpie/api-annotations-dotnet/macOS-AVKit.todo, tests/xtro-sharpie/api-annotations-dotnet/tvOS-AVKit.todo, tests/xtro-sharpie/iOS-AVKit.todo, tests/xtro-sharpie/macOS-AVKit.todo, tests/xtro-sharpie/tvOS-AVKit.todo
=> [AVKit] Implement Xcode 15 + Xcode 16.0 beta 1, beta 2 and beta 3 changes.

src/corebluetooth.cs, tests/xtro-sharpie/api-annotations-dotnet/iOS-CoreBluetooth.todo, tests/xtro-sharpie/api-annotations-dotnet/macOS-CoreBluetooth.todo, tests/xtro-sharpie/api-annotations-dotnet/tvOS-CoreBluetooth.todo, tests/xtro-sharpie/iOS-CoreBluetooth.todo, tests/xtro-sharpie/macOS-CoreBluetooth.todo, tests/xtro-sharpie/tvOS-CoreBluetooth.todo, tests/xtro-sharpie/watchOS-CoreBluetooth.todo
=> [CoreBluetooth] Implement Xcode 16.0 beta 1, beta 2 and beta 3 changes.

src/coretelephony.cs, tests/xtro-sharpie/api-annotations-dotnet/iOS-CoreTelephony.todo, tests/xtro-sharpie/iOS-CoreTelephony.todo
Note: there were no changes in beta 2 and beta 3.
=> [CoreTelephony] Implement Xcode 16.0 beta 1, beta 2 and beta 3 changes.

src/DeviceDiscoveryExtension/Enums.cs, src/devicediscoveryextension.cs, tests/xtro-sharpie/api-annotations-dotnet/iOS-DeviceDiscoveryExtension.todo, tests/xtro-sharpie/iOS-DeviceDiscoveryExtension.todo
=> [DeviceDiscoveryExtension] Implement Xcode 16.0 beta 1, beta 2 and beta 3 changes.

src/gamecontroller.cs, tests/xtro-sharpie/api-annotations-dotnet/iOS-GameController.todo, tests/xtro-sharpie/api-annotations-dotnet/tvOS-GameController.todo, tests/xtro-sharpie/iOS-GameController.todo, tests/xtro-sharpie/tvOS-GameController.todo
=> [GameController] Implement Xcode 16.0 beta 1, beta 2 and beta 3 changes.

dotnet/package/common.csproj, eng/Version.Details.xml, eng/Versions.props, tools/devops/automation/build-pipeline.yml, tools/devops/automation/build-pull-request.yml, tools/devops/automation/post-build-pipeline.yml, tools/devops/automation/templates/build/build-nugets.yml, tools/devops/automation/templates/build/build-pkgs.yml, tools/devops/automation/templates/main-stage.yml, tools/devops/automation/templates/release/vs-insertion-prep.yml
This reverts commit 2abbaf900be87eed474f86a6fbeef0c7d92077c3.
These publishing changes were intended for .NET 9.0+, and they require
some additional work to be compatible with stable package versioning.
=> Revert "[ci] Improve maestro artifact publishing (#20665)"

dotnet/targets/Xamarin.Shared.Sdk.targets
fixes: https://github.com/dotnet/maui/issues/23577
`MtouchInterpreter` is set as https://github.com/xamarin/xamarin-macios/blob/d1ec7a793f46f615f5f08f0a60f4c6daa6a1b671/msbuild/Xamarin.Shared/Xamarin.Shared.props#L308
`DynamicCodeSupport` is set by https://github.com/xamarin/xamarin-macios/blob/d1ec7a793f46f615f5f08f0a60f4c6daa6a1b671/dotnet/targets/Xamarin.Shared.Sdk.targets#L146
`Xamarin.Shared.Sdk.targets` is imported *before* `Xamarin.Shared.props` as shown below (courtesy of @ivanpovazan)
so unless the value of `MtouchInterpreter` is set in the project, it's value will be empty when the `DynamicCodeSupport` property is evaluated.
To minimize the impact of this change, until it can be investigated more fully, the value of `MtouchInterpreter` is evaluated as …
=> Add UseInterpreter as part of the check for DynamicCodeSupport

dotnet/targets/Xamarin.Shared.Sdk.targets
Manual backport of https://github.com/xamarin/xamarin-macios/pull/20912
=> [release/8.0.1xx-xcode15.4] Add UseInterpreter as part of the check for DynamicCodeSupport

dotnet/targets/Xamarin.Shared.Sdk.targets
Manual backport of https://github.com/xamarin/xamarin-macios/pull/20912
=> [release/8.0.1xx-xcode15.1] Add UseInterpreter as part of the check for DynamicCodeSupport

tools/devops/automation/build-pipeline.yml, tools/devops/automation/templates/release/vs-insertion-prep.yml
Context: xamarin/yaml-templates@8759ec9
Steps to upload release artifacts to custom blob storage have been
replaced with azure-artifacts-drop (aka.ms/drop).
A new version of nuget-msi-convert has been added that will create a set
of artifact drops for the following shipping artifacts:
* nugets
* vs-components
* vs-packs
The nugets drop contains all shipping packages that should be pushed to
various feeds or NuGet.org.
The components and packs drops are used for VS insertions.
=> [ci] Use drop service for SDK insertion artifacts

dotnet/targets/Xamarin.Shared.Sdk.targets, tests/dotnet/UnitTests/ProjectTest.cs
Backport of https://github.com/xamarin/xamarin-macios/pull/20945
---
This is a follow-up PR to: https://github.com/xamarin/xamarin-macios/pull/20936
We should not enable dedup when targeting `maccatalyst-x64` because in case when the project file specifies `MtouchInterpreter=all,-System.Private.CoreLib`, the build will run the full AOT compiler with interpreter enabled. 
In this setup the runtime is configured to run in interp only mode: https://github.com/xamarin/xamarin-macios/blob/97a91cc4e3bf7cf8a4c657ca00ece620f2e28e91/tools/common/Target.cs#L812-L813
which means that during runtime, AOT images will be ignored - aot runtime will load them but mark them as unusuable since they are compiled with `full` compiler switch and the code falls back to interpreter (ref: …
=> [release/8.0.1xx-xcode15.4] Do not enable dedup when targeting `maccatalyst-x64`

dotnet/targets/Xamarin.Shared.Sdk.targets, tests/dotnet/UnitTests/ProjectTest.cs
This is a follow-up PR to: https://github.com/xamarin/xamarin-macios/pull/20936
We should not enable dedup when targeting `maccatalyst-x64` because in case when the project file specifies `MtouchInterpreter=all,-System.Private.CoreLib`, the build will run the full AOT compiler with interpreter enabled. 
In this setup the runtime is configured to run in interp only mode: https://github.com/xamarin/xamarin-macios/blob/97a91cc4e3bf7cf8a4c657ca00ece620f2e28e91/tools/common/Target.cs#L812-L813
which means that during runtime, AOT images will be ignored - aot runtime will load them but mark them as unusuable since they are compiled with `full` compiler switch and the code falls back to interpreter (ref: https://github.com/dotnet/runtime/blob/efebf202a4a9bd78702bf4bf28a027f093e15d89/src/mono/mono …
=> Do not enable dedup when targeting `maccatalyst-x64`

tools/devops/automation/post-build-pipeline.yml
This post-build pipeline should only run against net8.0 servicing
branches that don't have the commit (2abbaf900b) that moved maestro
publishing into the regular build pipeline.
=> [ci] Update post-build pipeline triggers

dotnet/targets/Xamarin.Shared.Sdk.targets
The runtime now requires Swift so let's link with it by default
https://github.com/dotnet/runtime/commit/2c70e36356e8dfb50e6b32c8b7c9ce1a8e9f1331
Fixes: https://dev.azure.com/xamarin/public/_build/results?buildId=120547&view=logs&j=71979588-66ac-5e95-831a-69c8cd9b2cd2&t=acd19e4c-afbd-5efc-2769-76bfa657ccbb&l=2196
```
/Users/builder/azdo/_work/1/s/bin/dotnet/packs/Microsoft.MacCatalyst.Sdk.net9.0_17.5/17.5.9217-net9-p7/targets/Xamarin.Shared.Sdk.targets(1634,3): error : clang++ exited with code 1: [/Users/builder/azdo/_work/1/s/src/Controls/samples/Controls.Sample/Maui.Controls.Sample.csproj::TargetFramework=net9.0-maccatalyst]
/Users/builder/azdo/_work/1/s/bin/dotnet/packs/Microsoft.MacCatalyst.Sdk.net9.0_17.5/17.5.9217-net9-p7/targets/Xamarin.Shared.Sdk.targets(1634,3): error : Undefined …
```
=> [release/9.0.1xx-preview7] Link with swift

dotnet/targets/Xamarin.Shared.Sdk.targets, tests/dotnet/UnitTests/ProjectTest.cs
Previous fix https://github.com/xamarin/xamarin-macios/pull/20941 did not take into account that when we target non arm64 apple mobile platforms we are using `MONO_AOT_MODE_INTERP_ONLY` which cannot use dedup optimization as it discards AOT images during runtime (as noted in: https://github.com/xamarin/xamarin-macios/pull/20945).
- Enable dedup only when targeting ARM64
- Fix tests to cover builds for both ARM64 and X64 builds
Finally, the change was tested against MAUI iossimulator-x64 template app
=> [release/9.0.1xx-preview7] Enable dedup only when targeting ARM64 mobile platforms

dotnet/targets/Xamarin.Shared.Sdk.targets, tests/dotnet/UnitTests/ProjectTest.cs
Previous fix https://github.com/xamarin/xamarin-macios/pull/20945 did not take into account that when we target non arm64 apple mobile platforms we are using `MONO_AOT_MODE_INTERP_ONLY` which cannot use dedup optimization as it discards AOT images during runtime.
- Enable dedup only when targeting ARM64
- Fix tests to cover builds for both ARM64 and X64 builds
Finally, the change was tested against MAUI iossimulator-x64 template app
=> [release/8.0.1xx-xcode15.4] Enable dedup only when targeting arm64 platforms

dotnet/targets/Xamarin.Shared.Sdk.targets, tests/dotnet/UnitTests/ProjectTest.cs
Backport of https://github.com/xamarin/xamarin-macios/pull/20952
--------
Previous fix https://github.com/xamarin/xamarin-macios/pull/20945 did not take into account that when we target non arm64 apple mobile platforms we are using `MONO_AOT_MODE_INTERP_ONLY` which cannot use dedup optimization as it discards AOT images during runtime.
- Enable dedup only when targeting ARM64
- Fix tests to cover builds for both ARM64 and X64 builds
Finally, the change was tested against MAUI iossimulator-x64 template app
=> [main] Enable dedup only when targeting arm64 

tools/devops/automation/build-pipeline.yml, tools/devops/automation/scripts/bash/install-ios-simulator-simctl.sh, tools/devops/automation/scripts/generate_agent_logs.ps1, tools/devops/automation/templates/build/build-pkgs.yml, tools/devops/automation/templates/build/build-stage.yml, tools/devops/automation/templates/build/build.yml, tools/devops/automation/templates/common/mac-agent-logs.yml, tools/devops/automation/templates/main-stage.yml
There seems to be several problems with the xcode16 branch:
1. There was a merge issue and the ci broke were we were trying to use the sh to install the runtimes.
2. xcodebuild on xcode16 when using EO machines cannot install the needed simulator runtime.
The PR seems to have some noise because there is a back port missing where we fixed a number of yaml lint issues. The important change is at 'Provision simulators (xcodebuild)' (will add a comment). We had to do a few things:
1. Upload the needed runtime to an internal url.
2. Use simctl to add the runtime, which works as opposed to xcodebuild.
This PR unblocks the CI as seen here: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9918721&view=logs&j=600d49c6-e96b-5e8b-2c3a-9f351e2e5848&t=80a136b1-24dd-5d7f-8552-895fbffe54ed
=> [CI] Bring changes to the CI and fix the simulator install

dotnet/targets/Xamarin.Shared.Sdk.props, dotnet/targets/Xamarin.Shared.Sdk.targets, msbuild/Xamarin.Shared/Xamarin.Shared.targets
This reverts commit b4b6ff95bf7145349c7671faa45b8e3e18cc7b5d.
It breaks Hot Reload: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2053707
=> [release/8.0.1xx-xcode15.4] Revert "[dotnet] Compute _SdkIsSimulator and the trimmer configuration earlier in the build. (#20431)"

mk/xamarin.mk, tools/devops/governance/CredScanSuppressions.json
This is mainly to update the suppression files.
Diff: https://github.com/xamarin/maccore/compare/05609a34411fc8a0bc5224dabd2e6897e65167cf..d3ed4b343e2f39f7afc5d54b30aab74895a13dca
=> [release/8.0.1xx-xcode15.4] Bump maccore to get the new testing certificate excusions.

eng/Version.Details.xml
17.5.8020 hash is 700c59ad092ba56a5fc5a71e9aae01b3f4fa25de see https://github.com/xamarin/xamarin-macios/commits/release/8.0.1xx-xcode15.4/
=> [release/9.0.1xx-preview7] Fix .NET 8 dep hashes

Makefile
While not strictly necessary for a successful build, the API diff will fail
unless we have the correct global.json contents checked in.
=> Fail the build if global.json was updated.

mk/xamarin.mk
(cherry picked from commit fb30263d548f98ce489cdccc82bdd80ab1fbd491)
=> [release/9.0.1xx-preview7] [xcsync] Bump xcsync to 1.0.90

eng/Versions.props
The `MicrosoftDotNetXHarnessiOSSharedPackageVersion` value is bumped in `main`,
while `MicrosoftDotNetCecilPackageVersion` is bumped in `netX.Y` branches.
If both lines are next to eachother, and they've each been updated in their
respective branches, then merging `main` into `netX.Y` will result in a merge
failure.
Merge conflicts get old rather fast, so try to avoid this by rearranging these
lines a bit.
=> [maestro] Rearrange lines to try to have fewer merge conflicts.

src/ObjCRuntime/Runtime.cs, tests/bindings-test/ApiDefinition.cs, tests/bindings-test/Messaging.cs, tests/bindings-test/RegistrarBindingTest.cs, tests/test-libraries/libtest.h, tests/test-libraries/libtest.m
Allow a null delegate in Runtime.ReleaseBlockWhenDelegateIsCollected if the
corresponding native pointer is also null.
Fixes https://github.com/xamarin/xamarin-macios/issues/20920.
=> [ObjCRuntime] Allow a null delegate in Runtime.ReleaseBlockWhenDelegateIsCollected. Fixes #20920.

tools/devops/automation/post-build-pipeline.yml
This is required to release any previews of our xcode16 bits.
=> [devops] Publish Xcode 16 builds.

tools/devops/automation/templates/release/vs-insertion-prep.yml
Using the $(System.JobAttempt) variable in the drop metadata artifact
name is problematic. In some cases the drop artifacts created by the
nuget-msi-convert job will be used by a different job, and the job
attempt number will not necessarily match if any jobs are re-ran.
=> [ci] Simplify shipping drop metadata names

tools/devops/automation/post-build-pipeline.yml, tools/devops/automation/templates/main-stage.yml
This is required to release any previews of our xcode16 bits.
=> [devops] Publish Xcode 16 builds (take 2).

src/CoreGraphics/CGSession.cs, src/coregraphics.cs, src/frameworks.sources, tests/monotouch-test/CoreVideo/CVDisplayLinkTest.cs, tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-CoreGraphics.ignore, tests/xtro-sharpie/api-annotations-dotnet/macOS-CoreGraphics.ignore
And use it to ignore a few tests that fail when the screen is locked.
=> [CoreGraphics] Bind the CGSession API.

src/ObjCRuntime/Blocks.cs, src/ObjCRuntime/Registrar.cs, src/ObjCRuntime/UserDelegateTypeAttribute.cs, src/bgen/Generator.cs, tests/monotouch-test/ObjCRuntime/BlocksTest.cs, tools/common/StaticRegistrar.cs, tools/linker/CoreOptimizeGeneratedCode.cs
When we compute the signature of a block for Objective-C, we need to use parameters of the user-provided callback (and not the intermediate UnmanagedCallersOnly method) to compute the signature.
This is because the intermediate method's parameters don't have all the information we need to correctly compute the block signature (in particular for the issue in question, the user callback has an `NSError` parameter, while the intermediate method has an `IntPtr` parameter, and these two parameter types show up differently in the block signature).
This is solved by adding the `UserDelegateType` attribute (which was created for exactly this, and it's just in older generated code) to the intermediate method, pointing to a delegate with the correct managed signature.
Fixes …
=> [dotnet-linker] Fix computing block signatures. Fixes #21008.

tools/devops/automation/scripts/generate_agent_logs.ps1
Sometimes gathering logs fail:
========================== Starting Command Output ===========================
/usr/local/bin/pwsh -NoLogo -NoProfile -NonInteractive -Command . '/Users/builder/azdo/_work/_temp/d21eee53-34e9-41e1-bfb3-335bf6a0c07f.ps1'
Build pipeline start time:
generate_agent_logs.ps1: /Users/builder/azdo/_work/_temp/d21eee53-34e9-41e1-bfb3-335bf6a0c07f.ps1:3
Line |
3 |  /Users/builder/azdo/_work/2/s/xamarin-macios/tools/devops/automation/ …
|  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| Exception calling "Parse" with "1" argument(s): "String '' was not
| recognized as a valid DateTime."
##[error]PowerShell exited with code '1'.
Finishing: Gathering agent logs
Which isn't a big problem, except that the later "Publish Artifacts: Agent
logs" step …
=> [devops] Make agent log gathering more resilient.

tools/devops/automation/scripts/bash/compare.sh
This fixes an issue where we'd compute the wrong api diff for PRs.
=> [devops] Honor SYSTEM_PULLREQUEST_PULLREQUESTNUMBER for PR number if PR_ID isn't set.

.github/workflows/backport-trigger.yml
Because we can't currently build PRs from forks.
=> [actions] Make the backport bot use origin as the repo instead of a fork.

tools/common/Target.cs
This was an oversight in https://github.com/xamarin/xamarin-macios/commit/4a9bfcb154b7902edde55252b61e9559dee43db0
We need to keep underscore as-is to match what the AOT compiler generates.
=> Don't encode underscore in AOT symbol name

dotnet/targets/Xamarin.Shared.Sdk.props, dotnet/targets/Xamarin.Shared.Sdk.targets
When VS (Windows) needs to figure out where the iOS SDK is located on disk on
the Mac machine, the project is evaluated and
the`_XamarinRelativeSdkRootDirectory` property is read. Unfortunately an
MSBuild optimization recently occurred in VS, where they don't keep
underscored properties around after the build, and thus the property XVS needs
to inspect isn't there anymore.
So make `_XamarinRelativeSdkRootDirectory` and `_RelativeMlaunchPath` public
properties by removing the underscore.
Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2220369.
Backport of #21074
=> [release/8.0.1xx-xcode15.4] [dotnet] Make the RelativeMlaunchPath and XamarinRelativeSdkRootDirectory properties public.

dotnet/targets/Xamarin.Shared.Sdk.props, dotnet/targets/Xamarin.Shared.Sdk.targets
When VS (Windows) needs to figure out where the iOS SDK is located on disk on
the Mac machine, the project is evaluated and
the`_XamarinRelativeSdkRootDirectory` property is read. Unfortunately an
MSBuild optimization recently occurred in VS, where they don't keep
underscored properties around after the build, and thus the property XVS needs
to inspect isn't there anymore.
So make `_XamarinRelativeSdkRootDirectory` and `_RelativeMlaunchPath` public
properties by removing the underscore.
Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2220369.
Backport of #21074
=> [release/9.0.1xx-rc1] [dotnet] Make the RelativeMlaunchPath and XamarinRelativeSdkRootDirectory properties public.

src/ObjCRuntime/Blocks.cs, src/ObjCRuntime/Registrar.cs, src/ObjCRuntime/UserDelegateTypeAttribute.cs, src/bgen/Generator.cs, tests/monotouch-test/ObjCRuntime/BlocksTest.cs, tools/common/StaticRegistrar.cs, tools/linker/CoreOptimizeGeneratedCode.cs
When we compute the signature of a block for Objective-C, we need to use parameters of the user-provided callback (and not the intermediate UnmanagedCallersOnly method) to compute the signature.
This is because the intermediate method's parameters don't have all the information we need to correctly compute the block signature (in particular for the issue in question, the user callback has an `NSError` parameter, while the intermediate method has an `IntPtr` parameter, and these two parameter types show up differently in the block signature).
This is solved by adding the `UserDelegateType` attribute (which was created for exactly this, and it's just in older generated code) to the intermediate method, pointing to a delegate with the correct managed signature.
Fixes …
=> [release/8.0.1xx-xcode15.4] [dotnet-linker] Fix computing block signatures. Fixes #21008.

dotnet/targets/Xamarin.Shared.Sdk.props, dotnet/targets/Xamarin.Shared.Sdk.targets
When VS (Windows) needs to figure out where the iOS SDK is located on disk on
the Mac machine, the project is evaluated and
the`_XamarinRelativeSdkRootDirectory` property is read. Unfortunately an
MSBuild optimization recently occurred in VS, where they don't keep
underscored properties around after the build, and thus the property XVS needs
to inspect isn't there anymore.
So make `_XamarinRelativeSdkRootDirectory` and `_RelativeMlaunchPath` public
properties by removing the underscore.
Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2220369.
=> [dotnet] Make the RelativeMlaunchPath and XamarinRelativeSdkRootDirectory properties public.

src/speech.cs, tests/cecil-tests/ApiAvailabilityTest.cs, tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-Speech.todo, tests/xtro-sharpie/api-annotations-dotnet/iOS-Speech.todo, tests/xtro-sharpie/api-annotations-dotnet/macOS-Speech.todo, tests/xtro-sharpie/iOS-Speech.todo, tests/xtro-sharpie/macOS-Speech.todo
There were no changes in beta 2, beta 4, beta 5 or beta 6.
=> [Speech] Implement Xcode 16.0 beta 1-6 changes.

src/bgen/Generator.cs
There's a `System.Runtime.CompilerServices.RequiredMemberAttribute` type,
which may lead to ambiguous type references otherwise.
Fixes https://github.com/xamarin/xamarin-macios/issues/21073.
Backport of #21076
=> [release/8.0.1xx-xcode15.4] [bgen] Fully qualify the RequiredMember and OptionalMember attributes. Fixes #21073.

eng/Version.Details.xml
This way the dependency is automatically bumped and we're not left in the stone age.
=> [maestro] Add a subscription to 'Microsoft.DotNet.SharedFramework.Sdk'.

tools/devops/automation/build-pipeline.yml, tools/devops/automation/build-pull-request.yml, tools/devops/automation/scripts/bash/compare.sh, tools/devops/automation/scripts/generate_agent_logs.ps1, tools/devops/automation/templates/build/build-pkgs.yml, tools/devops/automation/templates/build/build-stage.yml, tools/devops/automation/templates/build/build.yml, tools/devops/automation/templates/main-stage.yml, tools/devops/automation/templates/release/vs-insertion-prep.yml, tools/devops/automation/templates/windows/build.yml, tools/devops/automation/templates/windows/reenable-mac.yml, tools/devops/automation/templates/windows/reserve-mac.yml
We do not intend to merge this branch back into main so it is safe to bring all CI changes at once in order to be in sync and avoid merge conflict cherry-picking commits
=> [release/8.0.1xx-xcode15.4] Merge main CI changes into our release branch

src/bgen/Generator.cs
There's a `System.Runtime.CompilerServices.RequiredMemberAttribute` type,
which may lead to ambiguous type references otherwise.
Fixes https://github.com/xamarin/xamarin-macios/issues/21073.
=> [bgen] Fully qualify the RequiredMember and OptionalMember attributes. Fixes #21073.

eng/Version.Details.xml
=> [release/9.0.1xx-rc1] [net9.0] Bump the .NET 8 / Xcode 15.4 bits to latest stable.

Make.config
BRANCH_NAME is the variable Jenkins used, so add support for the variable
Azure DevOps uses (BUILD_SOURCEBRANCH).
Backport of #21114
=> Fix calculating the branch name if BRANCH_NAME isn't set.

Make.config
BRANCH_NAME is the variable Jenkins used, so add support for the variable
Azure DevOps uses (BUILD_SOURCEBRANCH).
=> [release/8.0.1xx-xcode15.4] Fix calculating the branch name if BRANCH_NAME isn't set.

tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-CoreFoundation.ignore, tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-CoreFoundation.todo, tests/xtro-sharpie/api-annotations-dotnet/common-CoreFoundation.ignore, tests/xtro-sharpie/api-annotations-dotnet/iOS-CoreFoundation.todo, tests/xtro-sharpie/api-annotations-dotnet/macOS-CoreFoundation.todo, tests/xtro-sharpie/api-annotations-dotnet/tvOS-CoreFoundation.todo
Note: there we no changes in beta 1, beta 2, beta 3, beta 4 or beta 6.
Additionally, none of the added APIs are APIs we'll bind for now, they're
rather specialized.
=> [CoreFoundation] Implement Xcode 16.0 beta 1-6 changes.

Make.config
BRANCH_NAME is the variable Jenkins used, so add support for the variable
Azure DevOps uses (BUILD_SOURCEBRANCH).
Backport of #21114
=> [release/9.0.1xx-rc1] Fix calculating the branch name if BRANCH_NAME isn't set.

tools/devops/automation/scripts/VSTS.psm1
We want to be able to export and load the variables in the cacading pipelines. The way we have the scripts makes this process very complicated to do. We need to clean up the script. Then export the steps so that we can access them in the following pipelines.
This change is simply refactoring the way we load/export the default VSTS variables in a pipeline.
=> [CI] Start the process of cleaning up the config step.

src/Foundation/NSUrlSessionHandler.cs
Before PR
NSUrlSessionHandler.Proxy property throws NSE when client code set any value (including `null`)
After PR
NSUrlSessionHandler.Proxy property throws NSE only when the client code tries to set a value different from `null` (Custom proxy is not supported right now in iOS implementation so setting a value other than null must throws NSE)
The reason behind the change is described in #21132 
PR originally submitted by @adospace in #21137.
=> Fix described in #21132

src/avfoundation.cs, src/bgen/Enums.cs, src/bgen/Generator.cs, tests/generator/BGenTests.cs, tests/generator/tests/editor-browsable.cs
* Forward [Obsolete] from api definition interfaces.
* Generate [EditorBrowsable] whenever an api definition member as either
[EditorBrowsable] or [Obsolete].
=> [bgen] Generate Obsolete + EditorBrowsable attributes in a few more cases.

mk/xamarin.mk
* xamarin/maccore@ad4af9cde4 [mlaunch] Add support for the --console argument to devicectl when launching on device.
Diff: https://github.com/xamarin/maccore/compare/eb95ebf480..ad4af9cde4
=> [xcode16] Bump mlaunch to a newer version with fix for xamarin/maccore#20710.

src/Foundation/NSUrlSessionHandler.cs
Before PR
NSUrlSessionHandler.Proxy property throws NSE when client code set any value (including `null`)
After PR
NSUrlSessionHandler.Proxy property throws NSE only when the client code tries to set a value different from `null` (Custom proxy is not supported right now in iOS implementation so setting a value other than null must throws NSE)
The reason behind the change is described in #21132 
PR originally submitted by @adospace in #21137.
Backport of #21140
=> [release/8.0.1xx-xcode15.4] Fix described in #21132

tests/xtro-sharpie/api-annotations-dotnet/iOS-LockedCameraCapture.ignore, tests/xtro-sharpie/iOS-LockedCameraCapture.ignore
For all intents and purposes it's Swift only.
=> [LockedCameraCapture] Don't bind this framework.

tests/common/shared-dotnet.mk
Using RUNTIMEIDENTIFIER(S) in the Makefile interferes with the build, because
they get passed on to msbuild, which sees them as properties
(RuntimeIdentifier(s)).
Thus use RID instead, and only pass on the value to the build if appropriate.
=> [tests] Improve test Makefile when specifying runtime identifier on the command line.

src/Network/NWConnection.cs
The 'nw_connection_set_viability_changed_handler' P/Invoke was originally
bound as 'SetBooleanChangeHandler', which isn't quite right.
So now bind it as 'SetViabilityChangeHandler', obsolete the old version and
remove it in XAMCORE_5_0.
=> [Network] Fix binding mistake in NWConnection.

src/coreimage.cs, tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-CoreImage.ignore, tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-CoreImage.todo, tests/xtro-sharpie/api-annotations-dotnet/common-CoreImage.ignore, tests/xtro-sharpie/api-annotations-dotnet/iOS-CoreImage.ignore, tests/xtro-sharpie/api-annotations-dotnet/iOS-CoreImage.todo, tests/xtro-sharpie/api-annotations-dotnet/macOS-CoreImage.todo, tests/xtro-sharpie/api-annotations-dotnet/tvOS-CoreImage.todo, tests/xtro-sharpie/common-CoreImage.ignore, tests/xtro-sharpie/iOS-CoreImage.ignore, tests/xtro-sharpie/iOS-CoreImage.todo, tests/xtro-sharpie/macOS-CoreImage.todo, tests/xtro-sharpie/tvOS-CoreImage.todo
=> [CoreImage] Implement Xcode 16 beta 6 changes.

tests/common/shared-dotnet.mk
Because simulator is where we most commonly run tests.
And hardcode arm64 - if x64 is ever needed, and I'm bugged enough to add
auto-detection, I'll do it then.
=> [tests] Make the simulator the default runtime identifier when running test suites from the command line.

tools/devops/automation/templates/common/configure.yml
The pwsh used on windows is based on dotnet framework. Dotnet framework has a limit in the size of the env that can be passed to a child process. We are very close to reach the limit, but after #21009 we can ignore that env variable since it is parsed from the args.
This is just needed for the ci pipeline because the issues are going to have are related with the vsdrops task used to upload nuget results etc..
=> [CI] Do not export test matrix.

tools/mtouch/Errors.designer.cs, tools/mtouch/Errors.resx
Ref: https://github.com/xamarin/xamarin-macios/issues/21204
=> [tools] Improve error message when deployment target is too old.

tools/devops/automation/scripts/TestConfiguration.Tests.ps1, tools/devops/automation/scripts/TestConfiguration.psm1, tools/devops/automation/templates/main-stage.yml, tools/devops/automation/templates/tests-stage.yml
Also simplify some code that checks if we're running a .NET test (which will
always be true now).
=> [devops] Remove legacy-only test configurations.

mk/rules.mk
Apple recommends the "fast" mode for production code, and "debug" mode for
non-production, so we're mapping this to Release="fast" and Debug="debug".
References:
* https://developer.apple.com/xcode/cpp/#library-hardening
* https://libcxx.llvm.org/Hardening.html
Fixes https://github.com/xamarin/xamarin-macios/issues/20709.
=> [runtime] Enable C++ standard library hardening. Fixes #20709.

.github/ISSUE_TEMPLATE/01-building-an-application.yml, .github/ISSUE_TEMPLATE/02-running-an-application.yml, .github/ISSUE_TEMPLATE/03-api.yml, .github/ISSUE_TEMPLATE/04-bindings.yml, .github/ISSUE_TEMPLATE/05-other.yml
GitHub won't allow dropping files into a field where 'render: shell'
(presumably because that means the field will automatically become a fenced
block in the final issue), so just remove the 'render' property (this way it
matches all the other input fields).
Fixes https://github.com/xamarin/xamarin-macios/issues/21243.
=> [github] Make it possible to drop files in the "Additional Logs" field. Fixes #21243.

mk/xamarin.mk
=> [release/8.0.1xx-xcode15.4] Bump mlaunch to a version that works with Xcode 16.

tools/devops/automation/templates/windows/generate-token.yml
We need the AzDo.BearerToken in later steps that have the 'always()'
condition, and unless we actually get the AzDo.BearerToken under the same
conditions, those later steps will fail.
One example is if the job was cancelled, or previous steps failed (which is
common when running tests).
Example failure for re-enabling macOS bots:
```
AzDO.BearerToken : The term 'AzDO.BearerToken' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At D:\AzDO\_work\_temp\9b207e8a-c163-4c97-93d3-e7e3bb908583.ps1:6 char:23
+ $azdoBearerToken = "$(AzDO.BearerToken)"
+                       ~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: …
```
=> [devops] Always run the step to get the AzDo.BearerToken.

tools/devops/automation/scripts/generate_agent_logs.ps1
Append to the agent log, instead of creating the file, when an exception occcurs.
The problem is that creating the file fails if it already exists:
Exception occurred: Exception calling "Parse" with "1" argument(s): "String '' was not recognized as a valid DateTime."
New-Item: /Users/builder/azdo/_work/4/s/xamarin-macios/tools/devops/automation/scripts/generate_agent_logs.ps1:52
Line |
52 |      New-Item -Path $Output -Value "$_"
|      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| The file '/Users/builder/azdo/_work/4/s/agent-logs.log' already exists.
=> [devops] Append to the agent log, instead of creating the file.

msbuild/Xamarin.MacDev.Tasks/Tasks/UnpackLibraryResources.cs
This avoids the `UnpackLibraryResources` to fail.
```
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net8.0_17.5/17.5.8020/tools/msbuild/iOS/Xamarin.Shared.targets(1985,3): error MSB4018: System.ArgumentException: Value does not fall within the expected range. (Parameter 'resourceName') 
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net8.0_17.5/17.5.8020/tools/msbuild/iOS/Xamarin.Shared.targets(1985,3): error MSB4018:    at System.Reflection.TypeLoading.Ecma.EcmaAssembly.GetManifestResourceInfo(String resourceName)
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net8.0_17.5/17.5.8020/tools/msbuild/iOS/Xamarin.Shared.targets(1985,3): error MSB4018:    at Xamarin.MacDev.Tasks.UnpackLibraryResources.GetAssemblyManifestResources(String fileName)+MoveNext() in …
```
=> [msbuild] Fix: `Assembly.GetManifestResourceNames()` may return an empty string

src/uikit.cs
So remove the corresponding deprecation attributes.
=> [UIKit] UIFontPickerViewControllerConfiguration.FilteredTraits isn't deprecated.

tests/monotouch-test/Network/NWConnectionGroupTest.cs, tests/monotouch-test/Network/NWProtocolOptionsTest.cs, tests/monotouch-test/System.Net.Http/MessageHandlers.cs
This PR reenables failing tests on tvOS/x64 with NativeAOT as the dotnet/runtime fix became available in: https://github.com/dotnet/runtime/commit/cd064dd8cce624a541b5c966d9449aa5df4072b3 and got merged in to the xamarin net9.0 branch.
The tests were previously disabled in: https://github.com/xamarin/xamarin-macios/pull/20949
---
Fixes: https://github.com/xamarin/xamarin-macios/issues/20972
=> NativeAOT: Reenable failing networking tests on tvOS/x64 with NativeAOT

dotnet/targets/Xamarin.Shared.Sdk.targets, tests/dotnet/UnitTests/ProjectTest.cs
Previously we were including .pdbs in NativeAOT debug bundles, which was causing issues with debug builds of universal apps (during app bundle merging). This does not seem to be required, as in debug builds NativeAOT compiler uses information from pdbs to provide more data about the managed code during native debugging (like line numbers in stack traces, etc), embedding it into the native image, and does not require presence of said files during runtime.
- This PR excludes pdbs from NativeAOT app bundles by removing them from `ResolvedFileToPublish` item group.
- The relevant unit tests are reenabled.
---
Fixes https://github.com/xamarin/xamarin-macios/issues/20903
=> NativeAOT: Exclude pdbs from NativeAOT app bundles

src/Makefile, src/passkit.cs
Also fix a couple of compiler warnings:
passkit.cs(2797,15): warning CS0109: The member 'PKShareablePassMetadataPreview.PassThumbnailImage' does not hide an accessible member. The new keyword is not required.
passkit.cs(2800,14): warning CS0109: The member 'PKShareablePassMetadataPreview.LocalizedDescription' does not hide an accessible member. The new keyword is not required.
=> [src] Turn warnings into errors when compiling API definitions.

tools/devops/automation/scripts/undo_github_merge.ps1
This will typically save between 1 and 2 minutes for every test run.
But potentially much more if GitHub happens to be slow:
```
[...]
Working on a PR, Undoing the github merge with main.
##[error]The task has timed out.
[...]
```
=> [devops] Only fetch the exact remote branches we need to undo the GitHub merge.

dotnet/Workloads/SignList.xml
This change is missing from the last revert https://github.com/xamarin/xamarin-macios/pull/20790/commits/25509d79171fd5cb4ecb7c6db54bbecd83b297ec that happened on https://github.com/xamarin/xamarin-macios/pull/21264
=> [net9.0] Bring back missing change from #20790 to SignList

Makefile, dotnet/Makefile
This is a log from our bots, note the 14 minute gap just before printing the timing results:
```
[...]
2024-09-27T07:34:00.3958920Z Making install in dotnet
2024-09-27T07:34:01.7633820Z Validated file permissions for Xamarin.Mac.
2024-09-27T07:34:01.7800150Z Validated file permissions for Xamarin.iOS.
2024-09-27T07:34:01.7825300Z
2024-09-27T07:34:01.7872490Z 	Xamarin.iOS has not been installed into your system by 'make install'
2024-09-27T07:34:01.7918570Z 	In order to set the currently built Xamarin.iOS as your system version,
2024-09-27T07:34:01.7965090Z 	execute 'make install-system'.
2024-09-27T07:34:01.7987920Z
2024-09-27T07:34:01.8034290Z 	Xamarin.Mac has not been installed into your system by 'make install'
2024-09-27T07:34:01.8080260Z 	In order to set the currently built …
```
=> [build] Shutdown/kill any build servers at the end of the build.

tests/monotouch-test/CoreText/StringAttributes.cs
* CTLine crashes with certain NSAttributedStrings, so don't do that. This fixes #18656.
* Implement this test for macOS.
* Misc other fixes.
Fixes https://github.com/xamarin/xamarin-macios/issues/18656.
=> [tests] Rework StringAttributesTests.SimpleAttributesTest. Fixes #18656.

Make.config, builds/Makefile, builds/package-download/download-packages.csproj, eng/Version.Details.xml, eng/Versions.props, tests/dotnet/MySimpleApp/Directory.Build.props
.NET 9 RC 2 will include security fixes, so the very latest builds will be
internal. As a way for us to test the newest possible public builds, we can
update dotnet/runtime ahead of dotnet/sdk.
See also Android's PR: https://github.com/dotnet/android/pull/9347
=> [release/9.0.1xx-rc2] Track dotnet/runtime separately.

src/PassKit/PKPayLaterView.cs, tests/monotouch-test/PassKit/PKPayLaterViewTest.cs, tests/xtro-sharpie/api-annotations-dotnet/iOS-PassKit.ignore
Fixes https://github.com/xamarin/xamarin-macios/issues/19271.
=> [PassKit] Finish implementation of PKPayLaterValidateAmount. Fixes #19271.

.github/workflows/update-single-platform-branches.yml
Because there's nothing but .NET now.
=> [actions] There's no reason to keep testing a .NET-only configuration.

Make.config
The variable TRACKING_DOTNET_RUNTIME_SEPARATELYis already defined further
above in this file, so just remove the second definition.
I believe this happened due to an incorrect merge conflict resolution at some
point.
=> [net9.0] [build] Remove duplicate variable definition.

tools/devops/automation/run-post-ci-build-macos-tests.yml, tools/devops/automation/run-post-ci-build-tests.yml, tools/devops/automation/run-post-pr-build-macos-tests.yml, tools/devops/automation/run-post-pr-build-tests.yml
VSTS recommends this in their docs. We are going to do it to make it simpler to track what triggers what.
=> [CI] Use the full path for triggering resources.

src/Foundation/DictionaryContainer.cs, src/UIKit/UISegmentedControl.cs, src/uikit.cs, tests/monotouch-test/UIKit/SegmentedControlTest.cs, tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-UIKit.ignore, tests/xtro-sharpie/api-annotations-dotnet/iOS-UIKit.ignore, tests/xtro-sharpie/api-annotations-dotnet/tvOS-UIKit.ignore
1. Enable nullability.
2. Move Get|SetTitleTextAttributes to generated code.
3. Remove dead code (pre-.NET code paths).
Point 2. fixes #21289, so add tests for this scenario.
Fixes https://github.com/xamarin/xamarin-macios/issues/21289.
Backport of #21299
=> [net9.0] [UIKit] Improve code for UISegmentedControl. Fixes #21289.

msbuild/ILMerge.targets, msbuild/Xamarin.MacDev.Tasks/Tasks/ComputeCodesignItems.cs, tests/Makefile, tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/CompileAppManifestTaskTests.cs, tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/CompileEntitlementsTaskTests.cs, tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/ComputeCodesignItemsTaskTests.cs, tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/ResolveNativeReferencesTaskTest.cs, tests/msbuild/Xamarin.MacDev.Tasks.Tests/Xamarin.MacDev.Tasks.Tests.csproj, tests/msbuild/Xamarin.MacDev.Tests/TestHelpers/BuildEngine.cs, tests/msbuild/Xamarin.MacDev.Tests/Xamarin.MacDev.Tests.csproj, tests/xharness/Jenkins/NUnitTestTasksEnumerable.cs
This reverts commit 15c1e7527e8d621760b9fe2c6b1ce2382dcab2f7.
It breaks the Windows tests.
=> Revert "[msbuild/tests] Use 'dotnet test' for the MSBuild tests. (#21263)"

tests/monotouch-test/dotnet/shared.csproj, tests/test-libraries/custom-type-assembly/Makefile
Building the custom-type-assembly assembly doesn't work quite right if the
RuntimeIdentifier(s) variables are set in the environment frmo the project
file, so don't forward those to the sub-make we execute to build the assembly.
This fixes an issue where building monotouch-test would fail locally, because
building the custom-type-assembly assembly would fail.
Also remove legacy Xamarin logic.
=> [tests] Fix building the custom-type-assembly assembly from inside a project file.

tests/monotouch-test/CoreText/FontManagerTest.cs
This way we can actually run the test.
Fixes https://github.com/xamarin/xamarin-macios/issues/6690.
=> [tests] Fix FontManagerTest.RegisterFontDescriptors_WithCallback to be a bit more lax. Fixes #6690.

tools/devops/automation/run-post-ci-build-macos-tests.yml, tools/devops/automation/run-post-ci-build-tests.yml, tools/devops/automation/run-post-pr-build-macos-tests.yml, tools/devops/automation/run-post-pr-build-tests.yml, tools/devops/automation/templates/build/build-mac-tests-stage.yml, tools/devops/automation/templates/mac/build.yml, tools/devops/automation/templates/mac/stage.yml, tools/devops/automation/templates/pipelines/run-macos-tests-pipeline.yml, tools/devops/automation/templates/pipelines/run-tests-pipeline.yml, tools/devops/automation/templates/tests-stage.yml
This is a backport of the following PRs:
* [CI] Split the sim tests and the macOS tests. (#21215)
* [CI] Add missing configuration stage for the macos tests pipeline. (#21303)
* [CI] Fix the pipeline that runs the macOS tests. (6df33a86bb4e1ae499d75a603bb29c1695728100 - no PR for this one?)
* [CI] Use the full path for triggering resources. (#21338)
=> [release/8.0.1xx-xcode16.0] Fix the macOS tests in Azure DevOps.

tests/monotouch-test/Security/RecordTest.cs
This will hopefully help us track down a random test failure in this test.
Ref: https://github.com/xamarin/maccore/issues/868
=> [tests] Include more information in asserts in MonoTouchFixtures.Security.RecordTest.DeskCase_83099_InmutableDictionary.

builds/Makefile, tests/packaged-macos-tests.mk
On the bots we're executing with Rosetta, and 'arch' returns 'i386' under
Rosetta, so detect when we're executing under Rosetta, and install the arm64
version of .NET in that case as well.
Also fix a bug in the same area in our tests.
=> [build] Fix installing the arm64 version of .NET.

tools/devops/provision-shared.in.csx
It doesn't look like it's used anywhere (and I don't have it on my system either).
=> [devops] Remove the wget dependency.

dotnet/generate-target-platforms.csharp, msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx, msbuild/Xamarin.MacDev.Tasks/Tasks/CompileAppManifest.cs, msbuild/Xamarin.Shared/Xamarin.Shared.targets, tests/Makefile, tests/dotnet/UnitTests/ProjectTest.cs, tests/generator/BGenTool.cs, tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/CompileAppManifestTaskTests.cs, tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/GeneratePlistTaskTests/GeneratePlistTaskTests_Core.cs
This isn't very user friendly:
ILLink : unknown error IL7000: An error occurred while executing the custom linker steps. Please review the build log for more information.
ILLINK : error MT0073: Microsoft.iOS 18.0.8337 does not support a deployment target of 10.0 for iOS (the minimum is 11.0). Please select a newer deployment target in your project's Info.plist or change the SupportedOSPlatformVersion property in your project file.
ILLINK : error MT2301: The linker step 'Setup' failed during processing: Microsoft.iOS 18.0.8337 does not support a deployment target of 10.0 for iOS (the minimum is 11.0). Please select a newer deployment target in your project's Info.plist or change the SupportedOSPlatformVersion property in your project file. …
=> [net9.0] [msbuild] Improve the error message when the SupportedOSPlatformVersion is lower than the minimum. Fixes #21368. (#21369)

dotnet/Makefile, tools/devops/provision-shared.in.csx
According to @pjcollins the msi files we were generated aren't used anywhere, so this should be safe.
=> [devops] Remove the msitools dependency.

dotnet/targets/Xamarin.Shared.Sdk.props, tests/dotnet/UnitTests/ProjectTest.cs
We need to set "UseCurrentRuntimeIdentifier=false", we must only set it for
the outer build for universal builds - when `RuntimeIdentifiers` is set - but
that means we can only do it *after* we set any default value for
`RuntimeIdentifiers`.
Fixes https://github.com/xamarin/xamarin-macios/issues/19391#issuecomment-2405499973.
Backport of #21412
=> [net9.0] [dotnet] Fix building universal apps using NativeAOT when the default RuntimeIdentifiers value is set. Fixes #19391.

dotnet/generate-vs-workload.csharp, tools/devops/automation/build-pipeline.yml
Context: https://github.com/dotnet/arcade/commit/b2d3a3a35526b529490e8f7e410b3777b3f20bd6
Context: https://github.com/xamarin/yaml-templates/pull/339
The VS insertion manifest generation has been updated to use new VS
component IDs required for .NET 9+.
=> [nuget-msi-convert] Support improved VS component IDs

tests/dotnet/Windows/InstallDotNet.csproj
Just trust the exit code instead.
This way the installation doesn't fail due to random output.
=> [tests] Ignore output that looks like errors when installing .NET on Windows.

tools/devops/automation/templates/main-stage.yml
In the process of ensuring that we can run tests a single time, we are removing all extra stages from the CI. We have move the APIScan to the following pipelines.
- CI Pipeline: https://devdiv.visualstudio.com/DevDiv/_build?definitionId=24050
- PR Pipeline: https://devdiv.visualstudio.com/DevDiv/_build?definitionId=24049
=> [CI] Remove the APIScan stage since we have a pipeline to run it.

msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
Here's an example failure that didn't stop the build:
Target Name=_RunILLink Project=sampleproj.csproj
Building target "_RunILLink" completely.
Output file "obj\Release\net8.0-ios\ios-arm64\linked\Link.semaphore" does not exist.
[...]
Xamarin.MacDev.Tasks.ILLink
[...]
C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): [xma][err]: An exception occurred in the task 'ILLink'
C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8030\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): The post for client build1460814608Ilian on topic xvs/build/1.14.0.6/execute-task/ecacau/de6ed16002fILLink has been cancelled
at Xamarin.Messaging.Client.MessagingClient.PostAsync[TRequest,TResponse](TR …
=> [msbuild] Make sure the build doesn't keep going if the ILLink task fails.

Make.config, docs/preview-apis.md, mk/rules.mk, runtime/Makefile, runtime/swift-functions.swift, src/StoreKit/SwiftAPI.cs, src/frameworks.sources, src/storekit.cs, tests/cecil-tests/AttributeTest.cs, tests/introspection/ApiProtocolTest.cs, tests/introspection/ApiSelectorTest.cs, tests/xtro-sharpie/api-annotations-dotnet/common-StoreKit.ignore, tools/common/SdkVersions.cs
The existing Objective-C class to request an App Store review (SKStoreReviewController) is deprecated in Xcode 16+, and it doesn't even work on the corresponding OS versions.
The replacement API is Swift-only, but luckily it's a very simple API (just a static method), so it's possible to bind it manually.
This required a few other changes/improvements:
* Add support for Swift code in our runtime.
* Just to keep the changes to a minimum, bump the min OS version for legacy code to match the .NET min OS versions. This is because our build logic uses the legacy min versions when compiling native code (a more involved fix would be to update all the build logic to build native code to use the .NET min OS versions, but that's not the point of this PR, so I took the easy route). Fixes #10659. …
=> [StoreKit] Bind AppStore.requestReview. Fixes #21410.

dotnet/generate-vs-workload.csharp, tools/devops/automation/build-pipeline.yml
Context: https://github.com/dotnet/arcade/commit/b2d3a3a35526b529490e8f7e410b3777b3f20bd6
Context: https://github.com/xamarin/yaml-templates/pull/339
The VS insertion manifest generation has been updated to use new VS
component IDs required for .NET 9+.
Backport of #21423
=> [main] [nuget-msi-convert] Support improved VS component IDs

tools/devops/automation/scripts/prepare-for-remote-tests.sh
A dual-purpose script is always better than a single-purpose script!
This also removes a dependency on 'xamarin-macios' being the repository name.
=> [devops] Make the prepare-for-remote-tests.sh script callable locally.

tests/dotnet/Windows/collect-binlogs.sh, tools/devops/automation/scripts/clean-for-remote-tests.sh
Also collect any crash reports from the remote machine.
=> [devops] Clean up before and after running the Windows tests remotely.

tools/dotnet-linker/Steps/ConfigurationAwareStep.cs
This way we report the stack trace of the original exception in build logs.
=> [dotnet-linker] Improve error reporting by not forgetting about original exceptions.

dotnet/generate-vs-workload.csharp
Context: https://github.com/xamarin/xamarin-macios/commit/9013ae4f83a9236ac91a8fe857a2403371993534
We've decided hold off on this change until .NET 10.
=> [nuget-msi-convert] Do not use new VS component IDs

dotnet/generate-vs-workload.csharp
Context: https://github.com/xamarin/xamarin-macios/commit/9013ae4f83a9236ac91a8fe857a2403371993534
We've decided hold off on this change until .NET 10.
Backport of #21476
=> [net9.0] [nuget-msi-convert] Do not use new VS component IDs

msbuild/ILMerge.targets
This avoids a Mono dependency (the `sn` tool is installed with Mono).
=> [msbuild] Use ilrepack to sign instead of sn.

msbuild/Directory.Build.props
This makes it easier to consume a locally built version of Xamarin.Messaging
when build and testing locally.
=> [msbuild] Make MessagingVersion overridable from the environment.

tools/devops/automation/templates/tests/build.yml
Also:
* Improve file listing by not wrapping output.
* Be a bit more descriptive in step display names.
=> [devops] Clean previously downloaded artifacts.

tests/xtro-sharpie/Makefile, tests/xtro-sharpie/xtro-sharpie/xtro-sharpie.csproj
Note that it's still executed with Mono, because we load a native library that
needs Mono at runtime.
=> [xtro] Port the xtro-sharpie.csproj to a new style project and build with .NET.

msbuild/Xamarin.MacDev.Tasks/Tasks/CompileEntitlements.cs
Fixes this warning:
> [...]\packs\Microsoft.iOS.Sdk.net9.0_18.0\18.0.9731-ci.dev-rolf\tools\msbuild\iOS\Xamarin.Shared.targets(755,3): Access to the path 'C:\Users\rolf\Library\Caches\Xamarin\mtbs\builds\BundleStructure\e3602c179d4eceb04f35658ffc4180192072542b74da729d64a6505c255de589\obj\Debug\net9.0-ios\ios-arm64' is denied.
=> [msbuild] Don't try to create an output file on Windows using a full path.

Directory.Build.props, msbuild/Messaging/Xamarin.Messaging.Build/Xamarin.Messaging.Build.csproj, msbuild/Xamarin.MacDev.Tasks/Xamarin.MacDev.Tasks.csproj, msbuild/Xamarin.iOS.Tasks/Xamarin.iOS.Tasks.csproj, tests/msbuild/Xamarin.MacDev.Tasks.Tests/Xamarin.MacDev.Tasks.Tests.csproj, tools/class-redirector/class-redirector/class-redirector.csproj
Use MSBuild assemblies from NuGet instead of Mono's installation. Try to get
the closest version to Mono's assemblies.
This avoids a Mono dependency.
=> [msbuild] Use MSBuild assemblies from NuGet instead of Mono's installation.

dotnet/targets/Xamarin.Shared.Sdk.Trimming.props, tests/dotnet/AppWithXCFrameworkWithStaticLibraryInPackageReference/shared.csproj, tests/dotnet/UnitTests/BundleStructureTest.cs
The default build times for a Mac Catalyst app on arm64 are horrendous:
* `dotnet new maccatalyst && dotnet build`: 1 minute
Enabling the trimmer or the interpreter makes it _much_ better:
* `dotnet new maccatalyst && dotnet build /p:UseInterpreter`: 17 seconds
* `dotnet new maccatalyst && dotnet build /p:TrimMode=partial`: 12 seconds
* `dotnet new maccatalyst && dotnet build /p:TrimMode=full`: 12 seconds
* `dotnet new maccatalyst && dotnet build /p:TrimMode=partial /p:UseInterpreter=true`: 12 seconds
So enable the trimmer by default for Debug mode on ARM64 on:
* iOS
* tvOS
* Mac Catalyst
(we're already trimming for other build configurations, so it seemed like an easy to choice to enable the trimmer in these configurations as well, as opposed to enabling the interpreter)
Fixes …
=> [net10.0] Trim by default (SdkOnly) when building for arm64. Fixes #21444.

msbuild/Xamarin.MacDev.Tasks/Tasks/UnpackLibraryResources.cs
This avoids the `UnpackLibraryResources` to fail.
```
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net8.0_17.5/17.5.8020/tools/msbuild/iOS/Xamarin.Shared.targets(1985,3): error MSB4018: System.ArgumentException: Value does not fall within the expected range. (Parameter 'resourceName') 
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net8.0_17.5/17.5.8020/tools/msbuild/iOS/Xamarin.Shared.targets(1985,3): error MSB4018:    at System.Reflection.TypeLoading.Ecma.EcmaAssembly.GetManifestResourceInfo(String resourceName)
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net8.0_17.5/17.5.8020/tools/msbuild/iOS/Xamarin.Shared.targets(1985,3): error MSB4018:    at Xamarin.MacDev.Tasks.UnpackLibraryResources.GetAssemblyManifestResources(String fileName)+MoveNext() in …
```
=> [release/8.0.1xx-xcode16.0] [msbuild] Fix: `Assembly.GetManifestResourceNames()` may return an empty string

tools/devops/automation/scripts/System.psm1, tools/devops/automation/scripts/VSTS.psm1, tools/devops/automation/templates/mac/build.yml, tools/devops/automation/templates/tests/build.yml
File an AzDo issue if a bot runs out of space, but if there's already an open
issue for a bot, then just add a comment to the existing issue.
Example issue created locally: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2289908.
=> [devops] File an AzDo issue if a bot runs out of space.

msbuild/Xamarin.MacDev.Tasks/Tasks/CreateEmbeddedResources.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/PackLibraryResources.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/UnpackLibraryResources.cs, tests/msbuild/Xamarin.MacDev.Tests/TargetTests/TargetTests.cs
When embedding bundle resources to an assembly as assembly resources, we store
the LogicalName property for the resource. We do this by using the LogicalName
property as the resource name - but we need to encode forward and backward
slashes, since they don't work properly has resource names.
In the past, we've encoded forward and backward slashes differently, but this
results in different encodings depending on whether the resources are embedded
on Windows or macOS.
So change the encoding, so that both forward and backward slashes are encoded
the same way, and then they're extracted using the platform's path character.
This way we get consistent behavior on both platforms.
=> [msbuild] Unify escaping algorithm for mangled resources, and remove code duplication.

docs/build-apps/build-items.md, msbuild/Xamarin.MacDev.Tasks/Tasks/CompileAppManifest.cs, msbuild/Xamarin.Shared/Xamarin.Shared.targets, tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/CompileAppManifestTaskTests.cs
This makes it possible to provide partial app manifests with default values,
which can then be overridden in the main Info.plist.
=> [msbuild] Add support for the 'overwrite' metadata for PartialAppManifest items.

msbuild/Directory.Build.props
Brings some important fixes on client and agent side to handle agent status notifications better
Diff: https://github.com/xamarin/Xamarin.Messaging/compare/a3a1e00e5a89ec27bc9e19ddc596e2e63e3ac017..6b35d9de966802709767d61306917642ff72f622
This is a backport of #21521.
Also backport #21457 to avoid future merge failures during Xamarin.Messaging bumps.
=> [release/9.0.1xx] Update Xamarin.Messaging to 2.2.10.

tools/devops/automation/scripts/bash/build-nugets.sh, tools/devops/automation/scripts/bash/clean-bot.sh
* Find all git repositories in the default working directory, for both
multi-repo checkouts and single-repo checkouts, and clean them all.
* Completely remove the 'packages' directory before putting any other files in
it.
=> [devops] Clean up bots better from previous usage.

tools/devops/automation/scripts/VSTS.psm1
This makes the code to find existing work items for a given title actually
work.
=> [devops] Escape quotes when searching for work items using title.

src/Makefile, src/Makefile.rgenerator, src/rgen/Microsoft.Macios.Binding.Common/Microsoft.Macios.Binding.Common.csproj, src/rgen/Microsoft.Macios.Bindings.Analyzer.Sample/Microsoft.Macios.Bindings.Analyzer.Sample.csproj, src/rgen/Microsoft.Macios.Bindings.Analyzer/Microsoft.Macios.Bindings.Analyzer.csproj, src/rgen/Microsoft.Macios.Generator.Sample/Microsoft.Macios.Generator.Sample.csproj, src/rgen/Microsoft.Macios.Generator/Microsoft.Macios.Generator.csproj, src/rgen/rgen.sln, tests/rgen/Microsoft.Macios.Generator.Tests/Microsoft.Macios.Generator.Tests.csproj
This simplifies the usage of those external file, specially for test projects.
=> [RGen] Move common shared code to its own project.

mk/xamarin.mk
Relevant commits:
* https://github.com/xamarin/maccore/commits/fcd7847f00 [mlaunch] Fix --isappinstalled when using devicectl. (#2951)
Diff: https://github.com/xamarin/maccore/compare/c1a17a2f8081e6a7cf55e5b516c7fe7eeaa107b9..fcd7847f0059f4d8392e342d917a23c070f0b97d
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2291207.
Backport of #21550
=> [release/9.0.1xx] Bump mlaunch.

tools/devops/automation/scripts/undo_github_merge.ps1
We don't need the tags, so don't spend time fetching them.
=> [devops] Don't fetch tags when undoing the GitHub merge.

tests/common/Configuration.cs, tests/dotnet/UnitTests/TestBaseClass.cs, tests/dotnet/UnitTests/WindowsTest.cs, tests/dotnet/Windows/.gitignore, tools/devops/automation/scripts/run-local-windows-tests.ps1, tools/devops/automation/scripts/run-remote-windows-tests.ps1, tools/devops/automation/templates/windows/build.yml
* Run both sets of Windows tests (local and remote), and fail afterwards if there
are test failures. This way we get both test suites executed even if the first
one fails.
* Create a script for executing the local tests (makes it easier to run locally
as well).
* Make it possible to use a custom built .NET locally by honoring any DOTNET variable
instead of blindly setting it (makes it easier to test locally).
* Add a .gitignore for the test configuration file we create to run tests on Windows.
* Some minor code simplifications.
=> [devops] Improve Windows tests a little bit.

dotnet/targets/Xamarin.Shared.Sdk.targets, src/TrimAttributes.LinkDescription.xml, src/UIKit/UIBarButtonItem.cs
Rewrite how we handle events/callbacks for UIBarButtonItem: there's no need for a special class to receive the click events, we can use the same UIBarButtonItem instance through a category.
This simplifies the code a lot, and should also fix this random exception:
Failed to marshal the Objective-C object 0x2800fcc00 (type: UIKit_UIBarButtonItem_Callback). Could not find an existing managed instance for this object, nor was it possible to create a new managed instance (because the type 'UIKit.UIBarButtonItem+Callback' does not have a constructor that takes one NativeHandle argument).
at ObjCRuntime.Runtime.MissingCtor(IntPtr, IntPtr, Type, Runtime.MissingCtorResolution, IntPtr, RuntimeMethodHandle) + 0x1dc
at ObjCRuntime.Runtime.ConstructNSObject[T](IntPtr, Type, …
=> [net10.0] [UIKit] Fix a GC race in UIBarButtonItem.

src/appkit.cs, src/mediaextension.cs, tests/introspection/ApiSelectorTest.cs
* Mark a few MediaExtension fields as Notification fields.
* Remove extreanous NSSharingCollaborationModeRestriction.AlertRecoverySuggestionButtonLaunchUrl setter.
* introspection: ignore methods that start with '_Init', aren't publicly
visible, and bind an Objective-C constructor when verifying that a managed
method doesn't bind an Objective-C constructor.
=> [AppKit/MediaExtension/introspection] Fix issues found with introspection on Sequoia.

tests/common/Configuration.cs
This speeds up the tests somewhat, since it's fetched quite a few times.
=> [tests] Cache the evaluation of the DOTNET_DIR variable.

tests/bindings-framework-test/dotnet/shared.csproj, tests/bindings-test/dotnet/shared.csproj, tests/bindings-test2/dotnet/shared.csproj, tests/bindings-xcframework-test/dotnet/shared.csproj
Use a file (as opposed to a directory) as the Outputs property in MSBuild targets.
Directories have unintuitive file stamp behavior sometimes, which may confuse incremental
builds, so use files instead to drive incremental builds.
=> [tests] Use a file as the Outputs property in MSBuild.

.github/workflows/maestro-changelog.yml
So install that, since it doesn't look like it's installed by default yet.
Also build before running, because the new terminal logger for the build in .NET 9 ends up printing junk which ends up in the changelog.
=> [actions] The changelog action now requires .NET 9.

.github/workflows/maestro-changelog.yml
So install that, since it doesn't look like it's installed by default yet.
Also build before running, because the new terminal logger for the build in .NET 9 ends up printing junk which ends up in the changelog.
Backport of #21629
=> [release/8.0.1xx-xcode16.0] [actions] The changelog action now requires .NET 9.

.github/workflows/maestro-changelog.yml
So install that, since it doesn't look like it's installed by default yet.
Also build before running, because the new terminal logger for the build in .NET 9 ends up printing junk which ends up in the changelog.
Backport of #21629
=> [release/9.0.1xx] [actions] The changelog action now requires .NET 9.

tests/dotnet/UnitTests/BundleStructureTest.cs, tools/dotnet-linker/Steps/ManagedRegistrarLookupTablesStep.cs
If an assembly only required the lookup tables from the managed static
registrar (and not any other code), we wouldn't save those changes.
This would lead to a runtime exception:
```
Microsoft.iOS: Processing Objective-C exception for exception marshalling (mode: 2):
Could not find the type 'ObjCRuntime.__Registrar__' in the assembly 'X.Y.Z'. (ObjCRuntime.RuntimeException)
at ObjCRuntime.RegistrarHelper.GetMapEntry(String assemblyName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/RegistrarHelper.cs:line 105
at ObjCRuntime.RegistrarHelper.GetMapEntry(Assembly assembly) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/RegistrarHelper.cs:line 93
at ObjCRuntime.RegistrarHelper.LookupRegisteredType(Assembly assembly, UInt32 id) in …
```
=> [static registrar] Make sure to save any changes made by the managed static registrar. Fixes #21606.

tests/dotnet/UnitTests/BundleStructureTest.cs, tools/dotnet-linker/Steps/ManagedRegistrarLookupTablesStep.cs
If an assembly only required the lookup tables from the managed static
registrar (and not any other code), we wouldn't save those changes.
This would lead to a runtime exception:
```
Microsoft.iOS: Processing Objective-C exception for exception marshalling (mode: 2):
Could not find the type 'ObjCRuntime.__Registrar__' in the assembly 'X.Y.Z'. (ObjCRuntime.RuntimeException)
at ObjCRuntime.RegistrarHelper.GetMapEntry(String assemblyName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/RegistrarHelper.cs:line 105
at ObjCRuntime.RegistrarHelper.GetMapEntry(Assembly assembly) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/RegistrarHelper.cs:line 93
at ObjCRuntime.RegistrarHelper.LookupRegisteredType(Assembly assembly, UInt32 id) in …
```
=> [release/9.0.1xx] [static registrar] Make sure to save any changes made by the managed static registrar. Fixes #21606.

dotnet/Makefile, scripts/generate-vs-workload/generate-vs-workload.cs
Context: https://github.com/xamarin/xamarin-macios/commit/06fea905cf900ab5296b08d7b67dadddc733dd65
In order to add .NET 9 Xcode16.1 builds to VS we'll need to insert packs
from two different commits on the `release/9.0.1xx-preview` branch.
Xcode information will now be added to the VS manifest that we generate
to allow us to produce unique manifests across the same branch.
Backport of #21657
=> [release/9.0.1xx] [vs-workload.props] Append xcode info to VSMAN

dotnet/Makefile, scripts/generate-vs-workload/generate-vs-workload.cs
Context: https://github.com/xamarin/xamarin-macios/commit/06fea905cf900ab5296b08d7b67dadddc733dd65
In order to add .NET 9 Xcode16.1 builds to VS we'll need to insert packs
from two different commits on the `release/9.0.1xx-preview` branch.
Xcode information will now be added to the VS manifest that we generate
to allow us to produce unique manifests across the same branch.
=> [vs-workload.props] Append xcode info to VSMAN

Directory.Build.props, msbuild/Messaging/Xamarin.Messaging.Build/Xamarin.Messaging.Build.csproj, msbuild/Xamarin.MacDev.Tasks/Xamarin.MacDev.Tasks.csproj, msbuild/Xamarin.iOS.Tasks/Xamarin.iOS.Tasks.csproj, tests/msbuild/Xamarin.MacDev.Tasks.Tests/Xamarin.MacDev.Tasks.Tests.csproj, tools/class-redirector/class-redirector/class-redirector.csproj
This reverts commit 71a29e3777dfeba0e829ce375ce8be6acdd1d25d.
This seems to be breaking windows see: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2304182
=> [release/9.0.1xx] Revert "[msbuild] Use MSBuild assemblies from NuGet instead of Mono's installation. (#21471)"

tests/monotouch-test/PassKit/PassLibraryTest.cs
They fail randomly when running them locally.
=> [tests] Make the PassLibrary tests a bit more lenient.

tools/devops/automation/scripts/bash/generate-workload-rollback.sh, tools/devops/automation/scripts/bash/install-workloads.sh, tools/devops/automation/scripts/run-generator-tests-on-windows.ps1, tools/devops/automation/scripts/run-local-windows-tests.ps1, tools/devops/automation/scripts/run-remote-windows-tests.ps1
This makes it easier to run these scripts locally.
=> [devops] Make a few scripts a bit more self-contained by computing BUILD_REPOSITORY_TITLE if it's not already set.

docs/build-apps/build-properties.md, msbuild/Xamarin.MacDev.Tasks/Tasks/ALToolUpload.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/ALToolValidate.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/AlTool.cs, msbuild/Xamarin.Shared/Xamarin.iOS.Common.targets
This has a few advantages:
* We simplify and unify more of our code.
* We have more control over the error reporting / logging behavior.
Additionally:
* Use 'xcrun' to invoke 'altool' (partial fix for #3931).
* Allow for overriding the path to the command-line tool in question.
* Add support for cancellation.
* Fix nullability.
=> [msbuild] Port the ALToolUpload and ALToolValidate tasks to subclass XamarinTask.

mk/xamarin.mk
Fixes:
* https://github.com/xamarin/maccore/commit/9be5868253 [mlaunch] Try to be a bit more resilient when connecting to a device fails.
* https://github.com/xamarin/maccore/commit/3f0e86d245 [mlaunch] We can't create a tcp tunnel with devicectl, so use the old style AMDevice approach instead.
* Fixes #21664.
* https://github.com/xamarin/maccore/commit/3a1d11f4fd [mlaunch] Print stdout/stderr as we get it from devicectl.
* Fixes #21644.
Diff: https://github.com/xamarin/maccore/compare/fb16d52d12bc2e13b6f39d7d589115fa641f99df..9be5868253c4b604e6beb0997354619c47296304
=> Bump mlaunch

docs/website/mtouch-errors.md, tools/dotnet-linker/Steps/ManagedRegistrarStep.cs
Fixes AOT warnings like these:
> Unable to compile method 'ObjCRuntime.NativeHandle Foundation.NSDispatcher/__Registrar_Callbacks__:callback_1509_Foundation_NSDispatcher__ctor (intptr,intptr,byte*,intptr*)' due to: 'Cannot create an abstract class: Foundation.NSDispatcher assembly:<unknown assembly> type:<unknown type> member:(null)'.
=> [managed static registrar] Don't try to create instances of abstract types.

src/AudioUnit/AUEnums.cs
Also add a few more missing error codes from previous Xcode updates, and
remove some unnecessary availability attributes.
=> [AudioToolbox] Implement Xcode 16.2 beta 1-3 changes in AudioToolbox.

Directory.Build.props
Fixes https://github.com/xamarin/xamarin-macios/issues/21671.
=> [msbuild] Use earlier version of MSBuild assemblies. Fixes #21671.

src/rgen/Microsoft.Macios.Generator/BindingSourceGeneratorGenerator.cs, src/rgen/Microsoft.Macios.Generator/Context/ClassBindingContext.cs, src/rgen/Microsoft.Macios.Generator/Context/SymbolBindingContext.cs, src/rgen/Microsoft.Macios.Generator/DataModel/CodeChanges.cs, src/rgen/Microsoft.Macios.Generator/DataModel/CodeChangesEqualityComparer.cs, src/rgen/Microsoft.Macios.Generator/Emitters/EmitterFactory.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/ClassCodeChangesTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/CodeChangesComparerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/CodeChangesEqualityComparerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/CodeChangesTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/EnumDeclarationCodeChangesTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/InterfaceCodeChangesTests.cs
Update the data model to detect changes in protocols:
1. Events
2. Properties
3. Methods
Removed the reference to the BaseTypeSyntaxtDeclaration so that we can reuse the data model with other projects.
=> [RGen] Add code needed to detect changes in interface.

msbuild/Xamarin.MacDev.Tasks/Tasks/CreateAssetPack.cs, msbuild/Xamarin.Shared/Xamarin.iOS.Common.targets
This has a few advantages:
* We simplify and unify more of our code.
* We have more control over the error reporting / logging behavior.
Additionally:
* Use 'xcrun' to invoke 'zip' (partial fix for #3931).
* Allow for overriding the path to the command-line tool in question.
* Add support for cancellation.
=> [msbuild] Port the CreateAssetPack task to subclass XamarinTask.

tests/cecil-tests/SetHandleTest.KnownFailures.cs, tests/cecil-tests/SetHandleTest.cs
NSObject.Handle is virtual (because it's an implementation of
INativeObject.Handle), so it can be called with 'callvirt' - which means we
can't filter to only 'call' instructions, we need to look for 'callvirt'
instructions as well.
=> [tests] Fix SetHandleTest to handle 'callvirt'.

src/Foundation/NSAttributedString.cs, src/Foundation/NSObject2.cs, src/foundation.cs, tests/monotouch-test/Foundation/AttributedStringTest.cs
Managed constructors can't fail gracefully, which means that constructors with
an "out NSError" parameter doesn't make much sense. Instead bind these
constructors using a factory method.
Ref: https://github.com/xamarin/xamarin-macios/pull/16804#issuecomment-2500025776
Fixes https://github.com/xamarin/xamarin-macios/issues/14489.
=> [Foundation] Improve the NSAttributedString constructors. Fixes #14489.

tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-UIKit.ignore, tests/xtro-sharpie/api-annotations-dotnet/iOS-UIKit.ignore, tests/xtro-sharpie/api-annotations-dotnet/macOS-ScreenCaptureKit.ignore, tests/xtro-sharpie/api-annotations-dotnet/tvOS-UIKit.ignore, tests/xtro-sharpie/xtro-sharpie/FieldCheck.cs
The same native field may be declared in multiple frameworks, and if we remove
it from the list of managed fields we've matched, then we'll report the
binding as missing when we find it in the second framework.
Instead keep track of the fields we've matched in a separate hash table, and
use that to figure out which fields haven't been matched.
=> [xtro] Don't remove fields we've found from existing list of managed fields.

tests/xtro-sharpie/Makefile
Inside a template we need double escaping.
=> [xtro] Fix quiet commands in the makefile.

tools/devops/automation/templates/build/build.yml
Always report the build status, that way we'll automatically hide any previous
build failure comments.
=> [devops] Improve comment when a build completes.

src/bgen/DocumentationManager.cs, tests/cecil-tests/Documentation.cs
Roslyn's code for reference:
https://github.com/dotnet/roslyn/blob/bbff74e481aaf2c6d05949891a64c0d8ac533cf8/src/Compilers/CSharp/Portable/DocumentationComments/DocumentationCommentIDVisitor.PartVisitor.cs#L105-L109
=> [src/tests] Fix computing docid for generic method parameters.

src/MapKit/MKUserLocation.cs, src/frameworks.sources, src/mapkit.cs, tests/xtro-sharpie/api-annotations-dotnet/common-MapKit.ignore
It's important that MKUserLocation class implements the IMKAnnotation
interface, because a MKUserLocation instance might be passed as a parameter to
a function that takes an IMKAnnotation. If the managed class doesn't implement
the interface, this can result in an InvalidCastException at runtime.
Fixes https://github.com/xamarin/xamarin-macios/issues/21759.
=> [MapKit] Manually make MKUserLocation implement the MKAnnotation protocol. Fixes #21759.

tests/monotouch-test/CoreText/StringAttributes.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/21561.
=> [tests] Uncommont code in StringAttributesTests triggering crash that Apple has now fixed. Fixes #21561.

tests/monotouch-test/SystemConfiguration/NetworkReachabilityTest.cs
Ignore the TransientConnection flag on the asserted flags (another test also
does this).
Fixes this random test failure:
[FAIL] CtorNameAddress :   Reachable
Expected: Reachable
But was:  TransientConnection, Reachable
=> [tests] Adjust NetworkReachabilityTest.CtorNameAddress a bit.

src/rgen/Microsoft.Macios.Generator/Availability/PlatformAvailability.cs, src/rgen/Microsoft.Macios.Generator/Availability/PlatformAvailabilityBuilder.cs, src/rgen/Microsoft.Macios.Generator/DictionaryComparer.cs
To ensure a more consistent code generation we are moving to use SortedDictionary<K, KV> so that we always have the same order in the generatd attributes.
=> [Rgen] Move unsupported and obsoleted versions to a sorted dict.

mk/xamarin-reset.sh, tools/devops/automation/templates/build/api-diff-build-and-detect.yml, tools/devops/automation/templates/build/build.yml, tools/devops/automation/templates/pipelines/api-diff-pipeline.yml
Since incorporating the adr repository, the APIDIFF pipeline is failing since it does a cli checkout of the adr repository and it doesn't have the proper credentials to complete the checkout.
=> Fix APIDiff 

runtime/exports.t4, runtime/runtime.m
This means the debugger will be notified of all marshalled exceptions, and
consider them unhandled (and break the debugged app into the debugger).
There's no corresponding change for CoreCLR, because we have no configuration
where we can attach a debugger to a CoreCLR-based app (VSCode doesn't support
macOS, and NativeAOT doesn't support debugging).
Partial fix for https://github.com/xamarin/xamarin-macios/issues/15037.
Fixes https://github.com/dotnet/maui/issues/7176.
Ref: https://github.com/dotnet/android/pull/6106
=> [runtime] Call mono_debugger_agent_unhandled_exception when an exception is marshalled.

dotnet/Microsoft.iOS.Windows.Sdk/targets/Microsoft.iOS.Windows.Sdk.props, dotnet/Microsoft.iOS.Windows.Sdk/targets/Microsoft.iOS.Windows.Sdk.targets, msbuild/Makefile, msbuild/Xamarin.HotRestart.PreBuilt/Makefile
This avoids having to update APIScan exclusions for different locations for
these files.
=> [msbuild] Move some Windows-related files back to an iOS-specific directory.

Directory.Build.props
This seems to be the version in Mono: https://github.com/mono/mono/pull/21073
In particular we need the IBuildEngine9 interface, because the ILStrip task needs it:
https://github.com/dotnet/runtime/blob/3aa1ec5bb1f50f0a1bed9cfcac8734f742bcf24b/src/tasks/MonoTargetsTasks/ILStrip/ILStrip.cs#L78
The IBuildEngine9 interface was introduced in MSBuild 16.10 (around March 2021):
https://github.com/dotnet/msbuild/commit/1629921c2b537d4452ff238981bd18519b8f5230
=> [msbuild] Bump to Microsoft.Build 16.10.0.

src/ObjCRuntime/PlatformAvailability.cs, src/ObjCRuntime/PlatformAvailability2.cs, src/ObjCRuntime/PlatformAvailabilityShadow.cs, src/bgen/Attributes.cs, src/browserenginekit.cs, src/corelocation.cs, src/coremotion.cs, src/mapkit.cs, src/metal.cs, src/networkextension.cs, src/pdfkit.cs, src/social.cs, src/uikit.cs
The generator doesn't handle duplicates well - often it's random which version is looked at, which is not ideal if the attributes are different.
Technically this is a source-breaking change for the generator, but it should be easy to fix api definitions, and it avoids a potential random behavior from the generator.
=> [src] Fix duplicate availability attributes.

mk/xamarin-reset.sh
* Fix local checkout to only pass the extra http header if we have a SYSTEM_ACCESSTOKEN.
* Use a bash array to store authorization arguments, because quoting each
argument actually works when expanding an array into arguments - in
particular expanding an empty array expands into nothing (this avoids a
problem where DEPENDENCY_AUTH would be expanded into an empty (and quoted)
string, which would execute doing 'git ""', and "" is not a git command.)
* Fix clone command to not forget the 'clone' part of 'git clone ...'
=> [mk] Fix adr checkout.

tests/introspection/ApiProtocolTest.cs
These show up / fail on macOS 15.2+.
=> [introspection] Ignore a few protocol conformances for ScreenCaptureKit types.

dotnet/.gitignore, dotnet/Makefile, dotnet/package/microsoft.workloads.csproj, scripts/generate-workloaddependencies-json/README.md, scripts/generate-workloaddependencies-json/fragment.mk, scripts/generate-workloaddependencies-json/generate-workloaddependencies-json.cs, scripts/generate-workloaddependencies-json/generate-workloaddependencies-json.csproj
Fixes https://github.com/xamarin/xamarin-macios/issues/21768.
=> [release/9.0.1xx] [dotnet] Create and ship a WorkloadDependencies.json file. Fixes #21768.

dotnet/Workloads/SignList.xml, msbuild/Directory.Build.props, msbuild/ILMerge.targets, msbuild/Messaging/Xamarin.Messaging.Build/App.config, msbuild/Xamarin.MacDev.Tasks/MsBuildTasks/Exec.cs, msbuild/Xamarin.MacDev.Tasks/Xamarin.MacDev.Tasks.csproj
Xamarin.Messaging major version 3 means the replacement of the underlying MQTT library used for message communication. We've replaced the System.Net.Mqtt with MQTTnet (repo under the dotnet org). More details here: https://github.com/xamarin/Xamarin.Messaging/pull/818
For this reason, we also need to remove any System.Net.Mqtt reference from signing lists or ILMerge, and add MQTTnet instead.
This PR also removes the System.Security.Cryptography.ProtectedData runtime implementation handling, since the new version used by Messaging (8.0.0) doesn't include a specific Windows runtime implementation, so we don't need to do this extra MSBuild handling to reference the right assemblies anymore
Backport of #21767
=> [release/9.0.1xx] [xma] Updated Xamarin.Messaging to 3.0.13

tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/MergeAppBundleTaskTest.cs
It's not necessary; this already happens on the bots before the test run
anyway, so any work done here is redundant on the bots. It's even timing out
(after two minutes) on some test runs, which means this should save up to two
minutes for the msbuild tests on the bots.
=> [tests] Don't run 'make' in 'tests/tests-libraries' as part of test setup.

src/rgen/Microsoft.Macios.Generator/DataModel/Constructor.cs, src/rgen/Microsoft.Macios.Generator/DataModel/ConstructorComparer.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/ClassCodeChangesTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/CodeChangesEqualityComparerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/ConstructorComparerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/ConstructorTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/ConstructorsEqualityComparerTests.cs
This way, when we start generating the code we do not need to calculate the changes and this structure will take into account any changes in the class availability.
=> [RGen] Add the platform availability as part of the constructor data model

src/rgen/Microsoft.Macios.Generator/DataModel/Method.cs, src/rgen/Microsoft.Macios.Generator/DataModel/MethodComparer.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/ClassCodeChangesTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/CodeChangesComparerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/InterfaceCodeChangesTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/MethodComparerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/MethodEqualityComparerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/MethodTests.cs
This way we have all the needed data when generated the generated code taking into account the availability of the parent objects.
=> [RGen] Add the platform availabiltiy to the method data model.

src/rgen/Microsoft.Macios.Generator/Availability/PlatformAvailability.cs, src/rgen/Microsoft.Macios.Generator/Availability/PlatformAvailabilityBuilder.cs, src/rgen/Microsoft.Macios.Generator/Availability/SymbolAvailability.cs, src/rgen/Microsoft.Macios.Generator/Availability/SymbolAvailabilityBuilder.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Accessor.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Event.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Property.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Availability/PlatformAvailabilityTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Availability/PlatformAvailabilityToStringTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Availability/SymbolAvailabilityToStringTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/AccessorTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/AccessorsEqualityComparerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/ClassCodeChangesTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/CodeChangesComparerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/CodeChangesEqualityComparerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/EventEqualityComparerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/EventTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/InterfaceCodeChangesTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/PropertiesEqualityComparerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/PropertyTests.cs
Add the data in the model as well as the availability data to the accessors. We have not modified the events data model in this PR, we only focused on properties.
Added ToString implementations to simplify the test debugger and fixed a bug in one of the constructors in which the structure was not creating a copy of the dictionary but was keeping the ref that was passed to the structure, this resulted in undesirable side effects when modifying the collection.
=> [RGen] Add the platform availability as part of the property data model.

src/rgen/Microsoft.Macios.Generator/DataModel/CodeChanges.cs, src/rgen/Microsoft.Macios.Generator/DataModel/CodeChangesEqualityComparer.cs, src/rgen/Microsoft.Macios.Generator/Extensions/SemanticModelExtensions.cs, src/rgen/Microsoft.Macios.Generator/ListComparer.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/ClassCodeChangesTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/CodeChangesComparerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/CodeChangesEqualityComparerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/InterfaceCodeChangesTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Extensions/SemanticModelExtensionsTests.cs
We add the name and a collection with the namespaces that contains the type. This way we do not need to query the symbol when generating code and we can simply use the data in the structure.
=> [RGent] Add name and namespace to the codechanges struct.

src/rgen/Microsoft.Macios.Generator/DataModel/CodeChanges.cs, src/rgen/Microsoft.Macios.Generator/DataModel/CodeChangesEqualityComparer.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Constructor.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Method.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Property.cs, src/rgen/Microsoft.Macios.Generator/Extensions/SemanticModelExtensions.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/ClassCodeChangesTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/CodeChangesComparerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/CodeChangesEqualityComparerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/InterfaceCodeChangesTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Extensions/SemanticModelExtensionsTests.cs
Reduce the amount of work we need to do in the code generation by precalculating the availability of the class. This way we can later use the code change struct to generate the code.
=> [RGen] Add the named type symbol platform availability to the code change struct.

tests/rgen/Microsoft.Macios.Bindings.Analyzer.Tests/BindingTypeSemanticAnalyzerTests.cs, tests/rgen/Microsoft.Macios.Bindings.Analyzer.Tests/SmartEnumsAnalyzerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/BaseGeneratorTestClass.cs, tests/rgen/Microsoft.Macios.Generator.Tests/BindingSourceGeneratorGeneratorTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Context/RootBindingContextTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/ClassCodeChangesTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/CodeChangesTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/ConstructorTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/EnumDeclarationCodeChangesTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/EventTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/InterfaceCodeChangesTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/MethodTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/PropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/EmitterFactoryTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Extensions/BaseTypeDeclarationSyntaxExtensionsTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Extensions/CompilationExtensionsTest.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Extensions/FieldSymbolExtensionsTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Extensions/MemberDeclarationSyntaxExtensionsTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Extensions/NamedTypeSymbolExtensionsTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Extensions/SemanticModelExtensionsTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Extensions/TypeSymbolExtensionsTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/SmartEnum/SmartEnumDiagnosticsTests.cs
Use the CallerMemberNameAttribute to retrieve the name of the calling method and compilation time rather than using nameof. This allows the test writters to just pass the name if needed, otherwise it will be calculated implicitly by the compiler.
reference: https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.callermembernameattribute?view=net-9.0
=> [RGen] Remove the need to explicitly pass a name for the compilation in tests.

dotnet/targets/Xamarin.Shared.Sdk.targets
This speeds up the inner dev loop, because:
* The dedup assembly must be AOT-compiled for arm64
* arm64 is the default target architecture on more and more devices/macs
* AOT-compilation is slow
So disabling the dedup optimization in this case makes the build faster, because we don't have to AOT-compile something that doesn't exist.
Build times of a new MAUI app (`dotnet new maui`):
| -                              | with dedup   | without dedup |
| ------------------------------ | -----------: | ------------: |
| Simulator (Debug)              | 18 s         | 8 s           |
| Device (Debug)                 | 32 s         | 22 s          |
| Device (Release, interpreter)  | 43 s         | 18 s          |
| Device (Release, fullaot)      | 1m20 s       | 1m40 s        |
App size:
| - …
=> [dotnet] Disable dedup optimization if we're interpreting every assembly.

src/ObjCBindings/BindingTypeAttribute.cs, src/ObjCBindings/BindingTypeTag.cs, src/ObjCBindings/ExportTag.cs, src/frameworks.sources, src/rgen/Microsoft.Macios.Binding.Common/Microsoft.Macios.Binding.Common.csproj, src/rgen/Microsoft.Macios.Generator/Attributes/BindingTypeData.cs, src/rgen/Microsoft.Macios.Generator/DataModel/BindingData.cs, src/rgen/Microsoft.Macios.Generator/DataModel/BindingType.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/BindingDataTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/EnumMemberCodeChangesTests.cs
We want to be able to store as parte of the code change struct any information related to the binding type. To do so we have a new BindingTypeAttribute that is generic to allow extra config.
We also provide a new struct that works as a union of all the supported generic BindingTypeAttribute, that way we can add that new struct (in a follow up PR) to the code change struct.
=> [Rgen] Provide a way to parse the generic BindingTypeAttribute and an union struct.

src/rgen/Microsoft.Macios.Generator/DataModel/CodeChanges.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/ClassCodeChangesTests.cs
We precalculate the values form the modifiers, this later makes is simpler when writing the code generator to check those modifiers we are interested in without falling in the trap of executing the same LINQ query over an over.
=> [Rgen] Add helper properties to determine if a code change was for a static, abstract or partial class.

src/Makefile.rgenerator
Build the generator before the analyzer, because both of these projects
reference Microsoft.Macios.Binding.Common.csproj, and building both in
parallel will randomly run into issues with NuGet restoring packages for
Microsoft.Macios.Binding.Common.csproj for both builds simulataneously, which
will fail randomly (building the analyzer before the generator would also
work).
Fixes this build error:
/Users/builder/azdo/_work/20/a/change-detection/tmp/src/xamarin-macios/builds/downloads/dotnet-sdk-9.0.102-servicing.24610.2/sdk/9.0.102/NuGet.targets(170,5): error : The file '/Users/builder/azdo/_work/20/a/change-detection/tmp/src/xamarin-macios/src/rgen/Microsoft.Macios.Binding.Common/obj/Microsoft.Macios.Binding.Common.csproj.nuget.g.props' already exists.
make[1]: *** …
=> [rgen] Fix concurrent build problem with rgen.

tools/devops/automation/run-ci-api-diff.yml, tools/devops/automation/run-pr-api-diff.yml
This allows the pipeline to be triggered by the build allowing us to not need to tell azp to run apidiff and simply use '/azp run xamarin-macios-pr'
=> [CI] Make the API diff be triggered as soon as the config of the build is done.

src/rgen/Microsoft.Macios.Generator/BindingSourceGeneratorGenerator.cs, src/rgen/Microsoft.Macios.Generator/Context/BindingContext.cs, src/rgen/Microsoft.Macios.Generator/Emitters/CategoryEmitter.cs, src/rgen/Microsoft.Macios.Generator/Emitters/ClassEmitter.cs, src/rgen/Microsoft.Macios.Generator/Emitters/EmitterFactory.cs, src/rgen/Microsoft.Macios.Generator/Emitters/EnumEmitter.cs, src/rgen/Microsoft.Macios.Generator/Emitters/ICodeEmitter.cs, src/rgen/Microsoft.Macios.Generator/Emitters/TrampolineEmitter.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/EmitterFactoryTests.cs
Emitter should not store internal state that will changes based on the processed code changes. This means we can reduce the number of objects we create to the minimum amount. This change will reduce the memory usage specially when building the Apple SDK which has 100s of classes to generated.
=> [Rgen] Do not create an emitter per code change.

src/rgen/Microsoft.Macios.Generator/DataModel/Constructor.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Method.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Parameter.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/ConstructorTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/MethodTests.cs
By tracking if the parameter is an array we can later generate the method signature in a more robust manner since we can diff between and array parameter or params parameter when generating code.
=> [Rgen] Add extra data in the parameter struct to know if a parameter is an array.

src/ObjCRuntime/RegistrarHelper.cs
The managed static registrar depends on each assembly registering itself to
find types from that assembly. This is done using a module constructor, but
the module constructor isn't necessarily executed before the managed static
registrar needs the assembly registered (in particular for app extensions,
which don't have a managed entry point).
That would lead to exceptions like this:
*** Terminating app due to uncaught exception 'ObjCRuntime.RuntimeException', reason: 'Could not find the type 'ObjCRuntime.__Registrar__' in the assembly '...'. (ObjCRuntime.RuntimeException)
at ObjCRuntime.RegistrarHelper.GetMapEntry(String assemblyName)
at ObjCRuntime.RegistrarHelper.GetMapEntry(Assembly assembly)
[...]
Fix this by manually calling the module constructor for every loaded assembly
if we can't …
=> [ObjCRuntime] Ensure all assemblies' module constructors have executed before failing registrar lookup.

src/rgen/Microsoft.Macios.Generator/BindingSourceGeneratorGenerator.cs, src/rgen/Microsoft.Macios.Generator/TabbedStringBuilder.cs, tests/rgen/Microsoft.Macios.Generator.Tests/TabbedStringBuilderTests.cs
Reuse the same string builder and clear it before every iteration, this way the GC does not have to keep track of that many string builders.
=> [Rgen] Do not create a string builder per binding.

src/rgen/Microsoft.Macios.Generator/DataModel/Constructor.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Parameter.cs, src/rgen/Microsoft.Macios.Generator/DataModel/ReferenceKind.cs, src/rgen/Microsoft.Macios.Generator/Formatters/ConstructorFormatter.cs, src/rgen/Microsoft.Macios.Generator/Formatters/MethodFormatter.cs, src/rgen/Microsoft.Macios.Generator/Formatters/ParameterFormatter.cs, src/rgen/Microsoft.Macios.Generator/Formatters/PropertyFormatter.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/ClassCodeChangesTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/ConstructorTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/ReferenceKindTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Formatters/ConstructorFormatterTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Formatters/MethodFormatterTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Formatters/PropertyFormatterTests.cs
Use the SyntaxFactory from roslyn to format the data model to a c# compilation unit.
The methods have been added as extension so that if other tools (sharpie/migration) need to modify the formatting, the can easily do it.
=> [Rgen] Provide extension methods that will return a member declaration from the data model.

src/ObjCRuntime/RegistrarHelper.cs
The managed static registrar depends on each assembly registering itself to
find types from that assembly. This is done using a module constructor, but
the module constructor isn't necessarily executed before the managed static
registrar needs the assembly registered (in particular for app extensions,
which don't have a managed entry point).
That would lead to exceptions like this:
*** Terminating app due to uncaught exception 'ObjCRuntime.RuntimeException', reason: 'Could not find the type 'ObjCRuntime.__Registrar__' in the assembly '...'. (ObjCRuntime.RuntimeException)
at ObjCRuntime.RegistrarHelper.GetMapEntry(String assemblyName)
at ObjCRuntime.RegistrarHelper.GetMapEntry(Assembly assembly)
[...]
Fix this by manually calling the module constructor for every loaded assembly
if we can't …
=> [release/9.0.1xx] [ObjCRuntime] Ensure all assemblies' module constructors have executed before failing registrar lookup.

src/rgen/Microsoft.Macios.Generator/DataModel/Accessor.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Event.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Property.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/AccessorTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/AccessorsEqualityComparerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/ClassCodeChangesTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/CodeChangesComparerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/CodeChangesEqualityComparerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/EventEqualityComparerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/EventTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/InterfaceCodeChangesTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/PropertiesEqualityComparerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/PropertyTests.cs
This change keeps track of the usage of the export attribute in property
accessors allowing users to change the default selectors used in
properties.
=> [Rgen] Allow to add a export attribute to an accessor.

src/rgen/Microsoft.Macios.Generator/DataModel/Property.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/ClassCodeChangesTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/CodeChangesComparerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/CodeChangesEqualityComparerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/InterfaceCodeChangesTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/PropertiesEqualityComparerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/PropertyTests.cs
We will later use that information for the backing field generation.
=> [Rgen] Keep track in the property struct if the returned type is a ref one.

tools/devops/automation/build-pipeline.yml, tools/devops/automation/build-pull-request.yml, tools/devops/automation/run-ci-api-diff.yml, tools/devops/automation/run-pr-api-diff.yml, tools/devops/automation/templates/api-diff-stage.yml, tools/devops/automation/templates/build/api-diff-stage.yml, tools/devops/automation/templates/build/build-mac-tests-stage.yml, tools/devops/automation/templates/build/build-stage.yml, tools/devops/automation/templates/main-stage.yml, tools/devops/automation/templates/pipelines/api-diff-pipeline.yml, tools/devops/automation/templates/pipelines/run-api-scan.yml, tools/devops/automation/templates/pipelines/run-tests-pipeline.yml, tools/devops/automation/templates/tests-stage.yml, tools/devops/automation/templates/tests/stage.yml
Improve the way we work by:
1. Remove the need to do the autopool selection. This was needed when we had a single pipeline.
2. Make or developers life easier by autimatically build their dev/ branches.
=> [CI] Move away from automatic pool selector and allow builds on dev/*

tools/devops/automation/build-pipeline.yml
This is annoying because there is a diff between PR and CI trigger. PRs will cancel previous builds (which was giving problems due to the auto format). However, now we have the other problem around in which we are executing the build several times. We cannot cancel, but we can batch the builds.
The last commit will always be build.
=> [CI] Batch developer builds in the CI to use resources better.

tests/monotouch-test/System.Net.Http/MessageHandlers.cs
The test fails with:
[FAIL] AcceptSslCertificatesWithCustomValidationCallbackNSUrlSessionHandler("https://self-signed.badssl.com/") :   Status code was not success
[FAIL] AcceptSslCertificatesWithCustomValidationCallbackNSUrlSessionHandler("https://wrong.host.badssl.com/") :   Status code was not success
Debugging a bit it seems that these return 404 "Not Found" now, so it seems something changed on badssl.com's side.
We should probably use a different server we control at some point, but filed
an issue for now (https://github.com/xamarin/xamarin-macios/issues/21912).
=> [tests] Ignore AcceptSslCertificatesWithCustomValidationCallbackNSUrlSessionHandler - fails due to external factors.

docs/building-apps/build-properties.md, msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx, msbuild/Xamarin.MacDev.Tasks/Tasks/ValidateNoStaticLibraries.cs, msbuild/Xamarin.Shared/Xamarin.Shared.targets, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets, tests/dotnet/BundleStructure/shared.csproj, tests/dotnet/UnitTests/WindowsTest.cs, tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/ValidateNoStaticLibraresTests.cs, tools/common/MachO.cs
A fairly common problem is when apps try to use a static library when using
Hot Restart on Windows (which isn't supported), and then they're confused when
their app doesn't work.
Improve this scenario by raising an error if an app tries to link with a
static library when building for Hot Restart.
Add an escape hatch in case someone still wants to build apps with static
libraries using Hot Restart, since there are scenarios where it can be useful
(while testing parts of an app that don't require any static libraries for
instance).
=> [msbuild] Show an error if an app tries to link with a static library when building for Hot Restart.

tests/test-libraries/Makefile
Fix parallel build of test libraries by depending on the right thing when
building xcframeworks: the stamp file of each containing framework.
Depending on the actual binary doesn't work:
1. The entire framework might not be built, only the binary.
2. The binary might not even be the binary, it might only be a symlink to the
binary (for desktop platforms).
Fixes random build failures like:
[...]
GEN      SwiftTest2.xcframework
Determining projects to restore...
ZIP      XTest.framework.zip
SWIFT  [maccatalyst-arm64] libSwiftTest2.dylib
SWIFT  [maccatalyst-x64] libSwiftTest2.dylib
ZIP      SwiftTest.framework.zip
Restored /Users/builder/azdo/_work/9/s/xamarin-macios/tests/test-libraries/testgenerator.csproj (in 131 ms).
xcframework successfully written out to: …
=> [tests] Fix parallel build of test libraries.

tests/monotouch-test/System.Net.Http/MessageHandlers.cs
Hopefully makes assert failures a bit more useful than:
[FAIL] AcceptSslCertificatesWithCustomValidationCallbackNSUrlSessionHandler("https://self-signed.badssl.com/") : Status code was not success
[FAIL] AcceptSslCertificatesWithCustomValidationCallbackNSUrlSessionHandler("https://wrong.host.badssl.com/") : Status code was not success
=> [tests] Improve assert to show status code in case of failure.

tools/devops/automation/scripts/GitHub.psm1
Now that we allow PRs to be executed for our team members via a ci trigger the script that writes the comment does so in the commit (as we do in CI). This breaks the way we are used to work. To fix this problem the github script has been fixed to write the comment in the prs associated with a commit if they are open.
=> [CI] Allow the comments to be written in PRs that were started with a CI trigger

msbuild/Xamarin.MacDev.Tasks/BundleResource.cs
"TRACE" is defined by default, so this ends up always tracing.
Instead use a different conditional compilation symbol.
=> [msbuild] Don't use 'TRACE' to enable verbose tracing.

src/UIKit/UIImage.cs
Fixes this analyzer warning:
error CA2022: Avoid inexact read with 'System.IO.Stream.Read(byte[], int, int)' (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2022)
=> [UIKit] Fix inexact stream read in UIImage.

.editorconfig
This way any other .editorconfig file up the directory hierarchy won't affect
us.
=> Make our .editorconfig a root editor config.

src/ObjCBindings/BindingTypeTag.cs, src/rgen/Microsoft.Macios.Bindings.Analyzer/AnalyzerReleases.Unshipped.md, src/rgen/Microsoft.Macios.Bindings.Analyzer/BindingTypeSemanticAnalyzer.cs, src/rgen/Microsoft.Macios.Bindings.Analyzer/Extensions/BaseTypeDeclarationSyntaxExtensions.cs, src/rgen/Microsoft.Macios.Bindings.Analyzer/Extensions/IBindingTypeAnalyzerExtensions.cs, src/rgen/Microsoft.Macios.Bindings.Analyzer/IBindingTypeAnalyzer.cs, src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.Designer.cs, src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.resx, src/rgen/Microsoft.Macios.Bindings.Analyzer/SmartEnumsAnalyzer.cs, src/rgen/Microsoft.Macios.Generator/AttributesNames.cs, tests/rgen/Microsoft.Macios.Bindings.Analyzer.Tests/BindingTypeSemanticAnalyzerTests.cs, tests/rgen/Microsoft.Macios.Bindings.Analyzer.Tests/SmartEnumsAnalyzerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/AttributesNamesTests.cs
The analyzer now checks the following:
* All usages of `bindingTypeAttribute<T>` have to happen on partial classes.
* `BindingType<Class>` can only be used on classes.
* `BindingType<Category>` can only be used on static classes.
* `BindingType<Protocol>` can only be used on interfaces.
* `BindingType<StrongDictionary>` can only be used on classes.
* `BindingType` can only be used on enums.
Because we have not yet released any of the errors, we have sorted them to be the first ones from 0001-0006.
=> [Rgen] Complete the BindingTypeAttribute analyzer.

src/uikit.cs
UIAccessibility is a category on NSObject, with a comment saying
"UIAccessibility is implemented on all standard UIKit views and controls".
We can't create a single binding that exposes UIAccessibility as that comment
states, and adding it to NSObject will create a lot of noise for all other
types.
So a long time ago we decided to only add UIAccessibility to a few UIKit types
(UIView, UIBarItem and UIImage), but it seems UIApplication should have it
too, so do that.
Fixes https://github.com/xamarin/xamarin-macios/issues/21925.
=> [UIKit] Make UIApplication implement UIAccessibility. Fixes #21925.

src/bgen/Generator.cs, tests/generator/ExpectedXmlDocs.MacCatalyst.xml, tests/generator/ExpectedXmlDocs.iOS.xml, tests/generator/ExpectedXmlDocs.macOS.xml, tests/generator/ExpectedXmlDocs.tvOS.xml, tests/generator/tests/xmldocs.cs
CS1573 is raised when some, but not all, parameters in a method have xml
comments.
The generated code can trigger this when an api definition has a method with
documented parameters, and then the generator creates a method with additional
parameters (which won't have xml comments).
=> [src] Ignore CS1573 in certain cases.

src/ObjCBindings/FieldTag.cs, src/rgen/Microsoft.Macios.Generator/Attributes/FieldData.cs, src/rgen/Microsoft.Macios.Generator/AttributesNames.cs, src/rgen/Microsoft.Macios.Generator/DataModel/CodeChanges.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Property.cs, src/rgen/Microsoft.Macios.Generator/Extensions/TypeSymbolExtensions.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Attributes/ExportDataTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/AttributesNamesTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/ClassCodeChangesTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/CodeChangesTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/InterfaceCodeChangesTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/PropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Extensions/TypeSymbolExtensionsTests.cs
We cannot use Export because we need to be ablet to pass the library name to generate the property field correctly. This change moves from using Export<Field> to Field<Property> which allows to mark a property as a field AND will allow use to add the library name.
This change + the one in PR
https://github.com/xamarin/xamarin-macios/pull/21945 improves the way the Library.g.cs file is generated.
=> [RGen] Use the correct attribute for field properties.

src/rgen/Microsoft.Macios.Generator/DataModel/Method.cs, src/rgen/Microsoft.Macios.Generator/DataModel/MethodComparer.cs, src/rgen/Microsoft.Macios.Generator/DataModel/MethodsEqualityComparer.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Property.cs, src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfo.cs, src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfoComparer.cs, src/rgen/Microsoft.Macios.Generator/Formatters/TypeInfoFormatter.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/CodeChangesComparerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/MethodComparerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/PropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/TypeInfoComparerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/TypeInfoTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/TestDataFactory.cs
Also renamed the ReturnType.Type property to name to make it clear in the future when we are going to add a MetadataName in the struct to be able to differenciate between a nint and a IntPtr.
=> [RGent] Rename ReturnType to TypeInfo.

src/rgen/Microsoft.Macios.Generator/DataModel/CodeChanges.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Constructor.cs, src/rgen/Microsoft.Macios.Generator/DataModel/EnumMember.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Event.cs, src/rgen/Microsoft.Macios.Generator/DataModel/FieldInfo.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Method.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Property.cs, src/rgen/Microsoft.Macios.Generator/Emitters/EnumEmitter.cs, src/rgen/Microsoft.Macios.Generator/Emitters/LibraryEmitter.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/ClassCodeChangesTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/EnumMemberCodeChangesTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/FieldInfoTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/InterfaceCodeChangesTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/PropertyTests.cs
Provide a small wrapper struct that we can use to keep the infomation of a field data attr realted to its library name and path. This is later needed to generate the appropate getters and setters.
=> [RGen] Keep track of the libs needed for enums and fields.

tests/dotnet/UnitTests/MlaunchTest.cs
It seems this changes whenever Xcode 16.2 is installed on a machine, even if
Xcode 16.2 is not the currently selected Xcode.
=> [release/8.0.1xx-xcode16.0] [tests] Update the default simulator name for iOS.

src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfo.cs, tests/rgen/Microsoft.Macios.Generator.Tests/TestDataFactory.cs
This is needed to generate any possible casting when interacting with the native platform.
=> [Rgen] If a type is an enum, keep track of its underlying type.

tests/monotouch-test/ObjCRuntime/RegistrarTestGenerated.cs
Ref: https://github.com/xamarin/xamarin-macios/issues/19781
Also remove some outdated watchOS ignores.
Backport of #21322, #21403 and #21451.
=> [release/8.0.1xx-xcode16.0] [tests] Ignore a few tests that fail on desktop/arm64.

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Dlfcn.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Runtime.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryTests.cs
Add the initial implementation of a syntax factory that can be used to generate the C# calls needed by the bindings.
This implementation only contains the Getter methods needed to retrieve fields in order to keep PRs in a reasonable size.
Example usage when writing bindings:
```csharp
sb.AppendRaw($@"
if ({property.Name} is null)
{property.Name} = {FieldConstantGetter (property)};
return {property.Name}
";
```
The API takes advantage of the fact that the data model has all the needed info and the makes the code cleaner when importing it with a status using.
=> [Rgen] Add a binding syntax factory that will generate C# expressions.

src/rgen/Microsoft.Macios.Generator/Extensions/TypeSymbolExtensions.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/EventTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/PropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Extensions/TypeSymbolExtensionsTests.cs
Accessors are not contained in the property symbol but are associated to it. We needed to update the method to take that into account.
=> [Rgen] Add properties as part of the parent's list of accessors.

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Dlfcn.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.cs, src/rgen/Microsoft.Macios.Generator/Extensions/SpecialTypeExtensions.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryTests.cs
This commit has the following important changes to carefully review:
1. We move to make the method name otpional in the GetConstant and SetConstant. This is done by the CallerMemberName attribute which will add the name automatically to match the caller. This is done at compile time and is equal to nameof. This way we reduce typing and typos.
2. Added a tuple to return the getter and setter. This way we make sure that when we add support for a new kind of field, that we add both.
3. For those fields that we cannot set, we return a throw expression. Ideally this will never happen because we will make sure the analyzer stops us from trying to use Set properties on unsupported type.
4. Added support for casting in the Setter. We are using a lambda factory that captures the type of the …
=> [Rgen] Add support to the syntax factory to generate setters for fields.

tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/PropertyTests.cs
Add some extra tests to cover more properties combinations.
PS: I thought we had a bug, we didn't but is always nice to cover more cases.
=> [RGen] Add some extra tests for properties.

src/rgen/Microsoft.Macios.Generator/DataModel/Accessor.cs, src/rgen/Microsoft.Macios.Generator/Microsoft.Macios.Generator.csproj, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/AccessorTests.cs
The method takes into account the property associated with the accessor and any possible export method that has been added to the accessor itself.
The setter label for the default case uses the Registrar.core code.
=> [RGen] Provide a method that returns the selector for an accessor.

src/rgen/Microsoft.Macios.Generator/DataModel/Parameter.cs, src/rgen/Microsoft.Macios.Generator/DataModel/ParameterComparer.cs, src/rgen/Microsoft.Macios.Generator/Formatters/ParameterFormatter.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/ClassCodeChangesTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/CodeChangesComparerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/CodeChangesEqualityComparerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/ConstructorComparerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/ConstructorTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/ConstructorsEqualityComparerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/DelegateInfoTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/InterfaceCodeChangesTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/MethodComparerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/MethodEqualityComparerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/MethodTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/TestDataFactory.cs
This will later be used to be able to correctly calculate the signature of the ObjCRuntime messaging method to perform a native call to a property or method.
=> [Rgen] Move to use TypeInfo as the Type property in Parameters.

src/rgen/Microsoft.Macios.Generator/AttributesNames.cs, src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfo.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/TypeInfoTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/TestDataFactory.cs
We want to be able to know if a symbol is:
* An Interface
* An enumerator with a native attribute.
* If the interger used a C# keyword to be created.
=> [Rgen] Add more information about the type in the TypeInfo struct.

scripts/rsp-to-csproj/rsp-to-csproj.cs
The script could not handle setting the roslyn analyzer reporting, we need to add a single property for that in the csproj.
=> [Build] Fix the script that converts rsp to csproj when verbose is enabled.

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Dlfcn.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.cs, src/rgen/Microsoft.Macios.Generator/Emitters/ClassEmitter.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/ExpectedCIImage.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryFieldAccessorsTests.cs
Add the code generation for getters and setters for fields. The way this change works is by updating how we write the code in the getter/setter blocks.
The changes are:
1. Update the syntax factory to add the null forgiveness operator when getting a native nsstring.
2. Write the getter and setter implementations based on the return type of the property. If the object is a reference type, we use the baking field of the property, else we call the native code directly.
=> [Rgen] Add field getters and setters.

src/rgen/Microsoft.Macios.Generator/DataModel/Accessor.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Accessor.cs, src/rgen/Microsoft.Macios.Generator/DataModel/CodeChanges.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/CodeChanges.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Constructor.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Constructor.cs, src/rgen/Microsoft.Macios.Generator/DataModel/EnumMember.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/EnumMember.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Event.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Event.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Method.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Method.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Property.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Property.cs, src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfo.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfo.cs, src/rgen/Microsoft.Macios.Transformer/Attributes/ExportData.cs, src/rgen/Microsoft.Macios.Transformer/Attributes/FieldData.cs, src/rgen/Microsoft.Macios.Transformer/DataModel/Accessor.Transformer.cs, src/rgen/Microsoft.Macios.Transformer/DataModel/BindingInfo.cs, src/rgen/Microsoft.Macios.Transformer/DataModel/CodeChanges.Transformer.cs, src/rgen/Microsoft.Macios.Transformer/DataModel/EnumMember.Transformer.cs, src/rgen/Microsoft.Macios.Transformer/DataModel/Method.Transformer.cs, src/rgen/Microsoft.Macios.Transformer/DataModel/Property.Transformer.cs, src/rgen/Microsoft.Macios.Transformer/DataModel/TypeInfo.Transformer.cs, src/rgen/Microsoft.Macios.Transformer/Extensions/TypeSymbolExtensions.Transformer.cs, src/rgen/Microsoft.Macios.Transformer/Microsoft.Macios.Transformer.csproj
In this change we are making the necesary changes to share the data model code between the generator and the transformer.
When we talk about sharing code in C# the average dotnet developer would create a csproj with the shared code and would reference it. In normal circumtances this is not a bad option, but our case is different and here are some of the reasons we cannot take that path:
1. Roslyn code generators with more than one dll are problematic to distribute. You can already see how bad it is by looking at the dll shared between the code generator and the analyzer. The shared library has to be added as an analyzer so that it loads with the generator. We want to keep the number of dlls to a minimun.
2. While the data models are similar, they are not identical. The attributes used by …
=> [Rgen] Share DataModel between the generator and the transformer.

src/rgen/Microsoft.Macios.Bindings.Analyzer/Microsoft.Macios.Bindings.Analyzer.csproj, src/rgen/Microsoft.Macios.Generator/Availability/AvailabilityTrivia.cs, src/rgen/Microsoft.Macios.Generator/Availability/PlatformAvailability.cs, src/rgen/Microsoft.Macios.Generator/Availability/SymbolAvailability.cs, src/rgen/Microsoft.Macios.Generator/Extensions/ApplePlatformExtensions.cs, src/rgen/Microsoft.Macios.Transformer/Microsoft.Macios.Transformer.csproj, tests/rgen/Microsoft.Macios.Generator.Tests/Availability/AvailabilityTriviaTests.cs
If we are generating code, specially in the transformer, that does not have a specific platform, we need to generate the correct trivia to ensure that methods are not generated in the wrong platform.
=> [Rgen] Add a new struc that will represent the needed trivia for a symbol.

src/rgen/Microsoft.Macios.Transformer/Attributes/ExportData.cs, src/rgen/Microsoft.Macios.Transformer/Attributes/FieldData.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/ExportDataTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/FieldDataTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/DataModel/FieldDataTests.cs
Provide the missing code to parse the Foundation.FieldAttribute.
=> [RGen] Add the code to parse the field attribute in the transformer.

src/rgen/Microsoft.Macios.Transformer/Attributes/BaseTypeData.cs, src/rgen/Microsoft.Macios.Transformer/Attributes/ExportData.cs, src/rgen/Microsoft.Macios.Transformer/Attributes/FieldData.cs, src/rgen/Microsoft.Macios.Transformer/DataModel/BindingInfo.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/BaseTypeDataTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/ExportDataTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/FieldDataTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/DataModel/FieldDataTests.cs
Parse the attribute and retrieve all the needed data. We will use the full name type for events rather than a INamedType.
=> [Rgen] Add the parsing code for the BaseTypeAttribute in the transformer.

dotnet/Workloads/SignList.xml
These are now signed in their original build pipeline https://github.com/xamarin/XamarinVS/pull/14522
=> [release/9.0.1xx] [CI] Update signing list for imobiledevice

src/rgen/Microsoft.Macios.Generator/Attributes/MarshalDirective.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Property.cs, src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfo.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfo.cs, src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfoComparer.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Dlfcn.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.ObjCRuntime.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.cs, src/rgen/Microsoft.Macios.Generator/Extensions/EnumExtensions.cs, src/rgen/Microsoft.Macios.Generator/Extensions/SpecialTypeExtensions.cs, src/rgen/Microsoft.Macios.Generator/Formatters/ParameterFormatter.cs, src/rgen/Microsoft.Macios.Generator/Formatters/TypeInfoFormatter.cs, src/rgen/Microsoft.Macios.Transformer/Microsoft.Macios.Transformer.csproj, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/TypeInfoComparerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/TypeInfoToMarshallTypeTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/GetObjCMessageSendMethodNameTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Extensions/EnumExtensionTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/TestDataFactory.cs
Add the code that will calculate the signature needed in the objc_msgSend which will be the method that calls the native objc message.
When we create a binding for a native type we need to be able to send 'messages' to the objc objects. From a C# developer perspective a message can be considered a method. So for example, the following objc code:
```objc
[object foo:bar];
```
Can be translated to: 
```c
objc_msgSend(object, sel_getUid("foo:"), bar);
```
We can say this process is similar to reflection and the[ Invoke method](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.methodbase.invoke?view=net-9.0). Our bindings provide methods around [objc_msgsend](https://developer.apple.com/documentation/objectivec/1456712-objc_msgsend) which we use to send the messaged with the …
=> [Rgen] Add the needed code to make the objc_msgSend signatures.

src/rgen/Microsoft.Macios.Generator/BindingSourceGeneratorGenerator.cs, src/rgen/Microsoft.Macios.Generator/Context/BindingContext.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Binding.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Binding.cs, src/rgen/Microsoft.Macios.Generator/DataModel/BindingEqualityComparer.cs, src/rgen/Microsoft.Macios.Generator/Emitters/CategoryEmitter.cs, src/rgen/Microsoft.Macios.Generator/Emitters/ClassEmitter.cs, src/rgen/Microsoft.Macios.Generator/Emitters/EmitterFactory.cs, src/rgen/Microsoft.Macios.Generator/Emitters/EnumEmitter.cs, src/rgen/Microsoft.Macios.Generator/Emitters/ICodeEmitter.cs, src/rgen/Microsoft.Macios.Generator/Emitters/InterfaceEmitter.cs, src/rgen/Microsoft.Macios.Generator/Emitters/TrampolineEmitter.cs, src/rgen/Microsoft.Macios.Generator/Formatters/SmartEnumFormatter.cs, src/rgen/Microsoft.Macios.Transformer/DataModel/CodeChanges.Transformer.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/BindingComparerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/BindingEqualityComparerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/BindingTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/ClassBindingTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/EnumDeclarationCodeChangesTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/InterfaceCodeChangesTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/EmitterFactoryTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Formatters/SmartEnumFormatterTests.cs
Initially the structure was name to make it simpler to understand that it was a code change/update that was detected by the roslyn incremental generator. Now that the structure is shared with the transformer, it makes more sense to rename it to 'Binding'.
We have update all the helper classes too.
=> [Rgen] Renamed CodeChanges to Binding to be more clear.

src/rgen/Microsoft.Macios.Generator/TabbedStringBuilder.cs, src/rgen/Microsoft.Macios.Transformer.Generator/Microsoft.Macios.Transformer.Generator/Microsoft.Macios.Transformer.Generator.csproj
In theory we can use net9.0 but some editors need netstandard2.1. We don't want yet to move Rgen, but we do want to move the transformer one beause it makes workign with the project easier.
=> [RGen] Make the transformer generator be netstandard2.1 to make editors happy.

src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfo.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfo.cs, src/rgen/Microsoft.Macios.Generator/Extensions/TypeSymbolExtensions.Core.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Extensions/TypeSymbolExtensionsInheritanceTests.cs
Dictionary containers require a special marshaling when we use them in the msgSend functions. Keep track of that fact in the TypeInfo so that we can make sure that it is correctly dealt with.
=> [Rgen] Keep track if a type is a dictionary container.

src/rgen/Microsoft.Macios.Generator/Extensions/CompilationExtensions.cs, tests/common/Configuration.cs, tests/rgen/Microsoft.Macios.Generator.Tests/BaseGeneratorTestClass.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Extensions/CompilationExtensionsTest.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Microsoft.Macios.Generator.Tests.csproj
Use the current compilation preprocessor symbols to determine which of the UI namespaces are present in the compilation.
=> [Rgen] Provide a method to return the current UI namespaces.

src/rgen/Microsoft.Macios.Transformer.Generator/Microsoft.Macios.Transformer.Generator/XamarinBindingAPIGenerator.cs, src/rgen/Microsoft.Macios.Transformer/AttributesNames.cs
We cannot use an  or a & we need to provide a list, that leater is tested against a flag that has been either | or &.
=> [Rgen] Fix a bug in how the target flags are managed.

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.ObjCRuntime.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryObjCRuntimeTests.cs
This is needed because the pinvokes do not use bools but bytes.
=> [Rgen] Add method in the syntax factory to cast a bool to a byte.

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.ObjCRuntime.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryObjCRuntimeTests.cs
Case to the underlying type if it is not a smart enum, else use the CastToNative method.
=> [Rgen] Add needed factory methods to cast an enum to its primitive type.

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.ObjCRuntime.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryObjCRuntimeTests.cs
To be able to send arrays to objc we need to convert them to a NSArray. This change adds a factory method that will create the aux variables for when we need that conversion.
The factory allows to prepend the declaration with a using caluse to simplify the memory management in the bindings.
=> [Rgen] Add factory method that creates a NSArray aux variable.

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.ObjCRuntime.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryObjCRuntimeTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/TestDataFactory.cs
When we interact with nstobjects we need to send the Hanldes as a parameter and not the managed object. This new method will generated the aux variable needed to store the handle and use it in the message send objc method.
=> [Rgen] Add a factory method that will create the aux variable for handles.

src/rgen/Microsoft.Macios.Transformer/Attributes/SnippetData.cs, src/rgen/Microsoft.Macios.Transformer/AttributesNames.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/SnippetDataTests.cs
Allow the transformer to detect this. We will need to think a way to port them to the new API style.
=> [Rgen] Add code needed to parse the several snippet attrs.

tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/AsyncDataTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/AttributeParsingTestClass.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/BackingFieldTypeDataTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/BaseTypeDataTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/BindDataTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/CoreImageFilterDataTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/CoreImageFilterPropertyTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/ErrorDomainDataTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/ExportDataTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/FieldDataTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/NativeDataTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/SnippetDataTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/StrongDictionaryDataTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/ThreadSafeDataTests.cs
The tests for the attr parsing for all attrs are very similar, we can create a generic test that can be reused by all and that way mantain less code and be faster when adding a new test.
=> [Rgen] Create a generic method that can be used to test all attr parsing.

src/ObjCBindings/ExportTag.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Property.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Property.cs, src/rgen/Microsoft.Macios.Transformer/DataModel/Property.Transformer.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/PropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/TestDataFactory.cs
Add some new properties, to be only used by the generator, in the property data model to decide the inclusion of a backing field and if this field needs to be checked.
We have moved the ToString method to the .Generator and .Transformer files so that we can reflect the two new properties. The same has happened for the Equals method.
=> [Rgen] Add properties in the Property data model to decide if a field is needed.

src/rgen/Microsoft.Macios.Transformer/Attributes/NotificationData.cs, src/rgen/Microsoft.Macios.Transformer/AttributesNames.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/BindDataTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/NotificationDataTests.cs
Allow the transformer to parse notification attrs.
=> [Rgen] Provide the needed code to parse notification attrs.

src/rgen/Microsoft.Macios.Generator/Extensions/TypeSymbolExtensions.Core.cs, src/rgen/Microsoft.Macios.Transformer/Attributes/BindAsData.cs, src/rgen/Microsoft.Macios.Transformer/AttributesNames.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/BindAsDataTests.cs
This change is a little more interesting than the others because I had to update the way we retrieve the attributes. Return attrbutes are only present on a special collection for IMethodSymbols, this meant that we had to add an extra pass for those attributes in the generic method in pur extensions.
=> [Rgen] Add the needed code to parse a BindAsAttriubte.

src/rgen/Microsoft.Macios.Transformer/Attributes/AsyncData.cs, src/rgen/Microsoft.Macios.Transformer/Attributes/BackingFieldTypeData.cs, src/rgen/Microsoft.Macios.Transformer/Attributes/BaseTypeData.cs
No need to add more tests because they all ready cover all valid uses.
=> [Rgen] Use ITypeSymbol over INamedTypeSymbol since they interface is more general and will give less problems.

tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/StrongDictionaryDataTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Microsoft.Macios.Transformer.Tests.csproj
Lets be strict in everythig we do, that includes tests. Set the warnings to be errors and fix the one we had.
=> [Rgen] Set warnings to errors in the transformer tests.

src/ObjCBindings/BindFromAttribute.cs, src/frameworks.sources, src/rgen/Microsoft.Macios.Bindings.Analyzer/Microsoft.Macios.Bindings.Analyzer.csproj, src/rgen/Microsoft.Macios.Generator/Attributes/BindFromData.cs, src/rgen/Microsoft.Macios.Generator/Attributes/FieldData.cs, src/rgen/Microsoft.Macios.Generator/AttributesNames.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Method.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Method.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Parameter.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Parameter.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Property.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Property.cs, src/rgen/Microsoft.Macios.Generator/Extensions/TypeSymbolExtensions.Core.cs, src/rgen/Microsoft.Macios.Generator/Extensions/TypeSymbolExtensions.Generator.cs, src/rgen/Microsoft.Macios.Transformer/DataModel/Method.Transformer.cs, src/rgen/Microsoft.Macios.Transformer/DataModel/Parameter.Transformer.cs, src/rgen/Microsoft.Macios.Transformer/DataModel/Property.Transformer.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Attributes/FieldDataTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/EnumMemberCodeChangesTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/MethodTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/PropertyTests.cs
The BindFromAttribute is similar to the BindAsAttribute but in the opossite direction. This allows the bindings to be cleaner since we can specify in the partial method the return type we really want and the NSNumber/NSString transformation will be done in the generated code.
=> [RGen] Implement the BindFrom attribute.

src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfo.Generator.cs, src/rgen/Microsoft.Macios.Transformer/DataModel/Parameter.Transformer.cs, src/rgen/Microsoft.Macios.Transformer/DataModel/TypeInfo.Transformer.cs, tests/rgen/Microsoft.Macios.Generator.Tests/TestDataFactory.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/DataModel/ParameterTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Microsoft.Macios.Transformer.Tests.csproj
The transformer and the code generation share 90% of the data model, but we need a 10% that is used to fix the mismatch between two projects.
In this change we finish the implementation fo the TypeInfo struct in the transformer by providing the TryCreate method that will use the attribute data to decide if a type was marked as nullable or not.
Remember that in the old xamarin bindings we did not use the ? annotation but we use the NullAllowedAttribute.
=> [Rgen] Start implementing the missing parts of the data model for the transformer.

src/rgen/Microsoft.Macios.Generator/DataModel/Method.cs, src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfo.Generator.cs, src/rgen/Microsoft.Macios.Transformer/AttributesNames.cs, src/rgen/Microsoft.Macios.Transformer/DataModel/Method.Transformer.cs, src/rgen/Microsoft.Macios.Transformer/DataModel/Parameter.Transformer.cs, src/rgen/Microsoft.Macios.Transformer/DataModel/TypeInfo.Transformer.cs, tests/rgen/Microsoft.Macios.Generator.Tests/TestDataFactory.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/DataModel/MethodTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/DataModel/ParameterTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Microsoft.Macios.Transformer.Tests.csproj
Add the missing methods for the transformer to be ablet to create a data model representation of a method.
=> [Rgen] Add the method data model missing pieces for the transformer.

src/ObjCBindings/BindingTypeAttribute.cs, src/ObjCBindings/BindingTypeTag.cs, src/ObjCBindings/ExportAttribute.cs, src/ObjCBindings/ExportTag.cs, src/rgen/Microsoft.Macios.Generator/Attributes/BindingTypeData.cs, src/rgen/Microsoft.Macios.Generator/AttributesNames.cs, src/rgen/Microsoft.Macios.Generator/DataModel/AttributeCodeChange.cs, src/rgen/Microsoft.Macios.Generator/DataModel/BindingType.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/CoreImageFilterTests.cs, tools/devops/automation/scripts/GitHub.psm1
In the new binding API we want to be able to differentiate between a Class and a CoreImageFilter. This PR adds a new flag that can be used by the generator to identify the binding type and route the code generation to the correct emitter. This change allows the API to look as follows:
```csharp
// the following binding represents a class
[BindingType<Class> (Name="MyNSObject")
public partial class MyNSObjectClass : NSObject {
// export methods, properties, events etc..
}
// the following binding represents a core Image filter
[BindingType<CoreImageFilter> (Name="MyNSObject")
public partial class MyNSObjectClass : NSObject {
// export methods, properties, events etc..
}
```
The change also allows to customize the visibility of the core image filters like the following example:
```csharp …
```
=> [RGen] Add a new flag to determine if a type is a core image filter.

src/rgen/Microsoft.Macios.Generator/DataModel/Parameter.Generator.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.ObjCRuntime.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/ParameterTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryObjCRuntimeTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/TestDataFactory.cs
This change allows to be able to generate an aux variable that will be needed if a customer defined a export method in the following way:
```csharp
[Export<Method> ()]
public virtual partial void MyMethod ([BindFrom (typeof (NSNumber))] double myDouble);
```
The above binding API indicates that the native method in objc will take a NSNumber but we want to expose our users a double. In order to send a NSNumber to objc, we need to declare an aux variable that will be used for the native method invocation.
=> [RGen] Add factory method needed to create a aux variable for a BindFrom(typeof(NSNumber)).

src/rgen/Microsoft.Macios.Generator/TabbedStringBuilder.cs, tests/rgen/Microsoft.Macios.Generator.Tests/TabbedStringBuilderTests.cs
There are ocassions in which in we want to be able to concatenate several blocks one after the other. The most common scenario is when we are using fixed or using blocks. To make the code cleaner we do not want to create a collection of nested calls like:
```csharp
using (var m1 = new MemoryStream())
{
using (var m2 = new MemoryStream())
{
using (var m3 = new MemoryStream())
{
// this is an example with several usings
}
}
}
```
instead we want the generator to write:
```csharp
using (var m1 = new MemoryStream())
using (var m2 = new MemoryStream())
using (var m3 = new MemoryStream())
{
// this is an example with several usings
}
```
This new CreateBlock method takes an collection of lines and writes a single block similar to the one in the above example.
=> [Rgen] Add a new CreateBlock method for several concatenated blocks.

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.ObjCRuntime.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryObjCRuntimeTests.cs
This change allows to be able to generate an aux variable that will be needed if a customer defined a export method in the following way:
```csharp
[Export<Method> ()]
public virtual partial void MyMethod ([BindFrom (typeof (NSValue))] CGPoint point);
```
The above binding API indicates that the native method in objc will take a NSValue but we want to expose our users a CGPoint. In order to send a NSValue to objc, we need to declare an aux variable that will be used for the native method invocation.
=> [Rgen] Add a factory method to create the aux variable for a BindFrom(typeof(NSValue)).

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.ObjCRuntime.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryObjCRuntimeTests.cs
This method is the final step to be able to generate the aux variable for a BindFrom decorated parameter. We just need to perform a switch on the type of the BindFrom attribute to decide the final declaration needed.
=> [RGen] Add BindFrom factory method that will return the correct declaration.

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.ObjCRuntime.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryObjCRuntimeTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/TestDataFactory.cs
We forgot to add support for an array of value. We allow suers to do [BindFrom (NSNumer)] on a method that returns an array. This means that we need to generate an NSArray that we will use to call the native code.
There are 3 possible cases:
1. Array of enums (it people ever choose to do it).
2. Array of NSNumber.
3. Array of NSValue.
The above 3 create the following aux variables accordingly:
```csharp
// enum
var nsb_myParam = NSArray.FromNSObjects (obj => obj.GetConstant(), myParam)
// nsnumber
var nsb_myParam = NSArray.FromNSObjects (obj => new NSNumber (obj), myParam)
// nsValue
var nsb_myParam = NSArray.FromNSObjects (obj => new NSValue (obj), myParam)
```
=> [Rgen] Add the needed factory method to generate NSArrays for the BindFrom attr.

src/rgen/Microsoft.Macios.Generator/IO/TabbedWriter.cs, tests/rgen/Microsoft.Macios.Generator.Tests/IO/TabbedStringBuilderTests.cs
Add all the async methods than can be added to the class. Do remember the following about async methods during the review:
1. We cannot use 'ref' parameters for a async method.
2. We cannot use ref readonly structs parameters and Span is one.
3. We cannot use those same types inside the body of an asyc method. So WriteRaw has to do the string allocations.
The Async methods are meant for the transformer, which is a project in which we can use async IO and we do not need to worry about memory in the same way we do in the roslyn code generator.
=> [RGen] Provide async methods for the TabbedWriter.

src/rgen/Microsoft.Macios.Generator/IO/TabbedWriter.cs, src/rgen/Microsoft.Macios.Transformer/IO/TabbedStreamWriter.cs, src/rgen/Microsoft.Macios.Transformer/Microsoft.Macios.Transformer.csproj, tests/rgen/Microsoft.Macios.Generator.Tests/IO/TabbedStringBuilderTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/IO/TabbedStreamWriterTests.cs
The transformer can and will write to disk as opposed to the generator which needs to write to a string builder. We implement a file based stream writer that provides the same API plus it allows to perform the async IO for the transformer.
=> [Rgen] Provide a StreamWriter indent writer for the transformer.

src/rgen/Microsoft.Macios.Generator/IO/TabbedWriter.cs, tests/rgen/Microsoft.Macios.Generator.Tests/IO/TabbedStringBuilderTests.cs
GitHub should have stopped this, it allowed a merge that should have had a clash. Remove the duplicated methods.
=> [Rgen]Remove duplicated methods after bad merge.

src/rgen/Microsoft.Macios.Generator/DataModel/Constructor.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Method.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Parameter.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Property.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfo.Generator.cs
This changes a little the way we create parameters and types because we need the compilation target to know if a type needs a stret call.
We do not use the NeedsStret in the equlas method because that information has not value when we are deciding if a type needs to be regenerated or not by the roslyn code generator.
=> [RGen] Keep track in the generator if a type needs a stret call.

tests/dotnet/UnitTests/ProjectTest.cs
Fixes a few tests failures in .NET 10 (when the default value for
BundleOriginalResources switches from `false` to `true`).
=> [tests] Update BuildBundledResources test to actually take into account the 'BundleOriginalResources' value.

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.ObjCRuntime.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryObjCRuntimeTests.cs
There is no need to have a special case in that method. We can use the new added 'Using' method. Update the tests to show that the results are identical but with a more homogeneus API.
=> [Rgen] Remove the special case in the NSArray aux variable.

src/rgen/Microsoft.Macios.Generator/DataModel/Constructor.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Constructor.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Method.cs, src/rgen/Microsoft.Macios.Transformer/DataModel/Binding.Transformer.cs, src/rgen/Microsoft.Macios.Transformer/DataModel/Constructor.Transformer.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/DataModel/BindingMethodTests.cs
Add the parsing of methods and constructor in the data model for the transformer.
=> [Rgen] Add support for the Methods/Constructors in the transformer.

src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfo.Generator.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.ObjCRuntime.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryObjCRuntimeTests.cs
There are some cases in which we need to store the return type of a method/property in a variable before we return it. Create a factory that will return the name of the return variable and its declaration.
=> [Rgen] Add factory method to generate the return variable.

builds/Makefile
CDN locations changed, so we need a script that uses the correct CDN.
=> [builds] Get the very latest dotnet-install.sh script.

src/CoreVideo/CVBuffer.cs, src/WebKit/WKPreferences.cs
* Remove redundant OS version checks (if the OS checked for is earlier than
the earliest we support).
* Bring CVBuffer.GetAttachment<T> to macOS to unify API across all platforms.
* Rearrange code so that the indentation is the same on all conditional code
paths (that way code formatters don't fight depending on which conditional
compilation symbols are defined).
=> [CoreVideo/WebKit] Refactor code a bit to unify indentation.

src/rgen/Microsoft.Macios.Generator/Context/BindingContext.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.ObjCRuntime.cs, src/rgen/Microsoft.Macios.Generator/Emitters/ClassEmitter.cs, src/rgen/Microsoft.Macios.Generator/Extensions/ExportDataExtensions.cs, src/rgen/Microsoft.Macios.Generator/Extensions/StringExtensions.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/iOSExpectedPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/macOSExpectedPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/tvOSExpectedPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryObjCRuntimeTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Extensions/ExportDataExtensionsTests.cs
Ensure that rgen adds the static readonly fields needed for the selectors in a class. We do so by:
1. Keeping track if the selectors in the binding context.
2. Provide the same logic as used by bgen for the field names.
3. Add two new factory methods that will write the local declaration syntaxt for the fields.
We have added tests for:
1. The selector name calculation.
2. The factory methods.
3. Update the expected generated code for a class with propeties.
=> [Rgen] Add the selector fields to the generated classes.

tests/rgen/Microsoft.Macios.Bindings.Analyzer.Tests/BaseGeneratorWithAnalyzerTestClass.cs, tests/rgen/Microsoft.Macios.Generator.Tests/BaseGeneratorTestClass.cs, tests/rgen/Microsoft.Macios.Generator.Tests/BindingSourceGeneratorGeneratorTests.cs
The code generation will not run several compilations in memory at the same time, but that does happen in the tests.
We have some flacky tests that happen when we have 2 or more compilation at the same time that have different UI namespaces, for example, a MacOS and a iOS compilation. In the situation of having more than one compilation we have a race condition on the extension method that returns the UI namespaces, this is only a problem during the tests. To workaround it, we won't allow the code generation tests run in parallel.
=> [Rgen] Fix flacky tests when doing several compilations in parallel.

src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfo.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/GetObjCMessageSendMethodNameTests.cs
Make sure that the ToMarshallType return a NativeHandle when we are marshalling an array.
=> [Rgen] Fix a bug  in the ToMarshallType with arrays.

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.ObjCRuntime.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Runtime.cs, src/rgen/Microsoft.Macios.Generator/Emitters/ClassEmitter.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryRuntimeTests.cs
Create a factory method that will create the invoke expression for a objc msg method. This factory will prepend the two first parameters, handle and selector, and will add any extra argument nodes to the call.
=> [Rgen] Provide a factory method that creates the objc msg send calls.

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Dlfcn.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.ObjCRuntime.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Property.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Runtime.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.cs, src/rgen/Microsoft.Macios.Generator/Emitters/ClassEmitter.cs, src/rgen/Microsoft.Macios.Generator/Emitters/PropertyInvocations.cs
This will allow to have a struct that will contain all the needed invocation data.
We need to update some of the uses from a CompilationUnit to a StatementSyntax, which actually makes the code better overall while letting us use a throw statement as the invocation statement for a property.
=> [Rgen] Add a property invocations struct to be used with the syntax factory.

src/rgen/Microsoft.Macios.Generator/DataModel/BindingType.cs, src/rgen/Microsoft.Macios.Transformer/DataModel/Binding.Transformer.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/DataModel/BindingTests.cs
Allow to parse StrongDictionaries in the transformer. These bindings are special because we do not filter out properties that are missing the Export/Field attributes.
=> [Rgen] Add support to parse StrongDictionary in the transformer.

src/rgen/Microsoft.Macios.Generator/DataModel/Property.Generator.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Property.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/iOSExpectedPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/macOSExpectedPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/tvOSExpectedPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/PropertyTests/NeedsTempReturnTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryPropertyTests.cs
The use of a temp variable in boolean properties was due to a limitation of how bgen wrote the code. We copied the behaviour to make sure we were compatible, yet that was not needed.
This change adds supports to boolean getters in properties without the need of a temp var.
=> [Rgen] Boolean properties do not need a temp variable.

src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfo.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfo.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Dlfcn.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Property.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Runtime.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.cs, src/rgen/Microsoft.Macios.Generator/Emitters/ClassEmitter.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/iOSExpectedPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/macOSExpectedPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/tvOSExpectedPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/TestDataFactory.cs
Add support to return a NSObject or an array of NSObjects. The changes allow to get the variable assigment from the factory to be used in the writer.
=> [RGen] Support properties that return NSObjects and NSObject[].

src/Foundation/NSNumber2.cs, src/bgen/Generator.cs, src/bgen/TypeManager.cs
When a property that returns an NSNumber array is marked with the BindAs attribute, the bgen code generator uses the following pattern:
```csharp
NativeHandle retvalarrtmp;
ret = ((retvalarrtmp = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, Selector.GetHandle ("sourceSampleDataTrackIDs"))) == IntPtr.Zero ? null! : (NSArray.ArrayFromHandleFunc <int> (retvalarrtmp, ptr => {
using (var num = Runtime.GetNSObject<NSNumber> (ptr)!) {
return (int) num.Int32Value;
}
}, false)));
```
This code can be simplified to use a static group method. So that it looks like:
```csharp
NativeHandle retvalarrtmp;
ret = ((retvalarrtmp = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, Selector.GetHandle ("sourceSampleDataTrackIDs"))) == IntPtr.Zero ? null! : …
```
=> [Bgen] Simplify the BindAs generated code.

tests/xharness/Jenkins/TestServer.cs
In PR https://github.com/dotnet/macios/pull/22154 in an attempt to fix some CodeQL warnings we broke the local execution of xharness.
The reason is the following, CodeQL complained about sanitizing the local path and in an attempt to remove the warning a test to make sure that the local path does not have a '/' was added.
The issue is that our requests, when we run xharness locally, will return localpaths of the form: '/20250221_181807/index.html' that is because the request is for 'http://localhost:51234/20250221_181807/index.html'.
In webapps, the path of the request ALWAYS starts with '/' even when the request is for 'http://localhost:51234' (which returns '/').
In an attemp to fix xharness AND keep CodeQL happy I have made the following changes:
1. Ensure that the full path is one of …
=> [CI] Fix xharness local run.

tools/devops/automation/scripts/fetch-remote-binlogs.ps1, tools/devops/automation/templates/windows/reserve-mac.yml, tools/devops/automation/templates/windows/stage.yml
=> [devops] Make the reserve-mac job checkout like the reenable-mac job.

tests/rgen/Microsoft.Macios.Transformer.Tests/Microsoft.Macios.Transformer.Tests.csproj
When building in CI, check that the platform is included in the env variable to build the API definitions dll.
=> [Rgen] Ensure transformer tests can build with missing platforms.

src/bgen/Generator.cs, tests/generator/bindastests.cs
We do not longer support them in dotnet so we remove the support from bgen and update the tests to use the CoreGraphics alternatives.
If a user adds any of the remove types they will get an exception with an unboxing error.
=> [BGen] Remove support for the System.Drawing objects.

src/webkit.cs
Ref: https://github.com/xamarin/xamarin-macios/issues/15728.
=> [WebKit] Fix nullability in WKUIDelegate.RunJavaScriptTextInputPanel for XAMCORE_5_0.

src/ObjCBindings/ExportAttribute.cs
Looks like we landed code that should have never landed. But there is no issues because the API is marked as experimental. It is the rgen binding API.
=> [Rgen] Remove properties that are part of the binding type.

src/ObjCBindings/FieldAttribute.cs, src/rgen/Microsoft.Macios.Generator/Attributes/FieldData.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Attributes/FieldDataTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/ClassBindingTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/EnumMemberCodeChangesTests.cs
Add the missing notification configuration options for the FieldAttribute. Do remember that we will use the analyzer to make sure that those options are only used when the user passes the notification flag.
=> [RGen] Add missing configuration options for notifications.

src/CoreAnimation/NSValue.cs, src/CoreGraphics/NSValue.cs, src/CoreLocation/NSValue.cs, src/CoreMedia/NSValue.cs, src/Foundation/NSValue.cs, src/MapKit/NSValue.cs, src/SceneKit/NSValue.cs, src/UIKit/NSValue.cs, src/bgen/Generator.cs, src/bgen/TypeManager.cs, src/frameworks.sources
As with previous changes, move to use a method group instead of a lambda with a using block.
We only add the new methods in those platforms that have the specifict frameworks by using partial class. That way we keep the code cleaner than with a collection of #if statements.
=> [Bgen] Simplify the NSValue BindAS generated code.

system-dependencies.sh, tools/devops/automation/templates/tests/build.yml, tools/devops/automation/templates/windows/reserve-mac.yml
Because installing simulators means running a C# project, which requires .NET to build.
Also improve the .NET version check systemdependencies.sh to not blindly try
to execute `dotnet`, but check for its presence first.
This fixes a couple of issues on bots that don't have .NET installed.
=> [devops] Install .NET before trying to install simulators.

src/rgen/Microsoft.Macios.Generator/DataModel/Property.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.cs
Generalize the method so that we can use it with other values that are not properties. This will help later when we are generating the ErrorDomain backing field.
No need to change or add tests since we already test the method. This is an implementation detail change.
=> [Rgen] Generalize backing field method.

dotnet/package/common.csproj, scripts/generate-vs-workload/generate-vs-workload.cs
Context: https://github.com/xamarin/yaml-templates/commit/96d7858cce242c5eea76028f3f051bb9ffda793c
Adds the VS manifest zips needed by the workload versions VS insertion
pipeline to Maestro publishing.
The first update to VS that includes these changes will have to be done
manually, as the manifest names are also changing to work with the new
pipeline.
=> [ci] Publish VS workload zips

src/bgen/Generator.cs
If we look at the implementation of NSArray.ArrayFromHandleFunc we can see that we have the following:
```csharp
// Used when we need to provide our constructor
static public T [] ArrayFromHandleFunc<T> (NativeHandle handle, Func<NativeHandle, T> createObject)
{
if (handle == NativeHandle.Zero)
return null;
var c = GetCount (handle);
T [] ret = new T [c];
for (uint i = 0; i < c; i++)
ret [i] = createObject (GetAtIndex (handle, i));
return ret;
}
```
As you can see, we do not need to check if the passed pointer to the function is IntPtr.Zero as we currently do in the generated code:
```csharp
[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
[BindAs (typeof (global::CoreMedia.CMTime[]), OriginalType = typeof (NSValue[]))]
public virtual …
```
=> [Bgen] Simplify the BindAs of arrays.

dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalyst/csharp/AppDelegate.cs, dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/AppDelegate.cs, dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/AppDelegate.cs, dotnet/Templates/Microsoft.tvOS.Templates/tvos/csharp/AppDelegate.cs, src/uikit.cs, tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-UIKit.ignore, tests/xtro-sharpie/api-annotations-dotnet/iOS-UIKit.ignore, tests/xtro-sharpie/api-annotations-dotnet/tvOS-UIKit.ignore
Fixes https://github.com/dotnet/macios/issues/22278.
=> [UIKit] Fix a few nullability issues in UIApplication[Delegate]. Fixes #22278.

src/rgen/Microsoft.Macios.Bindings.Analyzer/Microsoft.Macios.Bindings.Analyzer.csproj, src/rgen/Microsoft.Macios.Generator/Attributes/BindFromData.cs, src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfo.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfo.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.ObjCRuntime.cs, src/rgen/Microsoft.Macios.Generator/Extensions/TypeSymbolExtensions.Core.cs, src/rgen/Microsoft.Macios.Generator/Extensions/TypeSymbolExtensions.Generator.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/MethodTests/FromDeclarationTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/PropertyTests/FromDeclarationTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryObjCRuntimeTests.cs
Move from using a string to a typeinfo data so that we haver more details about the type that was used.
=> [Rgen] Use TypeInfo as part of the BindAsData property.

Makefile
Hopefully this will fix the build randomly hanging at the end of 'make all'.
=> [build] Shut down the build server after 'make all' as well.

tools/devops/automation/scripts/VSTS.psm1, tools/devops/automation/templates/api-diff-stage.yml, tools/devops/automation/templates/common/configure.yml
This way we correctly detect if we're a pull request when we're in a backport pull request (where the branch name starts with backport-pr-*) or a dependency update from maestro (where the branch name starts with darc-*).
Example failure:
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=11130542&view=logs&s=0f8cf363-55a6-5c89-5a7b-27693abc5647&j=276491e5-a85e-51e3-6c38-98e261218d1a
Note that this branch is not a `dev/*` branch, in order to test this.
=> [devops] Use parameters instead of branch names to determine whether we're a PR or not.

dotnet/package/common.csproj, dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets, dotnet/targets/Xamarin.Shared.Sdk.TargetFrameworkInference.props, dotnet/targets/Xamarin.Shared.Sdk.Trimming.props, dotnet/targets/Xamarin.Shared.Sdk.props, dotnet/targets/Xamarin.Shared.Sdk.targets
These are remains from the initial port to .NET, since we've never supported
watchOS on .NET.
=> [dotnet] Remove any code related to watchOS.

tools/api-tools/mono-api-html/ApiChange.cs, tools/api-tools/mono-api-html/AssemblyComparer.cs, tools/api-tools/mono-api-html/ClassComparer.cs, tools/api-tools/mono-api-html/Comparer.cs, tools/api-tools/mono-api-html/ConstructorComparer.cs, tools/api-tools/mono-api-html/EventComparer.cs, tools/api-tools/mono-api-html/FieldComparer.cs, tools/api-tools/mono-api-html/Formatter.cs, tools/api-tools/mono-api-html/Helpers.cs, tools/api-tools/mono-api-html/HtmlFormatter.cs, tools/api-tools/mono-api-html/MarkdownFormatter.cs, tools/api-tools/mono-api-html/MemberComparer.cs, tools/api-tools/mono-api-html/MultiplexedFormatter.cs, tools/api-tools/mono-api-html/NamespaceComparer.cs, tools/api-tools/mono-api-html/PropertyComparer.cs, tools/api-tools/mono-api-info/mono-api-info.cs
* Simplify and expand how custom attributes are written into the xml description
by not doing any fancy computation about the attribute properties, instead just
write out what's in IL: any constructor arguments + parameter arguments.
* Compare and show attributes for types and members.
* Special-case [Experimental] attributes:
* Adding an [Experimental] attribute to an existing type/member  is a breaking change.
* If a type or a member has an [Experimental] attribute, no changes within are breaking.
* Removal of an obsolete type/member is a breaking change, so show it as such.
=> [mono-api-html] Improve attribute handling.

src/bgen/Generator.cs
The old generated code works but it is certainly interesting...
This changes affects both properties and methods that use the BindAsAttribute for their return type.
Properties:
The following shows an example of the new vs old code generated for property getters:
Old code:
```csharp
public virtual bool? IsCallerIdBlocked {
[Export ("isCallerIdBlocked", ArgumentSemantic.Copy)]
get {
bool? ret;
if (IsDirectBinding) {
NativeHandle retvaltmp;
ret = ((retvaltmp = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, Selector.GetHandle ("isCallerIdBlocked"))) == IntPtr.Zero ? default (bool?) : (Runtime.GetNSObject<NSNumber> (retvaltmp, false)!?.BoolValue));
} else {
NativeHandle retvaltmp;
ret = ((retvaltmp = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper …
```
=> [BGen] Simplify the BindAs generated code for NSNumber and NSValue.

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Runtime.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryRuntimeTests.cs
This call is used in several places for the BindAs/BindFrom attribute. The factory method allows to pass the expected return type and a list or arguments.
=> [RGen] Add factory method to create a NSArray.ArrayFromFunc call.

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Runtime.cs, src/rgen/Microsoft.Macios.Transformer/AttributesNames.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryRuntimeTests.cs
There was an error (yy probably) in which we used the wrong struct to parse the threadsafe attribute.
=> [RGen] Fix bug that was using the wrong struct to parse an attribute.

eng/Version.Details.xml, eng/Versions.props
Changes: http://github.com/dotnet/macios/compare/8354d6d971c635925ef7b26da8b04305b5b3035a...0ee28379dd5e85c830bad0270d064bbcec467647
Updates the previous .NET 8/Xcode 16.0 versions to the latest package
versions that are available in VS.
=> Update .NET 8/Xcode 16.0 ref to 18.0.8319

src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfo.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Runtime.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryRuntimeTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/TestDataFactory.cs
Array types a special because we have to track the array element type rathern that the actual SpecialType of the array (which is SpecialType.None).
We add a new property to our data model to track the special type of the element and we create a helper tuple to keep the switch expression clean. This could have been done without the helper tuple, but the code look a lot worse, the compiler is smart enough to remove that extra tuple.
=> [RGen] Return the correct NSNumber static method when we have an array.

tests/dotnet/UnitTests/BundleStructureTest.cs, tests/dotnet/UnitTests/PostBuildTest.cs, tests/dotnet/UnitTests/ProjectTest.cs, tests/dotnet/UnitTests/PublishTrimmedTest.cs
We don't support 32-bit iOS architectures anymore, so these test cases do
nothing.
=> [tests] Remove test cases for 32-bit iOS architectures.

src/rgen/Microsoft.Macios.Generator/Emitters/EnumEmitter.cs, src/rgen/Microsoft.Macios.Generator/Nomenclator.cs, tests/rgen/Microsoft.Macios.Generator.Tests/NomenclatorTests.cs
We will want to be able to generate code that references to the generated classes. Rather than having a pattern placed all over the project, we create a static class that given a string it will return the name to be used by the emitters.
This, for example, will later be useful when we want to call the extension methods for a smart enum.
=> [Rgen] Split the naming logic form the emitters.

tests/xtro-sharpie/Makefile
At the moment there's nothing useful for us here.
=> [BrowserEngineCore] Ignore this framework.

tests/common/shared-dotnet.csproj, tests/xharness/Jenkins/TestVariationsFactory.cs
This way it's set when building tests from the command line as well.
=> [tests] Set 'IlcTreatWarningsAsErrors=false' in csproj instead of from xharness for tests.

tools/devops/automation/templates/windows/build.yml
That way we run as many tests as we can before completely failing.
=> [devops] Only fail the Windows test run after running the bgen tests.

src/CoreText/CTParagraphStyle.cs, src/CoreText/CTStringAttributes.cs, src/ObjCRuntime/Class.cs, src/ObjCRuntime/DisposableObject.cs, src/ObjCRuntime/RegistrarHelper.cs, src/UIKit/UIAppearance.cs, src/UIKit/UIConfigurationColorTransformer.cs, src/UIKit/UIFont.cs, src/UIKit/UIGestureRecognizer.cs, src/rgen/Microsoft.Macios.Bindings.Analyzer/NativeObjectHandleAnalyzer.cs, tests/rgen/Microsoft.Macios.Bindings.Analyzer.Tests/NativeObjectHandleAnalyzerTests.cs
Update the analyzer to ignore the following cases:
- `a.Handle ==/!= b.Handle` equality comparisons
- `Class`/`Selector` is considered non-collectible
Address feedback
=> [dev/filipnavara/handle-gchole] Address PR feedback

.github/workflows/bump-global-json.yml
Example PR where this didn't happen: https://github.com/dotnet/macios/pull/22381
=> [actions] Run the global.json bumping action for dotnet/arcade bumps as well.

src/rgen/Microsoft.Macios.Bindings.Analyzer/DataModel/Parameter.Analyzer.cs, src/rgen/Microsoft.Macios.Bindings.Analyzer/Microsoft.Macios.Bindings.Analyzer.csproj, src/rgen/Microsoft.Macios.Generator/DataModel/Binding.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Parameter.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Parameter.cs, src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfo.cs, src/rgen/Microsoft.Macios.Transformer/DataModel/Parameter.Transformer.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/DelegateInfoTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/TestDataFactory.cs
This is done to accommodate the fact that we want to be able to generate the trampoline code from a TypeInfo because it's the most general struct that is both used for parameters and return types.
This later will allow use to have factory methods similar to the ones we have that target the trampoline code generation.
=> [Rgen] Move the DelegateInfo struct as part of the type info.

tests/dotnet/Windows/InstallDotNet.csproj
With the CDN changes the old location wasn't correct anymore.
Fixes https://github.com/dotnet/macios/issues/21418 (the other items there were already done)
=> Fix the DotNetInstallScriptBackupUrl to point to new location

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.ObjCRuntime.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Runtime.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryRuntimeTests.cs
The NSArray.FromNSObject is used in several parts of the code generation, for example trampolines will use it too. We generalize the call so that we can easily do function composition to generate the code.
=> [Rgen] Generalize NSArray.FromNSObject to later use it for other code generation.

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.ObjCRuntime.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Runtime.cs
The expression is needed to write the trampolines, extract it from the current methods that use it to be reused.
No need for tests since we already have test that exercise the method.
=> [Rgen] Extract the CFString.CreateNative expression to be reused.

src/bgen/Generator.cs
We used to generate:
```csharp
return NSArray.FromNSObjects(retval).Handle;
```
We now generate:
```csharp
return NSArray.FromNSObjects(retval).GetHandle ();
```
=> [Bgen] Use GetHandle in the trampoline NSArray code.

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Runtime.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryRuntimeTests.cs
Allows to create the expression:
```csharp
x == IntPtr.Zero ? null : expr;
```
The above expression is very common when generating bindings that are nullable.
=> [Rgen] Add ternary IntPtr.Zero check expression factory.

src/rgen/Microsoft.Macios.Generator/AttributesNames.cs, src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfo.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfo.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.ObjCRuntime.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Runtime.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Trampoline.cs, src/rgen/Microsoft.Macios.Transformer/Attributes/XamarinAvailabilityData.cs, src/rgen/Microsoft.Macios.Transformer/AttributesNames.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryRuntimeTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryTrampolineTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/AsyncDataTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/BackingFieldTypeDataTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/BaseTypeDataTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/BindAsDataTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/BindDataTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/CoreImageFilterDataTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/CoreImageFilterPropertyTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/ErrorDomainDataTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/ExportDataTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/FieldDataTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/NativeDataTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/NotificationDataTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/SnippetDataTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/StrongDictionaryDataTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/Attributes/ThreadSafeDataTests.cs
Based on the return type of a delegate we need to generate code to convert the native return type of the trampoline to that used by the managed delegate.
This new function takes the type info of the return type of the delegate and the name of the aux variable and generates the correct conversion.
=> [RGen] Generate code for the return type of a trampoline delegate.

src/rgen/Microsoft.Macios.Generator/DataModel/Parameter.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfo.Generator.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.ObjCRuntime.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Property.cs, src/rgen/Microsoft.Macios.Generator/Nomenclator.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/ParameterTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/NomenclatorTests.cs
This way we have all the naming in a single location and it is easier to make sure that we do name variables in a consistent manner.
This also removes the need of some of the special code for the generator in the data model.
=> [Rgen] Move most of the naming logic to the Nomenclator.

src/rgen/Microsoft.Macios.Bindings.Analyzer/BindingTypeSemanticAnalyzer.cs, src/rgen/Microsoft.Macios.Bindings.Analyzer/SmartEnumsAnalyzer.cs, src/rgen/Microsoft.Macios.Generator/AttributesNames.cs, src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfo.cs, src/rgen/Microsoft.Macios.Generator/Extensions/TypeSymbolExtensions.Generator.cs, tests/rgen/Microsoft.Macios.Generator.Tests/AttributesNamesTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/EnumDeclarationCodeChangesTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/PropertyTests/FromDeclarationTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/TestDataFactory.cs
This will later allow use to make decisions when generating code. To add this new flag we did the following:
* Make the variables that store the attribute names in the Generator and Transformer be the same. This way we make sharing the logic easier.
* Check if the protocol attr is present on a symbol when we retrieve its info.
* Clean the HashCode and ToString methods to reflect the new data.
* Add a new test on the property tests to assert that we indeed get the new flag set correctly.
=> [RGen] Add a flag to know if a type represents a Objc protocol.

tests/xtro-sharpie/Makefile, tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-LockedCameraCapture.todo, tests/xtro-sharpie/api-annotations-dotnet/iOS-LockedCameraCapture.ignore
At the moment there's nothing useful for us here, seems to be a Swift-only
framework.
=> [LockedCameraCapture] Ignore this framework.

tests/cecil-tests/PreviewApi.cs
It's undetermined when it'll be made non-experimental, so tentatively plan for
.NET 99.0.
=> [tests] Verify that everything in the ObjCBindings namespace is experimental.

tools/devops/automation/templates/windows/build.yml
We include them in the aggregate test results for all tests, so there's no
need to report the Windows tests specifically as well.
=> [devops] Don't report the test results from the Windows tests.

src/bgen/Generator.cs
This is an interesting change. After working on PR https://github.com/dotnet/macios/pull/22417 we noticed that we had a serious problem in how we called extension methods.
To understand the problem we first need to look at the code generation for an extension method:
```csharp
[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
internal static float _GetValue (ICIHueSaturationValueGradientProtocol This)
{
return global::ObjCRuntime.Messaging.float_objc_msgSend (This.Handle, Selector.GetHandle ("value"));
}
```
The issue with the above code is that the GC can collect the 'This' object while is being used by the objc_msgSend method. For this type of methods to be safe we would need to perform a call to GC.KeepAlive on This.
Fixing the generator is not as easy …
=> [Bgen] Ensure that GC.KeepAlive is called in extension methods.

docs/configuration-properties.md, dotnet/targets/Xamarin.Shared.Sdk.targets
Disable Metrics support when `Optimize=true` (instead of when `Release=true`) to avoid depending on a configuration.
This makes our logic identical to Android's logic: https://github.com/dotnet/android/pull/9928.
=> [net10.0] [dotnet] Disable Metrics support when Optimize=true.

src/bgen/Extensions/ParameterInfoExtensions.cs, src/bgen/Generator.cs, tests/generator/BGenTests.cs, tests/generator/generic-type-nsobject.cs
Generic parameter types are special and in reflection do not show as the Type that was given as a constrain. This is problematic because the generator tests for IsWrappedType or IsNativeObject do not work on a generic type.
This is a patch to get the current bindings working with generic parameters from generic classes. Once this is landed we will be able to detect if the types is a wrapped one and we can call GC.KeepAlive when needed.
=> [BGen] Fix argument tests for generic types.

src/rgen/Microsoft.Macios.Bindings.Analyzer/NativeObjectHandleAnalyzer.cs, tests/rgen/Microsoft.Macios.Bindings.Analyzer.Tests/NativeObjectHandleAnalyzerTests.cs
The analyzer returns a lot of false positives for a very common usage pattern in the generated code:
```csharp
if (foo) {
XMethod (x.Handle);
} else {
YMethod (x.Handle);
}
GC.KeepAlive (x);
```
This change takes into account this pattern and ignores those false positives. The code is not a general solution, it just accounts for a very well known pattern.
=> [RGen] Fix an issue with the GC.KeepAlive analyzer.

tests/xtro-sharpie/Makefile, tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-BrowserKit.todo, tests/xtro-sharpie/api-annotations-dotnet/iOS-BrowserKit.todo
At the moment there's nothing useful for us here.
=> [BrowserKit] Ignore this framework.

tests/monotouch-test/MapKit/LocalSearchTest.cs
It tends to randomly fail, so try to avoid that.
=> [tests] Adjust LocalSearchTest.EmptyRequest to be a bit more lenient.

dotnet/targets/Xamarin.Shared.Sdk.targets
Original PR #22482 contributed by @NatElkins.
Fixes https://github.com/dotnet/macios/issues/22481.
=> [dotnet] Quote MlaunchPath so that it works if the mlaunch path has spaces. Fixes #22481.

tests/packaged-macos-tests.mk
TIL: quotes are significant in make.
=> [tests] Fix running macOS tests on arm64 machines.

src/avfoundation.cs, tests/introspection/ApiCtorInitTest.cs
It doesn't work in the simulator, but it works on device.
Fixes https://github.com/dotnet/macios/issues/10139.
=> [AVFoundation] Add a default ctor for AVRouteDetector. Fixes #10139.

tests/Makefile
API diff doesn't currently work when the two last commits need two different versions of Xcode.
The last commit in the release/9.0.1xx branch requires Xcode 16.3, and the
previous commit requires Xcode 16.2, so API diff didn't work for the last
commit.
So add a useless commit so that API diff runs successfully.
=> [release/9.0.1xx] Add a useless commit to make apidiff work.

src/MapKit/MKMapCameraZoomRange.cs, src/mapkit.cs, tests/cecil-tests/ConstructorTest.KnownFailures.cs, tests/cecil-tests/Documentation.KnownFailures.txt, tests/introspection/ApiSelectorTest.cs
Improve and simplify the manually bound constructors for MKMapCameraZoomRange by
Also add these constructors to macOS.
=> [MapKit] Improve and simplify the manually bound constructors for MKMapCameraZoomRange slightly.

scripts/rsp-to-csproj/rsp-to-csproj.cs, src/Makefile
This is the default when building with MSBuild, and it also makes it easier to
c&p paths and have them work everywhere.
=> [src] Ask the compiler to print out the full path to files in compiler messages.

src/UIKit/UIBarButtonItem.cs
There was a race condition in the constructors, where we'd create a new
Callback instance when calling the base constructor, and then fetching that
Callback instance inside the constructor itself, storing it in a field: the GC
could collect the Callback instance once we'd call the native init method, and
before we'd fetched it later on.
Fix it by not creating the Callback instance in the call to the base
constructor, but add the event handler in the actual constructor later.
Also add a few more code improvements.
Hopefully fixes this crash:
*** Terminating app due to uncaught exception 'ObjCRuntime.RuntimeException', reason: 'Failed to marshal the Objective-C object 0x60000025f660 (type: UIKit_UIBarButtonItem_Callback). Could not find an existing managed instance for this object, nor was …
=> [UIKit] Fix UIBarButtonItem's callback logic.

msbuild/Xamarin.MacDev.Tasks/Tasks/ParseDeviceSpecificBuildInformation.cs, msbuild/Xamarin.Shared/Xamarin.Shared.targets
Improve a few things in the ParseDeviceSpecificBuildInformation task:
* Enable nullability.
* Update code a bit to newer standards.
* Don't pass 'SessionId' to the task, because it's not executed remotely anyways.
Fixes https://github.com/dotnet/macios/issues/22550.
=> [msbuild] Enable nullability in the ParseDeviceSpecificBuildInformation task. Fixes #22550.

src/rgen/Microsoft.Macios.Bindings.Analyzer/NativeObjectHandleAnalyzer.cs
This currently reports ~55k errors.
=> [rgen] Enable analysis of generated code in the native object handle analyzer.

tools/common/Rewriter.cs
Fixes these test failures when running a release build with all optimizations and the static registrar:
MonoTouchFixtures.AppKit.NSGridViewTest
[FAIL] CreateWithNSViewArrayOfArrayCheckDifferentArrayLength : System.InvalidProgramException : InvalidProgram_Default
at AppKit.NSGridView.Create(NSView[][])
at MonoTouchFixtures.AppKit.NSGridViewTest.CreateWithNSViewArrayOfArrayCheckDifferentArrayLength()
at System.RuntimeMethodHandle.InvokeMethod(Object, Void**, Signature, Boolean)
at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object, BindingFlags)
[FAIL] CreateWithNSViewArrayOfArrayCheckNSTextView : System.InvalidProgramException : InvalidProgram_Default
at AppKit.NSGridView.Create(NSView[][]) …
=> [tools] Fix class_ptr rewriter to patch exception handlers too when instructions change.

tools/common/Rewriter.cs
We can simply change operands of existing instructions instead.
Fixes these test failures:
MonoTouchFixtures.AppKit.NSGridViewTest
[FAIL] CreateWithNSViewArrayOfArrayCheckDifferentArrayLength : System.InvalidProgramException : InvalidProgram_Default
at AppKit.NSGridView.Create(NSView[][])
at MonoTouchFixtures.AppKit.NSGridViewTest.CreateWithNSViewArrayOfArrayCheckDifferentArrayLength()
at System.RuntimeMethodHandle.InvokeMethod(Object, Void**, Signature, Boolean)
at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object, BindingFlags)
[FAIL] CreateWithNSViewArrayOfArrayCheckNSTextView : System.InvalidProgramException : InvalidProgram_Default
at AppKit.NSGridView.Create(NSView[][])
at …
=> [tools] Simplify class_ptr rewriter to not create new instructions when not needed.

src/MapKit/MKPointOfInterestFilter.cs, src/mapkit.cs, tests/cecil-tests/ConstructorTest.KnownFailures.cs, tests/cecil-tests/Documentation.KnownFailures.txt, tests/introspection/ApiSelectorTest.cs
Improve and simplify the manually bound constructors for MKPointOfInterestFilter by
=> [MapKit] Improve and simplify the manually bound constructors for MKPointOfInterestFilter slightly.

src/Foundation/NSUrlProtectionSpace.cs, src/foundation.cs, tests/cecil-tests/SetHandleTest.KnownFailures.cs, tests/introspection/ApiSelectorTest.cs
Improve and simplify the manually bound constructors for NSUrlProtectionSpace by
=> [Foundation] Improve and simplify the manually bound constructors for NSUrlProtectionSpace slightly.

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Trampoline.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryTrampolineTests.cs
There are two simple cases:
1. void: we return null which will indicate no need to return a value.
2. value or native type: return the aux variable directly.
We updated the default type and added unit tests for both cases.
=> [Rgen] Update the method for the trampoline return type for the general case

src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfo.cs, src/rgen/Microsoft.Macios.Generator/Extensions/TypeSymbolExtensions.Core.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Extensions/TypeSymbolExtensionsTests.cs
This is needed for trampolines that are dealing with INativeObjects that are not inheriting from NSObject.
=> [RGen] Keep track if the element of an array is a INativeObject.

src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfo.cs, src/rgen/Microsoft.Macios.Generator/Extensions/TypeSymbolExtensions.Generator.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/TypeInfoTests.cs
Add an extra property that will let us known during code generation if a symbol represents a pointer. For that:
1. We add a boolean to ensure that the symbol is a pointer symbol.
2. Update the NeedsStret method to account for the fact that some symbols are pointers.
3. Add a new test case.
=> [RGen] Indicate if a symbol represents a pointer.

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryRuntimeTests.cs
This will later allow the code to use "global::" by a single switch. This change just adds the method, we will update the other methods accordingly in later PRs.
=> [Rgen] Add a factory for the IdentifierName.

src/rgen/Microsoft.Macios.Generator/DataModel/Binding.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Constructor.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/EnumMember.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Method.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Property.Generator.cs, src/rgen/Microsoft.Macios.Transformer/DataModel/Constructor.Transformer.cs, src/rgen/Microsoft.Macios.Transformer/DataModel/EnumMember.Transformer.cs, src/rgen/Microsoft.Macios.Transformer/DataModel/Method.Transformer.cs, src/rgen/Microsoft.Macios.Transformer/DataModel/Property.Transformer.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/BindingTests.cs
In the transformer we want to be able to quickly access the members of a bindings via its selectors since that is how we are going to identify the members that are present in more than one platform.
To do so, we add an index per member type and we use its selector to locate its possition in the immutable array.
=> [RGen] Add number of indexes to be able to use them to retrieve members.

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Dlfcn.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.ObjCRuntime.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Runtime.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryObjCRuntimeTests.cs
This way we reduce the possible collisions with the user namespaces.
=> [RGen] Use the global alias for NSValue and NSNumber.

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.ObjCRuntime.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Runtime.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/ExpectedAppKitPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/ExpectedThreadSafeAppKitPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/ExpectedThreadSafeUIKitPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/ExpectedTrampolinePropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/ExpectedUIKitPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/iOSExpectedPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/macOSExpectedPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/tvOSExpectedPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryObjCRuntimeTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryRuntimeTests.cs
Reduces the chances of a namespace collision.
=> [RGen] Use the global alias for the Selector class.

src/bgen/Attributes.cs, src/bgen/Generator.cs, tests/generator/ExpectedXmlDocs.MacCatalyst.xml, tests/generator/ExpectedXmlDocs.iOS.xml, tests/generator/ExpectedXmlDocs.macOS.xml, tests/generator/ExpectedXmlDocs.tvOS.xml, tests/generator/tests/xmldocs.cs
This is accomplished by adding two new properties to the Async attribute:
`XmlDocs` and `XmlDocsWithOutParameter`. We need two properties, because an
[Async] member can end up with two async overloads if the original member has
a return value (which will end up being the out parameter in one of the async
overloads).
=> [bgen] Add support for writing xml docs for async methods.

src/bgen/Attributes.cs, src/bgen/Generator.cs, tests/generator/ExpectedXmlDocs.MacCatalyst.xml, tests/generator/ExpectedXmlDocs.iOS.xml, tests/generator/ExpectedXmlDocs.macOS.xml, tests/generator/ExpectedXmlDocs.tvOS.xml, tests/generator/tests/xmldocs.cs
This is accomplished by adding a new `XmlDocs` property to the EventArgs
attribute.
=> [bgen] Add support for writing xml docs for events.

src/AppKit/NSGradient.cs, src/appkit.cs, tests/cecil-tests/ConstructorTest.KnownFailures.cs, tests/cecil-tests/SetHandleTest.KnownFailures.cs, tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.ignore
Improve and simplify the manually bound constructors for NSGradient by
=> [AppKit] Improve and simplify the manually bound constructors for NSGradient slightly.

src/CoreLocation/CLBeaconRegion.cs, src/corelocation.cs
Improve and simplify the manually bound constructors for CLBeaconRegion by
=> [CoreLocation] Improve and simplify the manually bound constructors for CLBeaconRegion slightly.

runtime/monotouch-debug.h, runtime/monotouch-debug.m, runtime/monotouch-main.m
Report how long the app launch takes (only in debug mode).
It's measured from the very beginning of the main method, until we receive the
[UIApplicationDidFinishLaunchingNotification][1] notification.
We now print the following to the system's log using `NSLog`:
Microsoft.iOS: Started launch timer
[...]
Microsoft.iOS: Did finish launching in 0.295 s
This is off by default, and can be enabled by setting the environment variable
`XAMARIN_TRACK_LAUNCH_DURATION` to:
* `enable`: enable.
* `disable`: disable.
If using mlaunch, the environment variable can be set by passing
`--setenv:XAMARIN_TRACK_LAUNCH_DURATION=...` to mlaunch.
Fixes https://github.com/dotnet/macios/issues/22510.
[1]: https://developer.apple.com/documentation/uikit/uiapplication/didfinishlaunchingnotification
=> [runtime] Add ability to report how long app launch takes. Fixes #22510.

dotnet/Makefile, scripts/template.mk
Hopefully fixes this random build error:
gmake[1]: Entering directory '[...]/macios/dotnet'
GEN      Microsoft.iOS.Sdk.Versions.props
GEN      Microsoft.tvOS.Sdk.Versions.props
GEN      Microsoft.macOS.Sdk.Versions.props
GEN      Microsoft.MacCatalyst.Sdk.Versions.props
GEN      Microsoft.iOS.Sdk.DefaultItems.props
GEN      Microsoft.iOS.Sdk.ImplicitNamespaceImports.props
GEN      AutoImport.props
GEN      Microsoft.tvOS.Sdk.ImplicitNamespaceImports.props
GEN      Microsoft.tvOS.Sdk.DefaultItems.props
GEN      AutoImport.props
GEN      Microsoft.MacCatalyst.Sdk.DefaultItems.props
GEN      Microsoft.MacCatalyst.Sdk.ImplicitNamespaceImports.props
GEN      AutoImport.props
GEN      AutoImport.props
GEN      Microsoft.macOS.Sdk.ImplicitNamespaceImports.props
GEN …
=> [dotnet] Build all scripts before doing surgery on the local .NET installation.

src/AppKit/NSTextContainer.cs, src/xkit.cs, tests/cecil-tests/ConstructorTest.KnownFailures.cs, tests/cecil-tests/SetHandleTest.KnownFailures.cs, tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.ignore
Improve and simplify the manually bound constructors for NSTextContainer by
=> [AppKit] Improve and simplify the manually bound constructors for NSTextContainer slightly.

src/Foundation/NSString.cs, tests/cecil-tests/ConstructorTest.KnownFailures.cs, tests/cecil-tests/SetHandleTest.KnownFailures.cs
Improve and simplify the manually bound constructors for NSString by
=> [Foundation] Improve and simplify the manually bound constructors for NSString slightly.

src/ObjCRuntime/Stret.cs, src/bgen/Generator.cs, src/rgen/Microsoft.Macios.Generator/Extensions/TypeSymbolExtensions.Core.cs, src/rgen/Microsoft.Macios.Generator/Extensions/TypeSymbolExtensions.Generator.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/iOSExpectedPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Extensions/TypeSymbolExtensionsSizeTests.cs
We don't support any 32-bit platforms anymore.
=> [bgen] Remove 32-bit support.

docs/website/mtouch-errors.md, src/AppKit/NSGradient.cs, src/ObjCRuntime/BindAs.cs, src/ObjCRuntime/Runtime.cs, src/ObjCRuntime/TypeConverter.cs, src/WebKit/WKWindowFeatures.cs
All pointers we support are now 64-bits.
=> [src] Remove pointer-size checks and code.

msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx, msbuild/Xamarin.MacDev.Tasks/Tasks/AnalyzeFileChanges.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/CalculateAssembliesReport.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/Zip.cs, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Windows.After.targets, tests/dotnet/UnitTests/WindowsTest.cs
With the new ICorDebug engine for MAUI, we need the debugger to always load the assemblies from Windows. Given that some dll and pdb files changes as part of the remote build, we need a mechanism to copy those modified files back to the Windows OutputPath, so the debugger can always load the right files. Otherwise, the debugger will try to load files that are not the same that are in the running app, so no symbols will be loaded. This also improves the debugger performance by ensuring the files are not loaded remotely but locally
=> [xma] Added targets and tasks to copy modified dll and pdb files back to Windows

msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx, msbuild/Xamarin.MacDev.Tasks/Tasks/AnalyzeFileChanges.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/CalculateAssembliesReport.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/Zip.cs, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Windows.After.targets, tests/dotnet/UnitTests/WindowsTest.cs
With the new ICorDebug engine for MAUI, we need the debugger to always load the assemblies from Windows. Given that some dll and pdb files changes as part of the remote build, we need a mechanism to copy those modified files back to the Windows OutputPath, so the debugger can always load the right files. Otherwise, the debugger will try to load files that are not the same that are in the running app, so no symbols will be loaded. This also improves the debugger performance by ensuring the files are not loaded remotely but locally
=> [release/9.0.1xx][xma] Added targets and tasks to copy modified dll and pdb files back to Windows

Makefile, mk/xamarin.mk
* It wasn't cleaning macios-adr, because it was assuming the path to
macios-adr was a relative path, thus prepending the current path, leading to
a path that didn't exist.
* Remove some dead code (we don't have a mono dependency anymore for instance).
* Misc other tweaks to improve output and readability.
=> [build] Fix a few issues with the 'git-clean-all' target.

tests/common/TestRuntime.cs, tests/dotnet/UnitTests/TestBaseClass.cs, tools/devops/automation/templates/mac/build.yml, tools/devops/automation/templates/tests/run-tests.yml
The 'BUILD_REASON' variable isn't reliable anymore to detect pull requests
(because the test stage is triggered using a resource trigger, BUILD_REASON
ends up being 'ResourceTrigger').
=> [devops] Set IS_PR for test runs and detect it correctly in tests.

dotnet/package/common.csproj, eng/common/core-templates/steps/install-microbuild.yml, eng/common/core-templates/steps/source-index-stage1-publish.yml, tools/devops/automation/templates/mac/build.yml, tools/devops/automation/templates/main-stage.yml, tools/devops/automation/templates/release/vs-insertion-prep.yml, tools/devops/automation/templates/tests/build.yml, tools/devops/automation/templates/variables/common.yml, tools/devops/automation/templates/windows/build.yml, tools/devops/automation/templates/windows/reserve-mac.yml
I noticed the net10.0 branch build was failing during the "generate and publish BAR manifest" step with:
D:\a\_work\1\s\dotnet\package\common.csproj(151,5): error MSB4062: The "PushToBuildStorage" task could not be loaded from the assembly D:\a\_work\1\s\packages\microsoft.dotnet.build.tasks.feed\10.0.0-beta.25228.101\build\../tools/net/Microsoft.DotNet.Build.Tasks.Feed.dll. Could not load file or assembly 'System.Runtime, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
The Microsoft.DotNet.Build.Tasks.Feed tasks are seemingly now being built against .NET 10, so we'll need to install .NET 10 to run them.
Variables that represent the current stable and preview versions of .NET have been added to be used throughout the …
=> [ci][net10.0] Use variables to control system .NET SDK installs

eng/common/core-templates/job/source-index-stage1.yml, tools/devops/automation/templates/mac/build.yml, tools/devops/automation/templates/main-stage.yml, tools/devops/automation/templates/release/vs-insertion-prep.yml, tools/devops/automation/templates/tests/build.yml, tools/devops/automation/templates/variables/common.yml, tools/devops/automation/templates/windows/build.yml, tools/devops/automation/templates/windows/reserve-mac.yml
I noticed the net10.0 branch build was failing during the
"generate and publish BAR manifest" step with:
D:\a\_work\1\s\dotnet\package\common.csproj(151,5): error MSB4062: The "PushToBuildStorage" task could not be loaded from the assembly D:\a\_work\1\s\packages\microsoft.dotnet.build.tasks.feed\10.0.0-beta.25228.101\build\../tools/net/Microsoft.DotNet.Build.Tasks.Feed.dll. Could not load file or assembly 'System.Runtime, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
The Microsoft.DotNet.Build.Tasks.Feed tasks are seemingly now being
built against .NET 10, so we'll need to install .NET 10 to run them.
Variables that represent the current stable and preview versions of .NET
have been added to be used throughout the …
=> [ci] Use variables to control system .NET SDK installs

src/Security/Items.cs, tests/monotouch-test/Security/KeyChainTest.cs
It works (according to tests at least), so I don't see a reason to exclude it.
=> [Security] Add SecKeyChain.QueryAsConcreteType to macOS.

docs/building-apps/build-properties.md, dotnet/targets/Xamarin.Shared.Sdk.targets, msbuild/Xamarin.Shared/Xamarin.Shared.props
Fixes https://github.com/dotnet/macios/issues/19370.
=> [dotnet] Add a 'EnableProfiler' property to enable the 'diagnostics_tracing' component. Fixes #19370.

src/Makefile, src/bgen/BindingTouch.cs
The compiler will validate the xml docs as much as it can, and will raise a warning
if it sees xml docs talking about APIs that don't exist.
However, in api definitions we might want to write xml docs that reference APIs that
are generated, and they won't exist yet. So ignore any such warnings - in any case,
if they're actually wrong, the compiler will show a warning when compiling the final
code.
=> [src] Ignore warnings related to xml docs when compiling core and api definition assemblies.

src/AppKit/NSOpenGLPixelFormat.cs, tests/cecil-tests/SetHandleTest.KnownFailures.cs
Improve and simplify the manually bound constructors for NSOpenGLPixelFormat by
=> [AppKit] Improve and simplify the manually bound constructors for NSOpenGLPixelFormat slightly.

tools/devops/automation/templates/windows/build.yml
Our tests require long paths to be enabled on Windows, so do that.
Fixes https://github.com/dotnet/macios/issues/22697.
=> [devops] Enable long paths on Windows bots. Fixes #22697.

runtime/delegates.t4, runtime/trampolines-invoke.m, runtime/trampolines.m, src/ObjCRuntime/Runtime.cs, tools/common/StaticRegistrar.cs
The interpreter has a bug where it doesn't correctly zero-extend small integer
values (such as bytes) upon returning from managed to native code (in a
reverse P/Invoke): https://github.com/dotnet/runtime/issues/110649.
Work around this by always using at least register-sized integer values
instead, which makes the interpreter return the correct values.
Fixes https://github.com/dotnet/macios/issues/22205.
=> [runtime] Implement workaround for an interpreter bug where it returns incorrect small integer values to reverse P/Invokes.

tests/dotnet/UnitTests/ProjectTest.cs
This reverts commit c5711236eba170cf66b3f6c7039b9bd63de0e3ce.
Fixes https://github.com/dotnet/macios/issues/22187.
=> [net10.0] [tests] Revert ignored NativeAOT tests that were failing due to a dotnet/sdk issue.

tools/devops/automation/build-pipeline.yml, tools/devops/automation/build-pull-request.yml
This way CI for localization PRs is automatically started correctly.
=> [devops] Treat lego/ branches as dev (PR) branches.

tools/devops/automation/templates/windows/build.yml
Our tests require long paths to be enabled on Windows, so do that.
Fixes https://github.com/dotnet/macios/issues/22697.
Backport of ##22725.
=> [release/10.0.1xx-preview4] [devops] Enable long paths on Windows bots. Fixes #22697.

src/rgen/Microsoft.Macios.Generator/DataModel/DelegateInfo.cs, src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfo.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/DelegateInfoTests.cs
In order for tramplones to be able to take delegates as parameters, we need to identify the type of callback.
We need to check if the CCallbackAttribute or BlockCallbackAttribute have been used in a parameter that is a delegate. This has been added as part of the TryCreate method. Tests got added to ensure that we indeed check the presence of the attrs.
=> [RGen] Retrieve the CCalback and BlockCallback attrs in a delegate.

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryRuntimeTests.cs
This is later needed for the trampoline.g.cs code.
=> [RGen] Create syntax for the GetDelegateForFunctionPointer static call.

src/rgen/Microsoft.Macios.Generator/Nomenclator.cs, tests/rgen/Microsoft.Macios.Generator.Tests/NomenclatorTests.cs
This way we have a centralized place in which the naming is calculated and its easier to change/fix.
=> [RGen] Use the nomenglator to decide the names of the temp vars in trampolines

msbuild/Xamarin.MacDev.Tasks/Tasks/AOTCompile.cs, msbuild/Xamarin.MacDev.Tasks/Tasks/CompileNativeCode.cs
Sort inputs when doing AOT compilation and native code compilation, so that we
start by processing the input that takes the longest to process. This helps
maximizing usage of parallel resources, because there's a smaller chance we'll
be left at the end working on a single long-running task.
Some tentative timings from compiling monotouch-test locally, it shows a few
seconds improvement (which percentage-wise can be significant).
| Task                    | Before | After |
| ----------------------- | ------ | ----- |
| Native code compilation | ~25s   |  ~22s |
| AOT compilation         | ~23s   |  ~22s |
=> [msbuild] Sort inputs when doing aot compilation and native compilation.

tests/monotouch-test/CoreFoundation/ProxyTest.cs
Fixes the test failing randomly like this:
MonoTouchFixtures.CoreFoundation.ProxyTest
[FAIL] Fields : OneTimeSetUp:   Expected: True But was:  False
[FAIL] TestPACParsingAsync : OneTimeSetUp:   Expected: True But was:  False
[FAIL] TestPACParsingAsyncNoProxy : OneTimeSetUp:   Expected: True But was:  False
[FAIL] TestPACParsingScript : OneTimeSetUp:   Expected: True But was:  False
[FAIL] TestPACParsingScriptError : OneTimeSetUp:   Expected: True But was:  False
[FAIL] TestPACParsingScriptNoProxy : OneTimeSetUp:   Expected: True But was:  False
[FAIL] TestPACParsingUrl : OneTimeSetUp:   Expected: True But was:  False
[FAIL] TestPACParsingUrlAsync : OneTimeSetUp:   Expected: True But was:  False
[FAIL] TestPACParsingUrlAsyncNoProxy : OneTimeSetUp:   Expected: True But was:  False
[FAIL] …
=> [tests] Ignore timeouts setting up ProxyTest in CI. Fixes @xamarin/maccore#2691.

msbuild/Xamarin.MacDev.Tasks/Tasks/CompileAppManifest.cs, msbuild/Xamarin.Shared/Xamarin.Shared.targets, tests/dotnet/UnitTests/PartialAppManifestTest.cs, tests/dotnet/UnitTests/ProjectTest.cs, tests/dotnet/UnitTests/WindowsTest.cs
Fixes: https://github.com/dotnet/macios/issues/19607
The `_CompileAppManifest` MSBuild target currently runs on every build because it has no `Inputs` defined.
In cases where the inputs are not discretely known, we can use a pattern we've used in dotnet/android:
https://github.com/dotnet/android/blob/b61cac33ea1a1a8c4751b8f9f1eade8cf27313c6/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets#L960-L990
* Write a file with `<WriteLinesToFile WriteOnlyWhenDifferent="true">` to the `obj` directory with all the parameters to the `<CompileAppManifest/>` MSBuild task.
* Use this file as the `Inputs` for the `_CompileAppManifest` target.
* If any of the parameters change, the file will be different and `_CompileAppManifest` will run again.
I updated …
=> [msbuild] introduce `_CompileAppManifestInputs`

src/Makefile, tests/xtro-sharpie/Makefile
Also use a temporary file when generating C# code to not fail to rebuild if
generation failed for whatever reason.
=> [xtro] Improve make output.

runtime/coreclr-bridge.m, runtime/delegates.t4, src/ObjCRuntime/Runtime.CoreCLR.cs, tests/dotnet/ExceptionalTestApp/AppDelegate.cs, tests/dotnet/UnitTests/ProjectTest.cs
Fixes https://github.com/dotnet/macios/issues/15252.
=> [runtime/src] Raise the AppDomain.UnhandledException event on CoreCLR. Fixes #15252.

src/Metal/MTLRasterizationRateLayerDescriptor.cs, src/metal.cs, tests/cecil-tests/Documentation.KnownFailures.txt, tests/monotouch-test/Metal/MTLRasterizationRateLayerDescriptorTest.cs
* Fix availability for the SampleCount property.
* Fix the [Horizontal|Vertical]SampleStorage properties to actually work by marshalling
a float array instead of double array.
* Add tests.
=> [Metal] Fix a few issues in MTLRasterizationRateLayerDescriptor.

msbuild/Xamarin.MacDev.Tasks/Tasks/XamarinTask.cs
It will end up throwing an exception, and it will just make the build log a
whole lot more confusing.
=> [msbuild] Don't try to log a null exception.

msbuild/Xamarin.Shared/Xamarin.Shared.targets
App Extensions on Mac Catalyst go where they do for macOS: inside the
Contents/ directory.
=> [msbuild] Fix placing app extensions for Mac Catalyst.

tests/dotnet/Windows/collect-binlogs.sh, tools/devops/automation/templates/windows/build.yml
Run the 'Fetch remote binlogs' after 'Fail if test failures', because the
'Fetch remote binlogs' step is not required to pass, but if it fails before
'Fail if test failures', it will be treated as a test failure and the job will
fail.
=> [devops] Reorder windows steps a bit.

macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.cs.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.de.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.es.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.fr.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.it.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ja.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ko.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pl.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pt-BR.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ru.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.tr.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hans.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 14411: Build ID 11610316

macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.cs.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.de.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.es.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.fr.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.it.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ja.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ko.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pl.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pt-BR.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ru.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.tr.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hans.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 14411: Build ID 11610317

macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.cs.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.de.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.es.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.fr.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.it.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ja.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ko.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pl.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pt-BR.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ru.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.tr.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hans.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 14411: Build ID 11610315

macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.cs.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.de.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.es.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.fr.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.it.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ja.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ko.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pl.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pt-BR.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ru.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.tr.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hans.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 14411: Build ID 11605235

macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.cs.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.de.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.es.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.fr.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.it.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ja.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ko.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pl.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pt-BR.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ru.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.tr.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hans.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 14411: Build ID 11605223

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.ObjCRuntime.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Trampoline.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryTrampolineTests.cs
Add a new method that will take a managed delegate parameter and will generate the needed parameter syntax for the Invoke and delegate in a trampoline.
Example of conversions:
Action -> IntrPtr
NSObject -> NativeHandle
Pointer -> Pointer
Array -> NativeHandle
The tests take care to verify that the correct conversions is done for all the known parameter types.
We need this conversion to fix the reviews in https://github.com/dotnet/macios/pull/22813
=> [RGen] Add method that can calculate the low level parameter for a trampoline.

macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.cs.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.de.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.es.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.fr.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.it.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ja.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ko.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pl.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pt-BR.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ru.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.tr.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hans.resx, macios/msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 14411: Build ID 11622326

src/ModelIO/MDLNoiseTexture.cs, src/modelio.cs, tests/cecil-tests/ConstructorTest.KnownFailures.cs, tests/cecil-tests/SetHandleTest.KnownFailures.cs
Improve and simplify the manually bound constructors for MDLNoiseTexture by
=> [ModelIO] Improve and simplify the manually bound constructors for MDLNoiseTexture slightly.

dotnet/targets/Xamarin.Shared.Sdk.targets, msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx, tests/dotnet/UnitTests/ProjectTest.cs
This fixes an infinite recursion when the runtime asks us to create the
selected native http handler, but we don't have a native http handler because
they've all been linked away, so we ask the runtime to create the http
handler.
=> [dotnet] Fix selecting NSUrlSessionHandler when not choosing a specific handler.

dotnet/targets/Xamarin.Shared.Sdk.targets, msbuild/Xamarin.MacDev.Tasks/Tasks/GetMlaunchArguments.cs
There are two ways:
> dotnet build /t:ShowRunHelp
or
> dotnet run -p:ShowRunHelp=true
either way results in something like this:
To run on physical device:
1. If the project has multiple target frameworks, select the desired target framework. Example: -f net10.0-ios
2. Pass a RuntimeIdentifier for a device. Example: -p:ios-arm64
3. Pass the name or identifier of the target device using '-p:DeviceName=<name or identifier of device>'
There are 3 device(s) connected to this Mac that can be used to run this app:
Rolf's iPad Pro 3rd Gen (00008027-00187158020A002E)
Rolf's iPhone 13 (00008110-000568491A92801E)
Rolf's iPhone 15 (00008130-0008490A3A12001C)
Example: -p:DeviceName=00008027-00187158020A002E or -p:DeviceName='Rolf\'s iPad Pro 3rd Gen'
For example:
dotnet run -f net10.0-ios -r …
=> [net10.0] [dotnet] Add a way to get help with how apps are launched on mobile.

src/AddressBook/ABGroup.cs, src/CoreFoundation/CFMutableString.cs, src/CoreFoundation/CFSocket.cs, src/CoreFoundation/CFString.cs, src/CoreFoundation/DispatchBlock.cs, src/CoreFoundation/OSLog.cs, src/CoreGraphics/CGPattern.cs, src/Foundation/NSUuid.cs, src/ScreenCaptureKit/SCContentFilter.cs, src/Security/SecTrust2.cs, tests/cecil-tests/Documentation.KnownFailures.txt, tests/cecil-tests/SetHandleTest.KnownFailures.cs
Call `InitializeHandle` instead of calling the `Handle` setter in various types.
=> [src] Use InitializeHandle instead of calling the Handle setter in several types.

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.ObjCRuntime.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Trampoline.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryTrampolineTests.cs
The argument conversions is from low level to high level, therefore we need to look for a bool parameter and convert the byte to a bool. Not the otherway around.
=> [RGen] Fix bug where we converted a bool to a byte when we needed the opposite.

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Runtime.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Trampoline.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryRuntimeTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryTrampolineTests.cs
Rather than take its own parameter, is better to relay in the method that returns the identifier of a type which is used all over the code generator and ensures that we will be consistent.
Tests have been updated to reflect the change.
=> [RGen] Fix missing 'global::' when using New.

src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfo.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/TypeInfoTests.cs
Ensure that the name of a nested class is "Parent.Class" and its namespace is that of the parent.
The previous algorithm was mixing the parent name class and the namespace which would be problematic when we want to import the namespace from a TypeInfo.
=> [RGen] Handle nested classes correctly.

dotnet/targets/Xamarin.Shared.Sdk.targets, tests/dotnet/UnitTests/IncrementalBuildTest.cs
Store the non-file inputs to the AOT compiler in a cache file, and if these inputs
change, then clean the entire cache of AOT-compiled output. This is implemented by
computing a hash of all these inputs (properties), store the hash to a file, and
overwrite the file if the hash changes. Then in a subsequent target, we wipe the
AOT compiler cache if the file with the hash value changed.
This is a similar implementation of how the csc task (C# compiler) creates a hash
of the compiler input in order to know when to re-execute the C# compiler.
Fixes https://github.com/dotnet/macios/issues/21061.
=> [dotnet] Fix dependency tracking for aot compilation. Fixes #21061.

msbuild/Xamarin.Shared/Xamarin.Shared.targets, tests/common/DotNet.cs, tests/dotnet/UnitTests/MauiTest.cs
The 'ParseDeviceSpecificBuildInformation' task is only applicable to mobile
targets (iOS and tvOS), so skip running it on Mac Catalyst (like we're already
doing for macOS).
This fixes a build error if happens to run on Mac Catalyst:
> The \"ParseDeviceSpecificBuildInformation\" task failed unexpectedly. System.InvalidOperationException: Invalid platform: MacCatalyst
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2484312.
Backport of #22887.
=> [release/10.0.1xx-preview5] [msbuild] Don't execute the ParseDeviceSpecificBuildInformation task on Mac Catalyst.

dotnet/targets/Xamarin.Shared.Sdk.targets, msbuild/Xamarin.MacDev.Tasks/Tasks/Codesign.cs, tests/dotnet/IncrementalTestApp/AppDelegate.cs, tests/dotnet/IncrementalTestApp/MacCatalyst/IncrementalTestApp.csproj, tests/dotnet/IncrementalTestApp/MacCatalyst/Makefile, tests/dotnet/IncrementalTestApp/Makefile, tests/dotnet/IncrementalTestApp/iOS/IncrementalTestApp.csproj, tests/dotnet/IncrementalTestApp/iOS/Makefile, tests/dotnet/IncrementalTestApp/macOS/IncrementalTestApp.csproj, tests/dotnet/IncrementalTestApp/macOS/Makefile, tests/dotnet/IncrementalTestApp/shared.csproj, tests/dotnet/IncrementalTestApp/shared.mk, tests/dotnet/IncrementalTestApp/tvOS/IncrementalTestApp.csproj, tests/dotnet/IncrementalTestApp/tvOS/Makefile, tests/dotnet/UnitTests/IncrementalBuildTest.cs
Store the non-file inputs to the trimmer and native linker in cache files, and if
these inputs change, then rerun the trimmer and native linker. This is implemented
by computing a hash of all these inputs (properties), store the hash to a file, and
overwrite the file if the hash changes. Then in a subsequent target, we force the
trimmer or native linekr to run if the file with the hash value changed.
This is a similar implementation of how the csc task (C# compiler) creates a hash
of the compiler input in order to know when to re-execute the C# compiler.
Also fix a bug in the Codesign task, where the task would always resign an app bundle
if it contained something inside that needed to be signed separately (it wouldn't
consider that the contained something could already be signed).
Fixes …
=> [dotnet] Fix dependency tracking for trimming and native linking. Fixes #21223.

src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfo.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/ClassGenerationTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/ExpectedAppKitPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/ExpectedThreadSafeAppKitPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/ExpectedThreadSafeUIKitPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/ExpectedUIKitPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/iOSExpectedPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/macOSExpectedPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/tvOSExpectedPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryFieldBackingVariableTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryTrampolineTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Formatters/MethodFormatterTests.cs
nint and nuint are meta types that point to IntPtr and UIntPtr. Due to that fact, we are not using the global::System.IntPtr string in the cases we find a nint. The way to fix this is to look at the special type, and if it matches IntPtr/UIntPtr, use the fully qualified name.
With this change we are consistent in all the generated code and we will always find global::System.IntPtr no matter if the user used nint or IntPtr.
=> [Rgen] Be consistent in the use of global when we encounter a nint/nuint.

msbuild/Xamarin.MacDev.Tasks/Tasks/CompileEntitlements.cs
Fixes:
macios/msbuild/Xamarin.MacDev.Tasks/Tasks/CompileEntitlements.cs(951,74): error CS8620: Argument of type 'KeyValuePair<string, PObject>' cannot be used for parameter 'kvp' of type 'KeyValuePair<string?, PObject>' in 'void CompileEntitlements.ValidateTypeOrArray<PString, string>(MobileProvision? profile, EntitlementInfo info, bool onlyWarn, string key, KeyValuePair<string?, PObject> kvp, string? provisioningProfileName, PDictionary? provisioningEntitlements, string requiredType)' due to differences in the nullability of reference types.
macios/msbuild/Xamarin.MacDev.Tasks/Tasks/CompileEntitlements.cs(956,73): error CS8620: Argument of type 'KeyValuePair<string, PObject>' cannot be used for parameter 'kvp' of type 'KeyValuePair<string?, PObject>' in 'void …
=> [msbuild] Fix build break.

src/rgen/Microsoft.Macios.Generator/DataModel/DelegateParameter.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/DelegateParameter.cs, src/rgen/Microsoft.Macios.Transformer.Generator/Microsoft.Macios.Transformer.Generator/XamarinBindingAPIGenerator.cs, src/rgen/Microsoft.Macios.Transformer/DataModel/DelegateParameter.Transformer.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/DelegateInfoTests.cs
This will allow to make the bindings more user friendly by allow to use a managed value in a delegate that later gets converted to the native one.
=> [RGen] Allow to use BindFrom in delegates.

msbuild/Xamarin.MacDev.Tasks/Tasks/ComputeCodesignItems.cs, tests/dotnet/CustomizedCodeSigning/shared.csproj, tests/dotnet/UnitTests/ProjectTest.cs, tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/ComputeCodesignItemsTaskTests.cs
Handle the following cases:
* If the item to be skipped is a file, checking if it's a directory first will fail.
* If the item is a directory, we need to canonicalize it to have a trailing slash.
Fixes https://github.com/dotnet/macios/issues/19222.
=> [msbuild] Correctly handle 'SkipCodesignItems' that are directories. Fixes #19222.

tests/monotouch-test/AudioUnit/AUGraphTestMac.cs, tests/monotouch-test/AudioUnit/AudioUnit.cs, tests/monotouch-test/CoreMedia/CMClockTest.cs
Sample failures this will hopefully fix:
Xamarin.Mac.Tests.AudioUnitTests
[PASS] AudioObjectPropertyScope4CCTest
[PASS] AudioObjectPropertySelector4CCTest
[FAIL] GetCurrentDevice_Test :   Expected: True
at Xamarin.Mac.Tests.AudioUnitTests.GetCurrentDevice_Test() in /Users/builder/azdo/_work/1/s/macios/tests/monotouch-test/AudioUnit/AudioUnit.cs:line 37
Xamarin.Mac.Tests.AudioUnitTests : 9.0972 ms
Xamarin.Mac.Tests.AUGraphTests
[FAIL] DoTest : Did not see events after 1 second
at Xamarin.Mac.Tests.AUGraphTests.WaitOnGraphAndMixerCallbacks() in /Users/builder/azdo/_work/1/s/macios/tests/monotouch-test/AudioUnit/AUGraphTestMac.cs:line 94
at Xamarin.Mac.Tests.AUGraphTests.DoTest() in /Users/builder/azdo/_work/1/s/macios/tests/monotouch-test/AudioUnit/AUGraphTestMac.cs:line 67 …
=> [monotouch-test] Tweak tests a bit to make them more reliable on bots.a

src/rgen/Microsoft.Macios.Generator/DataModel/DelegateParameter.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/DelegateParameter.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.ObjCRuntime.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Trampoline.cs, src/rgen/Microsoft.Macios.Transformer.Generator/Microsoft.Macios.Transformer.Generator/XamarinBindingAPIGenerator.cs, src/rgen/Microsoft.Macios.Transformer/DataModel/DelegateParameter.Transformer.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/DelegateInfoTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryTrampolineTests.cs
This allows to get the native object either a NSNumber, NSValue or NSString and upper its type to the managed one expected by the delegate.
Example of code generated for an NSValue
```csharp
var ret = del (global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSValue> (size)!.CGSizeValue);
```
Example of code generated for a NSString that represents a SmartEnum:
```csharp
var ret = del (global::NS.CustomLibraryEnum.GetValue (global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSString> (level)!));
```
Array will be added in a following PR to simplify the review process.
=> [RGen] Update the factory method to support non array BindFrom delegate arguments.

docs/building-apps/build-properties.md, dotnet/targets/Xamarin.Shared.Sdk.targets, msbuild/Xamarin.Shared/Xamarin.Shared.props, tools/common/Application.cs, tools/common/Target.cs
Ref: https://github.com/dotnet/runtime/issues/115473#issuecomment-2933946678
Android will do the same.
Backport of #22982.
=> [release/9.0.1xx] Use 'EnableDiagnostics' instead of 'EnableProfiler'.

tools/devops/automation/templates/windows/reserve-mac.yml
Provisionator isn't able to write to the new location yet, so remove both
settings locations just to make sure everything is pristine before asking the
provisionator to install Xcode.
This will hopefully fix an issue where the build picks up an earlier version of the settings plist with the wrong Xcode version.
=> [devops] Clear old Xcode settings.

docs/api/Foundation/NSString.xml, src/AppKit/NSImage.cs, src/AppKit/NSStringAttributes.cs, src/CoreFoundation/CFString.cs, src/CoreMedia/CMAttachmentBearer.cs, src/CoreServices/LaunchServices.cs, src/CoreTelephony/CoreTelephony.cs, src/Foundation/NSExceptionError.cs, src/Foundation/NSString.cs, src/MediaPlayer/MPNowPlayingInfoCenter.cs, src/ObjCRuntime/ThrowHelper.cs, src/Security/SecStatusCodeExtensions.cs, src/VideoToolbox/VTVideoEncoder.cs, src/appkit.cs, src/avfoundation.cs, src/healthkit.cs, src/xkit.cs, tests/cecil-tests/Documentation.KnownFailures.txt, tests/xtro-sharpie/api-annotations-dotnet/common-CoreFoundation.ignore
* Enable nullability and fix any resulting issues.
* CFString and NSString are toll-free bridged, so we can simplify the NSString
creation code to always create CFStrings and not NSStrings - which is a
really nice performance benefit, because creating a CFString is
significantly faster.
* Add a few methods to CFString to match NSString's API.
* Add/improve xml docs.
=> [src] Misc NSString improvements.

msbuild/Xamarin.MacDev.Tasks/Tasks/ACTool.cs
Compute the list of assets we want to process once at the beginning of
processing, instead of going through the list multiple times, each time
applying exclusion conditions.
This simplifies the code somewhat, and also makes it easier to add more
exclusion conditions in the future.
=> [msbuild] Refactor the ACTool task a bit to simplify code.

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Runtime.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Trampoline.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/iOSExpectedPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/macOSExpectedPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/tvOSExpectedPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryRuntimeTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryTrampolineTests.cs
This change will allow to add delegates in the following forms:
1. array for nsnumber to int[]
2. array for nsvalue to struct[]
3. arrya for nsstring to smart enum.
The generated code looks like:
NSNumber:
```csharp
var ret = del (Foundation.NSArray.ArrayFromHandleFunc<int> (pointerParameter, Foundation.NSNumber.ToInt32, false)!);
```
NSValue:
```csharp
var ret = del (Foundation.NSArray.ArrayFromHandleFunc<CoreGraphics.CGSize> (size, Foundation.NSValue.ToCGSize, false)!);
```
NSString
```csharp
var ret = del (Foundation.NSArray.ArrayFromHandleFunc<NS.CustomLibraryEnum> (level, NS.CustomLibraryEnumExtensions.GetValue, false)!);
```
=> [RGen] Add support for arrays in a delegate using BindFrom.

.config/dotnet-tools.json, msbuild/ILMerge.targets, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Tasks.Windows.csproj
* Update the dotnet-ilrepack tool to the latest version.
* Remove some old code in ILMerge.targets. This required adding the MSBuild package
references to Xamarin.iOS.Task.Windows.csproj, because these packages were getting
imported by the otherwise unused ILRepack.MSBuild.Task package reference.
* Ask ilrepack to merge ILLink resources (this fixes a warning about duplicate
ILLink.Substitutions.xml resources).
=> [msbuild] Update ilrepack.

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Runtime.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Trampoline.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryTrampolineTests.cs
Instead than calling the GC.KeepAlive method we want to call CFString.Release native which keeps a ref to the native string and, more importantly, frees the memory of the string once we are done with it.
=> [RGen] When a native string is created, released as part of the post invocation steps.

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.KnownTypes.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Runtime.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryRuntimeTests.cs
There are some types that are known and we want to create a new instance for using new rather than GetINativeObject/GetNSObject. Add a new
overload of the New method that allows to pass directly a TypeSyntax.
=> [RGen] Allow to generate a 'new' syntax using a known type.

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Trampoline.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryTrampolineTests.cs
If a delegate returns a smart enum, we need to ensure that we retain the NSString handle that is returned by the delegate execution.
=> [RGen] Ensure that we handle smart enums correctly when they are returned from the delegate.

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.KnownTypes.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryRuntimeTests.cs
AsPointer is used to ensure that we pass a ref/in/out parameter as a pointer to the native code.
=> [Rgen] Provide a factory method to generate AsPointer calls.

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryRuntimeTests.cs
This is a helper method that knows how to handle the ref kind and will create the correct argument syntax. This can later be used to create the arguments in a more elegant way.
=> [RGen] Add a ArgumentForParameter method to create ArgumentSyntax from the parameter info.

src/accessorysetupkit.cs
Fixes https://github.com/dotnet/macios/issues/22352#issuecomment-2969907846.
=> [AccessorySetupKit] Introduce a default ctor for a few classes.

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Trampoline.cs, src/rgen/Microsoft.Macios.Generator/Emitters/TrampolineEmitter.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/ClassGenerationTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/ExpectedTrampolinePropertyTestsTrampolines.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryTrampolineTests.cs
We achieve the following:
1. Create a method that will do any needed conversion of the return type.
2. Fix a bug in which we were keeping alive the handle, when it should the managed object.
3. Complete the generation of the invoke. Call the conversions, call the invoker, call the post conversions and return the valid value.
This completes all the code that needs to be generated by trampoline. We will add tests with known frameworks in coming commits to ensure that we are generating equivalent code.
=> [RGen] Complete the native invoke implementation.

msbuild/Xamarin.Shared/Xamarin.Shared.ObjCBinding.targets, msbuild/Xamarin.Shared/Xamarin.Shared.props, msbuild/Xamarin.Shared/Xamarin.Shared.targets, msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.ObjCBinding.CSharp.After.targets
Traditionally we've disabled building projects when doing design-time builds
(in an IDE), because such builds have to be quick, but building binding
projects required a remote connection to a Mac when building from Windows.
However, we recently completed support for building binding projects fully on
Windows, with one caveat: the option to bundle original resources in the
binding assembly has to be enabled (off by default in .NET 9, on by default in
.NET 10+), because otherwise the remote mac connection is still needed.
So here we enable design-time builds, as long as the project is bundling
original resources, since the entire binding project will be built on Windows.
Fixes https://github.com/dotnet/macios/issues/10148.
=> [msbuild] Enable design-time builds for binding projects when bundling original resources. Fixes #10148.

msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
Recently we added support for fully building library and binding projects on
Windows, without connecting to a remote Mac.
This fix makes it so that we won't connect to the Mac when it's not needed.
=> [msbuild] Don't connect to a remote mac for library projects that are bundling original resources.

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.ObjCRuntime.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryObjCRuntimeTests.cs
This later is required to be able to generate out NSObject parameters in trampolines.
=> [RGen] Add code to generate a aux variable for a NativeHandle.

runtime/runtime.m, runtime/trampolines.m, runtime/xamarin/runtime.h, runtime/xamarin/trampolines.h, src/ObjCRuntime/DynamicRegistrar.cs, src/ObjCRuntime/Method.cs, src/ObjCRuntime/Registrar.cs, src/ObjCRuntime/Runtime.cs, tools/common/StaticRegistrar.cs
The following happens:
1. An instance of a custom NSObject subclass is created, with both a native instance
and the corresponding managed wrapper.
2. Native code creates a weak reference to the native instance.
3. No other managed code references the managed instance, and there's no non-weak
native reference to the native instance, so the GC schedules the managed instance
for finalization.
4. Native code fetches the native instance from the weak reference.
5. Native code thinks it can do whatever it wants with the native instance, because
it got a perfectly valid (and retained) native instance. Unfortunately, there's no way
to stop the managed instance from being finalized (which happens on a background
thread anyway, so there's no thread-safe way to do it), which means havoc ensues.
The …
=> [src/runtime] Don't allow native code to resolve a weak reference for an object in the finalizer queue.

runtime/runtime.m, runtime/trampolines.m, runtime/xamarin/runtime.h, runtime/xamarin/trampolines.h, src/ObjCRuntime/DynamicRegistrar.cs, src/ObjCRuntime/Method.cs, src/ObjCRuntime/Registrar.cs, src/ObjCRuntime/Runtime.cs, tools/common/StaticRegistrar.cs
The following happens:
1. An instance of a custom NSObject subclass is created, with both a native instance
and the corresponding managed wrapper.
2. Native code creates a weak reference to the native instance.
3. No other managed code references the managed instance, and there's no non-weak
native reference to the native instance, so the GC schedules the managed instance
for finalization.
4. Native code fetches the native instance from the weak reference.
5. Native code thinks it can do whatever it wants with the native instance, because
it got a perfectly valid (and retained) native instance. Unfortunately, there's no way
to stop the managed instance from being finalized (which happens on a background
thread anyway, so there's no thread-safe way to do it), which means havoc ensues.
The …
=> [release/9.0.1xx] [src/runtime] Don't allow native code to resolve a weak reference for an object in the finalizer queue.

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Trampoline.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/ExpectedTrampolinePropertyTestsTrampolines.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryTrampolineTests.cs
Use the block literal pointer created in the conversions and cast it to a NativeHandle.
=> [RGen] Correctly generate the args for BlockLiterals in the invoker call.

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Property.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Trampoline.cs, src/rgen/Microsoft.Macios.Generator/Emitters/ClassEmitter.cs, src/rgen/Microsoft.Macios.Generator/IO/TabbedStringBuilderExtensions.cs, src/rgen/Microsoft.Macios.Generator/Nomenclator.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/ExpectedTrampolinePropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryTrampolineTests.cs
Complete the property getter implementation by:
1. Including the return and the param attributes.
2. Convert the return type to the correct delegate.
This was done after completing the Trampolines.g.cs so that we could reuse a number of methods needed to generate that file. This should mean that we finally completed all possible properyt getters.
=> [RGen] Add support for the use of Callbacks/Trampolines in properties.

src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Arguments.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.ObjCRuntime.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Property.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Trampoline.cs, src/rgen/Microsoft.Macios.Generator/Emitters/ReturnInfo.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryObjCRuntimeTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryTrampolineTests.cs
The code is the same for properties, trampolines and methods. We add a intermediate readonly struct to customize the conversion and that way we can share the logic.
=> [RGen] Unifier the code that convers a native type to a managed one.

src/rgen/Microsoft.Macios.Generator/Emitters/ArgumentInfo.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Arguments.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Trampoline.cs, src/rgen/Microsoft.Macios.Generator/Emitters/TrampolineEmitter.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryArgumentsTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryTrampolineTests.cs
The refactor was wrong and we refactored the
GetTrampolineInitializationByRefArgument whichs does native -> managed instead of GetTrampolineNativeInvokeArgumentInitializations.
This commit undoos that mistake.
=> [Rgen] Fix an error from PR #23115

src/ObjCRuntime/DynamicRegistrar.cs, tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
Fixes https://github.com/dotnet/macios/issues/23070.
=> [src] Fix checking if a constraint implements INativeObject. Fixes #23070.

src/UIKit/UIBarButtonItem.cs
There are three constructors involved here:
1. (UIBarButtonSystemItem systemItem, EventHandler handler)
2. (UIBarButtonSystemItem systemItem, NSObject target, Selector action)
3. (UIBarButtonSystemItem systemItem, UIAction primaryAction, UIMenu menu)
The first constructor is a manually written convenience constructor, and needs
to call another constructor. Either the second or the third constructor works,
but the third constructor is only available on iOS 16+, while the second is
available on all iOS version.
This means that calling the third constructor is a bad idea, because it won't
work on anything before iOS 16. Unfortunately that's exactly what we did.
So change the code to call the second constructor instead.
This is a regression that was introduced in …
=> [UIKit] Make sure to invoke the correct constructor. Fixes #23122.

src/rgen/Microsoft.Macios.Generator/DataModel/Property.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Property.cs, src/rgen/Microsoft.Macios.Generator/Emitters/ClassEmitter.cs, src/rgen/Microsoft.Macios.Generator/Nomenclator.cs, src/rgen/Microsoft.Macios.Transformer/Microsoft.Macios.Transformer.csproj, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/iOSExpectedPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/macOSExpectedPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/tvOSExpectedPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/PropertyTests/GeneralPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/NomenclatorTests.cs
Ensure that those properties that require a backing field and need to be marked as dirty are correctly generated. The WeakDelegate properties are not curreclty supported since they are a special case.
=> [RGen] Add support for backing fields on properties.

src/UIKit/UIBarButtonItem.cs
Backport of #23127 
Fixes #23122
There are three constructors involved here:
1. (UIBarButtonSystemItem systemItem, EventHandler handler)
2. (UIBarButtonSystemItem systemItem, NSObject target, Selector action)
3. (UIBarButtonSystemItem systemItem, UIAction primaryAction, UIMenu menu)
The first constructor is a manually written convenience constructor, and needs
to call another constructor. Either the second or the third constructor works,
but the third constructor is only available on iOS 16+, while the second is
available on all iOS version.
This means that calling the third constructor is a bad idea, because it won't
work on anything before iOS 16. Unfortunately that's exactly what we did.
So change the code to call the second constructor instead.
This is a regression that was introduced …
=> [release/10.0.1xx-preview6] [UIKit] Make sure to invoke the correct constructor.

tools/devops/automation/scripts/VSTS.psm1, tools/devops/governance/tsa_config.gdntsa
Backport of #23143
by changing the area path in AzDO, I accidentally broke the integration with TSA. This PR fixes the area path to point to the correct location.
=> [release/10.0.1xx-preview6] Update TSA Area Path to DevDiv\.NET MAUI

tools/devops/automation/scripts/VSTS.psm1, tools/devops/governance/tsa_config.gdntsa
by changing the area path in AzDO, I accidentally broke the integration with TSA. This PR fixes the area path to point to the correct location.
=> Update TSA Area Path to DevDiv\.NET MAUI

tools/common/Frameworks.cs
It's available in at least Xcode 15, maybe even earlier (I didn't test).
Fixes https://github.com/dotnet/macios/issues/23121#issuecomment-2995422413.
=> [tools] Mark CoreNFC as available in the simulator.

src/ObjCBindings/ExportTag.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Property.Generator.cs, src/rgen/Microsoft.Macios.Transformer/DataModel/Property.Transformer.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/PropertyTests/GeneralPropertyTests.cs
Do not use the name of the property to decide if it is a WeakDelegate but use a flag. This will allow to know if we are generating WeakDelegate property.
=> [RGen] Add a new property to mark properties as WeakDelegates.

system-dependencies.sh
Fix version comparison when there's only a single number in the version.
Fixes this system check warning:
> You should have exactly CoreSimulator.framework version 1043 (found 1043.0).
=> [system-dependencies] Fix CoreSimulator version check.

src/ObjCBindings/ExportAttribute.cs, src/ObjCBindings/ExportTag.cs, src/rgen/Microsoft.Macios.Generator/Attributes/ExportData.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Method.Generator.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Attributes/ExportDataTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/MethodTests/FromDeclarationTests.cs
Add extra data for the Export method that will only will be present when the async flags is present in the Export method. This allows to mark methods as async to be generated.
=> [Rgen] Add extra attribute data for async methods.

src/ObjCBindings/ExportAttribute.cs, src/ObjCBindings/ExportTag.cs, src/rgen/Microsoft.Macios.Generator/Attributes/ExportData.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Method.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Method.cs, src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfo.cs, src/rgen/Microsoft.Macios.Generator/Emitters/ClassEmitter.cs, src/scenekit.cs, src/spritekit.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Attributes/ExportDataTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/ClassGenerationTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/MethodTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/tvOSExpectedMethodsTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/MethodTests/FromDeclarationTests.cs
This commit adds the signatures of the async methods when a method is marked as Async. The code removes the last parameter of the original method - it is the callback - and updates the return type to be of the correct Task generic type.
=> [Rgen] Add the signatures of async methods.

src/rgen/Microsoft.Macios.Generator/DataModel/DelegateInfo.cs, src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfo.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Runtime.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Trampoline.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.cs, src/rgen/Microsoft.Macios.Generator/Extensions/ArgumentSyntaxExtensions.cs, src/rgen/Microsoft.Macios.Generator/Formatters/TypeInfoFormatter.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/ExpectedMethodsTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/MethodTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/tvOSExpectedMethodsTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/DelegateInfoTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/MethodTests/FromDeclarationTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/TypeInfoTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryRuntimeTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/TestDataFactory.cs
When a binding has an async method we give the developer the freedom to provide a ResultType or a ResultTypeName to generate a class. This works when we want some kind of specialization, for example overriding the Initialize method.
In most cases we do not add any extra Initialize method implementation to async return types so adding that extra parameter in the ExportAttribute is error prone (new commers tend to forget). Rgen with this commit will generate async methods that will use Tuples or NamedTuples when generating the code.
- Tuples: If the delegate was created using an Action<T> we do not want to use the default names, since they are arg1, arg2, etc.. In that case, we use a Tuple.
- Named Tuples: This are used when we use a delegate with logical named parameters.
If a user was to …
=> [RGen] If not class is provide for an Async method use Tuples.

src/rgen/Microsoft.Macios.Generator/DataModel/Method.Generator.cs, src/rgen/Microsoft.Macios.Generator/Emitters/ArgumentInfo.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Arguments.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Methods.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.ObjCRuntime.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Property.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Trampoline.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.cs, src/rgen/Microsoft.Macios.Generator/Emitters/ClassEmitter.cs, src/rgen/Microsoft.Macios.Generator/Emitters/MethodInvocations.cs, src/rgen/Microsoft.Macios.Generator/Emitters/ReturnInfo.cs, src/rgen/Microsoft.Macios.Generator/Emitters/TrampolineArgumentSyntax.cs, src/rgen/Microsoft.Macios.Generator/Emitters/TrampolineEmitter.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/ExpectedMethodsTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/MethodTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/iOSExpectedPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/macOSExpectedPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/tvOSExpectedMethodsTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/tvOSExpectedPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryArgumentsTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryMethodTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryObjCRuntimeTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/ReturnInfoTests.cs
Adds the generation of the sync methods. This is a list of the needed changes:
1. Improved how we deal with out parameters. This were not correctly exercised in delegates and properties as we have some small bugs.
2. Generate the method calls for sync methods in the class emitter.
3. Updated the tests to make methods virtual (if not static) and usafe. The modifiers will be provided by the new sharpie.
4. For async methods, remove the unsafe modifiers.
=> [Rgen] Generate sync methods.

msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx, msbuild/Xamarin.MacDev.Tasks/Tasks/ResolveNativeReferences.cs
"body": null,
Backport of #23252.
=> [release/9.0.1xx] [msbuild] Improve diagnostics when we fail to process an xcframework.

tests/monotouch-test/dotnet/shared.csproj
We don't have the required provisioing profiles set up.
=> [monotouch-test] Don't use entitlements when building for device.

NuGet.config, eng/Version.Details.xml, eng/Versions.props, global.json
This reverts commit 5feed5c9d7bc8dd05cce95f85c928a2902cfdca1.
This commit adds internal nuget feeds, which we want to avoid.
=> Revert "[release/9.0.1xx] Update dependencies from dotnet/sdk (#22770)"

dotnet/targets/Xamarin.Shared.Sdk.props
Visual Studio Build Acceleration is a feature designed to avoid rebuilding a project when changes occur in its project references.
For example, if you have an iOS app project and a MAUI class library that includes XAML files, an incremental change to the XAML will not trigger a rebuild of the iOS project. Instead, the updated assembly is simply copied into the iOS project’s output directory.
However, this behavior is not compatible with iOS builds, since the final app bundle is produced as part of the build process. As a result, skipping the build step can lead to unexpected behavior as incremental changes not reflected in the app.
For more details, see the https://github.com/dotnet/project-system/blob/main/docs/build-acceleration.md.
=> [vs] Disable build acceleration

src/bgen/Generator.cs
Old message:
error BI1078: bgen: Do not know how to make a signature for System.Object in method `get_ModifierFlags'
New message:
error BI1078: bgen: Do not know how to make a signature for System.Object in method `WebKit.WKNavigationAction.get_ModifierFlags'
=> [bgen] Improve the BI1078 error message to include the type name.

src/ObjCBindings/BindingTypeAttribute.cs, src/rgen/Microsoft.Macios.Generator/Attributes/BindingTypeData.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/BindingInfoTests.cs
This allows to pass the type rather than the name of the type which is a safer approach since the compiler will help us. The creation of a Category will now look like:
```csharp
[Binding<Category>(typeof (NSObject))]
public static class MyCategory {
// static extension methods
}
```
=> [RGen] Update the BindingAttribute to allow to pass the type for a category.

src/rgen/Microsoft.Macios.Generator/Emitters/ClassEmitter.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/CIImage.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/ExpectedCIImage.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/ExpectedMethodsTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/ExpectedThreadSafeAppKitPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/ExpectedThreadSafeUIKitPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/MethodTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/PropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/ThreadSafeAppKitPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/ThreadSafeUIKitPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/iOSExpectedPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/macOSExpectedPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/tvOSExpectedMethodsTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/tvOSExpectedPropertyTests.cs
We must add the availability to the top of the class generated for consistency. The reality is that is not needed but we are adding it to reduce the diff with the old code generated by bgen (important for the migration).
=> [RGen] Add missing availability in the class declaration.

src/rgen/Microsoft.Macios.Generator/DataModel/Binding.Generator.cs, src/rgen/Microsoft.Macios.Generator/Extensions/BaseTypeDeclarationSyntaxExtensions.cs, src/rgen/Microsoft.Macios.Transformer/DataModel/Binding.Transformer.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Extensions/BaseTypeDeclarationSyntaxExtensionsTests.cs
We have access to the semantic model which means that we can rely on the symbol to get the fully qualified name. This approach is more efficient that walking the AST, uses less code and still allows use to customize the way the fully qualified name is created.
=> [RGen] Performance improvement by using the semantic model over parsing the AST.

src/Makefile, src/frameworks.sources
This validation found a file that we weren't compiling because of a typo, and as
such we never noticed that the file never existed in the first place.
=> [src] Add validation to ensure we compile everything we have, and that we have everything we want to compile

builds/create-csproj-for-all-packagereferences.sh, dotnet/targets/Xamarin.Shared.Sdk.targets, msbuild/Xamarin.Shared/Xamarin.Shared.targets, tests/dotnet/AppWithXCFrameworkWithSymlinks/AppDelegate.cs, tests/dotnet/AppWithXCFrameworkWithSymlinks/MacCatalyst/AppWithXCFrameworkWithSymlinks.csproj, tests/dotnet/AppWithXCFrameworkWithSymlinks/MacCatalyst/Makefile, tests/dotnet/AppWithXCFrameworkWithSymlinks/Makefile, tests/dotnet/AppWithXCFrameworkWithSymlinks/iOS/AppWithXCFrameworkWithSymlinks.csproj, tests/dotnet/AppWithXCFrameworkWithSymlinks/iOS/Makefile, tests/dotnet/AppWithXCFrameworkWithSymlinks/macOS/AppWithXCFrameworkWithSymlinks.csproj, tests/dotnet/AppWithXCFrameworkWithSymlinks/macOS/Makefile, tests/dotnet/AppWithXCFrameworkWithSymlinks/shared.csproj, tests/dotnet/AppWithXCFrameworkWithSymlinks/shared.mk, tests/dotnet/AppWithXCFrameworkWithSymlinks/tvOS/AppWithXCFrameworkWithSymlinks.csproj, tests/dotnet/AppWithXCFrameworkWithSymlinks/tvOS/Makefile, tests/dotnet/UnitTests/WindowsTest.cs, tests/test-libraries/nugets/Makefile, tests/test-libraries/nugets/XCFrameworkWithSymlinks/Makefile, tests/test-libraries/nugets/XCFrameworkWithSymlinks/XCFrameworkWithSymlinks.csproj, tests/test-libraries/nugets/XCFrameworkWithSymlinks/manifest, tools/devops/automation/templates/windows/build.yml
Make sure that non-iOS platforms build successfully on non-macOS platforms,
even if the actual output is not usable. This makes developing on Windows
easier.
Fixes https://github.com/dotnet/macios/issues/23101.
=> [msbuild] Make sure that non-iOS platforms build successfully on non-macOS platforms. Fixes #23101.

src/rgen/Microsoft.Macios.Bindings.Analyzer/Microsoft.Macios.Bindings.Analyzer.csproj, src/rgen/Microsoft.Macios.Generator/DataModel/AttributesEqualityComparer.cs, src/rgen/Microsoft.Macios.Generator/DataModel/EnumMembersEqualityComparer.cs, src/rgen/Microsoft.Macios.Generator/DataModel/ImmutableArrayEqualityComparer.cs, src/rgen/Microsoft.Macios.Generator/DataModel/ModifiersEqualityComparer.cs, src/rgen/Microsoft.Macios.Generator/DataModel/OuterClassEqualityComparer.cs
Reduce the code by using a generic abstract class. Resulting behaviour is the same but with less lines.
=> [RGen] Simplify ImmutableArray Equality comparers via generics.

src/ObjCBindings/ExportTag.cs, src/rgen/Microsoft.Macios.Generator/Attributes/ProtocolMemberData.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Method.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Method.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Property.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Property.cs, src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfo.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfo.cs, src/rgen/Microsoft.Macios.Generator/IO/TabbedStringBuilderExtensions.cs, src/rgen/Microsoft.Macios.Transformer/Attributes/ExportData.cs, src/rgen/Microsoft.Macios.Transformer/DataModel/Method.Transformer.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Attributes/ProtocolMemberDataTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/iOSExpectedPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/macOSExpectedPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Classes/Data/tvOSExpectedPropertyTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/MethodTests/FromDeclarationTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/IO/TabbedStringBuilderTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/ProtocolMemberCustomEqualityComparer.cs, tests/rgen/Microsoft.Macios.Generator.Tests/TestDataFactory.cs, tests/rgen/Microsoft.Macios.Generator.Tests/TypeInfoCustomEqualityComparer.cs
Add a new structure that represents the data of the attr and several methods that allow to create the structure from the data found in a protocol declaration.
This changes will be used to create al the attrs needed by the static registrar in a protocol definition.
=> [RGen] Add support for the ProtocolMemberAttribute.

src/rgen/Microsoft.Macios.Bindings.Analyzer/Microsoft.Macios.Bindings.Analyzer.csproj, src/rgen/Microsoft.Macios.Generator/DataModel/Binding.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/FieldInfo.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Property.Generator.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Dlfcn.cs, src/rgen/Microsoft.Macios.Generator/Emitters/ClassEmitter.cs, src/rgen/Microsoft.Macios.Generator/StructState.cs, src/rgen/Microsoft.Macios.Transformer/Microsoft.Macios.Transformer.csproj, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/EnumMemberCodeChangesTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/PropertyTests/GeneralPropertyTests.cs
Remove the need to create a heap Nullable object for the FieldInfo attribute in properties, this is done to reduce the GC pressure and improve performance. A follow up PR will do the same for the ExportData attr.
=> [RGen] Remove boxing of Nullable<FieldInfo> in properties.

tools/devops/automation/scripts/install-qa-provisioning-profiles.sh, tools/devops/automation/templates/common/install-qa-provisioning-profiles.yml
Azure DevOps' UI to add and modify secure files is utterly horrible.
* There's no way to modify a secure file, you have to delete it and re-add it.
* There's no documented way to add/remove a secure file using the REST API,
although there's apparently an un-official REST API
(https://github.com/microsoft/azure-pipelines-tasks/issues/9172#issuecomment-466024682),
which was apparently supposed to become documented, which was over 6 years
ago and in the meantime the only thing that happened was that the issue got
closed.
* There's no way to update the security settings for a secure file using the
REST API that I could find, and the UI to do so is _sloooooow_ and clunky.
So instead of going through the pain of adding/deleting/updating 19 different
files, add them all in a single zip file, and …
=> [devops] Use a zip file with all the certificates and provisioning profiles.

tools/devops/automation/scripts/install-qa-provisioning-profiles.sh, tools/devops/automation/templates/common/install-qa-provisioning-profiles.yml
Azure DevOps' UI to add and modify secure files is utterly horrible.
* There's no way to modify a secure file, you have to delete it and re-add it.
* There's no documented way to add/remove a secure file using the REST API,
although there's apparently an un-official REST API
(https://github.com/microsoft/azure-pipelines-tasks/issues/9172#issuecomment-466024682),
which was apparently supposed to become documented, which was over 6 years
ago and in the meantime the only thing that happened was that the issue got
closed.
* There's no way to update the security settings for a secure file using the
REST API that I could find, and the UI to do so is _sloooooow_ and clunky.
So instead of going through the pain of adding/deleting/updating 19 different
files, add them all in a single zip file, and …
=> [release/9.0.1xx] [devops] Use a zip file with all the certificates and provisioning profiles.

runtime/exports.t4, runtime/monovm-bridge.m
Call `mono_jit_cleanup` upon exit, because profilers depend on this to flush
buffers, etc.
Also use `mono_jit_init` instead of `mono_jit_init_version`, because the
latter is deprecated.
Ref: https://github.com/dotnet/diagnostics/issues/5529#issuecomment-3138842754
=> [runtime] Call mono_jit_cleanup upon exit.

src/foundation.cs, tools/compare-commits.sh, tools/devops/automation/templates/build/api-diff-build-and-detect.yml, tools/devops/automation/templates/build/api-diff-stage.yml
We used to have the API diff be non-fatal, because it would fail the entire
build.
However, this isn't the case anymore, so treat API diff like any other test:
if it fails, fail the job.
=> [devops] Make a failing API diff fail the corresponding job.

docs/building-apps/build-properties.md, docs/configuration-properties.md, dotnet/targets/Xamarin.Shared.Sdk.targets
Context: dotnet/maui#31058
Context: dotnet/android#10388
We are in the process of adding `Metrics` to .NET MAUI to enable `dotnet-counters` such as:
> dotnet-counters monitor --dsrouter ios --counters Microsoft.Maui
Press p to pause, r to resume, q to quit.
Status: Running
Name                                      Current Value
[Microsoft.Maui]
maui.layout.arrange_count ({times})               6
maui.layout.arrange_duration (ns)
Percentile
50                                      518,656
95                                    2,367,488
99                                    2,367,488
maui.layout.measure_count ({times})              11
maui.layout.measure_duration (ns)
Percentile
50                                      389,632
95                                   28,475,392
99 …
=> [net10.0] Update the default value for 'EventSourceSupport' and 'MetricsSupport'.

tools/devops/automation/scripts/GitHub.psm1
Some comments fail to hide because:
> Warning: Failed to hide comment for non-latest commit: Cannot convert argument "restCommentId", with value: "3177717194", for "HideNewlyPostedComment" to type "System.Int32": "Cannot convert value "3177717194" to type "System.Int32". Error: "Value was either too large or too small for an Int32.""
Looking at the code, I found an area of improvement in HideNewlyPostedComment:
we have the underlying id for the comment we want to hide, yet we search all
the comments in the PR to find those matching a certain string and hide those.
Simplify this to just hide the comment with the underlying id. Additionally
pass the underlying id around as a string, that way we avoid any problems with
parsing integers. This made the entire HideNewlyPostedComment unused, so …
=> [devops] Fix hiding comments.

mk/xamarin.mk, tests/dotnet/UnitTests/MlaunchTest.cs
This _might_ be enough to make .NET 9 kind of work with Xcode 26.
=> Bump mlaunch to get a version that works with Xcode 26.

tools/devops/automation/scripts/bash/collect-and-upload-crash-reports.sh, tools/devops/automation/templates/build/build.yml
This makes it easier to diagnose bugs elsewhere if they cause .NET to crash.
=> [devops] Enable the generation of minidumps if dotnet crashes.

mk/xamarin.mk, tests/dotnet/UnitTests/MlaunchTest.cs
This _might_ be enough to make .NET 9 kind of work with Xcode 26.
Backport of #23499.
=> [release/9.0.1xx] Bump mlaunch to get a version that works with Xcode 26.

system-dependencies.sh
Example scenario:
1. Apple releases iOS 18.5 + corresponding Xcode, we update our build and
versions accordingly.
2. Apple releases iOS 18.6, without a corresponding Xcode, but with a new iOS
18.6 simulator which is installed whenever you ask Xcode to install the iOS
simulator. This causes problems, because now xharness will ask for an iOS
18.5 simulator, which may no be installed, because our install scripts
inadvertedly installs the iOS 18.6 simulator.
The fix is to make our install script explicitly install the simulator version
we expect to be installed.
=> [system-dependencies] Explicitly install the simulator version we're built for.

system-dependencies.sh
Example scenario:
1. Apple releases iOS 18.5 + corresponding Xcode, we update our build and
versions accordingly.
2. Apple releases iOS 18.6, without a corresponding Xcode, but with a new iOS
18.6 simulator which is installed whenever you ask Xcode to install the iOS
simulator. This causes problems, because now xharness will ask for an iOS
18.5 simulator, which may no be installed, because our install scripts
inadvertedly installs the iOS 18.6 simulator.
The fix is to make our install script explicitly install the simulator version
we expect to be installed.
Backport of #23670.
=> [release/9.0.1xx] [system-dependencies] Explicitly install the simulator version we're built for.

.azuredevops/policies/branchClassification.yml, tools/devops/automation/templates/release/vs-insertion-prep.yml
- Use the new sign-artifacts v4 that is already configured to enable PME for real signing. We use this to sign our NuGet pacakges.
- Adds production declaration our release branches as their names do not match 1ES classification.
=> [ci] Enable PME when signing NuGet packages

tests/monotouch-test/Network/NWPathTest.cs
This prevents random failures when running tests.
=> [tests] Adjust NWPathTest.LinkQuality to accept a wider range of network connectivity.

tests/monotouch-test/AppKit/NSDraggingItem.cs, tests/monotouch-test/AppKit/NSPasteboard.cs, tests/monotouch-test/AppKit/NSTextFinder.cs, tests/monotouch-test/ScriptingBridge/SBApplicationTest.cs
Fix a few formatting issues that the autoformat script only fix when the
macios working directory is fully built (because the offending code is behind
conditional compilation symbols, which are only defined in a fully built
working copy).
=> [tests] Fix a few formatting issues.

src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.Designer.cs, src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.resx, src/rgen/Microsoft.Macios.Bindings.Analyzer/RgenDiagnostics.cs, src/rgen/Microsoft.Macios.Bindings.Analyzer/Validator.cs, src/rgen/Microsoft.Macios.Bindings.Analyzer/Validators/ArrayValidator.cs, src/rgen/Microsoft.Macios.Bindings.Analyzer/Validators/FieldValidator.cs, src/rgen/Microsoft.Macios.Bindings.Analyzer/Validators/PropertyStrategies.cs, src/rgen/Microsoft.Macios.Bindings.Analyzer/Validators/PropertyValidator.cs, src/rgen/Microsoft.Macios.Bindings.Analyzer/Validators/StringStrategies.cs, tests/rgen/Microsoft.Macios.Bindings.Analyzer.Tests/Validators/ArrayValidatorTests.cs, tests/rgen/Microsoft.Macios.Bindings.Analyzer.Tests/Validators/PropertyValidatorTests.cs
Changes in this commit:
1. Added a generic array validator that will validate an array using an inner validator.
2. Added a property validator that validates the following from a property:
- Export<Property> attribute is valid.
- Must be declared partial.
- Supported platforms shoul be correct for the accessors.
- Validate each of the accessor selectors if they have been added.
Extra changes:
1. While test the property validator I found out that we were duplicating errors in nested valiators. There is no need to add a new strategy when adding a nested validator.
2. Updated some of the error messages in the FieldValidator since we got one of the descriptors wrong.
3. Added a new string strategy to ensure that the number of ':' is a selector matches the number of arguments in a method (this …
=> [RGen] Add two new validators one for arrays one for properties.

mk/rules.mk
This way clang will show the full paths to files when emitting errors and
warnings, which makes it much easier to c&p the path to open it in an editor.
=> [mk] Pass -fdiagnostics-absolute-paths to clang.

tests/xtro-sharpie/xtro-report/Reporter.cs
Adds a Vibe Coded 🤖 (Yay Copilot) dark mode to xtro test report so I do not keep being blinded every time I open a report in my all dark themed environment 😎
=> [Tests] Adds Dark mode to xtro test report

macios/Localize/loc/cs/macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.resx.lcl, macios/Localize/loc/it/macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.resx.lcl, macios/Localize/loc/ja/macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.resx.lcl, macios/Localize/loc/zh-Hans/macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.resx.lcl
LEGO: Pull request from lego/hb_5df43909-4a19-4f55-bc3f-9ea8fccf3c82_20250906173919255 to main with localized lcls
=> LEGO: Pull request from lego/hb_5df43909-4a19-4f55-bc3f-9ea8fccf3c82_20250906173919255 to main

tests/cecil-tests/BlittablePInvokes.cs
These tests aggregate test failures across all platforms, which means any
known failure list might be incorrect if not testing all platforms.
=> [tests] Ignore any blittable P/Invoke test if not all platforms are enabled.

src/Foundation/NSUrlSessionHandler.cs, tests/monotouch-test/System.Net.Http/MessageHandlers.cs
* Add a `CertificateChainPolicy` property to `NSUrlSessionHandler` to make it
possible for developers to customize the the policy that is used when
validating certificate chains when using a custom server certificate
validation.
* Also implement `NSUrlSessionHandler.CheckCertificateRevocationList` using
the new `CertificateChainPolicy` property.
Fixes https://github.com/dotnet/macios/issues/23764.
=> [Foundation] Make it possible to customize the X509ChainPolicy when validating certificates in NSUrlSessionHandler. Fixes #23764.

src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.Designer.cs, src/rgen/Microsoft.Macios.Bindings.Analyzer/Resources.resx, src/rgen/Microsoft.Macios.Bindings.Analyzer/RgenDiagnostics.cs, src/rgen/Microsoft.Macios.Bindings.Analyzer/Validators/ClassValidator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/Method.Generator.cs, src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Methods.cs, src/rgen/Microsoft.Macios.Generator/Emitters/ClassEmitterExtensions.cs, tests/rgen/Microsoft.Macios.Bindings.Analyzer.Tests/ClassAnalyzerTests.cs
Ensure that:
1. If a method can be async, that is marked as such (warning).
2. Make sure marked async methods return void (error).
3. Make sure marked async methods have a delegate (error).
4. Make sure that Async methods have diff async names if the parameters are the same (error).
The tests showed a number of bugs in the async generation when we use the async flag with no parameters. Those got fixed.
=> [RGen] Add analyzer rules for async methods in a class.

macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.cs.resx, macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.de.resx, macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.es.resx, macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.fr.resx, macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.it.resx, macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.ja.resx, macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.ko.resx, macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.pl.resx, macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.pt-BR.resx, macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.ru.resx, macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.tr.resx, macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.zh-Hans.resx, macios/src/rgen/Microsoft.Macios.Bindings.Analyzer/TranslatedAssemblies/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 14411: Build ID 12356888

src/rgen/Microsoft.Macios.Generator/IO/TabbedStringBuilderAvailability.cs, src/rgen/Microsoft.Macios.Transformer/IO/TabbedStreamWriterExtensions.cs, src/rgen/Microsoft.Macios.Transformer/Microsoft.Macios.Transformer.csproj, tests/rgen/Microsoft.Macios.Transformer.Tests/IO/TabbedStreamWriterTests.cs
This method will later be used to write the trivia and the symbol availability when doing the transformations.
=> [RGgen] Provide helper methods for the transformer stream writer.

src/rgen/Microsoft.Macios.Generator/Availability/PlatformSupportVersion.cs, src/rgen/Microsoft.Macios.Generator/Availability/SupportKind.cs, tests/rgen/Microsoft.Macios.Generator.Tests/Availability/PlatformSupportVersionTests.cs
When adding a platform to a symbol it might be the case that the addition has an implication for another platform. For example, when we add support for iOS we are adding support for Catalyst. This new struct keeps track of the reason why a version was added and will allow to choose always the Explicit version when two versions are compared.
This will later can be used with the Builder class to add Implicit versions for a platform and be able to calculate which version to use.
=> [RGen] Add a new type to track versions.

src/rgen/Microsoft.Macios.Generator/DataModel/Binding.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/EnumMember.Generator.cs, src/rgen/Microsoft.Macios.Generator/DataModel/EnumMember.cs, src/rgen/Microsoft.Macios.Transformer/DataModel/Binding.Transformer.cs, src/rgen/Microsoft.Macios.Transformer/DataModel/EnumMember.Transformer.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/BindingComparerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/BindingEqualityComparerTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/BindingTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/EnumMemberCodeChangesTests.cs, tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/EnumMembersEqualityComparerTests.cs, tests/rgen/Microsoft.Macios.Transformer.Tests/DataModel/SmartEnumTests.cs
This is needed by the transformer so that we can ensure that the enums are placed in the correct location when transforming APIs that might have diff members per platform.
=> [RGen] Keep the track of the enum member position.

msbuild/Xamarin.MacDev.Tasks/Tasks/CompileEntitlements.cs
And it requires a provisioning profile to enable it.
=> [msbuild] The App Groups entitlement is available on all platforms.

msbuild/Xamarin.MacDev.Tasks/Tasks/ParseBundlerArguments.cs, tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/ParseBundlerArgumentsTests.cs
This will avoid setting the _BundlerVerbosity property if the
AppBundleExtraOptions property doesn't specify any verbosity options.
=> [msbuild] Fix parsing bundler verbosity.

tests/monotouch-test/Security/SecProtocolMetadataTest.cs
Fixes this random test failure:
MonoTouchFixtures.Security.SecProtocolMetadataTest
[FAIL] TlsDefaults :   PeerPublicKey
Expected: not null
But was:  null
at MonoTouchFixtures.Security.SecProtocolMetadataTest.TlsDefaults() in tests/monotouch-test/Security/SecProtocolMetadataTest.cs:line 72
MonoTouchFixtures.Security.SecProtocolMetadataTest : 131.9134 ms
=> [tests] Adjust SecProtocolMetadataTest to be a bit more permissive.

tests/monotouch-test/MediaAccessibility/CaptionAppearanceTest.cs
Fixes:
MonoTouchFixtures.MediaAccessibility.CaptionAppearanceTest
[FAIL] TestProfiles :   ActiveProfileId#2
Expected string length 26 but was 24. Strings differ at index 17.
Expected: "MACaptionProfile-LargeText"
But was:  "MACaptionProfile-Default"
----------------------------^
at MonoTouchFixtures.MediaAccessibility.CaptionAppearanceTest.TestProfiles() in /Users/builder/azdo/_work/1/s/macios/tests/monotouch-test/MediaAccessibility/CaptionAppearanceTest.cs:line 66
MonoTouchFixtures.MediaAccessibility.CaptionAppearanceTest : 442.6109 ms
=> [tests] Be a bit more lenient in CaptionAppearanceTest.TestProfiles.

src/uikit.cs, tests/cecil-tests/Documentation.KnownFailures.txt
Fixes https://github.com/dotnet/macios/issues/14177.
=> [UIKit] Add a weakly typed UIMenu.Identifier property and UIMenu.Create overload. Fixes #14177.

src/networkextension.cs
And since it's a breaking change, only in XAMCORE_5_0.
Fixes https://github.com/dotnet/macios/issues/16789.
=> [NetworkExtension] Fix nullability for NETunnelProvider.HandleAppMessage. Fixes #16789.
