- runtime/runtime.m
If `old_gchandle` is not set (0) then the function returns early,
so can't be 0 after the `MONO_THREAD_ATTACH` meaning:
* the `else` branch is never executed;
* the `exception_gchandle` is never set to something other than 0
* ` if (exception_gchandle == 0) {` is always `true` and can be removed (diff looks bigger than it is because of indentation change)
* the call to `xamarin_process_managed_exception_gchandle` is unneeded
> [runtime] Simplify `xamarin_switch_gchandle` by removed dead code

- src/CoreGraphics/CGEventTypes.cs
https://github.com/xamarin/xamarin-macios/wiki/CoreGraphics-macOS-xcode11.2-beta2
> [CoreGraphics] Add CoreGraphics bindings for xcode11.2b2

- src/metalperformanceshaders.cs
- tests/xtro-sharpie/iOS-MetalPerformanceShaders.todo
- tests/xtro-sharpie/macOS-MetalPerformanceShaders.todo
- tests/xtro-sharpie/tvOS-MetalPerformanceShaders.todo
Xcode11.1 GM Diff - https://github.com/xamarin/xamarin-macios/wiki/MPSCore-iOS-xcode11.1-GM
Added missing 'offset' selector
> [MPSCore] Xcode11.1 GM Binding

- tests/introspection/ApiTypoTest.cs
Fixes: https://github.com/xamarin/maccore/issues/2052
> [Tests] Fix introspection failing due to a typo.

- tests/introspection/ApiTypoTest.cs
Fixes: https://github.com/xamarin/maccore/issues/2052
Backport of #7369.
> [master] [Tests] Fix introspection failing due to a typo.

- src/UIKit/UITraitCollection.cs
> Added Static to UITraitCollection.FromPreferredContentSizeCategory

- src/fileprovider.cs
https://github.com/xamarin/xamarin-macios/wiki/FileProvider-iOS-xcode11.2-beta1
> [FileProvider] Add FileProvider binding xcode11.2b1

- mk/xamarin.mk
Diff: https://github.com/xamarin/maccore/compare/f56575dcc2ec2d8975ea328feeeea697b7b2194b..92433b7757c57de089b3edb0e7060d90363273f9
> Bump maccore to get mlaunch fix.

- src/Foundation/NSString2.cs
- tests/apitest/src/Foundation/NSString.cs
> Add IComparable<T> to NSString

- src/Network/NWEthernetChannel.cs
- src/Network/NWParameters.cs
- src/frameworks.sources
- tests/xtro-sharpie/common-Network.ignore
- tests/xtro-sharpie/iOS-Network.todo
- tests/xtro-sharpie/macOS-Network.todo
- tests/xtro-sharpie/tvOS-Network.todo
- tests/xtro-sharpie/watchOS-Network.todo
Add missing APIs and complete the bindings for Xcode 11.
> [Networking] Add missing Mac OS X APIs.

- src/AVFoundation/AVMetadataObject.cs
Should solve https://github.com/xamarin/xamarin-macios/issues/7472
> [AVFoundation] Added mappings to AVMetadataObject.EnumToObject

- tests/xharness/AppRunner.cs
This will hopefully stop the runaway mlaunch processes we've seen on the bots.
Ref: https://github.com/xamarin/maccore/issues/1965.
Backport of #7499.
> [xcode11.3] [xharness] Make sure to always stop log and system capture.

- src/Network/NWParameters.cs
- tests/monotouch-test/Network/NWParametersTest.cs
Fixes: https://github.com/xamarin/xamarin-macios/issues/7513
> [Network] Add missing BindingImplAttr.

- docs/website/generator-errors.md
- src/Makefile.generator
- src/bgen
- src/btouch-native
- src/btouch.in
- src/btv
- src/bwatch
- tools/mtouch/Makefile
- tools/mtouch/mtouch
- tools/mtouch/mtouch.in
It makes relocating XI/XM easier.
> Use relative paths in scripts.

- msbuild/Xamarin.Mac.Tasks.Core/Tasks/ALToolUploadTaskBase.cs
- msbuild/Xamarin.Mac.Tasks.Core/Tasks/ALToolValidateTaskBase.cs
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/AlToolTaskBase.cs
- msbuild/Xamarin.iOS.Tasks.Core/Tasks/ALToolUploadTaskBase.cs
- msbuild/Xamarin.iOS.Tasks.Core/Tasks/ALToolValidateTaskBase.cs
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Affected targets:
* ValidateAppStoreBundle
* UploadAppStoreBundle
Attempt to fix: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1029041
> [vsts-1029041] Add FileType to the list of parameters for altool

- msbuild/Xamarin.Mac.Tasks.Core/Tasks/ALToolUploadTaskBase.cs
- msbuild/Xamarin.Mac.Tasks.Core/Tasks/ALToolValidateTaskBase.cs
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/AlToolTaskBase.cs
- msbuild/Xamarin.iOS.Tasks.Core/Tasks/ALToolUploadTaskBase.cs
- msbuild/Xamarin.iOS.Tasks.Core/Tasks/ALToolValidateTaskBase.cs
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Affected targets:
* ValidateAppStoreBundle
* UploadAppStoreBundle
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1029041
Backport of #7533.
/cc @olegoid
> [d16-5] [vsts-1029041] Add FileType to the list of parameters for altool

- tests/introspection/Mac/MacApiCtorInitTest.cs
- tests/introspection/Mac/MacApiProtocolTest.cs
> [d16-5] [introspection] Update according to changes that seem to have occurred in macOS 10.15.2.

- tools/common/FileCopier.cs
- tools/common/cache.cs
This reverts commit b3bc04c919a00b82c67fc7157a03b353f8b75f38.
> Revert "[mtouch] Fix caching issues. Fix #7514 (#7544)"

- tests/introspection/Mac/MacApiCtorInitTest.cs
- tests/introspection/Mac/MacApiProtocolTest.cs
Backport of #7567.
/cc @spouliot @rolfbjarne
> [xcode11.3] [introspection] Update according to changes that seem to have occurred in macOS 10.15.2.

- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Tasks.csproj
- msbuild/Xamarin.Mac.Tasks/packages.config
- msbuild/Xamarin.iOS.Tasks/Xamarin.iOS.Tasks.csproj
- msbuild/Xamarin.iOS.Tasks/packages.config
The latest ILRepack has fixes for netstandard we'll need.
Also use package references.
> [msbuild] Update to latest ILRepack.

- msbuild/Xamarin.MacDev.Tasks/Xamarin.MacDev.Tasks.csproj
- msbuild/Xamarin.MacDev.Tasks/packages.config
One of many steps towards building for netstandard 2.0.
> [msbuild] Use package references.

- tools/common/FileCopier.cs
Copying the framework could fail (error 260) and the failure was never
reported so the build succeeded - but without updating (completely) the
framework.
The exact reason it fails is unknown :( but we can recover from it by
deleting the target and copying (everything) back to the expected
(target) location.
Build logs will now indicate when this fails and will try to recover
before reporting a build error. Best case it works :) worse case we'll
be aware something is wrong (which is better than ignoring)
This is half the fix from https://github.com/xamarin/xamarin-macios/pull/7544
which was reverted due to the second half causing a regression (under
investigation).
Reference: https://github.com/xamarin/xamarin-macios/issues/7514 (partial fix)
> [mtouch] Fix case where `copyfile` could fail silently

- tools/common/Tuning.cs
- tools/mmp/Tuning.cs
- tools/mmp/mmp.csproj
- tools/mtouch/Tuning.cs
- tools/mtouch/mtouch.csproj
Originally https://github.com/xamarin/xamarin-macios/pull/6616
I fixed the style issue. 
@rolfbjarne it is difficult to test without adding a way to make mmp/mtouch throw an exception conditionally.
Thoughts?
> mtouch/mmp assembly resolution spam (Take II)

- Make.config
- runtime/Makefile
- src/CFNetwork/CFHTTPMessage.cs
- src/CoreFoundation/DispatchData.cs
- src/Makefile
- src/Makefile.generator
- tests/common.mk
- tests/common/mac/project_building.mk
- tests/xtro-sharpie/Makefile
Make csc to be more strict when compiling the projects and mix some
small errors we had in the bindings.
Fixes: https://github.com/xamarin/xamarin-macios/issues/5398
> [Makefile] Make csc strict and fix some small errors.

- src/Foundation/NSFileManager.cs
- tests/monotouch-test/Foundation/FileManagerTest.cs
- tests/xtro-sharpie/common-Foundation.ignore
Add the bindings since Enviroment does not provide all/same information.
Fixes: https://github.com/xamarin/xamarin-macios/issues/3378
> [Foundation] Add some missing C bindings in NSFileManager.

- tests/xharness/Jenkins.cs
Addressing https://github.com/xamarin/xamarin-macios/issues/6075
> [xharness] Run duration 

- src/Foundation/NSUrlSessionHandler.cs
The callback is missing the url wich is useful information to have when
trusting a cert. We do the following:
1. Allow users to use the old callback, but state it as Obsolete.
2. Add a new delegate that will take the url.
3. A cert is accepted if one of the callbacks accepts it. The general
callback is a superset of the url one.
Fixes: https://github.com/xamarin/xamarin-macios/issues/7413
> [Foundation] Add an improved NSUrlSessionHandlerTrustOverrideCallback that passes the url.

- mk/xamarin.mk
https://github.com/xamarin/maccore/compare/f56575dcc2ec2d8975ea328feeeea697b7b2194b...89f83d012347661c0eb92b0196ee001b35d6f70f
> [d16-5][devops] Bump maccore to update provisioning script

- Make.config
same as https://github.com/xamarin/xamarin-macios/pull/7721
done manually since it looks like monojenkins is not online right now...
> Bump to the latest xcode11.3 API diff

- jenkins/Jenkinsfile
Fixes compilation error: https://github.com/xamarin/xamarin-macios/commit/f8951f092e331c585f39f956b31a80d8a967de41
> [Jenkins] Fix JenkinsFile groovy.

- tests/sampletester/ProcessHelper.cs
- tests/sampletester/SampleTester.cs
- tests/sampletester/Samples.cs
New samples added:
* https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/Xaminals
* https://github.com/davidortinau/Xappy
* https://github.com/Microsoft/SmartHotel360-Mobile
* https://github.com/microsoft/ConferenceVision
> [SampleTester] Add 4 new samples

- src/AVFoundation/Enums.cs
See https://developer.apple.com/documentation/avfoundation/avcapturevideostabilizationmode/avcapturevideostabilizationmodecinematicextended?language=objc
> Add AVCaptureVideoStabilizationMode.CinematicExtended

- tests/sampletester/BaselineTest/AppDelegate.cs
- tests/sampletester/BaselineTest/BaselineTest.csproj
- tests/sampletester/BaselineTest/BaselineTest.sln
- tests/sampletester/BaselineTest/Info.plist
- tests/sampletester/BaselineTest/LaunchScreen.storyboard
- tests/sampletester/Configuration.cs
- tests/sampletester/ProcessHelper.cs
- tests/sampletester/SampleTester.cs
- tests/sampletester/Samples.cs
- tests/sampletester/sampletester.sln
- tools/devops/build-samples.sh
- tools/devops/build-samples.yml
- tools/devops/fetch-maccore.sh
- tools/devops/prepare-performance-data.sh
- tools/devops/push-performance-data.sh
- tools/devops/system-info.sh
- tools/mmp/driver.cs
Mostly* test code.
* but there's a small addition to `mmp` to use the environment
variable `MMP_ENV_OPTIONS` (like `mtouch` does) that is also
part of the backport (and required to work properly)
> [d16-5][tests][sampletester] Backport fixes from master

- tools/devops/device-tests.yml
Add two new steps that will ensure that the xml is uploaded to vsts.
> [VSTS] Update ddfun pipeline to upload xml results.

- msbuild/ILMerge.targets
> [msbuild] Make code a bit more future-proof.

- tools/common/Application.cs
- tools/mtouch/Application.cs
- tools/mtouch/errors.Designer.cs
- tools/mtouch/errors.resx
- tools/mtouch/xlf/Errors.cs.xlf
- tools/mtouch/xlf/Errors.de.xlf
- tools/mtouch/xlf/Errors.es.xlf
- tools/mtouch/xlf/Errors.fr.xlf
- tools/mtouch/xlf/Errors.it.xlf
- tools/mtouch/xlf/Errors.ja.xlf
- tools/mtouch/xlf/Errors.ko.xlf
- tools/mtouch/xlf/Errors.pl.xlf
- tools/mtouch/xlf/Errors.pt-BR.xlf
- tools/mtouch/xlf/Errors.ru.xlf
- tools/mtouch/xlf/Errors.tr.xlf
- tools/mtouch/xlf/Errors.zh-Hans.xlf
- tools/mtouch/xlf/Errors.zh-Hant.xlf
Fixes https://github.com/xamarin/xamarin-macios/issues/7793.
> [mtouch] Fix tests broken by localization

- src/CoreFoundation/OSLog.cs
- src/Vision/VNUtils.cs
- tests/cecil-tests/Helper.cs
- tests/cecil-tests/Makefile
- tests/cecil-tests/README.md
- tests/cecil-tests/Test.cs
- tests/cecil-tests/cecil-tests.csproj
- tests/cecil-tests/packages.config
- tests/tests.sln
- tests/xharness/Jenkins.cs
Only one to start... it's been discussed before but we generally
found other ways to do them. Let's continue to pick the best place
but we now have more options :)
> [tests] Add cecil-based unit tests

- jenkins/Jenkinsfile
- jenkins/productsign.sh
It was added as a backup and has not been needed. With the updates to
catalina it makes builds fail on CI.
> [Jenkins] Do not notarize on PRs.

- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.ObjCBinding.CSharp.props
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.ObjCBinding.Common.targets
- tests/common/Configuration.cs
- tests/mtouch/runSingleTest.sh
> Remove code that refers to /Developer/MonoTouch.

- jenkins/vsts-device-tests-set-status.sh
Since we now have test being imported in DDFun, lets use the test
results view so that the monitoring person just need to click once.
> [d16-6][DDFun|VSTS] Add a URL to a more interesting view. (#7845)

- tests/xharness/XmlResultParser.cs
Now that we have NUnit V3 xml results, do generate the test report for
those correctly.
> [XHarness] Generate TestReports for NUnit V3.

- tests/bcl-test/BCLTests-mac.csproj.in
- tests/bcl-test/BCLTests-tv.csproj.in
- tests/bcl-test/BCLTests-watchos-extension.csproj.in
- tests/bcl-test/BCLTests.csproj.in
- tests/bcl-test/templates/common/TestRunner.xUnit/NUnit3Xml.xslt
- tests/bcl-test/templates/common/TestRunner.xUnit/XUnitTestRunner.cs
Add the required changes in the xunit runner to write NUnit V3 xml
result files so that we can have attachments in VSTS.
> [Harness] Add support for NUnit V3 in the new bcl tests.

- src/appkit.cs
- tests/xtro-sharpie/macOS-AppKit.todo
diff: https://github.com/xamarin/xamarin-macios/wiki/AppKit-macOS-xcode11.4-beta1
> [AppKit] Update bindings to Xcode 11.4 Beta 1

- src/classkit.cs
- tests/xtro-sharpie/iOS-ClassKit.todo
diff: https://github.com/xamarin/xamarin-macios/wiki/ClassKit-iOS-xcode11.4-beta1
> [ClassKit] Update bindings to Xcode 11.4 Beta 1

- src/avfoundation.cs
- tests/xtro-sharpie/iOS-AVFoundation.todo
- tests/xtro-sharpie/tvOS-AVFoundation.todo
diff: https://github.com/xamarin/xamarin-macios/wiki/AVFoundation-iOS-xcode11.4-beta1
> [AVFoundation] Update bindings to Xcode 11.4 Beta 1

- src/contacts.cs
diff: https://github.com/xamarin/xamarin-macios/wiki/Contacts-iOS-xcode11.4-beta1
> [Contacts] Update bindings to Xcode 11.4 Beta 1

- src/CoreText/CTEnums.cs
diff: https://github.com/xamarin/xamarin-macios/wiki/CoreText-iOS-xcode11.4-beta1
> [CoreText] Update bindings to Xcode 11.4 Beta 1

- src/CoreGraphics/CGColorSpace.cs
- src/coregraphics.cs
- tests/xtro-sharpie/iOS-CoreGraphics.todo
- tests/xtro-sharpie/macOS-CoreGraphics.todo
- tests/xtro-sharpie/tvOS-CoreGraphics.todo
- tests/xtro-sharpie/watchOS-CoreGraphics.todo
diff: https://github.com/xamarin/xamarin-macios/wiki/CoreGraphics-iOS-xcode11.4-beta1
> [CoreGraphics] Update bindings to Xcode 11.4 Beta 1

- src/gamekit.cs
- tests/xtro-sharpie/iOS-GameKit.todo
- tests/xtro-sharpie/macOS-GameKit.todo
- tests/xtro-sharpie/tvOS-GameKit.todo
- tests/xtro-sharpie/watchOS-GameKit.todo
diff: https://github.com/xamarin/xamarin-macios/wiki/GameKit-iOS-xcode11.4-beta1
> [GameKit] Update bindings to Xcode 11.4 Beta 1

- tests/xharness/XmlResultParser.cs
There are two cases that are not currently considered in VSTS that we
need to report:
1. The application could not be built.
2. The application crashed.
In those cases we do not have xml to be imported by VSTS. What we are
going to do is create 'fake' test runs that will encapsulate a build
error or a crash to be imported by VSTS with the needed attachments.
This code just writes custom errors. The generated results are like the
following:
* [NUnit V2](https://gist.github.com/mandel-macaque/7207f6acb5a90895adf84f40a05e0b21)
* [NUnit V3](https://gist.github.com/mandel-macaque/99898c0570cde2e54e38d8af5991f824)
* [xUnit](https://gist.github.com/mandel-macaque/4591cc06d3db0e46de6a0bf886804f13)
> [Harness] Add code that will generate custom xml results with failures.

- src/corelocation.cs
- tests/xtro-sharpie/iOS-CoreLocation.todo
- tests/xtro-sharpie/macOS-CoreLocation.todo
- tests/xtro-sharpie/tvOS-CoreLocation.todo
- tests/xtro-sharpie/watchOS-CoreLocation.todo
diff: https://github.com/xamarin/xamarin-macios/wiki/CoreLocation-iOS-xcode11.4-beta1
> [CoreLocation] Update to Xcode 11.4 Beta 1

- src/callkit.cs
- tests/xtro-sharpie/iOS-CallKit.todo
diff: https://github.com/xamarin/xamarin-macios/wiki/CallKit-iOS-xcode11.4-beta1
> [CallKit] Update bindings to Xcode 11.4 Beta 1

- src/LocalAuthentication/LAEnums.cs
diff: https://github.com/xamarin/xamarin-macios/wiki/LocalAuthentication-iOS-xcode11.4-beta1
> [LocalAuthentication] Update bindings to Xcode 11.4 Beta 1

- tests/xharness/XmlResultParser.cs
Now that we have NUnit V3 xml results, do generate the test report for
those correctly.
Backport of #7851.
> [xcode11.4] [XHarness] Generate TestReports for NUnit V3.

- tests/xharness/XmlResultParser.cs
Now that we have NUnit V3 xml results, do generate the test report for
those correctly.
Backport of #7851.
> [d16-6] [XHarness] Generate TestReports for NUnit V3.

- jenkins/vsts-device-tests-set-status.sh
- tools/devops/device-tests-common.yml
- tools/devops/device-tests.yml
- tools/devops/run-tests.sh
Move to use a template for the DDFun pipeline. Copy the current pipeline
to a template, set some parameters and recreate the pipeline importing
the template.
> [VSTS] Remove the some hardcoded vars.

- src/SafariServices/SSEnums.cs
- src/safariservices.cs
diff: https://github.com/xamarin/xamarin-macios/wiki/SafariServices-iOS-xcode11.4-beta1
> [SafariServices] Update bindings to Xcode 11.4 Beta 1

- src/passkit.cs
- tests/xtro-sharpie/iOS-PassKit.todo
- tests/xtro-sharpie/watchOS-PassKit.todo
diff: https://github.com/xamarin/xamarin-macios/wiki/PassKit-iOS-xcode11.4-beta1
> [PassKit] Update bindings to Xcode 11.4 Beta 1

- tests/xharness/AppRunner.cs
- tests/xharness/XmlResultParser.cs
Make sure that when we are running on VSTS we do get test failures when
the application cannot be launched or crashes.
> [Harness] If app does not launch or crash, create a test failure.

- tests/xharness/Jenkins.cs
- tests/xharness/XmlResultParser.cs
If there is a build error generate a xml that will be imported by VSTS
and will be reported as a test failure.
Example of the error: https://gist.github.com/mandel-macaque/dab2a5a4f3d21a81c172a8c8450d2448
> [XHarness] If there is a build error, report it as a test failure.

- tools/devops/run-tests.sh
I'm stupid, of course -C thinks that -d is a path 🤦‍♂
> [VSTS] Correct order of params for make.

- tools/common/Driver.cs
- tools/mmp/driver.cs
- tools/mtouch/mtouch.cs
Share the logging/verbosity code between mtouch and mmp.
> [mtouch/mmp] Share verbosity code.

- tools/common/Driver.cs
- tools/mmp/aot.cs
- tools/mmp/driver.cs
- tools/mtouch/Target.cs
- tools/mtouch/mtouch.cs
> [mtouch/mmp] Share code to locate the framework directory.

- tests/mtouch/RegistrarTest.cs
- tools/common/Frameworks.cs
New frameworks were added and the test needs to be updated.
fixes: https://github.com/xamarin/maccore/issues/954
> [Tests] Update MT4134 tests for the new Xcode 11.4

- src/watchkit.cs
- tests/xtro-sharpie/watchOS-WatchKit.todo
diff https://github.com/xamarin/xamarin-macios/wiki/WatchKit-watchOS-xcode11.4-beta2
> [WatchKit] Update bindings to Xcode 11.4 Beta 2

- tools/mmp/Makefile
- tools/mmp/mmp
- tools/mmp/mmp.in
> [mmp] Use relative path in mmp script.

- src/videosubscriberaccount.cs
diff: https://github.com/xamarin/xamarin-macios/wiki/VideoSubscriberAccount-iOS-xcode11.4-beta2
> [VideoSubscriberAccount] Update bindings to Xcode 11.4 Beta 2

- tests/xharness/AppRunner.cs
fixes: https://github.com/xamarin/xamarin-macios/issues/7978
> [Harness] Fix false crash report.

- src/generator.cs
This regressed in 6f19d734b7003dd2317b7c68e357ee6425be737b.
> [bgen] Put output in subdirectories based on namespaces again.

- mk/xamarin.mk
Revert mlaunch localization changes until https://github.com/xamarin/xamarin-macios/issues/8030 is resolved.
Diff:
https://github.com/xamarin/maccore/compare/c95bf939240c0d95c971b0c0e330bed8e527b64f..cec1cba1372a766dd8054b39edb982ea81d68170
> [Bump][Maccore] Revert mlaunch localization changes

- src/VideoToolbox/VTDefs.cs
Diff: https://github.com/xamarin/xamarin-macios/wiki/VideoToolbox-iOS-xcode11.4-beta3
> [VideoToolbox] Update bindings to Xcode 11.4 Beta 3

- src/btouch.cs
It took me a while to figure out why my newly added references didn't quite
work as expected... so let's make sure future me doesn't run into the same
problem again.
> [bgen] Make --reference work as well as -r.

- src/btouch.cs
- tools/common/TargetFramework.cs
- tools/mtouch/mtouch.cs
Nobody should be using it anymore.
> [tools] Remove the MonoTouch,v1.0 target framework.

- tests/xharness/Jenkins/Jenkins.cs
- tests/xharness/Jenkins/TestTasks/MSBuildTask.cs
- tests/xharness/Jenkins/TestTasks/RunDeviceTask.cs
- tests/xharness/Jenkins/TestTasks/RunSimulatorTask.cs
- tests/xharness/Jenkins/TestTasks/RunTestTask.cs
- tests/xharness/xharness.csproj
We're not using xbuild anymore, and haven't for quite a while.
> [xharness] Rename XBuildTask to MSBuildTask.

- src/fileprovider.cs
- tests/xtro-sharpie/macOS-FileProvider.ignore
- tests/xtro-sharpie/macOS-FileProvider.todo
We got the deprecated attributes! Long live our test suites!
> [FileProvider] Update bindings to Xcode 11.4 Beta 3

- tests/xharness/Jenkins/Jenkins.cs
* It's built in parallel with populating the tests.
* A failure isn't silently ignored, it's now shown in the html report.
> [xharness] Rework how we build test-libraries a bit.

- tests/xharness/Hardware/TCCDatabase.cs
- tests/xharness/Xharness.Tests/Hardware/Tests/TCCDatabaseTests.cs
The wrong var name was used and the table was not correctly updated.
Updated tests to take into account the new \n in the sql.
> [Harness] Fix bug in TCCDb editing that is missing using the watchapp id.

- src/Foundation/NSExpression.cs
Not very important but I had those stashed for a loooong time
> [foundation] Fix typos in NSExpression

- tools/mmp/driver.cs
This regressed in 13a56ffb956f21f3284c6fa5728d23e5949b96cd.
> [mmp] Fix install_name_tool invocation.

- tests/xharness/AppRunner.cs
- tests/xharness/Harness.cs
- tests/xharness/Jenkins/Jenkins.cs
- tests/xharness/Jenkins/TestTasks/BuildProjectTask.cs
- tests/xharness/Jenkins/TestTasks/MSBuildTask.cs
- tests/xharness/Jenkins/TestTasks/NUnitExecuteTask.cs
- tests/xharness/Jenkins/TestTasks/TestTask.cs
- tests/xharness/Logging/Logs.cs
- tests/xharness/TestProject.cs
- tests/xharness/Utilities/DirectoryUtilities.cs
- tests/xharness/Utilities/Helpers.cs
- tests/xharness/XmlResultParser.cs
- tests/xharness/xharness.csproj
- Removing dependencies on Harness
- Making TTY utilities injectable and thus code using it testable
No functional changes
> [Harness] Move Timestamp and TTY utilities to Helpers

- tests/mmptest/src/MMPTest.cs
- tests/mmptest/src/NativeReferencesTests.cs
- tools/common/Driver.cs
- tools/devops/build-samples.yml
- tools/mmp/Application.cs
- tools/mmp/driver.cs
- tools/mmp/mmp.csproj
- tools/mtouch/Application.cs
- tools/mtouch/Target.cs
- tools/mtouch/mtouch.cs
> [d16-5-xcode11.4] Sample tester needs Catalina pool

- tools/common/Driver.cs
- tools/mtouch/errors.Designer.cs
- tools/mtouch/errors.resx
- tools/mtouch/xlf/Errors.cs.xlf
- tools/mtouch/xlf/Errors.de.xlf
- tools/mtouch/xlf/Errors.es.xlf
- tools/mtouch/xlf/Errors.fr.xlf
- tools/mtouch/xlf/Errors.it.xlf
- tools/mtouch/xlf/Errors.ja.xlf
- tools/mtouch/xlf/Errors.ko.xlf
- tools/mtouch/xlf/Errors.pl.xlf
- tools/mtouch/xlf/Errors.pt-BR.xlf
- tools/mtouch/xlf/Errors.ru.xlf
- tools/mtouch/xlf/Errors.tr.xlf
- tools/mtouch/xlf/Errors.zh-Hans.xlf
- tools/mtouch/xlf/Errors.zh-Hant.xlf
> [mtouch/mmp] Add better diagnostics if xcrun returns invalid data.

- src/fileprovider.cs
- tests/xtro-sharpie/macOS-FileProvider.ignore
- tests/xtro-sharpie/macOS-FileProvider.todo
* [FileProvider] Update bindings to Xcode 11.4 Beta 3
* Update src/fileprovider.cs
> [FileProvider] Update bindings to Xcode 11.4 Beta 3 (#8075)

- tests/xharness/AppRunner.cs
Fixes #8185 and some other minor things problems in AppRunner
> [Harness] Fix BUILD_REVISION env argument

- src/appkit.cs
- tests/xtro-sharpie/macOS-AppKit.ignore
- https://github.com/xamarin/xamarin-macios/issues/7712
> [mac] Add NSScrollView.WillStartLiveScrollNotification

- tests/xharness/Xharness.Tests/BCLTestImporter/Tests/BCLTestInfoPlistGeneratorTest.cs
- tests/xharness/Xharness.Tests/BCLTestImporter/Xamarin/Tests/ProjectFilterTest.cs
- tests/xharness/Xharness.Tests/Execution/Tests/ProcessManagerTests.cs
- tests/xharness/Xharness.Tests/Hardware/Tests/DevicesTest.cs
- tests/xharness/Xharness.Tests/Hardware/Tests/SimulatorsTest.cs
- Fixes tests that were not updated with code changes. Tests are not being run as part of the CI yet so we didn't notice.
- Fixes tests that leave files open and fail to clean up and fixes some path problems and changes in mlaunch argument definition
> [Harness] Fix XHarness unit tests

- src/appkit.cs
- tests/xtro-sharpie/macOS-AppKit.ignore
- https://github.com/xamarin/xamarin-macios/issues/7712
Backport of #8205.
/cc @chamons
> [d16-6] [mac] Add NSScrollView.WillStartLiveScrollNotification

- tests/xharness/Xharness.Tests/Samples/Issue8214.xml
- tests/xharness/Xharness.Tests/Tests/XmlResultParserTests.cs
- tests/xharness/Xharness.Tests/Xharness.Tests.csproj
- tests/xharness/XmlResultParser.cs
Added a test in the xml parser that verifies that the parsing of the xml
is correct and that the correct number of failures is reported in the
human readable form.
fixes: https://github.com/xamarin/xamarin-macios/issues/8214
> [Harness] Verify that issue #8214 is fixed.

- runtime/monotouch-main.m
Should fix https://github.com/mono/mono/issues/19372
> Wrap mono_gc_init_finalizer_thread() call with now-needed coop GC state transition

- tests/linker/ios/link all/LinkAllTest.cs
iOS fixed after Xcode 11 release
Fix https://github.com/xamarin/xamarin-macios/issues/6254
> [tests][link all] Remove test workaround

- tools/devops/azure-pipelines.yml
We need to use the Catalina pool now that Xcode 11.4 is stable
> [d16-6] Update azure-pipelines.yml

- tools/devops/azure-pipelines.yml
We need to use the Catalina pool now that Xcode 11.4 is stable
> [d16-5] Update azure-pipelines.yml

- tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Execution/ProcessManager.cs
- `XcodeRoot` will be detected using `xcode-select` and `mlaunch` will have a hardcoded default
> [Harness] Allow to create a process manager with default tool paths

- tools/linker/MobileRemoveAttributes.cs
Backport of #8301.
/cc @spouliot
> [d16-7] [linker] Remove nullability attributes than are not used at runtime

- tools/linker/CoreMarkStep.cs
- tools/linker/MobileMarkStep.cs
and removed previous workaround
Replace previous attempt https://github.com/xamarin/xamarin-macios/pull/8336
> [linker] Fix infinite queue found with nullability PR

- tools/linker/CoreMarkStep.cs
and removed previous workaround
Replace previous attempt https://github.com/xamarin/xamarin-macios/pull/8336
Backport of #8337.
/cc @spouliot
> [d16-7] [linker] Fix infinite queue found with nullability PR

- README.md
- https://github.com/xamarin/xamarin-macios/issues/7462
> [README] Add macOS download package table

- src/generator.cs
- tests/xharness/GitHub.cs
- tests/xharness/Jenkins/Jenkins.cs
fixes: https://github.com/xamarin/xamarin-macios/issues/8363
> [Harness] Ensure that the generator tests are set when we modify the sources.

- src/generator.cs
- tests/xharness/GitHub.cs
- tests/xharness/Jenkins/Jenkins.cs
fixes: https://github.com/xamarin/xamarin-macios/issues/8363
Backport of #8371.
/cc @spouliot @mandel-macaque
> [d16-7] [Harness] Ensure that the generator tests are set when we modify the sources.

- src/Foundation/NSString.cs
- tests/monotouch-test/Foundation/NSStringTest.cs
This matches our API elsewhere.
> [Foundation] Add an overload to NSString.FromHandle that takes an 'owns' parameter.

- src/generator.cs
as it can allocate memory (create string) in some cases
also a few other left over pieces from nullability work
> [generator] Avoid repetitive calls to GetSafeParamName

- jenkins/Jenkinsfile
It's annoying to have to track it down all the time when something goes wrong.
> [jenkins] State all the time where we're working on.

- src/corelocation.cs
- tests/xtro-sharpie/common-CoreLocation.ignore
Following the guidelines from @spouliot [comment](https://github.com/xamarin/xamarin-macios/issues/6154#issuecomment-620014843) I've added the missing nullability attributes to CoreLocation
> Added missing nullability attributes to CoreLocation

- src/corelocation.cs
- tests/xtro-sharpie/iOS-CoreLocation.ignore
- tests/xtro-sharpie/macOS-CoreLocation.ignore
- tests/xtro-sharpie/watchOS-CoreLocation.ignore
Adds platform specific nullability attributes to CoreLocation
> Adds platform specific nullability attributes to CoreLocation

- tests/xharness/Jenkins/ErrorKnowledgeBase.cs
- tests/xharness/Jenkins/Jenkins.cs
- tests/xharness/Jenkins/TestTasks/DotNetBuildTask.cs
- tests/xharness/Jenkins/TestTasks/MSBuildTask.cs
- tests/xharness/Jenkins/TestTasks/RunSimulatorTask.cs
- tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/IErrorKnowledgeBase.cs
- tests/xharness/Xharness.Tests/Jenkins/ErrorKnowledgeBaseTests.cs
- tests/xharness/Xharness.Tests/Xharness.Tests.csproj
- tests/xharness/xharness.csproj
Some small changes to make things a little easier to understand:
* Add a new method in case we find known install issues.
* enable nullable, lets go step by step.
* Move logic outside Jenkins.cs
* Add tests! \o/
> [Harness] Small refactor to get the knowledge base out of jenkins.

- tools/mmp/Makefile
> [mmp] No need to lipo a single executable file.

- tests/xharness/AppRunner.cs
- tests/xharness/Xharness.Tests/Tests/AppRunnerTests.cs
Tests are not ran as part of the CI and got borken again. Fix them, will
add them as part of the CI once they land fixed.
> [Harness] Fix broken tests.

- tests/xharness/GitHub.cs
- tests/xharness/Jenkins/Jenkins.cs
- tests/xharness/Jenkins/TestSelector.cs
Move to be a non static class so that we can later easily test the
TestSelector class.
> [Harness] Move GitHub to be a VCS interface to simplify testing.

- builds/Makefile
> [builds] Fix generation of the smcs script.

- tools/devops/Makefile
- tools/devops/device-tests-provisioning.csx.in
Create symlink to the expected location. For this to work we need https://github.com/xamarin/provisionator/pull/305
> [Devops] Do link xcode to the expected path.

- tools/mmp/Application.mmp.cs
- tools/mmp/driver.cs
- tools/mtouch/Application.mtouch.cs
* Driver.Registrar.
* DisableLldbAttach and DisableOmitFramePointer.
* AOTOptions
* CustomBundleName
> [mmp] Move several static Driver properties to be instance properties on the Application instance.

- tools/devops/device-tests-common.yml
- tools/devops/device-tests.yml
For when we need to debug some provisionator stuff on macios.
> Flag to disable Provisionator Cleanup

- tools/linker/MarkNSObjects.cs
also add a note that it's not optimal, as-is, if "Link All" is used since
it's too early to make a decision on overrides from user code, they could
be removed later (e.g. if the type is unused in the app).
> [linker] Simplify MarkNSObject a bit

- tests/xharness/Jenkins/ErrorKnowledgeBase.cs
- tests/xharness/Jenkins/Jenkins.cs
- tests/xharness/Jenkins/TestData.cs
- tests/xharness/Jenkins/TestVariationsFactory.cs
- tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/IErrorKnowledgeBase.cs
- tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Tasks/ITestTask.cs
- tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Tasks/MSBuild.cs
- tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Tasks/TestTask.cs
- tests/xharness/TestTasks/RunTest.cs
If we have a known issue, lets add the message and the link to the
markdown so that the monitoring person does not need to look at the
html page.
fixes: https://github.com/xamarin/xamarin-macios/issues/8625
> [Harness] When we have a known issue, add it to the markdown.

- tools/linker/MobileMarkStep.cs
- tools/linker/MobileSweepStep.cs
This is now supported by upstream mono/linker
> [linker] Remove code to deal with ExportedTypes

- tests/monotouch-test/System.Net.Http/MessageHandlers.cs
Backport of https://github.com/xamarin/xamarin-macios/pull/8580
> [d16-7][Tests] Use safe listed password by our Credentials Scanner tool (#8580)

- tests/xharness/AppRunner.cs
- tests/xharness/Harness.cs
- tests/xharness/Jenkins/Jenkins.cs
- tests/xharness/Jenkins/MacTestTasksEnumerable.cs
- tests/xharness/Jenkins/TestVariationsFactory.cs
- tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared.Tests/AppBundleInformationParserTests.cs
- tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/AppBundleInformationParser.cs
- tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Tasks/TestTask.cs
- tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/TestProject.cs
- tests/xharness/TestTasks/RunDevice.cs
- tests/xharness/TestTasks/RunSimulator.cs
- tests/xharness/Xharness.Tests/Tests/AppRunnerTests.cs
This will be required in a later PR (getting this in asap makes it easier to avoid merge conflicts since xharness code is changing frequently now).
> [xharness] Make AppBundleInformationParser.ParseFromProject async and make it take an ILog and a IProcessManager.

- tests/xharness/Jenkins/Jenkins.cs
- tests/xharness/Jenkins/ResourceManager.cs
- tests/xharness/Jenkins/TestTasks/AggregatedRunSimulatorTask.cs
- tests/xharness/Jenkins/TestTasks/AppleTestTask.cs
- tests/xharness/Jenkins/TestTasks/BuildProjectTask.cs
- tests/xharness/Jenkins/TestTasks/DotNetBuildTask.cs
- tests/xharness/Jenkins/TestTasks/MSBuildTask.cs
- tests/xharness/Jenkins/TestTasks/RunDeviceTask.cs
- tests/xharness/Jenkins/TestTasks/RunSimulatorTask.cs
- tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Tasks/IResourceManager.cs
- tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Tasks/Resources.cs
- tests/xharness/Xharness.Tests/Jenkins/ResourceManagerTests.cs
- tests/xharness/Xharness.Tests/Xharness.Tests.csproj
- tests/xharness/xharness.csproj
Move the resource management out of Jenkins. Add tests to the new class.
> [Harness] Move the resource manager implementation out of Jenkins.

- tools/devops/utils.csx
I did some last minute cleanup on `utils.csx` in #8630 that I thought was harmless, but wasn't :(
> satisfy the type-checking gods

- dotnet/targets/Xamarin.Shared.Sdk.props
- dotnet/targets/Xamarin.Shared.Sdk.targets
- msbuild/Makefile
- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.AppExtension.CSharp.targets
- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.CSharp.targets
- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.CSharp.targets
- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.Common.targets
- msbuild/Xamarin.Shared/Xamarin.Shared.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.TVOS.AppExtension.CSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.TVOS.CSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.App.CSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.AppExtension.CSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.CSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.AppExtension.CSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.CSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.props
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.ObjCBinding.CSharp.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.ObjCBinding.Common.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.WatchApp.CSharp.targets
Also fix them to not cause problems when used from the net5 targets files.
The current NuGet structure:
Microsoft.iOS.Sdk
└─── Sdk
│    └─── Sdk.props
│    └─── Sdk.targets
└─── Versions.plist
└─── targets
│    └─── Microsoft.iOS.*.props
│    └─── Microsoft.iOS.*.targets
│    └─── Xamarin.Shared.*.props
│    └─── Xamarin.Shared.*.targets
└─── tools
│    └─── msbuild
│    │    └─── iOS
│    │    │    └─── FrameworkList.xml
│    │    │    └─── Xamarin.*.dll
│    │    │    └─── Xamarin.*.pdb
│    │    │    └─── Xamarin.*.props
│    │    │    └─── Xamarin.*.targets
Microsoft.tvOS.Sdk
└─── Sdk
│    └─── Sdk.props
│    └─── Sdk.targets
└─── Versions.plist
└─── targets
│    └─── Microsoft.tvOS.*.props
│    └─── Microsoft.tvOS.*.targets
│    └─── Xamarin.Shared.*.props
│    └─── …
> [dotnet/msbuild] Add existing targets files to the net5 NuGets, and import them in the net5 targets files.

- tests/xharness/Jenkins/Jenkins.cs
- tests/xharness/Jenkins/Reports/HtmlReportWriter.cs
- tests/xharness/Jenkins/TestSelector.cs
- tests/xharness/Jenkins/TestServer.cs
- tests/xharness/Jenkins/TestTasks/AppleTestTask.cs
- tests/xharness/Jenkins/TestTasks/BuildToolTask.cs
- tests/xharness/xharness.csproj
Move all the logic of the server to its own class to later be able to
add tests in Jenkins (make sure that we do run it) and in the server
itself (check that files are served, correct actions are executed etc..)
At this point Jenkins just creates the tests tasks via other objects and
executes in server mode or not depending on the env.
> [Harness] Create a TestServer that will serve the Xharness page.

- tests/dotnet/MyClassLibrary/MyClass.cs
- tests/dotnet/MyClassLibrary/MyClassLibrary.csproj
- tests/dotnet/MyClassLibrary/iOS/MyClass.cs
- tests/dotnet/MyClassLibrary/iOS/MyClassLibrary.csproj
- tests/dotnet/MyClassLibrary/macOS/MyClass.cs
- tests/dotnet/MyClassLibrary/macOS/MyClassLibrary.csproj
- tests/dotnet/MyClassLibrary/tvOS/MyClass.cs
- tests/dotnet/MyClassLibrary/tvOS/MyClassLibrary.csproj
- tests/dotnet/MyClassLibrary/watchOS/MyClass.cs
- tests/dotnet/MyClassLibrary/watchOS/MyClassLibrary.csproj
- tests/dotnet/UnitTests/ProjectTest.cs
And tests to make sure it builds successfully as well.
> [dotnet] Add class library test project for every platform.

- src/AddressBookUI/ABPeoplePickerNavigationController.cs
This was just too annoying to ignore.
> [AddressBookUI] Fix indentation.

- src/ARKit/ARFaceGeometry.cs
- src/ARKit/ARPlaneGeometry.cs
- src/ARKit/ARPointCloud.cs
- src/ARKit/ARSkeleton2D.cs
- src/ARKit/ARSkeleton3D.cs
- src/Accelerate/vImageTypes.cs
- src/Accounts/AccountStoreOptions.cs
- src/AddressBook/ABPerson.cs
- src/AddressBook/ABSource.cs
- src/AddressBookUI/ABNewPersonViewController.cs
- src/AddressBookUI/ABPeoplePickerNavigationController.cs
- src/AddressBookUI/ABPersonViewController.cs
- src/AddressBookUI/ABUnknownPersonViewController.cs
- src/accounts.cs
- src/addressbookui.cs
- src/arkit.cs
> [d16-7] [src] Remove Classic code from the Accelerate, Accounts, AddressBook[UI] and ARKit frameworks.

- Make.config
- tests/xtro-sharpie/Makefile
- tests/xtro-sharpie/SimdCheck.cs
- tests/xtro-sharpie/xtro-sharpie.csproj
Backport of #8759.
/cc @dalexsoto
> [d16-7] [sharpie] Bump version of sharpie and accommodate xtro to new output

- CODEOWNERS
Done against my will and due to peer pressure.
> [CODEOWNERS] Update ownership.

- Make.config
Backport of #8766.
/cc @dalexsoto
> [d16-7] [sharpie] Use a better CDN download link

- tools/devops/utils.csx
I did some last minute cleanup on `utils.csx` in #8630 that I thought was harmless, but wasn't :(
Backport of #8680.
/cc @rolfbjarne @cadsit
> [d16-7] satisfy the type-checking gods

- src/AVFoundation/AVAssetImageGenerator.cs
- src/AVFoundation/AVAssetReaderVideoCompositionOutput.cs
- src/AVFoundation/AVAudioPlayer.cs
- src/AVFoundation/AVAudioRecorder.cs
- src/AVFoundation/AVAudioSession.cs
- src/AVFoundation/AVAudioSessionDataSourceDescription.cs
- src/AVFoundation/AVAudioSettings.cs
- src/AVFoundation/AVCaptureConnection.cs
- src/AVFoundation/AVCaptureDeviceInput.cs
- src/AVFoundation/AVCaptureMetadataOutput.cs
- src/AVFoundation/AVCompat.cs
- src/AVFoundation/AVLayerVideoGravity.cs
- src/AVFoundation/AVMetadataItemFilter.cs
- src/AVFoundation/AVMetadataMachineReadableCodeObject.cs
- src/AVFoundation/AVMetadataObject.cs
- src/AVFoundation/AVPlayer.cs
- src/AVFoundation/AVTypes.cs
- src/AVFoundation/AVVideoSettings.cs
- src/AVFoundation/Enums.cs
- src/avfoundation.cs
> [d16-7] [src] Remove Classic code from AVFoundation.

- mk/xamarin.mk
- tools/devops/azure-pipelines.yml
* xamarin/maccore@714066a4b6 Add PoliCheckExclusions.xml (#2228) (#2229)
Diff: https://github.com/xamarin/maccore/compare/ef861db73e7c0f74131d08d5afa64841d6b00e0b..714066a4b6b5062b3cfc12db0e79bfde0c3961ac
> [d16-7][devops] Add Policheck tool to our pipeline

- tools/mmp/driver.cs
* Remove old imports that are not needed anymore (left over from DRM days)
* Fix formatting (missing tab)
> [mmp] Update generated code for `main.c`

- NOTICE.txt
- tools/governance/README.md
- tools/governance/cgmanifest.json
- tools/governance/governance.cs
- tools/governance/governance.csproj
- Add generated NOTICE.txt with hand included [OpentTK license](https://github.com/mono/opentk/blob/master/Documentation/License.txt) not found by CG
- Add small dotnet core tool that updates cgmanifest.json based on new submodules/mono
- [Internal User Story](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1140262)
> Add NOTICE.txt and cgmanifest tool

- runtime/launcher.m
> [runtime] Update launcher to use `strndup`

- tests/xharness/BCLTestImportTargetFactory.cs
- tests/xharness/GitHub.cs
- tests/xharness/Harness.cs
- tests/xharness/IHarness.cs
- tests/xharness/Jenkins/Jenkins.cs
- tests/xharness/Jenkins/MakeTestTaskEnumerable.cs
- tests/xharness/Jenkins/NUnitTestTasksEnumerable.cs
- tests/xharness/Jenkins/Reports/HtmlReportWriter.cs
- tests/xharness/Jenkins/TestSelector.cs
- tests/xharness/Jenkins/TestServer.cs
- tests/xharness/Jenkins/TestTasks/AppleTestTask.cs
- tests/xharness/MakefileGenerator.cs
- tests/xharness/Program.cs
- tests/xharness/SolutionGenerator.cs
- tests/xharness/Targets/TVOSTarget.cs
- tests/xharness/Targets/Target.cs
- tests/xharness/xharness.csproj
In order to be able to test the TestSelectro in PR
https://github.com/xamarin/xamarin-macios/pull/8768 we need a more
general interface to mock and ensure that the correct properties are set
by the TestSelector.
> [Harness] Add a more general IHarness interface.

- tests/monotouch-test/Metal/MTLDeviceTests.cs
Apple's charts say indirect command buffers are available with MTLGpuFamilyCommon2.
That's not quite so, devices that support MTLGpuFamilyCommon2 may crash when
MTLDevice.CreateIndirectCommandBuffer is called.
So make the conditions for calling CreateIndirectCommandBuffer an intersection
of the previous condition for macOS (MTLFeatureSet.macOS_GPUFamily2_v1) + the
new condition (MTLGpuFamily.Common2) + Xcode 11+ (just to make things
simpler).
I've tested this on all our macOS bots, and it worked on all of them.
If it fails anywhere else (iOS devices), the next patch will remove the entire
test.
> [monotouch-test] Lower indirect command buffer availability.

- msbuild/Xamarin.Mac.Tasks.Core/Tasks/ALToolUploadTaskBase.cs
- msbuild/Xamarin.Mac.Tasks.Core/Tasks/ALToolValidateTaskBase.cs
- msbuild/Xamarin.Mac.Tasks.Core/Tasks/EmbedProvisionProfileTaskBase.cs
- msbuild/Xamarin.Mac.Tasks.Core/Tasks/MmpTaskBase.cs
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CollectFrameworksBase.cs
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CreateInstallerPackageTaskBase.cs
- msbuild/Xamarin.iOS.Tasks.Core/Tasks/ALToolUploadTaskBase.cs
- msbuild/Xamarin.iOS.Tasks.Core/Tasks/ALToolValidateTaskBase.cs
- msbuild/Xamarin.iOS.Tasks.Core/Tasks/ArchiveTaskBase.cs
- msbuild/Xamarin.iOS.Tasks.Core/Tasks/CollectAssetPacksTaskBase.cs
- msbuild/Xamarin.iOS.Tasks.Core/Tasks/CollectITunesSourceFilesTaskBase.cs
- msbuild/Xamarin.iOS.Tasks.Core/Tasks/CreateAssetPackTaskBase.cs
- msbuild/Xamarin.iOS.Tasks.Core/Tasks/WriteAssetPackManifestTaskBase.cs
- tests/cecil-tests/Helper.cs
- tests/cecil-tests/TaskAssemblyTests.cs
Also add a cecil test ensure our leaf MSBuild tasks don't have code.
> [msbuild] Make sure all the Base/Core tasks are abstract.

- dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets
- dotnet/targets/Xamarin.Shared.Sdk.targets
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileNativeCodeTaskBase.cs
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/LinkNativeCodeTaskBase.cs
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/XamarinTask.cs
- msbuild/Xamarin.MacDev.Tasks.Core/Xamarin.MacDev.Tasks.Core.csproj
- msbuild/Xamarin.MacDev.Tasks/Tasks/CompileNativeCode.cs
- msbuild/Xamarin.MacDev.Tasks/Tasks/LinkNativeCode.cs
- tools/dotnet-linker/Compat.cs
- tools/dotnet-linker/LinkerConfiguration.cs
- tools/dotnet-linker/SetupStep.cs
- tools/dotnet-linker/Steps/GenerateMainStep.cs
- tools/dotnet-linker/dotnet-linker.csproj
This PR is best reviewed commit-by-commit; each change is explained by its commit message.
> [dotnet] Generate a main function, and use it to compile the main executable.

- tools/devops/device-tests/scripts/GitHub.Tests.ps1
- tools/devops/device-tests/scripts/GitHub.psm1
- tools/devops/device-tests/scripts/MLaunch.Tests.ps1
- tools/devops/device-tests/templates/device-tests.yml
Comments were ugly. Clean a little the markdown.
> [DevOps] Improve the comments added in GitHub.

- src/AddressBookUI/ABPeoplePickerNavigationController.cs
This was just too annoying to ignore.
Backport of #8719.
> [xcode12] [AddressBookUI] Fix indentation.

- tests/linker/ios/link all/LinkAllTest.cs
- tests/mmptest/regression/link-remove-attributes-1/LinkRemoveAttributes.cs
- tools/linker/CoreRemoveAttributes.cs
- tools/linker/MobileMarkStep.cs
- tools/linker/MobileRemoveAttributes.cs
- tools/linker/MobileSweepStep.cs
Backport we few linker changes to make it easier to merge the
xcode12 branch into main in the fall.
Backports: #8535, #8568, #8632, #8337.
> [xcode12] Backport a few linker changes.

- src/generator.cs
Backport we few linker changes to make it easier to merge the
xcode12 branch into main in the fall.
Backports: #8712, #8668, #8443.
> [xcode12] [generator] Backport a few generator changes.

- tools/devops/device-tests/templates/device-tests.yml
Nicer than failing on ssh and faster to check if the ssh port is open.
> [DevOps] Using netcat over ssh to check if port is open.

- tests/xammac_tests/xammac_tests.csproj
New test that did not consider that tests are shared with mac os x.
fixes: https://github.com/xamarin/maccore/issues/2248
> [Tests] Add missing resource needed by tests. Fixes #2248

- src/accounts.cs
Added a deprecation that is not picked up by xtro. No other changes.
> [Accounts] Update binding for xcode 12 beta 1.

- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
> Include assembly refs in _CompileToNative Inputs

- tests/monotouch-test/Foundation/UrlRequestTest.cs
This has been tested on:
* macOS 10.9, 10.10, 10.11, 10.12, 10.13, 10.14 and 10.15.
* iOS device:
* iOS 8.2
* iOS 9.3.5
* iOS 11.4.1
* iOS 13.6
> [monotouch-test] Second attempt at fixing the broken UrlRequestTest.Mutability_30744 test.

- tools/compare-commits.sh
Ref:  https://github.com/xamarin/maccore/issues/1467
> [compare-commits] Add some diagnostics to try to figure out what's happening with #xamarin/maccore@1467.

- tools/devops/device-tests/templates/cambridge-variables.yml
- tools/devops/device-tests/templates/ddfun-variables.yml
- tools/devops/device-tests/templates/download-artifacts.yml
- tools/devops/device-tests/templates/publish-html.yml
Use the pool that is used just for utilities/short-lived tasks.
> [Devops] Use the deployment pool.

- tests/xharness/Jenkins/RunSimulatorTasksFactory.cs
- tests/xharness/Jenkins/TestVariationsFactory.cs
Now they're actually ignored if .NET tests are not included.
> [xharness] Fix how .NET projects are ignored.

- src/CoreBluetooth/Enums.cs
- src/corebluetooth.cs
- tests/xtro-sharpie/macOS-CoreBluetooth.todo
Apple removed the 10.16 API instead of marking them for 11.0 ?!?
> [corebluetooth] Update for Xcode 12 beta 3

- src/AppKit/NSPredicateEditorRowTemplate.cs
- src/NaturalLanguage/NLLanguageRecognizer.cs
- src/Security/Trust.cs
> Remove some LINQ usages

- src/appkit.cs
So correct for XAMCORE_4_0.
https://developer.apple.com/documentation/appkit/nsscrollview/1403485-documentview?language=objc
> [AppKit] NSScrollView.DocumentView is an NSView.

- tools/devops/device-tests/scripts/GitHub.psm1
- tools/devops/device-tests/scripts/VSTS.psm1
The parameter was added after powershell 6, and the one in the utility pool is older. We should not have issues with the aut.
> [DevOps] The powershell in Windows is older, we do not support the param.

- tools/dotnet-linker/dotnet-linker.csproj
This makes the layout match the mtouch and mmp project files.
Ref: 570f5ad8a31f1c6995b0ac4284534b6cd8d53e22
> [dotnet-linker] Rework the project file a bit.

- tools/common/Driver.cs
- tools/mmp/driver.cs
- tools/mtouch/mtouch.cs
This is just moving code, no functional changes.
> [mtouch/mmp] Share a few P/Invokes.

- msbuild/Xamarin.Shared/Xamarin.Shared.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
The .NET logic will inject an additional dependencies in these variables.
> [msbuild] Create a few '_*DependsOn' variables that specifies depend targets.

- src/HomeKit/HMEnums.cs
- tests/xtro-sharpie/iOS-HomeKit.todo
- tests/xtro-sharpie/tvOS-HomeKit.todo
- tests/xtro-sharpie/watchOS-HomeKit.todo
I'm not sure why these enums weren't added or picked up before.
do-not-merge added until beta 4 updates are added.
> [HomeKit][Xcode12] Update for beta 3

- src/CoreLocation/CLEnums.cs
- src/cfnetwork.cs
- src/classkit.cs
- src/coremotion.cs
> [Xcode12] Fix some availability attributes missed in the Beta 3/4 updates

- README.md
Fixes https://github.com/xamarin/xamarin-macios/issues/9337
> [README] Add d16-7 versions

- tests/generator/Makefile
- tests/mmptest/Makefile
- tests/mtouch/Makefile
- tests/sampletester/Makefile
Fixes https://github.com/xamarin/maccore/issues/2279
> [tests] Fix running several test suites from the command line. Fixes xamarin/maccore@2279.

- tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Utilities/ProjectFileExtensions.cs
Fixes https://github.com/xamarin/maccore/issues/2277.
> [xharness] Add support for adding PropertyGroups for unknown platform/configuration values in a csproj. Fixes xamarin/maccore@2277.

- src/arkit.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/9271
> [ARKit] Bug fix: Add SupportsFrameSemantics to all subclasses of ARConfiguration

- Make.config
Backport of #9359.
/cc @dalexsoto
> [xcode12] Update API diff to latest stable release

- Make.config
Backport of #9359.
/cc @dalexsoto
> [d16-8] Update API diff to latest stable release

- tests/monotouch-test/ARKit/ARAnchorTest.cs
- tests/monotouch-test/ARKit/AREnvironmentProbeAnchorTest.cs
Things are a bit better with beta 5
part of #8943
> [tests][monotouch-test] Re-enable some ARKit tests

- tests/xtro-sharpie/iOS-OSLog.ignore
- tests/xtro-sharpie/macOS-OSLog.ignore
- tests/xtro-sharpie/tvOS-OSLog.ignore
Issue: https://github.com/xamarin/xamarin-macios/issues/9480
> [OSLog] Moving Todo File Contents to Ignore Files

- src/appkit.cs
I closed the last PR, made my changes, and force pushed which did not allow me to open the PR back up. I apologize for that!
Here is the link to closed PR: https://github.com/xamarin/xamarin-macios/pull/9476
> [AppKit] Update bindings to Xcode 12 Beta 5 

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ParseBundlerArgumentsTaskBase.cs
- msbuild/Xamarin.Shared/Xamarin.Shared.targets
- msbuild/tests/Xamarin.iOS.Tasks.Tests/TaskTests/ParseBundlerArgumentsTests.cs
> [msbuild] Parse --marshal-managed-exceptions and --marshal-objectivec-exceptions in ParseBundlerArgumentsTask.

- tools/common/Assembly.cs
- tools/linker/MonoTouch.Tuner/Extensions.cs
- tools/linker/MonoTouch.Tuner/PreserveSmartEnumConversionsSubStep.cs
The latter just calls the former.
> [tools] Use Extensions.Is instead of Extensions.IsPlatformType.

- tools/devops/device-tests/scripts/System.Tests.ps1
- tools/devops/device-tests/scripts/System.psm1
Follow the changes in Jenkins: https://github.com/xamarin/xamarin-macios/pull/9548
> [DevOps] As with jenkins, remove old simulators.

- src/avfoundation.cs
Backport of #9555.
/cc @whitneyschmidt
> [d16-7] [Enhancement] Fix typo in AVFoundation

- src/avfoundation.cs
Backport of #9555.
/cc @whitneyschmidt
> [d16-8] [Enhancement] Fix typo in AVFoundation

- tests/linker/CommonLinkAllTest.cs
- tests/linker/ios/link all/AttributeTest.cs
- tests/linker/ios/link all/CalendarTest.cs
- tests/linker/ios/link all/ClassLayoutTest.cs
- tests/linker/ios/link all/DataContractTest.cs
- tests/linker/ios/link all/InterfacesTest.cs
- tests/linker/ios/link all/PreserveTest.cs
- tests/linker/ios/link all/XmlSerializationTest.cs
This gets linkall to an almost green state (there are still a few more failing
tests, those are a bit more complex to fix and will get seperate PRs).
> [tests] Ignore/fix/adjust several link all tests to make them pass in .NET.

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ParseBundlerArgumentsTaskBase.cs
- msbuild/Xamarin.Shared/Xamarin.Shared.targets
- msbuild/tests/Xamarin.iOS.Tasks.Tests/TaskTests/ParseBundlerArgumentsTests.cs
> [msbuild] Parse the --optimize extra bundler arguments in ParseBundlerArgumentsTask.

- src/CoreData/Obsolete.cs
Reference beta 2 bump / de306cd96d9b8b5665ceb24bfcce69a78e978edf
> [coredata] Fix breaking change for NSCoreDataCoreSpotlightDelegate

- src/uikit.cs
- tests/xtro-sharpie/iOS-UIKit.ignore
- tests/xtro-sharpie/tvOS-UIKit.ignore
- tests/xtro-sharpie/watchOS-UIKit.ignore
Fixes https://github.com/xamarin/xamarin-macios/issues/9597.
> [UIKit] Sprinkle NullAllowed on UIImage according to Apple's headers. Fixes #9597.

- tools/linker/ScanTypeReferenceStep.cs
The type references are not cleaned (anymore?) and what's in memory can
be different from what will be saved to disk (which is the part that
matter).
So before linking we can check for type references (in a module) but
after linking need to see if it resolve (which means the definition,
of the reference, can still be found) and, just be be thorough, check
that's it's marked (if found).
Fixes #8814.
> [linker] Fix warnings on type references that still exists. Fix #8814

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ParseBundlerArgumentsTaskBase.cs
- msbuild/Xamarin.Shared/Xamarin.Shared.targets
- msbuild/tests/Xamarin.iOS.Tasks.Tests/TaskTests/ParseBundlerArgumentsTests.cs
> [msbuild] Parse the --registrar extra bundler argument in ParseBundlerArgumentsTask.

- src/AudioToolbox/Enums.cs
- src/AudioUnit/AudioComponent.cs
- tests/monotouch-test/AudioUnit/AudioUnitTest.cs
- tests/xtro-sharpie/common-AudioToolbox.ignore
- tests/xtro-sharpie/iOS-AudioToolbox.todo
- tests/xtro-sharpie/macOS-AudioToolbox.todo
- tests/xtro-sharpie/tvOS-AudioToolbox.todo
The most important changes in the API are ignored until we fix issue https://github.com/xamarin/xamarin-macios/issues/9602
> [AudioToolbox] Update API to xcode 12 beta 6.

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ParseBundlerArgumentsTaskBase.cs
- msbuild/Xamarin.Shared/Xamarin.Shared.targets
- msbuild/tests/Xamarin.iOS.Tasks.Tests/TaskTests/ParseBundlerArgumentsTests.cs
> [msbuild] Parse the --xml extra bundler argument in ParseBundlerArgumentsTask.

- jenkins/Jenkinsfile
> [xcode12] [jenkins] Don't try to upload any packaged Xamarin.Mac tests if there aren't any or they failed to compile.

- src/Metal/MTLIntersectionFunctionTable.cs
Do it after the review comments on https://github.com/xamarin/xamarin-macios/pull/9651
> [Metal] Add missing GC.KeeAlive.

- tests/cecil-tests/packages.config
Try to fix the issue by stating the version of the runner. This change
will not be needed when we merge with main.
fixes https://github.com/xamarin/maccore/issues/2315
> [Cecil] Try to fix tests by stating the version in the console runner.

- jenkins/Jenkinsfile
There were are few more commits on xcode12 after the previous merge started,
this is those commits.
> [d16-8] Merge xcode12 into d16-8.

- Make.config
> [d16-8] [VSMac] Bump max version to current stable.

- tests/xtro-sharpie/DeprecatedCheck.cs
- tests/xtro-sharpie/common-CoreBluetooth.ignore
- tests/xtro-sharpie/common-CoreLocation.ignore
ref: https://github.com/xamarin/xamarin-macios/issues/9026
> [tests][xtro] Consider class (static) methods when checking for deprecation. Fix #9026

- src/CarPlay/CPCompat.cs
- src/carplay.cs
- src/frameworks.sources
- tests/xtro-sharpie/iOS-CarPlay.ignore
CPEntity docs got removed https://developer.apple.com/documentation/carplay/cpentity
so it is very likely that Apple will keep this out from the API.
> [CarPlay] Update bindings to Xcode 12.2 Beta 1

- tests/xtro-sharpie/DeprecatedCheck.cs
- tests/xtro-sharpie/common-CoreBluetooth.ignore
- tests/xtro-sharpie/common-CoreLocation.ignore
- tests/xtro-sharpie/macOS-CoreLocation.ignore
ref: https://github.com/xamarin/xamarin-macios/issues/9026
Backport of #9743.
/cc @spouliot
> [xcode12.2] [tests][xtro] Consider class (static) methods when checking for deprecation. Fix #9026

- src/uikit.cs
- tests/xtro-sharpie/Runner.cs
- tests/xtro-sharpie/UIAppearanceCheck.cs
- tests/xtro-sharpie/common-UIKit.ignore
- tests/xtro-sharpie/iOS-UIKit.ignore
- tests/xtro-sharpie/tvOS-UIKit.ignore
- tests/xtro-sharpie/xtro-sharpie.csproj
based on the header's `UI_APPEARANCE_SELECTOR` decorations
Fix https://github.com/xamarin/xamarin-macios/issues/7136
Backport of #9765.
/cc @spouliot
> [xcode12.2] [tests][xtro] Check for missing/extra [Appearance]. Fix #7136

- src/appkit.cs
- tests/xtro-sharpie/macOS-AppKit.ignore
- Fixes https://github.com/xamarin/xamarin-macios/issues/9827
> [AppKit] Allow NSGraphicsContext.CurrentContext to be null

- src/appkit.cs
- tests/xtro-sharpie/macOS-AppKit.ignore
- Fixes https://github.com/xamarin/xamarin-macios/issues/9827
Backport of #9838.
/cc @dalexsoto @chamons
> [xcode12.2] [AppKit] Allow NSGraphicsContext.CurrentContext to be null

- tests/msbuild/Xamarin.MacDev.Tasks.Tests/Xamarin.MacDev.Tasks.Tests.csproj
- tests/msbuild/Xamarin.MacDev.Tests/Xamarin.MacDev.Tests.csproj
This makes it easier to navigate the projects in the IDE.
> [tests] Put linked source code into an external/ folder in the msbuild test projects.

- tests/monotouch-test/Network/NWBrowserTest.cs
> [xcode12.2] [Tests][Network] Do not really check the value, just make sure that we are called.

- tests/xharness/Jenkins/Reports/HtmlReportWriter.cs
This makes emojiis in the html report render properly 😁
> [xharness] Announce to the world that we're creating UTF8 documents.

- tests/monotouch-test/Network/NWBrowserTest.cs
> [xcode12.1] [Tests][Network] Do not really check the value, just make sure that we are called.

- .github/workflows/label-checker.yml
Bring action so that we do release notes correctly.
> [d16-8] Add label checks.

- Make.config
> [Makefile] Point to xcode12.1 xip file.

- Make.config
RE provided the 12.1 version.
Backport of #9973.
> [d16-8] [Makefile] Point to xcode12.1 xip file.

- dotnet/.gitignore
- dotnet/Makefile
- dotnet/generate-wix.csharp
- jenkins/Jenkinsfile
- jenkins/build-nugets.sh
Create, upload and publish a Windows installer (.msi) for each workload.
> [dotnet] Package the workloads in a Windows installer (.msi) as well.

- src/btouch.cs
Improve output to include the command used to try to compile.
> [bgen] Improve output when compilation fails for either the binding sources or the generated sources.

- Make.config
RE updated the path in the bots.
> [Makefile] Update the path of xcode to be stable.

- .github/workflows/label-checker.yml
> [xcode12.2] [Actions] Add debug for the workflow to find why it does not work with hub

- .github/workflows/label-checker.yml
> [d16-8] [Actions] Add debug for the workflow to find why it does not work with hub

- .gitignore
- tools/devops/Makefile
- tools/devops/automation/build-pipeline.yml
- tools/devops/automation/productsign.sh
- tools/devops/build-provisioning.csx.in
- tools/devops/provision-brew-packages.csx
- tools/devops/provision-xcode.csx
- tools/devops/python-dependencies.txt
First steps for the migration, the job only does the following:
1. Builds the project
2. Builds the pkgs
3. Builds the nugets
4. Signs the pkgs
5. Uploads everything as a build artifact.
Next steps should be: 
1. Upload to azure blob storage. 
2. Create the artifacts json
3. Add Github status notifications.
> [VSTS] Make the pipeline build and notarize the pkgs

- Make.config
Both xtro and intro looks fine locally, no update required.
> Bump Xcode 12.2 to RC

- CODEOWNERS
- One last PR for the road. 
- Added Rolf on a few files that had no one but me but were msbuild/mmp related.
- Added Sebastien on a few files that had no one but me.
> Update CODEOWNERS. :wave:

- mk/xamarin.mk
Commits:
* Insert keychain into search list without overwriting other keychains https://github.com/xamarin/maccore/commit/243810037e19a81e39c8414d46d0567f73b2104a
* Fix working in comment https://github.com/xamarin/maccore/commit/243810037e19a81e39c8414d46d0567f73b2104a
* Insert login keychain without overwriting other keychains in the search https://github.com/xamarin/maccore/commit/7e6beed1d0d3120797e914ac8f49c3b986d176b2
* Merge pull request #2332 from xamarin/yaml-pipeline-device-tests https://github.com/xamarin/maccore/commit/7e6beed1d0d3120797e914ac8f49c3b986d176b2
* Avoid adding duplicate keychains to keychain list (#2333) https://github.com/xamarin/maccore/commit/7e6beed1d0d3120797e914ac8f49c3b986d176b2
* [Governance] Fix some small polycheck issues. …
> [Maccore] Bump maccore to fix governance issues.

- tools/devops/automation/build-pipeline.yml
- tools/devops/automation/scripts/GitHub.Tests.ps1
- tools/devops/automation/scripts/GitHub.psm1
- tools/devops/automation/templates/configure-build.yml
- tools/devops/automation/templates/device-tests.yml
- tools/devops/automation/templates/publish-html.yml
Use scripts under automation, device-tests will go away.
> [VSTS] Add support to get the info of a PR. 

- msbuild/Xamarin.MacDev.Tasks.Core/VerbosityUtils.cs
This way we get the full output from mtouch/mmp when the user creates a binary log.
> [msbuild] Default to verbose logs for mmp/mtouch if creating a binary log.

- src/AVKit/AVPlayerViewController.cs
- src/AVKit/Enums.cs
> [avkit] Add nullability for manual bindings

- src/AssetsLibrary/ALAsset.cs
- src/AssetsLibrary/ALAssetsGroup.cs
- src/AssetsLibrary/Enums.cs
> [assetslibrary] Add nullability for manual bindings

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ACToolTaskBase.cs
The platform is already validated in many other places.
> [msbuild] Remove unnecessary validation of the SdkPlatform.

- src/Accounts/AccountStoreOptions.cs
- src/Accounts/Enums.cs
- src/ObjCRuntime/ThrowHelper.cs
> [accounts] Add nullability for manual bindings

- src/Metal/MTLEnums.cs
Slight update done for macOS only in the final bits
https://github.com/xamarin/xamarin-macios/wiki/Metal-macOS-xcode12.2-FINAL
> [metal] Update Xcode 12.2 final

- src/networkextension.cs
- tests/xtro-sharpie/iOS-NetworkExtension.todo
- tests/xtro-sharpie/macOS-NetworkExtension.todo
Mostly changes in Xcode 12.2 (beta 3)
https://github.com/xamarin/xamarin-macios/wiki/NetworkExtension-iOS-xcode12.2-beta3
and macOS-only changes from 12.3 beta 1
https://github.com/xamarin/xamarin-macios/wiki/NetworkExtension-macOS-xcode12.3-beta1
> [networkextension] Update to Xcode 12.3 beta 1

- src/contacts.cs
- tests/xtro-sharpie/iOS-Contacts.todo
- tests/xtro-sharpie/macOS-Contacts.todo
- tests/xtro-sharpie/watchOS-Contacts.todo
intro Mac will fail but it will be resolved once https://github.com/xamarin/xamarin-macios/pull/10162 is merged
> [Contacts] Update bindings to Xcode 12.3 Beta 1

- src/coreimage.cs
- tests/xtro-sharpie/iOS-CoreImage.todo
- tests/xtro-sharpie/macOS-CoreImage.todo
- tests/xtro-sharpie/tvOS-CoreImage.todo
macOS intro will pass as soon as https://github.com/xamarin/xamarin-macios/pull/10162 is merged
> [CoreImage] Update bindings to Xcode 12.3 Beta 1

- tools/devops/device-tests/templates/device-tests.yml
This step is not working on certain bots, there are several examples at https://dev.azure.com/devdiv/DevDiv/_build?definitionId=13122&_a=summary
> [VSTS] If we fail dumping the env, continue.

- tests/common/mac/ProjectTestHelpers.cs
- tests/mmptest/src/MMPTest.cs
Fixes: https://github.com/xamarin/xamarin-macios/issues/8939
> [tests] Remove the MM0143 test, it doesn't look like VSMac is going to fix the bug. Fixes #8939.

- docs/website/binding_types_reference_guide.md
- From https://github.com/xamarin/ios-samples/pull/410
> [docs] Clarify optional protocol support with class vs interface

- tools/devops/device-tests/templates/device-tests.yml
This step is not working on certain bots, there are several examples at https://dev.azure.com/devdiv/DevDiv/_build?definitionId=13122&_a=summary
Backport of #10193.
> [xcode12.3] [VSTS] If we fail dumping the env, continue.

- src/CoreGraphics/CGColor.cs
- tests/monotouch-test/CoreGraphics/ColorTest.cs
and add unit test
Fix https://github.com/xamarin/xamarin-macios/issues/10212
> [coregraphics] Expose CGColor.CreateByMatchingToColorSpace

- src/GameKit/GKCompat.cs
- src/GameKit/GKLocalPlayerListener.cs
- src/GameKit/GKScore.cs
- src/GameKit/GameKit.cs
- src/GameKit/GameKit2.cs
- src/gamekit.cs
- tests/xtro-sharpie/iOS-GameKit.ignore
- tests/xtro-sharpie/macOS-GameKit.ignore
- tests/xtro-sharpie/tvOS-GameKit.ignore
- tests/xtro-sharpie/watchOS-GameKit.ignore
> [gamekit] Add nullability to (generated and manual) bindings

- src/CoreBluetooth/AdvertisementDataOptions.cs
- src/CoreBluetooth/CBCompat.cs
- src/CoreBluetooth/CBManager.cs
- src/CoreBluetooth/CBPeer.cs
- src/CoreBluetooth/CBUUID.cs
- src/CoreBluetooth/CoreBluetooth.cs
- src/CoreBluetooth/Enums.cs
- src/CoreBluetooth/GuidWrapper.cs
- src/CoreBluetooth/PeripheralConnectionOptions.cs
- src/CoreBluetooth/PeripheralScanningOptions.cs
- src/corebluetooth.cs
- tests/xtro-sharpie/common-CoreBluetooth.ignore
- tests/xtro-sharpie/iOS-CoreBluetooth.ignore
- tests/xtro-sharpie/macOS-CoreBluetooth.ignore
- tests/xtro-sharpie/tvOS-CoreBluetooth.ignore
> [corebluetooth] Add nullability to (generated and manual) bindings

- tools/devops/automation/build-pipeline.yml
- tools/devops/automation/templates/packages/build.yml
- tools/devops/automation/templates/packages/stage.yml
Allow to conditionally disable the tests when manually running the pipelines which makes working with the faster.
> [VSTS] Allow to skip tests via a parameter to make debugging easier.

- tools/devops/automation/templates/packages/upload-azure.yml
The wrong variable was used and therefore the dir path was used instead
of the mac pkg name.
fixes: https://github.com/xamarin/maccore/issues/2353
> [CI][VSTS] Add the correct mac pkg file name.

- tools/devops/automation/templates/packages/upload-azure.yml
The wrong variable was used and therefore the dir path was used instead
of the mac pkg name.
fixes: https://github.com/xamarin/maccore/issues/2353 
Backport of #10347
> [xcode12.3] [CI][VSTS] Add the correct mac pkg file name.

- .github/workflows/label-checker.yml
> [Actions] Ensure the new bot is considered.

- tools/devops/automation/build-pipeline.yml
fixes: https://github.com/xamarin/maccore/issues/2355
> [CI][VSTS] Add trigger for xcode branches.

- tools/devops/automation/build-pipeline.yml
fixes: https://github.com/xamarin/maccore/issues/2355 
Backport of #10349
> [d16-9] [CI][VSTS] Add trigger for xcode branches.

- .github/workflows/label-checker.yml
@monojenkins is no more. 
Backport of #10352
> [d16-9] [Actions] Ensure the new bot is considered.

- .github/workflows/label-checker.yml
@monojenkins is no more. 
Backport of #10352
> [xcode12.3] [Actions] Ensure the new bot is considered.

- Make.config
Let's make the provisioning step faster
> [xcode12.3] Update Xcode to stable 12.3

- .github/workflows/label-checker.yml
All branches have to be modified, lets remove monojenkins as @spouliot said.
> [Actions] Add the user to all branches. Remove monojenkins.

- .github/workflows/label-checker.yml
All branches have to be modified, lets remove monojenkins as @spouliot said. 
Backport of #10368
> [xcode12.3] [Actions] Add the user to all branches. Remove monojenkins.

- .github/workflows/label-checker.yml
All branches have to be modified, lets remove monojenkins as @spouliot said. 
Backport of #10368
> [d16-9] [Actions] Add the user to all branches. Remove monojenkins.

- tests/xtro-sharpie/Makefile
Use a variable for the sharpie executable, so that it's easier to override
while doing testing.
> [xtro] Make it possible to override the sharpie executable.

- tools/devops/automation/scripts/GitHub.psm1
Perseverance is failing 19 times and succeeding the 20th.
fix: https://github.com/xamarin/maccore/issues/2361
> [CI][VSTS] When webservers are rude, retry

- tools/devops/automation/scripts/GitHub.psm1
Perseverance is failing 19 times and succeeding the 20th.
fix: https://github.com/xamarin/maccore/issues/2361
Backport of #10411
> [d16-9] [CI][VSTS] When webservers are rude, retry

- tools/devops/automation/scripts/GitHub.psm1
Github has a limited size for messages in comments. If we did reach that
limit, we create a gist to show all the results.
> [CI][VSTS] If comments are too large, provide a gist.

- tests/package-mac-tests.sh
fixes: https://github.com/xamarin/maccore/issues/2363
> [CI][VSTS] The pkg of the tests fail because there is a path not longer found.

- tools/devops/automation/scripts/GitHub.psm1
Github has a limited size for messages in comments. If we did reach that
limit, we create a gist to show all the results.
Backport of #10431
> [xcode12.3] [CI][VSTS] If comments are too large, provide a gist.

- tools/devops/automation/scripts/GitHub.psm1
Perseverance is failing 19 times and succeeding the 20th.
fix: https://github.com/xamarin/maccore/issues/2361
Backport of #10411
> [xcode12.3] [CI][VSTS] When webservers are rude, retry

- tests/linker/ios/link all/dotnet/iOS/link all.csproj
Also don't overwrite DefineConstants, just add to it instead.
> [tests] Adjust link all's project file to set properties to their expected values according to the current configuration.

- tools/devops/automation/scripts/GitHub.psm1
- tools/devops/automation/templates/build/publish-html.yml
Add links to the comment for easy access, example: https://github.com/xamarin/xamarin-macios/commit/fb4e16fc8aba3739b156649389c5a7c5caf3bc9c#commitcomment-46162548
Backport of #10481
> [xcode12.3] [VSTS][CI] Add links with the generated pkgs.

- tools/devops/automation/scripts/GitHub.psm1
- tools/devops/automation/templates/build/publish-html.yml
Add links to the comment for easy access, example: https://github.com/xamarin/xamarin-macios/commit/fb4e16fc8aba3739b156649389c5a7c5caf3bc9c#commitcomment-46162548
Backport of #10481
> [d16-9] [VSTS][CI] Add links with the generated pkgs.

- tools/devops/automation/templates/build/build.yml
> [d16-9] [CI][VSTS] Add a poor mans debugger.

- tools/devops/automation/templates/build/build.yml
> [xcode12.3] [CI][VSTS] Add a poor mans debugger.

- tools/devops/automation/templates/build/build.yml
> [xcode12.3] [CI][VSTS] Fix needed in ESRP landed in the prod feed so we can use it now.

- mk/xamarin.mk
Commits:
* Remove Vincent as a code owner https://github.com/xamarin/maccore/commit/87e165fdbb207bc8a0eb46a8e9abb83ec058bb07
* [CI][VSTS] Add information when the external tool fails. https://github.com/xamarin/maccore/commit/0dfeb85ff607f6d0bb4063de4f4b91c4161b8e55
Full diff: https://github.com/xamarin/maccore/compare/55a700bb5ba3c092f511075d479d82ecb10fa5fe..0dfeb85ff607f6d0bb4063de4f4b91c4161b8e55
> [Maccore] Bump to pick CI fixes.

- src/CoreData/Enums.cs
- src/CoreData/NSEntityDescription.cs
- src/CoreData/Obsolete.cs
- src/coredata.cs
- tests/xtro-sharpie/MacCatalyst-CoreData.todo
- tests/xtro-sharpie/common-CoreData.ignore
- tests/xtro-sharpie/iOS-CoreData.ignore
- tests/xtro-sharpie/macOS-CoreData.ignore
- tests/xtro-sharpie/tvOS-CoreData.ignore
- tests/xtro-sharpie/watchOS-CoreData.ignore
> [coredata] Add nullability to (generated and manual) bindings

- tools/devops/automation/templates/build/build.yml
> [d16-9] [CI][VSTS] Fix needed in ESRP landed in the prod feed so we can use it now.

- tools/devops/automation/templates/build/build.yml
Manu[e|a]lbackport of https://github.com/xamarin/xamarin-macios/commit/390fab7c0b59a06a85fb325b7cdcb9b18e1545fc
> [xcode12.4][VSTS][CI] Fix issues with the internal pool and VSTS git usage.

- tools/devops/automation/templates/build/build.yml
Manu[e|a]lbackport of https://github.com/xamarin/xamarin-macios/commit/390fab7c0b59a06a85fb325b7cdcb9b18e1545fc
> [d16-9][VSTS][CI] Fix issues with the internal pool and VSTS git usage. 

- tools/devops/automation/templates/build/build.yml
Manu[e|a]lbackport of https://github.com/xamarin/xamarin-macios/commit/390fab7c0b59a06a85fb325b7cdcb9b18e1545fc
> [Xcode12.3][VSTS][CI] Fix issues with the internal pool and VSTS git usage. 

- tests/xharness/Harness.cs
Contributes to https://github.com/xamarin/xamarin-macios/issues/10440.
> [xharness] framework-test is now green on Mac Catalyst

- tests/linker/ios/link all/LinkAllTest.cs
- tests/linker/ios/link sdk/LinkSdkRegressionTest.cs
- tests/linker/ios/link sdk/OptimizeGeneratedCodeTest.cs
- tests/linker/ios/link sdk/extra-linker-defs-maccatalyst.xml
- tests/xharness/Harness.cs
Contributes towards https://github.com/xamarin/xamarin-macios/issues/10440.
> [tests] Make link sdk and link all work on Mac Catalyst.

- tools/devops/automation/templates/mac/stage.yml
fixes: https://github.com/xamarin/maccore/issues/2395
> [CI][VSTS] Do not run old macOS on PRs.

- src/MapKit/MKCompat.cs
- src/MapKit/MKDirections.cs
- src/MapKit/MKEnums.cs
- src/MapKit/MKFeatureDisplayPriority.cs
- src/MapKit/MKGeodesicPolyline.cs
- src/MapKit/MKLocalSearch.cs
- src/MapKit/MKMapCameraZoomRange.cs
- src/MapKit/MKMapItem.cs
- src/MapKit/MKMultiPoint.cs
- src/MapKit/MKOverlayView.cs
- src/MapKit/MKPointOfInterestFilter.cs
- src/MapKit/MKPolygon.cs
- src/MapKit/MKPolyline.cs
- src/MapKit/MapKit.cs
- src/mapkit.cs
- tests/xtro-sharpie/MacCatalyst-MapKit.todo
- tests/xtro-sharpie/common-MapKit.ignore
- tests/xtro-sharpie/iOS-MapKit.ignore
- tests/xtro-sharpie/macOS-MapKit.ignore
- tests/xtro-sharpie/tvOS-MapKit.ignore
- tests/xtro-sharpie/watchOS-MapKit.ignore
> [mapkit] Add nullability to (generated and manual) bindings

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileNativeCodeTaskBase.cs
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/LinkNativeCodeTaskBase.cs
Mac Catalyst is a special case, and needs some special casing.
> [msbuild] Add Mac Catalyst support to the CompileNativeCode and LinkNativeCode tasks.

- Makefile
The name of the branch says it all.
> [Makefile] Why copy-paste when you can 'make fix-xcode-select'

- tools/devops/automation/templates/build/build.yml
> [xcode12.5] [CI][VSTS]  Take into account timeouts and other errors.

- tools/devops/automation/templates/build/build.yml
> [d16-9] [CI][VSTS]  Take into account timeouts and other errors.

- tools/devops/automation/templates/build/build.yml
> [xcode12.4] [CI][VSTS]  Take into account timeouts and other errors.

- tests/sampletester/Configuration.cs
- tests/sampletester/Samples.cs
See 
https://dev.azure.com/xamarin/internal/_build/results?buildId=35682&view=results
https://dev.azure.com/xamarin/internal/_build/results?buildId=35737&view=results
> [tests] Make sampletester greener

- tests/sampletester/Configuration.cs
- tests/sampletester/Samples.cs
See 
https://dev.azure.com/xamarin/internal/_build/results?buildId=35682&view=results
https://dev.azure.com/xamarin/internal/_build/results?buildId=35737&view=results
Backport of #10713
> [xcode12.5] [tests] Make sampletester greener

- tests/sampletester/Configuration.cs
- tests/sampletester/Samples.cs
See 
https://dev.azure.com/xamarin/internal/_build/results?buildId=35682&view=results
https://dev.azure.com/xamarin/internal/_build/results?buildId=35737&view=results
Backport of #10713
> [xcode12.4] [tests] Make sampletester greener

- tests/sampletester/Configuration.cs
- tests/sampletester/Samples.cs
See 
https://dev.azure.com/xamarin/internal/_build/results?buildId=35682&view=results
https://dev.azure.com/xamarin/internal/_build/results?buildId=35737&view=results
Backport of #10713
> [d16-9] [tests] Make sampletester greener

- tools/devops/automation/scripts/GitHub.psm1
> [xcode12.4] [CI][VSTS] Fix small formatting issue.

- tools/devops/automation/scripts/GitHub.psm1
> [d16-9] [CI][VSTS] Fix small formatting issue.

- tools/devops/automation/scripts/GitHub.psm1
> [xcode12.5] [CI][VSTS] Fix small formatting issue.

- src/passkit.cs
- tests/xtro-sharpie/iOS-PassKit.todo
- tests/xtro-sharpie/macOS-PassKit.todo
- tests/xtro-sharpie/watchOS-PassKit.ignore
- tests/xtro-sharpie/watchOS-PassKit.todo
Also remove some extra xtro empty files
> [passkit] Update for xcode 12.5 beta 3

- dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileNativeCodeTaskBase.cs
- msbuild/Xamarin.Shared/Xamarin.Shared.props
- tests/dotnet/UnitTests/ProjectTest.cs
And fix a couple of issues that found.
> [tests] Add unit tests for building Mac Catalyst for ARM64.

- src/MediaPlayer/MPMediaItem.cs
- src/MediaPlayer/MPMediaItemArtwork.cs
- src/MediaPlayer/MPMediaQuery.cs
- src/MediaPlayer/MPMoviePlayerController.cs
- src/MediaPlayer/MPNowPlayingInfoCenter.cs
- src/MediaPlayer/MPPlayableContentDelegate.cs
- src/MediaPlayer/MPRemoteCommandCenter.cs
- src/MediaPlayer/MPSkipIntervalCommand.cs
- src/MediaPlayer/MPVolumeSettings.cs
- src/MediaPlayer/MediaPlayer.cs
- src/mediaplayer.cs
- tests/xtro-sharpie/MacCatalyst-MediaPlayer.todo
- tests/xtro-sharpie/common-MediaPlayer.ignore
- tests/xtro-sharpie/iOS-MediaPlayer.ignore
> [mediaplayer] Add nullability to (generated and manual) bindings

- src/Metal/Defs.cs
- src/Metal/MTLArgumentEncoder.cs
- src/Metal/MTLArrays.cs
- src/Metal/MTLBlitPassSampleBufferAttachmentDescriptorArray.cs
- src/Metal/MTLCompat.cs
- src/Metal/MTLComputeCommandEncoder.cs
- src/Metal/MTLComputePassSampleBufferAttachmentDescriptorArray.cs
- src/Metal/MTLDevice.cs
- src/Metal/MTLEnums.cs
- src/Metal/MTLIntersectionFunctionTable.cs
- src/Metal/MTLRasterizationRateLayerDescriptor.cs
- src/Metal/MTLRenderCommandEncoder.cs
- src/Metal/MTLRenderPassDescriptor.cs
- src/Metal/MTLRenderPassSampleBufferAttachmentDescriptorArray.cs
- src/Metal/MTLResourceStateCommandEncoder.cs
- src/Metal/MTLResourceStatePassSampleBufferAttachmentDescriptorArray.cs
- src/Metal/MTLVertexDescriptor.cs
- src/metal.cs
- tests/xtro-sharpie/MacCatalyst-Metal.todo
- tests/xtro-sharpie/iOS-Metal.ignore
- tests/xtro-sharpie/macOS-Metal.ignore
- tests/xtro-sharpie/tvOS-Metal.ignore
Removed some outdated comments (intro runs fine with them now)
> [metal] Add nullability to (generated and manual) bindings

- src/CoreText/CTRunDelegate.cs
* Make CTRunDelegateCallbacks a struct instead of class, since it's being
passed as a parameter to a P/Invoke. Passing an instance of a class to a
P/Invoke is just weird.
* Make CTRunDelegate subclass NativeObject. This allows us to remove a big
chunk of boiler-plate code.
* Make CTRunDelegateOperations.handle a private field. Handle fields should be
private.
* Put the CTRunDelegateCallbacks struct with the delegates passed to native
code on the CTRunDelegateOperations instance instead of the CTRunDelegate
instance, since the callbacks are tied to the CTRunDelegateOperations instance.
Fixes this fatal error on CoreCLR, because otherwise the Deallocate callback could be called after the CTRunDelegate instance was freed, in which case the Deallocate delegate could also be freed:
> A …
> [CoreText] Clean up CTRunDelegate[Operations] implementation.

- tools/devops/automation/templates/build/configure.yml
This PR adds a step to the configure yaml that will generate the LocProject.json file using changes to the Makefile from [this PR](https://github.com/xamarin/xamarin-macios/pull/10843).
> [Localization] Add Step to Generate LocProject.json

- src/Foundation/NSObject2.cs
Previously, the SuperHandle property returned a pointer into the middle of the
NSObject instance. This is not safe, because we can't make pin the NSObject
instance past the return of the SuperHandle property getter.
So rework the logic, to allocate a chunk of native memory that SuperHandle can
return, and use that instead. This means a little bit of book-keeping to
create and destroy this native memory.
Unfortunately it will also increase the memory usage for each NSObject
instance, but I don't see a way around that, while still fixing the problem
with SuperHandle, given that we can't change the signature of SuperHandle.
> [NSObject] Rework the SuperHandle property to not return a pointer into managed memory.

- tests/xharness/AppRunner.cs
- tests/xharness/xharness.csproj
We believe we reverted the culprint in main.
> [Xharness] Bump to the latests build in main.

- src/generate-type-forwarders/Program.cs
Examples:
```diff
-public void DidDeactivate (this IARCoachingOverlayViewDelegate This, ARCoachingOverlayView coachingOverlayView)
+public void DidDeactivate (IARCoachingOverlayViewDelegate This, ARCoachingOverlayView coachingOverlayView)
-public void DidRequestSessionReset (this IARCoachingOverlayViewDelegate This, ARCoachingOverlayView coachingOverlayView)
+public void DidRequestSessionReset (IARCoachingOverlayViewDelegate This, ARCoachingOverlayView coachingOverlayView)
-public void WillActivate (this IARCoachingOverlayViewDelegate This, ARCoachingOverlayView coachingOverlayView)
+public void WillActivate (IARCoachingOverlayViewDelegate This, ARCoachingOverlayView coachingOverlayView)
```
> [generate-type-forwarders] Fix extension methods

- src/generate-type-forwarders/Program.cs
Example
```diff
-public AvailabilityAttribute (Platform introduced, Platform deprecated = 0, Platform obsoleted = 0, Platform unavailable = 0)
+public AvailabilityAttribute (Platform introduced, Platform deprecated, Platform obsoleted, Platform unavailable)
```
> [generate-type-forwarders] Fix default parameters

- tests/mmptest/src/MMPTest.cs
This test verifies that the build log prints:
"execution started with arguments: actool --errors --warnings --notices --output-format xml1 --output-partial-info-plist "
However, for M1 machines, we don't call actool directly, we go through 'arch'
instead, and this line is printed:
Tool arch execution started with arguments: -arch arm64e /usr/bin/xcrun actool --errors --warnings --notices --output-format xml1 --output-partial-info-plist ...
So adjust the test to cope with both of these behaviors.
> [tests] Adjust BuildingSameSolutionTwice_ShouldNotRunACToolTwice to work on an M1 machine.

- tools/devops/automation/templates/build/publish-html.yml
> [CI][APDiff] Fix pattern matching.

- tools/devops/automation/templates/build/configure.yml
This PR adds the PAT that OneLocBuild requires.
> [Localization] Adding OneLocBuildPat Variable

- tools/devops/automation/templates/build/configure.yml
Passing in arguments to the OneLocBuild task to allow check-in to our github repo
> [Localization] Adding Check-In Capability

- tools/devops/automation/templates/build/configure.yml
Adding in a conditional to trigger OneLocBuild task only on merges
> [Localization] Adding Merge Conditional

- tools/devops/automation/templates/common/download-artifacts.yml
> [d16-9] [CI] Remove noise that was added while testing.

- tools/devops/automation/build-pipeline.yml
> [xcode12.5] [CI] VSdrops uris are case sensitive.

- tools/devops/automation/build-pipeline.yml
> [d16-9] [CI] VSdrops uris are case sensitive.

- tools/devops/automation/templates/build/build.yml
Manual backport of https://github.com/xamarin/xamarin-macios/commit/8041d36d356126b8d4c1d1c93b541e1c6ef093da
> [CI] Remove steps that are never used. (#11026)

- tools/devops/automation/templates/devices/build.yml
> [d16-9] [CI] 50gb is a lot. Reduce to 20gb since our device bots are old.

- tools/devops/automation/templates/devices/build.yml
> [xcode12.5] [CI] 50gb is a lot. Reduce to 20gb since our device bots are old.

- tools/devops/automation/templates/build/configure.yml
- tools/devops/automation/templates/build/stage.yml
> [xcode12.5] [CI] Fwd labels and ensure dotnet tests are run when targeting main.

- tools/devops/automation/templates/build/configure.yml
- tools/devops/automation/templates/build/stage.yml
> [d16-9] [CI] Fwd labels and ensure dotnet tests are run when targeting main.

- tools/devops/automation/build-pipeline.yml
> [d16-9] [CI] Do not build translation branches in the internal pool.

- tools/devops/automation/build-pipeline.yml
> [xcode12.5] [CI] Do not build translation branches in the internal pool.

- tools/devops/automation/templates/build/configure.yml
- tools/devops/automation/templates/build/stage.yml
> [xcode12.5] [CI] Add the id of the pr to an old env var to reuse scripts.

- tools/devops/automation/templates/build/configure.yml
- tools/devops/automation/templates/build/stage.yml
> [d16-9] [CI] Add the id of the pr to an old env var to reuse scripts.

- tools/devops/automation/build-pipeline.yml
> [d16-9] [CI] Do not build darc PRs in the CI.

- tools/devops/automation/templates/agent-pool-selector.yml
- tools/devops/automation/templates/build/build.yml
Manual backport of https://github.com/xamarin/xamarin-macios/pull/11090
> Target new xamarin-macios multi-OS agent pools (#11090)

- tools/devops/automation/build-pipeline.yml
> [xcode12.5] [CI] Do not build darc PRs in the CI.

- tools/devops/automation/build-pipeline.yml
Lets not trigger builds for readmes and other docs.
> [CI] Exclude builds for certain paths.

- tools/devops/automation/templates/build/api-diff.yml
- tools/devops/automation/templates/build/build.yml
Step fwd to group all API diff and get back the old generator and branch diffs.
> [CI] Group all API diff in a template to make things manageable.

- tools/devops/automation/templates/build/build.yml
- tools/devops/automation/templates/build/sign-and-notarized.yml
- tools/devops/automation/templates/build/stage.yml
Manual backport of https://github.com/xamarin/xamarin-macios/pull/11092
> [d16-9][CI] Move sign and notarize out. (#11092)

- tools/devops/automation/templates/build/configure.yml
We are trying to join the json rather than the collection of strings.
$tag is a collection we can join.
> [CI] Fix wrong fwd labels.

- tools/devops/automation/scripts/GitHub.psm1
> [xcode12.5] [CI][GitHub] Use the correct verb to the request.

- tools/devops/automation/scripts/GitHub.psm1
> [d16-9] [CI][GitHub] Use the correct verb to the request.

- tools/devops/automation/build-pipeline.yml
Create a cron job that will execute on Sundays at noon to have a green
build for the translations team to use.
> [CI] Perform a  run with no tests on Sundays for the translations team.

- eng/Version.Details.xml
- eng/Versions.props
Reverts xamarin/xamarin-macios#11127 it was incorrectly auto merged.
> Revert "[main] Update dependencies from dotnet/installer"

- tools/devops/automation/build-pipeline.yml
- tools/devops/automation/templates/build/download-artifacts.yml
- tools/devops/automation/templates/build/publish-html.yml
- tools/devops/automation/templates/build/stage.yml
- tools/devops/automation/templates/build/upload-vsdrops.yml
- tools/devops/automation/templates/common/download-artifacts.yml
We allow to manually run the builds with no tests, yet we had some
expectations in following jobs. This commit makes sure we do not get
errors when not runnning the tests.
> [CI] Do not try to upload test results when not ran.

- configure
Add a new option, fixed some alignment issues (an editor used tabs rather than spaces).
> [Build] Allow to disable the build with the xamarin parts.

- tools/devops/automation/templates/build/publish-html.yml
Co-authored-by: Alex Soto <alex@alexsoto.me>
> [xcode12.5][CI] Set status as error if one or more tests failed. (#11170)

- msbuild/Xamarin.Shared/Xamarin.Shared.targets
- runtime/monovm-bridge.m
- runtime/runtime.m
- runtime/xamarin/runtime.h
- src/Foundation/NSObject2.cs
Not sure how I could mess up a copy/paste between file - but I succeeded
to create a subtle bug (would have expected it more crash happy)
Fix issue #11151
Revert the previous (revert) fix (but not the build fixes)
> [d16-10][msbuild] Fix copy/paste error from #11196

- msbuild/Xamarin.Shared/Xamarin.Shared.targets
Not sure how I could mess up a copy/paste between file - but I succeeded
to create a subtle bug (would have expected it more crash happy)
Fix issue #11151
> [msbuild] Fix copy/paste error from #11196

- tools/devops/automation/scripts/GitHub.psm1
Will add an extra line with the commit message and the hash.
> [CI] Provide the info of the commit that generated a message.

- tools/devops/automation/scripts/GitHub.psm1
Will add an extra line with the commit message and the hash.
Backport of #11203
> [xcode12.5] [CI] Provide the info of the commit that generated a message.

- tools/devops/automation/scripts/GitHub.psm1
Will add an extra line with the commit message and the hash.
Backport of #11203
> [d16-9] [CI] Provide the info of the commit that generated a message.

- tools/devops/automation/templates/common/publish-html.yml
- tools/devops/automation/templates/common/upload-vsdrops.yml
- tools/devops/automation/templates/common/upload-vsts-tests.yml
- tools/devops/automation/templates/devices/stage.yml
> [xcode12.5] [CI] Avoid other not needed steps on provisioning issues.

- dotnet/targets/Xamarin.Shared.Sdk.targets
Fix crash for monotouch-test running on macOS / dotnet
fixes https://github.com/xamarin/maccore/issues/2413
> [dotnet][msbuild] Copy dylibs for macOS and Mac Catalyst

- mk/quiet.mk
- tests/Makefile
Ref: https://github.com/dotnet/sdk/issues/7986#issuecomment-604959822
> Make the quiet version of 'dotnet build' quieter.

- Make.config
- src/LocalAuthentication/LAEnums.cs
- src/arkit.cs
- src/avfoundation.cs
- src/metal.cs
- tests/xtro-sharpie/common-Metal.ignore
- tests/xtro-sharpie/macOS-Metal.ignore
and add the few new bindings added in the SDKs
> [xcode12.5] Bump for Xcode 12.5 RC

- Make.config
- src/LocalAuthentication/LAEnums.cs
- src/arkit.cs
- src/avfoundation.cs
- src/metal.cs
- tests/xtro-sharpie/common-Metal.ignore
- tests/xtro-sharpie/macOS-Metal.ignore
and add the few new bindings added in the SDKs
Backport of #11248
> [main] [xcode12.5] Bump for Xcode 12.5 RC

- tools/devops/automation/scripts/GitHub.psm1
VSTS has so many little corner cases....
> [CI] The env var is not provided in the CI builds, just PRs.

- tools/devops/automation/templates/build/upload-azure.yml
This is embarrassing. Was not catched because we do not run it on PR.
> [CI] Fix pwsh.

- Make.config
- src/LocalAuthentication/LAEnums.cs
- src/arkit.cs
- src/avfoundation.cs
- src/metal.cs
- tests/xtro-sharpie/common-Metal.ignore
- tests/xtro-sharpie/macOS-Metal.ignore
and add the few new bindings added in the SDKs
Backport of #11248
Backport of #11263
> [release/6.0.1xx-preview4] [main] [xcode12.5] Bump for Xcode 12.5 RC

- tools/devops/automation/scripts/GitHub.psm1
Move logic one level up and re-use it in the other status.
> [CI] Unify both failing statuses.

- mk/xamarin.mk
Commits:
* [Xamarin.Hosting] Show installation progress for higher verbosity (#2424) https://github.com/xamarin/maccore/commit/cddbd1915dcb27d8bf2d9b3b9cc4aeb22785698e
Full diff: https://github.com/xamarin/maccore/compare/d11721f55ede311d670acc5b0cc9a38562b499dc..cddbd1915dcb27d8bf2d9b3b9cc4aeb22785698e
> [Maccore] Bump maccore to the latests.

- tools/devops/automation/templates/common/publish-html.yml
> [d16-9] [CI] Add the context in the failed device bots.

- tools/devops/automation/templates/common/publish-html.yml
> [xcode12.5] [CI] Add the context in the failed device bots.

- tools/devops/automation/templates/build/upload-azure.yml
> [CI] Fix nuget messaging in case of failure.

- tools/devops/automation/templates/build/upload-azure.yml
-gt instead of >
Backport of #11335
> [d16-10] [CI] Fix nuget messaging in case of failure.

- src/VideoToolbox/VTCompressionProperties.cs
- src/VideoToolbox/VTCompressionSession.cs
- src/VideoToolbox/VTDecompressionSession.cs
- src/VideoToolbox/VTFrameSilo.cs
- src/VideoToolbox/VTMultiPassStorage.cs
- src/VideoToolbox/VTPixelTransferProperties.cs
- src/VideoToolbox/VTSession.cs
- src/VideoToolbox/VTUtilities.cs
- src/VideoToolbox/VTVideoEncoder.cs
- tests/xtro-sharpie/MacCatalyst-VideoToolbox.todo
and ajust xtro for unavbailable Catalyst API
> [videotoolbox] Update for dotnet attributes

- tests/xharness/Jenkins/TestSelector.cs
- tools/devops/automation/templates/build/build.yml
- tools/devops/automation/templates/build/stage.yml
Fix the tests selector by setting the PR number in an env variable that
is not longer linked with Jenkins.
Fixes #11299
> [Xharness] Fix the test selector.

- tests/xharness/Jenkins/TestSelector.cs
- tools/devops/automation/templates/build/build.yml
- tools/devops/automation/templates/build/stage.yml
Fix the tests selector by setting the PR number in an env variable that
is not longer linked with Jenkins.
Fixes #11299
> [xcode12.5][Xharness] Fix the test selector. (#11315)

- tests/xharness/Jenkins/TestSelector.cs
- tools/devops/automation/templates/build/build.yml
- tools/devops/automation/templates/build/stage.yml
Fix the tests selector by setting the PR number in an env variable that
is not longer linked with Jenkins.
Fixes #11299
> [d16-10][Xharness] Fix the test selector. (#11315)

- tests/xharness/Jenkins/TestSelector.cs
- tools/devops/automation/templates/build/build.yml
- tools/devops/automation/templates/build/stage.yml
Fix the tests selector by setting the PR number in an env variable that
is not longer linked with Jenkins.
Fixes #11299
> [d16-9][Xharness] Fix the test selector. (#11315)

- tools/devops/automation/build-pipeline.yml
> [d16-10] [CI] Unblock the CI by using our own channel for provisionator.

- tools/devops/automation/build-pipeline.yml
> [xcode12.5] [CI] Unblock the CI by using our own channel for provisionator.

- tools/devops/automation/build-pipeline.yml
> [release/6.0.1xx-preview4] [CI] Unblock the CI by using our own channel for provisionator.

- tests/xtro-sharpie/MacCatalyst-VideoToolbox.ignore
New file was not committed (should have been with a rename)
> [tests][xtro] Fix recent failures

- msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
There were some changes on the original target.
> [dotnet] Fixes _RunILLink from Windows for Preview 4

- tools/devops/automation/scripts/GitHub.psm1
- tools/devops/automation/templates/build/stage.yml
> [xcode12.5] [CI] Add a prefix to make it nicer to humans when several builds happen.

- tools/compare-commits.sh
> [d16-10] [Generator Diff] Ignore file we are not interested in.

- tools/compare-commits.sh
> [release/6.0.1xx-preview4] [Generator Diff] Ignore file we are not interested in.

- tools/compare-commits.sh
> [xcode12.5] [Generator Diff] Ignore file we are not interested in.

- tools/devops/automation/templates/build/configure.yml
Execute the loc step + the creation of a PR only in the cron job and
skipt it in anyother build.
> [CI] Just requests translations in the cron job.

- tools/devops/automation/build-pipeline.yml
- tools/devops/automation/templates/build/build.yml
- tools/devops/automation/templates/build/stage.yml
- tools/devops/automation/templates/devices/build.yml
Fixes https://github.com/xamarin/maccore/issues/2436.
Adds in certificate credentials into the environment so that we don't need to hit the keychain for passwords.
> d16-9 keychain removal

- tools/devops/automation/build-pipeline.yml
- tools/devops/automation/templates/devices/build.yml
Broke after landing https://github.com/xamarin/xamarin-macios/pull/11423
> [CI] Fix broken template after merge.

- tools/devops/automation/templates/mac/build.yml
Are we virtual or are we dancers?
> [CI] Dump the hardware of the bot to see if we are virtual.

- tools/devops/automation/templates/build/configure.yml
We are using cascade pipelines, those are triggered automatically and
get all the artifacts. We create a json file that will be used by one of
the cascaded pipelines to make educated choices.
> [CI] Store the config in a json to later be shared with other pipelines.

- tools/devops/automation/templates/mac/build.yml
Are we virtual or are we dancers?
Backport of #11453
> [release/6.0.1xx-preview4] [CI] Dump the hardware of the bot to see if we are virtual.

- tools/devops/automation/templates/mac/build.yml
Are we virtual or are we dancers?
Backport of #11453
> [d16-10] [CI] Dump the hardware of the bot to see if we are virtual.

- Make.config
Fixes https://github.com/xamarin/xamarin-macios/issues/11475.
> Bump system mono to get fix for #11475.

- tests/linker/ios/link all/DataContractTest.cs
- tests/linker/ios/link all/LinkAllTest.cs
Already known issues (already filled for similar tests in Link SDK)
> [dotnet][tests][link all] Ignore failures on devices

- tests/introspection/Mac/MacApiProtocolTest.cs
No notes worthy because I'm embarrassed.
Fixes https://github.com/xamarin/maccore/issues/2440
> [Tests] Undo change that broke intro in BS.

- tools/devops/LocProject.json.in
- tools/devops/automation/build-pipeline.yml
- tools/devops/automation/publish-pr-html-results.yml
- tools/devops/automation/scripts/bash/vsts-compare.sh
- tools/devops/automation/templates/build/api-diff.yml
- tools/devops/automation/templates/build/build.yml
- tools/devops/automation/templates/build/configure.yml
- tools/devops/automation/templates/build/download-artifacts.yml
- tools/devops/automation/templates/build/sign-and-notarized.yml
- tools/devops/automation/templates/build/stage.yml
- tools/devops/automation/templates/build/upload-azure.yml
- tools/devops/automation/templates/build/upload-vsdrops.yml
- tools/devops/automation/templates/devices/stage.yml
- tools/devops/automation/templates/mac/build.yml
- tools/devops/automation/templates/mac/stage.yml
- tools/devops/automation/templates/publish-html-result.yml
We have been drifting and that is not good. This is a backport doing:
```bash
git checkout main -- tools/devops
```
> [CI] Backport all changes in the CI from main to d16-10.

- tools/devops/LocProject.json.in
- tools/devops/automation/build-pipeline.yml
- tools/devops/automation/publish-pr-html-results.yml
- tools/devops/automation/scripts/GitHub.psm1
- tools/devops/automation/scripts/bash/compare.sh
- tools/devops/automation/scripts/bash/local-compare.sh
- tools/devops/automation/scripts/bash/vsts-compare.sh
- tools/devops/automation/templates/build/api-diff.yml
- tools/devops/automation/templates/build/build-nugets.yml
- tools/devops/automation/templates/build/build.yml
- tools/devops/automation/templates/build/configure.yml
- tools/devops/automation/templates/build/download-artifacts.yml
- tools/devops/automation/templates/build/publish-html.yml
- tools/devops/automation/templates/build/sign-and-notarized.yml
- tools/devops/automation/templates/build/stage.yml
- tools/devops/automation/templates/build/upload-azure.yml
- tools/devops/automation/templates/build/upload-vsdrops.yml
- tools/devops/automation/templates/common/publish-html.yml
- tools/devops/automation/templates/devices/stage.yml
- tools/devops/automation/templates/governance-checks.yml
- tools/devops/automation/templates/mac/build.yml
- tools/devops/automation/templates/mac/stage.yml
- tools/devops/automation/templates/publish-html-result.yml
We have been drifting and that is not ok. This is a backport doing:
```bash
git checkout main -- tools/devops
```
> [release-preview 4][CI] Backport all changes in the CI from main to release preview 4.

- tests/Makefile
> [d16-10] [CI] Do run 32b tests.

- tests/Makefile
Backport bot does not backport :/
> [CI] Do run 32b tests. (#11571)

- Localize/loc/cs/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/cs/tools/mtouch/Errors.resx.lcl
- Localize/loc/de/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/de/tools/mtouch/Errors.resx.lcl
- Localize/loc/es/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/es/tools/mtouch/Errors.resx.lcl
- Localize/loc/fr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/fr/tools/mtouch/Errors.resx.lcl
- Localize/loc/it/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/it/tools/mtouch/Errors.resx.lcl
- Localize/loc/ja/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/ja/tools/mtouch/Errors.resx.lcl
- Localize/loc/ko/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/ko/tools/mtouch/Errors.resx.lcl
- Localize/loc/pl/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/pl/tools/mtouch/Errors.resx.lcl
- Localize/loc/pt-BR/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/pt-BR/tools/mtouch/Errors.resx.lcl
- Localize/loc/ru/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/ru/tools/mtouch/Errors.resx.lcl
- Localize/loc/tr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/tr/tools/mtouch/Errors.resx.lcl
- Localize/loc/zh-Hans/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/zh-Hans/tools/mtouch/Errors.resx.lcl
- Localize/loc/zh-Hant/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/zh-Hant/tools/mtouch/Errors.resx.lcl
- tools/devops/automation/templates/build/configure.yml
- tools/devops/automation/templates/build/stage.yml
LEGO: Pull request from lego/hb_dca0a672-370a-4b3c-b55f-cd146e93faf9_20210518212627667 to Localization with localized lcls
> LEGO: Pull request from lego/hb_dca0a672-370a-4b3c-b55f-cd146e93faf9_20210518212627667 to Localization

- Localize/loc/de/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/de/tools/mtouch/Errors.resx.lcl
- Localize/loc/es/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/es/tools/mtouch/Errors.resx.lcl
- Localize/loc/fr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/fr/tools/mtouch/Errors.resx.lcl
- Localize/loc/it/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/it/tools/mtouch/Errors.resx.lcl
- Localize/loc/pl/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/pl/tools/mtouch/Errors.resx.lcl
- Localize/loc/tr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/tr/tools/mtouch/Errors.resx.lcl
LEGO: Pull request from lego/hb_dca0a672-370a-4b3c-b55f-cd146e93faf9_20210519221352778 to Localization with localized lcls
> LEGO: Pull request from lego/hb_dca0a672-370a-4b3c-b55f-cd146e93faf9_20210519221352778 to Localization

- Localize/loc/fr/tools/mtouch/Errors.resx.lcl
- Localize/loc/ja/tools/mtouch/Errors.resx.lcl
- Localize/loc/ko/tools/mtouch/Errors.resx.lcl
- Localize/loc/pt-BR/tools/mtouch/Errors.resx.lcl
- Localize/loc/zh-Hans/tools/mtouch/Errors.resx.lcl
- Localize/loc/zh-Hant/tools/mtouch/Errors.resx.lcl
LEGO: Pull request from lego/hb_dca0a672-370a-4b3c-b55f-cd146e93faf9_20210520101402758 to Localization with localized lcls
> LEGO: Pull request from lego/hb_dca0a672-370a-4b3c-b55f-cd146e93faf9_20210520101402758 to Localization

- tests/Makefile
- tests/common/Configuration.cs
- tests/msbuild/Xamarin.MacDev.Tests/DotnetTest.cs
- tests/xharness/Harness.cs
- tests/xharness/IHarness.cs
- tests/xharness/Jenkins/NUnitTestTasksEnumerable.cs
- tests/xharness/Jenkins/TestSelector.cs
- tests/xharness/Jenkins/TestTasks/BuildTool.cs
- tests/xharness/Jenkins/TestTasks/BuildToolTask.cs
- tests/xharness/Jenkins/TestTasks/MSBuild.cs
Allow to uses constants to ignore dotnet tests without creating a new project.
> [CI] Allow to ignore tests if dotnet is enabled.

- tools/devops/automation/templates/publish-html-result.yml
The branch name will be:
* pr/branchname/branch_commit/buildid - for builds triggered by a pr
* ci/branchname/branch_commit/buildid - for all others.
Commit and build id have been added to ensure we have no collisions.
> [CI] Create branch in cascade pipeline for the html of a given build.

- Localize/loc/cs/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/cs/tools/mtouch/Errors.resx.lcl
- Localize/loc/de/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/de/tools/mtouch/Errors.resx.lcl
- Localize/loc/es/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/es/tools/mtouch/Errors.resx.lcl
- Localize/loc/fr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/fr/tools/mtouch/Errors.resx.lcl
- Localize/loc/it/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/it/tools/mtouch/Errors.resx.lcl
- Localize/loc/ja/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/ja/tools/mtouch/Errors.resx.lcl
- Localize/loc/ko/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/ko/tools/mtouch/Errors.resx.lcl
- Localize/loc/pl/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/pl/tools/mtouch/Errors.resx.lcl
- Localize/loc/pt-BR/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/pt-BR/tools/mtouch/Errors.resx.lcl
- Localize/loc/ru/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/ru/tools/mtouch/Errors.resx.lcl
- Localize/loc/tr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/tr/tools/mtouch/Errors.resx.lcl
- Localize/loc/zh-Hans/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/zh-Hans/tools/mtouch/Errors.resx.lcl
- Localize/loc/zh-Hant/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/zh-Hant/tools/mtouch/Errors.resx.lcl
- tools/devops/automation/templates/build/configure.yml
- tools/devops/automation/templates/build/stage.yml
These are the files from the Loc team that contain the translations for MSBuild and Mtouch.
> [Localization] Bring localization check-in from Localization branch

- Make.config
> [xcode12.5] [Make] Use stable for completeness.

- Localize/loc/cs/tools/mtouch/Errors.resx.lcl
- Localize/loc/de/tools/mtouch/Errors.resx.lcl
- Localize/loc/es/tools/mtouch/Errors.resx.lcl
- Localize/loc/it/tools/mtouch/Errors.resx.lcl
LEGO: Pull request from lego/hb_dca0a672-370a-4b3c-b55f-cd146e93faf9_20210520221323564 to Localization with localized lcls
> LEGO: Pull request from lego/hb_dca0a672-370a-4b3c-b55f-cd146e93faf9_20210520221323564 to Localization

- tools/devops/automation/templates/publish-html-result.yml
Step fwd to get the stativ page. We download all the artifacts from the
cascade pipeline. The artifacts are inherited thanks to the trigger.
Download, extract, print files to be removed.
PS: Yes, diff download, because everything in VSTS has to look the same but be different.
> [CI] Download all artifacts and show files to be removed.

- tools/mlaunch/Makefile
This makes us ship mlaunch in .NET again.
> [mlaunch] Fix conditional makefile logic.

- eng/README.md
* Specify that that GitHub PATs need SSO enabled to work.
* Add command example to create new subscription for preview release branches.
> [darc] Update README

- Localize/loc/cs/tools/mtouch/Errors.resx.lcl
- Localize/loc/de/tools/mtouch/Errors.resx.lcl
- Localize/loc/es/tools/mtouch/Errors.resx.lcl
- Localize/loc/it/tools/mtouch/Errors.resx.lcl
- Localize/loc/pl/tools/mtouch/Errors.resx.lcl
- Localize/loc/ru/tools/mtouch/Errors.resx.lcl
- Localize/loc/tr/tools/mtouch/Errors.resx.lcl
These changes were not yet brought over from Localization but came out before we created the github action to automatically bring them over.
> [Localization] Cherry Picking lcl files

- tools/devops/automation/templates/publish-html-result.yml
This should not happen since we should not be getting same url.
> [CI] Override if present.

- tools/devops/automation/templates/publish-html-result.yml
Should keep checkout small and try to be within 10 gb.
> [CI] Remove xml files since they are in vsdrops and empty dirs.

- .github/workflows/github-page-clean-up.yml
CI should have a way to test locally :/
> [Action] Typo and space :/

- src/avfoundation.cs
- tests/introspection/ApiSelectorTest.cs
Fixes https://github.com/xamarin/maccore/issues/2420.
> [AVFoundation/introspection] Fix availability attributes / introspection for watchOS 5.0. Fixes #xamarin/maccore@2420.

- .github/workflows/github-page-clean-up.yml
Add names, provide a way to launch it manually for testing.
> [Actions] Work with VSEng to fix the clean action.

- .github/workflows/github-page-clean-up.yml
following https://www.pinel.cc/blog/2019/11/02/private-github-actions
> [Actions] Tryo to use a magic token $

- src/CoreAnimation/CATransform3D.cs
by avoiding casting every value set to create the `Identity` field.
**Before**
```cil
IL_0000: ldsflda valuetype CoreAnimation.CATransform3D CoreAnimation.CATransform3D::Identity
IL_0005: initobj CoreAnimation.CATransform3D
IL_000b: ldsflda valuetype CoreAnimation.CATransform3D CoreAnimation.CATransform3D::Identity
IL_0010: ldc.r4 1
IL_0015: call valuetype System.nfloat System.nfloat::op_Implicit(float32)
IL_001a: stfld valuetype System.nfloat CoreAnimation.CATransform3D::m11
IL_001f: ldsflda valuetype CoreAnimation.CATransform3D CoreAnimation.CATransform3D::Identity
IL_0024: ldc.r4 1
IL_0029: call valuetype System.nfloat System.nfloat::op_Implicit(float32)
IL_002e: stfld valuetype System.nfloat CoreAnimation.CATransform3D::m22
IL_0033: ldsflda valuetype CoreAnimation.CATransform3D …
```
> [coreanimation] Reduce the size of `CATransform3D`

- tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/LocalizationStringTest.cs
> adding first test to test2

- tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/CompileEntitlementsTaskTests.cs
- tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/LocalizationStringTest.cs
> Automating localization gha test2

- tools/devops/automation/build-pipeline.yml
- tools/devops/automation/templates/build/build.yml
- tools/devops/automation/templates/build/sign-and-notarized.yml
Needs to be only merge when all device bots and mac bots have at least used provisionator to install the deps. If they fail, the PR is wrong.
> [CI] Unify the password across templates.

- src/UIKit/UIControl.cs
The `RemoveTarget` method already checked if `allTargets` was `null`,
even if it was not possible (might have been at some point in time)
It makes some apps, like the one we track for the minimal size, able
to eliminate a few more types (for both _dotnet_ and _legacy_)
```diff
--- a.cs	2021-06-08 17:41:00.000000000 -0400
+++ b.cs	2021-06-08 17:41:02.000000000 -0400
@@ -3216,21 +3216,9 @@
NSString.ReleaseNative(intPtr);
}
}
-	[Register]
-	internal class UIControlEventProxy : NSObject
-	{
-		[MethodImpl(8)]
-		[Export("BridgeSelector")]
-		public void Activated()
-		{
-			throw new NotSupportedException("Linked away");
-		}
-	}
[Register("UIControl", true)]
public class UIControl : UIView, INativeObject, IDisposable
{
-		private static ConditionalWeakTable<UIControl, …
```
> [uikit] More linker-friendly `UIControl`

- tools/devops/automation/scripts/GitHub.psm1
Example of what we are trying to fix: https://github.com/xamarin/xamarin-macios/pull/11861
> [CI] Do not add links to static page if we never got results.

- tools/devops/automation/templates/devices/build.yml
Reminder, variables are strings, cannot have another type while parameters do have types.
> [CI] Fix condition to start executing the device tests.

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/SmartCopyTaskBase.cs
The native 'stat' function is not identical between x64 and arm64:
* The x64 version is the 32-bit version of the function, and takes a 32-bit
version of the stat structure.
* The arm64 version is the 64-bit version of the function, and takes a 64-bit
version of the stat structure.
We used the 32-bit version of the stat structure everywhere, which went
horribly wrong on arm64, because the layout and size of the struct is quite
different (120 bytes vs 144 bytes). The actual result on arm64 was that the
call to stat would null out one of the parameters to the calling function, and
the C# code would throw an ArgumentNullException when the code tried to use
that argument, and you'd end up with this exception which didn't make any
sense at all when looking at the code:
error : …
> [msbuild] Fix P/Invoke to stat.

- tools/devops/automation/templates/publish-html-result.yml
> [d16-10] [CI] Ensure that we do not have data downloaded from other builds.

- Localize/loc/es/tools/mtouch/Errors.resx.lcl
- Localize/loc/fr/tools/mtouch/Errors.resx.lcl
- Localize/loc/it/tools/mtouch/Errors.resx.lcl
- Localize/loc/ko/tools/mtouch/Errors.resx.lcl
- Localize/loc/pt-BR/tools/mtouch/Errors.resx.lcl
- Localize/loc/ru/tools/mtouch/Errors.resx.lcl
- Localize/loc/zh-Hans/tools/mtouch/Errors.resx.lcl
- Localize/loc/zh-Hant/tools/mtouch/Errors.resx.lcl
LEGO: Pull request from lego/hb_dca0a672-370a-4b3c-b55f-cd146e93faf9_20210612221406006 to Localization with localized lcls
> LEGO: Pull request from lego/hb_dca0a672-370a-4b3c-b55f-cd146e93faf9_20210612221406006 to Localization

- Localize/loc/ja/tools/mtouch/Errors.resx.lcl
- Localize/loc/pl/tools/mtouch/Errors.resx.lcl
- Localize/loc/tr/tools/mtouch/Errors.resx.lcl
LEGO: Pull request from lego/hb_dca0a672-370a-4b3c-b55f-cd146e93faf9_20210613101318038 to Localization with localized lcls
> LEGO: Pull request from lego/hb_dca0a672-370a-4b3c-b55f-cd146e93faf9_20210613101318038 to Localization

- src/CloudKit/CKCompat.cs
- src/cloudkit.cs
Their usage can cause app store rejections.
> [cloudkit] Remove obsoleted properties

- src/arkit.cs
- tests/xtro-sharpie/iOS-ARKit.todo
Simple diff, all other enums are the same, just got moved to a diff header.
> [ARKit] Provide updates for Xcode13 beta1.

- src/CloudKit/CKCompat.cs
From copy/paste mistake in https://github.com/xamarin/xamarin-macios/pull/11909
but only found in the backport https://github.com/xamarin/xamarin-macios/pull/11920/files#r650981533
> [cloudkit] Fix obsolete message

- src/CloudKit/CKCompat.cs
From copy/paste mistake in https://github.com/xamarin/xamarin-macios/pull/11909
but only found in the backport https://github.com/xamarin/xamarin-macios/pull/11920/files#r650981533
Backport of #11923
> [d16-10] [cloudkit] Fix obsolete message

- src/ObjCRuntime/RuntimeOptions.cs
- tests/monotouch-test/System.Net.Http/MessageHandlers.cs
Also allow `SocketsHttpHandler` on dotnet
> [dotnet] Change default http handler to NSUrlSessionHandler

- tests/monotouch-test/Foundation/NSTimeZoneTest.cs
This reverts commit 5fdd4e2dec744e8741beb2edf9c3d20873107283.
> Revert "[tests][monotouch-test] Ignore NSTimeZoneTest / All_28300 on dotnet as it hangs"

- Make.config
- src/avfoundation.cs
- tests/introspection/iOS/iOSApiSelectorTest.cs
Fixes https://github.com/xamarin/maccore/issues/2454.
> Bump min watchOS simulator to 6.0.

- tools/devops/automation/build-pipeline.yml
Lets make my 1000 commits a typo fix!
> [CI] Fix typo

- Make.config
> Follow the instructions for hardcoding version numbers.

- tools/devops/automation/templates/build/configure.yml
I believe the Weekly PRs are not being produced due to yaml not evaluating inputs the way I originally thought. 
This change may allow us to create the weekly PR by setting the input value correctly.
Help from @mandel-macaque
> [Localization] Change the Input value

- src/Foundation/NSUrlSessionHandler.cs
> NSUrlSessionHandler got attributed to my brother somehow

- src/imagekit.cs
- tests/xtro-sharpie/macOS-ImageKit.todo
I couldn't decide on if these names should be shortened due to the parameters, so I just followed the Swift naming. Let me know if I should change these!
> [ImageKit] Updates for Xcode13 Beta 1-2

- src/appkit.cs
- src/uikit.cs
- src/xkit.cs
This PR might be easier to review commit-by-commit.
> [AppKit/UIKit] Share the implementation of some classes between AppKit and UIKit.

- src/Foundation/NSObject2.cs
- tools/mtouch/Errors.designer.cs
- tools/mtouch/Errors.resx
Fixes https://github.com/xamarin/xamarin-macios/issues/12112.
> [Foundation] Improve error reporting when we fail to instantiate a type. Fixes #12112.

- dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalyst/AppDelegate.cs
- dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalyst/MacCatalystApp1.csproj
- dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalyst/SceneDelegate.cs
- dotnet/Templates/Microsoft.iOS.Templates/ios/AppDelegate.cs
- dotnet/Templates/Microsoft.iOS.Templates/ios/SceneDelegate.cs
- dotnet/Templates/Microsoft.iOS.Templates/ios/iOSApp1.csproj
- dotnet/Templates/Microsoft.iOS.Templates/ioslib/iOSLib1.csproj
- dotnet/Templates/Microsoft.macOS.Templates/macos/macOSApp1.csproj
- dotnet/Templates/Microsoft.tvOS.Templates/tvos/AppDelegate.cs
- dotnet/Templates/Microsoft.tvOS.Templates/tvos/tvOSApp1.csproj
And fix any warnings that came up.
> [dotnet] Enable nullability in template projects.

- src/CoreBluetooth/Enums.cs
- src/corebluetooth.cs
- tests/xtro-sharpie/MacCatalyst-CoreBluetooth.todo
- tests/xtro-sharpie/iOS-CoreBluetooth.todo
- tests/xtro-sharpie/macOS-CoreBluetooth.ignore
- tests/xtro-sharpie/macOS-CoreBluetooth.todo
- tests/xtro-sharpie/tvOS-CoreBluetooth.todo
- tests/xtro-sharpie/watchOS-CoreBluetooth.todo
> [release/6.0.1xx-preview7] [CoreBluetooth] Add Xcode 13 beta 3 support.

- tools/devops/automation/scripts/bash/clean-bot.sh
Clean bots since we are running out of space.
> [CI] Update xcode versions to remove.

- tests/xtro-sharpie/xtro-sanity/Sanitizer.cs
Now with support for auto-sanitizing todo files.
> [xtro] Improve the auto-sanitizer.

- tests/xtro-sharpie/Makefile
- tests/xtro-sharpie/u2todo/u2todo.cs
@spouliot  @rolfbjarne I don't know how I feel abut this. On one hand, is easy to just do sort -o filename filename. On the other hand I could have done everything in c#.
> [xtro] Append the lines and then sort them to get everything grouped better.

- src/btouch.cs
Waiting on builds.. and I saw this and found it annoying.
> [btouch] Remove some nullability warnings. fixes #12260

- tools/devops/automation/templates/build/build.yml
> [release/6.0.1xx-preview7] [CI] If the xcode path is not present, use the default.

- src/corelocation.cs
- tests/xtro-sharpie/MacCatalyst-CoreLocation.todo
- tests/xtro-sharpie/iOS-CoreLocation.todo
- tests/xtro-sharpie/macOS-CoreLocation.todo
- tests/xtro-sharpie/tvOS-CoreLocation.todo
- tests/xtro-sharpie/watchOS-CoreLocation.todo
> [release/6.0.1xx-preview7] [CoreLocation] Add support for Xcode 13 beta 4.

- dotnet/Microsoft.iOS.Windows.Sdk/targets/Microsoft.iOS.Windows.Sdk.props
- dotnet/targets/Xamarin.Shared.Sdk.props
- dotnet/targets/Xamarin.Shared.Sdk.targets
- msbuild/Messaging/Xamarin.Messaging.Build/TaskRunner.cs
> [release/6.0.1xx-preview7] [net6] Fixes build issues from VS for Preview 7

- src/quicklookthumbnailing.cs
- tests/xtro-sharpie/MacCatalyst-QuickLookThumbnailing.todo
- tests/xtro-sharpie/iOS-QuickLookThumbnailing.todo
- tests/xtro-sharpie/macOS-QuickLookThumbnailing.todo
> [QuickLookThumbnailing] Update bindings for Xcode 13.0 beta 1

- tests/framework-test/iOS/AppDelegate.cs
- tests/interdependent-binding-projects/Main.cs
- tests/introspection/iOS/AppDelegate.cs
- tests/linker/ios/dont link/AppDelegate.cs
- tests/linker/ios/link all/AppDelegate.cs
- tests/linker/ios/link sdk/AppDelegate.cs
- tests/monotouch-test/AppDelegate.cs
- tests/xcframework-test/iOS/AppDelegate.cs
Ref: https://github.com/xamarin/maccore/issues/2414
> [tests] Add debug spew to track down #xamarin/maccore@2414.

- src/NearbyInteraction/Enums.cs
- src/NearbyInteraction/NINearbyObject.cs
- src/nearbyinteraction.cs
Original author of the file did not follow the style of the project. Moving indentation to spaces. No code changes (use --ignore-space-change to check if needed).
> [NearbyInteraction] Convert spaces to tabs.

- tools/common/PathUtils.cs
- tools/mmp/mmp.csproj
> Fix lstat P/Invoke on arm64

- tests/xharness/Jenkins/Jenkins.cs
We keep adding more and more test cases...
> [xharness] Bump timeout for .NET tests again.

- tests/xharness/TestProject.cs
> [xharness] Remove debug lock.

- tests/xharness/Jenkins/Reports/HtmlReportWriter.cs
At startup, we load old test results that may exist on disk. However, this may
take a while, especially since the disk is usually quite busy already with
everything else we do at startup, so don't wait for this to finish before
displaying the UI.
> [xharness] Move loading old test results into the background.

- tests/introspection/ApiProtocolTest.cs
- tests/introspection/iOS/iOSApiProtocolTest.cs
so they can be ignored on macOS (12+) too
> [tests][intro] Move protocol check for QLPreviewReply* to base class

- dotnet/targets/Xamarin.Shared.Sdk.targets
- msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DetectSdkLocationCoreTaskBase.cs
- msbuild/Xamarin.Shared/Xamarin.Shared.targets
- msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
> Remove IsXcode8

- tests/common/mac/MacMain.fs
MonoTouch.NUnit.UI.MacRunner.MainAsync will try to invoke things on the main
thread, and at the same time execute a runloop, and if the runloop isn't
executing on the main thread, we end up with a deadlock, where we keep waiting
on the main thread to process stuff enqueued by the background thread, while
the main thread is waiting for the background thread to finish.
Solve this by fixing the F# code to call
MonoTouch.NUnit.UI.MacRunner.MainAsync on the main thread.
> [tests] Fix (a)synchronous F# code.

- tests/linker/ios/link sdk/LinkSdkRegressionTest.cs
Hopefully fixes https://github.com/xamarin/xamarin-macios/issues/12640.
> [tests] Relax a few special folder checks for tvOS even more. Fixes #12640.

- src/AVFoundation/AVTypes.cs
> [xcode13-ios] [Netcore] Remove warning from extra using.

- dotnet/targets/Xamarin.Shared.Sdk.targets
- tests/common/BinLog.cs
- tests/dotnet/UnitTests/IncrementalBuildTest.cs
- tests/dotnet/UnitTests/TestBaseClass.cs
This caused rebuilds to crash upon launch sometimes.
Backport of #12794
> [release/6.0.1xx-preview9] [dotnet] Fix an issue where we wouldn't re-link if some files changed.

- Localize/loc/cs/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/de/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/es/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/fr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/fr/tools/mtouch/Errors.resx.lcl
- Localize/loc/it/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/ja/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/ja/tools/mtouch/Errors.resx.lcl
- Localize/loc/ko/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/ko/tools/mtouch/Errors.resx.lcl
- Localize/loc/pl/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/pt-BR/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/ru/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/ru/tools/mtouch/Errors.resx.lcl
- Localize/loc/tr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/zh-Hans/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/zh-Hant/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
- Localize/loc/zh-Hant/tools/mtouch/Errors.resx.lcl
LEGO: Pull request from lego/hb_dca0a672-370a-4b3c-b55f-cd146e93faf9_20210927170446737 to Localization with localized lcls
> LEGO: Pull request from lego/hb_dca0a672-370a-4b3c-b55f-cd146e93faf9_20210927170446737 to Localization

- src/CoreFoundation/CFString.cs
- src/Foundation/NSObject2.cs
- src/GLKit/Defs.cs
- src/GameController/GCExtendedGamepadSnapshot.cs
- src/HealthKit/HKAppleWalkingSteadiness.cs
- tests/cecil-tests/MarshalAsTest.cs
- tests/monotouch-test/CoreFoundation/StringTest.cs
Added the marshaling attr and a test to ensure it is ok.
fixes: https://github.com/xamarin/maccore/issues/2519
> [Tests] Fix cecil tests ensuring that missing MarshalAs is present.

- src/CoreFoundation/CFString.cs
- src/Foundation/NSObject2.cs
- src/GLKit/Defs.cs
- src/GameController/GCExtendedGamepadSnapshot.cs
- src/HealthKit/HKAppleWalkingSteadiness.cs
- tests/cecil-tests/MarshalAsTest.cs
- tests/monotouch-test/CoreFoundation/StringTest.cs
Added the marshaling attr and a test to ensure it is ok.
fixes: https://github.com/xamarin/maccore/issues/2519
Backport of #12853
> [xcode13-ios] [Tests] Fix cecil tests ensuring that missing MarshalAs is present.

- .github/workflows/ping.yml
> [Action] Fix branch name.

- tests/monotouch-test/System.Net.Http/MessageHandlers.cs
Ref: https://github.com/xamarin/maccore/issues/2304
> [tests] Add more special cases for random network errors on CI.

- eng/common/SetupNugetSources.ps1
- eng/common/SetupNugetSources.sh
- eng/common/pipeline-logging-functions.ps1
- eng/common/pipeline-logging-functions.sh
- eng/common/tools.ps1
- eng/common/tools.sh
This in the future will be update by maestro + arcade.
> [CI] Manually add certain arcade files.

- tools/devops/automation/templates/build/stage.yml
Disable the step based on the repo id.
> [CI] Do not publish private pkgs.

- tools/devops/automation/build-pipeline.yml
- tools/devops/automation/templates/variables.yml
> [CI] Add a conditional variable template.

- tools/devops/automation/templates/release/publish-nugets.yml
Simplify the check, fixes issue with the CI.
> [CI] Fix yaml by using else.

- tools/devops/automation/templates/release/publish-nugets.yml
Not all bots are setup to support ${{ else }}:
> [CI] Not all bots support the new syntax.

- src/AudioToolbox/SystemSound.cs
In .NET 6 we can use the [UnmanagedCallersOnly] attribute to mark functions
that are called from native code (instead of the [MonoPInvokeCallback]
attribute). It turns out this is a rather major refactoring (in particular for
blocks), so start by doing it for just a single function, to make sure using
[UnmanagedCallersOnly] at least works somewhere.
Ref: https://github.com/xamarin/xamarin-macios/issues/10470
> [.NET/AudioToolbox] Make AudioServicesAddSystemSoundCompletion take an unmanaged function pointer instead of delegate. Very partial fix for #10470.

- src/corelocation.cs
- tests/xtro-sharpie/MacCatalyst-CoreLocation.ignore
- tests/xtro-sharpie/MacCatalyst-CoreLocation.todo
Move .todo to .ignore to prevent breaking changes
> [CoreLocation] Updates for Catalyst

- tests/introspection/Mac/MacApiSelectorTest.cs
> [xcode13.1] [AVFoundation] Fix intro issues in monterey.

- src/appkit.cs
- tests/xtro-sharpie/macOS-AppKit.ignore
> [xcode13.1] [AppKit] Fix intro tests on monterey.

- src/PdfKit/Enums.cs
- tests/xtro-sharpie/MacCatalyst-PDFKit.todo
- tests/xtro-sharpie/iOS-PDFKit.todo
- tests/xtro-sharpie/macOS-PDFKit.todo
> [xcode13.1] [PdfKit] Add missing enum.

- src/quicklook.cs
- tests/introspection/iOS/iOSApiProtocolTest.cs
- tests/xtro-sharpie/MacCatalyst-QuickLook.ignore
- tests/xtro-sharpie/iOS-QuickLook.todo
> [xcode13.1] [QuickLook] Add missing selectors for Xcode 13.1

- src/CoreText/CTTypesetter.cs
> [CTTypeSetter] Subclass NativeObject + numerous other code updates

- src/CoreText/CTRun.cs
> [CTRun] Subclass NativeObject + numerous other code updates

- src/CoreGraphics/CGPDFScanner.cs
> [CGPDFScanner] Subclass NativeObject + numerous other code updates

- tests/monotouch-test/Foundation/BlockOperationTest.cs
- tests/monotouch-test/Foundation/CachedUrlResponseTest.cs
- tests/monotouch-test/Foundation/CoderTest.cs
- tests/monotouch-test/Foundation/DateFormatterTest.cs
- tests/monotouch-test/Foundation/DateTest.cs
- tests/monotouch-test/Foundation/DecimalNumberTest.cs
- tests/monotouch-test/Foundation/DecimalTest.cs
- tests/monotouch-test/Foundation/EncodingDetectionOptionsTest.cs
- tests/monotouch-test/Foundation/NSCharacterSetTest.cs
- tests/monotouch-test/Foundation/NSDateComponentsTest.cs
- tests/monotouch-test/Foundation/NSLinguisticAnalysisTest.cs
- tests/monotouch-test/Foundation/NSLocaleTest.cs
- tests/monotouch-test/Foundation/NSStreamTest.cs
- tests/monotouch-test/Foundation/NSStringTest.cs
- tests/monotouch-test/Foundation/NSUrlSessionConfiguration.cs
- tests/monotouch-test/Foundation/ProtocolAttributeTest.cs
- tests/monotouch-test/Foundation/RegularExpressionTest.cs
- tests/monotouch-test/Foundation/ThreadTest.cs
- tests/monotouch-test/Foundation/TimerTest.cs
- tests/monotouch-test/Foundation/UbiquitousKeyValueStoreTest.cs
- tests/monotouch-test/Foundation/UrlConnectionTest.cs
- tests/monotouch-test/Foundation/UrlCredentialTest.cs
- tests/monotouch-test/Foundation/UrlSessionTaskTransactionMetricsTest.cs
OCD branch. No humans were used for this PR, it was automated.
> [Tests] Remove not needed usings in the Foundation tests.

- tests/monotouch-test/AudioUnit/AudioUnitTest.cs
- tests/monotouch-test/AudioUnit/ExtAudioFileTest.cs
OCD branch. No humans were used for this PR, it was automated.
> [Tests] Remove not needed usings in the AudioUnit tests.

- tests/monotouch-test/AudioToolbox/AudioBalanceFadeTest.cs
- tests/monotouch-test/AudioToolbox/AudioChannelLayoutTest.cs
- tests/monotouch-test/AudioToolbox/AudioFileGlobalInfoTest.cs
- tests/monotouch-test/AudioToolbox/AudioFileStreamTest.cs
- tests/monotouch-test/AudioToolbox/AudioFileTest.cs
- tests/monotouch-test/AudioToolbox/AudioFormatTest.cs
- tests/monotouch-test/AudioToolbox/AudioQueueTest.cs
- tests/monotouch-test/AudioToolbox/AudioSessionTest.cs
- tests/monotouch-test/AudioToolbox/AudioStreamBasicDescriptionTest.cs
- tests/monotouch-test/AudioToolbox/FourCCTest.cs
- tests/monotouch-test/AudioToolbox/SoundBankTest.cs
- tests/monotouch-test/AudioToolbox/SystemSoundTest.cs
OCD branch. No humans were used for this PR, it was automated.
> [Tests] Remove not needed usings in the AudioToolbox tests.

- tests/monotouch-test/Network/NWBrowserDescriptorTest.cs
- tests/monotouch-test/Network/NWBrowserTest.cs
- tests/monotouch-test/Network/NWConnectionGroupTest.cs
- tests/monotouch-test/Network/NWConnectionTest.cs
- tests/monotouch-test/Network/NWEstablishmentReportTest.cs
- tests/monotouch-test/Network/NWFramerMessageTest.cs
- tests/monotouch-test/Network/NWIPProtocolMetadataTest.cs
- tests/monotouch-test/Network/NWListenerTest.cs
- tests/monotouch-test/Network/NWMulticastGroupTest.cs
- tests/monotouch-test/Network/NWParametersTest.cs
- tests/monotouch-test/Network/NWPathMonitorTest.cs
- tests/monotouch-test/Network/NWPathTest.cs
- tests/monotouch-test/Network/NWProtocolDefinitionTest.cs
- tests/monotouch-test/Network/NWProtocolIPOptionsTest.cs
- tests/monotouch-test/Network/NWProtocolMetadataTest.cs
- tests/monotouch-test/Network/NWProtocolStackTest.cs
- tests/monotouch-test/Network/NWProtocolTcpOptionsTest.cs
- tests/monotouch-test/Network/NWProtocolTlsOptionsTest.cs
- tests/monotouch-test/Network/NWProtocolUdpOptionsTest.cs
- tests/monotouch-test/Network/NWTxtRecordTest.cs
- tests/monotouch-test/Network/NWWebSocketMetadataTest.cs
- tests/monotouch-test/Network/NWWebSocketOptionsTest.cs
OCD branch. No humans were used for this PR, it was automated.
> [Tests] Remove not needed usings in the Network tests.

- src/AudioToolbox/AudioFile.cs
> [AudioFile] Enable nullability + a few other code updates

- tests/xtro-sharpie/macOS-AppKit.ignore
I missed a failure in https://github.com/xamarin/xamarin-macios/pull/13244
> [Xtro] Fix xtro after a bad commit.

- src/AudioToolbox/MusicPlayer.cs
> [MusicPlayer] Enable nullability + a few other code updates

- src/CoreAnimation/CAFrameRateRange.cs
- src/coreanimation.cs
- src/frameworks.sources
- tests/monotouch-test/CoreAnimation/CAFrameRateRangeTest.cs
- tests/xtro-sharpie/MacCatalyst-CoreAnimation.todo
- tests/xtro-sharpie/iOS-CoreAnimation.todo
- tests/xtro-sharpie/macOS-CoreAnimation.todo
- tests/xtro-sharpie/tvOS-CoreAnimation.todo
> [xcode13.1] [CoreAnimation] Add support for Xcode 13.1 rc.

- tests/xtro-sharpie/macOS-AppKit.ignore
I missed a failure in https://github.com/xamarin/xamarin-macios/pull/13244 
Backport of #13271
> [xcode13.1] [Xtro] Fix xtro after a bad commit.

- src/AudioToolbox/MusicTrack.cs
* Rename the public '_MidiData' type to 'MidiData' for .NET.
* Remove some dead code.
> [MusicTrack] Enable nullability + a few other code updates

- src/AudioToolbox/MusicSequence.cs
> [MusicSequence] Enable nullability + a few other code updates

- src/SystemConfiguration/NetworkReachability.cs
Ref https://github.com/xamarin/xamarin-macios/issues/10470.
> [.NET/SystemConfiguration] Use [UnmanagedCallersOnly] instead of [MonoPInvokeCallback] for the managed callbacks called from native code.

- src/btouch.cs
Hopefully fixes https://github.com/xamarin/maccore/issues/2463.
> [generator] Dispose of the universe when done with it.

- tools/devops/automation/build-pipeline.yml
Following the comments in https://github.com/xamarin/xamarin-macios/pull/13259
> [CI] Use images for older macOS.

- src/accounts.cs
- src/addressbookui.cs
- src/appkit.cs
- src/assetslibrary.cs
- src/avfoundation.cs
- src/coredata.cs
- src/corelocation.cs
- src/coremotion.cs
- src/corewlan.cs
- src/eventkit.cs
- src/foundation.cs
- src/gamekit.cs
- src/healthkit.cs
- src/homekit.cs
- src/intents.cs
- src/localauthentication.cs
- src/mapkit.cs
- src/mediaplayer.cs
- src/metal.cs
- src/passkit.cs
- src/photos.cs
- src/replaykit.cs
- src/scenekit.cs
- src/security.cs
- src/storekit.cs
- src/twitter.cs
- src/uikit.cs
- src/webkit.cs
- src/wkwebkit.cs
- src/xkit.cs
This will allow us to remove the old-style attributes from .NET (since they won't be used in shared code).
> [src] Change all usages of old-style availability attributes to new-style availability attributes.

- tools/devops/automation/build-pipeline.yml
> [CI] Add display names so that we understand the ui better.

- tools/devops/automation/templates/devices/build.yml
- tools/devops/automation/templates/devices/run-tests.yml
Xharness needs fixes and this PR is just focusing on the CI part. Xharness fix will come later.
> [CI] Renable the steps to run the device tests

- tests/xharness/xharness.csproj
To get this fix: https://github.com/dotnet/xharness/commit/769755cc9859cb5423ca261deb1f8f2e17dd2d41
> Bump xharness.

- tests/xtro-sharpie/Log.cs
- tests/xtro-sharpie/Makefile
- tests/xtro-sharpie/Program.cs
- tests/xtro-sharpie/Runner.cs
- tests/xtro-sharpie/xtro-sharpie.csproj
This makes it possible to have a different output directory for .NET assemblies.
> [xtro-sharpie] Add support for specifying the output directory.

- src/AddressBook/ABMultiValue.cs
- src/AddressBook/ABPerson.cs
- src/CoreAnimation/CADefs.cs
- src/CoreFoundation/CFArray.cs
- src/CoreFoundation/CFString.cs
- src/CoreImage/CIImage.cs
- src/CoreText/Adapter.cs
- src/CoreText/CTFont.cs
- src/CoreText/CTParagraphStyle.cs
- src/CoreText/CTStringAttributes.cs
- src/Foundation/DictionaryContainer.cs
- src/Foundation/NSArray.cs
- src/Security/Certificate.cs
- src/Security/SslContext.cs
- src/UIKit/UIAppearance.cs
- src/UIKit/UIApplication.cs
- tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
The main part is the changes to CFArray and NSArray, the rest are just fallout
from those changes.
> [src] Adjust numerous APIs to take/return NativeHandle instead of IntPtr for .NET.

- tests/xharness/MacTestProject.cs
- tests/xharness/TestProject.cs
- tests/xharness/TestProjectExtensions.cs
- tests/xharness/iOSTestProject.cs
Also simplify some code elsewhere to make that easier.
> [xharness] Add nullability to the TestProject class.

- tools/devops/automation/build-pipeline.yml
Remove mohave tests because they are being removed by VSEng.
> [CI] Remove all macOS Mojave.

- tests/monotouch-test/ModelIO/MDLLight.cs
- tests/monotouch-test/ModelIO/MDLMaterialProperty.cs
- tests/monotouch-test/ModelIO/MDLMesh.cs
- tests/monotouch-test/ModelIO/MDLNoiseTexture.cs
- tests/monotouch-test/ModelIO/MDLObject.cs
- tests/monotouch-test/ModelIO/MDLTexture.cs
- tests/monotouch-test/ModelIO/MDLTransform.cs
- tests/monotouch-test/ModelIO/MDLVertexAttribute.cs
- tests/monotouch-test/SpriteKit/SK3DNodeTest.cs
- tests/monotouch-test/SpriteKit/UniformTest.cs
We're not executing anywhere where this bug is present anymore.
> [tests] Remove workaround for an objc_msgSend bug that's been fixed for a while.

- tools/devops/automation/build-pipeline.yml
The UI uses the order in which the parmaeters are found in the file,
which makes it look ugly because it adds a text bos ni between all
options.
> [CI] Rearrange the parameters so that we have all booleans grouped.

- src/Foundation/NSUrlSessionHandler.cs
- src/generator.cs
- tests/generator/ErrorTests.cs
- tests/generator/bi1042.cs
Fix reporting BI1042 to include the type + property that triggered the error +
add a test.
> [generator] Fix reporting BI1042.

- tools/devops/automation/templates/build/build.yml
- tools/devops/automation/templates/common/mac-agent-logs.yml
Allow to sport the system logs in an agent, this way we can debug crashes, perm and other issues.
> [CI] Allow to retrieve the logs of the agent.

- src/ObjCRuntime/DisposableObject.cs
- tests/monotouch-test/AudioToolbox/AudioConverterTest.cs
- tests/monotouch-test/ObjCRuntime/DisposableObjectTest.cs
Ops...
Also add tests to avoid more oopses.
Fixes https://github.com/xamarin/xamarin-macios/issues/13646.
> [ObjCRuntime] Fix the DisposableObject.Owns property to return the correct value. Fixes #13646.

- src/ARKit/ARSkeleton.cs
This one is admitting a bit silly, as we're swapping the order. But let's stay consistent with everything else I'm going to convert.
> [NET 6 Attribute Conversion] ARKit

- tools/devops/automation/templates/common/mac-agent-logs.yml
> [d17-1] [CI] Upload the agent logs as an artifact.

- dotnet/Workloads/SignList.xml
Fixes sign verification bugs: [#1460286](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1460286), [#1460285](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1460285), [#1460502](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1460502), [#1460503](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1460503)
Backport of #13688
> [release/6.0.2xx-preview12] Include Broker satellite assemblies to the sign list

- tools/devops/automation/scripts/GitHub.psm1
* Function names are {Verb}-{Action}
* Params start with a uppercase
* Function does not need to be exported, it is internal to the module.
> [CI] Clean the WriteDiff function to follow the pwsh style.

- tools/devops/automation/templates/build/build.yml
- tools/devops/automation/templates/mac/build.yml
This is weird bug in the agent code.
> [CI]  Invert if to workaround a bad variable expansion.

- dotnet/Workloads/SignList.xml
Fixes sign verification bugs: [#1460286](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1460286), [#1460285](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1460285), [#1460502](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1460502), [#1460503](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1460503)
> Include Broker satellite assemblies to the sign list

- tools/devops/automation/scripts/GitHub.psm1
Moving towards a skip for the device tests.
> [CI] Refactor the artifacts parsing.

- src/AVKit/Enums.cs
Done with `./scripts/convert.sh AVKit`. No manual corrections and no fixes outside required using.
> [NET 6 Attribute Conversion] AVKit

- tools/devops/automation/scripts/GitHub.psm1
> [CI] Add missing warning and list element.

- tools/devops/automation/scripts/GitHub.psm1
- tools/devops/automation/templates/common/publish-html.yml
Lets not add the api diff an other comments on mobile devices and mac devices.
> [CI] Do not add not needed data in the device test comments.

- src/ScriptingBridge/SBApplication.cs
- src/scriptingbridge.cs
- tests/monotouch-test/ScriptingBridge/SBApplicationTest.cs
- tests/xtro-sharpie/api-annotations-dotnet/macOS-ScriptingBridge.ignore
* Improve the API for both legacy Xamarin and .NET.
* Obsolete the old API in legacy Xamarin and point to the new API.
* Remove the old API in .NET.
* Add nullability.
> [ScriptingBridge] Improve API and add nullability.

- src/SceneKit/SCNCompat.cs
- src/SceneKit/SCNNode.cs
- src/SceneKit/SCNPhysicsShape.cs
- src/scenekit.cs
- tests/monotouch-test/SceneKit/ActionTest.cs
This means removing obsolete/deprecated methods.
> [SceneKit] Adopt XAMCORE_4_0 changes in .NET.

- msbuild/Xamarin.MacDev.Tasks/Tasks/FilterStaticFrameworks.cs
The FilterStaticFrameworks task takes a list of frameworks to process, but the
files actually needed by the task are inside those frameworks, which means we
have to tell XVS that those have to be copied to the Mac for the build as well.
Fixes https://github.com/xamarin/xamarin-macios/issues/13804.
> [msbuild] Copy all the files in a framework to the Mac for the FilterStaticFrameworks task. Fixes #13804.

- tools/devops/automation/templates/build/build.yml
- tools/devops/automation/templates/build/stage.yml
If the lab has good capacity it reduces the PR build time by 10%. It is better reviewed with a good diff tool since most of the code edits have been ifs with an indentation increase.
> [CI] Parallel api diff

- src/UIKit/Compat.cs
- src/UIKit/NSLayoutManager.cs
- src/UIKit/UIAccessibility.cs
- src/UIKit/UIActionSheet.cs
- src/UIKit/UIEnums.cs
- src/UIKit/UIImagePickerController.cs
- src/UIKit/UITraitCollection.cs
- src/UIKit/UIViewController.cs
- src/UIKit/UIWindow.cs
- src/uikit.cs
- tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-UIKit.todo
- tests/xtro-sharpie/api-annotations-dotnet/iOS-UIKit.ignore
- tests/xtro-sharpie/api-annotations-dotnet/tvOS-UIKit.ignore
This mostly involves removing obsolete/deprecated API.
> [UIKit] Adopt XAMCORE_4_0 changes in .NET.

- tools/devops/automation/templates/build/build.yml
- tools/devops/automation/templates/common/setup.yml
- tools/devops/automation/templates/devices/build.yml
Same code is used in both, unify it to make things cleaner.
> [CI] Unify all the setup steps in a template.

- tools/devops/automation/templates/build/upload-azure.yml
Add a loop for each of the products, better and will simplify the work for the SBOM.
> [CI] Improve the upload script to help with SBOM

- tools/devops/automation/templates/build/download-artifacts.yml
- tools/devops/automation/templates/build/publish-html.yml
- tools/devops/automation/templates/build/stage.yml
- tools/devops/automation/templates/build/upload-vsdrops.yml
Bonus points for finding a broken scape chars in paths (thanks windows paths) and a typo.
> [CI] Fix a broken CI when we skip the api diff.

- src/CoreMotion/CMDeviceMotion.cs
- src/CoreMotion/CMMagnetometer.cs
Trivial, but to match the ordering of the rest.
> [NET 6 Attribute Conversion] CoreMotion

- eng/Version.Details.xml
- eng/Versions.props
* https://github.com/dotnet/runtime [4f567e5...6371525](https://github.com/dotnet/runtime/compare/4f567e5ffa4bad5d2cbb5e82470f18534ee02c9f...63715256cc94963d608ef3d683d2529332c5140c)
Generated using https://github.com/spouliot/dotnet-tools/tree/master/changelog
> Bump to dotnet/runtime@6371525 6.0.2-mauipre.1.22074.5

- src/CarPlay/CPCompat.cs
The whole file is already under `!NET`
> [carplay] Remove unreachable code inside CPCompat.cs

- dotnet/BreakingChanges.md
- src/ObjCRuntime/Runtime.cs
and add it to the `BreakingChanges.md` document
> [net][objcruntime] Remove `UseAutoreleasePoolInThreadPool` in net profile

- src/MLCompute/MLHelpers.cs
This one is trivial reordering, but keeping it to match the formatting of other frameworks.
> [NET 6 Attribute Conversion] MlCompute

- src/MediaAccessibility/MAEnums.cs
- src/MediaAccessibility/MAImageCaptioning.cs
- src/MediaAccessibility/MediaAccessibility.cs
Trivial reorder but landing to keep formatting consistent.
> [NET 6 Attribute Conversion] MediaAccessibility

- src/foundation.cs
- tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.ignore
This is just removing obsolete API.
> [Foundation] Adopt more XAMCORE_4_0 changes in .NET.

- src/XKit/XKitCompat.cs
This just removes obsolete API.
> [XKit] Adopt XAMCORE_4_0 changes in .NET.

- src/appkit.cs
- src/xkit.cs
One of them is empty anyway.
Also update the availability attribute for Mac Catalyst.
> [AppKit] Unify two partial NSLayoutManager declarations.

- src/ObjCRuntime/Runtime.CoreCLR.cs
- src/ObjCRuntime/Runtime.cs
We have it, let's use it everywhere we can!
> [objcruntime] Use `AllocGCHandle` helper everywhere

- src/SceneKit/SCNMatrix4.cs
This entire file is already inside a !NET condition, so no need to have
additional conditions inside the file.
> [SceneKit] Remove dead code from SCNMatrix4.cs.

- dotnet/targets/Xamarin.Shared.Sdk.targets
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/InstallNameToolTaskBase.cs
- msbuild/Xamarin.MacDev.Tasks/Tasks/InstallNameTool.cs
- src/ObjCRuntime/ErrorHelper.cs
- tests/dotnet/BundleStructure/shared.csproj
- tests/dotnet/UnitTests/BundleStructureTest.cs
- tests/dotnet/UnitTests/DotNetUnitTests.csproj
- tests/test-libraries/libraries/Makefile
- tools/common/MachO.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/13999.
Backport of #14147
> [release/6.0.2xx-preview13] [dotnet/msbuild] Run install_name_tool to fix the id for dylibs. Fixes #13999.

- dotnet/targets/Xamarin.Shared.Sdk.targets
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/InstallNameToolTaskBase.cs
- msbuild/Xamarin.MacDev.Tasks/Tasks/InstallNameTool.cs
- src/ObjCRuntime/ErrorHelper.cs
- tests/dotnet/BundleStructure/shared.csproj
- tests/dotnet/UnitTests/BundleStructureTest.cs
- tests/dotnet/UnitTests/DotNetUnitTests.csproj
- tests/test-libraries/libraries/Makefile
- tools/common/MachO.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/13999.
> [dotnet/msbuild] Run install_name_tool to fix the id for dylibs. Fixes #13999.

- tools/devops/automation/templates/build/build-nugets.yml
- tools/devops/automation/templates/build/build.yml
> [release/6.0.2xx-preview13] [CI] Allow several builds to upload binlogs and do not fail.

- src/ObjCRuntime/ErrorHelper.cs
Simplified code and reduced visibility.
> [objcruntime] Small simplification of `ErrorHelper.CollectExceptions`

- src/AddressBook/ABEnums.cs
- src/AudioToolbox/AudioSessions.cs
- src/GameController/Enums.cs
- src/GameKit/GameKit.cs
* Remove .NET availability attributes for files that are processed by the generator.
* Make ABAddressBookError and ABPersonImageFormat non-native in .NET.
* Remove GKPeerPickerConnectionType from tvOS on .NET.
> [src] Remove .NET availability attributes for files that are processed by the generator and a few other misc changes.

- src/CoreGraphics/CGPDFOperatorTable.cs
Remove the CGPDFOperatorTable.SetCallback overload that takes a normal managed
delegate, because on platforms that are AOT'ed, this delegate must point to a
static function with the MonoPInvokeCallback attribute, and if you don't
follow this requirement, you'll either get an exception at runtime (which is
not very nice to the app developer) or make the AOT compiler crash (which is a
completely different level of not being nice to developers).
In .NET, we already have an overload that takes an unmanaged function pointer,
where these requirements are enforced by the C# compiler, so just use that
instead.
> [CoreGraphics] Remove a CGPDFOperatorTable.SetCallback overload in .NET.

- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CreateBindingResourcePackageBase.cs
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/MergeAppBundlesTaskBase.cs
- msbuild/Xamarin.MacDev.Tasks.Core/Tasks/XamarinTask.cs
- tools/common/FileCopier.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/12422.
Fixes https://github.com/xamarin/xamarin-macios/issues/13697.
Fixes https://github.com/xamarin/xamarin-macios/issues/14157.
> [msbuild] Implement proper MSBuild logging in FileCopier.

- src/WebKit/Enums.cs
- src/frameworks.sources
This also allows us to remove the .NET-style availability attributes, because
the generator will generate them.
> [WebKit] Make the enums api definitions.

- Make.config
- Make.versions
_Only merge right after we branch for preview 14._
> Bump .NET in main to RC 1

- src/ClockKit/CLKComplication.cs
- src/ClockKit/CLKEnums.cs
I am adding nullable enable to all manual files that are not "API_SOURCES" in src/frameworks.sources and making the required nullability changes
> [clockkit] Add nullability to (generated and manual) bindings

- src/CarPlay/CPCompat.cs
- src/CarPlay/CPNavigationAlert.cs
I am adding nullable enable to all manual files that are not "API_SOURCES" in src/frameworks.sources and making the required nullability changes
> [carplay] Add nullability to (generated and manual) bindings

- src/PassKit/PKEnums.cs
> [PassKit] Fix wrong enum values on PKPaymentButtonType

- src/PassKit/PKEnums.cs
Fixes: AB#1463538
Backport of #14301
> [release/6.0.2xx-preview14] [PassKit] Fix wrong enum values on PKPaymentButtonType

- tools/devops/automation/templates/build/upload-vsdrops.yml
> [release/6.0.2xx-preview14] [CI] Do not fail a build if we cannot upload to vsdrops.

- tests/generator/BGenTests.cs
- tests/generator/tests/csharp10syntax.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/13837.
> [tests] Add test to verify that the generator can compile C# 10+ code. Fixes #13837.

- Make.config
- builds/Makefile
- dotnet/Makefile
- msbuild/Xamarin.HotRestart.PreBuilt/Makefile
- src/Makefile.generator
- tests/Makefile
- tests/common/Configuration.cs
- tests/common/DotNet.cs
- tests/common/TestProjects/ComplexAssembly/Makefile
- tests/common/shared-dotnet.mk
- tests/dotnet/Makefile
- tests/dotnet/MyCatalystApp/Makefile
- tests/dotnet/MyCocoaApp/Makefile
- tests/dotnet/MySingleView/Makefile
- tests/dotnet/MyTVApp/Makefile
- tests/dotnet/UnitTests/Makefile
- tests/linker/ios/dont link/dotnet/iOS/Makefile
- tests/linker/ios/link all/dotnet/iOS/Makefile
- tests/linker/ios/link sdk/dotnet/iOS/Makefile
- tests/monotouch-test/dotnet/macOS/Makefile
- tests/perftest/Makefile
- tests/test-libraries/nugets/FrameworksInRuntimesNativeDirectory/Makefile
- tests/xharness/AppBundleLocator.cs
- tests/xharness/Harness.cs
- tools/devops/automation/scripts/bash/build-mlaunch-nuget.sh
- tools/devops/automation/templates/tests/run-tests.yml
- tools/dotnet-linker/Makefile
This is the follow-up to where the DOTNET variable was renamed SYSTEM_DOTNET.
> [dotnet] Rename the DOTNET6 make variable to DOTNET.
